/* Azerbaijani dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const az = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — spesifikasiya üzrə mühəndisliyi aparılan tam karbon tennis raketləri",
    defaultDescription:
      "Çərçivədən tutacağa qədər tam karbon tennis raketləri: GREAT 97 in², POWER 98 in² və SPIN 100 in², səkkiz zavod tutacaq ölçüsü L0–L7, çəki, balans, swingweight və sərtlik üçün dəqiqlik sinifləri, sorğu əsasında sifariş üzrə mühəndislik.",
  },
  common: {
    statuses: {
      current: "Aktual",
      agreement: "Razılaşma əsasında mövcuddur",
      development: "İşlənmə mərhələsində",
      concept: "Konsept",
      target: "İstehsal hədəfi",
      modelled: "Hesablanmış",
      confirmed: "Təsdiqlənmiş",
      requested: "Tələb olunan arxitektura",
      notprovided: "Verilməyib",
    },
    brief: { who: "Kimlər üçün", value: "Nə əldə edirsiniz", now: "Hazırda təsdiqlənmiş", next: "Növbəti addım" },
    labels: {
      next: "İrəli",
      back: "Geri",
      edit: "Cavabları redaktə edin",
      review: "Yoxlama",
      start: "Başla",
      restart: "Yenidən başla",
      copy: "Sorğu mətnini kopyalayın",
      copied: "Kopyalandı",
      openEmail: "Bu sorğunu göndərmək üçün e-poçtu açın",
      reference: "Sorğunun istinad nömrəsi",
      weight: "Çəki",
      balance: "Balans",
      swingweight: "Swingweight",
      stiffness: "Sərtlik",
      grip: "Tutacaq ölçüsü",
      headSize: "Baş ölçüsü",
      series: "Seriya",
      precisionClass: "Dəqiqlik sinfi",
      quantity: "Miqdar",
      notProvided: "Hələ dərc edilməyib",
      requestTarget: "Tələb olunan hədəf",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Ətraflı oxuyun",
      allSeries: "Bütün seriyalar",
      points: "siyahıdakı çəki",
      optional: "istəyə bağlı",
      required: "mütləq",
      select: "Seçin",
      yes: "Bəli",
      no: "Xeyr",
      unknown: "Əmin deyiləm",
      custom: "Fərdi hədəf",
      listed: "Siyahıdakı çəki",
      individual: "Tək raket",
      pair: "Uyğunlaşdırılmış cüt",
      triple: "Uyğunlaşdırılmış üçlük",
      team: "Komanda dəsti",
      summaryTitle: "Sorğunuzun xülasəsi",
      nextAction: "Növbəti hərəkət",
      status: "Vəziyyət",
      learn: "Ətraflı məlumat",
      schematic: "Sxem — ölçmə deyil",
      photo: "Fotoşəkil",
    },
    ecosystemStrip: "MAXIMUS ekosistemi",
    truth: {
      noPrices: "Qiymətlər, minimal miqdarlar, hazırlanma müddətləri, zəmanətlər və çatdırılma öhdəlikləri hər bazar və hər proqram üzrə yazılı şəkildə təsdiqlənir.",
      requestNotOrder: "Sorğu baxış üçün müraciətdir. O, qəbul edilmiş sifariş, istehsal öhdəliyi və ya təsdiqlənmiş görüş deyil.",
      noGuarantee: "Burada təsvir olunan heç bir avadanlıq, metod və ya proqram konkret oyunçu üçün nəticəyə zəmanət vermir.",
      governing: "Bu səhifə bir neçə dildə dərc olunur. Hüquqi qüvvəyə malik variant ingilis dilindəki variantdır; tərcümə rahatlıq üçün təqdim edilir.",
    },
  },
  nav: {
    language: "Dil",
    groups: { racquets: "Raketlər", training: "Məşq", ecosystem: "Ekosistem", partnerships: "Tərəfdaşlıq" },
    familyPlan: "Ailə Planı",
    racquets: "Raket seriyaları və müqayisə",
    great: "GREAT — 97 in² · Nəzarət",
    power: "POWER — 98 in² · Güc",
    spin: "SPIN — 100 in² · Fırlanma",
    precision: "Dəqiqlik və sərtlik",
    grip: "Zavod tutacaq arxitekturası L0–L7",
    custom: "Sifariş üzrə mühəndislik",
    training: "Məşq sistemləri",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologiya",
    gps: "MAXIMUS GPS",
    build: "Konfiqurator",
    choose: "Seçməyə kömək edin",
    ecosystem: "Ekosistem xəritəsi",
    engineering: "Mühəndislik və istehsal",
    experience: "Sınaq və fitting",
    brands: "Şəxsi brendlər və brend səfirləri",
    families: "Ailələr və valideynlər",
    owners: "Sahiblər və sahib seyfi",
    network: "Sports Network",
    partnerships: "Bütün tərəfdaşlıq yolları",
    coaches: "Məşqçilər",
    clubs: "Klublar və akademiyalar",
    distribution: "Distribusiya və ölkə inkişafı",
    strategic: "Strateji və investisiya",
    institutional: "İnstitusional proqramlar",
    contact: "Əlaqə",
    legal: "Hüquqi kimlik",
    privacy: "Məxfilik",
    terms: "Şərtlər",
    menu: "Menyu",
    close: "Bağla",
    home: "Ana səhifə",
    skip: "Məzmuna keçin",
  },
  footer: {
    line: "MAXIMUS raketi sizin MAXIMUS dünyasına açarınızdır.",
    product: "Məhsul",
    ecosystem: "Ekosistem",
    company: "Təşkilat",
    instagram: "Instagram",
    email: "E-poçt",
    analytics: "Analitika parametrləri",
    subscribe: {
      title: "MAXIMUS ilə qalın",
      line: "Yeni seriyalar, fitting tarixləri, məşq materialları və sahib proqramı. İldə bir neçə məktub — başqa heç nə.",
      label: "E-poçt ünvanı",
      placeholder: "your@email.com",
      button: "Abunə ol",
      sending: "Göndərilir",
      done: "Siz siyahıdasınız. Yalnız oxumağa dəyər bir şey olanda yazırıq.",
      invalid: "Zəhmət olmasa ünvanı yoxlayın.",
      failed: "Ünvan qeydə alınmadı. Zəhmət olmasa bir az sonra yenidən cəhd edin.",
      terms: "Abunə olmaqla MAXIMUS-un bu yenilikləri sizə göndərməsinə və ünvanınızı bu məqsədlə saxlamasına razılıq verirsiniz. Hər məktubda abunəlikdən çıxmaq üçün keçid var.",
    },
    rights: "MAXIMUS® və aslan emblemi MAXIMUS ekosisteminin nişanlarıdır. MIPA daxili əqli mülkiyyət, mənşə və sənəd nəzarəti.",
    boundary:
      "Kommersiya və müqavilə şərtləri ayrıca, yazılı şəkildə razılaşdırılır. Raketin alınması institusional üzvlük, investisiya hüququ, əqli mülkiyyət sahibliyi və ya royalti hüququ yaratmır.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Dəqiqlik təmas anında başlayır.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer və MAXIMUS metodologiyası fokuslanmış məşqi tam karbon performans raketləri ilə birləşdirir.",
    heroCta1: "Məşq sistemini kəşf edin",
    heroCta2: "GREAT-i kəşf edin",
    heroCaption: "MAXIMUS GREAT · 97 in² · Nəzarət",
    heroMeta: [
      ["Tam karbon", "çərçivədən tutacağa qədər"],
      ["4 parametr", "çəki · balans · swingweight · sərtlik"],
      ["8 tutacaq ölçüsü", "zavod həndəsəsi L0–L7"],
      ["3 seriya", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Ailə Planı · Bizimlə töhfə verin",
      title: "Ailə büdcəniz. Nəyi qarşılayır? Nəyi qurur?",
      p: "Üç ssenari yan-yana — indi, plan və arzu. Büdcənizin qarşıladığı məşqlər, saatlar və topla təmaslar, həmçinin bir məşqin, bir saatın və bir zərbənin dəyəri — hamısı öz rəqəmlərinizlə hesablanır.",
      points: [
        ["Öz rəqəmləriniz", "Hər məbləğ sizdən gəlir. Heç nə fərz edilmir, heç nə konvertasiya olunmur."],
        ["Üç ssenari", "İndi etdiyinizi planlaşdırdığınızla və etmək istədiyinizlə müqayisə edin."],
        ["On il irəli", "Təyin etdiyiniz yaşlarla məhdudlaşan, bir ildən on ilədək xərc planı."],
        ["Kortdan kənarda", "Aparıcı məktəblərə qəbulda dəstək və oyunçuda qalan rəqəmsal aktivlər."],
      ],
      cta: "Ailə planınızı hesablayın",
    },
    paths: {
      eyebrow: "Buradan başlayın",
      title: "Yolunuzu seçin",
      items: {
        player: { h: "Oyunçu", p: "Səviyyənizə və prioritetlərinizə uyğun raket tapın və ya birbaşa konfiqurasiya edin.", a: "Raketinizi tapın" },
        parent: { h: "Valideyn", p: "İnkişaf hədəfləri, məşqçinin iştirakı və uyğun avadanlıq üçün yazılı yol.", a: "Ailə yolu" },
        coach: { h: "Məşqçi, klub və ya akademiya", p: "Məşq sistemləri, fitting, komanda dəstləri və fərdiləşdirmə.", a: "Məşqçi və klub yolları" },
        partner: { h: "Distribyutor və ya tərəfdaş", p: "Distribusiya, ölkə inkişafı, strateji və institusional yollar.", a: "Tərəfdaşlıq yolları" },
      },
    },
    series: {
      eyebrow: "Performans seriyaları",
      title: "Üç performans arxitekturası. Bir mühəndislik platforması.",
      lead: "Seriyanı oyun istiqamətinə görə seçin, sonra konfiqurasiyanı tamamlayın: dəqiqlik sinfi, çəki, tutacaq, fərdiləşdirmə.",
      cta: "Seriyaları müqayisə edin",
      configure: "Konfiqurasiya edin",
      open: "Seriyanı açın",
      photoPending: "Fotoşəkil hələ dərc edilməyib",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS Dəqiqlik Sistemi",
      title: "Çəki. Balans. Swingweight. Sərtlik.",
      sub: "Vahid mühəndislik sistemi kimi nəzarətdə saxlanılır.",
      lead: "Üç dəqiqlik sinfi hazır hər raketin bəyan edilmiş spesifikasiyasına nə qədər sıx riayət etdiyini müəyyən edir. P0.5 müəyyən edilmiş ölçmə protokolu çərçivəsində sıx tolerantlıqdır — sıfır xəta deyil.",
      cta: "Dəqiqlik və sərtlik barədə ətraflı",
    },
    stiffness: {
      eyebrow: "Sərtlik",
      title: "Bəyan edilmiş hədəfə uyğun təkrarlanan çərçivə cavabı.",
      p: "Çərçivənin sərtliyi cavabı, hissi və raketlər arasındakı ardıcıllığı formalaşdırır. MAXIMUS bunu nəzarətdə saxlanılan dördüncü parametr kimi qəbul edir: hədəf, ölçmə nəticəsi, yol verilən tolerantlıq və ölçmə cihazının imkanı ayrı-ayrı qeydlər kimi saxlanılır. Fayda təkrarlanma qabiliyyətidir — hər oyunçu üçün zəmanətli nəticə deyil.",
      cols: [["Cavab", "Çərçivənin təmas anında enerjini necə qaytarması."], ["Hiss", "Oyunçunun təmas anında nə duyması."], ["Ardıcıllıq", "Eyni spesifikasiya üzrə hazırlanan raketlər öz sinfi daxilində eyni cür cavab verir."]],
      schematicCaption: "Sxem: hər sinif üçün bəyan edilmiş sərtlik hədəfi ətrafında yol verilən sapma. Bu ölçmə deyil; heç bir RA dəyəri nəzərdə tutulmur.",
      bands: { p25: "hədəf tolerantlığı ±1 RA", p15: "hədəf tolerantlığı ±0.5 RA", p05: "mövcud zavod ölçmə protokolu çərçivəsində bəyan edilmiş hədəf RA dəyərinə uyğundur — sıfır xəta deyil", target: "bəyan edilmiş hədəf (heç bir dəyər nəzərdə tutulmur)" },
    },
    carbon: {
      eyebrow: "Konstruksiya standartı",
      title: "Tam karbon. Çərçivədən tutacağa qədər.",
      p: "Bu platformadakı bütün aktual MAXIMUS raketləri, tutacaq da daxil olmaqla, konstruksiyası etibarı ilə tam karbondur. Tutacağın formalaşdırılmasında köpük istifadə olunmur.",
      gripTitle: "Səkkiz zavod tutacaq ölçüsü. L0–L7.",
      gripP: "Hər ölçü zavodda hazırlanan karbon tutacaq həndəsəsidir — overgrip ilə qalınlaşdırma deyil.",
      scaleCaption: "Sxem: nominal tutacaq işarələri L0–L7 (4″-dən 4⅞″-ə qədər). Bunlar ölçülmüş tutacaq ölçüləri deyil.",
      cta: "Zavod tutacaq arxitekturası",
    },
    custom: {
      eyebrow: "Sifariş üzrə mühəndislik",
      title: "Spesifikasiya üzrə mühəndislik.",
      sub: "Standart çeşid başlanğıc nöqtəsidir.",
      p: "MAXIMUS dərc edilmiş matrislərdən kənar texniki tələbləri qiymətləndirmə, mühəndislik, doğrulama və razılaşdırılmış spesifikasiya üzrə istehsal üçün qəbul edir. İcra oluna bilənlik yazılı şəkildə təsdiqlənir.",
      chain: ["Müəyyənləşdirmə", "Mühəndislik", "Doğrulama", "Spesifikasiya", "İstehsal", "Ölçmə / qeyd"],
      cta: "Texniki brif göndərin",
      cta2: "Sifariş üzrə mühəndisliyi müzakirə edin",
    },
    training: {
      eyebrow: "Məşq sistemləri",
      title: "Təmas nöqtəsi ətrafında qurulmuş məşq sistemi.",
      p: "Sweet Spot Trainer, MAXIMUS metodologiyası və Spot Trainer avadanlığı məşqçinin rəhbərliyi ilə aparılan işlə birləşdirir: mərkəzdən təmas, nəzarət, mərhələli yükləmə və performans raketinə qayıdış.",
      cta: "Məşq sistemləri",
      cta2: "Nümayiş tələb edin",
      photoPending: "Məşq raketinin fotoşəkli hələ dərc edilməyib",
      sstP: "Mərkəzdən təmas məşqi üçün 50 in² məşq başı; məşqçinin seçdiyi yükləmə üçün dörd çəki konfiqurasiyası.",
      sstCta: "Sweet Spot Trainer-i kəşf edin",
      sstCaption: "300 g konfiqurasiyası, dördündən biri",
      methodP: "Hədəfləri qoyun, avadanlığı seçin, məşqçinin iştirakı ilə çalışın, müşahidələri qeyd edin, yenidən qiymətləndirin, tənzimləyin və işi performans oyununa daşıyın.",
      methodCta: "Metodologiyanı kəşf edin",
      spotP: "Dəqiq və təkrarlanan təmas nöqtəsini məşq etmək üçün kiçik dairəvi hədəf.",
      spotCta: "Spot Trainer-i kəşf edin",
    },
    manufacturing: {
      eyebrow: "İstehsal və keyfiyyət nəzarəti",
      title: "Spesifikasiya üzrə hazırlanır. Ölçülür və qeydə alınır.",
      p: "İstehsal hər sifarişin yazılı spesifikasiyasına uyğun aparılır. Qeydlər dəqiqlik sinfindən asılıdır: P2.5 üçün saxlanılan istehsal qeydləri, P1.5 üçün fərdi qeydlər və izlənilə bilənlik, P0.5 üçün — sifarişin proqramı bunu nəzərdə tutduğu halda — fərdi nəzarət və sənədləşmə.",
      confirmedTitle: "Təsdiqlənmiş",
      confirmed: ["Çərçivədən tutacağa qədər tam karbon konstruksiya.", "Dörd nəzarət parametri ilə P2.5, P1.5 və P0.5 dəqiqlik sinifləri.", "Səkkiz zavod tutacaq ölçüsü L0–L7."],
      pendingTitle: "Hələ dərc edilməyib",
      pending: "Ölçmə avadanlığının fotoşəkilləri, nümunə keyfiyyət nəzarəti qeydləri və zavod görüntüləri hələ dərc edilməyib. Bu səhifədəki heç bir məlumat ölçülmüş sertifikat deyil.",
      captions: { lettering: "Mat çərçivə üzərində parlaq MAXIMUS yazısı", buttcap: "Aslan nişanlı tutacaq və alt qapaq", handle: "Gümüş fərdiləşdirmə qravürası", finish: "Baş və sim səthi" },
      cta: "Mühəndislik və istehsal",
    },
    world: {
      eyebrow: "MAXIMUS dünyası",
      title: "Bir açar. Bir ekosistem. Limitsiz imkanlar.",
      note: "«Limitsiz imkanlar» brend ifadəsidir, limitsiz texniki icra imkanı, gəlir və ya çıxış vədi deyil. Alış royalti, investisiya gəliri, sponsorluq və ya oyunçunun inkişafının maliyyələşdirilməsi yaratmır.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — və tennis dünyasında naviqasiyanız: yazılı cavablandırılan, istiqamətləndirilmiş avadanlıq profili." },
        personal: { h: "Fərdiləşdirmə", p: "Təsdiqlənmiş gümüş qravüra icrasında adlar, baş hərflər, nömrələr və komanda identifikasiyası." },
        development: { h: "İnkişaf", p: "Məşqçinin rəhbərliyi ilə məşq sistemləri, qeydlər və yenidən qiymətləndirmə." },
        ecosystem: { h: "Genişləndirilmiş ekosistem", p: "Şəxsi brendlər, sahib qeydləri, şəbəkə, lisenziyalaşdırma və institusional proqramlar — hər biri faktiki vəziyyəti ilə göstərilir." },
      },
      cta: "Ekosistemi kəşf edin",
    },
    partners: {
      eyebrow: "Tərəfdaşlıq yolları",
      title: "Məşqçilər, klublar, distribyutorlar və tərəfdaşlar.",
      p: "Əvvəlcə yazılı kvalifikasiya. Ölkə hüquqları, eksklüzivlik və kommersiya şərtləri yazılı şəkildə müzakirə olunur — heç vaxt forma vasitəsilə verilmir.",
      cta: "Bütün tərəfdaşlıq yolları",
      formTitle: "Qısa müraciət",
      formLead: "Məqsədi seçin və MAXIMUS-a yazın. Sorğu nömrəsini bu səhifədə alacaqsınız.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "TENNİS DÜNYASINDA NAVİQASİYANIZ" } },
    personal: { eyebrow: "Fərdiləşdirmə", title: "Adınız. Nömrəniz. MAXIMUS-unuz." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Üç seriya. Real parametrlər." },
    map: { cta: "Ekosistemi kəşf edin" },
  },
  racquets: {
    title: "Raketlər",
    lead: "Ümumi konstruksiya standartını, ümumi dəqiqlik sistemini və ümumi zavod tutacaq arxitekturasını bölüşən üç performans seriyası. Hər seriya daha geniş mühəndislik platforması daxilində formalaşmış performans arxitekturasıdır.",
    direction: { control: "Nəzarət", power: "Güc", spin: "Fırlanma" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Əsas oyun istiqaməti",
    compareTitle: "Seriyaların müqayisəsi",
    compareLead: "Yalnız təsdiqlənmiş arxitektura məlumatları. Bu seriyalar üçün sim sxemi, uzunluq, çərçivə profili, sim gərginliyi aralığı, swingweight və sərtliyin nominal dəyərləri dərc edilmir; onlar texniki baxış üçün tələb olunan hədəflər kimi toplanır.",
    columns: { series: "Seriya", head: "Baş ölçüsü", direction: "İstiqamət", weights: "Siyahıdakı çəkilər", range: "Çəki aralığı", balance: "Balans məlumatları" },
    balanceModelled: "Hesablanmış dəyərlər",
    balanceNotProvided: "Hələ dərc edilməyib",
    construction: "Konstruksiya: çərçivədən tutacağa tam karbon · Dəqiqlik: P2.5 / P1.5 / P0.5 · Tutacaqlar: L0–L7",
    otherTitle: "Digər raket idmanları",
    otherLead: "Təsdiqlənmiş inkişaf istiqamətləri. Bu kateqoriyalarda satışa hazır məhsul yoxdur və onlara heç bir tennis spesifikasiyası ötürülmür.",
    other: { padel: "Padel", pickleball: "Piklbol", squash: "Skvoş", badminton: "Badminton", racquetball: "Raketbol", beachTennis: "Çimərlik tennisi" },
    ctaConfigure: "Sorğunu konfiqurasiya edin",
    ctaSeries: "Seriyanı açın",
  },
  seriesPage: {
    eyebrow: "Performans seriyaları",
    intro: {
      great: "97 in² GREAT arxitekturası nəzarət üzərində qurulub: yığcam baş, dəqiq təmas və istiqamət inamı.",
      power: "98 in² POWER arxitekturası enerji ötürülməsi üzərində qurulub: stabil çərçivədən dərinlik və sürət.",
      spin: "100 in² SPIN arxitekturası topun davranışı üzərində qurulub: fırlanma, ehtiyat payı və trayektoriyanın formalaşdırılması.",
    },
    photoPending: "Seriyanın fotoşəkli hələ dərc edilməyib",
    detailPending: "Bu seriyanın konstruksiya və tutacaq detallarının fotoşəkilləri hələ dərc edilməyib.",
    specsTitle: "Spesifikasiya və vəziyyət",
    catalogue: {
      eyebrow: "{series} seriyasının kataloqu",
      title: "{n} çəki variantı",
      lead: "{series} seriyasının çəkiyə görə sıralanmış bütün variantları. Çəki qramla, balans tutacağın dibindən millimetrlə verilir. Hər vizualizasiya bütöv göstərilir: heç nə kəsilmir, maskalanmır və dartılmır.",
      selectLabel: "Çəki variantını seçin",
      select: "Bu variantı göstər",
      selected: "Yuxarıda göstərilir",
      balanceLabel: "Balans",
      headLabel: "Baş ölçüsü",
      constructionLabel: "Konstruksiya",
      gripsLabel: "Zavod tutacaq ölçüləri",
      precisionLabel: "Dəqiqlik sinifləri",
      balanceConfirmed: "Balans bu çəki üçün təsdiqlənmiş dəyərdir və vizualizasiyada yazılmış rəqəmlə üst-üstə düşür. Qiymətlər, anbar qalığı və çatdırılma müddətləri burada dərc edilmir.",
      balanceModelled: "Balans siyahıdakı bu çəki üçün hesablanmış dəyərdir, fərdi zavod ölçməsi deyil; vizualizasiyada yazılmış rəqəmlə üst-üstə düşür. Qiymətlər, anbar qalığı və çatdırılma müddətləri burada dərc edilmir.",
      zoom: "Şəkli açın",
      close: "Bağla",
      allTitle: "Bütün {n} variant",
    },
    specs: { head: "Baş ölçüsü", direction: "Əsas istiqamət", weights: "Siyahıdakı çəkilər", range: "Çəki aralığı", balance: "Balans", construction: "Konstruksiya", grips: "Zavod tutacaqları", precision: "Dəqiqlik sinifləri" },
    construction: "Çərçivədən tutacağa tam karbon",
    statusTitle: "Dəyərlərin vəziyyəti",
    matrixTitle: "Tam çəki matrisi",
    matrixLead: "Siyahıdakı çəkilər standart seçimdir. Digər çəkilər fərdi hədəf kimi tələb oluna bilər; çatışmayan aralıq dəyərlər əlavə edilmir.",
    balanceNote: {
      confirmed: "Balans dəyərləri siyahıdakı hər çəki üçün təsdiqlənib (tutacağın dibindən mm) və həmin çəkinin vizualizasiyasında yazılmış rəqəmlə üst-üstə düşür. Onlar burada hesablanmır və qonşu çəkilər arasında hamarlanmır; ölçmə əsası yazılı spesifikasiyada təsdiqlənir.",
      modelled: "Balans dəyərləri siyahıdakı hər çəki üçün hesablanır (tutacağın dibindən mm). Bunlar fərdi zavod ölçmələri deyil; ölçmə əsası yazılı spesifikasiyada təsdiqlənir.",
      notprovided: "Bu seriya üçün balans dəyərləri verilməyib. Onları başqa seriyadan çıxarmayın.",
    },
    optionsTitle: "Dəqiqlik, tutacaq və çəki",
    notPublished: "Bu seriya üçün dərc edilməyənlər: sim sxemi, uzunluq, çərçivə profili, sim gərginliyi aralığı, swingweight və sərtlik dəyərləri. Onları texniki baxış üçün tələb olunan hədəflər kimi göstərə bilərsiniz.",
    offerTitle: "Sorğunuzdan sonra nə olur",
    offerSteps: [
      ["Sorğu", "Konfiqurasiya və ya sual göndərin. Sorğu nömrəsi dərhal göstərilir."],
      ["Baxış", "MAXIMUS seriyanı, sinfi, çəkini, tutacağı və tələb olunan hədəfləri nəzərdən keçirir."],
      ["Yazılı cavab", "Spesifikasiya, mövcudluq və kommersiya şərtləri yazılı şəkildə təsdiqlənir."],
    ],
    faqTitle: "Suallar",
    faq: [
      ["Balans dəyərləri ölçülüb?", "Onlar siyahıdakı çəkilər üçün hesablanıb, fərdi ölçmə deyil. Ölçmə əsası yazılı spesifikasiyada təsdiqlənir."],
      ["Siyahıda olmayan çəkini tələb edə bilərəm?", "Bəli, tam qramla fərdi hədəf kimi. O, texniki cəhətdən nəzərdən keçirilir və icra oluna bilənlik yazılı şəkildə təsdiqlənir."],
      ["Dəqiqlik sinfi nəyi dəyişir?", "Çəkinin, balansın, swingweight-in və sərtliyin bəyan edilmiş spesifikasiyaya nə qədər sıx riayət etdiyini və hansı qeydlərin saxlanıldığını."],
      ["Tutacaq overgrip ilə qalınlaşdırılır?", "Xeyr. L0–L7 zavodda hazırlanan karbon tutacaq həndəsələridir."],
      ["Qiymətlər və çatdırılma müddətləri haradadır?", "Onlar hər sorğu üçün yazılı şəkildə təsdiqlənir və burada dərc edilmir."],
    ],
    faqSpinBalance: ["SPIN balans dəyərləri haradan gəlir?", "Təsdiqlənmiş Spin seriyası cədvəlindən: tutacağın dibindən millimetrlə balansı göstərilmiş 33 çəki variantı. Hər cütlük həmin çəkinin təsdiqlənmiş vizualizasiyasında yazılmış rəqəmlə üst-üstə düşür. Dəyərlər hesablanmır və qonşu çəkilər arasında hamarlanmır."],
    ctaBuild: "Bu seriyanı konfiqurasiya edin",
    ctaAsk: "Bu seriya barədə sual verin",
    ctaCompare: "Bütün seriyaları müqayisə edin",
    weightsLabel: "siyahıdakı çəki",
    headLabel: "baş",
  },
  precision: {
    title: "Dəqiqlik və sərtlik",
    switch: { label: "Dəqiqlik sinfini seçin", panelLabel: "Dörd nəzarət parametri —", qcLabel: "Keyfiyyət nəzarəti arxitekturası", protocolNote: "müəyyən edilmiş zavod keyfiyyət nəzarəti ölçmə protokolu çərçivəsində", fullTable: "Tam müqayisə cədvəli" },
    lead: "Vahid mühəndislik sistemi kimi nəzarətdə saxlanılan dörd parametr. Hər sinif hazır raketin bəyan edilmiş spesifikasiyasına nə qədər sıx riayət etdiyini və hansı keyfiyyət qeydlərinin yaradıldığını müəyyən edir.",
    statement: "Çəki. Balans. Swingweight. Sərtlik. Vahid mühəndislik sistemi kimi nəzarətdə saxlanılır.",
    classes: {
      "P2.5": { name: "Miqyaslana bilən performans nüvəsi", qc: "Fərdi ölçmə və saxlanılan istehsal qeydləri." },
      "P1.5": { name: "Təkmilləşdirilmiş dəqiqlik", qc: "Fərdi ölçmə, fərdi qeydlər və izlənilə bilənlik." },
      "P0.5": { name: "Peşəkar · fərdi nəzarətlə", qc: "Nominal və faktiki dəyərlərlə fərdi nəzarət və fərdi ölçmə qeydləri; sifarişin proqramı bunu nəzərdə tutduğu halda seriya kimliyi, partiya izlənilə bilənliyi, dəqiqlik sertifikatı və uyğunlaşdırılmış dəstlər." },
    },
    columns: { cls: "Sinif", weight: "Çəki", balance: "Balans", sw: "Swingweight", stiff: "Sərtlik", qc: "Keyfiyyət nəzarəti arxitekturası" },
    stiffTarget: "hədəf tolerantlığı",
    stiffExact: "mövcud zavod ölçmə protokolu çərçivəsində bəyan edilmiş hədəf RA dəyərinə uyğundur",
    programmeNote: "Seriya kimliyi, sertifikatlar və uyğunlaşdırılmış dəst sənədləşməsi yalnız konkret sifarişin proqramı bunu nəzərdə tutduğu hallarda verilir.",
    targetsNote: "Sərtlik spesifikasiyaları müvafiq protokol və istehsal sübutları daha güclü iddianı dəstəkləyənə qədər istehsal hədəfləri olaraq qalır. Arxitektura təklifi siyahıdakı hər konfiqurasiyanın dörd parametr üzrə tam buraxılış prosesindən keçdiyini bildirmir.",
    stiffnessTitle: "Sərtlik nəyə görə vacibdir",
    stiffnessP1: "Çərçivənin sərtliyi onun təmas anında necə cavab verdiyinə, necə hiss olunduğuna və iki raketin bir-biri ilə nə qədər ardıcıl olduğuna təsir edir. Buna nəzarət etməyin əsas faydası bəyan edilmiş spesifikasiyaya uyğun təkrarlanan cavabdır.",
    stiffnessP2: "Doğrulanmış uyğunluq dərc edilənə qədər daxili keyfiyyət nəzarəti qeydi cihazı, onun kalibrləmə vəziyyətini, metodu, raketin halını, ayırdetmə qabiliyyətini, ölçmə qeyri-müəyyənliyini, təkrar ölçmələri, yuvarlaqlaşdırma qaydasını və qəbul qaydasını müəyyən edir. Ekranda eyni tam ədədin görünməsi sıfır fiziki dəyişkənliyin və ya sıfır ölçmə xətasının sübutu deyil.",
    fields: ["Hədəf", "Ölçmə nəticəsi", "Yol verilən tolerantlıq", "Cihazın imkanı"],
    fieldsNote: "Hər qeyddə ayrı sahələr kimi saxlanılır.",
    matchedTitle: "Uyğunlaşdırılmış dəstlər",
    matchedP: "Uyğunlaşdırılmış dəstin kriteriyaları fərdi tolerantlıqdan ayrı müəyyən edilir. Hər raketin öz nominal tolerantlığına uyğun olması təkbaşına iki raket arasındakı konkret maksimum fərqi sübut etmir. Uyğunlaşdırılmış cütlər, üçlüklər və komanda dəstləri konfiqurator vasitəsilə tələb olunur və yazılı şəkildə təsdiqlənir.",
    extendedTitle: "Genişləndirilmiş texniki model",
    extendedP: "Məlumat modeli əlavə parametrləri dəstəkləyir. Onlar üçün hələ dəyər və ya tolerantlıq sinfi yoxdur; texniki brifdə tələb olunan hədəflər kimi göstərilə bilərlər.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Burulma davranışı", length: "Uzunluq", beamProfile: "Çərçivə profili", headGeometry: "Baş həndəsəsi", stringPattern: "Sim sxemi", durability: "Davamlılıq", vibration: "Vibrasiya xüsusiyyətləri" },
    noZero: "MAXIMUS siyahıdakı çeşidini sıfır tolerantlıqlı kimi təqdim etmir. Çeşiddəki dəqiqlik bəyan edilmiş tolerantlığı və müəyyən edilmiş keyfiyyət nəzarəti arxitekturası olan sinif kimi göstərilir. ZERO çeşidin bir hissəsi deyil.",
    zero: {
      eyebrow: "Eksklüziv seçim",
      title: "ZERO",
      sub: "Sıfır qram tolerantlıq.",
      p: "Üç sinif hazır raketi bəyan edilmiş tolerantlıq zolağının içində saxlayır. ZERO bu zolağı aradan götürür. Raket, ölçmə dəyəri zavod cihazının ayırdetmə qabiliyyəti səviyyəsində bəyan edilmiş dəyərə bərabər olana qədər hazırlanır və ölçülür; həmin ölçmə dəyəri raketlə birlikdə verilir. O, siyahıdakı çeşidin bir hissəsi deyil və dördüncü sinif deyil: bir raket və ya bir uyğunlaşdırılmış dəst üçün sifariş üzrə hazırlanan eksklüziv kimi fərdi razılaşdırılır. Razılaşma əsasında eyni yanaşma balansa və swingweight-ə də tətbiq edilir.",
      points: [
        ["Zolaq yoxdur", "Bəyan edilmiş dəyər nəticənin özüdür, tolerantlığın mərkəzi deyil."],
        ["Hər dəfə bir raket", "Vahid məhsul kimi hazırlanır, ölçülür və qeydə alınır."],
        ["Raketlə birlikdə verilir", "Ölçülmüş dəyər təhvil verilir və istehsal qeydində saxlanılır."],
        ["Yazılı şəkildə təsdiqlənir", "Parametrlər, əhatə dairəsi və hazırlanma müddəti istehsaldan əvvəl razılaşdırılır."],
      ],
      note: "Bərabərlik zavod ölçmə cihazının ayırdetmə qabiliyyəti səviyyəsində etibarlıdır. Göstərilən dəyərin eyni olması sıfır fiziki dəyişkənlik iddiası deyil. Mövcudluq və şərtlər hər sifariş üçün fərdi razılaşdırılır.",
      cta: "ZERO tələb edin",
    },
    cta: "Dəqiqlik sinfi ilə konfiqurasiya edin",
  },
  grip: {
    title: "Zavod tutacaq arxitekturası",
    statement: "Səkkiz zavod tutacaq ölçüsü. L0–L7.",
    lead: "Tutacağın həndəsəsi karbon tutacaq arxitekturasının bir hissəsidir. Hər ölçü tutacaq həndəsəsi kimi istehsal olunur, overgrip ilə qalınlaşdırılmır.",
    emph: "Genişləndirilmiş ölçülər",
    p1: "Səkkiz ölçüdən ibarət zavod çeşidi məşqçilərə və oyunçulara avadanlığın oyunçunun ətrafında müəyyənləşdirilə biləcəyi daha geniş konfiqurasiya aralığı verir; buraya daha böyük L6 və L7 həndəsələri də daxildir.",
    p2: "Nominal tutacaq işarəsi xam struktur tutacaq ölçülərindən və son ölçmə protokolundan fərqlənir. Ölçülər bu platformadakı performans seriyalarına və məşq ailələrinə aiddir.",
    p3: "Bu çeşid üçün dünya üzrə eksklüzivlik iddiası irəli sürülmür.",
    columns: { size: "Ölçü", nominal: "Nominal", family: "Aid olduğu məhsullar" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Tutacaq ölçünüzlə konfiqurasiya edin",
  },
  custom: {
    title: "Sifariş üzrə mühəndislik",
    statement: "Spesifikasiya üzrə mühəndislik.",
    sub: "Standart çeşid başlanğıc nöqtəsidir.",
    lead: "MAXIMUS dərc edilmiş konfiqurasiya matrislərindən kənar texniki tələbləri qiymətləndirmə, mühəndislik, doğrulama və razılaşdırılmış spesifikasiya üzrə istehsal üçün qəbul edir. İcra oluna bilənlik baxış yolu ilə təsdiqlənir — ağla gələn hər sorğu fiziki və ya kommersiya baxımından icra oluna bilən deyil.",
    scopeTitle: "Texniki brif nələri əhatə edə bilər",
    scope: ["Baş və çərçivə həndəsəsi", "Uzunluq", "Çəki", "Balans", "Swingweight", "Sərtlik", "Twistweight", "Tutacaq həndəsəsi", "Konstruksiya", "Uyğunlaşdırılmış dəstlər", "Məşq çərçivələri", "Kosmetika və qravüra", "Kimlik və komanda proqramları", "Qəlibdən asılı işləmələr"],
    processTitle: "Proses",
    process: [
      ["Müəyyənləşdirmə", "Arzu olunan hədəflər, məcburi hədlər, istifadə məqsədi və qəbul edilə bilən güzəştlər."],
      ["Mühəndislik", "Platforma və qəliblər baxımından mühəndislik qiymətləndirməsi."],
      ["Doğrulama", "Razılaşdırılmış spesifikasiyaya uyğunluğun doğrulanması."],
      ["Spesifikasiya", "Ölçmə əsası və tolerantlıqları göstərilən yazılı spesifikasiya."],
      ["İstehsal", "Spesifikasiya üzrə istehsal."],
      ["Ölçmə / qeyd", "Müvafiq dəqiqlik sinfinə uyğun ölçmə və saxlanılan qeydlər."],
    ],
    formTitle: "Texniki brif göndərin",
    formLead: "Arzu olunan hədəfləri məcburi hədlərdən ayırın. Nəticə avtomatik qəbul edilmiş istehsal sifarişi deyil, texniki baxış sorğusudur.",
    protected: "Karbon laylarının düzülüş reseptləri, qəliblər, təchizatçıların kimliyi, daxili maya dəyəri hesablamaları və qorunan bilik bazası bu yolla açıqlanmır.",
    cta: "Texniki brif göndərin",
  },
  training: {
    title: "Məşq sistemləri",
    lead: "Öz istehsal standartları olan iki məşq ailəsi vahid metodologiya ilə birləşir: məşqçinin rəhbərliyi ilə iş, qeydlər, yenidən qiymətləndirmə və performans oyununa qayıdış.",
    sst: { h: "Sweet Spot Trainer", p: "Mərkəzdən təmas məşqi, sweet spot hissiyyatı, raket nəzarəti və mərhələli yükləmə üçün dörd çəkili sistemdə 50 in² kiçildilmiş başlı məşq raketi." },
    spot: { h: "Spot Trainer", p: "Təsdiqlənmiş dörd çəki təməli üzərində, kiçik dairəvi təmas hədəfi ilə təmas nöqtəsi məşqi." },
    method: { h: "Metodologiya", p: "Hədəfləri qoyun, avadanlığı məşqçinin iştirakı ilə seçin, müvafiq sistemdən istifadə edin, qeyd aparın, yenidən qiymətləndirin, tənzimləyin və əldə olunanı oyuna daşıyın." },
    experience: "Əlinizə alın. Yelləyin. Hiss edin.",
    experienceP: "Sınaq, fitting və ya məşqçi dəstəkli nümayiş tələb edin. Göndərilmiş sorğu təsdiqlənmiş görüş deyil.",
    cta: "Fitting və ya nümayiş tələb edin",
    distinct: "Sweet Spot Trainer, Spot Trainer və hər hansı ayrı nümayiş qurğusu fərqli məhsullardır və heç vaxt birləşdirilmir.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Öz istehsal standartı olan ayrı məşq kateqoriyası. 50 in² baş diqqəti təmas yerinə yönəldir; dörd çəki yükləmə mərhələliliyini təmin edir.",
    baseline: "Təsdiqlənmiş təməl",
    columns: { head: "Baş", length: "Uzunluq", pattern: "Sim sxemi", grips: "Zavod tutacaqları" },
    systemTitle: "Dörd raketdən ibarət sistem",
    detailsTitle: "Konstruksiya detalları",
    systemLead: "Təchiz olunduğu haldakı çəki və balans. Ölçmə əsası ayrıca qeyd olunur və hələ dərc edilməyib.",
    purposeTitle: "Məqsəd",
    purpose: ["Mərkəzdən təmas məşqi", "Sweet spot hissiyyatı", "Raket nəzarəti", "Mərhələli yükləmə", "Məşqçinin rəhbərliyi ilə inkişaf", "Oyunçunun performans raketinə qayıdış"],
    heavy: "400 g model nəzarətdə saxlanılan məşq konfiqurasiyasıdır. O, uşaqlara, yeni başlayanlara və ya hər oyunçuya avtomatik tövsiyə edilmir; yükü, müddəti və mərhələliliyi məşqçi müəyyən edir.",
    precisionNote: "P2.5, P1.5 və P0.5 performans dəqiqlik sinifləri bu məşq ailəsinə avtomatik tətbiq olunmur. Məşq istehsalının tolerantlıqları ailənin öz təsdiqlənmiş spesifikasiyasına uyğundur.",
    health: "Tennis dirsəyinin qarşısının alınması və ya müalicəsi, zədələrin aradan qaldırılması və ya zəmanətli irəliləyiş vəd olunmur.",
    cta: "Sweet Spot Trainer nümayişi tələb edin",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Kiçik dairəvi təmas hədəfi ilə təmas nöqtəsi məşqi. Təsdiqlənmiş dörd çəki təməli üzərində qurulmuş, öz vizual kimliyi olan ayrı məhsul.",
    purposeTitle: "Təsdiqlənmiş məqsəd",
    purposeP: "Oyunçuya dəqiq təmas nöqtəsini tapmağı və təkrarlamağı məşq etdirmək.",
    weightsTitle: "Çəki mərhələliliyi",
    weightsP: "Çəki mərhələliliyi təsdiqlənmiş Sweet Spot Trainer çəki təməlinə uyğundur. Balans dəyərləri və digər Sweet Spot Trainer spesifikasiyaları Spot Trainer-ə köçürülmür.",
    dims: "Hədəfin dəqiq ölçüləri hələ dərc edilməyib.",
    grips: "Zavod tutacaq arxitekturası L0–L7.",
    notes: ["Performans dəqiqlik sinifləri avtomatik tətbiq olunmur.", "Bu, ənənəvi raketin kiçildilmiş variantı deyil və heç bir sim sxemi dərc olunmur.", "Spot Trainer, Sweet Spot Trainer və hər hansı ayrı nümayiş qurğusu bir-birindən ayırd edilə bilən olaraq qalır."],
    cta: "Spot Trainer barədə sual verin",
  },
  methodology: {
    title: "Metodologiya və məhsul təcrübəsi",
    lead: "Avadanlıq strukturlaşdırılmış inkişaf yolunun yalnız bir hissəsidir. Metod məhsulun adından deyil, oyunçunun hədəflərindən başlayır.",
    stepsTitle: "İnkişaf yolu",
    steps: [
      ["Hədəfləri qoymaq", "Oyunçunun hədəfləri və başlanğıc nöqtəsi."],
      ["Avadanlığı seçmək", "Məşqçinin iştirakı ilə uyğun avadanlığın seçilməsi."],
      ["Sistemdən istifadə etmək", "Məşqçinin rəhbərliyi ilə müvafiq məşq sistemi."],
      ["Qeyd aparmaq", "Faktiki iştirakın müşahidələri, uydurma nəticələr olmadan."],
      ["Yenidən qiymətləndirmək", "Müqayisə oluna bilən yoxlama nöqtələri."],
      ["Tənzimləmək", "Konfiqurasiya və ya proqram tənzimləmələri."],
      ["Daşımaq", "Əldə olunanın performans oyununa daşınması."],
    ],
    educationTitle: "Təlim yolları",
    education: { player: "Oyunçular — konfiqurasiyanın, yüklənmənin və mərhələliliyin dərk edilməsi.", parent: "Valideynlər — inkişafın davamlılığı, uyğun avadanlıq, qeydlər və hüquqlar.", coach: "Məşqçilər — məşq sistemləri, fitting, qiymətləndirmə və icazəli proqramlardan istifadə." },
    evidenceTitle: "Sübut intizamı",
    evidenceP: "Faktiki iştirakın qeydləri və müşahidələr öz təsnifatı ilə saxlanılır — iştirakçının bəyan etdiyi, qəyyumun təsdiqlədiyi, məşqçinin doğruladığı və ya sistemin ölçdüyü. İrəliləyiş, nəticələr və doğrulama heç vaxt uydurulmur.",
    experienceTitle: "Əlinizə alın. Yelləyin. Hiss edin.",
    experienceP: "Sınaq, fitting və ya məşqçi dəstəkli nümayiş tələb oluna bilər. Göndərilmiş sorğu təsdiqlənmiş görüş deyil.",
    cta: "Fitting və ya nümayiş tələb edin",
    cta2: "Məşqçi tərəfdaşlığı müraciəti",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — istiqamətləndirilmiş avadanlıq profili",
    title: "MAXIMUS GPS",
    lead: "İstiqamətləndirilmiş avadanlıq profili. Yalnız sizə aid olanı cavablandırın; cavablarınızı yoxlayıb düzəldin; xülasə, tətbiq olunan konfiqurasiya istiqamətləri və real növbəti addım alın.",
    honesty: "Bu buraxılışda avtomatik fitting qaydaları təsdiqlənməyib. Buna görə GPS aydın tələblər xülasəsi hazırlayır və konfiqurasiya istiqamətlərini göstərir; avadanlığa dair konkret məsələlər ekspert baxışına yönləndirilir.",
    rulesVersion: "Qaydaların versiyası",
    dataVersion: "Məhsul məlumatlarının versiyası",
    steps: { role: "Rol", sport: "İdman növü", experience: "Təcrübə", objectives: "Hədəflər", style: "Oyun tərzi", equipment: "Mövcud avadanlıq", preference: "Üstünlüklər", coach: "Məşqçinin iştirakı", ageBand: "Yaş qrupu", review: "Yoxlama" },
    notStored: "Bu brauzerdə saxlanılmır.",
    ageNote: "Yalnız sorğunun yönləndirilməsi üçün istifadə olunur. Ad, doğum tarixi və ya tibbi məlumat soruşulmur.",
    q: {
      role: "Özünüzü necə təsvir edərdiniz?",
      sport: "Hansı idman növü?",
      experience: "Təcrübə səviyyəsi",
      objectives: "Sizin üçün ən vacibi nədir? (üçə qədər seçin)",
      style: "Bilirsinizsə, oyun tərziniz",
      equipment: "Varsa, mövcud avadanlığınız",
      equipmentHint: "Bilirsinizsə, brend və model, çəki və ya tutacaq ölçüsü. İstəyə bağlıdır.",
      preference: "Üstün tutduğunuz konfiqurasiya və ya bildiyiniz tutacaq ölçüsü",
      grip: "Bildiyiniz tutacaq ölçüsü",
      coach: "Avadanlıq qərarlarınızda məşqçi iştirak edir?",
      ageBand: "Oyunçunun yaş qrupu (yalnız sorğunun düzgün yönləndirilməsi üçün istifadə olunur)",
    },
    roles: { player: "Oyunçu", parent: "Valideyn və ya qəyyum", coach: "Məşqçi", club: "Klub və ya akademiya", other: "Digər" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Piklbol", squash: "Skvoş", badminton: "Badminton", other: "Digər raket idmanı" },
    sportNote: "Məhsullar tennis üçün mövcuddur. Digər idman növləri inkişaf istiqamətləridir; marağınız müvafiq proqram üçün qeydə alınır.",
    experience: { beginner: "Yeni başlayan", developing: "İnkişaf edən", intermediate: "Orta səviyyə", advanced: "Yüksək səviyyə", competitive: "Yarış səviyyəsi", professional: "Peşəkar" },
    objectives: { control: "Nəzarət", power: "Güc", spin: "Fırlanma", comfort: "Rahatlıq", manoeuvrability: "Manevr qabiliyyəti", development: "Uzunmüddətli inkişaf", competition: "Yarışlar", training: "Məşq sistemi", team: "Komanda və ya uyğunlaşdırılmış dəst", personal: "Fərdiləşdirmə" },
    styles: { baseline: "Arxa xəttdən oyun", allcourt: "Universal oyun", attacking: "Hücum", defensive: "Müdafiə", coach: "Məşqçinin seçimi", unknown: "Əmin deyiləm" },
    ageBands: { u10: "10 yaşdan kiçik", u14: "10–13", u18: "14–17", adult: "18 və yuxarı" },
    output: {
      title: "Avadanlıq profiliniz",
      status: "Ekspert baxışı tələb olunur",
      statusP: "Bu buraxılışda avtomatik uyğunlaşdırma aparılmır. Profiliniz ekspert baxışı üçün xülasə edilib.",
      directionsTitle: "Tətbiq olunan konfiqurasiya istiqamətləri",
      directionsP: "Bildirdiyiniz hədəflərə və hər seriyanın bəyan edilmiş oyun istiqamətinə əsaslanır. Bu istiqamətdir, fitting tövsiyəsi deyil.",
      trainingHint: "Hədəflərinizə məşq sistemi daxildir: Sweet Spot Trainer və Spot Trainer bölmələrinə baxın.",
      teamHint: "Uyğunlaşdırılmış dəstlər konfiqurator vasitəsilə tələb olunur və yazılı şəkildə təsdiqlənir.",
      next1: "Profili ekspert baxışına göndərin",
      show: "Profilimi göstər",
      configure: "Konfiqurasiya edin",
      sendP: "Profilinizi ekspert baxışı üçün MAXIMUS-a göndərin. Sorğu nömrəsi dərhal göstərilir; cavab yazılı şəkildə verilir.",
      otherSport: "MAXIMUS raketləri tennis üçün mövcuddur. Digər raket idmanları üçün heç bir tennis seriyası təklif edilmir; marağınız inkişaf istiqaməti kimi qeydə alınır.",
      noDirection: "Hədəfləriniz bir oyun istiqamətinə işarə etmir. Konfiqurasiyanı ekspert baxışı təklif edir.",
      incomplete: "Bəzi zəruri cavablar çatışmır — onları tamamlamaq üçün «Cavabları redaktə edin» bölməsindən istifadə edin.",
    },
    privacy: "GPS heç bir tibbi məlumat və uşaq identifikatoru soruşmur. Bu brauzer sessiyasında yalnız seçim variantları saxlanılır; sərbəst mətn saxlanılmır.",
  },
  build: {
    title: "Özünüz qurun",
    lead: "Sorğunu konfiqurasiya edin: seriya, dəqiqlik sinfi, siyahıdakı çəki və ya fərdi hədəf, tutacaq ölçüsü, tələb olunan hədəflər, fərdiləşdirmə, uyğunlaşdırılmış dəstlər və miqdar. Nəticə sorğu nömrəsi olan konfiqurasiya sorğusudur — SKU, qiymət, çatdırılma tarixi və ya sertifikat deyil.",
    steps: { series: "Seriya", cls: "Dəqiqlik sinfi", weight: "Çəki", grip: "Tutacaq", targets: "Hədəflər", personal: "Fərdiləşdirmə", set: "Dəst və miqdar", use: "İstifadə", review: "Yoxlama" },
    q: {
      series: "Seriyanı seçin",
      cls: "Dəqiqlik sinfini seçin",
      weightMode: "Çəki",
      listed: "Siyahıdakı çəki",
      customWeight: "Tələb olunan çəki (g)",
      balanceShown: "Bu çəki üçün hesablanmış balans",
      balanceRequest: "Tələb olunan balans (mm)",
      grip: "Zavod tutacaq ölçüsü",
      targetsTitle: "Tələb olunan hədəflər",
      swingweight: "Tələb olunan swingweight (kg·cm²)",
      stiffness: "Tələb olunan sərtlik (RA)",
      basis: "Tələb olunan dəyərlər üçün ölçmə əsası",
      engraving: "Qravüra mətni",
      engravingHint: "Ad, baş hərflər və ya nömrə. Latın hərfləri, rəqəmlər, boşluq, defis, apostrof və nöqtə; 24 simvola qədər. Digər əlifbalar eskizin təsdiqi şərti ilə qəbul olunur.",
      engravingType: "Fərdiləşdirmə",
      types: { none: "Yoxdur", name: "Oyunçunun adı", initials: "Baş hərflər", number: "Dəst nömrəsi", academy: "Məşqçi və ya akademiya identifikasiyası", team: "Komanda proqramı" },
      set: "Tək raket və ya uyğunlaşdırılmış dəst",
      use: "İstifadə məqsədi",
      uses: { play: "Şəxsi oyun", competition: "Yarışlar", coaching: "Məşqçilik", team: "Komanda və ya akademiya", retail: "Pərakəndə satış və ya distribusiya qiymətləndirməsi", other: "Digər" },
      notes: "Əlavə texniki tələblər",
    },
    classes: { "P2.5": "P2.5 — miqyaslana bilən performans nüvəsi", "P1.5": "P1.5 — təkmilləşdirilmiş dəqiqlik", "P0.5": "P0.5 — peşəkar, fərdi nəzarətlə" },
    stiffExactShort: "sərtlik mövcud zavod protokolu çərçivəsində bəyan edilmiş hədəf RA dəyərinə uyğundur",
    clsNote: "Hər sinif dörd parametri nəzarətdə saxlayır. P0.5 müəyyən edilmiş ölçmə protokolu çərçivəsində sıx tolerantlıqdır — sıfır xəta deyil. Seriya kimliyi, sertifikatlar və uyğunlaşdırılmış dəst sənədləşməsi yalnız sifarişinizin proqramı bunu nəzərdə tutduğu halda tətbiq olunur.",
    listedNote: "Seriyanın təsdiqlənmiş matrisindən.",
    customNote: "Matrisdən kənar çəki, texniki cəhətdən nəzərdən keçirilir.",
    balanceCaption: "Siyahıdakı hər çəki üçün tutacağın dibindən mm ilə hesablanmış balans göstərilir. Hesablanmış dəyərlər fərdi ölçmələr deyil.",
    spinNote: "SPIN çəkiləri tələb olunan çəki arxitekturasını təşkil edir. SPIN üçün balans, swingweight və sərtlik verilməyib; onlar texniki baxışda müəyyən edilir.",
    customHint: "Tam qram, yalnız rəqəmlərlə. Fərdi çəki texniki baxış üçün sorğudur; icra oluna bilənlik yazılı şəkildə təsdiqlənir və heç bir dəyər yuvarlaqlaşdırılmır.",
    gripNote: "zavodda hazırlanan karbon tutacaq həndəsəsi, overgrip ilə qalınlaşdırma deyil",
    targetsLead: "İstəyə bağlıdır. Yalnız sizə lazım olan dəyərləri daxil edin. Hər biri dərc edilmiş spesifikasiya kimi deyil, texniki baxış üçün tələb olunan hədəf kimi qeydə alınır.",
    basisHint: "Fərdi çəki və ya hər hansı hədəf tələb etdikdə mütləqdir: dəyərlər simsiz, yoxsa simli raketə aiddir?",
    inputRange: "Qəbul edilən aralıq: {min}–{max}.",
    inputRangeNote: "Daxiletmə aralıqları yalnız mümkün olmayan dəyərləri süzgəcdən keçirir. Onlar istehsal imkanını təsvir etmir.",
    listedBasis: "siyahıdakı dəyərlər — ölçmə əsası yazılı spesifikasiyada təsdiqlənir",
    notStored: "Bu brauzerdə saxlanılmır; səhifəni yenidən yükləsəniz, təkrar daxil edin.",
    artworkReview: "eskizin təsdiqi tələb olunur",
    previewNote: "Vizual önbaxış göstərilmir: bu model üçün təsdiqlənmiş qravüra şablonu hələ dərc edilməyib. Mətniniz eskizin təsdiqi üçün toplanır.",
    teamSub: "dəst üzrə 4–99 raket",
    setsLabel: { individual: "Raketlərin sayı", pair: "Uyğunlaşdırılmış cütlərin sayı", triple: "Uyğunlaşdırılmış üçlüklərin sayı", team: "Komanda dəstlərinin sayı" },
    teamSizeLabel: "Komanda dəstindəki raketlərin sayı",
    totalLabel: "Ümumi raket sayı",
    racquetsUnit: "raket",
    setRule: "Miqdar dəstləri sayır: uyğunlaşdırılmış cüt dəst üzrə 2 raket, uyğunlaşdırılmış üçlük 3 raketdir.",
    restart: "Yeni konfiqurasiyaya başla",
    notices: { weightCleared: "{w} g {series} matrisində yoxdur, buna görə çəki təmizləndi. Siyahıdakı çəkini seçin və ya fərdi hədəf tələb edin." },
    reviewTitle: "Konfiqurasiya sorğusu",
    reviewP: "Konfiqurasiyanı yoxlayın, sonra əlaqə məlumatlarınızı əlavə edin. Sorğu nömrə ilə saxlanılır və yazılı cavablandırılır; mövcudluq və kommersiya şərtləri yazılı şəkildə təsdiqlənir.",
    reviewErrors: "Bəzi konfiqurasiya cavabları diqqət tələb edir:",
    edit: "Redaktə",
    fieldNames: { series: "Seriya", cls: "Dəqiqlik sinfi", mode: "Çəkinin seçilməsi", weight: "Siyahıdakı çəki", customWeight: "Tələb olunan çəki", basis: "Ölçmə əsası", balanceReq: "Tələb olunan balans", sw: "Tələb olunan swingweight", ra: "Tələb olunan sərtlik", grip: "Tutacaq ölçüsü", ptype: "Fərdiləşdirmə", engraving: "Qravüra mətni", setType: "Dəstin tipi", sets: "Miqdar", teamSize: "Komanda dəstindəki raketlərin sayı", use: "İstifadə məqsədi", notes: "Əlavə tələblər" },
    status: { listed: "siyahıdakı çəki", requestedArchitecture: "tələb olunan çəki arxitekturası", technicalReview: "texniki baxış sorğusu", notPublished: "verilməyib", requestedCondition: "tələb olunan hal" },
    chooseLink: "Hansı seriyanın uyğun olduğunu bilmirsiniz? Seçimdə kömək alın",
    cta: "Konfiqurasiya sorğusunu göndərin",
  },
  experience: {
    title: "Sınaq və fitting",
    statement: "Əlinizə alın. Yelləyin. Hiss edin.",
    lead: "Sınaq, fitting və ya məşqçi dəstəkli nümayiş tələb edin. Sorğular nəzərdən keçirilir və yazılı cavablandırılır; göndərilmiş sorğu təsdiqlənmiş görüş deyil.",
    optionsTitle: "Nə tələb oluna bilər",
    options: ["Raketin sınaqdan keçirilməsi", "Fitting sessiyası", "Məşqçi dəstəkli nümayiş", "Sweet Spot Trainer və ya Spot Trainer nümayişi", "Komanda və ya akademiya üçün nümayiş günü"],
    formTitle: "Fitting və ya nümayiş sorğusu",
  },
  engineering: {
    title: "Mühəndislik və istehsal",
    statement: "Təyyarələr. Yaxtalar. Raketlər.",
    lead: "Üç mühitdə vahid mühəndislik fəlsəfəsi: təyyarəni formalaşdıran prinsiplər, yaxtanı açıq suda idarə edən dəqiqlik, hər MAXIMUS raketini müəyyən edən performans. Bu, mühəndislik fəlsəfəsinin təsviridir — təyyarə sertifikatı, yaxta sahibliyi, zavod sahibliyi və ya birbaşa material ötürülməsi iddiası deyil.",
    manifesto: ["İnanırıq ki, böyük mühəndisliyin sərhədi yoxdur.", "Vahid fəlsəfə. Güzəştsiz mühəndislik."],
    capabilityTitle: "İstehsal imkanı",
    capabilityLead: "İmkan şüar deyil, ardıcıllıq kimi göstərilir.",
    sequence: [
      ["Spesifikasiya", "Seriya, dəqiqlik sinfi, çəki, balans, swingweight, sərtlik hədəfi, tutacaq həndəsəsi, fərdiləşdirmə."],
      ["İstehsal", "Çərçivədən tutacağa qədər tam karbon konstruksiya, spesifikasiya üzrə hazırlanır."],
      ["Keyfiyyət nəzarəti", "Dəqiqlik sinfinə uyğun ölçmə və qeydlər: istehsal qeydləri, fərdi qeydlər və izlənilə bilənlik, fərdi sertifikatlaşdırma."],
      ["Təkrar istehsal", "Partiyalar arasında bəyan edilmiş spesifikasiyaya uyğun təkrarlanan cavab."],
      ["İzlənilə bilənlik", "Sinif bunu nəzərdə tutduğu halda seriya kimliyi, partiya izlənilə bilənliyi və Dəqiqlik Sertifikatı."],
    ],
    capacityNote: "İstehsal gücü, hazırlanma müddətləri, minimal miqdarlar və çatdırılma qrafikləri təsdiqlənmiş sifarişlər və razılaşdırılmış buraxılış qrafiki əsasında hər proqram üzrə yazılı şəkildə təsdiqlənir.",
    truth: "İstehsal gücü məhsul buraxılışı, anbar qalığı, zəmanətli çatdırılma tarixi və ya istehsal müəssisəsinin sahibliyi demək deyil.",
    cta: "Distribusiya və ölkə inkişafı",
    cta2: "Texniki brif göndərin",
  },
  ecosystem: {
    title: "MAXIMUS ekosistemi",
    lead: "Bir açar. Onun açdıqları budur. Hər qovşağın izahı, dəqiq vəziyyəti və müvafiq növbəti addımı var.",
    words: ["Mühəndislik", "Performans", "İnnovasiya", "Birlik", "İmkan", "Məqsəd"],
    nodes: {
      engineering: { h: "Raket mühəndisliyi və istehsalı", p: "Spesifikasiya üzrə mühəndisliyi aparılan tam karbon raketlər, keyfiyyət qeydləri və izlənilə bilənliklə istehsal olunur.", a: "Mühəndislik və istehsal" },
      precision: { h: "Dəqiqlik və fərdi konfiqurasiya", p: "Dörd parametr, üç dəqiqlik sinfi, səkkiz tutacaq ölçüsü və sifariş üzrə mühəndislik.", a: "Dəqiqlik və sərtlik" },
      training: { h: "Məşq və metodologiya", p: "Sweet Spot Trainer, Spot Trainer və strukturlaşdırılmış inkişaf yolu.", a: "Məşq sistemləri" },
      development: { h: "Oyunçu və məşqçi inkişafı", p: "Məşqçinin rəhbərliyi ilə seçim, qeydlər, yenidən qiymətləndirmə və təlim yolları.", a: "Metodologiya" },
      identity: { h: "Şəxsi kimlik və şəxsi brendlər", p: "Qravüradan hüquqi cəhətdən tənzimlənən şəxsi və ya peşəkar brendə qədər.", a: "Şəxsi brendlər" },
      owners: { h: "Sahib qeydləri, bilik və hüquqlar", p: "Avadanlıq, inkişaf və hüquq qeydləri üçün təklif olunan icazə əsaslı sahib seyfi.", a: "Sahiblər və seyf" },
      mipa: { h: "MIPA mənşə və daxili nəzarət", p: "Daxili əqli mülkiyyət, mənşə və sənəd nəzarəti qatı.", a: "Hüquqi kimlik və nəzarət" },
      digital: { h: "Rəqəmsal infrastruktur və Blockchain 5.0 istiqaməti", p: "Bəyan edilmiş texnoloji istiqamət kimi mənşə, izlənilən qeydlər, icazə əsaslı sübutlar və məhsul kimliyi.", a: "Texnoloji istiqamət" },
      licensing: { h: "Müqavilə əsaslı lisenziyalaşdırma və royalti proqramları", p: "Şərtləri hər müqavilə üzrə müəyyən edilən lisenziyalı brendlər, məhsullar və hüquq paketləri.", a: "Lisenziyalaşdırma yolları" },
      families: { h: "Ailənin iştirakı və proqram faydaları", p: "Əsaslandırılmış qərarlar, davamlılıq, saxlanılan qeydlər və proqramla müəyyən edilən faydalar.", a: "Ailələr və valideynlər" },
      network: { h: "MAXIMUS Sports Network", p: "Oyunçular, məşqçilər, klublar, akademiyalar, xidmət təminatçıları, operatorlar və regional tərəfdaşlar.", a: "Sports Network" },
      market: { h: "Klublar, akademiyalar, distribusiya və ölkə inkişafı", p: "Yazılı kvalifikasiya yolu ilə komanda proqramları, pərakəndə satış, distribusiya və ərazi inkişafı.", a: "Tərəfdaşlıq yolları" },
      institutional: { h: "İnstitusional proqramlar, təhsil, innovasiya və sosial təsir", p: "Proqram bu rolu müəyyən etdiyi hallarda MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tərəfindən təmin edilən institusional qat.", a: "İnstitusional proqramlar" },
      extensions: { h: "Gələcək raket idmanları və MAXIMUS geyim genişlənmələri", p: "İnkişaf istiqamətləri kimi padel, piklbol, skvoş, badminton, raketbol, çimərlik tennisi və geyim.", a: "Raket idmanları" },
    },
    boundaryTitle: "Hədlər",
    boundary: [
      "Raketin alınması institusional üzvlük, idarəetmə hüquqları, royalti və ya investisiya hüququ yaratmır.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) yalnız proqram bu rolu müəyyən etdiyi hallarda institusional operatordur; avadanlıq satışlarında faktiki müqavilə tərəfi göstərilir.",
      "Qrantlar, xeyriyyə statusu, vergi rejimi və tənzimləyici icazələr ölkələr arasında avtomatik tətbiq olunmur.",
    ],
    techTitle: "Texnoloji istiqamət",
    techP: "Blockchain 5.0 MAXIMUS-un bəyan etdiyi texnoloji istiqamətdir. Onun funksional məqsədləri mənşə, izlənilən qeydlər, icazə əsaslı sübutlar, məhsul kimliyi və uyğun kommersiya hadisələrinin üzləşdirilməsidir. Heç bir konsensus mexanizmi, tranzaksiya tutumu, qovşaq şəbəkəsi, smart-kontrakt ünvanı, token və ya müstəqil sertifikatlaşdırma təqdim edilmir və heç bir işə salınmış tətbiq iddia olunmur. Şəxsi məlumatlar, uşaqlara dair qeydlər və konfidensial müqavilələr heç vaxt standart olaraq açıq, dəyişdirilə bilməyən sistemə yerləşdirilmir.",
  },
  brands: {
    title: "Şəxsi brendlər və brend səfirləri",
    statement: "Oyunçudan brendə. Məşqçidən brendə.",
    lead: "Şəxsi brend üçün ayrı yol. MAXIMUS-un iştirakı brendin inkişafını və razılaşdırılmış təşviqi əhatə edir — yalnız raket üzərindəki adı deyil.",
    progressionTitle: "Nəzərdə tutulan mərhələlilik",
    progression: [
      ["Doğrulanmış kimlik", "Doğrulanmış kimlik və inkişaf tarixçəsi."],
      ["Fərqlənən brend", "Fərqlənən şəxsi və ya peşəkar brend."],
      ["Hüquqları təmizlənmiş məzmun", "Hüquqları təmizlənmiş məzmun və təsdiqlənmiş məhsul kimliyi."],
      ["Mühəndislik və kolleksiyalar", "Razılaşdırıldığı hallarda mühəndislik və kolleksiyanın işlənməsi."],
      ["Təşviq", "Razılaşdırılmış MAXIMUS kanalları və tərəfdaşlıqları vasitəsilə təşviq."],
      ["İştirak", "Uyğun satışlarda və ya lisenziyalaşdırmada müqavilə əsaslı iştirak."],
      ["Hesabatlılıq", "Müqaviləyə uyğun şəffaf hesabatlılıq."],
    ],
    royaltiesTitle: "Royalti və lisenziyalaşdırma",
    royalties: [
      "Royalti müəyyən edilmiş lisenziyalı brendə, məhsula, tranzaksiyaya və ya hüquq paketinə bağlanır.",
      "«Dünya üzrə satışlar» müqavilənin əhatəsi daxilindəki uyğun satışları bildirir — heç vaxt əlaqəsi olmayan hər MAXIMUS raketini deyil.",
      "Dərəcələr, hesablama bazası, ərazilər, müddət, geri qaytarmalar, tutulmalar, hesabatlılıq, hesablaşma və yoxlama müvafiq müqavilə ilə müəyyən edilir. Heç bir standart royalti faizi dərc olunmur.",
      "Razılaşdırılmış əhatə olmadan heç bir qlobal kampaniya, media büdcəsi, sponsorluq nəticəsi və ya kommersiya müvəffəqiyyəti vəd edilmir.",
    ],
    cta: "Brend əməkdaşlığı müraciəti göndərin",
    cta2: "Məşqçi tərəfdaşlığı müraciəti",
  },
  families: {
    title: "Ailələr və valideynlər",
    lead: "Avadanlıq barədə əsaslandırılmış qərarlar, inkişafın davamlılığı, saxlanılan bilik və hüquqlar, iştirakın görünən olması və gələcək fəaliyyəti dəstəkləyə bilən, proqramla müəyyən edilmiş faydalar.",
    nowTitle: "Hazırda mövcuddur",
    now: ["Ailə və inkişaf müraciətlərinin yazılı qəbulu.", "Məşqçinin iştirakı ilə avadanlıq seçimi, fitting və nümayiş sorğuları.", "Məxfi qeydlər: uşaqların profilləri heç vaxt dərc olunmur və standart olaraq kommersiyalaşdırılmır.", "Valideynlər üçün təlim yolu: konfiqurasiya, yüklənmə, mərhələlilik, qeydlər və hüquqlar."],
    plannedTitle: "Planlaşdırılır",
    planned: ["Nağd faiz yerinə ekosistem daxilində mal və xidmətlər üçün istifadə oluna bilən, proqramla müəyyən edilmiş iştirak faydaları.", "Təklif olunan sahib seyfində qəyyum icazələri və 18 yaşda nəzarətin ötürülməsi ilə sahib və ailə qeydləri."],
    categoriesTitle: "Ayrı saxlanılır",
    categories: ["Lisenziyalı hüquqlardan və ya uyğun satışlardan yaranan müqavilə royaltisi", "Proqramla müəyyən edilmiş iştirak faydaları", "Alış və ya xidmət kreditləri", "Avans ödənişləri", "İnstitusional üzvlük"],
    categoriesP: "Bu kateqoriyalar heç vaxt bir-birinin yerinə keçən kimi qəbul edilmir.",
    statusTitle: "Ailə proqramının faktiki vəziyyəti",
    journeyTitle: "Ailə yolu",
    journey: [
      ["Hədəf", "Oyunçunun növbəti mərhələdə nəyə nail olmaq istədiyi."],
      ["Mövcud səviyyə", "Oyunçunun bugünkü vəziyyəti."],
      ["Məşqçi", "Məşqçinin avadanlıq qərarlarında iştirak edib-etmədiyi."],
      ["Avadanlıq", "Lazım gəldikdə məşq sistemləri də daxil olmaqla, mərhələyə uyğun avadanlıq."],
      ["Razılaşdırılmış məşq", "Əvvəlcədən razılaşdırılmış, məşqçinin rəhbərliyi ilə istifadə."],
      ["Təkrar baxış", "Müqayisə oluna bilən yoxlama nöqtələrində yenidən qiymətləndirmə."],
    ],
    brief: {
      who: "Hər mərhələdə olan oyunçuların valideynləri və qəyyumları.",
      value: "Uyğun avadanlıq, məşqçinin iştirakı və növbəti inkişaf addımı barədə yazılı cavab.",
      now: "Ailə müraciətlərinin yazılı qəbulu; məşqçinin iştirakı ilə seçim; məxfi qeydlər — uşaqların profilləri heç vaxt dərc olunmur.",
      next: "Aşağıdakı ailə müraciətini göndərin. Sorğu nömrəsini dərhal alırsınız.",
    },
    formTitle: "Ailə müraciəti",
    formNote: "Valideyn və ya qəyyum tərəfindən doldurulmalıdır. Uşağın adını, doğum tarixini, məktəbini və ya tibbi məlumatlarını yazmayın.",
    noPromise: "Alış royalti, investisiya gəliri, sponsorluq və ya uşağın inkişafının maliyyələşdirilməsini vəd etmir.",
    statusP: "Bu buraxılış modeli izah edir və proqram müraciətlərini qəbul edir. Uyğun hadisələr, faydalananlar, maliyyə mənbəyi, hesablama əsası, icazəli istifadə halları, uçot rejimi, geri qaytarmalar, ləğvlər, müddətin bitməsi, ötürülə bilənlik, proqramın bağlanması və mübahisələrin həlli yazılı şəkildə müəyyən edilənə qədər yığım, ödənişlər və istifadə mümkün deyil. Heç bir balansın azalmayacağı vəd olunmur, heç bir iştirak bütün məşqlərin xərcini ödəmir və heç bir kapital müdafiəsi nəzərdə tutulmur.",
    cta: "Ailə və ya inkişaf müraciəti göndərin",
  },
  owners: {
    title: "Sahiblər və sahib seyfi",
    lead: "Sahib seyfi avadanlığın, inkişafın, biliyin, məzmunun və sənədləşdirilmiş hüquqların icazə əsaslı qeydi üçün təklif olunur. O, planlaşdırılan sahib arxitekturasının bir hissəsi kimi təqdim edilir: heç bir aktiv hesab, balans, sertifikat və ya nailiyyət göstərilmir.",
    nowTitle: "Mövcud sahiblər üçün hazırda",
    now: ["Sahib müraciətləri: məhsul və ya seriya nömrəsi, quraşdırma, servis və qeyd sorğularının yazılı qəbulu.", "Dəqiqlik sinfi bunu nəzərdə tutduğu halda məhsulla birlikdə verilən Dəqiqlik Sertifikatı və uyğunlaşdırılmış dəst sənədləşməsi."],
    archTitle: "Planlaşdırılan seyf arxitekturası",
    arch: ["Məhsul kimliyi və seriya nömrələri", "Konfiqurasiya və müvafiq keyfiyyət nəzarəti sertifikatları", "Servis və quraşdırma tarixçəsi", "Oyunçu və ya məşqçi inkişaf qeydləri", "İxtisaslar və doğrulanmış nailiyyətlər", "Hüquqları təmizlənmiş media və müəllif materialları", "Lisenziyalar, icazələr və müqavilə istinadları", "Şəxsi brend proqramının qeydləri", "Müvafiq royalti hesabatları və ya iştirak faydaları"],
    separationTitle: "Sahiblik nə deməkdir",
    separation: [
      "Fiziki raketin sahibliyi müəllif hüququnun, lisenziyanın, müqavilə hüququnun və ya bunları təsvir edən qeydin sahibliyindən ayrıdır.",
      "Saxlanılan sənəd və ya blokçeyn yazısı hüququn mövcudluğunun yaxud ötürülməsinin avtomatik sübutu deyil.",
      "Sübutlar öz təsnifatını saxlayır: iştirakçının bəyan etdiyi, qəyyumun təsdiqlədiyi, məşqçinin doğruladığı, sistemin ölçdüyü.",
      "Yetkinlik yaşına çatmayanlar üçün: məxfi qeydlər, qəyyum icazələri, uşaq profillərinin dərc olunmaması və standart olaraq kimliyin kommersiyalaşdırılmaması.",
      "İxrac, düzəliş, giriş nəzarəti və nəzarətin müvafiq şəkildə ötürülməsi dizaynın bir hissəsidir.",
    ],
    techTitle: "Blockchain 5.0 və MxSN",
    techP: "Blockchain 5.0 bəyan edilmiş texnoloji istiqamətdir; MxSN razılıq, çatdırılma, sübut, hüquqlar və hesabatlılıq üçün icazə əsaslı şəbəkənin konsepsiyalarını müəyyən edir. Əməliyyat səviyyəsində tətbiq təqdim edilmir. Tətbiqin məlumat modeli bağlantının bugün mövcud olduğunu göstərmədən, sənədləşdirilmiş interfeys vasitəsilə sonradan inteqrasiya oluna bilən şəkildə qurulub.",
    cta: "Sahib müraciəti",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Oyunçular, məşqçilər, klublar, akademiyalar, xidmət təminatçıları, proqram operatorları və regional tərəfdaşlar arasındakı əlaqə.",
    functionsTitle: "Potensial funksiyalar",
    functions: ["Axtarış", "Tanışlıqlar", "İnkişaf proqramları", "Avadanlıq dəstəyi", "Tədbirlər", "Xidmətə çıxış", "Tərəfdaş imkanları"],
    statusTitle: "Faktiki vəziyyət",
    statusP: "Hələ heç bir açıq kataloq dərc olunmur: yalnız kimliyi, münasibəti və göstərilməyə icazəsi müəyyən edilmiş iştirakçılar siyahıya daxil ediləcək. Kluba göndərilən təklif tərəfdaşlıq deyil, potensial distribyutor isə təyin edilmiş distribyutor deyil. Kataloqun dərci, rezervasiya, mesajlaşma və kommersiya əməliyyatları ayrıca nəzarətdədir və aktiv deyil.",
    cta: "Şəbəkəyə müraciət edin",
  },
  partnerships: {
    title: "Tərəfdaşlıq yolları",
    lead: "Əvvəlcə yazılı kvalifikasiya. Hər yol rola uyğun müraciətə aparır; kommersiya şərtləri sonra yazılı şəkildə verilir.",
    commercialTitle: "Platformanın potensial kommersiya fəaliyyətləri",
    commercial: ["Avadanlıq", "Sifariş üzrə mühəndislik", "Fərdiləşdirmə", "Komanda və akademiya proqramları", "Məşq sistemləri", "Müqavilə əsaslı lisenziyalaşdırma", "Distribusiya", "Təsdiqlənmiş xidmətlər", "Gələcək məhsul kateqoriyaları"],
    boundary: "Ölkə hüquqları, eksklüzivlik, ərazi ödənişləri və distribyutor marjası müzakirə olunan şərtlərdir. Heç bir gəlir, proqnoz, qiymətləndirmə, bazar payı, gəlirlilik, maliyyə öhdəliyi və ya adı açıqlanmayan tərəfdaşlıq dərc olunmur.",
    routes: {
      coaches: {
        title: "Məşqçilər",
        lead: "Məşq sistemləri, fitting, peşəkar kimlik, icazəli proqramlar, şəxsi brend imkanları və avadanlıq təchizatı.",
        points: ["Məşqçinin rəhbərliyi ilə işdə Sweet Spot Trainer və Spot Trainer.", "Konfiqurasiya matrisləri və səkkiz zavod tutacaq ölçüsü ilə fitting.", "Coach-to-Brand: doğrulanmış peşəkar profil və hüquqi cəhətdən tənzimlənən alt brend.", "İcazəli proqramlardan istifadə yazılı müqaviləyə əsaslanır."],
        cta: "Məşqçi tərəfdaşlığı müraciəti göndərin",
        brief: {
          who: "Müstəqil məşqçilər və məşqçi komandaları.",
          value: "Məşqçinin rəhbərliyi ilə iş üçün məşq sistemləri, seriya matrisləri və səkkiz zavod tutacağı ilə fitting, həmçinin peşəkar kimliyə aparan yol.",
          now: "Məşqçi müraciətlərinin yazılı qəbulu. Heç bir komissiya, qazanc və ya istiqamətləndirmə dərəcəsi dərc olunmur və nəzərdə tutulmur.",
          next: "Aşağıdakı məşqçi müraciətini göndərin. Şərtlər sonra yazılı şəkildə verilir.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klublar və akademiyalar",
        lead: "Komanda avadanlığı, məşq sistemləri, fərdiləşdirmə, inkişaf proqramları, servis və şəbəkədə iştirak.",
        points: ["Konfiqurator vasitəsilə tələb olunan komanda və uyğunlaşdırılmış dəstlər.", "Strukturlaşdırılmış inkişaf üçün məşq sistemləri və metodologiya.", "Təsdiqlənmiş zonalarda komanda proqramları üçün fərdiləşdirmə.", "Nümayiş günləri, fitting sessiyaları və şəbəkədə iştirak."],
        cta: "Klub və ya akademiya brifi göndərin",
        brief: {
          who: "Klublar, akademiyalar və komanda proqramları.",
          value: "Komanda və uyğunlaşdırılmış dəstlər, məşq sistemləri, komanda proqramları üçün fərdiləşdirmə və nümayiş günləri.",
          now: "Klub və akademiya briflərinin yazılı qəbulu; komanda dəstləri konfiqurator vasitəsilə tələb olunur.",
          next: "Aşağıdakı klub və ya akademiya brifini göndərin.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribusiya və ölkə inkişafı",
        lead: "Çeşid, istehsalın koordinasiyası, texniki imkan, ərazi inkişafı və konfidensial kommersiya kvalifikasiyası.",
        points: ["Qarşı tərəfin, ərazinin və kanalın yazılı kvalifikasiyası.", "Konfiqurasiya matrisləri və dəqiqlik siniflərinə əsaslanan çeşid.", "Ərazi, eksklüzivlik, həcmlər, qiymətqoyma və kommersiya müdafiəsi yazılı şəkildə razılaşdırılan müzakirə mövzularıdır.", "Müqavilə tərəfi, ödəniş şərtləri və çatdırılma əsası hər əməliyyat üzrə müəyyən edilir."],
        cta: "Distribusiya və ya ölkə inkişafı müraciəti göndərin",
        brief: {
          who: "Pərakəndə satıcılar, distribyutorlar və ölkə tərəfdaşları.",
          value: "Təsdiqlənmiş matrislər, dəqiqlik sinifləri və tutacaq çeşidi əsasında formalaşan çeşid, ərazinin və kanalın yazılı kvalifikasiyası ilə.",
          now: "Distribusiya müraciətlərinin yazılı qəbulu. Ərazi, eksklüzivlik, həcmlər və qiymətqoyma müzakirə olunur — heç biri forma vasitəsilə verilmir.",
          next: "Aşağıdakı distribusiya müraciətini göndərin.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strateji və investisiya",
        lead: "Mühəndislik imkanı, konfiqurasiyanın dərinliyi, istehsal modeli, bazara çıxış yolları, əqli mülkiyyət, xidmətlər və genişlənmə imkanları.",
        points: ["Kvalifikasiyadan keçmiş strateji müzakirə və ya nəzarətli məlumat girişi yazılı kvalifikasiyadan sonra mümkündür.", "Açıq məlumat təsdiqlənmiş məhsul spesifikasiyaları, konfiqurasiya arxitekturası, doğrulanmış imkanlar və proqram izahları ilə məhdudlaşır.", "Alıcıya xas iqtisadi göstəricilər, maya dəyəri, qorunan metodologiya və dərc olunmamış müqavilələr yalnız məxfilik sazişi və ya müqavilə əsasında açıqlanır."],
        cta: "Kvalifikasiyadan keçmiş strateji müzakirə tələb edin",
        brief: {
          who: "İnvestorlar və strateji tərəfdaşlar.",
          value: "Mühəndislik imkanı, konfiqurasiyanın dərinliyi, istehsal modeli, bazara çıxış yolları və əqli mülkiyyətin kvalifikasiyalı müzakirəsi.",
          now: "Heç bir maliyyə göstəricisi, proqnoz, qiymətləndirmə və ya gəlirlilik dərc olunmur. Nəzarətli məlumat yazılı kvalifikasiya və məxfilik sazişindən sonra verilir.",
          next: "Aşağıda kvalifikasiyadan keçmiş strateji müzakirə tələb edin.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "İnstitusional proqramlar",
        lead: "Təhsil, çıxış imkanı, innovasiya, inkişaf sübutları, sosial təsir və uyğun şəkildə qurulmuş proqramlar.",
        points: ["Proqram bu rolu müəyyən etdiyi hallarda institusional proqramlar MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) vasitəsilə qurulur.", "Məhdudlaşdırılmış proqram vəsaitləri ilə kommersiya əməliyyatları ayrı qalır.", "Müraciət qəbul edilmiş üzvlük ərizəsi deyil, avadanlıq alıcısı isə institusional üzv deyil.", "Qrantlar, xeyriyyə statusu, vergi rejimi və tənzimləyici icazələr ölkəyə xasdır və heç vaxt ehtimal edilmir."],
        cta: "İnstitusional proqram müraciəti göndərin",
        brief: {
          who: "Qurumlar, təhsil və inkişaf proqramları.",
          value: "Uyğun operatorla qurulan təhsil, çıxış imkanı, innovasiya və inkişaf sübutları proqramları.",
          now: "İnstitusional müraciətlərin yazılı qəbulu. Müraciət üzvlük ərizəsi deyil; avadanlığın alınması institusional üzvlük deyil.",
          next: "Aşağıdakı institusional müraciəti göndərin.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Açıq və nəzarətli məlumat",
    disclosure: {
      public: { h: "Açıq", p: "Təsdiqlənmiş məhsul spesifikasiyaları, konstruksiya, konfiqurasiya arxitekturası, məşq məqsədləri, doğrulanmış imkanlar, proqram izahları və tərəfdaşlıq yolları." },
      qualified: { h: "Kvalifikasiyalı müraciət", p: "Texniki tələblər, miqdarlar, əraziyə maraq, inkişafın əhatəsi və müvafiq kommersiya müzakirələri." },
      controlled: { h: "Məxfilik sazişi və ya müqavilə ilə nəzarətdə", p: "Daxili formullar, keyfiyyət nəzarətinin detallı protokolları, karbon laylarının düzülüşü, qəliblər, istehsal metodları, təchizatçıların kimliyi, maya dəyəri, alıcıya xas iqtisadi göstəricilər, qorunan metodologiya, dərc olunmamış müqavilələr və həssas hüquq qeydləri." },
    },
  },
  contact: {
    title: "Əlaqə və sorğular",
    lead: "Sorğunuzun məqsədini seçin. Hər forma yalnız yönləndirmə və qiymətləndirmə üçün lazım olanı toplayır. Sorğular yazılı cavablandırılır.",
    email: "E-poçt",
    instagram: "Instagram",
    legalLink: "Hüquqi kimlik",
  },
  form: {
    purposeLabel: "Sorğunun məqsədi",
    purposes: {
      selection: "Raket seçiminə kömək",
      product: "Məhsul müraciəti",
      fitting: "Fitting və ya nümayiş",
      technical: "Texniki brif",
      config: "Konfiqurasiya sorğusu",
      gps: "GPS avadanlıq profili",
      coach: "Məşqçi tərəfdaşlığı",
      club: "Klub və ya akademiya brifi",
      distribution: "Distribusiya və ya ölkə inkişafı",
      brand: "Brend əməkdaşlığı və ya brend səfirliyi",
      family: "Ailə və ya inkişaf müraciəti",
      institutional: "İnstitusional proqram",
      strategic: "Strateji və ya investisiya müzakirəsi",
      owner: "Sahib müraciəti",
      network: "Sports Network üçün müraciət",
      general: "Ümumi müraciət",
    },
    fields: {
      name: "Ad",
      email: "E-poçt",
      role: "Rolunuz",
      country: "Ölkə və ya region",
      organisation: "Təşkilat",
      message: "Mesajınız",
      level: "Mövcud səviyyə",
      objectives: "Ən vacib olanlar (üçə qədər)",
      currentRacquet: "Mövcud raket",
      grip: "Bilirsinizsə, tutacaq ölçüsü",
      seriesInterest: "Maraq göstərdiyiniz seriya",
      quantity: "Miqdar",
      city: "Sessiya üçün şəhər və ya yer",
      coachInvolved: "Məşqçi iştirak edir?",
      timing: "Üstün tutulan vaxt",
      targets: "Arzu olunan hədəflər",
      limits: "Məcburi hədlər",
      use: "İstifadə məqsədi",
      tradeoffs: "Qəbul edilə bilən güzəştlər",
      basis: "Ölçmə əsası",
      players: "Oyunçuların sayı",
      interests: "Maraq sahələri",
      territory: "Maraq göstərdiyiniz ərazi",
      channels: "Mövcud kanallar və təcrübə",
      audience: "Auditoriya və ya ixtisas",
      proposal: "Təklif olunan əməkdaşlıq",
      goal: "İnkişaf hədəfi",
      ageBand: "Oyunçunun yaş qrupu",
      scope: "Proqramın əhatəsi",
      interestArea: "Maraq sahəsi",
      productRef: "Məhsul və ya seriya nömrəsi",
      requestType: "Sorğunun növü",
      seeking: "Nə axtarırsınız",
      consent: "MAXIMUS-un bu sorğuya cavab vermək üçün göstərdiyim məlumatları saxlamasına və istifadə etməsinə razıyam. Bu, marketinq abunəliyi deyil.",
    },
    roles: { player: "Oyunçu", parent: "Valideyn və ya qəyyum", coach: "Məşqçi", club: "Klub və ya akademiya", retailer: "Pərakəndə satıcı", distributor: "Distribyutor", brand: "Brend və ya brend səfiri", investor: "İnvestor və ya strateji tərəfdaş", institution: "Qurum", other: "Digər" },
    interestOptions: { training: "Məşq sistemləri", fitting: "Fitting", identity: "Peşəkar kimlik", programmes: "İcazəli proqramlar", brand: "Şəxsi brend", supply: "Avadanlıq təchizatı", team: "Komanda avadanlığı", personalisation: "Fərdiləşdirmə", development: "İnkişaf proqramları", service: "Servis", network: "Şəbəkədə iştirak" },
    ownerTypes: { setup: "Quraşdırma və konfiqurasiya", service: "Servis", records: "Qeydlər və sertifikatlar", other: "Digər" },
    strategicAreas: { engineering: "Mühəndislik imkanı", configuration: "Konfiqurasiyanın dərinliyi", manufacturing: "İstehsal modeli", routes: "Bazara çıxış yolları", ip: "Əqli mülkiyyət və xidmətlər", expansion: "Genişlənmə imkanları" },
    errors: {
      required: "Bu sahə mütləqdir.",
      too_long: "Bu qeyd çox uzundur.",
      too_short: "Bu qeyd çox qısadır.",
      invalid_email: "Düzgün e-poçt ünvanı daxil edin, məsələn ad@example.com.",
      invalid_choice: "Variantlardan birini seçin.",
      not_number: "Yalnız rəqəmlərlə tam ədəd daxil edin.",
      out_of_range: "Bu dəyər qəbul edilən aralıqdan kənardır.",
      not_in_matrix: "Bu çəki seçilmiş seriyanın siyahı matrisində yoxdur.",
      decimal_not_supported: "Onluq kəsrsiz tam ədəd daxil edin.",
      too_many: "Üçdən çox variant seçməyin.",
      consent_required: "MAXIMUS-un bu sorğuya cavab verə bilməsi üçün razılıq mütləqdir.",
      invalid: "Bu qeyd düzgün deyil.",
    },
  },
  legal: {
    title: "Hüquqi kimlik və nəzarət",
    lead: "Açıq brend MAXIMUS / MAXIMUS GPS-dir. Hüquqi fəaliyyət kimlikləri bir-birindən ayırd edilir və burada göstərilir.",
    entities: {
      institutional: { role: "İnstitusional proqram qatı", p: "Proqram bu rolu müəyyən etdiyi hallarda institusional proqram qatını təmin edir. Raketlərin kommersiya satıcısı deyil. Dubay Beynəlxalq Maliyyə Mərkəzində qeydiyyata alınmış qeyri-kommersiya təşkilatı." },
      equipment: { role: "Avadanlıq üzrə kommersiya qurumu", p: "Mövcud fəaliyyət sənədləri bu rolu müəyyən etdiyi hallarda təchizat, distribusiya və müqavilə əsaslı kommersiya çatdırılması üzrə kommersiya qurumu. Hər hansı əməliyyatın müqavilə tərəfi həmin əməliyyatın sənədlərində göstərilir." },
      ip: { role: "Əqli mülkiyyət, brend və kommersiya koordinasiyası", p: "Müəyyən edilmiş əqli mülkiyyət, brend və ya kommersiya koordinasiyası rolu üçün göstərilir. Təsdiqlənməmiş heç bir müqavilə məsuliyyəti təyin edilmir." },
      stewardship: { role: "Nəzarətçi istinadı", p: "Müvafiq mənbə ilə dəstəkləndiyi hallarda House of Maximus ekosistem üçün nəzarətçi istinadıdır." },
      control: { role: "Daxili əqli mülkiyyət, mənşə və sənəd nəzarəti", p: "MIPA daxili əqli mülkiyyət, mənşə və sənəd nəzarəti qatıdır. Daxili MIPA qeydi xarici əmtəə nişanı, patent, müəllif hüququ qeydiyyatı və ya məhkəmə tanınmasından fərqlənir və vizual təsdiq demək deyil." },
    },
    labels: { licence: "Lisenziya", registration: "Qeydiyyat", vat: "VAT TRN", address: "Ünvan", email: "E-poçt", jurisdiction: "Yurisdiksiya" },
    boundaryTitle: "Hədlər",
    boundary: [
      "Alış avtomatik olaraq institusional üzvlük, idarəetmə hüquqları, royalti və ya investisiya hüququ vermir.",
      "İnstitusional rol kommersiya avadanlıq əməliyyatlarından ayrıdır.",
      "Məxfilik, proqram şərtləri və nəzarətli giriş qaydaları faktiki buraxılmış funksiyalara uyğundur.",
      "Hər ziyarətçiyə, satışa və ya xarici proqrama tətbiq olunan ümumi tətbiq olunan hüquq bəyanatı yoxdur; müqavilə əsası hər saziş üzrə müəyyən edilir.",
    ],
  },
  privacy: {
    title: "Məxfilik",
    updated: "Versiya 2026-09-21 · sayt 4.2",
    contactTitle: "Məxfilik sualları üçün əlaqə",
    sections: {
      collect: ["Nələr toplanır", "Formanı göndərdiyiniz zaman: daxil etdiyiniz məlumatlar (ad, e-poçt, rol, ölkə və ya region, göstərilibsə təşkilat, mesajınız və formanın cavabları), ziyarətinizin səhifə və kampaniya parametrləri (giriş səhifəsi, dil, utm parametrləri; reklam klik identifikatorları yalnız analitikaya icazə vermisinizsə) və göndərilmə vaxtı. IP ünvanınız yalnız heşlənmiş və qısamüddətli formada, sui-istifadənin məhdudlaşdırılması üçün istifadə olunur və sorğunuzla birlikdə saxlanılmır."],
      purpose: ["Nə üçün", "Sorğunuzu cavablandırmaq, istədiyiniz təklifi və ya spesifikasiyanı hazırlamaq və sorğunun qeydini saxlamaq üçün. Forma əsasında heç bir marketinq mesajı göndərilmir."],
      storageOn: ["Sorğular harada saxlanılır", "Sorğular Vercel Inc. hostinq platforması vasitəsilə təmin edilən Upstash, Inc. (Redis) verilənlər bazasında saxlanılır."],
      notifyEmail: ["Yeni sorğu barədə bildiriş", "Sorğu qəbul edildikdə, göndərdiyiniz məlumatları əhatə edən bildiriş e-poçtla MAXIMUS-un məsul poçt qutusuna göndərilir."],
      notifyTelegram: ["Yeni sorğu barədə bildiriş", "Sorğu qəbul edildikdə, göndərdiyiniz məlumatları əhatə edən bildiriş MAXIMUS-un məsul şəxsinə Telegram (Telegram FZ-LLC, Dubay) vasitəsilə göndərilir; bu zaman həmin bildiriş tranzit halında Telegram tərəfindən emal olunur."],
      notifyWebhook: ["Yeni sorğu barədə bildiriş", "Sorğu qəbul edildikdə, göndərdiyiniz məlumatları əhatə edən bildiriş imzalanmış, şifrələnmiş bağlantı üzərindən MAXIMUS-un daxili son nöqtəsinə göndərilir."],
      notifyNone: ["Yeni sorğu barədə bildiriş", "Yeni sorğular barədə bildiriş hazırlanma mərhələsindədir. Sorğunuz saxlanılır və MAXIMUS onu daxili reyestrdən oxuyur; bu məqsədlə heç bir üçüncü tərəfə heç nə göndərilmir."],
      storageOff: ["Sorğular harada saxlanılır", "Sorğuların saxlanılması hazırlanma mərhələsindədir. O, aktiv olana qədər formalar sorğunun qəbul edilə bilmədiyini bildirir; heç nə saxlanılmır. Sayt Vercel Inc. tərəfindən hostlanır."],
      browser: ["Brauzer yaddaşı", "Sessiya yaddaşı GPS və konfiquratorun seçim cavablarını, həmçinin ziyarətinizin kampaniya parametrlərini bu brauzer sessiyası üçün saxlayır. Əlaqə məlumatları, sərbəst mətn, qravüra mətni və uşaqlara dair məlumatlar brauzerdə saxlanılmır."],
      analyticsOn: ["Analitika", "Razılığınızla Google Analytics 4 əlaqə məlumatları və sorğu mətni olmadan ziyarətləri və forma hadisələrini ölçür. Seçiminiz lokal yaddaşda saxlanılır və altbaşlıqdakı «Analitika parametrləri» bölməsində istənilən vaxt dəyişdirilə bilər. Formalar analitika olmadan da işləyir."],
      analyticsOff: ["Analitika", "Bu saytda heç bir analitika aləti aktiv deyil."],
      retention: ["Saxlanma müddəti", "Hələ heç bir avtomatik silinmə müddəti qurulmayıb. Sorğunuzun silinməsini istənilən vaxt tələb edə bilərsiniz."],
      children: ["Uşaqlar", "Formalar yetkin şəxs tərəfindən doldurulmalıdır. 18 yaşadək oyunçulara dair sorğular valideyn və ya qəyyum tərəfindən edilir. Uşağın adını, doğum tarixini, məktəbini və ya tibbi məlumatlarını göndərməyin. Uşaqların profilləri heç vaxt dərc olunmur."],
      rights: ["Hüquqlarınız", "Sorğunuza baxmaq, onu düzəltmək və ya silmək üçün gps@maximus.tennis ünvanına yazın və sorğu nömrənizi göstərin."],
      controlled: ["Nəzarətli məlumat", "Konfidensial sənədlər bu saytda saxlanılmır və bu sayt vasitəsilə verilmir. Nəzarətli açıqlama ayrı kanallar vasitəsilə məxfilik sazişi və ya müqavilə əsasında həyata keçirilir."],
    },
  },
  terms: {
    title: "İstifadə şərtləri",
    copyright: "Bu saytın — mətnlərinin, fotoşəkillərinin, dizaynının və kodunun — müəllif hüququ yalnız Maximus Kiriyakulova aiddir. O, heç bir şirkətə və heç bir digər şəxsə ötürülməyib.",
    updated: "Versiya 2026-09-21",
    sections: [
      ["Məlumat, təklif deyil", "Bu saytdakı məhsul məlumatı təsdiqlənmiş spesifikasiyaları, konfiqurasiya arxitekturasını və proqram izahlarını təsvir edir. Bu, satış təklifi, qiymət cədvəli, anbar qalığı bəyanatı və ya çatdırılma öhdəliyi deyil. Kommersiya şərtləri hər əməliyyatda göstərilən müqavilə tərəfi ilə ayrıca, yazılı şəkildə razılaşdırılır."],
      ["Sorğular", "Bu sayt vasitəsilə göndərilən sorğu — GPS profilləri, konfiqurasiya sorğuları və texniki briflər də daxil olmaqla — sorğu nömrəsi ilə saxlanılır və nəzərdən keçirilir. O, qəbul edilmiş sifariş, istehsal öhdəliyi, təsdiqlənmiş görüş, üzvlük ərizəsi və ya hər hansı proqrama qəbul edilmiş müraciət deyil."],
      ["Spesifikasiyalar və sübutlar", "Hesablanmış dəyərlər, istehsal hədəfləri və təsdiqlənmiş spesifikasiyalar müvafiq səhifələrdə bir-birindən ayırd edilir. Sərtlik dəyərləri əksi dərc olunana qədər istehsal hədəfləridir. Konkret oyunçu üçün heç bir nəticəyə zəmanət verilmir."],
      ["Ekosistem, üzvlük və hüquqlar", "Raketin alınması institusional üzvlük, investisiya hüququ, əqli mülkiyyət sahibliyi, royalti hüququ və ya iştirak faydaları yaratmır. Hüquqlar dərc edilmiş proqram şərtlərindən və ya yazılı müqavilədən irəli gəlir."],
      ["Əqli mülkiyyət", "MAXIMUS®, aslan emblemi, GPS nişanı və bu saytın məzmunu qorunur. Daxili mühəndislik formulları, keyfiyyət nəzarəti protokolları, karbon laylarının düzülüşü, qəliblər, təchizatçıların kimliyi, maya dəyəri hesablamaları və qorunan metodologiya burada açıqlanmır."],
    ],
  },
  lead: {
    submit: "Sorğunu göndər",
    submitting: "Göndərilir…",
    retry: "Yenidən cəhd edin",
    acceptedEyebrow: "Sorğu qəbul edildi",
    acceptedTitle: "Sorğunuz alındı.",
    requestId: "Sorğu nömrəsi",
    acceptedNext: "MAXIMUS hər sorğunu nəzərdən keçirir və göstərdiyiniz e-poçt ünvanına yazılı cavab verir. Sonrakı müraciətlər üçün sorğu nömrəsini saxlayın.",
    duplicate: "Bu sorğu artıq alınmışdı; təkrar yaradılmadı.",
    another: "Yeni sorğuya başla",
    errorsTitle: "Zəhmət olmasa bu sahələri yoxlayın:",
    failTitle: "Sorğunuz göndərilmədi.",
    fail: {
      offline: "Cihazınız oflayndır.",
      network: "Serverlə bağlantı alınmadı.",
      timeout: "Server vaxtında cavab vermədi.",
      rate_limited: "Bu şəbəkədən çox sayda sorğu gəldi. Zəhmət olmasa bir neçə dəqiqə sonra yenidən cəhd edin.",
      too_fast: "Forma çox sürətlə göndərildi. Zəhmət olmasa yoxlayıb yenidən göndərin.",
      spam_suspected: "Sorğu spam süzgəci tərəfindən dayandırıldı.",
      unavailable: "Sorğular hazırda qəbul edilə bilmir.",
      default: "Gözlənilməz xəta baş verdi.",
    },
    keepNote: "Daxil etdikləriniz bu səhifədə saxlanılır, yenidən cəhd edə bilərsiniz.",
    sendByEmail: "Bu sorğunu e-poçtla göndərin",
    sendByEmailNote: "E-poçt proqramınız bu sorğunun mətni ilə açılır. Siz e-poçtu göndərdikdə MAXIMUS onu alır.",
    mailConfig: "Konfiqurasiya",
    mailPage: "Səhifə",
    fallback: "Problem davam edərsə, {email} ünvanına yazın. Sorğu yalnız sorğu nömrəsi göstərildikdə göndərilmiş sayılır.",
    privacyLink: "Məxfilik bildirişi",
    hpLabel: "Bu sahəni boş buraxın",
    consentShort: "Razılıq",
    after: "Göndərildikdən sonra sorğu nömrəsi bu səhifədə göstərilir. Sorğular nəzərdən keçirilir və yazılı cavablandırılır; sorğu sifariş deyil.",
    basis: { unstrung: "Simsiz", strung: "Simli", unknown: "Əmin deyiləm — spesifikasiyada razılaşdırılacaq" },
    hints: {
      email: "MAXIMUS bu ünvana yazılı cavab verir.",
      goal: "Məsələn: ilk yarış raketi və ya yeniyetmə raketindən keçid. Uşağın adını, doğum tarixini və ya tibbi məlumatlarını yazmayın.",
      currentRacquet: "Bilirsinizsə, brend və model.",
      message: "Şifrələri, ödəniş məlumatlarını və ya tibbi məlumatları yazmayın.",
    },
  },
  choose: {
    eyebrow: "Seçimdə kömək",
    title: "Raket seçməyə kömək edin",
    lead: "MAXIMUS-a səviyyənizi və sizin üçün ən vacib olanı bildirin. Cavablarınız nəzərdən keçirilir və yazılı təklif alırsınız: seriya, dəqiqlik sinfi, çəki və tutacaq.",
    stepsTitle: "Bundan sonra nə olur",
    steps: [
      ["Cavablarınız", "Səviyyə, prioritetlər və bilirsinizsə tutacaq ölçüsü."],
      ["Ekspert baxışı", "MAXIMUS cavablarınızı seriya matrisləri ilə müqayisə edir."],
      ["Yazılı təklif", "Təklif olunan konfiqurasiya və növbəti addım, yazılı şəkildə."],
    ],
    formTitle: "Cavablarınız",
    submit: "Seçimdə kömək tələb edin",
    altTitle: "Özünüz qərar vermək istəyirsiniz?",
    altGps: "Detallı GPS profili",
    altBuild: "Birbaşa konfiqurasiya edin",
    note: "Avtomatik fitting yoxdur və dəqiqlik iddiası irəli sürülmür: hər sorğuya insan baxır.",
  },
  consent: {
    title: "Analitika",
    text: "MAXIMUS ziyarətləri Google Analytics ilə ölçə bilər? Formalar hər iki halda işləyir; analitikaya heç bir əlaqə məlumatı və sorğu mətni göndərilmir.",
    allow: "Analitikaya icazə ver",
    decline: "İmtina et",
  },
  familyPlan: {
    title: "Ailə Planı",
    metaDescription: "Ailənizin tennis büdcəsini hesablayın: məşqlər, saatlar, topla təmaslar və bir məşqin, bir saatın və bir zərbənin dəyəri — öz rəqəmlərinizlə, üç ssenaridə.",
    eyebrow: "Ailə Planı · Bizimlə töhfə verin",
    heroTitle: "Ailənizin tennisi neçəyə başa gəlir — və bunun qarşılığında nə əldə edirsiniz?",
    heroLead: "Ailə büdcənizi, onun ödədiyi məşqləri və saatları, təxmini topla təmasları və bir məşqin, bir saatın və bir zərbənin dəyərini hesablayın — öz şərtlərinizlə.",
    heroCta: "Ailə planınızı hesablayın",
    strategy: {
      eyebrow: "Məqsədimiz",
      title: "Daha çox tennis. Daha çox imkan. Birlikdə.",
      p1: "Məqsədimiz iştirakı genişləndirərək və tennisə gedən yolu daha aydın və əlçatan edərək dünya tennis bazarını on dəfə böyütməkdir. MAXIMUS idarəetmə, metodologiya, keyfiyyət, nəticələr və oyunun populyarlaşdırılması vasitəsilə liderlik etməyi qarşısına məqsəd qoyur.",
      p2: "Digər tennis istehsalçılarını və onların brendlərini potensial tərəfdaş kimi görürük. Şirkətlərin, məşqçilərin, klubların və ailələrin güclərini tennisi qarşılıqlı fayda əsasında inkişaf etdirmək, təbliğ etmək və genişləndirmək üçün ortaq proqramda birləşdirməyi təklif edirik.",
      p3: "MAXIMUS bu yanaşmanın beşinci elementidir: ayrı-ayrı güclərin birlikdə işləməsinə kömək edən birləşdirici rol. Ortaq çağırışlarımız xəstəliklər, uşaqların hərəkətsizliyi və insanların oynamağa başlamasının və davam etməsinin qarşısını alan əngəllərdir.",
      p4: "Ailə üçün hər şey aydınlıqdan başlayır. Ailə Planı büdcəni, məşq və saat sayını, topla təmasların təxmini həcmini və məşqin dəyərini göstərir. Şərtləri dəyişin və sizə uyğun ssenarini seçin.",
      note: "On qat artım MAXIMUS olaraq qarşımıza qoyduğumuz strateji məqsəddir, artıq əldə olunmuş nəticə deyil. Kalkulyator ssenari hesablamalarını göstərir və heç bir qənaət, heç bir tibbi effekt və heç bir idman nəticəsi vəd etmir.",
      ctaCalc: "Ailə planınızı hesablayın",
      ctaPartner: "Tennisi birlikdə inkişaf etdirməyi müzakirə edək",
    },
    beyond: {
      eyebrow: "Kortdan kənarda",
      title: "Planın məşqdən əlavə qurduqları",
      admission: {
        h: "Aparıcı məktəb və universitetlərə qəbul",
        p: "MAXIMUS dünyanın aparıcı məktəb və universitetlərinə gedən yolda ailəni dəstəkləyir: oyunçunun idman portfoliosunun formalaşdırılması, sənədlərin və müraciətlərin hazırlanması, idmanla təhsilin birlikdə getdiyi proqramların seçilməsi. İdman təqaüdü verildiyi hallarda o, ailənin təhsil üçün ödədiyi məbləği azaldır.",
      },
      assets: {
        h: "Rəqəmsal aktivlər: oyunçunun adı, imici və nailiyyətləri",
        p: "Oyunçunun adı, imici, nəticələri, kontenti və şəxsi brendi aktivlərdir və zaman keçdikcə əhəmiyyətli maliyyə və status dəyəri qazana bilər. MAXIMUS onları yaratmağa, qeydiyyatdan keçirməyə və qorumağa kömək edir ki, bu dəyər oyunçuda və ailədə qalsın.",
      },
      note: "Heç biri kalkulyatorun hissəsi deyil. Məktəbdəki yerin, təqaüdün və ya rəqəmsal aktivin dəyəri konkret haldan asılıdır və burada qiymətləndirilmir.",
      cta: "Qəbul dəstəyi və rəqəmsal aktivlər barədə soruşun",
    },
    steps: ["Ailə məlumatları", "Məşqin iqtisadiyyatı", "Uzunmüddətli plan", "Yekun hesablama"],
    stepsLabel: "Kalkulyatorun addımları",
    scenarios: { now: "İndi", planned: "Plan", wish: "Arzu" },
    scenarioHints: { now: "Ailənizin bu gün etdiyi.", planned: "Növbəti addımda etməyi nəzərdə tutduğunuz.", wish: "Etmək istədiyiniz." },
    currency: {
      label: "Valyuta",
      note: "Daxil etdiyiniz hər məbləğ bu valyutadadır. Heç nə konvertasiya olunmur.",
    },
    fields: {
      players: { label: "Oynayan ailə üzvləri", hint: "Tam ədəd." },
      cost: { label: "Bir oyunçu üçün bir məşqin qiyməti", hint: "Vergi və rüsumlar daxil olmaqla tam məbləğ." },
      sessions: { label: "Bir oyunçu üçün ayda məşq sayı", hint: "Tam ədəd." },
      minutes: { label: "Bir məşqin müddəti, dəqiqə ilə", hint: "Fasilələr daxil olmaqla tam müddət. Kəsr ədədlərə icazə verilir." },
      contacts: { label: "Bir məşqdə bir oyunçunun topla təmasları", hint: "Təmas oyunçunun öz raketinin topa toxunmasıdır. Bir ralli tək bir təmas sayılmır. Hər ssenaridə eyni qaydada sayın." },
    },
    presetsLabel: "Sürətli seçim, dəqiqə",
    ages: {
      title: "Planın müddəti",
      start: "Başlanğıc yaşı",
      end: "Son yaş",
      hint: "Planın nə qədər davam edəcəyinə dair anonim fərziyyə; yalnız uzunmüddətli cədvəl üçün istifadə olunur. Bu, doğum tarixi deyil, tövsiyə olunan başlanğıc yaşı da deyil.",
    },
    extras: {
      title: "Ailənin əlavə xərcləri",
      note: "Bu məbləğlər bütün ailə üçündür və hər üç ssenariyə tətbiq olunur. Onlar oyunçuların sayına vurulmur və bir saatın və ya bir təmasın dəyərinə daxil edilmir.",
      equipment: "İlk avadanlıq — dövr üçün bir məbləğ",
      clothing: "Geyim və ayaqqabı — dövr üçün bir məbləğ",
      renewal: "Avadanlığın yenilənməsi — dövr üçün bir məbləğ, avtomatik təkrarlanmır",
      court: "Kort və ya klub — aylıq, bütün ailə",
      travel: "Səfərlər və tədbirlər — aylıq, bütün ailə",
      quoteSource: "Qiymətlərin mənbəyi (istəyə bağlı)",
      quoteDate: "Qiymətlərin tarixi (istəyə bağlı)",
      quoteNote: "Daxil etdiyiniz kimi göstərilir. MAXIMUS bu qiymətləri yoxlamır.",
    },
    storage: {
      save: "Planı bu cihazda saxlayın",
      clear: "Planı bu cihazdan silin",
      saved: "Plan bu cihazda saxlanıldı. Heç yerə heç nə göndərilmədi.",
      cleared: "Plan silindi. Kalkulyator başlanğıc dəyərlərinə qayıtdı.",
      restored: "Bu cihazda saxladığınız plan bərpa olundu.",
      invalid: "Bu cihazda saxlanılmış plan oxuna bilmədi və tətbiq olunmadı. Yeni hesablamaya başlaya bilərsiniz.",
      unavailable: "Bu brauzer cihazda saxlamağa icazə vermir.",
    },
    annual: {
      title: "Bir il, yan-yana",
      sessions: "İllik oyunçu-məşq",
      cost: "Ailənin illik məşq xərcləri",
      hours: "İllik oyunçu-saat",
      length: "Bir məşqin müddəti",
      contacts: "İllik topla təmaslar",
      note: "Oyunçu-məşq və oyunçu-saat göstəriciləri hər oyunçunun məşqlərini toplayır. Bunlar kort icarəsi saatları və ya qrup görüşləri deyil: birlikdə 90 dəqiqə məşq edən iki oyunçu 2 oyunçu-məşq və 3 oyunçu-saat deməkdir.",
    },
    economics: {
      title: "Bir məşqin, bir saatın və bir təmasın dəyəri",
      session: "Bir oyunçunun bir məşqi",
      hour: "Bir oyunçunun bir saatlıq məşqi",
      contact: "Topla bir təmas",
      undefinedContacts: "Müəyyən edilməyib: 0 təmas",
      undefinedMinutes: "Müəyyən edilməyib: 0 dəqiqə",
      below: "{value} məbləğindən az",
      note: "Bu rəqəmlərə yalnız məşqin qiyməti daxildir. Ailənin əlavə xərcləri təmaslara bölünmür.",
      caption: "Təmasların sayı seçilmiş məşq həcmindən və modelin fərziyyələrindən hesablanır. Faktiki məşq formatdan, fasilələrdən və məşq şəraitindən asılıdır. Bir təmasın dəyəri büdcə göstəricisidir, məşqçilik keyfiyyətinin göstəricisi deyil.",
    },
    longTerm: {
      title: "Uzunmüddətli xərc planı",
      horizon: "Müddət",
      activeYears: "Aktiv illər",
      years: "{n} il",
      note: "Aktiv illər iki yaş arasındakı fərqlə məhdudlaşır. Qiymətlər, tezlik, inflyasiya, mövsümlər, buraxılmış məşqlər və valyuta məzənnələri sabit qəbul edilir. Əlavə xərclər bu cədvələ daxil deyil.",
    },
    final: {
      title: "Yekun hesablama",
      scenario: "Ssenari",
      months: "Dövr, aylarla",
      heading: "{scenario} · {months} ay",
      total: "Dövr üzrə cəmi",
      training: "Məşqlər",
      extras: "Əlavə xərclər",
      oneOff: "Birdəfəlik xərclər",
      monthly: "Aylıq xərclər × ay",
      sessions: "Dövr ərzində oyunçu-məşq",
      hours: "Dövr ərzində oyunçu-saat",
      contacts: "Dövr ərzində topla təmaslar",
      formulaTitle: "Necə hesablanır",
      formula: "Cəmi = oyunçular × ayda məşq × ay × məşqin qiyməti + birdəfəlik xərclər + ay × aylıq əlavə xərclər.",
      formulaNote: "Əlavə xərclər bütün ailə üçün daxil edilir. Birdəfəlik xərclər 0 aylıq dövr üçün belə bir dəfə hesablanır.",
      inputs: "Daxil etdiyiniz məlumatlar",
    },
    units: { min: "dəq", h: "saat", approx: "≈" },
    errors: {
      title: "Nəticəni görmək üçün bu sahələri düzəldin",
      required: "Məcburi — rəqəm daxil edin; 0 qəbul olunur.",
      negative: "Mənfi ola bilməz.",
      integer: "Yalnız tam ədəd.",
      number: "Rəqəm daxil edin.",
      tooLarge: "Bu rəqəm hesablama üçün çox böyükdür.",
      endBeforeStart: "Son yaş başlanğıc yaşından kiçik ola bilməz.",
      tooLong: "200 simvoldan çox olmamalıdır.",
      date: "Düzgün tarix daxil edin.",
      currency: "Valyuta seçin.",
      scenario: "Ssenari seçin.",
      result: "Nəticə etibarlı şəkildə göstərilə bilməyəcək qədər böyükdür. Daxil etdiyiniz dəyərləri azaldın.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: tam kompozisiya — öndən və yandan görünən məşq raketi, dairəvi təmas başındakı qravüralı dairəvi aslan emblemi, şaft boyunca MAXIMUS və SPOT TRAINER qravürası və aslan nişanlı səkkizbucaqlı alt qapaq",
    greatHero: "MAXIMUS GREAT seriyası, 363 g: qırmızı və sarı baş detalları, parlaq MAXIMUS yazısı, şaftdakı Maximus avtoqrafı və aslanlı alt qapaqla tam kompozisiya",
    spotDetail: "Daha yaxından görünən iki MAXIMUS Spot Trainer: mat qara təmas başındakı qravüralı aslan, yivli tutacaq sarğısı və aslan nişanlı səkkizbucaqlı alt qapaqlar",
    spotPair: "Tünd səth üzərində maili şəkildə uzanmış iki MAXIMUS Spot Trainer, bir şaft boyunca MAXIMUS, digər şaft boyunca SPOT TRAINER qravürası, hər təmas başında aslan emblemi",
    spinVisual: "MAXIMUS SPIN: simli baş, parlaq MAXIMUS yazısı, tutacaq və aslanlı alt qapaq",
    powerVisual: "MAXIMUS POWER: simli baş, parlaq MAXIMUS yazısı, fərdiləşdirmə qravürası, tutacaq və aslanlı alt qapaq",
    greatVisual: "MAXIMUS GREAT: simli baş, parlaq MAXIMUS yazısı, fərdiləşdirmə qravürası, tutacaq, aslanlı alt qapaq və boğazdakı G seriyası nişanı",
    spinHead: "MAXIMUS SPIN başı və sim səthi",
    handleLion: "MAXIMUS boğazı, tutacağı və aslan nişanlı alt qapağı",
    engraving: "Şaftda gümüş fərdiləşdirmə qravürası",
    lettering: "Mat qara çərçivə üzərində parlaq qara MAXIMUS yazısı",
    variantAlt: "MAXIMUS {series} seriyası — {w} g, balans {b} mm: spesifikasiya zolağı, fərdiləşdirmə qravürası zonası və MIPA nişanı ilə tam vizualizasiya",
    sstSystem: "MAXIMUS Sweet Spot Trainer, dörd raketdən ibarət sistem",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "MAXIMUS yazısı ilə Sweet Spot Trainer şaftları",
    sstGrips: "Sweet Spot Trainer tutacaqları və alt qapaqları",
    sstButtcaps: "Sweet Spot Trainer, aslan nişanlı dörd alt qapaq",
    note: "Məhsul vizualı",
  },
  notFound: { title: "Səhifə tapılmadı", p: "İstədiyiniz səhifə bu dildə mövcud deyil.", cta: "Ana səhifəyə keçin" },
};

export default az;
