/* Bosnian dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const bs = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — teniski reketi u cijelosti od karbona, projektovani prema specifikaciji",
    defaultDescription:
      "Teniski reketi u cijelosti od karbona, od okvira do ručke: GREAT 97 in², POWER 98 in² i SPIN 100 in², osam fabričkih veličina ručke L0–L7, klase preciznosti za težinu, balans, težinu zamaha i krutost te inženjering po mjeri na zahtjev.",
  },
  common: {
    statuses: {
      current: "Aktuelno",
      agreement: "Dostupno po dogovoru",
      development: "U razvoju",
      concept: "Koncept",
      target: "Proizvodni cilj",
      modelled: "Izračunato",
      confirmed: "Potvrđeno",
      requested: "Zahtijevana arhitektura",
      notprovided: "Nije dostavljeno",
    },
    brief: { who: "Za koga je", value: "Šta dobijate", now: "Potvrđeno sada", next: "Sljedeći korak" },
    labels: {
      next: "Dalje",
      back: "Nazad",
      edit: "Uredite odgovore",
      review: "Provjera",
      start: "Počnite",
      restart: "Počnite iznova",
      copy: "Kopirajte tekst zahtjeva",
      copied: "Kopirano",
      openEmail: "Otvorite e-mail za slanje ovog zahtjeva",
      reference: "Referenca zahtjeva",
      weight: "Težina",
      balance: "Balans",
      swingweight: "Swingweight (težina zamaha)",
      stiffness: "Krutost",
      grip: "Veličina ručke",
      headSize: "Veličina glave",
      series: "Serija",
      precisionClass: "Klasa preciznosti",
      quantity: "Količina",
      notProvided: "Još nije objavljeno",
      requestTarget: "Zahtijevani cilj",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Pročitajte više",
      allSeries: "Sve serije",
      points: "navedene težine",
      optional: "neobavezno",
      required: "obavezno",
      select: "Izaberite",
      yes: "Da",
      no: "Ne",
      unknown: "Nisam siguran",
      custom: "Cilj po mjeri",
      listed: "Navedena težina",
      individual: "Pojedinačni reket",
      pair: "Usklađeni par",
      triple: "Usklađena trojka",
      team: "Timski set",
      summaryTitle: "Sažetak vašeg zahtjeva",
      nextAction: "Sljedeća radnja",
      status: "Stanje",
      learn: "Saznajte više",
      schematic: "Shema — nije mjerenje",
      photo: "Fotografija",
    },
    ecosystemStrip: "MAXIMUS ekosistem",
    truth: {
      noPrices: "Cijene, minimalne količine, rokovi izrade, garancije i obaveze isporuke potvrđuju se pisano, za svako tržište i svaki program.",
      requestNotOrder: "Zahtjev je zahtjev za razmatranje. On nije prihvaćena narudžba, proizvodna obaveza niti potvrđen termin.",
      noGuarantee: "Nijedna oprema, metoda ili program opisan ovdje ne garantuje rezultat pojedinom igraču.",
      governing: "Ova stranica objavljuje se na više jezika. Engleska verzija je obavezujuća; prijevod je dat radi lakšeg razumijevanja.",
    },
  },
  nav: {
    language: "Jezik",
    groups: { racquets: "Reketi", training: "Trening", ecosystem: "Ekosistem", partnerships: "Partnerstva" },
    familyPlan: "Porodični tenis",
    racquets: "Serije reketa i uporedba",
    great: "GREAT — 97 in² · Kontrola",
    power: "POWER — 98 in² · Snaga",
    spin: "SPIN — 100 in² · Rotacija",
    precision: "Preciznost i krutost",
    grip: "Fabrička arhitektura ručke L0–L7",
    custom: "Inženjering po mjeri",
    training: "Sistemi za trening",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologija",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Pomoć pri izboru",
    ecosystem: "Mapa ekosistema",
    engineering: "Inženjering i proizvodnja",
    experience: "Testiranje i prilagođavanje",
    brands: "Lični brendovi i ambasadori",
    families: "Porodice i roditelji",
    owners: "Vlasnici i trezor vlasnika",
    network: "Sports Network",
    partnerships: "Svi pravci partnerstva",
    coaches: "Treneri",
    clubs: "Klubovi i akademije",
    distribution: "Distribucija i razvoj tržišta",
    strategic: "Strategija i ulaganja",
    institutional: "Institucionalni programi",
    contact: "Kontakt",
    legal: "Pravni identitet",
    privacy: "Privatnost",
    terms: "Uslovi korištenja",
    menu: "Meni",
    close: "Zatvorite",
    home: "Početna",
    skip: "Pređite na sadržaj",
  },
  footer: {
    line: "Reket MAXIMUS vaš je ključ za svijet MAXIMUS.",
    product: "Proizvod",
    ecosystem: "Ekosistem",
    company: "Organizacija",
    instagram: "Instagram",
    email: "E-mail",
    analytics: "Postavke analitike",
    subscribe: {
      title: "Ostanite uz MAXIMUS",
      line: "Nove serije, termini prilagođavanja, materijali za trening i program za vlasnike. Nekoliko pisama godišnje, ništa više.",
      label: "E-mail adresa",
      placeholder: "your@email.com",
      button: "Prijavite se",
      sending: "Šalje se",
      done: "Adresa je na listi. Pišemo samo kada imamo nešto vrijedno čitanja.",
      invalid: "Provjerite adresu.",
      failed: "Adresa nije zabilježena. Pokušajte ponovo za trenutak.",
      terms: "Prijavom prihvatate da vam MAXIMUS može slati ove novosti i da u tu svrhu čuva vašu adresu. Svako pismo sadrži link za odjavu.",
    },
    rights: "MAXIMUS® i amblem lava oznake su MAXIMUS ekosistema. MIPA: interna kontrola intelektualne svojine, porijekla i dokumentacije.",
    boundary:
      "Komercijalni i ugovorni uslovi dogovaraju se posebno, pisanim putem. Kupovina reketa ne stvara institucionalno članstvo, investiciona prava, nosilaštvo prava intelektualne svojine niti pravo na tantijeme.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Preciznost počinje u trenutku kontakta.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer i MAXIMUS metodologija povezuju usmjeren trening s reketima visokih performansi izrađenim u cijelosti od karbona.",
    heroCta1: "Istražite sistem za trening",
    heroCta2: "Istražite GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrola",
    heroMeta: [
      ["U cijelosti od karbona", "od okvira do ručke"],
      ["4 parametra", "težina · balans · težina zamaha · krutost"],
      ["8 veličina ručke", "fabrička geometrija L0–L7"],
      ["3 serije", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Porodični teniski plan · Doprinesite s nama",
      title: "Vaš porodični budžet. Šta za njega dobijate. Šta njime gradite.",
      p: "Tri scenarija jedan pored drugog — trenutno, planirano i željeno. Koliko treninga, sati i kontakata s lopticom pokriva vaš budžet i koliko košta jedan trening, jedan sat i jedan udarac — sve izračunato na osnovu vaših vlastitih brojeva.",
      points: [
        ["Vaši brojevi", "Svaki iznos dolazi od vas. Bez pretpostavki i bez preračunavanja valuta."],
        ["Tri scenarija", "Uporedite ono što radite sada s onim što planirate i s onim što biste željeli."],
        ["Deset godina unaprijed", "Plan troškova za period od jedne do deset godina, ograničen rasponom uzrasta koji sami odredite."],
        ["Izvan terena", "Podrška pri upisu u vodeće škole i digitalna imovina koja ostaje igraču."],
      ],
      cta: "Izračunajte svoj porodični teniski plan",
    },
    paths: {
      eyebrow: "Počnite ovdje",
      title: "Izaberite svoj put",
      items: {
        player: { h: "Igrač", p: "Pronađite reket prema nivou i prioritetima ili ga odmah konfigurišite.", a: "Pronađite svoj reket" },
        parent: { h: "Roditelj", p: "Pisani put za razvojne ciljeve, uključenost trenera i odgovarajuću opremu.", a: "Put za porodice" },
        coach: { h: "Trener, klub ili akademija", p: "Sistemi za trening, prilagođavanje, timski setovi i personalizacija.", a: "Pravci za trenere i klubove" },
        partner: { h: "Distributer ili partner", p: "Distribucija, razvoj tržišta, strateški i institucionalni pravci.", a: "Pravci partnerstva" },
      },
    },
    series: {
      eyebrow: "Serije visokih performansi",
      title: "Tri arhitekture performansi. Jedna inženjerska platforma.",
      lead: "Izaberite seriju prema smjeru igre, a zatim dovršite konfiguraciju: klasa preciznosti, težina, ručka, personalizacija.",
      cta: "Uporedite serije",
      configure: "Konfigurišite",
      open: "Otvorite seriju",
      photoPending: "Fotografija još nije objavljena",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS sistem preciznosti",
      title: "Težina. Balans. Težina zamaha. Krutost.",
      sub: "Kontrolisani kao jedan inženjerski sistem.",
      lead: "Tri klase preciznosti određuju koliko se strogo svaki gotov reket drži svoje deklarisane specifikacije. P0.5 je uska tolerancija prema definisanom protokolu mjerenja — a ne nulta greška.",
      cta: "Preciznost i krutost u detalje",
    },
    stiffness: {
      eyebrow: "Krutost",
      title: "Ponovljiv odziv okvira prema deklarisanom cilju.",
      p: "Krutost okvira oblikuje odziv, osjećaj i konzistentnost između reketa. MAXIMUS je tretira kao četvrti kontrolisani parametar: cilj, izmjereni rezultat, dopuštena tolerancija i mogućnosti mjernog instrumenta vode se kao odvojeni zapisi. Korist je ponovljivost — a ne garantovan rezultat za svakog igrača.",
      cols: [["Odziv", "Kako okvir vraća energiju u trenutku kontakta."], ["Osjećaj", "Šta igrač osjeti u trenutku kontakta."], ["Konzistentnost", "Reketi izrađeni prema istoj specifikaciji reaguju jednako, unutar svoje klase."]],
      schematicCaption: "Shema: dopušteno odstupanje oko deklarisanog cilja krutosti za svaku klasu. Nije mjerenje; nijedna RA vrijednost se ne podrazumijeva.",
      bands: { p25: "tolerancija cilja ±1 RA", p15: "tolerancija cilja ±0,5 RA", p05: "odgovara deklarisanoj ciljnoj RA vrijednosti prema utvrđenom fabričkom protokolu mjerenja — a ne nulta greška", target: "deklarisani cilj (bez podrazumijevane vrijednosti)" },
    },
    carbon: {
      eyebrow: "Standard konstrukcije",
      title: "U cijelosti od karbona. Od okvira do ručke.",
      p: "Svi aktuelni MAXIMUS reketi na ovoj platformi po svojoj strukturi su u cijelosti od karbona, uključujući i ručku. Pjena se ne koristi za oblikovanje ručke.",
      gripTitle: "Osam fabričkih veličina ručke. L0–L7.",
      gripP: "Svaka veličina je fabrička geometrija karbonske ručke — a ne nadogradnja overgripom.",
      scaleCaption: "Shema: nominalne oznake veličina ručke L0–L7 (4″ do 4⅞″). Nisu izmjerene dimenzije ručke.",
      cta: "Fabrička arhitektura ručke",
    },
    custom: {
      eyebrow: "Inženjering po mjeri",
      title: "Izrađeno prema specifikaciji.",
      sub: "Standardna ponuda je početna tačka.",
      p: "MAXIMUS prima tehničke zahtjeve izvan objavljenih matrica na ocjenu, inženjersku obradu, validaciju i proizvodnju prema dogovorenoj specifikaciji. Izvodljivost se potvrđuje pisanim putem.",
      chain: ["Definisanje", "Inženjering", "Validacija", "Specifikacija", "Proizvodnja", "Mjerenje / zapis"],
      cta: "Pošaljite tehnički zahtjev",
      cta2: "Razgovarajte o inženjeringu po mjeri",
    },
    training: {
      eyebrow: "Sistemi za trening",
      title: "Sistem treninga izgrađen oko kontakta.",
      p: "Sweet Spot Trainer, MAXIMUS metodologija i Spot Trainer povezuju opremu s treningom pod vodstvom trenera: centriran kontakt, kontrola, progresivno opterećenje i vraćanje na reket visokih performansi.",
      cta: "Sistemi za trening",
      cta2: "Zatražite demonstraciju",
      photoPending: "Fotografija trenažera još nije objavljena",
      sstP: "Glava od 50 in² za trening centriranog kontakta, s četiri konfiguracije težine za opterećenje koje bira trener.",
      sstCta: "Istražite Sweet Spot Trainer",
      sstCaption: "Konfiguracija od 300 g, jedna od četiri",
      methodP: "Postavite ciljeve, izaberite opremu, trenirajte uz uključenost trenera, zapišite zapažanja, ponovo ocijenite, prilagodite i prenesite rad u takmičarsku igru.",
      methodCta: "Istražite metodologiju",
      spotP: "Mala okrugla meta za uvježbavanje precizne, ponovljive tačke kontakta.",
      spotCta: "Istražite Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Proizvodnja i kontrola kvaliteta",
      title: "Izrađeno prema specifikaciji. Izmjereno i zapisano.",
      p: "Proizvodnja prati pisanu specifikaciju svake narudžbe. Zapisi prate klasu preciznosti: sačuvani proizvodni zapisi za P2.5, pojedinačni zapisi i sljedivost za P1.5, pojedinačna kontrola i dokumentacija za P0.5 tamo gdje ih program narudžbe predviđa.",
      confirmedTitle: "Potvrđeno",
      confirmed: ["Konstrukcija u cijelosti od karbona, od okvira do ručke.", "Klase preciznosti P2.5, P1.5 i P0.5 sa četiri kontrolisana parametra.", "Osam fabričkih veličina ručke L0–L7."],
      pendingTitle: "Još nije objavljeno",
      pending: "Fotografije mjerne opreme, primjeri zapisa kontrole kvaliteta i snimci iz fabrike još nisu objavljeni. Ništa na ovoj stranici nije mjerni certifikat.",
      captions: { lettering: "Sjajni MAXIMUS natpis na mat okviru", buttcap: "Ručka i poklopac ručke s oznakom lava", handle: "Srebrna gravura personalizacije", finish: "Glava i površina žica" },
      cta: "Inženjering i proizvodnja",
    },
    world: {
      eyebrow: "Svijet MAXIMUS",
      title: "Jedan ključ. Jedan ekosistem. Neograničene mogućnosti.",
      note: "„Neograničene mogućnosti“ brendski je izraz, a ne obećanje neograničene tehničke izvodljivosti, prihoda ili pristupa. Kupovina ne stvara tantijeme, povrate na ulaganje, sponzorstvo niti finansiranje razvoja igrača.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — i vaša navigacija u svijetu tenisa: vođeni profil opreme na koji se odgovara pisanim putem." },
        personal: { h: "Personalizacija", p: "Imena, inicijali, brojevi i timska identifikacija u odobrenoj srebrnoj gravuri." },
        development: { h: "Razvoj", p: "Sistemi treninga pod vodstvom trenera, zapisi i ponovna ocjena." },
        ecosystem: { h: "Prošireni ekosistem", p: "Lični brendovi, zapisi vlasnika, mreža, licenciranje i institucionalni programi — svaki prikazan sa svojim stvarnim stanjem." },
      },
      cta: "Istražite ekosistem",
    },
    partners: {
      eyebrow: "Pravci partnerstva",
      title: "Treneri, klubovi, distributeri i partneri.",
      p: "Prvo pisana kvalifikacija. Prava za državu, ekskluzivnost i komercijalni uslovi dogovaraju se pisanim putem — nikada se ne dodjeljuju kroz obrazac.",
      cta: "Svi pravci partnerstva",
      formTitle: "Kratak upit",
      formLead: "Izaberite svrhu i pišite MAXIMUS-u. Broj zahtjeva dobijate na ovoj stranici.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "VAŠA NAVIGACIJA U SVIJETU TENISA" } },
    personal: { eyebrow: "Personalizacija", title: "Vaše ime. Vaš broj. Vaš MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tri serije. Stvarni parametri." },
    map: { cta: "Istražite ekosistem" },
  },
  racquets: {
    title: "Reketi",
    lead: "Tri serije visokih performansi sa zajedničkim standardom konstrukcije, zajedničkim sistemom preciznosti i zajedničkom fabričkom arhitekturom ručke. Svaka serija je utvrđena arhitektura performansi unutar šire inženjerske platforme.",
    direction: { control: "Kontrola", power: "Snaga", spin: "Rotacija" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Osnovni smjer igre",
    compareTitle: "Uporedba serija",
    compareLead: "Samo potvrđeni podaci o arhitekturi. Raspored žica, dužine, profili okvira, opsezi napetosti te nominalne vrijednosti težine zamaha i krutosti za ove serije se ne objavljuju; prikupljaju se kao zahtijevani ciljevi za tehničku ocjenu.",
    columns: { series: "Serija", head: "Veličina glave", direction: "Smjer", weights: "Navedene težine", range: "Opseg težina", balance: "Podaci o balansu" },
    balanceModelled: "Izračunate vrijednosti",
    balanceNotProvided: "Još nije objavljeno",
    construction: "Konstrukcija: u cijelosti od karbona, od okvira do ručke · Preciznost: P2.5 / P1.5 / P0.5 · Ručke: L0–L7",
    otherTitle: "Drugi reketni sportovi",
    otherLead: "Odobreni pravci razvoja. U ovim kategorijama ne postoje proizvodi za prodaju i na njih se ne prenosi teniska specifikacija.",
    other: { padel: "Padel tenis", pickleball: "Piklbol", squash: "Skvoš", badminton: "Badminton", racquetball: "Reketbol", beachTennis: "Tenis na pijesku" },
    ctaConfigure: "Konfigurišite zahtjev",
    ctaSeries: "Otvorite seriju",
  },
  seriesPage: {
    eyebrow: "Serije visokih performansi",
    intro: {
      great: "Arhitektura GREAT od 97 in² izgrađena je oko kontrole: kompaktna glava, precizan kontakt i sigurnost u usmjeravanju udarca.",
      power: "Arhitektura POWER od 98 in² izgrađena je oko prijenosa energije: dubina i tempo iz stabilnog okvira.",
      spin: "Arhitektura SPIN od 100 in² izgrađena je oko ponašanja loptice: rotacija, margina i oblikovanje putanje.",
    },
    photoPending: "Fotografija serije još nije objavljena",
    detailPending: "Fotografije konstrukcije i detalja ručke za ovu seriju još nisu objavljene.",
    specsTitle: "Specifikacija i stanje",
    catalogue: {
      eyebrow: "Katalog serije {series}",
      title: "{n} varijanti težine",
      lead: "Svaka varijanta serije {series}, sortirana po težini. Težina u gramima, balans u milimetrima od poklopca ručke. Svaka vizualizacija prikazana je u cijelosti: ništa nije odrezano, maskirano ni razvučeno.",
      selectLabel: "Izaberite varijantu težine",
      select: "Prikažite ovu varijantu",
      selected: "Prikazano iznad",
      balanceLabel: "Balans",
      headLabel: "Veličina glave",
      constructionLabel: "Konstrukcija",
      gripsLabel: "Fabričke veličine ručke",
      precisionLabel: "Klase preciznosti",
      balanceConfirmed: "Balans je potvrđena vrijednost za ovu težinu i odgovara broju ispisanom na vizualizaciji.",
      balanceModelled: "Balans je izračunata vrijednost za ovu navedenu težinu, a ne pojedinačno fabričko mjerenje; odgovara broju ispisanom na vizualizaciji.",
      zoom: "Otvorite sliku",
      close: "Zatvorite",
      allTitle: "Sve {n} varijante",
    },
    specs: { head: "Veličina glave", direction: "Osnovni smjer", weights: "Navedene težine", range: "Opseg težina", balance: "Balans", construction: "Konstrukcija", grips: "Fabričke ručke", precision: "Klase preciznosti" },
    construction: "U cijelosti od karbona, od okvira do ručke",
    statusTitle: "Stanje vrijednosti",
    matrixTitle: "Potpuna matrica težina",
    matrixLead: "Navedene težine su standardni izbor. Druge težine mogu se zahtijevati kao ciljevi po mjeri; međuvrijednosti koje nisu navedene ne dodaju se naknadno.",
    balanceNote: {
      confirmed: "Vrijednosti balansa potvrđene su za svaku navedenu težinu (mm od poklopca ručke) i odgovaraju broju ispisanom na vizualizaciji te težine. One se ovdje ne izračunavaju i ne izglađuju između susjednih težina; osnova mjerenja potvrđuje se u pisanoj specifikaciji.",
      modelled: "Vrijednosti balansa izračunate su za svaku navedenu težinu (mm od poklopca ručke). One nisu pojedinačna fabrička mjerenja; osnova mjerenja potvrđuje se u pisanoj specifikaciji.",
      notprovided: "Vrijednosti balansa za ovu seriju nisu dostavljene. Ne izvodite ih iz druge serije.",
    },
    optionsTitle: "Preciznost, ručka i težina",
    notPublished: "Za ovu seriju nije objavljeno: raspored žica, dužina, profil okvira, opseg napetosti te vrijednosti težine zamaha i krutosti. Možete ih navesti kao zahtijevane ciljeve za tehničku ocjenu.",
    offerTitle: "Šta se dešava nakon vašeg zahtjeva",
    offerSteps: [
      ["Zahtjev", "Pošaljite konfiguraciju ili pitanje. Broj zahtjeva prikazuje se odmah."],
      ["Ocjena", "MAXIMUS ocjenjuje seriju, klasu, težinu, ručku i sve zahtijevane ciljeve."],
      ["Pisani odgovor", "Specifikacija, dostupnost i komercijalni uslovi potvrđuju se pisanim putem."],
    ],
    faqTitle: "Pitanja",
    faq: [
      ["Jesu li vrijednosti balansa izmjerene?", "Izračunate su za navedene težine, a nisu pojedinačna mjerenja. Osnova mjerenja potvrđuje se u pisanoj specifikaciji."],
      ["Mogu li zahtijevati težinu koja nije navedena?", "Da, kao cilj po mjeri u punim gramima. Zahtjev se tehnički ocjenjuje, a izvodljivost se potvrđuje pisanim putem."],
      ["Šta mijenja klasa preciznosti?", "Koliko se strogo težina, balans, težina zamaha i krutost drže deklarisane specifikacije i koji se zapisi vode."],
      ["Nadograđuje li se ručka overgripovima?", "Ne. L0–L7 su fabričke geometrije karbonske ručke."],
      ["Gdje su cijene i rokovi dostave?", "Potvrđuju se pisanim putem za svaki zahtjev i ne objavljuju se ovdje."],
    ],
    faqSpinBalance: ["Odakle dolaze vrijednosti balansa za SPIN?", "Iz potvrđene tabele serije Spin: 33 varijante težine s balansom u milimetrima od poklopca ručke. Svaki par odgovara broju ispisanom na odobrenoj vizualizaciji te težine. Vrijednosti se ne izračunavaju i ne izglađuju između susjednih težina."],
    ctaBuild: "Konfigurišite ovu seriju",
    ctaAsk: "Pitajte o ovoj seriji",
    ctaCompare: "Uporedite sve serije",
    weightsLabel: "navedene težine",
    headLabel: "glava",
  },
  precision: {
    title: "Preciznost i krutost",
    switch: { label: "Izaberite klasu preciznosti", panelLabel: "Četiri kontrolisana parametra —", qcLabel: "QC arhitektura", protocolNote: "prema definisanom fabričkom protokolu mjerenja u kontroli kvaliteta", fullTable: "Potpuna tabela uporedbe" },
    lead: "Četiri parametra kontrolisana kao jedan inženjerski sistem. Svaka klasa određuje koliko se strogo gotov reket drži svoje deklarisane specifikacije i koji se zapisi kontrole kvaliteta stvaraju.",
    statement: "Težina. Balans. Težina zamaha. Krutost. Kontrolisani kao jedan inženjerski sistem.",
    classes: {
      "P2.5": { name: "Skalabilno jezgro performansi", qc: "Pojedinačno mjerenje i sačuvani proizvodni zapisi." },
      "P1.5": { name: "Povišena preciznost", qc: "Pojedinačno mjerenje, pojedinačni zapisi i sljedivost." },
      "P0.5": { name: "Profesionalno · pojedinačno kontrolisano", qc: "Pojedinačna kontrola s nominalnim i stvarnim vrijednostima i pojedinačnim zapisima mjerenja; serijski identitet, sljedivost serije, certifikat preciznosti i usklađeni setovi tamo gdje ih program narudžbe predviđa." },
    },
    columns: { cls: "Klasa", weight: "Težina", balance: "Balans", sw: "Težina zamaha", stiff: "Krutost", qc: "Arhitektura kontrole kvaliteta" },
    stiffTarget: "tolerancija cilja",
    stiffExact: "odgovara deklarisanoj ciljnoj RA vrijednosti prema utvrđenom fabričkom protokolu mjerenja",
    programmeNote: "Serijski identitet, certifikati i dokumentacija usklađenog seta izdaju se samo tamo gdje ih program konkretne narudžbe predviđa.",
    targetsNote: "Specifikacije krutosti ostaju proizvodni ciljevi dok odgovarajući protokol i proizvodni dokazi ne potkrijepe jaču tvrdnju. Opis arhitekture ne znači da je svaka navedena konfiguracija već prošla potpun proces otpuštanja po četiri parametra.",
    stiffnessTitle: "Zašto je krutost važna",
    stiffnessP1: "Krutost okvira utiče na to kako okvir reaguje u trenutku kontakta, kakav je osjećaj i koliko su dva reketa međusobno usklađena. Osnovna korist od njene kontrole je ponovljiv odziv u odnosu na deklarisanu specifikaciju.",
    stiffnessP2: "Prije objave provjerene usklađenosti, interni zapis kontrole kvaliteta navodi instrument, stanje njegove kalibracije, metodu, stanje reketa, rezoluciju, mjernu nesigurnost, ponovljena mjerenja, pravilo zaokruživanja i pravilo prihvatanja. Jednak prikazan cijeli broj nije dokaz nultog fizičkog odstupanja niti nulte greške mjerenja.",
    fields: ["Cilj", "Izmjereni rezultat", "Dopuštena tolerancija", "Mogućnosti instrumenta"],
    fieldsNote: "Vode se kao odvojena polja u svakom zapisu.",
    matchedTitle: "Usklađeni setovi",
    matchedP: "Kriteriji usklađenog seta određuju se odvojeno od pojedinačne tolerancije. Usklađenost svakog reketa s njegovom nominalnom tolerancijom sama po sebi ne dokazuje određenu najveću razliku između dva reketa. Usklađeni parovi, trojke i timski setovi zahtijevaju se kroz konfigurator i potvrđuju pisanim putem.",
    extendedTitle: "Prošireni tehnički model",
    extendedP: "Model podataka podržava dodatne parametre. Za njih još ne postoje vrijednosti ni klase tolerancije; mogu se navesti kao zahtijevani ciljevi u tehničkom zahtjevu.",
    extended: { twistweight: "Torziona težina (twistweight)", torsionalBehaviour: "Torziono ponašanje", length: "Dužina", beamProfile: "Profil okvira", headGeometry: "Geometrija glave", stringPattern: "Raspored žica", durability: "Trajnost", vibration: "Karakteristike vibracija" },
    noZero: "MAXIMUS svoju navedenu ponudu ne opisuje kao ponudu s nultom tolerancijom. Preciznost u ponudi navodi se kao klasa s deklarisanom tolerancijom i definisanom arhitekturom kontrole kvaliteta. ZERO nije dio ponude.",
    zero: {
      eyebrow: "Ekskluzivna opcija",
      title: "ZERO",
      sub: "Nulta tolerancija po gramu.",
      p: "Tri klase drže gotov reket unutar deklarisanog opsega tolerancije. ZERO ukida taj opseg. Reket se izrađuje i mjeri dok očitana vrijednost ne bude jednaka deklarisanom broju u rezoluciji fabričkog instrumenta, a to očitanje predaje se zajedno s njim. Nije dio navedene ponude i nije četvrta klasa: dogovara se pojedinačno, za jedan reket ili jedan usklađen set, kao ekskluzivna izrada po mjeri. Po dogovoru se isti pristup primjenjuje na balans i težinu zamaha.",
      points: [
        ["Bez opsega", "Deklarisani broj je rezultat, a ne središte tolerancije."],
        ["Jedan po jedan", "Izrađuje se, mjeri i zapisuje kao pojedinačna jedinica."],
        ["Predaje se s reketom", "Očitana vrijednost predaje se i čuva u proizvodnom zapisu."],
        ["Potvrđeno pisanim putem", "Parametri, obim i rok izrade dogovaraju se prije proizvodnje."],
      ],
      note: "Usklađenost se postiže u rezoluciji fabričkog mjernog instrumenta. Jednak prikazan broj nije tvrdnja o nultom fizičkom odstupanju. Dostupnost i uslovi dogovaraju se pojedinačno za svaku narudžbu.",
      cta: "Zatražite ZERO",
    },
    cta: "Konfigurišite uz klasu preciznosti",
  },
  grip: {
    title: "Fabrička arhitektura ručke",
    statement: "Osam fabričkih veličina ručke. L0–L7.",
    lead: "Geometrija ručke dio je arhitekture karbonske ručke. Svaka veličina proizvodi se kao geometrija same ručke, a ne nadograđuje overgripovima.",
    emph: "Proširene veličine",
    p1: "Fabrička ponuda od osam veličina daje trenerima i igračima širi konfiguracioni opseg kroz koji se oprema specificira oko igrača, uključujući i veće geometrije L6 i L7.",
    p2: "Nominalna oznaka ručke razlikuje se od sirovih konstrukcionih dimenzija ručke i od konačnog protokola mjerenja. Veličine važe za serije visokih performansi i za familije za trening na ovoj platformi.",
    p3: "Za ovu ponudu ne tvrdi se svjetska ekskluzivnost.",
    columns: { size: "Veličina", nominal: "Nominalno", family: "Važi za" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurišite uz svoju veličinu ručke",
  },
  custom: {
    title: "Inženjering po mjeri",
    statement: "Izrađeno prema specifikaciji.",
    sub: "Standardna ponuda je početna tačka.",
    lead: "MAXIMUS prima tehničke zahtjeve izvan objavljenih konfiguracionih matrica na ocjenu, inženjersku obradu, validaciju i proizvodnju prema dogovorenoj specifikaciji. Izvodljivost se potvrđuje kroz ocjenu — nije svaki zamislivi zahtjev fizički ili komercijalno izvodljiv.",
    scopeTitle: "Šta tehnički zahtjev može obuhvatiti",
    scope: ["Geometrija glave i okvira", "Dužina", "Težina", "Balans", "Težina zamaha", "Krutost", "Torziona težina", "Geometrija ručke", "Konstrukcija", "Usklađeni setovi", "Okviri za trening", "Vizualni izgled i gravura", "Identitet i timski programi", "Razvoj zavisan od alata"],
    processTitle: "Proces",
    process: [
      ["Definisanje", "Željeni ciljevi, obavezne granice, namjena i prihvatljivi kompromisi."],
      ["Inženjering", "Inženjerska ocjena u odnosu na platformu i alate."],
      ["Validacija", "Validacija u odnosu na dogovorenu specifikaciju."],
      ["Specifikacija", "Pisana specifikacija s osnovom mjerenja i tolerancijama."],
      ["Proizvodnja", "Proizvodnja prema specifikaciji."],
      ["Mjerenje / zapis", "Mjerenje i sačuvani zapisi prema odgovarajućoj klasi preciznosti."],
    ],
    formTitle: "Pošaljite tehnički zahtjev",
    formLead: "Razlikujte željene ciljeve od obaveznih granica. Rezultat je zahtjev za tehničku ocjenu, a ne automatski prihvaćena proizvodna narudžba.",
    protected: "Recepture slaganja karbona, alati, identitet dobavljača, interni obračun troškova i zaštićeno znanje ne otkrivaju se ovim putem.",
    cta: "Pošaljite tehnički zahtjev",
  },
  training: {
    title: "Sistemi za trening",
    lead: "Dvije familije za trening s vlastitim proizvodnim standardima, povezane jednom metodologijom: trening pod vodstvom trenera, zapisi, ponovna ocjena i vraćanje u takmičarsku igru.",
    sst: { h: "Sweet Spot Trainer", p: "Reket za trening sa smanjenom glavom od 50 in² u sistemu od četiri težine za trening centriranog kontakta, svijest o sweet spotu, kontrolu reketa i progresivno opterećenje." },
    spot: { h: "Spot Trainer", p: "Trening tačke kontakta pomoću male okrugle kontaktne mete, na odobrenoj osnovi od četiri težine." },
    method: { h: "Metodologija", p: "Postavite ciljeve, izaberite opremu uz uključenost trenera, koristite odgovarajući sistem, zapišite, ponovo ocijenite, prilagodite i prenesite." },
    experience: "Uzmite ga u ruku. Zamahnite. Osjetite.",
    experienceP: "Zatražite testiranje, prilagođavanje ili demonstraciju uz podršku trenera. Poslan zahtjev nije potvrđen termin.",
    cta: "Zatražite prilagođavanje ili demonstraciju",
    distinct: "Sweet Spot Trainer, Spot Trainer i svaki odvojeni demonstracioni uređaj različiti su proizvodi i nikada se ne spajaju.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Odvojena kategorija za trening s vlastitim proizvodnim standardom. Glava od 50 in² usmjerava pažnju na mjesto kontakta; četiri težine daju progresiju opterećenja.",
    baseline: "Potvrđena osnova",
    columns: { head: "Glava", length: "Dužina", pattern: "Raspored žica", grips: "Fabričke ručke" },
    systemTitle: "Sistem od četiri reketa",
    detailsTitle: "Detalji konstrukcije",
    systemLead: "Težina i balans kako su isporučeni. Osnova mjerenja vodi se odvojeno i još nije objavljena.",
    purposeTitle: "Namjena",
    purpose: ["Trening centriranog kontakta", "Svijest o sweet spotu", "Kontrola reketa", "Progresivno opterećenje", "Razvoj pod vodstvom trenera", "Vraćanje na igračev reket visokih performansi"],
    heavy: "Model od 400 g je kontrolisana konfiguracija za trening. Ne preporučuje se automatski djeci, početnicima ni svakom igraču; trener određuje opterećenje, trajanje i progresiju.",
    precisionNote: "Klase preciznosti P2.5, P1.5 i P0.5 ne primjenjuju se automatski na ovu familiju za trening. Tolerancije u proizvodnji za trening slijede vlastitu odobrenu specifikaciju familije.",
    health: "Ne obećava se sprječavanje ili liječenje teniskog lakta, otklanjanje povreda niti garantovano napredovanje.",
    cta: "Zatražite demonstraciju Sweet Spot Trainera",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Trening tačke kontakta pomoću male okrugle kontaktne mete. Zaseban proizvod s vlastitim vizualnim identitetom, izgrađen na odobrenoj osnovi od četiri težine.",
    purposeTitle: "Potvrđena namjena",
    purposeP: "Učenje igrača da nađe i ponavlja preciznu tačku kontakta.",
    weightsTitle: "Progresija težina",
    weightsP: "Progresija težina slijedi odobrenu osnovu težina Sweet Spot Trainera. Vrijednosti balansa i druge specifikacije Sweet Spot Trainera ne prenose se na Spot Trainer.",
    dims: "Tačne dimenzije mete još nisu objavljene.",
    grips: "Fabrička arhitektura ručke L0–L7.",
    notes: ["Klase preciznosti za performanse ne primjenjuju se automatski.", "Nije minijaturni klasični reket i ne objavljuje se raspored žica.", "Spot Trainer, Sweet Spot Trainer i svaki odvojeni demonstracioni uređaj ostaju razlučivi."],
    cta: "Pitajte o Spot Traineru",
  },
  methodology: {
    title: "Metodologija i iskustvo proizvoda",
    lead: "Oprema je jedan dio strukturiranog razvojnog puta. Metoda počinje od ciljeva igrača, a ne od naziva proizvoda.",
    stepsTitle: "Razvojni put",
    steps: [
      ["Postavite ciljeve", "Ciljevi igrača i početna tačka."],
      ["Izaberite opremu", "Odgovarajuća oprema izabrana uz uključenost trenera."],
      ["Koristite sistem", "Odgovarajući sistem za trening, pod vodstvom trenera."],
      ["Zapišite", "Zapažanja o stvarnom učešću, bez izmišljenih rezultata."],
      ["Ponovno ocijenite", "Uporedive kontrolne tačke."],
      ["Prilagodite", "Prilagođavanja konfiguracije ili programa."],
      ["Prenesite", "Naučeno se prenosi u takmičarsku igru."],
    ],
    educationTitle: "Edukacioni pravci",
    education: { player: "Igrači — razumijevanje konfiguracije, opterećenja i progresije.", parent: "Roditelji — kontinuitet razvoja, odgovarajuća oprema, zapisi i prava.", coach: "Treneri — sistemi za trening, prilagođavanje, ocjena i ovlašteno korištenje programa." },
    evidenceTitle: "Disciplina dokaza",
    evidenceP: "Zapisi o stvarnom učešću i zapažanja čuvaju se sa svojom klasifikacijom — izjava učesnika, potvrda staratelja, validacija trenera ili mjerenje sistema. Napredak, rezultati i validacija nikada se ne izmišljaju.",
    experienceTitle: "Uzmite ga u ruku. Zamahnite. Osjetite.",
    experienceP: "Testiranje, prilagođavanje ili demonstracija uz podršku trenera mogu se zatražiti. Poslan zahtjev nije potvrđen termin.",
    cta: "Zatražite prilagođavanje ili demonstraciju",
    cta2: "Upit za partnerstvo s trenerom",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — vođeni profil opreme",
    title: "MAXIMUS GPS",
    lead: "Vođeni profil opreme. Odgovorite samo na ono što je relevantno; provjerite i ispravite svoje odgovore; dobijate sažetak, konfiguracione pravce koji se primjenjuju i stvarnu sljedeću radnju.",
    honesty: "U ovoj verziji nijedno automatsko pravilo prilagođavanja nije odobreno. GPS zato daje jasan sažetak zahtjeva i upućuje na konfiguracione pravce; detalji opreme usmjeravaju se na ekspertnu ocjenu.",
    rulesVersion: "Verzija pravila",
    dataVersion: "Verzija podataka o proizvodima",
    steps: { role: "Uloga", sport: "Disciplina", experience: "Iskustvo", objectives: "Ciljevi", style: "Stil igre", equipment: "Trenutna oprema", preference: "Preferencije", coach: "Uključenost trenera", ageBand: "Uzrasna grupa", review: "Provjera" },
    notStored: "Ne čuva se u ovom pretraživaču.",
    ageNote: "Koristi se samo za usmjeravanje zahtjeva. Ne traže se ime, datum rođenja ni medicinski podaci.",
    q: {
      role: "Šta vas najbolje opisuje?",
      sport: "Koji sport?",
      experience: "Nivo iskustva",
      objectives: "Šta je najvažnije? (izaberite do tri)",
      style: "Stil igre, ako je poznat",
      equipment: "Trenutna oprema, ako je imate",
      equipmentHint: "Marka i model, težina ili veličina ručke ako ih znate. Neobavezno.",
      preference: "Željena konfiguracija ili poznata veličina ručke",
      grip: "Poznata veličina ručke",
      coach: "Učestvuje li trener u vašim odlukama o opremi?",
      ageBand: "Uzrasna grupa igrača (koristi se samo za ispravno usmjeravanje zahtjeva)",
    },
    roles: { player: "Igrač", parent: "Roditelj ili staratelj", coach: "Trener", club: "Klub ili akademija", other: "Drugo" },
    sports: { tennis: "Tenis", padel: "Padel tenis", pickleball: "Piklbol", squash: "Skvoš", badminton: "Badminton", other: "Drugi reketni sport" },
    sportNote: "Za tenis postoje proizvodi. Ostali sportovi su pravci razvoja; vaš interes se zapisuje za odgovarajući program.",
    experience: { beginner: "Početnik", developing: "Napredujem", intermediate: "Srednji nivo", advanced: "Visoki nivo", competitive: "Takmičarski", professional: "Profesionalni" },
    objectives: { control: "Kontrola", power: "Snaga", spin: "Rotacija", comfort: "Komfor", manoeuvrability: "Upravljivost", development: "Dugoročni razvoj", competition: "Takmičenje", training: "Sistem za trening", team: "Tim ili usklađen set", personal: "Personalizacija" },
    styles: { baseline: "Igra s osnovne linije", allcourt: "Univerzalna igra", attacking: "Napadačka igra", defensive: "Odbrambena igra", coach: "Po izboru trenera", unknown: "Nisam siguran" },
    ageBands: { u10: "Do 10 godina", u14: "10–13", u18: "14–17", adult: "18 i više" },
    output: {
      title: "Vaš profil opreme",
      status: "Potrebna je ekspertna ocjena",
      statusP: "U ovoj verziji ne izrađuje se automatsko uparivanje. Vaš profil je sažet za ekspertnu ocjenu.",
      directionsTitle: "Konfiguracioni pravci koji se primjenjuju",
      directionsP: "Na osnovu vaših navedenih ciljeva i deklarisanog smjera igre svake serije. Ovo je pravac, a ne preporuka prilagođavanja.",
      trainingHint: "Vaši ciljevi uključuju sistem za trening: pogledajte Sweet Spot Trainer i Spot Trainer.",
      teamHint: "Usklađeni setovi zahtijevaju se kroz konfigurator i potvrđuju pisanim putem.",
      next1: "Pošaljite profil na ekspertnu ocjenu",
      show: "Prikažite moj profil",
      configure: "Konfigurišite",
      sendP: "Pošaljite svoj profil MAXIMUS-u na ekspertnu ocjenu. Broj zahtjeva prikazuje se odmah; odgovor dolazi pisanim putem.",
      otherSport: "MAXIMUS reketi postoje za tenis. Za druge reketne sportove ne predlaže se teniska serija; vaš interes zapisuje se kao pravac razvoja.",
      noDirection: "Vaši ciljevi ne upućuju na jedan smjer igre. Ekspertna ocjena predložiće konfiguraciju.",
      incomplete: "Neki obavezni odgovori nedostaju — upotrijebite „Uredite odgovore“ da ih dopunite.",
    },
    privacy: "GPS ne traži zdravstvene podatke ni podatke koji identifikuju dijete. U sesiji ovog pretraživača čuvaju se samo odgovori s izborom iz liste; slobodan tekst se ne čuva.",
  },
  build: {
    title: "Napravite svoj",
    lead: "Konfigurišite zahtjev: serija, klasa preciznosti, navedena težina ili cilj po mjeri, veličina ručke, zahtijevani ciljevi, personalizacija, usklađeni setovi i količina. Rezultat je konfiguracioni zahtjev s brojem zahtjeva — a ne SKU, cijena, datum dostave ili certifikat.",
    steps: { series: "Serija", cls: "Klasa preciznosti", weight: "Težina", grip: "Ručka", targets: "Ciljevi", personal: "Personalizacija", set: "Set i količina", use: "Namjena", review: "Provjera" },
    q: {
      series: "Izaberite seriju",
      cls: "Izaberite klasu preciznosti",
      weightMode: "Težina",
      listed: "Navedena težina",
      customWeight: "Zahtijevana težina (g)",
      balanceShown: "Izračunat balans za ovu težinu",
      balanceRequest: "Zahtijevani balans (mm)",
      grip: "Fabrička veličina ručke",
      targetsTitle: "Zahtijevani ciljevi",
      swingweight: "Zahtijevana težina zamaha (kg·cm²)",
      stiffness: "Zahtijevana krutost (RA)",
      basis: "Osnova mjerenja za zahtijevane vrijednosti",
      engraving: "Tekst gravure",
      engravingHint: "Ime, inicijali ili broj. Latinična slova, cifre, razmak, crtica, apostrof i tačka; do 24 znaka. Druga pisma prihvataju se uz potvrdu grafičke pripreme.",
      engravingType: "Personalizacija",
      types: { none: "Bez personalizacije", name: "Ime igrača", initials: "Inicijali", number: "Broj seta", academy: "Identifikacija trenera ili akademije", team: "Timski program" },
      set: "Pojedinačni reket ili usklađen set",
      use: "Namjena",
      uses: { play: "Lična igra", competition: "Takmičenje", coaching: "Trenerski rad", team: "Tim ili akademija", retail: "Ocjena za maloprodaju ili distribuciju", other: "Drugo" },
      notes: "Dodatni tehnički zahtjevi",
    },
    classes: { "P2.5": "P2.5 — skalabilno jezgro performansi", "P1.5": "P1.5 — povišena preciznost", "P0.5": "P0.5 — profesionalno, pojedinačno kontrolisano" },
    stiffExactShort: "krutost odgovara deklarisanoj ciljnoj RA vrijednosti prema utvrđenom fabričkom protokolu",
    clsNote: "Svaka klasa kontroliše četiri parametra. P0.5 je uska tolerancija prema definisanom protokolu mjerenja — a ne nulta greška. Serijski identitet, certifikati i dokumentacija usklađenog seta važe samo tamo gdje ih program vaše narudžbe predviđa.",
    listedNote: "Iz potvrđene matrice serije.",
    customNote: "Težina izvan matrice, tehnički ocijenjena.",
    balanceCaption: "Svaka navedena težina prikazuje svoj izračunat balans u mm od poklopca ručke. Izračunate vrijednosti nisu pojedinačna mjerenja.",
    spinNote: "Težine serije SPIN čine zahtijevanu arhitekturu težina. Balans, težina zamaha i krutost za SPIN nisu dostavljeni; određuju se u tehničkoj ocjeni.",
    customHint: "Puni grami, samo cifre. Težina po mjeri je zahtjev za tehničku ocjenu; izvodljivost se potvrđuje pisanim putem i nijedna vrijednost se ne zaokružuje.",
    gripNote: "fabrička geometrija karbonske ručke, a ne nadogradnja overgripom",
    targetsLead: "Neobavezno. Unesite samo vrijednosti koje su vam potrebne. Svaka se zapisuje kao zahtijevani cilj za tehničku ocjenu, a ne kao objavljena specifikacija.",
    basisHint: "Obavezno kada zahtijevate težinu po mjeri ili bilo koji cilj: odnose li se vrijednosti na reket bez žica ili sa žicama?",
    inputRange: "Prihvaćen unos: {min}–{max}.",
    inputRangeNote: "Opsezi unosa samo odbacuju nemoguće vrijednosti. Oni ne opisuju proizvodnu sposobnost.",
    listedBasis: "navedene vrijednosti — osnova mjerenja potvrđuje se u pisanoj specifikaciji",
    notStored: "Ne čuva se u ovom pretraživaču; unesite ponovo ako osvježite stranicu.",
    artworkReview: "potrebna je potvrda grafičke pripreme",
    previewNote: "Vizualni pregled se ne prikazuje: odobren šablon gravure za ovaj model još nije objavljen. Vaš tekst prikuplja se za potvrdu grafičke pripreme.",
    teamSub: "4–99 reketa po setu",
    setsLabel: { individual: "Broj reketa", pair: "Broj usklađenih parova", triple: "Broj usklađenih trojki", team: "Broj timskih setova" },
    teamSizeLabel: "Reketa po timskom setu",
    totalLabel: "Ukupno reketa",
    racquetsUnit: "reketa",
    setRule: "Količina se računa po setovima: usklađen par je 2 reketa po setu, usklađena trojka 3.",
    restart: "Počnite novu konfiguraciju",
    notices: { weightCleared: "{w} g nije u matrici serije {series}, pa je težina obrisana. Izaberite navedenu težinu ili zatražite cilj po mjeri." },
    reviewTitle: "Konfiguracioni zahtjev",
    reviewP: "Provjerite konfiguraciju, a zatim dodajte svoje kontakt podatke. Zahtjev se čuva s brojem zahtjeva i na njega se odgovara pisanim putem; dostupnost i komercijalni uslovi potvrđuju se pisanim putem.",
    reviewErrors: "Neki odgovori u konfiguraciji zahtijevaju pažnju:",
    edit: "Uredite",
    fieldNames: { series: "Serija", cls: "Klasa preciznosti", mode: "Izbor težine", weight: "Navedena težina", customWeight: "Zahtijevana težina", basis: "Osnova mjerenja", balanceReq: "Zahtijevani balans", sw: "Zahtijevana težina zamaha", ra: "Zahtijevana krutost", grip: "Veličina ručke", ptype: "Personalizacija", engraving: "Tekst gravure", setType: "Vrsta seta", sets: "Količina", teamSize: "Reketa po timskom setu", use: "Namjena", notes: "Dodatni zahtjevi" },
    status: { listed: "navedena težina", requestedArchitecture: "zahtijevana arhitektura težina", technicalReview: "zahtjev za tehničku ocjenu", notPublished: "nije dostavljeno", requestedCondition: "zahtijevano stanje" },
    chooseLink: "Nisi siguran koja serija odgovara? Zatražite pomoć pri izboru",
    cta: "Pošaljite konfiguracioni zahtjev",
  },
  experience: {
    title: "Testiranje i prilagođavanje",
    statement: "Uzmite ga u ruku. Zamahnite. Osjetite.",
    lead: "Zatražite testiranje, prilagođavanje ili demonstraciju uz podršku trenera. Zahtjevi se ocjenjuju i na njih se odgovara pisanim putem; poslan zahtjev nije potvrđen termin.",
    optionsTitle: "Šta se može zatražiti",
    options: ["Testiranje reketa", "Sesija prilagođavanja", "Demonstracija uz podršku trenera", "Demonstracija Sweet Spot Trainera ili Spot Trainera", "Demo dan za tim ili akademiju"],
    formTitle: "Zahtjev za prilagođavanje ili demonstraciju",
  },
  engineering: {
    title: "Inženjering i proizvodnja",
    statement: "Avioni. Jahte. Reketi.",
    lead: "Jedna inženjerska filozofija u tri okruženja: principi koji oblikuju avion, preciznost koja vodi jahtu kroz otvoreno more, performanse koje određuju svaki MAXIMUS reket. Inženjerska priča — a ne tvrdnja o avionskoj certifikaciji, vlasništvu jahte, vlasništvu fabrike ili direktnom prenosu materijala.",
    manifesto: ["Vjerujemo da veliki inženjering nema granica.", "Jedna filozofija. Projektovano bez kompromisa."],
    capabilityTitle: "Proizvodna sposobnost",
    capabilityLead: "Sposobnost se prikazuje kao niz koraka, a ne kao slogan.",
    sequence: [
      ["Specifikacija", "Serija, klasa preciznosti, težina, balans, težina zamaha, ciljna krutost, geometrija ručke, personalizacija."],
      ["Proizvodnja", "Konstrukcija u cijelosti od karbona, od okvira do ručke, izrađena prema specifikaciji."],
      ["Kontrola kvaliteta", "Mjerenje i zapisi prema klasi preciznosti: proizvodni zapisi, pojedinačni zapisi i sljedivost, pojedinačna certifikacija."],
      ["Ponovljena proizvodnja", "Ponovljiv odziv u odnosu na deklarisanu specifikaciju kroz više serija."],
      ["Sljedivost", "Serijski identitet, sljedivost serije i certifikat preciznosti tamo gdje ih klasa predviđa."],
    ],
    capacityNote: "Proizvodni kapacitet, rokovi izrade, minimalne količine i planovi dostave potvrđuju se za svaki program pisanim putem, u odnosu na potvrđene narudžbe i dogovoren plan otpuštanja.",
    truth: "Kapacitet nije proizvedena količina, zaliha, garantovan datum dostave niti vlasništvo proizvodnog objekta.",
    cta: "Distribucija i razvoj tržišta",
    cta2: "Pošaljite tehnički zahtjev",
  },
  ecosystem: {
    title: "MAXIMUS ekosistem",
    lead: "Jedan ključ. Ovo je ono što otvara. Svaki čvor ima objašnjenje, tačno stanje i relevantnu sljedeću radnju.",
    words: ["Inženjering", "Performanse", "Inovacija", "Zajednica", "Prilika", "Svrha"],
    nodes: {
      engineering: { h: "Inženjering i proizvodnja reketa", p: "Reketi u cijelosti od karbona, projektovani prema specifikaciji, izrađeni sa zapisima kvaliteta i sljedivošću.", a: "Inženjering i proizvodnja" },
      precision: { h: "Preciznost i pojedinačna konfiguracija", p: "Četiri parametra, tri klase preciznosti, osam veličina ručke i inženjering po mjeri.", a: "Preciznost i krutost" },
      training: { h: "Trening i metodologija", p: "Sweet Spot Trainer, Spot Trainer i strukturiran razvojni put.", a: "Sistemi za trening" },
      development: { h: "Razvoj igrača i trenera", p: "Izbor opreme pod vodstvom trenera, zapisi, ponovna ocjena i edukacioni pravci.", a: "Metodologija" },
      identity: { h: "Lični identitet i lični brendovi", p: "Od gravure do ličnog ili profesionalnog brenda uređenog pravima.", a: "Lični brendovi" },
      owners: { h: "Zapisi vlasnika, znanje i prava", p: "Predloženi trezor vlasnika s dozvolama, za zapise o opremi, razvoju i pravima.", a: "Vlasnici i trezor" },
      mipa: { h: "MIPA porijeklo i interna kontrola", p: "Interni sloj kontrole intelektualne svojine, porijekla i dokumentacije.", a: "Pravni identitet i kontrola" },
      digital: { h: "Digitalna infrastruktura i pravac Blockchain 5.0", p: "Porijeklo, sljedivi zapisi, dokazi s dozvolama i identitet proizvoda kao navedeni tehnološki pravac.", a: "Tehnološki pravac" },
      licensing: { h: "Ugovorno licenciranje i programi tantijema", p: "Licencirani brendovi, proizvodi i paketi prava s uslovima određenim po ugovoru.", a: "Pravci licenciranja" },
      families: { h: "Učešće porodice i programske koristi", p: "Informisane odluke, kontinuitet, sačuvani zapisi i koristi određene programom.", a: "Porodice i roditelji" },
      network: { h: "MAXIMUS Sports Network", p: "Igrači, treneri, klubovi, akademije, pružaoci usluga, operateri i regionalni partneri.", a: "Sports Network" },
      market: { h: "Klubovi, akademije, distribucija i razvoj tržišta", p: "Timski programi, maloprodaja, distribucija i razvoj teritorije kroz pisanu kvalifikaciju.", a: "Pravci partnerstva" },
      institutional: { h: "Institucionalni programi, edukacija, inovacija i društveni uticaj", p: "Institucionalni sloj koji pruža MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tamo gdje program utvrđuje tu ulogu.", a: "Institucionalni programi" },
      extensions: { h: "Buduća proširenja na reketne sportove i MAXIMUS odjeću", p: "Padel tenis, piklbol, skvoš, badminton, reketbol, tenis na pijesku i odjeća kao pravci razvoja.", a: "Reketni sportovi" },
    },
    boundaryTitle: "Granice",
    boundary: [
      "Kupovina reketa ne stvara institucionalno članstvo, upravljačka prava, tantijeme niti investiciona prava.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) je institucionalni operater samo tamo gdje program utvrđuje tu ulogu; prodaja opreme navodi svoj stvarni ugovorni subjekt.",
      "Grantovi, status neprofitne organizacije, poreski status i regulatorne dozvole ne važe automatski u svim državama.",
    ],
    techTitle: "Tehnološki pravac",
    techP: "Blockchain 5.0 je navedeni tehnološki pravac MAXIMUS-a. Njegove funkcionalne namjene su porijeklo, sljedivi zapisi, dokazi s dozvolama, identitet proizvoda i usklađivanje kvalifikovanih komercijalnih događaja. Ne prikazuje se nijedan mehanizam konsenzusa, transakcioni kapacitet, mreža čvorova, adresa pametnog ugovora, token ili nezavisna certifikacija, i ne tvrdi se da je implementacija puštena u rad. Lični podaci, zapisi o djeci i povjerljivi ugovori nikada se po pravilu ne unose u javni nepromjenjivi sistem.",
  },
  brands: {
    title: "Lični brendovi i ambasadori",
    statement: "Od igrača do brenda. Od trenera do brenda.",
    lead: "Poseban pravac za lični brend. Uključenost MAXIMUS-a obuhvata razvoj brenda i dogovorenu promociju — a ne samo ime na reketu.",
    progressionTitle: "Predviđen razvoj",
    progression: [
      ["Provjeren identitet", "Provjeren identitet i historija razvoja."],
      ["Prepoznatljiv brend", "Prepoznatljiv lični ili profesionalni brend."],
      ["Sadržaj s riješenim pravima", "Sadržaj s riješenim pravima i odobren identitet proizvoda."],
      ["Inženjering i kolekcije", "Inženjering i razvoj kolekcije tamo gdje je dogovoreno."],
      ["Promocija", "Promocija kroz dogovorene MAXIMUS kanale i partnerstva."],
      ["Učešće", "Ugovorno učešće u kvalifikovanoj prodaji ili licenciranju."],
      ["Izvještavanje", "Transparentno izvještavanje prema ugovoru."],
    ],
    royaltiesTitle: "Tantijeme i licenciranje",
    royalties: [
      "Tantijeme se vežu za određeni licencirani brend, proizvod, transakciju ili paket prava.",
      "„Prodaja u svijetu“ znači kvalifikovanu prodaju u obimu ugovora — nikada svaki nepovezani MAXIMUS reket.",
      "Stope, osnovica obračuna, teritorije, trajanje, povrati, odbici, izvještavanje, obračun i provjera određuju se odgovarajućim ugovorom. Nijedan podrazumijevani procenat tantijema se ne objavljuje.",
      "Nijedna globalna kampanja, medijski budžet, rezultat sponzorstva niti komercijalni uspjeh ne obećava se bez dogovorenog obima.",
    ],
    cta: "Pošaljite upit za saradnju na brendu",
    cta2: "Upit za partnerstvo s trenerom",
  },
  families: {
    title: "Porodice i roditelji",
    lead: "Informisane odluke o opremi, kontinuitet razvoja, sačuvano znanje i prava, vidljivost učešća i koristi određene programom koje mogu podržati buduće aktivnosti.",
    nowTitle: "Dostupno sada",
    now: ["Porodični i razvojni upiti pisanim putem.", "Izbor opreme uz trenera, zahtjevi za prilagođavanje i demonstraciju.", "Privatni zapisi: profili djece se nikada ne objavljuju i po pravilu se nikada ne komercijalizuju.", "Edukacioni pravac za roditelje: konfiguracija, opterećenje, progresija, zapisi i prava."],
    plannedTitle: "Planirano",
    planned: ["Koristi od učešća određene programom, upotrebljive za robu i usluge unutar ekosistema, a ne kao kamata u novcu.", "Zapisi vlasnika i porodice u predloženom trezoru vlasnika, s dozvolama staratelja i prenosom kontrole s 18 godina."],
    categoriesTitle: "Drži se odvojeno",
    categories: ["Ugovorne tantijeme iz licenciranih prava ili kvalifikovane prodaje", "Koristi od učešća određene programom", "Krediti za kupovinu ili usluge", "Avansne uplate", "Institucionalno članstvo"],
    categoriesP: "Ove kategorije nikada se ne tretiraju kao zamjenjive.",
    statusTitle: "Stvarno stanje porodičnog programa",
    journeyTitle: "Put za porodice",
    journey: [
      ["Cilj", "Šta igrač želi postići u sljedećem koraku."],
      ["Trenutni nivo", "Gdje je igrač danas."],
      ["Trener", "Da li trener učestvuje u odlukama o opremi."],
      ["Oprema", "Odgovarajuća oprema za tu fazu, uključujući sisteme za trening kada su relevantni."],
      ["Dogovoren trening", "Korištenje pod vodstvom trenera dogovoreno unaprijed."],
      ["Provjera", "Ponovna ocjena na uporedivim kontrolnim tačkama."],
    ],
    brief: {
      who: "Roditelji i staratelji igrača u svakoj fazi.",
      value: "Pisani odgovor o odgovarajućoj opremi, uključenosti trenera i sljedećem razvojnom koraku.",
      now: "Porodični upiti pisanim putem; izbor uz trenera; privatni zapisi — profili djece se nikada ne objavljuju.",
      next: "Pošaljite porodični upit ispod. Broj zahtjeva dobijate odmah.",
    },
    formTitle: "Porodični upit",
    formNote: "Popunjava roditelj ili staratelj. Ne navodite ime djeteta, datum rođenja, školu ni medicinske podatke.",
    noPromise: "Kupovina ne obećava tantijeme, povrate na ulaganje, sponzorstvo niti finansiranje razvoja djeteta.",
    statusP: "Ova verzija objašnjava model i prima upite o programu. Pripisivanje, isplate i iskorištavanje nisu dostupni dok se kvalifikovani događaji, korisnici, izvor sredstava, osnovica obračuna, dozvoljene namjene, računovodstveni postupak, povrati, poništenja, rokovi važenja, prenosivost, zatvaranje programa i rješavanje sporova ne odrede pisanim putem. Ne obećava se da stanje nikada neće opadati, nijedno učešće ne plaća sav trening i ne podrazumijeva se zaštita uloženog kapitala.",
    cta: "Pošaljite porodični ili razvojni upit",
  },
  owners: {
    title: "Vlasnici i trezor vlasnika",
    lead: "Trezor vlasnika je predloženi zapis s dozvolama o opremi, razvoju, znanju, sadržaju i dokumentovanim pravima. Prikazan je kao dio planirane arhitekture za vlasnike: ne prikazuju se aktivni računi, stanja, certifikati ni postignuća.",
    nowTitle: "Za sadašnje vlasnike sada",
    now: ["Upiti vlasnika: referenca proizvoda ili serijskog broja, postavka, servis i zahtjevi za zapise, pisanim putem.", "Certifikat preciznosti i dokumentacija usklađenog seta tamo gdje ih klasa preciznosti predviđa, dostavljeni s proizvodom."],
    archTitle: "Planirana arhitektura trezora",
    arch: ["Identitet proizvoda i serijske reference", "Konfiguracija i primjenjivi certifikati kontrole kvaliteta", "Historija servisa i postavki", "Zapisi o razvoju igrača ili trenera", "Kvalifikacije i provjerena postignuća", "Mediji s riješenim pravima i autorski materijali", "Licence, dozvole i reference ugovora", "Zapisi programa ličnog brenda", "Primjenjivi obračuni tantijema ili koristi od učešća"],
    separationTitle: "Šta vlasništvo znači",
    separation: [
      "Vlasništvo nad fizičkim reketom odvojeno je od vlasništva nad autorskim pravom, licencom, ugovornim pravom ili zapisom koji te stvari opisuje.",
      "Sačuvan dokument ili unos u blockchain nije automatski dokaz da pravo postoji ili da je preneseno.",
      "Dokaz zadržava svoju klasifikaciju: izjava učesnika, potvrda staratelja, validacija trenera, mjerenje sistema.",
      "Za maloljetne: privatni zapisi, dozvole staratelja, bez objavljenih profila djece i bez komercijalizacije identiteta po pravilu.",
      "Izvoz, ispravka, kontrola pristupa i odgovarajući prenos kontrole dio su projekta.",
    ],
    techTitle: "Blockchain 5.0 i MxSN",
    techP: "Blockchain 5.0 je navedeni tehnološki pravac; MxSN određuje koncepte mreže s dozvolama za saglasnost, dostavu, dokaze, prava i izvještavanje. Operativna implementacija se ne prikazuje. Model podataka aplikacije izgrađen je tako da se kasnije poveže kroz dokumentovan interfejs, bez tvrdnje da veza danas postoji.",
    cta: "Upit vlasnika",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Veza između igrača, trenera, klubova, akademija, pružalaca usluga, operatera programa i regionalnih partnera.",
    functionsTitle: "Moguće funkcije",
    functions: ["Pronalaženje", "Upoznavanja", "Razvojni programi", "Podrška s opremom", "Događaji", "Pristup uslugama", "Partnerske prilike"],
    statusTitle: "Stvarno stanje",
    statusP: "Javni direktorij još nije objavljen: navest će se samo učesnici čiji su identitet, odnos i dozvola za objavu utvrđeni. Predlog poslan klubu nije partnerstvo, a potencijalni distributer nije imenovani distributer. Objava direktorija, rezervacije, razmjena poruka i komercijalne transakcije posebno se kontrolišu i nisu aktivni.",
    cta: "Prijavite se u mrežu",
  },
  partnerships: {
    title: "Pravci partnerstva",
    lead: "Prvo pisana kvalifikacija. Svaki pravac vodi do upita za određenu ulogu; komercijalni uslovi slijede pisanim putem.",
    commercialTitle: "Moguće komercijalne aktivnosti platforme",
    commercial: ["Oprema", "Inženjering po mjeri", "Personalizacija", "Timski i akademijski programi", "Sistemi za trening", "Ugovorno licenciranje", "Distribucija", "Odobrene usluge", "Buduće kategorije proizvoda"],
    boundary: "Prava za državu, ekskluzivnost, naknade za teritoriju i marže distributera predmet su pregovora. Ne objavljuju se prihodi, projekcije, procjene vrijednosti, tržišni udio, povrati, obaveze finansiranja niti neimenovana partnerstva.",
    routes: {
      coaches: {
        title: "Treneri",
        lead: "Sistemi za trening, prilagođavanje, profesionalni identitet, ovlašteni programi, prilike za lični brend i snabdijevanje opremom.",
        points: ["Sweet Spot Trainer i Spot Trainer u treningu pod vodstvom trenera.", "Prilagođavanje uz konfiguracione matrice i osam fabričkih veličina ručke.", "Coach-to-Brand: provjeren profesionalni profil i podbrend uređen pravima.", "Ovlašteno korištenje programa slijedi pisani ugovor."],
        cta: "Pošaljite upit za partnerstvo s trenerom",
        brief: {
          who: "Samostalni treneri i trenerski timovi.",
          value: "Sistemi za trening pod vodstvom trenera, prilagođavanje uz matrice serija i osam fabričkih ručki, te put do profesionalnog identiteta.",
          now: "Upiti trenera pisanim putem. Nijedna provizija, zarada ni stopa za preporuku se ne objavljuje niti podrazumijeva.",
          next: "Pošaljite trenerski upit ispod. Uslovi slijede pisanim putem.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubovi i akademije",
        lead: "Timska oprema, sistemi za trening, personalizacija, razvojni programi, servis i učešće u mreži.",
        points: ["Timski i usklađeni setovi zahtijevaju se kroz konfigurator.", "Sistemi za trening i metodologija za strukturiran razvoj.", "Personalizacija za timske programe na odobrenim zonama.", "Demo dani, sesije prilagođavanja i učešće u mreži."],
        cta: "Pošaljite zahtjev kluba ili akademije",
        brief: {
          who: "Klubovi, akademije i timski programi.",
          value: "Timski i usklađeni setovi, sistemi za trening, personalizacija za timske programe i demonstracioni dani.",
          now: "Zahtjevi klubova i akademija pisanim putem; timski setovi zahtijevaju se kroz konfigurator.",
          next: "Pošaljite zahtjev kluba ili akademije ispod.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribucija i razvoj tržišta",
        lead: "Asortiman, koordinacija proizvodnje, tehnička sposobnost, razvoj teritorije i povjerljiva komercijalna kvalifikacija.",
        points: ["Pisana kvalifikacija druge strane, teritorije i kanala.", "Asortiman određen iz konfiguracionih matrica i klasa preciznosti.", "Teritorija, ekskluzivnost, količine, cijene i komercijalna zaštita predmet su pregovora i dogovaraju se pisanim putem.", "Ugovorni subjekt, uslovi plaćanja i osnova dostave određuju se za svaku transakciju."],
        cta: "Pošaljite upit o distribuciji ili razvoju tržišta",
        brief: {
          who: "Trgovci, distributeri i partneri za pojedine države.",
          value: "Asortiman određen iz potvrđenih matrica, klasa preciznosti i ponude ručki, s pisanom kvalifikacijom teritorije i kanala.",
          now: "Upiti o distribuciji pisanim putem. Teritorija, ekskluzivnost, količine i cijene predmet su pregovora — ništa se ne dodjeljuje kroz obrazac.",
          next: "Pošaljite upit o distribuciji ispod.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategija i ulaganja",
        lead: "Inženjerska sposobnost, dubina konfiguracije, model proizvodnje, putevi do tržišta, intelektualna svojina, usluge i prilike za širenje.",
        points: ["Kvalifikovan strateški razgovor ili kontrolisan pristup informacijama slijedi nakon pisane kvalifikacije.", "Javne informacije ograničene su na odobrene specifikacije proizvoda, konfiguracionu arhitekturu, provjerene sposobnosti i objašnjenja programa.", "Ekonomika za pojedinog kupca, obračun troškova, zaštićena metodologija i neobjavljeni ugovori otkrivaju se samo uz NDA ili ugovor."],
        cta: "Zatražite kvalifikovan strateški razgovor",
        brief: {
          who: "Investitori i strateški partneri.",
          value: "Kvalifikovan razgovor o inženjerskoj sposobnosti, dubini konfiguracije, modelu proizvodnje, putevima do tržišta i intelektualnoj svojini.",
          now: "Ne objavljuju se finansijski podaci, projekcije, procjene vrijednosti ni povrati. Kontrolisane informacije slijede nakon pisane kvalifikacije i NDA.",
          next: "Zatražite kvalifikovan strateški razgovor ispod.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institucionalni programi",
        lead: "Edukacija, pristup, inovacija, dokazi o razvoju, društveni uticaj i primjereno strukturirani programi.",
        points: ["Institucionalni programi strukturiraju se kroz MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tamo gdje program utvrđuje tu ulogu.", "Namjenska programska sredstva i komercijalne transakcije ostaju odvojeni.", "Upit nije prihvaćena prijava za članstvo, a kupac opreme nije institucionalni član.", "Grantovi, status neprofitne organizacije, poreski status i regulatorne dozvole zavise od države i nikada se ne podrazumijevaju."],
        cta: "Pošaljite upit o institucionalnom programu",
        brief: {
          who: "Institucije, obrazovni i razvojni programi.",
          value: "Programi za edukaciju, pristup, inovaciju i dokaze o razvoju, strukturirani s odgovarajućim operaterom.",
          now: "Institucionalni upiti pisanim putem. Upit nije prijava za članstvo; kupovina opreme nije institucionalno članstvo.",
          next: "Pošaljite institucionalni upit ispod.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Javno i kontrolisano otkrivanje",
    disclosure: {
      public: { h: "Javno", p: "Odobrene specifikacije proizvoda, konstrukcija, konfiguraciona arhitektura, namjene treninga, provjerene sposobnosti, objašnjenja programa i pravci partnerstva." },
      qualified: { h: "Kvalifikovan upit", p: "Tehnički zahtjevi, količine, interes za teritoriju, obim razvoja i relevantni komercijalni razgovori." },
      controlled: { h: "Kontrolisano uz NDA ili ugovor", p: "Interne formule, detaljni protokoli kontrole kvaliteta, slaganje karbona, alati, metode proizvodnje, identitet dobavljača, obračun troškova, ekonomika za pojedinog kupca, zaštićena metodologija, neobjavljeni ugovori i osjetljivi zapisi o pravima." },
    },
  },
  contact: {
    title: "Kontakt i zahtjevi",
    lead: "Izaberite svrhu svog zahtjeva. Svaki obrazac prikuplja samo ono što je potrebno za usmjeravanje i ocjenu. Na zahtjeve se odgovara pisanim putem.",
    email: "E-mail",
    instagram: "Instagram",
    legalLink: "Pravni identitet",
  },
  form: {
    purposeLabel: "Svrha zahtjeva",
    purposes: {
      selection: "Pomoć pri izboru reketa",
      product: "Upit o proizvodu",
      fitting: "Prilagođavanje ili demonstracija",
      technical: "Tehnički zahtjev",
      config: "Konfiguracioni zahtjev",
      gps: "GPS profil opreme",
      coach: "Partnerstvo s trenerom",
      club: "Zahtjev kluba ili akademije",
      distribution: "Distribucija ili razvoj tržišta",
      brand: "Saradnja na brendu ili ambasadorstvo",
      family: "Porodični ili razvojni upit",
      institutional: "Institucionalni program",
      strategic: "Strateški ili investicioni razgovor",
      owner: "Upit vlasnika",
      network: "Prijava za Sports Network",
      general: "Opšti upit",
    },
    fields: {
      name: "Ime",
      email: "E-mail",
      role: "Vaša uloga",
      country: "Država ili regija",
      organisation: "Organizacija",
      message: "Vaša poruka",
      level: "Trenutni nivo",
      objectives: "Šta je najvažnije (do tri)",
      currentRacquet: "Trenutni reket",
      grip: "Veličina ručke, ako je poznata",
      seriesInterest: "Serija koja vas zanima",
      quantity: "Količina",
      city: "Grad ili lokacija za sesiju",
      coachInvolved: "Je li trener uključen?",
      timing: "Željeni termin",
      targets: "Željeni ciljevi",
      limits: "Obavezne granice",
      use: "Namjena",
      tradeoffs: "Prihvatljivi kompromisi",
      basis: "Osnova mjerenja",
      players: "Broj igrača",
      interests: "Oblasti interesa",
      territory: "Teritorija koja vas zanima",
      channels: "Postojeći kanali i iskustvo",
      audience: "Publika ili disciplina",
      proposal: "Predložena saradnja",
      goal: "Razvojni cilj",
      ageBand: "Uzrasna grupa igrača",
      scope: "Obim programa",
      interestArea: "Oblast interesa",
      productRef: "Referenca proizvoda ili serijskog broja",
      requestType: "Vrsta zahtjeva",
      seeking: "Šta tražite",
      consent: "Saglasan sam da MAXIMUS može čuvati i koristiti ove podatke kako bi odgovorio na ovaj zahtjev. Ovo nije prijava na marketinške poruke.",
    },
    roles: { player: "Igrač", parent: "Roditelj ili staratelj", coach: "Trener", club: "Klub ili akademija", retailer: "Trgovac", distributor: "Distributer", brand: "Brend ili ambasador", investor: "Investitor ili strateški partner", institution: "Institucija", other: "Drugo" },
    interestOptions: { training: "Sistemi za trening", fitting: "Prilagođavanje", identity: "Profesionalni identitet", programmes: "Ovlašteni programi", brand: "Lični brend", supply: "Snabdijevanje opremom", team: "Timska oprema", personalisation: "Personalizacija", development: "Razvojni programi", service: "Servis", network: "Učešće u mreži" },
    ownerTypes: { setup: "Postavka i konfiguracija", service: "Servis", records: "Zapisi i certifikati", other: "Drugo" },
    strategicAreas: { engineering: "Inženjerska sposobnost", configuration: "Dubina konfiguracije", manufacturing: "Model proizvodnje", routes: "Putevi do tržišta", ip: "Intelektualna svojina i usluge", expansion: "Prilike za širenje" },
    errors: {
      required: "Ovo polje je obavezno.",
      too_long: "Ovaj unos je predugačak.",
      too_short: "Ovaj unos je prekratak.",
      invalid_email: "Unesite ispravnu e-mail adresu, na primjer ime@primjer.com.",
      invalid_choice: "Izaberite jednu od opcija.",
      not_number: "Unesite cijeli broj, samo ciframa.",
      out_of_range: "Ova vrijednost je izvan prihvaćenog opsega.",
      not_in_matrix: "Ova težina nije u navedenoj matrici izabrane serije.",
      decimal_not_supported: "Unesite cijeli broj, bez decimala.",
      too_many: "Izaberite najviše tri opcije.",
      consent_required: "Saglasnost je potrebna da bi MAXIMUS mogao odgovoriti na ovaj zahtjev.",
      invalid: "Ovaj unos nije ispravan.",
    },
  },
  legal: {
    title: "Pravni identitet i kontrola",
    lead: "Javni brend je MAXIMUS / MAXIMUS GPS. Pravni poslovni identiteti su razlučivi i navedeni su ovdje.",
    entities: {
      institutional: { role: "Sloj institucionalnih programa", p: "Pruža sloj institucionalnih programa tamo gdje program utvrđuje tu ulogu. Nije komercijalni prodavač reketa. Neprofitna registrovana organizacija u Dubai International Financial Centre." },
      equipment: { role: "Komercijalni subjekt za opremu", p: "Komercijalni subjekt za opremu, za snabdijevanje, distribuciju i ugovorenu komercijalnu dostavu tamo gdje aktuelni poslovni dokumenti utvrđuju tu ulogu. Ugovorna strana za svaku transakciju navedena je u dokumentima te transakcije." },
      ip: { role: "Intelektualna svojina, brend i komercijalna koordinacija", p: "Pojavljuje se za utvrđenu ulogu u intelektualnoj svojini, brendu ili komercijalnoj koordinaciji. Ne pripisuje se nijedna nepotvrđena ugovorna odgovornost." },
      stewardship: { role: "Referenca upravljanja", p: "House of Maximus je referenca upravljanja ekosistemom tamo gdje je to potkrijepljeno odgovarajućim izvorom." },
      control: { role: "Interna kontrola intelektualne svojine, porijekla i dokumentacije", p: "MIPA je interni sloj kontrole intelektualne svojine, porijekla i dokumentacije. Interni MIPA unos razlikuje se od vanjske registracije robnog znaka, patenta ili autorskog prava i od sudskog priznanja, i ne predstavlja vizualno odobrenje." },
    },
    labels: { licence: "Licenca", registration: "Registracija", vat: "VAT TRN", address: "Adresa", email: "E-mail", jurisdiction: "Jurisdikcija" },
    boundaryTitle: "Granice",
    boundary: [
      "Kupovina automatski ne daje institucionalno članstvo, upravljačka prava, tantijeme niti investiciona prava.",
      "Institucionalna uloga odvojena je od komercijalnih transakcija s opremom.",
      "Privatnost, uslovi programa i kontrolisani pristup odgovaraju funkcijama koje su stvarno objavljene.",
      "Nijedna opšta izjava o primjenjivom pravu ne važi za svakog posjetioca, svaku prodaju ili svaki program u inostranstvu; ugovorna osnova određuje se po ugovoru.",
    ],
  },
  privacy: {
    title: "Privatnost",
    updated: "Verzija 2026-09-21 · web 4.2",
    contactTitle: "Kontakt za pitanja o privatnosti",
    sections: {
      collect: ["Šta se prikuplja", "Kada pošaljete obrazac: podaci koje unesete (ime, e-mail, uloga, država ili regija, organizacija ako je navedena, vaša poruka i odgovori iz obrasca), stranica i kampanjski parametri vaše posjete (ulazna stranica, jezik, utm parametri; identifikatori klikova na oglase samo ako ste dopustili analitiku) i vrijeme slanja. Vaša IP adresa koristi se samo u heširanom obliku i kratko, radi ograničavanja zloupotrebe, i ne čuva se s vašim zahtjevom."],
      purpose: ["Zašto", "Da bismo odgovorili na vaš zahtjev, pripremili ponudu ili specifikaciju koju ste tražili i vodili zapis o zahtjevu. Na osnovu obrasca ne šalju se marketinške poruke."],
      storageOn: ["Gdje se zahtjevi čuvaju", "Zahtjevi se čuvaju u bazi podataka kompanije Upstash, Inc. (Redis), koja se pruža kroz hosting platformu Vercel Inc."],
      notifyEmail: ["Obavijest o novom zahtjevu", "Kada je zahtjev prihvaćen, obavijest s podacima koje ste poslali šalje se e-mailom na odgovornu MAXIMUS adresu."],
      notifyTelegram: ["Obavijest o novom zahtjevu", "Kada je zahtjev prihvaćen, obavijest s podacima koje ste poslali šalje se odgovornoj osobi u MAXIMUS-u putem Telegrama (Telegram FZ-LLC, Dubai), koji tu obavijest time obrađuje u prenosu."],
      notifyWebhook: ["Obavijest o novom zahtjevu", "Kada je zahtjev prihvaćen, obavijest s podacima koje ste poslali šalje se na internu MAXIMUS krajnju tačku preko potpisane, šifrovane veze."],
      notifyNone: ["Obavijest o novom zahtjevu", "Obavještavanje o novim zahtjevima se uspostavlja. Vaš zahtjev se čuva i MAXIMUS ga čita iz internog registra; ništa se u tu svrhu ne šalje trećoj strani."],
      storageOff: ["Gdje se zahtjevi čuvaju", "Čuvanje zahtjeva se uspostavlja. Dok nije aktivno, obrasci navode da zahtjev ne može biti prihvaćen; ništa se ne čuva. Web stranicu hostuje Vercel Inc."],
      browser: ["Čuvanje u pretraživaču", "Sesijsko čuvanje zadržava odgovore s izborom iz liste u GPS-u i konfiguratoru te kampanjske parametre vaše posjete za ovu sesiju pretraživača. Kontakt podaci, slobodan tekst, tekst gravure i podaci o djeci ne čuvaju se u pretraživaču."],
      analyticsOn: ["Analitika", "Uz vašu saglasnost, Google Analytics 4 mjeri posjete i događaje u obrascima bez kontakt podataka i bez teksta zahtjeva. Vaš izbor čuva se u lokalnoj memoriji i možete ga promijeniti u svakom trenutku pod „Postavke analitike“ u podnožju stranice. Obrasci rade i bez analitike."],
      analyticsOff: ["Analitika", "Na ovoj web stranici nije aktivan nijedan alat za analitiku."],
      retention: ["Čuvanje podataka", "Automatski rok brisanja još nije postavljen. U svakom trenutku možete zahtijevati brisanje svog zahtjeva."],
      children: ["Djeca", "Obrasce popunjava odrasla osoba. Zahtjeve za igrače ispod 18 godina podnosi roditelj ili staratelj. Ne unosite ime djeteta, datum rođenja, školu ni medicinske podatke. Profili djece se nikada ne objavljuju."],
      rights: ["Vaša prava", "Za pristup, ispravku ili brisanje svog zahtjeva pišite na gps@maximus.tennis i navedite broj svog zahtjeva."],
      controlled: ["Kontrolisane informacije", "Povjerljivi dokumenti ne čuvaju se na ovoj web stranici i ne poslužuju se s nje. Kontrolisano otkrivanje provodi se uz NDA ili ugovor, kroz odvojene kanale."],
    },
  },
  terms: {
    title: "Uslovi korištenja",
    copyright: "Autorsko pravo na ovoj web stranici — na njenim tekstovima, fotografijama, dizajnu i kodu — pripada isključivo Maximusu Kiriyakulovu. Nije preneseno ni na jednu kompaniju ni na bilo koju drugu osobu.",
    updated: "Verzija 2026-09-21",
    sections: [
      ["Informacija, a ne ponuda", "Podaci o proizvodima na ovoj web stranici opisuju odobrene specifikacije, konfiguracionu arhitekturu i objašnjenja programa. Oni nisu ponuda za prodaju, cjenovnik, izjava o zalihama niti obaveza dostave. Komercijalni uslovi dogovaraju se posebno i pisanim putem s ugovornim subjektom navedenim u svakoj transakciji."],
      ["Zahtjevi", "Zahtjev poslan kroz ovu web stranicu — uključujući GPS profile, konfiguracione zahtjeve i tehničke zahtjeve — čuva se s brojem zahtjeva i ocjenjuje se. On nije prihvaćena narudžba, proizvodna obaveza, potvrđen termin, prijava za članstvo niti prihvaćena prijava za bilo koji program."],
      ["Specifikacije i dokazi", "Izračunate vrijednosti, proizvodni ciljevi i potvrđene specifikacije razlikuju se na odgovarajućim stranicama. Vrijednosti krutosti su proizvodni ciljevi dok se ne objavi drugačije. Nijedan rezultat za pojedinog igrača se ne garantuje."],
      ["Ekosistem, članstvo i prava", "Kupovina reketa ne stvara institucionalno članstvo, investiciona prava, nosilaštvo prava intelektualne svojine, pravo na tantijeme niti koristi od učešća. Prava slijede objavljene uslove programa ili pisani ugovor."],
      ["Intelektualna svojina", "MAXIMUS®, amblem lava, oznaka GPS i sadržaj ove web stranice su zaštićeni. Interne inženjerske formule, protokoli kontrole kvaliteta, slaganje karbona, alati, identitet dobavljača, obračun troškova i zaštićena metodologija ne otkrivaju se ovdje."],
    ],
  },
  lead: {
    submit: "Pošaljite zahtjev",
    submitting: "Šalje se…",
    retry: "Pokušajte ponovo",
    acceptedEyebrow: "Zahtjev je prihvaćen",
    acceptedTitle: "Vaš zahtjev je primljen.",
    requestId: "Broj zahtjeva",
    acceptedNext: "MAXIMUS ocjenjuje svaki zahtjev i odgovara pisanim putem na e-mail adresu koju ste dali. Sačuvajte broj zahtjeva za svaku dalju komunikaciju.",
    duplicate: "Ovaj zahtjev je već bio primljen; duplikat nije napravljen.",
    another: "Počnite novi zahtjev",
    errorsTitle: "Provjerite ova polja:",
    failTitle: "Vaš zahtjev nije poslan.",
    fail: {
      offline: "Vaš uređaj nije na mreži.",
      network: "Veza sa serverom nije uspjela.",
      timeout: "Server nije odgovorio na vrijeme.",
      rate_limited: "S ove mreže je došlo previše zahtjeva. Pokušajte ponovo za nekoliko minuta.",
      too_fast: "Obrazac je poslan veoma brzo. Provjerite ga i pošaljite ponovo.",
      spam_suspected: "Zahtjev je zaustavio filter neželjene pošte.",
      unavailable: "Zahtjevi se trenutno ne mogu primati.",
      default: "Došlo je do neočekivane greške.",
    },
    keepNote: "Vaš unos ostaje na ovoj stranici, pa možete pokušati ponovo.",
    sendByEmail: "Pošaljite ovaj zahtjev e-mailom",
    sendByEmailNote: "Otvara se vaša e-mail aplikacija s tekstom ovog zahtjeva. MAXIMUS ga prima kada pošaljete e-mail.",
    mailConfig: "Konfiguracija",
    mailPage: "Stranica",
    fallback: "Ako se problem nastavi, pišite na {email}. Zahtjev se smatra poslanim samo kada je prikazan broj zahtjeva.",
    privacyLink: "Obavijest o privatnosti",
    hpLabel: "Ostavite ovo polje prazno",
    consentShort: "Saglasnost",
    after: "Nakon slanja na ovoj stranici prikazuje se broj zahtjeva. Zahtjevi se ocjenjuju i na njih se odgovara pisanim putem; zahtjev nije narudžba.",
    basis: { unstrung: "Bez žica", strung: "Sa žicama", unknown: "Nisam siguran — dogovoriće se u specifikaciji" },
    hints: {
      email: "MAXIMUS odgovara pisanim putem na ovu adresu.",
      goal: "Na primjer: prvi takmičarski reket ili prelazak s juniorskog reketa. Ne navodite imena, datume rođenja ni medicinske podatke o djetetu.",
      currentRacquet: "Marka i model, ako su poznati.",
      message: "Ne navodite lozinke, podatke o plaćanju ni medicinske podatke.",
    },
  },
  choose: {
    eyebrow: "Pomoć pri izboru",
    title: "Pomozite mi da izaberem reket",
    lead: "Recite MAXIMUS-u svoj nivo i šta vam je najvažnije. Vaši odgovori se ocjenjuju i dobijate pisani predlog: serija, klasa preciznosti, težina i ručka.",
    stepsTitle: "Šta se dešava dalje",
    steps: [
      ["Vaši odgovori", "Nivo, prioriteti i veličina ručke ako je znate."],
      ["Ekspertna ocjena", "MAXIMUS uporedi vaše odgovore s matricama serija."],
      ["Pisani predlog", "Predložena konfiguracija i sljedeći korak, pisanim putem."],
    ],
    formTitle: "Vaši odgovori",
    submit: "Zatražite pomoć pri izboru",
    altTitle: "Želite sami odlučiti?",
    altGps: "Detaljan GPS profil",
    altBuild: "Konfigurišite direktno",
    note: "Bez automatskog prilagođavanja i bez tvrdnje o tačnosti: svaki zahtjev pregleda čovjek.",
  },
  consent: {
    title: "Analitika",
    text: "Može li MAXIMUS mjeriti posjete pomoću Google Analytics? Obrasci rade u oba slučaja; analitici se ne šalju kontakt podaci ni tekst zahtjeva.",
    allow: "Dopustite analitiku",
    decline: "Odbijte",
  },
  familyPlan: {
    title: "Porodični teniski plan",
    metaDescription: "Izračunajte teniski budžet svoje porodice: treninge, sate, kontakte s lopticom i cijenu jednog treninga, jednog sata i jednog udarca — na osnovu vlastitih brojeva, u tri scenarija.",
    eyebrow: "Porodični teniski plan · Doprinesite s nama",
    heroTitle: "Koliko vašu porodicu košta tenis — i šta za to dobijate?",
    heroLead: "Izračunajte porodični budžet, treninge i sate koje on pokriva, procijenjeni broj kontakata s lopticom te cijenu jednog treninga, jednog sata i jednog udarca — prema vlastitim uslovima.",
    heroCta: "Izračunajte svoj porodični teniski plan",
    strategy: {
      eyebrow: "Naš cilj",
      title: "Više tenisa. Više prilika. Zajedno.",
      p1: "Naš cilj je desetostruko povećati svjetsko tržište tenisa tako što ćemo proširiti učešće i put u tenis učiniti jasnijim i dostupnijim. MAXIMUS želi preuzeti vodeću ulogu kroz upravljanje, metodologiju, kvalitet, rezultate i popularizaciju igre.",
      p2: "Druge proizvođače teniske opreme i njihove brendove vidimo kao potencijalne partnere. Predlažemo da snage kompanija, trenera, klubova i porodica udružimo u zajednički program za razvoj, promociju i širenje tenisa, na obostranu korist.",
      p3: "MAXIMUS je peti element ovog pristupa: uloga koja ujedinjuje i pomaže da odvojene snage djeluju zajedno. Naši zajednički izazovi su bolesti, neaktivnost djece i prepreke koje ljude sprječavaju da počnu i nastave igrati.",
      p4: "Za porodicu sve počinje jasnoćom. Porodični teniski plan prikazuje budžet, broj treninga i sati, procijenjeni broj kontakata s lopticom i cijenu treniranja. Promijenite uslove i izaberite scenarij koji vam odgovara.",
      note: "Za MAXIMUS je desetostruki rast strateški cilj, a ne već postignut rezultat. Kalkulator prikazuje proračune po scenarijima i ne obećava ni uštedu, ni medicinski efekat, ni sportski rezultat.",
      ctaCalc: "Izračunajte svoj porodični teniski plan",
      ctaPartner: "Razgovarajmo o zajedničkom razvoju tenisa",
    },
    beyond: {
      eyebrow: "Izvan terena",
      title: "Šta plan gradi osim treninga",
      admission: {
        h: "Upis u vodeće škole i univerzitete",
        p: "MAXIMUS podržava porodicu na putu do vodećih škola i univerziteta u svijetu: izgradnjom sportske biografije igrača, pripremom dokumenata i prijava te izborom programa u kojima sport i školovanje idu ruku pod ruku. Ako se dodijeli sportska stipendija, ona smanjuje iznos koji porodica plaća za obrazovanje.",
      },
      assets: {
        h: "Digitalna imovina: ime, lik i postignuća igrača",
        p: "Ime, lik, rezultati, sadržaj i lični brend igrača su imovina koja s vremenom može izgraditi značajnu finansijsku i statusnu vrijednost. MAXIMUS pomaže da se ta imovina stvori, registruje i zaštiti, kako bi ta vrijednost ostala igraču i porodici.",
      },
      note: "Ni jedno ni drugo nije dio kalkulatora. Vrijednost mjesta u školi, stipendije ili digitalne imovine zavisi od konkretnog slučaja i ovdje se ne procjenjuje.",
      cta: "Pitajte o podršci pri upisu i o digitalnoj imovini",
    },
    steps: ["Podaci porodice", "Ekonomika treninga", "Dugoročni plan", "Konačni obračun"],
    stepsLabel: "Koraci kalkulatora",
    scenarios: { now: "Trenutno", planned: "Planirano", wish: "Željeno" },
    scenarioHints: { now: "Ono što vaša porodica radi danas.", planned: "Ono što namjeravate raditi dalje.", wish: "Ono što biste željeli raditi." },
    currency: {
      label: "Valuta",
      note: "Svaki iznos koji unesete izražen je u ovoj valuti. Ništa se ne preračunava u drugu valutu.",
    },
    fields: {
      players: { label: "Članovi porodice koji igraju", hint: "Cijeli broj." },
      cost: { label: "Cijena jednog treninga za jednog igrača", hint: "Iznos bez decimala, s uključenim porezima i taksama." },
      sessions: { label: "Broj treninga po igraču mjesečno", hint: "Cijeli broj." },
      minutes: { label: "Trajanje jednog treninga, u minutama", hint: "Puno vrijeme, uključujući pauze. Dozvoljeni su decimalni brojevi." },
      contacts: { label: "Kontakti s lopticom po igraču po treningu", hint: "Kontakt je dodir igračevog vlastitog reketa s lopticom. Jedna razmjena udaraca nije jedan kontakt. U svakom scenariju brojite na isti način." },
    },
    presetsLabel: "Brzi izbor, minute",
    ages: {
      title: "Trajanje plana",
      start: "Početni uzrast",
      end: "Završni uzrast",
      hint: "Anonimna pretpostavka o tome koliko plan traje, koristi se samo za dugoročnu tabelu. Nije datum rođenja niti preporučeni uzrast za početak.",
    },
    extras: {
      title: "Dodatni troškovi porodice",
      note: "Ovi iznosi se odnose na cijelu porodicu i važe za sva tri scenarija. Ne množe se brojem igrača i ne ulaze u cijenu sata niti kontakta.",
      equipment: "Prva oprema — jedan iznos za period",
      clothing: "Odjeća i obuća — jedan iznos za period",
      renewal: "Obnova opreme — jedan iznos za period, ne ponavlja se automatski",
      court: "Teren ili klub — mjesečno, za cijelu porodicu",
      travel: "Putovanja i događaji — mjesečno, za cijelu porodicu",
      quoteSource: "Izvor cijena (neobavezno)",
      quoteDate: "Datum cijena (neobavezno)",
      quoteNote: "Prikazuje se tačno onako kako ste unijeli. MAXIMUS ne provjerava ove cijene.",
    },
    storage: {
      save: "Sačuvajte plan na ovom uređaju",
      clear: "Obrišite plan s ovog uređaja",
      saved: "Plan je sačuvan na ovom uređaju. Ništa nije nigdje poslano.",
      cleared: "Plan je obrisan. Kalkulator je vraćen na početne vrijednosti.",
      restored: "Vraćen je plan koji ste sačuvali na ovom uređaju.",
      invalid: "Plan sačuvan na ovom uređaju nije se mogao pročitati i nije primijenjen. Možete započeti novi proračun.",
      unavailable: "Ovaj pretraživač ne dozvoljava čuvanje na uređaju.",
    },
    annual: {
      title: "Jedna godina, uporedo",
      sessions: "Igrač-treninzi godišnje",
      cost: "Izdaci porodice za treninge godišnje",
      hours: "Igrač-sati godišnje",
      length: "Trajanje jednog treninga",
      contacts: "Kontakti s lopticom godišnje",
      note: "Igrač-treninzi i igrač-sati sabiraju treninge svih igrača. To nisu sati iznajmljivanja terena niti grupni termini: dva igrača koji zajedno treniraju 90 minuta čine 2 igrač-treninga i 3 igrač-sata.",
    },
    economics: {
      title: "Cijena treninga, sata i kontakta",
      session: "Jedan trening jednog igrača",
      hour: "Jedan sat treninga jednog igrača",
      contact: "Jedan kontakt s lopticom",
      undefinedContacts: "Nije definisano: 0 kontakata",
      undefinedMinutes: "Nije definisano: 0 minuta",
      below: "manje od {value}",
      note: "U ove brojke ulazi samo cijena treninga. Dodatni troškovi porodice ne raspoređuju se na kontakte.",
      caption: "Broj kontakata izračunava se na osnovu izabranog obima treninga i pretpostavki modela. Stvarni trening zavisi od formata, pauza i uslova rada. Cijena kontakta je budžetski pokazatelj, a ne mjera kvaliteta trenerskog rada.",
    },
    longTerm: {
      title: "Dugoročni plan troškova",
      horizon: "Horizont",
      activeYears: "Aktivne godine",
      years: "{n} god.",
      note: "Aktivne godine ograničene su razlikom između početnog i završnog uzrasta. Cijene, učestalost, inflacija, sezone, propušteni treninzi i devizni kursevi uzimaju se kao nepromjenjivi. Dodatni troškovi nisu dio ove tabele.",
    },
    final: {
      title: "Konačni obračun",
      scenario: "Scenarij",
      months: "Period, u mjesecima",
      heading: "{scenario} · {months} mj.",
      total: "Ukupno za period",
      training: "Treninzi",
      extras: "Dodatni troškovi",
      oneOff: "Jednokratne stavke",
      monthly: "Mjesečne stavke × broj mjeseci",
      sessions: "Igrač-treninzi u periodu",
      hours: "Igrač-sati u periodu",
      contacts: "Kontakti s lopticom u periodu",
      formulaTitle: "Kako se računa",
      formula: "Ukupno = broj igrača × broj treninga mjesečno × broj mjeseci × cijena treninga + jednokratni troškovi + broj mjeseci × mjesečni dodatni troškovi.",
      formulaNote: "Dodatni troškovi unose se za cijelu porodicu. Jednokratne stavke računaju se jednom, čak i za period od 0 mjeseci.",
      inputs: "Vaši unosi",
    },
    units: { min: "min", h: "h", approx: "≈" },
    errors: {
      title: "Ispravite ova polja da biste vidjeli rezultat",
      required: "Obavezno polje — unesite broj; 0 je dozvoljena vrijednost.",
      negative: "Vrijednost ne može biti negativna.",
      integer: "Samo cijeli broj.",
      number: "Unesite broj.",
      tooLarge: "Ovaj broj je prevelik za proračun.",
      endBeforeStart: "Završni uzrast ne može biti manji od početnog.",
      tooLong: "Najviše 200 znakova.",
      date: "Unesite ispravan datum.",
      currency: "Izaberite valutu.",
      scenario: "Izaberite scenarij.",
      result: "Rezultat je prevelik da bi se pouzdano prikazao. Smanjite unesene vrijednosti.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: cjelovita kompozicija — trenažer sprijeda i sa strane, gravirani medaljon s lavom na okrugloj glavi za kontakt, gravura MAXIMUS i SPOT TRAINER duž vrata reketa i osmougaoni poklopac ručke s oznakom lava",
    greatHero: "MAXIMUS GREAT serija, 363 g: cjelovita kompozicija s crvenim i žutim detaljima na glavi, sjajnim MAXIMUS natpisom, Maximusovim autogramom na vratu reketa i znakom lava na ručki",
    spotDetail: "Dva MAXIMUS Spot Trainera izbliza: gravirani lav na mat crnoj glavi za kontakt, rebrasti omot ručke i osmougaoni poklopci ručki s oznakom lava",
    spotPair: "Dva MAXIMUS Spot Trainera položena pod uglom na tamnoj površini, s gravurom MAXIMUS duž jednog vrata reketa i SPOT TRAINER duž drugog, s medaljonom lava na svakoj glavi za kontakt",
    spinVisual: "MAXIMUS SPIN: glava sa žicama, sjajni MAXIMUS natpis, ručka i poklopac ručke s lavom",
    powerVisual: "MAXIMUS POWER: glava sa žicama, sjajni MAXIMUS natpis, gravura personalizacije, ručka i poklopac ručke s lavom",
    greatVisual: "MAXIMUS GREAT: glava sa žicama, sjajni MAXIMUS natpis, gravura personalizacije, ručka, poklopac ručke s lavom i oznaka serije G na grlu reketa",
    spinHead: "MAXIMUS SPIN glava i površina žica",
    handleLion: "MAXIMUS grlo reketa, ručka i poklopac ručke s oznakom lava",
    engraving: "Srebrna gravura personalizacije na vratu reketa",
    lettering: "Sjajni crni MAXIMUS natpis na mat crnom okviru",
    variantAlt: "MAXIMUS serija {series} — {w} g, balans {b} mm: cjelovita vizualizacija s trakom specifikacije, zonom gravure personalizacije i MIPA oznakom",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistem od četiri reketa",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Vratovi reketa Sweet Spot Trainer s MAXIMUS natpisom",
    sstGrips: "Ručke i poklopci ručki Sweet Spot Trainera",
    sstButtcaps: "Sweet Spot Trainer, četiri poklopca ručke s oznakom lava",
    note: "Vizual proizvoda",
  },
  notFound: { title: "Stranica nije pronađena", p: "Stranica koju ste zatražili ne postoji na ovom jeziku.", cta: "Idite na početnu stranicu" },
};

export default bs;
