/* Czech dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const cs = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — celokarbonové tenisové rakety vyvinuté podle specifikace",
    defaultDescription:
      "Celokarbonové tenisové rakety od rámu až po rukojeť: GREAT 97 in², POWER 98 in² a SPIN 100 in², osm výrobních velikostí gripu L0–L7, třídy přesnosti pro hmotnost, vyvážení, swingweight a tuhost a individuální konstrukce na vyžádání.",
  },
  common: {
    statuses: {
      current: "Aktuální",
      agreement: "Dostupné po dohodě",
      development: "Ve vývoji",
      concept: "Koncept",
      target: "Výrobní cíl",
      modelled: "Vypočteno",
      confirmed: "Potvrzeno",
      requested: "Požadovaná architektura",
      notprovided: "Neuvedeno",
    },
    brief: { who: "Pro koho je to určeno", value: "Co získáte", now: "Potvrzeno nyní", next: "Další krok" },
    labels: {
      next: "Další",
      back: "Zpět",
      edit: "Upravit odpovědi",
      review: "Přehled",
      start: "Začít",
      restart: "Začít znovu",
      copy: "Kopírovat text poptávky",
      copied: "Zkopírováno",
      openEmail: "Otevřít e-mail a odeslat tuto poptávku",
      reference: "Číslo poptávky",
      weight: "Hmotnost",
      balance: "Vyvážení",
      swingweight: "Swingweight",
      stiffness: "Tuhost",
      grip: "Velikost gripu",
      headSize: "Velikost hlavy",
      series: "Série",
      precisionClass: "Třída přesnosti",
      quantity: "Množství",
      notProvided: "Dosud nezveřejněno",
      requestTarget: "Požadovaná cílová hodnota",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Více informací",
      allSeries: "Všechny série",
      points: "uvedené hmotnosti",
      optional: "nepovinné",
      required: "povinné",
      select: "Vybrat",
      yes: "Ano",
      no: "Ne",
      unknown: "Nevím",
      custom: "Vlastní cílová hodnota",
      listed: "Uvedená hmotnost",
      individual: "Jednotlivá raketa",
      pair: "Párovaná dvojice",
      triple: "Párovaná trojice",
      team: "Týmová sada",
      summaryTitle: "Souhrn vaší poptávky",
      nextAction: "Další akce",
      status: "Stav",
      learn: "Zjistit více",
      schematic: "Schéma — nikoli měření",
      photo: "Fotografie",
    },
    ecosystemStrip: "Ekosystém MAXIMUS",
    truth: {
      noPrices: "Ceny, minimální objemy, dodací lhůty, záruky a dodací závazky se potvrzují písemně pro každý trh a každý program.",
      requestNotOrder: "Poptávka je žádostí o posouzení. Není přijatou zakázkou, výrobním závazkem ani potvrzeným termínem schůzky.",
      noGuarantee: "Žádné vybavení, metoda ani program popsaný na těchto stránkách nezaručuje konkrétnímu hráči určitý výsledek.",
      governing: "Tato stránka je publikována v několika jazycích. Rozhodující je anglická verze; překlad slouží pro snazší porozumění.",
    },
  },
  nav: {
    language: "Jazyk",
    groups: { racquets: "Rakety", training: "Trénink", ecosystem: "Ekosystém", partnerships: "Partnerství" },
    familyPlan: "Rodinný plán",
    racquets: "Série raket a srovnání",
    great: "GREAT — 97 in² · Kontrola",
    power: "POWER — 98 in² · Síla",
    spin: "SPIN — 100 in² · Rotace",
    precision: "Přesnost a tuhost",
    grip: "Výrobní architektura gripů L0–L7",
    custom: "Individuální konstrukce",
    training: "Tréninkové systémy",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodika",
    gps: "MAXIMUS GPS",
    build: "Postavte si vlastní",
    choose: "Pomozte mi vybrat",
    ecosystem: "Mapa ekosystému",
    engineering: "Konstrukce a výroba",
    experience: "Vyzkoušení a nastavení",
    brands: "Osobní značky a ambasadoři",
    families: "Rodiny a rodiče",
    owners: "Majitelé a trezor majitele",
    network: "Sports Network",
    partnerships: "Všechny partnerské cesty",
    coaches: "Trenéři",
    clubs: "Kluby a akademie",
    distribution: "Distribuce a rozvoj zemí",
    strategic: "Strategická spolupráce a investice",
    institutional: "Institucionální programy",
    contact: "Kontakt",
    legal: "Právní identita",
    privacy: "Ochrana osobních údajů",
    terms: "Podmínky",
    menu: "Nabídka",
    close: "Zavřít",
    home: "Domů",
    skip: "Přejít k obsahu",
  },
  footer: {
    line: "Raketa MAXIMUS je vaším klíčem do světa MAXIMUS.",
    product: "Produkt",
    ecosystem: "Ekosystém",
    company: "Organizace",
    instagram: "Instagram",
    email: "E-mail",
    analytics: "Nastavení analytiky",
    subscribe: {
      title: "Zůstaňte s MAXIMUS",
      line: "Nové série, termíny fittingu, tréninkové materiály a program pro majitele. Několik dopisů za rok, nic víc.",
      label: "E-mailová adresa",
      placeholder: "your@email.com",
      button: "Přihlásit se",
      sending: "Odesílá se",
      done: "Jste na seznamu. Píšeme jen tehdy, když máme něco, co stojí za přečtení.",
      invalid: "Zkontrolujte prosím adresu.",
      failed: "Adresu se nepodařilo zaregistrovat. Zkuste to prosím za chvíli znovu.",
      terms: "Přihlášením souhlasíte s tím, že vám MAXIMUS může tyto novinky zasílat a uchovávat pro tento účel vaši adresu. Každý dopis obsahuje odkaz pro odhlášení.",
    },
    rights: "MAXIMUS® a emblém lva jsou známkami ekosystému MAXIMUS. MIPA — interní správa duševního vlastnictví, původu a dokumentace.",
    boundary:
      "Komerční a smluvní podmínky se sjednávají samostatně písemně. Nákup rakety nezakládá institucionální členství, investiční práva, vlastnictví duševního vlastnictví ani nárok na licenční odměny.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Přesnost začíná v okamžiku kontaktu.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer a metodika MAXIMUS spojují soustředěný trénink s výkonem celokarbonových raket.",
    heroCta1: "Prozkoumat tréninkový systém",
    heroCta2: "Prozkoumat GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrola",
    heroMeta: [
      ["Celokarbonová konstrukce", "od rámu až po rukojeť"],
      ["4 parametry", "hmotnost · vyvážení · swingweight · tuhost"],
      ["8 velikostí gripu", "výrobní geometrie L0–L7"],
      ["3 série", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Rodinný plán · Přispějte spolu s námi",
      title: "Váš rodinný rozpočet. Co za něj pořídíte. Co s ním vybudujete.",
      p: "Tři scénáře vedle sebe — současnost, plán a přání. Tréninky, hodiny a kontakty s míčem, které váš rozpočet zaplatí, a cena jednoho tréninku, jedné hodiny a jednoho úderu — vše vypočtené z vašich vlastních čísel.",
      points: [
        ["Vaše čísla", "Každou částku zadáváte vy. Nic se nepředpokládá, nic se nepřepočítává."],
        ["Tři scénáře", "Porovnejte, co děláte nyní, s tím, co plánujete, a s tím, co byste si přáli."],
        ["Deset let dopředu", "Plán výdajů na jeden až deset let, ohraničený počátečním a konečným věkem, které zadáte."],
        ["Mimo kurt", "Podpora při přijetí na přední školy a digitální aktiva, která zůstávají hráči."],
      ],
      cta: "Spočítat svůj rodinný plán",
    },
    paths: {
      eyebrow: "Začněte zde",
      title: "Vyberte si svou cestu",
      items: {
        player: { h: "Hráč", p: "Najděte raketu podle úrovně a priorit, nebo si ji přímo nakonfigurujte.", a: "Najděte svou raketu" },
        parent: { h: "Rodič", p: "Písemná cesta pro rozvojové cíle, zapojení trenéra a vhodné vybavení.", a: "Cesta pro rodiny" },
        coach: { h: "Trenér, klub nebo akademie", p: "Tréninkové systémy, fitting, týmové sady a personalizace.", a: "Cesty pro trenéry a kluby" },
        partner: { h: "Distributor nebo partner", p: "Distribuce, rozvoj zemí, strategické a institucionální cesty.", a: "Partnerské cesty" },
      },
    },
    series: {
      eyebrow: "Výkonnostní série",
      title: "Tři výkonnostní architektury. Jedna konstrukční platforma.",
      lead: "Vyberte sérii podle herního zaměření a poté dokončete konfiguraci: třída přesnosti, hmotnost, grip, personalizace.",
      cta: "Porovnat série",
      configure: "Konfigurovat",
      open: "Otevřít sérii",
      photoPending: "Fotografie dosud nezveřejněna",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Systém přesnosti MAXIMUS",
      title: "Hmotnost. Vyvážení. Swingweight. Tuhost.",
      sub: "Řízeno jako jeden konstrukční systém.",
      lead: "Tři třídy přesnosti určují, jak přísně je každá hotová raketa držena na své deklarované specifikaci. P0.5 je úzká tolerance podle definovaného protokolu měření — nikoli nulová chyba.",
      cta: "Přesnost a tuhost podrobně",
    },
    stiffness: {
      eyebrow: "Tuhost",
      title: "Opakovatelná odezva rámu vůči deklarovanému cíli.",
      p: "Tuhost rámu určuje odezvu, pocit a shodu mezi raketami. MAXIMUS s ní pracuje jako se čtvrtým řízeným parametrem: cílová hodnota, výsledek měření, povolená tolerance a schopnost měřicího přístroje se vedou jako samostatné záznamy. Přínosem je opakovatelnost — nikoli zaručený výsledek pro každého hráče.",
      cols: [["Odezva", "Jak rám vrací energii v okamžiku kontaktu."], ["Pocit", "Co hráč v okamžiku kontaktu cítí."], ["Shoda", "Rakety postavené podle stejné specifikace reagují v rámci své třídy stejně."]],
      schematicCaption: "Schéma: povolená odchylka okolo deklarované cílové tuhosti pro každou třídu. Nejde o měření a nevyplývá z něj žádná hodnota RA.",
      bands: { p25: "cílová tolerance ±1 RA", p15: "cílová tolerance ±0,5 RA", p05: "odpovídá deklarované cílové hodnotě RA podle zavedeného výrobního protokolu měření — nikoli nulová chyba", target: "deklarovaný cíl (bez uvedení hodnoty)" },
    },
    carbon: {
      eyebrow: "Konstrukční standard",
      title: "Celokarbonová konstrukce. Od rámu až po rukojeť.",
      p: "Všechny současné rakety MAXIMUS na této platformě jsou ve své struktuře celokarbonové, včetně rukojeti. K vytvoření rukojeti se nepoužívá pěna.",
      gripTitle: "Osm výrobních velikostí gripu. L0–L7.",
      gripP: "Každá velikost je geometrií karbonové rukojeti z výroby — nikoli navinutím omotávek.",
      scaleCaption: "Schéma: nominální označení gripů L0–L7 (4″ až 4⅞″). Nejde o naměřené rozměry rukojeti.",
      cta: "Výrobní architektura gripů",
    },
    custom: {
      eyebrow: "Individuální konstrukce",
      title: "Vyvinuto podle specifikace.",
      sub: "Standardní řada je výchozím bodem.",
      p: "MAXIMUS přijímá technické požadavky nad rámec zveřejněných matic k vyhodnocení, konstrukci, validaci a výrobě podle sjednané specifikace. Realizovatelnost se potvrzuje písemně.",
      chain: ["Definovat", "Zkonstruovat", "Validovat", "Specifikovat", "Vyrobit", "Změřit / zaznamenat"],
      cta: "Zaslat technické zadání",
      cta2: "Projednat individuální konstrukci",
    },
    training: {
      eyebrow: "Tréninkové systémy",
      title: "Tréninkový systém postavený na kontaktu.",
      p: "Sweet Spot Trainer, metodika MAXIMUS a Spot Trainer spojují vybavení s tréninkem vedeným trenérem: kontakt ve středu, kontrola, postupné zatížení a přechod zpět k výkonnostní raketě.",
      cta: "Tréninkové systémy",
      cta2: "Vyžádat ukázku",
      photoPending: "Fotografie traineru dosud nezveřejněna",
      sstP: "Tréninková hlava 50 in² pro nácvik kontaktu ve středu, se čtyřmi hmotnostními konfiguracemi pro zatížení zvolené trenérem.",
      sstCta: "Prozkoumat Sweet Spot Trainer",
      sstCaption: "Konfigurace 300 g, jedna ze čtyř",
      methodP: "Stanovte cíle, vyberte vybavení, trénujte se zapojením trenéra, zaznamenávejte pozorování, znovu vyhodnoťte, upravte a přeneste práci do výkonnostní hry.",
      methodCta: "Prozkoumat metodiku",
      spotP: "Malý kruhový terč pro nácvik přesného a opakovatelného bodu kontaktu.",
      spotCta: "Prozkoumat Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Výroba a kontrola kvality",
      title: "Postaveno podle specifikace. Změřeno a zaznamenáno.",
      p: "Výroba se řídí písemnou specifikací každé zakázky. Záznamy odpovídají třídě přesnosti: uchovávané výrobní záznamy u P2.5, individuální záznamy a dohledatelnost u P1.5, individuální kontrola a dokumentace u P0.5 tam, kde je program dané zakázky zavádí.",
      confirmedTitle: "Potvrzeno",
      confirmed: ["Celokarbonová konstrukce od rámu až po rukojeť.", "Třídy přesnosti P2.5, P1.5 a P0.5 se čtyřmi řízenými parametry.", "Osm výrobních velikostí gripu L0–L7."],
      pendingTitle: "Dosud nezveřejněno",
      pending: "Fotografie měřicího vybavení, vzorové záznamy kontroly kvality a záběry z výroby zatím nejsou zveřejněny. Nic na této stránce není naměřeným certifikátem.",
      captions: { lettering: "Lesklý nápis MAXIMUS na matném rámu", buttcap: "Grip a koncová krytka s emblémem lva", handle: "Stříbrná personalizační gravura", finish: "Hlava a výplet" },
      cta: "Konstrukce a výroba",
    },
    world: {
      eyebrow: "Svět MAXIMUS",
      title: "Jeden klíč. Jeden ekosystém. Neomezené možnosti.",
      note: "„Neomezené možnosti“ je značkové vyjádření, nikoli slib neomezené technické realizovatelnosti, příjmu nebo přístupu. Nákup nezakládá licenční odměny, investiční výnosy, sponzorství ani financování rozvoje hráče.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — a vaše navigace ve světě tenisu: řízený profil vybavení s písemnou odpovědí." },
        personal: { h: "Personalizace", p: "Jména, iniciály, čísla a týmová identifikace ve schváleném provedení stříbrné gravury." },
        development: { h: "Rozvoj", p: "Tréninkové systémy vedené trenérem, záznamy a opakované vyhodnocení." },
        ecosystem: { h: "Rozšířený ekosystém", p: "Osobní značky, záznamy majitelů, síť, licencování a institucionální programy — každý se svým skutečným stavem." },
      },
      cta: "Prozkoumat ekosystém",
    },
    partners: {
      eyebrow: "Partnerské cesty",
      title: "Trenéři, kluby, distributoři a partneři.",
      p: "Nejprve písemná kvalifikace. Práva pro zemi, exkluzivita a komerční podmínky se sjednávají písemně — nikdy se nepřidělují prostřednictvím formuláře.",
      cta: "Všechny partnerské cesty",
      formTitle: "Krátká poptávka",
      formLead: "Vyberte účel a napište MAXIMUS. Na této stránce obdržíte číslo poptávky.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "VAŠE NAVIGACE VE SVĚTĚ TENISU" } },
    personal: { eyebrow: "Personalizace", title: "Vaše jméno. Vaše číslo. Váš MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tři série. Skutečné parametry." },
    map: { cta: "Prozkoumat ekosystém" },
  },
  racquets: {
    title: "Rakety",
    lead: "Tři výkonnostní série se společným konstrukčním standardem, společným systémem přesnosti a společnou výrobní architekturou gripů. Každá série je ustavenou výkonnostní architekturou v rámci širší konstrukční platformy.",
    direction: { control: "Kontrola", power: "Síla", spin: "Rotace" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Hlavní herní zaměření",
    compareTitle: "Srovnání sérií",
    compareLead: "Pouze potvrzená data architektury. Vzory výpletu, délky, profily rámu, rozsahy napětí a nominální hodnoty swingweightu a tuhosti nejsou pro tyto série zveřejněny; shromažďují se jako požadované cílové hodnoty pro technické posouzení.",
    columns: { series: "Série", head: "Velikost hlavy", direction: "Zaměření", weights: "Uvedené hmotnosti", range: "Rozsah hmotností", balance: "Data o vyvážení" },
    balanceModelled: "Vypočtené hodnoty",
    balanceNotProvided: "Dosud nezveřejněno",
    construction: "Konstrukce: celokarbonová, od rámu po rukojeť · Přesnost: P2.5 / P1.5 / P0.5 · Gripy: L0–L7",
    otherTitle: "Další raketové sporty",
    otherLead: "Schválené směry vývoje. V těchto kategoriích neexistují prodejné produkty a nepřenáší se na ně žádná tenisová specifikace.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Plážový tenis" },
    ctaConfigure: "Nakonfigurovat poptávku",
    ctaSeries: "Otevřít sérii",
  },
  seriesPage: {
    eyebrow: "Výkonnostní série",
    intro: {
      great: "Architektura GREAT s hlavou 97 in² je postavena na kontrole: kompaktní hlava, přesný kontakt a jistota ve směru.",
      power: "Architektura POWER s hlavou 98 in² je postavena na přenosu energie: délka a tempo ze stabilního rámu.",
      spin: "Architektura SPIN s hlavou 100 in² je postavena na chování míče: rotace, bezpečná rezerva a tvarování trajektorie.",
    },
    photoPending: "Fotografie série dosud nezveřejněna",
    detailPending: "Detailní fotografie konstrukce a rukojeti této série zatím nejsou zveřejněny.",
    specsTitle: "Specifikace a stav",
    catalogue: {
      eyebrow: "Katalog série {series}",
      title: "{n} hmotnostních variant",
      lead: "Každá varianta série {series}, seřazená podle hmotnosti. Hmotnost v gramech, vyvážení v milimetrech od konce rukojeti. Každá vizualizace je zobrazena celá: nic není ořezáno, zamaskováno ani roztaženo.",
      selectLabel: "Vyberte hmotnostní variantu",
      select: "Zobrazit tuto variantu",
      selected: "Zobrazeno výše",
      balanceLabel: "Vyvážení",
      headLabel: "Velikost hlavy",
      constructionLabel: "Konstrukce",
      gripsLabel: "Výrobní velikosti gripu",
      precisionLabel: "Třídy přesnosti",
      balanceConfirmed: "Vyvážení je potvrzenou hodnotou pro tuto hmotnost a odpovídá číslu vytištěnému na vizualizaci.",
      balanceModelled: "Vyvážení je vypočtenou hodnotou pro tuto uvedenou hmotnost, nikoli individuálním výrobním měřením; odpovídá číslu vytištěnému na vizualizaci.",
      zoom: "Otevřít obrázek",
      close: "Zavřít",
      allTitle: "Všech {n} variant",
    },
    specs: { head: "Velikost hlavy", direction: "Hlavní zaměření", weights: "Uvedené hmotnosti", range: "Rozsah hmotností", balance: "Vyvážení", construction: "Konstrukce", grips: "Výrobní gripy", precision: "Třídy přesnosti" },
    construction: "Celokarbonová, od rámu po rukojeť",
    statusTitle: "Stav hodnot",
    matrixTitle: "Úplná matice hmotností",
    matrixLead: "Uvedené hmotnosti představují standardní výběr. Jiné hmotnosti lze poptat jako vlastní cílové hodnoty; chybějící mezihodnoty se nedoplňují.",
    balanceNote: {
      confirmed: "Hodnoty vyvážení jsou potvrzeny pro každou uvedenou hmotnost (mm od konce rukojeti) a odpovídají číslu vytištěnému na vizualizaci dané hmotnosti. Nejsou zde vypočítávány ani vyhlazovány mezi sousedními hmotnostmi; základ měření se potvrzuje v písemné specifikaci.",
      modelled: "Hodnoty vyvážení jsou vypočteny pro každou uvedenou hmotnost (mm od konce rukojeti). Nejde o individuální výrobní měření; základ měření se potvrzuje v písemné specifikaci.",
      notprovided: "Hodnoty vyvážení pro tuto sérii nejsou uvedeny. Nevyvozujte je z jiné série.",
    },
    optionsTitle: "Přesnost, grip a hmotnost",
    notPublished: "Pro tuto sérii nejsou zveřejněny: vzor výpletu, délka, profil rámu, rozsah napětí a hodnoty swingweightu a tuhosti. Můžete je uvést jako požadované cílové hodnoty pro technické posouzení.",
    offerTitle: "Co se stane po vaší poptávce",
    offerSteps: [
      ["Poptávka", "Odešlete konfiguraci nebo dotaz. Číslo poptávky se zobrazí okamžitě."],
      ["Posouzení", "MAXIMUS posoudí sérii, třídu, hmotnost, grip a případné požadované cílové hodnoty."],
      ["Písemná odpověď", "Specifikace, dostupnost a komerční podmínky se potvrzují písemně."],
    ],
    faqTitle: "Dotazy",
    faq: [
      ["Jsou hodnoty vyvážení naměřené?", "Pro uvedené hmotnosti jsou vypočtené, nejde o individuální měření. Základ měření se potvrzuje v písemné specifikaci."],
      ["Mohu poptat hmotnost, která není uvedena?", "Ano, jako vlastní cílovou hodnotu v celých gramech. Prochází technickým posouzením a realizovatelnost se potvrzuje písemně."],
      ["Co mění třída přesnosti?", "Jak přísně jsou hmotnost, vyvážení, swingweight a tuhost drženy na deklarované specifikaci a jaké záznamy se vedou."],
      ["Navyšuje se grip omotávkami?", "Ne. L0–L7 jsou geometrie karbonové rukojeti z výroby."],
      ["Kde jsou ceny a dodací lhůty?", "Potvrzují se písemně ke každé poptávce a zde se nezveřejňují."],
    ],
    faqSpinBalance: ["Odkud pocházejí hodnoty vyvážení série SPIN?", "Z potvrzené tabulky série Spin: 33 hmotnostních variant s vyvážením v milimetrech od konce rukojeti. Každá dvojice odpovídá číslu vytištěnému na schválené vizualizaci dané hmotnosti. Hodnoty nejsou vypočítávány ani vyhlazovány mezi sousedními hmotnostmi."],
    ctaBuild: "Nakonfigurovat tuto sérii",
    ctaAsk: "Dotaz k této sérii",
    ctaCompare: "Porovnat všechny série",
    weightsLabel: "uvedené hmotnosti",
    headLabel: "hlava",
  },
  precision: {
    title: "Přesnost a tuhost",
    switch: { label: "Vyberte třídu přesnosti", panelLabel: "Čtyři řízené parametry —", qcLabel: "Architektura kontroly kvality", protocolNote: "podle definovaného výrobního protokolu měření kontroly kvality", fullTable: "Úplná srovnávací tabulka" },
    lead: "Čtyři parametry řízené jako jeden konstrukční systém. Každá třída určuje, jak přísně je hotová raketa držena na své deklarované specifikaci a jaké záznamy kvality vznikají.",
    statement: "Hmotnost. Vyvážení. Swingweight. Tuhost. Řízeno jako jeden konstrukční systém.",
    classes: {
      "P2.5": { name: "Škálovatelné výkonnostní jádro", qc: "Individuální měření a uchovávané výrobní záznamy." },
      "P1.5": { name: "Pokročilá přesnost", qc: "Individuální měření, individuální záznamy a dohledatelnost." },
      "P0.5": { name: "Profesionální · individuálně kontrolováno", qc: "Individuální kontrola s nominálními a skutečnými hodnotami a individuálními záznamy měření; sériová identita, dohledatelnost šarže, certifikát přesnosti a párované sady tam, kde je program dané zakázky zavádí." },
    },
    columns: { cls: "Třída", weight: "Hmotnost", balance: "Vyvážení", sw: "Swingweight", stiff: "Tuhost", qc: "Architektura kontroly kvality" },
    stiffTarget: "cílová tolerance",
    stiffExact: "odpovídá deklarované cílové hodnotě RA podle zavedeného výrobního protokolu měření",
    programmeNote: "Sériová identita, certifikáty a dokumentace párovaných sad se vydávají pouze tam, kde je program konkrétní zakázky zavádí.",
    targetsNote: "Specifikace tuhosti jsou výrobními cíli, dokud příslušný protokol a výrobní doklady neumožní silnější tvrzení. Teze o architektuře neznamená, že každá uvedená konfigurace již prošla úplným uvolňovacím procesem pro všechny čtyři parametry.",
    stiffnessTitle: "Proč je tuhost důležitá",
    stiffnessP1: "Tuhost rámu ovlivňuje, jak rám reaguje v okamžiku kontaktu, jaký má pocit a jak shodné jsou dvě rakety mezi sebou. Hlavním přínosem jejího řízení je opakovatelná odezva vůči deklarované specifikaci.",
    stiffnessP2: "Než se zveřejní ověřená shoda, interní záznam kontroly kvality uvádí přístroj, stav jeho kalibrace, metodu, stav rakety, rozlišení, nejistotu měření, opakovaná měření, pravidlo zaokrouhlení a kritérium přijetí. Shodné zobrazené celé číslo není důkazem nulové fyzické odchylky ani nulové chyby měření.",
    fields: ["Cílová hodnota", "Výsledek měření", "Povolená tolerance", "Schopnost přístroje"],
    fieldsNote: "V každém záznamu vedeno jako samostatná pole.",
    matchedTitle: "Párované sady",
    matchedP: "Kritéria párované sady se definují odděleně od individuální tolerance. Shoda každé rakety s její nominální tolerancí sama o sobě nedokazuje konkrétní maximální rozdíl mezi dvěma raketami. Párované dvojice, trojice a týmové sady se poptávají přes konfigurátor a potvrzují písemně.",
    extendedTitle: "Rozšířený technický model",
    extendedP: "Datový model podporuje další parametry. Dosud pro ně neexistují žádné hodnoty ani třídy tolerance; lze je uvést jako požadované cílové hodnoty v technickém zadání.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torzní chování", length: "Délka", beamProfile: "Profil rámu", headGeometry: "Geometrie hlavy", stringPattern: "Vzor výpletu", durability: "Trvanlivost", vibration: "Vibrační charakteristiky" },
    noZero: "MAXIMUS nepopisuje svou uvedenou řadu jako řadu s nulovou tolerancí. Přesnost v řadě se uvádí jako třída s deklarovanou tolerancí a definovanou architekturou kontroly kvality. ZERO není součástí řady.",
    zero: {
      eyebrow: "Exkluzivní možnost",
      title: "ZERO",
      sub: "Nulová tolerance v gramech.",
      p: "Tři třídy drží hotovou raketu uvnitř deklarovaného pásma. ZERO toto pásmo ruší. Raketa se staví a měří, dokud se naměřený údaj nerovná deklarovanému číslu v rozlišení výrobního přístroje, a tento údaj se vydává spolu s ní. Není součástí uvedené řady ani čtvrtou třídou: sjednává se individuálně, pro jednu raketu nebo jednu párovanou sadu, jako exkluzivní zakázková výroba. Po dohodě se stejný postup uplatňuje na vyvážení a swingweight.",
      points: [
        ["Žádné pásmo", "Deklarované číslo je výsledkem, nikoli středem tolerance."],
        ["Po jedné", "Postaveno, změřeno a zaznamenáno jako jediný kus."],
        ["Vydáno s raketou", "Naměřený údaj se předává a zůstává ve výrobním záznamu."],
        ["Potvrzeno písemně", "Parametry, rozsah a dodací lhůta se sjednávají před výrobou."],
      ],
      note: "Párováno v rozlišení výrobního měřicího přístroje. Shodné zobrazené číslo není tvrzením o nulové fyzické odchylce. Dostupnost a podmínky se sjednávají individuálně pro každou zakázku.",
      cta: "Poptat ZERO",
    },
    cta: "Konfigurovat s třídou přesnosti",
  },
  grip: {
    title: "Výrobní architektura gripů",
    statement: "Osm výrobních velikostí gripu. L0–L7.",
    lead: "Geometrie gripu je součástí architektury karbonové rukojeti. Každá velikost se vyrábí jako geometrie rukojeti, nikoli navyšováním omotávkami.",
    emph: "Rozšířené velikosti",
    p1: "Osmivelikostní výrobní řada dává trenérům a hráčům širší konfigurační rozsah, v němž lze vybavení specifikovat podle hráče, včetně větších geometrií L6 a L7.",
    p2: "Nominální označení gripu je odlišné od surových rozměrů konstrukční rukojeti i od výsledného protokolu měření. Velikosti se vztahují na výkonnostní série a na tréninkové řady této platformy.",
    p3: "Pro tuto řadu se neuplatňuje žádné tvrzení o celosvětové exkluzivitě.",
    columns: { size: "Velikost", nominal: "Nominální", family: "Platí pro" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurovat s vaší velikostí gripu",
  },
  custom: {
    title: "Individuální konstrukce",
    statement: "Vyvinuto podle specifikace.",
    sub: "Standardní řada je výchozím bodem.",
    lead: "MAXIMUS přijímá technické požadavky nad rámec zveřejněných konfiguračních matic k vyhodnocení, konstrukci, validaci a výrobě podle sjednané specifikace. Realizovatelnost se potvrzuje posouzením — ne každý myslitelný požadavek je fyzicky nebo komerčně realizovatelný.",
    scopeTitle: "Čeho se technické zadání může týkat",
    scope: ["Geometrie hlavy a rámu", "Délka", "Hmotnost", "Vyvážení", "Swingweight", "Tuhost", "Twistweight", "Geometrie gripu", "Konstrukce", "Párované sady", "Tréninkové rámy", "Design a gravura", "Identita a týmové programy", "Vývoj závislý na formách"],
    processTitle: "Postup",
    process: [
      ["Definovat", "Preferované cílové hodnoty, povinné limity, zamýšlené použití a přijatelné kompromisy."],
      ["Zkonstruovat", "Konstrukční posouzení vůči platformě a formám."],
      ["Validovat", "Validace vůči sjednané specifikaci."],
      ["Specifikovat", "Písemná specifikace se základem měření a tolerancemi."],
      ["Vyrobit", "Výroba podle specifikace."],
      ["Změřit / zaznamenat", "Měření a uchovávané záznamy podle příslušné třídy přesnosti."],
    ],
    formTitle: "Zaslat technické zadání",
    formLead: "Rozlište preferované cílové hodnoty od povinných limitů. Výsledkem je žádost o technické posouzení, nikoli automaticky přijatá výrobní zakázka.",
    protected: "Receptury laminace, formy, identita dodavatelů, interní kalkulace a chráněné know-how se touto cestou neposkytují.",
    cta: "Zaslat technické zadání",
  },
  training: {
    title: "Tréninkové systémy",
    lead: "Dvě tréninkové řady s vlastními výrobními standardy, spojené jednou metodikou: trénink vedený trenérem, záznamy, opakované vyhodnocení a přenos zpět do výkonnostní hry.",
    sst: { h: "Sweet Spot Trainer", p: "Tréninková raketa se zmenšenou hlavou 50 in² ve čtyřhmotnostním systému pro nácvik kontaktu ve středu, vnímání sweet spotu, kontrolu rakety a postupné zatěžování." },
    spot: { h: "Spot Trainer", p: "Trénink bodu kontaktu pomocí malého kruhového terče, na schváleném čtyřhmotnostním základu." },
    method: { h: "Metodika", p: "Stanovte cíle, vyberte vybavení se zapojením trenéra, používejte příslušný systém, zaznamenávejte, znovu vyhodnoťte, upravte a přeneste." },
    experience: "Vezměte ji do ruky. Rozehrajte ji. Vnímejte ji.",
    experienceP: "Vyžádejte si testování, fitting nebo ukázku s podporou trenéra. Odeslaná poptávka není potvrzeným termínem.",
    cta: "Vyžádat fitting nebo ukázku",
    distinct: "Sweet Spot Trainer, Spot Trainer a jakékoli samostatné předváděcí zařízení jsou odlišné produkty a nikdy se nesměšují.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Samostatná tréninková kategorie s vlastním výrobním standardem. Hlava 50 in² soustředí pozornost na místo kontaktu; čtyři hmotnosti zajišťují progresi zatížení.",
    baseline: "Potvrzený základ",
    columns: { head: "Hlava", length: "Délka", pattern: "Vzor výpletu", grips: "Výrobní gripy" },
    systemTitle: "Systém čtyř raket",
    detailsTitle: "Detaily konstrukce",
    systemLead: "Hmotnost a vyvážení ve stavu dodání. Základ měření se vede samostatně a dosud není zveřejněn.",
    purposeTitle: "Účel",
    purpose: ["Nácvik kontaktu ve středu", "Vnímání sweet spotu", "Kontrola rakety", "Postupné zatěžování", "Rozvoj vedený trenérem", "Přechod zpět k výkonnostní raketě hráče"],
    heavy: "Model 400 g je řízenou tréninkovou konfigurací. Není automaticky doporučován dětem, začátečníkům ani každému hráči; zatížení, délku a progresi určuje trenér.",
    precisionNote: "Výkonnostní třídy přesnosti P2.5, P1.5 a P0.5 se na tuto tréninkovou řadu automaticky nevztahují. Tolerance tréninkové výroby se řídí vlastní schválenou specifikací této řady.",
    health: "Neslibuje se žádná prevence ani léčba tenisového lokte, odstranění úrazů ani zaručené zlepšení.",
    cta: "Vyžádat ukázku Sweet Spot Traineru",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Trénink bodu kontaktu pomocí malého kruhového terče. Samostatný produkt s vlastní vizuální identitou, postavený na schváleném čtyřhmotnostním základu.",
    purposeTitle: "Potvrzený účel",
    purposeP: "Naučit hráče najít a opakovat přesný bod kontaktu.",
    weightsTitle: "Progrese hmotností",
    weightsP: "Progrese hmotností vychází ze schváleného hmotnostního základu Sweet Spot Traineru. Hodnoty vyvážení a další specifikace Sweet Spot Traineru se na Spot Trainer nepřenášejí.",
    dims: "Přesné rozměry terče dosud nejsou zveřejněny.",
    grips: "Výrobní architektura gripů L0–L7.",
    notes: ["Výkonnostní třídy přesnosti se neuplatňují automaticky.", "Nejde o miniaturu běžné rakety a nezveřejňuje se žádný vzor výpletu.", "Spot Trainer, Sweet Spot Trainer a jakékoli samostatné předváděcí zařízení zůstávají rozlišitelné."],
    cta: "Dotaz k Spot Traineru",
  },
  methodology: {
    title: "Metodika a zkušenost s produktem",
    lead: "Vybavení je jednou částí strukturované cesty rozvoje. Metoda začíná cíli hráče, nikoli označením produktu.",
    stepsTitle: "Cesta rozvoje",
    steps: [
      ["Stanovit cíle", "Cíle hráče a výchozí bod."],
      ["Vybrat vybavení", "Vhodné vybavení vybrané se zapojením trenéra."],
      ["Používat systém", "Příslušný tréninkový systém, vedený trenérem."],
      ["Zaznamenat", "Pozorování skutečné účasti, bez vymyšlených hodnocení."],
      ["Znovu vyhodnotit", "Srovnatelné kontrolní body."],
      ["Upravit", "Úpravy konfigurace nebo programu."],
      ["Přenést", "Přenesení naučeného zpět do výkonnostní hry."],
    ],
    educationTitle: "Vzdělávací cesty",
    education: { player: "Hráči — porozumění konfiguraci, zatížení a progresi.", parent: "Rodiče — kontinuita rozvoje, vhodné vybavení, záznamy a práva.", coach: "Trenéři — tréninkové systémy, fitting, hodnocení a autorizované používání programů." },
    evidenceTitle: "Disciplína dokladů",
    evidenceP: "Záznamy o skutečné účasti a pozorování se uchovávají se svou klasifikací — uvedeno účastníkem, potvrzeno zákonným zástupcem, validováno trenérem nebo změřeno systémem. Pokrok, výsledky ani validace se nikdy nevymýšlejí.",
    experienceTitle: "Vezměte ji do ruky. Rozehrajte ji. Vnímejte ji.",
    experienceP: "Lze si vyžádat testování, fitting nebo ukázku s podporou trenéra. Odeslaná poptávka není potvrzeným termínem.",
    cta: "Vyžádat fitting nebo ukázku",
    cta2: "Poptávka partnerství pro trenéry",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — řízený profil vybavení",
    title: "MAXIMUS GPS",
    lead: "Řízený profil vybavení. Odpovídejte jen na to, co je relevantní; odpovědi zkontrolujte a opravte; získáte souhrn, konfigurační směry, které se na vás vztahují, a skutečný další krok.",
    honesty: "V této verzi nejsou schválena žádná automatická pravidla fittingu. GPS proto vytváří jasný souhrn požadavků a ukazuje konfigurační směry; konkrétní parametry vybavení se směrují k odbornému posouzení.",
    rulesVersion: "Verze pravidel",
    dataVersion: "Verze produktových dat",
    steps: { role: "Role", sport: "Sport", experience: "Zkušenosti", objectives: "Cíle", style: "Herní styl", equipment: "Současné vybavení", preference: "Preference", coach: "Zapojení trenéra", ageBand: "Věková kategorie", review: "Přehled" },
    notStored: "V tomto prohlížeči se neukládá.",
    ageNote: "Používá se pouze ke směrování poptávky. Nevyžaduje se jméno, datum narození ani zdravotní informace.",
    q: {
      role: "Co vás nejlépe popisuje?",
      sport: "Jaký sport?",
      experience: "Úroveň zkušeností",
      objectives: "Co je nejdůležitější? (vyberte až tři)",
      style: "Herní styl, pokud ho znáte",
      equipment: "Současné vybavení, pokud nějaké máte",
      equipmentHint: "Značka a model, hmotnost nebo grip, pokud je znáte. Nepovinné.",
      preference: "Preferovaná konfigurace nebo známá velikost gripu",
      grip: "Známá velikost gripu",
      coach: "Podílí se trenér na rozhodnutích o vašem vybavení?",
      ageBand: "Věková kategorie hráče (slouží pouze ke správnému směrování poptávky)",
    },
    roles: { player: "Hráč", parent: "Rodič nebo zákonný zástupce", coach: "Trenér", club: "Klub nebo akademie", other: "Jiné" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Jiný raketový sport" },
    sportNote: "Produkty existují pro tenis. Ostatní sporty jsou směry vývoje; váš zájem zaznamenáváme pro příslušný program.",
    experience: { beginner: "Začátečník", developing: "Rozvíjející se", intermediate: "Středně pokročilý", advanced: "Pokročilý", competitive: "Soutěžní", professional: "Profesionální" },
    objectives: { control: "Kontrola", power: "Síla", spin: "Rotace", comfort: "Komfort", manoeuvrability: "Ovladatelnost", development: "Dlouhodobý rozvoj", competition: "Soutěže", training: "Tréninkový systém", team: "Tým nebo párovaná sada", personal: "Personalizace" },
    styles: { baseline: "Od základní čáry", allcourt: "Univerzální", attacking: "Útočný", defensive: "Obranný", coach: "Určuje trenér", unknown: "Nevím" },
    ageBands: { u10: "Do 10 let", u14: "10–13", u18: "14–17", adult: "18 a více let" },
    output: {
      title: "Váš profil vybavení",
      status: "Vyžaduje odborné posouzení",
      statusP: "V této verzi se nevytváří žádné automatické přiřazení. Váš profil byl shrnut pro odborné posouzení.",
      directionsTitle: "Konfigurační směry, které se uplatní",
      directionsP: "Na základě vašich uvedených cílů a deklarovaného herního zaměření každé série. Jde o směr, nikoli o doporučení fittingu.",
      trainingHint: "Mezi vašimi cíli je tréninkový systém: podívejte se na Sweet Spot Trainer a Spot Trainer.",
      teamHint: "Párované sady se poptávají přes konfigurátor a potvrzují písemně.",
      next1: "Odeslat profil k odbornému posouzení",
      show: "Zobrazit můj profil",
      configure: "Konfigurovat",
      sendP: "Odešlete svůj profil MAXIMUS k odbornému posouzení. Číslo poptávky se zobrazí okamžitě; odpověď přijde písemně.",
      otherSport: "Rakety MAXIMUS existují pro tenis. Pro ostatní raketové sporty se nenavrhuje žádná tenisová série; váš zájem zaznamenáváme jako směr vývoje.",
      noDirection: "Vaše cíle neukazují na jedno herní zaměření. Konfiguraci navrhne odborné posouzení.",
      incomplete: "Některé povinné odpovědi chybí — doplňte je přes „Upravit odpovědi“.",
    },
    privacy: "GPS se neptá na žádné zdravotní informace ani na identifikační údaje dětí. V této relaci prohlížeče se uchovávají pouze odpovědi s výběrem z možností; volný text se neukládá.",
  },
  build: {
    title: "Postavte si vlastní",
    lead: "Nakonfigurujte poptávku: série, třída přesnosti, uvedená hmotnost nebo vlastní cílová hodnota, velikost gripu, požadované cílové hodnoty, personalizace, párované sady a množství. Výsledkem je konfigurační poptávka s číslem — nikoli SKU, cena, datum dodání nebo certifikát.",
    steps: { series: "Série", cls: "Třída přesnosti", weight: "Hmotnost", grip: "Velikost gripu", targets: "Cílové hodnoty", personal: "Personalizace", set: "Sada a množství", use: "Použití", review: "Přehled" },
    q: {
      series: "Vyberte sérii",
      cls: "Vyberte třídu přesnosti",
      weightMode: "Hmotnost",
      listed: "Uvedená hmotnost",
      customWeight: "Požadovaná hmotnost (g)",
      balanceShown: "Vypočtené vyvážení pro tuto hmotnost",
      balanceRequest: "Požadované vyvážení (mm)",
      grip: "Výrobní velikost gripu",
      targetsTitle: "Požadované cílové hodnoty",
      swingweight: "Požadovaný swingweight (kg·cm²)",
      stiffness: "Požadovaná tuhost (RA)",
      basis: "Základ měření požadovaných hodnot",
      engraving: "Text gravury",
      engravingHint: "Jméno, iniciály nebo číslo. Latinská písmena, číslice, mezera, spojovník, apostrof a tečka; až 24 znaků. Jiná písma přijímáme s potvrzením grafického návrhu.",
      engravingType: "Personalizace",
      types: { none: "Žádná", name: "Jméno hráče", initials: "Iniciály", number: "Číslo sady", academy: "Označení trenéra nebo akademie", team: "Týmový program" },
      set: "Jednotlivá raketa nebo párovaná sada",
      use: "Zamýšlené použití",
      uses: { play: "Vlastní hra", competition: "Soutěže", coaching: "Trénování", team: "Tým nebo akademie", retail: "Posouzení pro prodej nebo distribuci", other: "Jiné" },
      notes: "Další technické požadavky",
    },
    classes: { "P2.5": "P2.5 — škálovatelné výkonnostní jádro", "P1.5": "P1.5 — pokročilá přesnost", "P0.5": "P0.5 — profesionální, individuálně kontrolováno" },
    stiffExactShort: "tuhost odpovídá deklarované cílové hodnotě RA podle zavedeného výrobního protokolu",
    clsNote: "Každá třída řídí čtyři parametry. P0.5 je úzká tolerance podle definovaného protokolu měření — nikoli nulová chyba. Sériová identita, certifikáty a dokumentace párovaných sad se uplatňují pouze tam, kde je program vaší zakázky zavádí.",
    listedNote: "Z potvrzené matice série.",
    customNote: "Hmotnost mimo matici, posuzovaná technicky.",
    balanceCaption: "U každé uvedené hmotnosti se zobrazuje vypočtené vyvážení v mm od konce rukojeti. Vypočtené hodnoty nejsou individuálními měřeními.",
    spinNote: "Hmotnosti SPIN tvoří požadovanou hmotnostní architekturu. Vyvážení, swingweight a tuhost pro SPIN nejsou uvedeny; definují se v technickém posouzení.",
    customHint: "Celé gramy, pouze číslice. Vlastní hmotnost je žádostí o technické posouzení; realizovatelnost se potvrzuje písemně a žádná hodnota se nezaokrouhluje.",
    gripNote: "geometrie karbonové rukojeti z výroby, nikoli navinutí omotávek",
    targetsLead: "Nepovinné. Zadejte pouze hodnoty, které potřebujete. Každá se zaznamenává jako požadovaná cílová hodnota pro technické posouzení, nikoli jako zveřejněná specifikace.",
    basisHint: "Povinné, pokud požadujete vlastní hmotnost nebo jakoukoli cílovou hodnotu: vztahují se hodnoty k raketě bez výpletu, nebo s výpletem?",
    inputRange: "Přijímaný vstup: {min}–{max}.",
    inputRangeNote: "Rozsahy vstupu pouze odfiltrují nemožná zadání. Nepopisují výrobní možnosti.",
    listedBasis: "uvedené hodnoty — základ měření se potvrzuje v písemné specifikaci",
    notStored: "V tomto prohlížeči se neukládá; po načtení stránky jej zadejte znovu.",
    artworkReview: "vyžaduje potvrzení grafického návrhu",
    previewNote: "Vizuální náhled se nezobrazuje: schválená šablona gravury pro tento model dosud není zveřejněna. Váš text shromažďujeme pro potvrzení grafického návrhu.",
    teamSub: "4–99 raket na sadu",
    setsLabel: { individual: "Počet raket", pair: "Počet párovaných dvojic", triple: "Počet párovaných trojic", team: "Počet týmových sad" },
    teamSizeLabel: "Raket na týmovou sadu",
    totalLabel: "Raket celkem",
    racquetsUnit: "raket",
    setRule: "Množství se počítá v sadách: párovaná dvojice jsou 2 rakety na sadu, párovaná trojice 3.",
    restart: "Začít novou konfiguraci",
    notices: { weightCleared: "{w} g není v matici série {series}, proto byla hmotnost zrušena. Vyberte uvedenou hmotnost nebo poptejte vlastní cílovou hodnotu." },
    reviewTitle: "Konfigurační poptávka",
    reviewP: "Zkontrolujte konfiguraci a poté doplňte kontaktní údaje. Poptávka se uloží s číslem a odpovídáme na ni písemně; dostupnost a komerční podmínky se potvrzují písemně.",
    reviewErrors: "Některé odpovědi v konfiguraci vyžadují pozornost:",
    edit: "Upravit",
    fieldNames: { series: "Série", cls: "Třída přesnosti", mode: "Výběr hmotnosti", weight: "Uvedená hmotnost", customWeight: "Požadovaná hmotnost", basis: "Základ měření", balanceReq: "Požadované vyvážení", sw: "Požadovaný swingweight", ra: "Požadovaná tuhost", grip: "Velikost gripu", ptype: "Personalizace", engraving: "Text gravury", setType: "Typ sady", sets: "Množství", teamSize: "Raket na týmovou sadu", use: "Zamýšlené použití", notes: "Další požadavky" },
    status: { listed: "uvedená hmotnost", requestedArchitecture: "požadovaná hmotnostní architektura", technicalReview: "žádost o technické posouzení", notPublished: "neuvedeno", requestedCondition: "požadovaný stav" },
    chooseLink: "Nejste si jisti, která série se hodí? Nechte si pomoci s výběrem",
    cta: "Odeslat konfigurační poptávku",
  },
  experience: {
    title: "Vyzkoušení a nastavení",
    statement: "Vezměte ji do ruky. Rozehrajte ji. Vnímejte ji.",
    lead: "Vyžádejte si testování, fitting nebo ukázku s podporou trenéra. Poptávky posuzujeme a odpovídáme na ně písemně; odeslaná poptávka není potvrzeným termínem.",
    optionsTitle: "Co si lze vyžádat",
    options: ["Testování rakety", "Individuální fitting", "Ukázka s podporou trenéra", "Ukázka Sweet Spot Traineru nebo Spot Traineru", "Předváděcí den pro tým nebo akademii"],
    formTitle: "Poptávka fittingu nebo ukázky",
  },
  engineering: {
    title: "Konstrukce a výroba",
    statement: "Letadla. Jachty. Rakety.",
    lead: "Jedna konstrukční filozofie ve třech prostředích: principy, které formují letadlo, přesnost, která vede jachtu otevřeným mořem, a výkon, který definuje každou raketu MAXIMUS. Jde o konstrukční vyprávění — nikoli o tvrzení o letecké certifikaci, vlastnictví jachet, vlastnictví výrobního závodu nebo přímém přenosu materiálů.",
    manifesto: ["Věříme, že skvělá konstrukce nemá hranice.", "Jedna filozofie. Vyvinuto bez kompromisů."],
    capabilityTitle: "Výrobní schopnosti",
    capabilityLead: "Schopnosti ukazujeme jako posloupnost, nikoli jako slogan.",
    sequence: [
      ["Specifikace", "Série, třída přesnosti, hmotnost, vyvážení, swingweight, cílová tuhost, geometrie gripu, personalizace."],
      ["Výroba", "Celokarbonová konstrukce od rámu po rukojeť, vyrobená podle specifikace."],
      ["Kontrola kvality", "Měření a záznamy podle třídy přesnosti: výrobní záznamy, individuální záznamy a dohledatelnost, individuální certifikace."],
      ["Opakovaná výroba", "Opakovatelná odezva vůči deklarované specifikaci napříč šaržemi."],
      ["Dohledatelnost", "Sériová identita, dohledatelnost šarže a certifikát přesnosti tam, kde je třída poskytuje."],
    ],
    capacityNote: "Výrobní kapacita, dodací lhůty, minimální objemy a plány dodávek se potvrzují písemně pro každý program na základě potvrzených zakázek a sjednaného harmonogramu uvolňování.",
    truth: "Kapacita není výstup, zásoba, zaručené datum dodání ani vlastnictví výrobního závodu.",
    cta: "Distribuce a rozvoj zemí",
    cta2: "Zaslat technické zadání",
  },
  ecosystem: {
    title: "Ekosystém MAXIMUS",
    lead: "Jeden klíč. Toto je, co odemyká. Každý prvek má vysvětlení, přesný stav a odpovídající další krok.",
    words: ["Konstrukce", "Výkon", "Inovace", "Komunita", "Příležitost", "Smysl"],
    nodes: {
      engineering: { h: "Konstrukce a výroba raket", p: "Celokarbonové rakety vyvinuté podle specifikace, vyrobené se záznamy kvality a dohledatelností.", a: "Konstrukce a výroba" },
      precision: { h: "Přesnost a individuální konfigurace", p: "Čtyři parametry, tři třídy přesnosti, osm velikostí gripu a individuální konstrukce.", a: "Přesnost a tuhost" },
      training: { h: "Trénink a metodika", p: "Sweet Spot Trainer, Spot Trainer a strukturovaná cesta rozvoje.", a: "Tréninkové systémy" },
      development: { h: "Rozvoj hráčů a trenérů", p: "Výběr vedený trenérem, záznamy, opakované vyhodnocení a vzdělávací cesty.", a: "Metodika" },
      identity: { h: "Osobní identita a osobní značky", p: "Od gravury až po osobní nebo profesionální značku s vypořádanými právy.", a: "Osobní značky" },
      owners: { h: "Záznamy majitelů, znalosti a práva", p: "Navrhovaný trezor majitele s řízeným přístupem pro záznamy o vybavení, rozvoji a právech.", a: "Majitelé a trezor" },
      mipa: { h: "MIPA — původ a interní kontrola", p: "Interní vrstva pro duševní vlastnictví, původ a kontrolu dokumentů.", a: "Právní identita a kontrola" },
      digital: { h: "Digitální infrastruktura a směr Blockchain 5.0", p: "Původ, dohledatelné záznamy, doklady s řízeným přístupem a identita produktu jako deklarovaný technologický směr.", a: "Technologický směr" },
      licensing: { h: "Smluvní licencování a programy licenčních odměn", p: "Licencované značky, produkty a balíčky práv s podmínkami definovanými v každé smlouvě.", a: "Licenční cesty" },
      families: { h: "Zapojení rodiny a výhody programu", p: "Informovaná rozhodnutí, kontinuita, uchované záznamy a výhody definované programem.", a: "Rodiny a rodiče" },
      network: { h: "MAXIMUS Sports Network", p: "Hráči, trenéři, kluby, akademie, poskytovatelé služeb, operátoři a regionální partneři.", a: "Sports Network" },
      market: { h: "Kluby, akademie, distribuce a rozvoj zemí", p: "Týmové programy, prodej, distribuce a rozvoj území prostřednictvím písemné kvalifikace.", a: "Partnerské cesty" },
      institutional: { h: "Institucionální programy, vzdělávání, inovace a společenský dopad", p: "Institucionální vrstvu poskytuje MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, kde program tuto roli zakládá.", a: "Institucionální programy" },
      extensions: { h: "Budoucí rozšíření na raketové sporty a textil MAXIMUS", p: "Padel, pickleball, squash, badminton, racquetball, plážový tenis a textil jako směry vývoje.", a: "Raketové sporty" },
    },
    boundaryTitle: "Hranice",
    boundary: [
      "Nákup rakety nezakládá institucionální členství, práva na správu, licenční odměny ani investiční práva.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) je institucionálním operátorem pouze tam, kde program tuto roli zakládá; prodej vybavení uvádí svůj skutečný smluvní subjekt.",
      "Granty, status neziskové organizace, daňový režim a regulatorní povolení se mezi zeměmi neuplatňují automaticky.",
    ],
    techTitle: "Technologický směr",
    techP: "Blockchain 5.0 je deklarovaným technologickým směrem MAXIMUS. Jeho funkčními účely jsou původ, dohledatelné záznamy, doklady s řízeným přístupem, identita produktu a vypořádání kvalifikovaných komerčních událostí. Nepředstavuje se žádný konsenzuální mechanismus, transakční kapacita, síť uzlů, adresa smart kontraktu, token ani nezávislá certifikace a netvrdí se žádné nasazené řešení. Osobní informace, záznamy o dětech a důvěrné smlouvy se standardně nikdy neukládají do veřejného neměnného systému.",
  },
  brands: {
    title: "Osobní značky a ambasadoři",
    statement: "Od hráče ke značce. Od trenéra ke značce.",
    lead: "Samostatná cesta pro osobní značku. Zapojení MAXIMUS zahrnuje rozvoj značky a sjednanou propagaci — nejen jméno na raketě.",
    progressionTitle: "Zamýšlený postup",
    progression: [
      ["Ověřená identita", "Ověřená identita a historie rozvoje."],
      ["Rozlišitelná značka", "Rozlišitelná osobní nebo profesionální značka."],
      ["Obsah s vypořádanými právy", "Obsah s vypořádanými právy a schválená identita produktu."],
      ["Konstrukce a kolekce", "Konstrukce a rozvoj kolekcí tam, kde je to sjednáno."],
      ["Propagace", "Propagace prostřednictvím sjednaných kanálů a partnerství MAXIMUS."],
      ["Účast", "Smluvní účast na kvalifikovaných prodejích nebo licencování."],
      ["Vykazování", "Transparentní vykazování podle smlouvy."],
    ],
    royaltiesTitle: "Licenční odměny a licencování",
    royalties: [
      "Licenční odměny se vztahují k definované licencované značce, produktu, transakci nebo balíčku práv.",
      "„Celosvětové prodeje“ znamenají kvalifikované prodeje v rozsahu smlouvy — nikdy každou nesouvisející raketu MAXIMUS.",
      "Sazby, základ výpočtu, území, doba trvání, vratky, odpočty, vykazování, vypořádání a ověřování se definují v příslušné smlouvě. Nezveřejňuje se žádná výchozí procentní sazba.",
      "Bez sjednaného rozsahu se neslibuje žádná globální kampaň, mediální rozpočet, sponzorský výsledek ani komerční úspěch.",
    ],
    cta: "Zaslat poptávku spolupráce na značce",
    cta2: "Poptávka partnerství pro trenéry",
  },
  families: {
    title: "Rodiny a rodiče",
    lead: "Informovaná rozhodnutí o vybavení, kontinuita rozvoje, uchované znalosti a práva, přehled o účasti a výhody definované programem, které mohou podpořit budoucí činnost.",
    nowTitle: "Dostupné nyní",
    now: ["Rodinné a rozvojové poptávky písemně.", "Výběr vybavení se zapojením trenéra, poptávky fittingu a ukázek.", "Soukromé záznamy: profily dětí se nikdy nezveřejňují a standardně se nijak komerčně nevyužívají.", "Vzdělávací cesta pro rodiče: konfigurace, zatížení, progrese, záznamy a práva."],
    plannedTitle: "Plánováno",
    planned: ["Výhody účasti definované programem, využitelné na zboží a služby v rámci ekosystému, nikoli hotovostní úrok.", "Záznamy majitele a rodiny v navrhovaném trezoru majitele s oprávněními zákonných zástupců a převodem kontroly v 18 letech."],
    categoriesTitle: "Vedeno odděleně",
    categories: ["Smluvní licenční odměny vyplývající z licencovaných práv nebo kvalifikovaných prodejů", "Výhody účasti definované programem", "Kredity na nákup nebo služby", "Předplatby", "Institucionální členství"],
    categoriesP: "Tyto kategorie se nikdy nepovažují za vzájemně zaměnitelné.",
    statusTitle: "Skutečný stav rodinného programu",
    journeyTitle: "Cesta pro rodiny",
    journey: [
      ["Cíl", "Čeho chce hráč dosáhnout jako dalšího."],
      ["Současná úroveň", "Kde se hráč nachází dnes."],
      ["Trenér", "Zda se trenér podílí na rozhodnutích o vybavení."],
      ["Vybavení", "Vhodné vybavení pro danou fázi, včetně tréninkových systémů, pokud jsou relevantní."],
      ["Sjednaný trénink", "Používání vedené trenérem, sjednané předem."],
      ["Kontrola", "Opakované vyhodnocení ve srovnatelných kontrolních bodech."],
    ],
    brief: {
      who: "Rodiče a zákonní zástupci hráčů v jakékoli fázi.",
      value: "Písemná odpověď k vhodnému vybavení, zapojení trenéra a dalšímu kroku v rozvoji.",
      now: "Rodinné poptávky písemně; výběr se zapojením trenéra; soukromé záznamy — profily dětí se nikdy nezveřejňují.",
      next: "Odešlete rodinnou poptávku níže. Číslo poptávky obdržíte okamžitě.",
    },
    formTitle: "Rodinná poptávka",
    formNote: "Vyplňuje rodič nebo zákonný zástupce. Neuvádějte jméno dítěte, datum narození, školu ani zdravotní informace.",
    noPromise: "Nákup neslibuje licenční odměny, investiční výnosy, sponzorství ani financování rozvoje dítěte.",
    statusP: "Tato verze vysvětluje model a přijímá poptávky k programu. Načítání, výplaty a uplatnění nejsou dostupné, dokud nebudou písemně definovány kvalifikované události, příjemci, zdroj financování, základ výpočtu, povolená použití, účetní zacházení, vratky, zrušení, expirace, přenositelnost, ukončení programu a řešení sporů. Neslibuje se žádný zůstatek, který nikdy nepoklesne, žádná účast nehradí celý trénink a nevyplývá z ní žádná ochrana kapitálu.",
    cta: "Odeslat rodinnou nebo rozvojovou poptávku",
  },
  owners: {
    title: "Majitelé a trezor majitele",
    lead: "Trezor majitele je navrhovaným záznamem s řízeným přístupem pro vybavení, rozvoj, znalosti, obsah a dokumentovaná práva. Prezentuje se jako součást plánované architektury pro majitele: nezobrazují se žádné živé účty, zůstatky, certifikáty ani úspěchy.",
    nowTitle: "Pro současné majitele nyní",
    now: ["Poptávky majitelů: produktová nebo sériová reference, nastavení, servis a žádosti o záznamy písemně.", "Certifikát přesnosti a dokumentace párované sady tam, kde je třída přesnosti poskytuje, dodávané s produktem."],
    archTitle: "Plánovaná architektura trezoru",
    arch: ["Identita produktu a sériové reference", "Konfigurace a příslušné certifikáty kontroly kvality", "Historie servisu a nastavení", "Záznamy o rozvoji hráče nebo trenéra", "Kvalifikace a ověřené úspěchy", "Média s vypořádanými právy a autorské materiály", "Licence, oprávnění a odkazy na smlouvy", "Záznamy programu osobní značky", "Příslušné výkazy licenčních odměn nebo výhod účasti"],
    separationTitle: "Co vlastnictví znamená",
    separation: [
      "Vlastnictví fyzické rakety je odlišné od vlastnictví autorského práva, licence, smluvního nároku nebo záznamu, který tyto věci popisuje.",
      "Uložený dokument nebo záznam v blockchainu není automaticky důkazem, že právo existuje nebo že bylo převedeno.",
      "Doklady si uchovávají svou klasifikaci: uvedeno účastníkem, potvrzeno zákonným zástupcem, validováno trenérem, změřeno systémem.",
      "U nezletilých: soukromé záznamy, oprávnění zákonných zástupců, žádné zveřejněné profily dětí a standardně žádné komerční využití identity.",
      "Export, oprava, řízení přístupu a odpovídající převod kontroly jsou součástí návrhu.",
    ],
    techTitle: "Blockchain 5.0 a MxSN",
    techP: "Blockchain 5.0 je deklarovaným technologickým směrem; MxSN definuje koncepty sítě s řízeným přístupem pro souhlas, doručení, doklady, práva a vykazování. Provozní nasazení se nepředstavuje. Datový model aplikace je postaven tak, aby se později integroval přes dokumentované rozhraní, bez předstírání, že spojení dnes existuje.",
    cta: "Poptávka majitele",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Spojení mezi hráči, trenéry, kluby, akademiemi, poskytovateli služeb, operátory programů a regionálními partnery.",
    functionsTitle: "Možné funkce",
    functions: ["Vyhledávání", "Představení", "Rozvojové programy", "Podpora vybavení", "Akce", "Přístup ke službám", "Partnerské příležitosti"],
    statusTitle: "Skutečný stav",
    statusP: "Žádný veřejný katalog zatím není zveřejněn: uvedeni budou pouze účastníci, u nichž je ustavena identita, vztah a souhlas s uvedením. Návrh zaslaný klubu není partnerstvím a potenciální distributor není jmenovaným distributorem. Zveřejnění katalogu, rezervace, zasílání zpráv a komerční transakce se řídí samostatně a nejsou v provozu.",
    cta: "Přihlásit se do sítě",
  },
  partnerships: {
    title: "Partnerské cesty",
    lead: "Nejprve písemná kvalifikace. Každá cesta vede k poptávce podle role; komerční podmínky následují písemně.",
    commercialTitle: "Možné komerční činnosti platformy",
    commercial: ["Vybavení", "Individuální konstrukce", "Personalizace", "Týmové a akademické programy", "Tréninkové systémy", "Smluvní licencování", "Distribuce", "Schválené služby", "Budoucí produktové kategorie"],
    boundary: "Práva pro zemi, exkluzivita, poplatky za území a marže distributorů jsou vyjednávané podmínky. Nezveřejňují se žádné výnosy, prognózy, ocenění, podíly na trhu, návratnosti, závazky financování ani nejmenovaná partnerství.",
    routes: {
      coaches: {
        title: "Trenéři",
        lead: "Tréninkové systémy, fitting, profesionální identita, autorizované programy, příležitosti osobní značky a dodávky vybavení.",
        points: ["Sweet Spot Trainer a Spot Trainer v tréninku vedeném trenérem.", "Fitting s konfiguračními maticemi a osmi výrobními velikostmi gripu.", "Coach-to-Brand: ověřený profesionální profil a dílčí značka s vypořádanými právy.", "Autorizované používání programů se řídí písemnou smlouvou."],
        cta: "Zaslat poptávku partnerství pro trenéry",
        brief: {
          who: "Nezávislí trenéři a trenérské týmy.",
          value: "Tréninkové systémy pro trénink vedený trenérem, fitting s maticemi sérií a osmi výrobními gripy a cesta k profesionální identitě.",
          now: "Poptávky trenérů písemně. Nezveřejňuje se ani neimplikuje žádná provize, výdělek nebo sazba za doporučení.",
          next: "Odešlete poptávku trenéra níže. Podmínky následují písemně.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Kluby a akademie",
        lead: "Týmové vybavení, tréninkové systémy, personalizace, rozvojové programy, servis a účast v síti.",
        points: ["Týmové a párované sady poptávané přes konfigurátor.", "Tréninkové systémy a metodika pro strukturovaný rozvoj.", "Personalizace pro týmové programy ve schválených zónách.", "Předváděcí dny, individuální fitting a účast v síti."],
        cta: "Zaslat zadání klubu nebo akademie",
        brief: {
          who: "Kluby, akademie a týmové programy.",
          value: "Týmové a párované sady, tréninkové systémy, personalizace pro týmové programy a předváděcí dny.",
          now: "Zadání klubů a akademií písemně; týmové sady se poptávají přes konfigurátor.",
          next: "Odešlete zadání klubu nebo akademie níže.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribuce a rozvoj zemí",
        lead: "Sortiment, koordinace výroby, technické schopnosti, rozvoj území a důvěrná komerční kvalifikace.",
        points: ["Písemná kvalifikace protistrany, území a kanálu.", "Sortiment definovaný z konfiguračních matic a tříd přesnosti.", "Území, exkluzivita, objemy, ceny a komerční ochrana jsou vyjednávané podmínky sjednané písemně.", "Smluvní subjekt, platební podmínky a dodací podmínky se určují u každé transakce."],
        cta: "Zaslat poptávku distribuce nebo rozvoje země",
        brief: {
          who: "Prodejci, distributoři a partneři pro jednotlivé země.",
          value: "Sortiment definovaný z potvrzených matic, tříd přesnosti a řady gripů, s písemnou kvalifikací území a kanálu.",
          now: "Poptávky distribuce písemně. Území, exkluzivita, objemy a ceny se vyjednávají — nic z toho se nepřiděluje prostřednictvím formuláře.",
          next: "Odešlete poptávku distribuce níže.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategická spolupráce a investice",
        lead: "Konstrukční schopnosti, hloubka konfigurace, výrobní model, cesty na trh, duševní vlastnictví, služby a příležitosti expanze.",
        points: ["Kvalifikovaná strategická diskuse nebo řízený přístup k informacím následuje po písemné kvalifikaci.", "Veřejné informace se omezují na schválené specifikace produktů, konfigurační architekturu, ověřené schopnosti a vysvětlení programů.", "Ekonomika konkrétního kupujícího, kalkulace, chráněná metodika a nezveřejněné smlouvy se poskytují pouze na základě NDA nebo smlouvy."],
        cta: "Vyžádat kvalifikovanou strategickou diskusi",
        brief: {
          who: "Investoři a strategičtí partneři.",
          value: "Kvalifikovaná diskuse o konstrukčních schopnostech, hloubce konfigurace, výrobním modelu, cestách na trh a duševním vlastnictví.",
          now: "Nezveřejňují se žádná finanční čísla, prognózy, ocenění ani návratnosti. Řízené informace následují po písemné kvalifikaci a NDA.",
          next: "Vyžádejte kvalifikovanou strategickou diskusi níže.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institucionální programy",
        lead: "Vzdělávání, přístup, inovace, doklady o rozvoji, společenský dopad a vhodně strukturované programy.",
        points: ["Institucionální programy se strukturují prostřednictvím MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, kde program tuto roli zakládá.", "Vázané programové prostředky a komerční transakce zůstávají oddělené.", "Poptávka není přijatou žádostí o členství a kupující vybavení není institucionálním členem.", "Granty, status neziskové organizace, daňový režim a regulatorní povolení jsou specifické pro každou zemi a nikdy se nepředpokládají."],
        cta: "Zaslat poptávku institucionálního programu",
        brief: {
          who: "Instituce, vzdělávací a rozvojové programy.",
          value: "Programy pro vzdělávání, přístup, inovace a doklady o rozvoji, strukturované s vhodným operátorem.",
          now: "Institucionální poptávky písemně. Poptávka není žádostí o členství; nákup vybavení není institucionálním členstvím.",
          next: "Odešlete institucionální poptávku níže.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Veřejné a řízené poskytování informací",
    disclosure: {
      public: { h: "Veřejné", p: "Schválené specifikace produktů, konstrukce, konfigurační architektura, účely tréninku, ověřené schopnosti, vysvětlení programů a partnerské cesty." },
      qualified: { h: "Kvalifikovaná poptávka", p: "Technické požadavky, objemy, zájem o území, rozsah rozvoje a související komerční diskuse." },
      controlled: { h: "Řízeno NDA nebo smlouvou", p: "Interní receptury, podrobné protokoly kontroly kvality, laminace, formy, výrobní metody, identita dodavatelů, kalkulace, ekonomika konkrétního kupujícího, chráněná metodika, nezveřejněné smlouvy a citlivé záznamy o právech." },
    },
  },
  contact: {
    title: "Kontakt a poptávky",
    lead: "Vyberte účel své poptávky. Každý formulář shromažďuje pouze to, co je potřeba k jejímu nasměrování a vyhodnocení. Na poptávky odpovídáme písemně.",
    email: "E-mail",
    instagram: "Instagram",
    legalLink: "Právní identita",
  },
  form: {
    purposeLabel: "Účel poptávky",
    purposes: {
      selection: "Pomoc s výběrem rakety",
      product: "Dotaz k produktu",
      fitting: "Fitting nebo ukázka",
      technical: "Technické zadání",
      config: "Konfigurační poptávka",
      gps: "Profil vybavení GPS",
      coach: "Partnerství pro trenéry",
      club: "Zadání klubu nebo akademie",
      distribution: "Distribuce nebo rozvoj země",
      brand: "Spolupráce na značce nebo ambasador",
      family: "Rodinná nebo rozvojová poptávka",
      institutional: "Institucionální program",
      strategic: "Strategická nebo investiční diskuse",
      owner: "Poptávka majitele",
      network: "Přihláška do Sports Network",
      general: "Obecný dotaz",
    },
    fields: {
      name: "Jméno",
      email: "E-mail",
      role: "Vaše role",
      country: "Země nebo region",
      organisation: "Organizace",
      message: "Vaše zpráva",
      level: "Současná úroveň",
      objectives: "Co je nejdůležitější (až tři)",
      currentRacquet: "Současná raketa",
      grip: "Velikost gripu, pokud ji znáte",
      seriesInterest: "Série, o kterou máte zájem",
      quantity: "Množství",
      city: "Město nebo místo pro schůzku",
      coachInvolved: "Podílí se trenér?",
      timing: "Preferovaný termín",
      targets: "Preferované cílové hodnoty",
      limits: "Povinné limity",
      use: "Zamýšlené použití",
      tradeoffs: "Přijatelné kompromisy",
      basis: "Základ měření",
      players: "Počet hráčů",
      interests: "Oblasti zájmu",
      territory: "Území, o které máte zájem",
      channels: "Existující kanály a zkušenosti",
      audience: "Publikum nebo disciplína",
      proposal: "Navrhovaná spolupráce",
      goal: "Cíl rozvoje",
      ageBand: "Věková kategorie hráče",
      scope: "Rozsah programu",
      interestArea: "Oblast zájmu",
      productRef: "Produktová nebo sériová reference",
      requestType: "Typ poptávky",
      seeking: "Co hledáte",
      consent: "Souhlasím s tím, že MAXIMUS může tyto údaje uchovávat a použít k odpovědi na tuto poptávku. Nejde o marketingový odběr.",
    },
    roles: { player: "Hráč", parent: "Rodič nebo zákonný zástupce", coach: "Trenér", club: "Klub nebo akademie", retailer: "Prodejce", distributor: "Distributor", brand: "Značka nebo ambasador", investor: "Investor nebo strategický partner", institution: "Instituce", other: "Jiné" },
    interestOptions: { training: "Tréninkové systémy", fitting: "Fitting rakety", identity: "Profesionální identita", programmes: "Autorizované programy", brand: "Osobní značka", supply: "Dodávky vybavení", team: "Týmové vybavení", personalisation: "Personalizace", development: "Rozvojové programy", service: "Servis", network: "Účast v síti" },
    ownerTypes: { setup: "Nastavení a konfigurace", service: "Servis", records: "Záznamy a certifikáty", other: "Jiné" },
    strategicAreas: { engineering: "Konstrukční schopnosti", configuration: "Hloubka konfigurace", manufacturing: "Výrobní model", routes: "Cesty na trh", ip: "Duševní vlastnictví a služby", expansion: "Příležitosti expanze" },
    errors: {
      required: "Toto pole je povinné.",
      too_long: "Tento údaj je příliš dlouhý.",
      too_short: "Tento údaj je příliš krátký.",
      invalid_email: "Zadejte platnou e-mailovou adresu, například jmeno@example.com.",
      invalid_choice: "Vyberte jednu z možností.",
      not_number: "Zadejte celé číslo pouze číslicemi.",
      out_of_range: "Tato hodnota je mimo přijímaný rozsah.",
      not_in_matrix: "Tato hmotnost není v uvedené matici vybrané série.",
      decimal_not_supported: "Zadejte celé číslo bez desetinných míst.",
      too_many: "Vyberte nejvýše tři možnosti.",
      consent_required: "Souhlas je nutný, aby MAXIMUS mohl na tuto poptávku odpovědět.",
      invalid: "Tento údaj není platný.",
    },
  },
  legal: {
    title: "Právní identita a kontrola",
    lead: "Veřejnou značkou je MAXIMUS / MAXIMUS GPS. Právní provozní identity jsou rozlišitelné a jsou zde uvedeny.",
    entities: {
      institutional: { role: "Vrstva institucionálních programů", p: "Poskytuje vrstvu institucionálních programů tam, kde program tuto roli zakládá. Není komerčním prodejcem raket. Nezisková zapsaná organizace v Dubai International Financial Centre." },
      equipment: { role: "Komerční subjekt pro vybavení", p: "Komerční subjekt pro vybavení zajišťující dodávky, distribuci a smluvní komerční plnění tam, kde tuto roli zakládají aktuální provozní dokumenty. Smluvní strana každé transakce je uvedena v dokumentech dané transakce." },
      ip: { role: "Duševní vlastnictví, značka a komerční koordinace", p: "Vystupuje v ustavené roli pro duševní vlastnictví, značku nebo komerční koordinaci. Nepřiřazuje se žádná nepotvrzená smluvní odpovědnost." },
      stewardship: { role: "Referenční správa", p: "House of Maximus je referenční správou ekosystému tam, kde to příslušný zdroj podporuje." },
      control: { role: "Interní duševní vlastnictví, původ a kontrola dokumentů", p: "MIPA je interní vrstvou pro duševní vlastnictví, původ a kontrolu dokumentů. Interní záznam MIPA je odlišný od vnější registrace ochranné známky, patentu či autorského práva i od soudního uznání a nepředstavuje schválení vizuálu." },
    },
    labels: { licence: "Licence", registration: "Registrace", vat: "VAT TRN", address: "Adresa", email: "E-mail", jurisdiction: "Jurisdikce" },
    boundaryTitle: "Hranice",
    boundary: [
      "Nákup automaticky nezakládá institucionální členství, práva na správu, licenční odměny ani investiční práva.",
      "Institucionální role je oddělena od komerčních transakcí s vybavením.",
      "Ochrana osobních údajů, podmínky programů a ujednání o řízeném přístupu odpovídají skutečně uvolněným funkcím.",
      "Na každého návštěvníka, prodej nebo zahraniční program se neuplatňuje žádné paušální určení rozhodného práva; smluvní základ se stanovuje v každé smlouvě.",
    ],
  },
  privacy: {
    title: "Ochrana osobních údajů",
    updated: "Verze 2026-09-21 · webové stránky 4.2",
    contactTitle: "Kontakt pro dotazy k ochraně osobních údajů",
    sections: {
      collect: ["Co se shromažďuje", "Při odeslání formuláře: údaje, které zadáte (jméno, e-mail, role, země nebo region, organizace, pokud ji uvedete, vaše zpráva a odpovědi ve formuláři), stránka a kampaňové parametry vaší návštěvy (vstupní stránka, jazyk, parametry utm; identifikátory reklamních kliknutí pouze tehdy, pokud jste povolili analytiku) a čas odeslání. Vaše IP adresa se používá pouze v hašované a krátkodobé podobě k omezení zneužití a neukládá se spolu s vaší poptávkou."],
      purpose: ["Proč", "Abychom odpověděli na vaši poptávku, připravili nabídku nebo specifikaci, o kterou jste požádali, a vedli záznam o poptávce. Na základě formuláře se nezasílají žádné marketingové zprávy."],
      storageOn: ["Kde se poptávky ukládají", "Poptávky se ukládají v databázi společnosti Upstash, Inc. (Redis), poskytované prostřednictvím hostingové platformy Vercel Inc."],
      notifyEmail: ["Oznámení o nové poptávce", "Po přijetí poptávky se oznámení obsahující údaje, které jste odeslali, zasílá e-mailem do odpovědné poštovní schránky MAXIMUS."],
      notifyTelegram: ["Oznámení o nové poptávce", "Po přijetí poptávky se oznámení obsahující údaje, které jste odeslali, zasílá odpovědné osobě v MAXIMUS přes Telegram (Telegram FZ-LLC, Dubaj), který toto oznámení při přenosu zpracovává."],
      notifyWebhook: ["Oznámení o nové poptávce", "Po přijetí poptávky se oznámení obsahující údaje, které jste odeslali, zasílá na interní koncový bod MAXIMUS podepsaným a šifrovaným spojením."],
      notifyNone: ["Oznámení o nové poptávce", "Oznamování nových poptávek se právě nastavuje. Vaše poptávka se ukládá a MAXIMUS ji čte z interního registru; nic se za tímto účelem nezasílá třetí straně."],
      storageOff: ["Kde se poptávky ukládají", "Ukládání poptávek se právě nastavuje. Dokud není aktivní, formuláře uvádějí, že poptávku nelze přijmout; nic se neukládá. Webové stránky hostuje Vercel Inc."],
      browser: ["Úložiště prohlížeče", "Úložiště relace uchovává odpovědi s výběrem z možností z GPS a konfigurátoru a kampaňové parametry vaší návštěvy po dobu této relace prohlížeče. Kontaktní údaje, volný text, text gravury a informace o dětech se v prohlížeči neukládají."],
      analyticsOn: ["Analytika", "S vaším souhlasem měří Google Analytics 4 návštěvy a události formulářů bez kontaktních údajů a bez textu poptávky. Vaše volba se uchovává v lokálním úložišti a lze ji kdykoli změnit v „Nastavení analytiky“ v zápatí. Formuláře fungují i bez analytiky."],
      analyticsOff: ["Analytika", "Na těchto webových stránkách není aktivní žádný analytický nástroj."],
      retention: ["Doba uchování", "Zatím není nastaveno žádné automatické mazání. O smazání své poptávky můžete kdykoli požádat."],
      children: ["Děti", "Formuláře musí vyplnit dospělá osoba. Poptávky týkající se hráčů do 18 let podává rodič nebo zákonný zástupce. Neodesílejte jméno dítěte, datum narození, školu ani zdravotní informace. Profily dětí se nikdy nezveřejňují."],
      rights: ["Vaše práva", "Pro přístup ke své poptávce, její opravu nebo smazání napište na gps@maximus.tennis a uveďte číslo poptávky."],
      controlled: ["Řízené informace", "Důvěrné dokumenty se na těchto webových stránkách neukládají ani z nich nejsou poskytovány. Řízené poskytování probíhá na základě NDA nebo smlouvy samostatnými kanály."],
    },
  },
  terms: {
    title: "Podmínky použití",
    copyright: "Autorské právo k těmto webovým stránkám — k jejich textům, fotografiím, designu a kódu — patří výhradně Maximusu Kiriyakulovovi. Nebylo převedeno na žádnou společnost ani na žádnou jinou osobu.",
    updated: "Verze 2026-09-21",
    sections: [
      ["Informace, nikoli nabídka", "Informace o produktech na těchto webových stránkách popisují schválené specifikace, konfigurační architekturu a vysvětlení programů. Nejsou nabídkou k prodeji, cenníkem, prohlášením o zásobách ani závazkem dodání. Komerční podmínky se sjednávají samostatně písemně se smluvním subjektem uvedeným u každé transakce."],
      ["Poptávky", "Poptávka odeslaná prostřednictvím těchto webových stránek — včetně profilů GPS, konfiguračních poptávek a technických zadání — se ukládá s číslem poptávky a posuzuje. Není přijatou zakázkou, výrobním závazkem, potvrzeným termínem, žádostí o členství ani přijatou přihláškou do jakéhokoli programu."],
      ["Specifikace a doklady", "Vypočtené hodnoty, výrobní cíle a potvrzené specifikace jsou na příslušných stránkách rozlišeny. Hodnoty tuhosti jsou výrobními cíli, dokud není zveřejněno jinak. Žádný výsledek pro konkrétního hráče není zaručen."],
      ["Ekosystém, členství a práva", "Nákup rakety nezakládá institucionální členství, investiční práva, vlastnictví duševního vlastnictví, nárok na licenční odměny ani výhody účasti. Nároky se řídí zveřejněnými podmínkami programu nebo písemnou smlouvou."],
      ["Duševní vlastnictví", "MAXIMUS®, emblém lva, značka GPS a obsah těchto webových stránek jsou chráněny. Interní konstrukční receptury, protokoly kontroly kvality, laminace, formy, identita dodavatelů, kalkulace a chráněná metodika se zde neposkytují."],
    ],
  },
  lead: {
    submit: "Odeslat poptávku",
    submitting: "Odesílá se…",
    retry: "Zkusit znovu",
    acceptedEyebrow: "Poptávka přijata",
    acceptedTitle: "Vaši poptávku jsme obdrželi.",
    requestId: "Číslo poptávky",
    acceptedNext: "MAXIMUS posuzuje každou poptávku a odpovídá písemně na e-mailovou adresu, kterou jste uvedli. Číslo poptávky si uschovejte pro další komunikaci.",
    duplicate: "Tato poptávka již byla přijata; duplikát nebyl vytvořen.",
    another: "Začít novou poptávku",
    errorsTitle: "Zkontrolujte prosím tato pole:",
    failTitle: "Vaše poptávka nebyla odeslána.",
    fail: {
      offline: "Vaše zařízení je offline.",
      network: "Spojení se serverem se nezdařilo.",
      timeout: "Server neodpověděl v daném čase.",
      rate_limited: "Z této sítě přišlo příliš mnoho požadavků. Zkuste to prosím za několik minut.",
      too_fast: "Formulář byl odeslán velmi rychle. Zkontrolujte jej prosím a odešlete znovu.",
      spam_suspected: "Poptávku zastavil spamový filtr.",
      unavailable: "Poptávky nelze v tuto chvíli přijímat.",
      default: "Došlo k neočekávané chybě.",
    },
    keepNote: "Vaše zadání zůstává na této stránce, takže to můžete zkusit znovu.",
    sendByEmail: "Odeslat tuto poptávku e-mailem",
    sendByEmailNote: "Otevře se vaše e-mailová aplikace s textem této poptávky. MAXIMUS ji obdrží, až e-mail odešlete.",
    mailConfig: "Konfigurace",
    mailPage: "Stránka",
    fallback: "Pokud problém trvá, napište na {email}. Poptávka se považuje za odeslanou pouze tehdy, když se zobrazí její číslo.",
    privacyLink: "Zásady ochrany osobních údajů",
    hpLabel: "Toto pole nechte prázdné",
    consentShort: "Souhlas",
    after: "Po odeslání se na této stránce zobrazí číslo poptávky. Poptávky posuzujeme a odpovídáme na ně písemně; poptávka není zakázkou.",
    basis: { unstrung: "Bez výpletu", strung: "S výpletem", unknown: "Nevím — bude sjednáno ve specifikaci" },
    hints: {
      email: "MAXIMUS odpovídá písemně na tuto adresu.",
      goal: "Například: první soutěžní raketa nebo přechod z juniorské rakety. Neuvádějte jména, data narození ani zdravotní informace o dítěti.",
      currentRacquet: "Značka a model, pokud je znáte.",
      message: "Neuvádějte hesla, platební údaje ani zdravotní informace.",
    },
  },
  choose: {
    eyebrow: "Pomoc s výběrem",
    title: "Pomozte mi vybrat raketu",
    lead: "Napište MAXIMUS svou úroveň a to, co je pro vás nejdůležitější. Vaše odpovědi posoudíme a obdržíte písemný návrh: série, třída přesnosti, hmotnost a grip.",
    stepsTitle: "Co bude dál",
    steps: [
      ["Vaše odpovědi", "Úroveň, priority a velikost gripu, pokud ji znáte."],
      ["Odborné posouzení", "MAXIMUS porovná vaše odpovědi s maticemi sérií."],
      ["Písemný návrh", "Navrhovaná konfigurace a další krok, písemně."],
    ],
    formTitle: "Vaše odpovědi",
    submit: "Vyžádat pomoc s výběrem",
    altTitle: "Chcete se rozhodnout sami?",
    altGps: "Podrobný profil GPS",
    altBuild: "Konfigurovat přímo",
    note: "Žádný automatický fitting a žádné tvrzení o přesnosti: každou poptávku posuzuje člověk.",
  },
  consent: {
    title: "Analytika",
    text: "Může MAXIMUS měřit návštěvy pomocí Google Analytics? Formuláře fungují v obou případech; do analytiky se nezasílají žádné kontaktní údaje ani text poptávky.",
    allow: "Povolit analytiku",
    decline: "Odmítnout",
  },
  familyPlan: {
    title: "Rodinný plán",
    metaDescription: "Spočítejte tenisový rozpočet své rodiny: tréninky, hodiny, kontakty s míčem a cenu jednoho tréninku, jedné hodiny a jednoho úderu — z vlastních čísel, ve třech scénářích.",
    eyebrow: "Rodinný plán · Přispějte spolu s námi",
    heroTitle: "Kolik stojí tenis vaši rodinu — a co za to získáte?",
    heroLead: "Spočítejte si rodinný rozpočet, tréninky a hodiny, které z něj zaplatíte, odhadovaný počet kontaktů s míčem a cenu jednoho tréninku, jedné hodiny a jednoho úderu — podle vlastních podmínek.",
    heroCta: "Spočítat svůj rodinný plán",
    strategy: {
      eyebrow: "Náš cíl",
      title: "Více tenisu. Více příležitostí. Společně.",
      p1: "Naším cílem je zdesetinásobit světový tenisový trh — rozšířením účasti a tím, že cestu k tenisu učiníme srozumitelnější a dostupnější. MAXIMUS usiluje o vedoucí postavení prostřednictvím řízení, metodiky, kvality, výsledků a popularizace hry.",
      p2: "Ostatní výrobce tenisového vybavení a jejich značky vnímáme jako potenciální partnery. Navrhujeme spojit silné stránky firem, trenérů, klubů a rodin ve společném programu, který bude tenis rozvíjet, propagovat a rozšiřovat ke vzájemnému prospěchu.",
      p3: "MAXIMUS je pátým prvkem tohoto přístupu: sjednocující rolí, která pomáhá samostatným silám spolupracovat. Našimi společnými výzvami jsou nemoci, nedostatek pohybu u dětí a překážky, které lidem brání začít hrát a ve hře pokračovat.",
      p4: "Pro rodinu začíná všechno jasným přehledem. Rodinný plán ukazuje rozpočet, počet tréninků a hodin, odhadovaný objem kontaktů s míčem a náklady na trénink. Změňte podmínky a vyberte scénář, který vám vyhovuje.",
      note: "Desetinásobný růst je strategický cíl, který si MAXIMUS stanovil, nikoli již dosažený výsledek. Kalkulačka zobrazuje výpočty scénářů a neslibuje žádnou úsporu, žádný zdravotní účinek ani žádný sportovní výsledek.",
      ctaCalc: "Spočítat svůj rodinný plán",
      ctaPartner: "Projednat společný rozvoj tenisu",
    },
    beyond: {
      eyebrow: "Mimo kurt",
      title: "Co plán buduje kromě tréninku",
      admission: {
        h: "Přijetí na přední školy a univerzity",
        p: "MAXIMUS podporuje rodinu na cestě na přední školy a univerzity po celém světě: při budování sportovního životopisu hráče, přípravě dokumentů a přihlášek a výběru programů, v nichž jde sport ruku v ruce se studiem. Pokud je uděleno sportovní stipendium, snižuje částku, kterou rodina za vzdělání platí.",
      },
      assets: {
        h: "Digitální aktiva: jméno, podoba a sportovní historie hráče",
        p: "Jméno, podoba, výsledky, obsah a osobní značka hráče jsou aktiva, která mohou časem získat významnou finanční i prestižní hodnotu. MAXIMUS pomáhá tato aktiva vytvářet, registrovat a chránit, aby jejich hodnota zůstala hráči a jeho rodině.",
      },
      note: "Ani jedno není součástí kalkulačky. Hodnota místa ve škole, stipendia nebo digitálního aktiva závisí na konkrétním případu a zde se neodhaduje.",
      cta: "Zeptat se na podporu při přijetí a na digitální aktiva",
    },
    steps: ["Údaje rodiny", "Ekonomika tréninku", "Dlouhodobý plán", "Konečný výpočet"],
    stepsLabel: "Kroky kalkulačky",
    scenarios: { now: "Současnost", planned: "Plán", wish: "Přání" },
    scenarioHints: { now: "Co vaše rodina dělá dnes.", planned: "Co máte v úmyslu dělat dál.", wish: "Co byste chtěli dělat." },
    currency: {
      label: "Měna",
      note: "Všechny zadané částky jsou v této měně. Nic se nepřepočítává.",
    },
    fields: {
      players: { label: "Hrající členové rodiny", hint: "Celé číslo." },
      cost: { label: "Cena jednoho tréninku pro jednoho hráče", hint: "Celá částka bez desetinných míst, včetně daní a poplatků." },
      sessions: { label: "Tréninky na hráče za měsíc", hint: "Celé číslo." },
      minutes: { label: "Délka jednoho tréninku v minutách", hint: "Celý čas včetně přestávek. Desetinná čísla jsou povolena." },
      contacts: { label: "Kontakty s míčem na hráče za trénink", hint: "Kontakt je dotek míče vlastní raketou hráče. Jedna výměna není jeden kontakt. Ve všech scénářích počítejte stejně." },
    },
    presetsLabel: "Rychlá volba, minuty",
    ages: {
      title: "Délka plánu",
      start: "Počáteční věk",
      end: "Konečný věk",
      hint: "Anonymní předpoklad, jak dlouho plán poběží, používaný pouze pro dlouhodobou tabulku. Nejde o datum narození ani o doporučený věk, kdy začít.",
    },
    extras: {
      title: "Další náklady rodiny",
      note: "Tyto částky platí pro celou rodinu a pro všechny tři scénáře. Nenásobí se počtem hráčů a nezapočítávají se do ceny hodiny ani kontaktu.",
      equipment: "První vybavení — jedna částka za celé období",
      clothing: "Oblečení a obuv — jedna částka za celé období",
      renewal: "Obnova vybavení — jedna částka za celé období, automaticky se neopakuje",
      court: "Kurt nebo klub — měsíčně, celá rodina",
      travel: "Cestování a akce — měsíčně, celá rodina",
      quoteSource: "Odkud ceny pocházejí (nepovinné)",
      quoteDate: "Ceny ke dni (nepovinné)",
      quoteNote: "Zobrazuje se přesně tak, jak jste to zadali. MAXIMUS tyto ceny neověřuje.",
    },
    storage: {
      save: "Uložit plán v tomto zařízení",
      clear: "Smazat plán z tohoto zařízení",
      saved: "Plán je uložen v tomto zařízení. Nic nebylo nikam odesláno.",
      cleared: "Plán je smazán. Kalkulačka se vrátila k výchozím hodnotám.",
      restored: "Váš plán uložený v tomto zařízení byl obnoven.",
      invalid: "Plán uložený v tomto zařízení se nepodařilo načíst, a proto nebyl použit. Můžete začít nový výpočet.",
      unavailable: "Tento prohlížeč neumožňuje ukládání v zařízení.",
    },
    annual: {
      title: "Jeden rok, scénáře vedle sebe",
      sessions: "Tréninky hráčů za rok",
      cost: "Výdaje rodiny na tréninky za rok",
      hours: "Hodiny tréninku hráčů za rok",
      length: "Délka jednoho tréninku",
      contacts: "Kontakty s míčem za rok",
      note: "Tréninky a hodiny tréninku hráčů jsou součtem za všechny hráče. Nejde o hodiny pronájmu kurtu ani o počet skupinových setkání: dva hráči, kteří spolu trénují 90 minut, představují 2 tréninky hráčů a 3 hodiny tréninku hráčů.",
    },
    economics: {
      title: "Cena tréninku, hodiny a kontaktu",
      session: "Jeden trénink jednoho hráče",
      hour: "Jedna hodina tréninku jednoho hráče",
      contact: "Jeden kontakt s míčem",
      undefinedContacts: "Neurčeno: 0 kontaktů",
      undefinedMinutes: "Neurčeno: 0 minut",
      below: "méně než {value}",
      note: "Do těchto hodnot vstupuje pouze cena tréninku. Další náklady rodiny se počtem kontaktů nedělí.",
      caption: "Počet kontaktů se počítá z vybraného objemu tréninků a z předpokladů modelu. Skutečný průběh tréninku závisí na jeho formě, přestávkách a podmínkách. Cena kontaktu je rozpočtový ukazatel, nikoli měřítko kvality trenérské práce.",
    },
    longTerm: {
      title: "Dlouhodobý plán výdajů",
      horizon: "Horizont",
      activeYears: "Aktivní roky",
      years: "{n}letý",
      note: "Počet aktivních let je omezen rozdílem mezi počátečním a konečným věkem. Ceny, četnost, inflace, sezóny, zmeškané tréninky a směnné kurzy se považují za neměnné. Další náklady nejsou součástí této tabulky.",
    },
    final: {
      title: "Konečný výpočet",
      scenario: "Scénář",
      months: "Období v měsících",
      heading: "{scenario} · {months} měs.",
      total: "Celkem za období",
      training: "Tréninky",
      extras: "Další náklady",
      oneOff: "Jednorázové položky",
      monthly: "Měsíční položky × měsíce",
      sessions: "Tréninky hráčů za období",
      hours: "Hodiny tréninku hráčů za období",
      contacts: "Kontakty s míčem za období",
      formulaTitle: "Jak se to počítá",
      formula: "Celkem = hráči × tréninky za měsíc × měsíce × cena tréninku + jednorázové náklady + měsíce × měsíční další náklady.",
      formulaNote: "Další náklady se zadávají za celou rodinu. Jednorázové položky se započítávají jednou, i pro období 0 měsíců.",
      inputs: "Vaše zadání",
    },
    units: { min: "min", h: "h", approx: "≈" },
    errors: {
      title: "Opravte tato pole, aby se zobrazil výsledek",
      required: "Povinné — zadejte číslo; hodnota 0 je povolena.",
      negative: "Hodnota nemůže být záporná.",
      integer: "Pouze celé číslo.",
      number: "Zadejte číslo.",
      tooLarge: "Toto číslo je pro výpočet příliš velké.",
      endBeforeStart: "Konečný věk nemůže být nižší než počáteční věk.",
      tooLong: "Nejvýše 200 znaků.",
      date: "Zadejte platné datum.",
      currency: "Vyberte měnu.",
      scenario: "Vyberte scénář.",
      result: "Výsledek je příliš velký na spolehlivé zobrazení. Snižte zadané hodnoty.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: celá kompozice — trainer zpředu a z profilu, gravírovaný lev v kruhovém poli na kruhové kontaktní hlavě, gravura MAXIMUS a SPOT TRAINER po délce krčku a osmihranná koncová krytka s emblémem lva",
    greatHero: "Série MAXIMUS GREAT, 369 g: celá kompozice s červeným a žlutým detailem hlavy, lesklým nápisem MAXIMUS, podpisem Maximus na krčku a koncovou krytkou se lvem",
    spotDetail: "Dva kusy MAXIMUS Spot Trainer zblízka: gravírovaný lev na matně černé kontaktní hlavě, žebrovaná omotávka gripu a osmihranné koncové krytky s emblémem lva",
    spotPair: "Dva kusy MAXIMUS Spot Trainer položené šikmo na tmavé ploše, na jednom krčku gravura MAXIMUS a na druhém SPOT TRAINER, s kruhovým polem se lvem na každé kontaktní hlavě",
    spinVisual: "MAXIMUS SPIN: hlava s výpletem, lesklý nápis MAXIMUS, grip a koncová krytka se lvem",
    powerVisual: "MAXIMUS POWER: hlava s výpletem, lesklý nápis MAXIMUS, personalizační gravura, grip a koncová krytka se lvem",
    greatVisual: "MAXIMUS GREAT: hlava s výpletem, lesklý nápis MAXIMUS, personalizační gravura, grip, koncová krytka se lvem a označení série G na srdci rakety",
    spinHead: "Hlava a výplet MAXIMUS SPIN",
    handleLion: "Srdce rakety, grip a koncová krytka MAXIMUS s emblémem lva",
    engraving: "Stříbrná personalizační gravura na krčku",
    lettering: "Lesklý černý nápis MAXIMUS na matně černém rámu",
    variantAlt: "Série MAXIMUS {series} — {w} g, vyvážení {b} mm: úplná vizualizace se specifikačním pásem, zónou personalizační gravury a označením MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, systém čtyř raket",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Krčky Sweet Spot Trainer s nápisem MAXIMUS",
    sstGrips: "Gripy a koncové krytky Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, čtyři koncové krytky s emblémem lva",
    note: "Produktová vizualizace",
  },
  notFound: { title: "Stránka nenalezena", p: "Stránka, kterou jste požadovali, v tomto jazyce neexistuje.", cta: "Přejít na domovskou stránku" },
};

export default cs;
