/* English master dictionary — MAXIMUS website v4.0. Numerical product data lives in data/products.js. */
const en = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — fully carbon tennis racquets engineered to specification",
    defaultDescription:
      "Fully carbon tennis racquets from frame to handle: GREAT 97 in², POWER 98 in² and SPIN 100 in², eight factory grip sizes L0–L7, precision classes for weight, balance, swingweight and stiffness, and custom engineering on request.",
  },
  common: {
    statuses: {
      current: "Current",
      agreement: "Available by agreement",
      development: "In development",
      concept: "Concept",
      target: "Manufacturing target",
      modelled: "Calculated",
      confirmed: "Confirmed",
      requested: "Requested architecture",
      notprovided: "Not provided",
    },
    brief: { who: "Who it is for", value: "What you get", now: "Confirmed now", next: "Next step" },
    labels: {
      next: "Next",
      back: "Back",
      edit: "Edit answers",
      review: "Review",
      start: "Start",
      restart: "Start again",
      copy: "Copy request text",
      copied: "Copied",
      openEmail: "Open email to send this request",
      reference: "Request reference",
      weight: "Weight",
      balance: "Balance",
      swingweight: "Swingweight",
      stiffness: "Stiffness",
      grip: "Grip size",
      headSize: "Head size",
      series: "Series",
      precisionClass: "Precision class",
      quantity: "Quantity",
      notProvided: "Not yet published",
      requestTarget: "Requested target",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Read more",
      allSeries: "All series",
      points: "listed weights",
      optional: "optional",
      required: "required",
      select: "Select",
      yes: "Yes",
      no: "No",
      unknown: "Not sure",
      custom: "Custom target",
      listed: "Listed weight",
      individual: "Individual racquet",
      pair: "Matched pair",
      triple: "Matched triple",
      team: "Team set",
      summaryTitle: "Your request summary",
      nextAction: "Next action",
      status: "Status",
      learn: "Learn more",
      schematic: "Schematic — not a measurement",
      photo: "Photograph",
    },
    ecosystemStrip: "The MAXIMUS ecosystem",
    truth: {
      noPrices: "Prices, minimum quantities, lead times, warranties and delivery commitments are confirmed in writing per market and per programme.",
      requestNotOrder: "A request is a review request. It is not an accepted order, a manufacturing commitment or a confirmed appointment.",
      noGuarantee: "No outcome for a specific player is guaranteed by any equipment, method or programme described here.",
    },
  },
  nav: {
    groups: { racquets: "Racquets", training: "Training", ecosystem: "Ecosystem", partnerships: "Partnerships" },
    racquets: "Racquet series and comparison",
    great: "GREAT — 97 in² · Control",
    power: "POWER — 98 in² · Power",
    spin: "SPIN — 100 in² · Spin",
    precision: "Precision and stiffness",
    grip: "Factory grip architecture L0–L7",
    custom: "Custom engineering",
    training: "Training systems",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Methodology",
    gps: "MAXIMUS GPS",
    build: "Build yours",
    choose: "Find your racquet",
    ecosystem: "Ecosystem map",
    engineering: "Engineering and manufacturing",
    experience: "Experience and fitting",
    brands: "Personal brands and ambassadors",
    families: "Families and parents",
    owners: "Owners and the owner vault",
    network: "Sports Network",
    partnerships: "All partnership routes",
    coaches: "Coaches",
    clubs: "Clubs and academies",
    distribution: "Distribution and country development",
    strategic: "Strategic and investment",
    institutional: "Institutional programmes",
    contact: "Contact",
    legal: "Legal identity",
    privacy: "Privacy",
    terms: "Terms",
    menu: "Menu",
    close: "Close",
    home: "Home",
    skip: "Skip to content",
  },
  footer: {
    line: "MAXIMUS racquet is your key to the MAXIMUS world.",
    product: "Product",
    ecosystem: "Ecosystem",
    company: "Organisation",
    instagram: "Instagram",
    email: "Email",
    analytics: "Analytics settings",
    rights: "MAXIMUS® and the lion emblem are marks of the MAXIMUS ecosystem. MIPA internal IP, provenance and document control.",
    boundary:
      "Commercial and contractual terms are agreed separately in writing. A racquet purchase does not create institutional membership, investment rights, ownership of intellectual property or an entitlement to royalties.",
  },
  home: {
    heroEyebrow: "MAXIMUS GPS · GREAT POWER & SPIN",
    heroTitle: "MAXIMUS racquet is your key to the MAXIMUS world.",
    heroProduct: "Fully carbon racquets with factory grips L0–L7, configured to your requirements.",
    heroCta1: "Find your racquet",
    heroCta2: "View the series",
    heroCaption: "MAXIMUS POWER · 98 in² · unstrung frame",
    heroMeta: [
      ["Fully carbon", "from frame to handle"],
      ["4 parameters", "weight · balance · swingweight · stiffness"],
      ["8 grip sizes", "factory geometry L0–L7"],
      ["3 series", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Start here",
      title: "Choose your path",
      items: {
        player: { h: "Player", p: "Find a racquet by level and priorities, or configure one directly.", a: "Find your racquet" },
        parent: { h: "Parent", p: "A written route for development goals, coach involvement and suitable equipment.", a: "Family route" },
        coach: { h: "Coach, club or academy", p: "Training systems, fitting, team sets and personalisation.", a: "Coach and club routes" },
        partner: { h: "Distributor or partner", p: "Distribution, country development, strategic and institutional routes.", a: "Partnership routes" },
      },
    },
    series: {
      eyebrow: "Performance series",
      title: "Three performance architectures. One engineering platform.",
      lead: "Choose the series by playing direction, then complete the configuration: precision class, weight, grip, personalisation.",
      cta: "Compare the series",
      configure: "Configure",
      open: "Open series",
      photoPending: "Photograph not yet published",
      photoLabel: { great: "GREAT · head and V-throat geometry", power: "POWER · full frame, unstrung" },
    },
    precision: {
      eyebrow: "MAXIMUS Precision System",
      title: "Weight. Balance. Swingweight. Stiffness.",
      sub: "Controlled as one engineering system.",
      lead: "Three precision classes define how tightly each finished racquet is held to its declared specification. P0.5 is a tight tolerance under a defined measurement protocol — not zero error.",
      cta: "Precision and stiffness in detail",
    },
    stiffness: {
      eyebrow: "Stiffness",
      title: "Repeatable frame response against a declared target.",
      p: "Frame stiffness shapes response, feel and consistency between racquets. MAXIMUS treats it as the fourth controlled parameter: the target, the measured result, the permitted tolerance and the instrument capability are kept as separate records. The benefit is repeatability — not a guaranteed result for every player.",
      cols: [["Response", "How the frame returns energy at contact."], ["Feel", "What the player senses at contact."], ["Consistency", "Racquets built to the same specification respond alike within their class."]],
      schematicCaption: "Schematic: permitted deviation around a declared stiffness target for each class. Not a measurement; no RA value is implied.",
      bands: { p25: "target tolerance ±1 RA", p15: "target tolerance ±0.5 RA", p05: "conforms to the declared target RA under the factory measurement protocol — not zero error", target: "declared target (no value implied)" },
    },
    carbon: {
      eyebrow: "Construction standard",
      title: "Fully carbon. From frame to handle.",
      p: "All current MAXIMUS racquets on this platform are fully carbon in their structure, including the handle. Foam is not used to form the handle.",
      gripTitle: "Eight factory grip sizes. L0–L7.",
      gripP: "Each size is factory carbon handle geometry — not an overgrip build-up.",
      scaleCaption: "Schematic: nominal grip designations L0–L7 (4″ to 4⅞″). Not measured handle dimensions.",
      cta: "Factory grip architecture",
    },
    custom: {
      eyebrow: "Custom engineering",
      title: "Engineered to specification.",
      sub: "The standard range is the starting point.",
      p: "MAXIMUS accepts technical requirements beyond the published matrices for evaluation, engineering, validation and manufacture to an agreed specification. Feasibility is confirmed in writing.",
      chain: ["Define", "Engineer", "Validate", "Specify", "Produce", "Measure / record"],
      cta: "Submit a technical brief",
      cta2: "Discuss custom engineering",
    },
    training: {
      eyebrow: "Training systems",
      title: "Hold it. Swing it. Feel it.",
      p: "Sweet Spot Trainer and Spot Trainer connect equipment with coach-led practice: centred contact, control, progressive load and the transition back to the performance racquet.",
      cta: "Training systems",
      cta2: "Request a demonstration",
      photoPending: "Trainer photograph not yet published",
    },
    manufacturing: {
      eyebrow: "Manufacturing and quality control",
      title: "Built to a specification. Measured and recorded.",
      p: "Production follows the written specification of each order. Records follow the precision class: retained production records for P2.5, individual records and traceability for P1.5, individual control and documentation for P0.5 where the programme for the order implements them.",
      confirmedTitle: "Confirmed",
      confirmed: ["Fully carbon construction from frame to handle.", "Precision classes P2.5, P1.5 and P0.5 with four controlled parameters.", "Eight factory grip sizes L0–L7."],
      pendingTitle: "Not yet published",
      pending: "Photographs of measurement equipment, sample QC records and factory footage are not published yet. Nothing on this page is a measured certificate.",
      captions: { lettering: "Gloss black MAXIMUS lettering on a matte black frame", buttcap: "Lion emblem on the butt cap", handle: "POWER throat-to-handle transition", finish: "Finish reference — frames not identified by series" },
      cta: "Engineering and manufacturing",
    },
    world: {
      eyebrow: "The MAXIMUS world",
      title: "One key. One ecosystem. Unlimited opportunities.",
      note: "“Unlimited opportunities” is a brand expression, not a promise of unlimited technical feasibility, income or access. A purchase does not create royalties, investment returns, sponsorship or funding of a player's development.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — and your navigation in the world of tennis: a guided equipment profile answered in writing." },
        personal: { h: "Personalisation", p: "Names, initials, numbers and team identification in the approved silver engraving treatment." },
        development: { h: "Development", p: "Coach-led training systems, records and reassessment." },
        ecosystem: { h: "Extended ecosystem", p: "Personal brands, owner records, network, licensing and institutional programmes — each shown with its actual status." },
      },
      cta: "Explore the ecosystem",
    },
    partners: {
      eyebrow: "Partnership routes",
      title: "Coaches, clubs, distributors and partners.",
      p: "Written qualification first. Country rights, exclusivity and commercial terms are negotiated in writing — never granted through a form.",
      cta: "All partnership routes",
      formTitle: "Short enquiry",
      formLead: "Choose the purpose and write to MAXIMUS. You receive a request ID on this page.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "YOUR NAVIGATION IN THE WORLD OF TENNIS" } },
    personal: { eyebrow: "Personalisation", title: "Your name. Your number. Your MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Three series. Real parameters." },
    map: { cta: "Explore the ecosystem" },
  },
  racquets: {
    title: "Racquets",
    lead: "Three performance series with a shared construction standard, a shared precision system and a shared factory grip architecture. Each series is an established performance architecture within a wider engineering platform.",
    direction: { control: "Control", power: "Power", spin: "Spin" },
    directionLabel: "Primary playing direction",
    compareTitle: "Series comparison",
    compareLead: "Confirmed architecture data only. String patterns, lengths, beam profiles, tension ranges, swingweight and stiffness nominal values for these series are not published; they are collected as requested targets for technical review.",
    columns: { series: "Series", head: "Head size", direction: "Direction", weights: "Listed weights", range: "Weight range", balance: "Balance data" },
    balanceModelled: "Calculated values",
    balanceNotProvided: "Not yet published",
    construction: "Construction: fully carbon, frame to handle · Precision: P2.5 / P1.5 / P0.5 · Grips: L0–L7",
    otherTitle: "Other racquet sports",
    otherLead: "Approved development directions. No saleable products exist in these categories and no tennis specification is transferred to them.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Beach tennis" },
    ctaConfigure: "Configure a request",
    ctaSeries: "Open series",
  },
  seriesPage: {
    eyebrow: "Performance series",
    intro: {
      great: "The 97 in² GREAT architecture is built around control: a compact head, precise contact and directional confidence.",
      power: "The 98 in² POWER architecture is built around energy transfer: depth and pace from a stable frame.",
      spin: "The 100 in² SPIN architecture is built around ball behaviour: rotation, margin and trajectory shaping.",
    },
    photoPending: "Series photograph not yet published",
    detailPending: "Construction and handle detail photographs for this series are not yet published.",
    specsTitle: "Specification and status",
    specs: { head: "Head size", direction: "Primary direction", weights: "Listed weights", range: "Weight range", balance: "Balance", construction: "Construction", grips: "Factory grips", precision: "Precision classes" },
    construction: "Fully carbon, frame to handle",
    statusTitle: "Status of the values",
    spinExplanation: "SPIN keeps the status “requested weight architecture”: the 29 weights below are the requested architecture. Balance, swingweight and stiffness for SPIN are not provided; they are defined in technical review.",
    matrixTitle: "Full weight matrix",
    matrixLead: "Listed weights are the standard selection. Other weights can be requested as custom targets; missing intermediate values are not inserted.",
    balanceNote: {
      modelled: "Balance values are calculated for each listed weight (mm from the butt). They are not individual factory measurements; the measurement basis is confirmed in the written specification.",
      notprovided: "Balance values for this series are not provided. Do not infer them from another series.",
    },
    optionsTitle: "Precision, grip and weight",
    notPublished: "Not published for this series: string pattern, length, beam, tension range, swingweight and stiffness values. You can state them as requested targets for technical review.",
    offerTitle: "What happens after your request",
    offerSteps: [
      ["Request", "Submit a configuration or a question. A request ID is shown immediately."],
      ["Review", "MAXIMUS reviews series, class, weight, grip and any requested targets."],
      ["Written answer", "Specification, availability and commercial terms are confirmed in writing."],
    ],
    faqTitle: "Questions",
    faq: [
      ["Are the balance values measured?", "They are calculated for the listed weights, not individual measurements. The measurement basis is confirmed in the written specification."],
      ["Can I request a weight that is not listed?", "Yes, as a custom target in whole grams. It is reviewed technically and feasibility is confirmed in writing."],
      ["What does the precision class change?", "How tightly weight, balance, swingweight and stiffness are held to the declared specification, and which records are kept."],
      ["Is the grip built up with overgrips?", "No. L0–L7 are factory carbon handle geometries."],
      ["Where are prices and delivery times?", "They are confirmed in writing for each request and are not published here."],
    ],
    faqSpinBalance: ["Are balance values available for SPIN?", "No. Balance, swingweight and stiffness for SPIN are not provided; they are defined in technical review."],
    ctaBuild: "Configure this series",
    ctaAsk: "Ask about this series",
    ctaCompare: "Compare all series",
    weightsLabel: "listed weights",
    headLabel: "head",
  },
  precision: {
    title: "Precision and stiffness",
    switch: { label: "Select a precision class", panelLabel: "Four controlled parameters —", qcLabel: "QC architecture", protocolNote: "under the defined factory QC measurement protocol", fullTable: "Full comparison table" },
    lead: "Four parameters controlled as one engineering system. Each class defines how tightly a finished racquet is held to its declared specification and which quality records are produced.",
    statement: "Weight. Balance. Swingweight. Stiffness. Controlled as one engineering system.",
    classes: {
      "P2.5": { name: "Scalable performance core", qc: "Individual measurement and retained production records." },
      "P1.5": { name: "Advanced precision", qc: "Individual measurement, individual records and traceability." },
      "P0.5": { name: "Professional · individually controlled", qc: "Individual control with nominal and actual values and individual measurement records; serial identity, batch traceability, a precision certificate and matched sets where the programme for the order implements them." },
    },
    columns: { cls: "Class", weight: "Weight", balance: "Balance", sw: "Swingweight", stiff: "Stiffness", qc: "QC architecture" },
    stiffTarget: "target tolerance",
    stiffExact: "conforms to the declared target RA under the factory measurement protocol",
    programmeNote: "Serial identity, certificates and matched-set documentation are issued only where the programme for a specific order implements them.",
    targetsNote: "Stiffness specifications are manufacturing targets until the relevant protocol and production evidence support a stronger claim. The architecture proposition does not imply that every listed configuration has already passed a complete four-parameter release process.",
    stiffnessTitle: "Why stiffness matters",
    stiffnessP1: "Frame stiffness influences how the frame responds at contact, how it feels, and how consistent two racquets are with each other. The central benefit of controlling it is repeatable response against a declared specification.",
    stiffnessP2: "Before verified conformity is published, the internal QC record identifies the instrument, its calibration status, the method, racquet condition, resolution, measurement uncertainty, repeat measurements, rounding rule and acceptance rule. An identical displayed integer is not proof of zero physical variation or zero measurement error.",
    fields: ["Target", "Measured result", "Permitted tolerance", "Instrument capability"],
    fieldsNote: "Kept as separate fields in every record.",
    matchedTitle: "Matched sets",
    matchedP: "Matched-set criteria are defined separately from individual tolerance. Conformity of each racquet to its nominal tolerance does not by itself prove a particular maximum difference between two racquets. Matched pairs, triples and team sets are requested through the configurator and confirmed in writing.",
    extendedTitle: "Extended technical model",
    extendedP: "The data model supports additional parameters. No values or tolerance classes exist for them yet; they can be stated as requested targets in a technical brief.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torsional behaviour", length: "Length", beamProfile: "Beam profile", headGeometry: "Head geometry", stringPattern: "String pattern", durability: "Durability", vibration: "Vibration characteristics" },
    noZero: "MAXIMUS does not describe its range as having zero tolerance. Precision is stated as a class with a declared tolerance and a defined QC architecture.",
    cta: "Configure with a precision class",
  },
  grip: {
    title: "Factory grip architecture",
    statement: "Eight factory grip sizes. L0–L7.",
    lead: "Grip geometry is part of the carbon handle architecture. Each size is manufactured as handle geometry, not built up with overgrips.",
    emph: "Extended sizes",
    p1: "The eight-size factory range gives coaches and players a broader configuration range through which equipment can be specified around the player, including the larger L6 and L7 geometries.",
    p2: "The nominal grip designation is distinct from raw structural-handle dimensions and from the final measurement protocol. Sizes apply to the performance series and to the training families on this platform.",
    p3: "No claim of worldwide exclusivity is made for this range.",
    columns: { size: "Size", nominal: "Nominal", family: "Applies to" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Configure with your grip size",
  },
  custom: {
    title: "Custom engineering",
    statement: "Engineered to specification.",
    sub: "The standard range is the starting point.",
    lead: "MAXIMUS accepts technical requirements beyond the published configuration matrices for evaluation, engineering, validation and manufacture to an agreed specification. Feasibility is confirmed through review — not every conceivable request is physically or commercially feasible.",
    scopeTitle: "What a technical brief may address",
    scope: ["Head and frame geometry", "Length", "Weight", "Balance", "Swingweight", "Stiffness", "Twistweight", "Grip geometry", "Construction", "Matched sets", "Training frames", "Cosmetics and engraving", "Identity and team programmes", "Tooling-dependent development"],
    processTitle: "Process",
    process: [
      ["Define", "Preferred targets, mandatory limits, intended use and acceptable trade-offs."],
      ["Engineer", "Engineering assessment against the platform and tooling."],
      ["Validate", "Validation against the agreed specification."],
      ["Specify", "A written specification with measurement basis and tolerances."],
      ["Produce", "Production against the specification."],
      ["Measure and record", "Measurement and retained records per the applicable precision class."],
    ],
    formTitle: "Submit a technical brief",
    formLead: "Distinguish preferred targets from mandatory limits. The result is a technical review request, not an automatically accepted manufacturing order.",
    protected: "Layup recipes, tooling, supplier identities, internal costing and protected know-how are not disclosed through this route.",
    cta: "Submit a technical brief",
  },
  training: {
    title: "Training systems",
    lead: "Two training families with their own production standards, connected by one methodology: coach-led practice, records, reassessment and transfer back to performance play.",
    sst: { h: "Sweet Spot Trainer", p: "A 50 in² reduced-head training racquet in a four-weight system for centred-contact practice, sweet-spot awareness, racquet control and progressive loading." },
    spot: { h: "Spot Trainer", p: "Contact-point training using a small round contact target, on the approved four-weight foundation." },
    method: { h: "Methodology", p: "Establish objectives, select equipment with coach involvement, use the relevant system, record, reassess, adjust and transfer." },
    experience: "Hold it. Swing it. Feel it.",
    experienceP: "Request testing, fitting or a coach-supported demonstration. A submitted request is not a confirmed appointment.",
    cta: "Request a fitting or demonstration",
    distinct: "Sweet Spot Trainer, Spot Trainer and any separate demonstration device are distinct products and are never merged.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "A separate training category with its own production standard. The 50 in² head focuses attention on contact location; the four weights provide the loading progression.",
    baseline: "Confirmed baseline",
    columns: { head: "Head", length: "Length", pattern: "String pattern", grips: "Factory grips" },
    systemTitle: "Four-racquet system",
    systemLead: "Weight and balance as supplied. Measurement basis is recorded separately and is not yet published.",
    purposeTitle: "Purpose",
    purpose: ["Centred-contact practice", "Sweet-spot awareness", "Racquet control", "Progressive loading", "Coach-led development", "Transition back to the player's performance racquet"],
    heavy: "The 400 g model is a controlled training configuration. It is not automatically recommended to children, beginners or every player; the coach defines the load, duration and progression.",
    precisionNote: "Performance precision classes P2.5, P1.5 and P0.5 are not automatically applied to this training family. Training-production tolerances follow the family's own approved specification.",
    health: "No prevention or treatment of tennis elbow, injury elimination or guaranteed improvement is promised.",
    cta: "Request a Sweet Spot Trainer demonstration",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Contact-point training using a small round contact target. A distinct product with its own visual identity, built on the approved four-weight foundation.",
    purposeTitle: "Confirmed purpose",
    purposeP: "Training the player to find and repeat a precise contact point.",
    weightsTitle: "Weight progression",
    weightsP: "The weight progression follows the approved Sweet Spot Trainer weight foundation. Balance values and other Sweet Spot Trainer specifications are not copied onto Spot Trainer.",
    dims: "Exact target dimensions are not yet published.",
    grips: "Factory grip architecture L0–L7.",
    notes: ["Performance precision classes are not applied automatically.", "It is not a miniature conventional racquet and no string pattern is published.", "Spot Trainer, Sweet Spot Trainer and any separate demonstration device remain distinguishable."],
    cta: "Ask about Spot Trainer",
  },
  methodology: {
    title: "Methodology and product experience",
    lead: "Equipment is one part of a structured development journey. The method starts with the player's objectives, not with a product label.",
    stepsTitle: "The development journey",
    steps: [
      ["Establish objectives", "The player's objectives and starting point."],
      ["Select equipment", "Appropriate equipment selected with coach involvement."],
      ["Use the system", "The relevant training system, coach-led."],
      ["Record", "Observations of actual participation, without invented scores."],
      ["Reassess", "Comparable checkpoints."],
      ["Adjust", "Configuration or programme adjustments."],
      ["Transfer", "Learning transferred back to performance play."],
    ],
    educationTitle: "Education routes",
    education: { player: "Players — understanding configuration, loading and progression.", parent: "Parents — development continuity, suitable equipment, records and rights.", coach: "Coaches — training systems, fitting, assessment and authorised programme use." },
    evidenceTitle: "Evidence discipline",
    evidenceP: "Records of actual participation and observations are preserved with their classification — participant-declared, guardian-confirmed, coach-validated or system-measured. Progress, scores and validation are never invented.",
    experienceTitle: "Hold it. Swing it. Feel it.",
    experienceP: "Testing, fitting or a coach-supported demonstration can be requested. A submitted request is not a confirmed appointment.",
    cta: "Request fitting or demonstration",
    cta2: "Coach partnership enquiry",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — guided equipment profile",
    title: "MAXIMUS GPS",
    lead: "A guided equipment profile. Answer only what is relevant; review and correct your answers; receive a summary, the configuration directions that apply and a real next action.",
    honesty: "In this release no automated fitting rules are approved. GPS therefore produces a clear requirements summary and points to configuration directions; equipment specifics are routed for expert review.",
    rulesVersion: "Rules version",
    dataVersion: "Product-data version",
    steps: { role: "Role", sport: "Sport", experience: "Experience", objectives: "Objectives", style: "Playing style", equipment: "Current equipment", preference: "Preferences", coach: "Coach involvement", ageBand: "Age band", review: "Review" },
    notStored: "Not stored in this browser.",
    ageNote: "Used only to route the request. No name, date of birth or medical information is requested.",
    q: {
      role: "Which describes you?",
      sport: "Which sport?",
      experience: "Experience level",
      objectives: "What matters most? (select up to three)",
      style: "Playing style, if known",
      equipment: "Current equipment, if any",
      equipmentHint: "Brand and model, weight or grip if you know them. Optional.",
      preference: "Preferred configuration or known grip size",
      grip: "Known grip size",
      coach: "Is a coach involved in your equipment decisions?",
      ageBand: "Age band of the player (only used to route the request appropriately)",
    },
    roles: { player: "Player", parent: "Parent or guardian", coach: "Coach", club: "Club or academy", other: "Other" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Other racquet sport" },
    sportNote: "Products exist for tennis. Other sports are development directions; your interest is recorded for the relevant programme.",
    experience: { beginner: "Beginner", developing: "Developing", intermediate: "Intermediate", advanced: "Advanced", competitive: "Competitive", professional: "Professional" },
    objectives: { control: "Control", power: "Power", spin: "Spin", comfort: "Comfort", manoeuvrability: "Manoeuvrability", development: "Long-term development", competition: "Competition", training: "Training system", team: "Team or matched set", personal: "Personalisation" },
    styles: { baseline: "Baseline", allcourt: "All-court", attacking: "Attacking", defensive: "Defensive", coach: "Coach-selected", unknown: "Not sure" },
    ageBands: { u10: "Under 10", u14: "10–13", u18: "14–17", adult: "18 and over" },
    output: {
      title: "Your equipment profile",
      status: "Expert review required",
      statusP: "No automated match is produced in this release. Your profile has been summarised for expert review.",
      directionsTitle: "Configuration directions that apply",
      directionsP: "Based on your stated objectives and the declared playing direction of each series. This is a direction, not a fitting recommendation.",
      trainingHint: "Your objectives include a training system: see Sweet Spot Trainer and Spot Trainer.",
      teamHint: "Matched sets are requested through the configurator and confirmed in writing.",
      next1: "Send the profile for expert review",
      show: "Show my profile",
      configure: "Configure",
      sendP: "Send your profile to MAXIMUS for expert review. A request ID is shown immediately; the answer comes in writing.",
      otherSport: "MAXIMUS racquets exist for tennis. For other racquet sports no tennis series is suggested; your interest is recorded as a development direction.",
      noDirection: "Your objectives do not point to one playing direction. Expert review proposes a configuration.",
      incomplete: "Some required answers are missing — use “Edit answers” to complete them.",
    },
    privacy: "GPS asks for no health information and no child identifiers. Only multiple-choice answers are kept in this browser session; free text is not stored.",
  },
  build: {
    title: "Build yours",
    lead: "Configure a request: series, precision class, listed weight or custom target, grip size, requested targets, personalisation, matched sets and quantity. The result is a configuration request with a request ID — not an SKU, price, delivery date or certificate.",
    steps: { series: "Series", cls: "Precision class", weight: "Weight", grip: "Grip", targets: "Targets", personal: "Personalisation", set: "Set and quantity", use: "Use", review: "Review" },
    q: {
      series: "Choose a series",
      cls: "Choose a precision class",
      weightMode: "Weight",
      listed: "Listed weight",
      customWeight: "Requested weight (g)",
      balanceShown: "Calculated balance for this weight",
      balanceRequest: "Requested balance (mm)",
      grip: "Factory grip size",
      targetsTitle: "Requested targets",
      swingweight: "Requested swingweight (kg·cm²)",
      stiffness: "Requested stiffness (RA)",
      basis: "Measurement basis for requested values",
      engraving: "Engraving text",
      engravingHint: "Name, initials or number. Latin letters, digits, space, hyphen, apostrophe and full stop; up to 24 characters. Other scripts are accepted for artwork confirmation.",
      engravingType: "Personalisation",
      types: { none: "None", name: "Player name", initials: "Initials", number: "Set number", academy: "Coach or academy identification", team: "Team programme" },
      set: "Individual racquet or matched set",
      use: "Intended use",
      uses: { play: "Personal play", competition: "Competition", coaching: "Coaching", team: "Team or academy", retail: "Retail or distribution evaluation", other: "Other" },
      notes: "Additional technical requirements",
    },
    classes: { "P2.5": "P2.5 — scalable performance core", "P1.5": "P1.5 — advanced precision", "P0.5": "P0.5 — professional, individually controlled" },
    stiffExactShort: "stiffness conforms to the declared target RA under the factory protocol",
    clsNote: "Every class controls four parameters. P0.5 is a tight tolerance under a defined measurement protocol — not zero error. Serial identity, certificates and matched-set documentation apply only where the programme for your order implements them.",
    listedNote: "From the confirmed matrix of the series.",
    customNote: "A weight outside the matrix, reviewed technically.",
    balanceCaption: "Each listed weight shows its calculated balance in mm from the butt. Calculated values are not individual measurements.",
    spinNote: "SPIN weights form the requested weight architecture. Balance, swingweight and stiffness for SPIN are not provided; they are defined in technical review.",
    customHint: "Whole grams, digits only. A custom weight is a request for technical review; feasibility is confirmed in writing and no value is rounded.",
    gripNote: "factory carbon handle geometry, not an overgrip build-up",
    targetsLead: "Optional. Enter only the values you need. Each is recorded as a requested target for technical review, not as a published specification.",
    basisHint: "Required when you request a custom weight or any target: do the values refer to an unstrung or a strung racquet?",
    inputRange: "Accepted input: {min}–{max}.",
    inputRangeNote: "Input ranges only filter out impossible entries. They do not describe production capability.",
    listedBasis: "listed values — measurement basis confirmed in the written specification",
    notStored: "Not stored in this browser; re-enter it if you reload the page.",
    artworkReview: "artwork confirmation required",
    previewNote: "No visual preview is shown: an approved engraving template for this model is not yet published. Your text is collected for artwork confirmation.",
    teamSub: "4–99 racquets per set",
    setsLabel: { individual: "Number of racquets", pair: "Number of matched pairs", triple: "Number of matched triples", team: "Number of team sets" },
    teamSizeLabel: "Racquets per team set",
    totalLabel: "Racquets in total",
    racquetsUnit: "racquets",
    setRule: "Quantity counts sets: a matched pair is 2 racquets per set, a matched triple 3.",
    restart: "Start a new configuration",
    notices: { weightCleared: "{w} g is not in the {series} matrix, so the weight was cleared. Choose a listed weight or request a custom target." },
    reviewTitle: "Configuration request",
    reviewP: "Check the configuration, then add your contact details. The request is stored with a request ID and answered in writing; availability and commercial terms are confirmed in writing.",
    reviewErrors: "Some configuration answers need attention:",
    edit: "Edit",
    fieldNames: { series: "Series", cls: "Precision class", mode: "Weight selection", weight: "Listed weight", customWeight: "Requested weight", basis: "Measurement basis", balanceReq: "Requested balance", sw: "Requested swingweight", ra: "Requested stiffness", grip: "Grip size", ptype: "Personalisation", engraving: "Engraving text", setType: "Set type", sets: "Quantity", teamSize: "Racquets per team set", use: "Intended use", notes: "Additional requirements" },
    status: { listed: "listed weight", requestedArchitecture: "requested weight architecture", technicalReview: "request for technical review", notPublished: "not provided", requestedCondition: "requested condition" },
    chooseLink: "Not sure which series fits? Get help choosing",
    cta: "Submit configuration request",
  },
  experience: {
    title: "Experience and fitting",
    statement: "Hold it. Swing it. Feel it.",
    lead: "Request testing, fitting or a coach-supported demonstration. Requests are reviewed and answered in writing; a submitted request is not a confirmed appointment.",
    optionsTitle: "What can be requested",
    options: ["Racquet testing", "Fitting session", "Coach-supported demonstration", "Sweet Spot Trainer or Spot Trainer demonstration", "Team or academy demo day"],
    formTitle: "Fitting or demonstration request",
  },
  engineering: {
    title: "Engineering and manufacturing",
    statement: "Aircraft. Yachts. Racquets.",
    lead: "One engineering philosophy across three environments: the principles that shape an aircraft, the precision that guides a yacht through open water, the performance that defines every MAXIMUS racquet. An engineering narrative — not a claim of aircraft certification, yacht ownership, factory ownership or direct material transfer.",
    manifesto: ["We believe great engineering has no boundaries.", "One philosophy. Engineered without compromise."],
    capabilityTitle: "Manufacturing capability",
    capabilityLead: "Capability is shown as a sequence, not a slogan.",
    sequence: [
      ["Specification", "Series, precision class, weight, balance, swingweight, stiffness target, grip geometry, personalisation."],
      ["Production", "Fully carbon construction from frame to handle, produced against the specification."],
      ["Quality control", "Measurement and records per precision class: production records, individual records and traceability, individual certification."],
      ["Repeat production", "Repeatable response against a declared specification across batches."],
      ["Traceability", "Serial identity, batch traceability and a Precision Certificate where the class provides it."],
    ],
    capacityNote: "Production capacity, lead times, minimum quantities and delivery schedules are confirmed per programme in writing against confirmed orders and an agreed release schedule.",
    truth: "Capacity is not output, stock, a guaranteed delivery date or ownership of a manufacturing facility.",
    cta: "Distribution and country development",
    cta2: "Submit a technical brief",
  },
  ecosystem: {
    title: "The MAXIMUS ecosystem",
    lead: "One key. This is what it unlocks. Every node has an explanation, an accurate status and a relevant next action.",
    words: ["Engineering", "Performance", "Innovation", "Community", "Opportunity", "Purpose"],
    nodes: {
      engineering: { h: "Racquet engineering and manufacturing", p: "Fully carbon racquets engineered to specification, produced with quality records and traceability.", a: "Engineering and manufacturing" },
      precision: { h: "Precision and individual configuration", p: "Four parameters, three precision classes, eight grip sizes and custom engineering.", a: "Precision and stiffness" },
      training: { h: "Training and methodology", p: "Sweet Spot Trainer, Spot Trainer and a structured development journey.", a: "Training systems" },
      development: { h: "Player and coach development", p: "Coach-led selection, records, reassessment and education routes.", a: "Methodology" },
      identity: { h: "Personal identity and personal brands", p: "From engraving to a rights-governed personal or professional brand.", a: "Personal brands" },
      owners: { h: "Owner records, knowledge and rights", p: "A proposed permissioned owner vault for equipment, development and rights records.", a: "Owners and the vault" },
      mipa: { h: "MIPA provenance and internal control", p: "The internal IP, provenance and document-control layer.", a: "Legal identity and control" },
      digital: { h: "Digital infrastructure and Blockchain 5.0 direction", p: "Provenance, traceable records, permissioned evidence and product identity as the stated technology direction.", a: "Technology direction" },
      licensing: { h: "Contractual licensing and royalty programmes", p: "Licensed brands, products and rights packages with terms defined per agreement.", a: "Licensing routes" },
      families: { h: "Family participation and programme benefits", p: "Informed decisions, continuity, preserved records and programme-defined benefits.", a: "Families and parents" },
      network: { h: "MAXIMUS Sports Network", p: "Players, coaches, clubs, academies, service providers, operators and regional partners.", a: "Sports Network" },
      market: { h: "Clubs, academies, distribution and country development", p: "Team programmes, retail, distribution and territory development through written qualification.", a: "Partnership routes" },
      institutional: { h: "Institutional programmes, education, innovation and social impact", p: "The institutional layer provided by MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) where a programme establishes that role.", a: "Institutional programmes" },
      extensions: { h: "Future racquet-sport and MAXIMUS apparel extensions", p: "Padel, pickleball, squash, badminton, racquetball, beach tennis and apparel as development directions.", a: "Racquet sports" },
    },
    boundaryTitle: "Boundaries",
    boundary: [
      "A racquet purchase does not create institutional membership, governance rights, royalties or investment rights.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) is the institutional operator only where a programme establishes that role; equipment sales identify their actual contracting entity.",
      "Grants, charitable status, tax treatment and regulatory permissions do not apply automatically across countries.",
    ],
    techTitle: "Technology direction",
    techP: "Blockchain 5.0 is the stated MAXIMUS technology direction. Its functional purposes are provenance, traceable records, permissioned evidence, product identity and reconciliation of qualifying commercial events. No consensus mechanism, transaction capacity, node network, smart-contract address, token or independent certification is represented, and no deployed implementation is claimed. Personal information, children's records and confidential agreements are never placed into a public immutable system by default.",
  },
  brands: {
    title: "Personal brands and ambassadors",
    statement: "From player to brand. From coach to brand.",
    lead: "A dedicated personal-brand route. MAXIMUS involvement includes brand development and agreed promotion — not only a name on a racquet.",
    progressionTitle: "Intended progression",
    progression: [
      ["Verified identity", "A verified identity and development history."],
      ["Distinctive brand", "A distinctive personal or professional brand."],
      ["Rights-cleared content", "Rights-cleared content and approved product identity."],
      ["Engineering and collections", "Engineering and collection development where agreed."],
      ["Promotion", "Promotion through agreed MAXIMUS channels and partnerships."],
      ["Participation", "Contractual participation in qualifying sales or licensing."],
      ["Reporting", "Transparent reporting under the agreement."],
    ],
    royaltiesTitle: "Royalties and licensing",
    royalties: [
      "Royalties attach to the defined licensed brand, product, transaction or rights package.",
      "“Worldwide sales” means qualifying sales within the contract's scope — never every unrelated MAXIMUS racquet.",
      "Rates, calculation base, territories, term, refunds, deductions, reporting, settlement and verification are defined through the relevant agreement. No default royalty percentage is published.",
      "No global campaign, media budget, sponsorship outcome or commercial success is promised without an agreed scope.",
    ],
    cta: "Submit a brand collaboration enquiry",
    cta2: "Coach partnership enquiry",
  },
  families: {
    title: "Families and parents",
    lead: "Informed equipment decisions, continuity of development, preserved knowledge and rights, visibility of participation, and programme-defined benefits that may support future activity.",
    nowTitle: "Available now",
    now: ["Family and development enquiries in writing.", "Coach-involved equipment selection, fitting and demonstration requests.", "Private records: children's profiles are never published and never commercialised by default.", "Education route for parents: configuration, loading, progression, records and rights."],
    plannedTitle: "Planned",
    planned: ["Programme-defined participation benefits usable for goods and services within the ecosystem, rather than cash interest.", "Owner and family records in the proposed owner vault with guardian permissions and an age-18 transition of control."],
    categoriesTitle: "Kept separate",
    categories: ["Contractual royalties arising from licensed rights or qualifying sales", "Participation benefits defined by a programme", "Purchase or service credits", "Prepayments", "Institutional membership"],
    categoriesP: "These categories are never treated as interchangeable.",
    statusTitle: "Actual status of the family programme",
    journeyTitle: "The family route",
    journey: [
      ["Goal", "What the player wants to achieve next."],
      ["Current level", "Where the player is today."],
      ["Coach", "Whether a coach takes part in equipment decisions."],
      ["Equipment", "Suitable equipment for the stage, including training systems where relevant."],
      ["Agreed practice", "Coach-led use agreed in advance."],
      ["Review", "Reassessment at comparable checkpoints."],
    ],
    brief: {
      who: "Parents and guardians of players at any stage.",
      value: "A written answer on suitable equipment, coach involvement and the next development step.",
      now: "Family enquiries in writing; coach-involved selection; private records — children's profiles are never published.",
      next: "Submit the family enquiry below. You receive a request ID immediately.",
    },
    formTitle: "Family enquiry",
    formNote: "To be completed by a parent or guardian. Do not include the child's name, date of birth, school or medical information.",
    noPromise: "A purchase does not promise royalties, investment returns, sponsorship or funding of a child's development.",
    statusP: "This release explains the model and accepts programme enquiries. Accrual, payments and redemption are not available until the qualifying events, beneficiaries, funding source, calculation basis, permitted uses, accounting treatment, refunds, reversals, expiry, transferability, programme closure and dispute handling are defined in writing. No balance is promised to never decline, no participation pays for all training, and no capital protection is implied.",
    cta: "Submit a family or development enquiry",
  },
  owners: {
    title: "Owners and the owner vault",
    lead: "The owner vault is a proposed permissioned record of equipment, development, knowledge, content and documented rights. It is presented as part of the planned owner architecture: no live accounts, balances, certificates or achievements are shown.",
    nowTitle: "For current owners now",
    now: ["Owner enquiries: product or serial reference, setup, service and record requests in writing.", "Precision Certificate and matched-set documentation where the precision class provides it, delivered with the product."],
    archTitle: "Planned vault architecture",
    arch: ["Product identity and serial references", "Configuration and applicable QC certificates", "Service and setup history", "Player or coach development records", "Qualifications and verified achievements", "Rights-cleared media and authored materials", "Licences, permissions and contract references", "Personal-brand programme records", "Applicable royalty statements or participation benefits"],
    separationTitle: "What ownership means",
    separation: [
      "Ownership of a physical racquet is separate from ownership of copyright, a licence, a contractual entitlement or a record describing those things.",
      "A stored document or blockchain entry is not automatically proof that a legal right exists or has transferred.",
      "Evidence keeps its classification: participant-declared, guardian-confirmed, coach-validated, system-measured.",
      "For minors: private records, guardian permissions, no published child profiles and no commercialisation of identity by default.",
      "Export, correction, access control and an appropriate transition of control are part of the design.",
    ],
    techTitle: "Blockchain 5.0 and MxSN",
    techP: "Blockchain 5.0 is the stated technology direction; MxSN defines the concepts of a permissioned network for consent, delivery, evidence, rights and reporting. Operational implementation is not represented. The application data model is built to integrate later through a documented interface, without pretending that a connection exists today.",
    cta: "Owner enquiry",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "The connection between players, coaches, clubs, academies, service providers, programme operators and regional partners.",
    functionsTitle: "Potential functions",
    functions: ["Discovery", "Introductions", "Development programmes", "Equipment support", "Events", "Service access", "Partner opportunities"],
    statusTitle: "Actual status",
    statusP: "No public directory is published yet: only participants whose identity, relationship and permission to appear are established will be listed. A proposal sent to a club is not a partnership, and a prospective distributor is not an appointed distributor. Directory publication, booking, messaging and commercial transactions are separately controlled and are not live.",
    cta: "Apply to the network",
  },
  partnerships: {
    title: "Partnership routes",
    lead: "Written qualification first. Every route leads to a role-specific enquiry; commercial terms follow in writing.",
    commercialTitle: "Potential commercial activities of the platform",
    commercial: ["Equipment", "Custom engineering", "Personalisation", "Team and academy programmes", "Training systems", "Contractual licensing", "Distribution", "Approved services", "Future product categories"],
    boundary: "Country rights, exclusivity, territory fees and distributor margins are negotiated terms. No revenue, forecast, valuation, market share, return, funding commitment or unnamed partnership is published.",
    routes: {
      coaches: {
        title: "Coaches",
        lead: "Training systems, fitting, professional identity, authorised programmes, personal-brand opportunities and equipment supply.",
        points: ["Sweet Spot Trainer and Spot Trainer in coach-led practice.", "Fitting with the configuration matrices and eight factory grip sizes.", "Coach-to-Brand: a verified professional profile and rights-governed sub-brand.", "Authorised programme use follows a written agreement."],
        cta: "Submit a coach partnership enquiry",
        brief: {
          who: "Independent coaches and coaching teams.",
          value: "Training systems for coach-led practice, fitting with the series matrices and eight factory grips, and a route to a professional identity.",
          now: "Coach enquiries in writing. No commission, earnings or referral rate is published or implied.",
          next: "Submit the coach enquiry below. Terms follow in writing.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Clubs and academies",
        lead: "Team equipment, training systems, personalisation, development programmes, service and network participation.",
        points: ["Team and matched sets requested through the configurator.", "Training systems and methodology for structured development.", "Personalisation for team programmes on approved zones.", "Demo days, fitting sessions and network participation."],
        cta: "Submit a club or academy brief",
        brief: {
          who: "Clubs, academies and team programmes.",
          value: "Team and matched sets, training systems, personalisation for team programmes and demonstration days.",
          now: "Club and academy briefs in writing; team sets are requested through the configurator.",
          next: "Submit the club or academy brief below.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribution and country development",
        lead: "Assortment, manufacturing coordination, technical capability, territory development and confidential commercial qualification.",
        points: ["Written qualification of the counterparty, territory and channel.", "Assortment defined from the configuration matrices and precision classes.", "Territory, exclusivity, volumes, pricing and commercial protection are negotiated terms agreed in writing.", "Contracting entity, payment terms and delivery basis are identified per transaction."],
        cta: "Submit a distribution or country-development enquiry",
        brief: {
          who: "Retailers, distributors and country partners.",
          value: "An assortment defined from the confirmed matrices, precision classes and grip range, with written qualification of territory and channel.",
          now: "Distribution enquiries in writing. Territory, exclusivity, volumes and pricing are negotiated — none is granted through a form.",
          next: "Submit the distribution enquiry below.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategic and investment",
        lead: "Engineering capability, configuration depth, manufacturing model, routes to market, IP, services and expansion opportunities.",
        points: ["Qualified strategic discussion or controlled information access follows written qualification.", "Public information is limited to approved product specifications, configuration architecture, verified capabilities and programme explanations.", "Buyer-specific economics, costing, protected methodology and unpublished agreements are disclosed only under NDA or contract."],
        cta: "Request a qualified strategic discussion",
        brief: {
          who: "Investors and strategic partners.",
          value: "A qualified discussion of engineering capability, configuration depth, manufacturing model, routes to market and IP.",
          now: "No financial figures, forecasts, valuations or returns are published. Controlled information follows written qualification and NDA.",
          next: "Request a qualified strategic discussion below.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institutional programmes",
        lead: "Education, access, innovation, development evidence, social impact and appropriately structured programmes.",
        points: ["Institutional programmes are structured through MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) where the programme establishes that role.", "Restricted programme funds and commercial transactions remain distinct.", "An enquiry is not an accepted membership application, and an equipment buyer is not an institutional member.", "Grants, charitable status, tax treatment and regulatory permissions are country-specific and never assumed."],
        cta: "Submit an institutional programme enquiry",
        brief: {
          who: "Institutions, education and development programmes.",
          value: "Programmes for education, access, innovation and development evidence, structured with the appropriate operator.",
          now: "Institutional enquiries in writing. An enquiry is not a membership application; an equipment purchase is not an institutional membership.",
          next: "Submit the institutional enquiry below.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Public and controlled disclosure",
    disclosure: {
      public: { h: "Public", p: "Approved product specifications, construction, configuration architecture, training purposes, verified capabilities, programme explanations and partnership routes." },
      qualified: { h: "Qualified enquiry", p: "Technical requirements, quantities, territory interest, development scope and relevant commercial discussions." },
      controlled: { h: "NDA or contract controlled", p: "Internal formulas, detailed QC protocols, layups, tooling, manufacturing methods, supplier identities, costing, buyer-specific economics, protected methodology, unpublished agreements and sensitive rights records." },
    },
  },
  contact: {
    title: "Contact and requests",
    lead: "Choose the purpose of your request. Each form collects only what is needed to route and evaluate it. Requests are answered in writing.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Legal identity",
  },
  form: {
    purposeLabel: "Purpose of the request",
    purposes: {
      selection: "Help choosing a racquet",
      product: "Product enquiry",
      fitting: "Fitting or demonstration",
      technical: "Technical brief",
      config: "Configuration request",
      gps: "GPS equipment profile",
      coach: "Coach partnership",
      club: "Club or academy brief",
      distribution: "Distribution or country development",
      brand: "Brand collaboration or ambassador",
      family: "Family or development enquiry",
      institutional: "Institutional programme",
      strategic: "Strategic or investment discussion",
      owner: "Owner enquiry",
      network: "Sports Network application",
      general: "General enquiry",
    },
    fields: {
      name: "Name",
      email: "Email",
      role: "Your role",
      country: "Country or region",
      organisation: "Organisation",
      message: "Your message",
      level: "Current level",
      objectives: "What matters most (up to three)",
      currentRacquet: "Current racquet",
      grip: "Grip size, if known",
      seriesInterest: "Series of interest",
      quantity: "Quantity",
      city: "City or location for the session",
      coachInvolved: "Is a coach involved?",
      timing: "Preferred timing",
      targets: "Preferred targets",
      limits: "Mandatory limits",
      use: "Intended use",
      tradeoffs: "Acceptable trade-offs",
      basis: "Measurement basis",
      players: "Number of players",
      interests: "Areas of interest",
      territory: "Territory of interest",
      channels: "Existing channels and experience",
      audience: "Audience or discipline",
      proposal: "Proposed collaboration",
      goal: "Development goal",
      ageBand: "Age band of the player",
      scope: "Programme scope",
      interestArea: "Area of interest",
      productRef: "Product or serial reference",
      requestType: "Type of request",
      seeking: "What you are seeking",
      consent: "I agree that MAXIMUS may store and use these details to answer this request. This is not a marketing subscription.",
    },
    roles: { player: "Player", parent: "Parent or guardian", coach: "Coach", club: "Club or academy", retailer: "Retailer", distributor: "Distributor", brand: "Brand or ambassador", investor: "Investor or strategic partner", institution: "Institution", other: "Other" },
    interestOptions: { training: "Training systems", fitting: "Fitting", identity: "Professional identity", programmes: "Authorised programmes", brand: "Personal brand", supply: "Equipment supply", team: "Team equipment", personalisation: "Personalisation", development: "Development programmes", service: "Service", network: "Network participation" },
    ownerTypes: { setup: "Setup and configuration", service: "Service", records: "Records and certificates", other: "Other" },
    strategicAreas: { engineering: "Engineering capability", configuration: "Configuration depth", manufacturing: "Manufacturing model", routes: "Routes to market", ip: "IP and services", expansion: "Expansion opportunities" },
    errors: {
      required: "This field is required.",
      too_long: "This entry is too long.",
      too_short: "This entry is too short.",
      invalid_email: "Enter a valid email address, for example name@example.com.",
      invalid_choice: "Choose one of the options.",
      not_number: "Enter a whole number using digits only.",
      out_of_range: "This value is outside the accepted range.",
      not_in_matrix: "This weight is not in the listed matrix of the selected series.",
      decimal_not_supported: "Enter a whole number without decimals.",
      too_many: "Select no more than three options.",
      consent_required: "Consent is required so that MAXIMUS can answer this request.",
      invalid: "This entry is not valid.",
    },
  },
  legal: {
    title: "Legal identity and control",
    lead: "The public brand is MAXIMUS / MAXIMUS GPS. The legal operating identities are distinguishable and are stated here.",
    entities: {
      institutional: { role: "Institutional programme layer", p: "Provides the institutional programme layer where a programme establishes that role. Not a commercial seller of racquets. A non-profit incorporated organisation in the Dubai International Financial Centre." },
      equipment: { role: "Equipment commercial entity", p: "The equipment commercial entity for supply, distribution and contracted commercial delivery where current operating documents establish that role. The contracting party for any transaction is identified in that transaction's documents." },
      ip: { role: "IP, brand and commercial coordination", p: "Appears for an established IP, brand or commercial-coordination role. No unconfirmed contractual responsibility is assigned." },
      stewardship: { role: "Stewardship reference", p: "House of Maximus is the stewardship reference for the ecosystem where supported by the relevant source." },
      control: { role: "Internal IP, provenance and document control", p: "MIPA is the internal IP, provenance and document-control layer. An internal MIPA entry is distinct from an external trademark, patent, copyright registration or judicial recognition, and does not constitute visual approval." },
    },
    labels: { licence: "Licence", registration: "Registration", vat: "VAT TRN", address: "Address", email: "Email", jurisdiction: "Jurisdiction" },
    boundaryTitle: "Boundaries",
    boundary: [
      "A purchase does not automatically grant institutional membership, governance rights, royalties or investment rights.",
      "The institutional role is separate from commercial equipment transactions.",
      "Privacy, programme terms and controlled-access arrangements correspond to the features actually released.",
      "No blanket statement of governing law applies to every visitor, sale or foreign programme; the contractual basis is set per agreement.",
    ],
  },
  privacy: {
    title: "Privacy",
    updated: "Version 2026-09-21 · website 4.2",
    contactTitle: "Contact for privacy questions",
    sections: {
      collect: ["What is collected", "When you submit a form: the details you enter (name, email, role, country or region, organisation if given, your message and the answers of the form), the page and campaign parameters of your visit (landing page, language, utm parameters; advertising click identifiers only if you allowed analytics) and the time of submission. Your IP address is used only in hashed, short-lived form to limit abuse and is not stored with your request."],
      purpose: ["Why", "To answer your request, to prepare the proposal or specification you asked for, and to keep a record of the request. No marketing messages are sent on the basis of a form."],
      storageOn: ["Where requests are stored", "Requests are stored in a database of Upstash, Inc. (Redis), provided through the hosting platform Vercel Inc. Notifications of new requests are delivered to the MAXIMUS mailbox by email."],
      storageOff: ["Where requests are stored", "Request storage is being set up. Until it is active, forms state that a request cannot be accepted; nothing is stored. The website is hosted by Vercel Inc."],
      browser: ["Browser storage", "Session storage keeps the multiple-choice answers of GPS and the configurator and the campaign parameters of your visit for this browser session. Contact details, free text, engraving text and information about children are not stored in the browser."],
      analyticsOn: ["Analytics", "With your consent, Google Analytics 4 measures visits and form events without contact details or request text. Your choice is kept in local storage and can be changed at any time under “Analytics settings” in the footer. Forms work without analytics."],
      analyticsOff: ["Analytics", "No analytics tool is active on this website."],
      retention: ["Retention", "No automatic deletion period is configured yet. You can ask for your request to be deleted at any time."],
      children: ["Children", "Forms must be completed by an adult. Requests concerning players under 18 are made by a parent or guardian. Do not submit a child's name, date of birth, school or medical information. Children's profiles are never published."],
      rights: ["Your rights", "To access, correct or delete your request, write to gps@maximus.tennis and quote your request ID."],
      controlled: ["Controlled information", "Confidential documents are not stored in or served by this website. Controlled disclosure takes place under NDA or contract through separate channels."],
    },
  },
  terms: {
    title: "Terms of use",
    updated: "Version 2026-09-21",
    sections: [
      ["Information, not offer", "Product information on this website describes approved specifications, configuration architecture and programme explanations. It is not an offer to sell, a price list, a stock statement or a delivery commitment. Commercial terms are agreed separately in writing with the contracting entity identified in each transaction."],
      ["Requests", "A request submitted through this website — including GPS profiles, configuration requests and technical briefs — is stored with a request ID and reviewed. It is not an accepted order, a manufacturing commitment, a confirmed appointment, a membership application or an accepted application to any programme."],
      ["Specifications and evidence", "Calculated values, manufacturing targets and confirmed specifications are distinguished on the relevant pages. Stiffness values are manufacturing targets until published otherwise. No result for a specific player is guaranteed."],
      ["Ecosystem, membership and rights", "A racquet purchase does not create institutional membership, investment rights, ownership of intellectual property, an entitlement to royalties or participation benefits. Entitlements follow published programme terms or a written agreement."],
      ["Intellectual property", "MAXIMUS®, the lion emblem, the GPS mark and the content of this website are protected. Internal engineering formulas, QC protocols, layups, tooling, supplier identities, costing and protected methodology are not disclosed here."],
    ],
  },
  lead: {
    submit: "Submit request",
    submitting: "Submitting…",
    retry: "Try again",
    acceptedEyebrow: "Request accepted",
    acceptedTitle: "Your request has been received.",
    requestId: "Request ID",
    acceptedNext: "MAXIMUS reviews each request and answers in writing to the email address you provided. Keep the request ID for any follow-up.",
    duplicate: "This request had already been received; no duplicate was created.",
    another: "Start a new request",
    errorsTitle: "Please check these fields:",
    failTitle: "Your request has not been submitted.",
    fail: {
      offline: "Your device is offline.",
      network: "The connection to the server failed.",
      timeout: "The server did not answer in time.",
      rate_limited: "Too many requests came from this network. Please try again in a few minutes.",
      too_fast: "The form was submitted very quickly. Please check it and submit again.",
      spam_suspected: "The request was stopped by the spam filter.",
      unavailable: "Requests cannot be accepted at the moment.",
      default: "An unexpected error occurred.",
    },
    keepNote: "Your input is kept on this page, so you can try again.",
    fallback: "If the problem persists, write to {email}. A request counts as submitted only when a request ID is shown.",
    privacyLink: "Privacy notice",
    hpLabel: "Leave this field empty",
    after: "After submission a request ID is shown on this page. Requests are reviewed and answered in writing; a request is not an order.",
    basis: { unstrung: "Unstrung", strung: "Strung", unknown: "Not sure — to be agreed in the specification" },
    hints: {
      email: "MAXIMUS answers in writing to this address.",
      goal: "For example: first competition racquet, or moving on from a junior racquet. Do not include names, dates of birth or medical information about a child.",
      currentRacquet: "Brand and model, if known.",
      message: "Do not include passwords, payment details or medical information.",
    },
  },
  choose: {
    eyebrow: "Help choosing",
    title: "Find your racquet",
    lead: "Tell MAXIMUS your level and what matters most. Your answers are reviewed and you receive a written proposal: series, precision class, weight and grip.",
    stepsTitle: "What happens next",
    steps: [
      ["Your answers", "Level, priorities and grip size if you know it."],
      ["Expert review", "MAXIMUS compares your answers with the series matrices."],
      ["Written proposal", "A proposed configuration and the next step, in writing."],
    ],
    formTitle: "Your answers",
    submit: "Request help choosing",
    altTitle: "Prefer to decide yourself?",
    altGps: "Detailed GPS profile",
    altBuild: "Configure directly",
    note: "No automatic fitting and no accuracy claim: a person reviews every request.",
  },
  consent: {
    title: "Analytics",
    text: "May MAXIMUS measure visits with Google Analytics? Forms work either way; no contact details or request text are sent to analytics.",
    allow: "Allow analytics",
    decline: "Decline",
  },
  media: {
    powerFull: "MAXIMUS POWER racquet, unstrung frame, matte black",
    powerHandle: "MAXIMUS POWER throat-to-handle transition",
    buttcap: "Lion emblem on the MAXIMUS butt cap",
    lettering: "Gloss black MAXIMUS lettering on a matte black frame",
    greatHead: "MAXIMUS GREAT head and V-throat geometry",
    finish: "MAXIMUS frames, finish reference",
  },
  notFound: { title: "Page not found", p: "The page you requested does not exist in this language.", cta: "Go to the homepage" },
};

export default en;
