/* English master dictionary — MAXIMUS website v4.0. Numerical product data lives in data/products.js. */
const en = {
  meta: {
    siteName: "MAXIMUS GPS",
    titleSuffix: " — MAXIMUS GPS",
    defaultTitle: "MAXIMUS GPS — Your Navigation in the World of Tennis",
    defaultDescription:
      "MAXIMUS is a racquet-engineering, personal-development, commercial and institutional ecosystem. Fully carbon racquets engineered to specification, a four-parameter precision system, eight factory grip sizes and structured training methodology.",
  },
  common: {
    statuses: {
      available: "Available now",
      request: "Request route open",
      planned: "Planned",
      direction: "Development direction",
      agreement: "By written agreement",
      target: "Manufacturing target",
      modelled: "Calculated value",
      confirmed: "Confirmed specification",
      notprovided: "Not yet published",
    },
    labels: {
      next: "Next",
      back: "Back",
      edit: "Edit answers",
      review: "Review",
      start: "Start",
      restart: "Start again",
      copy: "Copy request text",
      copied: "Copied",
      openEmail: "Open email to send this request",
      reference: "Request reference",
      weight: "Weight",
      balance: "Balance",
      swingweight: "Swingweight",
      stiffness: "Stiffness",
      grip: "Grip size",
      headSize: "Head size",
      series: "Series",
      precisionClass: "Precision class",
      quantity: "Quantity",
      notProvided: "Not yet published",
      requestTarget: "Requested target",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Read more",
      allSeries: "All series",
      points: "listed weights",
      optional: "optional",
      required: "required",
      select: "Select",
      yes: "Yes",
      no: "No",
      unknown: "Not sure",
      custom: "Custom target",
      listed: "Listed weight",
      individual: "Individual racquet",
      pair: "Matched pair",
      triple: "Matched triple",
      team: "Team set",
      summaryTitle: "Your request summary",
      nextAction: "Next action",
      status: "Status",
      learn: "Learn more",
    },
    ecosystemStrip: "The MAXIMUS ecosystem",
    compose: {
      title: "How this request reaches MAXIMUS",
      text:
        "This website does not yet record requests on a server. The button below opens your own email application with the request text prepared. The request reaches MAXIMUS only when you send that email. If your device has no email application, copy the text and send it to",
      notSent: "Nothing has been sent yet.",
    },
    truth: {
      noPrices: "Prices, minimum quantities, lead times, warranties and delivery commitments are confirmed in writing per market and per programme.",
      requestNotOrder: "A request is a review request. It is not an accepted order, a manufacturing commitment or a confirmed appointment.",
      noGuarantee: "No outcome for a specific player is guaranteed by any equipment, method or programme described here.",
    },
  },
  nav: {
    groups: { racquets: "Racquets", training: "Training", ecosystem: "Ecosystem", partnerships: "Partnerships" },
    racquets: "Racquet series and comparison",
    great: "GREAT — 97 in² · Control",
    power: "POWER — 98 in² · Power",
    spin: "SPIN — 100 in² · Spin",
    precision: "Precision and stiffness",
    grip: "Factory grip architecture L0–L7",
    custom: "Custom engineering",
    training: "Training systems",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Methodology",
    gps: "MAXIMUS GPS",
    build: "Build yours",
    ecosystem: "Ecosystem map",
    engineering: "Engineering and manufacturing",
    experience: "Experience and fitting",
    brands: "Personal brands and ambassadors",
    families: "Families and parents",
    owners: "Owners and the owner vault",
    network: "Sports Network",
    partnerships: "All partnership routes",
    coaches: "Coaches",
    clubs: "Clubs and academies",
    distribution: "Distribution and country development",
    strategic: "Strategic and investment",
    institutional: "Institutional programmes",
    contact: "Contact",
    legal: "Legal identity",
    privacy: "Privacy",
    terms: "Terms",
    menu: "Menu",
    close: "Close",
    home: "Home",
  },
  footer: {
    line: "A MAXIMUS racquet is your key to the MAXIMUS world.",
    product: "Product",
    ecosystem: "Ecosystem",
    company: "Organisation",
    store: "Online store",
    instagram: "Instagram",
    email: "Email",
    rights: "MAXIMUS® and the lion emblem are marks of the MAXIMUS ecosystem. MIPA internal IP, provenance and document control.",
    boundary:
      "Commercial and contractual terms are agreed separately in writing. A racquet purchase does not create institutional membership, investment rights, ownership of intellectual property or an entitlement to royalties.",
  },
  home: {
    heroEyebrow: "MAXIMUS · RACQUET ECOSYSTEM",
    heroTitle: "A MAXIMUS racquet is your key to the MAXIMUS world.",
    heroLine: "One key. One ecosystem. Unlimited opportunities.",
    heroLead:
      "MAXIMUS is a racquet-engineering, personal-development, commercial and institutional ecosystem. The racquet is the physical entry point: equipment engineered to specification, structured training, personal configuration, identity, records, rights and partnership routes connected in one system.",
    heroCta1: "Start MAXIMUS GPS",
    heroCta2: "Build yours",
    heroMeta: [
      ["Fully carbon", "from frame to handle"],
      ["4 parameters", "weight · balance · swingweight · stiffness"],
      ["8 grip sizes", "factory architecture L0–L7"],
      ["3 series", "GREAT · POWER · SPIN"],
    ],
    keyNote:
      "“Key” describes the entry proposition. Specific entitlements follow published programme terms or a written agreement. “Unlimited opportunities” is a brand expression, not a promise of unlimited technical feasibility, income or access.",
    gps: {
      eyebrow: "MAXIMUS GPS",
      title: "GPS — two meanings, one system.",
      a: { h: "GREAT POWER & SPIN", p: "The performance meaning. Control (GREAT), energy transfer (POWER) and ball behaviour (SPIN) as three performance architectures within one engineering platform." },
      b: { h: "YOUR NAVIGATION IN THE WORLD OF TENNIS", p: "The navigation meaning. A guided route from your objectives to a configuration request, a fitting, a training system or a partnership — and onward into the wider ecosystem." },
      cta: "Start MAXIMUS GPS",
      note: "GPS names the performance system and the guided experience. It does not refer to location-tracking hardware.",
    },
    series: {
      eyebrow: "Performance series",
      title: "Three performance architectures. One engineering platform.",
      lead: "Model selection is the beginning of configuration. Precision class, weight, balance, swingweight, stiffness, grip geometry, personalisation and applicable certification complete it.",
      cta: "Compare the series",
    },
    precision: {
      eyebrow: "MAXIMUS Precision System",
      title: "Weight. Balance. Swingweight. Stiffness.",
      sub: "Controlled as one engineering system.",
      lead: "Three precision classes define how tightly each finished racquet is held to its declared specification. Stiffness values are manufacturing targets until the corresponding protocol and production evidence support a stronger statement.",
      cta: "Precision and stiffness in detail",
    },
    stiffness: {
      eyebrow: "Stiffness",
      title: "Repeatable frame response against a declared specification.",
      p: "Frame stiffness shapes response, feel and consistency between racquets. MAXIMUS treats it as the fourth controlled parameter, with target, measured result, permitted tolerance and instrument capability kept as separate records. One stiffness value does not guarantee a particular result for every player; the benefit is repeatability.",
    },
    carbon: {
      eyebrow: "Construction standard",
      title: "Fully carbon. From frame to handle.",
      p: "All current MAXIMUS racquets on this platform have fully carbon structural construction, including the handle. Foam is not used to form the handle. The handle and grip-size geometry form part of the carbon structure — the current standard, not an optional upgrade.",
      gripTitle: "Eight factory grip sizes. L0–L7.",
      gripP: "Grip geometry is part of the carbon handle architecture, not an overgrip build-up. A broader factory range means equipment can be specified around the player.",
      cta: "Factory grip architecture",
    },
    custom: {
      eyebrow: "Custom engineering",
      title: "Engineered to specification.",
      sub: "The standard range is the starting point.",
      p: "MAXIMUS accepts technical requirements beyond the published configuration matrices for evaluation, engineering, validation and manufacture to an agreed specification.",
      chain: ["Define", "Engineer", "Validate", "Specify", "Produce", "Measure and record"],
      cta: "Submit a technical brief",
    },
    personal: {
      eyebrow: "Personalisation",
      title: "Your name. Your number. Your MAXIMUS.",
      p: "Names, initials, set numbers, coach or academy identification and team programmes in the approved silver engraving treatment, on model-specific approved zones. Personalisation is identity and belonging — and the first step toward a personal brand.",
      cta: "Build yours",
    },
    training: {
      eyebrow: "Training systems",
      title: "Hold it. Swing it. Feel it.",
      p: "Sweet Spot Trainer, Spot Trainer and a structured development journey connect equipment with coach-led practice, records and reassessment.",
      cta: "Training and methodology",
      cta2: "Request a fitting or demonstration",
    },
    brands: {
      eyebrow: "Player-to-Brand · Coach-to-Brand",
      title: "From verified identity to a personal brand.",
      p: "A dedicated route from verified development history to a distinctive personal or professional brand, rights-cleared content, approved product identity, promotion through agreed channels and contractual participation in qualifying sales or licensing.",
      cta: "Personal brands and ambassadors",
    },
    families: {
      eyebrow: "Families · Owners",
      title: "Records, rights and participation that stay with the player.",
      p: "A family and parent route, a proposed permissioned owner vault for equipment, development and rights records, and programme-defined participation benefits. Presented with their actual status: what is available now and what remains planned.",
      cta1: "Families and parents",
      cta2: "Owners and the vault",
    },
    network: {
      eyebrow: "MAXIMUS Sports Network",
      title: "Players, coaches, clubs, academies, operators and regional partners.",
      p: "The network connects the people who develop the game. Directory publication, booking and messaging are separately controlled; the application route is open now.",
      cta: "Enter the network",
      routesTitle: "Choose your route",
    },
    engineering: {
      eyebrow: "Engineering and manufacturing",
      title: "Aircraft. Yachts. Racquets.",
      p: "One engineering philosophy applied across air, water and court. Manufacturing capability is shown through a clear specification-to-production sequence, quality control, repeat production and traceability.",
      cta: "Engineering and manufacturing",
    },
    partners: {
      eyebrow: "Partnership routes",
      title: "Distribution, strategic and institutional routes.",
      p: "Written qualification first. Country rights, exclusivity, territory fees and margins are negotiated terms — never granted through a form.",
      cta: "All partnership routes",
    },
    map: {
      eyebrow: "Ecosystem",
      title: "One key. This is what it unlocks.",
      cta: "Explore the ecosystem",
    },
    final: {
      title: "Your MAXIMUS racquet is the key.",
      p: "Start with your objectives, a configuration or a written enquiry. Every route leads to a real next step.",
      cta1: "Start MAXIMUS GPS",
      cta2: "Contact MAXIMUS",
    },
  },
  routes: {
    title: "Audience routes",
    lead: "Distinct routes with relevant content and a written next action. A telephone call is never the first step.",
    items: {
      player: { h: "Player", p: "Configuration, precision, grip fit, training, personalisation and ownership.", a: "Start GPS or request fitting", href: "gps", purpose: "fitting" },
      parent: { h: "Parent", p: "Development continuity, suitable equipment, coaching, private records, rights and family programme information.", a: "Submit a family enquiry", purpose: "family" },
      coach: { h: "Coach", p: "Training systems, fitting, professional identity, authorised programmes, personal-brand opportunities and equipment supply.", a: "Submit a coach enquiry", purpose: "coach" },
      club: { h: "Club or academy", p: "Team equipment, training systems, personalisation, development programmes, service and network participation.", a: "Submit a club or academy brief", purpose: "club" },
      distributor: { h: "Distributor or country partner", p: "Assortment, manufacturing coordination, technical capability, territory development and confidential commercial qualification.", a: "Submit a distribution enquiry", purpose: "distribution" },
      brand: { h: "Brand collaborator or ambassador", p: "Co-development, personal identity, promotion, licensing and qualifying royalties.", a: "Submit a brand collaboration enquiry", purpose: "brand" },
      investor: { h: "Investor or strategic partner", p: "Engineering capability, configuration depth, manufacturing model, routes to market, IP, services and expansion opportunities.", a: "Request a qualified strategic discussion", purpose: "strategic" },
      institutional: { h: "Institutional partner", p: "Education, access, innovation, development evidence, social impact and appropriately structured programmes.", a: "Submit an institutional enquiry", purpose: "institutional" },
    },
  },
  racquets: {
    title: "Racquets",
    lead: "Three performance series with a shared construction standard, a shared precision system and a shared factory grip architecture. Each series is an established performance architecture within a wider engineering platform.",
    direction: { control: "Control", power: "Power", spin: "Spin" },
    directionLabel: "Primary playing direction",
    compareTitle: "Series comparison",
    compareLead: "Confirmed architecture data only. String patterns, lengths, beam profiles, tension ranges, swingweight and stiffness nominal values for these series are not published; they are collected as requested targets for technical review.",
    columns: { series: "Series", head: "Head size", direction: "Direction", weights: "Listed weights", range: "Weight range", balance: "Balance data" },
    balanceModelled: "Calculated values",
    balanceNotProvided: "Not yet published",
    construction: "Construction: fully carbon, frame to handle · Precision: P2.5 / P1.5 / P0.5 · Grips: L0–L7",
    otherTitle: "Other racquet sports",
    otherLead: "Approved development directions. No saleable products exist in these categories and no tennis specification is transferred to them.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Beach tennis" },
    ctaConfigure: "Configure a request",
    ctaSeries: "Open series",
  },
  seriesPage: {
    eyebrow: "Performance series",
    intro: {
      great: "The 97 in² GREAT architecture is built around control: a compact head, precise contact and directional confidence.",
      power: "The 98 in² POWER architecture is built around energy transfer: depth and pace from a stable frame.",
      spin: "The 100 in² SPIN architecture is built around ball behaviour: rotation, margin and trajectory shaping.",
    },
    matrixTitle: "Configuration matrix",
    matrixLead: "Listed weights are the standard selection. Additional weights may be submitted as custom requirements; missing intermediate values are not inserted.",
    balanceNote: {
      modelled: "Balance values in this matrix are calculated/modelled values, not individual factory measurements. Measurement basis (strung or unstrung, grip and accessory state) is recorded per configuration and is collected as a requested target in the enquiry workflow until published.",
      notprovided: "Balance values for this series are not yet published. Do not infer them from another series; request a target through the configurator.",
    },
    sharedTitle: "Shared platform",
    shared: [
      "Fully carbon structural construction including the handle; grip geometry is part of the carbon structure.",
      "Precision classes P2.5, P1.5 and P0.5 across weight, balance, swingweight and stiffness.",
      "Eight factory grip sizes, L0–L7.",
      "Personalisation on model-specific approved engraving zones.",
      "Requests beyond the matrix are evaluated through custom engineering.",
    ],
    notPublished: "Not published for this series: string pattern, length, beam profile, tension range, swingweight and stiffness nominal values. Requested targets are collected for technical review.",
    ctaBuild: "Configure this series",
    ctaCompare: "Compare all series",
    weightsLabel: "listed weights",
    headLabel: "head",
  },
  precision: {
    title: "Precision and stiffness",
    lead: "Four parameters controlled as one engineering system. Each class defines how tightly a finished racquet is held to its declared specification and which quality records are produced.",
    statement: "Weight. Balance. Swingweight. Stiffness. Controlled as one engineering system.",
    classes: {
      "P2.5": { name: "Scalable performance core", qc: "Individual measurement and retained production records." },
      "P1.5": { name: "Advanced precision", qc: "Individual measurement, individual records and traceability." },
      "P0.5": { name: "Professional · individually controlled", qc: "Unique serial identity, nominal and actual values, individual measurement records, batch traceability, a Precision Certificate and matched pairs, triples or team sets where implemented." },
    },
    columns: { cls: "Class", weight: "Weight", balance: "Balance", sw: "Swingweight", stiff: "Stiffness", qc: "QC architecture" },
    stiffTarget: "target tolerance",
    stiffExact: "conformity to the exact declared RA reading under a defined factory QC protocol",
    stiffExample: "Example: a declared target of RA 69 requires the specified release result of RA 69 under that protocol.",
    targetsNote: "Stiffness specifications are manufacturing targets until the relevant protocol and production evidence support a stronger claim. The architecture proposition does not imply that every listed configuration has already passed a complete four-parameter release process.",
    stiffnessTitle: "Why stiffness matters",
    stiffnessP1: "Frame stiffness influences how the frame responds at contact, how it feels, and how consistent two racquets are with each other. The central benefit of controlling it is repeatable response against a declared specification.",
    stiffnessP2: "Before verified conformity is published, the internal QC record identifies the instrument, its calibration status, the method, racquet condition, resolution, measurement uncertainty, repeat measurements, rounding rule and acceptance rule. An identical displayed integer is not proof of zero physical variation or zero measurement error.",
    fields: ["Target", "Measured result", "Permitted tolerance", "Instrument capability"],
    fieldsNote: "Kept as separate fields in every record.",
    matchedTitle: "Matched sets",
    matchedP: "Matched-set criteria are defined separately from individual tolerance. Conformity of each racquet to its nominal tolerance does not by itself prove a particular maximum difference between two racquets. Matched pairs, triples and team sets are requested through the configurator and confirmed in writing.",
    extendedTitle: "Extended technical model",
    extendedP: "The data model supports additional parameters. No values or tolerance classes exist for them yet; they can be stated as requested targets in a technical brief.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torsional behaviour", length: "Length", beamProfile: "Beam profile", headGeometry: "Head geometry", stringPattern: "String pattern", durability: "Durability", vibration: "Vibration characteristics" },
    noZero: "MAXIMUS does not describe its range as having zero tolerance. Precision is stated as a class with a declared tolerance and a defined QC architecture.",
    cta: "Configure with a precision class",
  },
  grip: {
    title: "Factory grip architecture",
    statement: "Eight factory grip sizes. L0–L7.",
    lead: "Grip geometry is part of the carbon handle architecture. Each size is manufactured as handle geometry, not built up with overgrips.",
    emph: "Extended sizes",
    p1: "The eight-size factory range gives coaches and players a broader configuration range through which equipment can be specified around the player — including the larger L6 and L7 geometries that are rarely available as factory sizes.",
    p2: "The nominal grip designation is distinct from raw structural-handle dimensions and from the final measurement protocol. Sizes apply to the performance series and to the training families on this platform.",
    p3: "No claim of worldwide exclusivity is made for this range.",
    columns: { size: "Size", nominal: "Nominal", family: "Applies to" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Configure with your grip size",
  },
  custom: {
    title: "Custom engineering",
    statement: "Engineered to specification.",
    sub: "The standard range is the starting point.",
    lead: "MAXIMUS accepts technical requirements beyond the published configuration matrices for evaluation, engineering, validation and manufacture to an agreed specification. Feasibility is confirmed through review — not every conceivable request is physically or commercially feasible.",
    scopeTitle: "What a technical brief may address",
    scope: ["Head and frame geometry", "Length", "Weight", "Balance", "Swingweight", "Stiffness", "Twistweight", "Grip geometry", "Construction", "Matched sets", "Training frames", "Cosmetics and engraving", "Identity and team programmes", "Tooling-dependent development"],
    processTitle: "Process",
    process: [
      ["Define", "Preferred targets, mandatory limits, intended use and acceptable trade-offs."],
      ["Engineer", "Engineering assessment against the platform and tooling."],
      ["Validate", "Validation against the agreed specification."],
      ["Specify", "A written specification with measurement basis and tolerances."],
      ["Produce", "Production against the specification."],
      ["Measure and record", "Measurement and retained records per the applicable precision class."],
    ],
    formTitle: "Submit a technical brief",
    formLead: "Distinguish preferred targets from mandatory limits. The result is a technical review request, not an automatically accepted manufacturing order.",
    protected: "Layup recipes, tooling, supplier identities, internal costing and protected know-how are not disclosed through this route.",
    cta: "Submit a technical brief",
  },
  training: {
    title: "Training systems",
    lead: "Two training families with their own production standards, connected by one methodology: coach-led practice, records, reassessment and transfer back to performance play.",
    sst: { h: "Sweet Spot Trainer", p: "A 50 in² reduced-head training racquet in a four-weight system for centred-contact practice, sweet-spot awareness, racquet control and progressive loading." },
    spot: { h: "Spot Trainer", p: "Contact-point training using a small round contact target, on the approved four-weight foundation." },
    method: { h: "Methodology", p: "Establish objectives, select equipment with coach involvement, use the relevant system, record, reassess, adjust and transfer." },
    experience: "Hold it. Swing it. Feel it.",
    experienceP: "Request testing, fitting or a coach-supported demonstration. A submitted request is not a confirmed appointment.",
    cta: "Request a fitting or demonstration",
    distinct: "Sweet Spot Trainer, Spot Trainer and any separate demonstration device are distinct products and are never merged.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "A separate training category with its own production standard. The 50 in² head focuses attention on contact location; the four weights provide the loading progression.",
    baseline: "Confirmed baseline",
    columns: { head: "Head", length: "Length", pattern: "String pattern", grips: "Factory grips" },
    systemTitle: "Four-racquet system",
    systemLead: "Weight and balance as supplied. Measurement basis is recorded separately and is not yet published.",
    purposeTitle: "Purpose",
    purpose: ["Centred-contact practice", "Sweet-spot awareness", "Racquet control", "Progressive loading", "Coach-led development", "Transition back to the player's performance racquet"],
    heavy: "The 400 g model is a controlled training configuration. It is not automatically recommended to children, beginners or every player; the coach defines the load, duration and progression.",
    precisionNote: "Performance precision classes P2.5, P1.5 and P0.5 are not automatically applied to this training family. Training-production tolerances follow the family's own approved specification.",
    health: "No prevention or treatment of tennis elbow, injury elimination or guaranteed improvement is promised.",
    cta: "Request a Sweet Spot Trainer demonstration",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Contact-point training using a small round contact target. A distinct product with its own visual identity, built on the approved four-weight foundation.",
    purposeTitle: "Confirmed purpose",
    purposeP: "Training the player to find and repeat a precise contact point.",
    weightsTitle: "Weight progression",
    weightsP: "The weight progression follows the approved Sweet Spot Trainer weight foundation. Balance values and other Sweet Spot Trainer specifications are not copied onto Spot Trainer.",
    dims: "Exact target dimensions are not yet published.",
    grips: "Factory grip architecture L0–L7.",
    notes: ["Performance precision classes are not applied automatically.", "It is not a miniature conventional racquet and no string pattern is published.", "Spot Trainer, Sweet Spot Trainer and any separate demonstration device remain distinguishable."],
    cta: "Ask about Spot Trainer",
  },
  methodology: {
    title: "Methodology and product experience",
    lead: "Equipment is one part of a structured development journey. The method starts with the player's objectives, not with a product label.",
    stepsTitle: "The development journey",
    steps: [
      ["Establish objectives", "The player's objectives and starting point."],
      ["Select equipment", "Appropriate equipment selected with coach involvement."],
      ["Use the system", "The relevant training system, coach-led."],
      ["Record", "Observations of actual participation, without invented scores."],
      ["Reassess", "Comparable checkpoints."],
      ["Adjust", "Configuration or programme adjustments."],
      ["Transfer", "Learning transferred back to performance play."],
    ],
    educationTitle: "Education routes",
    education: { player: "Players — understanding configuration, loading and progression.", parent: "Parents — development continuity, suitable equipment, records and rights.", coach: "Coaches — training systems, fitting, assessment and authorised programme use." },
    evidenceTitle: "Evidence discipline",
    evidenceP: "Records of actual participation and observations are preserved with their classification — participant-declared, guardian-confirmed, coach-validated or system-measured. Progress, scores and validation are never invented.",
    experienceTitle: "Hold it. Swing it. Feel it.",
    experienceP: "Testing, fitting or a coach-supported demonstration can be requested. A submitted request is not a confirmed appointment.",
    cta: "Request fitting or demonstration",
    cta2: "Coach partnership enquiry",
  },
  gps: {
    title: "MAXIMUS GPS",
    lead: "A guided equipment profile. Answer only what is relevant; review and correct your answers; receive a summary, the configuration directions that apply and a real next action.",
    honesty: "In this release no automated fitting rules are approved. GPS therefore produces a clear requirements summary and points to configuration directions; equipment specifics are routed for expert review.",
    rulesVersion: "Rules version",
    dataVersion: "Product-data version",
    steps: { role: "Role", sport: "Sport", experience: "Experience", objectives: "Objectives", style: "Playing style", equipment: "Current equipment", preference: "Preferences", coach: "Coach involvement", review: "Review" },
    q: {
      role: "Which describes you?",
      sport: "Which sport?",
      experience: "Experience level",
      objectives: "What matters most? (select up to three)",
      style: "Playing style, if known",
      equipment: "Current equipment, if any",
      equipmentHint: "Brand and model, weight or grip if you know them. Optional.",
      preference: "Preferred configuration or known grip size",
      grip: "Known grip size",
      coach: "Is a coach involved in your equipment decisions?",
      ageBand: "Age band of the player (only used to route the request appropriately)",
    },
    roles: { player: "Player", parent: "Parent or guardian", coach: "Coach", club: "Club or academy", other: "Other" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Other racquet sport" },
    sportNote: "Products exist for tennis. Other sports are development directions; your interest is recorded for the relevant programme.",
    experience: { beginner: "Beginner", developing: "Developing", intermediate: "Intermediate", advanced: "Advanced", competitive: "Competitive", professional: "Professional" },
    objectives: { control: "Control", power: "Power", spin: "Spin", comfort: "Comfort", manoeuvrability: "Manoeuvrability", development: "Long-term development", competition: "Competition", training: "Training system", team: "Team or matched set", personal: "Personalisation" },
    styles: { baseline: "Baseline", allcourt: "All-court", attacking: "Attacking", defensive: "Defensive", coach: "Coach-selected", unknown: "Not sure" },
    ageBands: { u10: "Under 10", u14: "10–13", u18: "14–17", adult: "18 and over" },
    output: {
      title: "Your equipment profile",
      status: "Expert review required",
      statusP: "No automated match is produced in this release. Your profile has been summarised for expert review.",
      directionsTitle: "Configuration directions that apply",
      directionsP: "Based on your stated objectives and the declared playing direction of each series. This is a direction, not a fitting recommendation.",
      trainingHint: "Your objectives include a training system: see Sweet Spot Trainer and Spot Trainer.",
      teamHint: "Matched sets are requested through the configurator and confirmed in writing.",
      next1: "Send the profile for expert review",
      next2: "Continue to the configurator",
      next3: "Request a fitting",
      audit: "This summary records the GPS rules version and product-data version for review.",
    },
    privacy: "GPS asks for no health information and no child identifiers. Non-sensitive progress is kept in this browser session only.",
  },
  build: {
    title: "Build yours",
    lead: "Configure a request: series, precision class, listed weight or custom target, grip size, requested swingweight and stiffness, personalisation, matched sets and quantity. The result is a configuration request with a unique reference — not an SKU, price, delivery date or certificate.",
    steps: { series: "Series", cls: "Precision class", weight: "Weight", grip: "Grip", targets: "Targets", personal: "Personalisation", set: "Set and quantity", use: "Use", review: "Review" },
    q: {
      series: "Choose a series",
      cls: "Choose a precision class",
      weightMode: "Weight selection",
      listed: "Choose a listed weight",
      customWeight: "Custom target weight (g)",
      balanceShown: "Calculated balance for this listed weight",
      balanceRequest: "Requested balance (mm), optional",
      grip: "Factory grip size",
      swingweight: "Requested swingweight (kg·cm²), optional",
      stiffness: "Requested stiffness (RA), optional",
      engraving: "Engraving text",
      engravingHint: "Name, initials or number. Latin letters, digits, space, hyphen, apostrophe and full stop; up to 24 characters. Other scripts are submitted for artwork confirmation and are not confirmed automatically.",
      engravingType: "Personalisation type",
      types: { none: "None", name: "Player name", initials: "Initials", number: "Set number", academy: "Coach or academy identification", team: "Team programme" },
      set: "Individual racquet or matched set",
      quantity: "Quantity",
      use: "Intended use",
      uses: { play: "Personal play", competition: "Competition", coaching: "Coaching", team: "Team or academy", retail: "Retail or distribution evaluation", other: "Other" },
      notes: "Additional technical requirements",
    },
    balanceNA: "Balance for this series is not yet published. Enter a requested balance if you have one.",
    customNote: "A custom target is a requested configuration, not a listed standard option.",
    listedNote: "Selected from the listed standard matrix.",
    classes: { "P2.5": "P2.5 — scalable performance core", "P1.5": "P1.5 — advanced precision", "P0.5": "P0.5 — professional, individually controlled" },
    previewNote: "No visual preview is shown: an approved engraving template and placement zone for this model are not yet published. Your text is collected for artwork confirmation.",
    reviewTitle: "Configuration request",
    reviewP: "Check the summary. Editing is possible until you open the email. Every combination is a request for review; validation, availability and commercial terms are confirmed in writing.",
    outcome: "Technical request — not a manufacturing acceptance",
    cta: "Open email to send this configuration request",
  },
  experience: {
    title: "Experience and fitting",
    statement: "Hold it. Swing it. Feel it.",
    lead: "Request testing, fitting or a coach-supported demonstration. Requests are reviewed and answered in writing; a submitted request is not a confirmed appointment.",
    optionsTitle: "What can be requested",
    options: ["Racquet testing", "Fitting session", "Coach-supported demonstration", "Sweet Spot Trainer or Spot Trainer demonstration", "Team or academy demo day"],
    formTitle: "Fitting or demonstration request",
  },
  engineering: {
    title: "Engineering and manufacturing",
    statement: "Aircraft. Yachts. Racquets.",
    lead: "One engineering philosophy across three environments: the principles that shape an aircraft, the precision that guides a yacht through open water, the performance that defines every MAXIMUS racquet. An engineering narrative — not a claim of aircraft certification, yacht ownership, factory ownership or direct material transfer.",
    manifesto: ["We believe great engineering has no boundaries.", "One philosophy. Engineered without compromise."],
    capabilityTitle: "Manufacturing capability",
    capabilityLead: "Capability is shown as a sequence, not a slogan.",
    sequence: [
      ["Specification", "Series, precision class, weight, balance, swingweight, stiffness target, grip geometry, personalisation."],
      ["Production", "Fully carbon construction from frame to handle, produced against the specification."],
      ["Quality control", "Measurement and records per precision class: production records, individual records and traceability, individual certification."],
      ["Repeat production", "Repeatable response against a declared specification across batches."],
      ["Traceability", "Serial identity, batch traceability and a Precision Certificate where the class provides it."],
    ],
    capacityNote: "Production capacity, lead times, minimum quantities and delivery schedules are confirmed per programme in writing against confirmed orders and an agreed release schedule.",
    truth: "Capacity is not output, stock, a guaranteed delivery date or ownership of a manufacturing facility.",
    cta: "Distribution and country development",
    cta2: "Submit a technical brief",
  },
  ecosystem: {
    title: "The MAXIMUS ecosystem",
    lead: "One key. This is what it unlocks. Every node has an explanation, an accurate status and a relevant next action.",
    words: ["Engineering", "Performance", "Innovation", "Community", "Opportunity", "Purpose"],
    nodes: {
      engineering: { h: "Racquet engineering and manufacturing", p: "Fully carbon racquets engineered to specification, produced with quality records and traceability.", a: "Engineering and manufacturing" },
      precision: { h: "Precision and individual configuration", p: "Four parameters, three precision classes, eight grip sizes and custom engineering.", a: "Precision and stiffness" },
      training: { h: "Training and methodology", p: "Sweet Spot Trainer, Spot Trainer and a structured development journey.", a: "Training systems" },
      development: { h: "Player and coach development", p: "Coach-led selection, records, reassessment and education routes.", a: "Methodology" },
      identity: { h: "Personal identity and personal brands", p: "From engraving to a rights-governed personal or professional brand.", a: "Personal brands" },
      owners: { h: "Owner records, knowledge and rights", p: "A proposed permissioned owner vault for equipment, development and rights records.", a: "Owners and the vault" },
      mipa: { h: "MIPA provenance and internal control", p: "The internal IP, provenance and document-control layer.", a: "Legal identity and control" },
      digital: { h: "Digital infrastructure and Blockchain 5.0 direction", p: "Provenance, traceable records, permissioned evidence and product identity as the stated technology direction.", a: "Technology direction" },
      licensing: { h: "Contractual licensing and royalty programmes", p: "Licensed brands, products and rights packages with terms defined per agreement.", a: "Licensing routes" },
      families: { h: "Family participation and programme benefits", p: "Informed decisions, continuity, preserved records and programme-defined benefits.", a: "Families and parents" },
      network: { h: "MAXIMUS Sports Network", p: "Players, coaches, clubs, academies, service providers, operators and regional partners.", a: "Sports Network" },
      market: { h: "Clubs, academies, distribution and country development", p: "Team programmes, retail, distribution and territory development through written qualification.", a: "Partnership routes" },
      institutional: { h: "Institutional programmes, education, innovation and social impact", p: "The institutional layer provided by MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) where a programme establishes that role.", a: "Institutional programmes" },
      extensions: { h: "Future racquet-sport and MAXIMUS apparel extensions", p: "Padel, pickleball, squash, badminton, racquetball, beach tennis and apparel as development directions.", a: "Racquet sports" },
    },
    boundaryTitle: "Boundaries",
    boundary: [
      "A racquet purchase does not create institutional membership, governance rights, royalties or investment rights.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) is the institutional operator only where a programme establishes that role; equipment sales identify their actual contracting entity.",
      "Grants, charitable status, tax treatment and regulatory permissions do not apply automatically across countries.",
    ],
    techTitle: "Technology direction",
    techP: "Blockchain 5.0 is the stated MAXIMUS technology direction. Its functional purposes are provenance, traceable records, permissioned evidence, product identity and reconciliation of qualifying commercial events. No consensus mechanism, transaction capacity, node network, smart-contract address, token or independent certification is represented, and no deployed implementation is claimed. Personal information, children's records and confidential agreements are never placed into a public immutable system by default.",
  },
  brands: {
    title: "Personal brands and ambassadors",
    statement: "From player to brand. From coach to brand.",
    lead: "A dedicated personal-brand route. MAXIMUS involvement includes brand development and agreed promotion — not only a name on a racquet.",
    progressionTitle: "Intended progression",
    progression: [
      ["Verified identity", "A verified identity and development history."],
      ["Distinctive brand", "A distinctive personal or professional brand."],
      ["Rights-cleared content", "Rights-cleared content and approved product identity."],
      ["Engineering and collections", "Engineering and collection development where agreed."],
      ["Promotion", "Promotion through agreed MAXIMUS channels and partnerships."],
      ["Participation", "Contractual participation in qualifying sales or licensing."],
      ["Reporting", "Transparent reporting under the agreement."],
    ],
    royaltiesTitle: "Royalties and licensing",
    royalties: [
      "Royalties attach to the defined licensed brand, product, transaction or rights package.",
      "“Worldwide sales” means qualifying sales within the contract's scope — never every unrelated MAXIMUS racquet.",
      "Rates, calculation base, territories, term, refunds, deductions, reporting, settlement and verification are defined through the relevant agreement. No default royalty percentage is published.",
      "No global campaign, media budget, sponsorship outcome or commercial success is promised without an agreed scope.",
    ],
    cta: "Submit a brand collaboration enquiry",
    cta2: "Coach partnership enquiry",
  },
  families: {
    title: "Families and parents",
    lead: "Informed equipment decisions, continuity of development, preserved knowledge and rights, visibility of participation, and programme-defined benefits that may support future activity.",
    nowTitle: "Available now",
    now: ["Family and development enquiries in writing.", "Coach-involved equipment selection, fitting and demonstration requests.", "Private records: children's profiles are never published and never commercialised by default.", "Education route for parents: configuration, loading, progression, records and rights."],
    plannedTitle: "Planned",
    planned: ["Programme-defined participation benefits usable for goods and services within the ecosystem, rather than cash interest.", "Owner and family records in the proposed owner vault with guardian permissions and an age-18 transition of control."],
    categoriesTitle: "Kept separate",
    categories: ["Contractual royalties arising from licensed rights or qualifying sales", "Participation benefits defined by a programme", "Purchase or service credits", "Prepayments", "Institutional membership"],
    categoriesP: "These categories are never treated as interchangeable.",
    statusTitle: "Actual status of the family programme",
    statusP: "This release explains the model and accepts programme enquiries. Accrual, payments and redemption are not available until the qualifying events, beneficiaries, funding source, calculation basis, permitted uses, accounting treatment, refunds, reversals, expiry, transferability, programme closure and dispute handling are defined in writing. No balance is promised to never decline, no participation pays for all training, and no capital protection is implied.",
    cta: "Submit a family or development enquiry",
  },
  owners: {
    title: "Owners and the owner vault",
    lead: "The owner vault is a proposed permissioned record of equipment, development, knowledge, content and documented rights. It is presented as part of the planned owner architecture: no live accounts, balances, certificates or achievements are shown.",
    nowTitle: "For current owners now",
    now: ["Owner enquiries: product or serial reference, setup, service and record requests in writing.", "Precision Certificate and matched-set documentation where the precision class provides it, delivered with the product."],
    archTitle: "Planned vault architecture",
    arch: ["Product identity and serial references", "Configuration and applicable QC certificates", "Service and setup history", "Player or coach development records", "Qualifications and verified achievements", "Rights-cleared media and authored materials", "Licences, permissions and contract references", "Personal-brand programme records", "Applicable royalty statements or participation benefits"],
    separationTitle: "What ownership means",
    separation: [
      "Ownership of a physical racquet is separate from ownership of copyright, a licence, a contractual entitlement or a record describing those things.",
      "A stored document or blockchain entry is not automatically proof that a legal right exists or has transferred.",
      "Evidence keeps its classification: participant-declared, guardian-confirmed, coach-validated, system-measured.",
      "For minors: private records, guardian permissions, no published child profiles and no commercialisation of identity by default.",
      "Export, correction, access control and an appropriate transition of control are part of the design.",
    ],
    techTitle: "Blockchain 5.0 and MxSN",
    techP: "Blockchain 5.0 is the stated technology direction; MxSN defines the concepts of a permissioned network for consent, delivery, evidence, rights and reporting. Operational implementation is not represented. The application data model is built to integrate later through a documented interface, without pretending that a connection exists today.",
    cta: "Owner enquiry",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "The connection between players, coaches, clubs, academies, service providers, programme operators and regional partners.",
    functionsTitle: "Potential functions",
    functions: ["Discovery", "Introductions", "Development programmes", "Equipment support", "Events", "Service access", "Partner opportunities"],
    statusTitle: "Actual status",
    statusP: "No public directory is published yet: only participants whose identity, relationship and permission to appear are established will be listed. A proposal sent to a club is not a partnership, and a prospective distributor is not an appointed distributor. Directory publication, booking, messaging and commercial transactions are separately controlled and are not live.",
    cta: "Apply to the network",
  },
  partnerships: {
    title: "Partnership routes",
    lead: "Written qualification first. Every route leads to a role-specific enquiry; commercial terms follow in writing.",
    commercialTitle: "Potential commercial activities of the platform",
    commercial: ["Equipment", "Custom engineering", "Personalisation", "Team and academy programmes", "Training systems", "Contractual licensing", "Distribution", "Approved services", "Future product categories"],
    boundary: "Country rights, exclusivity, territory fees and distributor margins are negotiated terms. No revenue, forecast, valuation, market share, return, funding commitment or unnamed partnership is published.",
    routes: {
      coaches: {
        title: "Coaches",
        lead: "Training systems, fitting, professional identity, authorised programmes, personal-brand opportunities and equipment supply.",
        points: ["Sweet Spot Trainer and Spot Trainer in coach-led practice.", "Fitting with the configuration matrices and eight factory grip sizes.", "Coach-to-Brand: a verified professional profile and rights-governed sub-brand.", "Authorised programme use follows a written agreement."],
        cta: "Submit a coach partnership enquiry",
        purpose: "coach",
      },
      clubs: {
        title: "Clubs and academies",
        lead: "Team equipment, training systems, personalisation, development programmes, service and network participation.",
        points: ["Team and matched sets requested through the configurator.", "Training systems and methodology for structured development.", "Personalisation for team programmes on approved zones.", "Demo days, fitting sessions and network participation."],
        cta: "Submit a club or academy brief",
        purpose: "club",
      },
      distribution: {
        title: "Distribution and country development",
        lead: "Assortment, manufacturing coordination, technical capability, territory development and confidential commercial qualification.",
        points: ["Written qualification of the counterparty, territory and channel.", "Assortment defined from the configuration matrices and precision classes.", "Territory, exclusivity, volumes, pricing and commercial protection are negotiated terms agreed in writing.", "Contracting entity, payment terms and delivery basis are identified per transaction."],
        cta: "Submit a distribution or country-development enquiry",
        purpose: "distribution",
      },
      strategic: {
        title: "Strategic and investment",
        lead: "Engineering capability, configuration depth, manufacturing model, routes to market, IP, services and expansion opportunities.",
        points: ["Qualified strategic discussion or controlled information access follows written qualification.", "Public information is limited to approved product specifications, configuration architecture, verified capabilities and programme explanations.", "Buyer-specific economics, costing, protected methodology and unpublished agreements are disclosed only under NDA or contract."],
        cta: "Request a qualified strategic discussion",
        purpose: "strategic",
      },
      institutional: {
        title: "Institutional programmes",
        lead: "Education, access, innovation, development evidence, social impact and appropriately structured programmes.",
        points: ["Institutional programmes are structured through MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) where the programme establishes that role.", "Restricted programme funds and commercial transactions remain distinct.", "An enquiry is not an accepted membership application, and an equipment buyer is not an institutional member.", "Grants, charitable status, tax treatment and regulatory permissions are country-specific and never assumed."],
        cta: "Submit an institutional programme enquiry",
        purpose: "institutional",
      },
    },
    disclosureTitle: "Public and controlled disclosure",
    disclosure: {
      public: { h: "Public", p: "Approved product specifications, construction, configuration architecture, training purposes, verified capabilities, programme explanations and partnership routes." },
      qualified: { h: "Qualified enquiry", p: "Technical requirements, quantities, territory interest, development scope and relevant commercial discussions." },
      controlled: { h: "NDA or contract controlled", p: "Internal formulas, detailed QC protocols, layups, tooling, manufacturing methods, supplier identities, costing, buyer-specific economics, protected methodology, unpublished agreements and sensitive rights records." },
    },
  },
  contact: {
    title: "Contact and requests",
    lead: "Choose the purpose of your request. Each form collects only what is needed to route and evaluate it. Requests are answered in writing.",
    email: "Email",
    instagram: "Instagram",
    store: "Online store",
    legalLink: "Legal identity",
  },
  form: {
    purposeLabel: "Purpose of the request",
    purposes: {
      product: "Product enquiry",
      fitting: "Fitting or demonstration",
      technical: "Technical brief",
      coach: "Coach partnership",
      club: "Club or academy brief",
      distribution: "Distribution or country development",
      brand: "Brand collaboration or ambassador",
      family: "Family or development enquiry",
      institutional: "Institutional programme",
      strategic: "Strategic or investment discussion",
      owner: "Owner enquiry",
      network: "Sports Network application",
      general: "General enquiry",
    },
    fields: {
      name: "Name",
      email: "Contact email",
      role: "Your role",
      country: "Country or region",
      organisation: "Organisation",
      message: "Your request",
      seriesInterest: "Series of interest",
      quantity: "Quantity",
      city: "City or location for the session",
      coachInvolved: "Is a coach involved?",
      timing: "Preferred timing",
      targets: "Preferred targets",
      limits: "Mandatory limits",
      use: "Intended use",
      tradeoffs: "Acceptable trade-offs",
      players: "Number of players",
      interests: "Areas of interest",
      territory: "Territory of interest",
      channels: "Existing channels and experience",
      audience: "Audience or discipline",
      proposal: "Proposed collaboration",
      ageBand: "Age band of the player(s)",
      scope: "Programme scope",
      interestArea: "Area of interest",
      productRef: "Product or serial reference",
      requestType: "Type of request",
      seeking: "What you are seeking",
      consent: "I agree that MAXIMUS may use these details to answer this request. No marketing consent is given by this request.",
    },
    roles: { player: "Player", parent: "Parent or guardian", coach: "Coach", club: "Club or academy", retailer: "Retailer", distributor: "Distributor", brand: "Brand or ambassador", investor: "Investor or strategic partner", institution: "Institution", other: "Other" },
    interestOptions: { training: "Training systems", fitting: "Fitting", identity: "Professional identity", programmes: "Authorised programmes", brand: "Personal brand", supply: "Equipment supply", team: "Team equipment", personalisation: "Personalisation", development: "Development programmes", service: "Service", network: "Network participation" },
    ownerTypes: { setup: "Setup and configuration", service: "Service", records: "Records and certificates", other: "Other" },
    strategicAreas: { engineering: "Engineering capability", configuration: "Configuration depth", manufacturing: "Manufacturing model", routes: "Routes to market", ip: "IP and services", expansion: "Expansion opportunities" },
    errors: { required: "This field is required.", email: "Enter a valid email address.", consent: "Consent is required to answer this request.", number: "Enter a number." },
    review: "Review and prepare the request",
    subject: "MAXIMUS request",
    reference: "Reference",
    prepared: "Request prepared",
    edit: "Edit request",
    routeNote: "Requests are routed to gps@maximus.tennis and answered in writing.",
  },
  legal: {
    title: "Legal identity and control",
    lead: "The public brand is MAXIMUS / MAXIMUS GPS. The legal operating identities are distinguishable and are stated here.",
    entities: {
      institutional: { role: "Institutional programme layer", p: "Provides the institutional programme layer where a programme establishes that role. Not a commercial seller of racquets. A non-profit incorporated organisation in the Dubai International Financial Centre." },
      equipment: { role: "Equipment commercial entity", p: "The equipment commercial entity for supply, distribution and contracted commercial delivery where current operating documents establish that role. The contracting party for any transaction is identified in that transaction's documents." },
      ip: { role: "IP, brand and commercial coordination", p: "Appears for an established IP, brand or commercial-coordination role. No unconfirmed contractual responsibility is assigned." },
      stewardship: { role: "Stewardship reference", p: "House of Maximus is the stewardship reference for the ecosystem where supported by the relevant source." },
      control: { role: "Internal IP, provenance and document control", p: "MIPA is the internal IP, provenance and document-control layer. An internal MIPA entry is distinct from an external trademark, patent, copyright registration or judicial recognition, and does not constitute visual approval." },
    },
    labels: { licence: "Licence", registration: "Registration", vat: "VAT TRN", address: "Address", email: "Email", jurisdiction: "Jurisdiction" },
    boundaryTitle: "Boundaries",
    boundary: [
      "A purchase does not automatically grant institutional membership, governance rights, royalties or investment rights.",
      "The institutional role is separate from commercial equipment transactions.",
      "Privacy, programme terms and controlled-access arrangements correspond to the features actually released.",
      "No blanket statement of governing law applies to every visitor, sale or foreign programme; the contractual basis is set per agreement.",
    ],
    store: "Online store",
  },
  privacy: {
    title: "Privacy",
    updated: "Version 2026-09-21",
    sections: [
      ["What this website collects", "This website has no user accounts and does not record form submissions on a server. Request forms prepare an email in your own mail application; the data you enter reaches MAXIMUS only when you send that email, and is then used to answer your request. Non-sensitive progress in MAXIMUS GPS and the configurator is kept in your browser session only and is cleared when the session ends."],
      ["What is not collected", "No health information, no precise child identifiers and no engraving text are stored on a server by this website. No analytics platform is currently configured; no tracking events are transmitted."],
      ["Children", "Requests concerning players under 18 are made by a parent or guardian. Children's profiles are never published and never commercialised by default."],
      ["Controlled information", "Confidential documents are not stored in or served by this website. Controlled disclosure takes place under NDA or contract through separate channels."],
      ["Your rights", "To correct or delete details you sent by email, write to gps@maximus.tennis. The responsible entity for each activated service is identified in that service's documents."],
    ],
  },
  terms: {
    title: "Terms of use",
    updated: "Version 2026-09-21",
    sections: [
      ["Information, not offer", "Product information on this website describes approved specifications, configuration architecture and programme explanations. It is not an offer to sell, a price list, a stock statement or a delivery commitment. Commercial terms are agreed separately in writing with the contracting entity identified in each transaction."],
      ["Requests", "A request submitted through this website — including GPS profiles, configuration requests and technical briefs — is a request for review. It is not an accepted order, a manufacturing commitment, a confirmed appointment, a membership application or an accepted application to any programme."],
      ["Specifications and evidence", "Calculated values, manufacturing targets and confirmed specifications are distinguished on the relevant pages. Stiffness values are manufacturing targets until published otherwise. No result for a specific player is guaranteed."],
      ["Ecosystem, membership and rights", "A racquet purchase does not create institutional membership, investment rights, ownership of intellectual property, an entitlement to royalties or participation benefits. Entitlements follow published programme terms or a written agreement."],
      ["Intellectual property", "MAXIMUS®, the lion emblem, the GPS mark and the content of this website are protected. Internal engineering formulas, QC protocols, layups, tooling, supplier identities, costing and protected methodology are not disclosed here."],
      ["Store", "The online store is operated separately under its own terms."],
    ],
  },
  notFound: { title: "Page not found", p: "The page you requested does not exist in this language.", cta: "Go to the homepage" },
};

export default en;
