/* Spanish dictionary — MAXIMUS website v4.0. Translated from content/en.js; numerical product data lives in data/products.js. */
const es = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — raquetas de tenis íntegramente de carbono diseñadas según especificación",
    defaultDescription:
      "Raquetas de tenis íntegramente de carbono, del marco al mango: GREAT 97 in², POWER 98 in² y SPIN 100 in², ocho medidas de empuñadura de fábrica L0–L7, clases de precisión para peso, balance, swingweight y rigidez, e ingeniería personalizada a petición.",
  },
  common: {
    statuses: {
      current: "Actual",
      agreement: "Disponible por acuerdo",
      development: "En desarrollo",
      concept: "Concepto",
      target: "Objetivo de fabricación",
      modelled: "Calculado",
      confirmed: "Confirmado",
      requested: "Arquitectura solicitada",
      notprovided: "No facilitado",
    },
    brief: { who: "Para quién es", value: "Qué obtiene", now: "Confirmado ahora", next: "Siguiente paso" },
    labels: {
      next: "Siguiente",
      back: "Atrás",
      edit: "Editar respuestas",
      review: "Revisión",
      start: "Comenzar",
      restart: "Empezar de nuevo",
      copy: "Copiar el texto de la solicitud",
      copied: "Copiado",
      openEmail: "Abrir el correo para enviar esta solicitud",
      reference: "Referencia de la solicitud",
      weight: "Peso",
      balance: "Balance",
      swingweight: "Swingweight",
      stiffness: "Rigidez",
      grip: "Medida de empuñadura",
      headSize: "Tamaño de cabeza",
      series: "Serie",
      precisionClass: "Clase de precisión",
      quantity: "Cantidad",
      notProvided: "Aún no publicado",
      requestTarget: "Objetivo solicitado",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Leer más",
      allSeries: "Todas las series",
      points: "pesos listados",
      optional: "opcional",
      required: "obligatorio",
      select: "Seleccionar",
      yes: "Sí",
      no: "No",
      unknown: "No estoy seguro",
      custom: "Objetivo personalizado",
      listed: "Peso listado",
      individual: "Raqueta individual",
      pair: "Par emparejado",
      triple: "Trío emparejado",
      team: "Conjunto de equipo",
      summaryTitle: "Resumen de su solicitud",
      nextAction: "Siguiente acción",
      status: "Estado",
      learn: "Más información",
      schematic: "Esquema — no es una medición",
      photo: "Fotografía",
    },
    ecosystemStrip: "El ecosistema MAXIMUS",
    truth: {
      noPrices: "Los precios, las cantidades mínimas, los plazos de entrega, las garantías y los compromisos de entrega se confirman por escrito para cada mercado y cada programa.",
      requestNotOrder: "Una solicitud es una solicitud de revisión. No es un pedido aceptado, un compromiso de fabricación ni una cita confirmada.",
      noGuarantee: "Ningún equipamiento, método o programa descrito aquí garantiza un resultado para un jugador concreto.",
      governing: "Esta página se publica en varios idiomas. La versión en inglés es la que prevalece; la traducción se ofrece para facilitar la lectura.",
    },
  },
  nav: {
    language: "Idioma",
    groups: { racquets: "Raquetas", training: "Entrenamiento", ecosystem: "Ecosistema", partnerships: "Alianzas" },
    racquets: "Series de raquetas y comparación",
    great: "GREAT — 97 in² · Control",
    power: "POWER — 98 in² · Potencia",
    spin: "SPIN — 100 in² · Efecto",
    precision: "Precisión y rigidez",
    grip: "Arquitectura de empuñadura de fábrica L0–L7",
    custom: "Ingeniería personalizada",
    training: "Sistemas de entrenamiento",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodología",
    gps: "MAXIMUS GPS",
    build: "Configurador",
    choose: "Ayúdenme a elegir",
    ecosystem: "Mapa del ecosistema",
    engineering: "Ingeniería y fabricación",
    experience: "Experiencia y adaptación",
    brands: "Marcas personales y embajadores",
    families: "Familias y padres",
    owners: "Propietarios y la bóveda del propietario",
    network: "Sports Network",
    partnerships: "Todas las vías de colaboración",
    coaches: "Entrenadores",
    clubs: "Clubes y academias",
    distribution: "Distribución y desarrollo de país",
    strategic: "Estratégico e inversión",
    institutional: "Programas institucionales",
    contact: "Contacto",
    legal: "Identidad jurídica",
    privacy: "Privacidad",
    terms: "Condiciones",
    menu: "Menú",
    close: "Cerrar",
    home: "Inicio",
    skip: "Saltar al contenido",
  },
  footer: {
    line: "La raqueta MAXIMUS es su llave al mundo MAXIMUS.",
    product: "Producto",
    ecosystem: "Ecosistema",
    company: "Organización",
    instagram: "Instagram",
    email: "Email",
    analytics: "Configuración de analítica",
    rights: "MAXIMUS® y el emblema del león son marcas del ecosistema MAXIMUS. MIPA: control interno de PI, procedencia y documentación.",
    boundary:
      "Las condiciones comerciales y contractuales se acuerdan por separado y por escrito. La compra de una raqueta no crea la condición de miembro institucional, derechos de inversión, titularidad de propiedad intelectual ni derecho a regalías.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "La precisión empieza en el impacto.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer y la metodología MAXIMUS conectan la práctica específica con raquetas de rendimiento íntegramente de carbono.",
    heroCta1: "Descubra el sistema de entrenamiento",
    heroCta2: "Descubra GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Control",
    heroMeta: [
      ["Íntegramente de carbono", "del marco al mango"],
      ["4 parámetros", "peso · balance · swingweight · rigidez"],
      ["8 medidas de empuñadura", "geometría de fábrica L0–L7"],
      ["3 series de rendimiento", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Empiece aquí",
      title: "Elija su vía",
      items: {
        player: { h: "Jugador", p: "Encuentre una raqueta por nivel y prioridades, o configúrela directamente.", a: "Encuentre su raqueta" },
        parent: { h: "Padre o madre", p: "Una vía por escrito para los objetivos de desarrollo, la participación del entrenador y el equipamiento adecuado.", a: "Vía familiar" },
        coach: { h: "Entrenador, club o academia", p: "Sistemas de entrenamiento, adaptación, conjuntos de equipo y personalización.", a: "Vías para entrenadores y clubes" },
        partner: { h: "Distribuidor o socio", p: "Vías de distribución, desarrollo de país, estratégicas e institucionales.", a: "Vías de colaboración" },
      },
    },
    series: {
      eyebrow: "Series de rendimiento",
      title: "Tres arquitecturas de rendimiento. Una plataforma de ingeniería.",
      lead: "Elija la serie por dirección de juego y complete después la configuración: clase de precisión, peso, empuñadura, personalización.",
      cta: "Compare las series",
      configure: "Configurar",
      open: "Abrir la serie",
      photoPending: "Fotografía aún no publicada",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Sistema de Precisión MAXIMUS",
      title: "Peso. Balance. Swingweight. Rigidez.",
      sub: "Controlados como un único sistema de ingeniería.",
      lead: "Tres clases de precisión definen con qué exactitud se ajusta cada raqueta terminada a su especificación declarada. P0.5 es una tolerancia estrecha bajo un protocolo de medición definido — no un error cero.",
      cta: "La precisión y la rigidez en detalle",
    },
    stiffness: {
      eyebrow: "Rigidez",
      title: "Respuesta repetible del marco frente a un objetivo declarado.",
      p: "La rigidez del marco determina la respuesta, la sensación y la consistencia entre raquetas. MAXIMUS la trata como el cuarto parámetro controlado: el objetivo, el resultado medido, la tolerancia permitida y la capacidad del instrumento se conservan como registros separados. El beneficio es la repetibilidad, no un resultado garantizado para cada jugador.",
      cols: [["Respuesta", "Cómo devuelve el marco la energía en el impacto."], ["Sensación", "Lo que percibe el jugador en el impacto."], ["Consistencia", "Las raquetas construidas según la misma especificación responden igual dentro de su clase."]],
      schematicCaption: "Esquema: desviación permitida en torno a un objetivo de rigidez declarado para cada clase. No es una medición; no se implica ningún valor RA.",
      bands: { p25: "tolerancia objetivo ±1 RA", p15: "tolerancia objetivo ±0.5 RA", p05: "cumple el valor RA objetivo declarado bajo el protocolo de medición de fábrica establecido — no un error cero", target: "objetivo declarado (no se implica ningún valor)" },
    },
    carbon: {
      eyebrow: "Estándar de construcción",
      title: "Íntegramente de carbono. Del marco al mango.",
      p: "Todas las raquetas MAXIMUS actuales de esta plataforma son íntegramente de carbono en su estructura, incluido el mango. No se usa espuma para formar el mango.",
      gripTitle: "Ocho medidas de empuñadura de fábrica. L0–L7.",
      gripP: "Cada medida es geometría de fábrica del mango de carbono, no un engrosamiento con overgrips.",
      scaleCaption: "Esquema: designaciones nominales de empuñadura L0–L7 (de 4″ a 4⅞″). No son dimensiones medidas del mango.",
      cta: "Arquitectura de empuñadura de fábrica",
    },
    custom: {
      eyebrow: "Ingeniería personalizada",
      title: "Diseñada según especificación.",
      sub: "La gama estándar es el punto de partida.",
      p: "MAXIMUS acepta requisitos técnicos que van más allá de las matrices publicadas para su evaluación, ingeniería, validación y fabricación según una especificación acordada. La viabilidad se confirma por escrito.",
      chain: ["Definir", "Diseñar", "Validar", "Especificar", "Producir", "Medir / registrar"],
      cta: "Enviar un pliego técnico",
      cta2: "Tratar la ingeniería personalizada",
    },
    training: {
      eyebrow: "Sistemas de entrenamiento",
      title: "Un sistema de entrenamiento construido en torno al impacto.",
      p: "Sweet Spot Trainer, la metodología MAXIMUS y Spot Trainer conectan el equipamiento con la práctica dirigida por el entrenador: impacto centrado, control, carga progresiva y el retorno a la raqueta de rendimiento.",
      cta: "Sistemas de entrenamiento",
      cta2: "Solicitar una demostración",
      photoPending: "Fotografía del equipo de entrenamiento aún no publicada",
      sstP: "Una cabeza de entrenamiento de 50 in² para la práctica del impacto centrado, con cuatro configuraciones de peso para la carga que seleccione el entrenador.",
      sstCta: "Descubra Sweet Spot Trainer",
      sstCaption: "Configuración de 300 g, una de cuatro",
      methodP: "Fije objetivos, seleccione el equipamiento, practique con la participación del entrenador, registre observaciones, reevalúe, ajuste y traslade el trabajo al juego de rendimiento.",
      methodCta: "Descubra la metodología",
      spotP: "Una pequeña diana redonda para practicar un punto de impacto preciso y repetible.",
      spotCta: "Descubra Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Fabricación y control de calidad",
      title: "Construida según una especificación. Medida y registrada.",
      p: "La producción sigue la especificación escrita de cada pedido. Los registros dependen de la clase de precisión: registros de producción conservados para P2.5, registros individuales y trazabilidad para P1.5, control individual y documentación para P0.5 cuando el programa del pedido los implementa.",
      confirmedTitle: "Confirmado",
      confirmed: ["Construcción íntegramente de carbono, del marco al mango.", "Clases de precisión P2.5, P1.5 y P0.5 con cuatro parámetros controlados.", "Ocho medidas de empuñadura de fábrica L0–L7."],
      pendingTitle: "Aún no publicado",
      pending: "Las fotografías del equipo de medición, los registros de control de calidad de muestra y las imágenes de fábrica aún no se han publicado. Nada de esta página es un certificado de medición.",
      captions: { lettering: "Letras MAXIMUS brillantes sobre el marco mate", buttcap: "Empuñadura y tapa del mango con la marca del león", handle: "Grabado de personalización en plata", finish: "Cabeza y plano de cordaje" },
      cta: "Ingeniería y fabricación",
    },
    world: {
      eyebrow: "El mundo MAXIMUS",
      title: "Una llave. Un ecosistema. Oportunidades ilimitadas.",
      note: "“Oportunidades ilimitadas” es una expresión de marca, no una promesa de viabilidad técnica, ingresos o acceso ilimitados. Una compra no crea regalías, rendimientos de inversión, patrocinio ni financiación del desarrollo de un jugador.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — y su navegación en el mundo del tenis: un perfil de equipamiento guiado que se responde por escrito." },
        personal: { h: "Personalización", p: "Nombres, iniciales, números e identificación de equipo, con el grabado en plata aprobado." },
        development: { h: "Desarrollo", p: "Sistemas de entrenamiento dirigidos por el entrenador, registros y reevaluación." },
        ecosystem: { h: "Ecosistema ampliado", p: "Marcas personales, registros de propietario, red, licencias y programas institucionales: cada uno con su estado real." },
      },
      cta: "Descubra el ecosistema",
    },
    partners: {
      eyebrow: "Vías de colaboración",
      title: "Entrenadores, clubes, distribuidores y socios.",
      p: "Primero la cualificación por escrito. Los derechos de país, la exclusividad y las condiciones comerciales se negocian por escrito, nunca se conceden a través de un formulario.",
      cta: "Todas las vías de colaboración",
      formTitle: "Consulta breve",
      formLead: "Elija el propósito y escriba a MAXIMUS. Recibirá un ID de solicitud en esta página.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "SU NAVEGACIÓN EN EL MUNDO DEL TENIS" } },
    personal: { eyebrow: "Personalización", title: "Su nombre. Su número. Su MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tres series. Parámetros reales." },
    map: { cta: "Descubra el ecosistema" },
  },
  racquets: {
    title: "Raquetas",
    lead: "Tres series de rendimiento que comparten estándar de construcción, sistema de precisión y arquitectura de empuñadura de fábrica. Cada serie es una arquitectura de rendimiento establecida dentro de una plataforma de ingeniería más amplia.",
    direction: { control: "Control", power: "Potencia", spin: "Efecto" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Dirección de juego principal",
    compareTitle: "Comparación de series",
    compareLead: "Solo datos de arquitectura confirmados. Los patrones de cordaje, las longitudes, los perfiles del marco, los rangos de tensión, el swingweight y los valores nominales de rigidez de estas series no se publican; se recogen como objetivos solicitados para revisión técnica.",
    columns: { series: "Serie", head: "Tamaño de cabeza", direction: "Dirección", weights: "Pesos listados", range: "Rango de peso", balance: "Datos de balance" },
    balanceModelled: "Valores calculados",
    balanceNotProvided: "Aún no publicado",
    construction: "Construcción: íntegramente de carbono, del marco al mango · Precisión: P2.5 / P1.5 / P0.5 · Empuñaduras: L0–L7",
    otherTitle: "Otros deportes de raqueta",
    otherLead: "Direcciones de desarrollo aprobadas. No existen productos comercializables en estas categorías y no se transfiere a ellas ninguna especificación de tenis.",
    other: { padel: "Pádel", pickleball: "Pickleball", squash: "Squash", badminton: "Bádminton", racquetball: "Racquetball", beachTennis: "Tenis playa" },
    ctaConfigure: "Configurar una solicitud",
    ctaSeries: "Abrir la serie",
  },
  seriesPage: {
    eyebrow: "Series de rendimiento",
    intro: {
      great: "La arquitectura GREAT de 97 in² está construida en torno al control: cabeza compacta, impacto preciso y confianza direccional.",
      power: "La arquitectura POWER de 98 in² está construida en torno a la transferencia de energía: profundidad y velocidad desde un marco estable.",
      spin: "La arquitectura SPIN de 100 in² está construida en torno al comportamiento de la pelota: rotación, margen y trazado de la trayectoria.",
    },
    photoPending: "Fotografía de la serie aún no publicada",
    detailPending: "Las fotografías de detalle de la construcción y del mango de esta serie aún no se han publicado.",
    specsTitle: "Especificación y estado",
    catalogue: {
      eyebrow: "Catálogo de la serie {series}",
      title: "{n} variantes de peso",
      lead: "Todas las variantes de la serie {series}, ordenadas por peso. Peso en gramos, balance en milímetros desde el tope del mango. Cada visualización se muestra completa: nada recortado, enmascarado ni estirado.",
      selectLabel: "Elija una variante de peso",
      select: "Mostrar esta variante",
      selected: "Mostrada arriba",
      balanceLabel: "Balance",
      headLabel: "Tamaño de cabeza",
      constructionLabel: "Construcción",
      gripsLabel: "Medidas de empuñadura de fábrica",
      precisionLabel: "Clases de precisión",
      balanceConfirmed: "El balance es el valor confirmado para este peso y coincide con la cifra impresa en la visualización. Los precios, el stock y los plazos de entrega no se publican aquí.",
      balanceModelled: "El balance es un valor calculado para este peso listado, no una medición individual de fábrica; coincide con la cifra impresa en la visualización. Los precios, el stock y los plazos de entrega no se publican aquí.",
      zoom: "Abrir la imagen",
      close: "Cerrar",
      allTitle: "Todas las {n} variantes",
    },
    specs: { head: "Tamaño de cabeza", direction: "Dirección principal", weights: "Pesos listados", range: "Rango de peso", balance: "Balance", construction: "Construcción", grips: "Empuñaduras de fábrica", precision: "Clases de precisión" },
    construction: "Íntegramente de carbono, del marco al mango",
    statusTitle: "Estado de los valores",
    matrixTitle: "Matriz completa de pesos",
    matrixLead: "Los pesos listados son la selección estándar. Otros pesos pueden solicitarse como objetivos personalizados; no se insertan valores intermedios que falten.",
    balanceNote: {
      confirmed: "Los valores de balance están confirmados para cada peso listado (mm desde el tope del mango) y coinciden con la cifra impresa en la visualización de ese peso. No se calculan aquí ni se suavizan entre pesos vecinos; la base de medición se confirma en la especificación escrita.",
      modelled: "Los valores de balance se calculan para cada peso listado (mm desde el tope del mango). No son mediciones individuales de fábrica; la base de medición se confirma en la especificación escrita.",
      notprovided: "Los valores de balance de esta serie no se facilitan. No los deduzca de otra serie.",
    },
    optionsTitle: "Precisión, empuñadura y peso",
    notPublished: "No publicado para esta serie: patrón de cordaje, longitud, perfil del marco, rango de tensión, swingweight y valores de rigidez. Puede indicarlos como objetivos solicitados para revisión técnica.",
    offerTitle: "Qué ocurre después de su solicitud",
    offerSteps: [
      ["Solicitud", "Envíe una configuración o una pregunta. El ID de solicitud se muestra de inmediato."],
      ["Revisión", "MAXIMUS revisa la serie, la clase, el peso, la empuñadura y cualquier objetivo solicitado."],
      ["Respuesta por escrito", "La especificación, la disponibilidad y las condiciones comerciales se confirman por escrito."],
    ],
    faqTitle: "Preguntas",
    faq: [
      ["¿Se miden los valores de balance?", "Se calculan para los pesos listados; no son mediciones individuales. La base de medición se confirma en la especificación escrita."],
      ["¿Puedo solicitar un peso que no esté listado?", "Sí, como objetivo personalizado en gramos enteros. Se revisa técnicamente y la viabilidad se confirma por escrito."],
      ["¿Qué cambia la clase de precisión?", "Con qué exactitud se ajustan el peso, el balance, el swingweight y la rigidez a la especificación declarada, y qué registros se conservan."],
      ["¿La empuñadura se engrosa con overgrips?", "No. L0–L7 son geometrías de mango de carbono de fábrica."],
      ["¿Dónde están los precios y los plazos de entrega?", "Se confirman por escrito para cada solicitud y no se publican aquí."],
    ],
    faqSpinBalance: ["¿De dónde proceden los valores de balance de SPIN?", "De la tabla confirmada de la serie Spin: 33 variantes de peso con el balance en milímetros desde el tope del mango. Cada pareja coincide con la cifra impresa en la visualización aprobada de ese peso. Los valores no se calculan ni se suavizan entre pesos vecinos."],
    ctaBuild: "Configurar esta serie",
    ctaAsk: "Preguntar sobre esta serie",
    ctaCompare: "Comparar todas las series",
    weightsLabel: "pesos listados",
    headLabel: "cabeza",
  },
  precision: {
    title: "Precisión y rigidez",
    switch: { label: "Seleccione una clase de precisión", panelLabel: "Cuatro parámetros controlados —", qcLabel: "Arquitectura de control de calidad", protocolNote: "bajo el protocolo definido de medición de control de calidad de fábrica", fullTable: "Tabla comparativa completa" },
    lead: "Cuatro parámetros controlados como un único sistema de ingeniería. Cada clase define con qué exactitud se ajusta una raqueta terminada a su especificación declarada y qué registros de calidad se producen.",
    statement: "Peso. Balance. Swingweight. Rigidez. Controlados como un único sistema de ingeniería.",
    classes: {
      "P2.5": { name: "Núcleo de rendimiento escalable", qc: "Medición individual y registros de producción conservados." },
      "P1.5": { name: "Precisión avanzada", qc: "Medición individual, registros individuales y trazabilidad." },
      "P0.5": { name: "Profesional · control individual", qc: "Control individual con valores nominales y reales y registros de medición individuales; identidad de serie, trazabilidad de lote, certificado de precisión y conjuntos emparejados cuando el programa del pedido los implementa." },
    },
    columns: { cls: "Clase", weight: "Peso", balance: "Balance", sw: "Swingweight", stiff: "Rigidez", qc: "Arquitectura de control de calidad" },
    stiffTarget: "tolerancia objetivo",
    stiffExact: "cumple el valor RA objetivo declarado bajo el protocolo de medición de fábrica establecido",
    programmeNote: "La identidad de serie, los certificados y la documentación de conjuntos emparejados se emiten únicamente cuando el programa de un pedido concreto los implementa.",
    targetsNote: "Las especificaciones de rigidez son objetivos de fabricación hasta que el protocolo correspondiente y la evidencia de producción respalden una afirmación más firme. La propuesta de arquitectura no implica que cada configuración listada haya superado ya un proceso completo de liberación de cuatro parámetros.",
    stiffnessTitle: "Por qué importa la rigidez",
    stiffnessP1: "La rigidez del marco influye en cómo responde en el impacto, en cómo se siente y en la consistencia entre dos raquetas. El beneficio central de controlarla es una respuesta repetible frente a una especificación declarada.",
    stiffnessP2: "Antes de publicar una conformidad verificada, el registro interno de control de calidad identifica el instrumento, su estado de calibración, el método, el estado de la raqueta, la resolución, la incertidumbre de medición, las mediciones repetidas, la regla de redondeo y la regla de aceptación. Un número entero idéntico en pantalla no es prueba de variación física cero ni de error de medición cero.",
    fields: ["Objetivo", "Resultado medido", "Tolerancia permitida", "Capacidad del instrumento"],
    fieldsNote: "Se conservan como campos separados en cada registro.",
    matchedTitle: "Conjuntos emparejados",
    matchedP: "Los criterios de los conjuntos emparejados se definen por separado de la tolerancia individual. La conformidad de cada raqueta con su tolerancia nominal no prueba por sí sola una diferencia máxima concreta entre dos raquetas. Los pares, tríos y conjuntos de equipo emparejados se solicitan a través del configurador y se confirman por escrito.",
    extendedTitle: "Modelo técnico ampliado",
    extendedP: "El modelo de datos admite parámetros adicionales. Todavía no existen valores ni clases de tolerancia para ellos; pueden indicarse como objetivos solicitados en un pliego técnico.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Comportamiento torsional", length: "Longitud", beamProfile: "Perfil del marco", headGeometry: "Geometría de la cabeza", stringPattern: "Patrón de cordaje", durability: "Durabilidad", vibration: "Características de vibración" },
    noZero: "MAXIMUS no describe su gama como de tolerancia cero. La precisión se indica como una clase con una tolerancia declarada y una arquitectura de control de calidad definida.",
    cta: "Configurar con una clase de precisión",
  },
  grip: {
    title: "Arquitectura de empuñadura de fábrica",
    statement: "Ocho medidas de empuñadura de fábrica. L0–L7.",
    lead: "La geometría de la empuñadura forma parte de la arquitectura del mango de carbono. Cada medida se fabrica como geometría del mango, no se engrosa con overgrips.",
    emph: "Medidas ampliadas",
    p1: "La gama de fábrica de ocho medidas da a entrenadores y jugadores un rango de configuración más amplio para especificar el equipamiento en torno al jugador, incluidas las geometrías mayores L6 y L7.",
    p2: "La designación nominal de la empuñadura es distinta de las dimensiones estructurales brutas del mango y del protocolo de medición final. Las medidas se aplican a las series de rendimiento y a las familias de entrenamiento de esta plataforma.",
    p3: "No se reclama ninguna exclusividad mundial para esta gama.",
    columns: { size: "Medida", nominal: "Valor nominal", family: "Se aplica a" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Configurar con su medida de empuñadura",
  },
  custom: {
    title: "Ingeniería personalizada",
    statement: "Diseñada según especificación.",
    sub: "La gama estándar es el punto de partida.",
    lead: "MAXIMUS acepta requisitos técnicos que van más allá de las matrices de configuración publicadas para su evaluación, ingeniería, validación y fabricación según una especificación acordada. La viabilidad se confirma mediante revisión: no toda solicitud imaginable es física o comercialmente viable.",
    scopeTitle: "Qué puede abordar un pliego técnico",
    scope: ["Geometría de la cabeza y del marco", "Longitud", "Peso", "Balance", "Swingweight", "Rigidez", "Twistweight", "Geometría de la empuñadura", "Construcción", "Conjuntos emparejados", "Marcos de entrenamiento", "Decoración y grabado", "Programas de identidad y de equipo", "Desarrollo dependiente de utillaje"],
    processTitle: "Proceso",
    process: [
      ["Definir", "Objetivos preferidos, límites obligatorios, uso previsto y compromisos aceptables."],
      ["Diseñar", "Evaluación de ingeniería frente a la plataforma y el utillaje."],
      ["Validar", "Validación frente a la especificación acordada."],
      ["Especificar", "Una especificación escrita con base de medición y tolerancias."],
      ["Producir", "Producción según la especificación."],
      ["Medir / registrar", "Medición y registros conservados según la clase de precisión aplicable."],
    ],
    formTitle: "Enviar un pliego técnico",
    formLead: "Distinga los objetivos preferidos de los límites obligatorios. El resultado es una solicitud de revisión técnica, no un pedido de fabricación aceptado automáticamente.",
    protected: "Las recetas de laminado, el utillaje, la identidad de los proveedores, los costes internos y el conocimiento protegido no se divulgan por esta vía.",
    cta: "Enviar un pliego técnico",
  },
  training: {
    title: "Sistemas de entrenamiento",
    lead: "Dos familias de entrenamiento con sus propios estándares de producción, conectadas por una sola metodología: práctica dirigida por el entrenador, registros, reevaluación y retorno al juego de rendimiento.",
    sst: { h: "Sweet Spot Trainer", p: "Una raqueta de entrenamiento de cabeza reducida de 50 in² en un sistema de cuatro pesos para la práctica del impacto centrado, la percepción del punto dulce, el control de la raqueta y la carga progresiva." },
    spot: { h: "Spot Trainer", p: "Entrenamiento del punto de impacto con una pequeña diana redonda de impacto, sobre la base aprobada de cuatro pesos." },
    method: { h: "Metodología", p: "Establecer objetivos, seleccionar el equipamiento con la participación del entrenador, usar el sistema correspondiente, registrar, reevaluar, ajustar y trasladar." },
    experience: "Sosténgala. Muévala. Siéntala.",
    experienceP: "Solicite una prueba, una adaptación o una demostración con apoyo del entrenador. Una solicitud enviada no es una cita confirmada.",
    cta: "Solicitar una adaptación o demostración",
    distinct: "Sweet Spot Trainer, Spot Trainer y cualquier dispositivo de demostración independiente son productos distintos y nunca se fusionan.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Una categoría de entrenamiento independiente con su propio estándar de producción. La cabeza de 50 in² centra la atención en la zona de impacto; los cuatro pesos aportan la progresión de carga.",
    baseline: "Base confirmada",
    columns: { head: "Cabeza", length: "Longitud", pattern: "Patrón de cordaje", grips: "Empuñaduras de fábrica" },
    systemTitle: "Sistema de cuatro raquetas",
    detailsTitle: "Detalles de construcción",
    systemLead: "Peso y balance tal como se suministran. La base de medición se registra por separado y aún no se ha publicado.",
    purposeTitle: "Propósito",
    purpose: ["Práctica del impacto centrado", "Percepción del punto dulce", "Control de la raqueta", "Carga progresiva", "Desarrollo dirigido por el entrenador", "Retorno a la raqueta de rendimiento del jugador"],
    heavy: "El modelo de 400 g es una configuración de entrenamiento controlada. No se recomienda automáticamente a niños, principiantes ni a todos los jugadores; el entrenador define la carga, la duración y la progresión.",
    precisionNote: "Las clases de precisión de rendimiento P2.5, P1.5 y P0.5 no se aplican automáticamente a esta familia de entrenamiento. Las tolerancias de producción de entrenamiento siguen la especificación aprobada propia de la familia.",
    health: "No se promete prevención ni tratamiento del codo de tenista, eliminación de lesiones ni mejora garantizada.",
    cta: "Solicitar una demostración de Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Entrenamiento del punto de impacto con una pequeña diana redonda de impacto. Un producto distinto con su propia identidad visual, construido sobre la base aprobada de cuatro pesos.",
    purposeTitle: "Propósito confirmado",
    purposeP: "Entrenar al jugador para encontrar y repetir un punto de impacto preciso.",
    weightsTitle: "Progresión de pesos",
    weightsP: "La progresión de pesos sigue la base de pesos aprobada de Sweet Spot Trainer. Los valores de balance y otras especificaciones de Sweet Spot Trainer no se trasladan a Spot Trainer.",
    dims: "Las dimensiones exactas de la diana aún no se han publicado.",
    grips: "Arquitectura de empuñadura de fábrica L0–L7.",
    notes: ["Las clases de precisión de rendimiento no se aplican automáticamente.", "No es una raqueta convencional en miniatura y no se publica ningún patrón de cordaje.", "Spot Trainer, Sweet Spot Trainer y cualquier dispositivo de demostración independiente permanecen distinguibles."],
    cta: "Preguntar sobre Spot Trainer",
  },
  methodology: {
    title: "Metodología y experiencia de producto",
    lead: "El equipamiento es una parte de un recorrido de desarrollo estructurado. El método empieza por los objetivos del jugador, no por una etiqueta de producto.",
    stepsTitle: "El recorrido de desarrollo",
    steps: [
      ["Establecer objetivos", "Los objetivos del jugador y su punto de partida."],
      ["Seleccionar el equipamiento", "Equipamiento adecuado seleccionado con la participación del entrenador."],
      ["Usar el sistema", "El sistema de entrenamiento correspondiente, dirigido por el entrenador."],
      ["Registrar", "Observaciones de la participación real, sin puntuaciones inventadas."],
      ["Reevaluar", "Puntos de control comparables."],
      ["Ajustar", "Ajustes de configuración o de programa."],
      ["Trasladar", "El aprendizaje se traslada al juego de rendimiento."],
    ],
    educationTitle: "Vías de formación",
    education: { player: "Jugadores: comprender la configuración, la carga y la progresión.", parent: "Padres y madres: continuidad del desarrollo, equipamiento adecuado, registros y derechos.", coach: "Entrenadores: sistemas de entrenamiento, adaptación, evaluación y uso autorizado de los programas." },
    evidenceTitle: "Disciplina de la evidencia",
    evidenceP: "Los registros de participación real y las observaciones se conservan con su clasificación: declarado por el participante, confirmado por el tutor, validado por el entrenador o medido por el sistema. El progreso, las puntuaciones y la validación nunca se inventan.",
    experienceTitle: "Sosténgala. Muévala. Siéntala.",
    experienceP: "Puede solicitarse una prueba, una adaptación o una demostración con apoyo del entrenador. Una solicitud enviada no es una cita confirmada.",
    cta: "Solicitar adaptación o demostración",
    cta2: "Consulta de colaboración para entrenadores",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — perfil de equipamiento guiado",
    title: "MAXIMUS GPS",
    lead: "Un perfil de equipamiento guiado. Responda solo lo que sea pertinente; revise y corrija sus respuestas; reciba un resumen, las direcciones de configuración aplicables y una siguiente acción real.",
    honesty: "En esta versión no hay reglas de adaptación automática aprobadas. Por eso GPS produce un resumen claro de requisitos y señala direcciones de configuración; los detalles del equipamiento se envían a revisión experta.",
    rulesVersion: "Versión de las reglas",
    dataVersion: "Versión de los datos de producto",
    steps: { role: "Función", sport: "Deporte", experience: "Experiencia", objectives: "Objetivos", style: "Estilo de juego", equipment: "Equipamiento actual", preference: "Preferencias", coach: "Participación del entrenador", ageBand: "Franja de edad", review: "Revisión" },
    notStored: "No se guarda en este navegador.",
    ageNote: "Se usa únicamente para encaminar la solicitud. No se pide nombre, fecha de nacimiento ni información médica.",
    q: {
      role: "¿Cuál le describe?",
      sport: "¿Qué deporte?",
      experience: "Nivel de experiencia",
      objectives: "¿Qué es lo más importante? (seleccione hasta tres)",
      style: "Estilo de juego, si lo conoce",
      equipment: "Equipamiento actual, si lo hay",
      equipmentHint: "Marca y modelo, peso o empuñadura si los conoce. Opcional.",
      preference: "Configuración preferida o medida de empuñadura conocida",
      grip: "Medida de empuñadura conocida",
      coach: "¿Participa un entrenador en sus decisiones de equipamiento?",
      ageBand: "Franja de edad del jugador (solo se usa para encaminar la solicitud adecuadamente)",
    },
    roles: { player: "Jugador", parent: "Padre, madre o tutor", coach: "Entrenador", club: "Club o academia", other: "Otro" },
    sports: { tennis: "Tenis", padel: "Pádel", pickleball: "Pickleball", squash: "Squash", badminton: "Bádminton", other: "Otro deporte de raqueta" },
    sportNote: "Existen productos para tenis. Los demás deportes son direcciones de desarrollo; su interés se registra para el programa correspondiente.",
    experience: { beginner: "Principiante", developing: "En progresión", intermediate: "Intermedio", advanced: "Avanzado", competitive: "Competitivo", professional: "Profesional" },
    objectives: { control: "Control", power: "Potencia", spin: "Efecto", comfort: "Comodidad", manoeuvrability: "Manejabilidad", development: "Desarrollo a largo plazo", competition: "Competición", training: "Sistema de entrenamiento", team: "Equipo o conjunto emparejado", personal: "Personalización" },
    styles: { baseline: "Juego de fondo", allcourt: "Juego completo", attacking: "Ofensivo", defensive: "Defensivo", coach: "Elegido por el entrenador", unknown: "No estoy seguro" },
    ageBands: { u10: "Menos de 10 años", u14: "10–13", u18: "14–17", adult: "18 años o más" },
    output: {
      title: "Su perfil de equipamiento",
      status: "Se requiere revisión experta",
      statusP: "En esta versión no se produce ninguna coincidencia automática. Su perfil se ha resumido para revisión experta.",
      directionsTitle: "Direcciones de configuración aplicables",
      directionsP: "A partir de los objetivos que ha indicado y de la dirección de juego declarada de cada serie. Es una dirección, no una recomendación de adaptación.",
      trainingHint: "Sus objetivos incluyen un sistema de entrenamiento: consulte Sweet Spot Trainer y Spot Trainer.",
      teamHint: "Los conjuntos emparejados se solicitan a través del configurador y se confirman por escrito.",
      next1: "Enviar el perfil para revisión experta",
      show: "Mostrar mi perfil",
      configure: "Configurar",
      sendP: "Envíe su perfil a MAXIMUS para revisión experta. El ID de solicitud se muestra de inmediato; la respuesta llega por escrito.",
      otherSport: "Las raquetas MAXIMUS existen para tenis. Para otros deportes de raqueta no se sugiere ninguna serie de tenis; su interés se registra como dirección de desarrollo.",
      noDirection: "Sus objetivos no apuntan a una única dirección de juego. La revisión experta propone una configuración.",
      incomplete: "Faltan algunas respuestas obligatorias: use “Editar respuestas” para completarlas.",
    },
    privacy: "GPS no pide información de salud ni identificadores de menores. En esta sesión del navegador solo se conservan las respuestas de opción múltiple; el texto libre no se guarda.",
  },
  build: {
    title: "Configure la suya",
    lead: "Configure una solicitud: serie, clase de precisión, peso listado u objetivo personalizado, medida de empuñadura, objetivos solicitados, personalización, conjuntos emparejados y cantidad. El resultado es una solicitud de configuración con un ID de solicitud, no un SKU, un precio, una fecha de entrega ni un certificado.",
    steps: { series: "Serie", cls: "Clase de precisión", weight: "Peso", grip: "Empuñadura", targets: "Objetivos", personal: "Personalización", set: "Conjunto y cantidad", use: "Uso", review: "Revisión" },
    q: {
      series: "Elija una serie",
      cls: "Elija una clase de precisión",
      weightMode: "Peso",
      listed: "Peso listado",
      customWeight: "Peso solicitado (g)",
      balanceShown: "Balance calculado para este peso",
      balanceRequest: "Balance solicitado (mm)",
      grip: "Medida de empuñadura de fábrica",
      targetsTitle: "Objetivos solicitados",
      swingweight: "Swingweight solicitado (kg·cm²)",
      stiffness: "Rigidez solicitada (RA)",
      basis: "Base de medición de los valores solicitados",
      engraving: "Texto del grabado",
      engravingHint: "Nombre, iniciales o número. Letras latinas, dígitos, espacio, guion, apóstrofo y punto; hasta 24 caracteres. Se aceptan otros alfabetos para la confirmación del arte final.",
      engravingType: "Personalización",
      types: { none: "Ninguna", name: "Nombre del jugador", initials: "Iniciales", number: "Número del conjunto", academy: "Identificación del entrenador o de la academia", team: "Programa de equipo" },
      set: "Raqueta individual o conjunto emparejado",
      use: "Uso previsto",
      uses: { play: "Juego personal", competition: "Competición", coaching: "Entrenamiento", team: "Equipo o academia", retail: "Evaluación para venta en tienda o distribución", other: "Otro" },
      notes: "Requisitos técnicos adicionales",
    },
    classes: { "P2.5": "P2.5 — núcleo de rendimiento escalable", "P1.5": "P1.5 — precisión avanzada", "P0.5": "P0.5 — profesional, control individual" },
    stiffExactShort: "la rigidez cumple el valor RA objetivo declarado bajo el protocolo de fábrica establecido",
    clsNote: "Todas las clases controlan cuatro parámetros. P0.5 es una tolerancia estrecha bajo un protocolo de medición definido — no un error cero. La identidad de serie, los certificados y la documentación de conjuntos emparejados se aplican únicamente cuando el programa de su pedido los implementa.",
    listedNote: "De la matriz confirmada de la serie.",
    customNote: "Un peso fuera de la matriz, revisado técnicamente.",
    balanceCaption: "Cada peso listado muestra su balance calculado en mm desde el tope del mango. Los valores calculados no son mediciones individuales.",
    spinNote: "Los pesos de SPIN forman la arquitectura de pesos solicitada. El balance, el swingweight y la rigidez de SPIN no se facilitan; se definen en la revisión técnica.",
    customHint: "Gramos enteros, solo dígitos. Un peso personalizado es una solicitud de revisión técnica; la viabilidad se confirma por escrito y no se redondea ningún valor.",
    gripNote: "geometría de fábrica del mango de carbono, no un engrosamiento con overgrips",
    targetsLead: "Opcional. Introduzca solo los valores que necesite. Cada uno se registra como objetivo solicitado para revisión técnica, no como especificación publicada.",
    basisHint: "Obligatorio cuando solicita un peso personalizado o cualquier objetivo: ¿los valores se refieren a una raqueta sin encordar o encordada?",
    inputRange: "Entrada aceptada: {min}–{max}.",
    inputRangeNote: "Los rangos de entrada solo filtran entradas imposibles. No describen la capacidad de producción.",
    listedBasis: "valores listados: la base de medición se confirma en la especificación escrita",
    notStored: "No se guarda en este navegador; vuelva a introducirlo si recarga la página.",
    artworkReview: "se requiere confirmación del arte final",
    previewNote: "No se muestra vista previa visual: aún no se ha publicado una plantilla de grabado aprobada para este modelo. Su texto se recoge para la confirmación del arte final.",
    teamSub: "4–99 raquetas por conjunto",
    setsLabel: { individual: "Número de raquetas", pair: "Número de pares emparejados", triple: "Número de tríos emparejados", team: "Número de conjuntos de equipo" },
    teamSizeLabel: "Raquetas por conjunto de equipo",
    totalLabel: "Raquetas en total",
    racquetsUnit: "raquetas",
    setRule: "La cantidad cuenta conjuntos: un par emparejado son 2 raquetas por conjunto; un trío emparejado, 3.",
    restart: "Iniciar una nueva configuración",
    notices: { weightCleared: "{w} g no está en la matriz de {series}, por lo que se ha borrado el peso. Elija un peso listado o solicite un objetivo personalizado." },
    reviewTitle: "Solicitud de configuración",
    reviewP: "Compruebe la configuración y añada después sus datos de contacto. La solicitud se guarda con un ID de solicitud y se responde por escrito; la disponibilidad y las condiciones comerciales se confirman por escrito.",
    reviewErrors: "Algunas respuestas de la configuración necesitan revisión:",
    edit: "Editar",
    fieldNames: { series: "Serie", cls: "Clase de precisión", mode: "Selección de peso", weight: "Peso listado", customWeight: "Peso solicitado", basis: "Base de medición", balanceReq: "Balance solicitado", sw: "Swingweight solicitado", ra: "Rigidez solicitada", grip: "Medida de empuñadura", ptype: "Personalización", engraving: "Texto del grabado", setType: "Tipo de conjunto", sets: "Cantidad", teamSize: "Raquetas por conjunto de equipo", use: "Uso previsto", notes: "Requisitos adicionales" },
    status: { listed: "peso listado", requestedArchitecture: "arquitectura de pesos solicitada", technicalReview: "solicitud de revisión técnica", notPublished: "no facilitado", requestedCondition: "condición solicitada" },
    chooseLink: "¿No sabe qué serie le conviene? Reciba ayuda para elegir",
    cta: "Enviar la solicitud de configuración",
  },
  experience: {
    title: "Experiencia y adaptación",
    statement: "Sosténgala. Muévala. Siéntala.",
    lead: "Solicite una prueba, una adaptación o una demostración con apoyo del entrenador. Las solicitudes se revisan y se responden por escrito; una solicitud enviada no es una cita confirmada.",
    optionsTitle: "Qué se puede solicitar",
    options: ["Prueba de raquetas", "Sesión de adaptación", "Demostración con apoyo del entrenador", "Demostración de Sweet Spot Trainer o Spot Trainer", "Jornada de demostración para equipo o academia"],
    formTitle: "Solicitud de adaptación o demostración",
  },
  engineering: {
    title: "Ingeniería y fabricación",
    statement: "Aviones. Yates. Raquetas.",
    lead: "Una sola filosofía de ingeniería en tres entornos: los principios que dan forma a un avión, la precisión que guía un yate en mar abierto, el rendimiento que define cada raqueta MAXIMUS. Un relato de ingeniería, no una afirmación de certificación aeronáutica, propiedad de yates, propiedad de fábrica ni transferencia directa de materiales.",
    manifesto: ["Creemos que la gran ingeniería no tiene fronteras.", "Una sola filosofía. Diseñada sin concesiones."],
    capabilityTitle: "Capacidad de fabricación",
    capabilityLead: "La capacidad se muestra como una secuencia, no como un eslogan.",
    sequence: [
      ["Especificación", "Serie, clase de precisión, peso, balance, swingweight, objetivo de rigidez, geometría de la empuñadura, personalización."],
      ["Producción", "Construcción íntegramente de carbono del marco al mango, producida según la especificación."],
      ["Control de calidad", "Medición y registros según la clase de precisión: registros de producción, registros individuales y trazabilidad, certificación individual."],
      ["Producción repetida", "Respuesta repetible frente a una especificación declarada entre lotes."],
      ["Trazabilidad", "Identidad de serie, trazabilidad de lote y un Certificado de Precisión cuando la clase lo prevé."],
    ],
    capacityNote: "La capacidad de producción, los plazos, las cantidades mínimas y los calendarios de entrega se confirman por escrito para cada programa, frente a pedidos confirmados y a un calendario de liberación acordado.",
    truth: "La capacidad no es producción entregada, existencias, una fecha de entrega garantizada ni la propiedad de una planta de fabricación.",
    cta: "Distribución y desarrollo de país",
    cta2: "Enviar un pliego técnico",
  },
  ecosystem: {
    title: "El ecosistema MAXIMUS",
    lead: "Una llave. Esto es lo que abre. Cada nodo tiene una explicación, un estado exacto y una siguiente acción pertinente.",
    words: ["Ingeniería", "Rendimiento", "Innovación", "Comunidad", "Oportunidad", "Propósito"],
    nodes: {
      engineering: { h: "Ingeniería y fabricación de raquetas", p: "Raquetas íntegramente de carbono diseñadas según especificación, producidas con registros de calidad y trazabilidad.", a: "Ingeniería y fabricación" },
      precision: { h: "Precisión y configuración individual", p: "Cuatro parámetros, tres clases de precisión, ocho medidas de empuñadura e ingeniería personalizada.", a: "Precisión y rigidez" },
      training: { h: "Entrenamiento y metodología", p: "Sweet Spot Trainer, Spot Trainer y un recorrido de desarrollo estructurado.", a: "Sistemas de entrenamiento" },
      development: { h: "Desarrollo del jugador y del entrenador", p: "Selección dirigida por el entrenador, registros, reevaluación y vías de formación.", a: "Metodología" },
      identity: { h: "Identidad personal y marcas personales", p: "Del grabado a una marca personal o profesional regida por derechos.", a: "Marcas personales" },
      owners: { h: "Registros, conocimiento y derechos del propietario", p: "Una bóveda del propietario propuesta, con permisos, para los registros de equipamiento, desarrollo y derechos.", a: "Propietarios y la bóveda" },
      mipa: { h: "Procedencia MIPA y control interno", p: "La capa interna de PI, procedencia y control documental.", a: "Identidad jurídica y control" },
      digital: { h: "Infraestructura digital y dirección Blockchain 5.0", p: "Procedencia, registros trazables, evidencia con permisos e identidad del producto como dirección tecnológica declarada.", a: "Dirección tecnológica" },
      licensing: { h: "Programas contractuales de licencia y regalías", p: "Marcas, productos y paquetes de derechos licenciados, con condiciones definidas en cada acuerdo.", a: "Vías de licencia" },
      families: { h: "Participación familiar y beneficios del programa", p: "Decisiones informadas, continuidad, registros conservados y beneficios definidos por el programa.", a: "Familias y padres" },
      network: { h: "MAXIMUS Sports Network", p: "Jugadores, entrenadores, clubes, academias, proveedores de servicios, operadores y socios regionales.", a: "Sports Network" },
      market: { h: "Clubes, academias, distribución y desarrollo de país", p: "Programas de equipo, venta en tienda, distribución y desarrollo de territorio mediante cualificación por escrito.", a: "Vías de colaboración" },
      institutional: { h: "Programas institucionales, educación, innovación e impacto social", p: "La capa institucional que aporta MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) cuando un programa establece esa función.", a: "Programas institucionales" },
      extensions: { h: "Futuras extensiones a otros deportes de raqueta y a la ropa MAXIMUS", p: "Pádel, pickleball, squash, bádminton, racquetball, tenis playa y ropa como direcciones de desarrollo.", a: "Deportes de raqueta" },
    },
    boundaryTitle: "Límites",
    boundary: [
      "La compra de una raqueta no crea la condición de miembro institucional, derechos de gobierno, regalías ni derechos de inversión.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) es el operador institucional únicamente cuando un programa establece esa función; las ventas de equipamiento identifican su entidad contratante real.",
      "Las subvenciones, el estatus de entidad sin ánimo de lucro, el tratamiento fiscal y las autorizaciones regulatorias no se aplican automáticamente en todos los países.",
    ],
    techTitle: "Dirección tecnológica",
    techP: "Blockchain 5.0 es la dirección tecnológica declarada de MAXIMUS. Sus finalidades funcionales son la procedencia, los registros trazables, la evidencia con permisos, la identidad del producto y la conciliación de los eventos comerciales que cumplan los requisitos. No se representa ningún mecanismo de consenso, capacidad de transacción, red de nodos, dirección de contrato inteligente, token ni certificación independiente, y no se afirma ninguna implementación desplegada. La información personal, los registros de menores y los acuerdos confidenciales nunca se colocan por defecto en un sistema público inmutable.",
  },
  brands: {
    title: "Marcas personales y embajadores",
    statement: "Del jugador a la marca. Del entrenador a la marca.",
    lead: "Una vía específica para la marca personal. La participación de MAXIMUS incluye el desarrollo de marca y la promoción acordada, no solo un nombre en una raqueta.",
    progressionTitle: "Progresión prevista",
    progression: [
      ["Identidad verificada", "Una identidad verificada y un historial de desarrollo."],
      ["Marca distintiva", "Una marca personal o profesional distintiva."],
      ["Contenido con derechos liberados", "Contenido con derechos liberados e identidad de producto aprobada."],
      ["Ingeniería y colecciones", "Ingeniería y desarrollo de colecciones cuando así se acuerde."],
      ["Promoción", "Promoción a través de canales y colaboraciones MAXIMUS acordados."],
      ["Participación", "Participación contractual en las ventas o licencias que cumplan los requisitos."],
      ["Informes", "Informes transparentes conforme al acuerdo."],
    ],
    royaltiesTitle: "Regalías y licencias",
    royalties: [
      "Las regalías se vinculan a la marca, el producto, la transacción o el paquete de derechos licenciados que se hayan definido.",
      "“Ventas mundiales” significa las ventas que cumplan los requisitos dentro del alcance del contrato, nunca cualquier raqueta MAXIMUS no relacionada.",
      "Los porcentajes, la base de cálculo, los territorios, la vigencia, las devoluciones, las deducciones, los informes, la liquidación y la verificación se definen en el acuerdo correspondiente. No se publica ningún porcentaje de regalías por defecto.",
      "No se promete ninguna campaña global, presupuesto de medios, resultado de patrocinio ni éxito comercial sin un alcance acordado.",
    ],
    cta: "Enviar una consulta de colaboración de marca",
    cta2: "Consulta de colaboración para entrenadores",
  },
  families: {
    title: "Familias y padres",
    lead: "Decisiones de equipamiento informadas, continuidad del desarrollo, conocimiento y derechos conservados, visibilidad de la participación y beneficios definidos por el programa que pueden apoyar la actividad futura.",
    nowTitle: "Disponible ahora",
    now: ["Consultas familiares y de desarrollo por escrito.", "Selección de equipamiento con participación del entrenador, solicitudes de adaptación y de demostración.", "Registros privados: los perfiles de menores nunca se publican ni se comercializan por defecto.", "Vía de formación para padres: configuración, carga, progresión, registros y derechos."],
    plannedTitle: "Previsto",
    planned: ["Beneficios de participación definidos por el programa, utilizables para bienes y servicios dentro del ecosistema, en lugar de intereses en efectivo.", "Registros de propietario y de familia en la bóveda del propietario propuesta, con permisos del tutor y transición del control a los 18 años."],
    categoriesTitle: "Se mantienen separados",
    categories: ["Regalías contractuales derivadas de derechos licenciados o de ventas que cumplan los requisitos", "Beneficios de participación definidos por un programa", "Créditos de compra o de servicio", "Pagos anticipados", "Condición de miembro institucional"],
    categoriesP: "Estas categorías nunca se tratan como intercambiables.",
    statusTitle: "Estado real del programa familiar",
    journeyTitle: "La vía familiar",
    journey: [
      ["Objetivo", "Lo que el jugador quiere lograr a continuación."],
      ["Nivel actual", "Dónde está el jugador hoy."],
      ["Entrenador", "Si un entrenador participa en las decisiones de equipamiento."],
      ["Equipamiento", "Equipamiento adecuado para la etapa, incluidos los sistemas de entrenamiento cuando corresponda."],
      ["Práctica acordada", "Uso dirigido por el entrenador y acordado de antemano."],
      ["Revisión", "Reevaluación en puntos de control comparables."],
    ],
    brief: {
      who: "Padres, madres y tutores de jugadores en cualquier etapa.",
      value: "Una respuesta por escrito sobre el equipamiento adecuado, la participación del entrenador y el siguiente paso de desarrollo.",
      now: "Consultas familiares por escrito; selección con participación del entrenador; registros privados: los perfiles de menores nunca se publican.",
      next: "Envíe la consulta familiar a continuación. Recibirá un ID de solicitud de inmediato.",
    },
    formTitle: "Consulta familiar",
    formNote: "Debe completarla un padre, una madre o un tutor. No incluya el nombre, la fecha de nacimiento, el centro escolar ni información médica del menor.",
    noPromise: "Una compra no promete regalías, rendimientos de inversión, patrocinio ni financiación del desarrollo de un menor.",
    statusP: "Esta versión explica el modelo y acepta consultas sobre el programa. La acumulación, los pagos y el canje no están disponibles hasta que se definan por escrito los eventos que cumplen los requisitos, los beneficiarios, la fuente de financiación, la base de cálculo, los usos permitidos, el tratamiento contable, las devoluciones, las reversiones, la caducidad, la transferibilidad, el cierre del programa y la gestión de conflictos. No se promete que un saldo nunca disminuya, ninguna participación paga la totalidad del entrenamiento y no se implica ninguna protección del capital.",
    cta: "Enviar una consulta familiar o de desarrollo",
  },
  owners: {
    title: "Propietarios y la bóveda del propietario",
    lead: "La bóveda del propietario es un registro propuesto, con permisos, de equipamiento, desarrollo, conocimiento, contenido y derechos documentados. Se presenta como parte de la arquitectura de propietario prevista: no se muestran cuentas, saldos, certificados ni logros activos.",
    nowTitle: "Para los propietarios actuales, ahora",
    now: ["Consultas de propietario: referencia de producto o de serie, puesta a punto, servicio y solicitudes de registros, por escrito.", "Certificado de Precisión y documentación de conjuntos emparejados cuando la clase de precisión lo prevé, entregados con el producto."],
    archTitle: "Arquitectura prevista de la bóveda",
    arch: ["Identidad del producto y referencias de serie", "Configuración y certificados de control de calidad aplicables", "Historial de servicio y de puesta a punto", "Registros de desarrollo del jugador o del entrenador", "Cualificaciones y logros verificados", "Medios con derechos liberados y materiales de autoría propia", "Licencias, permisos y referencias contractuales", "Registros del programa de marca personal", "Estados de regalías o beneficios de participación aplicables"],
    separationTitle: "Qué significa la propiedad",
    separation: [
      "La propiedad de una raqueta física es distinta de la titularidad de los derechos de autor, de una licencia, de un derecho contractual o de un registro que describa esas cosas.",
      "Un documento almacenado o una entrada en blockchain no es prueba automática de que exista un derecho legal o de que se haya transferido.",
      "La evidencia conserva su clasificación: declarada por el participante, confirmada por el tutor, validada por el entrenador, medida por el sistema.",
      "Para menores: registros privados, permisos del tutor, ningún perfil de menor publicado y ninguna comercialización de la identidad por defecto.",
      "La exportación, la corrección, el control de acceso y una transición adecuada del control forman parte del diseño.",
    ],
    techTitle: "Blockchain 5.0 y MxSN",
    techP: "Blockchain 5.0 es la dirección tecnológica declarada; MxSN define los conceptos de una red con permisos para el consentimiento, la entrega, la evidencia, los derechos y los informes. No se representa ninguna implementación operativa. El modelo de datos de la aplicación está construido para integrarse más adelante a través de una interfaz documentada, sin pretender que hoy exista una conexión.",
    cta: "Consulta de propietario",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "La conexión entre jugadores, entrenadores, clubes, academias, proveedores de servicios, operadores de programas y socios regionales.",
    functionsTitle: "Funciones potenciales",
    functions: ["Descubrimiento", "Presentaciones", "Programas de desarrollo", "Apoyo con equipamiento", "Eventos", "Acceso a servicios", "Oportunidades para socios"],
    statusTitle: "Estado real",
    statusP: "Todavía no se publica ningún directorio público: solo se listarán los participantes cuya identidad, relación y permiso para aparecer estén establecidos. Una propuesta enviada a un club no es una colaboración, y un posible distribuidor no es un distribuidor designado. La publicación del directorio, las reservas, la mensajería y las transacciones comerciales se controlan por separado y no están activas.",
    cta: "Solicitar el acceso a la red",
  },
  partnerships: {
    title: "Vías de colaboración",
    lead: "Primero la cualificación por escrito. Cada vía conduce a una consulta específica de la función; las condiciones comerciales llegan después por escrito.",
    commercialTitle: "Actividades comerciales potenciales de la plataforma",
    commercial: ["Equipamiento", "Ingeniería personalizada", "Personalización", "Programas de equipo y de academia", "Sistemas de entrenamiento", "Licencias contractuales", "Distribución", "Servicios aprobados", "Futuras categorías de producto"],
    boundary: "Los derechos de país, la exclusividad, las tasas de territorio y los márgenes del distribuidor son condiciones negociadas. No se publica ningún ingreso, previsión, valoración, cuota de mercado, retorno, compromiso de financiación ni colaboración sin nombrar.",
    routes: {
      coaches: {
        title: "Entrenadores",
        lead: "Sistemas de entrenamiento, adaptación, identidad profesional, programas autorizados, oportunidades de marca personal y suministro de equipamiento.",
        points: ["Sweet Spot Trainer y Spot Trainer en la práctica dirigida por el entrenador.", "Adaptación con las matrices de configuración y las ocho medidas de empuñadura de fábrica.", "Coach-to-Brand: un perfil profesional verificado y una submarca regida por derechos.", "El uso autorizado de los programas sigue un acuerdo por escrito."],
        cta: "Enviar una consulta de colaboración para entrenadores",
        brief: {
          who: "Entrenadores independientes y equipos técnicos.",
          value: "Sistemas de entrenamiento para la práctica dirigida por el entrenador, adaptación con las matrices de las series y las ocho empuñaduras de fábrica, y una vía hacia una identidad profesional.",
          now: "Consultas de entrenadores por escrito. No se publica ni se implica ninguna comisión, ingreso o tarifa por recomendación.",
          next: "Envíe la consulta de entrenador a continuación. Las condiciones llegan por escrito.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Clubes y academias",
        lead: "Equipamiento de equipo, sistemas de entrenamiento, personalización, programas de desarrollo, servicio y participación en la red.",
        points: ["Conjuntos de equipo y emparejados solicitados a través del configurador.", "Sistemas de entrenamiento y metodología para un desarrollo estructurado.", "Personalización para programas de equipo en las zonas aprobadas.", "Jornadas de demostración, sesiones de adaptación y participación en la red."],
        cta: "Enviar un pliego de club o academia",
        brief: {
          who: "Clubes, academias y programas de equipo.",
          value: "Conjuntos de equipo y emparejados, sistemas de entrenamiento, personalización para programas de equipo y jornadas de demostración.",
          now: "Pliegos de clubes y academias por escrito; los conjuntos de equipo se solicitan a través del configurador.",
          next: "Envíe el pliego de club o academia a continuación.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribución y desarrollo de país",
        lead: "Surtido, coordinación de la fabricación, capacidad técnica, desarrollo de territorio y cualificación comercial confidencial.",
        points: ["Cualificación por escrito de la contraparte, el territorio y el canal.", "Surtido definido a partir de las matrices de configuración y las clases de precisión.", "El territorio, la exclusividad, los volúmenes, los precios y la protección comercial son condiciones negociadas y se acuerdan por escrito.", "La entidad contratante, las condiciones de pago y la base de entrega se identifican en cada transacción."],
        cta: "Enviar una consulta de distribución o de desarrollo de país",
        brief: {
          who: "Tiendas especializadas, distribuidores y socios de país.",
          value: "Un surtido definido a partir de las matrices confirmadas, las clases de precisión y la gama de empuñaduras, con cualificación por escrito del territorio y del canal.",
          now: "Consultas de distribución por escrito. El territorio, la exclusividad, los volúmenes y los precios se negocian: nada se concede a través de un formulario.",
          next: "Envíe la consulta de distribución a continuación.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Estratégico e inversión",
        lead: "Capacidad de ingeniería, profundidad de configuración, modelo de fabricación, vías de acceso al mercado, PI, servicios y oportunidades de expansión.",
        points: ["La discusión estratégica cualificada o el acceso controlado a la información sigue a una cualificación por escrito.", "La información pública se limita a las especificaciones de producto aprobadas, la arquitectura de configuración, las capacidades verificadas y las explicaciones de los programas.", "Las condiciones económicas específicas del comprador, los costes, la metodología protegida y los acuerdos no publicados se divulgan únicamente bajo acuerdo de confidencialidad o contrato."],
        cta: "Solicitar una discusión estratégica cualificada",
        brief: {
          who: "Inversores y socios estratégicos.",
          value: "Una discusión cualificada sobre la capacidad de ingeniería, la profundidad de configuración, el modelo de fabricación, las vías de acceso al mercado y la PI.",
          now: "No se publican cifras financieras, previsiones, valoraciones ni retornos. La información controlada sigue a una cualificación por escrito y a un acuerdo de confidencialidad.",
          next: "Solicite a continuación una discusión estratégica cualificada.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Programas institucionales",
        lead: "Educación, acceso, innovación, evidencia de desarrollo, impacto social y programas estructurados de forma adecuada.",
        points: ["Los programas institucionales se estructuran a través de MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) cuando el programa establece esa función.", "Los fondos restringidos de programa y las transacciones comerciales permanecen distintos.", "Una consulta no es una solicitud de adhesión aceptada, y un comprador de equipamiento no es un miembro institucional.", "Las subvenciones, el estatus de entidad sin ánimo de lucro, el tratamiento fiscal y las autorizaciones regulatorias son específicos de cada país y nunca se presuponen."],
        cta: "Enviar una consulta de programa institucional",
        brief: {
          who: "Instituciones, programas de educación y de desarrollo.",
          value: "Programas de educación, acceso, innovación y evidencia de desarrollo, estructurados con el operador adecuado.",
          now: "Consultas institucionales por escrito. Una consulta no es una solicitud de adhesión; la compra de equipamiento no es una condición de miembro institucional.",
          next: "Envíe la consulta institucional a continuación.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Divulgación pública y controlada",
    disclosure: {
      public: { h: "Pública", p: "Especificaciones de producto aprobadas, construcción, arquitectura de configuración, propósitos de entrenamiento, capacidades verificadas, explicaciones de los programas y vías de colaboración." },
      qualified: { h: "Consulta cualificada", p: "Requisitos técnicos, cantidades, interés por territorio, alcance del desarrollo y las discusiones comerciales pertinentes." },
      controlled: { h: "Controlada por acuerdo de confidencialidad o contrato", p: "Fórmulas internas, protocolos detallados de control de calidad, laminados, utillaje, métodos de fabricación, identidad de los proveedores, costes, condiciones económicas específicas del comprador, metodología protegida, acuerdos no publicados y registros de derechos sensibles." },
    },
  },
  contact: {
    title: "Contacto y solicitudes",
    lead: "Elija el propósito de su solicitud. Cada formulario recoge solo lo necesario para encaminarla y evaluarla. Las solicitudes se responden por escrito.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Identidad jurídica",
  },
  form: {
    purposeLabel: "Propósito de la solicitud",
    purposes: {
      selection: "Ayuda para elegir una raqueta",
      product: "Consulta de producto",
      fitting: "Adaptación o demostración",
      technical: "Pliego técnico",
      config: "Solicitud de configuración",
      gps: "Perfil de equipamiento GPS",
      coach: "Colaboración para entrenadores",
      club: "Pliego de club o academia",
      distribution: "Distribución o desarrollo de país",
      brand: "Colaboración de marca o embajador",
      family: "Consulta familiar o de desarrollo",
      institutional: "Programa institucional",
      strategic: "Discusión estratégica o de inversión",
      owner: "Consulta de propietario",
      network: "Solicitud a la Sports Network",
      general: "Consulta general",
    },
    fields: {
      name: "Nombre",
      email: "Email",
      role: "Su función",
      country: "País o región",
      organisation: "Organización",
      message: "Su mensaje",
      level: "Nivel actual",
      objectives: "Qué es lo más importante (hasta tres)",
      currentRacquet: "Raqueta actual",
      grip: "Medida de empuñadura, si la conoce",
      seriesInterest: "Serie de interés",
      quantity: "Cantidad",
      city: "Ciudad o lugar de la sesión",
      coachInvolved: "¿Participa un entrenador?",
      timing: "Fechas preferidas",
      targets: "Objetivos preferidos",
      limits: "Límites obligatorios",
      use: "Uso previsto",
      tradeoffs: "Compromisos aceptables",
      basis: "Base de medición",
      players: "Número de jugadores",
      interests: "Áreas de interés",
      territory: "Territorio de interés",
      channels: "Canales y experiencia actuales",
      audience: "Público o disciplina",
      proposal: "Colaboración propuesta",
      goal: "Objetivo de desarrollo",
      ageBand: "Franja de edad del jugador",
      scope: "Alcance del programa",
      interestArea: "Área de interés",
      productRef: "Referencia de producto o de serie",
      requestType: "Tipo de solicitud",
      seeking: "Qué busca",
      consent: "Acepto que MAXIMUS conserve y use estos datos para responder a esta solicitud. No es una suscripción de marketing.",
    },
    roles: { player: "Jugador", parent: "Padre, madre o tutor", coach: "Entrenador", club: "Club o academia", retailer: "Tienda especializada", distributor: "Distribuidor", brand: "Marca o embajador", investor: "Inversor o socio estratégico", institution: "Institución", other: "Otro" },
    interestOptions: { training: "Sistemas de entrenamiento", fitting: "Adaptación", identity: "Identidad profesional", programmes: "Programas autorizados", brand: "Marca personal", supply: "Suministro de equipamiento", team: "Equipamiento de equipo", personalisation: "Personalización", development: "Programas de desarrollo", service: "Servicio", network: "Participación en la red" },
    ownerTypes: { setup: "Puesta a punto y configuración", service: "Servicio", records: "Registros y certificados", other: "Otro" },
    strategicAreas: { engineering: "Capacidad de ingeniería", configuration: "Profundidad de configuración", manufacturing: "Modelo de fabricación", routes: "Vías de acceso al mercado", ip: "PI y servicios", expansion: "Oportunidades de expansión" },
    errors: {
      required: "Este campo es obligatorio.",
      too_long: "Esta entrada es demasiado larga.",
      too_short: "Esta entrada es demasiado corta.",
      invalid_email: "Introduzca una dirección de correo válida, por ejemplo nombre@ejemplo.com.",
      invalid_choice: "Elija una de las opciones.",
      not_number: "Introduzca un número entero usando solo dígitos.",
      out_of_range: "Este valor está fuera del rango aceptado.",
      not_in_matrix: "Este peso no está en la matriz listada de la serie seleccionada.",
      decimal_not_supported: "Introduzca un número entero, sin decimales.",
      too_many: "Seleccione no más de tres opciones.",
      consent_required: "El consentimiento es necesario para que MAXIMUS pueda responder a esta solicitud.",
      invalid: "Esta entrada no es válida.",
    },
  },
  legal: {
    title: "Identidad jurídica y control",
    lead: "La marca pública es MAXIMUS / MAXIMUS GPS. Las identidades jurídicas operativas son distinguibles y se indican aquí.",
    entities: {
      institutional: { role: "Capa de programas institucionales", p: "Aporta la capa de programas institucionales cuando un programa establece esa función. No es un vendedor comercial de raquetas. Una organización sin ánimo de lucro constituida en el Dubai International Financial Centre." },
      equipment: { role: "Entidad comercial de equipamiento", p: "La entidad comercial de equipamiento para el suministro, la distribución y la entrega comercial contratada cuando los documentos operativos vigentes establecen esa función. La parte contratante de cualquier transacción se identifica en los documentos de esa transacción." },
      ip: { role: "PI, marca y coordinación comercial", p: "Aparece por una función establecida de PI, marca o coordinación comercial. No se le asigna ninguna responsabilidad contractual no confirmada." },
      stewardship: { role: "Referencia de tutela", p: "House of Maximus es la referencia de tutela del ecosistema cuando así lo respalda la fuente correspondiente." },
      control: { role: "Control interno de PI, procedencia y documentación", p: "MIPA es la capa interna de PI, procedencia y control documental. Una entrada interna de MIPA es distinta de una marca registrada, una patente, un registro de derechos de autor o un reconocimiento judicial externos, y no constituye una aprobación visual." },
    },
    labels: { licence: "Licencia", registration: "Registro", vat: "VAT TRN", address: "Dirección", email: "Email", jurisdiction: "Jurisdicción" },
    boundaryTitle: "Límites",
    boundary: [
      "Una compra no concede automáticamente la condición de miembro institucional, derechos de gobierno, regalías ni derechos de inversión.",
      "La función institucional es independiente de las transacciones comerciales de equipamiento.",
      "La privacidad, las condiciones de los programas y los acuerdos de acceso controlado corresponden a las funciones efectivamente publicadas.",
      "Ninguna declaración general de derecho aplicable rige para todo visitante, venta o programa extranjero; la base contractual se fija en cada acuerdo.",
    ],
  },
  privacy: {
    title: "Privacidad",
    updated: "Versión 2026-09-21 · sitio web 4.2",
    contactTitle: "Contacto para cuestiones de privacidad",
    sections: {
      collect: ["Qué se recoge", "Cuando envía un formulario: los datos que introduce (nombre, email, función, país o región, organización si la indica, su mensaje y las respuestas del formulario), la página y los parámetros de campaña de su visita (página de entrada, idioma, parámetros utm; los identificadores de clic publicitario solo si autorizó la analítica) y la hora del envío. Su dirección IP se usa únicamente en forma cifrada (hash) y de corta duración para limitar el abuso, y no se guarda junto con su solicitud."],
      purpose: ["Por qué", "Para responder a su solicitud, preparar la propuesta o la especificación que ha pedido y conservar un registro de la solicitud. No se envía ningún mensaje de marketing sobre la base de un formulario."],
      storageOn: ["Dónde se guardan las solicitudes", "Las solicitudes se guardan en una base de datos de Upstash, Inc. (Redis), provista a través de la plataforma de alojamiento Vercel Inc."],
      notifyEmail: ["Notificación de una nueva solicitud", "Cuando se acepta una solicitud, se envía por correo electrónico al buzón responsable de MAXIMUS una notificación con los datos que ha facilitado."],
      notifyTelegram: ["Notificación de una nueva solicitud", "Cuando se acepta una solicitud, se envía a la persona responsable en MAXIMUS una notificación con los datos que ha facilitado a través de Telegram (Telegram FZ-LLC, Dubai), que por tanto procesa esa notificación en tránsito."],
      notifyWebhook: ["Notificación de una nueva solicitud", "Cuando se acepta una solicitud, se envía una notificación con los datos que ha facilitado a un punto final interno de MAXIMUS a través de una conexión firmada y cifrada."],
      notifyNone: ["Notificación de una nueva solicitud", "La notificación de nuevas solicitudes está en preparación. Su solicitud se guarda y MAXIMUS la lee en el registro interno; nada se envía a un tercero con este fin."],
      storageOff: ["Dónde se guardan las solicitudes", "El almacenamiento de solicitudes está en preparación. Hasta que esté activo, los formularios indican que no se puede aceptar una solicitud; nada se guarda. El sitio web está alojado por Vercel Inc."],
      browser: ["Almacenamiento en el navegador", "El almacenamiento de sesión conserva, durante esta sesión del navegador, las respuestas de opción múltiple de GPS y del configurador y los parámetros de campaña de su visita. Los datos de contacto, el texto libre, el texto del grabado y la información sobre menores no se guardan en el navegador."],
      analyticsOn: ["Analítica", "Con su consentimiento, Google Analytics 4 mide las visitas y los eventos de formulario sin datos de contacto ni el texto de la solicitud. Su elección se conserva en el almacenamiento local y puede cambiarse en cualquier momento en “Configuración de analítica”, en el pie de página. Los formularios funcionan sin analítica."],
      analyticsOff: ["Analítica", "En este sitio web no hay ninguna herramienta de analítica activa."],
      retention: ["Conservación", "Todavía no hay configurado ningún plazo de eliminación automática. Puede pedir en cualquier momento que se elimine su solicitud."],
      children: ["Menores", "Los formularios debe completarlos una persona adulta. Las solicitudes relativas a jugadores menores de 18 años las realiza un padre, una madre o un tutor. No envíe el nombre, la fecha de nacimiento, el centro escolar ni información médica de un menor. Los perfiles de menores nunca se publican."],
      rights: ["Sus derechos", "Para acceder a su solicitud, corregirla o eliminarla, escriba a gps@maximus.tennis e indique su ID de solicitud."],
      controlled: ["Información controlada", "Los documentos confidenciales no se guardan en este sitio web ni se sirven desde él. La divulgación controlada se realiza bajo acuerdo de confidencialidad o contrato, a través de canales separados."],
    },
  },
  terms: {
    title: "Condiciones de uso",
    copyright: "Los derechos de autor de este sitio web — sus textos, fotografías, diseño y código — pertenecen exclusivamente a Maximus Kiriyakulov. No han sido cedidos a ninguna empresa ni a ninguna otra persona.",
    updated: "Versión 2026-09-21",
    sections: [
      ["Información, no oferta", "La información de producto de este sitio web describe especificaciones aprobadas, arquitectura de configuración y explicaciones de los programas. No es una oferta de venta, una lista de precios, una declaración de existencias ni un compromiso de entrega. Las condiciones comerciales se acuerdan por separado y por escrito con la entidad contratante identificada en cada transacción."],
      ["Solicitudes", "Una solicitud enviada a través de este sitio web —incluidos los perfiles GPS, las solicitudes de configuración y los pliegos técnicos— se guarda con un ID de solicitud y se revisa. No es un pedido aceptado, un compromiso de fabricación, una cita confirmada, una solicitud de adhesión ni una solicitud aceptada a ningún programa."],
      ["Especificaciones y evidencia", "Los valores calculados, los objetivos de fabricación y las especificaciones confirmadas se distinguen en las páginas correspondientes. Los valores de rigidez son objetivos de fabricación hasta que se publique lo contrario. No se garantiza ningún resultado para un jugador concreto."],
      ["Ecosistema, adhesión y derechos", "La compra de una raqueta no crea la condición de miembro institucional, derechos de inversión, titularidad de propiedad intelectual, derecho a regalías ni beneficios de participación. Los derechos se rigen por las condiciones publicadas del programa o por un acuerdo escrito."],
      ["Propiedad intelectual", "MAXIMUS®, el emblema del león, la marca GPS y el contenido de este sitio web están protegidos. Las fórmulas internas de ingeniería, los protocolos de control de calidad, los laminados, el utillaje, la identidad de los proveedores, los costes y la metodología protegida no se divulgan aquí."],
    ],
  },
  lead: {
    submit: "Enviar la solicitud",
    submitting: "Enviando…",
    retry: "Inténtelo de nuevo",
    acceptedEyebrow: "Solicitud aceptada",
    acceptedTitle: "Hemos recibido su solicitud.",
    requestId: "ID de solicitud",
    acceptedNext: "MAXIMUS revisa cada solicitud y responde por escrito a la dirección de correo que ha facilitado. Conserve el ID de solicitud para cualquier seguimiento.",
    duplicate: "Esta solicitud ya se había recibido; no se ha creado ningún duplicado.",
    another: "Iniciar una nueva solicitud",
    errorsTitle: "Compruebe estos campos:",
    failTitle: "Su solicitud no se ha enviado.",
    fail: {
      offline: "Su dispositivo está sin conexión.",
      network: "La conexión con el servidor ha fallado.",
      timeout: "El servidor no ha respondido a tiempo.",
      rate_limited: "Han llegado demasiadas solicitudes desde esta red. Inténtelo de nuevo en unos minutos.",
      too_fast: "El formulario se ha enviado muy rápido. Revíselo y envíelo de nuevo.",
      spam_suspected: "La solicitud ha sido detenida por el filtro de spam.",
      unavailable: "En este momento no se pueden aceptar solicitudes.",
      default: "Se ha producido un error inesperado.",
    },
    keepNote: "Sus datos se conservan en esta página, para que pueda intentarlo de nuevo.",
    sendByEmail: "Enviar esta solicitud por correo electrónico",
    sendByEmailNote: "Su aplicación de correo se abrirá con el texto de esta solicitud. MAXIMUS la recibe cuando usted envía el correo.",
    mailConfig: "Configuración",
    mailPage: "Página",
    fallback: "Si el problema persiste, escriba a {email}. Una solicitud solo cuenta como enviada cuando se muestra un ID de solicitud.",
    privacyLink: "Aviso de privacidad",
    hpLabel: "Deje este campo vacío",
    consentShort: "Consentimiento",
    after: "Tras el envío se muestra un ID de solicitud en esta página. Las solicitudes se revisan y se responden por escrito; una solicitud no es un pedido.",
    basis: { unstrung: "Sin encordar", strung: "Encordada", unknown: "No estoy seguro — se acordará en la especificación" },
    hints: {
      email: "MAXIMUS responde por escrito a esta dirección.",
      goal: "Por ejemplo: primera raqueta de competición, o dejar atrás una raqueta junior. No incluya nombres, fechas de nacimiento ni información médica de un menor.",
      currentRacquet: "Marca y modelo, si los conoce.",
      message: "No incluya contraseñas, datos de pago ni información médica.",
    },
  },
  choose: {
    eyebrow: "Ayuda para elegir",
    title: "Ayúdenme a elegir una raqueta",
    lead: "Indique a MAXIMUS su nivel y lo que más le importa. Sus respuestas se revisan y recibirá una propuesta por escrito: serie, clase de precisión, peso y empuñadura.",
    stepsTitle: "Qué ocurre a continuación",
    steps: [
      ["Sus respuestas", "Nivel, prioridades y medida de empuñadura si la conoce."],
      ["Revisión experta", "MAXIMUS compara sus respuestas con las matrices de las series."],
      ["Propuesta por escrito", "Una configuración propuesta y el siguiente paso, por escrito."],
    ],
    formTitle: "Sus respuestas",
    submit: "Solicitar ayuda para elegir",
    altTitle: "¿Prefiere decidir usted mismo?",
    altGps: "Perfil GPS detallado",
    altBuild: "Configurar directamente",
    note: "Sin adaptación automática y sin afirmación de exactitud: una persona revisa cada solicitud.",
  },
  consent: {
    title: "Analítica",
    text: "¿Puede MAXIMUS medir las visitas con Google Analytics? Los formularios funcionan en cualquier caso; no se envían a la analítica datos de contacto ni el texto de la solicitud.",
    allow: "Permitir la analítica",
    decline: "Rechazar",
  },
  media: {
    spotHeadsUp: "Cinco MAXIMUS Spot Trainer uno al lado del otro, con las cabezas redondas de impacto hacia arriba y los mangos hacia abajo, y pelotas apoyadas sobre las cabezas",
    greatHero: "Serie MAXIMUS GREAT, 363 g: la composición completa con los detalles rojos y amarillos en la cabeza, las letras MAXIMUS brillantes, el autógrafo Maximus en el corazón y la tapa del mango con el león",
    spotRow: "Cinco MAXIMUS Spot Trainer dispuestos en fila, con pelotas apoyadas sobre sus cabezas redondas de impacto",
    spotPair: "Dos MAXIMUS Spot Trainer de pie ante el emblema del león MAXIMUS, con pelotas sobre sus cabezas redondas de impacto",
    spinVisual: "MAXIMUS SPIN: cabeza encordada, letras MAXIMUS brillantes, empuñadura y tapa del mango con el león",
    powerVisual: "MAXIMUS POWER: cabeza encordada, letras MAXIMUS brillantes, grabado de personalización, empuñadura y tapa del mango con el león",
    greatVisual: "MAXIMUS GREAT: cabeza encordada, letras MAXIMUS brillantes, grabado de personalización, empuñadura, tapa del mango con el león y la marca de la serie G en la garganta",
    spinHead: "Cabeza y plano de cordaje de MAXIMUS SPIN",
    handleLion: "Garganta, empuñadura y tapa del mango de MAXIMUS con la marca del león",
    engraving: "Grabado de personalización en plata en el corazón",
    lettering: "Letras MAXIMUS en negro brillante sobre un marco negro mate",
    variantAlt: "Serie MAXIMUS {series} — {w} g, balance {b} mm: visualización completa con la franja de especificación, la zona de grabado de personalización y la marca MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistema de cuatro raquetas",
    sst270: "Sweet Spot Trainer de 270 g / 330 mm",
    sst285: "Sweet Spot Trainer de 285 g / 325 mm",
    sst300: "Sweet Spot Trainer de 300 g / 325 mm",
    sst400: "Sweet Spot Trainer de 400 g / 320 mm",
    sstShafts: "El corazón de los Sweet Spot Trainer con las letras MAXIMUS",
    sstGrips: "Empuñaduras y tapas del mango de Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, cuatro tapas del mango con la marca del león",
    note: "Imagen de producto",
  },
  notFound: { title: "Página no encontrada", p: "La página que ha solicitado no existe en este idioma.", cta: "Ir a la página de inicio" },
};

export default es;
