/* Basque dictionary — MAXIMUS website v4.0. Translated from content/en.js; numerical product data lives in data/products.js. */
const eu = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — zehaztapenaren arabera diseinatutako osorik karbonozko tenis-erraketak",
    defaultDescription:
      "Osorik karbonozko tenis-erraketak, markotik heldulekura: GREAT 97 in², POWER 98 in² eta SPIN 100 in², fabrikako zortzi helduleku-neurri L0–L7, zehaztasun-klaseak pisurako, balantzerako, swingweight-erako eta zurruntasunerako, eta ingeniaritza pertsonalizatua eskatuta.",
  },
  common: {
    statuses: {
      current: "Egungoa",
      agreement: "Akordioz eskuragarri",
      development: "Garatzen",
      concept: "Kontzeptua",
      target: "Fabrikazio-helburua",
      modelled: "Kalkulatua",
      confirmed: "Berretsia",
      requested: "Eskatutako arkitektura",
      notprovided: "Ez da eman",
    },
    brief: { who: "Norentzat da", value: "Zer jasotzen duzu", now: "Orain berretsia", next: "Hurrengo urratsa" },
    labels: {
      next: "Hurrengoa",
      back: "Atzera",
      edit: "Editatu erantzunak",
      review: "Berrikuspena",
      start: "Hasi",
      restart: "Hasi berriro",
      copy: "Kopiatu eskaeraren testua",
      copied: "Kopiatuta",
      openEmail: "Ireki posta eskaera hau bidaltzeko",
      reference: "Eskaeraren erreferentzia",
      weight: "Pisua",
      balance: "Balantzea",
      swingweight: "Swingweight",
      stiffness: "Zurruntasuna",
      grip: "Helduleku-neurria",
      headSize: "Buruaren neurria",
      series: "Seriea",
      precisionClass: "Zehaztasun-klasea",
      quantity: "Kopurua",
      notProvided: "Oraindik argitaratu gabe",
      requestTarget: "Eskatutako helburua",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Irakurri gehiago",
      allSeries: "Serie guztiak",
      points: "katalogoko pisuak",
      optional: "aukerakoa",
      required: "beharrezkoa",
      select: "Hautatu",
      yes: "Bai",
      no: "Ez",
      unknown: "Ez dakit zehatz",
      custom: "Helburu pertsonalizatua",
      listed: "Katalogoko pisua",
      individual: "Erraketa bakarra",
      pair: "Bikote parekatua",
      triple: "Hirukote parekatua",
      team: "Taldeko multzoa",
      summaryTitle: "Zure eskaeraren laburpena",
      nextAction: "Hurrengo ekintza",
      status: "Egoera",
      learn: "Informazio gehiago",
      schematic: "Eskema — ez da neurketa",
      photo: "Argazkia",
    },
    ecosystemStrip: "MAXIMUS ekosistema",
    truth: {
      noPrices: "Prezioak, gutxieneko kopuruak, entrega-epeak, garantiak eta entrega-konpromisoak idatziz berresten dira merkatu bakoitzeko eta programa bakoitzeko.",
      requestNotOrder: "Eskaera bat azterketa-eskaera da. Ez da onartutako eskari bat, ez fabrikazio-konpromiso bat, ez hitzordu berretsi bat.",
      noGuarantee: "Hemen azaltzen den ekipamendu, metodo edo programa batek ez du jokalari jakin batentzako emaitzarik bermatzen.",
      governing: "Orri hau hainbat hizkuntzatan argitaratzen da. Ingelesezko bertsioa da bertsio baliagarria; itzulpena erosotasunerako eskaintzen da.",
    },
  },
  nav: {
    language: "Hizkuntza",
    groups: { racquets: "Erraketak", training: "Entrenamendua", ecosystem: "Ekosistema", partnerships: "Lankidetzak" },
    familyPlan: "Familia Tenisa",
    racquets: "Erraketa-serieak eta konparazioa",
    great: "GREAT — 97 in² · Kontrola",
    power: "POWER — 98 in² · Indarra",
    spin: "SPIN — 100 in² · Efektua",
    precision: "Zehaztasuna eta zurruntasuna",
    grip: "Fabrikako helduleku-arkitektura L0–L7",
    custom: "Ingeniaritza pertsonalizatua",
    training: "Entrenamendu-sistemak",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologia",
    gps: "MAXIMUS GPS",
    build: "Osatu zurea",
    choose: "Lagundu aukeratzen",
    ecosystem: "Ekosistemaren mapa",
    engineering: "Ingeniaritza eta fabrikazioa",
    experience: "Esperientzia eta doikuntza",
    brands: "Marka pertsonalak eta enbaxadoreak",
    families: "Familiak eta gurasoak",
    owners: "Jabeak eta jabearen ganbera",
    network: "Sports Network",
    partnerships: "Lankidetza-bide guztiak",
    coaches: "Entrenatzaileak",
    clubs: "Klubak eta akademiak",
    distribution: "Banaketa eta herrialdeen garapena",
    strategic: "Estrategia eta inbertsioa",
    institutional: "Erakunde-programak",
    contact: "Harremana",
    legal: "Identitate juridikoa",
    privacy: "Pribatutasuna",
    terms: "Baldintzak",
    menu: "Menua",
    close: "Itxi",
    home: "Hasiera",
    skip: "Joan edukira",
  },
  footer: {
    line: "MAXIMUS erraketa zure giltza da MAXIMUS mundura.",
    product: "Produktua",
    ecosystem: "Ekosistema",
    company: "Erakundea",
    instagram: "Instagram",
    email: "Email",
    analytics: "Analitikaren ezarpenak",
    subscribe: {
      title: "Jarraitu MAXIMUS munduan",
      line: "Serie berriak, doikuntza-datak, entrenamendu-materiala eta jabeen programa. Urtean gutun gutxi batzuk, besterik ez.",
      label: "Posta-helbidea",
      placeholder: "your@email.com",
      button: "Harpidetu",
      sending: "Bidaltzen",
      done: "Zerrendan zaude. Irakurtzea merezi duen zerbait dagoenean soilik idazten dugu.",
      invalid: "Egiaztatu helbidea.",
      failed: "Helbidea ez da erregistratu. Saiatu berriro une batean.",
      terms: "Harpidetzean, MAXIMUS taldeak berritasun hauek bidaltzea eta zure helbidea horretarako gordetzea onartzen duzu. Gutun bakoitzak baja emateko lotura darama.",
    },
    rights: "MAXIMUS® eta lehoiaren ikurra MAXIMUS ekosistemaren markak dira. MIPA barne jabetza intelektuala, jatorria eta dokumentu-kontrola.",
    boundary:
      "Baldintza komertzialak eta kontratualak bereiz eta idatziz adosten dira. Erraketa bat erostea ez da erakunde-kidetza, ez inbertsio-eskubide, ez jabetza intelektualaren titulartasun, ez kanonetarako eskubide.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Zehaztasuna kontaktuan hasten da.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer eta MAXIMUS metodologiak entrenamendu zentratua eta osorik karbonozko errendimendu-erraketak lotzen dituzte.",
    heroCta1: "Ezagutu entrenamendu-sistema",
    heroCta2: "Ezagutu GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrola",
    heroMeta: [
      ["Osorik karbonozkoa", "markotik heldulekura"],
      ["4 parametro", "pisua · balantzea · swingweight · zurruntasuna"],
      ["8 helduleku-neurri", "fabrikako geometria L0–L7"],
      ["3 serie", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Familiako Tenis Plana · Egin ekarpena gurekin",
      title: "Zure familiaren aurrekontua. Zer ordaintzen duen. Zer eraikitzen duen.",
      p: "Hiru agertoki elkarren ondoan: egungoa, aurreikusia eta desiratua. Zure aurrekontuak ordaintzen dituen saioak, orduak eta pilota-kontaktuak, eta saio baten, ordu baten eta kolpe baten kostua, zeure zenbakiekin kalkulatuta.",
      points: [
        ["Zure zenbakiak", "Zenbateko oro zuregandik dator. Ez da ezer suposatzen, ez da ezer bihurtzen."],
        ["Hiru agertoki", "Alderatu orain egiten duzuna aurreikusten duzunarekin eta egin nahiko zenukeenarekin."],
        ["Hamar urteko ikuspegia", "Gastu-plana urte batetik hamar urtera, zuk ezarritako adinek mugatuta."],
        ["Pistatik haratago", "Ikastetxe entzutetsuetan sartzeko laguntza, eta jokalariarekin geratzen diren aktibo digitalak."],
      ],
      cta: "Kalkulatu zure familiako tenis-plana",
    },
    paths: {
      eyebrow: "Hasi hemen",
      title: "Aukeratu zure bidea",
      items: {
        player: { h: "Jokalaria", p: "Bilatu erraketa bat mailaren eta lehentasunen arabera, edo konfiguratu bat zuzenean.", a: "Bilatu zure erraketa" },
        parent: { h: "Gurasoa", p: "Bide idatzi bat garapen-helburuetarako, entrenatzailearen parte-hartzerako eta ekipamendu egokirako.", a: "Familia-bidea" },
        coach: { h: "Entrenatzailea, kluba edo akademia", p: "Entrenamendu-sistemak, doikuntza, taldeko multzoak eta pertsonalizazioa.", a: "Entrenatzaile eta kluben bideak" },
        partner: { h: "Banatzailea edo bazkidea", p: "Banaketa, herrialdeen garapena, estrategia eta erakunde-bideak.", a: "Lankidetza-bideak" },
      },
    },
    series: {
      eyebrow: "Errendimendu-serieak",
      title: "Hiru errendimendu-arkitektura. Ingeniaritza-plataforma bat.",
      lead: "Aukeratu seriea jokoaren norabidearen arabera, eta osatu gero konfigurazioa: zehaztasun-klasea, pisua, heldulekua, pertsonalizazioa.",
      cta: "Alderatu serieak",
      configure: "Konfiguratu",
      open: "Ireki seriea",
      photoPending: "Argazkia oraindik argitaratu gabe",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS Zehaztasun Sistema",
      title: "Pisua. Balantzea. Swingweight. Zurruntasuna.",
      sub: "Ingeniaritza-sistema bakar gisa kontrolatuta.",
      lead: "Hiru zehaztasun-klasek zehazten dute amaitutako erraketa bakoitzak adierazitako zehaztapena zein zorrotz bete behar duen. P0.5 tolerantzia estua da neurketa-protokolo zehatz baten barruan — ez da errore zero.",
      cta: "Zehaztasuna eta zurruntasuna xehetasunez",
    },
    stiffness: {
      eyebrow: "Zurruntasuna",
      title: "Markoaren erantzun errepikagarria adierazitako helburuaren aurrean.",
      p: "Markoaren zurruntasunak erantzuna, sentsazioa eta erraketen arteko koherentzia moldatzen ditu. MAXIMUS markak laugarren parametro kontrolatu gisa tratatzen du: helburua, neurtutako emaitza, onartutako tolerantzia eta tresnaren gaitasuna erregistro bereizi gisa gordetzen dira. Onura errepikagarritasuna da — ez jokalari ororentzako emaitza bermatua.",
      cols: [["Erantzuna", "Nola itzultzen duen markoak energia kontaktuan."], ["Sentsazioa", "Zer sentitzen duen jokalariak kontaktuan."], ["Koherentzia", "Zehaztapen beraren arabera eginiko erraketek berdin erantzuten dute beren klasearen barruan."]],
      schematicCaption: "Eskema: klase bakoitzean adierazitako zurruntasun-helburuaren inguruan onartutako desbideratzea. Ez da neurketa; ez da RA baliorik iradokitzen.",
      bands: { p25: "helburuaren tolerantzia ±1 RA", p15: "helburuaren tolerantzia ±0,5 RA", p05: "adierazitako RA balioarekin bat dator fabrikako neurketa-protokolo ezarriaren arabera — ez da errore zero", target: "adierazitako helburua (baliorik iradoki gabe)" },
    },
    carbon: {
      eyebrow: "Eraikuntza-estandarra",
      title: "Osorik karbonozkoa. Markotik heldulekura.",
      p: "Plataforma honetako egungo MAXIMUS erraketa guztiak osorik karbonozkoak dira egituran, heldulekua barne. Ez da aparra erabiltzen heldulekua osatzeko.",
      gripTitle: "Fabrikako zortzi helduleku-neurri. L0–L7.",
      gripP: "Neurri bakoitza fabrikako karbonozko helduleku-geometria da — ez gainestalkiz lortutako lodiera.",
      scaleCaption: "Eskema: L0–L7 helduleku-izendapen nominalak (4″ eta 4⅞″ artean). Ez dira heldulekuaren neurri neurtuak.",
      cta: "Fabrikako helduleku-arkitektura",
    },
    custom: {
      eyebrow: "Ingeniaritza pertsonalizatua",
      title: "Zehaztapenaren arabera diseinatua.",
      sub: "Gama estandarra abiapuntua da.",
      p: "MAXIMUS markak argitaratutako matrizeetatik kanpoko eskakizun teknikoak onartzen ditu, ebaluatzeko, diseinatzeko, balioztatzeko eta adostutako zehaztapenaren arabera fabrikatzeko. Bideragarritasuna idatziz berresten da.",
      chain: ["Definitu", "Diseinatu", "Balioztatu", "Zehaztu", "Ekoitzi", "Neurtu / erregistratu"],
      cta: "Aurkeztu txosten tekniko bat",
      cta2: "Hitz egin ingeniaritza pertsonalizatuaz",
    },
    training: {
      eyebrow: "Entrenamendu-sistemak",
      title: "Kontaktuaren inguruan eraikitako entrenamendu-sistema.",
      p: "Sweet Spot Trainer, MAXIMUS metodologia eta Spot Trainer ekipamendua eta entrenatzaileak gidatutako lana lotzen dituzte: kontaktu zentratua, kontrola, karga progresiboa eta errendimendu-erraketara itzultzea.",
      cta: "Entrenamendu-sistemak",
      cta2: "Eskatu erakustaldi bat",
      photoPending: "Entrenatzailearen argazkia oraindik argitaratu gabe",
      sstP: "50 in²-ko entrenamendu-burua kontaktu zentratua lantzeko, lau pisu-konfigurazioarekin entrenatzaileak aukeratutako kargarako.",
      sstCta: "Ezagutu Sweet Spot Trainer",
      sstCaption: "300 g-ko konfigurazioa, lauetako bat",
      methodP: "Helburuak ezarri, ekipamendua hautatu, entrenatzailearen parte-hartzearekin landu, behaketak erregistratu, berriro ebaluatu, doitu eta lana errendimendu-jokora eraman.",
      methodCta: "Ezagutu metodologia",
      spotP: "Helburu biribil txiki bat kontaktu-puntu zehatza eta errepikagarria lantzeko.",
      spotCta: "Ezagutu Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Fabrikazioa eta kalitate-kontrola",
      title: "Zehaztapen baten arabera eginda. Neurtuta eta erregistratuta.",
      p: "Ekoizpenak eskari bakoitzaren zehaztapen idatzia betetzen du. Erregistroak zehaztasun-klasearen araberakoak dira: gordetako ekoizpen-erregistroak P2.5-erako, erregistro indibidualak eta trazabilitatea P1.5-erako, kontrol indibiduala eta dokumentazioa P0.5-erako, eskariaren programak halakorik ezartzen duenean.",
      confirmedTitle: "Berretsia",
      confirmed: ["Osorik karbonozko eraikuntza, markotik heldulekura.", "P2.5, P1.5 eta P0.5 zehaztasun-klaseak lau parametro kontrolaturekin.", "Fabrikako zortzi helduleku-neurri L0–L7."],
      pendingTitle: "Oraindik argitaratu gabe",
      pending: "Neurketa-tresnen argazkiak, kalitate-kontrolaren erregistro-laginak eta fabrikako irudiak oraindik ez dira argitaratu. Orri honetan ezer ez da neurketa-ziurtagiria.",
      captions: { lettering: "MAXIMUS letra distiratsuak marko matean", buttcap: "Heldulekua eta oinarri-tapa lehoiaren markarekin", handle: "Zilarrezko pertsonalizazio-grabatua", finish: "Burua eta korda-sareta" },
      cta: "Ingeniaritza eta fabrikazioa",
    },
    world: {
      eyebrow: "MAXIMUS mundua",
      title: "Giltza bat. Ekosistema bat. Aukera mugagabeak.",
      note: "«Aukera mugagabeak» marka-esapide bat da, ez bideragarritasun tekniko, diru-sarrera edo sarbide mugagabeen promesa. Erosketa batek ez du kanonik, inbertsio-errendimendurik, babeslerik edo jokalari baten garapenerako finantzaketarik sortzen.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — eta zure nabigazioa tenisaren munduan: gidatutako ekipamendu-profila, idatziz erantzuna." },
        personal: { h: "Pertsonalizazioa", p: "Izenak, inizialak, zenbakiak eta taldearen identifikazioa onartutako zilarrezko grabatuarekin." },
        development: { h: "Garapena", p: "Entrenatzaileak gidatutako entrenamendu-sistemak, erregistroak eta berrebaluazioa." },
        ecosystem: { h: "Ekosistema zabaldua", p: "Marka pertsonalak, jabeen erregistroak, sarea, lizentziak eta erakunde-programak — bakoitza bere egoera errealarekin." },
      },
      cta: "Ezagutu ekosistema",
    },
    partners: {
      eyebrow: "Lankidetza-bideak",
      title: "Entrenatzaileak, klubak, banatzaileak eta bazkideak.",
      p: "Lehenik kalifikazioa idatziz. Herrialde-eskubideak, esklusibotasuna eta baldintza komertzialak idatziz negoziatzen dira — inoiz ez inprimaki baten bidez ematen.",
      cta: "Lankidetza-bide guztiak",
      formTitle: "Kontsulta laburra",
      formLead: "Aukeratu xedea eta idatzi MAXIMUS taldeari. Eskaeraren identifikatzailea orri honetan jasotzen duzu.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "ZURE NABIGAZIOA TENISAREN MUNDUAN" } },
    personal: { eyebrow: "Pertsonalizazioa", title: "Zure izena. Zure zenbakia. Zure MAXIMUS erraketa." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Hiru serie. Parametro errealak." },
    map: { cta: "Ezagutu ekosistema" },
  },
  racquets: {
    title: "Erraketak",
    lead: "Hiru errendimendu-serie, eraikuntza-estandar komun batekin, zehaztasun-sistema komun batekin eta fabrikako helduleku-arkitektura komun batekin. Serie bakoitza errendimendu-arkitektura finkatua da ingeniaritza-plataforma zabalago baten barruan.",
    direction: { control: "Kontrola", power: "Indarra", spin: "Efektua" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Jokoaren norabide nagusia",
    compareTitle: "Serieen konparazioa",
    compareLead: "Arkitektura-datu berretsiak soilik. Serie hauen korda-ereduak, luzerak, markoaren profilak, tentsio-tarteak eta swingweight eta zurruntasun balio nominalak ez dira argitaratzen; azterketa teknikorako eskatutako helburu gisa biltzen dira.",
    columns: { series: "Seriea", head: "Buruaren neurria", direction: "Norabidea", weights: "Katalogoko pisuak", range: "Pisu-tartea", balance: "Balantze-datuak" },
    balanceModelled: "Kalkulatutako balioak",
    balanceNotProvided: "Oraindik argitaratu gabe",
    construction: "Eraikuntza: osorik karbonozkoa, markotik heldulekura · Zehaztasuna: P2.5 / P1.5 / P0.5 · Heldulekuak: L0–L7",
    otherTitle: "Beste erraketa-kirolak",
    otherLead: "Onartutako garapen-norabideak. Kategoria hauetan ez dago salgai dagoen produkturik eta ez da tenis-zehaztapenik haietara eramaten.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Hondartza-tenisa" },
    ctaConfigure: "Konfiguratu eskaera bat",
    ctaSeries: "Ireki seriea",
  },
  seriesPage: {
    eyebrow: "Errendimendu-serieak",
    intro: {
      great: "97 in²-ko GREAT arkitektura kontrolaren inguruan eraikita dago: buru trinkoa, kontaktu zehatza eta norabide-konfiantza.",
      power: "98 in²-ko POWER arkitektura energia-transferentziaren inguruan eraikita dago: sakontasuna eta erritmoa marko egonkor batetik.",
      spin: "100 in²-ko SPIN arkitektura baloiaren jokabidearen inguruan eraikita dago: biraketa, marjina eta ibilbidearen moldaketa.",
    },
    photoPending: "Seriearen argazkia oraindik argitaratu gabe",
    detailPending: "Serie honen eraikuntzaren eta heldulekuaren xehetasun-argazkiak oraindik ez dira argitaratu.",
    specsTitle: "Zehaztapena eta egoera",
    catalogue: {
      eyebrow: "{series} seriearen katalogoa",
      title: "{n} pisu-aldaera",
      lead: "{series} seriearen aldaera guztiak, pisuaren arabera ordenatuta. Pisua gramotan, balantzea milimetrotan oinarri-tapatik. Bistaratze bakoitza osorik erakusten da: ezer moztu, estali edo luzatu gabe.",
      selectLabel: "Aukeratu pisu-aldaera bat",
      select: "Erakutsi aldaera hau",
      selected: "Goian erakutsita",
      balanceLabel: "Balantzea",
      headLabel: "Buruaren neurria",
      constructionLabel: "Eraikuntza",
      gripsLabel: "Fabrikako helduleku-neurriak",
      precisionLabel: "Zehaztasun-klaseak",
      balanceConfirmed: "Balantzea pisu honetarako balio berretsia da eta bistaratzean inprimatutako zifrarekin bat dator.",
      balanceModelled: "Balantzea katalogoko pisu honetarako kalkulatutako balioa da, ez fabrikako neurketa indibiduala; bistaratzean inprimatutako zifrarekin bat dator.",
      zoom: "Ireki irudia",
      close: "Itxi",
      allTitle: "{n} aldaera guztiak",
    },
    specs: { head: "Buruaren neurria", direction: "Norabide nagusia", weights: "Katalogoko pisuak", range: "Pisu-tartea", balance: "Balantzea", construction: "Eraikuntza", grips: "Fabrikako heldulekuak", precision: "Zehaztasun-klaseak" },
    construction: "Osorik karbonozkoa, markotik heldulekura",
    statusTitle: "Balioen egoera",
    matrixTitle: "Pisu-matrize osoa",
    matrixLead: "Katalogoko pisuak hautaketa estandarra dira. Beste pisuak helburu pertsonalizatu gisa eska daitezke; falta diren bitarteko balioak ez dira txertatzen.",
    balanceNote: {
      confirmed: "Balantze-balioak katalogoko pisu guztietarako berretsita daude (mm oinarri-tapatik) eta pisu horren bistaratzean inprimatutako zifrarekin bat datoz. Ez dira hemen kalkulatzen eta ez dira ondoko pisuen artean leuntzen; neurketa-oinarria zehaztapen idatzian berresten da.",
      modelled: "Balantze-balioak katalogoko pisu bakoitzerako kalkulatzen dira (mm oinarri-tapatik). Ez dira fabrikako neurketa indibidualak; neurketa-oinarria zehaztapen idatzian berresten da.",
      notprovided: "Serie honen balantze-balioak ez dira ematen. Ez atera beste serie batetik.",
    },
    optionsTitle: "Zehaztasuna, heldulekua eta pisua",
    notPublished: "Serie honetarako argitaratu gabe: korda-eredua, luzera, markoaren profila, tentsio-tartea eta swingweight eta zurruntasun balioak. Azterketa teknikorako eskatutako helburu gisa adieraz ditzakezu.",
    offerTitle: "Zer gertatzen da zure eskaeraren ondoren",
    offerSteps: [
      ["Eskaera", "Bidali konfigurazio bat edo galdera bat. Eskaeraren identifikatzailea berehala erakusten da."],
      ["Azterketa", "MAXIMUS taldeak seriea, klasea, pisua, heldulekua eta eskatutako helburuak aztertzen ditu."],
      ["Erantzun idatzia", "Zehaztapena, eskuragarritasuna eta baldintza komertzialak idatziz berresten dira."],
    ],
    faqTitle: "Galderak",
    faq: [
      ["Balantze-balioak neurtuak dira?", "Katalogoko pisuetarako kalkulatzen dira, ez dira neurketa indibidualak. Neurketa-oinarria zehaztapen idatzian berresten da."],
      ["Katalogoan ez dagoen pisu bat eska dezaket?", "Bai, helburu pertsonalizatu gisa, gramo osotan. Teknikoki aztertzen da eta bideragarritasuna idatziz berresten da."],
      ["Zer aldatzen du zehaztasun-klaseak?", "Pisuak, balantzeak, swingweight-ak eta zurruntasunak adierazitako zehaztapena zein zorrotz bete behar duten, eta zer erregistro gordetzen diren."],
      ["Heldulekua gainestalkiz lodituta dago?", "Ez. L0–L7 fabrikako karbonozko helduleku-geometriak dira."],
      ["Non daude prezioak eta entrega-epeak?", "Eskaera bakoitzerako idatziz berresten dira eta ez dira hemen argitaratzen."],
    ],
    faqSpinBalance: ["Nondik datoz SPIN seriearen balantze-balioak?", "Spin seriearen taula berretsitik: 33 pisu-aldaera, balantzea milimetrotan oinarri-tapatik. Bikote bakoitza pisu horren bistaratze onartuan inprimatutako zifrarekin bat dator. Balioak ez dira kalkulatzen eta ez dira ondoko pisuen artean leuntzen."],
    ctaBuild: "Konfiguratu serie hau",
    ctaAsk: "Galdetu serie honi buruz",
    ctaCompare: "Alderatu serie guztiak",
    weightsLabel: "katalogoko pisuak",
    headLabel: "burua",
  },
  precision: {
    title: "Zehaztasuna eta zurruntasuna",
    switch: { label: "Aukeratu zehaztasun-klase bat", panelLabel: "Lau parametro kontrolatu —", qcLabel: "Kalitate-kontrolaren arkitektura", protocolNote: "fabrikako kalitate-kontrolaren neurketa-protokolo zehatzaren arabera", fullTable: "Konparazio-taula osoa" },
    lead: "Lau parametro ingeniaritza-sistema bakar gisa kontrolatuta. Klase bakoitzak zehazten du amaitutako erraketa batek adierazitako zehaztapena zein zorrotz bete behar duen eta zer kalitate-erregistro sortzen diren.",
    statement: "Pisua. Balantzea. Swingweight. Zurruntasuna. Ingeniaritza-sistema bakar gisa kontrolatuta.",
    classes: {
      "P2.5": { name: "Errendimendu-nukleo eskalagarria", qc: "Neurketa indibiduala eta gordetako ekoizpen-erregistroak." },
      "P1.5": { name: "Zehaztasun aurreratua", qc: "Neurketa indibiduala, erregistro indibidualak eta trazabilitatea." },
      "P0.5": { name: "Profesionala · banaka kontrolatua", qc: "Kontrol indibiduala balio nominalekin eta errealekin eta neurketa-erregistro indibidualekin; serie-identitatea, lotearen trazabilitatea, zehaztasun-ziurtagiria eta multzo parekatuak, eskariaren programak halakorik ezartzen duenean." },
    },
    columns: { cls: "Klasea", weight: "Pisua", balance: "Balantzea", sw: "Swingweight", stiff: "Zurruntasuna", qc: "Kalitate-kontrolaren arkitektura" },
    stiffTarget: "helburuaren tolerantzia",
    stiffExact: "adierazitako RA balioarekin bat dator fabrikako neurketa-protokolo ezarriaren arabera",
    programmeNote: "Serie-identitatea, ziurtagiriak eta multzo parekatuen dokumentazioa eskari jakin baten programak halakorik ezartzen duenean soilik ematen dira.",
    targetsNote: "Zurruntasun-zehaztapenak fabrikazio-helburuak dira, dagokion protokoloak eta ekoizpen-frogek baieztapen sendoagoa eusten duten arte. Arkitekturaren proposamenak ez du esan nahi katalogoko konfigurazio bakoitzak lau parametroen askatze-prozesu osoa jadanik gainditu duela.",
    stiffnessTitle: "Zergatik da garrantzitsua zurruntasuna",
    stiffnessP1: "Markoaren zurruntasunak eragina du markoak kontaktuan nola erantzuten duen, nola sentitzen den eta bi erraketa elkarren artean zein koherenteak diren. Hura kontrolatzearen onura nagusia adierazitako zehaztapenaren aurrean erantzun errepikagarria izatea da.",
    stiffnessP2: "Egiaztatutako betetzea argitaratu aurretik, barne kalitate-kontrolaren erregistroak tresna, haren kalibrazio-egoera, metodoa, erraketaren egoera, bereizmena, neurketaren ziurgabetasuna, errepikatutako neurketak, biribiltze-araua eta onarpen-araua identifikatzen ditu. Erakutsitako zenbaki oso bera izateak ez du frogatzen aldakuntza fisiko zero edo neurketa-errore zero dagoela.",
    fields: ["Helburua", "Neurtutako emaitza", "Onartutako tolerantzia", "Tresnaren gaitasuna"],
    fieldsNote: "Erregistro bakoitzean eremu bereizi gisa gordetzen dira.",
    matchedTitle: "Multzo parekatuak",
    matchedP: "Multzo parekatuen irizpideak tolerantzia indibidualetik bereiz definitzen dira. Erraketa bakoitzak bere tolerantzia nominala betetzeak ez du berez frogatzen bi erraketaren arteko gehienezko alde jakin bat. Bikote, hirukote eta taldeko multzo parekatuak konfiguragailuaren bidez eskatzen dira eta idatziz berresten dira.",
    extendedTitle: "Eredu tekniko zabaldua",
    extendedP: "Datu-ereduak parametro gehigarriak onartzen ditu. Oraindik ez dago haietarako baliorik edo tolerantzia-klaserik; txosten tekniko batean eskatutako helburu gisa adieraz daitezke.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Jokabide torsionala", length: "Luzera", beamProfile: "Markoaren profila", headGeometry: "Buruaren geometria", stringPattern: "Korda-eredua", durability: "Iraunkortasuna", vibration: "Bibrazio-ezaugarriak" },
    noZero: "MAXIMUS markak ez du bere katalogoko gama tolerantzia zerokoa dela esaten. Gamaren zehaztasuna klase gisa adierazten da, tolerantzia jakin batekin eta kalitate-kontrolaren arkitektura zehatz batekin. ZERO ez da gamaren parte.",
    zero: {
      eyebrow: "Aukera esklusiboa",
      title: "ZERO",
      sub: "Zero gramoko tolerantzia.",
      p: "Hiru klaseek amaitutako erraketa adierazitako banda baten barruan mantentzen dute. ZERO aukerak banda kentzen du. Erraketa fabrikatu eta neurtzen da irakurketa adierazitako zifraren berdina izan arte, fabrikako tresnaren bereizmenean, eta irakurketa hori erraketarekin batera ematen da. Ez da katalogoko gamaren parte eta ez da laugarren klase bat: banaka adosten da, erraketa batentzat edo multzo parekatu batentzat, neurrira egindako produktu esklusibo gisa. Akordioz, hurbilketa bera balantzeari eta swingweight-ari aplikatzen zaie.",
      points: [
        ["Bandarik gabe", "Adierazitako zifra emaitza da, ez tolerantzia baten erdigunea."],
        ["Banan-banan", "Unitate bakar gisa fabrikatua, neurtua eta erregistratua."],
        ["Erraketarekin batera emana", "Neurtutako irakurketa entregatzen da eta ekoizpen-erregistroan gordetzen da."],
        ["Idatziz berretsia", "Parametroak, irismena eta epea ekoitzi aurretik adosten dira."],
      ],
      note: "Fabrikako neurketa-tresnaren bereizmenean parekatua. Erakutsitako zifra bera izateak ez du aldakuntza fisiko zerorik baieztatzen. Eskuragarritasuna eta baldintzak eskari bakoitzerako banaka adosten dira.",
      cta: "Eskatu ZERO",
    },
    cta: "Konfiguratu zehaztasun-klase batekin",
  },
  grip: {
    title: "Fabrikako helduleku-arkitektura",
    statement: "Fabrikako zortzi helduleku-neurri. L0–L7.",
    lead: "Heldulekuaren geometria karbonozko helduleku-arkitekturaren parte da. Neurri bakoitza helduleku-geometria gisa fabrikatzen da, ez da gainestalkiz lodiagotzen.",
    emph: "Neurri zabalduak",
    p1: "Fabrikako zortzi neurrien gamak konfigurazio-tarte zabalagoa ematen die entrenatzaileei eta jokalariei, ekipamendua jokalariaren inguruan zehazteko, L6 eta L7 geometria handiagoak barne.",
    p2: "Heldulekuaren izendapen nominala bereizia da heldulekuaren egitura-neurri gordinetatik eta azken neurketa-protokolotik. Neurriak errendimendu-serieei eta plataforma honetako entrenamendu-familiei aplikatzen zaizkie.",
    p3: "Gama honetarako ez da mundu osoko esklusibotasunik baieztatzen.",
    columns: { size: "Neurria", nominal: "Nominala", family: "Honi aplikatzen zaio" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfiguratu zure helduleku-neurriarekin",
  },
  custom: {
    title: "Ingeniaritza pertsonalizatua",
    statement: "Zehaztapenaren arabera diseinatua.",
    sub: "Gama estandarra abiapuntua da.",
    lead: "MAXIMUS markak argitaratutako konfigurazio-matrizeetatik kanpoko eskakizun teknikoak onartzen ditu, ebaluatzeko, diseinatzeko, balioztatzeko eta adostutako zehaztapenaren arabera fabrikatzeko. Bideragarritasuna azterketa bidez berresten da — eska daitekeen oro ez da fisikoki edo komertzialki bideragarria.",
    scopeTitle: "Zer landu dezake txosten tekniko batek",
    scope: ["Buruaren eta markoaren geometria", "Luzera", "Pisua", "Balantzea", "Swingweight", "Zurruntasuna", "Twistweight", "Heldulekuaren geometria", "Eraikuntza", "Multzo parekatuak", "Entrenamendu-markoak", "Estetika eta grabatua", "Identitatea eta taldeko programak", "Tresneriaren araberako garapena"],
    processTitle: "Prozesua",
    process: [
      ["Definitu", "Nahiago diren helburuak, muga derrigorrezkoak, aurreikusitako erabilera eta onargarri diren trukeak."],
      ["Diseinatu", "Ingeniaritza-ebaluazioa plataformaren eta tresneriaren aurrean."],
      ["Balioztatu", "Adostutako zehaztapenaren aurkako balioztatzea."],
      ["Zehaztu", "Zehaztapen idatzia, neurketa-oinarriarekin eta tolerantziekin."],
      ["Ekoitzi", "Ekoizpena zehaztapenaren arabera."],
      ["Neurtu / erregistratu", "Neurketa eta gordetako erregistroak dagokion zehaztasun-klasearen arabera."],
    ],
    formTitle: "Aurkeztu txosten tekniko bat",
    formLead: "Bereizi nahiago dituzun helburuak eta muga derrigorrezkoak. Emaitza azterketa teknikoaren eskaera bat da, ez automatikoki onartutako fabrikazio-eskari bat.",
    protected: "Laminatuen errezetak, tresneria, hornitzaileen identitatea, barne kostu-kalkuluak eta babestutako jakintza ez dira bide honetatik ezagutarazten.",
    cta: "Aurkeztu txosten tekniko bat",
  },
  training: {
    title: "Entrenamendu-sistemak",
    lead: "Bi entrenamendu-familia, bakoitza bere ekoizpen-estandarrekin, metodologia bakar batek lotuta: entrenatzaileak gidatutako lana, erregistroak, berrebaluazioa eta errendimendu-jokora itzultzea.",
    sst: { h: "Sweet Spot Trainer", p: "50 in²-ko buru txikituko entrenamendu-erraketa, lau pisuren sisteman, kontaktu zentratua, sweet spot-aren kontzientzia, erraketaren kontrola eta karga progresiboa lantzeko." },
    spot: { h: "Spot Trainer", p: "Kontaktu-puntuaren entrenamendua helburu biribil txiki batekin, onartutako lau pisuren oinarriaren gainean." },
    method: { h: "Metodologia", p: "Helburuak ezarri, ekipamendua entrenatzailearen parte-hartzearekin hautatu, dagokion sistema erabili, erregistratu, berriro ebaluatu, doitu eta eraman." },
    experience: "Hartu eskuetan. Astindu. Sentitu.",
    experienceP: "Eskatu proba bat, doikuntza bat edo entrenatzailearen laguntzaz egindako erakustaldi bat. Bidalitako eskaera bat ez da hitzordu berretsia.",
    cta: "Eskatu doikuntza edo erakustaldia",
    distinct: "Sweet Spot Trainer, Spot Trainer eta erakustaldirako beste edozein gailu produktu bereiziak dira eta inoiz ez dira batzen.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Entrenamendu-kategoria bereizia, bere ekoizpen-estandar propioarekin. 50 in²-ko buruak kontaktuaren kokapenean jartzen du arreta; lau pisuek karga-progresioa ematen dute.",
    baseline: "Oinarri berretsia",
    columns: { head: "Burua", length: "Luzera", pattern: "Korda-eredua", grips: "Fabrikako heldulekuak" },
    systemTitle: "Lau erraketako sistema",
    detailsTitle: "Eraikuntzaren xehetasunak",
    systemLead: "Pisua eta balantzea entregatzen diren bezala. Neurketa-oinarria bereiz erregistratzen da eta oraindik ez da argitaratu.",
    purposeTitle: "Xedea",
    purpose: ["Kontaktu zentratuaren lanketa", "Sweet spot-aren kontzientzia", "Erraketaren kontrola", "Karga progresiboa", "Entrenatzaileak gidatutako garapena", "Jokalariaren errendimendu-erraketara itzultzea"],
    heavy: "400 g-ko eredua entrenamendu-konfigurazio kontrolatua da. Ez da automatikoki gomendatzen haurrei, hasiberriei edo jokalari guztiei; entrenatzaileak zehazten ditu karga, iraupena eta progresioa.",
    precisionNote: "Errendimenduaren P2.5, P1.5 eta P0.5 zehaztasun-klaseak ez dira automatikoki aplikatzen entrenamendu-familia honi. Entrenamendu-ekoizpenaren tolerantziek familiaren beraren zehaztapen onartua betetzen dute.",
    health: "Ez da tenis-ukondoaren prebentzio edo tratamendurik, lesioen desagerpenik edo hobekuntza bermaturik agintzen.",
    cta: "Eskatu Sweet Spot Trainer erakustaldi bat",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Kontaktu-puntuaren entrenamendua helburu biribil txiki batekin. Produktu bereizia, bere identitate bisual propioarekin, onartutako lau pisuren oinarriaren gainean eraikia.",
    purposeTitle: "Xede berretsia",
    purposeP: "Jokalaria kontaktu-puntu zehatz bat aurkitzen eta errepikatzen trebatzea.",
    weightsTitle: "Pisu-progresioa",
    weightsP: "Pisu-progresioak Sweet Spot Trainer produktuaren pisu-oinarri onartua betetzen du. Balantze-balioak eta Sweet Spot Trainer produktuaren beste zehaztapenak ez dira Spot Trainer produktura kopiatzen.",
    dims: "Helburuaren neurri zehatzak oraindik ez dira argitaratu.",
    grips: "Fabrikako helduleku-arkitektura L0–L7.",
    notes: ["Errendimenduaren zehaztasun-klaseak ez dira automatikoki aplikatzen.", "Ez da erraketa konbentzional txikitu bat eta ez da korda-eredurik argitaratzen.", "Spot Trainer, Sweet Spot Trainer eta erakustaldirako beste edozein gailu bereizgarriak izaten jarraitzen dute."],
    cta: "Galdetu Spot Trainer produktuaz",
  },
  methodology: {
    title: "Metodologia eta produktuaren esperientzia",
    lead: "Ekipamendua garapen-ibilbide egituratu baten zati bat da. Metodoa jokalariaren helburuekin hasten da, ez produktuaren etiketarekin.",
    stepsTitle: "Garapen-ibilbidea",
    steps: [
      ["Helburuak ezarri", "Jokalariaren helburuak eta abiapuntua."],
      ["Ekipamendua hautatu", "Ekipamendu egokia entrenatzailearen parte-hartzearekin hautatuta."],
      ["Sistema erabili", "Dagokion entrenamendu-sistema, entrenatzaileak gidatuta."],
      ["Erregistratu", "Benetako parte-hartzearen behaketak, asmatutako puntuaziorik gabe."],
      ["Berriro ebaluatu", "Kontrol-puntu alderagarriak."],
      ["Doitu", "Konfigurazioaren edo programaren doikuntzak."],
      ["Eraman", "Ikasitakoa errendimendu-jokora eramaten da."],
    ],
    educationTitle: "Prestakuntza-bideak",
    education: { player: "Jokalariak — konfigurazioa, karga eta progresioa ulertzea.", parent: "Gurasoak — garapenaren jarraitutasuna, ekipamendu egokia, erregistroak eta eskubideak.", coach: "Entrenatzaileak — entrenamendu-sistemak, doikuntza, ebaluazioa eta programen erabilera baimendua." },
    evidenceTitle: "Frogen diziplina",
    evidenceP: "Benetako parte-hartzearen erregistroak eta behaketak beren sailkapenarekin gordetzen dira — parte-hartzaileak adierazita, tutoreak berretsita, entrenatzaileak balioztatuta edo sistemak neurtuta. Aurrerapena, puntuazioak eta balioztapena inoiz ez dira asmatzen.",
    experienceTitle: "Hartu eskuetan. Astindu. Sentitu.",
    experienceP: "Proba bat, doikuntza bat edo entrenatzailearen laguntzaz egindako erakustaldi bat eska daitezke. Bidalitako eskaera bat ez da hitzordu berretsia.",
    cta: "Eskatu doikuntza edo erakustaldia",
    cta2: "Entrenatzaileen lankidetza-kontsulta",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — gidatutako ekipamendu-profila",
    title: "MAXIMUS GPS",
    lead: "Gidatutako ekipamendu-profila. Erantzun garrantzia duena soilik; berrikusi eta zuzendu zure erantzunak; jaso laburpen bat, aplikatzen diren konfigurazio-norabideak eta hurrengo ekintza erreal bat.",
    honesty: "Bertsio honetan ez dago doikuntza automatikoaren araurik onartuta. Beraz, GPSak eskakizunen laburpen argia sortzen du eta konfigurazio-norabideak seinalatzen ditu; ekipamenduaren xehetasunak adituen azterketara bideratzen dira.",
    rulesVersion: "Arauen bertsioa",
    dataVersion: "Produktu-datuen bertsioa",
    steps: { role: "Rola", sport: "Kirola", experience: "Esperientzia", objectives: "Helburuak", style: "Joko-estiloa", equipment: "Egungo ekipamendua", preference: "Lehentasunak", coach: "Entrenatzailearen parte-hartzea", ageBand: "Adin-tartea", review: "Berrikuspena" },
    notStored: "Ez da nabigatzaile honetan gordetzen.",
    ageNote: "Eskaera bideratzeko soilik erabiltzen da. Ez da izenik, jaiotze-datarik edo mediku-informaziorik eskatzen.",
    q: {
      role: "Zein da zure rola?",
      sport: "Zein kirol?",
      experience: "Esperientzia-maila",
      objectives: "Zer da garrantzitsuena? (hiru arte hautatu)",
      style: "Joko-estiloa, ezagutzen baduzu",
      equipment: "Egungo ekipamendua, baldin baduzu",
      equipmentHint: "Marka eta modeloa, pisua edo heldulekua ezagutzen badituzu. Aukerakoa.",
      preference: "Nahiago duzun konfigurazioa edo ezagutzen duzun helduleku-neurria",
      grip: "Ezagutzen duzun helduleku-neurria",
      coach: "Entrenatzaile batek parte hartzen du zure ekipamendu-erabakietan?",
      ageBand: "Jokalariaren adin-tartea (eskaera behar bezala bideratzeko soilik erabiltzen da)",
    },
    roles: { player: "Jokalaria", parent: "Gurasoa edo tutorea", coach: "Entrenatzailea", club: "Kluba edo akademia", other: "Bestelakoa" },
    sports: { tennis: "Tenisa", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Beste erraketa-kirol bat" },
    sportNote: "Produktuak tenisarako daude. Beste kirolak garapen-norabideak dira; zure interesa dagokion programarako erregistratzen da.",
    experience: { beginner: "Hasiberria", developing: "Garatzen", intermediate: "Ertaina", advanced: "Aurreratua", competitive: "Lehiakorra", professional: "Profesionala" },
    objectives: { control: "Kontrola", power: "Indarra", spin: "Efektua", comfort: "Erosotasuna", manoeuvrability: "Maneiagarritasuna", development: "Epe luzeko garapena", competition: "Lehiaketa", training: "Entrenamendu-sistema", team: "Taldea edo multzo parekatua", personal: "Pertsonalizazioa" },
    styles: { baseline: "Atzeko lerrokoa", allcourt: "Pista osokoa", attacking: "Erasokorra", defensive: "Defentsiboa", coach: "Entrenatzaileak hautatua", unknown: "Ez dakit zehatz" },
    ageBands: { u10: "10 urtetik beherakoa", u14: "10–13", u18: "14–17", adult: "18 urte edo gehiago" },
    output: {
      title: "Zure ekipamendu-profila",
      status: "Adituen azterketa behar da",
      statusP: "Bertsio honetan ez da bat-etortze automatikorik sortzen. Zure profila adituen azterketarako laburbildu da.",
      directionsTitle: "Aplikatzen diren konfigurazio-norabideak",
      directionsP: "Adierazi dituzun helburuetan eta serie bakoitzaren jokoaren norabide adierazian oinarrituta. Norabide bat da, ez doikuntza-gomendio bat.",
      trainingHint: "Zure helburuen artean entrenamendu-sistema bat dago: ikusi Sweet Spot Trainer eta Spot Trainer.",
      teamHint: "Multzo parekatuak konfiguragailuaren bidez eskatzen dira eta idatziz berresten dira.",
      next1: "Bidali profila adituen azterketara",
      show: "Erakutsi nire profila",
      configure: "Konfiguratu",
      sendP: "Bidali zure profila MAXIMUS taldeari adituen azterketa egiteko. Eskaeraren identifikatzailea berehala erakusten da; erantzuna idatziz dator.",
      otherSport: "MAXIMUS erraketak tenisarako daude. Beste erraketa-kiroletarako ez da tenis-serierik proposatzen; zure interesa garapen-norabide gisa erregistratzen da.",
      noDirection: "Zure helburuek ez dute jokoaren norabide bakar bat seinalatzen. Adituen azterketak konfigurazio bat proposatzen du.",
      incomplete: "Beharrezko erantzun batzuk falta dira — erabili «Editatu erantzunak» osatzeko.",
    },
    privacy: "GPSak ez du osasun-informaziorik edo haurren identifikatzailerik eskatzen. Nabigatzailearen saio honetan aukera anizkoitzeko erantzunak soilik gordetzen dira; testu librea ez da gordetzen.",
  },
  build: {
    title: "Osatu zurea",
    lead: "Konfiguratu eskaera bat: seriea, zehaztasun-klasea, katalogoko pisua edo helburu pertsonalizatua, helduleku-neurria, eskatutako helburuak, pertsonalizazioa, multzo parekatuak eta kopurua. Emaitza identifikatzailea duen konfigurazio-eskaera bat da — ez SKU bat, ez prezioa, ez entrega-data, ez ziurtagiria.",
    steps: { series: "Seriea", cls: "Zehaztasun-klasea", weight: "Pisua", grip: "Heldulekua", targets: "Helburuak", personal: "Pertsonalizazioa", set: "Multzoa eta kopurua", use: "Erabilera", review: "Berrikuspena" },
    q: {
      series: "Aukeratu serie bat",
      cls: "Aukeratu zehaztasun-klase bat",
      weightMode: "Pisua",
      listed: "Katalogoko pisua",
      customWeight: "Eskatutako pisua (g)",
      balanceShown: "Pisu honetarako kalkulatutako balantzea",
      balanceRequest: "Eskatutako balantzea (mm)",
      grip: "Fabrikako helduleku-neurria",
      targetsTitle: "Eskatutako helburuak",
      swingweight: "Eskatutako swingweight (kg·cm²)",
      stiffness: "Eskatutako zurruntasuna (RA)",
      basis: "Eskatutako balioen neurketa-oinarria",
      engraving: "Grabatuaren testua",
      engravingHint: "Izena, inizialak edo zenbakia. Letra latinoak, zifrak, zuriunea, marratxoa, apostrofoa eta puntua; 24 karaktere arte. Beste idazkerak arte-lanaren berrespenarekin onartzen dira.",
      engravingType: "Pertsonalizazioa",
      types: { none: "Bat ere ez", name: "Jokalariaren izena", initials: "Inizialak", number: "Multzoaren zenbakia", academy: "Entrenatzailearen edo akademiaren identifikazioa", team: "Taldeko programa" },
      set: "Erraketa bakarra edo multzo parekatua",
      use: "Aurreikusitako erabilera",
      uses: { play: "Norberaren jokoa", competition: "Lehiaketa", coaching: "Entrenamendua", team: "Taldea edo akademia", retail: "Txikizkako edo banaketa-ebaluazioa", other: "Bestelakoa" },
      notes: "Eskakizun tekniko gehigarriak",
    },
    classes: { "P2.5": "P2.5 — errendimendu-nukleo eskalagarria", "P1.5": "P1.5 — zehaztasun aurreratua", "P0.5": "P0.5 — profesionala, banaka kontrolatua" },
    stiffExactShort: "zurruntasuna adierazitako RA balioarekin bat dator fabrikako protokolo ezarriaren arabera",
    clsNote: "Klase bakoitzak lau parametro kontrolatzen ditu. P0.5 tolerantzia estua da neurketa-protokolo zehatz baten barruan — ez da errore zero. Serie-identitatea, ziurtagiriak eta multzo parekatuen dokumentazioa zure eskariaren programak halakorik ezartzen duenean soilik aplikatzen dira.",
    listedNote: "Seriearen matrize berretsitik.",
    customNote: "Matrizetik kanpoko pisua, teknikoki aztertuta.",
    balanceCaption: "Katalogoko pisu bakoitzak bere balantze kalkulatua erakusten du, mm-tan oinarri-tapatik. Kalkulatutako balioak ez dira neurketa indibidualak.",
    spinNote: "SPIN seriearen pisuek eskatutako pisu-arkitektura osatzen dute. SPIN seriearen balantzea, swingweight-a eta zurruntasuna ez dira ematen; azterketa teknikoan zehazten dira.",
    customHint: "Gramo osoak, zifrak soilik. Pisu pertsonalizatua azterketa teknikoaren eskaera bat da; bideragarritasuna idatziz berresten da eta ez da baliorik biribiltzen.",
    gripNote: "fabrikako karbonozko helduleku-geometria, ez gainestalkiz lortutako lodiera",
    targetsLead: "Aukerakoa. Sartu behar dituzun balioak soilik. Bakoitza azterketa teknikorako eskatutako helburu gisa erregistratzen da, ez argitaratutako zehaztapen gisa.",
    basisHint: "Beharrezkoa pisu pertsonalizatu bat edo edozein helburu eskatzen duzunean: balioak kordarik gabeko erraketari ala kordatutako erraketari dagozkio?",
    inputRange: "Onartutako sarrera: {min}–{max}.",
    inputRangeNote: "Sarrera-tarteek balio ezinezkoak baztertzen dituzte soilik. Ez dute ekoizpen-gaitasuna deskribatzen.",
    listedBasis: "katalogoko balioak — neurketa-oinarria zehaztapen idatzian berretsia",
    notStored: "Ez da nabigatzaile honetan gordetzen; sartu berriro orria birkargatzen baduzu.",
    artworkReview: "arte-lanaren berrespena beharrezkoa",
    previewNote: "Ez da aurrebista erakusten: modelo honentzat onartutako grabatu-txantiloia oraindik ez da argitaratu. Zure testua arte-lana berresteko biltzen da.",
    teamSub: "4–99 erraketa multzo bakoitzeko",
    setsLabel: { individual: "Erraketa kopurua", pair: "Bikote parekatuen kopurua", triple: "Hirukote parekatuen kopurua", team: "Taldeko multzoen kopurua" },
    teamSizeLabel: "Erraketak taldeko multzo bakoitzeko",
    totalLabel: "Erraketak guztira",
    racquetsUnit: "erraketa",
    setRule: "Kopuruak multzoak zenbatzen ditu: bikote parekatu bat 2 erraketa da multzo bakoitzean, hirukote parekatu bat 3.",
    restart: "Hasi konfigurazio berri bat",
    notices: { weightCleared: "{w} g ez dago {series} seriearen matrizean, eta, beraz, pisua garbitu da. Aukeratu katalogoko pisu bat edo eskatu helburu pertsonalizatu bat." },
    reviewTitle: "Konfigurazio-eskaera",
    reviewP: "Egiaztatu konfigurazioa eta gehitu zure harremanetarako datuak. Eskaera identifikatzaile batekin gordetzen da eta idatziz erantzuten da; eskuragarritasuna eta baldintza komertzialak idatziz berresten dira.",
    reviewErrors: "Konfigurazioaren erantzun batzuk berrikusi behar dira:",
    edit: "Editatu",
    fieldNames: { series: "Seriea", cls: "Zehaztasun-klasea", mode: "Pisuaren hautaketa", weight: "Katalogoko pisua", customWeight: "Eskatutako pisua", basis: "Neurketa-oinarria", balanceReq: "Eskatutako balantzea", sw: "Eskatutako swingweight", ra: "Eskatutako zurruntasuna", grip: "Helduleku-neurria", ptype: "Pertsonalizazioa", engraving: "Grabatuaren testua", setType: "Multzo-mota", sets: "Kopurua", teamSize: "Erraketak taldeko multzoko", use: "Aurreikusitako erabilera", notes: "Eskakizun gehigarriak" },
    status: { listed: "katalogoko pisua", requestedArchitecture: "eskatutako pisu-arkitektura", technicalReview: "azterketa teknikoaren eskaera", notPublished: "ez da eman", requestedCondition: "eskatutako egoera" },
    chooseLink: "Ez dakizu zein serie datorkizun ondo? Eskatu laguntza aukeratzeko",
    cta: "Bidali konfigurazio-eskaera",
  },
  experience: {
    title: "Esperientzia eta doikuntza",
    statement: "Hartu eskuetan. Astindu. Sentitu.",
    lead: "Eskatu proba bat, doikuntza bat edo entrenatzailearen laguntzaz egindako erakustaldi bat. Eskaerak aztertu eta idatziz erantzuten dira; bidalitako eskaera bat ez da hitzordu berretsia.",
    optionsTitle: "Zer eska daiteke",
    options: ["Erraketen proba", "Doikuntza-saioa", "Entrenatzailearen laguntzaz egindako erakustaldia", "Sweet Spot Trainer edo Spot Trainer erakustaldia", "Talde edo akademientzako proba-eguna"],
    formTitle: "Doikuntza- edo erakustaldi-eskaera",
  },
  engineering: {
    title: "Ingeniaritza eta fabrikazioa",
    statement: "Hegazkinak. Yateak. Erraketak.",
    lead: "Ingeniaritza-filosofia bakarra hiru ingurunetan: hegazkin bat moldatzen duten printzipioak, yate bat itsaso zabalean gidatzen duen zehaztasuna, MAXIMUS erraketa bakoitza definitzen duen errendimendua. Ingeniaritza-narrazio bat da — ez hegazkin-ziurtagiririk, yate-jabetzarik, fabrika-jabetzarik edo material-transferentzia zuzenik baieztatzea.",
    manifesto: ["Ingeniaritza handiak mugarik ez duela uste dugu.", "Filosofia bat. Amorerik gabe diseinatua."],
    capabilityTitle: "Fabrikazio-gaitasuna",
    capabilityLead: "Gaitasuna sekuentzia gisa erakusten da, ez esaldi gisa.",
    sequence: [
      ["Zehaztapena", "Seriea, zehaztasun-klasea, pisua, balantzea, swingweight-a, zurruntasun-helburua, heldulekuaren geometria, pertsonalizazioa."],
      ["Ekoizpena", "Osorik karbonozko eraikuntza markotik heldulekura, zehaztapenaren arabera ekoitzita."],
      ["Kalitate-kontrola", "Neurketa eta erregistroak zehaztasun-klasearen arabera: ekoizpen-erregistroak, erregistro indibidualak eta trazabilitatea, ziurtapen indibiduala."],
      ["Ekoizpen errepikatua", "Erantzun errepikagarria adierazitako zehaztapenaren aurrean loteen artean."],
      ["Trazabilitatea", "Serie-identitatea, lotearen trazabilitatea eta Zehaztasun Ziurtagiria, klaseak hala aurreikusten duenean."],
    ],
    capacityNote: "Ekoizpen-ahalmena, epeak, gutxieneko kopuruak eta entrega-egutegiak programa bakoitzeko idatziz berresten dira, berretsitako eskarien eta adostutako askatze-egutegiaren arabera.",
    truth: "Ahalmena ez da ekoizpena, ez izakinak, ez entrega-data bermatua, ez fabrika baten jabetza.",
    cta: "Banaketa eta herrialdeen garapena",
    cta2: "Aurkeztu txosten tekniko bat",
  },
  ecosystem: {
    title: "MAXIMUS ekosistema",
    lead: "Giltza bat. Hau da irekitzen duena. Nodo bakoitzak azalpen bat, egoera zehatz bat eta hurrengo ekintza egoki bat du.",
    words: ["Ingeniaritza", "Errendimendua", "Berrikuntza", "Komunitatea", "Aukera", "Xedea"],
    nodes: {
      engineering: { h: "Erraketen ingeniaritza eta fabrikazioa", p: "Zehaztapenaren arabera diseinatutako osorik karbonozko erraketak, kalitate-erregistroekin eta trazabilitatearekin ekoitzita.", a: "Ingeniaritza eta fabrikazioa" },
      precision: { h: "Zehaztasuna eta konfigurazio indibiduala", p: "Lau parametro, hiru zehaztasun-klase, zortzi helduleku-neurri eta ingeniaritza pertsonalizatua.", a: "Zehaztasuna eta zurruntasuna" },
      training: { h: "Entrenamendua eta metodologia", p: "Sweet Spot Trainer, Spot Trainer eta garapen-ibilbide egituratu bat.", a: "Entrenamendu-sistemak" },
      development: { h: "Jokalarien eta entrenatzaileen garapena", p: "Entrenatzaileak gidatutako hautaketa, erregistroak, berrebaluazioa eta prestakuntza-bideak.", a: "Metodologia" },
      identity: { h: "Identitate pertsonala eta marka pertsonalak", p: "Grabatutik eskubidez araututako marka pertsonal edo profesional batera.", a: "Marka pertsonalak" },
      owners: { h: "Jabeen erregistroak, jakintza eta eskubideak", p: "Baimen bidezko jabe-ganbera proposatu bat ekipamenduaren, garapenaren eta eskubideen erregistroetarako.", a: "Jabeak eta ganbera" },
      mipa: { h: "MIPA jatorria eta barne-kontrola", p: "Jabetza intelektualaren, jatorriaren eta dokumentu-kontrolaren barne-geruza.", a: "Identitate juridikoa eta kontrola" },
      digital: { h: "Azpiegitura digitala eta Blockchain 5.0 norabidea", p: "Jatorria, erregistro trazagarriak, baimen bidezko frogak eta produktuaren identitatea adierazitako teknologia-norabide gisa.", a: "Teknologia-norabidea" },
      licensing: { h: "Kontratu bidezko lizentziak eta kanon-programak", p: "Lizentziatutako markak, produktuak eta eskubide-paketeak, akordio bakoitzean zehaztutako baldintzekin.", a: "Lizentzia-bideak" },
      families: { h: "Familien parte-hartzea eta programaren onurak", p: "Erabaki informatuak, jarraitutasuna, gordetako erregistroak eta programak zehaztutako onurak.", a: "Familiak eta gurasoak" },
      network: { h: "MAXIMUS Sports Network", p: "Jokalariak, entrenatzaileak, klubak, akademiak, zerbitzu-hornitzaileak, operadoreak eta eskualdeko bazkideak.", a: "Sports Network" },
      market: { h: "Klubak, akademiak, banaketa eta herrialdeen garapena", p: "Taldeko programak, txikizkako salmenta, banaketa eta lurraldeen garapena idatzizko kalifikazioaren bidez.", a: "Lankidetza-bideak" },
      institutional: { h: "Erakunde-programak, prestakuntza, berrikuntza eta eragin soziala", p: "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) erakundeak eskaintzen duen erakunde-geruza, programa batek rol hori ezartzen duenean.", a: "Erakunde-programak" },
      extensions: { h: "Etorkizuneko erraketa-kirolak eta MAXIMUS arroparen hedapenak", p: "Padel, pickleball, squash, badminton, racquetball, hondartza-tenisa eta arropa garapen-norabide gisa.", a: "Erraketa-kirolak" },
    },
    boundaryTitle: "Mugak",
    boundary: [
      "Erraketa bat erostea ez da erakunde-kidetza, ez gobernantza-eskubide, ez kanon, ez inbertsio-eskubide.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) erakunde-operadorea da programa batek rol hori ezartzen duenean soilik; ekipamenduaren salmentek beren benetako kontratu-entitatea identifikatzen dute.",
      "Diru-laguntzak, ongintza-izaera, tratamendu fiskala eta araudiaren baimenak ez dira automatikoki aplikatzen herrialde guztietan.",
    ],
    techTitle: "Teknologia-norabidea",
    techP: "Blockchain 5.0 da MAXIMUS markak adierazitako teknologia-norabidea. Haren xede funtzionalak jatorria, erregistro trazagarriak, baimen bidezko frogak, produktuaren identitatea eta baldintzak betetzen dituzten gertaera komertzialen bateratzea dira. Ez da adostasun-mekanismorik, transakzio-ahalmenik, nodo-sarerik, kontratu adimentsuen helbiderik, tokenik edo ziurtapen independenterik irudikatzen, eta ez da inplementazio hedaturik baieztatzen. Informazio pertsonala, haurren erregistroak eta akordio konfidentzialak inoiz ez dira lehenespenez sistema publiko aldaezin batean jartzen.",
  },
  brands: {
    title: "Marka pertsonalak eta enbaxadoreak",
    statement: "Jokalaritik markara. Entrenatzailetik markara.",
    lead: "Marka pertsonalerako bide berezia. MAXIMUS markaren parte-hartzeak marka-garapena eta adostutako promozioa biltzen ditu — ez erraketa batean izen bat soilik.",
    progressionTitle: "Aurreikusitako bilakaera",
    progression: [
      ["Egiaztatutako identitatea", "Egiaztatutako identitate bat eta garapen-historia bat."],
      ["Marka berezia", "Marka pertsonal edo profesional berezi bat."],
      ["Eskubideak argituta duen edukia", "Eskubideak argituta duen edukia eta onartutako produktu-identitatea."],
      ["Ingeniaritza eta bildumak", "Ingeniaritza eta bildumen garapena, hala adosten denean."],
      ["Promozioa", "Promozioa adostutako MAXIMUS kanalen eta lankidetzen bitartez."],
      ["Parte-hartzea", "Kontratu bidezko parte-hartzea baldintzak betetzen dituzten salmentetan edo lizentzietan."],
      ["Txostenak", "Txosten gardenak akordioaren arabera."],
    ],
    royaltiesTitle: "Kanonak eta lizentziak",
    royalties: [
      "Kanonak zehaztutako marka, produktu, eragiketa edo eskubide-pakete lizentziatuari lotzen zaizkio.",
      "«Mundu osoko salmentak» kontratuaren irismenaren barruan baldintzak betetzen dituzten salmentak esan nahi du — inoiz ez zerikusirik ez duen MAXIMUS erraketa oro.",
      "Tasak, kalkulu-oinarria, lurraldeak, epea, itzulketak, kenkariak, txostenak, likidazioa eta egiaztapena dagokion akordioan zehazten dira. Ez da lehenespeneko kanon-ehunekorik argitaratzen.",
      "Ez da kanpaina global, komunikabide-aurrekontu, babes-emaitza edo arrakasta komertzialik agintzen irismen adosturik gabe.",
    ],
    cta: "Bidali marka-lankidetzaren kontsulta",
    cta2: "Entrenatzaileen lankidetza-kontsulta",
  },
  families: {
    title: "Familiak eta gurasoak",
    lead: "Ekipamendu-erabaki informatuak, garapenaren jarraitutasuna, gordetako jakintza eta eskubideak, parte-hartzearen ikusgarritasuna eta programak zehaztutako onurak, etorkizuneko jarduera lagun ditzaketenak.",
    nowTitle: "Orain eskuragarri",
    now: ["Familia- eta garapen-kontsultak idatziz.", "Entrenatzailearen parte-hartzearekin egindako ekipamendu-hautaketa, doikuntza eta erakustaldi-eskaerak.", "Erregistro pribatuak: haurren profilak inoiz ez dira argitaratzen eta lehenespenez ez dira merkaturatzen.", "Gurasoentzako prestakuntza-bidea: konfigurazioa, karga, progresioa, erregistroak eta eskubideak."],
    plannedTitle: "Aurreikusita",
    planned: ["Programak zehaztutako parte-hartze onurak, ekosistemaren barruko ondasun eta zerbitzuetarako erabilgarriak, diru-interesaren ordez.", "Jabeen eta familien erregistroak proposatutako jabe-ganberan, tutorearen baimenekin eta 18 urterekin kontrolaren eskualdatzearekin."],
    categoriesTitle: "Bereiz gordetzen dira",
    categories: ["Lizentziatutako eskubideetatik edo baldintzak betetzen dituzten salmentetatik datozen kontratu-kanonak", "Programa batek zehaztutako parte-hartze onurak", "Erosketa- edo zerbitzu-kredituak", "Aurrerakinak", "Erakunde-kidetza"],
    categoriesP: "Kategoria hauek inoiz ez dira elkarrekin trukagarri gisa tratatzen.",
    statusTitle: "Familia-programaren egoera erreala",
    journeyTitle: "Familia-bidea",
    journey: [
      ["Helburua", "Zer lortu nahi du jokalariak hurrengo urratsean."],
      ["Egungo maila", "Non dago jokalaria gaur."],
      ["Entrenatzailea", "Entrenatzaile batek ekipamendu-erabakietan parte hartzen duen ala ez."],
      ["Ekipamendua", "Etaparako ekipamendu egokia, entrenamendu-sistemak barne hala badagokio."],
      ["Adostutako lanketa", "Entrenatzaileak gidatutako erabilera aurrez adostuta."],
      ["Berrikuspena", "Berrebaluazioa kontrol-puntu alderagarrietan."],
    ],
    brief: {
      who: "Edozein etapan dauden jokalarien gurasoak eta tutoreak.",
      value: "Erantzun idatzi bat ekipamendu egokiari, entrenatzailearen parte-hartzeari eta garapenaren hurrengo urratsari buruz.",
      now: "Familia-kontsultak idatziz; entrenatzailearen parte-hartzearekin egindako hautaketa; erregistro pribatuak — haurren profilak inoiz ez dira argitaratzen.",
      next: "Bidali beheko familia-kontsulta. Eskaeraren identifikatzailea berehala jasotzen duzu.",
    },
    formTitle: "Familia-kontsulta",
    formNote: "Gurasoak edo tutoreak bete behar du. Ez sartu haurraren izena, jaiotze-data, ikastetxea edo mediku-informazioa.",
    noPromise: "Erosketa batek ez du kanonik, inbertsio-errendimendurik, babeslerik edo haur baten garapenerako finantzaketarik agintzen.",
    statusP: "Bertsio honek eredua azaltzen du eta programa-kontsultak onartzen ditu. Sortzapena, ordainketak eta trukea ez daude eskuragarri baldintzak betetzen dituzten gertaerak, onuradunak, finantzaketa-iturria, kalkulu-oinarria, onartutako erabilerak, kontabilitate-tratamendua, itzulketak, atzera-eragiteak, iraungipena, eskualdagarritasuna, programaren itxiera eta gatazken kudeaketa idatziz zehazten diren arte. Ez da inoiz jaitsiko ez den saldorik agintzen, parte-hartze batek ez du entrenamendu osoa ordaintzen eta ez da kapitalaren babesik iradokitzen.",
    cta: "Bidali familia- edo garapen-kontsulta",
  },
  owners: {
    title: "Jabeak eta jabearen ganbera",
    lead: "Jabearen ganbera ekipamenduaren, garapenaren, jakintzaren, edukiaren eta dokumentatutako eskubideen baimen bidezko erregistro proposatu bat da. Aurreikusitako jabe-arkitekturaren zati gisa aurkezten da: ez da kontu, saldo, ziurtagiri edo lorpen aktiborik erakusten.",
    nowTitle: "Egungo jabeentzat orain",
    now: ["Jabeen kontsultak: produktu- edo serie-erreferentzia, prestaketa, zerbitzua eta erregistro-eskaerak idatziz.", "Zehaztasun Ziurtagiria eta multzo parekatuen dokumentazioa, zehaztasun-klaseak hala aurreikusten duenean, produktuarekin batera emanda."],
    archTitle: "Ganberaren arkitektura aurreikusia",
    arch: ["Produktuaren identitatea eta serie-erreferentziak", "Konfigurazioa eta dagozkion kalitate-kontroleko ziurtagiriak", "Zerbitzuaren eta prestaketaren historia", "Jokalariaren edo entrenatzailearen garapen-erregistroak", "Kualifikazioak eta egiaztatutako lorpenak", "Eskubideak argituta dituen materiala eta sortutako materialak", "Lizentziak, baimenak eta kontratu-erreferentziak", "Marka pertsonalaren programaren erregistroak", "Dagozkion kanon-txostenak edo parte-hartze onurak"],
    separationTitle: "Zer esan nahi du jabetzak",
    separation: [
      "Erraketa fisiko baten jabetza bereizia da egile-eskubideen, lizentzia baten, kontratu-eskubide baten edo horiek deskribatzen dituen erregistro baten jabetzatik.",
      "Gordetako dokumentu bat edo bloke-kateko sarrera bat ez da automatikoki eskubide juridiko bat existitzen edo eskualdatu dela frogatzen duen froga.",
      "Frogek beren sailkapena gordetzen dute: parte-hartzaileak adierazita, tutoreak berretsita, entrenatzaileak balioztatuta, sistemak neurtuta.",
      "Adingabeentzat: erregistro pribatuak, tutorearen baimenak, haurren profil argitaraturik ez eta lehenespenez identitatearen merkaturatzerik ez.",
      "Esportazioa, zuzenketa, sarbide-kontrola eta kontrolaren eskualdatze egokia diseinuaren parte dira.",
    ],
    techTitle: "Blockchain 5.0 eta MxSN",
    techP: "Blockchain 5.0 da adierazitako teknologia-norabidea; MxSN sistemak baimen bidezko sare baten kontzeptuak zehazten ditu baimenerako, entregarako, frogetarako, eskubideetarako eta txostenetarako. Ez da inplementazio operatiborik irudikatzen. Aplikazioaren datu-eredua geroago interfaze dokumentatu baten bidez integratzeko eraikita dago, gaur konexio bat badela itxurarik egin gabe.",
    cta: "Jabearen kontsulta",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Jokalarien, entrenatzaileen, kluben, akademien, zerbitzu-hornitzaileen, programa-operadoreen eta eskualdeko bazkideen arteko lotura.",
    functionsTitle: "Balizko funtzioak",
    functions: ["Aurkikuntza", "Aurkezpenak", "Garapen-programak", "Ekipamendu-laguntza", "Ekitaldiak", "Zerbitzuetarako sarbidea", "Bazkideentzako aukerak"],
    statusTitle: "Egoera erreala",
    statusP: "Oraindik ez da direktorio publikorik argitaratzen: identitatea, lotura eta agertzeko baimena finkatuta dituzten parte-hartzaileak soilik zerrendatuko dira. Klub bati bidalitako proposamen bat ez da lankidetza bat, eta banatzaile izateko hautagai bat ez da izendatutako banatzaile bat. Direktorioaren argitalpena, erreserbak, mezularitza eta eragiketa komertzialak bereiz kontrolatzen dira eta ez daude martxan.",
    cta: "Eskatu sarean sartzea",
  },
  partnerships: {
    title: "Lankidetza-bideak",
    lead: "Lehenik kalifikazioa idatziz. Bide bakoitza rolaren araberako kontsulta batera darama; baldintza komertzialak gero idatziz datoz.",
    commercialTitle: "Plataformaren balizko jarduera komertzialak",
    commercial: ["Ekipamendua", "Ingeniaritza pertsonalizatua", "Pertsonalizazioa", "Talde eta akademien programak", "Entrenamendu-sistemak", "Kontratu bidezko lizentziak", "Banaketa", "Onartutako zerbitzuak", "Etorkizuneko produktu-kategoriak"],
    boundary: "Herrialde-eskubideak, esklusibotasuna, lurralde-kuotak eta banatzailearen marjinak negoziatutako baldintzak dira. Ez da diru-sarrera, aurreikuspen, balorazio, merkatu-kuota, errendimendu, finantzaketa-konpromiso edo izenik gabeko lankidetzarik argitaratzen.",
    routes: {
      coaches: {
        title: "Entrenatzaileak",
        lead: "Entrenamendu-sistemak, doikuntza, identitate profesionala, baimendutako programak, marka pertsonalaren aukerak eta ekipamendu-hornidura.",
        points: ["Sweet Spot Trainer eta Spot Trainer entrenatzaileak gidatutako lanketan.", "Doikuntza konfigurazio-matrizeekin eta fabrikako zortzi helduleku-neurriekin.", "Coach-to-Brand: profil profesional egiaztatu bat eta eskubidez araututako azpimarka bat.", "Programen erabilera baimendua akordio idatzi baten araberakoa da."],
        cta: "Bidali entrenatzaileen lankidetza-kontsulta",
        brief: {
          who: "Entrenatzaile independenteak eta entrenatzaile-taldeak.",
          value: "Entrenatzaileak gidatutako lanketarako entrenamendu-sistemak, doikuntza serieen matrizeekin eta fabrikako zortzi heldulekuekin, eta identitate profesional baterako bidea.",
          now: "Entrenatzaileen kontsultak idatziz. Ez da komisio, irabazi edo gomendio-tasarik argitaratzen edo iradokitzen.",
          next: "Bidali beheko entrenatzaile-kontsulta. Baldintzak gero idatziz datoz.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubak eta akademiak",
        lead: "Taldeko ekipamendua, entrenamendu-sistemak, pertsonalizazioa, garapen-programak, zerbitzua eta sareko parte-hartzea.",
        points: ["Taldeko eta parekatutako multzoak konfiguragailuaren bidez eskatuta.", "Entrenamendu-sistemak eta metodologia garapen egituratuarentzat.", "Pertsonalizazioa taldeko programetarako onartutako guneetan.", "Proba-egunak, doikuntza-saioak eta sareko parte-hartzea."],
        cta: "Bidali klub edo akademiaren txostena",
        brief: {
          who: "Klubak, akademiak eta taldeko programak.",
          value: "Taldeko eta parekatutako multzoak, entrenamendu-sistemak, taldeko programetarako pertsonalizazioa eta erakustaldi-egunak.",
          now: "Klub eta akademien txostenak idatziz; taldeko multzoak konfiguragailuaren bidez eskatzen dira.",
          next: "Bidali beheko klub edo akademiaren txostena.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Banaketa eta herrialdeen garapena",
        lead: "Sortimendua, fabrikazioaren koordinazioa, gaitasun teknikoa, lurraldeen garapena eta kalifikazio komertzial konfidentziala.",
        points: ["Kontrako aldearen, lurraldearen eta kanalaren kalifikazioa idatziz.", "Sortimendua konfigurazio-matrizeetatik eta zehaztasun-klaseetatik zehaztuta.", "Lurraldea, esklusibotasuna, bolumenak, prezioak eta babes komertziala negoziatutako baldintzak dira, idatziz adostuta.", "Kontratu-entitatea, ordainketa-baldintzak eta entrega-oinarria eragiketa bakoitzean identifikatzen dira."],
        cta: "Bidali banaketa- edo herrialde-garapenaren kontsulta",
        brief: {
          who: "Dendariak, banatzaileak eta herrialdeko bazkideak.",
          value: "Matrize berretsietatik, zehaztasun-klaseetatik eta helduleku-gamatik zehaztutako sortimendua, lurraldearen eta kanalaren kalifikazioa idatziz.",
          now: "Banaketa-kontsultak idatziz. Lurraldea, esklusibotasuna, bolumenak eta prezioak negoziatzen dira — ezer ez da inprimaki baten bidez ematen.",
          next: "Bidali beheko banaketa-kontsulta.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Estrategia eta inbertsioa",
        lead: "Ingeniaritza-gaitasuna, konfigurazioaren sakontasuna, fabrikazio-eredua, merkaturako bideak, jabetza intelektuala, zerbitzuak eta hedapen-aukerak.",
        points: ["Elkarrizketa estrategiko kalifikatua edo informazio-sarbide kontrolatua kalifikazio idatziaren ondoren dator.", "Informazio publikoa onartutako produktu-zehaztapenetara, konfigurazio-arkitekturara, egiaztatutako gaitasunetara eta programen azalpenetara mugatzen da.", "Erosleari lotutako ekonomia, kostu-kalkuluak, babestutako metodologia eta argitaratu gabeko akordioak konfidentzialtasun-akordio edo kontratu baten barruan soilik ezagutarazten dira."],
        cta: "Eskatu elkarrizketa estrategiko kalifikatu bat",
        brief: {
          who: "Inbertitzaileak eta bazkide estrategikoak.",
          value: "Ingeniaritza-gaitasunari, konfigurazioaren sakontasunari, fabrikazio-ereduari, merkaturako bideei eta jabetza intelektualari buruzko elkarrizketa kalifikatua.",
          now: "Ez da finantza-zifra, aurreikuspen, balorazio edo errendimendurik argitaratzen. Informazio kontrolatua kalifikazio idatziaren eta konfidentzialtasun-akordioaren ondoren dator.",
          next: "Eskatu beheko elkarrizketa estrategiko kalifikatua.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Erakunde-programak",
        lead: "Prestakuntza, sarbidea, berrikuntza, garapenaren frogak, eragin soziala eta behar bezala egituratutako programak.",
        points: ["Erakunde-programak MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) erakundearen bidez egituratzen dira, programak rol hori ezartzen duenean.", "Programaren funts mugatuak eta eragiketa komertzialak bereizita daude.", "Kontsulta bat ez da onartutako kidetza-eskaera bat, eta ekipamendu-erosle bat ez da erakundeko kide bat.", "Diru-laguntzak, ongintza-izaera, tratamendu fiskala eta araudiaren baimenak herrialde bakoitzari dagozkio eta inoiz ez dira aurretik emantzat hartzen."],
        cta: "Bidali erakunde-programaren kontsulta",
        brief: {
          who: "Erakundeak, prestakuntza- eta garapen-programak.",
          value: "Prestakuntzarako, sarbiderako, berrikuntzarako eta garapenaren frogetarako programak, operadore egokiarekin egituratuta.",
          now: "Erakunde-kontsultak idatziz. Kontsulta bat ez da kidetza-eskaera bat; ekipamendua erostea ez da erakunde-kidetza.",
          next: "Bidali beheko erakunde-kontsulta.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Ezagutarazte publikoa eta kontrolatua",
    disclosure: {
      public: { h: "Publikoa", p: "Onartutako produktu-zehaztapenak, eraikuntza, konfigurazio-arkitektura, entrenamendu-xedeak, egiaztatutako gaitasunak, programen azalpenak eta lankidetza-bideak." },
      qualified: { h: "Kontsulta kalifikatua", p: "Eskakizun teknikoak, kopuruak, lurralde-interesa, garapenaren irismena eta dagozkion elkarrizketa komertzialak." },
      controlled: { h: "Konfidentzialtasun-akordio edo kontratu bidez kontrolatua", p: "Barne-formulak, kalitate-kontrolaren protokolo zehatzak, laminatuak, tresneria, fabrikazio-metodoak, hornitzaileen identitatea, kostu-kalkuluak, erosleari lotutako ekonomia, babestutako metodologia, argitaratu gabeko akordioak eta eskubideen erregistro sentikorrak." },
    },
  },
  contact: {
    title: "Harremana eta eskaerak",
    lead: "Aukeratu zure eskaeraren xedea. Inprimaki bakoitzak bideratzeko eta ebaluatzeko behar dena soilik biltzen du. Eskaerak idatziz erantzuten dira.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Identitate juridikoa",
  },
  form: {
    purposeLabel: "Eskaeraren xedea",
    purposes: {
      selection: "Laguntza erraketa aukeratzeko",
      product: "Produktuari buruzko kontsulta",
      fitting: "Doikuntza edo erakustaldia",
      technical: "Txosten teknikoa",
      config: "Konfigurazio-eskaera",
      gps: "GPS ekipamendu-profila",
      coach: "Entrenatzailearen lankidetza",
      club: "Klub edo akademiaren txostena",
      distribution: "Banaketa edo herrialdearen garapena",
      brand: "Marka-lankidetza edo enbaxadorea",
      family: "Familia- edo garapen-kontsulta",
      institutional: "Erakunde-programa",
      strategic: "Elkarrizketa estrategikoa edo inbertsioa",
      owner: "Jabearen kontsulta",
      network: "Sports Network sarerako eskaera",
      general: "Kontsulta orokorra",
    },
    fields: {
      name: "Izena",
      email: "Email",
      role: "Zure rola",
      country: "Herrialdea edo eskualdea",
      organisation: "Erakundea",
      message: "Zure mezua",
      level: "Egungo maila",
      objectives: "Zer da garrantzitsuena (hiru arte)",
      currentRacquet: "Egungo erraketa",
      grip: "Helduleku-neurria, ezagutzen baduzu",
      seriesInterest: "Interesatzen zaizun seriea",
      quantity: "Kopurua",
      city: "Saioaren hiria edo lekua",
      coachInvolved: "Entrenatzaile batek parte hartzen du?",
      timing: "Nahiago duzun egutegia",
      targets: "Nahiago dituzun helburuak",
      limits: "Muga derrigorrezkoak",
      use: "Aurreikusitako erabilera",
      tradeoffs: "Onargarri diren trukeak",
      basis: "Neurketa-oinarria",
      players: "Jokalari kopurua",
      interests: "Interes-eremuak",
      territory: "Interesatzen zaizun lurraldea",
      channels: "Dauden kanalak eta esperientzia",
      audience: "Publikoa edo diziplina",
      proposal: "Proposatutako lankidetza",
      goal: "Garapen-helburua",
      ageBand: "Jokalariaren adin-tartea",
      scope: "Programaren irismena",
      interestArea: "Interes-eremua",
      productRef: "Produktu- edo serie-erreferentzia",
      requestType: "Eskaera-mota",
      seeking: "Zer bilatzen duzu",
      consent: "Onartzen dut MAXIMUS taldeak datu hauek gordetzea eta erabiltzea eskaera honi erantzuteko. Hau ez da marketin-harpidetza bat.",
    },
    roles: { player: "Jokalaria", parent: "Gurasoa edo tutorea", coach: "Entrenatzailea", club: "Kluba edo akademia", retailer: "Dendaria", distributor: "Banatzailea", brand: "Marka edo enbaxadorea", investor: "Inbertitzailea edo bazkide estrategikoa", institution: "Erakundea", other: "Bestelakoa" },
    interestOptions: { training: "Entrenamendu-sistemak", fitting: "Doikuntza", identity: "Identitate profesionala", programmes: "Baimendutako programak", brand: "Marka pertsonala", supply: "Ekipamendu-hornidura", team: "Taldeko ekipamendua", personalisation: "Pertsonalizazioa", development: "Garapen-programak", service: "Zerbitzua", network: "Sareko parte-hartzea" },
    ownerTypes: { setup: "Prestaketa eta konfigurazioa", service: "Zerbitzua", records: "Erregistroak eta ziurtagiriak", other: "Bestelakoa" },
    strategicAreas: { engineering: "Ingeniaritza-gaitasuna", configuration: "Konfigurazioaren sakontasuna", manufacturing: "Fabrikazio-eredua", routes: "Merkaturako bideak", ip: "Jabetza intelektuala eta zerbitzuak", expansion: "Hedapen-aukerak" },
    errors: {
      required: "Eremu hau beharrezkoa da.",
      too_long: "Sarrera hau luzeegia da.",
      too_short: "Sarrera hau laburregia da.",
      invalid_email: "Sartu baliozko posta-helbide bat, adibidez izena@adibidea.com.",
      invalid_choice: "Aukeratu aukeretako bat.",
      not_number: "Sartu zenbaki oso bat zifrak soilik erabiliz.",
      out_of_range: "Balio hau onartutako tartetik kanpo dago.",
      not_in_matrix: "Pisu hau ez dago hautatutako seriearen katalogoko matrizean.",
      decimal_not_supported: "Sartu zenbaki oso bat hamartarrik gabe.",
      too_many: "Ez hautatu hiru aukera baino gehiago.",
      consent_required: "Baimena beharrezkoa da MAXIMUS taldeak eskaera honi erantzun ahal izateko.",
      invalid: "Sarrera hau ez da baliozkoa.",
    },
  },
  legal: {
    title: "Identitate juridikoa eta kontrola",
    lead: "Marka publikoa MAXIMUS / MAXIMUS GPS da. Identitate juridiko operatiboak bereiz daitezke eta hemen adierazten dira.",
    entities: {
      institutional: { role: "Erakunde-programen geruza", p: "Erakunde-programen geruza eskaintzen du, programa batek rol hori ezartzen duenean. Ez da erraketen saltzaile komertziala. Dubai International Financial Centre gunean eratutako irabazi-asmorik gabeko erakundea da." },
      equipment: { role: "Ekipamenduaren entitate komertziala", p: "Ekipamenduaren entitate komertziala da horniduraren, banaketaren eta kontratatutako entrega komertzialaren arloan, indarrean dauden dokumentu operatiboek rol hori ezartzen dutenean. Edozein eragiketaren kontratu-aldea eragiketa horren dokumentuetan identifikatzen da." },
      ip: { role: "Jabetza intelektuala, marka eta koordinazio komertziala", p: "Jabetza intelektualaren, markaren edo koordinazio komertzialaren rol finkatu baterako agertzen da. Ez da berretsi gabeko kontratu-erantzukizunik esleitzen." },
      stewardship: { role: "Zaintzaren erreferentzia", p: "House of Maximus da ekosistemaren zaintza-erreferentzia, dagokion iturriak hala eusten duenean." },
      control: { role: "Barne jabetza intelektuala, jatorria eta dokumentu-kontrola", p: "MIPA da jabetza intelektualaren, jatorriaren eta dokumentu-kontrolaren barne-geruza. MIPAren barne-sarrera bat bereizia da kanpoko marka erregistratu, patente, egile-eskubideen erregistro edo aitorpen judizial batetik, eta ez da onarpen bisuala." },
    },
    labels: { licence: "Lizentzia", registration: "Erregistroa", vat: "VAT TRN", address: "Helbidea", email: "Email", jurisdiction: "Jurisdikzioa" },
    boundaryTitle: "Mugak",
    boundary: [
      "Erosketa batek ez du automatikoki erakunde-kidetza, gobernantza-eskubide, kanon edo inbertsio-eskubiderik ematen.",
      "Erakunde-rola bereizia da ekipamenduaren eragiketa komertzialetatik.",
      "Pribatutasuna, programen baldintzak eta sarbide kontrolatuaren akordioak benetan argitaratutako funtzioei dagozkie.",
      "Ez dago lege aplikagarriaren adierazpen orokorrik bisitari, salmenta edo atzerriko programa guztietarako; kontratu-oinarria akordio bakoitzean ezartzen da.",
    ],
  },
  privacy: {
    title: "Pribatutasuna",
    updated: "2026-09-21 bertsioa · webgunea 4.2",
    contactTitle: "Pribatutasunari buruzko galderetarako harremana",
    sections: {
      collect: ["Zer biltzen da", "Inprimaki bat bidaltzen duzunean: sartzen dituzun datuak (izena, posta, rola, herrialdea edo eskualdea, erakundea ematen baduzu, zure mezua eta inprimakiaren erantzunak), zure bisitaren orria eta kanpaina-parametroak (sarrera-orria, hizkuntza, utm parametroak; publizitate-klikaren identifikatzaileak analitika onartu baduzu soilik) eta bidalketaren ordua. Zure IP helbidea hash moduan eta bizitza laburrarekin soilik erabiltzen da gehiegikeriak mugatzeko, eta ez da zure eskaerarekin gordetzen."],
      purpose: ["Zergatik", "Zure eskaerari erantzuteko, eskatu duzun proposamena edo zehaztapena prestatzeko eta eskaeraren erregistroa gordetzeko. Inprimaki batean oinarrituta ez da marketin-mezurik bidaltzen."],
      storageOn: ["Non gordetzen dira eskaerak", "Eskaerak Upstash, Inc. (Redis) datu-base batean gordetzen dira, Vercel Inc. ostatu-plataformaren bidez eskainia."],
      notifyEmail: ["Eskaera berriaren jakinarazpena", "Eskaera bat onartzen denean, bidali dituzun datuak dituen jakinarazpen bat posta elektronikoz bidaltzen da MAXIMUS taldearen postontzi arduradunera."],
      notifyTelegram: ["Eskaera berriaren jakinarazpena", "Eskaera bat onartzen denean, bidali dituzun datuak dituen jakinarazpen bat MAXIMUS taldearen arduradunari bidaltzen zaio Telegram bidez (Telegram FZ-LLC, Dubai), eta, beraz, horrek jakinarazpen hori bidean tratatzen du."],
      notifyWebhook: ["Eskaera berriaren jakinarazpena", "Eskaera bat onartzen denean, bidali dituzun datuak dituen jakinarazpen bat MAXIMUS taldearen barne-helmuga batera bidaltzen da, sinatutako eta zifratutako konexio baten bidez."],
      notifyNone: ["Eskaera berriaren jakinarazpena", "Eskaera berrien jakinarazpena ezartzen ari da. Zure eskaera gorde egiten da eta MAXIMUS taldeak barne-erregistrotik irakurtzen du; xede horretarako ez da ezer hirugarren bati bidaltzen."],
      storageOff: ["Non gordetzen dira eskaerak", "Eskaeren biltegiratzea ezartzen ari da. Martxan egon arte, inprimakiek adierazten dute ezin dela eskaerarik onartu; ez da ezer gordetzen. Webgunea Vercel Inc. enpresak ostatatzen du."],
      browser: ["Nabigatzailearen biltegiratzea", "Saioko biltegiak GPSaren eta konfiguragailuaren aukera anizkoitzeko erantzunak eta zure bisitaren kanpaina-parametroak gordetzen ditu nabigatzailearen saio honetarako. Harremanetarako datuak, testu librea, grabatuaren testua eta haurrei buruzko informazioa ez dira nabigatzailean gordetzen."],
      analyticsOn: ["Analitika", "Zure baimenarekin, Google Analytics 4 tresnak bisitak eta inprimaki-gertaerak neurtzen ditu, harremanetarako daturik eta eskaeraren testurik gabe. Zure erabakia biltegi lokalean gordetzen da eta edonoiz alda daiteke orri-oinean «Analitikaren ezarpenak» atalean. Inprimakiak analitikarik gabe ere funtzionatzen dute."],
      analyticsOff: ["Analitika", "Webgune honetan ez dago analitika-tresnarik aktibo."],
      retention: ["Gordetzea", "Oraindik ez da ezabatze automatikoaren eperik ezarri. Edonoiz eska dezakezu zure eskaera ezabatzea."],
      children: ["Haurrak", "Inprimakiak heldu batek bete behar ditu. 18 urtetik beherako jokalariei buruzko eskaerak gurasoak edo tutoreak egiten ditu. Ez bidali haurraren izena, jaiotze-data, ikastetxea edo mediku-informazioa. Haurren profilak inoiz ez dira argitaratzen."],
      rights: ["Zure eskubideak", "Zure eskaera ikusteko, zuzentzeko edo ezabatzeko, idatzi gps@maximus.tennis helbidera eta adierazi eskaeraren identifikatzailea."],
      controlled: ["Informazio kontrolatua", "Dokumentu konfidentzialak ez dira webgune honetan gordetzen eta ez dira hemendik zerbitzatzen. Ezagutaraztea kontrolatua konfidentzialtasun-akordio edo kontratu baten barruan egiten da, bide bereizietatik."],
    },
  },
  terms: {
    title: "Erabilera-baldintzak",
    copyright: "Webgune honen egile-eskubideak — testuak, argazkiak, diseinua eta kodea — Maximus Kiriyakulov-enak dira soilik. Ez dira enpresa bati edo beste pertsona bati laga.",
    updated: "2026-09-21 bertsioa",
    sections: [
      ["Informazioa, ez eskaintza", "Webgune honetako produktu-informazioak onartutako zehaztapenak, konfigurazio-arkitektura eta programen azalpenak deskribatzen ditu. Ez da salmenta-eskaintza bat, ez prezio-zerrenda bat, ez izakinen adierazpen bat, ez entrega-konpromiso bat. Baldintza komertzialak bereiz eta idatziz adosten dira eragiketa bakoitzean identifikatutako kontratu-entitatearekin."],
      ["Eskaerak", "Webgune honetatik bidalitako eskaera bat — GPS profilak, konfigurazio-eskaerak eta txosten teknikoak barne — identifikatzaile batekin gordetzen da eta aztertzen da. Ez da onartutako eskari bat, ez fabrikazio-konpromiso bat, ez hitzordu berretsi bat, ez kidetza-eskaera bat, ez edozein programarako onartutako eskaera bat."],
      ["Zehaztapenak eta frogak", "Kalkulatutako balioak, fabrikazio-helburuak eta zehaztapen berretsiak bereizten dira dagozkien orrietan. Zurruntasun-balioak fabrikazio-helburuak dira, bestelakorik argitaratu arte. Ez da jokalari jakin batentzako emaitzarik bermatzen."],
      ["Ekosistema, kidetza eta eskubideak", "Erraketa bat erostea ez da erakunde-kidetza, ez inbertsio-eskubide, ez jabetza intelektualaren titulartasun, ez kanonetarako edo parte-hartze onuretarako eskubide. Eskubideak argitaratutako programa-baldintzen edo akordio idatzi baten araberakoak dira."],
      ["Jabetza intelektuala", "MAXIMUS®, lehoiaren ikurra, GPS marka eta webgune honen edukia babestuta daude. Barne ingeniaritza-formulak, kalitate-kontrolaren protokoloak, laminatuak, tresneria, hornitzaileen identitatea, kostu-kalkuluak eta babestutako metodologia ez dira hemen ezagutarazten."],
    ],
  },
  lead: {
    submit: "Bidali eskaera",
    submitting: "Bidaltzen…",
    retry: "Saiatu berriro",
    acceptedEyebrow: "Eskaera onartuta",
    acceptedTitle: "Zure eskaera jaso dugu.",
    requestId: "Eskaeraren identifikatzailea",
    acceptedNext: "MAXIMUS taldeak eskaera bakoitza aztertzen du eta idatziz erantzuten du eman duzun posta-helbidera. Gorde eskaeraren identifikatzailea edozein jarraipenerako.",
    duplicate: "Eskaera hau jadanik jasota zegoen; ez da bikoiztu bat sortu.",
    another: "Hasi eskaera berri bat",
    errorsTitle: "Egiaztatu eremu hauek:",
    failTitle: "Zure eskaera ez da bidali.",
    fail: {
      offline: "Zure gailua konexiorik gabe dago.",
      network: "Zerbitzariarekiko konexioak huts egin du.",
      timeout: "Zerbitzariak ez du garaiz erantzun.",
      rate_limited: "Sare honetatik eskaera gehiegi jaso dira. Saiatu berriro minutu batzuk barru.",
      too_fast: "Inprimakia oso azkar bidali da. Egiaztatu eta bidali berriro.",
      spam_suspected: "Spam-iragazkiak eskaera gelditu du.",
      unavailable: "Une honetan ezin da eskaerarik onartu.",
      default: "Ustekabeko errore bat gertatu da.",
    },
    keepNote: "Idatzi duzuna orri honetan gordeta dago, beraz, berriro saia zaitezke.",
    sendByEmail: "Bidali eskaera hau posta elektronikoz",
    sendByEmailNote: "Zure posta-aplikazioa eskaera honen testuarekin irekitzen da. MAXIMUS taldeak posta bidaltzen duzunean jasotzen du.",
    mailConfig: "Konfigurazioa",
    mailPage: "Orria",
    fallback: "Arazoak jarraitzen badu, idatzi hona: {email}. Eskaera bat bidalitzat hartzen da eskaeraren identifikatzailea erakusten denean soilik.",
    privacyLink: "Pribatutasun-oharra",
    hpLabel: "Utzi eremu hau hutsik",
    consentShort: "Baimena",
    after: "Bidali ondoren, eskaeraren identifikatzailea orri honetan erakusten da. Eskaerak aztertu eta idatziz erantzuten dira; eskaera bat ez da eskari bat.",
    basis: { unstrung: "Kordarik gabe", strung: "Kordatuta", unknown: "Ez dakit zehatz — zehaztapenean adostuko da" },
    hints: {
      email: "MAXIMUS taldeak helbide honetara erantzuten du idatziz.",
      goal: "Adibidez: lehiaketarako lehen erraketa, edo gazte-erraketa bat atzean uztea. Ez sartu haur baten izen, jaiotze-data edo mediku-informaziorik.",
      currentRacquet: "Marka eta modeloa, ezagutzen badituzu.",
      message: "Ez sartu pasahitz, ordainketa-datu edo mediku-informaziorik.",
    },
  },
  choose: {
    eyebrow: "Laguntza aukeratzeko",
    title: "Lagundu erraketa bat aukeratzen",
    lead: "Esan MAXIMUS taldeari zure maila eta zer zaizun garrantzitsuena. Zure erantzunak aztertzen dira eta proposamen bat jasotzen duzu idatziz: seriea, zehaztasun-klasea, pisua eta heldulekua.",
    stepsTitle: "Zer gertatzen da ondoren",
    steps: [
      ["Zure erantzunak", "Maila, lehentasunak eta helduleku-neurria, ezagutzen baduzu."],
      ["Adituen azterketa", "MAXIMUS taldeak zure erantzunak serieen matrizeekin alderatzen ditu."],
      ["Proposamen idatzia", "Proposatutako konfigurazio bat eta hurrengo urratsa, idatziz."],
    ],
    formTitle: "Zure erantzunak",
    submit: "Eskatu laguntza aukeratzeko",
    altTitle: "Nahiago duzu zuk zeuk erabakitzea?",
    altGps: "GPS profil zehatza",
    altBuild: "Konfiguratu zuzenean",
    note: "Doikuntza automatikorik gabe eta zehaztasun-baieztapenik gabe: pertsona batek eskaera bakoitza aztertzen du.",
  },
  consent: {
    title: "Analitika",
    text: "Baimena ematen diozu MAXIMUS webguneari bisitak Google Analytics bidez neurtzeko? Inprimakiak bi kasuetan funtzionatzen dute; ez da harremanetarako daturik edo eskaeraren testurik analitikara bidaltzen.",
    allow: "Baimendu analitika",
    decline: "Ez baimendu",
  },
  familyPlan: {
    title: "Familiako Tenis Plana",
    metaDescription: "Kalkulatu zure familiaren tenis-aurrekontua: saioak, orduak, pilota-kontaktuak eta saio baten, ordu baten eta kolpe baten kostua — zeure zenbakiekin, hiru agertokitan.",
    eyebrow: "Familiako Tenis Plana · Egin ekarpena gurekin",
    heroTitle: "Zenbat kostatzen zaio tenisa zure familiari — eta zer lortzen du horren truke?",
    heroLead: "Kalkulatu zure familiaren aurrekontua, harekin ordaintzen diren saioak eta orduak, pilota-kontaktu estimatuak eta saio baten, ordu baten eta kolpe baten kostua — zeure baldintzetan.",
    heroCta: "Kalkulatu zure familiako tenis-plana",
    strategy: {
      eyebrow: "Gure helburua",
      title: "Tenis gehiago. Aukera gehiago. Elkarrekin.",
      p1: "Gure helburua munduko tenis-merkatua hamar aldiz handitzea da, parte-hartzea zabalduz eta tenisera iristeko bidea argiago eta eskuragarriago eginez. MAXIMUS markak bide horretan gidari izan nahi du kudeaketaren, metodologiaren, kalitatearen, emaitzen eta jokoaren zabalkundearen bidez.",
      p2: "Tenis-ekipamenduaren beste fabrikatzaileak eta haien markak balizko bazkidetzat hartzen ditugu. Enpresen, entrenatzaileen, kluben eta familien indarrak programa partekatu batean batzea proposatzen dugu, tenisa garatzeko, sustatzeko eta eskala handiagora eramateko, elkarren onurarako.",
      p3: "MAXIMUS da ikuspegi honen bosgarren elementua: indar bereiziei elkarrekin lan egiten laguntzen dien rol bateratzailea. Gure erronka partekatuak gaixotasuna, haurren sedentarismoa eta jendeari jokatzen hastea eta jarraitzea eragozten dioten oztopoak dira.",
      p4: "Familia batentzat, dena argitasunarekin hasten da. Familiako Tenis Planak aurrekontua, saio- eta ordu-kopurua, pilota-kontaktuen bolumen estimatua eta entrenamenduaren kostua erakusten ditu. Aldatu baldintzak eta aukeratu hobekien datorkizun agertokia.",
      note: "Hamar aldiz haztea MAXIMUS markaren helburu estrategikoa da, ez jada lortutako emaitza bat. Kalkulagailuak agertokien araberako kalkuluak erakusten ditu, eta ez du agintzen ez aurrezpenik, ez efektu medikorik, ez kirol-emaitzarik.",
      ctaCalc: "Kalkulatu zure familiako tenis-plana",
      ctaPartner: "Hitz egin dezagun tenisa elkarrekin garatzeaz",
    },
    beyond: {
      eyebrow: "Pistatik haratago",
      title: "Entrenamenduaz gain, planak eraikitzen duena",
      admission: {
        h: "Ikastetxe eta unibertsitate entzutetsuetan sartzea",
        p: "MAXIMUS taldeak familiari laguntzen dio mundu osoko ikastetxe eta unibertsitate entzutetsuetan sartzeko bidean: jokalariaren kirol-ibilbidea eraikitzen, dokumentuak eta eskabideak prestatzen, eta kirola eta ikasketak uztartzen dituzten programak aukeratzen. Kirol-beka bat ematen denean, familiak hezkuntzagatik ordaintzen duena murrizten du.",
      },
      assets: {
        h: "Aktibo digitalak: jokalariaren izena, irudia eta ibilbidea",
        p: "Jokalari baten izena, irudia, emaitzak, edukiak eta marka pertsonala aktiboak dira, eta, denborarekin, balio ekonomiko eta ospe-balio handia sor dezakete. MAXIMUS taldeak horiek sortzen, erregistratzen eta babesten laguntzen du, balio hori jokalariarekin eta familiarekin gera dadin.",
      },
      note: "Bietako bat ere ez da kalkulagailuaren parte. Ikastetxeko plaza baten, beka baten edo aktibo digital baten balioa kasu bakoitzaren araberakoa da, eta ez da hemen estimatzen.",
      cta: "Galdetu ikastetxeetan sartzeko laguntzaz eta aktibo digitalez",
    },
    steps: ["Familiaren datuak", "Saioen kostua", "Epe luzeko plana", "Azken kalkulua"],
    stepsLabel: "Kalkulagailuaren urratsak",
    scenarios: { now: "Egungoa", planned: "Aurreikusia", wish: "Desiratua" },
    scenarioHints: { now: "Zure familiak gaur egiten duena.", planned: "Hemendik aurrera egiteko asmoa duzuna.", wish: "Egin nahiko zenukeena." },
    currency: {
      label: "Moneta",
      note: "Sartzen dituzun zenbateko guztiak moneta honetan daude. Ez da ezer bihurtzen.",
    },
    fields: {
      players: { label: "Jokatzen duten familiakideak", hint: "Zenbaki osoa." },
      cost: { label: "Saio baten prezioa jokalari batentzat", hint: "Zenbateko osoa, zergak eta tasak barne." },
      sessions: { label: "Saioak jokalari bakoitzeko hilean", hint: "Zenbaki osoa." },
      minutes: { label: "Saio baten iraupena, minututan", hint: "Denbora osoa, atsedenaldiak barne. Hamartarrak onartzen dira." },
      contacts: { label: "Pilota-kontaktuak jokalari eta saio bakoitzeko", hint: "Kontaktu bat jokalariaren beraren erraketak pilota ukitzen duen aldi bakoitza da. Pilota-truke bat ez da kontaktu bat. Zenbatu modu berean agertoki guztietan." },
    },
    presetsLabel: "Aukera azkarra, minututan",
    ages: {
      title: "Planaren iraupena",
      start: "Hasierako adina",
      end: "Amaierako adina",
      hint: "Planak zenbat irauten duen adierazteko hipotesi anonimoa, epe luzeko taularako soilik erabiltzen dena. Ez da jaiotze-data bat, ezta gomendatutako hasiera-adin bat ere.",
    },
    extras: {
      title: "Familiaren kostu gehigarriak",
      note: "Zenbateko hauek familia osoarentzat dira eta hiru agertokiei aplikatzen zaizkie. Ez dira jokalari kopuruarekin biderkatzen, eta ez dira ordu baten edo kontaktu baten kostuan sartzen.",
      equipment: "Lehen ekipamendua — zenbateko bakarra aldirako",
      clothing: "Arropa eta oinetakoak — zenbateko bakarra aldirako",
      renewal: "Ekipamendua berritzea — zenbateko bakarra aldirako, ez da automatikoki errepikatzen",
      court: "Pista edo kluba — hilean, familia osoa",
      travel: "Bidaiak eta ekitaldiak — hilean, familia osoa",
      quoteSource: "Prezioen jatorria (aukerakoa)",
      quoteDate: "Prezioen data (aukerakoa)",
      quoteNote: "Idatzi duzun bezalaxe erakusten da. MAXIMUS taldeak ez ditu prezio hauek egiaztatzen.",
    },
    storage: {
      save: "Gorde plana gailu honetan",
      clear: "Ezabatu plana gailu honetatik",
      saved: "Plana gailu honetan gorde da. Ez da ezer inora bidali.",
      cleared: "Plana ezabatu da. Kalkulagailuak hasierako balioak ditu berriro.",
      restored: "Gailu honetan gordetako zure plana leheneratu da.",
      invalid: "Gailu honetan gordetako plan bat ezin izan da irakurri, eta ez da aplikatu. Kalkulu berri bat has dezakezu.",
      unavailable: "Nabigatzaile honek ez du uzten gailuan gordetzen.",
    },
    annual: {
      title: "Urtebete, elkarren ondoan",
      sessions: "Jokalari-saioak urtean",
      cost: "Familiaren gastua saioetan, urtean",
      hours: "Jokalari-orduak urtean",
      length: "Saio baten iraupena",
      contacts: "Pilota-kontaktuak urtean",
      note: "Jokalari-saioek eta jokalari-orduek jokalari bakoitzaren saioak batzen dituzte. Ez dira pista alokatzeko orduak, ezta talde-saioak ere: elkarrekin 90 minutuz entrenatzen diren bi jokalari 2 jokalari-saio eta 3 jokalari-ordu dira.",
    },
    economics: {
      title: "Saio baten, ordu baten eta kontaktu baten kostua",
      session: "Jokalari baten saio bat",
      hour: "Jokalari baten entrenamendu-ordu bat",
      contact: "Pilota-kontaktu bat",
      undefinedContacts: "Zehaztu gabe: 0 kontaktu",
      undefinedMinutes: "Zehaztu gabe: 0 minutu",
      below: "{value} baino gutxiago",
      note: "Zifra hauetan saioaren prezioa soilik sartzen da. Familiaren kostu gehigarriak ez dira kontaktuen artean banatzen.",
      caption: "Kontaktu kopurua aukeratutako saio-bolumenetik eta ereduaren hipotesietatik kalkulatzen da. Benetako entrenamendua formatuaren, atsedenaldien eta entrenamendu-baldintzen araberakoa da. Kontaktu baten kostua aurrekontu-neurri bat da, ez entrenamenduaren kalitatearen neurri bat.",
    },
    longTerm: {
      title: "Epe luzeko gastu-plana",
      horizon: "Horizontea",
      activeYears: "Urte aktiboak",
      years: "{n} urte",
      note: "Urte aktiboak bi adinen arteko aldeak mugatzen ditu. Prezioak, maiztasuna, inflazioa, denboraldiak, galdutako saioak eta truke-tasak konstante mantentzen dira. Kostu gehigarriak ez daude taula honetan.",
    },
    final: {
      title: "Azken kalkulua",
      scenario: "Agertokia",
      months: "Aldia, hilabetetan",
      heading: "{scenario} · {months} hilabete",
      total: "Aldiko guztizkoa",
      training: "Saioak",
      extras: "Kostu gehigarriak",
      oneOff: "Behin bakarreko kostuak",
      monthly: "Hileko kostuak × hilabeteak",
      sessions: "Jokalari-saioak aldian",
      hours: "Jokalari-orduak aldian",
      contacts: "Pilota-kontaktuak aldian",
      formulaTitle: "Nola kalkulatzen den",
      formula: "Guztira = jokalariak × saioak hilean × hilabeteak × saioaren prezioa + behin bakarreko kostuak + hilabeteak × hileko kostu gehigarriak.",
      formulaNote: "Kostu gehigarriak familia osoarentzat sartzen dira. Behin bakarreko kostuak behin bakarrik zenbatzen dira, baita 0 hilabeteko aldi baterako ere.",
      inputs: "Zure datuak",
    },
    units: { min: "min", h: "h", approx: "≈" },
    errors: {
      title: "Zuzendu eremu hauek emaitza ikusteko",
      required: "Beharrezkoa — sartu zenbaki bat; 0 onartzen da.",
      negative: "Ezin da negatiboa izan.",
      integer: "Zenbaki osoak soilik.",
      number: "Sartu zenbaki bat.",
      tooLarge: "Zenbaki hau handiegia da kalkulatzeko.",
      endBeforeStart: "Amaierako adina ezin da hasierako adina baino txikiagoa izan.",
      tooLong: "Gehienez 200 karaktere.",
      date: "Sartu baliozko data bat.",
      currency: "Aukeratu moneta bat.",
      scenario: "Aukeratu agertoki bat.",
      result: "Emaitza handiegia da modu fidagarrian erakusteko. Murriztu sartutako balioak.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: konposizio osoa — entrenagailua aurretik eta saihetsetik ikusita, lehoiaren domina grabatua kontaktu-buru biribilean, MAXIMUS eta SPOT TRAINER grabatuak lepoan zehar, eta lehoiaren marka daraman oinarri-tapa oktogonala",
    greatHero: "MAXIMUS GREAT seriea, 363 g: konposizio osoa buruko xehetasun gorri eta horiekin, MAXIMUS letra distiratsuekin, Maximus-en autografoarekin lepoan eta kirtenean lehoiaren ikurrarekin",
    spotDetail: "Bi MAXIMUS Spot Trainer hurbilagotik ikusita: lehoia grabatua kontaktu-buru beltz matean, helduleku-zinta ildaskatua eta lehoiaren marka duten oinarri-tapa oktogonalak",
    spotPair: "Bi MAXIMUS Spot Trainer angeluan jarrita gainazal ilun batean, MAXIMUS lepo batean grabatua eta SPOT TRAINER bestean, lehoiaren domina kontaktu-buru bakoitzean",
    spinVisual: "MAXIMUS SPIN: burua kordekin, MAXIMUS letra distiratsuak, heldulekua eta lehoiaren oinarri-tapa",
    powerVisual: "MAXIMUS POWER: burua kordekin, MAXIMUS letra distiratsuak, pertsonalizazio-grabatua, heldulekua eta lehoiaren oinarri-tapa",
    greatVisual: "MAXIMUS GREAT: burua kordekin, MAXIMUS letra distiratsuak, pertsonalizazio-grabatua, heldulekua, lehoiaren oinarri-tapa eta G seriearen marka lepoan",
    spinHead: "MAXIMUS SPIN burua eta korda-sareta",
    handleLion: "MAXIMUS lepoa, heldulekua eta oinarri-tapa lehoiaren markarekin",
    engraving: "Zilarrezko pertsonalizazio-grabatua lepoan",
    lettering: "MAXIMUS letra beltz distiratsuak marko beltz matean",
    variantAlt: "MAXIMUS {series} seriea — {w} g, {b} mm-ko balantzea: bistaratze osoa zehaztapen-zerrendarekin, pertsonalizazio-grabatuaren eremuarekin eta MIPA markarekin",
    sstSystem: "MAXIMUS Sweet Spot Trainer, lau erraketako sistema",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Sweet Spot Trainer lepoak MAXIMUS letrekin",
    sstGrips: "Sweet Spot Trainer heldulekuak eta oinarri-tapak",
    sstButtcaps: "Sweet Spot Trainer, lau oinarri-tapa lehoiaren markarekin",
    note: "Produktuaren irudia",
  },
  notFound: { title: "Orria ez da aurkitu", p: "Eskatu duzun orria ez dago hizkuntza honetan.", cta: "Joan hasiera-orrira" },
};

export default eu;
