/* French dictionary — MAXIMUS website v4.0. Translated from content/en.js; numerical product data lives in data/products.js. */
const fr = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — raquettes de tennis tout carbone conçues sur spécification",
    defaultDescription:
      "Raquettes de tennis tout carbone, du cadre au manche : GREAT 97 in², POWER 98 in² et SPIN 100 in², huit tailles de manche d'usine L0–L7, classes de précision pour le poids, l'équilibre, l'inertie de swing et la rigidité, et ingénierie sur mesure sur demande.",
  },
  common: {
    statuses: {
      current: "Actuel",
      agreement: "Disponible sur accord",
      development: "En développement",
      concept: "Au stade de concept",
      target: "Cible de fabrication",
      modelled: "Calculé",
      confirmed: "Confirmé",
      requested: "Architecture demandée",
      notprovided: "Non fourni",
    },
    brief: { who: "À qui cela s'adresse", value: "Ce que vous obtenez", now: "Confirmé à ce jour", next: "Étape suivante" },
    labels: {
      next: "Suivant",
      back: "Retour",
      edit: "Modifier les réponses",
      review: "Vérifier",
      start: "Commencer",
      restart: "Recommencer",
      copy: "Copier le texte de la demande",
      copied: "Copié",
      openEmail: "Ouvrir un e-mail pour envoyer cette demande",
      reference: "Référence de la demande",
      weight: "Poids",
      balance: "Équilibre",
      swingweight: "Inertie de swing",
      stiffness: "Rigidité",
      grip: "Taille de manche",
      headSize: "Taille de tamis",
      series: "Série",
      precisionClass: "Classe de précision",
      quantity: "Quantité",
      notProvided: "Pas encore publié",
      requestTarget: "Cible demandée",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Lire la suite",
      allSeries: "Toutes les séries",
      points: "poids répertoriés",
      optional: "facultatif",
      required: "obligatoire",
      select: "Sélectionner",
      yes: "Oui",
      no: "Non",
      unknown: "Je ne sais pas",
      custom: "Cible personnalisée",
      listed: "Poids répertorié",
      individual: "Raquette individuelle",
      pair: "Paire appariée",
      triple: "Triplette appariée",
      team: "Lot d'équipe",
      summaryTitle: "Récapitulatif de votre demande",
      nextAction: "Action suivante",
      status: "Statut",
      learn: "En savoir plus",
      schematic: "Schéma — pas une mesure",
      photo: "Photographie",
    },
    ecosystemStrip: "L'écosystème MAXIMUS",
    truth: {
      noPrices: "Les prix, les quantités minimales, les délais, les garanties et les engagements de livraison sont confirmés par écrit, par marché et par programme.",
      requestNotOrder: "Une demande est une demande d'examen. Ce n'est pas une commande acceptée, un engagement de fabrication ni un rendez-vous confirmé.",
      noGuarantee: "Aucun résultat pour un joueur donné n'est garanti par un équipement, une méthode ou un programme décrit ici.",
    },
  },
  nav: {
    language: "Langue",
    groups: { racquets: "Raquettes", training: "Entraînement", ecosystem: "Écosystème", partnerships: "Partenariats" },
    racquets: "Séries de raquettes et comparaison",
    great: "GREAT — 97 in² · Contrôle",
    power: "POWER — 98 in² · Puissance",
    spin: "SPIN — 100 in² · Effet",
    precision: "Précision et rigidité",
    grip: "Architecture de manche d'usine L0–L7",
    custom: "Ingénierie sur mesure",
    training: "Systèmes d'entraînement",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Méthodologie",
    gps: "MAXIMUS GPS",
    build: "Configurez la vôtre",
    choose: "Aidez-moi à choisir",
    ecosystem: "Carte de l'écosystème",
    engineering: "Ingénierie et fabrication",
    experience: "Essais et ajustement",
    brands: "Marques personnelles et ambassadeurs",
    families: "Familles et parents",
    owners: "Propriétaires et coffre-fort du propriétaire",
    network: "Sports Network",
    partnerships: "Toutes les voies de partenariat",
    coaches: "Entraîneurs",
    clubs: "Clubs et académies",
    distribution: "Distribution et développement de pays",
    strategic: "Stratégie et investissement",
    institutional: "Programmes institutionnels",
    contact: "Nous contacter",
    legal: "Identité juridique",
    privacy: "Confidentialité",
    terms: "Conditions",
    menu: "Menu",
    close: "Fermer",
    home: "Accueil",
    skip: "Aller au contenu",
  },
  footer: {
    line: "La raquette MAXIMUS est votre clé du monde MAXIMUS.",
    product: "Produit",
    ecosystem: "Écosystème",
    company: "Organisation",
    instagram: "Instagram",
    email: "Email",
    analytics: "Paramètres d'analyse",
    rights: "MAXIMUS® et l'emblème au lion sont des marques de l'écosystème MAXIMUS. MIPA : propriété intellectuelle interne, provenance et contrôle documentaire.",
    boundary:
      "Les conditions commerciales et contractuelles sont convenues séparément par écrit. L'achat d'une raquette ne crée ni adhésion institutionnelle, ni droits d'investissement, ni propriété de droits intellectuels, ni droit à des redevances.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "La précision commence au point de contact.",
    heroProduct: "Le Sweet Spot Trainer, le Spot Trainer et la méthodologie MAXIMUS relient un entraînement ciblé aux raquettes de performance tout carbone.",
    heroCta1: "Découvrir le système d'entraînement",
    heroCta2: "Découvrir GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Contrôle",
    heroMeta: [
      ["Tout carbone", "du cadre au manche"],
      ["4 paramètres", "poids · équilibre · inertie de swing · rigidité"],
      ["8 tailles de manche", "géométrie d'usine L0–L7"],
      ["3 séries", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Commencez ici",
      title: "Choisissez votre parcours",
      items: {
        player: { h: "Joueur", p: "Trouvez une raquette selon votre niveau et vos priorités, ou configurez-la directement.", a: "Trouver votre raquette" },
        parent: { h: "Parents", p: "Un parcours écrit pour les objectifs de développement, l'implication de l'entraîneur et l'équipement adapté.", a: "Parcours famille" },
        coach: { h: "Entraîneur, club ou académie", p: "Systèmes d'entraînement, ajustement, lots d'équipe et personnalisation.", a: "Parcours entraîneurs et clubs" },
        partner: { h: "Distributeur ou partenaire", p: "Distribution, développement de pays, voies stratégiques et institutionnelles.", a: "Voies de partenariat" },
      },
    },
    series: {
      eyebrow: "Séries de performance",
      title: "Trois architectures de performance. Une seule plateforme d'ingénierie.",
      lead: "Choisissez la série selon la direction de jeu, puis complétez la configuration : classe de précision, poids, taille de manche, personnalisation.",
      cta: "Comparer les séries",
      configure: "Configurer",
      open: "Ouvrir la série",
      photoPending: "Photographie pas encore publiée",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Système de précision MAXIMUS",
      title: "Poids. Équilibre. Inertie de swing. Rigidité.",
      sub: "Contrôlés comme un seul système d'ingénierie.",
      lead: "Trois classes de précision définissent avec quelle rigueur chaque raquette finie est tenue à sa spécification déclarée. P0.5 est une tolérance serrée sous un protocole de mesure défini — pas une erreur nulle.",
      cta: "La précision et la rigidité en détail",
    },
    stiffness: {
      eyebrow: "Rigidité",
      title: "Une réponse de cadre reproductible face à une cible déclarée.",
      p: "La rigidité du cadre façonne la réponse, le ressenti et la constance entre les raquettes. MAXIMUS la traite comme le quatrième paramètre contrôlé : la cible, le résultat mesuré, la tolérance admise et la capabilité de l'instrument sont conservés comme des enregistrements distincts. Le bénéfice est la répétabilité — pas un résultat garanti pour chaque joueur.",
      cols: [["Réponse", "Comment le cadre restitue l'énergie au contact."], ["Ressenti", "Ce que le joueur perçoit au contact."], ["Constance", "Des raquettes construites selon la même spécification répondent de la même manière, dans les limites de leur classe."]],
      schematicCaption: "Schéma : écart admis autour d'une cible de rigidité déclarée, pour chaque classe. Pas une mesure ; aucune valeur RA n'est sous-entendue.",
      bands: { p25: "tolérance cible ±1 RA", p15: "tolérance cible ±0.5 RA", p05: "conforme au RA cible déclaré sous le protocole de mesure établi en usine — pas une erreur nulle", target: "cible déclarée (aucune valeur sous-entendue)" },
    },
    carbon: {
      eyebrow: "Standard de construction",
      title: "Tout carbone. Du cadre au manche.",
      p: "Toutes les raquettes MAXIMUS actuelles de cette plateforme sont tout carbone dans leur structure, manche inclus. Aucune mousse n'est utilisée pour former le manche.",
      gripTitle: "Huit tailles de manche d'usine. L0–L7.",
      gripP: "Chaque taille est une géométrie de manche carbone d'usine — pas une surépaisseur de surgrip.",
      scaleCaption: "Schéma : désignations nominales de manche L0–L7 (4″ à 4⅞″). Pas des dimensions de manche mesurées.",
      cta: "Architecture de manche d'usine",
    },
    custom: {
      eyebrow: "Ingénierie sur mesure",
      title: "Conçue sur spécification.",
      sub: "La gamme standard est le point de départ.",
      p: "MAXIMUS accepte des exigences techniques au-delà des matrices publiées, pour évaluation, ingénierie, validation et fabrication selon une spécification convenue. La faisabilité est confirmée par écrit.",
      chain: ["Définir", "Concevoir", "Valider", "Spécifier", "Produire", "Mesurer / enregistrer"],
      cta: "Soumettre un cahier des charges technique",
      cta2: "Discuter d'une ingénierie sur mesure",
    },
    training: {
      eyebrow: "Systèmes d'entraînement",
      title: "Un système d'entraînement construit autour du contact.",
      p: "Le Sweet Spot Trainer, la méthodologie MAXIMUS et le Spot Trainer relient l'équipement à la pratique dirigée par l'entraîneur : contact centré, contrôle, charge progressive et retour vers la raquette de performance.",
      cta: "Systèmes d'entraînement",
      cta2: "Demander une démonstration",
      photoPending: "Photographie du trainer pas encore publiée",
      sstP: "Un tamis d'entraînement de 50 in² pour le travail du contact centré, avec quatre configurations de poids pour une charge choisie par l'entraîneur.",
      sstCta: "Découvrir le Sweet Spot Trainer",
      sstCaption: "Configuration 300 g, l'une des quatre",
      methodP: "Fixer les objectifs, choisir l'équipement, s'entraîner avec l'entraîneur, consigner les observations, réévaluer, ajuster et transférer le travail vers le jeu de performance.",
      methodCta: "Découvrir la méthodologie",
      spotP: "Une petite cible ronde pour travailler un point de contact précis et reproductible.",
      spotCta: "Découvrir le Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Fabrication et contrôle qualité",
      title: "Construit selon une spécification. Mesuré et enregistré.",
      p: "La production suit la spécification écrite de chaque commande. Les enregistrements suivent la classe de précision : enregistrements de production conservés pour P2.5, enregistrements individuels et traçabilité pour P1.5, contrôle individuel et documentation pour P0.5 lorsque le programme de la commande les met en œuvre.",
      confirmedTitle: "Confirmé",
      confirmed: ["Construction tout carbone, du cadre au manche.", "Classes de précision P2.5, P1.5 et P0.5 avec quatre paramètres contrôlés.", "Huit tailles de manche d'usine L0–L7."],
      pendingTitle: "Pas encore publié",
      pending: "Les photographies des équipements de mesure, les exemples d'enregistrements de contrôle qualité et les images d'usine ne sont pas encore publiés. Rien sur cette page n'est un certificat de mesure.",
      captions: { lettering: "Lettrage MAXIMUS brillant sur le cadre mat", buttcap: "Grip et capuchon de manche avec la marque au lion", handle: "Gravure de personnalisation argentée", finish: "Tamis et plan de cordage" },
      cta: "Ingénierie et fabrication",
    },
    world: {
      eyebrow: "Le monde MAXIMUS",
      title: "Une clé. Un écosystème. Des opportunités illimitées.",
      note: "« Opportunités illimitées » est une expression de marque, non une promesse de faisabilité technique, de revenus ou d'accès illimités. Un achat ne crée ni redevances, ni rendement d'investissement, ni parrainage, ni financement du développement d'un joueur.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — et votre navigation dans le monde du tennis : un profil d'équipement guidé, auquel il est répondu par écrit." },
        personal: { h: "Personnalisation", p: "Noms, initiales, numéros et identification d'équipe, dans le traitement de gravure argentée approuvé." },
        development: { h: "Développement", p: "Systèmes d'entraînement dirigés par l'entraîneur, enregistrements et réévaluation." },
        ecosystem: { h: "Écosystème étendu", p: "Marques personnelles, enregistrements des propriétaires, réseau, licences et programmes institutionnels — chacun présenté avec son statut réel." },
      },
      cta: "Découvrir l'écosystème",
    },
    partners: {
      eyebrow: "Voies de partenariat",
      title: "Entraîneurs, clubs, distributeurs et partenaires.",
      p: "La qualification écrite d'abord. Les droits de pays, l'exclusivité et les conditions commerciales sont négociés par écrit — jamais accordés au moyen d'un formulaire.",
      cta: "Toutes les voies de partenariat",
      formTitle: "Demande courte",
      formLead: "Choisissez l'objet et écrivez à MAXIMUS. Vous recevez un identifiant de demande sur cette page.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "VOTRE NAVIGATION DANS LE MONDE DU TENNIS" } },
    personal: { eyebrow: "Personnalisation", title: "Votre nom. Votre numéro. Votre MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Trois séries. Des paramètres réels." },
    map: { cta: "Découvrir l'écosystème" },
  },
  racquets: {
    title: "Raquettes",
    lead: "Trois séries de performance partageant un standard de construction, un système de précision et une architecture de manche d'usine communs. Chaque série est une architecture de performance établie au sein d'une plateforme d'ingénierie plus large.",
    direction: { control: "Contrôle", power: "Puissance", spin: "Effet" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Direction de jeu principale",
    compareTitle: "Comparaison des séries",
    compareLead: "Uniquement des données d'architecture confirmées. Les plans de cordage, les longueurs, les profils de cadre, les plages de tension et les valeurs nominales d'inertie de swing et de rigidité de ces séries ne sont pas publiés ; ils sont recueillis comme cibles demandées pour examen technique.",
    columns: { series: "Série", head: "Taille de tamis", direction: "Direction de jeu", weights: "Poids répertoriés", range: "Plage de poids", balance: "Données d'équilibre" },
    balanceModelled: "Valeurs calculées",
    balanceNotProvided: "Pas encore publié",
    construction: "Construction : tout carbone, du cadre au manche · Précision : P2.5 / P1.5 / P0.5 · Manches : L0–L7",
    otherTitle: "Autres sports de raquette",
    otherLead: "Directions de développement approuvées. Aucun produit vendable n'existe dans ces catégories et aucune spécification tennis ne leur est transférée.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Beach-tennis" },
    ctaConfigure: "Configurer une demande",
    ctaSeries: "Ouvrir la série",
  },
  seriesPage: {
    eyebrow: "Séries de performance",
    intro: {
      great: "L'architecture GREAT de 97 in² est construite autour du contrôle : un tamis compact, un contact précis et une confiance directionnelle.",
      power: "L'architecture POWER de 98 in² est construite autour du transfert d'énergie : longueur de balle et vitesse depuis un cadre stable.",
      spin: "L'architecture SPIN de 100 in² est construite autour du comportement de la balle : rotation, marge et construction de la trajectoire.",
    },
    photoPending: "Photographie de la série pas encore publiée",
    detailPending: "Les photographies de détail de la construction et du manche de cette série ne sont pas encore publiées.",
    specsTitle: "Spécification et statut",
    catalogue: {
      eyebrow: "Catalogue de la série {series}",
      title: "{n} variantes de poids",
      lead: "Toutes les variantes de la série {series}, triées par poids. Poids en grammes, équilibre en millimètres depuis le talon. Chaque visualisation est montrée entière : rien n'est recadré, masqué ni étiré.",
      selectLabel: "Choisir une variante de poids",
      select: "Afficher cette variante",
      selected: "Affichée ci-dessus",
      balanceLabel: "Équilibre",
      headLabel: "Taille de tamis",
      constructionLabel: "Construction",
      gripsLabel: "Tailles de manche d'usine",
      precisionLabel: "Classes de précision",
      balanceConfirmed: "L'équilibre est la valeur confirmée pour ce poids et correspond au chiffre imprimé sur la visualisation. Les prix, les stocks et les délais de livraison ne sont pas publiés ici.",
      balanceModelled: "L'équilibre est une valeur calculée pour ce poids répertorié, non une mesure d'usine individuelle ; elle correspond au chiffre imprimé sur la visualisation. Les prix, les stocks et les délais de livraison ne sont pas publiés ici.",
      zoom: "Ouvrir l'image",
      close: "Fermer",
      allTitle: "Les {n} variantes",
    },
    specs: { head: "Taille de tamis", direction: "Direction principale", weights: "Poids répertoriés", range: "Plage de poids", balance: "Équilibre", construction: "Construction", grips: "Manches d'usine", precision: "Classes de précision" },
    construction: "Tout carbone, du cadre au manche",
    statusTitle: "Statut des valeurs",
    matrixTitle: "Matrice complète des poids",
    matrixLead: "Les poids répertoriés constituent la sélection standard. D'autres poids peuvent être demandés comme cibles personnalisées ; aucune valeur intermédiaire manquante n'est insérée.",
    balanceNote: {
      confirmed: "Les valeurs d'équilibre sont confirmées pour chaque poids répertorié (mm depuis le talon) et correspondent au chiffre imprimé sur la visualisation de ce poids. Elles ne sont pas calculées ici et ne sont pas lissées entre poids voisins ; la base de mesure est confirmée dans la spécification écrite.",
      modelled: "Les valeurs d'équilibre sont calculées pour chaque poids répertorié (mm depuis le talon). Ce ne sont pas des mesures d'usine individuelles ; la base de mesure est confirmée dans la spécification écrite.",
      notprovided: "Les valeurs d'équilibre de cette série ne sont pas fournies. Ne les déduisez pas d'une autre série.",
    },
    optionsTitle: "Précision, manche et poids",
    notPublished: "Non publié pour cette série : plan de cordage, longueur, profil de cadre, plage de tension, valeurs d'inertie de swing et de rigidité. Vous pouvez les indiquer comme cibles demandées pour examen technique.",
    offerTitle: "Ce qui se passe après votre demande",
    offerSteps: [
      ["Demande", "Envoyez une configuration ou une question. Un identifiant de demande s'affiche immédiatement."],
      ["Examen", "MAXIMUS examine la série, la classe, le poids, la taille de manche et les cibles demandées."],
      ["Réponse écrite", "La spécification, la disponibilité et les conditions commerciales sont confirmées par écrit."],
    ],
    faqTitle: "Questions fréquentes",
    faq: [
      ["Les valeurs d'équilibre sont-elles mesurées ?", "Elles sont calculées pour les poids répertoriés ; ce ne sont pas des mesures individuelles. La base de mesure est confirmée dans la spécification écrite."],
      ["Puis-je demander un poids qui n'est pas répertorié ?", "Oui, comme cible personnalisée en grammes entiers. Elle est examinée techniquement et la faisabilité est confirmée par écrit."],
      ["Qu'est-ce que la classe de précision change ?", "La rigueur avec laquelle le poids, l'équilibre, l'inertie de swing et la rigidité sont tenus à la spécification déclarée, et les enregistrements qui sont conservés."],
      ["Le manche est-il épaissi avec des surgrips ?", "Non. L0–L7 sont des géométries de manche carbone d'usine."],
      ["Où sont les prix et les délais de livraison ?", "Ils sont confirmés par écrit pour chaque demande et ne sont pas publiés ici."],
    ],
    faqSpinBalance: ["D'où viennent les valeurs d'équilibre de SPIN ?", "Du tableau confirmé de la série Spin : 33 variantes de poids avec l'équilibre en millimètres depuis le talon. Chaque paire correspond au chiffre imprimé sur la visualisation approuvée de ce poids. Les valeurs ne sont pas calculées et ne sont pas lissées entre poids voisins."],
    ctaBuild: "Configurer cette série",
    ctaAsk: "Poser une question sur cette série",
    ctaCompare: "Comparer toutes les séries",
    weightsLabel: "poids répertoriés",
    headLabel: "tamis",
  },
  precision: {
    title: "Précision et rigidité",
    switch: { label: "Choisir une classe de précision", panelLabel: "Quatre paramètres contrôlés —", qcLabel: "Architecture de contrôle qualité", protocolNote: "sous le protocole de mesure qualité défini en usine", fullTable: "Tableau comparatif complet" },
    lead: "Quatre paramètres contrôlés comme un seul système d'ingénierie. Chaque classe définit avec quelle rigueur une raquette finie est tenue à sa spécification déclarée et quels enregistrements qualité sont produits.",
    statement: "Poids. Équilibre. Inertie de swing. Rigidité. Contrôlés comme un seul système d'ingénierie.",
    classes: {
      "P2.5": { name: "Socle de performance évolutif", qc: "Mesure individuelle et enregistrements de production conservés." },
      "P1.5": { name: "Précision avancée", qc: "Mesure individuelle, enregistrements individuels et traçabilité." },
      "P0.5": { name: "Professionnel · contrôlé individuellement", qc: "Contrôle individuel avec valeurs nominales et réelles et enregistrements de mesure individuels ; identité série, traçabilité de lot, certificat de précision et lots appariés lorsque le programme de la commande les met en œuvre." },
    },
    columns: { cls: "Classe", weight: "Poids", balance: "Équilibre", sw: "Inertie de swing", stiff: "Rigidité", qc: "Architecture de contrôle qualité" },
    stiffTarget: "tolérance cible",
    stiffExact: "conforme au RA cible déclaré sous le protocole de mesure établi en usine",
    programmeNote: "L'identité série, les certificats et la documentation de lot apparié ne sont délivrés que lorsque le programme d'une commande donnée les met en œuvre.",
    targetsNote: "Les spécifications de rigidité sont des cibles de fabrication jusqu'à ce que le protocole applicable et les preuves de production appuient une affirmation plus forte. La proposition d'architecture n'implique pas que chaque configuration répertoriée a déjà passé un processus complet de libération sur quatre paramètres.",
    stiffnessTitle: "Pourquoi la rigidité compte",
    stiffnessP1: "La rigidité du cadre influence la façon dont le cadre répond au contact, son ressenti et la constance entre deux raquettes. Le bénéfice central de son contrôle est une réponse reproductible face à une spécification déclarée.",
    stiffnessP2: "Avant la publication d'une conformité vérifiée, l'enregistrement qualité interne identifie l'instrument, son état d'étalonnage, la méthode, l'état de la raquette, la résolution, l'incertitude de mesure, les mesures répétées, la règle d'arrondi et la règle d'acceptation. Un entier affiché identique n'est la preuve ni d'une variation physique nulle ni d'une erreur de mesure nulle.",
    fields: ["Cible", "Résultat mesuré", "Tolérance admise", "Capabilité de l'instrument"],
    fieldsNote: "Conservés comme champs distincts dans chaque enregistrement.",
    matchedTitle: "Lots appariés",
    matchedP: "Les critères de lot apparié sont définis séparément de la tolérance individuelle. La conformité de chaque raquette à sa tolérance nominale ne prouve pas à elle seule un écart maximal donné entre deux raquettes. Les paires, triplettes et lots d'équipe appariés sont demandés via le configurateur et confirmés par écrit.",
    extendedTitle: "Modèle technique étendu",
    extendedP: "Le modèle de données prend en charge des paramètres supplémentaires. Aucune valeur ni classe de tolérance n'existe encore pour eux ; ils peuvent être indiqués comme cibles demandées dans un cahier des charges technique.",
    extended: { twistweight: "Inertie en torsion", torsionalBehaviour: "Comportement en torsion", length: "Longueur", beamProfile: "Profil de cadre", headGeometry: "Géométrie de tamis", stringPattern: "Plan de cordage", durability: "Durabilité", vibration: "Caractéristiques vibratoires" },
    noZero: "MAXIMUS ne décrit pas sa gamme comme ayant une tolérance nulle. La précision est énoncée comme une classe, avec une tolérance déclarée et une architecture qualité définie.",
    cta: "Configurer avec une classe de précision",
  },
  grip: {
    title: "Architecture de manche d'usine",
    statement: "Huit tailles de manche d'usine. L0–L7.",
    lead: "La géométrie du manche fait partie de l'architecture du manche carbone. Chaque taille est fabriquée comme une géométrie de manche, elle n'est pas épaissie avec des surgrips.",
    emph: "Tailles étendues",
    p1: "La gamme d'usine de huit tailles donne aux entraîneurs et aux joueurs une plage de configuration plus large pour spécifier l'équipement autour du joueur, y compris les géométries L6 et L7, plus grandes.",
    p2: "La désignation nominale de manche est distincte des dimensions brutes du manche structurel et du protocole de mesure final. Les tailles s'appliquent aux séries de performance et aux familles d'entraînement de cette plateforme.",
    p3: "Aucune exclusivité mondiale n'est revendiquée pour cette gamme.",
    columns: { size: "Taille", nominal: "Valeur nominale", family: "S'applique à" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Configurer avec votre taille de manche",
  },
  custom: {
    title: "Ingénierie sur mesure",
    statement: "Conçue sur spécification.",
    sub: "La gamme standard est le point de départ.",
    lead: "MAXIMUS accepte des exigences techniques au-delà des matrices de configuration publiées, pour évaluation, ingénierie, validation et fabrication selon une spécification convenue. La faisabilité est confirmée par examen — toute demande imaginable n'est pas physiquement ou commercialement réalisable.",
    scopeTitle: "Ce qu'un cahier des charges technique peut couvrir",
    scope: ["Géométrie du tamis et du cadre", "Longueur", "Poids", "Équilibre", "Inertie de swing", "Rigidité", "Inertie en torsion", "Géométrie de manche", "Construction", "Lots appariés", "Cadres d'entraînement", "Cosmétique et gravure", "Identité et programmes d'équipe", "Développement dépendant d'un outillage"],
    processTitle: "Processus",
    process: [
      ["Définir", "Cibles préférées, limites impératives, usage prévu et compromis acceptables."],
      ["Concevoir", "Évaluation d'ingénierie au regard de la plateforme et de l'outillage."],
      ["Valider", "Validation au regard de la spécification convenue."],
      ["Spécifier", "Une spécification écrite avec base de mesure et tolérances."],
      ["Produire", "Production conforme à la spécification."],
      ["Mesurer / enregistrer", "Mesure et enregistrements conservés selon la classe de précision applicable."],
    ],
    formTitle: "Soumettre un cahier des charges technique",
    formLead: "Distinguez les cibles préférées des limites impératives. Le résultat est une demande d'examen technique, pas une commande de fabrication automatiquement acceptée.",
    protected: "Les recettes de drapage, l'outillage, l'identité des fournisseurs, les coûts internes et le savoir-faire protégé ne sont pas divulgués par cette voie.",
    cta: "Soumettre un cahier des charges technique",
  },
  training: {
    title: "Systèmes d'entraînement",
    lead: "Deux familles d'entraînement avec leurs propres standards de production, reliées par une seule méthodologie : pratique dirigée par l'entraîneur, enregistrements, réévaluation et transfert vers le jeu de performance.",
    sst: { h: "Sweet Spot Trainer", p: "Une raquette d'entraînement à tamis réduit de 50 in², en système de quatre poids, pour le travail du contact centré, la perception du sweet spot, le contrôle de la raquette et la charge progressive." },
    spot: { h: "Spot Trainer", p: "Entraînement du point de contact avec une petite cible de contact ronde, sur la base approuvée des quatre poids." },
    method: { h: "Méthodologie", p: "Fixer les objectifs, choisir l'équipement avec l'entraîneur, utiliser le système pertinent, consigner, réévaluer, ajuster et transférer." },
    experience: "Prenez-la en main. Jouez-la. Ressentez-la.",
    experienceP: "Demandez un essai, un ajustement ou une démonstration accompagnée par un entraîneur. Une demande envoyée n'est pas un rendez-vous confirmé.",
    cta: "Demander un ajustement ou une démonstration",
    distinct: "Le Sweet Spot Trainer, le Spot Trainer et tout dispositif de démonstration distinct sont des produits distincts et ne sont jamais confondus.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Une catégorie d'entraînement distincte, avec son propre standard de production. Le tamis de 50 in² concentre l'attention sur la zone de contact ; les quatre poids fournissent la progression de charge.",
    baseline: "Base confirmée",
    columns: { head: "Tamis", length: "Longueur", pattern: "Plan de cordage", grips: "Manches d'usine" },
    systemTitle: "Système de quatre raquettes",
    detailsTitle: "Détails de construction",
    systemLead: "Poids et équilibre tels que livrés. La base de mesure est enregistrée séparément et n'est pas encore publiée.",
    purposeTitle: "Objet",
    purpose: ["Travail du contact centré", "Perception du sweet spot", "Contrôle de la raquette", "Charge progressive", "Développement dirigé par l'entraîneur", "Retour vers la raquette de performance du joueur"],
    heavy: "Le modèle de 400 g est une configuration d'entraînement contrôlée. Il n'est pas automatiquement recommandé aux enfants, aux débutants ni à tout joueur ; l'entraîneur définit la charge, la durée et la progression.",
    precisionNote: "Les classes de précision de performance P2.5, P1.5 et P0.5 ne s'appliquent pas automatiquement à cette famille d'entraînement. Les tolérances de production d'entraînement suivent la spécification approuvée propre à la famille.",
    health: "Aucune prévention ou traitement du tennis elbow, aucune élimination des blessures et aucune amélioration garantie ne sont promis.",
    cta: "Demander une démonstration du Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Entraînement du point de contact avec une petite cible de contact ronde. Un produit distinct, avec sa propre identité visuelle, bâti sur la base approuvée des quatre poids.",
    purposeTitle: "Objet confirmé",
    purposeP: "Entraîner le joueur à trouver et à répéter un point de contact précis.",
    weightsTitle: "Progression des poids",
    weightsP: "La progression des poids suit la base de poids approuvée du Sweet Spot Trainer. Les valeurs d'équilibre et les autres spécifications du Sweet Spot Trainer ne sont pas reportées sur le Spot Trainer.",
    dims: "Les dimensions exactes de la cible ne sont pas encore publiées.",
    grips: "Architecture de manche d'usine L0–L7.",
    notes: ["Les classes de précision de performance ne s'appliquent pas automatiquement.", "Ce n'est pas une raquette conventionnelle miniature et aucun plan de cordage n'est publié.", "Le Spot Trainer, le Sweet Spot Trainer et tout dispositif de démonstration distinct restent distinguables."],
    cta: "Poser une question sur le Spot Trainer",
  },
  methodology: {
    title: "Méthodologie et expérience produit",
    lead: "L'équipement n'est qu'une partie d'un parcours de développement structuré. La méthode part des objectifs du joueur, non d'une étiquette produit.",
    stepsTitle: "Le parcours de développement",
    steps: [
      ["Fixer les objectifs", "Les objectifs du joueur et son point de départ."],
      ["Choisir l'équipement", "Un équipement adapté, choisi avec l'entraîneur."],
      ["Utiliser le système", "Le système d'entraînement pertinent, dirigé par l'entraîneur."],
      ["Consigner", "Observations de la participation réelle, sans scores inventés."],
      ["Réévaluer", "Points de contrôle comparables."],
      ["Ajuster", "Ajustements de configuration ou de programme."],
      ["Transférer", "Les acquis transférés vers le jeu de performance."],
    ],
    educationTitle: "Parcours pédagogiques",
    education: { player: "Joueurs — comprendre la configuration, la charge et la progression.", parent: "Parents — continuité du développement, équipement adapté, enregistrements et droits.", coach: "Entraîneurs — systèmes d'entraînement, ajustement, évaluation et usage autorisé des programmes." },
    evidenceTitle: "Discipline de la preuve",
    evidenceP: "Les enregistrements de participation réelle et les observations sont conservés avec leur classification — déclaré par le participant, confirmé par le tuteur, validé par l'entraîneur ou mesuré par le système. Les progrès, les scores et les validations ne sont jamais inventés.",
    experienceTitle: "Prenez-la en main. Jouez-la. Ressentez-la.",
    experienceP: "Un essai, un ajustement ou une démonstration accompagnée par un entraîneur peuvent être demandés. Une demande envoyée n'est pas un rendez-vous confirmé.",
    cta: "Demander un ajustement ou une démonstration",
    cta2: "Demande de partenariat entraîneur",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — profil d'équipement guidé",
    title: "MAXIMUS GPS",
    lead: "Un profil d'équipement guidé. Ne répondez qu'à ce qui vous concerne ; vérifiez et corrigez vos réponses ; recevez un récapitulatif, les directions de configuration applicables et une action suivante concrète.",
    honesty: "Dans cette version, aucune règle d'ajustement automatique n'est approuvée. GPS produit donc un récapitulatif clair des besoins et indique des directions de configuration ; les détails d'équipement sont orientés vers un examen d'expert.",
    rulesVersion: "Version des règles",
    dataVersion: "Version des données produit",
    steps: { role: "Rôle", sport: "Discipline", experience: "Expérience", objectives: "Objectifs", style: "Style de jeu", equipment: "Équipement actuel", preference: "Préférences", coach: "Implication de l'entraîneur", ageBand: "Tranche d'âge", review: "Vérification" },
    notStored: "Non conservé dans ce navigateur.",
    ageNote: "Utilisée uniquement pour orienter la demande. Aucun nom, date de naissance ni information médicale n'est demandé.",
    q: {
      role: "Qu'est-ce qui vous décrit ?",
      sport: "Quelle discipline ?",
      experience: "Niveau d'expérience",
      objectives: "Qu'est-ce qui compte le plus ? (trois choix au maximum)",
      style: "Style de jeu, si connu",
      equipment: "Équipement actuel, le cas échéant",
      equipmentHint: "Marque et modèle, poids ou taille de manche si vous les connaissez. Facultatif.",
      preference: "Configuration préférée ou taille de manche connue",
      grip: "Taille de manche connue",
      coach: "Un entraîneur intervient-il dans vos décisions d'équipement ?",
      ageBand: "Tranche d'âge du joueur (utilisée uniquement pour orienter correctement la demande)",
    },
    roles: { player: "Joueur", parent: "Parent ou tuteur", coach: "Entraîneur", club: "Club ou académie", other: "Autre" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Autre sport de raquette" },
    sportNote: "Des produits existent pour le tennis. Les autres disciplines sont des directions de développement ; votre intérêt est enregistré pour le programme concerné.",
    experience: { beginner: "Débutant", developing: "En progression", intermediate: "Intermédiaire", advanced: "Avancé", competitive: "Compétiteur", professional: "Professionnel" },
    objectives: { control: "Contrôle", power: "Puissance", spin: "Effet", comfort: "Confort", manoeuvrability: "Maniabilité", development: "Développement à long terme", competition: "Compétition", training: "Système d'entraînement", team: "Équipe ou lot apparié", personal: "Personnalisation" },
    styles: { baseline: "Fond de court", allcourt: "Jeu complet", attacking: "Offensif", defensive: "Défensif", coach: "Choisi par l'entraîneur", unknown: "Je ne sais pas" },
    ageBands: { u10: "Moins de 10 ans", u14: "10–13", u18: "14–17", adult: "18 ans et plus" },
    output: {
      title: "Votre profil d'équipement",
      status: "Examen d'expert requis",
      statusP: "Aucune correspondance automatique n'est produite dans cette version. Votre profil a été résumé pour un examen d'expert.",
      directionsTitle: "Directions de configuration applicables",
      directionsP: "D'après les objectifs que vous avez indiqués et la direction de jeu déclarée de chaque série. C'est une direction, pas une recommandation d'ajustement.",
      trainingHint: "Vos objectifs incluent un système d'entraînement : voir le Sweet Spot Trainer et le Spot Trainer.",
      teamHint: "Les lots appariés sont demandés via le configurateur et confirmés par écrit.",
      next1: "Envoyer le profil pour examen d'expert",
      show: "Afficher mon profil",
      configure: "Configurer",
      sendP: "Envoyez votre profil à MAXIMUS pour examen d'expert. Un identifiant de demande s'affiche immédiatement ; la réponse arrive par écrit.",
      otherSport: "Les raquettes MAXIMUS existent pour le tennis. Pour les autres sports de raquette, aucune série tennis n'est proposée ; votre intérêt est enregistré comme direction de développement.",
      noDirection: "Vos objectifs ne désignent pas une seule direction de jeu. L'examen d'expert propose une configuration.",
      incomplete: "Certaines réponses obligatoires manquent — utilisez « Modifier les réponses » pour les compléter.",
    },
    privacy: "GPS ne demande aucune information médicale ni identifiant d'enfant. Seules les réponses à choix multiples sont conservées dans cette session de navigateur ; le texte libre n'est pas conservé.",
  },
  build: {
    title: "Configurez la vôtre",
    lead: "Configurez une demande : série, classe de précision, poids répertorié ou cible personnalisée, taille de manche, cibles demandées, personnalisation, lots appariés et quantité. Le résultat est une demande de configuration avec un identifiant de demande — pas une référence article, un prix, une date de livraison ni un certificat.",
    steps: { series: "Série", cls: "Classe de précision", weight: "Poids", grip: "Manche", targets: "Cibles", personal: "Personnalisation", set: "Lot et quantité", use: "Usage", review: "Vérification" },
    q: {
      series: "Choisissez une série",
      cls: "Choisissez une classe de précision",
      weightMode: "Poids",
      listed: "Poids répertorié",
      customWeight: "Poids demandé (g)",
      balanceShown: "Équilibre calculé pour ce poids",
      balanceRequest: "Équilibre demandé (mm)",
      grip: "Taille de manche d'usine",
      targetsTitle: "Cibles demandées",
      swingweight: "Inertie de swing demandée (kg·cm²)",
      stiffness: "Rigidité demandée (RA)",
      basis: "Base de mesure des valeurs demandées",
      engraving: "Texte de la gravure",
      engravingHint: "Nom, initiales ou numéro. Lettres latines, chiffres, espace, trait d'union, apostrophe et point ; jusqu'à 24 caractères. D'autres écritures sont acceptées sous réserve de confirmation du visuel.",
      engravingType: "Personnalisation",
      types: { none: "Aucune", name: "Nom du joueur", initials: "Initiales", number: "Numéro de lot", academy: "Identification de l'entraîneur ou de l'académie", team: "Programme d'équipe" },
      set: "Raquette individuelle ou lot apparié",
      use: "Usage prévu",
      uses: { play: "Jeu personnel", competition: "Compétition", coaching: "Entraînement", team: "Équipe ou académie", retail: "Évaluation pour la vente ou la distribution", other: "Autre" },
      notes: "Exigences techniques supplémentaires",
    },
    classes: { "P2.5": "P2.5 — socle de performance évolutif", "P1.5": "P1.5 — précision avancée", "P0.5": "P0.5 — professionnel, contrôlé individuellement" },
    stiffExactShort: "la rigidité est conforme au RA cible déclaré sous le protocole d'usine établi",
    clsNote: "Chaque classe contrôle quatre paramètres. P0.5 est une tolérance serrée sous un protocole de mesure défini — pas une erreur nulle. L'identité série, les certificats et la documentation de lot apparié ne s'appliquent que lorsque le programme de votre commande les met en œuvre.",
    listedNote: "Issu de la matrice confirmée de la série.",
    customNote: "Un poids hors matrice, examiné techniquement.",
    balanceCaption: "Chaque poids répertorié affiche son équilibre calculé en mm depuis le talon. Les valeurs calculées ne sont pas des mesures individuelles.",
    spinNote: "Les poids SPIN forment l'architecture de poids demandée. L'équilibre, l'inertie de swing et la rigidité de SPIN ne sont pas fournis ; ils sont définis lors de l'examen technique.",
    customHint: "Grammes entiers, chiffres uniquement. Un poids personnalisé est une demande d'examen technique ; la faisabilité est confirmée par écrit et aucune valeur n'est arrondie.",
    gripNote: "géométrie de manche carbone d'usine, pas une surépaisseur de surgrip",
    targetsLead: "Facultatif. Saisissez uniquement les valeurs dont vous avez besoin. Chacune est enregistrée comme cible demandée pour examen technique, non comme spécification publiée.",
    basisHint: "Obligatoire lorsque vous demandez un poids personnalisé ou une cible : les valeurs se rapportent-elles à une raquette non cordée ou cordée ?",
    inputRange: "Saisie acceptée : {min}–{max}.",
    inputRangeNote: "Les plages de saisie ne filtrent que les entrées impossibles. Elles ne décrivent pas la capacité de production.",
    listedBasis: "valeurs répertoriées — base de mesure confirmée dans la spécification écrite",
    notStored: "Non conservé dans ce navigateur ; ressaisissez-le si vous rechargez la page.",
    artworkReview: "confirmation du visuel requise",
    previewNote: "Aucun aperçu visuel n'est affiché : aucun gabarit de gravure approuvé n'est encore publié pour ce modèle. Votre texte est recueilli pour confirmation du visuel.",
    teamSub: "4–99 raquettes par lot",
    setsLabel: { individual: "Nombre de raquettes", pair: "Nombre de paires appariées", triple: "Nombre de triplettes appariées", team: "Nombre de lots d'équipe" },
    teamSizeLabel: "Raquettes par lot d'équipe",
    totalLabel: "Raquettes au total",
    racquetsUnit: "raquettes",
    setRule: "La quantité compte des lots : une paire appariée fait 2 raquettes par lot, une triplette appariée 3.",
    restart: "Commencer une nouvelle configuration",
    notices: { weightCleared: "{w} g n'est pas dans la matrice {series} ; le poids a donc été effacé. Choisissez un poids répertorié ou demandez une cible personnalisée." },
    reviewTitle: "Demande de configuration",
    reviewP: "Vérifiez la configuration, puis ajoutez vos coordonnées. La demande est enregistrée avec un identifiant de demande et reçoit une réponse écrite ; la disponibilité et les conditions commerciales sont confirmées par écrit.",
    reviewErrors: "Certaines réponses de configuration demandent votre attention :",
    edit: "Modifier",
    fieldNames: { series: "Série", cls: "Classe de précision", mode: "Choix du poids", weight: "Poids répertorié", customWeight: "Poids demandé", basis: "Base de mesure", balanceReq: "Équilibre demandé", sw: "Inertie de swing demandée", ra: "Rigidité demandée", grip: "Taille de manche", ptype: "Personnalisation", engraving: "Texte de la gravure", setType: "Type de lot", sets: "Quantité", teamSize: "Raquettes par lot d'équipe", use: "Usage prévu", notes: "Exigences supplémentaires" },
    status: { listed: "poids répertorié", requestedArchitecture: "architecture de poids demandée", technicalReview: "demande d'examen technique", notPublished: "non fourni", requestedCondition: "condition demandée" },
    chooseLink: "Vous hésitez sur la série ? Obtenez de l'aide pour choisir",
    cta: "Envoyer la demande de configuration",
  },
  experience: {
    title: "Essais et ajustement",
    statement: "Prenez-la en main. Jouez-la. Ressentez-la.",
    lead: "Demandez un essai, un ajustement ou une démonstration accompagnée par un entraîneur. Les demandes sont examinées et reçoivent une réponse écrite ; une demande envoyée n'est pas un rendez-vous confirmé.",
    optionsTitle: "Ce qui peut être demandé",
    options: ["Essai de raquette", "Séance d'ajustement", "Démonstration accompagnée par un entraîneur", "Démonstration du Sweet Spot Trainer ou du Spot Trainer", "Journée de démonstration pour une équipe ou une académie"],
    formTitle: "Demande d'ajustement ou de démonstration",
  },
  engineering: {
    title: "Ingénierie et fabrication",
    statement: "Aéronefs. Yachts. Raquettes.",
    lead: "Une seule philosophie d'ingénierie dans trois environnements : les principes qui façonnent un aéronef, la précision qui guide un yacht en pleine mer, la performance qui définit chaque raquette MAXIMUS. Un récit d'ingénierie — non une revendication de certification aéronautique, de propriété d'un yacht, de propriété d'une usine ou de transfert direct de matériaux.",
    manifesto: ["Nous croyons que la grande ingénierie ne connaît pas de frontières.", "Une philosophie. Conçue sans compromis."],
    capabilityTitle: "Capacité de fabrication",
    capabilityLead: "La capacité est présentée comme une séquence, non comme un slogan.",
    sequence: [
      ["Spécification", "Série, classe de précision, poids, équilibre, inertie de swing, cible de rigidité, géométrie de manche, personnalisation."],
      ["Production", "Construction tout carbone du cadre au manche, produite conformément à la spécification."],
      ["Contrôle qualité", "Mesure et enregistrements selon la classe de précision : enregistrements de production, enregistrements individuels et traçabilité, certification individuelle."],
      ["Production répétée", "Réponse reproductible face à une spécification déclarée, d'un lot de production à l'autre."],
      ["Traçabilité", "Identité série, traçabilité de lot et Certificat de précision lorsque la classe le prévoit."],
    ],
    capacityNote: "La capacité de production, les délais, les quantités minimales et les calendriers de livraison sont confirmés par programme, par écrit, au regard de commandes confirmées et d'un calendrier de mise à disposition convenu.",
    truth: "La capacité n'est ni une production réalisée, ni un stock, ni une date de livraison garantie, ni la propriété d'une unité de fabrication.",
    cta: "Distribution et développement de pays",
    cta2: "Soumettre un cahier des charges technique",
  },
  ecosystem: {
    title: "L'écosystème MAXIMUS",
    lead: "Une clé. Voici ce qu'elle ouvre. Chaque nœud a une explication, un statut exact et une action suivante pertinente.",
    words: ["Ingénierie", "Performances", "Innovations", "Communauté", "Opportunités", "Raison d'être"],
    nodes: {
      engineering: { h: "Ingénierie et fabrication de raquettes", p: "Raquettes tout carbone conçues sur spécification, produites avec des enregistrements qualité et une traçabilité.", a: "Ingénierie et fabrication" },
      precision: { h: "Précision et configuration individuelle", p: "Quatre paramètres, trois classes de précision, huit tailles de manche et l'ingénierie sur mesure.", a: "Précision et rigidité" },
      training: { h: "Entraînement et méthodologie", p: "Le Sweet Spot Trainer, le Spot Trainer et un parcours de développement structuré.", a: "Systèmes d'entraînement" },
      development: { h: "Développement du joueur et de l'entraîneur", p: "Choix dirigé par l'entraîneur, enregistrements, réévaluation et parcours pédagogiques.", a: "Méthodologie" },
      identity: { h: "Identité personnelle et marques personnelles", p: "De la gravure à une marque personnelle ou professionnelle encadrée par des droits.", a: "Marques personnelles" },
      owners: { h: "Enregistrements, savoirs et droits des propriétaires", p: "Un coffre-fort du propriétaire à accès autorisé, proposé pour les enregistrements d'équipement, de développement et de droits.", a: "Propriétaires et coffre-fort" },
      mipa: { h: "Provenance MIPA et contrôle interne", p: "La couche interne de propriété intellectuelle, de provenance et de contrôle documentaire.", a: "Identité juridique et contrôle" },
      digital: { h: "Infrastructure numérique et direction Blockchain 5.0", p: "Provenance, enregistrements traçables, preuves à accès autorisé et identité produit, comme direction technologique déclarée.", a: "Direction technologique" },
      licensing: { h: "Licences contractuelles et programmes de redevances", p: "Marques, produits et ensembles de droits sous licence, aux conditions définies par accord.", a: "Voies de licence" },
      families: { h: "Participation des familles et avantages de programme", p: "Décisions informées, continuité, enregistrements conservés et avantages définis par programme.", a: "Familles et parents" },
      network: { h: "MAXIMUS Sports Network", p: "Joueurs, entraîneurs, clubs, académies, prestataires, opérateurs et partenaires régionaux.", a: "Sports Network" },
      market: { h: "Clubs, académies, distribution et développement de pays", p: "Programmes d'équipe, vente au détail, distribution et développement de territoire, après qualification écrite.", a: "Voies de partenariat" },
      institutional: { h: "Programmes institutionnels, éducation, innovation et impact social", p: "La couche institutionnelle assurée par MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) lorsqu'un programme établit ce rôle.", a: "Programmes institutionnels" },
      extensions: { h: "Futures extensions aux sports de raquette et à l'habillement MAXIMUS", p: "Padel, pickleball, squash, badminton, racquetball, beach-tennis et habillement comme directions de développement.", a: "Sports de raquette" },
    },
    boundaryTitle: "Limites",
    boundary: [
      "L'achat d'une raquette ne crée ni adhésion institutionnelle, ni droits de gouvernance, ni redevances, ni droits d'investissement.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) est l'opérateur institutionnel uniquement lorsqu'un programme établit ce rôle ; les ventes d'équipement identifient leur entité contractante réelle.",
      "Les subventions, le statut caritatif, le traitement fiscal et les autorisations réglementaires ne s'appliquent pas automatiquement d'un pays à l'autre.",
    ],
    techTitle: "Direction technologique",
    techP: "Blockchain 5.0 est la direction technologique déclarée de MAXIMUS. Ses finalités fonctionnelles sont la provenance, les enregistrements traçables, les preuves à accès autorisé, l'identité produit et le rapprochement des événements commerciaux éligibles. Aucun mécanisme de consensus, capacité de transaction, réseau de nœuds, adresse de contrat intelligent, jeton ou certification indépendante n'est présenté, et aucune implémentation déployée n'est revendiquée. Les informations personnelles, les enregistrements concernant des enfants et les accords confidentiels ne sont jamais placés par défaut dans un système public immuable.",
  },
  brands: {
    title: "Marques personnelles et ambassadeurs",
    statement: "Du joueur à la marque. De l'entraîneur à la marque.",
    lead: "Une voie dédiée aux marques personnelles. L'implication de MAXIMUS comprend le développement de la marque et une promotion convenue — pas seulement un nom sur une raquette.",
    progressionTitle: "Progression prévue",
    progression: [
      ["Identité vérifiée", "Une identité vérifiée et un historique de développement."],
      ["Marque distinctive", "Une marque personnelle ou professionnelle distinctive."],
      ["Contenus libres de droits", "Des contenus libres de droits et une identité produit approuvée."],
      ["Ingénierie et collections", "Ingénierie et développement de collections lorsque cela est convenu."],
      ["Promotion", "Promotion par les canaux et partenariats MAXIMUS convenus."],
      ["Participation", "Participation contractuelle aux ventes ou licences éligibles."],
      ["Comptes rendus", "Des comptes rendus transparents au titre de l'accord."],
    ],
    royaltiesTitle: "Redevances et licences",
    royalties: [
      "Les redevances portent sur la marque, le produit, la transaction ou l'ensemble de droits sous licence qui sont définis.",
      "« Ventes mondiales » désigne les ventes éligibles dans le périmètre du contrat — jamais toute raquette MAXIMUS sans lien avec celui-ci.",
      "Les taux, la base de calcul, les territoires, la durée, les remboursements, les déductions, les comptes rendus, le règlement et la vérification sont définis par l'accord applicable. Aucun pourcentage de redevance par défaut n'est publié.",
      "Aucune campagne mondiale, budget média, résultat de parrainage ou succès commercial n'est promis sans un périmètre convenu.",
    ],
    cta: "Envoyer une demande de collaboration de marque",
    cta2: "Demande de partenariat entraîneur",
  },
  families: {
    title: "Familles et parents",
    lead: "Des décisions d'équipement informées, la continuité du développement, la préservation des savoirs et des droits, la visibilité de la participation, et des avantages définis par programme susceptibles de soutenir une activité future.",
    nowTitle: "Disponible dès maintenant",
    now: ["Demandes famille et développement par écrit.", "Choix d'équipement avec l'entraîneur, demandes d'ajustement et de démonstration.", "Enregistrements privés : les profils d'enfants ne sont jamais publiés ni commercialisés par défaut.", "Parcours pédagogique pour les parents : configuration, charge, progression, enregistrements et droits."],
    plannedTitle: "Prévu",
    planned: ["Des avantages de participation définis par programme, utilisables pour des biens et services au sein de l'écosystème, plutôt qu'un intérêt en numéraire.", "Enregistrements des propriétaires et des familles dans le coffre-fort du propriétaire proposé, avec permissions du tuteur et transfert du contrôle à 18 ans."],
    categoriesTitle: "Tenus séparés",
    categories: ["Redevances contractuelles issues de droits sous licence ou de ventes éligibles", "Avantages de participation définis par un programme", "Crédits d'achat ou de service", "Acomptes", "Adhésion institutionnelle"],
    categoriesP: "Ces catégories ne sont jamais traitées comme interchangeables.",
    statusTitle: "Statut réel du programme famille",
    journeyTitle: "Le parcours famille",
    journey: [
      ["Objectif", "Ce que le joueur veut atteindre ensuite."],
      ["Niveau actuel", "Où le joueur se situe aujourd'hui."],
      ["Entraîneur", "Si un entraîneur participe aux décisions d'équipement."],
      ["Équipement", "L'équipement adapté à l'étape, y compris les systèmes d'entraînement le cas échéant."],
      ["Pratique convenue", "Un usage dirigé par l'entraîneur, convenu à l'avance."],
      ["Bilan", "Réévaluation à des points de contrôle comparables."],
    ],
    brief: {
      who: "Parents et tuteurs de joueurs, à toute étape.",
      value: "Une réponse écrite sur l'équipement adapté, l'implication de l'entraîneur et l'étape suivante du développement.",
      now: "Demandes famille par écrit ; choix avec l'entraîneur ; enregistrements privés — les profils d'enfants ne sont jamais publiés.",
      next: "Envoyez la demande famille ci-dessous. Vous recevez immédiatement un identifiant de demande.",
    },
    formTitle: "Demande famille",
    formNote: "À remplir par un parent ou un tuteur. N'indiquez pas le nom de l'enfant, sa date de naissance, son école ni d'information médicale.",
    noPromise: "Un achat ne promet ni redevances, ni rendement d'investissement, ni parrainage, ni financement du développement d'un enfant.",
    statusP: "Cette version explique le modèle et accepte les demandes de programme. L'accumulation, les paiements et l'utilisation ne sont pas disponibles tant que les événements éligibles, les bénéficiaires, la source de financement, la base de calcul, les usages autorisés, le traitement comptable, les remboursements, les annulations, l'expiration, la transférabilité, la clôture du programme et le traitement des litiges ne sont pas définis par écrit. Aucun solde n'est promis comme ne diminuant jamais, aucune participation ne paie l'intégralité de l'entraînement et aucune protection du capital n'est sous-entendue.",
    cta: "Envoyer une demande famille ou développement",
  },
  owners: {
    title: "Propriétaires et coffre-fort du propriétaire",
    lead: "Le coffre-fort du propriétaire est un enregistrement à accès autorisé, proposé, de l'équipement, du développement, des savoirs, des contenus et des droits documentés. Il est présenté comme une partie de l'architecture propriétaire prévue : aucun compte actif, solde, certificat ou palmarès n'est affiché.",
    nowTitle: "Pour les propriétaires actuels, dès maintenant",
    now: ["Demandes des propriétaires : référence produit ou numéro de série, réglage, entretien et demandes d'enregistrements, par écrit.", "Certificat de précision et documentation de lot apparié lorsque la classe de précision le prévoit, livrés avec le produit."],
    archTitle: "Architecture prévue du coffre-fort",
    arch: ["Identité produit et numéros de série", "Configuration et certificats qualité applicables", "Historique d'entretien et de réglage", "Enregistrements de développement du joueur ou de l'entraîneur", "Qualifications et résultats vérifiés", "Médias libres de droits et documents rédigés", "Licences, autorisations et références contractuelles", "Enregistrements du programme de marque personnelle", "Relevés de redevances applicables ou avantages de participation"],
    separationTitle: "Ce que signifie la propriété",
    separation: [
      "La propriété d'une raquette physique est distincte de la propriété d'un droit d'auteur, d'une licence, d'un droit contractuel ou d'un enregistrement décrivant ces éléments.",
      "Un document conservé ou une inscription en blockchain ne prouve pas automatiquement qu'un droit existe ou a été transféré.",
      "La preuve conserve sa classification : déclarée par le participant, confirmée par le tuteur, validée par l'entraîneur, mesurée par le système.",
      "Pour les mineurs : enregistrements privés, permissions du tuteur, aucun profil d'enfant publié et aucune commercialisation de l'identité par défaut.",
      "L'export, la correction, le contrôle d'accès et un transfert approprié du contrôle font partie de la conception.",
    ],
    techTitle: "Blockchain 5.0 et MxSN",
    techP: "Blockchain 5.0 est la direction technologique déclarée ; MxSN définit les concepts d'un réseau à accès autorisé pour le consentement, la remise, la preuve, les droits et les comptes rendus. Aucune mise en œuvre opérationnelle n'est présentée. Le modèle de données de l'application est conçu pour une intégration ultérieure par une interface documentée, sans prétendre qu'une connexion existe aujourd'hui.",
    cta: "Demande propriétaire",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Le lien entre joueurs, entraîneurs, clubs, académies, prestataires, opérateurs de programmes et partenaires régionaux.",
    functionsTitle: "Fonctions potentielles",
    functions: ["Découverte", "Mises en relation", "Programmes de développement", "Soutien en équipement", "Événements", "Accès aux prestations", "Opportunités pour les partenaires"],
    statusTitle: "Statut réel",
    statusP: "Aucun annuaire public n'est encore publié : seuls les participants dont l'identité, la relation et l'autorisation de figurer sont établies seront listés. Une proposition envoyée à un club n'est pas un partenariat, et un distributeur potentiel n'est pas un distributeur désigné. La publication de l'annuaire, la réservation, la messagerie et les transactions commerciales sont contrôlées séparément et ne sont pas actives.",
    cta: "Candidater au réseau",
  },
  partnerships: {
    title: "Voies de partenariat",
    lead: "La qualification écrite d'abord. Chaque voie conduit à une demande propre au rôle ; les conditions commerciales suivent par écrit.",
    commercialTitle: "Activités commerciales potentielles de la plateforme",
    commercial: ["Équipement", "Ingénierie sur mesure", "Personnalisation", "Programmes d'équipe et d'académie", "Systèmes d'entraînement", "Licences contractuelles", "Distribution", "Services approuvés", "Futures catégories de produits"],
    boundary: "Les droits de pays, l'exclusivité, les redevances de territoire et les marges distributeur sont des conditions négociées. Aucun chiffre d'affaires, prévision, valorisation, part de marché, rendement, engagement de financement ou partenariat non nommé n'est publié.",
    routes: {
      coaches: {
        title: "Entraîneurs",
        lead: "Systèmes d'entraînement, ajustement, identité professionnelle, programmes autorisés, opportunités de marque personnelle et fourniture d'équipement.",
        points: ["Le Sweet Spot Trainer et le Spot Trainer dans la pratique dirigée par l'entraîneur.", "Ajustement avec les matrices de configuration et les huit tailles de manche d'usine.", "Coach-to-Brand : un profil professionnel vérifié et une sous-marque encadrée par des droits.", "L'usage autorisé des programmes suit un accord écrit."],
        cta: "Envoyer une demande de partenariat entraîneur",
        brief: {
          who: "Entraîneurs indépendants et équipes d'entraîneurs.",
          value: "Des systèmes d'entraînement pour la pratique dirigée par l'entraîneur, l'ajustement avec les matrices des séries et les huit manches d'usine, et une voie vers une identité professionnelle.",
          now: "Demandes des entraîneurs par écrit. Aucune commission, rémunération ou taux d'apport n'est publié ni sous-entendu.",
          next: "Envoyez la demande entraîneur ci-dessous. Les conditions suivent par écrit.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Clubs et académies",
        lead: "Équipement d'équipe, systèmes d'entraînement, personnalisation, programmes de développement, entretien et participation au réseau.",
        points: ["Lots d'équipe et lots appariés demandés via le configurateur.", "Systèmes d'entraînement et méthodologie pour un développement structuré.", "Personnalisation des programmes d'équipe sur les zones approuvées.", "Journées de démonstration, séances d'ajustement et participation au réseau."],
        cta: "Envoyer un dossier club ou académie",
        brief: {
          who: "Clubs, académies et programmes d'équipe.",
          value: "Lots d'équipe et lots appariés, systèmes d'entraînement, personnalisation des programmes d'équipe et journées de démonstration.",
          now: "Dossiers club et académie par écrit ; les lots d'équipe sont demandés via le configurateur.",
          next: "Envoyez le dossier club ou académie ci-dessous.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribution et développement de pays",
        lead: "Assortiment, coordination de fabrication, capacité technique, développement de territoire et qualification commerciale confidentielle.",
        points: ["Qualification écrite de la contrepartie, du territoire et du canal.", "Assortiment défini à partir des matrices de configuration et des classes de précision.", "Le territoire, l'exclusivité, les volumes, les prix et la protection commerciale sont des conditions négociées, convenues par écrit.", "L'entité contractante, les conditions de paiement et la base de livraison sont identifiées pour chaque transaction."],
        cta: "Envoyer une demande de distribution ou de développement de pays",
        brief: {
          who: "Détaillants, distributeurs et partenaires pays.",
          value: "Un assortiment défini à partir des matrices confirmées, des classes de précision et de la gamme de manches, avec qualification écrite du territoire et du canal.",
          now: "Demandes de distribution par écrit. Le territoire, l'exclusivité, les volumes et les prix sont négociés — rien n'est accordé au moyen d'un formulaire.",
          next: "Envoyez la demande de distribution ci-dessous.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Stratégie et investissement",
        lead: "Capacité d'ingénierie, profondeur de configuration, modèle de fabrication, accès au marché, propriété intellectuelle, services et opportunités d'expansion.",
        points: ["Une discussion stratégique qualifiée ou un accès contrôlé à l'information suit une qualification écrite.", "L'information publique se limite aux spécifications produit approuvées, à l'architecture de configuration, aux capacités vérifiées et aux explications de programme.", "L'économie propre à l'acquéreur, les coûts, la méthodologie protégée et les accords non publiés ne sont divulgués que sous NDA ou contrat."],
        cta: "Demander une discussion stratégique qualifiée",
        brief: {
          who: "Investisseurs et partenaires stratégiques.",
          value: "Une discussion qualifiée sur la capacité d'ingénierie, la profondeur de configuration, le modèle de fabrication, l'accès au marché et la propriété intellectuelle.",
          now: "Aucun chiffre financier, prévision, valorisation ou rendement n'est publié. L'information contrôlée suit une qualification écrite et un NDA.",
          next: "Demandez une discussion stratégique qualifiée ci-dessous.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Programmes institutionnels",
        lead: "Éducation, accès, innovation, preuves de développement, impact social et programmes structurés de façon appropriée.",
        points: ["Les programmes institutionnels sont structurés par MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) lorsque le programme établit ce rôle.", "Les fonds de programme affectés et les transactions commerciales restent distincts.", "Une demande n'est pas une candidature d'adhésion acceptée, et un acheteur d'équipement n'est pas un membre institutionnel.", "Les subventions, le statut caritatif, le traitement fiscal et les autorisations réglementaires sont propres à chaque pays et ne sont jamais présumés."],
        cta: "Envoyer une demande de programme institutionnel",
        brief: {
          who: "Institutions, programmes d'éducation et de développement.",
          value: "Des programmes d'éducation, d'accès, d'innovation et de preuve du développement, structurés avec l'opérateur approprié.",
          now: "Demandes institutionnelles par écrit. Une demande n'est pas une candidature d'adhésion ; un achat d'équipement n'est pas une adhésion institutionnelle.",
          next: "Envoyez la demande institutionnelle ci-dessous.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Divulgation publique et contrôlée",
    disclosure: {
      public: { h: "Informations publiques", p: "Spécifications produit approuvées, construction, architecture de configuration, objets d'entraînement, capacités vérifiées, explications de programme et voies de partenariat." },
      qualified: { h: "Demande qualifiée", p: "Exigences techniques, quantités, intérêt de territoire, périmètre de développement et discussions commerciales pertinentes." },
      controlled: { h: "Sous NDA ou contrat", p: "Formules internes, protocoles qualité détaillés, drapages, outillage, méthodes de fabrication, identité des fournisseurs, coûts, économie propre à l'acquéreur, méthodologie protégée, accords non publiés et enregistrements de droits sensibles." },
    },
  },
  contact: {
    title: "Contact et demandes",
    lead: "Choisissez l'objet de votre demande. Chaque formulaire ne recueille que ce qui est nécessaire pour l'orienter et l'évaluer. Les demandes reçoivent une réponse écrite.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Identité juridique",
  },
  form: {
    purposeLabel: "Objet de la demande",
    purposes: {
      selection: "Aide au choix d'une raquette",
      product: "Demande produit",
      fitting: "Ajustement ou démonstration",
      technical: "Cahier des charges technique",
      config: "Demande de configuration",
      gps: "Profil d'équipement GPS",
      coach: "Partenariat entraîneur",
      club: "Dossier club ou académie",
      distribution: "Distribution ou développement de pays",
      brand: "Collaboration de marque ou ambassadeur",
      family: "Demande famille ou développement",
      institutional: "Programme institutionnel",
      strategic: "Discussion stratégique ou d'investissement",
      owner: "Demande propriétaire",
      network: "Candidature au Sports Network",
      general: "Demande générale",
    },
    fields: {
      name: "Nom",
      email: "Email",
      role: "Votre rôle",
      country: "Pays ou région",
      organisation: "Organisation",
      message: "Votre message",
      level: "Niveau actuel",
      objectives: "Ce qui compte le plus (trois au maximum)",
      currentRacquet: "Raquette actuelle",
      grip: "Taille de manche, si connue",
      seriesInterest: "Série qui vous intéresse",
      quantity: "Quantité",
      city: "Ville ou lieu de la séance",
      coachInvolved: "Un entraîneur intervient-il ?",
      timing: "Période souhaitée",
      targets: "Cibles préférées",
      limits: "Limites impératives",
      use: "Usage prévu",
      tradeoffs: "Compromis acceptables",
      basis: "Base de mesure",
      players: "Nombre de joueurs",
      interests: "Domaines d'intérêt",
      territory: "Territoire visé",
      channels: "Canaux existants et expérience",
      audience: "Public ou discipline",
      proposal: "Collaboration proposée",
      goal: "Objectif de développement",
      ageBand: "Tranche d'âge du joueur",
      scope: "Périmètre du programme",
      interestArea: "Domaine d'intérêt",
      productRef: "Référence produit ou numéro de série",
      requestType: "Type de demande",
      seeking: "Ce que vous recherchez",
      consent: "J'accepte que MAXIMUS conserve et utilise ces informations pour répondre à cette demande. Il ne s'agit pas d'un abonnement marketing.",
    },
    roles: { player: "Joueur", parent: "Parent ou tuteur", coach: "Entraîneur", club: "Club ou académie", retailer: "Détaillant", distributor: "Distributeur", brand: "Marque ou ambassadeur", investor: "Investisseur ou partenaire stratégique", institution: "Institution", other: "Autre" },
    interestOptions: { training: "Systèmes d'entraînement", fitting: "Ajustement", identity: "Identité professionnelle", programmes: "Programmes autorisés", brand: "Marque personnelle", supply: "Fourniture d'équipement", team: "Équipement d'équipe", personalisation: "Personnalisation", development: "Programmes de développement", service: "Entretien et service", network: "Participation au réseau" },
    ownerTypes: { setup: "Réglage et configuration", service: "Entretien", records: "Enregistrements et certificats", other: "Autre" },
    strategicAreas: { engineering: "Capacité d'ingénierie", configuration: "Profondeur de configuration", manufacturing: "Modèle de fabrication", routes: "Accès au marché", ip: "Propriété intellectuelle et services", expansion: "Opportunités d'expansion" },
    errors: {
      required: "Ce champ est obligatoire.",
      too_long: "Cette saisie est trop longue.",
      too_short: "Cette saisie est trop courte.",
      invalid_email: "Saisissez une adresse e-mail valide, par exemple nom@example.com.",
      invalid_choice: "Choisissez l'une des options.",
      not_number: "Saisissez un nombre entier, en chiffres uniquement.",
      out_of_range: "Cette valeur est en dehors de la plage acceptée.",
      not_in_matrix: "Ce poids n'est pas dans la matrice répertoriée de la série sélectionnée.",
      decimal_not_supported: "Saisissez un nombre entier, sans décimales.",
      too_many: "Ne sélectionnez pas plus de trois options.",
      consent_required: "Le consentement est nécessaire pour que MAXIMUS puisse répondre à cette demande.",
      invalid: "Cette saisie n'est pas valide.",
    },
  },
  legal: {
    title: "Identité juridique et contrôle",
    lead: "La marque publique est MAXIMUS / MAXIMUS GPS. Les identités juridiques d'exploitation se distinguent et sont indiquées ici.",
    entities: {
      institutional: { role: "Couche des programmes institutionnels", p: "Assure la couche des programmes institutionnels lorsqu'un programme établit ce rôle. N'est pas un vendeur commercial de raquettes. Une organisation à but non lucratif constituée dans le Dubai International Financial Centre." },
      equipment: { role: "Entité commerciale équipement", p: "L'entité commerciale pour la fourniture, la distribution et la livraison commerciale sous contrat, lorsque les documents d'exploitation en vigueur établissent ce rôle. La partie contractante de toute transaction est identifiée dans les documents de cette transaction." },
      ip: { role: "Propriété intellectuelle, marque et coordination commerciale", p: "Apparaît pour un rôle établi de propriété intellectuelle, de marque ou de coordination commerciale. Aucune responsabilité contractuelle non confirmée n'est attribuée." },
      stewardship: { role: "Référence d'intendance", p: "House of Maximus est la référence d'intendance de l'écosystème lorsque la source pertinente l'appuie." },
      control: { role: "Propriété intellectuelle interne, provenance et contrôle documentaire", p: "MIPA est la couche interne de propriété intellectuelle, de provenance et de contrôle documentaire. Une inscription MIPA interne est distincte d'une marque déposée externe, d'un brevet, d'un enregistrement de droit d'auteur ou d'une reconnaissance judiciaire, et ne constitue pas une approbation visuelle." },
    },
    labels: { licence: "Licence", registration: "Enregistrement", vat: "VAT TRN", address: "Adresse", email: "Email", jurisdiction: "Juridiction" },
    boundaryTitle: "Limites",
    boundary: [
      "Un achat n'accorde pas automatiquement l'adhésion institutionnelle, des droits de gouvernance, des redevances ou des droits d'investissement.",
      "Le rôle institutionnel est distinct des transactions commerciales d'équipement.",
      "La confidentialité, les conditions de programme et les dispositifs d'accès contrôlé correspondent aux fonctions effectivement mises en service.",
      "Aucune déclaration générale de droit applicable ne vaut pour chaque visiteur, vente ou programme étranger ; la base contractuelle est fixée par accord.",
    ],
  },
  privacy: {
    title: "Confidentialité",
    updated: "Version 2026-09-21 · site 4.2",
    contactTitle: "Contact pour les questions de confidentialité",
    sections: {
      collect: ["Ce qui est collecté", "Lorsque vous envoyez un formulaire : les informations que vous saisissez (nom, e-mail, rôle, pays ou région, organisation le cas échéant, votre message et les réponses du formulaire), la page et les paramètres de campagne de votre visite (page d'arrivée, langue, paramètres utm ; identifiants de clic publicitaire uniquement si vous avez autorisé l'analyse d'audience) et l'heure de l'envoi. Votre adresse IP n'est utilisée que sous forme hachée et de courte durée, pour limiter les abus, et n'est pas conservée avec votre demande."],
      purpose: ["Pourquoi", "Pour répondre à votre demande, préparer la proposition ou la spécification que vous avez demandée et conserver une trace de la demande. Aucun message marketing n'est envoyé sur la base d'un formulaire."],
      storageOn: ["Où les demandes sont conservées", "Les demandes sont conservées dans une base de données d'Upstash, Inc. (Redis), fournie via la plateforme d'hébergement Vercel Inc."],
      notifyEmail: ["Notification d'une nouvelle demande", "Lorsqu'une demande est acceptée, une notification contenant les informations que vous avez envoyées est adressée par e-mail à la boîte MAXIMUS responsable."],
      notifyTelegram: ["Notification d'une nouvelle demande", "Lorsqu'une demande est acceptée, une notification contenant les informations que vous avez envoyées est adressée au responsable chez MAXIMUS via Telegram (Telegram FZ-LLC, Dubai), qui traite donc cette notification en transit."],
      notifyWebhook: ["Notification d'une nouvelle demande", "Lorsqu'une demande est acceptée, une notification contenant les informations que vous avez envoyées est adressée à un point d'accès interne MAXIMUS, par une connexion signée et chiffrée."],
      notifyNone: ["Notification d'une nouvelle demande", "La notification des nouvelles demandes est en cours de mise en place. Votre demande est conservée et lue par MAXIMUS dans le registre interne ; rien n'est transmis à un tiers à cette fin."],
      storageOff: ["Où les demandes sont conservées", "La conservation des demandes est en cours de mise en place. Tant qu'elle n'est pas active, les formulaires indiquent qu'une demande ne peut pas être acceptée ; rien n'est conservé. Le site est hébergé par Vercel Inc."],
      browser: ["Stockage dans le navigateur", "Le stockage de session conserve les réponses à choix multiples du GPS et du configurateur ainsi que les paramètres de campagne de votre visite, pour cette session de navigateur. Les coordonnées, le texte libre, le texte de gravure et les informations concernant des enfants ne sont pas conservés dans le navigateur."],
      analyticsOn: ["Analyse d'audience", "Avec votre consentement, Google Analytics 4 mesure les visites et les événements de formulaire, sans coordonnées ni texte de demande. Votre choix est conservé dans le stockage local et peut être modifié à tout moment via « Paramètres d'analyse » en pied de page. Les formulaires fonctionnent sans analyse d'audience."],
      analyticsOff: ["Analyse d'audience", "Aucun outil d'analyse d'audience n'est actif sur ce site."],
      retention: ["Conservation", "Aucune durée de suppression automatique n'est encore configurée. Vous pouvez demander la suppression de votre demande à tout moment."],
      children: ["Enfants", "Les formulaires doivent être remplis par un adulte. Les demandes concernant des joueurs de moins de 18 ans sont faites par un parent ou un tuteur. N'envoyez pas le nom d'un enfant, sa date de naissance, son école ni d'information médicale. Les profils d'enfants ne sont jamais publiés."],
      rights: ["Vos droits", "Pour consulter, corriger ou supprimer votre demande, écrivez à gps@maximus.tennis en indiquant votre identifiant de demande."],
      controlled: ["Informations contrôlées", "Les documents confidentiels ne sont ni conservés sur ce site ni diffusés par lui. La divulgation contrôlée a lieu sous NDA ou contrat, par des canaux distincts."],
    },
  },
  terms: {
    title: "Conditions d'utilisation",
    updated: "Version 2026-09-21",
    sections: [
      ["Information, non offre", "Les informations produit de ce site décrivent des spécifications approuvées, l'architecture de configuration et des explications de programme. Elles ne constituent ni une offre de vente, ni une liste de prix, ni un état des stocks, ni un engagement de livraison. Les conditions commerciales sont convenues séparément par écrit avec l'entité contractante identifiée dans chaque transaction."],
      ["Demandes", "Une demande envoyée via ce site — y compris les profils GPS, les demandes de configuration et les cahiers des charges techniques — est conservée avec un identifiant de demande et examinée. Ce n'est pas une commande acceptée, un engagement de fabrication, un rendez-vous confirmé, une candidature d'adhésion ni une candidature acceptée à un programme."],
      ["Spécifications et preuves", "Les valeurs calculées, les cibles de fabrication et les spécifications confirmées sont distinguées sur les pages concernées. Les valeurs de rigidité sont des cibles de fabrication jusqu'à publication contraire. Aucun résultat pour un joueur donné n'est garanti."],
      ["Écosystème, adhésion et droits", "L'achat d'une raquette ne crée ni adhésion institutionnelle, ni droits d'investissement, ni propriété de droits intellectuels, ni droit à des redevances ou à des avantages de participation. Les droits découlent des conditions de programme publiées ou d'un accord écrit."],
      ["Propriété intellectuelle", "MAXIMUS®, l'emblème au lion, la marque GPS et le contenu de ce site sont protégés. Les formules d'ingénierie internes, les protocoles qualité, les drapages, l'outillage, l'identité des fournisseurs, les coûts et la méthodologie protégée ne sont pas divulgués ici."],
    ],
  },
  lead: {
    submit: "Envoyer la demande",
    submitting: "Envoi en cours…",
    retry: "Réessayer",
    acceptedEyebrow: "Demande acceptée",
    acceptedTitle: "Votre demande a été reçue.",
    requestId: "Identifiant de demande",
    acceptedNext: "MAXIMUS examine chaque demande et répond par écrit à l'adresse e-mail que vous avez indiquée. Conservez l'identifiant de demande pour tout suivi.",
    duplicate: "Cette demande avait déjà été reçue ; aucun doublon n'a été créé.",
    another: "Commencer une nouvelle demande",
    errorsTitle: "Veuillez vérifier ces champs :",
    failTitle: "Votre demande n'a pas été envoyée.",
    fail: {
      offline: "Votre appareil est hors ligne.",
      network: "La connexion au serveur a échoué.",
      timeout: "Le serveur n'a pas répondu à temps.",
      rate_limited: "Trop de demandes sont venues de ce réseau. Réessayez dans quelques minutes.",
      too_fast: "Le formulaire a été envoyé très rapidement. Vérifiez-le et envoyez-le à nouveau.",
      spam_suspected: "La demande a été arrêtée par le filtre anti-spam.",
      unavailable: "Les demandes ne peuvent pas être acceptées pour le moment.",
      default: "Une erreur inattendue est survenue.",
    },
    keepNote: "Votre saisie est conservée sur cette page, vous pouvez donc réessayer.",
    sendByEmail: "Envoyer cette demande par e-mail",
    sendByEmailNote: "Votre application de messagerie s'ouvre avec le texte de cette demande. MAXIMUS la reçoit lorsque vous envoyez l'e-mail.",
    mailConfig: "Configuration demandée",
    mailPage: "Page du site",
    fallback: "Si le problème persiste, écrivez à {email}. Une demande n'est considérée comme envoyée que lorsqu'un identifiant de demande s'affiche.",
    privacyLink: "Avis de confidentialité",
    hpLabel: "Laissez ce champ vide",
    consentShort: "Consentement",
    after: "Après l'envoi, un identifiant de demande s'affiche sur cette page. Les demandes sont examinées et reçoivent une réponse écrite ; une demande n'est pas une commande.",
    basis: { unstrung: "Non cordée", strung: "Cordée", unknown: "Je ne sais pas — à convenir dans la spécification" },
    hints: {
      email: "MAXIMUS répond par écrit à cette adresse.",
      goal: "Par exemple : première raquette de compétition, ou passage d'une raquette junior à une autre. N'indiquez pas de noms, de dates de naissance ni d'informations médicales concernant un enfant.",
      currentRacquet: "Marque et modèle, si connus.",
      message: "N'indiquez pas de mots de passe, de coordonnées de paiement ni d'informations médicales.",
    },
  },
  choose: {
    eyebrow: "Aide au choix",
    title: "Aidez-moi à choisir une raquette",
    lead: "Indiquez à MAXIMUS votre niveau et ce qui compte le plus. Vos réponses sont examinées et vous recevez une proposition écrite : série, classe de précision, poids et taille de manche.",
    stepsTitle: "Ce qui se passe ensuite",
    steps: [
      ["Vos réponses", "Niveau, priorités et taille de manche si vous la connaissez."],
      ["Examen d'expert", "MAXIMUS compare vos réponses aux matrices des séries."],
      ["Proposition écrite", "Une configuration proposée et l'étape suivante, par écrit."],
    ],
    formTitle: "Vos réponses",
    submit: "Demander une aide au choix",
    altTitle: "Vous préférez décider vous-même ?",
    altGps: "Profil GPS détaillé",
    altBuild: "Configurer directement",
    note: "Aucun ajustement automatique et aucune revendication d'exactitude : une personne examine chaque demande.",
  },
  consent: {
    title: "Analyse d'audience",
    text: "MAXIMUS peut-il mesurer les visites avec Google Analytics ? Les formulaires fonctionnent dans les deux cas ; aucune coordonnée ni texte de demande n'est transmis à l'analyse d'audience.",
    allow: "Autoriser l'analyse d'audience",
    decline: "Refuser",
  },
  media: {
    spotHeadsUp: "Cinq MAXIMUS Spot Trainer côte à côte, têtes de contact rondes vers le haut et manches vers le bas, avec des balles posées sur les têtes",
    greatHero: "Série MAXIMUS GREAT, 363 g : la composition complète avec les détails rouges et jaunes sur le tamis, le lettrage MAXIMUS brillant, l'autographe Maximus sur le cœur et le capuchon de manche au lion",
    spotRow: "Cinq MAXIMUS Spot Trainer alignés, des balles posées sur leurs têtes de contact rondes",
    spotPair: "Deux MAXIMUS Spot Trainer dressés devant l'emblème au lion MAXIMUS, des balles posées sur leurs têtes de contact rondes",
    spinVisual: "MAXIMUS SPIN : tamis cordé, lettrage MAXIMUS brillant, grip et capuchon de manche au lion",
    powerVisual: "MAXIMUS POWER : tamis cordé, lettrage MAXIMUS brillant, gravure de personnalisation, grip et capuchon de manche au lion",
    greatVisual: "MAXIMUS GREAT : tamis cordé, lettrage MAXIMUS brillant, gravure de personnalisation, grip, capuchon de manche au lion et marque de série G sur le cœur",
    spinHead: "Tamis et plan de cordage MAXIMUS SPIN",
    handleLion: "Cœur, grip et capuchon de manche MAXIMUS avec la marque au lion",
    engraving: "Gravure de personnalisation argentée sur le cœur",
    lettering: "Lettrage MAXIMUS noir brillant sur un cadre noir mat",
    variantAlt: "Série MAXIMUS {series} — {w} g, équilibre {b} mm : visualisation complète avec la bande de spécification, la zone de gravure de personnalisation et le marquage MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, système de quatre raquettes",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Cœurs de Sweet Spot Trainer avec le lettrage MAXIMUS",
    sstGrips: "Grips et capuchons de manche de Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, quatre capuchons de manche avec la marque au lion",
    note: "Visuel produit",
  },
  notFound: { title: "Page introuvable", p: "La page que vous avez demandée n'existe pas dans cette langue.", cta: "Aller à la page d'accueil" },
};

export default fr;
