/* Irish (Gaeilge, An Caighdeán Oifigiúil) dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const ga = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — raicéid leadóige go hiomlán as carbón, déanta de réir sonraíochta",
    defaultDescription:
      "Raicéid leadóige go hiomlán as carbón ón bhfráma go dtí an hanla: GREAT 97 in², POWER 98 in² agus SPIN 100 in², ocht méid greama ón monarcha L0–L7, aicmí beachtais do mheáchan, cothromaíocht, meáchan luasctha agus righne, agus innealtóireacht shaincheaptha ar iarratas.",
  },
  common: {
    statuses: {
      current: "Reatha",
      agreement: "Ar fáil trí chomhaontú",
      development: "Á fhorbairt",
      concept: "Coincheap",
      target: "Sprioc déantúsaíochta",
      modelled: "Ríofa",
      confirmed: "Deimhnithe",
      requested: "Ailtireacht iarrtha",
      notprovided: "Níor soláthraíodh",
    },
    brief: { who: "Cé dó a bhfuil sé", value: "Cad a fhaigheann tú", now: "Deimhnithe anois", next: "An chéad chéim eile" },
    labels: {
      next: "Ar aghaidh",
      back: "Siar",
      edit: "Freagraí a athrú",
      review: "Athbhreithniú",
      start: "Tosaigh",
      restart: "Tosaigh arís",
      copy: "Cóipeáil téacs an iarratais",
      copied: "Cóipeáilte",
      openEmail: "Oscail an ríomhphost chun an iarratas seo a sheoladh",
      reference: "Tagairt an iarratais",
      weight: "Meáchan",
      balance: "Cothromaíocht",
      swingweight: "Meáchan luasctha",
      stiffness: "Righne",
      grip: "Méid greama",
      headSize: "Méid an chinn",
      series: "Sraith",
      precisionClass: "Aicme bheachtais",
      quantity: "Cainníocht",
      notProvided: "Gan foilsiú go fóill",
      requestTarget: "Sprioc iarrtha",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Tuilleadh eolais",
      allSeries: "Gach sraith",
      points: "meáchain liostaithe",
      optional: "roghnach",
      required: "riachtanach",
      select: "Roghnaigh",
      yes: "Tá",
      no: "Níl",
      unknown: "Nílim cinnte",
      custom: "Sprioc shaincheaptha",
      listed: "Meáchan liostaithe",
      individual: "Raicéad aonair",
      pair: "Péire meaitseáilte",
      triple: "Trírín meaitseáilte",
      team: "Tacar foirne",
      summaryTitle: "Achoimre ar an iarratas",
      nextAction: "An chéad ghníomh eile",
      status: "Stádas",
      learn: "Foghlaim tuilleadh",
      schematic: "Léaráid — ní tomhas",
      photo: "Grianghraf",
    },
    ecosystemStrip: "Éiceachóras MAXIMUS",
    truth: {
      noPrices: "Deimhnítear praghsanna, cainníochtaí íosta, amanna soláthair, baránta agus gealltanais seachadta i scríbhinn de réir margaidh agus de réir cláir.",
      requestNotOrder: "Is iarratas ar athbhreithniú atá i gceist. Ní ordú glactha, ní gealltanas déantúsaíochta ná ní coinne dheimhnithe é.",
      noGuarantee: "Ní ráthaíonn aon trealamh, modh ná clár a bhfuil cur síos air anseo toradh ar leith d'imreoir ar leith.",
      governing: "Foilsítear an leathanach seo i roinnt teangacha. Is é an leagan Béarla an leagan rialaithe; cuirtear aistriúchán ar fáil mar áis.",
    },
  },
  nav: {
    language: "Teanga",
    groups: { racquets: "Raicéid", training: "Traenáil", ecosystem: "Éiceachóras", partnerships: "Comhpháirtithe" },
    familyPlan: "Leadóg Theaghlaigh",
    racquets: "Sraitheanna raicéad agus comparáid",
    great: "GREAT — 97 in² · Smacht",
    power: "POWER — 98 in² · Cumhacht",
    spin: "SPIN — 100 in² · Casadh",
    precision: "Beachtas agus righne",
    grip: "Ailtireacht greama ón monarcha L0–L7",
    custom: "Innealtóireacht shaincheaptha",
    training: "Córais traenála",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Modheolaíocht",
    gps: "MAXIMUS GPS",
    build: "Tóg do cheann féin",
    choose: "Cabhraigh liom roghnú",
    ecosystem: "Léarscáil an éiceachórais",
    engineering: "Innealtóireacht agus déantúsaíocht",
    experience: "Triail agus feistiú",
    brands: "Brandaí pearsanta agus ambasadóirí",
    families: "Teaghlaigh agus tuismitheoirí",
    owners: "Úinéirí agus taisceadán an úinéara",
    network: "Sports Network",
    partnerships: "Gach bealach comhpháirtíochta",
    coaches: "Cóitseálaithe",
    clubs: "Clubanna agus acadaimh",
    distribution: "Dáileadh agus forbairt tíre",
    strategic: "Straitéis agus infheistíocht",
    institutional: "Cláir institiúideacha",
    contact: "Teagmháil",
    legal: "Céannacht dhlíthiúil",
    privacy: "Príobháideachas",
    terms: "Téarmaí",
    menu: "Roghchlár",
    close: "Dún",
    home: "Baile",
    skip: "Léim chuig an inneachar",
  },
  footer: {
    line: "Is é raicéad MAXIMUS an eochair atá agat chuig domhan MAXIMUS.",
    product: "Táirge",
    ecosystem: "Éiceachóras",
    company: "Eagraíocht",
    instagram: "Instagram",
    email: "Ríomhphost",
    analytics: "Socruithe anailísíochta",
    subscribe: {
      title: "Fan le MAXIMUS",
      line: "Sraitheanna nua, dátaí feistithe, ábhar traenála agus clár na n-úinéirí. Cúpla litir sa bhliain, agus sin é.",
      label: "Seoladh ríomhphoist",
      placeholder: "your@email.com",
      button: "Liostáil",
      sending: "Á sheoladh",
      done: "Tá tú ar an liosta. Ní scríobhaimid ach nuair a bhíonn rud éigin fiúntach le léamh.",
      invalid: "Seiceáil an seoladh, le do thoil.",
      failed: "Níor cláraíodh an seoladh. Bain triail eile as i gceann nóiméid.",
      terms: "Nuair a liostálann tú, aontaíonn tú go bhféadfaidh MAXIMUS na nuashonruithe seo a sheoladh chugat agus do sheoladh a choinneáil chuige sin. Tá nasc díliostála i ngach litir.",
    },
    rights: "Is marcanna d'éiceachóras MAXIMUS é MAXIMUS® agus suaitheantas an leoin. Déanann MIPA rialú inmheánach ar mhaoin intleachtúil, ar bhunús ábhair agus ar dhoiciméid.",
    boundary:
      "Aontaítear téarmaí tráchtála agus conarthacha ar leithligh i scríbhinn. Ní chruthaíonn ceannach raicéid ballraíocht institiúideach, cearta infheistíochta, úinéireacht ar mhaoin intleachtúil ná teideal chun ríchíosanna.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Tosaíonn an beachtas ag an teagmháil.",
    heroProduct: "Nascann Sweet Spot Trainer, Spot Trainer agus modheolaíocht MAXIMUS cleachtadh dírithe le raicéid feidhmíochta go hiomlán as carbón.",
    heroCta1: "Féach ar an gcóras traenála",
    heroCta2: "Féach ar GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Smacht",
    heroMeta: [
      ["Go hiomlán as carbón", "ón bhfráma go dtí an hanla"],
      ["4 pharaiméadar", "meáchan · cothromaíocht · meáchan luasctha · righne"],
      ["8 méid greama", "céimseata na monarchan L0–L7"],
      ["3 shraith", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Plean Leadóige an Teaghlaigh · Bí páirteach linn",
      title: "Buiséad do theaghlaigh. Cad a cheannaíonn sé. Cad a thógann sé.",
      p: "Trí chás taobh le taobh — anois, beartaithe agus mian. Na seisiúin, na huaireanta agus na teagmhálacha liathróide a cheannaíonn do bhuiséad, agus costas seisiúin amháin, uair an chloig amháin agus buille amháin, ríofa ó d'uimhreacha féin.",
      points: [
        ["D'uimhreacha féin", "Is uaitse a thagann gach suim. Níl aon toimhde ann agus ní dhéantar aon tiontú."],
        ["Trí chás", "Cuir a bhfuil á dhéanamh agat anois i gcomparáid leis a bhfuil beartaithe agat agus leis an méid ba mhaith leat a dhéanamh."],
        ["Deich mbliana chun tosaigh", "An plean caiteachais thar bhliain amháin go deich mbliana, teoranta ag na haoiseanna a shocraíonn tú."],
        ["Lasmuigh den chúirt", "Tacaíocht le hiontráil i bpríomhscoileanna, agus sócmhainní digiteacha a fhanann leis an imreoir."],
      ],
      cta: "Ríomh plean leadóige do theaghlaigh",
    },
    paths: {
      eyebrow: "Tosaigh anseo",
      title: "Roghnaigh do bhealach",
      items: {
        player: { h: "Imreoir", p: "Faigh raicéad de réir leibhéil agus tosaíochtaí, nó cumraigh ceann go díreach.", a: "Faigh do raicéad" },
        parent: { h: "Tuismitheoir", p: "Bealach i scríbhinn do spriocanna forbartha, do pháirt an chóitseálaí agus do threalamh oiriúnach.", a: "Bealach an teaghlaigh" },
        coach: { h: "Cóitseálaí, club nó acadamh", p: "Córais traenála, feistiú, tacair foirne agus pearsantú.", a: "Bealaí cóitseálaithe agus clubanna" },
        partner: { h: "Dáileoir nó comhpháirtí", p: "Dáileadh, forbairt tíre, bealaí straitéiseacha agus institiúideacha.", a: "Bealaí comhpháirtíochta" },
      },
    },
    series: {
      eyebrow: "Sraitheanna feidhmíochta",
      title: "Trí ailtireacht feidhmíochta. Ardán innealtóireachta amháin.",
      lead: "Roghnaigh an tsraith de réir treo imirte, agus críochnaigh an chumraíocht ansin: aicme bheachtais, meáchan, greim, pearsantú.",
      cta: "Déan comparáid idir na sraitheanna",
      configure: "Cumraigh",
      open: "Oscail an tsraith",
      photoPending: "Grianghraf gan foilsiú go fóill",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Córas Beachtais MAXIMUS",
      title: "Meáchan. Cothromaíocht. Meáchan luasctha. Righne.",
      sub: "Á rialú mar aon chóras innealtóireachta.",
      lead: "Sainíonn trí aicme bheachtais cé chomh docht a choinnítear gach raicéad críochnaithe leis an sonraíocht dhearbhaithe. Is lamháltas docht é P0.5 faoi phrótacal tomhais sainithe — ní earráid nialasach.",
      cta: "Beachtas agus righne go mion",
    },
    stiffness: {
      eyebrow: "Righne",
      title: "Freagairt inathdhéanta ón bhfráma i gcoinne sprice dearbhaithe.",
      p: "Múnlaíonn righne an fhráma an fhreagairt, an mothú agus an chomhsheasmhacht idir raicéid. Déileálann MAXIMUS léi mar an ceathrú paraiméadar rialaithe: coinnítear an sprioc, an toradh tomhaiste, an lamháltas ceadaithe agus cumas na hionstraime i dtaifid ar leithligh. Is inathdhéanmhacht an buntáiste — ní toradh ráthaithe do gach imreoir.",
      cols: [["Freagairt", "An chaoi a gcuireann an fráma fuinneamh ar ais ag an teagmháil."], ["Mothú", "An rud a bhraitheann an t-imreoir ag an teagmháil."], ["Comhsheasmhacht", "Freagraíonn raicéid a tógadh de réir na sonraíochta céanna ar an gcaoi chéanna laistigh den aicme."]],
      schematicCaption: "Léaráid: an diall ceadaithe timpeall ar sprioc righne dhearbhaithe gach aicme. Ní tomhas é; ní thugtar aon luach RA le fios.",
      bands: { p25: "lamháltas sprice ±1 RA", p15: "lamháltas sprice ±0.5 RA", p05: "comhlíonann an sprioc RA dhearbhaithe faoi phrótacal tomhais bunaithe na monarchan — ní earráid nialasach", target: "sprioc dhearbhaithe (ní thugtar aon luach le fios)" },
    },
    carbon: {
      eyebrow: "Caighdeán tógála",
      title: "Go hiomlán as carbón. Ón bhfráma go dtí an hanla.",
      p: "Tá gach raicéad MAXIMUS reatha ar an ardán seo go hiomlán as carbón ina struchtúr, an hanla san áireamh. Ní úsáidtear cúrán chun an hanla a mhúnlú.",
      gripTitle: "Ocht méid greama ón monarcha. L0–L7.",
      gripP: "Is céimseata hanla carbóin ón monarcha gach méid — ní forghreim atá tógtha suas.",
      scaleCaption: "Léaráid: ainmniúcháin ainmniúla greama L0–L7 (4″ go 4⅞″). Ní toisí tomhaiste hanla.",
      cta: "Ailtireacht greama ón monarcha",
    },
    custom: {
      eyebrow: "Innealtóireacht shaincheaptha",
      title: "Déanta de réir sonraíochta.",
      sub: "Is túsphointe an raon caighdeánach.",
      p: "Glacann MAXIMUS le riachtanais theicniúla atá taobh amuigh de na maitrísí foilsithe le haghaidh measúnaithe, innealtóireachta, bailíochtaithe agus déantúsaíochta de réir sonraíochta comhaontaithe. Deimhnítear indéantacht i scríbhinn.",
      chain: ["Sainigh", "Innealtóireacht", "Bailíochtaigh", "Sonraigh", "Déan", "Tomhais / taifead"],
      cta: "Seol cur síos teicniúil",
      cta2: "Pléigh innealtóireacht shaincheaptha",
    },
    training: {
      eyebrow: "Córais traenála",
      title: "Córas traenála tógtha timpeall na teagmhála.",
      p: "Nascann Sweet Spot Trainer, modheolaíocht MAXIMUS agus Spot Trainer an trealamh le cleachtadh faoi stiúir cóitseálaí: teagmháil sa lár, smacht, ualach céimnithe agus an aistriú ar ais chuig an raicéad feidhmíochta.",
      cta: "Córais traenála",
      cta2: "Iarr taispeántas",
      photoPending: "Grianghraf den traenálaí gan foilsiú go fóill",
      sstP: "Ceann traenála 50 in² do chleachtadh teagmhála sa lár, le ceithre chumraíocht meáchain as a roghnaíonn an cóitseálaí an ualach.",
      sstCta: "Féach ar Sweet Spot Trainer",
      sstCaption: "Cumraíocht 300 g, ceann de cheithre cheann",
      methodP: "Socraigh cuspóirí, roghnaigh trealamh, cleacht le páirt an chóitseálaí, taifead breathnuithe, athmheas, coigeartaigh agus aistrigh an obair chuig imirt feidhmíochta.",
      methodCta: "Féach ar an modheolaíocht",
      spotP: "Sprioc bheag chruinn chun pointe teagmhála beacht inathdhéanta a chleachtadh.",
      spotCta: "Féach ar Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Déantúsaíocht agus rialú cáilíochta",
      title: "Tógtha de réir sonraíochta. Tomhaiste agus taifeadta.",
      p: "Leanann an táirgeadh sonraíocht scríofa gach ordaithe. Leanann na taifid an aicme bheachtais: taifid táirgthe coinnithe do P2.5, taifid aonair agus inrianaitheacht do P1.5, rialú aonair agus doiciméadú do P0.5 nuair a chuireann clár an ordaithe i bhfeidhm iad.",
      confirmedTitle: "Deimhnithe",
      confirmed: ["Tógáil go hiomlán as carbón ón bhfráma go dtí an hanla.", "Aicmí beachtais P2.5, P1.5 agus P0.5 le ceithre pharaiméadar rialaithe.", "Ocht méid greama ón monarcha L0–L7."],
      pendingTitle: "Gan foilsiú go fóill",
      pending: "Níl grianghraif de threalamh tomhais, taifid shamplacha rialaithe cáilíochta ná píosaí scannáin ón monarcha foilsithe go fóill. Ní teastas tomhaiste aon rud ar an leathanach seo.",
      captions: { lettering: "Litreoireacht MAXIMUS shnasta ar an bhfráma neamhlonrach", buttcap: "An greim agus an caipín deiridh le marc an leoin", handle: "Greanadh pearsantaithe airgid", finish: "An ceann agus leaba na sreang" },
      cta: "Innealtóireacht agus déantúsaíocht",
    },
    world: {
      eyebrow: "Domhan MAXIMUS",
      title: "Aon eochair. Aon éiceachóras. Deiseanna gan teorainn.",
      note: "Is caint bhranda é “deiseanna gan teorainn”, agus ní gealltanas ar indéantacht theicniúil, ar ioncam ná ar rochtain gan teorainn. Ní chruthaíonn ceannach ríchíosanna, torthaí infheistíochta, urraíocht ná maoiniú ar fhorbairt imreora.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — agus an treoir atá agat i saol na leadóige: próifíl threoraithe trealaimh a fhreagraítear i scríbhinn." },
        personal: { h: "Pearsantú", p: "Ainmneacha, ceannlitreacha, uimhreacha agus aitheantas foirne sa ghreanadh airgid ceadaithe." },
        development: { h: "Forbairt", p: "Córais traenála faoi stiúir cóitseálaí, taifid agus athmheasúnú." },
        ecosystem: { h: "Éiceachóras leathnaithe", p: "Brandaí pearsanta, taifid úinéirí, an líonra, ceadúnú agus cláir institiúideacha — gach ceann taispeánta le fíorstádas." },
      },
      cta: "Féach ar an éiceachóras",
    },
    partners: {
      eyebrow: "Bealaí comhpháirtíochta",
      title: "Cóitseálaithe, clubanna, dáileoirí agus comhpháirtithe.",
      p: "Cáiliú i scríbhinn ar dtús. Déantar cearta tíre, eisiachas agus téarmaí tráchtála a chaibidil i scríbhinn — ní thugtar riamh trí fhoirm iad.",
      cta: "Gach bealach comhpháirtíochta",
      formTitle: "Fiosrúchán gearr",
      formLead: "Roghnaigh an cuspóir agus scríobh chuig MAXIMUS. Gheobhaidh tú aitheantas iarratais ar an leathanach seo.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "AN TREOIR ATÁ AGAT I SAOL NA LEADÓIGE" } },
    personal: { eyebrow: "Pearsantú", title: "D'ainm. D'uimhir. Do MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Trí shraith. Fíorpharaiméadair." },
    map: { cta: "Féach ar an éiceachóras" },
  },
  racquets: {
    title: "Raicéid",
    lead: "Trí shraith feidhmíochta le caighdeán tógála comhroinnte, córas beachtais comhroinnte agus ailtireacht greama ón monarcha comhroinnte. Is ailtireacht feidhmíochta bhunaithe gach sraith laistigh d'ardán innealtóireachta níos leithne.",
    direction: { control: "Smacht", power: "Cumhacht", spin: "Casadh" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Príomhtreo imirte",
    compareTitle: "Comparáid idir na sraitheanna",
    compareLead: "Sonraí ailtireachta deimhnithe amháin. Níl patrúin sreang, faid, próifílí bíoma, raonta teannais, luachanna ainmniúla meáchain luasctha ná righne foilsithe do na sraitheanna seo; bailítear iad mar spriocanna iarrtha le haghaidh athbhreithnithe theicniúil.",
    columns: { series: "Sraith", head: "Méid an chinn", direction: "Treo", weights: "Meáchain liostaithe", range: "Raon meáchain", balance: "Sonraí cothromaíochta" },
    balanceModelled: "Luachanna ríofa",
    balanceNotProvided: "Gan foilsiú go fóill",
    construction: "Tógáil: go hiomlán as carbón, fráma go hanla · Beachtas: P2.5 / P1.5 / P0.5 · Greamanna: L0–L7",
    otherTitle: "Spóirt raicéad eile",
    otherLead: "Treonna forbartha ceadaithe. Níl aon táirgí indíolta sna catagóirí seo agus ní aistrítear aon sonraíocht leadóige chucu.",
    other: { padel: "Padal", pickleball: "Pickleball", squash: "Scuais", badminton: "Badmantan", racquetball: "Racquetball", beachTennis: "Leadóg trá" },
    ctaConfigure: "Cumraigh iarratas",
    ctaSeries: "Oscail an tsraith",
  },
  seriesPage: {
    eyebrow: "Sraitheanna feidhmíochta",
    intro: {
      great: "Tá ailtireacht GREAT, 97 in², tógtha timpeall ar smacht: ceann dlúth, teagmháil bheacht agus muinín treo.",
      power: "Tá ailtireacht POWER, 98 in², tógtha timpeall ar aistriú fuinnimh: doimhneacht agus luas ó fhráma seasmhach.",
      spin: "Tá ailtireacht SPIN, 100 in², tógtha timpeall ar iompar na liathróide: casadh, lamháil agus múnlú ruthaig.",
    },
    photoPending: "Grianghraf na sraithe gan foilsiú go fóill",
    detailPending: "Níl grianghraif mhionsonraithe de thógáil ná de hanla na sraithe seo foilsithe go fóill.",
    specsTitle: "Sonraíocht agus stádas",
    catalogue: {
      eyebrow: "Catalóg na sraithe {series}",
      title: "{n} leagan meáchain",
      lead: "Gach leagan de shraith {series}, curtha in ord de réir meáchain. Meáchan i ngraim, cothromaíocht i milliméadair ón tóin. Taispeántar gach léirshamhlú ina iomláine: níl aon rud bearrtha, folaithe ná sínte.",
      selectLabel: "Roghnaigh leagan meáchain",
      select: "Taispeáin an leagan seo",
      selected: "Taispeánta thuas",
      balanceLabel: "Cothromaíocht",
      headLabel: "Méid an chinn",
      constructionLabel: "Tógáil",
      gripsLabel: "Méideanna greama ón monarcha",
      precisionLabel: "Aicmí beachtais",
      balanceConfirmed: "Is é an luach deimhnithe don mheáchan seo an chothromaíocht agus tagann sé leis an bhfigiúr atá priontáilte ar an léirshamhlú.",
      balanceModelled: "Is luach ríofa don mheáchan liostaithe seo an chothromaíocht, agus ní tomhas aonair ón monarcha é; tagann sé leis an bhfigiúr atá priontáilte ar an léirshamhlú.",
      zoom: "Oscail an íomhá",
      close: "Dún",
      allTitle: "Na {n} leagan ar fad",
    },
    specs: { head: "Méid an chinn", direction: "Príomhtreo", weights: "Meáchain liostaithe", range: "Raon meáchain", balance: "Cothromaíocht", construction: "Tógáil", grips: "Greamanna ón monarcha", precision: "Aicmí beachtais" },
    construction: "Go hiomlán as carbón, fráma go hanla",
    statusTitle: "Stádas na luachanna",
    matrixTitle: "An maitrís meáchain iomlán",
    matrixLead: "Is é an rogha chaighdeánach na meáchain liostaithe. Is féidir meáchain eile a iarraidh mar spriocanna saincheaptha; ní chuirtear luachanna idirmheánacha atá in easnamh isteach.",
    balanceNote: {
      confirmed: "Tá na luachanna cothromaíochta deimhnithe do gach meáchan liostaithe (mm ón tóin) agus tagann siad leis an bhfigiúr atá priontáilte ar léirshamhlú an mheáchain sin. Ní ríomhtar anseo iad agus ní réitítear idir meáchain chomharsanacha iad; deimhnítear bonn an tomhais sa sonraíocht scríofa.",
      modelled: "Ríomhtar na luachanna cothromaíochta do gach meáchan liostaithe (mm ón tóin). Ní tomhais aonair ón monarcha iad; deimhnítear bonn an tomhais sa sonraíocht scríofa.",
      notprovided: "Níl luachanna cothromaíochta don tsraith seo soláthraithe. Ná bain tátal astu ó shraith eile.",
    },
    optionsTitle: "Beachtas, greim agus meáchan",
    notPublished: "Gan foilsiú don tsraith seo: patrún sreang, fad, bíoma, raon teannais, meáchan luasctha agus luachanna righne. Is féidir leat iad a lua mar spriocanna iarrtha le haghaidh athbhreithnithe theicniúil.",
    offerTitle: "Cad a tharlaíonn tar éis an iarratais",
    offerSteps: [
      ["Iarratas", "Cuir cumraíocht nó ceist isteach. Taispeántar aitheantas iarratais láithreach."],
      ["Athbhreithniú", "Déanann MAXIMUS athbhreithniú ar an tsraith, an aicme, an meáchan, an greim agus aon spriocanna iarrtha."],
      ["Freagra i scríbhinn", "Deimhnítear an tsonraíocht, an infhaighteacht agus na téarmaí tráchtála i scríbhinn."],
    ],
    faqTitle: "Ceisteanna",
    faq: [
      ["An bhfuil na luachanna cothromaíochta tomhaiste?", "Ríomhtar iad do na meáchain liostaithe, agus ní tomhais aonair iad. Deimhnítear bonn an tomhais sa sonraíocht scríofa."],
      ["An féidir meáchan nach bhfuil liostaithe a iarraidh?", "Is féidir, mar sprioc shaincheaptha i ngraim iomlána. Déantar athbhreithniú teicniúil air agus deimhnítear an indéantacht i scríbhinn."],
      ["Cad a athraíonn an aicme bheachtais?", "Cé chomh docht a choinnítear meáchan, cothromaíocht, meáchan luasctha agus righne leis an sonraíocht dhearbhaithe, agus cé na taifid a choinnítear."],
      ["An dtógtar an greim suas le forghreamanna?", "Ní thógtar. Is céimseatacha hanla carbóin ón monarcha iad L0–L7."],
      ["Cá bhfuil na praghsanna agus na hamanna seachadta?", "Deimhnítear i scríbhinn iad do gach iarratas agus níl siad foilsithe anseo."],
    ],
    faqSpinBalance: ["Cá as a dtagann luachanna cothromaíochta SPIN?", "Ó thábla deimhnithe na sraithe Spin: 33 leagan meáchain le cothromaíocht i milliméadair ón tóin. Tagann gach péire leis an bhfigiúr atá priontáilte ar léirshamhlú ceadaithe an mheáchain sin. Ní ríomhtar na luachanna agus ní réitítear idir meáchain chomharsanacha iad."],
    ctaBuild: "Cumraigh an tsraith seo",
    ctaAsk: "Cuir ceist faoin tsraith seo",
    ctaCompare: "Déan comparáid idir gach sraith",
    weightsLabel: "meáchain liostaithe",
    headLabel: "ceann",
  },
  precision: {
    title: "Beachtas agus righne",
    switch: { label: "Roghnaigh aicme bheachtais", panelLabel: "Ceithre pharaiméadar rialaithe —", qcLabel: "Ailtireacht rialú cáilíochta", protocolNote: "faoi phrótacal tomhais sainithe rialú cáilíochta na monarchan", fullTable: "Tábla comparáide iomlán" },
    lead: "Ceithre pharaiméadar á rialú mar aon chóras innealtóireachta. Sainíonn gach aicme cé chomh docht a choinnítear raicéad críochnaithe leis an sonraíocht dhearbhaithe agus cé na taifid cháilíochta a chruthaítear.",
    statement: "Meáchan. Cothromaíocht. Meáchan luasctha. Righne. Á rialú mar aon chóras innealtóireachta.",
    classes: {
      "P2.5": { name: "Croí feidhmíochta inscálaithe", qc: "Tomhas aonair agus taifid táirgthe coinnithe." },
      "P1.5": { name: "Beachtas ardleibhéil", qc: "Tomhas aonair, taifid aonair agus inrianaitheacht." },
      "P0.5": { name: "Gairmiúil · rialaithe ina aonar", qc: "Rialú aonair le luachanna ainmniúla agus luachanna iarbhír agus taifid tomhais aonair; céannacht shraithuimhreach, inrianaitheacht baisce, teastas beachtais agus tacair mheaitseáilte nuair a chuireann clár an ordaithe i bhfeidhm iad." },
    },
    columns: { cls: "Aicme", weight: "Meáchan", balance: "Cothromaíocht", sw: "Meáchan luasctha", stiff: "Righne", qc: "Ailtireacht rialú cáilíochta" },
    stiffTarget: "lamháltas sprice",
    stiffExact: "comhlíonann an sprioc RA dhearbhaithe faoi phrótacal tomhais bunaithe na monarchan",
    programmeNote: "Ní eisítear céannacht shraithuimhreach, teastais ná doiciméadú tacair mheaitseáilte ach nuair a chuireann clár ordaithe ar leith i bhfeidhm iad.",
    targetsNote: "Is spriocanna déantúsaíochta na sonraíochtaí righne go dtí go dtacaíonn an prótacal cuí agus fianaise táirgthe le maíomh níos láidre. Ní thugann an ailtireacht le fios go bhfuil próiseas eisiúna iomlán ceithre pharaiméadar curtha di cheana ag gach cumraíocht liostaithe.",
    stiffnessTitle: "Cén fáth a bhfuil righne tábhachtach",
    stiffnessP1: "Imríonn righne an fhráma tionchar ar an gcaoi a bhfreagraíonn an fráma ag an teagmháil, ar an mothú, agus ar an gcomhsheasmhacht idir dhá raicéad. Is é príomhbhuntáiste an rialaithe freagairt inathdhéanta i gcoinne sonraíochta dearbhaithe.",
    stiffnessP2: "Sula bhfoilsítear comhréireacht fhíoraithe, ainmníonn an taifead inmheánach rialú cáilíochta an ionstraim, a stádas calabrúcháin, an modh, riocht an raicéid, an taifeach, éiginnteacht an tomhais, na tomhais athdhéanta, an riail slánaithe agus an riail glactha. Ní cruthúnas ar athrú fisiceach nialasach ná ar earráid tomhais nialasach í an tslánuimhir chéanna ar an scáileán.",
    fields: ["Sprioc", "Toradh tomhaiste", "Lamháltas ceadaithe", "Cumas na hionstraime"],
    fieldsNote: "Coinnithe mar réimsí ar leithligh i ngach taifead.",
    matchedTitle: "Tacair mheaitseáilte",
    matchedP: "Sainítear critéir na dtacar meaitseáilte ar leithligh ó lamháltas aonair. Ní chruthaíonn comhréireacht gach raicéid lena lamháltas ainmniúil féin difríocht uasta ar leith idir dhá raicéad. Iarrtar péirí, trírín agus tacair foirne mheaitseáilte tríd an gcumraitheoir agus deimhnítear i scríbhinn iad.",
    extendedTitle: "Samhail theicniúil leathnaithe",
    extendedP: "Tacaíonn an tsamhail sonraí le paraiméadair bhreise. Níl aon luachanna ná aicmí lamháltais ann dóibh go fóill; is féidir iad a lua mar spriocanna iarrtha i gcur síos teicniúil.",
    extended: { twistweight: "Meáchan casta", torsionalBehaviour: "Iompar toirsiúin", length: "Fad", beamProfile: "Próifíl an bhíoma", headGeometry: "Céimseata an chinn", stringPattern: "Patrún sreang", durability: "Buanfas", vibration: "Tréithe creatha" },
    noZero: "Ní dhéanann MAXIMUS cur síos ar a raon liostaithe mar raon gan lamháltas. Luaitear beachtas sa raon mar aicme le lamháltas dearbhaithe agus le hailtireacht shainithe rialú cáilíochta. Ní cuid den raon é ZERO.",
    zero: {
      eyebrow: "Rogha eisiach",
      title: "ZERO",
      sub: "Lamháltas nialasach gram.",
      p: "Coinníonn na trí aicme raicéad críochnaithe laistigh de bhanda dearbhaithe. Baineann ZERO an banda ar shiúl. Tógtar agus tomhaistear an raicéad go dtí go bhfuil an léamh cothrom leis an bhfigiúr dearbhaithe ag taifeach ionstraime na monarchan, agus eisítear an léamh sin leis. Ní cuid den raon liostaithe é agus ní ceathrú aicme é: aontaítear ina aonar é, do raicéad amháin nó do thacar meaitseáilte amháin, mar rogha eisiach shaindéanta. Trí chomhaontú cuirtear an cur chuige céanna i bhfeidhm ar chothromaíocht agus ar mheáchan luasctha.",
      points: [
        ["Gan banda", "Is é an figiúr dearbhaithe an toradh, agus ní lár lamháltais."],
        ["Ceann ag an am", "Tógtha, tomhaiste agus taifeadta mar aonad amháin."],
        ["Eisithe leis an raicéad", "Tugtar an léamh tomhaiste ar láimh agus coinnítear sa taifead táirgthe é."],
        ["Deimhnithe i scríbhinn", "Aontaítear na paraiméadair, an raon feidhme agus an t-am soláthair roimh an táirgeadh."],
      ],
      note: "Meaitseáilte ag taifeach ionstraim tomhais na monarchan. Ní maíomh ar athrú fisiceach nialasach é an figiúr céanna ar an scáileán. Aontaítear an infhaighteacht agus na coinníollacha ina aonar do gach ordú.",
      cta: "Iarr ZERO",
    },
    cta: "Cumraigh le haicme bheachtais",
  },
  grip: {
    title: "Ailtireacht greama ón monarcha",
    statement: "Ocht méid greama ón monarcha. L0–L7.",
    lead: "Is cuid d'ailtireacht an hanla carbóin í céimseata an ghreama. Déantar gach méid mar chéimseata hanla, agus ní thógtar suas le forghreamanna é.",
    emph: "Méideanna leathnaithe",
    p1: "Tugann an raon ocht méid ón monarcha raon cumraíochta níos leithne do chóitseálaithe agus d'imreoirí trínar féidir trealamh a shonrú timpeall ar an imreoir, na céimseatacha L6 agus L7 níos mó san áireamh.",
    p2: "Is rud eile an t-ainmniúchán ainmniúil greama ná toisí struchtúracha an hanla agus ná an prótacal tomhais deiridh. Baineann na méideanna leis na sraitheanna feidhmíochta agus leis na teaghlaigh traenála ar an ardán seo.",
    p3: "Ní dhéantar aon mhaíomh ar eisiachas domhanda don raon seo.",
    columns: { size: "Méid", nominal: "Ainmniúil", family: "Baineann le" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Cumraigh le do mhéid greama",
  },
  custom: {
    title: "Innealtóireacht shaincheaptha",
    statement: "Déanta de réir sonraíochta.",
    sub: "Is túsphointe an raon caighdeánach.",
    lead: "Glacann MAXIMUS le riachtanais theicniúla atá taobh amuigh de na maitrísí cumraíochta foilsithe le haghaidh measúnaithe, innealtóireachta, bailíochtaithe agus déantúsaíochta de réir sonraíochta comhaontaithe. Deimhnítear indéantacht trí athbhreithniú — ní gach iarratas insamhlaithe atá indéanta go fisiceach ná go tráchtála.",
    scopeTitle: "Cad is féidir le cur síos teicniúil a chlúdach",
    scope: ["Céimseata an chinn agus an fhráma", "Fad", "Meáchan", "Cothromaíocht", "Meáchan luasctha", "Righne", "Meáchan casta", "Céimseata an ghreama", "Tógáil", "Tacair mheaitseáilte", "Frámaí traenála", "Cuma agus greanadh", "Aitheantas agus cláir foirne", "Forbairt atá spleách ar uirlisí"],
    processTitle: "An próiseas",
    process: [
      ["Sainigh", "Spriocanna inmhianaithe, teorainneacha éigeantacha, úsáid bheartaithe agus comhbhabhtálacha inghlactha."],
      ["Innealtóireacht", "Measúnú innealtóireachta i gcoinne an ardáin agus na n-uirlisí."],
      ["Bailíochtaigh", "Bailíochtú i gcoinne na sonraíochta comhaontaithe."],
      ["Sonraigh", "Sonraíocht scríofa le bonn tomhais agus lamháltais."],
      ["Déan", "Táirgeadh de réir na sonraíochta."],
      ["Tomhais / taifead", "Tomhas agus taifid choinnithe de réir na haicme beachtais is infheidhme."],
    ],
    formTitle: "Seol cur síos teicniúil",
    formLead: "Déan idirdhealú idir spriocanna inmhianaithe agus teorainneacha éigeantacha. Is iarratas ar athbhreithniú teicniúil an toradh, agus ní ordú déantúsaíochta a nglactar leis go huathoibríoch.",
    protected: "Ní nochtar oidis leagain, uirlisí, céannacht soláthraithe, costáil inmheánach ná saineolas cosanta tríd an mbealach seo.",
    cta: "Seol cur síos teicniúil",
  },
  training: {
    title: "Córais traenála",
    lead: "Dhá theaghlach traenála lena gcaighdeáin táirgthe féin, nasctha ag modheolaíocht amháin: cleachtadh faoi stiúir cóitseálaí, taifid, athmheasúnú agus aistriú ar ais chuig imirt feidhmíochta.",
    sst: { h: "Sweet Spot Trainer", p: "Raicéad traenála le ceann laghdaithe 50 in² i gcóras ceithre mheáchan do chleachtadh teagmhála sa lár, feasacht ar an áit is fearr ar an gceann, smacht raicéid agus ualach céimnithe." },
    spot: { h: "Spot Trainer", p: "Traenáil ar an bpointe teagmhála le sprioc bheag chruinn, ar bhonn ceadaithe na gceithre mheáchan." },
    method: { h: "Modheolaíocht", p: "Socraigh cuspóirí, roghnaigh trealamh le páirt an chóitseálaí, úsáid an córas cuí, taifead, athmheas, coigeartaigh agus aistrigh." },
    experience: "Beir air. Luasc é. Braith é.",
    experienceP: "Iarr tástáil, feistiú nó taispeántas le tacaíocht cóitseálaí. Ní coinne dheimhnithe é iarratas a cuireadh isteach.",
    cta: "Iarr feistiú nó taispeántas",
    distinct: "Is táirgí ar leith iad Sweet Spot Trainer, Spot Trainer agus aon ghléas taispeántais ar leith, agus ní chumasctar riamh iad.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Catagóir traenála ar leith lena caighdeán táirgthe féin. Díríonn an ceann 50 in² an aird ar shuíomh na teagmhála; tugann na ceithre mheáchan an dul chun cinn ualaigh.",
    baseline: "Bonnlíne dheimhnithe",
    columns: { head: "Ceann", length: "Fad", pattern: "Patrún sreang", grips: "Greamanna ón monarcha" },
    systemTitle: "Córas ceithre raicéad",
    detailsTitle: "Mionsonraí tógála",
    systemLead: "Meáchan agus cothromaíocht mar a sholáthraítear iad. Taifeadtar bonn an tomhais ar leithligh agus níl sé foilsithe go fóill.",
    purposeTitle: "Cuspóir",
    purpose: ["Cleachtadh teagmhála sa lár", "Feasacht ar an áit is fearr ar an gceann", "Smacht raicéid", "Ualach céimnithe", "Forbairt faoi stiúir cóitseálaí", "Aistriú ar ais chuig raicéad feidhmíochta an imreora"],
    heavy: "Is cumraíocht traenála rialaithe í an tsamhail 400 g. Ní mholtar go huathoibríoch do pháistí, do thosaitheoirí ná do gach imreoir í; socraíonn an cóitseálaí an t-ualach, an fad agus an dul chun cinn.",
    precisionNote: "Ní chuirtear aicmí beachtais na feidhmíochta P2.5, P1.5 agus P0.5 i bhfeidhm go huathoibríoch ar an teaghlach traenála seo. Leanann lamháltais tháirgthe na traenála sonraíocht cheadaithe an teaghlaigh féin.",
    health: "Ní ghealltar cosc ná cóireáil ar uillinn leadóige, deireadh a chur le gortuithe ná feabhas ráthaithe.",
    cta: "Iarr taispeántas ar Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Traenáil ar an bpointe teagmhála le sprioc bheag chruinn. Táirge ar leith lena chéannacht amhairc féin, tógtha ar bhonn ceadaithe na gceithre mheáchan.",
    purposeTitle: "Cuspóir deimhnithe",
    purposeP: "An t-imreoir a thraenáil chun pointe teagmhála beacht a aimsiú agus a athdhéanamh.",
    weightsTitle: "Dul chun cinn meáchain",
    weightsP: "Leanann an dul chun cinn meáchain bonn meáchain ceadaithe Sweet Spot Trainer. Ní chóipeáiltear luachanna cothromaíochta ná sonraíochtaí eile Sweet Spot Trainer anonn chuig Spot Trainer.",
    dims: "Níl toisí beachta na sprice foilsithe go fóill.",
    grips: "Ailtireacht greama ón monarcha L0–L7.",
    notes: ["Ní chuirtear aicmí beachtais na feidhmíochta i bhfeidhm go huathoibríoch.", "Ní raicéad gnách ar scála beag é agus níl aon phatrún sreang foilsithe.", "Fanann Spot Trainer, Sweet Spot Trainer agus aon ghléas taispeántais ar leith inaitheanta óna chéile."],
    cta: "Cuir ceist faoi Spot Trainer",
  },
  methodology: {
    title: "Modheolaíocht agus taithí ar an táirge",
    lead: "Níl sa trealamh ach cuid d'aistear forbartha struchtúrtha. Tosaíonn an modh le cuspóirí an imreora, agus ní le lipéad táirge.",
    stepsTitle: "An t-aistear forbartha",
    steps: [
      ["Socraigh cuspóirí", "Cuspóirí an imreora agus an pointe tosaigh."],
      ["Roghnaigh trealamh", "Trealamh oiriúnach roghnaithe le páirt an chóitseálaí."],
      ["Úsáid an córas", "An córas traenála cuí, faoi stiúir cóitseálaí."],
      ["Taifead", "Breathnuithe ar an rannpháirtíocht iarbhír, gan scóir a chumadh."],
      ["Athmheas", "Seicphointí inchomparáide."],
      ["Coigeartaigh", "Coigeartuithe ar an gcumraíocht nó ar an gclár."],
      ["Aistrigh", "An fhoghlaim aistrithe ar ais chuig imirt feidhmíochta."],
    ],
    educationTitle: "Bealaí oideachais",
    education: { player: "Imreoirí — tuiscint ar an gcumraíocht, ar an ualach agus ar an dul chun cinn.", parent: "Tuismitheoirí — leanúnachas forbartha, trealamh oiriúnach, taifid agus cearta.", coach: "Cóitseálaithe — córais traenála, feistiú, measúnú agus úsáid údaraithe clár." },
    evidenceTitle: "Araíonacht fianaise",
    evidenceP: "Caomhnaítear taifid ar an rannpháirtíocht iarbhír agus breathnuithe lena n-aicmiú — dearbhaithe ag an rannpháirtí, deimhnithe ag an gcaomhnóir, bailíochtaithe ag an gcóitseálaí nó tomhaiste ag an gcóras. Ní chumtar dul chun cinn, scóir ná bailíochtú riamh.",
    experienceTitle: "Beir air. Luasc é. Braith é.",
    experienceP: "Is féidir tástáil, feistiú nó taispeántas le tacaíocht cóitseálaí a iarraidh. Ní coinne dheimhnithe é iarratas a cuireadh isteach.",
    cta: "Iarr feistiú nó taispeántas",
    cta2: "Fiosrúchán faoi chomhpháirtíocht cóitseálaí",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — próifíl threoraithe trealaimh",
    title: "MAXIMUS GPS",
    lead: "Próifíl threoraithe trealaimh. Freagair an méid atá ábhartha amháin; déan athbhreithniú ar do fhreagraí agus ceartaigh iad; faigh achoimre, na treonna cumraíochta a bhaineann leat agus fíorghníomh eile.",
    honesty: "Níl aon rialacha feistithe uathoibríocha ceadaithe san eisiúint seo. Mar sin, cruthaíonn GPS achoimre shoiléir ar na riachtanais agus díríonn sé ar threonna cumraíochta; cuirtear sonraí an trealaimh chuig athbhreithniú saineolaí.",
    rulesVersion: "Leagan na rialacha",
    dataVersion: "Leagan shonraí na dtáirgí",
    steps: { role: "Ról", sport: "Spórt", experience: "Taithí", objectives: "Cuspóirí", style: "Stíl imeartha", equipment: "Trealamh reatha", preference: "Roghanna", coach: "Páirt an chóitseálaí", ageBand: "Banda aoise", review: "Athbhreithniú" },
    notStored: "Ní stóráiltear sa bhrabhsálaí seo é.",
    ageNote: "Ní úsáidtear é ach chun an t-iarratas a sheoladh ar aghaidh. Ní iarrtar ainm, dáta breithe ná faisnéis leighis.",
    q: {
      role: "Cé acu a dhéanann cur síos ort?",
      sport: "Cén spórt?",
      experience: "Leibhéal taithí",
      objectives: "Cad is tábhachtaí? (roghnaigh suas le trí cinn)",
      style: "Stíl imeartha, má tá sí ar eolas",
      equipment: "Trealamh reatha, más ann dó",
      equipmentHint: "Branda agus samhail, meáchan nó greim má tá siad ar eolas agat. Roghnach.",
      preference: "An chumraíocht is fearr leat nó méid greama atá ar eolas",
      grip: "Méid greama atá ar eolas",
      coach: "An bhfuil cóitseálaí páirteach i do chinntí faoi threalamh?",
      ageBand: "Banda aoise an imreora (ní úsáidtear é ach chun an t-iarratas a sheoladh ar aghaidh mar is cuí)",
    },
    roles: { player: "Imreoir", parent: "Tuismitheoir nó caomhnóir", coach: "Cóitseálaí", club: "Club nó acadamh", other: "Eile" },
    sports: { tennis: "Leadóg", padel: "Padal", pickleball: "Pickleball", squash: "Scuais", badminton: "Badmantan", other: "Spórt raicéid eile" },
    sportNote: "Tá táirgí ann don leadóg. Is treonna forbartha na spóirt eile; taifeadtar do shuim don chlár cuí.",
    experience: { beginner: "Tosaitheoir", developing: "Ag forbairt", intermediate: "Meánleibhéal", advanced: "Ardleibhéal", competitive: "Iomaíoch", professional: "Gairmiúil" },
    objectives: { control: "Smacht", power: "Cumhacht", spin: "Casadh", comfort: "Compord", manoeuvrability: "Inláimhsitheacht", development: "Forbairt fhadtéarmach", competition: "Comórtas", training: "Córas traenála", team: "Foireann nó tacar meaitseáilte", personal: "Pearsantú" },
    styles: { baseline: "Bunlíne", allcourt: "An chúirt ar fad", attacking: "Ionsaitheach", defensive: "Cosantach", coach: "Roghnaithe ag an gcóitseálaí", unknown: "Nílim cinnte" },
    ageBands: { u10: "Faoi bhun 10", u14: "10–13", u18: "14–17", adult: "18 agus os a chionn" },
    output: {
      title: "Do phróifíl trealaimh",
      status: "Athbhreithniú saineolaí riachtanach",
      statusP: "Ní chruthaítear meaitseáil uathoibríoch san eisiúint seo. Rinneadh achoimre ar do phróifíl le haghaidh athbhreithnithe saineolaí.",
      directionsTitle: "Treonna cumraíochta a bhaineann leat",
      directionsP: "Bunaithe ar na cuspóirí a luaigh tú agus ar threo imeartha dearbhaithe gach sraithe. Is treo é seo, agus ní moladh feistithe.",
      trainingHint: "Áirítear córas traenála i do chuspóirí: féach ar Sweet Spot Trainer agus Spot Trainer.",
      teamHint: "Iarrtar tacair mheaitseáilte tríd an gcumraitheoir agus deimhnítear i scríbhinn iad.",
      next1: "Seol an phróifíl le haghaidh athbhreithnithe saineolaí",
      show: "Taispeáin mo phróifíl",
      configure: "Cumraigh",
      sendP: "Seol do phróifíl chuig MAXIMUS le haghaidh athbhreithnithe saineolaí. Taispeántar aitheantas iarratais láithreach; tagann an freagra i scríbhinn.",
      otherSport: "Tá raicéid MAXIMUS ann don leadóg. Do spóirt raicéid eile ní mholtar aon sraith leadóige; taifeadtar do shuim mar threo forbartha.",
      noDirection: "Ní dhíríonn do chuspóirí ar aon treo imeartha amháin. Molann an t-athbhreithniú saineolaí cumraíocht.",
      incomplete: "Tá roinnt freagraí riachtanacha in easnamh — bain úsáid as “Freagraí a athrú” chun iad a chríochnú.",
    },
    privacy: "Ní iarrann GPS faisnéis sláinte ná aitheantóirí leanaí. Ní choinnítear ach freagraí ilrogha sa seisiún brabhsálaí seo; ní stóráiltear téacs saor.",
  },
  build: {
    title: "Tóg do cheann féin",
    lead: "Cumraigh iarratas: sraith, aicme bheachtais, meáchan liostaithe nó sprioc shaincheaptha, méid greama, spriocanna iarrtha, pearsantú, tacair mheaitseáilte agus cainníocht. Is iarratas cumraíochta le haitheantas iarratais an toradh — ní SKU, ní praghas, ní dáta seachadta ná ní teastas.",
    steps: { series: "Sraith", cls: "Aicme bheachtais", weight: "Meáchan", grip: "Greim", targets: "Spriocanna", personal: "Pearsantú", set: "Tacar agus cainníocht", use: "Úsáid", review: "Athbhreithniú" },
    q: {
      series: "Roghnaigh sraith",
      cls: "Roghnaigh aicme bheachtais",
      weightMode: "Meáchan",
      listed: "Meáchan liostaithe",
      customWeight: "Meáchan iarrtha (g)",
      balanceShown: "Cothromaíocht ríofa don mheáchan seo",
      balanceRequest: "Cothromaíocht iarrtha (mm)",
      grip: "Méid greama ón monarcha",
      targetsTitle: "Spriocanna iarrtha",
      swingweight: "Meáchan luasctha iarrtha (kg·cm²)",
      stiffness: "Righne iarrtha (RA)",
      basis: "Bonn tomhais na luachanna iarrtha",
      engraving: "Téacs greanta",
      engravingHint: "Ainm, ceannlitreacha nó uimhir. Litreacha Laidine, digití, spás, fleiscín, uaschamóg agus lánstad; suas le 24 carachtar. Glactar le scripteanna eile le haghaidh deimhnithe na hoibre ealaíne.",
      engravingType: "Pearsantú",
      types: { none: "Gan ceann", name: "Ainm an imreora", initials: "Ceannlitreacha", number: "Uimhir an tacair", academy: "Aitheantas cóitseálaí nó acadaimh", team: "Clár foirne" },
      set: "Raicéad aonair nó tacar meaitseáilte",
      use: "Úsáid bheartaithe",
      uses: { play: "Imirt phearsanta", competition: "Comórtas", coaching: "Cóitseáil", team: "Foireann nó acadamh", retail: "Measúnú miondíola nó dáilte", other: "Eile" },
      notes: "Riachtanais theicniúla bhreise",
    },
    classes: { "P2.5": "P2.5 — croí feidhmíochta inscálaithe", "P1.5": "P1.5 — beachtas ardleibhéil", "P0.5": "P0.5 — gairmiúil, rialaithe ina aonar" },
    stiffExactShort: "comhlíonann an righne an sprioc RA dhearbhaithe faoi phrótacal bunaithe na monarchan",
    clsNote: "Rialaíonn gach aicme ceithre pharaiméadar. Is lamháltas docht é P0.5 faoi phrótacal tomhais sainithe — ní earráid nialasach. Ní bhaineann céannacht shraithuimhreach, teastais ná doiciméadú tacair mheaitseáilte ach nuair a chuireann clár d'ordaithe i bhfeidhm iad.",
    listedNote: "Ó mhaitrís dheimhnithe na sraithe.",
    customNote: "Meáchan taobh amuigh den mhaitrís, a ndéantar athbhreithniú teicniúil air.",
    balanceCaption: "Taispeánann gach meáchan liostaithe a chothromaíocht ríofa i mm ón tóin. Ní tomhais aonair na luachanna ríofa.",
    spinNote: "Is ailtireacht meáchain iarrtha a chruthaíonn meáchain SPIN. Níl cothromaíocht, meáchan luasctha ná righne do SPIN soláthraithe; sainítear iad i rith athbhreithnithe theicniúil.",
    customHint: "Graim iomlána, digití amháin. Is iarratas ar athbhreithniú teicniúil meáchan saincheaptha; deimhnítear an indéantacht i scríbhinn agus ní shlánaítear aon luach.",
    gripNote: "céimseata hanla carbóin ón monarcha, agus ní forghreim atá tógtha suas",
    targetsLead: "Roghnach. Cuir isteach na luachanna atá uait amháin. Taifeadtar gach ceann mar sprioc iarrtha le haghaidh athbhreithnithe theicniúil, agus ní mar shonraíocht fhoilsithe.",
    basisHint: "Riachtanach nuair a iarrann tú meáchan saincheaptha nó aon sprioc: an mbaineann na luachanna le raicéad gan sreangú nó le raicéad sreangaithe?",
    inputRange: "Ionchur a ghlactar: {min}–{max}.",
    inputRangeNote: "Ní dhéanann raonta ionchuir ach iontrálacha dodhéanta a scagadh amach. Ní dhéanann siad cur síos ar chumas táirgthe.",
    listedBasis: "luachanna liostaithe — bonn tomhais deimhnithe sa sonraíocht scríofa",
    notStored: "Ní stóráiltear sa bhrabhsálaí seo é; cuir isteach arís é má athlódálann tú an leathanach.",
    artworkReview: "deimhniú na hoibre ealaíne riachtanach",
    previewNote: "Ní thaispeántar aon réamhamharc: níl teimpléad greanta ceadaithe don tsamhail seo foilsithe go fóill. Bailítear do théacs le haghaidh deimhnithe na hoibre ealaíne.",
    teamSub: "4–99 raicéad sa tacar",
    setsLabel: { individual: "Líon raicéad", pair: "Líon péirí meaitseáilte", triple: "Líon trírín meaitseáilte", team: "Líon tacar foirne" },
    teamSizeLabel: "Raicéid in aghaidh gach tacar foirne",
    totalLabel: "Raicéid san iomlán",
    racquetsUnit: "raicéid",
    setRule: "Comhaireamh tacar atá sa chainníocht: is 2 raicéad sa tacar péire meaitseáilte, agus is 3 trírín meaitseáilte.",
    restart: "Tosaigh cumraíocht nua",
    notices: { weightCleared: "Níl {w} g i maitrís {series}, mar sin glanadh an meáchan. Roghnaigh meáchan liostaithe nó iarr sprioc shaincheaptha." },
    reviewTitle: "Iarratas cumraíochta",
    reviewP: "Seiceáil an chumraíocht, agus cuir do shonraí teagmhála leis ansin. Stóráiltear an iarratas le haitheantas iarratais agus freagraítear i scríbhinn é; deimhnítear an infhaighteacht agus na téarmaí tráchtála i scríbhinn.",
    reviewErrors: "Tá roinnt freagraí cumraíochta a dteastaíonn aird orthu:",
    edit: "Athraigh",
    fieldNames: { series: "Sraith", cls: "Aicme bheachtais", mode: "Roghnú meáchain", weight: "Meáchan liostaithe", customWeight: "Meáchan iarrtha", basis: "Bonn tomhais", balanceReq: "Cothromaíocht iarrtha", sw: "Meáchan luasctha iarrtha", ra: "Righne iarrtha", grip: "Méid greama", ptype: "Pearsantú", engraving: "Téacs greanta", setType: "Cineál tacair", sets: "Cainníocht", teamSize: "Raicéid in aghaidh gach tacar foirne", use: "Úsáid bheartaithe", notes: "Riachtanais bhreise" },
    status: { listed: "meáchan liostaithe", requestedArchitecture: "ailtireacht meáchain iarrtha", technicalReview: "iarratas ar athbhreithniú teicniúil", notPublished: "níor soláthraíodh", requestedCondition: "riocht iarrtha" },
    chooseLink: "Nach bhfuil tú cinnte cén tsraith a oireann? Faigh cabhair le roghnú",
    cta: "Cuir an iarratas cumraíochta isteach",
  },
  experience: {
    title: "Triail agus feistiú",
    statement: "Beir air. Luasc é. Braith é.",
    lead: "Iarr tástáil, feistiú nó taispeántas le tacaíocht cóitseálaí. Déantar athbhreithniú ar na hiarratais agus freagraítear i scríbhinn iad; ní coinne dheimhnithe é iarratas a cuireadh isteach.",
    optionsTitle: "Cad is féidir a iarraidh",
    options: ["Tástáil raicéid", "Seisiún feistithe", "Taispeántas le tacaíocht cóitseálaí", "Taispeántas ar Sweet Spot Trainer nó Spot Trainer", "Lá taispeána don fhoireann nó don acadamh"],
    formTitle: "Iarratas ar fheistiú nó ar thaispeántas",
  },
  engineering: {
    title: "Innealtóireacht agus déantúsaíocht",
    statement: "Aerárthaí. Luamha. Raicéid.",
    lead: "Fealsúnacht innealtóireachta amháin i dtrí thimpeallacht: na prionsabail a mhúnlaíonn aerárthach, an beachtas a threoraíonn luamh trí uisce oscailte, an fheidhmíocht a shainíonn gach raicéad MAXIMUS. Insint innealtóireachta — agus ní maíomh ar dheimhniúchán aerárthaí, ar úinéireacht luamh, ar úinéireacht monarchan ná ar aistriú ábhair go díreach.",
    manifesto: ["Creidimid nach bhfuil teorainn le sárinnealtóireacht.", "Fealsúnacht amháin. Déanta gan chomhréiteach."],
    capabilityTitle: "Cumas déantúsaíochta",
    capabilityLead: "Taispeántar an cumas mar sheicheamh, agus ní mar mhana.",
    sequence: [
      ["Sonraíocht", "Sraith, aicme bheachtais, meáchan, cothromaíocht, meáchan luasctha, sprioc righne, céimseata greama, pearsantú."],
      ["Táirgeadh", "Tógáil go hiomlán as carbón ón bhfráma go dtí an hanla, déanta de réir na sonraíochta."],
      ["Rialú cáilíochta", "Tomhas agus taifid de réir aicme beachtais: taifid táirgthe, taifid aonair agus inrianaitheacht, deimhniúchán aonair."],
      ["Aththáirgeadh", "Freagairt inathdhéanta i gcoinne sonraíochta dearbhaithe thar bhaisceanna."],
      ["Inrianaitheacht", "Céannacht shraithuimhreach, inrianaitheacht baisce agus Teastas Beachtais nuair a chuireann an aicme ar fáil é."],
    ],
    capacityNote: "Deimhnítear cumas táirgthe, amanna soláthair, cainníochtaí íosta agus sceidil seachadta i scríbhinn de réir cláir i gcoinne orduithe deimhnithe agus sceidil eisiúna chomhaontaithe.",
    truth: "Ní aschur, ní stoc, ní dáta seachadta ráthaithe ná ní úinéireacht ar áis déantúsaíochta é cumas.",
    cta: "Dáileadh agus forbairt tíre",
    cta2: "Seol cur síos teicniúil",
  },
  ecosystem: {
    title: "Éiceachóras MAXIMUS",
    lead: "Aon eochair. Seo an rud a osclaíonn sí. Tá míniú, fíorstádas agus an chéad ghníomh cuí eile ag gach nód.",
    words: ["Innealtóireacht", "Feidhmíocht", "Nuálaíocht", "Pobal", "Deis", "Cuspóir"],
    nodes: {
      engineering: { h: "Innealtóireacht agus déantúsaíocht raicéad", p: "Raicéid go hiomlán as carbón déanta de réir sonraíochta, táirgthe le taifid cháilíochta agus inrianaitheacht.", a: "Innealtóireacht agus déantúsaíocht" },
      precision: { h: "Beachtas agus cumraíocht aonair", p: "Ceithre pharaiméadar, trí aicme bheachtais, ocht méid greama agus innealtóireacht shaincheaptha.", a: "Beachtas agus righne" },
      training: { h: "Traenáil agus modheolaíocht", p: "Sweet Spot Trainer, Spot Trainer agus aistear forbartha struchtúrtha.", a: "Córais traenála" },
      development: { h: "Forbairt imreoirí agus cóitseálaithe", p: "Roghnú faoi stiúir cóitseálaí, taifid, athmheasúnú agus bealaí oideachais.", a: "Modheolaíocht" },
      identity: { h: "Céannacht phearsanta agus brandaí pearsanta", p: "Ón ngreanadh go branda pearsanta nó gairmiúil a rialaítear le cearta.", a: "Brandaí pearsanta" },
      owners: { h: "Taifid úinéirí, eolas agus cearta", p: "Taisceadán úinéara ceadbhunaithe atá beartaithe do thaifid trealaimh, forbartha agus ceart.", a: "Úinéirí agus an taisceadán" },
      mipa: { h: "MIPA — bunús ábhair agus rialú inmheánach", p: "An ciseal inmheánach do mhaoin intleachtúil, do bhunús ábhair agus do rialú doiciméad.", a: "Céannacht dhlíthiúil agus rialú" },
      digital: { h: "Bonneagar digiteach agus treo Blockchain 5.0", p: "Bunús ábhair, taifid inrianaithe, fianaise cheadbhunaithe agus céannacht táirge mar an treo teicneolaíochta a luaitear.", a: "Treo teicneolaíochta" },
      licensing: { h: "Ceadúnú conarthach agus cláir ríchíosa", p: "Brandaí, táirgí agus pacáistí ceart faoi cheadúnas le téarmaí sainithe in aghaidh gach comhaontaithe.", a: "Bealaí ceadúnaithe" },
      families: { h: "Rannpháirtíocht teaghlaigh agus buntáistí clár", p: "Cinntí eolasacha, leanúnachas, taifid chaomhnaithe agus buntáistí a shainíonn clár.", a: "Teaghlaigh agus tuismitheoirí" },
      network: { h: "MAXIMUS Sports Network", p: "Imreoirí, cóitseálaithe, clubanna, acadaimh, soláthraithe seirbhíse, oibreoirí agus comhpháirtithe réigiúnacha.", a: "Sports Network" },
      market: { h: "Clubanna, acadaimh, dáileadh agus forbairt tíre", p: "Cláir foirne, miondíol, dáileadh agus forbairt críche trí cháiliú i scríbhinn.", a: "Bealaí comhpháirtíochta" },
      institutional: { h: "Cláir institiúideacha, oideachas, nuálaíocht agus tionchar sóisialta", p: "An ciseal institiúideach a sholáthraíonn MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) nuair a bhunaíonn clár an ról sin.", a: "Cláir institiúideacha" },
      extensions: { h: "Leathnuithe amach anseo i spóirt raicéad agus in éadaí MAXIMUS", p: "Padal, pickleball, scuais, badmantan, racquetball, leadóg trá agus éadaí mar threonna forbartha.", a: "Spóirt raicéad" },
    },
    boundaryTitle: "Teorainneacha",
    boundary: [
      "Ní chruthaíonn ceannach raicéid ballraíocht institiúideach, cearta rialachais, ríchíosanna ná cearta infheistíochta.",
      "Is é MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) an oibreoir institiúideach nuair a bhunaíonn clár an ról sin amháin; ainmníonn díolacháin trealaimh an t-aonán conarthach iarbhír.",
      "Ní bhaineann deontais, stádas carthanúil, cóireáil chánach ná ceadanna rialála go huathoibríoch thar thíortha.",
    ],
    techTitle: "Treo teicneolaíochta",
    techP: "Is é Blockchain 5.0 an treo teicneolaíochta a luann MAXIMUS. Is éard atá mar fheidhmeanna aige bunús ábhair, taifid inrianaithe, fianaise cheadbhunaithe, céannacht táirge agus réiteach imeachtaí tráchtála incháilithe. Ní dhéantar ionadaíocht ar aon sásra comhthola, ar acmhainn idirbheart, ar líonra nód, ar sheoladh conartha chliste, ar chomhartha ná ar dheimhniúchán neamhspleách, agus ní mhaítear aon chur i bhfeidhm imlonnaithe. Ní chuirtear faisnéis phearsanta, taifid leanaí ná comhaontuithe faoi rún i gcóras poiblí dochlaonta mar réamhshocrú riamh.",
  },
  brands: {
    title: "Brandaí pearsanta agus ambasadóirí",
    statement: "Ón imreoir go branda. Ón gcóitseálaí go branda.",
    lead: "Bealach tiomnaithe chuig branda pearsanta. Áirítear forbairt branda agus cur chun cinn comhaontaithe i rannpháirtíocht MAXIMUS — agus ní hé amháin ainm ar raicéad.",
    progressionTitle: "An dul chun cinn beartaithe",
    progression: [
      ["Céannacht fhíoraithe", "Céannacht fhíoraithe agus stair forbartha."],
      ["Branda sainiúil", "Branda pearsanta nó gairmiúil sainiúil."],
      ["Inneachar le cearta glanta", "Inneachar le cearta glanta agus céannacht táirge cheadaithe."],
      ["Innealtóireacht agus bailiúcháin", "Innealtóireacht agus forbairt bailiúcháin nuair a aontaítear é."],
      ["Cur chun cinn", "Cur chun cinn trí bhealaí agus trí chomhpháirtíochtaí comhaontaithe MAXIMUS."],
      ["Rannpháirtíocht", "Rannpháirtíocht chonarthach i ndíolacháin nó i gceadúnú incháilithe."],
      ["Tuairisciú", "Tuairisciú trédhearcach faoin gcomhaontú."],
    ],
    royaltiesTitle: "Ríchíosanna agus ceadúnú",
    royalties: [
      "Baineann ríchíosanna leis an mbranda, leis an táirge, leis an idirbheart nó leis an bpacáiste ceart ceadúnaithe atá sainithe.",
      "Ciallaíonn “díolacháin dhomhanda” díolacháin incháilithe laistigh de raon feidhme an chonartha — agus ní gach raicéad MAXIMUS neamhghaolmhar.",
      "Sainítear rátaí, bonn ríofa, críocha, téarma, aisíocaíochtaí, asbhaintí, tuairisciú, socrú agus fíorú tríd an gcomhaontú cuí. Ní fhoilsítear aon chéatadán ríchíosa réamhshocraithe.",
      "Ní ghealltar aon fheachtas domhanda, buiséad meán, toradh urraíochta ná rath tráchtála gan raon feidhme comhaontaithe.",
    ],
    cta: "Cuir fiosrúchán comhoibrithe branda isteach",
    cta2: "Fiosrúchán faoi chomhpháirtíocht cóitseálaí",
  },
  families: {
    title: "Teaghlaigh agus tuismitheoirí",
    lead: "Cinntí eolasacha faoi threalamh, leanúnachas forbartha, eolas agus cearta caomhnaithe, léargas ar an rannpháirtíocht, agus buntáistí a shainíonn clár agus a fhéadfaidh tacú le gníomhaíocht amach anseo.",
    nowTitle: "Ar fáil anois",
    now: ["Fiosrúcháin teaghlaigh agus forbartha i scríbhinn.", "Roghnú trealaimh le páirt an chóitseálaí, feistiú agus iarratais ar thaispeántas.", "Taifid phríobháideacha: ní fhoilsítear próifílí leanaí riamh agus ní dhéantar tráchtálú orthu mar réamhshocrú.", "Bealach oideachais do thuismitheoirí: cumraíocht, ualach, dul chun cinn, taifid agus cearta."],
    plannedTitle: "Beartaithe",
    planned: ["Buntáistí rannpháirtíochta a shainíonn clár agus is féidir a úsáid le haghaidh earraí agus seirbhísí laistigh den éiceachóras, in ionad úis in airgead tirim.", "Taifid úinéirí agus teaghlaigh sa taisceadán úinéara atá beartaithe, le ceadanna caomhnóra agus aistriú rialaithe ag 18 mbliana d'aois."],
    categoriesTitle: "Coinnithe ar leithligh",
    categories: ["Ríchíosanna conarthacha a eascraíonn as cearta ceadúnaithe nó as díolacháin incháilithe", "Buntáistí rannpháirtíochta a shainíonn clár", "Creidmheasanna ceannaigh nó seirbhíse", "Réamhíocaíochtaí", "Ballraíocht institiúideach"],
    categoriesP: "Ní dhéileáiltear riamh leis na catagóirí seo mar chatagóirí inmhalartaithe.",
    statusTitle: "Fíorstádas chlár na dteaghlach",
    journeyTitle: "Bealach an teaghlaigh",
    journey: [
      ["Sprioc", "An rud atá an imreoir ag iarraidh a bhaint amach ina dhiaidh seo."],
      ["An leibhéal reatha", "Cá bhfuil an imreoir inniu."],
      ["Cóitseálaí", "Cé acu a bhfuil cóitseálaí páirteach i gcinntí faoi threalamh."],
      ["Trealamh", "Trealamh oiriúnach don chéim, lena n-áirítear córais traenála nuair is cuí."],
      ["Cleachtadh comhaontaithe", "Úsáid faoi stiúir cóitseálaí a aontaítear roimh ré."],
      ["Athbhreithniú", "Athmheasúnú ag seicphointí inchomparáide."],
    ],
    brief: {
      who: "Tuismitheoirí agus caomhnóirí imreoirí ag aon chéim.",
      value: "Freagra i scríbhinn ar threalamh oiriúnach, ar pháirt an chóitseálaí agus ar an gcéad chéim forbartha eile.",
      now: "Fiosrúcháin teaghlaigh i scríbhinn; roghnú le páirt an chóitseálaí; taifid phríobháideacha — ní fhoilsítear próifílí leanaí riamh.",
      next: "Cuir fiosrúchán an teaghlaigh isteach thíos. Gheobhaidh tú aitheantas iarratais láithreach.",
    },
    formTitle: "Fiosrúchán teaghlaigh",
    formNote: "Tuismitheoir nó caomhnóir a líonfaidh isteach é. Ná cuir ainm, dáta breithe, scoil ná faisnéis leighis an linbh san áireamh.",
    noPromise: "Ní ghealltar ríchíosanna, torthaí infheistíochta, urraíocht ná maoiniú ar fhorbairt linbh le ceannach.",
    statusP: "Míníonn an eisiúint seo an tsamhail agus glacann sí le fiosrúcháin faoin gclár. Níl fabhrú, íocaíochtaí ná fuascailt ar fáil go dtí go mbeidh na himeachtaí incháilithe, na tairbhithe, foinse an mhaoiniúcháin, an bonn ríofa, na húsáidí ceadaithe, an chóireáil chuntasaíochta, aisíocaíochtaí, aisiompuithe, dul in éag, inaistritheacht, dúnadh an chláir agus láimhseáil díospóidí sainithe i scríbhinn. Ní ghealltar go dtitfidh aon iarmhéid riamh, ní íocann aon rannpháirtíocht as an traenáil ar fad, agus ní thugtar cosaint chaipitil le fios.",
    cta: "Cuir fiosrúchán teaghlaigh nó forbartha isteach",
  },
  owners: {
    title: "Úinéirí agus taisceadán an úinéara",
    lead: "Is taifead ceadbhunaithe beartaithe ar threalamh, ar fhorbairt, ar eolas, ar inneachar agus ar chearta doiciméadaithe é taisceadán an úinéara. Cuirtear i láthair é mar chuid den ailtireacht úinéirí atá beartaithe: ní thaispeántar aon chuntais, iarmhéideanna, teastais ná gaiscí beo.",
    nowTitle: "Do na húinéirí reatha anois",
    now: ["Fiosrúcháin úinéirí: tagairt táirge nó sraithuimhreach, socrú, seirbhís agus iarratais ar thaifid, i scríbhinn.", "Teastas Beachtais agus doiciméadú tacair mheaitseáilte nuair a chuireann an aicme bheachtais ar fáil é, seachadta leis an táirge."],
    archTitle: "Ailtireacht bheartaithe an taisceadáin",
    arch: ["Céannacht táirge agus tagairtí sraithuimhreacha", "Cumraíocht agus teastais rialú cáilíochta is infheidhme", "Stair seirbhíse agus socraithe", "Taifid forbartha imreora nó cóitseálaí", "Cáilíochtaí agus gaiscí fíoraithe", "Meáin le cearta glanta agus ábhair údaraithe", "Ceadúnais, ceadanna agus tagairtí conartha", "Taifid chláir na mbrandaí pearsanta", "Ráitis ríchíosa nó buntáistí rannpháirtíochta is infheidhme"],
    separationTitle: "Cad is úinéireacht ann",
    separation: [
      "Is rud eile úinéireacht ar raicéad fisiceach ná úinéireacht ar chóipcheart, ar cheadúnas, ar theideal conarthach nó ar thaifead a dhéanann cur síos ar na nithe sin.",
      "Ní cruthúnas uathoibríoch é doiciméad stóráilte ná iontráil bhlocshlabhra go bhfuil ceart dlíthiúil ann nó go bhfuil sé aistrithe.",
      "Coinníonn an fhianaise a aicmiú: dearbhaithe ag an rannpháirtí, deimhnithe ag an gcaomhnóir, bailíochtaithe ag an gcóitseálaí, tomhaiste ag an gcóras.",
      "I gcás mionaoiseach: taifid phríobháideacha, ceadanna caomhnóra, gan próifílí leanaí foilsithe agus gan tráchtálú na céannachta mar réamhshocrú.",
      "Is cuid den dearadh easpórtáil, ceartú, rialú rochtana agus aistriú cuí rialaithe.",
    ],
    techTitle: "Blockchain 5.0 agus MxSN",
    techP: "Is é Blockchain 5.0 an treo teicneolaíochta a luaitear; sainíonn MxSN coincheapa líonra cheadbhunaithe do thoiliú, do sheachadadh, do fhianaise, do chearta agus do thuairisciú. Ní dhéantar ionadaíocht ar chur i bhfeidhm oibríochtúil. Tá samhail sonraí an fheidhmchláir tógtha chun comhtháthú níos déanaí trí chomhéadan doiciméadaithe, gan a ligean orainn go bhfuil ceangal ann inniu.",
    cta: "Fiosrúchán úinéara",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "An ceangal idir imreoirí, cóitseálaithe, clubanna, acadaimh, soláthraithe seirbhíse, oibreoirí clár agus comhpháirtithe réigiúnacha.",
    functionsTitle: "Feidhmeanna féideartha",
    functions: ["Fionnachtain", "Cur in aithne", "Cláir forbartha", "Tacaíocht trealaimh", "Imeachtaí", "Rochtain ar sheirbhísí", "Deiseanna comhpháirtíochta"],
    statusTitle: "An fíorstádas",
    statusP: "Níl aon eolaire poiblí foilsithe go fóill: ní liostófar ach rannpháirtithe a bhfuil a gcéannacht, a gcaidreamh agus a gcead chun bheith le feiceáil bunaithe. Ní comhpháirtíocht togra a sheoltar chuig club, agus ní dáileoir ceaptha dáileoir ionchasach. Rialaítear foilsiú an eolaire, áirithintí, teachtaireachtaí agus idirbhearta tráchtála ar leithligh agus níl siad beo.",
    cta: "Déan iarratas ar an líonra",
  },
  partnerships: {
    title: "Bealaí comhpháirtíochta",
    lead: "Cáiliú i scríbhinn ar dtús. Tagann gach bealach chuig fiosrúchán a oireann don ról; leanann téarmaí tráchtála i scríbhinn.",
    commercialTitle: "Gníomhaíochtaí tráchtála féideartha an ardáin",
    commercial: ["Trealamh", "Innealtóireacht shaincheaptha", "Pearsantú", "Cláir foirne agus acadaimh", "Córais traenála", "Ceadúnú conarthach", "Dáileadh", "Seirbhísí ceadaithe", "Catagóirí táirgí amach anseo"],
    boundary: "Is téarmaí caibidlithe cearta tíre, eisiachas, táillí críche agus corrlaigh dáileoirí. Ní fhoilsítear aon ioncam, réamhaisnéis, luacháil, sciar margaidh, toradh, gealltanas maoinithe ná comhpháirtíocht gan ainm.",
    routes: {
      coaches: {
        title: "Cóitseálaithe",
        lead: "Córais traenála, feistiú, céannacht ghairmiúil, cláir údaraithe, deiseanna branda phearsanta agus soláthar trealaimh.",
        points: ["Sweet Spot Trainer agus Spot Trainer i gcleachtadh faoi stiúir cóitseálaí.", "Feistiú leis na maitrísí cumraíochta agus leis na hocht méid greama ón monarcha.", "Coach-to-Brand: próifíl ghairmiúil fhíoraithe agus fobhranda a rialaítear le cearta.", "Leanann úsáid údaraithe clár comhaontú scríofa."],
        cta: "Cuir fiosrúchán comhpháirtíochta cóitseálaí isteach",
        brief: {
          who: "Cóitseálaithe neamhspleácha agus foirne cóitseálaithe.",
          value: "Córais traenála do chleachtadh faoi stiúir cóitseálaí, feistiú le maitrísí na sraitheanna agus le hocht greim ón monarcha, agus bealach chuig céannacht ghairmiúil.",
          now: "Fiosrúcháin chóitseálaithe i scríbhinn. Ní fhoilsítear ná ní thugtar le fios aon choimisiún, tuilleamh ná ráta tagairte.",
          next: "Cuir fiosrúchán an chóitseálaí isteach thíos. Leanann na téarmaí i scríbhinn.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Clubanna agus acadaimh",
        lead: "Trealamh foirne, córais traenála, pearsantú, cláir forbartha, seirbhís agus rannpháirtíocht sa líonra.",
        points: ["Tacair foirne agus tacair mheaitseáilte iarrtha tríd an gcumraitheoir.", "Córais traenála agus modheolaíocht d'fhorbairt struchtúrtha.", "Pearsantú do chláir foirne ar na limistéir cheadaithe.", "Laethanta taispeána, seisiúin feistithe agus rannpháirtíocht sa líonra."],
        cta: "Cuir cur síos club nó acadaimh isteach",
        brief: {
          who: "Clubanna, acadaimh agus cláir foirne.",
          value: "Tacair foirne agus tacair mheaitseáilte, córais traenála, pearsantú do chláir foirne agus laethanta taispeána.",
          now: "Cur síos clubanna agus acadamh i scríbhinn; iarrtar tacair foirne tríd an gcumraitheoir.",
          next: "Cuir cur síos an chlub nó an acadaimh isteach thíos.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Dáileadh agus forbairt tíre",
        lead: "Rogha táirgí, comhordú déantúsaíochta, cumas teicniúil, forbairt críche agus cáiliú tráchtála faoi rún.",
        points: ["Cáiliú i scríbhinn ar an gcontrapháirtí, ar an gcríoch agus ar an gcainéal.", "Rogha táirgí sainithe ó na maitrísí cumraíochta agus ó na haicmí beachtais.", "Is téarmaí caibidlithe a aontaítear i scríbhinn críoch, eisiachas, méideanna, praghsáil agus cosaint tráchtála.", "Sainaithnítear an t-aonán conarthach, na téarmaí íocaíochta agus bonn an tseachadta in aghaidh gach idirbhirt."],
        cta: "Cuir fiosrúchán dáilte nó forbartha tíre isteach",
        brief: {
          who: "Miondíoltóirí, dáileoirí agus comhpháirtithe tíre.",
          value: "Rogha táirgí sainithe ó na maitrísí deimhnithe, ó na haicmí beachtais agus ón raon greama, le cáiliú i scríbhinn ar an gcríoch agus ar an gcainéal.",
          now: "Fiosrúcháin dáilte i scríbhinn. Caibidlítear críoch, eisiachas, méideanna agus praghsáil — ní thugtar ceann ar bith trí fhoirm.",
          next: "Cuir an fiosrúchán dáilte isteach thíos.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Straitéis agus infheistíocht",
        lead: "Cumas innealtóireachta, doimhneacht cumraíochta, samhail déantúsaíochta, bealaí chuig an margadh, maoin intleachtúil, seirbhísí agus deiseanna fáis.",
        points: ["Leanann plé straitéiseach cáilithe nó rochtain rialaithe ar fhaisnéis cáiliú i scríbhinn.", "Tá an fhaisnéis phoiblí teoranta do shonraíochtaí táirge ceadaithe, d'ailtireacht cumraíochta, do chumais fhíoraithe agus do mhínithe clár.", "Ní nochtar eacnamaíocht a bhaineann go sonrach le ceannaitheoir, costáil, modheolaíocht chosanta ná comhaontuithe neamhfhoilsithe ach faoi NDA nó faoi chonradh."],
        cta: "Iarr plé straitéiseach cáilithe",
        brief: {
          who: "Infheisteoirí agus comhpháirtithe straitéiseacha.",
          value: "Plé cáilithe ar chumas innealtóireachta, ar dhoimhneacht cumraíochta, ar an tsamhail déantúsaíochta, ar bhealaí chuig an margadh agus ar mhaoin intleachtúil.",
          now: "Ní fhoilsítear aon fhigiúirí airgeadais, réamhaisnéisí, luachálacha ná torthaí. Leanann faisnéis rialaithe cáiliú i scríbhinn agus NDA.",
          next: "Iarr plé straitéiseach cáilithe thíos.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Cláir institiúideacha",
        lead: "Oideachas, rochtain, nuálaíocht, fianaise forbartha, tionchar sóisialta agus cláir atá struchtúrtha mar is cuí.",
        points: ["Struchtúraítear cláir institiúideacha trí MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) nuair a bhunaíonn an clár an ról sin.", "Fanann cistí srianta clár agus idirbhearta tráchtála ar leithligh.", "Ní iarratas ballraíochta glactha fiosrúchán, agus ní ball institiúideach ceannaitheoir trealaimh.", "Is ceisteanna a bhaineann le tír ar leith deontais, stádas carthanúil, cóireáil chánach agus ceadanna rialála, agus ní ghlactar riamh leo mar bhuntáiste."],
        cta: "Cuir fiosrúchán cláir institiúidigh isteach",
        brief: {
          who: "Institiúidí, cláir oideachais agus forbartha.",
          value: "Cláir d'oideachas, do rochtain, do nuálaíocht agus do fhianaise forbartha, struchtúrtha leis an oibreoir cuí.",
          now: "Fiosrúcháin institiúideacha i scríbhinn. Ní iarratas ballraíochta fiosrúchán; ní ballraíocht institiúideach ceannach trealaimh.",
          next: "Cuir an fiosrúchán institiúideach isteach thíos.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Nochtadh poiblí agus rialaithe",
    disclosure: {
      public: { h: "Poiblí", p: "Sonraíochtaí táirge ceadaithe, tógáil, ailtireacht cumraíochta, cuspóirí traenála, cumais fhíoraithe, mínithe clár agus bealaí comhpháirtíochta." },
      qualified: { h: "Fiosrúchán cáilithe", p: "Riachtanais theicniúla, cainníochtaí, suim i gcríocha, raon feidhme forbartha agus pléití tráchtála ábhartha." },
      controlled: { h: "Rialaithe le NDA nó le conradh", p: "Foirmlí inmheánacha, prótacail mhionsonraithe rialú cáilíochta, leaganacha, uirlisí, modhanna déantúsaíochta, céannacht soláthraithe, costáil, eacnamaíocht a bhaineann go sonrach le ceannaitheoir, modheolaíocht chosanta, comhaontuithe neamhfhoilsithe agus taifid íogaire ceart." },
    },
  },
  contact: {
    title: "Teagmháil agus iarratais",
    lead: "Roghnaigh cuspóir d'iarratais. Ní bhailíonn gach foirm ach an méid atá riachtanach chun é a sheoladh ar aghaidh agus chun é a mheas. Freagraítear iarratais i scríbhinn.",
    email: "Ríomhphost",
    instagram: "Instagram",
    legalLink: "Céannacht dhlíthiúil",
  },
  form: {
    purposeLabel: "Cuspóir an iarratais",
    purposes: {
      selection: "Cabhair le raicéad a roghnú",
      product: "Fiosrúchán faoi tháirge",
      fitting: "Feistiú nó taispeántas",
      technical: "Cur síos teicniúil",
      config: "Iarratas cumraíochta",
      gps: "Próifíl trealaimh GPS",
      coach: "Comhpháirtíocht chóitseálaí",
      club: "Cur síos club nó acadaimh",
      distribution: "Dáileadh nó forbairt tíre",
      brand: "Comhoibriú branda nó ambasadóir",
      family: "Fiosrúchán teaghlaigh nó forbartha",
      institutional: "Clár institiúideach",
      strategic: "Plé straitéiseach nó infheistíochta",
      owner: "Fiosrúchán úinéara",
      network: "Iarratas ar Sports Network",
      general: "Fiosrúchán ginearálta",
    },
    fields: {
      name: "Ainm",
      email: "Ríomhphost",
      role: "Do ról",
      country: "Tír nó réigiún",
      organisation: "Eagraíocht",
      message: "Do theachtaireacht",
      level: "An leibhéal reatha",
      objectives: "Cad is tábhachtaí (suas le trí cinn)",
      currentRacquet: "An raicéad reatha",
      grip: "Méid greama, má tá sí ar eolas",
      seriesInterest: "An tsraith a bhfuil suim agat inti",
      quantity: "Cainníocht",
      city: "Cathair nó suíomh an tseisiúin",
      coachInvolved: "An bhfuil cóitseálaí páirteach?",
      timing: "An uainiú is fearr leat",
      targets: "Spriocanna inmhianaithe",
      limits: "Teorainneacha éigeantacha",
      use: "Úsáid bheartaithe",
      tradeoffs: "Comhbhabhtálacha inghlactha",
      basis: "Bonn tomhais",
      players: "Líon imreoirí",
      interests: "Réimsí suime",
      territory: "An chríoch a bhfuil suim agat inti",
      channels: "Cainéil atá ann agus taithí",
      audience: "Lucht féachana nó disciplín",
      proposal: "An comhoibriú atá beartaithe",
      goal: "Sprioc forbartha",
      ageBand: "Banda aoise an imreora",
      scope: "Raon feidhme an chláir",
      interestArea: "Réimse suime",
      productRef: "Tagairt táirge nó sraithuimhreach",
      requestType: "Cineál iarratais",
      seeking: "Cad atá uait",
      consent: "Aontaím go bhféadfaidh MAXIMUS na sonraí seo a stóráil agus a úsáid chun an iarratas seo a fhreagairt. Ní síntiús margaíochta é seo.",
    },
    roles: { player: "Imreoir", parent: "Tuismitheoir nó caomhnóir", coach: "Cóitseálaí", club: "Club nó acadamh", retailer: "Miondíoltóir", distributor: "Dáileoir", brand: "Branda nó ambasadóir", investor: "Infheisteoir nó comhpháirtí straitéiseach", institution: "Institiúid", other: "Eile" },
    interestOptions: { training: "Córais traenála", fitting: "Feistiú", identity: "Céannacht ghairmiúil", programmes: "Cláir údaraithe", brand: "Branda pearsanta", supply: "Soláthar trealaimh", team: "Trealamh foirne", personalisation: "Pearsantú", development: "Cláir forbartha", service: "Seirbhís", network: "Rannpháirtíocht sa líonra" },
    ownerTypes: { setup: "Socrú agus cumraíocht", service: "Seirbhís", records: "Taifid agus teastais", other: "Eile" },
    strategicAreas: { engineering: "Cumas innealtóireachta", configuration: "Doimhneacht cumraíochta", manufacturing: "Samhail déantúsaíochta", routes: "Bealaí chuig an margadh", ip: "Maoin intleachtúil agus seirbhísí", expansion: "Deiseanna fáis" },
    errors: {
      required: "Tá an réimse seo riachtanach.",
      too_long: "Tá an iontráil seo rófhada.",
      too_short: "Tá an iontráil seo róghearr.",
      invalid_email: "Cuir seoladh ríomhphoist bailí isteach, mar shampla ainm@sampla.ie.",
      invalid_choice: "Roghnaigh ceann de na roghanna.",
      not_number: "Cuir slánuimhir isteach le digití amháin.",
      out_of_range: "Tá an luach seo taobh amuigh den raon a ghlactar.",
      not_in_matrix: "Níl an meáchan seo i maitrís liostaithe na sraithe roghnaithe.",
      decimal_not_supported: "Cuir slánuimhir isteach gan deachúlacha.",
      too_many: "Ná roghnaigh níos mó ná trí rogha.",
      consent_required: "Tá toiliú riachtanach chun go bhféadfaidh MAXIMUS an iarratas seo a fhreagairt.",
      invalid: "Níl an iontráil seo bailí.",
    },
  },
  legal: {
    title: "Céannacht dhlíthiúil agus rialú",
    lead: "Is é MAXIMUS / MAXIMUS GPS an branda poiblí. Tá na céannachtaí dlíthiúla oibriúcháin inaitheanta óna chéile agus luaitear anseo iad.",
    entities: {
      institutional: { role: "Ciseal na gclár institiúideach", p: "Soláthraíonn ciseal na gclár institiúideach nuair a bhunaíonn clár an ról sin. Ní díoltóir tráchtála raicéad é. Eagraíocht chorpraithe neamhbhrabúis i Dubai International Financial Centre." },
      equipment: { role: "Aonán tráchtála an trealaimh", p: "An t-aonán tráchtála don trealamh maidir le soláthar, dáileadh agus seachadadh tráchtála faoi chonradh nuair a bhunaíonn na doiciméid oibriúcháin reatha an ról sin. Sainaithnítear an páirtí conarthach d'aon idirbheart i ndoiciméid an idirbhirt sin." },
      ip: { role: "Maoin intleachtúil, branda agus comhordú tráchtála", p: "Bíonn sé le feiceáil i gcás ról bunaithe maidir le maoin intleachtúil, le branda nó le comhordú tráchtála. Ní shanntar aon fhreagracht chonarthach neamhdheimhnithe." },
      stewardship: { role: "Tagairt stiúardachta", p: "Is é House of Maximus an tagairt stiúardachta don éiceachóras nuair a thacaíonn an fhoinse chuí leis." },
      control: { role: "Maoin intleachtúil inmheánach, bunús ábhair agus rialú doiciméad", p: "Is é MIPA an ciseal inmheánach do mhaoin intleachtúil, do bhunús ábhair agus do rialú doiciméad. Is rud eile iontráil inmheánach MIPA ná trádmharc, paitinn, clárú cóipchirt nó aitheantas breithiúnach seachtrach, agus ní ceadú amhairc í." },
    },
    labels: { licence: "Ceadúnas", registration: "Clárú", vat: "VAT TRN", address: "Seoladh", email: "Ríomhphost", jurisdiction: "Dlínse" },
    boundaryTitle: "Teorainneacha",
    boundary: [
      "Ní thugann ceannach ballraíocht institiúideach, cearta rialachais, ríchíosanna ná cearta infheistíochta go huathoibríoch.",
      "Tá an ról institiúideach scartha ó idirbhearta tráchtála trealaimh.",
      "Freagraíonn an príobháideachas, téarmaí na gclár agus socruithe rochtana rialaithe do na gnéithe atá eisithe iarbhír.",
      "Ní bhaineann aon ráiteas ginearálta ar an dlí is infheidhme le gach cuairteoir, le gach díolachán ná le gach clár thar lear; socraítear an bonn conarthach in aghaidh gach comhaontaithe.",
    ],
  },
  privacy: {
    title: "Príobháideachas",
    updated: "Leagan 2026-09-21 · suíomh 4.2",
    contactTitle: "Teagmháil le haghaidh ceisteanna príobháideachais",
    sections: {
      collect: ["Cad a bhailítear", "Nuair a chuireann tú foirm isteach: na sonraí a chuireann tú isteach (ainm, ríomhphost, ról, tír nó réigiún, eagraíocht má thugtar í, do theachtaireacht agus freagraí na foirme), paraiméadair leathanaigh agus feachtais do chuairte (leathanach tuirlingthe, teanga, paraiméadair utm; aitheantóirí cliceáil fógraíochta ach amháin má cheadaigh tú anailísíocht) agus am an chur isteach. Ní úsáidtear do sheoladh IP ach i bhfoirm haiseáilte ghearrshaolach chun mí-úsáid a theorannú agus ní stóráiltear é le d'iarratas."],
      purpose: ["Cén fáth", "Chun d'iarratas a fhreagairt, chun an togra nó an tsonraíocht a d'iarr tú a ullmhú, agus chun taifead ar an iarratas a choinneáil. Ní sheoltar aon teachtaireachtaí margaíochta ar bhonn foirme."],
      storageOn: ["Cá stóráiltear iarratais", "Stóráiltear iarratais i mbunachar sonraí Upstash, Inc. (Redis), a chuirtear ar fáil tríd an ardán óstála Vercel Inc."],
      notifyEmail: ["Fógra faoi iarratas nua", "Nuair a ghlactar le hiarratas, seoltar fógra ina bhfuil na sonraí a chuir tú isteach le ríomhphost chuig bosca poist freagrach MAXIMUS."],
      notifyTelegram: ["Fógra faoi iarratas nua", "Nuair a ghlactar le hiarratas, seoltar fógra ina bhfuil na sonraí a chuir tú isteach chuig an duine freagrach ag MAXIMUS trí Telegram (Telegram FZ-LLC, Dubai), a phróiseálann an fógra sin agus é ar idirthuras dá bharr."],
      notifyWebhook: ["Fógra faoi iarratas nua", "Nuair a ghlactar le hiarratas, seoltar fógra ina bhfuil na sonraí a chuir tú isteach chuig críochphointe inmheánach MAXIMUS thar nasc sínithe criptithe."],
      notifyNone: ["Fógra faoi iarratas nua", "Tá fógairt faoi iarratais nua á socrú. Stóráiltear d'iarratas agus léann MAXIMUS é ón gclár inmheánach; ní sheoltar aon rud chuig tríú páirtí chuige seo."],
      storageOff: ["Cá stóráiltear iarratais", "Tá stóráil iarratas á socrú. Go dtí go mbeidh sí gníomhach, deir na foirmeacha nach féidir glacadh le hiarratas; ní stóráiltear aon rud. Tá an suíomh á óstáil ag Vercel Inc."],
      browser: ["Stóráil sa bhrabhsálaí", "Coinníonn stóráil an tseisiúin freagraí ilrogha GPS agus an chumraitheora agus paraiméadair feachtais do chuairte don seisiún brabhsálaí seo. Ní stóráiltear sonraí teagmhála, téacs saor, téacs greanta ná faisnéis faoi leanaí sa bhrabhsálaí."],
      analyticsOn: ["Anailísíocht", "Le do thoiliú, déanann Google Analytics 4 cuairteanna agus imeachtaí foirme a mheas gan sonraí teagmhála ná téacs iarratais. Coinnítear do rogha sa stóráil áitiúil agus is féidir é a athrú ag aon am faoi “Socruithe anailísíochta” i mbun an leathanaigh. Oibríonn na foirmeacha gan anailísíocht."],
      analyticsOff: ["Anailísíocht", "Níl aon uirlis anailísíochta gníomhach ar an suíomh seo."],
      retention: ["Coinneáil", "Níl aon tréimhse scriosta uathoibríoch cumraithe go fóill. Is féidir leat iarraidh go scriosfaí d'iarratas ag aon am."],
      children: ["Leanaí", "Is duine fásta a chaithfidh na foirmeacha a líonadh. Is tuismitheoir nó caomhnóir a dhéanann iarratais a bhaineann le himreoirí faoi 18. Ná cuir isteach ainm, dáta breithe, scoil ná faisnéis leighis linbh. Ní fhoilsítear próifílí leanaí riamh."],
      rights: ["Do chearta", "Chun rochtain a fháil ar d'iarratas, é a cheartú nó é a scriosadh, scríobh chuig gps@maximus.tennis agus luaigh aitheantas d'iarratais."],
      controlled: ["Faisnéis rialaithe", "Ní stóráiltear doiciméid faoi rún sa suíomh seo agus ní fhreastalaítear orthu uaidh. Tarlaíonn nochtadh rialaithe faoi NDA nó faoi chonradh trí bhealaí ar leithligh."],
    },
  },
  terms: {
    title: "Téarmaí úsáide",
    copyright: "Is le Maximus Kiriyakulov amháin an cóipcheart sa suíomh seo — a théacsanna, a ghrianghraif, a dhearadh agus a chód. Níor sannadh é d'aon chuideachta ná d'aon duine eile.",
    updated: "Leagan 2026-09-21",
    sections: [
      ["Eolas, agus ní tairiscint", "Déanann faisnéis táirge ar an suíomh seo cur síos ar shonraíochtaí ceadaithe, ar ailtireacht cumraíochta agus ar mhínithe clár. Ní tairiscint díola, ní praghasliosta, ní ráiteas stoic ná ní gealltanas seachadta í. Aontaítear téarmaí tráchtála ar leithligh i scríbhinn leis an aonán conarthach a shainaithnítear i ngach idirbheart."],
      ["Iarratais", "Iarratas a chuirtear isteach tríd an suíomh seo — próifílí GPS, iarratais chumraíochta agus cur síos teicniúil san áireamh — stóráiltear le haitheantas iarratais agus déantar athbhreithniú air. Ní ordú glactha, ní gealltanas déantúsaíochta, ní coinne dheimhnithe, ní iarratas ballraíochta ná ní iarratas glactha ar aon chlár é."],
      ["Sonraíochtaí agus fianaise", "Déantar idirdhealú ar na leathanaigh chuí idir luachanna ríofa, spriocanna déantúsaíochta agus sonraíochtaí deimhnithe. Is spriocanna déantúsaíochta na luachanna righne go dtí go bhfoilsítear a mhalairt. Ní ráthaítear aon toradh d'imreoir ar leith."],
      ["Éiceachóras, ballraíocht agus cearta", "Ní chruthaíonn ceannach raicéid ballraíocht institiúideach, cearta infheistíochta, úinéireacht ar mhaoin intleachtúil, teideal chun ríchíosanna ná buntáistí rannpháirtíochta. Leanann teidil téarmaí foilsithe cláir nó comhaontú scríofa."],
      ["Maoin intleachtúil", "Tá MAXIMUS®, suaitheantas an leoin, marc GPS agus inneachar an tsuímh seo cosanta. Ní nochtar anseo foirmlí innealtóireachta inmheánacha, prótacail rialú cáilíochta, leaganacha, uirlisí, céannacht soláthraithe, costáil ná modheolaíocht chosanta."],
    ],
  },
  lead: {
    submit: "Cuir an iarratas isteach",
    submitting: "Á chur isteach…",
    retry: "Bain triail eile as",
    acceptedEyebrow: "Glacadh leis an iarratas",
    acceptedTitle: "Fuarthas d'iarratas.",
    requestId: "Aitheantas an iarratais",
    acceptedNext: "Déanann MAXIMUS athbhreithniú ar gach iarratas agus freagraíonn i scríbhinn chuig an seoladh ríomhphoist a thug tú. Coinnigh aitheantas an iarratais le haghaidh aon teagmhála eile.",
    duplicate: "Bhí an iarratas seo faighte cheana; ní dhearnadh dúblach.",
    another: "Tosaigh iarratas nua",
    errorsTitle: "Seiceáil na réimsí seo, le do thoil:",
    failTitle: "Níor cuireadh d'iarratas isteach.",
    fail: {
      offline: "Tá do ghléas as líne.",
      network: "Theip ar an gceangal leis an bhfreastalaí.",
      timeout: "Níor fhreagair an freastalaí in am.",
      rate_limited: "Tháinig an iomarca iarratas ón líonra seo. Bain triail eile as i gceann cúpla nóiméad.",
      too_fast: "Cuireadh an fhoirm isteach go han-tapa. Seiceáil í agus cuir isteach arís í.",
      spam_suspected: "Stop an scagaire turscair an iarratas.",
      unavailable: "Ní féidir glacadh le hiarratais faoi láthair.",
      default: "Tharla earráid gan choinne.",
    },
    keepNote: "Coinnítear do chuid ionchuir ar an leathanach seo, agus is féidir leat triail eile a bhaint as.",
    sendByEmail: "Seol an iarratas seo le ríomhphost",
    sendByEmailNote: "Osclaíonn d'aip ríomhphoist le téacs an iarratais seo. Faigheann MAXIMUS é nuair a sheolann tú an ríomhphost.",
    mailConfig: "Cumraíocht",
    mailPage: "Leathanach",
    fallback: "Má leanann an fhadhb, scríobh chuig {email}. Ní mheastar iarratas a bheith curtha isteach ach nuair a thaispeántar aitheantas iarratais.",
    privacyLink: "Fógra príobháideachais",
    hpLabel: "Fág an réimse seo folamh",
    consentShort: "Toiliú",
    after: "Tar éis an chur isteach taispeántar aitheantas iarratais ar an leathanach seo. Déantar athbhreithniú ar iarratais agus freagraítear i scríbhinn iad; ní ordú iarratas.",
    basis: { unstrung: "Gan sreangú", strung: "Sreangaithe", unknown: "Nílim cinnte — aontófar sa sonraíocht" },
    hints: {
      email: "Freagraíonn MAXIMUS i scríbhinn chuig an seoladh seo.",
      goal: "Mar shampla: an chéad raicéad comórtais, nó bogadh ar aghaidh ó raicéad sóisearach. Ná cuir ainmneacha, dátaí breithe ná faisnéis leighis faoi leanbh san áireamh.",
      currentRacquet: "Branda agus samhail, má tá sé ar eolas.",
      message: "Ná cuir pasfhocail, sonraí íocaíochta ná faisnéis leighis san áireamh.",
    },
  },
  choose: {
    eyebrow: "Cabhair le roghnú",
    title: "Cabhraigh liom raicéad a roghnú",
    lead: "Inis do MAXIMUS cad é do leibhéal agus cad is tábhachtaí. Déantar athbhreithniú ar do fhreagraí agus gheobhaidh tú togra i scríbhinn: sraith, aicme bheachtais, meáchan agus greim.",
    stepsTitle: "Cad a tharlaíonn ina dhiaidh seo",
    steps: [
      ["Do fhreagraí", "Leibhéal, tosaíochtaí agus méid greama má tá sí ar eolas agat."],
      ["Athbhreithniú saineolaí", "Déanann MAXIMUS comparáid idir do fhreagraí agus maitrísí na sraitheanna."],
      ["Togra i scríbhinn", "Cumraíocht atá molta agus an chéad chéim eile, i scríbhinn."],
    ],
    formTitle: "Do fhreagraí",
    submit: "Iarr cabhair le roghnú",
    altTitle: "Ar mhaith leat cinneadh a dhéanamh tú féin?",
    altGps: "Próifíl GPS mhionsonraithe",
    altBuild: "Cumraigh go díreach",
    note: "Gan feistiú uathoibríoch agus gan aon mhaíomh ar chruinneas: déanann duine athbhreithniú ar gach iarratas.",
  },
  consent: {
    title: "Anailísíocht",
    text: "An bhféadfaidh MAXIMUS cuairteanna a mheas le Google Analytics? Oibríonn na foirmeacha ar aon nós; ní sheoltar aon sonraí teagmhála ná téacs iarratais chuig an anailísíocht.",
    allow: "Ceadaigh anailísíocht",
    decline: "Diúltaigh",
  },
  familyPlan: {
    title: "Plean Leadóige an Teaghlaigh",
    metaDescription: "Ríomh buiséad leadóige do theaghlaigh: seisiúin, uaireanta, teagmhálacha liathróide agus costas seisiúin amháin, uair an chloig amháin agus buille amháin — ó d'uimhreacha féin, i dtrí chás.",
    eyebrow: "Plean Leadóige an Teaghlaigh · Bí páirteach linn",
    heroTitle: "Cé mhéad a chosnaíonn leadóg do theaghlaigh — agus cad a fhaigheann tú ar an airgead sin?",
    heroLead: "Ríomh buiséad do theaghlaigh, na seisiúin agus na huaireanta a íocann sé astu, an líon measta teagmhálacha liathróide agus costas seisiúin amháin, uair an chloig amháin agus buille amháin — ar do théarmaí féin.",
    heroCta: "Ríomh plean leadóige do theaghlaigh",
    strategy: {
      eyebrow: "Ár sprioc",
      title: "Níos mó leadóige. Níos mó deiseanna. Le chéile.",
      p1: "Tá sé mar sprioc againn margadh domhanda na leadóige a mhéadú faoi dheich trí rannpháirtíocht a leathnú agus an bealach isteach sa leadóg a dhéanamh níos soiléire agus níos inrochtana. Féachann MAXIMUS le bheith ar thús cadhnaíochta trí bhainistíocht, trí mhodheolaíocht, trí cháilíocht, trí thorthaí agus tríd an gcluiche a chur i mbéal an phobail.",
      p2: "Feicimid na déantóirí trealaimh leadóige eile agus a mbrandaí mar chomhpháirtithe féideartha. Molaimid láidreachtaí cuideachtaí, cóitseálaithe, clubanna agus teaghlach a chomhcheangal i gclár comhroinnte chun an leadóg a fhorbairt, a chur chun cinn agus a leathnú ar bhonn comhthairbheach.",
      p3: "Is é MAXIMUS an cúigiú dúil sa chur chuige seo: an ról aontaitheach a chuidíonn le láidreachtaí ar leith oibriú le chéile. Is iad ár ndúshláin chomhroinnte ná breoiteacht, easpa gníomhaíochta coirp i measc leanaí agus na bacainní a choisceann ar dhaoine tosú ag imirt agus leanúint ar aghaidh leis.",
      p4: "Don teaghlach, tosaíonn gach rud le soiléireacht. Taispeánann Plean Leadóige an Teaghlaigh an buiséad, líon na seisiún agus na n-uaireanta, an líon measta teagmhálacha liathróide agus costas an chleachtaidh. Athraigh na coinníollacha agus roghnaigh an cás a oireann duit.",
      note: "Is sprioc straitéiseach de chuid MAXIMUS é fás faoi dheich, ní toradh atá bainte amach cheana féin. Taispeánann an t-áireamhán ríomhanna cásanna agus ní gheallann sé coigilt, éifeacht leighis ná toradh spóirt.",
      ctaCalc: "Ríomh plean leadóige do theaghlaigh",
      ctaPartner: "Pléigh forbairt na leadóige in éineacht linn",
    },
    beyond: {
      eyebrow: "Lasmuigh den chúirt",
      title: "An méid a thógann an plean seachas cleachtadh",
      admission: {
        h: "Iontráil i bpríomhscoileanna agus i bpríomhollscoileanna",
        p: "Tacaíonn MAXIMUS leis an teaghlach ar an mbealach isteach i bpríomhscoileanna agus i bpríomhollscoileanna ar fud an domhain: taifead spóirt an imreora a thógáil, doiciméid agus iarratais a ullmhú, agus cláir a roghnú ina dtéann spórt agus staidéar lámh ar láimh. I gcás ina mbronntar scoláireacht spóirt, laghdaíonn sí an méid a íocann an teaghlach as oideachas.",
      },
      assets: {
        h: "Sócmhainní digiteacha: ainm, íomhá agus taifead an imreora",
        p: "Is sócmhainní iad ainm, íomhá, torthaí, ábhar agus branda pearsanta imreora, agus le himeacht ama is féidir leo luach suntasach airgeadais agus stádais a chothú. Cabhraíonn MAXIMUS lena gcruthú, lena gclárú agus lena gcosaint, ionas go bhfanfaidh an luach sin leis an imreoir agus leis an teaghlach.",
      },
      note: "Níl ceachtar acu mar chuid den áireamhán. Braitheann luach áite scoile, scoláireachta nó sócmhainne digití ar an gcás, agus ní dhéantar meastachán air anseo.",
      cta: "Fiafraigh faoi thacaíocht iontrála agus faoi shócmhainní digiteacha",
    },
    steps: ["Ionchur an teaghlaigh", "Eacnamaíocht an tseisiúin", "Plean fadtéarmach", "Ríomh deiridh"],
    stepsLabel: "Céimeanna an áireamháin",
    scenarios: { now: "Anois", planned: "Beartaithe", wish: "Mian" },
    scenarioHints: { now: "An rud a dhéanann do theaghlach inniu.", planned: "An rud atá beartaithe agat a dhéanamh ina dhiaidh seo.", wish: "An rud ba mhaith leat a dhéanamh." },
    currency: {
      label: "Airgeadra",
      note: "Is san airgeadra seo atá gach suim a chuireann tú isteach. Ní dhéantar aon tiontú.",
    },
    fields: {
      players: { label: "Baill teaghlaigh a imríonn", hint: "Slánuimhir." },
      cost: { label: "Praghas seisiúin amháin d'imreoir amháin", hint: "Suim i slánuimhir, cánacha agus táillí san áireamh." },
      sessions: { label: "Seisiúin in aghaidh an imreora in aghaidh na míosa", hint: "Slánuimhir." },
      minutes: { label: "Fad seisiúin amháin, i nóiméid", hint: "An t-am iomlán, sosanna san áireamh. Ceadaítear deachúlacha." },
      contacts: { label: "Teagmhálacha liathróide in aghaidh an imreora in aghaidh an tseisiúin", hint: "Is éard is teagmháil ann ná raicéad an imreora féin ag bualadh na liathróide. Ní hionann malartú buillí amháin agus teagmháil amháin. Comhair ar an mbealach céanna i ngach cás." },
    },
    presetsLabel: "Rogha thapa, nóiméid",
    ages: {
      title: "Fad an phlean",
      start: "Aois tosaigh",
      end: "Aois deiridh",
      hint: "Toimhde anaithnid faoi cé chomh fada a mhairfidh an plean; ní úsáidtear í ach don tábla fadtéarmach. Ní dáta breithe í ná aois tosaigh mholta.",
    },
    extras: {
      title: "Costais bhreise an teaghlaigh",
      note: "Is don teaghlach ar fad na suimeanna seo agus baineann siad leis na trí chás ar fad. Ní iolraítear iad faoi líon na n-imreoirí, agus ní chuirtear san áireamh iad i gcostas uaire ná teagmhála.",
      equipment: "An chéad trealamh — suim amháin don tréimhse",
      clothing: "Éadaí agus coisbheart — suim amháin don tréimhse",
      renewal: "Athnuachan trealaimh — suim amháin don tréimhse, ní athdhéantar go huathoibríoch í",
      court: "Cúirt nó club — in aghaidh na míosa, an teaghlach ar fad",
      travel: "Taisteal agus imeachtaí — in aghaidh na míosa, an teaghlach ar fad",
      quoteSource: "Cá as a dtagann na praghsanna (roghnach)",
      quoteDate: "Dáta na bpraghsanna (roghnach)",
      quoteNote: "Taispeántar é díreach mar a chuir tú isteach é. Ní fhíoraíonn MAXIMUS na praghsanna seo.",
    },
    storage: {
      save: "Sábháil an plean ar an ngléas seo",
      clear: "Glan an plean ón ngléas seo",
      saved: "Sábháladh an plean ar an ngléas seo. Níor seoladh aon rud áit ar bith.",
      cleared: "Glanadh an plean. Tá an t-áireamhán ar ais ag a luachanna tosaigh.",
      restored: "Tugadh ar ais do phlean a sábháladh ar an ngléas seo.",
      invalid: "Níorbh fhéidir plean a sábháladh ar an ngléas seo a léamh, agus níor cuireadh i bhfeidhm é. Is féidir leat ríomh nua a thosú.",
      unavailable: "Ní cheadaíonn an brabhsálaí seo sábháil ar an ngléas.",
    },
    annual: {
      title: "Bliain amháin, taobh le taobh",
      sessions: "Seisiúin imreora sa bhliain",
      cost: "Caiteachas an teaghlaigh ar sheisiúin sa bhliain",
      hours: "Uaireanta imreora sa bhliain",
      length: "Fad seisiúin amháin",
      contacts: "Teagmhálacha liathróide sa bhliain",
      note: "Suimíonn na seisiúin imreora agus na huaireanta imreora seisiúin gach imreora. Ní uaireanta fruilithe cúirte ná cruinnithe grúpa iad: is ionann beirt imreoirí a thraenálann le chéile ar feadh 90 nóiméad agus 2 sheisiún imreora agus 3 huaire imreora.",
    },
    economics: {
      title: "Costas seisiúin, uaire agus teagmhála",
      session: "Seisiún amháin d'imreoir amháin",
      hour: "Uair an chloig de chleachtadh imreora amháin",
      contact: "Teagmháil liathróide amháin",
      undefinedContacts: "Gan sainiú: 0 teagmháil",
      undefinedMinutes: "Gan sainiú: 0 nóiméad",
      below: "níos lú ná {value}",
      note: "Ní théann isteach sna figiúirí seo ach praghas an tseisiúin. Ní roinntear costais bhreise an teaghlaigh ar na teagmhálacha.",
      caption: "Ríomhtar líon na dteagmhálacha ón méid seisiún a roghnaíodh agus ó thoimhdí na samhla. Braitheann an cleachtadh iarbhír ar an bhformáid, ar na sosanna agus ar choinníollacha na traenála. Is tomhas buiséid é costas teagmhála, ní tomhas ar cháilíocht an chóitseála.",
    },
    longTerm: {
      title: "Plean caiteachais fadtéarmach",
      horizon: "Léaslíne",
      activeYears: "Blianta gníomhacha",
      years: "{n} bl",
      note: "Tá na blianta gníomhacha teoranta ag an difríocht idir an dá aois. Coinnítear praghsanna, minicíocht, boilsciú, séasúir, seisiúin a cailleadh agus rátaí malairte seasta. Níl na costais bhreise mar chuid den tábla seo.",
    },
    final: {
      title: "Ríomh deiridh",
      scenario: "Cás",
      months: "Tréimhse, i míonna",
      heading: "{scenario} · Míonna: {months}",
      total: "Iomlán na tréimhse",
      training: "Seisiúin",
      extras: "Costais bhreise",
      oneOff: "Míreanna aonuaire",
      monthly: "Míreanna míosúla × míonna",
      sessions: "Seisiúin imreora sa tréimhse",
      hours: "Uaireanta imreora sa tréimhse",
      contacts: "Teagmhálacha liathróide sa tréimhse",
      formulaTitle: "Conas a ríomhtar é",
      formula: "Iomlán = imreoirí × seisiúin sa mhí × míonna × praghas seisiúin + costais aonuaire + míonna × costais bhreise mhíosúla.",
      formulaNote: "Cuirtear costais bhreise isteach don teaghlach ar fad. Comhairtear míreanna aonuaire uair amháin, fiú más 0 líon na míonna.",
      inputs: "Na sonraí a chuir tú isteach",
    },
    units: { min: "nóim", h: "u", approx: "≈" },
    errors: {
      title: "Ceartaigh na réimsí seo chun an toradh a fheiceáil",
      required: "Riachtanach — cuir uimhir isteach; ceadaítear 0.",
      negative: "Ní cheadaítear luach diúltach.",
      integer: "Slánuimhreacha amháin.",
      number: "Cuir uimhir isteach.",
      tooLarge: "Tá an uimhir seo rómhór le ríomh.",
      endBeforeStart: "Ní féidir leis an aois deiridh a bheith níos ísle ná an aois tosaigh.",
      tooLong: "200 carachtar ar a mhéad.",
      date: "Cuir dáta bailí isteach.",
      currency: "Roghnaigh airgeadra.",
      scenario: "Roghnaigh cás.",
      result: "Tá an toradh rómhór le taispeáint go hiontaofa. Laghdaigh na luachanna a chuir tú isteach.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: an chumadóireacht iomlán — an traenálaí ó thosach agus ó thaobh, rondal greanta an leoin ar an gceann teagmhála cruinn, an greanadh MAXIMUS agus SPOT TRAINER feadh an chrainn, agus an caipín deiridh ochtagánach le marc an leoin",
    greatHero: "Sraith MAXIMUS GREAT, 363 g: an chumadóireacht iomlán le mionsonraí dearga agus buí ar an gceann, litreoireacht MAXIMUS shnasta, síniú Maximus ar an gcrann agus marc an leoin ar an hanla",
    spotDetail: "Dhá MAXIMUS Spot Trainer níos cóngaraí: an leon greanta ar an gceann teagmhála dubh neamhlonrach, an fillteán greama rillithe agus na caipíní deiridh ochtagánacha le marc an leoin",
    spotPair: "Dhá MAXIMUS Spot Trainer leagtha ar fhiar ar dhromchla dorcha, MAXIMUS greanta feadh crainn amháin agus SPOT TRAINER feadh an chrainn eile, le rondal an leoin ar gach ceann teagmhála",
    spinVisual: "MAXIMUS SPIN: ceann le sreanga, litreoireacht MAXIMUS shnasta, greim agus caipín deiridh an leoin",
    powerVisual: "MAXIMUS POWER: ceann le sreanga, litreoireacht MAXIMUS shnasta, greanadh pearsantaithe, greim agus caipín deiridh an leoin",
    greatVisual: "MAXIMUS GREAT: ceann le sreanga, litreoireacht MAXIMUS shnasta, greanadh pearsantaithe, greim, caipín deiridh an leoin agus marc sraithe G ar an scornach",
    spinHead: "Ceann agus leaba sreang MAXIMUS SPIN",
    handleLion: "Scornach, greim agus caipín deiridh MAXIMUS le marc an leoin",
    engraving: "Greanadh pearsantaithe airgid ar an gcrann",
    lettering: "Litreoireacht MAXIMUS dhubh shnasta ar fhráma dubh neamhlonrach",
    variantAlt: "Sraith MAXIMUS {series} — {w} g, cothromaíocht {b} mm: léirshamhlú iomlán le stráice na sonraíochta, limistéar an ghreanta phearsantaithe agus marcáil MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, córas ceithre raicéad",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Crainn Sweet Spot Trainer leis an litreoireacht MAXIMUS",
    sstGrips: "Greamanna agus caipíní deiridh Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, ceithre chaipín deiridh le marc an leoin",
    note: "Amharc táirge",
  },
  notFound: { title: "Leathanach gan aimsiú", p: "Níl an leathanach a d'iarr tú ann sa teanga seo.", cta: "Téigh chuig an leathanach baile" },
};

export default ga;
