/* Galician dictionary — MAXIMUS website v4.0. Translated from content/en.js; numerical product data lives in data/products.js. */
const gl = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — raquetas de tenis integramente de carbono deseñadas segundo especificación",
    defaultDescription:
      "Raquetas de tenis integramente de carbono, do marco ao mango: GREAT 97 in², POWER 98 in² e SPIN 100 in², oito medidas de empuñadura de fábrica L0–L7, clases de precisión para o peso, o balance, o swingweight e a rixidez, e enxeñaría personalizada a pedimento.",
  },
  common: {
    statuses: {
      current: "Actual",
      agreement: "Dispoñible por acordo",
      development: "En desenvolvemento",
      concept: "Concepto",
      target: "Obxectivo de fabricación",
      modelled: "Calculado",
      confirmed: "Confirmado",
      requested: "Arquitectura solicitada",
      notprovided: "Non facilitado",
    },
    brief: { who: "A quen vai dirixido", value: "Que obtén", now: "Confirmado agora", next: "Paso seguinte" },
    labels: {
      next: "Seguinte",
      back: "Atrás",
      edit: "Editar as respostas",
      review: "Revisión",
      start: "Comezar",
      restart: "Comezar de novo",
      copy: "Copiar o texto da solicitude",
      copied: "Copiado",
      openEmail: "Abrir o correo para enviar esta solicitude",
      reference: "Referencia da solicitude",
      weight: "Peso",
      balance: "Balance",
      swingweight: "Swingweight",
      stiffness: "Rixidez",
      grip: "Medida de empuñadura",
      headSize: "Tamaño da cabeza",
      series: "Serie",
      precisionClass: "Clase de precisión",
      quantity: "Cantidade",
      notProvided: "Aínda non publicado",
      requestTarget: "Obxectivo solicitado",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Ler máis",
      allSeries: "Todas as series",
      points: "pesos do catálogo",
      optional: "opcional",
      required: "obrigatorio",
      select: "Seleccionar",
      yes: "Si",
      no: "Non",
      unknown: "Non o sei con certeza",
      custom: "Obxectivo personalizado",
      listed: "Peso do catálogo",
      individual: "Raqueta individual",
      pair: "Parella emparellada",
      triple: "Trío emparellado",
      team: "Xogo de equipo",
      summaryTitle: "Resumo da súa solicitude",
      nextAction: "Acción seguinte",
      status: "Estado",
      learn: "Máis información",
      schematic: "Esquema — non é unha medición",
      photo: "Fotografía",
    },
    ecosystemStrip: "O ecosistema MAXIMUS",
    truth: {
      noPrices: "Os prezos, as cantidades mínimas, os prazos de produción, as garantías e os compromisos de entrega confírmanse por escrito para cada mercado e cada programa.",
      requestNotOrder: "Unha solicitude é unha petición de revisión. Non é un pedido aceptado, nin un compromiso de fabricación, nin unha cita confirmada.",
      noGuarantee: "Ningún equipamento, método ou programa descrito aquí garante un resultado concreto para un xogador determinado.",
      governing: "Esta páxina publícase en varias linguas. A versión inglesa é a versión vinculante; a tradución facilítase por comodidade.",
    },
  },
  nav: {
    language: "Idioma",
    groups: { racquets: "Raquetas", training: "Adestramento", ecosystem: "Ecosistema", partnerships: "Colaboracións" },
    familyPlan: "Tenis en Familia",
    racquets: "Series de raquetas e comparación",
    great: "GREAT — 97 in² · Control",
    power: "POWER — 98 in² · Potencia",
    spin: "SPIN — 100 in² · Efecto",
    precision: "Precisión e rixidez",
    grip: "Arquitectura de empuñadura de fábrica L0–L7",
    custom: "Enxeñaría personalizada",
    training: "Sistemas de adestramento",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodoloxía",
    gps: "MAXIMUS GPS",
    build: "Configure a súa",
    choose: "Axúdeme a escoller",
    ecosystem: "Mapa do ecosistema",
    engineering: "Enxeñaría e fabricación",
    experience: "Experiencia e axuste",
    brands: "Marcas persoais e embaixadores",
    families: "Familias e pais",
    owners: "Propietarios e arquivo seguro do propietario",
    network: "Sports Network",
    partnerships: "Todas as vías de colaboración",
    coaches: "Adestradores",
    clubs: "Clubs e academias",
    distribution: "Distribución e desenvolvemento de países",
    strategic: "Estratexia e investimento",
    institutional: "Programas institucionais",
    contact: "Contacto",
    legal: "Identidade legal",
    privacy: "Privacidade",
    terms: "Condicións",
    menu: "Menú",
    close: "Pechar",
    home: "Inicio",
    skip: "Ir ao contido",
  },
  footer: {
    line: "A raqueta MAXIMUS é a súa chave ao mundo MAXIMUS.",
    product: "Produto",
    ecosystem: "Ecosistema",
    company: "Organización",
    instagram: "Instagram",
    email: "Email",
    analytics: "Configuración de analítica",
    subscribe: {
      title: "Siga con MAXIMUS",
      line: "Series novas, datas de axuste, material de adestramento e o programa de propietarios. Unhas poucas cartas ao ano, nada máis.",
      label: "Enderezo de correo",
      placeholder: "your@email.com",
      button: "Subscribirse",
      sending: "Enviando",
      done: "Xa está na listaxe. Só escribimos cando hai algo que paga a pena ler.",
      invalid: "Comprobe o enderezo.",
      failed: "O enderezo non se rexistrou. Inténteo de novo nun momento.",
      terms: "Ao subscribirse acepta que MAXIMUS lle envíe estas novidades e conserve o seu enderezo con esa finalidade. Cada carta leva unha ligazón para darse de baixa.",
    },
    rights: "MAXIMUS® e o emblema do león son marcas do ecosistema MAXIMUS. Propiedade intelectual interna, procedencia e control documental MIPA.",
    boundary:
      "As condicións comerciais e contractuais acórdanse á parte e por escrito. A compra dunha raqueta non crea afiliación institucional, nin dereitos de investimento, nin titularidade da propiedade intelectual, nin dereito a canons.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "A precisión comeza no contacto.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer e a metodoloxía MAXIMUS unen a práctica focalizada con raquetas de rendemento integramente de carbono.",
    heroCta1: "Descubra o sistema de adestramento",
    heroCta2: "Descubra GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Control",
    heroMeta: [
      ["Integramente de carbono", "do marco ao mango"],
      ["4 parámetros", "peso · balance · swingweight · rixidez"],
      ["8 medidas de empuñadura", "xeometría de fábrica L0–L7"],
      ["3 series", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Plan de Tenis en Familia · Contribúa connosco",
      title: "O seu orzamento familiar. O que cobre. O que constrúe.",
      p: "Tres escenarios en paralelo: actual, previsto e desexado. As sesións, as horas e os contactos coa bóla que cobre o seu orzamento, e o custo dunha sesión, dunha hora e dun golpe, calculados a partir das súas propias cifras.",
      points: [
        ["As súas cifras", "Cada importe vén de vostede. Nada se supón, nada se converte."],
        ["Tres escenarios", "Compare o que fai agora co que ten previsto e co que lle gustaría facer."],
        ["Dez anos por diante", "O plan de gasto dun a dez anos, limitado polas idades que indique."],
        ["Máis alá da pista", "Apoio para acceder a centros educativos de primeiro nivel, e activos dixitais que quedan co xogador."],
      ],
      cta: "Calcule o seu plan de tenis en familia",
    },
    paths: {
      eyebrow: "Comece aquí",
      title: "Escolla o seu camiño",
      items: {
        player: { h: "Xogador", p: "Busque unha raqueta polo nivel e as prioridades, ou configure unha directamente.", a: "Busque a súa raqueta" },
        parent: { h: "Pai ou nai", p: "Unha vía escrita para os obxectivos de desenvolvemento, a participación do adestrador e o equipamento axeitado.", a: "Vía familiar" },
        coach: { h: "Adestrador, club ou academia", p: "Sistemas de adestramento, axuste, xogos de equipo e personalización.", a: "Vías para adestradores e clubs" },
        partner: { h: "Distribuidor ou socio", p: "Vías de distribución, desenvolvemento de países, estratéxicas e institucionais.", a: "Vías de colaboración" },
      },
    },
    series: {
      eyebrow: "Series de rendemento",
      title: "Tres arquitecturas de rendemento. Unha plataforma de enxeñaría.",
      lead: "Escolla a serie segundo a dirección de xogo e complete despois a configuración: clase de precisión, peso, empuñadura, personalización.",
      cta: "Compare as series",
      configure: "Configurar",
      open: "Abrir a serie",
      photoPending: "Fotografía aínda non publicada",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Sistema de Precisión MAXIMUS",
      title: "Peso. Balance. Swingweight. Rixidez.",
      sub: "Controlados como un único sistema de enxeñaría.",
      lead: "Tres clases de precisión definen con que rigor cada raqueta acabada se axusta á especificación declarada. P0.5 é unha tolerancia estreita baixo un protocolo de medición definido — non é erro cero.",
      cta: "Precisión e rixidez en detalle",
    },
    stiffness: {
      eyebrow: "Rixidez",
      title: "Resposta do marco repetible fronte a un obxectivo declarado.",
      p: "A rixidez do marco configura a resposta, a sensación e a coherencia entre raquetas. MAXIMUS trátaa como o cuarto parámetro controlado: o obxectivo, o resultado medido, a tolerancia permitida e a capacidade do instrumento consérvanse como rexistros separados. O beneficio é a repetibilidade — non un resultado garantido para cada xogador.",
      cols: [["Resposta", "Como devolve o marco a enerxía no contacto."], ["Sensación", "Que percibe o xogador no contacto."], ["Coherencia", "As raquetas feitas coa mesma especificación responden igual dentro da súa clase."]],
      schematicCaption: "Esquema: desviación permitida arredor dun obxectivo de rixidez declarado para cada clase. Non é unha medición; non se insinúa ningún valor RA.",
      bands: { p25: "tolerancia do obxectivo ±1 RA", p15: "tolerancia do obxectivo ±0,5 RA", p05: "axústase ao valor RA declarado baixo o protocolo de medición de fábrica establecido — non é erro cero", target: "obxectivo declarado (sen insinuar ningún valor)" },
    },
    carbon: {
      eyebrow: "Estándar de construción",
      title: "Integramente de carbono. Do marco ao mango.",
      p: "Todas as raquetas MAXIMUS actuais desta plataforma son integramente de carbono na súa estrutura, incluído o mango. Non se emprega escuma para formar o mango.",
      gripTitle: "Oito medidas de empuñadura de fábrica. L0–L7.",
      gripP: "Cada medida é xeometría de mango de carbono de fábrica — non un engrosamento con sobreempuñaduras.",
      scaleCaption: "Esquema: designacións nominais de empuñadura L0–L7 (de 4″ a 4⅞″). Non son dimensións medidas do mango.",
      cta: "Arquitectura de empuñadura de fábrica",
    },
    custom: {
      eyebrow: "Enxeñaría personalizada",
      title: "Deseñada segundo especificación.",
      sub: "A gama estándar é o punto de partida.",
      p: "MAXIMUS acepta requisitos técnicos máis alá das matrices publicadas para avalialos, deseñalos, validalos e fabricalos segundo unha especificación acordada. A viabilidade confírmase por escrito.",
      chain: ["Definir", "Deseñar", "Validar", "Especificar", "Producir", "Medir / rexistrar"],
      cta: "Presentar un informe técnico",
      cta2: "Falar de enxeñaría personalizada",
    },
    training: {
      eyebrow: "Sistemas de adestramento",
      title: "Un sistema de adestramento construído arredor do contacto.",
      p: "Sweet Spot Trainer, a metodoloxía MAXIMUS e Spot Trainer conectan o equipamento coa práctica dirixida polo adestrador: contacto centrado, control, carga progresiva e volta á raqueta de rendemento.",
      cta: "Sistemas de adestramento",
      cta2: "Solicitar unha demostración",
      photoPending: "Fotografía do adestrador aínda non publicada",
      sstP: "Unha cabeza de adestramento de 50 in² para practicar o contacto centrado, con catro configuracións de peso para a carga que escolla o adestrador.",
      sstCta: "Descubra o Sweet Spot Trainer",
      sstCaption: "Configuración de 300 g, unha de catro",
      methodP: "Fixar obxectivos, escoller o equipamento, practicar coa participación do adestrador, rexistrar observacións, reavaliar, axustar e levar o traballo ao xogo de rendemento.",
      methodCta: "Descubra a metodoloxía",
      spotP: "Un pequeno obxectivo redondo para practicar un punto de contacto preciso e repetible.",
      spotCta: "Descubra o Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Fabricación e control de calidade",
      title: "Feita segundo unha especificación. Medida e rexistrada.",
      p: "A produción segue a especificación escrita de cada pedido. Os rexistros seguen a clase de precisión: rexistros de produción conservados para P2.5, rexistros individuais e rastreabilidade para P1.5, control individual e documentación para P0.5 cando o programa do pedido os implementa.",
      confirmedTitle: "Confirmado",
      confirmed: ["Construción integramente de carbono, do marco ao mango.", "Clases de precisión P2.5, P1.5 e P0.5 con catro parámetros controlados.", "Oito medidas de empuñadura de fábrica L0–L7."],
      pendingTitle: "Aínda non publicado",
      pending: "As fotografías dos equipos de medición, os rexistros de control de calidade de mostra e as imaxes de fábrica aínda non se publicaron. Nada nesta páxina é un certificado de medición.",
      captions: { lettering: "Letras MAXIMUS brillantes sobre o marco mate", buttcap: "Empuñadura e tapón coa marca do león", handle: "Gravado de personalización en prata", finish: "Cabeza e plano de cordaxe" },
      cta: "Enxeñaría e fabricación",
    },
    world: {
      eyebrow: "O mundo MAXIMUS",
      title: "Unha chave. Un ecosistema. Oportunidades ilimitadas.",
      note: "«Oportunidades ilimitadas» é unha expresión de marca, non unha promesa de viabilidade técnica, ingresos ou acceso ilimitados. Unha compra non xera canons, rendementos de investimento, patrocinio nin financiamento do desenvolvemento dun xogador.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — e a súa navegación no mundo do tenis: un perfil de equipamento guiado e respondido por escrito." },
        personal: { h: "Personalización", p: "Nomes, iniciais, números e identificación de equipo co tratamento de gravado en prata aprobado." },
        development: { h: "Desenvolvemento", p: "Sistemas de adestramento dirixidos polo adestrador, rexistros e reavaliación." },
        ecosystem: { h: "Ecosistema ampliado", p: "Marcas persoais, rexistros de propietarios, rede, licenzas e programas institucionais — cada un co seu estado real." },
      },
      cta: "Descubra o ecosistema",
    },
    partners: {
      eyebrow: "Vías de colaboración",
      title: "Adestradores, clubs, distribuidores e socios.",
      p: "Primeiro a cualificación por escrito. Os dereitos de país, a exclusividade e as condicións comerciais negócianse por escrito — nunca se conceden a través dun formulario.",
      cta: "Todas as vías de colaboración",
      formTitle: "Consulta breve",
      formLead: "Escolla a finalidade e escriba a MAXIMUS. Recibirá un identificador de solicitude nesta páxina.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "A SÚA NAVEGACIÓN NO MUNDO DO TENIS" } },
    personal: { eyebrow: "Personalización", title: "O seu nome. O seu número. A súa MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tres series. Parámetros reais." },
    map: { cta: "Descubra o ecosistema" },
  },
  racquets: {
    title: "Raquetas",
    lead: "Tres series de rendemento cun estándar de construción compartido, un sistema de precisión compartido e unha arquitectura de empuñadura de fábrica compartida. Cada serie é unha arquitectura de rendemento consolidada dentro dunha plataforma de enxeñaría máis ampla.",
    direction: { control: "Control", power: "Potencia", spin: "Efecto" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Dirección de xogo principal",
    compareTitle: "Comparación de series",
    compareLead: "Só datos de arquitectura confirmados. Os patróns de cordaxe, as lonxitudes, os perfís de marco, os rangos de tensión e os valores nominais de swingweight e rixidez destas series non se publican; recóllense como obxectivos solicitados para a revisión técnica.",
    columns: { series: "Serie", head: "Tamaño da cabeza", direction: "Dirección", weights: "Pesos do catálogo", range: "Intervalo de peso", balance: "Datos de balance" },
    balanceModelled: "Valores calculados",
    balanceNotProvided: "Aínda non publicado",
    construction: "Construción: integramente de carbono, do marco ao mango · Precisión: P2.5 / P1.5 / P0.5 · Empuñaduras: L0–L7",
    otherTitle: "Outros deportes de raqueta",
    otherLead: "Direccións de desenvolvemento aprobadas. Non existen produtos vendibles nestas categorías e non se transfire ningunha especificación de tenis a elas.",
    other: { padel: "Pádel", pickleball: "Pickleball", squash: "Squash", badminton: "Bádminton", racquetball: "Racquetball", beachTennis: "Tenis praia" },
    ctaConfigure: "Configurar unha solicitude",
    ctaSeries: "Abrir a serie",
  },
  seriesPage: {
    eyebrow: "Series de rendemento",
    intro: {
      great: "A arquitectura GREAT de 97 in² está construída arredor do control: cabeza compacta, contacto preciso e confianza direccional.",
      power: "A arquitectura POWER de 98 in² está construída arredor da transferencia de enerxía: profundidade e ritmo dende un marco estable.",
      spin: "A arquitectura SPIN de 100 in² está construída arredor do comportamento da bóla: rotación, marxe e modelado da traxectoria.",
    },
    photoPending: "Fotografía da serie aínda non publicada",
    detailPending: "As fotografías de detalle da construción e do mango desta serie aínda non se publicaron.",
    specsTitle: "Especificación e estado",
    catalogue: {
      eyebrow: "Catálogo da serie {series}",
      title: "{n} variantes de peso",
      lead: "Cada variante da serie {series}, ordenada por peso. Peso en gramos, balance en milímetros dende o tapón. Cada visualización amósase enteira: nada recortado, enmascarado nin estirado.",
      selectLabel: "Escolla unha variante de peso",
      select: "Amosar esta variante",
      selected: "Amosada arriba",
      balanceLabel: "Balance",
      headLabel: "Tamaño da cabeza",
      constructionLabel: "Construción",
      gripsLabel: "Medidas de empuñadura de fábrica",
      precisionLabel: "Clases de precisión",
      balanceConfirmed: "O balance é o valor confirmado para este peso e coincide coa cifra impresa na visualización.",
      balanceModelled: "O balance é un valor calculado para este peso do catálogo, non unha medición individual de fábrica; coincide coa cifra impresa na visualización.",
      zoom: "Abrir a imaxe",
      close: "Pechar",
      allTitle: "Todas as {n} variantes",
    },
    specs: { head: "Tamaño da cabeza", direction: "Dirección principal", weights: "Pesos do catálogo", range: "Intervalo de peso", balance: "Balance", construction: "Construción", grips: "Empuñaduras de fábrica", precision: "Clases de precisión" },
    construction: "Integramente de carbono, do marco ao mango",
    statusTitle: "Estado dos valores",
    matrixTitle: "Matriz de pesos completa",
    matrixLead: "Os pesos do catálogo son a selección estándar. Pódense solicitar outros pesos como obxectivos personalizados; os valores intermedios que faltan non se engaden.",
    balanceNote: {
      confirmed: "Os valores de balance están confirmados para cada peso do catálogo (mm dende o tapón) e coinciden coa cifra impresa na visualización dese peso. Aquí non se calculan nin se suavizan entre pesos veciños; a base de medición confírmase na especificación escrita.",
      modelled: "Os valores de balance calcúlanse para cada peso do catálogo (mm dende o tapón). Non son medicións individuais de fábrica; a base de medición confírmase na especificación escrita.",
      notprovided: "Os valores de balance desta serie non se facilitan. Non os deduza a partir doutra serie.",
    },
    optionsTitle: "Precisión, empuñadura e peso",
    notPublished: "Non publicado para esta serie: patrón de cordaxe, lonxitude, perfil de marco, intervalo de tensión e valores de swingweight e rixidez. Pode indicalos como obxectivos solicitados para a revisión técnica.",
    offerTitle: "Que acontece despois da súa solicitude",
    offerSteps: [
      ["Solicitude", "Envíe unha configuración ou unha pregunta. O identificador de solicitude amósase de inmediato."],
      ["Revisión", "MAXIMUS revisa a serie, a clase, o peso, a empuñadura e calquera obxectivo solicitado."],
      ["Resposta escrita", "A especificación, a dispoñibilidade e as condicións comerciais confírmanse por escrito."],
    ],
    faqTitle: "Preguntas",
    faq: [
      ["Os valores de balance están medidos?", "Calcúlanse para os pesos do catálogo, non son medicións individuais. A base de medición confírmase na especificación escrita."],
      ["Podo solicitar un peso que non está no catálogo?", "Si, como obxectivo personalizado en gramos enteiros. Revísase tecnicamente e a viabilidade confírmase por escrito."],
      ["Que cambia a clase de precisión?", "Con que rigor se manteñen o peso, o balance, o swingweight e a rixidez fronte á especificación declarada, e que rexistros se conservan."],
      ["A empuñadura engrósase con sobreempuñaduras?", "Non. L0–L7 son xeometrías de mango de carbono de fábrica."],
      ["Onde están os prezos e os prazos de entrega?", "Confírmanse por escrito para cada solicitude e aquí non se publican."],
    ],
    faqSpinBalance: ["De onde saen os valores de balance de SPIN?", "Da táboa confirmada da serie Spin: 33 variantes de peso con balance en milímetros dende o tapón. Cada parella coincide coa cifra impresa na visualización aprobada dese peso. Os valores non se calculan nin se suavizan entre pesos veciños."],
    ctaBuild: "Configurar esta serie",
    ctaAsk: "Preguntar sobre esta serie",
    ctaCompare: "Comparar todas as series",
    weightsLabel: "pesos do catálogo",
    headLabel: "cabeza",
  },
  precision: {
    title: "Precisión e rixidez",
    switch: { label: "Escolla unha clase de precisión", panelLabel: "Catro parámetros controlados —", qcLabel: "Arquitectura de control de calidade", protocolNote: "baixo o protocolo de medición do control de calidade de fábrica definido", fullTable: "Táboa de comparación completa" },
    lead: "Catro parámetros controlados como un único sistema de enxeñaría. Cada clase define con que rigor unha raqueta acabada se axusta á especificación declarada e que rexistros de calidade se producen.",
    statement: "Peso. Balance. Swingweight. Rixidez. Controlados como un único sistema de enxeñaría.",
    classes: {
      "P2.5": { name: "Núcleo de rendemento escalable", qc: "Medición individual e rexistros de produción conservados." },
      "P1.5": { name: "Precisión avanzada", qc: "Medición individual, rexistros individuais e rastreabilidade." },
      "P0.5": { name: "Profesional · controlada individualmente", qc: "Control individual con valores nominais e reais e rexistros de medición individuais; identidade de serie, rastreabilidade de lote, certificado de precisión e xogos emparellados cando o programa do pedido os implementa." },
    },
    columns: { cls: "Clase", weight: "Peso", balance: "Balance", sw: "Swingweight", stiff: "Rixidez", qc: "Arquitectura de control de calidade" },
    stiffTarget: "tolerancia do obxectivo",
    stiffExact: "axústase ao valor RA declarado baixo o protocolo de medición de fábrica establecido",
    programmeNote: "A identidade de serie, os certificados e a documentación de xogos emparellados emítense só cando o programa dun pedido concreto os implementa.",
    targetsNote: "As especificacións de rixidez son obxectivos de fabricación ata que o protocolo correspondente e as probas de produción sosteñan unha afirmación máis forte. A proposta de arquitectura non implica que cada configuración do catálogo xa superase un proceso completo de liberación de catro parámetros.",
    stiffnessTitle: "Por que importa a rixidez",
    stiffnessP1: "A rixidez do marco inflúe en como responde o marco no contacto, en como se sente e en canto coherentes son dúas raquetas entre si. O beneficio central de controlala é unha resposta repetible fronte a unha especificación declarada.",
    stiffnessP2: "Antes de publicar unha conformidade verificada, o rexistro interno de control de calidade identifica o instrumento, o seu estado de calibración, o método, o estado da raqueta, a resolución, a incerteza de medición, as medicións repetidas, a regra de arredondamento e a regra de aceptación. Un número enteiro amosado idéntico non é proba de variación física cero nin de erro de medición cero.",
    fields: ["Obxectivo", "Resultado medido", "Tolerancia permitida", "Capacidade do instrumento"],
    fieldsNote: "Consérvanse como campos separados en cada rexistro.",
    matchedTitle: "Xogos emparellados",
    matchedP: "Os criterios dos xogos emparellados defínense á parte da tolerancia individual. A conformidade de cada raqueta coa súa tolerancia nominal non demostra por si soa unha diferenza máxima determinada entre dúas raquetas. As parellas, os tríos e os xogos de equipo emparellados solicítanse a través do configurador e confírmanse por escrito.",
    extendedTitle: "Modelo técnico ampliado",
    extendedP: "O modelo de datos admite parámetros adicionais. Aínda non existen valores nin clases de tolerancia para eles; pódense indicar como obxectivos solicitados nun informe técnico.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Comportamento torsional", length: "Lonxitude", beamProfile: "Perfil do marco", headGeometry: "Xeometría da cabeza", stringPattern: "Patrón de cordaxe", durability: "Durabilidade", vibration: "Características de vibración" },
    noZero: "MAXIMUS non describe a súa gama do catálogo como unha gama de tolerancia cero. A precisión da gama exprésase como unha clase cunha tolerancia declarada e unha arquitectura de control de calidade definida. ZERO non forma parte da gama.",
    zero: {
      eyebrow: "Opción exclusiva",
      title: "ZERO",
      sub: "Tolerancia de cero gramos.",
      p: "As tres clases manteñen unha raqueta acabada dentro dunha banda declarada. ZERO elimina a banda. A raqueta constrúese e mídese ata que a lectura iguala a cifra declarada na resolución do instrumento de fábrica, e esa lectura entrégase con ela. Non forma parte da gama do catálogo nin é unha cuarta clase: acórdase individualmente, para unha raqueta ou un xogo emparellado, como unha exclusividade feita á medida. Por acordo, o mesmo enfoque aplícase ao balance e ao swingweight.",
      points: [
        ["Sen banda", "A cifra declarada é o resultado, non o centro dunha tolerancia."],
        ["Unha cada vez", "Construída, medida e rexistrada como unha unidade única."],
        ["Entregada coa raqueta", "A lectura medida entrégase e consérvase no rexistro de produción."],
        ["Confirmada por escrito", "Os parámetros, o alcance e o prazo acórdanse antes de producir."],
      ],
      note: "Emparellada na resolución do instrumento de medición de fábrica. Unha cifra amosada idéntica non é unha afirmación de variación física cero. A dispoñibilidade e as condicións acórdanse individualmente para cada pedido.",
      cta: "Solicitar ZERO",
    },
    cta: "Configurar cunha clase de precisión",
  },
  grip: {
    title: "Arquitectura de empuñadura de fábrica",
    statement: "Oito medidas de empuñadura de fábrica. L0–L7.",
    lead: "A xeometría da empuñadura forma parte da arquitectura do mango de carbono. Cada medida fabrícase como xeometría de mango, non se engrosa con sobreempuñaduras.",
    emph: "Medidas ampliadas",
    p1: "A gama de fábrica de oito medidas dálles a adestradores e xogadores un abano de configuración máis amplo co que especificar o equipamento arredor do xogador, incluídas as xeometrías maiores L6 e L7.",
    p2: "A designación nominal da empuñadura é distinta das dimensións estruturais brutas do mango e do protocolo de medición final. As medidas aplícanse ás series de rendemento e ás familias de adestramento desta plataforma.",
    p3: "Non se fai ningunha afirmación de exclusividade mundial para esta gama.",
    columns: { size: "Medida", nominal: "Nominal", family: "Aplícase a" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Configurar coa súa medida de empuñadura",
  },
  custom: {
    title: "Enxeñaría personalizada",
    statement: "Deseñada segundo especificación.",
    sub: "A gama estándar é o punto de partida.",
    lead: "MAXIMUS acepta requisitos técnicos máis alá das matrices de configuración publicadas para avalialos, deseñalos, validalos e fabricalos segundo unha especificación acordada. A viabilidade confírmase mediante revisión — non toda solicitude imaxinable é física ou comercialmente viable.",
    scopeTitle: "Que pode abordar un informe técnico",
    scope: ["Xeometría da cabeza e do marco", "Lonxitude", "Peso", "Balance", "Swingweight", "Rixidez", "Twistweight", "Xeometría da empuñadura", "Construción", "Xogos emparellados", "Marcos de adestramento", "Estética e gravado", "Identidade e programas de equipo", "Desenvolvemento dependente de ferramentaxe"],
    processTitle: "Proceso",
    process: [
      ["Definir", "Obxectivos preferidos, límites obrigatorios, uso previsto e compromisos aceptables."],
      ["Deseñar", "Avaliación de enxeñaría fronte á plataforma e á ferramentaxe."],
      ["Validar", "Validación fronte á especificación acordada."],
      ["Especificar", "Unha especificación escrita coa base de medición e as tolerancias."],
      ["Producir", "Produción segundo a especificación."],
      ["Medir / rexistrar", "Medición e rexistros conservados segundo a clase de precisión aplicable."],
    ],
    formTitle: "Presentar un informe técnico",
    formLead: "Distinga os obxectivos preferidos dos límites obrigatorios. O resultado é unha solicitude de revisión técnica, non un pedido de fabricación aceptado automaticamente.",
    protected: "As receitas de laminado, a ferramentaxe, a identidade dos provedores, os cálculos de custo internos e o coñecemento protexido non se revelan por esta vía.",
    cta: "Presentar un informe técnico",
  },
  training: {
    title: "Sistemas de adestramento",
    lead: "Dúas familias de adestramento cos seus propios estándares de produción, unidas por unha soa metodoloxía: práctica dirixida polo adestrador, rexistros, reavaliación e volta ao xogo de rendemento.",
    sst: { h: "Sweet Spot Trainer", p: "Unha raqueta de adestramento de cabeza reducida de 50 in² nun sistema de catro pesos para practicar o contacto centrado, a consciencia do sweet spot, o control da raqueta e a carga progresiva." },
    spot: { h: "Spot Trainer", p: "Adestramento do punto de contacto cun pequeno obxectivo redondo, sobre a base aprobada de catro pesos." },
    method: { h: "Metodoloxía", p: "Fixar obxectivos, escoller o equipamento coa participación do adestrador, empregar o sistema correspondente, rexistrar, reavaliar, axustar e transferir." },
    experience: "Colla. Golpee. Sinta.",
    experienceP: "Solicite unha proba, un axuste ou unha demostración co apoio dun adestrador. Unha solicitude enviada non é unha cita confirmada.",
    cta: "Solicitar un axuste ou demostración",
    distinct: "Sweet Spot Trainer, Spot Trainer e calquera dispositivo de demostración independente son produtos distintos e nunca se fusionan.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Unha categoría de adestramento separada co seu propio estándar de produción. A cabeza de 50 in² concentra a atención no punto de contacto; os catro pesos achegan a progresión de carga.",
    baseline: "Base confirmada",
    columns: { head: "Cabeza", length: "Lonxitude", pattern: "Patrón de cordaxe", grips: "Empuñaduras de fábrica" },
    systemTitle: "Sistema de catro raquetas",
    detailsTitle: "Detalles de construción",
    systemLead: "Peso e balance tal como se subministran. A base de medición rexístrase á parte e aínda non se publicou.",
    purposeTitle: "Finalidade",
    purpose: ["Práctica do contacto centrado", "Consciencia do sweet spot", "Control da raqueta", "Carga progresiva", "Desenvolvemento dirixido polo adestrador", "Volta á raqueta de rendemento do xogador"],
    heavy: "O modelo de 400 g é unha configuración de adestramento controlada. Non se recomenda automaticamente a nenos, principiantes nin a todos os xogadores; o adestrador define a carga, a duración e a progresión.",
    precisionNote: "As clases de precisión de rendemento P2.5, P1.5 e P0.5 non se aplican automaticamente a esta familia de adestramento. As tolerancias de produción de adestramento seguen a especificación aprobada da propia familia.",
    health: "Non se promete ningunha prevención ou tratamento do cóbado de tenista, nin a eliminación de lesións, nin ningunha mellora garantida.",
    cta: "Solicitar unha demostración do Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Adestramento do punto de contacto cun pequeno obxectivo redondo. Un produto diferenciado coa súa propia identidade visual, construído sobre a base aprobada de catro pesos.",
    purposeTitle: "Finalidade confirmada",
    purposeP: "Adestrar o xogador para atopar e repetir un punto de contacto preciso.",
    weightsTitle: "Progresión de pesos",
    weightsP: "A progresión de pesos segue a base de pesos aprobada do Sweet Spot Trainer. Os valores de balance e outras especificacións do Sweet Spot Trainer non se copian ao Spot Trainer.",
    dims: "As dimensións exactas do obxectivo aínda non se publicaron.",
    grips: "Arquitectura de empuñadura de fábrica L0–L7.",
    notes: ["As clases de precisión de rendemento non se aplican automaticamente.", "Non é unha raqueta convencional en miniatura e non se publica ningún patrón de cordaxe.", "Spot Trainer, Sweet Spot Trainer e calquera dispositivo de demostración independente seguen sendo distinguibles."],
    cta: "Preguntar sobre o Spot Trainer",
  },
  methodology: {
    title: "Metodoloxía e experiencia de produto",
    lead: "O equipamento é unha parte dun percorrido de desenvolvemento estruturado. O método comeza cos obxectivos do xogador, non cunha etiqueta de produto.",
    stepsTitle: "O percorrido de desenvolvemento",
    steps: [
      ["Fixar obxectivos", "Os obxectivos do xogador e o punto de partida."],
      ["Escoller o equipamento", "Equipamento axeitado escollido coa participación do adestrador."],
      ["Empregar o sistema", "O sistema de adestramento correspondente, dirixido polo adestrador."],
      ["Rexistrar", "Observacións da participación real, sen puntuacións inventadas."],
      ["Reavaliar", "Puntos de control comparables."],
      ["Axustar", "Axustes de configuración ou de programa."],
      ["Transferir", "A aprendizaxe transfírese ao xogo de rendemento."],
    ],
    educationTitle: "Vías de formación",
    education: { player: "Xogadores — entender a configuración, a carga e a progresión.", parent: "Pais — continuidade do desenvolvemento, equipamento axeitado, rexistros e dereitos.", coach: "Adestradores — sistemas de adestramento, axuste, avaliación e uso autorizado dos programas." },
    evidenceTitle: "Disciplina da evidencia",
    evidenceP: "Os rexistros de participación real e as observacións consérvanse coa súa clasificación — declarada polo participante, confirmada polo titor, validada polo adestrador ou medida polo sistema. O progreso, as puntuacións e a validación nunca se inventan.",
    experienceTitle: "Colla. Golpee. Sinta.",
    experienceP: "Pódese solicitar unha proba, un axuste ou unha demostración co apoio dun adestrador. Unha solicitude enviada non é unha cita confirmada.",
    cta: "Solicitar axuste ou demostración",
    cta2: "Consulta de colaboración para adestradores",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — perfil de equipamento guiado",
    title: "MAXIMUS GPS",
    lead: "Un perfil de equipamento guiado. Responda só o que sexa relevante; revise e corrixa as súas respostas; reciba un resumo, as direccións de configuración que se aplican e unha acción seguinte real.",
    honesty: "Nesta versión non hai regras de axuste automático aprobadas. Por iso, o GPS produce un resumo claro de requisitos e sinala direccións de configuración; os detalles do equipamento derívanse a revisión experta.",
    rulesVersion: "Versión das regras",
    dataVersion: "Versión dos datos de produto",
    steps: { role: "Perfil", sport: "Deporte", experience: "Experiencia", objectives: "Obxectivos", style: "Estilo de xogo", equipment: "Equipamento actual", preference: "Preferencias", coach: "Participación do adestrador", ageBand: "Franxa de idade", review: "Revisión" },
    notStored: "Non se garda neste navegador.",
    ageNote: "Emprégase só para derivar a solicitude. Non se pide ningún nome, data de nacemento nin información médica.",
    q: {
      role: "Que o describe?",
      sport: "Que deporte?",
      experience: "Nivel de experiencia",
      objectives: "Que é o máis importante? (escolla ata tres)",
      style: "Estilo de xogo, se o coñece",
      equipment: "Equipamento actual, se o ten",
      equipmentHint: "Marca e modelo, peso ou empuñadura se os coñece. Opcional.",
      preference: "Configuración preferida ou medida de empuñadura coñecida",
      grip: "Medida de empuñadura coñecida",
      coach: "Participa un adestrador nas súas decisións de equipamento?",
      ageBand: "Franxa de idade do xogador (emprégase só para derivar a solicitude correctamente)",
    },
    roles: { player: "Xogador", parent: "Pai, nai ou titor", coach: "Adestrador", club: "Club ou academia", other: "Outro" },
    sports: { tennis: "Tenis", padel: "Pádel", pickleball: "Pickleball", squash: "Squash", badminton: "Bádminton", other: "Outro deporte de raqueta" },
    sportNote: "Existen produtos para o tenis. Os outros deportes son direccións de desenvolvemento; o seu interese rexístrase para o programa correspondente.",
    experience: { beginner: "Principiante", developing: "En progreso", intermediate: "Intermedio", advanced: "Avanzado", competitive: "De competición", professional: "Profesional" },
    objectives: { control: "Control", power: "Potencia", spin: "Efecto", comfort: "Confort", manoeuvrability: "Manexabilidade", development: "Desenvolvemento a longo prazo", competition: "Competición", training: "Sistema de adestramento", team: "Equipo ou xogo emparellado", personal: "Personalización" },
    styles: { baseline: "De fondo", allcourt: "Xogo completo", attacking: "Ofensivo", defensive: "Defensivo", coach: "Escóllelo o adestrador", unknown: "Non o sei con certeza" },
    ageBands: { u10: "Menos de 10 anos", u14: "10–13", u18: "14–17", adult: "18 anos ou máis" },
    output: {
      title: "O seu perfil de equipamento",
      status: "Precísase revisión experta",
      statusP: "Nesta versión non se produce ningunha coincidencia automática. O seu perfil resumiuse para a revisión experta.",
      directionsTitle: "Direccións de configuración que se aplican",
      directionsP: "Segundo os obxectivos que indicou e a dirección de xogo declarada de cada serie. É unha dirección, non unha recomendación de axuste.",
      trainingHint: "Os seus obxectivos inclúen un sistema de adestramento: vexa Sweet Spot Trainer e Spot Trainer.",
      teamHint: "Os xogos emparellados solicítanse a través do configurador e confírmanse por escrito.",
      next1: "Enviar o perfil a revisión experta",
      show: "Amosar o meu perfil",
      configure: "Configurar",
      sendP: "Envíe o seu perfil a MAXIMUS para a revisión experta. O identificador de solicitude amósase de inmediato; a resposta chega por escrito.",
      otherSport: "As raquetas MAXIMUS existen para o tenis. Para outros deportes de raqueta non se propón ningunha serie de tenis; o seu interese rexístrase como unha dirección de desenvolvemento.",
      noDirection: "Os seus obxectivos non apuntan a unha soa dirección de xogo. A revisión experta propón unha configuración.",
      incomplete: "Faltan algunhas respostas obrigatorias — empregue «Editar as respostas» para completalas.",
    },
    privacy: "O GPS non pide información de saúde nin identificadores de menores. Nesta sesión do navegador consérvanse só as respostas de opción múltiple; o texto libre non se garda.",
  },
  build: {
    title: "Configure a súa",
    lead: "Configure unha solicitude: serie, clase de precisión, peso do catálogo ou obxectivo personalizado, medida de empuñadura, obxectivos solicitados, personalización, xogos emparellados e cantidade. O resultado é unha solicitude de configuración cun identificador — non un SKU, un prezo, unha data de entrega ou un certificado.",
    steps: { series: "Serie", cls: "Clase de precisión", weight: "Peso", grip: "Empuñadura", targets: "Obxectivos", personal: "Personalización", set: "Xogo e cantidade", use: "Uso", review: "Revisión" },
    q: {
      series: "Escolla unha serie",
      cls: "Escolla unha clase de precisión",
      weightMode: "Peso",
      listed: "Peso do catálogo",
      customWeight: "Peso solicitado (g)",
      balanceShown: "Balance calculado para este peso",
      balanceRequest: "Balance solicitado (mm)",
      grip: "Medida de empuñadura de fábrica",
      targetsTitle: "Obxectivos solicitados",
      swingweight: "Swingweight solicitado (kg·cm²)",
      stiffness: "Rixidez solicitada (RA)",
      basis: "Base de medición dos valores solicitados",
      engraving: "Texto do gravado",
      engravingHint: "Nome, iniciais ou número. Letras latinas, cifras, espazo, guión, apóstrofo e punto; ata 24 caracteres. Acéptanse outras escrituras con confirmación da arte final.",
      engravingType: "Personalización",
      types: { none: "Ningunha", name: "Nome do xogador", initials: "Iniciais", number: "Número do xogo", academy: "Identificación de adestrador ou academia", team: "Programa de equipo" },
      set: "Raqueta individual ou xogo emparellado",
      use: "Uso previsto",
      uses: { play: "Xogo persoal", competition: "Competición", coaching: "Adestramento", team: "Equipo ou academia", retail: "Avaliación de venda ou distribución", other: "Outro" },
      notes: "Requisitos técnicos adicionais",
    },
    classes: { "P2.5": "P2.5 — núcleo de rendemento escalable", "P1.5": "P1.5 — precisión avanzada", "P0.5": "P0.5 — profesional, controlada individualmente" },
    stiffExactShort: "a rixidez axústase ao valor RA declarado baixo o protocolo de fábrica establecido",
    clsNote: "Cada clase controla catro parámetros. P0.5 é unha tolerancia estreita baixo un protocolo de medición definido — non é erro cero. A identidade de serie, os certificados e a documentación de xogos emparellados aplícanse só cando o programa do seu pedido os implementa.",
    listedNote: "Da matriz confirmada da serie.",
    customNote: "Un peso fóra da matriz, revisado tecnicamente.",
    balanceCaption: "Cada peso do catálogo amosa o seu balance calculado en mm dende o tapón. Os valores calculados non son medicións individuais.",
    spinNote: "Os pesos de SPIN forman a arquitectura de peso solicitada. O balance, o swingweight e a rixidez de SPIN non se facilitan; defínense na revisión técnica.",
    customHint: "Gramos enteiros, só cifras. Un peso personalizado é unha solicitude de revisión técnica; a viabilidade confírmase por escrito e ningún valor se arredonda.",
    gripNote: "xeometría de mango de carbono de fábrica, non un engrosamento con sobreempuñaduras",
    targetsLead: "Opcional. Introduza só os valores que precise. Cada un rexístrase como un obxectivo solicitado para a revisión técnica, non como unha especificación publicada.",
    basisHint: "Obrigatorio cando solicita un peso personalizado ou calquera obxectivo: os valores refírense a unha raqueta sen cordaxe ou con cordaxe?",
    inputRange: "Entrada aceptada: {min}–{max}.",
    inputRangeNote: "Os intervalos de entrada só descartan valores imposibles. Non describen a capacidade de produción.",
    listedBasis: "valores do catálogo — base de medición confirmada na especificación escrita",
    notStored: "Non se garda neste navegador; introdúzao de novo se recarga a páxina.",
    artworkReview: "precísase confirmación da arte final",
    previewNote: "Non se amosa ningunha previsualización: aínda non se publicou un modelo de gravado aprobado para este produto. O seu texto recóllese para confirmar a arte final.",
    teamSub: "4–99 raquetas por xogo",
    setsLabel: { individual: "Número de raquetas", pair: "Número de parellas emparelladas", triple: "Número de tríos emparellados", team: "Número de xogos de equipo" },
    teamSizeLabel: "Raquetas por xogo de equipo",
    totalLabel: "Raquetas en total",
    racquetsUnit: "raquetas",
    setRule: "A cantidade conta xogos: unha parella emparellada son 2 raquetas por xogo; un trío emparellado, 3.",
    restart: "Comezar unha configuración nova",
    notices: { weightCleared: "{w} g non está na matriz da serie {series}, polo que se borrou o peso. Escolla un peso do catálogo ou solicite un obxectivo personalizado." },
    reviewTitle: "Solicitude de configuración",
    reviewP: "Comprobe a configuración e engada os seus datos de contacto. A solicitude gárdase cun identificador e respóndese por escrito; a dispoñibilidade e as condicións comerciais confírmanse por escrito.",
    reviewErrors: "Hai respostas da configuración que precisan atención:",
    edit: "Editar",
    fieldNames: { series: "Serie", cls: "Clase de precisión", mode: "Selección do peso", weight: "Peso do catálogo", customWeight: "Peso solicitado", basis: "Base de medición", balanceReq: "Balance solicitado", sw: "Swingweight solicitado", ra: "Rixidez solicitada", grip: "Medida de empuñadura", ptype: "Personalización", engraving: "Texto do gravado", setType: "Tipo de xogo", sets: "Cantidade", teamSize: "Raquetas por xogo de equipo", use: "Uso previsto", notes: "Requisitos adicionais" },
    status: { listed: "peso do catálogo", requestedArchitecture: "arquitectura de peso solicitada", technicalReview: "solicitude de revisión técnica", notPublished: "non facilitado", requestedCondition: "condición solicitada" },
    chooseLink: "Non sabe que serie lle convén? Pida axuda para escoller",
    cta: "Enviar a solicitude de configuración",
  },
  experience: {
    title: "Experiencia e axuste",
    statement: "Colla. Golpee. Sinta.",
    lead: "Solicite unha proba, un axuste ou unha demostración co apoio dun adestrador. As solicitudes revísanse e respóndense por escrito; unha solicitude enviada non é unha cita confirmada.",
    optionsTitle: "Que se pode solicitar",
    options: ["Proba de raquetas", "Sesión de axuste", "Demostración co apoio dun adestrador", "Demostración do Sweet Spot Trainer ou do Spot Trainer", "Xornada de probas para equipos ou academias"],
    formTitle: "Solicitude de axuste ou demostración",
  },
  engineering: {
    title: "Enxeñaría e fabricación",
    statement: "Avións. Iates. Raquetas.",
    lead: "Unha soa filosofía de enxeñaría en tres contornos: os principios que dan forma a un avión, a precisión que guía un iate por mar aberto, o rendemento que define cada raqueta MAXIMUS. É un relato de enxeñaría — non unha afirmación de certificación aeronáutica, propiedade de iates, propiedade de fábricas nin transferencia directa de materiais.",
    manifesto: ["Cremos que a boa enxeñaría non ten fronteiras.", "Unha filosofía. Deseñada sen concesións."],
    capabilityTitle: "Capacidade de fabricación",
    capabilityLead: "A capacidade amósase como unha secuencia, non como un slogan.",
    sequence: [
      ["Especificación", "Serie, clase de precisión, peso, balance, swingweight, obxectivo de rixidez, xeometría da empuñadura, personalización."],
      ["Produción", "Construción integramente de carbono do marco ao mango, producida segundo a especificación."],
      ["Control de calidade", "Medición e rexistros segundo a clase de precisión: rexistros de produción, rexistros individuais e rastreabilidade, certificación individual."],
      ["Produción repetida", "Resposta repetible fronte a unha especificación declarada entre lotes."],
      ["Rastreabilidade", "Identidade de serie, rastreabilidade de lote e Certificado de Precisión cando a clase o prevé."],
    ],
    capacityNote: "A capacidade de produción, os prazos, as cantidades mínimas e os calendarios de entrega confírmanse por escrito para cada programa, fronte a pedidos confirmados e un calendario de liberación acordado.",
    truth: "A capacidade non é produción, nin existencias, nin unha data de entrega garantida, nin a propiedade dunha planta de fabricación.",
    cta: "Distribución e desenvolvemento de países",
    cta2: "Presentar un informe técnico",
  },
  ecosystem: {
    title: "O ecosistema MAXIMUS",
    lead: "Unha chave. Isto é o que abre. Cada nodo ten unha explicación, un estado exacto e unha acción seguinte pertinente.",
    words: ["Enxeñaría", "Rendemento", "Innovación", "Comunidade", "Oportunidade", "Propósito"],
    nodes: {
      engineering: { h: "Enxeñaría e fabricación de raquetas", p: "Raquetas integramente de carbono deseñadas segundo especificación, producidas con rexistros de calidade e rastreabilidade.", a: "Enxeñaría e fabricación" },
      precision: { h: "Precisión e configuración individual", p: "Catro parámetros, tres clases de precisión, oito medidas de empuñadura e enxeñaría personalizada.", a: "Precisión e rixidez" },
      training: { h: "Adestramento e metodoloxía", p: "Sweet Spot Trainer, Spot Trainer e un percorrido de desenvolvemento estruturado.", a: "Sistemas de adestramento" },
      development: { h: "Desenvolvemento de xogadores e adestradores", p: "Selección dirixida polo adestrador, rexistros, reavaliación e vías de formación.", a: "Metodoloxía" },
      identity: { h: "Identidade persoal e marcas persoais", p: "Do gravado a unha marca persoal ou profesional rexida por dereitos.", a: "Marcas persoais" },
      owners: { h: "Rexistros, coñecemento e dereitos dos propietarios", p: "Un arquivo seguro de propietario con permisos, proposto para rexistros de equipamento, desenvolvemento e dereitos.", a: "Propietarios e o arquivo seguro" },
      mipa: { h: "Procedencia MIPA e control interno", p: "A capa interna de propiedade intelectual, procedencia e control documental.", a: "Identidade legal e control" },
      digital: { h: "Infraestrutura dixital e dirección Blockchain 5.0", p: "Procedencia, rexistros rastreables, evidencia con permisos e identidade de produto como dirección tecnolóxica declarada.", a: "Dirección tecnolóxica" },
      licensing: { h: "Licenzas contractuais e programas de canons", p: "Marcas, produtos e paquetes de dereitos licenciados con condicións definidas por acordo.", a: "Vías de licenza" },
      families: { h: "Participación familiar e beneficios do programa", p: "Decisións informadas, continuidade, rexistros conservados e beneficios definidos polo programa.", a: "Familias e pais" },
      network: { h: "MAXIMUS Sports Network", p: "Xogadores, adestradores, clubs, academias, provedores de servizos, operadores e socios rexionais.", a: "Sports Network" },
      market: { h: "Clubs, academias, distribución e desenvolvemento de países", p: "Programas de equipo, venda polo miúdo, distribución e desenvolvemento de territorios con cualificación por escrito.", a: "Vías de colaboración" },
      institutional: { h: "Programas institucionais, formación, innovación e impacto social", p: "A capa institucional que achega MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) cando un programa establece ese papel.", a: "Programas institucionais" },
      extensions: { h: "Futuras extensións a deportes de raqueta e roupa MAXIMUS", p: "Pádel, pickleball, squash, bádminton, racquetball, tenis praia e roupa como direccións de desenvolvemento.", a: "Deportes de raqueta" },
    },
    boundaryTitle: "Límites",
    boundary: [
      "A compra dunha raqueta non crea afiliación institucional, dereitos de goberno, canons nin dereitos de investimento.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) é o operador institucional só cando un programa establece ese papel; as vendas de equipamento identifican a súa entidade contratante real.",
      "As subvencións, o estatuto benéfico, o tratamento fiscal e os permisos regulatorios non se aplican automaticamente en todos os países.",
    ],
    techTitle: "Dirección tecnolóxica",
    techP: "Blockchain 5.0 é a dirección tecnolóxica declarada de MAXIMUS. As súas finalidades funcionais son a procedencia, os rexistros rastreables, a evidencia con permisos, a identidade de produto e a conciliación de eventos comerciais que cumpran as condicións. Non se representa ningún mecanismo de consenso, capacidade de transacción, rede de nodos, enderezo de contrato intelixente, token nin certificación independente, e non se afirma ningunha implementación despregada. A información persoal, os rexistros de menores e os acordos confidenciais nunca se colocan por defecto nun sistema público inmutable.",
  },
  brands: {
    title: "Marcas persoais e embaixadores",
    statement: "Do xogador á marca. Do adestrador á marca.",
    lead: "Unha vía dedicada á marca persoal. A participación de MAXIMUS inclúe o desenvolvemento de marca e a promoción acordada — non só un nome nunha raqueta.",
    progressionTitle: "Progresión prevista",
    progression: [
      ["Identidade verificada", "Unha identidade verificada e un historial de desenvolvemento."],
      ["Marca distintiva", "Unha marca persoal ou profesional distintiva."],
      ["Contido con dereitos resoltos", "Contido con dereitos resoltos e identidade de produto aprobada."],
      ["Enxeñaría e coleccións", "Enxeñaría e desenvolvemento de coleccións cando se acorde."],
      ["Promoción", "Promoción a través das canles e as colaboracións MAXIMUS acordadas."],
      ["Participación", "Participación contractual en vendas ou licenzas que cumpran as condicións."],
      ["Informes", "Informes transparentes segundo o acordo."],
    ],
    royaltiesTitle: "Canons e licenzas",
    royalties: [
      "Os canons asócianse á marca, ao produto, á operación ou ao paquete de dereitos licenciado definido.",
      "«Vendas mundiais» significa vendas que cumpran as condicións dentro do alcance do contrato — nunca cada raqueta MAXIMUS allea.",
      "As taxas, a base de cálculo, os territorios, o prazo, as devolucións, as deducións, os informes, a liquidación e a verificación defínense no acordo correspondente. Non se publica ningunha porcentaxe de canon por defecto.",
      "Non se promete ningunha campaña global, orzamento de medios, resultado de patrocinio nin éxito comercial sen un alcance acordado.",
    ],
    cta: "Enviar unha consulta de colaboración de marca",
    cta2: "Consulta de colaboración para adestradores",
  },
  families: {
    title: "Familias e pais",
    lead: "Decisións de equipamento informadas, continuidade do desenvolvemento, coñecemento e dereitos conservados, visibilidade da participación e beneficios definidos polo programa que poden apoiar actividades futuras.",
    nowTitle: "Dispoñible agora",
    now: ["Consultas familiares e de desenvolvemento por escrito.", "Selección de equipamento coa participación do adestrador, axuste e solicitudes de demostración.", "Rexistros privados: os perfís dos menores nunca se publican nin se comercializan por defecto.", "Vía de formación para pais: configuración, carga, progresión, rexistros e dereitos."],
    plannedTitle: "Previsto",
    planned: ["Beneficios de participación definidos polo programa, utilizables para bens e servizos dentro do ecosistema, en lugar de xuros en efectivo.", "Rexistros de propietarios e familias no arquivo seguro proposto, con permisos do titor e unha transición do control aos 18 anos."],
    categoriesTitle: "Mantéñense separados",
    categories: ["Canons contractuais derivados de dereitos licenciados ou vendas que cumpran as condicións", "Beneficios de participación definidos por un programa", "Créditos de compra ou de servizo", "Pagamentos anticipados", "Afiliación institucional"],
    categoriesP: "Estas categorías nunca se tratan como intercambiables.",
    statusTitle: "Estado real do programa familiar",
    journeyTitle: "A vía familiar",
    journey: [
      ["Obxectivo", "Que quere acadar o xogador a continuación."],
      ["Nivel actual", "Onde está o xogador hoxe."],
      ["Adestrador", "Se un adestrador participa nas decisións de equipamento."],
      ["Equipamento", "Equipamento axeitado para a etapa, incluídos os sistemas de adestramento cando corresponda."],
      ["Práctica acordada", "Uso dirixido polo adestrador acordado por adiantado."],
      ["Revisión", "Reavaliación en puntos de control comparables."],
    ],
    brief: {
      who: "Pais e titores de xogadores en calquera etapa.",
      value: "Unha resposta escrita sobre o equipamento axeitado, a participación do adestrador e o paso seguinte do desenvolvemento.",
      now: "Consultas familiares por escrito; selección coa participación do adestrador; rexistros privados — os perfís dos menores nunca se publican.",
      next: "Envíe a consulta familiar a continuación. Recibirá un identificador de solicitude de inmediato.",
    },
    formTitle: "Consulta familiar",
    formNote: "Debe cubrila un pai, unha nai ou un titor. Non inclúa o nome do menor, a data de nacemento, a escola nin información médica.",
    noPromise: "Unha compra non promete canons, rendementos de investimento, patrocinio nin financiamento do desenvolvemento dun menor.",
    statusP: "Esta versión explica o modelo e acepta consultas de programa. A acumulación, os pagamentos e o resgate non están dispoñibles ata que os eventos que cumpran as condicións, os beneficiarios, a fonte de financiamento, a base de cálculo, os usos permitidos, o tratamento contable, as devolucións, as reversións, a caducidade, a transferibilidade, o peche do programa e a xestión de conflitos se definan por escrito. Non se promete ningún saldo que nunca baixe, ningunha participación paga todo o adestramento e non se insinúa ningunha protección do capital.",
    cta: "Enviar unha consulta familiar ou de desenvolvemento",
  },
  owners: {
    title: "Propietarios e o arquivo seguro do propietario",
    lead: "O arquivo seguro do propietario é un rexistro con permisos, proposto, de equipamento, desenvolvemento, coñecemento, contido e dereitos documentados. Preséntase como parte da arquitectura de propietarios prevista: non se amosan contas, saldos, certificados nin logros activos.",
    nowTitle: "Para os propietarios actuais agora",
    now: ["Consultas de propietarios: referencia de produto ou de serie, posta a punto, servizo e solicitudes de rexistros por escrito.", "Certificado de Precisión e documentación de xogos emparellados cando a clase de precisión os prevé, entregados co produto."],
    archTitle: "Arquitectura prevista do arquivo seguro",
    arch: ["Identidade de produto e referencias de serie", "Configuración e certificados de control de calidade aplicables", "Historial de servizo e posta a punto", "Rexistros de desenvolvemento do xogador ou do adestrador", "Cualificacións e logros verificados", "Material con dereitos resoltos e materiais de autoría propia", "Licenzas, permisos e referencias contractuais", "Rexistros do programa de marca persoal", "Extractos de canons aplicables ou beneficios de participación"],
    separationTitle: "Que significa ser propietario",
    separation: [
      "A propiedade dunha raqueta física é independente da titularidade dos dereitos de autor, dunha licenza, dun dereito contractual ou dun rexistro que describa esas cousas.",
      "Un documento gardado ou unha entrada nunha cadea de bloques non é automaticamente proba de que un dereito legal exista ou se transferise.",
      "A evidencia conserva a súa clasificación: declarada polo participante, confirmada polo titor, validada polo adestrador, medida polo sistema.",
      "Para os menores: rexistros privados, permisos do titor, ningún perfil de menor publicado e ningunha comercialización da identidade por defecto.",
      "A exportación, a corrección, o control de acceso e unha transición do control axeitada forman parte do deseño.",
    ],
    techTitle: "Blockchain 5.0 e MxSN",
    techP: "Blockchain 5.0 é a dirección tecnolóxica declarada; MxSN define os conceptos dunha rede con permisos para o consentimento, a entrega, a evidencia, os dereitos e os informes. Non se representa ningunha implementación operativa. O modelo de datos da aplicación está construído para integrarse máis adiante mediante unha interface documentada, sen pretender que hoxe exista unha conexión.",
    cta: "Consulta de propietario",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "A conexión entre xogadores, adestradores, clubs, academias, provedores de servizos, operadores de programas e socios rexionais.",
    functionsTitle: "Funcións potenciais",
    functions: ["Descubrimento", "Presentacións", "Programas de desenvolvemento", "Apoio de equipamento", "Eventos", "Acceso a servizos", "Oportunidades para socios"],
    statusTitle: "Estado real",
    statusP: "Aínda non se publica ningún directorio público: só se listarán os participantes con identidade, relación e permiso para aparecer establecidos. Unha proposta enviada a un club non é unha colaboración, e un distribuidor potencial non é un distribuidor designado. A publicación do directorio, as reservas, a mensaxaría e as operacións comerciais contrólanse á parte e non están activas.",
    cta: "Solicitar a entrada na rede",
  },
  partnerships: {
    title: "Vías de colaboración",
    lead: "Primeiro a cualificación por escrito. Cada vía leva a unha consulta específica do perfil; as condicións comerciais chegan despois por escrito.",
    commercialTitle: "Actividades comerciais potenciais da plataforma",
    commercial: ["Equipamento", "Enxeñaría personalizada", "Personalización", "Programas de equipos e academias", "Sistemas de adestramento", "Licenzas contractuais", "Distribución", "Servizos aprobados", "Futuras categorías de produto"],
    boundary: "Os dereitos de país, a exclusividade, as taxas de territorio e as marxes do distribuidor son condicións negociadas. Non se publica ningún ingreso, previsión, valoración, cota de mercado, retorno, compromiso de financiamento nin colaboración sen nome.",
    routes: {
      coaches: {
        title: "Adestradores",
        lead: "Sistemas de adestramento, axuste, identidade profesional, programas autorizados, oportunidades de marca persoal e subministración de equipamento.",
        points: ["Sweet Spot Trainer e Spot Trainer na práctica dirixida polo adestrador.", "Axuste coas matrices de configuración e as oito medidas de empuñadura de fábrica.", "Coach-to-Brand: un perfil profesional verificado e unha submarca rexida por dereitos.", "O uso autorizado dos programas segue un acordo escrito."],
        cta: "Enviar unha consulta de colaboración para adestradores",
        brief: {
          who: "Adestradores independentes e equipos técnicos.",
          value: "Sistemas de adestramento para a práctica dirixida polo adestrador, axuste coas matrices das series e as oito empuñaduras de fábrica, e unha vía cara a unha identidade profesional.",
          now: "Consultas de adestradores por escrito. Non se publica nin se insinúa ningunha comisión, ganancia ou tarifa de recomendación.",
          next: "Envíe a consulta de adestrador a continuación. As condicións chegan por escrito.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Clubs e academias",
        lead: "Equipamento de equipo, sistemas de adestramento, personalización, programas de desenvolvemento, servizo e participación na rede.",
        points: ["Xogos de equipo e emparellados solicitados a través do configurador.", "Sistemas de adestramento e metodoloxía para un desenvolvemento estruturado.", "Personalización para programas de equipo nas zonas aprobadas.", "Xornadas de proba, sesións de axuste e participación na rede."],
        cta: "Enviar un informe de club ou academia",
        brief: {
          who: "Clubs, academias e programas de equipo.",
          value: "Xogos de equipo e emparellados, sistemas de adestramento, personalización para programas de equipo e xornadas de demostración.",
          now: "Informes de clubs e academias por escrito; os xogos de equipo solicítanse a través do configurador.",
          next: "Envíe o informe de club ou academia a continuación.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribución e desenvolvemento de países",
        lead: "Surtido, coordinación da fabricación, capacidade técnica, desenvolvemento de territorios e cualificación comercial confidencial.",
        points: ["Cualificación por escrito da contraparte, o territorio e a canle.", "Surtido definido a partir das matrices de configuración e das clases de precisión.", "O territorio, a exclusividade, os volumes, os prezos e a protección comercial son condicións negociadas e acordadas por escrito.", "A entidade contratante, as condicións de pagamento e a base de entrega identifícanse para cada operación."],
        cta: "Enviar unha consulta de distribución ou desenvolvemento de país",
        brief: {
          who: "Tendas, distribuidores e socios de país.",
          value: "Un surtido definido a partir das matrices confirmadas, das clases de precisión e da gama de empuñaduras, con cualificación por escrito do territorio e da canle.",
          now: "Consultas de distribución por escrito. O territorio, a exclusividade, os volumes e os prezos negócianse — nada se concede a través dun formulario.",
          next: "Envíe a consulta de distribución a continuación.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Estratexia e investimento",
        lead: "Capacidade de enxeñaría, profundidade de configuración, modelo de fabricación, vías ao mercado, propiedade intelectual, servizos e oportunidades de expansión.",
        points: ["A conversa estratéxica cualificada ou o acceso controlado á información segue unha cualificación por escrito.", "A información pública limítase a especificacións de produto aprobadas, arquitectura de configuración, capacidades verificadas e explicacións dos programas.", "A economía específica do comprador, os cálculos de custo, a metodoloxía protexida e os acordos non publicados revélanse só baixo acordo de confidencialidade ou contrato."],
        cta: "Solicitar unha conversa estratéxica cualificada",
        brief: {
          who: "Investidores e socios estratéxicos.",
          value: "Unha conversa cualificada sobre capacidade de enxeñaría, profundidade de configuración, modelo de fabricación, vías ao mercado e propiedade intelectual.",
          now: "Non se publica ningunha cifra financeira, previsión, valoración nin retorno. A información controlada segue unha cualificación por escrito e un acordo de confidencialidade.",
          next: "Solicite unha conversa estratéxica cualificada a continuación.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Programas institucionais",
        lead: "Formación, acceso, innovación, evidencia de desenvolvemento, impacto social e programas estruturados axeitadamente.",
        points: ["Os programas institucionais estrutúranse a través de MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) cando o programa establece ese papel.", "Os fondos restrinxidos do programa e as operacións comerciais mantéñense separados.", "Unha consulta non é unha solicitude de afiliación aceptada, e un comprador de equipamento non é un membro institucional.", "As subvencións, o estatuto benéfico, o tratamento fiscal e os permisos regulatorios son específicos de cada país e nunca se presupoñen."],
        cta: "Enviar unha consulta de programa institucional",
        brief: {
          who: "Institucións, programas educativos e de desenvolvemento.",
          value: "Programas de formación, acceso, innovación e evidencia de desenvolvemento, estruturados co operador axeitado.",
          now: "Consultas institucionais por escrito. Unha consulta non é unha solicitude de afiliación; a compra de equipamento non é unha afiliación institucional.",
          next: "Envíe a consulta institucional a continuación.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Divulgación pública e controlada",
    disclosure: {
      public: { h: "Pública", p: "Especificacións de produto aprobadas, construción, arquitectura de configuración, finalidades de adestramento, capacidades verificadas, explicacións dos programas e vías de colaboración." },
      qualified: { h: "Consulta cualificada", p: "Requisitos técnicos, cantidades, interese territorial, alcance do desenvolvemento e conversas comerciais pertinentes." },
      controlled: { h: "Controlada por confidencialidade ou contrato", p: "Fórmulas internas, protocolos detallados de control de calidade, laminados, ferramentaxe, métodos de fabricación, identidade dos provedores, cálculos de custo, economía específica do comprador, metodoloxía protexida, acordos non publicados e rexistros de dereitos sensibles." },
    },
  },
  contact: {
    title: "Contacto e solicitudes",
    lead: "Escolla a finalidade da súa solicitude. Cada formulario recolle só o que se precisa para derivala e avaliala. As solicitudes respóndense por escrito.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Identidade legal",
  },
  form: {
    purposeLabel: "Finalidade da solicitude",
    purposes: {
      selection: "Axuda para escoller unha raqueta",
      product: "Consulta de produto",
      fitting: "Axuste ou demostración",
      technical: "Informe técnico",
      config: "Solicitude de configuración",
      gps: "Perfil de equipamento GPS",
      coach: "Colaboración con adestrador",
      club: "Informe de club ou academia",
      distribution: "Distribución ou desenvolvemento de país",
      brand: "Colaboración de marca ou embaixador",
      family: "Consulta familiar ou de desenvolvemento",
      institutional: "Programa institucional",
      strategic: "Conversa estratéxica ou de investimento",
      owner: "Consulta de propietario",
      network: "Solicitude á Sports Network",
      general: "Consulta xeral",
    },
    fields: {
      name: "Nome",
      email: "Email",
      role: "O seu perfil",
      country: "País ou rexión",
      organisation: "Organización",
      message: "A súa mensaxe",
      level: "Nivel actual",
      objectives: "Que é o máis importante (ata tres)",
      currentRacquet: "Raqueta actual",
      grip: "Medida de empuñadura, se a coñece",
      seriesInterest: "Serie de interese",
      quantity: "Cantidade",
      city: "Cidade ou lugar da sesión",
      coachInvolved: "Participa un adestrador?",
      timing: "Calendario preferido",
      targets: "Obxectivos preferidos",
      limits: "Límites obrigatorios",
      use: "Uso previsto",
      tradeoffs: "Compromisos aceptables",
      basis: "Base de medición",
      players: "Número de xogadores",
      interests: "Áreas de interese",
      territory: "Territorio de interese",
      channels: "Canles existentes e experiencia",
      audience: "Público ou disciplina",
      proposal: "Colaboración proposta",
      goal: "Obxectivo de desenvolvemento",
      ageBand: "Franxa de idade do xogador",
      scope: "Alcance do programa",
      interestArea: "Área de interese",
      productRef: "Referencia de produto ou de serie",
      requestType: "Tipo de solicitude",
      seeking: "Que busca",
      consent: "Acepto que MAXIMUS garde e empregue estes datos para responder esta solicitude. Non é unha subscrición de mercadotecnia.",
    },
    roles: { player: "Xogador", parent: "Pai, nai ou titor", coach: "Adestrador", club: "Club ou academia", retailer: "Tenda", distributor: "Distribuidor", brand: "Marca ou embaixador", investor: "Investidor ou socio estratéxico", institution: "Institución", other: "Outro" },
    interestOptions: { training: "Sistemas de adestramento", fitting: "Axuste", identity: "Identidade profesional", programmes: "Programas autorizados", brand: "Marca persoal", supply: "Subministración de equipamento", team: "Equipamento de equipo", personalisation: "Personalización", development: "Programas de desenvolvemento", service: "Servizo", network: "Participación na rede" },
    ownerTypes: { setup: "Posta a punto e configuración", service: "Servizo", records: "Rexistros e certificados", other: "Outro" },
    strategicAreas: { engineering: "Capacidade de enxeñaría", configuration: "Profundidade de configuración", manufacturing: "Modelo de fabricación", routes: "Vías ao mercado", ip: "Propiedade intelectual e servizos", expansion: "Oportunidades de expansión" },
    errors: {
      required: "Este campo é obrigatorio.",
      too_long: "Esta entrada é demasiado longa.",
      too_short: "Esta entrada é demasiado curta.",
      invalid_email: "Introduza un enderezo de correo válido, por exemplo nome@exemplo.com.",
      invalid_choice: "Escolla unha das opcións.",
      not_number: "Introduza un número enteiro empregando só cifras.",
      out_of_range: "Este valor está fóra do intervalo aceptado.",
      not_in_matrix: "Este peso non está na matriz do catálogo da serie seleccionada.",
      decimal_not_supported: "Introduza un número enteiro sen decimais.",
      too_many: "Non escolla máis de tres opcións.",
      consent_required: "O consentimento é necesario para que MAXIMUS poida responder esta solicitude.",
      invalid: "Esta entrada non é válida.",
    },
  },
  legal: {
    title: "Identidade legal e control",
    lead: "A marca pública é MAXIMUS / MAXIMUS GPS. As identidades legais operativas pódense distinguir e indícanse aquí.",
    entities: {
      institutional: { role: "Capa de programas institucionais", p: "Achega a capa de programas institucionais cando un programa establece ese papel. Non é un vendedor comercial de raquetas. É unha organización sen ánimo de lucro constituída no Dubai International Financial Centre." },
      equipment: { role: "Entidade comercial de equipamento", p: "É a entidade comercial de equipamento para a subministración, a distribución e a entrega comercial contratada cando os documentos operativos vixentes establecen ese papel. A parte contratante de calquera operación identifícase nos documentos desa operación." },
      ip: { role: "Propiedade intelectual, marca e coordinación comercial", p: "Aparece para un papel establecido de propiedade intelectual, marca ou coordinación comercial. Non se lle asigna ningunha responsabilidade contractual non confirmada." },
      stewardship: { role: "Referencia de tutela", p: "House of Maximus é a referencia de tutela do ecosistema cando a fonte pertinente o sostén." },
      control: { role: "Propiedade intelectual interna, procedencia e control documental", p: "MIPA é a capa interna de propiedade intelectual, procedencia e control documental. Unha entrada interna de MIPA é distinta dunha marca rexistrada externa, dunha patente, dun rexistro de dereitos de autor ou dun recoñecemento xudicial, e non constitúe unha aprobación visual." },
    },
    labels: { licence: "Licenza", registration: "Rexistro", vat: "VAT TRN", address: "Enderezo", email: "Email", jurisdiction: "Xurisdición" },
    boundaryTitle: "Límites",
    boundary: [
      "Unha compra non concede automaticamente afiliación institucional, dereitos de goberno, canons nin dereitos de investimento.",
      "O papel institucional é independente das operacións comerciais de equipamento.",
      "A privacidade, as condicións dos programas e os acordos de acceso controlado correspóndense coas funcións realmente publicadas.",
      "Ningunha declaración xeral de lei aplicable rexe para todos os visitantes, vendas ou programas estranxeiros; a base contractual fíxase en cada acordo.",
    ],
  },
  privacy: {
    title: "Privacidade",
    updated: "Versión 2026-09-21 · sitio web 4.2",
    contactTitle: "Contacto para cuestións de privacidade",
    sections: {
      collect: ["Que se recolle", "Cando envía un formulario: os datos que introduce (nome, correo, perfil, país ou rexión, organización se a indica, a súa mensaxe e as respostas do formulario), a páxina e os parámetros de campaña da súa visita (páxina de entrada, idioma, parámetros utm; identificadores de clic publicitario só se permitiu a analítica) e a hora do envío. O seu enderezo IP emprégase só en forma resumida (hash) e de vida curta para limitar os abusos, e non se garda coa súa solicitude."],
      purpose: ["Por que", "Para responder a súa solicitude, preparar a proposta ou a especificación que pediu e conservar un rexistro da solicitude. Non se envía ningunha mensaxe de mercadotecnia a partir dun formulario."],
      storageOn: ["Onde se gardan as solicitudes", "As solicitudes gárdanse nunha base de datos de Upstash, Inc. (Redis), facilitada mediante a plataforma de aloxamento Vercel Inc."],
      notifyEmail: ["Notificación dunha solicitude nova", "Cando se acepta unha solicitude, envíase por correo electrónico unha notificación cos datos que enviou á caixa de correo MAXIMUS responsable."],
      notifyTelegram: ["Notificación dunha solicitude nova", "Cando se acepta unha solicitude, envíase unha notificación cos datos que enviou á persoa responsable de MAXIMUS a través de Telegram (Telegram FZ-LLC, Dubai), que por tanto trata esa notificación en tránsito."],
      notifyWebhook: ["Notificación dunha solicitude nova", "Cando se acepta unha solicitude, envíase unha notificación cos datos que enviou a un punto final interno de MAXIMUS por unha conexión asinada e cifrada."],
      notifyNone: ["Notificación dunha solicitude nova", "A notificación de solicitudes novas estase a configurar. A súa solicitude gárdase e MAXIMUS consúltaa no rexistro interno; para esta finalidade non se envía nada a ningún terceiro."],
      storageOff: ["Onde se gardan as solicitudes", "O almacenamento de solicitudes estase a configurar. Ata que estea activo, os formularios indican que non se pode aceptar ningunha solicitude; non se garda nada. O sitio web está aloxado por Vercel Inc."],
      browser: ["Almacenamento no navegador", "O almacenamento de sesión conserva as respostas de opción múltiple do GPS e do configurador e os parámetros de campaña da súa visita durante esta sesión do navegador. Os datos de contacto, o texto libre, o texto do gravado e a información sobre menores non se gardan no navegador."],
      analyticsOn: ["Analítica", "Co seu consentimento, Google Analytics 4 mide visitas e eventos de formulario sen datos de contacto nin texto de solicitude. A súa decisión gárdase no almacenamento local e pode cambiarse en calquera momento en «Configuración de analítica», no pé de páxina. Os formularios funcionan sen analítica."],
      analyticsOff: ["Analítica", "Neste sitio web non hai ningunha ferramenta de analítica activa."],
      retention: ["Conservación", "Aínda non hai configurado ningún prazo de eliminación automática. Pode pedir que se borre a súa solicitude en calquera momento."],
      children: ["Menores", "Os formularios debe cubrilos unha persoa adulta. As solicitudes relativas a xogadores menores de 18 anos fainas un pai, unha nai ou un titor. Non envíe o nome do menor, a data de nacemento, a escola nin información médica. Os perfís dos menores nunca se publican."],
      rights: ["Os seus dereitos", "Para acceder á súa solicitude, corrixila ou borrala, escriba a gps@maximus.tennis e indique o identificador de solicitude."],
      controlled: ["Información controlada", "Os documentos confidenciais non se gardan neste sitio web nin se serven dende el. A divulgación controlada realízase baixo acordo de confidencialidade ou contrato por canles separadas."],
    },
  },
  terms: {
    title: "Condicións de uso",
    copyright: "Os dereitos de autor deste sitio web — os textos, as fotografías, o deseño e o código — pertencen unicamente a Maximus Kiriyakulov. Non se cederon a ningunha empresa nin a ningunha outra persoa.",
    updated: "Versión 2026-09-21",
    sections: [
      ["Información, non oferta", "A información de produto deste sitio web describe especificacións aprobadas, arquitectura de configuración e explicacións dos programas. Non é unha oferta de venda, nin unha lista de prezos, nin unha declaración de existencias, nin un compromiso de entrega. As condicións comerciais acórdanse á parte e por escrito coa entidade contratante identificada en cada operación."],
      ["Solicitudes", "Unha solicitude enviada a través deste sitio web — incluídos os perfís GPS, as solicitudes de configuración e os informes técnicos — gárdase cun identificador e revísase. Non é un pedido aceptado, nin un compromiso de fabricación, nin unha cita confirmada, nin unha solicitude de afiliación, nin unha solicitude aceptada a ningún programa."],
      ["Especificacións e evidencia", "Os valores calculados, os obxectivos de fabricación e as especificacións confirmadas distínguense nas páxinas correspondentes. Os valores de rixidez son obxectivos de fabricación ata que se publique outra cousa. Non se garante ningún resultado para un xogador concreto."],
      ["Ecosistema, afiliación e dereitos", "A compra dunha raqueta non crea afiliación institucional, dereitos de investimento, titularidade de propiedade intelectual, dereito a canons nin beneficios de participación. Os dereitos seguen as condicións publicadas do programa ou un acordo escrito."],
      ["Propiedade intelectual", "MAXIMUS®, o emblema do león, a marca GPS e o contido deste sitio web están protexidos. As fórmulas de enxeñaría internas, os protocolos de control de calidade, os laminados, a ferramentaxe, a identidade dos provedores, os cálculos de custo e a metodoloxía protexida non se revelan aquí."],
    ],
  },
  lead: {
    submit: "Enviar a solicitude",
    submitting: "Enviando…",
    retry: "Inténteo de novo",
    acceptedEyebrow: "Solicitude aceptada",
    acceptedTitle: "Recibimos a súa solicitude.",
    requestId: "Identificador de solicitude",
    acceptedNext: "MAXIMUS revisa cada solicitude e responde por escrito ao enderezo de correo que indicou. Conserve o identificador de solicitude para calquera seguimento.",
    duplicate: "Esta solicitude xa se recibira; non se creou ningún duplicado.",
    another: "Comezar unha solicitude nova",
    errorsTitle: "Comprobe estes campos:",
    failTitle: "A súa solicitude non se enviou.",
    fail: {
      offline: "O seu dispositivo está sen conexión.",
      network: "A conexión co servidor fallou.",
      timeout: "O servidor non respondeu a tempo.",
      rate_limited: "Recibíronse demasiadas solicitudes desta rede. Inténteo de novo nuns minutos.",
      too_fast: "O formulario enviouse moi rápido. Compróbeo e envíeo de novo.",
      spam_suspected: "O filtro de correo lixo detivo a solicitude.",
      unavailable: "Neste momento non se poden aceptar solicitudes.",
      default: "Produciuse un erro inesperado.",
    },
    keepNote: "O que escribiu consérvase nesta páxina, así que pode tentalo de novo.",
    sendByEmail: "Enviar esta solicitude por correo electrónico",
    sendByEmailNote: "A súa aplicación de correo ábrese co texto desta solicitude. MAXIMUS recíbea cando envía o correo.",
    mailConfig: "Configuración",
    mailPage: "Páxina",
    fallback: "Se o problema persiste, escriba a {email}. Unha solicitude só conta como enviada cando se amosa un identificador de solicitude.",
    privacyLink: "Aviso de privacidade",
    hpLabel: "Deixe este campo baleiro",
    consentShort: "Consentimento",
    after: "Despois do envío amósase un identificador de solicitude nesta páxina. As solicitudes revísanse e respóndense por escrito; unha solicitude non é un pedido.",
    basis: { unstrung: "Sen cordaxe", strung: "Con cordaxe", unknown: "Non o sei con certeza — acordarase na especificación" },
    hints: {
      email: "MAXIMUS responde por escrito a este enderezo.",
      goal: "Por exemplo: primeira raqueta de competición, ou deixar atrás unha raqueta xuvenil. Non inclúa nomes, datas de nacemento nin información médica dun menor.",
      currentRacquet: "Marca e modelo, se os coñece.",
      message: "Non inclúa contrasinais, datos de pagamento nin información médica.",
    },
  },
  choose: {
    eyebrow: "Axuda para escoller",
    title: "Axúdeme a escoller unha raqueta",
    lead: "Dígalle a MAXIMUS o seu nivel e que lle importa máis. As súas respostas revísanse e recibe unha proposta por escrito: serie, clase de precisión, peso e empuñadura.",
    stepsTitle: "Que acontece a continuación",
    steps: [
      ["As súas respostas", "Nivel, prioridades e medida de empuñadura se a coñece."],
      ["Revisión experta", "MAXIMUS compara as súas respostas coas matrices das series."],
      ["Proposta escrita", "Unha configuración proposta e o paso seguinte, por escrito."],
    ],
    formTitle: "As súas respostas",
    submit: "Pedir axuda para escoller",
    altTitle: "Prefire decidilo vostede?",
    altGps: "Perfil GPS detallado",
    altBuild: "Configurar directamente",
    note: "Sen axuste automático e sen ningunha afirmación de exactitude: unha persoa revisa cada solicitude.",
  },
  consent: {
    title: "Analítica",
    text: "Pode MAXIMUS medir as visitas con Google Analytics? Os formularios funcionan nos dous casos; non se envía ningún dato de contacto nin texto de solicitude á analítica.",
    allow: "Permitir a analítica",
    decline: "Rexeitar",
  },
  familyPlan: {
    title: "Plan de Tenis en Familia",
    metaDescription: "Calcule o orzamento de tenis da súa familia: sesións, horas, contactos coa bóla e o custo dunha sesión, dunha hora e dun golpe, a partir das súas propias cifras e en tres escenarios.",
    eyebrow: "Plan de Tenis en Familia · Contribúa connosco",
    heroTitle: "Canto lle custa o tenis á súa familia e que obtén a cambio?",
    heroLead: "Calcule o seu orzamento familiar, as sesións e as horas que cobre, os contactos coa bóla estimados e o custo dunha sesión, dunha hora e dun golpe, cos seus propios criterios.",
    heroCta: "Calcule o seu plan de tenis en familia",
    strategy: {
      eyebrow: "O noso obxectivo",
      title: "Máis tenis. Máis oportunidades. Xuntos.",
      p1: "O noso obxectivo é multiplicar por dez o mercado mundial do tenis ampliando a participación e facendo que o camiño cara ao tenis sexa máis claro e accesible. MAXIMUS aspira a liderar este camiño mediante a xestión, a metodoloxía, a calidade, os resultados e a popularización do xogo.",
      p2: "Vemos os demais fabricantes de material de tenis e as súas marcas como socios potenciais. Propoñemos unir as forzas de empresas, adestradores, clubs e familias nun programa compartido para desenvolver, promover e levar o tenis a unha escala maior, en beneficio mutuo.",
      p3: "MAXIMUS é o quinto elemento deste enfoque: o papel aglutinador que axuda a que forzas separadas traballen xuntas. Os nosos retos comúns son a enfermidade, o sedentarismo infantil e as barreiras que impiden comezar a xogar e seguir xogando.",
      p4: "Para unha familia, todo comeza pola claridade. O Plan de Tenis en Familia amosa o orzamento, o número de sesións e de horas, o volume estimado de contactos coa bóla e o custo da práctica. Cambie as condicións e escolla o escenario que mellor lle conveña.",
      note: "Multiplicar o mercado por dez é o obxectivo estratéxico de MAXIMUS, non un resultado xa acadado. A calculadora amosa cálculos por escenarios e non promete ningún aforro, ningún efecto médico nin ningún resultado deportivo.",
      ctaCalc: "Calcule o seu plan de tenis en familia",
      ctaPartner: "Falemos de desenvolver xuntos o tenis",
    },
    beyond: {
      eyebrow: "Máis alá da pista",
      title: "O que constrúe o plan, ademais do adestramento",
      admission: {
        h: "Admisión en escolas e universidades de primeiro nivel",
        p: "MAXIMUS acompaña a familia no camiño cara a escolas e universidades de primeiro nivel de todo o mundo: construción do historial deportivo do xogador, preparación de documentos e solicitudes, e elección de programas nos que o deporte e os estudos van da man. Cando se concede unha bolsa deportiva, esta reduce o que a familia paga pola educación.",
      },
      assets: {
        h: "Activos dixitais: o nome, a imaxe e o historial do xogador",
        p: "O nome, a imaxe, os resultados, os contidos e a marca persoal dun xogador son activos e, co tempo, poden xerar un valor económico e de prestixio considerable. MAXIMUS axuda a crealos, rexistralos e protexelos para que ese valor quede co xogador e a súa familia.",
      },
      note: "Ningún dos dous forma parte da calculadora. O valor dunha praza escolar, dunha bolsa ou dun activo dixital depende de cada caso e non se estima aquí.",
      cta: "Preguntar polo apoio na admisión e os activos dixitais",
    },
    steps: ["Datos da familia", "Custo das sesións", "Plan a longo prazo", "Cálculo final"],
    stepsLabel: "Pasos da calculadora",
    scenarios: { now: "Actual", planned: "Previsto", wish: "Desexado" },
    scenarioHints: { now: "O que fai hoxe a súa familia.", planned: "O que ten previsto facer a continuación.", wish: "O que lle gustaría facer." },
    currency: {
      label: "Moeda",
      note: "Todos os importes que introduza están nesta moeda. Non se converte nada.",
    },
    fields: {
      players: { label: "Membros da familia que xogan", hint: "Número enteiro." },
      cost: { label: "Prezo dunha sesión para un xogador", hint: "Importe enteiro, con impostos e taxas incluídos." },
      sessions: { label: "Sesións por xogador ao mes", hint: "Número enteiro." },
      minutes: { label: "Duración dunha sesión, en minutos", hint: "Tempo total, pausas incluídas. Admítense decimais." },
      contacts: { label: "Contactos coa bóla por xogador e sesión", hint: "Un contacto é cada vez que a raqueta do propio xogador toca a bóla. Un intercambio non é un contacto. Conte do mesmo xeito en todos os escenarios." },
    },
    presetsLabel: "Selección rápida, en minutos",
    ages: {
      title: "Duración do plan",
      start: "Idade inicial",
      end: "Idade final",
      hint: "Unha suposición anónima sobre a duración do plan, que só se emprega para a táboa a longo prazo. Non é unha data de nacemento nin unha idade de inicio recomendada.",
    },
    extras: {
      title: "Gastos adicionais da familia",
      note: "Estes importes son para toda a familia e aplícanse aos tres escenarios. Non se multiplican polo número de xogadores nin entran no custo dunha hora ou dun contacto.",
      equipment: "Primeiro equipamento — un só importe para o período",
      clothing: "Roupa e calzado — un só importe para o período",
      renewal: "Renovación do equipamento — un só importe para o período, non se repite automaticamente",
      court: "Pista ou club — ao mes, toda a familia",
      travel: "Viaxes e eventos — ao mes, toda a familia",
      quoteSource: "De onde proceden os prezos (opcional)",
      quoteDate: "Data dos prezos (opcional)",
      quoteNote: "Amósase exactamente tal como o introduciu. MAXIMUS non verifica estes prezos.",
    },
    storage: {
      save: "Gardar o plan neste dispositivo",
      clear: "Borrar o plan deste dispositivo",
      saved: "Plan gardado neste dispositivo. Non se enviou nada a ningures.",
      cleared: "Plan borrado. A calculadora volveu aos valores iniciais.",
      restored: "Restaurouse o plan gardado neste dispositivo.",
      invalid: "Non se puido ler un plan gardado neste dispositivo e non se aplicou. Pode comezar un cálculo novo.",
      unavailable: "Este navegador non permite gardar no dispositivo.",
    },
    annual: {
      title: "Un ano, en paralelo",
      sessions: "Sesións-xogador ao ano",
      cost: "Gasto familiar en sesións ao ano",
      hours: "Horas-xogador ao ano",
      length: "Duración dunha sesión",
      contacts: "Contactos coa bóla ao ano",
      note: "As sesións-xogador e as horas-xogador suman as sesións de cada xogador. Non son horas de aluguer de pista nin sesións de grupo: dous xogadores que adestran xuntos durante 90 minutos suman 2 sesións-xogador e 3 horas-xogador.",
    },
    economics: {
      title: "O custo dunha sesión, dunha hora e dun contacto",
      session: "Unha sesión dun xogador",
      hour: "Unha hora de práctica dun xogador",
      contact: "Un contacto coa bóla",
      undefinedContacts: "Sen definir: 0 contactos",
      undefinedMinutes: "Sen definir: 0 minutos",
      below: "menos de {value}",
      note: "Nestas cifras só entra o prezo da sesión. Os gastos adicionais da familia non se reparten entre os contactos.",
      caption: "O número de contactos calcúlase a partir do volume de sesións escollido e dos supostos do modelo. A práctica real depende do formato, das pausas e das condicións do adestramento. O custo dun contacto é unha medida orzamentaria, non unha medida da calidade do adestramento.",
    },
    longTerm: {
      title: "Plan de gasto a longo prazo",
      horizon: "Horizonte",
      activeYears: "Anos activos",
      years: "{n} ano(s)",
      note: "Os anos activos están limitados pola diferenza entre as dúas idades. Os prezos, a frecuencia, a inflación, as tempadas, as sesións perdidas e os tipos de cambio mantéñense constantes. Os gastos adicionais non forman parte desta táboa.",
    },
    final: {
      title: "Cálculo final",
      scenario: "Escenario",
      months: "Período, en meses",
      heading: "{scenario} · {months} meses",
      total: "Total do período",
      training: "Sesións",
      extras: "Gastos adicionais",
      oneOff: "Gastos puntuais",
      monthly: "Gastos mensuais × meses",
      sessions: "Sesións-xogador no período",
      hours: "Horas-xogador no período",
      contacts: "Contactos coa bóla no período",
      formulaTitle: "Como se calcula",
      formula: "Total = xogadores × sesións ao mes × meses × prezo da sesión + gastos puntuais + meses × gastos adicionais mensuais.",
      formulaNote: "Os gastos adicionais introdúcense para toda a familia. Os gastos puntuais cóntanse unha soa vez, mesmo para un período de 0 meses.",
      inputs: "Os seus datos",
    },
    units: { min: "min", h: "h", approx: "≈" },
    errors: {
      title: "Corrixa estes campos para ver o resultado",
      required: "Obrigatorio: introduza un número; admítese o 0.",
      negative: "Non pode ser negativo.",
      integer: "Só números enteiros.",
      number: "Introduza un número.",
      tooLarge: "Este número é demasiado grande para calculalo.",
      endBeforeStart: "A idade final non pode ser inferior á idade inicial.",
      tooLong: "Como máximo, 200 caracteres.",
      date: "Introduza unha data válida.",
      currency: "Escolla unha moeda.",
      scenario: "Escolla un escenario.",
      result: "O resultado é demasiado grande para amosalo de forma fiable. Reduza os valores introducidos.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: a composición completa — o adestrador visto de fronte e de lado, o medallón do león gravado na cabeza de contacto redonda, o gravado MAXIMUS e SPOT TRAINER ao longo do pescozo, e o tapón octogonal coa marca do león",
    greatHero: "Serie MAXIMUS GREAT, 363 g: a composición completa cos detalles vermellos e amarelos na cabeza, as letras MAXIMUS brillantes, o autógrafo de Maximus no pescozo e o león no mango",
    spotDetail: "Dous MAXIMUS Spot Trainer vistos máis de preto: o león gravado na cabeza de contacto negra mate, a cinta de empuñadura estriada e os tapóns octogonais coa marca do león",
    spotPair: "Dous MAXIMUS Spot Trainer colocados en ángulo sobre unha superficie escura, con MAXIMUS gravado nun pescozo e SPOT TRAINER no outro, e o medallón do león en cada cabeza de contacto",
    spinVisual: "MAXIMUS SPIN: cabeza con cordaxe, letras MAXIMUS brillantes, empuñadura e tapón co león",
    powerVisual: "MAXIMUS POWER: cabeza con cordaxe, letras MAXIMUS brillantes, gravado de personalización, empuñadura e tapón co león",
    greatVisual: "MAXIMUS GREAT: cabeza con cordaxe, letras MAXIMUS brillantes, gravado de personalización, empuñadura, tapón co león e a marca da serie G no pescozo",
    spinHead: "Cabeza e plano de cordaxe do MAXIMUS SPIN",
    handleLion: "Pescozo, empuñadura e tapón MAXIMUS coa marca do león",
    engraving: "Gravado de personalización en prata no pescozo",
    lettering: "Letras MAXIMUS negras brillantes sobre un marco negro mate",
    variantAlt: "Serie MAXIMUS {series} — {w} g, balance {b} mm: visualización completa coa franxa de especificación, a zona de gravado de personalización e a marcaxe MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistema de catro raquetas",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Pescozos do Sweet Spot Trainer coas letras MAXIMUS",
    sstGrips: "Empuñaduras e tapóns do Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, catro tapóns coa marca do león",
    note: "Visual de produto",
  },
  notFound: { title: "Páxina non atopada", p: "A páxina que solicitou non existe nesta lingua.", cta: "Ir á páxina de inicio" },
};

export default gl;
