/* Croatian dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const hr = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — teniski reketi u cijelosti od karbona, projektirani prema specifikaciji",
    defaultDescription:
      "Teniski reketi u cijelosti od karbona, od okvira do ručke: GREAT 97 in², POWER 98 in² i SPIN 100 in², osam tvorničkih veličina ručke L0–L7, klase preciznosti za težinu, balans, swingweight i krutost te inženjering po mjeri na zahtjev.",
  },
  common: {
    statuses: {
      current: "Aktualno",
      agreement: "Dostupno po dogovoru",
      development: "U razvoju",
      concept: "Koncept",
      target: "Proizvodni cilj",
      modelled: "Izračunano",
      confirmed: "Potvrđeno",
      requested: "Zahtijevana arhitektura",
      notprovided: "Nije dostavljeno",
    },
    brief: { who: "Za koga je", value: "Što dobivate", now: "Potvrđeno sada", next: "Sljedeći korak" },
    labels: {
      next: "Dalje",
      back: "Natrag",
      edit: "Uredite odgovore",
      review: "Provjera",
      start: "Počnite",
      restart: "Počnite iznova",
      copy: "Kopirajte tekst zahtjeva",
      copied: "Kopirano",
      openEmail: "Otvorite e-poštu za slanje ovog zahtjeva",
      reference: "Referenca zahtjeva",
      weight: "Težina",
      balance: "Balans",
      swingweight: "Swingweight",
      stiffness: "Krutost",
      grip: "Veličina ručke",
      headSize: "Veličina glave",
      series: "Serija",
      precisionClass: "Klasa preciznosti",
      quantity: "Količina",
      notProvided: "Još nije objavljeno",
      requestTarget: "Zahtijevani cilj",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Pročitajte više",
      allSeries: "Sve serije",
      points: "navedene težine",
      optional: "neobvezno",
      required: "obvezno",
      select: "Odaberite",
      yes: "Da",
      no: "Ne",
      unknown: "Nisam siguran",
      custom: "Cilj po mjeri",
      listed: "Navedena težina",
      individual: "Pojedinačni reket",
      pair: "Usklađeni par",
      triple: "Usklađena trojka",
      team: "Timski set",
      summaryTitle: "Sažetak vašeg zahtjeva",
      nextAction: "Sljedeća radnja",
      status: "Status",
      learn: "Saznajte više",
      schematic: "Shema — nije mjerenje",
      photo: "Fotografija",
    },
    ecosystemStrip: "MAXIMUS ekosustav",
    truth: {
      noPrices: "Cijene, minimalne količine, rokovi izrade, jamstva i obveze isporuke potvrđuju se u pisanom obliku, za svako tržište i svaki program.",
      requestNotOrder: "Zahtjev je zahtjev za razmatranje. Nije prihvaćena narudžba, proizvodna obveza niti potvrđen termin.",
      noGuarantee: "Nijedna oprema, metoda ili program opisan ovdje ne jamči rezultat pojedinom igraču.",
      governing: "Ova se stranica objavljuje na više jezika. Engleska je verzija obvezujuća; prijevod je dan radi lakšeg razumijevanja.",
    },
  },
  nav: {
    language: "Jezik",
    groups: { racquets: "Reketi", training: "Trening", ecosystem: "Ekosustav", partnerships: "Partnerstva" },
    racquets: "Serije reketa i usporedba",
    great: "GREAT — 97 in² · Kontrola",
    power: "POWER — 98 in² · Snaga",
    spin: "SPIN — 100 in² · Rotacija",
    precision: "Preciznost i krutost",
    grip: "Tvornička arhitektura ručke L0–L7",
    custom: "Inženjering po mjeri",
    training: "Sustavi za trening",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologija",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Pomoć pri odabiru",
    ecosystem: "Mapa ekosustava",
    engineering: "Inženjering i proizvodnja",
    experience: "Testiranje i prilagodba",
    brands: "Osobni brendovi i ambasadori",
    families: "Obitelji i roditelji",
    owners: "Vlasnici i trezor vlasnika",
    network: "Sports Network",
    partnerships: "Svi putevi partnerstva",
    coaches: "Treneri",
    clubs: "Klubovi i akademije",
    distribution: "Distribucija i razvoj tržišta",
    strategic: "Strategija i ulaganja",
    institutional: "Institucionalni programi",
    contact: "Kontakt",
    legal: "Pravni identitet",
    privacy: "Privatnost",
    terms: "Uvjeti korištenja",
    menu: "Izbornik",
    close: "Zatvorite",
    home: "Početna",
    skip: "Prijeđite na sadržaj",
  },
  footer: {
    line: "Reket MAXIMUS vaš je ključ za svijet MAXIMUS.",
    product: "Proizvod",
    ecosystem: "Ekosustav",
    company: "Organizacija",
    instagram: "Instagram",
    email: "E-pošta",
    analytics: "Postavke analitike",
    subscribe: {
      title: "Ostanite uz MAXIMUS",
      line: "Nove serije, termini prilagodbe, materijali za trening i program za vlasnike. Nekoliko pisama godišnje, ništa više.",
      label: "Adresa e-pošte",
      placeholder: "your@email.com",
      button: "Pretplatite se",
      sending: "Šalje se",
      done: "Adresa je na popisu. Pišemo samo kada imamo nešto vrijedno čitanja.",
      invalid: "Provjerite adresu.",
      failed: "Adresa nije zabilježena. Pokušajte ponovno za trenutak.",
      terms: "Pretplatom prihvaćate da vam MAXIMUS može slati te obavijesti i da u tu svrhu čuva vašu adresu. Svako pismo sadrži poveznicu za odjavu.",
    },
    rights: "MAXIMUS® i amblem lava oznake su MAXIMUS ekosustava. MIPA: interna kontrola intelektualnog vlasništva, podrijetla i dokumentacije.",
    boundary:
      "Komercijalni i ugovorni uvjeti dogovaraju se posebno, u pisanom obliku. Kupnja reketa ne stvara institucionalno članstvo, investicijska prava, nositeljstvo prava intelektualnog vlasništva niti pravo na tantijeme.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Preciznost počinje u trenutku udarca.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer i MAXIMUS metodologija povezuju usredotočen trening s reketima visokih performansi izrađenima u cijelosti od karbona.",
    heroCta1: "Istražite sustav za trening",
    heroCta2: "Istražite GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrola",
    heroMeta: [
      ["U cijelosti od karbona", "od okvira do ručke"],
      ["4 parametra", "težina · balans · swingweight · krutost"],
      ["8 veličina ručke", "tvornička geometrija L0–L7"],
      ["3 serije", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Počnite ovdje",
      title: "Odaberite svoj put",
      items: {
        player: { h: "Igrač", p: "Pronađite reket prema razini i prioritetima ili ga odmah konfigurirajte.", a: "Pronađite svoj reket" },
        parent: { h: "Roditelj", p: "Pisani put za razvojne ciljeve, uključenost trenera i odgovarajuću opremu.", a: "Put za obitelji" },
        coach: { h: "Trener, klub ili akademija", p: "Sustavi za trening, prilagodba, timski setovi i personalizacija.", a: "Putevi za trenere i klubove" },
        partner: { h: "Distributer ili partner", p: "Distribucija, razvoj tržišta, strateški i institucionalni putevi.", a: "Putevi partnerstva" },
      },
    },
    series: {
      eyebrow: "Serije visokih performansi",
      title: "Tri arhitekture performansi. Jedna inženjerska platforma.",
      lead: "Odaberite seriju prema smjeru igre, a zatim dovršite konfiguraciju: klasa preciznosti, težina, ručka, personalizacija.",
      cta: "Usporedite serije",
      configure: "Konfigurirajte",
      open: "Otvorite seriju",
      photoPending: "Fotografija još nije objavljena",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS sustav preciznosti",
      title: "Težina. Balans. Swingweight. Krutost.",
      sub: "Kontrolirani kao jedan inženjerski sustav.",
      lead: "Tri klase preciznosti određuju koliko se strogo svaki gotov reket drži svoje deklarirane specifikacije. P0.5 je uska tolerancija prema definiranom protokolu mjerenja — a ne nulta pogreška.",
      cta: "Preciznost i krutost u detalje",
    },
    stiffness: {
      eyebrow: "Krutost",
      title: "Ponovljiv odziv okvira prema deklariranom cilju.",
      p: "Krutost okvira oblikuje odziv, osjećaj i dosljednost između reketa. MAXIMUS je tretira kao četvrti kontrolirani parametar: cilj, izmjereni rezultat, dopuštena tolerancija i mogućnosti mjernog instrumenta vode se kao zasebni zapisi. Korist je ponovljivost — a ne zajamčen rezultat za svakog igrača.",
      cols: [["Odziv", "Kako okvir vraća energiju u trenutku udarca."], ["Osjećaj", "Što igrač osjeti u trenutku udarca."], ["Dosljednost", "Reketi izrađeni prema istoj specifikaciji reagiraju jednako, unutar svoje klase."]],
      schematicCaption: "Shema: dopušteno odstupanje oko deklariranog cilja krutosti za svaku klasu. Nije mjerenje; nijedna RA vrijednost ne podrazumijeva se.",
      bands: { p25: "tolerancija cilja ±1 RA", p15: "tolerancija cilja ±0.5 RA", p05: "odgovara deklariranoj ciljnoj RA vrijednosti prema utvrđenom tvorničkom protokolu mjerenja — a ne nulta pogreška", target: "deklarirani cilj (bez podrazumijevane vrijednosti)" },
    },
    carbon: {
      eyebrow: "Standard konstrukcije",
      title: "U cijelosti od karbona. Od okvira do ručke.",
      p: "Svi aktualni MAXIMUS reketi na ovoj platformi u cijelosti su od karbona po svojoj strukturi, uključujući i ručku. Pjena se ne koristi za oblikovanje ručke.",
      gripTitle: "Osam tvorničkih veličina ručke. L0–L7.",
      gripP: "Svaka je veličina tvornička geometrija karbonske ručke — a ne nadogradnja overgripom.",
      scaleCaption: "Shema: nominalne oznake veličina ručke L0–L7 (4″ do 4⅞″). Nisu izmjerene dimenzije ručke.",
      cta: "Tvornička arhitektura ručke",
    },
    custom: {
      eyebrow: "Inženjering po mjeri",
      title: "Projektirano prema specifikaciji.",
      sub: "Standardni asortiman polazna je točka.",
      p: "MAXIMUS prihvaća tehničke zahtjeve izvan objavljenih matrica radi procjene, inženjerskog razvoja, validacije i proizvodnje prema dogovorenoj specifikaciji. Izvedivost se potvrđuje u pisanom obliku.",
      chain: ["Definiranje", "Inženjering", "Validacija", "Specifikacija", "Proizvodnja", "Mjerenje / evidentiranje"],
      cta: "Pošaljite tehnički zahtjev",
      cta2: "Razgovor o inženjeringu po mjeri",
    },
    training: {
      eyebrow: "Sustavi za trening",
      title: "Sustav treninga izgrađen oko trenutka udarca.",
      p: "Sweet Spot Trainer, MAXIMUS metodologija i Spot Trainer povezuju opremu s treningom pod vodstvom trenera: centriran udarac, kontrola, progresivno opterećenje i prijelaz natrag na natjecateljski reket.",
      cta: "Sustavi za trening",
      cta2: "Zatražite demonstraciju",
      photoPending: "Fotografija trenažnog reketa još nije objavljena",
      sstP: "Trenažna glava od 50 in² za vježbanje centriranog udarca, s četiri konfiguracije težine za opterećenje koje određuje trener.",
      sstCta: "Istražite Sweet Spot Trainer",
      sstCaption: "Konfiguracija od 300 g, jedna od četiri",
      methodP: "Postavite ciljeve, odaberite opremu, trenirajte uz uključenost trenera, zabilježite opažanja, ponovno procijenite, prilagodite i prenesite rad u natjecateljsku igru.",
      methodCta: "Istražite metodologiju",
      spotP: "Mala okrugla meta za vježbanje precizne i ponovljive točke udarca.",
      spotCta: "Istražite Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Proizvodnja i kontrola kvalitete",
      title: "Izrađeno prema specifikaciji. Izmjereno i evidentirano.",
      p: "Proizvodnja prati pisanu specifikaciju svake narudžbe. Zapisi ovise o klasi preciznosti: pohranjena proizvodna evidencija za P2.5, pojedinačni zapisi i sljedivost za P1.5, pojedinačna kontrola i dokumentacija za P0.5 tamo gdje ih program za tu narudžbu provodi.",
      confirmedTitle: "Potvrđeno",
      confirmed: ["Konstrukcija u cijelosti od karbona, od okvira do ručke.", "Klase preciznosti P2.5, P1.5 i P0.5 s četiri kontrolirana parametra.", "Osam tvorničkih veličina ručke L0–L7."],
      pendingTitle: "Još nije objavljeno",
      pending: "Fotografije mjerne opreme, primjeri zapisa kontrole kvalitete i snimke iz tvornice još nisu objavljeni. Ništa na ovoj stranici nije certifikat o mjerenju.",
      captions: { lettering: "Sjajni MAXIMUS natpis na mat okviru", buttcap: "Ručka i poklopac ručke s oznakom lava", handle: "Srebrna gravura personalizacije", finish: "Glava i površina žica" },
      cta: "Inženjering i proizvodnja",
    },
    world: {
      eyebrow: "Svijet MAXIMUS",
      title: "Jedan ključ. Jedan ekosustav. Neograničene mogućnosti.",
      note: "„Neograničene mogućnosti” izraz je brenda, a ne obećanje neograničene tehničke izvedivosti, prihoda ili pristupa. Kupnja ne stvara tantijeme, prinose od ulaganja, sponzorstvo niti financiranje razvoja igrača.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — i vaša navigacija u svijetu tenisa: vođeni profil opreme na koji se odgovara u pisanom obliku." },
        personal: { h: "Personalizacija", p: "Imena, inicijali, brojevi i timska identifikacija u odobrenoj tehnici srebrne gravure." },
        development: { h: "Razvoj", p: "Sustavi za trening pod vodstvom trenera, zapisi i ponovna procjena." },
        ecosystem: { h: "Prošireni ekosustav", p: "Osobni brendovi, zapisi vlasnika, mreža, licenciranje i institucionalni programi — svaki prikazan sa svojim stvarnim statusom." },
      },
      cta: "Istražite ekosustav",
    },
    partners: {
      eyebrow: "Putevi partnerstva",
      title: "Treneri, klubovi, distributeri i partneri.",
      p: "Prvo pisana kvalifikacija. Prava za zemlju, ekskluzivnost i komercijalni uvjeti dogovaraju se u pisanom obliku — nikada se ne dodjeljuju putem obrasca.",
      cta: "Svi putevi partnerstva",
      formTitle: "Kratak upit",
      formLead: "Odaberite svrhu i pišite MAXIMUS-u. ID zahtjeva dobivate na ovoj stranici.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "VAŠA NAVIGACIJA U SVIJETU TENISA" } },
    personal: { eyebrow: "Personalizacija", title: "Vaše ime. Vaš broj. Vaš MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tri serije. Stvarni parametri." },
    map: { cta: "Istražite ekosustav" },
  },
  racquets: {
    title: "Reketi",
    lead: "Tri serije visokih performansi sa zajedničkim standardom konstrukcije, zajedničkim sustavom preciznosti i zajedničkom tvorničkom arhitekturom ručke. Svaka je serija ustanovljena arhitektura performansi unutar šire inženjerske platforme.",
    direction: { control: "Kontrola", power: "Snaga", spin: "Rotacija" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Primarni smjer igre",
    compareTitle: "Usporedba serija",
    compareLead: "Samo potvrđeni podaci o arhitekturi. Raspored žica, duljine, profili okvira, rasponi napetosti žica te nominalne vrijednosti za swingweight i krutost za ove serije nisu objavljeni; prikupljaju se kao zahtijevani ciljevi za tehničku provjeru.",
    columns: { series: "Serija", head: "Veličina glave", direction: "Smjer", weights: "Navedene težine", range: "Raspon težine", balance: "Podaci o balansu" },
    balanceModelled: "Izračunane vrijednosti",
    balanceNotProvided: "Još nije objavljeno",
    construction: "Konstrukcija: u cijelosti od karbona, od okvira do ručke · Preciznost: P2.5 / P1.5 / P0.5 · Ručke: L0–L7",
    otherTitle: "Drugi sportovi s reketom",
    otherLead: "Odobreni smjerovi razvoja. U tim kategorijama ne postoje proizvodi za prodaju i nijedna se teniska specifikacija na njih ne prenosi.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Skvoš", badminton: "Badminton", racquetball: "Reketbol", beachTennis: "Tenis na pijesku" },
    ctaConfigure: "Konfigurirajte zahtjev",
    ctaSeries: "Otvorite seriju",
  },
  seriesPage: {
    eyebrow: "Serije visokih performansi",
    intro: {
      great: "Arhitektura GREAT od 97 in² izgrađena je oko kontrole: kompaktna glava, precizan udarac i sigurnost u usmjeravanju.",
      power: "Arhitektura POWER od 98 in² izgrađena je oko prijenosa energije: dubina i brzina iz stabilnog okvira.",
      spin: "Arhitektura SPIN od 100 in² izgrađena je oko ponašanja loptice: rotacija, sigurnosna margina i oblikovanje putanje.",
    },
    photoPending: "Fotografija serije još nije objavljena",
    detailPending: "Fotografije detalja konstrukcije i ručke za ovu seriju još nisu objavljene.",
    specsTitle: "Specifikacija i status",
    catalogue: {
      eyebrow: "Katalog serije {series}",
      title: "Varijante težine: {n}",
      lead: "Svaka varijanta serije {series}, razvrstana po težini. Težina u gramima, balans u milimetrima od kraja ručke. Svaka je vizualizacija prikazana u cijelosti: ništa nije izrezano, maskirano ni rastegnuto.",
      selectLabel: "Odaberite varijantu težine",
      select: "Prikažite ovu varijantu",
      selected: "Prikazano iznad",
      balanceLabel: "Balans",
      headLabel: "Veličina glave",
      constructionLabel: "Konstrukcija",
      gripsLabel: "Tvorničke veličine ručke",
      precisionLabel: "Klase preciznosti",
      balanceConfirmed: "Balans je potvrđena vrijednost za ovu težinu i odgovara broju ispisanom na vizualizaciji. Cijene, zalihe i rokovi isporuke ovdje se ne objavljuju.",
      balanceModelled: "Balans je izračunana vrijednost za ovu navedenu težinu, a ne pojedinačno tvorničko mjerenje; odgovara broju ispisanom na vizualizaciji. Cijene, zalihe i rokovi isporuke ovdje se ne objavljuju.",
      zoom: "Otvorite sliku",
      close: "Zatvorite",
      allTitle: "Sve varijante ({n})",
    },
    specs: { head: "Veličina glave", direction: "Primarni smjer", weights: "Navedene težine", range: "Raspon težine", balance: "Balans", construction: "Konstrukcija", grips: "Tvorničke ručke", precision: "Klase preciznosti" },
    construction: "U cijelosti od karbona, od okvira do ručke",
    statusTitle: "Status vrijednosti",
    matrixTitle: "Puna matrica težina",
    matrixLead: "Navedene težine standardni su odabir. Druge se težine mogu zatražiti kao ciljevi po mjeri; međuvrijednosti koje ne postoje ne dodaju se.",
    balanceNote: {
      confirmed: "Vrijednosti balansa potvrđene su za svaku navedenu težinu (mm od kraja ručke) i odgovaraju broju ispisanom na vizualizaciji te težine. Ne izračunavaju se ovdje i ne izglađuju se između susjednih težina; osnova mjerenja potvrđuje se u pisanoj specifikaciji.",
      modelled: "Vrijednosti balansa izračunane su za svaku navedenu težinu (mm od kraja ručke). Nisu pojedinačna tvornička mjerenja; osnova mjerenja potvrđuje se u pisanoj specifikaciji.",
      notprovided: "Vrijednosti balansa za ovu seriju nisu dostavljene. Ne izvodite ih iz druge serije.",
    },
    optionsTitle: "Preciznost, ručka i težina",
    notPublished: "Nije objavljeno za ovu seriju: raspored žica, duljina, profil okvira, raspon napetosti žica, swingweight i vrijednosti krutosti. Možete ih navesti kao zahtijevane ciljeve za tehničku provjeru.",
    offerTitle: "Što se događa nakon vašeg zahtjeva",
    offerSteps: [
      ["Zahtjev", "Pošaljite konfiguraciju ili pitanje. ID zahtjeva prikazuje se odmah."],
      ["Provjera", "MAXIMUS provjerava seriju, klasu, težinu, ručku i sve zahtijevane ciljeve."],
      ["Pisani odgovor", "Specifikacija, dostupnost i komercijalni uvjeti potvrđuju se u pisanom obliku."],
    ],
    faqTitle: "Pitanja",
    faq: [
      ["Jesu li vrijednosti balansa izmjerene?", "Izračunane su za navedene težine, nisu pojedinačna mjerenja. Osnova mjerenja potvrđuje se u pisanoj specifikaciji."],
      ["Mogu li zatražiti težinu koja nije navedena?", "Da, kao cilj po mjeri u cijelim gramima. Provjerava se tehnički, a izvedivost se potvrđuje u pisanom obliku."],
      ["Što mijenja klasa preciznosti?", "Koliko se strogo težina, balans, swingweight i krutost drže deklarirane specifikacije i koji se zapisi vode."],
      ["Nadograđuje li se ručka overgripovima?", "Ne. L0–L7 tvorničke su geometrije karbonske ručke."],
      ["Gdje su cijene i rokovi isporuke?", "Potvrđuju se u pisanom obliku za svaki zahtjev i ovdje se ne objavljuju."],
    ],
    faqSpinBalance: ["Odakle dolaze vrijednosti balansa za SPIN?", "Iz potvrđene tablice serije Spin: 33 varijante težine s balansom u milimetrima od kraja ručke. Svaki par odgovara broju ispisanom na odobrenoj vizualizaciji te težine. Vrijednosti se ne izračunavaju i ne izglađuju između susjednih težina."],
    ctaBuild: "Konfigurirajte ovu seriju",
    ctaAsk: "Pitajte o ovoj seriji",
    ctaCompare: "Usporedite sve serije",
    weightsLabel: "navedene težine",
    headLabel: "glava",
  },
  precision: {
    title: "Preciznost i krutost",
    switch: { label: "Odaberite klasu preciznosti", panelLabel: "Četiri kontrolirana parametra —", qcLabel: "Arhitektura kontrole kvalitete", protocolNote: "prema definiranom tvorničkom protokolu mjerenja za kontrolu kvalitete", fullTable: "Puna usporedna tablica" },
    lead: "Četiri parametra kontrolirana kao jedan inženjerski sustav. Svaka klasa definira koliko se strogo gotov reket drži svoje deklarirane specifikacije i koji se zapisi kvalitete izrađuju.",
    statement: "Težina. Balans. Swingweight. Krutost. Kontrolirani kao jedan inženjerski sustav.",
    classes: {
      "P2.5": { name: "Skalabilna osnova performansi", qc: "Pojedinačno mjerenje i pohranjena proizvodna evidencija." },
      "P1.5": { name: "Napredna preciznost", qc: "Pojedinačno mjerenje, pojedinačni zapisi i sljedivost." },
      "P0.5": { name: "Profesionalno · pojedinačno kontrolirano", qc: "Pojedinačna kontrola s nominalnim i stvarnim vrijednostima te pojedinačnim zapisima mjerenja; serijski identitet, sljedivost proizvodne serije, certifikat preciznosti i usklađeni setovi tamo gdje ih program za tu narudžbu provodi." },
    },
    columns: { cls: "Klasa", weight: "Težina", balance: "Balans", sw: "Swingweight", stiff: "Krutost", qc: "Arhitektura kontrole kvalitete" },
    stiffTarget: "tolerancija cilja",
    stiffExact: "odgovara deklariranoj ciljnoj RA vrijednosti prema utvrđenom tvorničkom protokolu mjerenja",
    programmeNote: "Serijski identitet, certifikati i dokumentacija o usklađenim setovima izdaju se samo tamo gdje ih program za pojedinu narudžbu provodi.",
    targetsNote: "Specifikacije krutosti proizvodni su ciljevi dok odgovarajući protokol i proizvodni dokazi ne potkrijepe snažniju tvrdnju. Postavka arhitekture ne podrazumijeva da je svaka navedena konfiguracija već prošla potpuni postupak odobrenja po sva četiri parametra.",
    stiffnessTitle: "Zašto je krutost važna",
    stiffnessP1: "Krutost okvira utječe na to kako okvir reagira u trenutku udarca, kakav je osjećaj i koliko su dva reketa međusobno dosljedna. Glavna je korist od njezine kontrole ponovljiv odziv prema deklariranoj specifikaciji.",
    stiffnessP2: "Prije objave verificirane usklađenosti interni zapis kontrole kvalitete identificira instrument, status njegove kalibracije, metodu, stanje reketa, rezoluciju, mjernu nesigurnost, ponovljena mjerenja, pravilo zaokruživanja i pravilo prihvaćanja. Isti prikazani cijeli broj nije dokaz nulte fizičke varijacije ni nulte pogreške mjerenja.",
    fields: ["Cilj", "Izmjereni rezultat", "Dopuštena tolerancija", "Mogućnosti mjernog instrumenta"],
    fieldsNote: "Vode se kao zasebna polja u svakom zapisu.",
    matchedTitle: "Usklađeni setovi",
    matchedP: "Kriteriji za usklađeni set definiraju se odvojeno od pojedinačne tolerancije. Usklađenost svakog reketa s njegovom nominalnom tolerancijom sama po sebi ne dokazuje određenu najveću razliku između dva reketa. Usklađeni parovi, trojke i timski setovi traže se preko konfiguratora i potvrđuju u pisanom obliku.",
    extendedTitle: "Prošireni tehnički model",
    extendedP: "Model podataka podržava dodatne parametre. Za njih još ne postoje vrijednosti ni klase tolerancije; mogu se navesti kao zahtijevani ciljevi u tehničkom zahtjevu.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torzijsko ponašanje", length: "Duljina", beamProfile: "Profil okvira", headGeometry: "Geometrija glave", stringPattern: "Raspored žica", durability: "Trajnost", vibration: "Karakteristike vibracija" },
    noZero: "MAXIMUS ne opisuje svoj asortiman kao asortiman s nultom tolerancijom. Preciznost se navodi kao klasa s deklariranom tolerancijom i definiranom arhitekturom kontrole kvalitete.",
    cta: "Konfigurirajte s klasom preciznosti",
  },
  grip: {
    title: "Tvornička arhitektura ručke",
    statement: "Osam tvorničkih veličina ručke. L0–L7.",
    lead: "Geometrija ručke dio je arhitekture karbonske ručke. Svaka se veličina proizvodi kao geometrija ručke, a ne nadograđuje overgripovima.",
    emph: "Proširene veličine",
    p1: "Tvornički asortiman od osam veličina daje trenerima i igračima širi raspon konfiguracije kroz koji se oprema može specificirati oko igrača, uključujući i veće geometrije L6 i L7.",
    p2: "Nominalna oznaka veličine ručke razlikuje se od sirovih dimenzija strukturne ručke i od konačnog protokola mjerenja. Veličine se primjenjuju na serije visokih performansi i na trenažne linije na ovoj platformi.",
    p3: "Za ovaj se asortiman ne tvrdi svjetska ekskluzivnost.",
    columns: { size: "Veličina", nominal: "Nominalno", family: "Primjenjuje se na" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurirajte sa svojom veličinom ručke",
  },
  custom: {
    title: "Inženjering po mjeri",
    statement: "Projektirano prema specifikaciji.",
    sub: "Standardni asortiman polazna je točka.",
    lead: "MAXIMUS prihvaća tehničke zahtjeve izvan objavljenih matrica konfiguracije radi procjene, inženjerskog razvoja, validacije i proizvodnje prema dogovorenoj specifikaciji. Izvedivost se potvrđuje provjerom — nije svaki zamisliv zahtjev fizički ili komercijalno izvediv.",
    scopeTitle: "Što tehnički zahtjev može obuhvatiti",
    scope: ["Geometrija glave i okvira", "Duljina", "Težina", "Balans", "Swingweight", "Krutost", "Twistweight", "Geometrija ručke", "Konstrukcija", "Usklađeni setovi", "Trenažni okviri", "Estetika i gravura", "Identitet i timski programi", "Razvoj koji ovisi o alatima"],
    processTitle: "Proces",
    process: [
      ["Definiranje", "Željeni ciljevi, obvezna ograničenja, namjena i prihvatljivi kompromisi."],
      ["Inženjering", "Inženjerska procjena u odnosu na platformu i alate."],
      ["Validacija", "Validacija u odnosu na dogovorenu specifikaciju."],
      ["Specifikacija", "Pisana specifikacija s osnovom mjerenja i tolerancijama."],
      ["Proizvodnja", "Proizvodnja prema specifikaciji."],
      ["Mjerenje / evidentiranje", "Mjerenje i pohranjeni zapisi prema primjenjivoj klasi preciznosti."],
    ],
    formTitle: "Pošaljite tehnički zahtjev",
    formLead: "Razlikujte željene ciljeve od obveznih ograničenja. Rezultat je zahtjev za tehničku provjeru, a ne automatski prihvaćena proizvodna narudžba.",
    protected: "Recepture slaganja karbonskih slojeva, alati, identitet dobavljača, interni obračun troškova i zaštićeno znanje ne otkrivaju se ovim putem.",
    cta: "Pošaljite tehnički zahtjev",
  },
  training: {
    title: "Sustavi za trening",
    lead: "Dvije trenažne linije s vlastitim proizvodnim standardima, povezane jednom metodologijom: trening pod vodstvom trenera, zapisi, ponovna procjena i prijenos natrag u natjecateljsku igru.",
    sst: { h: "Sweet Spot Trainer", p: "Trenažni reket smanjene glave od 50 in² u sustavu od četiri težine, za vježbanje centriranog udarca, osjećaj za sweet spot, kontrolu reketa i progresivno opterećenje." },
    spot: { h: "Spot Trainer", p: "Trening točke udarca pomoću male okrugle mete za kontakt, na odobrenoj osnovi od četiri težine." },
    method: { h: "Metodologija", p: "Postavite ciljeve, odaberite opremu uz uključenost trenera, koristite odgovarajući sustav, bilježite, ponovno procijenite, prilagodite i prenesite u igru." },
    experience: "Držite ga. Zamahnite njime. Osjetite ga.",
    experienceP: "Zatražite testiranje, prilagodbu ili demonstraciju uz podršku trenera. Poslan zahtjev nije potvrđen termin.",
    cta: "Zatražite prilagodbu ili demonstraciju",
    distinct: "Sweet Spot Trainer, Spot Trainer i svaki zaseban demonstracijski uređaj različiti su proizvodi i nikada se ne spajaju.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Zasebna trenažna kategorija s vlastitim proizvodnim standardom. Glava od 50 in² usmjerava pozornost na mjesto udarca; četiri težine daju progresiju opterećenja.",
    baseline: "Potvrđena osnova",
    columns: { head: "Glava", length: "Duljina", pattern: "Raspored žica", grips: "Tvorničke ručke" },
    systemTitle: "Sustav od četiri reketa",
    detailsTitle: "Detalji konstrukcije",
    systemLead: "Težina i balans kako se dostavljaju. Osnova mjerenja evidentira se zasebno i još nije objavljena.",
    purposeTitle: "Namjena",
    purpose: ["Vježbanje centriranog udarca", "Osjećaj za sweet spot", "Kontrola reketa", "Progresivno opterećenje", "Razvoj pod vodstvom trenera", "Prijelaz natrag na igračev natjecateljski reket"],
    heavy: "Model od 400 g kontrolirana je trenažna konfiguracija. Ne preporučuje se automatski djeci, početnicima ni svakom igraču; trener određuje opterećenje, trajanje i progresiju.",
    precisionNote: "Klase preciznosti P2.5, P1.5 i P0.5 iz serija visokih performansi ne primjenjuju se automatski na ovu trenažnu liniju. Tolerancije trenažne proizvodnje slijede vlastitu odobrenu specifikaciju te linije.",
    health: "Ne obećava se sprječavanje ni liječenje teniskog lakta, uklanjanje ozljeda niti zajamčeno napredovanje.",
    cta: "Zatražite demonstraciju Sweet Spot Trainera",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Trening točke udarca pomoću male okrugle mete za kontakt. Zaseban proizvod s vlastitim vizualnim identitetom, izgrađen na odobrenoj osnovi od četiri težine.",
    purposeTitle: "Potvrđena namjena",
    purposeP: "Učenje igrača da pronađe i ponovi preciznu točku udarca.",
    weightsTitle: "Progresija težine",
    weightsP: "Progresija težine slijedi odobrenu osnovu težina sustava Sweet Spot Trainer. Vrijednosti balansa i druge specifikacije sustava Sweet Spot Trainer ne prenose se na Spot Trainer.",
    dims: "Točne dimenzije mete još nisu objavljene.",
    grips: "Tvornička arhitektura ručke L0–L7.",
    notes: ["Klase preciznosti iz serija visokih performansi ne primjenjuju se automatski.", "Nije minijaturni konvencionalni reket i nijedan raspored žica nije objavljen.", "Spot Trainer, Sweet Spot Trainer i svaki zaseban demonstracijski uređaj ostaju jasno razdvojeni."],
    cta: "Pitajte o Spot Traineru",
  },
  methodology: {
    title: "Metodologija i iskustvo proizvoda",
    lead: "Oprema je samo jedan dio strukturiranog razvojnog puta. Metoda počinje od ciljeva igrača, a ne od naziva proizvoda.",
    stepsTitle: "Razvojni put",
    steps: [
      ["Postavite ciljeve", "Ciljevi igrača i polazna točka."],
      ["Odaberite opremu", "Odgovarajuća oprema odabrana uz uključenost trenera."],
      ["Koristite sustav", "Odgovarajući sustav za trening, pod vodstvom trenera."],
      ["Bilježite", "Opažanja o stvarnom sudjelovanju, bez izmišljenih rezultata."],
      ["Ponovno procijenite", "Usporedive kontrolne točke."],
      ["Prilagodite", "Prilagodbe konfiguracije ili programa."],
      ["Prenesite", "Naučeno se prenosi u natjecateljsku igru."],
    ],
    educationTitle: "Putevi edukacije",
    education: { player: "Igrači — razumijevanje konfiguracije, opterećenja i progresije.", parent: "Roditelji — kontinuitet razvoja, odgovarajuća oprema, zapisi i prava.", coach: "Treneri — sustavi za trening, prilagodba, procjena i ovlaštena uporaba programa." },
    evidenceTitle: "Disciplina dokaza",
    evidenceP: "Zapisi o stvarnom sudjelovanju i opažanja čuvaju se sa svojom klasifikacijom — prijavio sudionik, potvrdio skrbnik, validirao trener ili izmjerio sustav. Napredak, rezultati i validacija nikada se ne izmišljaju.",
    experienceTitle: "Držite ga. Zamahnite njime. Osjetite ga.",
    experienceP: "Testiranje, prilagodba ili demonstracija uz podršku trenera mogu se zatražiti. Poslan zahtjev nije potvrđen termin.",
    cta: "Zatražite prilagodbu ili demonstraciju",
    cta2: "Upit za partnerstvo s trenerom",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — vođeni profil opreme",
    title: "MAXIMUS GPS",
    lead: "Vođeni profil opreme. Odgovorite samo na ono što je relevantno; pregledajte i ispravite svoje odgovore; dobivate sažetak, smjerove konfiguracije koji se primjenjuju i stvarnu sljedeću radnju.",
    honesty: "U ovom izdanju nisu odobrena automatska pravila prilagodbe. GPS zato daje jasan sažetak zahtjeva i upućuje na smjerove konfiguracije; detalji opreme upućuju se na stručnu provjeru.",
    rulesVersion: "Verzija pravila",
    dataVersion: "Verzija podataka o proizvodima",
    steps: { role: "Uloga", sport: "Sport", experience: "Iskustvo", objectives: "Ciljevi", style: "Stil igre", equipment: "Trenutna oprema", preference: "Preferencije", coach: "Uključenost trenera", ageBand: "Dobna skupina", review: "Provjera" },
    notStored: "Ne pohranjuje se u ovom pregledniku.",
    ageNote: "Koristi se samo za usmjeravanje zahtjeva. Ime, datum rođenja i medicinski podaci ne traže se.",
    q: {
      role: "Što vas najbolje opisuje?",
      sport: "Koji sport?",
      experience: "Razina iskustva",
      objectives: "Što je najvažnije? (odaberite do tri)",
      style: "Stil igre, ako je poznat",
      equipment: "Trenutna oprema, ako je imate",
      equipmentHint: "Marka i model, težina ili veličina ručke ako ih znate. Neobvezno.",
      preference: "Željena konfiguracija ili poznata veličina ručke",
      grip: "Poznata veličina ručke",
      coach: "Je li trener uključen u vaše odluke o opremi?",
      ageBand: "Dobna skupina igrača (koristi se samo za pravilno usmjeravanje zahtjeva)",
    },
    roles: { player: "Igrač", parent: "Roditelj ili skrbnik", coach: "Trener", club: "Klub ili akademija", other: "Ostalo" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Skvoš", badminton: "Badminton", other: "Drugi sport s reketom" },
    sportNote: "Proizvodi postoje za tenis. Drugi su sportovi smjerovi razvoja; vaš se interes evidentira za odgovarajući program.",
    experience: { beginner: "Početnik", developing: "U razvoju", intermediate: "Srednja razina", advanced: "Napredna razina", competitive: "Natjecateljska razina", professional: "Profesionalna razina" },
    objectives: { control: "Kontrola", power: "Snaga", spin: "Rotacija", comfort: "Udobnost", manoeuvrability: "Upravljivost", development: "Dugoročni razvoj", competition: "Natjecanje", training: "Sustav za trening", team: "Tim ili usklađeni set", personal: "Personalizacija" },
    styles: { baseline: "Igra s osnovne linije", allcourt: "Univerzalna igra", attacking: "Napadački", defensive: "Obrambeni", coach: "Trener odlučuje", unknown: "Nisam siguran" },
    ageBands: { u10: "Do 10 godina", u14: "10–13", u18: "14–17", adult: "18 i više" },
    output: {
      title: "Vaš profil opreme",
      status: "Potrebna je stručna provjera",
      statusP: "U ovom se izdanju ne provodi automatsko uparivanje. Vaš je profil sažet za stručnu provjeru.",
      directionsTitle: "Smjerovi konfiguracije koji se primjenjuju",
      directionsP: "Na temelju ciljeva koje ste naveli i deklariranog smjera igre svake serije. Ovo je smjer, a ne preporuka prilagodbe.",
      trainingHint: "Vaši ciljevi uključuju sustav za trening: pogledajte Sweet Spot Trainer i Spot Trainer.",
      teamHint: "Usklađeni setovi traže se preko konfiguratora i potvrđuju u pisanom obliku.",
      next1: "Pošaljite profil na stručnu provjeru",
      show: "Prikažite moj profil",
      configure: "Konfigurirajte",
      sendP: "Pošaljite svoj profil MAXIMUS-u na stručnu provjeru. ID zahtjeva prikazuje se odmah; odgovor dolazi u pisanom obliku.",
      otherSport: "MAXIMUS reketi postoje za tenis. Za druge sportove s reketom ne predlaže se nijedna teniska serija; vaš se interes evidentira kao smjer razvoja.",
      noDirection: "Vaši ciljevi ne upućuju na jedan smjer igre. Stručna provjera predlaže konfiguraciju.",
      incomplete: "Neki obvezni odgovori nedostaju — upotrijebite „Uredite odgovore” da ih dopunite.",
    },
    privacy: "GPS ne traži medicinske podatke ni identifikatore djece. U ovoj se sesiji preglednika pohranjuju samo odgovori s višestrukim odabirom; slobodan tekst ne pohranjuje se.",
  },
  build: {
    title: "Konfigurirajte svoj reket",
    lead: "Konfigurirajte zahtjev: serija, klasa preciznosti, navedena težina ili cilj po mjeri, veličina ručke, zahtijevani ciljevi, personalizacija, usklađeni setovi i količina. Rezultat je zahtjev za konfiguraciju s ID-om zahtjeva — a ne šifra artikla, cijena, datum isporuke ili certifikat.",
    steps: { series: "Serija", cls: "Klasa preciznosti", weight: "Težina", grip: "Ručka", targets: "Ciljevi", personal: "Personalizacija", set: "Set i količina", use: "Namjena", review: "Provjera" },
    q: {
      series: "Odaberite seriju",
      cls: "Odaberite klasu preciznosti",
      weightMode: "Težina",
      listed: "Navedena težina",
      customWeight: "Zahtijevana težina (g)",
      balanceShown: "Izračunani balans za ovu težinu",
      balanceRequest: "Zahtijevani balans (mm)",
      grip: "Tvornička veličina ručke",
      targetsTitle: "Zahtijevani ciljevi",
      swingweight: "Zahtijevani swingweight (kg·cm²)",
      stiffness: "Zahtijevana krutost (RA)",
      basis: "Osnova mjerenja za zahtijevane vrijednosti",
      engraving: "Tekst gravure",
      engravingHint: "Ime, inicijali ili broj. Latinična slova, brojke, razmak, crtica, apostrof i točka; do 24 znaka. Druga se pisma prihvaćaju uz potvrdu grafičkog rješenja.",
      engravingType: "Personalizacija",
      types: { none: "Bez personalizacije", name: "Ime igrača", initials: "Inicijali", number: "Broj seta", academy: "Identifikacija trenera ili akademije", team: "Timski program" },
      set: "Pojedinačni reket ili usklađeni set",
      use: "Namjena",
      uses: { play: "Osobna igra", competition: "Natjecanje", coaching: "Trenerski rad", team: "Tim ili akademija", retail: "Procjena za maloprodaju ili distribuciju", other: "Ostalo" },
      notes: "Dodatni tehnički zahtjevi",
    },
    classes: { "P2.5": "P2.5 — skalabilna osnova performansi", "P1.5": "P1.5 — napredna preciznost", "P0.5": "P0.5 — profesionalno, pojedinačno kontrolirano" },
    stiffExactShort: "krutost odgovara deklariranoj ciljnoj RA vrijednosti prema utvrđenom tvorničkom protokolu",
    clsNote: "Svaka klasa kontrolira četiri parametra. P0.5 je uska tolerancija prema definiranom protokolu mjerenja — a ne nulta pogreška. Serijski identitet, certifikati i dokumentacija o usklađenim setovima primjenjuju se samo tamo gdje ih program za vašu narudžbu provodi.",
    listedNote: "Iz potvrđene matrice serije.",
    customNote: "Težina izvan matrice, uz tehničku provjeru.",
    balanceCaption: "Za svaku je navedenu težinu prikazan izračunani balans u mm od kraja ručke. Izračunane vrijednosti nisu pojedinačna mjerenja.",
    spinNote: "Težine serije SPIN čine zahtijevanu arhitekturu težina. Balans, swingweight i krutost za SPIN nisu dostavljeni; definiraju se u tehničkoj provjeri.",
    customHint: "Cijeli grami, samo brojke. Težina po mjeri zahtjev je za tehničku provjeru; izvedivost se potvrđuje u pisanom obliku i nijedna se vrijednost ne zaokružuje.",
    gripNote: "tvornička geometrija karbonske ručke, a ne nadogradnja overgripom",
    targetsLead: "Neobvezno. Unesite samo vrijednosti koje su vam potrebne. Svaka se evidentira kao zahtijevani cilj za tehničku provjeru, a ne kao objavljena specifikacija.",
    basisHint: "Obvezno kada zahtijevate težinu po mjeri ili bilo koji cilj: odnose li se vrijednosti na reket bez žica ili sa žicama?",
    inputRange: "Prihvaćen unos: {min}–{max}.",
    inputRangeNote: "Rasponi unosa samo isključuju nemoguće vrijednosti. Ne opisuju proizvodnu sposobnost.",
    listedBasis: "navedene vrijednosti — osnova mjerenja potvrđuje se u pisanoj specifikaciji",
    notStored: "Ne pohranjuje se u ovom pregledniku; unesite ponovno ako osvježite stranicu.",
    artworkReview: "potrebna je potvrda grafičkog rješenja",
    previewNote: "Vizualni pregled ne prikazuje se: odobreni predložak gravure za ovaj model još nije objavljen. Vaš se tekst prikuplja radi potvrde grafičkog rješenja.",
    teamSub: "4–99 reketa po setu",
    setsLabel: { individual: "Broj reketa", pair: "Broj usklađenih parova", triple: "Broj usklađenih trojki", team: "Broj timskih setova" },
    teamSizeLabel: "Reketa po timskom setu",
    totalLabel: "Ukupno reketa",
    racquetsUnit: "reketa",
    setRule: "Količina se računa po setovima: usklađeni par ima 2 reketa po setu, usklađena trojka 3.",
    restart: "Započnite novu konfiguraciju",
    notices: { weightCleared: "{w} g nije u matrici serije {series}, pa je težina uklonjena. Odaberite navedenu težinu ili zatražite cilj po mjeri." },
    reviewTitle: "Zahtjev za konfiguraciju",
    reviewP: "Provjerite konfiguraciju, a zatim dodajte svoje kontaktne podatke. Zahtjev se pohranjuje s ID-om zahtjeva i na njega se odgovara u pisanom obliku; dostupnost i komercijalni uvjeti potvrđuju se u pisanom obliku.",
    reviewErrors: "Neki odgovori u konfiguraciji zahtijevaju pozornost:",
    edit: "Uredite",
    fieldNames: { series: "Serija", cls: "Klasa preciznosti", mode: "Odabir težine", weight: "Navedena težina", customWeight: "Zahtijevana težina", basis: "Osnova mjerenja", balanceReq: "Zahtijevani balans", sw: "Zahtijevani swingweight", ra: "Zahtijevana krutost", grip: "Veličina ručke", ptype: "Personalizacija", engraving: "Tekst gravure", setType: "Vrsta seta", sets: "Količina", teamSize: "Reketa po timskom setu", use: "Namjena", notes: "Dodatni zahtjevi" },
    status: { listed: "navedena težina", requestedArchitecture: "zahtijevana arhitektura težina", technicalReview: "zahtjev za tehničku provjeru", notPublished: "nije dostavljeno", requestedCondition: "zahtijevano stanje" },
    chooseLink: "Niste sigurni koja vam serija odgovara? Zatražite pomoć pri odabiru",
    cta: "Pošaljite zahtjev za konfiguraciju",
  },
  experience: {
    title: "Testiranje i prilagodba",
    statement: "Držite ga. Zamahnite njime. Osjetite ga.",
    lead: "Zatražite testiranje, prilagodbu ili demonstraciju uz podršku trenera. Zahtjevi se razmatraju i na njih se odgovara u pisanom obliku; poslan zahtjev nije potvrđen termin.",
    optionsTitle: "Što se može zatražiti",
    options: ["Testiranje reketa", "Sesija prilagodbe", "Demonstracija uz podršku trenera", "Demonstracija sustava Sweet Spot Trainer ili Spot Trainer", "Demo dan za tim ili akademiju"],
    formTitle: "Zahtjev za prilagodbu ili demonstraciju",
  },
  engineering: {
    title: "Inženjering i proizvodnja",
    statement: "Zrakoplovi. Jahte. Reketi.",
    lead: "Jedna inženjerska filozofija u tri okruženja: načela koja oblikuju zrakoplov, preciznost koja vodi jahtu kroz otvoreno more i performanse koje definiraju svaki MAXIMUS reket. Inženjerska priča — a ne tvrdnja o certifikaciji zrakoplova, vlasništvu nad jahtama, vlasništvu nad tvornicom ili izravnom prijenosu materijala.",
    manifesto: ["Vjerujemo da veliki inženjering nema granica.", "Jedna filozofija. Projektirano bez kompromisa."],
    capabilityTitle: "Proizvodna sposobnost",
    capabilityLead: "Sposobnost se prikazuje kao niz koraka, a ne kao slogan.",
    sequence: [
      ["Specifikacija", "Serija, klasa preciznosti, težina, balans, swingweight, ciljna krutost, geometrija ručke, personalizacija."],
      ["Proizvodnja", "Konstrukcija u cijelosti od karbona, od okvira do ručke, izrađena prema specifikaciji."],
      ["Kontrola kvalitete", "Mjerenje i zapisi prema klasi preciznosti: proizvodna evidencija, pojedinačni zapisi i sljedivost, pojedinačna certifikacija."],
      ["Ponovljena proizvodnja", "Ponovljiv odziv prema deklariranoj specifikaciji kroz proizvodne serije."],
      ["Sljedivost", "Serijski identitet, sljedivost proizvodne serije i Certifikat preciznosti tamo gdje ih klasa predviđa."],
    ],
    capacityNote: "Proizvodni kapacitet, rokovi izrade, minimalne količine i planovi isporuke potvrđuju se za svaki program u pisanom obliku, na temelju potvrđenih narudžbi i dogovorenog plana otpreme.",
    truth: "Kapacitet nije proizvedena količina, zaliha, zajamčen datum isporuke niti vlasništvo nad proizvodnim objektom.",
    cta: "Distribucija i razvoj tržišta",
    cta2: "Pošaljite tehnički zahtjev",
  },
  ecosystem: {
    title: "MAXIMUS ekosustav",
    lead: "Jedan ključ. Ovo je ono što otvara. Svaki čvor ima objašnjenje, točan status i relevantnu sljedeću radnju.",
    words: ["Inženjering", "Performanse", "Inovacija", "Zajednica", "Prilika", "Svrha"],
    nodes: {
      engineering: { h: "Inženjering i proizvodnja reketa", p: "Reketi u cijelosti od karbona, projektirani prema specifikaciji, proizvedeni sa zapisima kvalitete i sljedivošću.", a: "Inženjering i proizvodnja" },
      precision: { h: "Preciznost i pojedinačna konfiguracija", p: "Četiri parametra, tri klase preciznosti, osam veličina ručke i inženjering po mjeri.", a: "Preciznost i krutost" },
      training: { h: "Trening i metodologija", p: "Sweet Spot Trainer, Spot Trainer i strukturiran razvojni put.", a: "Sustavi za trening" },
      development: { h: "Razvoj igrača i trenera", p: "Odabir opreme uz trenera, zapisi, ponovna procjena i putevi edukacije.", a: "Metodologija" },
      identity: { h: "Osobni identitet i osobni brendovi", p: "Od gravure do osobnog ili profesionalnog brenda uređenog pravima.", a: "Osobni brendovi" },
      owners: { h: "Zapisi vlasnika, znanje i prava", p: "Predloženi trezor vlasnika s kontroliranim pristupom, za zapise o opremi, razvoju i pravima.", a: "Vlasnici i trezor" },
      mipa: { h: "MIPA podrijetlo i interna kontrola", p: "Interni sloj kontrole intelektualnog vlasništva, podrijetla i dokumentacije.", a: "Pravni identitet i kontrola" },
      digital: { h: "Digitalna infrastruktura i smjer Blockchain 5.0", p: "Podrijetlo, sljedivi zapisi, dokazi s kontroliranim pristupom i identitet proizvoda kao navedeni tehnološki smjer.", a: "Tehnološki smjer" },
      licensing: { h: "Ugovorno licenciranje i programi tantijema", p: "Licencirani brendovi, proizvodi i paketi prava, s uvjetima definiranima po ugovoru.", a: "Putevi licenciranja" },
      families: { h: "Sudjelovanje obitelji i pogodnosti programa", p: "Informirane odluke, kontinuitet, sačuvani zapisi i pogodnosti definirane programom.", a: "Obitelji i roditelji" },
      network: { h: "MAXIMUS Sports Network", p: "Igrači, treneri, klubovi, akademije, pružatelji usluga, operatori i regionalni partneri.", a: "Sports Network" },
      market: { h: "Klubovi, akademije, distribucija i razvoj tržišta", p: "Timski programi, maloprodaja, distribucija i razvoj teritorija uz pisanu kvalifikaciju.", a: "Putevi partnerstva" },
      institutional: { h: "Institucionalni programi, edukacija, inovacija i društveni utjecaj", p: "Institucionalni sloj koji osigurava MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tamo gdje program utvrđuje tu ulogu.", a: "Institucionalni programi" },
      extensions: { h: "Buduća proširenja na sportove s reketom i MAXIMUS odjeću", p: "Padel, pickleball, skvoš, badminton, reketbol, tenis na pijesku i odjeća kao smjerovi razvoja.", a: "Sportovi s reketom" },
    },
    boundaryTitle: "Granice",
    boundary: [
      "Kupnja reketa ne stvara institucionalno članstvo, upravljačka prava, tantijeme ni investicijska prava.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) institucionalni je operator samo tamo gdje program utvrđuje tu ulogu; prodaja opreme navodi svoj stvarni ugovorni subjekt.",
      "Bespovratna sredstva, status dobrotvorne organizacije, porezni tretman i regulatorna odobrenja ne primjenjuju se automatski u svim zemljama.",
    ],
    techTitle: "Tehnološki smjer",
    techP: "Blockchain 5.0 navedeni je tehnološki smjer MAXIMUS-a. Njegove su funkcionalne namjene podrijetlo, sljedivi zapisi, dokazi s kontroliranim pristupom, identitet proizvoda i usklađivanje kvalificiranih komercijalnih događaja. Ne prikazuje se nikakav mehanizam konsenzusa, transakcijski kapacitet, mreža čvorova, adresa pametnog ugovora, token ni neovisna certifikacija i ne tvrdi se da je implementacija postavljena. Osobni podaci, zapisi o djeci i povjerljivi ugovori nikada se po pravilu ne unose u javni nepromjenjivi sustav.",
  },
  brands: {
    title: "Osobni brendovi i ambasadori",
    statement: "Od igrača do brenda. Od trenera do brenda.",
    lead: "Zaseban put za osobni brend. Uključenost MAXIMUS-a obuhvaća razvoj brenda i dogovorenu promociju — a ne samo ime na reketu.",
    progressionTitle: "Predviđeni razvoj",
    progression: [
      ["Verificiran identitet", "Verificiran identitet i povijest razvoja."],
      ["Prepoznatljiv brend", "Prepoznatljiv osobni ili profesionalni brend."],
      ["Sadržaj s riješenim pravima", "Sadržaj s riješenim pravima i odobren identitet proizvoda."],
      ["Inženjering i kolekcije", "Inženjering i razvoj kolekcije tamo gdje je dogovoreno."],
      ["Promocija", "Promocija kroz dogovorene MAXIMUS kanale i partnerstva."],
      ["Sudjelovanje", "Ugovorno sudjelovanje u kvalificiranoj prodaji ili licenciranju."],
      ["Izvješćivanje", "Transparentno izvješćivanje u skladu s ugovorom."],
    ],
    royaltiesTitle: "Tantijeme i licenciranje",
    royalties: [
      "Tantijeme se vezuju za definirani licencirani brend, proizvod, transakciju ili paket prava.",
      "„Prodaja na svjetskoj razini” znači kvalificiranu prodaju u okviru obuhvata ugovora — nikada svaki nepovezani MAXIMUS reket.",
      "Stope, osnovica obračuna, teritoriji, trajanje, povrati, odbici, izvješćivanje, obračun i provjera definiraju se odgovarajućim ugovorom. Nijedan podrazumijevani postotak tantijema ne objavljuje se.",
      "Nijedna globalna kampanja, medijski proračun, rezultat sponzorstva ni komercijalni uspjeh ne obećavaju se bez dogovorenog obuhvata.",
    ],
    cta: "Pošaljite upit za suradnju na brendu",
    cta2: "Upit za partnerstvo s trenerom",
  },
  families: {
    title: "Obitelji i roditelji",
    lead: "Informirane odluke o opremi, kontinuitet razvoja, sačuvano znanje i prava, vidljivost sudjelovanja te pogodnosti definirane programom koje mogu podržati buduće aktivnosti.",
    nowTitle: "Dostupno sada",
    now: ["Upiti o obitelji i razvoju u pisanom obliku.", "Odabir opreme uz uključenost trenera, zahtjevi za prilagodbu i demonstraciju.", "Privatni zapisi: profili djece nikada se ne objavljuju i po pravilu se ne komercijaliziraju.", "Put edukacije za roditelje: konfiguracija, opterećenje, progresija, zapisi i prava."],
    plannedTitle: "Planirano",
    planned: ["Pogodnosti sudjelovanja definirane programom, upotrebljive za robu i usluge unutar ekosustava, a ne kao kamata u novcu.", "Zapisi vlasnika i obitelji u predloženom trezoru vlasnika, s odobrenjima skrbnika i prijenosom kontrole s 18 godina."],
    categoriesTitle: "Strogo odvojeno",
    categories: ["Ugovorne tantijeme iz licenciranih prava ili kvalificirane prodaje", "Pogodnosti sudjelovanja definirane programom", "Krediti za kupnju ili usluge", "Predujmovi", "Institucionalno članstvo"],
    categoriesP: "Te se kategorije nikada ne tretiraju kao zamjenjive.",
    statusTitle: "Stvarni status obiteljskog programa",
    journeyTitle: "Put za obitelji",
    journey: [
      ["Cilj", "Što igrač želi postići u sljedećem koraku."],
      ["Trenutna razina", "Gdje je igrač danas."],
      ["Trener", "Sudjeluje li trener u odlukama o opremi."],
      ["Oprema", "Oprema odgovarajuća za tu fazu, uključujući sustave za trening kada je to relevantno."],
      ["Dogovoren trening", "Uporaba pod vodstvom trenera, dogovorena unaprijed."],
      ["Provjera", "Ponovna procjena u usporedivim kontrolnim točkama."],
    ],
    brief: {
      who: "Roditelji i skrbnici igrača u svakoj fazi.",
      value: "Pisani odgovor o odgovarajućoj opremi, uključenosti trenera i sljedećem razvojnom koraku.",
      now: "Obiteljski upiti u pisanom obliku; odabir uz uključenost trenera; privatni zapisi — profili djece nikada se ne objavljuju.",
      next: "Pošaljite obiteljski upit u nastavku. ID zahtjeva dobivate odmah.",
    },
    formTitle: "Obiteljski upit",
    formNote: "Obrazac ispunjava roditelj ili skrbnik. Ne navodite ime djeteta, datum rođenja, školu ni medicinske podatke.",
    noPromise: "Kupnja ne obećava tantijeme, prinose od ulaganja, sponzorstvo niti financiranje razvoja djeteta.",
    statusP: "Ovo izdanje objašnjava model i prihvaća upite o programu. Obračun, isplate i iskorištavanje nisu dostupni dok se kvalificirani događaji, korisnici, izvor sredstava, osnovica obračuna, dopuštene namjene, računovodstveni tretman, povrati, storniranja, rokovi važenja, prenosivost, zatvaranje programa i rješavanje sporova ne definiraju u pisanom obliku. Ne obećava se da nijedno stanje nikada neće pasti, nijedno sudjelovanje ne pokriva cijeli trening i ne podrazumijeva se zaštita kapitala.",
    cta: "Pošaljite obiteljski ili razvojni upit",
  },
  owners: {
    title: "Vlasnici i trezor vlasnika",
    lead: "Trezor vlasnika predložena je evidencija s kontroliranim pristupom, o opremi, razvoju, znanju, sadržaju i dokumentiranim pravima. Predstavljen je kao dio planirane arhitekture za vlasnike: ne prikazuju se aktivni računi, stanja, certifikati ni postignuća.",
    nowTitle: "Za sadašnje vlasnike sada",
    now: ["Upiti vlasnika: referenca proizvoda ili serijski broj, postavljanje, servis i zahtjevi za zapise u pisanom obliku.", "Certifikat preciznosti i dokumentacija o usklađenom setu tamo gdje ih klasa preciznosti predviđa, dostavljeni s proizvodom."],
    archTitle: "Planirana arhitektura trezora",
    arch: ["Identitet proizvoda i serijske reference", "Konfiguracija i primjenjivi certifikati kontrole kvalitete", "Povijest servisa i postavljanja", "Zapisi o razvoju igrača ili trenera", "Kvalifikacije i verificirana postignuća", "Mediji s riješenim pravima i autorski materijali", "Licencije, dozvole i reference ugovora", "Zapisi o programu osobnog brenda", "Primjenjivi obračuni tantijema ili pogodnosti sudjelovanja"],
    separationTitle: "Što znači vlasništvo",
    separation: [
      "Vlasništvo nad fizičkim reketom odvojeno je od vlasništva nad autorskim pravom, licencijom, ugovornim pravom ili zapisom koji te stvari opisuje.",
      "Pohranjen dokument ili unos u blockchain nije automatski dokaz da pravo postoji ili da je preneseno.",
      "Dokaz zadržava svoju klasifikaciju: prijavio sudionik, potvrdio skrbnik, validirao trener, izmjerio sustav.",
      "Za maloljetnike: privatni zapisi, odobrenja skrbnika, bez objavljenih profila djece i bez komercijalizacije identiteta po pravilu.",
      "Izvoz, ispravak, kontrola pristupa i odgovarajući prijenos kontrole dio su projektiranog rješenja.",
    ],
    techTitle: "Blockchain 5.0 i MxSN",
    techP: "Blockchain 5.0 navedeni je tehnološki smjer; MxSN definira koncepte mreže s kontroliranim pristupom za suglasnost, dostavu, dokaze, prava i izvješćivanje. Operativna implementacija ne prikazuje se. Model podataka aplikacije izgrađen je tako da se kasnije integrira preko dokumentiranog sučelja, bez pretvaranja da veza danas postoji.",
    cta: "Upit vlasnika",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Veza između igrača, trenera, klubova, akademija, pružatelja usluga, operatora programa i regionalnih partnera.",
    functionsTitle: "Moguće funkcije",
    functions: ["Pronalaženje", "Upoznavanje", "Razvojni programi", "Podrška u opremi", "Događanja", "Pristup uslugama", "Partnerske prilike"],
    statusTitle: "Stvarni status",
    statusP: "Javni imenik još nije objavljen: navedeni će biti samo sudionici čiji su identitet, odnos i odobrenje za prikazivanje utvrđeni. Prijedlog poslan klubu nije partnerstvo, a potencijalni distributer nije imenovani distributer. Objava imenika, rezervacije, razmjena poruka i komercijalne transakcije kontroliraju se odvojeno i nisu aktivni.",
    cta: "Prijavite se u mrežu",
  },
  partnerships: {
    title: "Putevi partnerstva",
    lead: "Prvo pisana kvalifikacija. Svaki put vodi do upita specifičnog za ulogu; komercijalni uvjeti slijede u pisanom obliku.",
    commercialTitle: "Moguće komercijalne aktivnosti platforme",
    commercial: ["Oprema", "Inženjering po mjeri", "Personalizacija", "Programi za timove i akademije", "Sustavi za trening", "Ugovorno licenciranje", "Distribucija", "Odobrene usluge", "Buduće kategorije proizvoda"],
    boundary: "Prava za zemlju, ekskluzivnost, naknade za teritorij i marže distributera predmet su pregovora. Ne objavljuju se prihodi, projekcije, procjene vrijednosti, tržišni udjeli, prinosi, obveze financiranja niti neimenovana partnerstva.",
    routes: {
      coaches: {
        title: "Treneri",
        lead: "Sustavi za trening, prilagodba, profesionalni identitet, ovlašteni programi, prilike za osobni brend i opskrba opremom.",
        points: ["Sweet Spot Trainer i Spot Trainer u treningu pod vodstvom trenera.", "Prilagodba pomoću matrica konfiguracije i osam tvorničkih veličina ručke.", "Coach-to-Brand: verificiran profesionalni profil i podbrend uređen pravima.", "Ovlaštena uporaba programa slijedi iz pisanog ugovora."],
        cta: "Pošaljite upit za partnerstvo s trenerom",
        brief: {
          who: "Samostalni treneri i trenerski timovi.",
          value: "Sustavi za trening pod vodstvom trenera, prilagodba pomoću matrica serija i osam tvorničkih veličina ručke te put do profesionalnog identiteta.",
          now: "Upiti trenera u pisanom obliku. Nijedna provizija, zarada ni stopa za preporuku ne objavljuje se niti podrazumijeva.",
          next: "Pošaljite upit za trenere u nastavku. Uvjeti slijede u pisanom obliku.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubovi i akademije",
        lead: "Timska oprema, sustavi za trening, personalizacija, razvojni programi, servis i sudjelovanje u mreži.",
        points: ["Timski i usklađeni setovi traže se preko konfiguratora.", "Sustavi za trening i metodologija za strukturiran razvoj.", "Personalizacija za timske programe na odobrenim zonama.", "Demo dani, sesije prilagodbe i sudjelovanje u mreži."],
        cta: "Pošaljite zahtjev kluba ili akademije",
        brief: {
          who: "Klubovi, akademije i timski programi.",
          value: "Timski i usklađeni setovi, sustavi za trening, personalizacija za timske programe i demonstracijski dani.",
          now: "Zahtjevi klubova i akademija u pisanom obliku; timski se setovi traže preko konfiguratora.",
          next: "Pošaljite zahtjev kluba ili akademije u nastavku.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribucija i razvoj tržišta",
        lead: "Asortiman, koordinacija proizvodnje, tehnička sposobnost, razvoj teritorija i povjerljiva komercijalna kvalifikacija.",
        points: ["Pisana kvalifikacija partnera, teritorija i kanala.", "Asortiman definiran iz matrica konfiguracije i klasa preciznosti.", "Teritorij, ekskluzivnost, količine, cijene i komercijalna zaštita predmet su pregovora i dogovaraju se u pisanom obliku.", "Ugovorni subjekt, uvjeti plaćanja i osnova isporuke određuju se za svaku transakciju."],
        cta: "Pošaljite upit za distribuciju ili razvoj tržišta",
        brief: {
          who: "Trgovci, distributeri i partneri po zemljama.",
          value: "Asortiman definiran iz potvrđenih matrica, klasa preciznosti i raspona veličina ručke, uz pisanu kvalifikaciju teritorija i kanala.",
          now: "Upiti za distribuciju u pisanom obliku. Teritorij, ekskluzivnost, količine i cijene predmet su pregovora — nijedno se ne dodjeljuje putem obrasca.",
          next: "Pošaljite upit za distribuciju u nastavku.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategija i ulaganja",
        lead: "Inženjerska sposobnost, dubina konfiguracije, model proizvodnje, putevi na tržište, intelektualno vlasništvo, usluge i prilike za širenje.",
        points: ["Kvalificiran strateški razgovor ili kontroliran pristup informacijama slijedi nakon pisane kvalifikacije.", "Javne su informacije ograničene na odobrene specifikacije proizvoda, arhitekturu konfiguracije, verificirane sposobnosti i objašnjenja programa.", "Ekonomika specifična za kupca, obračun troškova, zaštićena metodologija i neobjavljeni ugovori otkrivaju se samo pod NDA ili ugovorom."],
        cta: "Zatražite kvalificiran strateški razgovor",
        brief: {
          who: "Ulagači i strateški partneri.",
          value: "Kvalificiran razgovor o inženjerskoj sposobnosti, dubini konfiguracije, modelu proizvodnje, putevima na tržište i intelektualnom vlasništvu.",
          now: "Ne objavljuju se financijski podaci, projekcije, procjene vrijednosti ni prinosi. Kontrolirane informacije slijede nakon pisane kvalifikacije i NDA.",
          next: "Zatražite kvalificiran strateški razgovor u nastavku.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institucionalni programi",
        lead: "Edukacija, pristup, inovacija, dokazi o razvoju, društveni utjecaj i programi odgovarajuće strukture.",
        points: ["Institucionalni se programi strukturiraju preko MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tamo gdje program utvrđuje tu ulogu.", "Namjenska sredstva programa i komercijalne transakcije ostaju odvojeni.", "Upit nije prihvaćena prijava za članstvo, a kupac opreme nije institucionalni član.", "Bespovratna sredstva, status dobrotvorne organizacije, porezni tretman i regulatorna odobrenja ovise o zemlji i nikada se ne podrazumijevaju."],
        cta: "Pošaljite upit za institucionalni program",
        brief: {
          who: "Institucije, obrazovni i razvojni programi.",
          value: "Programi za edukaciju, pristup, inovaciju i dokaze o razvoju, strukturirani s odgovarajućim operatorom.",
          now: "Institucionalni upiti u pisanom obliku. Upit nije prijava za članstvo; kupnja opreme nije institucionalno članstvo.",
          next: "Pošaljite institucionalni upit u nastavku.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Javno i kontrolirano otkrivanje",
    disclosure: {
      public: { h: "Javno", p: "Odobrene specifikacije proizvoda, konstrukcija, arhitektura konfiguracije, namjene treninga, verificirane sposobnosti, objašnjenja programa i putevi partnerstva." },
      qualified: { h: "Kvalificiran upit", p: "Tehnički zahtjevi, količine, interes za teritorij, obuhvat razvoja i relevantni komercijalni razgovori." },
      controlled: { h: "Kontrolirano NDA ili ugovorom", p: "Interne formule, detaljni protokoli kontrole kvalitete, slojevi karbona, alati, metode proizvodnje, identitet dobavljača, obračun troškova, ekonomika specifična za kupca, zaštićena metodologija, neobjavljeni ugovori i osjetljivi zapisi o pravima." },
    },
  },
  contact: {
    title: "Kontakt i zahtjevi",
    lead: "Odaberite svrhu svojeg zahtjeva. Svaki obrazac prikuplja samo ono što je potrebno za usmjeravanje i procjenu. Na zahtjeve se odgovara u pisanom obliku.",
    email: "E-pošta",
    instagram: "Instagram",
    legalLink: "Pravni identitet",
  },
  form: {
    purposeLabel: "Svrha zahtjeva",
    purposes: {
      selection: "Pomoć pri odabiru reketa",
      product: "Upit o proizvodu",
      fitting: "Prilagodba ili demonstracija",
      technical: "Tehnički zahtjev",
      config: "Zahtjev za konfiguraciju",
      gps: "GPS profil opreme",
      coach: "Partnerstvo s trenerom",
      club: "Zahtjev kluba ili akademije",
      distribution: "Distribucija ili razvoj tržišta",
      brand: "Suradnja na brendu ili ambasador",
      family: "Obiteljski ili razvojni upit",
      institutional: "Institucionalni program",
      strategic: "Strateški razgovor ili razgovor o ulaganju",
      owner: "Upit vlasnika",
      network: "Prijava za Sports Network",
      general: "Opći upit",
    },
    fields: {
      name: "Ime",
      email: "E-pošta",
      role: "Vaša uloga",
      country: "Zemlja ili regija",
      organisation: "Organizacija",
      message: "Vaša poruka",
      level: "Trenutna razina",
      objectives: "Što je najvažnije (do tri)",
      currentRacquet: "Trenutni reket",
      grip: "Veličina ručke, ako je poznata",
      seriesInterest: "Serija koja vas zanima",
      quantity: "Količina",
      city: "Grad ili mjesto za sesiju",
      coachInvolved: "Je li trener uključen?",
      timing: "Željeni termin",
      targets: "Željeni ciljevi",
      limits: "Obvezna ograničenja",
      use: "Namjena",
      tradeoffs: "Prihvatljivi kompromisi",
      basis: "Osnova mjerenja",
      players: "Broj igrača",
      interests: "Područja interesa",
      territory: "Teritorij interesa",
      channels: "Postojeći kanali i iskustvo",
      audience: "Publika ili disciplina",
      proposal: "Predložena suradnja",
      goal: "Razvojni cilj",
      ageBand: "Dobna skupina igrača",
      scope: "Obuhvat programa",
      interestArea: "Područje interesa",
      productRef: "Referenca proizvoda ili serijski broj",
      requestType: "Vrsta zahtjeva",
      seeking: "Što tražite",
      consent: "Prihvaćam da MAXIMUS može pohraniti i koristiti ove podatke radi odgovora na ovaj zahtjev. Ovo nije prijava na marketinške poruke.",
    },
    roles: { player: "Igrač", parent: "Roditelj ili skrbnik", coach: "Trener", club: "Klub ili akademija", retailer: "Trgovac", distributor: "Distributer", brand: "Brend ili ambasador", investor: "Ulagač ili strateški partner", institution: "Institucija", other: "Ostalo" },
    interestOptions: { training: "Sustavi za trening", fitting: "Prilagodba", identity: "Profesionalni identitet", programmes: "Ovlašteni programi", brand: "Osobni brend", supply: "Opskrba opremom", team: "Timska oprema", personalisation: "Personalizacija", development: "Razvojni programi", service: "Servis", network: "Sudjelovanje u mreži" },
    ownerTypes: { setup: "Postavljanje i konfiguracija", service: "Servis", records: "Zapisi i certifikati", other: "Ostalo" },
    strategicAreas: { engineering: "Inženjerska sposobnost", configuration: "Dubina konfiguracije", manufacturing: "Model proizvodnje", routes: "Putevi na tržište", ip: "Intelektualno vlasništvo i usluge", expansion: "Prilike za širenje" },
    errors: {
      required: "Ovo je polje obvezno.",
      too_long: "Ovaj je unos predugačak.",
      too_short: "Ovaj je unos prekratak.",
      invalid_email: "Unesite ispravnu adresu e-pošte, na primjer name@example.com.",
      invalid_choice: "Odaberite jednu od opcija.",
      not_number: "Unesite cijeli broj, samo brojke.",
      out_of_range: "Ova je vrijednost izvan prihvaćenog raspona.",
      not_in_matrix: "Ova težina nije u navedenoj matrici odabrane serije.",
      decimal_not_supported: "Unesite cijeli broj, bez decimala.",
      too_many: "Odaberite najviše tri opcije.",
      consent_required: "Suglasnost je obvezna kako bi MAXIMUS mogao odgovoriti na ovaj zahtjev.",
      invalid: "Ovaj unos nije ispravan.",
    },
  },
  legal: {
    title: "Pravni identitet i kontrola",
    lead: "Javni je brend MAXIMUS / MAXIMUS GPS. Pravni operativni subjekti razlikuju se i navedeni su ovdje.",
    entities: {
      institutional: { role: "Institucionalni programski sloj", p: "Osigurava institucionalni programski sloj tamo gdje program utvrđuje tu ulogu. Nije komercijalni prodavač reketa. Neprofitna inkorporirana organizacija u Dubai International Financial Centre." },
      equipment: { role: "Komercijalni subjekt za opremu", p: "Komercijalni subjekt za opremu, za opskrbu, distribuciju i ugovorenu komercijalnu isporuku tamo gdje aktualni operativni dokumenti utvrđuju tu ulogu. Ugovorna strana za svaku transakciju navedena je u dokumentima te transakcije." },
      ip: { role: "Intelektualno vlasništvo, brend i komercijalna koordinacija", p: "Pojavljuje se za utvrđenu ulogu u području intelektualnog vlasništva, brenda ili komercijalne koordinacije. Ne dodjeljuje se nijedna nepotvrđena ugovorna odgovornost." },
      stewardship: { role: "Referenca upravljanja", p: "House of Maximus referenca je upravljanja za ekosustav tamo gdje je to podržano odgovarajućim izvorom." },
      control: { role: "Interna kontrola intelektualnog vlasništva, podrijetla i dokumentacije", p: "MIPA je interni sloj kontrole intelektualnog vlasništva, podrijetla i dokumentacije. Interni MIPA unos razlikuje se od vanjske registracije žiga, patenta ili autorskog prava i od sudskog priznanja te ne predstavlja odobrenje vizualnog rješenja." },
    },
    labels: { licence: "Licencija", registration: "Registracija", vat: "VAT TRN", address: "Adresa", email: "E-pošta", jurisdiction: "Jurisdikcija" },
    boundaryTitle: "Granice",
    boundary: [
      "Kupnja ne daje automatski institucionalno članstvo, upravljačka prava, tantijeme ni investicijska prava.",
      "Institucionalna je uloga odvojena od komercijalnih transakcija s opremom.",
      "Privatnost, uvjeti programa i rješenja za kontroliran pristup odgovaraju funkcijama koje su stvarno objavljene.",
      "Nijedna opća izjava o mjerodavnom pravu ne primjenjuje se na svakog posjetitelja, svaku prodaju ili svaki program u inozemstvu; ugovorna se osnova određuje po ugovoru.",
    ],
  },
  privacy: {
    title: "Privatnost",
    updated: "Verzija 2026-09-21 · web-stranice 4.2",
    contactTitle: "Kontakt za pitanja o privatnosti",
    sections: {
      collect: ["Što se prikuplja", "Kada pošaljete obrazac: podaci koje unesete (ime, e-pošta, uloga, zemlja ili regija, organizacija ako je navedena, vaša poruka i odgovori iz obrasca), parametri stranice i kampanje vašeg posjeta (ulazna stranica, jezik, utm parametri; identifikatori klikova na oglase samo ako ste dopustili analitiku) te vrijeme slanja. Vaša se IP adresa koristi samo u heširanom obliku kratkog trajanja, radi ograničavanja zloupotrebe, i ne pohranjuje se s vašim zahtjevom."],
      purpose: ["Zašto", "Da se odgovori na vaš zahtjev, da se pripremi ponuda ili specifikacija koju ste zatražili i da se vodi evidencija o zahtjevu. Na temelju obrasca ne šalju se marketinške poruke."],
      storageOn: ["Gdje se zahtjevi pohranjuju", "Zahtjevi se pohranjuju u bazi podataka društva Upstash, Inc. (Redis), koja se osigurava preko platforme za hosting Vercel Inc."],
      notifyEmail: ["Obavijest o novom zahtjevu", "Kada se zahtjev prihvati, obavijest s podacima koje ste poslali šalje se e-poštom na odgovorni MAXIMUS poštanski sandučić."],
      notifyTelegram: ["Obavijest o novom zahtjevu", "Kada se zahtjev prihvati, obavijest s podacima koje ste poslali šalje se odgovornoj osobi u MAXIMUS-u preko Telegrama (Telegram FZ-LLC, Dubai), koji zato obrađuje tu obavijest u prijenosu."],
      notifyWebhook: ["Obavijest o novom zahtjevu", "Kada se zahtjev prihvati, obavijest s podacima koje ste poslali šalje se na internu MAXIMUS adresu, preko potpisane i šifrirane veze."],
      notifyNone: ["Obavijest o novom zahtjevu", "Obavješćivanje o novim zahtjevima je u postavljanju. Vaš se zahtjev pohranjuje i MAXIMUS ga čita iz internog registra; ništa se za tu namjenu ne šalje trećoj strani."],
      storageOff: ["Gdje se zahtjevi pohranjuju", "Pohrana zahtjeva je u postavljanju. Dok ne postane aktivna, obrasci navode da zahtjev ne može biti prihvaćen; ništa se ne pohranjuje. Web-stranice hostira Vercel Inc."],
      browser: ["Pohrana u pregledniku", "Pohrana sesije zadržava odgovore s višestrukim odabirom iz GPS-a i konfiguratora te parametre kampanje vašeg posjeta za ovu sesiju preglednika. Kontaktni podaci, slobodan tekst, tekst gravure i podaci o djeci ne pohranjuju se u pregledniku."],
      analyticsOn: ["Analitika", "Uz vašu suglasnost, Google Analytics 4 mjeri posjete i događaje u obrascima, bez kontaktnih podataka i bez teksta zahtjeva. Vaš se odabir pohranjuje u lokalnoj pohrani i može se promijeniti u svakom trenutku preko „Postavke analitike” u podnožju. Obrasci rade i bez analitike."],
      analyticsOff: ["Analitika", "Na ovim web-stranicama nije aktivan nijedan alat za analitiku."],
      retention: ["Rok pohrane", "Automatski rok brisanja još nije postavljen. U svakom trenutku možete zatražiti brisanje svojeg zahtjeva."],
      children: ["Djeca", "Obrasce ispunjava punoljetna osoba. Zahtjeve za igrače mlađe od 18 godina podnosi roditelj ili skrbnik. Ne unosite ime djeteta, datum rođenja, školu ni medicinske podatke. Profili djece nikada se ne objavljuju."],
      rights: ["Vaša prava", "Za pristup, ispravak ili brisanje svojeg zahtjeva pišite na gps@maximus.tennis i navedite ID zahtjeva."],
      controlled: ["Kontrolirane informacije", "Povjerljivi dokumenti ne pohranjuju se na ovim web-stranicama i ne dostavljaju se preko njih. Kontrolirano otkrivanje provodi se pod NDA ili ugovorom, preko odvojenih kanala."],
    },
  },
  terms: {
    title: "Uvjeti korištenja",
    copyright: "Autorsko pravo na ovim web-stranicama — na njihovim tekstovima, fotografijama, dizajnu i kodu — pripada isključivo Maximusu Kiriyakulovu. Nije preneseno nijednoj tvrtki niti bilo kojoj drugoj osobi.",
    updated: "Verzija 2026-09-21",
    sections: [
      ["Informacija, ne ponuda", "Informacije o proizvodima na ovim web-stranicama opisuju odobrene specifikacije, arhitekturu konfiguracije i objašnjenja programa. Nisu ponuda za prodaju, cjenik, izjava o zalihama niti obveza isporuke. Komercijalni se uvjeti dogovaraju posebno, u pisanom obliku, s ugovornim subjektom navedenim u svakoj transakciji."],
      ["Zahtjevi", "Zahtjev poslan preko ovih web-stranica — uključujući GPS profile, zahtjeve za konfiguraciju i tehničke zahtjeve — pohranjuje se s ID-om zahtjeva i razmatra se. Nije prihvaćena narudžba, proizvodna obveza, potvrđen termin, prijava za članstvo niti prihvaćena prijava za bilo koji program."],
      ["Specifikacije i dokazi", "Izračunane vrijednosti, proizvodni ciljevi i potvrđene specifikacije razlikuju se na odgovarajućim stranicama. Vrijednosti su krutosti proizvodni ciljevi dok se ne objavi drugačije. Nijedan rezultat za pojedinog igrača nije zajamčen."],
      ["Ekosustav, članstvo i prava", "Kupnja reketa ne stvara institucionalno članstvo, investicijska prava, nositeljstvo prava intelektualnog vlasništva, pravo na tantijeme niti pogodnosti sudjelovanja. Prava proizlaze iz objavljenih uvjeta programa ili iz pisanog ugovora."],
      ["Intelektualno vlasništvo", "MAXIMUS®, amblem lava, oznaka GPS i sadržaj ovih web-stranica zaštićeni su. Interne inženjerske formule, protokoli kontrole kvalitete, slojevi karbona, alati, identitet dobavljača, obračun troškova i zaštićena metodologija ne otkrivaju se ovdje."],
    ],
  },
  lead: {
    submit: "Pošaljite zahtjev",
    submitting: "Šalje se…",
    retry: "Pokušajte ponovno",
    acceptedEyebrow: "Zahtjev je prihvaćen",
    acceptedTitle: "Vaš je zahtjev primljen.",
    requestId: "ID zahtjeva",
    acceptedNext: "MAXIMUS razmatra svaki zahtjev i odgovara u pisanom obliku na adresu e-pošte koju ste naveli. Sačuvajte ID zahtjeva za svaku daljnju komunikaciju.",
    duplicate: "Ovaj je zahtjev već bio primljen; duplikat nije izrađen.",
    another: "Započnite novi zahtjev",
    errorsTitle: "Provjerite ova polja:",
    failTitle: "Vaš zahtjev nije poslan.",
    fail: {
      offline: "Vaš uređaj nije povezan s mrežom.",
      network: "Veza s poslužiteljem nije uspjela.",
      timeout: "Poslužitelj nije odgovorio na vrijeme.",
      rate_limited: "S ove je mreže došlo previše zahtjeva. Pokušajte ponovno za nekoliko minuta.",
      too_fast: "Obrazac je poslan vrlo brzo. Provjerite ga i pošaljite ponovno.",
      spam_suspected: "Zahtjev je zaustavio filtar neželjene pošte.",
      unavailable: "Zahtjevi se trenutačno ne mogu prihvatiti.",
      default: "Došlo je do neočekivane pogreške.",
    },
    keepNote: "Vaš unos ostaje na ovoj stranici pa možete pokušati ponovno.",
    sendByEmail: "Pošaljite ovaj zahtjev e-poštom",
    sendByEmailNote: "Vaša se aplikacija za e-poštu otvara s tekstom ovog zahtjeva. MAXIMUS ga prima kada pošaljete e-poruku.",
    mailConfig: "Konfiguracija",
    mailPage: "Stranica",
    fallback: "Ako se problem nastavi, pišite na {email}. Zahtjev se smatra poslanim samo kada se prikaže ID zahtjeva.",
    privacyLink: "Obavijest o privatnosti",
    hpLabel: "Ostavite ovo polje prazno",
    consentShort: "Suglasnost",
    after: "Nakon slanja ID zahtjeva prikazuje se na ovoj stranici. Zahtjevi se razmatraju i na njih se odgovara u pisanom obliku; zahtjev nije narudžba.",
    basis: { unstrung: "Bez žica", strung: "Sa žicama", unknown: "Nisam siguran — dogovoriti u specifikaciji" },
    hints: {
      email: "MAXIMUS odgovara u pisanom obliku na ovu adresu.",
      goal: "Na primjer: prvi natjecateljski reket ili prelazak s juniorskog reketa. Ne navodite imena, datume rođenja ni medicinske podatke o djetetu.",
      currentRacquet: "Marka i model, ako su poznati.",
      message: "Ne navodite lozinke, podatke o plaćanju ni medicinske podatke.",
    },
  },
  choose: {
    eyebrow: "Pomoć pri odabiru",
    title: "Pomozite mi odabrati reket",
    lead: "Recite MAXIMUS-u svoju razinu i što vam je najvažnije. Vaši se odgovori razmatraju i dobivate pisani prijedlog: serija, klasa preciznosti, težina i veličina ručke.",
    stepsTitle: "Što slijedi",
    steps: [
      ["Vaši odgovori", "Razina, prioriteti i veličina ručke ako je znate."],
      ["Stručna provjera", "MAXIMUS uspoređuje vaše odgovore s matricama serija."],
      ["Pisani prijedlog", "Predložena konfiguracija i sljedeći korak, u pisanom obliku."],
    ],
    formTitle: "Vaši odgovori",
    submit: "Zatražite pomoć pri odabiru",
    altTitle: "Želite sami odlučiti?",
    altGps: "Detaljan GPS profil",
    altBuild: "Konfigurirajte izravno",
    note: "Bez automatske prilagodbe i bez tvrdnje o točnosti: svaki zahtjev pregledava čovjek.",
  },
  consent: {
    title: "Analitika",
    text: "Smije li MAXIMUS mjeriti posjete pomoću Google Analyticsa? Obrasci rade u svakom slučaju; analitici se ne šalju kontaktni podaci ni tekst zahtjeva.",
    allow: "Dopustite analitiku",
    decline: "Odbijte",
  },
  media: {
    spotHeadsUp: "Pet MAXIMUS Spot Trainera jedan uz drugi, okruglim glavama za kontakt prema gore i ručkama prema dolje, s lopticama koje leže na glavama",
    greatHero: "MAXIMUS GREAT serija, 363 g: cjelovita kompozicija s crvenim i žutim detaljima na glavi, sjajnim MAXIMUS natpisom, Maximusovim autogramom na vratu reketa i poklopcem ručke s lavom",
    spotRow: "Pet MAXIMUS Spot Trainera poredanih u niz, s lopticama koje leže na okruglim glavama za kontakt",
    spotPair: "Dva MAXIMUS Spot Trainera stoje uspravno pred amblemom MAXIMUS lava, s lopticama na okruglim glavama za kontakt",
    spinVisual: "MAXIMUS SPIN: glava sa žicama, sjajni MAXIMUS natpis, ručka i poklopac ručke s lavom",
    powerVisual: "MAXIMUS POWER: glava sa žicama, sjajni MAXIMUS natpis, gravura personalizacije, ručka i poklopac ručke s lavom",
    greatVisual: "MAXIMUS GREAT: glava sa žicama, sjajni MAXIMUS natpis, gravura personalizacije, ručka, poklopac ručke s lavom i oznaka serije G na grlu reketa",
    spinHead: "MAXIMUS SPIN glava i površina žica",
    handleLion: "MAXIMUS grlo reketa, ručka i poklopac ručke s oznakom lava",
    engraving: "Srebrna gravura personalizacije na vratu reketa",
    lettering: "Sjajni crni MAXIMUS natpis na mat crnom okviru",
    variantAlt: "MAXIMUS serija {series} — {w} g, balans {b} mm: cjelovita vizualizacija s trakom specifikacije, zonom gravure personalizacije i MIPA oznakom",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sustav od četiri reketa",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Vratovi reketa Sweet Spot Trainer s MAXIMUS natpisom",
    sstGrips: "Ručke i poklopci ručki Sweet Spot Trainera",
    sstButtcaps: "Sweet Spot Trainer, četiri poklopca ručke s oznakom lava",
    note: "Vizual proizvoda",
  },
  notFound: { title: "Stranica nije pronađena", p: "Stranica koju ste zatražili ne postoji na ovom jeziku.", cta: "Idite na početnu stranicu" },
};

export default hr;
