/* Indonesian dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const id = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — raket tenis karbon penuh yang direkayasa sesuai spesifikasi",
    defaultDescription:
      "Raket tenis karbon penuh dari rangka hingga gagang: GREAT 97 in², POWER 98 in² dan SPIN 100 in², delapan ukuran grip pabrik L0–L7, kelas presisi untuk berat, keseimbangan, swingweight dan kekakuan, serta rekayasa khusus atas permintaan.",
  },
  common: {
    statuses: {
      current: "Saat ini",
      agreement: "Tersedia berdasarkan kesepakatan",
      development: "Dalam pengembangan",
      concept: "Konsep",
      target: "Target produksi",
      modelled: "Dihitung",
      confirmed: "Terkonfirmasi",
      requested: "Arsitektur yang diminta",
      notprovided: "Tidak dicantumkan",
    },
    brief: { who: "Untuk siapa", value: "Apa yang Anda peroleh", now: "Terkonfirmasi saat ini", next: "Langkah berikutnya" },
    labels: {
      next: "Lanjut",
      back: "Kembali",
      edit: "Ubah jawaban",
      review: "Periksa",
      start: "Mulai",
      restart: "Mulai ulang",
      copy: "Salin teks permintaan",
      copied: "Tersalin",
      openEmail: "Buka e-mail untuk mengirim permintaan ini",
      reference: "Referensi permintaan",
      weight: "Berat",
      balance: "Keseimbangan",
      swingweight: "Swingweight",
      stiffness: "Kekakuan",
      grip: "Ukuran grip",
      headSize: "Ukuran kepala",
      series: "Seri",
      precisionClass: "Kelas presisi",
      quantity: "Jumlah",
      notProvided: "Belum dipublikasikan",
      requestTarget: "Target yang diminta",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Baca selengkapnya",
      allSeries: "Semua seri",
      points: "berat terdaftar",
      optional: "opsional",
      required: "wajib",
      select: "Pilih",
      yes: "Ya",
      no: "Tidak",
      unknown: "Tidak yakin",
      custom: "Target khusus",
      listed: "Berat terdaftar",
      individual: "Raket tunggal",
      pair: "Pasangan serasi",
      triple: "Trio serasi",
      team: "Set tim",
      summaryTitle: "Ringkasan permintaan Anda",
      nextAction: "Tindakan berikutnya",
      status: "Status",
      learn: "Pelajari lebih lanjut",
      schematic: "Skema — bukan hasil pengukuran",
      photo: "Foto",
    },
    ecosystemStrip: "Ekosistem MAXIMUS",
    truth: {
      noPrices: "Harga, jumlah minimum, waktu tunggu, garansi dan komitmen pengiriman dikonfirmasi secara tertulis per pasar dan per program.",
      requestNotOrder: "Sebuah permintaan adalah permintaan untuk ditinjau. Itu bukan pesanan yang diterima, bukan komitmen produksi dan bukan jadwal pertemuan yang sudah dipastikan.",
      noGuarantee: "Tidak ada perlengkapan, metode atau program yang dijelaskan di sini yang menjamin hasil bagi pemain tertentu.",
      governing: "Halaman ini diterbitkan dalam beberapa bahasa. Versi bahasa Inggris adalah versi yang mengikat; terjemahan disediakan untuk kemudahan pembacaan.",
    },
  },
  nav: {
    language: "Bahasa",
    groups: { racquets: "Raket", training: "Latihan", ecosystem: "Ekosistem", partnerships: "Kemitraan" },
    familyPlan: "Rencana Keluarga",
    racquets: "Seri raket dan perbandingan",
    great: "GREAT — 97 in² · Kontrol",
    power: "POWER — 98 in² · Tenaga",
    spin: "SPIN — 100 in² · Putaran",
    precision: "Presisi dan kekakuan",
    grip: "Arsitektur grip pabrik L0–L7",
    custom: "Rekayasa khusus",
    training: "Sistem latihan",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologi",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Bantu saya memilih",
    ecosystem: "Peta ekosistem",
    engineering: "Rekayasa dan produksi",
    experience: "Uji coba dan fitting",
    brands: "Merek pribadi dan duta merek",
    families: "Keluarga dan orang tua",
    owners: "Pemilik dan arsip pemilik",
    network: "Sports Network",
    partnerships: "Semua jalur kemitraan",
    coaches: "Pelatih",
    clubs: "Klub dan akademi",
    distribution: "Distribusi dan pengembangan negara",
    strategic: "Strategis dan investasi",
    institutional: "Program institusional",
    contact: "Kontak",
    legal: "Identitas hukum",
    privacy: "Privasi",
    terms: "Ketentuan",
    menu: "Menu",
    close: "Tutup",
    home: "Beranda",
    skip: "Lewati ke konten",
  },
  footer: {
    line: "Raket MAXIMUS adalah kunci Anda menuju dunia MAXIMUS.",
    product: "Produk",
    ecosystem: "Ekosistem",
    company: "Organisasi",
    instagram: "Instagram",
    email: "Email",
    analytics: "Pengaturan analitik",
    subscribe: {
      title: "Tetap terhubung dengan MAXIMUS",
      line: "Seri baru, jadwal fitting, materi latihan dan program pemilik. Beberapa surat dalam setahun, tidak lebih.",
      label: "Alamat e-mail",
      placeholder: "your@email.com",
      button: "Berlangganan",
      sending: "Mengirim",
      done: "Anda sudah masuk daftar. Kami menulis hanya bila ada yang layak dibaca.",
      invalid: "Mohon periksa alamatnya.",
      failed: "Alamat belum tercatat. Silakan coba lagi dalam beberapa saat.",
      terms: "Dengan berlangganan, Anda setuju MAXIMUS mengirimkan pembaruan ini kepada Anda dan menyimpan alamat Anda untuk tujuan tersebut. Setiap surat memuat tautan untuk berhenti berlangganan.",
    },
    rights: "MAXIMUS® dan lambang singa adalah merek dari ekosistem MAXIMUS. MIPA: kendali internal atas kekayaan intelektual, asal-usul dan dokumen.",
    boundary:
      "Syarat komersial dan kontraktual disepakati secara terpisah dan tertulis. Pembelian sebuah raket tidak menciptakan keanggotaan institusional, hak investasi, kepemilikan atas kekayaan intelektual atau hak atas royalti.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Presisi dimulai pada titik kontak.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer dan metodologi MAXIMUS menghubungkan latihan yang terfokus dengan raket performa karbon penuh.",
    heroCta1: "Jelajahi sistem latihan",
    heroCta2: "Jelajahi GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrol",
    heroMeta: [
      ["Karbon penuh", "dari rangka hingga gagang"],
      ["4 parameter", "berat · keseimbangan · swingweight · kekakuan"],
      ["8 ukuran grip", "geometri pabrik L0–L7"],
      ["3 seri", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Rencana Keluarga · Berkontribusi bersama kami",
      title: "Anggaran keluarga Anda. Apa yang didapat. Apa yang dibangun.",
      p: "Tiga skenario berdampingan — sekarang, rencana, dan keinginan. Sesi, jam, dan kontak bola yang dapat dibiayai anggaran Anda, serta biaya satu sesi, satu jam, dan satu pukulan, dihitung dari angka Anda sendiri.",
      points: [
        ["Angka Anda sendiri", "Setiap jumlah berasal dari Anda. Tidak ada yang diasumsikan, tidak ada yang dikonversi."],
        ["Tiga skenario", "Bandingkan apa yang Anda lakukan sekarang dengan apa yang Anda rencanakan dan apa yang Anda inginkan."],
        ["Sepuluh tahun ke depan", "Rencana pengeluaran untuk satu hingga sepuluh tahun, dibatasi oleh usia yang Anda tetapkan."],
        ["Di luar lapangan", "Dukungan untuk masuk ke sekolah unggulan, serta aset digital yang tetap menjadi milik pemain."],
      ],
      cta: "Hitung rencana keluarga Anda",
    },
    paths: {
      eyebrow: "Mulai di sini",
      title: "Pilih jalur Anda",
      items: {
        player: { h: "Pemain", p: "Temukan raket berdasarkan level dan prioritas Anda, atau konfigurasikan langsung.", a: "Temukan raket Anda" },
        parent: { h: "Orang tua", p: "Jalur tertulis untuk sasaran pengembangan, keterlibatan pelatih dan perlengkapan yang sesuai.", a: "Jalur keluarga" },
        coach: { h: "Pelatih, klub atau akademi", p: "Sistem latihan, fitting, set tim dan personalisasi.", a: "Jalur pelatih dan klub" },
        partner: { h: "Distributor atau mitra", p: "Jalur distribusi, pengembangan negara, strategis dan institusional.", a: "Jalur kemitraan" },
      },
    },
    series: {
      eyebrow: "Seri performa",
      title: "Tiga arsitektur performa. Satu platform rekayasa.",
      lead: "Pilih seri berdasarkan arah permainan, lalu lengkapi konfigurasinya: kelas presisi, berat, grip, personalisasi.",
      cta: "Bandingkan seri",
      configure: "Konfigurasikan",
      open: "Buka seri",
      photoPending: "Foto belum dipublikasikan",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Sistem Presisi MAXIMUS",
      title: "Berat. Keseimbangan. Swingweight. Kekakuan.",
      sub: "Dikendalikan sebagai satu sistem rekayasa.",
      lead: "Tiga kelas presisi menentukan seberapa ketat setiap raket jadi dipertahankan pada spesifikasi yang dinyatakan. P0.5 adalah toleransi yang ketat menurut protokol pengukuran yang telah ditetapkan — bukan nol kesalahan.",
      cta: "Presisi dan kekakuan secara rinci",
    },
    stiffness: {
      eyebrow: "Kekakuan",
      title: "Respons rangka yang dapat diulang terhadap target yang dinyatakan.",
      p: "Kekakuan rangka membentuk respons, rasa dan konsistensi antar raket. MAXIMUS memperlakukannya sebagai parameter keempat yang dikendalikan: target, hasil pengukuran, toleransi yang diizinkan dan kapabilitas alat ukur disimpan sebagai catatan terpisah. Manfaatnya adalah keterulangan — bukan jaminan hasil bagi setiap pemain.",
      cols: [["Respons", "Bagaimana rangka mengembalikan energi pada saat kontak."], ["Rasa", "Apa yang dirasakan pemain pada saat kontak."], ["Konsistensi", "Raket yang dibuat dengan spesifikasi sama memberi respons serupa di dalam kelasnya."]],
      schematicCaption: "Skema: penyimpangan yang diizinkan di sekitar target kekakuan yang dinyatakan untuk setiap kelas. Bukan hasil pengukuran; tidak ada nilai RA yang tersirat.",
      bands: { p25: "toleransi target ±1 RA", p15: "toleransi target ±0.5 RA", p05: "sesuai dengan nilai RA target yang dinyatakan menurut protokol pengukuran pabrik yang berlaku — bukan nol kesalahan", target: "target yang dinyatakan (tanpa nilai tersirat)" },
    },
    carbon: {
      eyebrow: "Standar konstruksi",
      title: "Karbon penuh. Dari rangka hingga gagang.",
      p: "Seluruh raket MAXIMUS yang berlaku pada platform ini berstruktur karbon penuh, termasuk gagangnya. Gagang tidak dibentuk menggunakan foam.",
      gripTitle: "Delapan ukuran grip pabrik. L0–L7.",
      gripP: "Setiap ukuran adalah geometri gagang karbon dari pabrik — bukan penebalan dengan overgrip.",
      scaleCaption: "Skema: penandaan nominal grip L0–L7 (4″ hingga 4⅞″). Bukan dimensi gagang hasil pengukuran.",
      cta: "Arsitektur grip pabrik",
    },
    custom: {
      eyebrow: "Rekayasa khusus",
      title: "Direkayasa sesuai spesifikasi.",
      sub: "Rangkaian standar adalah titik awalnya.",
      p: "MAXIMUS menerima kebutuhan teknis di luar matriks yang dipublikasikan untuk dievaluasi, direkayasa, divalidasi dan diproduksi sesuai spesifikasi yang disepakati. Kelayakannya dikonfirmasi secara tertulis.",
      chain: ["Tetapkan", "Rekayasa", "Validasi", "Spesifikasi", "Produksi", "Ukur / catat"],
      cta: "Kirim ringkasan teknis",
      cta2: "Bahas rekayasa khusus",
    },
    training: {
      eyebrow: "Sistem latihan",
      title: "Sistem latihan yang dibangun di sekitar titik kontak.",
      p: "Sweet Spot Trainer, metodologi MAXIMUS dan Spot Trainer menghubungkan perlengkapan dengan latihan yang dipandu pelatih: kontak di titik tengah, kontrol, beban bertahap dan transisi kembali ke raket performa.",
      cta: "Sistem latihan",
      cta2: "Minta demonstrasi",
      photoPending: "Foto raket latihan belum dipublikasikan",
      sstP: "Kepala raket latihan 50 in² untuk melatih kontak di titik tengah, dengan empat konfigurasi berat untuk pembebanan yang dipilih pelatih.",
      sstCta: "Jelajahi Sweet Spot Trainer",
      sstCaption: "Konfigurasi 300 g, satu dari empat",
      methodP: "Tetapkan sasaran, pilih perlengkapan, berlatih dengan keterlibatan pelatih, catat pengamatan, nilai ulang, sesuaikan dan terapkan hasilnya pada permainan kompetitif.",
      methodCta: "Jelajahi metodologinya",
      spotP: "Target bundar kecil untuk melatih titik kontak yang presisi dan dapat diulang.",
      spotCta: "Jelajahi Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Produksi dan kendali mutu",
      title: "Dibuat sesuai spesifikasi. Diukur dan dicatat.",
      p: "Produksi mengikuti spesifikasi tertulis dari setiap pesanan. Catatan mengikuti kelas presisi: catatan produksi yang disimpan untuk P2.5, catatan per unit dan keterlacakan untuk P1.5, kendali dan dokumentasi per unit untuk P0.5 sejauh program untuk pesanan tersebut menerapkannya.",
      confirmedTitle: "Terkonfirmasi",
      confirmed: ["Konstruksi karbon penuh dari rangka hingga gagang.", "Kelas presisi P2.5, P1.5 dan P0.5 dengan empat parameter yang dikendalikan.", "Delapan ukuran grip pabrik L0–L7."],
      pendingTitle: "Belum dipublikasikan",
      pending: "Foto peralatan ukur, contoh catatan kendali mutu dan rekaman pabrik belum dipublikasikan. Tidak ada bagian dari halaman ini yang merupakan sertifikat hasil pengukuran.",
      captions: { lettering: "Tulisan MAXIMUS mengilap pada rangka hitam matte", buttcap: "Grip dan tutup gagang dengan lambang singa", handle: "Gravir personalisasi warna perak", finish: "Kepala raket dan bidang senar" },
      cta: "Rekayasa dan produksi",
    },
    world: {
      eyebrow: "Dunia MAXIMUS",
      title: "Satu kunci. Satu ekosistem. Peluang tanpa batas.",
      note: "“Peluang tanpa batas” adalah ungkapan merek, bukan janji atas kelayakan teknis, penghasilan atau akses yang tak terbatas. Pembelian tidak menciptakan royalti, imbal hasil investasi, sponsorship atau pembiayaan pengembangan seorang pemain.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — sekaligus navigasi Anda di dunia tenis: profil perlengkapan terpandu yang dijawab secara tertulis." },
        personal: { h: "Personalisasi", p: "Nama, inisial, nomor dan identifikasi tim dalam gravir warna perak yang telah disetujui." },
        development: { h: "Pengembangan", p: "Sistem latihan yang dipandu pelatih, catatan dan penilaian ulang." },
        ecosystem: { h: "Ekosistem yang lebih luas", p: "Merek pribadi, catatan pemilik, jaringan, lisensi dan program institusional — masing-masing ditampilkan dengan status sebenarnya." },
      },
      cta: "Jelajahi ekosistemnya",
    },
    partners: {
      eyebrow: "Jalur kemitraan",
      title: "Pelatih, klub, distributor dan mitra.",
      p: "Kualifikasi tertulis lebih dahulu. Hak atas negara, eksklusivitas dan syarat komersial dinegosiasikan secara tertulis — tidak pernah diberikan melalui formulir.",
      cta: "Semua jalur kemitraan",
      formTitle: "Pertanyaan singkat",
      formLead: "Pilih tujuannya dan tulis kepada MAXIMUS. Anda menerima ID permintaan di halaman ini.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "NAVIGASI ANDA DI DUNIA TENIS" } },
    personal: { eyebrow: "Personalisasi", title: "Nama Anda. Nomor Anda. MAXIMUS Anda." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tiga seri. Parameter yang nyata." },
    map: { cta: "Jelajahi ekosistemnya" },
  },
  racquets: {
    title: "Raket",
    lead: "Tiga seri performa dengan standar konstruksi yang sama, sistem presisi yang sama dan arsitektur grip pabrik yang sama. Setiap seri adalah arsitektur performa yang sudah mapan di dalam satu platform rekayasa yang lebih luas.",
    direction: { control: "Kontrol", power: "Tenaga", spin: "Putaran" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Arah permainan utama",
    compareTitle: "Perbandingan seri",
    compareLead: "Hanya data arsitektur yang terkonfirmasi. Pola senar, panjang, profil rangka, rentang tegangan senar serta nilai nominal swingweight dan kekakuan untuk seri ini tidak dipublikasikan; semuanya dicatat sebagai target yang diminta untuk ditinjau secara teknis.",
    columns: { series: "Seri", head: "Ukuran kepala", direction: "Arah", weights: "Berat terdaftar", range: "Rentang berat", balance: "Data keseimbangan" },
    balanceModelled: "Nilai hasil perhitungan",
    balanceNotProvided: "Belum dipublikasikan",
    construction: "Konstruksi: karbon penuh, rangka hingga gagang · Presisi: P2.5 / P1.5 / P0.5 · Grip: L0–L7",
    otherTitle: "Olahraga raket lainnya",
    otherLead: "Arah pengembangan yang disetujui. Belum ada produk yang dapat dijual dalam kategori ini dan tidak ada spesifikasi tenis yang dialihkan ke dalamnya.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Bulu tangkis", racquetball: "Racquetball", beachTennis: "Tenis pantai" },
    ctaConfigure: "Konfigurasikan permintaan",
    ctaSeries: "Buka seri",
  },
  seriesPage: {
    eyebrow: "Seri performa",
    intro: {
      great: "Arsitektur GREAT 97 in² dibangun di sekitar kontrol: kepala yang ringkas, kontak yang presisi dan keyakinan dalam mengarahkan bola.",
      power: "Arsitektur POWER 98 in² dibangun di sekitar transfer energi: kedalaman dan kecepatan bola dari rangka yang stabil.",
      spin: "Arsitektur SPIN 100 in² dibangun di sekitar perilaku bola: putaran, margin aman dan pembentukan lintasan.",
    },
    photoPending: "Foto seri belum dipublikasikan",
    detailPending: "Foto detail konstruksi dan gagang untuk seri ini belum dipublikasikan.",
    specsTitle: "Spesifikasi dan status",
    catalogue: {
      eyebrow: "Katalog seri {series}",
      title: "{n} varian berat",
      lead: "Setiap varian seri {series}, diurutkan menurut berat. Berat dalam gram, keseimbangan dalam milimeter dari ujung gagang. Setiap visualisasi ditampilkan utuh: tidak ada yang dipotong, ditutup atau diregangkan.",
      selectLabel: "Pilih varian berat",
      select: "Tampilkan varian ini",
      selected: "Ditampilkan di atas",
      balanceLabel: "Keseimbangan",
      headLabel: "Ukuran kepala",
      constructionLabel: "Konstruksi",
      gripsLabel: "Ukuran grip pabrik",
      precisionLabel: "Kelas presisi",
      balanceConfirmed: "Keseimbangan adalah nilai terkonfirmasi untuk berat ini dan sesuai dengan angka yang tercetak pada visualisasi.",
      balanceModelled: "Keseimbangan adalah nilai hasil perhitungan untuk berat terdaftar ini, bukan hasil pengukuran pabrik per unit; nilainya sesuai dengan angka yang tercetak pada visualisasi.",
      zoom: "Buka gambar",
      close: "Tutup",
      allTitle: "Semua {n} varian",
    },
    specs: { head: "Ukuran kepala", direction: "Arah utama", weights: "Berat terdaftar", range: "Rentang berat", balance: "Keseimbangan", construction: "Konstruksi", grips: "Grip pabrik", precision: "Kelas presisi" },
    construction: "Karbon penuh, rangka hingga gagang",
    statusTitle: "Status nilai-nilai tersebut",
    matrixTitle: "Matriks berat lengkap",
    matrixLead: "Berat terdaftar adalah pilihan standar. Berat lain dapat diajukan sebagai target khusus; nilai antara yang tidak ada tidak ditambahkan begitu saja.",
    balanceNote: {
      confirmed: "Nilai keseimbangan terkonfirmasi untuk setiap berat terdaftar (mm dari ujung gagang) dan sesuai dengan angka yang tercetak pada visualisasi berat tersebut. Nilainya tidak dihitung di sini dan tidak dihaluskan antar berat yang berdekatan; dasar pengukurannya dikonfirmasi dalam spesifikasi tertulis.",
      modelled: "Nilai keseimbangan dihitung untuk setiap berat terdaftar (mm dari ujung gagang). Nilainya bukan hasil pengukuran pabrik per unit; dasar pengukurannya dikonfirmasi dalam spesifikasi tertulis.",
      notprovided: "Nilai keseimbangan untuk seri ini tidak dicantumkan. Jangan menyimpulkannya dari seri lain.",
    },
    optionsTitle: "Presisi, grip dan berat",
    notPublished: "Tidak dipublikasikan untuk seri ini: pola senar, panjang, profil rangka, rentang tegangan senar, serta nilai swingweight dan kekakuan. Anda dapat menyampaikannya sebagai target yang diminta untuk ditinjau secara teknis.",
    offerTitle: "Apa yang terjadi setelah permintaan Anda",
    offerSteps: [
      ["Permintaan", "Kirim konfigurasi atau pertanyaan. ID permintaan langsung ditampilkan."],
      ["Peninjauan", "MAXIMUS meninjau seri, kelas, berat, grip dan setiap target yang diminta."],
      ["Jawaban tertulis", "Spesifikasi, ketersediaan dan syarat komersial dikonfirmasi secara tertulis."],
    ],
    faqTitle: "Pertanyaan",
    faq: [
      ["Apakah nilai keseimbangan diukur?", "Nilainya dihitung untuk berat terdaftar, bukan hasil pengukuran per unit. Dasar pengukurannya dikonfirmasi dalam spesifikasi tertulis."],
      ["Bisakah saya meminta berat yang tidak terdaftar?", "Bisa, sebagai target khusus dalam satuan gram bulat. Permintaan itu ditinjau secara teknis dan kelayakannya dikonfirmasi secara tertulis."],
      ["Apa yang diubah oleh kelas presisi?", "Seberapa ketat berat, keseimbangan, swingweight dan kekakuan dipertahankan pada spesifikasi yang dinyatakan, dan catatan apa saja yang disimpan."],
      ["Apakah grip ditebalkan dengan overgrip?", "Tidak. L0–L7 adalah geometri gagang karbon dari pabrik."],
      ["Di mana harga dan waktu pengiriman?", "Keduanya dikonfirmasi secara tertulis untuk setiap permintaan dan tidak dipublikasikan di sini."],
    ],
    faqSpinBalance: ["Dari mana nilai keseimbangan SPIN berasal?", "Dari tabel seri Spin yang terkonfirmasi: 33 varian berat dengan keseimbangan dalam milimeter dari ujung gagang. Setiap pasangan nilai sesuai dengan angka yang tercetak pada visualisasi berat tersebut yang telah disetujui. Nilainya tidak dihitung dan tidak dihaluskan antar berat yang berdekatan."],
    ctaBuild: "Konfigurasikan seri ini",
    ctaAsk: "Tanyakan tentang seri ini",
    ctaCompare: "Bandingkan semua seri",
    weightsLabel: "berat terdaftar",
    headLabel: "kepala",
  },
  precision: {
    title: "Presisi dan kekakuan",
    switch: { label: "Pilih kelas presisi", panelLabel: "Empat parameter yang dikendalikan —", qcLabel: "Arsitektur kendali mutu", protocolNote: "menurut protokol pengukuran kendali mutu pabrik yang ditetapkan", fullTable: "Tabel perbandingan lengkap" },
    lead: "Empat parameter yang dikendalikan sebagai satu sistem rekayasa. Setiap kelas menentukan seberapa ketat raket jadi dipertahankan pada spesifikasi yang dinyatakan dan catatan mutu apa saja yang dihasilkan.",
    statement: "Berat. Keseimbangan. Swingweight. Kekakuan. Dikendalikan sebagai satu sistem rekayasa.",
    classes: {
      "P2.5": { name: "Inti performa yang dapat diskalakan", qc: "Pengukuran per unit dan catatan produksi yang disimpan." },
      "P1.5": { name: "Presisi lanjutan", qc: "Pengukuran per unit, catatan per unit dan keterlacakan." },
      "P0.5": { name: "Profesional · dikendalikan per unit", qc: "Kendali per unit dengan nilai nominal dan nilai aktual serta catatan pengukuran per unit; identitas serial, keterlacakan batch, sertifikat presisi dan set serasi sejauh program untuk pesanan tersebut menerapkannya." },
    },
    columns: { cls: "Kelas", weight: "Berat", balance: "Keseimbangan", sw: "Swingweight", stiff: "Kekakuan", qc: "Arsitektur kendali mutu" },
    stiffTarget: "toleransi target",
    stiffExact: "sesuai dengan nilai RA target yang dinyatakan menurut protokol pengukuran pabrik yang berlaku",
    programmeNote: "Identitas serial, sertifikat dan dokumentasi set serasi hanya diterbitkan sejauh program untuk pesanan tertentu menerapkannya.",
    targetsNote: "Spesifikasi kekakuan merupakan target produksi sampai protokol yang relevan dan bukti produksi mendukung klaim yang lebih kuat. Proposisi arsitektur ini tidak menyiratkan bahwa setiap konfigurasi yang terdaftar telah melewati proses pelepasan empat parameter secara lengkap.",
    stiffnessTitle: "Mengapa kekakuan penting",
    stiffnessP1: "Kekakuan rangka memengaruhi cara rangka merespons pada saat kontak, bagaimana rasanya, dan seberapa konsisten dua raket satu terhadap yang lain. Manfaat utama dari mengendalikannya adalah respons yang dapat diulang terhadap spesifikasi yang dinyatakan.",
    stiffnessP2: "Sebelum kesesuaian yang terverifikasi dipublikasikan, catatan kendali mutu internal mengidentifikasi alat ukur, status kalibrasinya, metode, kondisi raket, resolusi, ketidakpastian pengukuran, pengukuran berulang, aturan pembulatan dan aturan penerimaan. Angka bulat yang tampil sama tidak membuktikan nol variasi fisik atau nol kesalahan pengukuran.",
    fields: ["Nilai target", "Hasil pengukuran", "Toleransi yang diizinkan", "Kapabilitas alat ukur"],
    fieldsNote: "Disimpan sebagai kolom terpisah dalam setiap catatan.",
    matchedTitle: "Set serasi",
    matchedP: "Kriteria set serasi ditetapkan terpisah dari toleransi per unit. Kesesuaian setiap raket terhadap toleransi nominalnya tidak dengan sendirinya membuktikan selisih maksimum tertentu antara dua raket. Pasangan serasi, trio serasi dan set tim diajukan melalui konfigurator dan dikonfirmasi secara tertulis.",
    extendedTitle: "Model teknis yang diperluas",
    extendedP: "Model data ini mendukung parameter tambahan. Belum ada nilai atau kelas toleransi untuknya; parameter tersebut dapat disampaikan sebagai target yang diminta di dalam ringkasan teknis.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Perilaku torsional", length: "Panjang", beamProfile: "Profil rangka", headGeometry: "Geometri kepala", stringPattern: "Pola senar", durability: "Daya tahan", vibration: "Karakteristik getaran" },
    noZero: "MAXIMUS tidak menggambarkan rangkaian produknya yang terdaftar sebagai nol toleransi. Presisi di dalam rangkaian ini dinyatakan sebagai kelas dengan toleransi yang dideklarasikan dan arsitektur kendali mutu yang ditetapkan. ZERO bukan bagian dari rangkaian ini.",
    zero: {
      eyebrow: "Opsi eksklusif",
      title: "ZERO",
      sub: "Toleransi nol gram.",
      p: "Ketiga kelas mempertahankan raket jadi di dalam rentang toleransi yang dinyatakan. ZERO menghapus rentang tersebut. Raket dibuat dan diukur sampai hasil pengukuran sama dengan nilai yang dinyatakan pada resolusi alat ukur pabrik, dan hasil pengukuran itu diserahkan bersama raket tersebut. Ini bukan bagian dari rangkaian yang terdaftar dan bukan kelas keempat: hal ini disepakati secara individual, untuk satu raket atau satu set serasi, sebagai produk eksklusif yang dibuat khusus. Atas kesepakatan, pendekatan yang sama diterapkan pada keseimbangan dan Swingweight.",
      points: [
        ["Tanpa rentang toleransi", "Nilai yang dinyatakan adalah hasilnya, bukan titik tengah sebuah toleransi."],
        ["Satu per satu", "Dibuat, diukur dan dicatat sebagai satu unit tunggal."],
        ["Diserahkan bersama raket", "Hasil pengukuran diserahkan dan disimpan di dalam catatan produksi."],
        ["Dikonfirmasi secara tertulis", "Parameter, lingkup dan waktu tunggu disepakati sebelum produksi."],
      ],
      note: "Pencocokan dilakukan pada resolusi alat ukur pabrik. Angka yang tampil sama bukan merupakan klaim nol variasi fisik. Ketersediaan dan syaratnya disepakati secara individual untuk setiap pesanan.",
      cta: "Ajukan permintaan ZERO",
    },
    cta: "Konfigurasikan dengan kelas presisi",
  },
  grip: {
    title: "Arsitektur grip pabrik",
    statement: "Delapan ukuran grip pabrik. L0–L7.",
    lead: "Geometri grip adalah bagian dari arsitektur gagang karbon. Setiap ukuran diproduksi sebagai geometri gagang, bukan ditebalkan dengan overgrip.",
    emph: "Ukuran yang diperluas",
    p1: "Rangkaian pabrik dengan delapan ukuran memberi pelatih dan pemain rentang konfigurasi yang lebih luas sehingga perlengkapan dapat dispesifikasikan di sekitar pemain, termasuk geometri L6 dan L7 yang lebih besar.",
    p2: "Penandaan nominal grip berbeda dari dimensi mentah gagang struktural dan dari protokol pengukuran akhir. Ukuran-ukuran ini berlaku untuk seri performa dan untuk rumpun produk latihan pada platform ini.",
    p3: "Tidak ada klaim eksklusivitas global yang dibuat untuk rangkaian ini.",
    columns: { size: "Ukuran", nominal: "Penandaan nominal", family: "Berlaku untuk" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurasikan dengan ukuran grip Anda",
  },
  custom: {
    title: "Rekayasa khusus",
    statement: "Direkayasa sesuai spesifikasi.",
    sub: "Rangkaian standar adalah titik awalnya.",
    lead: "MAXIMUS menerima kebutuhan teknis di luar matriks konfigurasi yang dipublikasikan untuk dievaluasi, direkayasa, divalidasi dan diproduksi sesuai spesifikasi yang disepakati. Kelayakan dikonfirmasi melalui peninjauan — tidak setiap permintaan yang terpikirkan layak secara fisik maupun komersial.",
    scopeTitle: "Apa yang dapat dibahas dalam ringkasan teknis",
    scope: ["Geometri kepala dan rangka", "Panjang", "Berat", "Keseimbangan", "Swingweight", "Kekakuan", "Twistweight", "Geometri grip", "Konstruksi", "Set serasi", "Rangka latihan", "Tampilan dan gravir", "Program identitas dan tim", "Pengembangan yang bergantung pada perkakas"],
    processTitle: "Proses",
    process: [
      ["Tetapkan", "Target yang diinginkan, batas yang wajib, tujuan penggunaan dan kompromi yang dapat diterima."],
      ["Rekayasa", "Penilaian rekayasa terhadap platform dan perkakas."],
      ["Validasi", "Validasi terhadap spesifikasi yang disepakati."],
      ["Spesifikasi", "Spesifikasi tertulis dengan dasar pengukuran dan toleransinya."],
      ["Produksi", "Produksi sesuai spesifikasi."],
      ["Ukur / catat", "Pengukuran dan catatan yang disimpan menurut kelas presisi yang berlaku."],
    ],
    formTitle: "Kirim ringkasan teknis",
    formLead: "Bedakan target yang diinginkan dari batas yang wajib. Hasilnya adalah permintaan peninjauan teknis, bukan pesanan produksi yang otomatis diterima.",
    protected: "Resep susunan lapisan karbon, perkakas, identitas pemasok, perhitungan biaya internal dan pengetahuan teknis yang dilindungi tidak diungkapkan melalui jalur ini.",
    cta: "Kirim ringkasan teknis",
  },
  training: {
    title: "Sistem latihan",
    lead: "Dua rumpun produk latihan dengan standar produksinya masing-masing, dihubungkan oleh satu metodologi: latihan yang dipandu pelatih, catatan, penilaian ulang dan penerapan kembali pada permainan kompetitif.",
    sst: { h: "Sweet Spot Trainer", p: "Raket latihan berkepala kecil 50 in² dalam sistem empat berat untuk melatih kontak di titik tengah, kesadaran akan sweet spot, kontrol raket dan pembebanan bertahap." },
    spot: { h: "Spot Trainer", p: "Latihan titik kontak menggunakan target kontak bundar kecil, di atas fondasi empat berat yang telah disetujui." },
    method: { h: "Metodologi", p: "Tetapkan sasaran, pilih perlengkapan dengan keterlibatan pelatih, gunakan sistem yang relevan, catat, nilai ulang, sesuaikan dan terapkan." },
    experience: "Pegang. Ayunkan. Rasakan.",
    experienceP: "Ajukan uji coba, fitting atau demonstrasi dengan pendampingan pelatih. Permintaan yang dikirim bukan jadwal pertemuan yang sudah dipastikan.",
    cta: "Ajukan sesi fitting atau demonstrasi",
    distinct: "Sweet Spot Trainer, Spot Trainer dan setiap alat demonstrasi terpisah adalah produk yang berbeda dan tidak pernah digabungkan.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Kategori latihan tersendiri dengan standar produksinya sendiri. Kepala 50 in² memusatkan perhatian pada lokasi kontak; empat berat menyediakan tahapan pembebanan.",
    baseline: "Dasar yang terkonfirmasi",
    columns: { head: "Kepala", length: "Panjang", pattern: "Pola senar", grips: "Grip pabrik" },
    systemTitle: "Sistem empat raket",
    detailsTitle: "Detail konstruksi",
    systemLead: "Berat dan keseimbangan sebagaimana dikirimkan. Dasar pengukurannya dicatat terpisah dan belum dipublikasikan.",
    purposeTitle: "Tujuan",
    purpose: ["Latihan kontak di titik tengah", "Kesadaran akan sweet spot", "Kontrol raket", "Pembebanan bertahap", "Pengembangan yang dipandu pelatih", "Transisi kembali ke raket performa pemain"],
    heavy: "Model 400 g adalah konfigurasi latihan yang terkendali. Model ini tidak otomatis disarankan untuk anak-anak, pemula atau setiap pemain; pelatih yang menentukan beban, durasi dan tahapannya.",
    precisionNote: "Kelas presisi performa P2.5, P1.5 dan P0.5 tidak otomatis diterapkan pada rumpun produk latihan ini. Toleransi produksi latihan mengikuti spesifikasi rumpun produk itu sendiri yang telah disetujui.",
    health: "Tidak ada janji pencegahan atau penyembuhan tennis elbow, penghapusan risiko cedera maupun jaminan peningkatan kemampuan.",
    cta: "Ajukan demonstrasi Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Latihan titik kontak menggunakan target kontak bundar kecil. Produk tersendiri dengan identitas visualnya sendiri, dibangun di atas fondasi empat berat yang telah disetujui.",
    purposeTitle: "Tujuan yang terkonfirmasi",
    purposeP: "Melatih pemain menemukan dan mengulang titik kontak yang presisi.",
    weightsTitle: "Tahapan berat",
    weightsP: "Tahapan berat mengikuti fondasi berat Sweet Spot Trainer yang telah disetujui. Nilai keseimbangan dan spesifikasi Sweet Spot Trainer lainnya tidak disalin ke Spot Trainer.",
    dims: "Dimensi target yang tepat belum dipublikasikan.",
    grips: "Arsitektur grip pabrik L0–L7.",
    notes: ["Kelas presisi performa tidak diterapkan secara otomatis.", "Produk ini bukan raket konvensional versi mini dan tidak ada pola senar yang dipublikasikan.", "Spot Trainer, Sweet Spot Trainer dan setiap alat demonstrasi terpisah tetap dapat dibedakan."],
    cta: "Tanyakan tentang Spot Trainer",
  },
  methodology: {
    title: "Metodologi dan pengalaman produk",
    lead: "Perlengkapan hanyalah satu bagian dari perjalanan pengembangan yang terstruktur. Metode ini dimulai dari sasaran pemain, bukan dari label produk.",
    stepsTitle: "Perjalanan pengembangan",
    steps: [
      ["Tetapkan sasaran", "Sasaran pemain dan titik awalnya."],
      ["Pilih perlengkapan", "Perlengkapan yang sesuai dipilih dengan keterlibatan pelatih."],
      ["Gunakan sistemnya", "Sistem latihan yang relevan, dipandu pelatih."],
      ["Catat", "Pengamatan atas partisipasi yang sebenarnya, tanpa nilai yang direka."],
      ["Nilai ulang", "Titik evaluasi yang sebanding."],
      ["Sesuaikan", "Penyesuaian konfigurasi atau program."],
      ["Terapkan", "Hasil belajar diterapkan kembali pada permainan kompetitif."],
    ],
    educationTitle: "Jalur edukasi",
    education: { player: "Pemain — memahami konfigurasi, pembebanan dan tahapan.", parent: "Orang tua — kesinambungan pengembangan, perlengkapan yang sesuai, catatan dan hak.", coach: "Pelatih — sistem latihan, fitting, penilaian dan penggunaan program yang diizinkan." },
    evidenceTitle: "Disiplin pembuktian",
    evidenceP: "Catatan partisipasi yang sebenarnya dan hasil pengamatan disimpan beserta klasifikasinya — dinyatakan peserta, dikonfirmasi wali, divalidasi pelatih atau diukur sistem. Kemajuan, nilai dan validasi tidak pernah direka.",
    experienceTitle: "Pegang. Ayunkan. Rasakan.",
    experienceP: "Uji coba, fitting atau demonstrasi dengan pendampingan pelatih dapat diajukan. Permintaan yang dikirim bukan jadwal pertemuan yang sudah dipastikan.",
    cta: "Ajukan fitting atau demonstrasi",
    cta2: "Pengajuan kemitraan pelatih",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — profil perlengkapan terpandu",
    title: "MAXIMUS GPS",
    lead: "Profil perlengkapan terpandu. Jawab hanya yang relevan; periksa dan perbaiki jawaban Anda; terima ringkasan, arah konfigurasi yang berlaku dan satu langkah lanjutan yang nyata.",
    honesty: "Pada rilis ini belum ada aturan fitting otomatis yang disetujui. Karena itu GPS menghasilkan ringkasan kebutuhan yang jelas dan menunjukkan arah konfigurasi; rincian perlengkapan diteruskan untuk ditinjau oleh ahli.",
    rulesVersion: "Versi aturan",
    dataVersion: "Versi data produk",
    steps: { role: "Peran", sport: "Olahraga", experience: "Pengalaman", objectives: "Sasaran", style: "Gaya bermain", equipment: "Perlengkapan saat ini", preference: "Preferensi", coach: "Keterlibatan pelatih", ageBand: "Kelompok usia", review: "Periksa" },
    notStored: "Tidak disimpan di peramban ini.",
    ageNote: "Hanya digunakan untuk mengarahkan permintaan. Nama, tanggal lahir atau informasi medis tidak diminta.",
    q: {
      role: "Mana yang menggambarkan Anda?",
      sport: "Olahraga apa?",
      experience: "Tingkat pengalaman",
      objectives: "Apa yang paling penting? (pilih maksimal tiga)",
      style: "Gaya bermain, jika diketahui",
      equipment: "Perlengkapan saat ini, jika ada",
      equipmentHint: "Merek dan model, berat atau grip jika Anda mengetahuinya. Opsional.",
      preference: "Konfigurasi yang diinginkan atau ukuran grip yang diketahui",
      grip: "Ukuran grip yang diketahui",
      coach: "Apakah pelatih terlibat dalam keputusan perlengkapan Anda?",
      ageBand: "Kelompok usia pemain (hanya digunakan untuk mengarahkan permintaan secara tepat)",
    },
    roles: { player: "Pemain", parent: "Orang tua atau wali", coach: "Pelatih", club: "Klub atau akademi", other: "Lainnya" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Bulu tangkis", other: "Olahraga raket lainnya" },
    sportNote: "Produk tersedia untuk tenis. Olahraga lain merupakan arah pengembangan; minat Anda dicatat untuk program yang relevan.",
    experience: { beginner: "Pemula", developing: "Sedang berkembang", intermediate: "Menengah", advanced: "Lanjutan", competitive: "Kompetitif", professional: "Profesional" },
    objectives: { control: "Kontrol", power: "Tenaga", spin: "Putaran", comfort: "Kenyamanan", manoeuvrability: "Kelincahan", development: "Pengembangan jangka panjang", competition: "Kompetisi", training: "Sistem latihan", team: "Tim atau set serasi", personal: "Personalisasi" },
    styles: { baseline: "Bermain di garis belakang", allcourt: "Bermain di seluruh area lapangan", attacking: "Menyerang", defensive: "Bertahan", coach: "Ditentukan pelatih", unknown: "Tidak yakin" },
    ageBands: { u10: "Di bawah 10", u14: "10–13", u18: "14–17", adult: "18 tahun ke atas" },
    output: {
      title: "Profil perlengkapan Anda",
      status: "Perlu ditinjau ahli",
      statusP: "Tidak ada pencocokan otomatis pada rilis ini. Profil Anda telah diringkas untuk ditinjau oleh ahli.",
      directionsTitle: "Arah konfigurasi yang berlaku",
      directionsP: "Berdasarkan sasaran yang Anda sampaikan dan arah permainan yang dinyatakan untuk setiap seri. Ini adalah sebuah arah, bukan rekomendasi fitting.",
      trainingHint: "Sasaran Anda mencakup sistem latihan: lihat Sweet Spot Trainer dan Spot Trainer.",
      teamHint: "Set serasi diajukan melalui konfigurator dan dikonfirmasi secara tertulis.",
      next1: "Kirim profil untuk ditinjau ahli",
      show: "Tampilkan profil saya",
      configure: "Konfigurasikan",
      sendP: "Kirim profil Anda ke MAXIMUS untuk ditinjau ahli. ID permintaan langsung ditampilkan; jawabannya diberikan secara tertulis.",
      otherSport: "Raket MAXIMUS tersedia untuk tenis. Untuk olahraga raket lain tidak ada seri tenis yang disarankan; minat Anda dicatat sebagai arah pengembangan.",
      noDirection: "Sasaran Anda tidak mengarah pada satu arah permainan. Peninjauan oleh ahli akan mengusulkan konfigurasinya.",
      incomplete: "Beberapa jawaban yang wajib masih kosong — gunakan “Ubah jawaban” untuk melengkapinya.",
    },
    privacy: "GPS tidak meminta informasi kesehatan maupun identitas anak. Hanya jawaban pilihan ganda yang disimpan dalam sesi peramban ini; teks bebas tidak disimpan.",
  },
  build: {
    title: "Rancang milik Anda",
    lead: "Konfigurasikan sebuah permintaan: seri, kelas presisi, berat terdaftar atau target khusus, ukuran grip, target yang diminta, personalisasi, set serasi dan jumlah. Hasilnya adalah permintaan konfigurasi dengan ID permintaan — bukan SKU, harga, tanggal pengiriman atau sertifikat.",
    steps: { series: "Seri", cls: "Kelas presisi", weight: "Berat", grip: "Ukuran grip", targets: "Target", personal: "Personalisasi", set: "Set dan jumlah", use: "Penggunaan", review: "Periksa" },
    q: {
      series: "Pilih seri",
      cls: "Pilih kelas presisi",
      weightMode: "Berat",
      listed: "Berat terdaftar",
      customWeight: "Berat yang diminta (g)",
      balanceShown: "Keseimbangan hasil perhitungan untuk berat ini",
      balanceRequest: "Keseimbangan yang diminta (mm)",
      grip: "Ukuran grip pabrik",
      targetsTitle: "Target yang diminta",
      swingweight: "Swingweight yang diminta (kg·cm²)",
      stiffness: "Kekakuan yang diminta (RA)",
      basis: "Dasar pengukuran untuk nilai yang diminta",
      engraving: "Teks gravir",
      engravingHint: "Nama, inisial atau nomor. Huruf Latin, angka, spasi, tanda hubung, apostrof dan titik; maksimal 24 karakter. Aksara lain diterima untuk konfirmasi desain.",
      engravingType: "Personalisasi",
      types: { none: "Tidak ada", name: "Nama pemain", initials: "Inisial", number: "Nomor set", academy: "Identifikasi pelatih atau akademi", team: "Program tim" },
      set: "Raket tunggal atau set serasi",
      use: "Tujuan penggunaan",
      uses: { play: "Permainan pribadi", competition: "Kompetisi", coaching: "Kepelatihan", team: "Tim atau akademi", retail: "Evaluasi ritel atau distribusi", other: "Lainnya" },
      notes: "Kebutuhan teknis tambahan",
    },
    classes: { "P2.5": "P2.5 — inti performa yang dapat diskalakan", "P1.5": "P1.5 — presisi lanjutan", "P0.5": "P0.5 — profesional, dikendalikan per unit" },
    stiffExactShort: "kekakuan sesuai dengan nilai RA target yang dinyatakan menurut protokol pabrik yang berlaku",
    clsNote: "Setiap kelas mengendalikan empat parameter. P0.5 adalah toleransi yang ketat menurut protokol pengukuran yang ditetapkan — bukan nol kesalahan. Identitas serial, sertifikat dan dokumentasi set serasi hanya berlaku sejauh program untuk pesanan Anda menerapkannya.",
    listedNote: "Dari matriks seri yang terkonfirmasi.",
    customNote: "Berat di luar matriks, ditinjau secara teknis.",
    balanceCaption: "Setiap berat terdaftar menampilkan keseimbangan hasil perhitungannya dalam mm dari ujung gagang. Nilai hasil perhitungan bukan hasil pengukuran per unit.",
    spinNote: "Berat SPIN membentuk arsitektur berat yang diminta. Keseimbangan, swingweight dan kekakuan untuk SPIN tidak dicantumkan; semuanya ditetapkan dalam peninjauan teknis.",
    customHint: "Gram bulat, hanya angka. Berat khusus adalah permintaan untuk ditinjau secara teknis; kelayakannya dikonfirmasi secara tertulis dan tidak ada nilai yang dibulatkan.",
    gripNote: "geometri gagang karbon dari pabrik, bukan penebalan dengan overgrip",
    targetsLead: "Opsional. Masukkan hanya nilai yang Anda perlukan. Masing-masing dicatat sebagai target yang diminta untuk ditinjau secara teknis, bukan sebagai spesifikasi yang dipublikasikan.",
    basisHint: "Wajib bila Anda meminta berat khusus atau target apa pun: apakah nilai tersebut mengacu pada raket tanpa senar atau dengan senar?",
    inputRange: "Masukan yang diterima: {min}–{max}.",
    inputRangeNote: "Rentang masukan hanya menyaring entri yang tidak mungkin. Rentang itu tidak menggambarkan kemampuan produksi.",
    listedBasis: "nilai terdaftar — dasar pengukuran dikonfirmasi dalam spesifikasi tertulis",
    notStored: "Tidak disimpan di peramban ini; masukkan kembali bila Anda memuat ulang halaman.",
    artworkReview: "perlu konfirmasi desain",
    previewNote: "Tidak ada pratinjau visual yang ditampilkan: templat gravir yang disetujui untuk model ini belum dipublikasikan. Teks Anda dikumpulkan untuk konfirmasi desain.",
    teamSub: "4–99 raket per set",
    setsLabel: { individual: "Jumlah raket", pair: "Jumlah pasangan serasi", triple: "Jumlah trio serasi", team: "Jumlah set tim" },
    teamSizeLabel: "Raket per set tim",
    totalLabel: "Total raket",
    racquetsUnit: "raket",
    setRule: "Jumlah dihitung per set: satu pasangan serasi berisi 2 raket per set, satu trio serasi berisi 3.",
    restart: "Mulai konfigurasi baru",
    notices: { weightCleared: "{w} g tidak ada di dalam matriks {series}, sehingga pilihan beratnya dikosongkan. Pilih berat terdaftar atau ajukan target khusus." },
    reviewTitle: "Permintaan konfigurasi",
    reviewP: "Periksa konfigurasinya, lalu tambahkan data kontak Anda. Permintaan disimpan dengan ID permintaan dan dijawab secara tertulis; ketersediaan dan syarat komersial dikonfirmasi secara tertulis.",
    reviewErrors: "Beberapa jawaban konfigurasi perlu diperhatikan:",
    edit: "Ubah",
    fieldNames: { series: "Seri", cls: "Kelas presisi", mode: "Pemilihan berat", weight: "Berat terdaftar", customWeight: "Berat yang diminta", basis: "Dasar pengukuran", balanceReq: "Keseimbangan yang diminta", sw: "Swingweight yang diminta", ra: "Kekakuan yang diminta", grip: "Ukuran grip", ptype: "Personalisasi", engraving: "Teks gravir", setType: "Jenis set", sets: "Jumlah", teamSize: "Raket per set tim", use: "Tujuan penggunaan", notes: "Kebutuhan tambahan" },
    status: { listed: "berat terdaftar", requestedArchitecture: "arsitektur berat yang diminta", technicalReview: "permintaan untuk peninjauan teknis", notPublished: "tidak dicantumkan", requestedCondition: "kondisi yang diminta" },
    chooseLink: "Belum yakin seri mana yang cocok? Dapatkan bantuan memilih",
    cta: "Kirim permintaan konfigurasi",
  },
  experience: {
    title: "Uji coba dan fitting",
    statement: "Pegang. Ayunkan. Rasakan.",
    lead: "Ajukan uji coba, fitting atau demonstrasi dengan pendampingan pelatih. Permintaan ditinjau dan dijawab secara tertulis; permintaan yang dikirim bukan jadwal pertemuan yang sudah dipastikan.",
    optionsTitle: "Apa yang dapat diajukan",
    options: ["Uji coba raket", "Sesi fitting", "Demonstrasi dengan pendampingan pelatih", "Demonstrasi Sweet Spot Trainer atau Spot Trainer", "Hari demo untuk tim atau akademi"],
    formTitle: "Permintaan fitting atau demonstrasi",
  },
  engineering: {
    title: "Rekayasa dan produksi",
    statement: "Pesawat terbang. Kapal pesiar. Raket.",
    lead: "Satu filosofi rekayasa di tiga lingkungan: prinsip yang membentuk sebuah pesawat terbang, presisi yang memandu kapal pesiar melintasi laut lepas, performa yang menentukan setiap raket MAXIMUS. Sebuah narasi rekayasa — bukan klaim atas sertifikasi penerbangan, kepemilikan kapal pesiar, kepemilikan pabrik atau pengalihan material secara langsung.",
    manifesto: ["Kami percaya bahwa rekayasa yang unggul tidak mengenal batas.", "Satu filosofi. Direkayasa tanpa kompromi."],
    capabilityTitle: "Kemampuan produksi",
    capabilityLead: "Kemampuan ditunjukkan sebagai sebuah urutan kerja, bukan slogan.",
    sequence: [
      ["Spesifikasi", "Seri, kelas presisi, berat, keseimbangan, swingweight, target kekakuan, geometri grip, personalisasi."],
      ["Produksi", "Konstruksi karbon penuh dari rangka hingga gagang, diproduksi sesuai spesifikasi."],
      ["Kendali mutu", "Pengukuran dan catatan menurut kelas presisi: catatan produksi, catatan per unit dan keterlacakan, sertifikasi per unit."],
      ["Produksi ulang", "Respons yang dapat diulang terhadap spesifikasi yang dinyatakan di seluruh batch."],
      ["Keterlacakan", "Identitas serial, keterlacakan batch dan Sertifikat Presisi sejauh kelasnya menyediakannya."],
    ],
    capacityNote: "Kapasitas produksi, waktu tunggu, jumlah minimum dan jadwal pengiriman dikonfirmasi per program secara tertulis berdasarkan pesanan yang terkonfirmasi dan jadwal pelepasan yang disepakati.",
    truth: "Kapasitas bukan hasil produksi, bukan stok, bukan jaminan tanggal pengiriman dan bukan kepemilikan atas fasilitas produksi.",
    cta: "Distribusi dan pengembangan negara",
    cta2: "Kirim ringkasan teknis",
  },
  ecosystem: {
    title: "Ekosistem MAXIMUS",
    lead: "Satu kunci. Inilah yang dibukanya. Setiap simpul memiliki penjelasan, status yang akurat dan langkah lanjutan yang relevan.",
    words: ["Rekayasa", "Performa", "Inovasi", "Komunitas", "Peluang", "Tujuan"],
    nodes: {
      engineering: { h: "Rekayasa dan produksi raket", p: "Raket karbon penuh yang direkayasa sesuai spesifikasi, diproduksi dengan catatan mutu dan keterlacakan.", a: "Rekayasa dan produksi" },
      precision: { h: "Presisi dan konfigurasi per individu", p: "Empat parameter, tiga kelas presisi, delapan ukuran grip dan rekayasa khusus.", a: "Presisi dan kekakuan" },
      training: { h: "Latihan dan metodologi", p: "Sweet Spot Trainer, Spot Trainer dan perjalanan pengembangan yang terstruktur.", a: "Sistem latihan" },
      development: { h: "Pengembangan pemain dan pelatih", p: "Pemilihan yang dipandu pelatih, catatan, penilaian ulang dan jalur edukasi.", a: "Metodologi" },
      identity: { h: "Identitas pribadi dan merek pribadi", p: "Dari gravir hingga merek pribadi atau profesional yang diatur oleh hak.", a: "Merek pribadi" },
      owners: { h: "Catatan pemilik, pengetahuan dan hak", p: "Usulan arsip pemilik berizin untuk catatan perlengkapan, pengembangan dan hak.", a: "Pemilik dan arsipnya" },
      mipa: { h: "Asal-usul dan kendali internal MIPA", p: "Lapisan internal untuk kekayaan intelektual, asal-usul dan kendali dokumen.", a: "Identitas hukum dan kendali" },
      digital: { h: "Infrastruktur digital dan arah Blockchain 5.0", p: "Asal-usul, catatan yang dapat dilacak, bukti berizin dan identitas produk sebagai arah teknologi yang dinyatakan.", a: "Arah teknologi" },
      licensing: { h: "Lisensi kontraktual dan program royalti", p: "Merek, produk dan paket hak berlisensi dengan syarat yang ditetapkan per perjanjian.", a: "Jalur lisensi" },
      families: { h: "Partisipasi keluarga dan manfaat program", p: "Keputusan yang terinformasi, kesinambungan, catatan yang terjaga dan manfaat yang ditetapkan program.", a: "Keluarga dan orang tua" },
      network: { h: "MAXIMUS Sports Network", p: "Pemain, pelatih, klub, akademi, penyedia layanan, operator dan mitra regional.", a: "Sports Network" },
      market: { h: "Klub, akademi, distribusi dan pengembangan negara", p: "Program tim, ritel, distribusi dan pengembangan wilayah melalui kualifikasi tertulis.", a: "Jalur kemitraan" },
      institutional: { h: "Program institusional, edukasi, inovasi dan dampak sosial", p: "Lapisan institusional yang disediakan oleh MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) sejauh sebuah program menetapkan peran tersebut.", a: "Program institusional" },
      extensions: { h: "Perluasan ke olahraga raket lain dan apparel MAXIMUS", p: "Padel, pickleball, squash, bulu tangkis, racquetball, tenis pantai dan apparel sebagai arah pengembangan.", a: "Olahraga raket" },
    },
    boundaryTitle: "Batasan",
    boundary: [
      "Pembelian sebuah raket tidak menciptakan keanggotaan institusional, hak tata kelola, royalti atau hak investasi.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) adalah operator institusional hanya sejauh sebuah program menetapkan peran tersebut; penjualan perlengkapan menyebutkan badan hukum yang sesungguhnya menjadi pihak kontrak.",
      "Hibah, status nirlaba, perlakuan pajak dan izin regulator tidak berlaku secara otomatis di semua negara.",
    ],
    techTitle: "Arah teknologi",
    techP: "Blockchain 5.0 adalah arah teknologi MAXIMUS yang dinyatakan. Tujuan fungsionalnya adalah asal-usul, catatan yang dapat dilacak, bukti berizin, identitas produk dan rekonsiliasi peristiwa komersial yang memenuhi syarat. Tidak ada mekanisme konsensus, kapasitas transaksi, jaringan node, alamat kontrak pintar, token atau sertifikasi independen yang direpresentasikan, dan tidak ada implementasi terpasang yang diklaim. Informasi pribadi, catatan anak dan perjanjian rahasia tidak pernah dimasukkan ke dalam sistem publik yang tidak dapat diubah secara default.",
  },
  brands: {
    title: "Merek pribadi dan duta merek",
    statement: "Dari pemain menjadi merek. Dari pelatih menjadi merek.",
    lead: "Jalur khusus untuk merek pribadi. Keterlibatan MAXIMUS mencakup pengembangan merek dan promosi yang disepakati — bukan sekadar nama di atas sebuah raket.",
    progressionTitle: "Tahapan yang dimaksudkan",
    progression: [
      ["Identitas terverifikasi", "Identitas dan riwayat pengembangan yang terverifikasi."],
      ["Merek yang khas", "Merek pribadi atau profesional yang khas."],
      ["Konten dengan hak bersih", "Konten dengan hak yang bersih dan identitas produk yang disetujui."],
      ["Rekayasa dan koleksi", "Rekayasa dan pengembangan koleksi sejauh disepakati."],
      ["Promosi", "Promosi melalui kanal dan kemitraan MAXIMUS yang disepakati."],
      ["Partisipasi", "Partisipasi kontraktual dalam penjualan atau lisensi yang memenuhi syarat."],
      ["Pelaporan", "Pelaporan yang transparan berdasarkan perjanjian."],
    ],
    royaltiesTitle: "Royalti dan lisensi",
    royalties: [
      "Royalti melekat pada merek, produk, transaksi atau paket hak berlisensi yang ditetapkan.",
      "“Penjualan global” berarti penjualan yang memenuhi syarat di dalam cakupan kontrak — tidak pernah berarti setiap raket MAXIMUS yang tidak terkait.",
      "Tarif, dasar perhitungan, wilayah, jangka waktu, pengembalian dana, pengurangan, pelaporan, penyelesaian dan verifikasi ditetapkan melalui perjanjian yang relevan. Tidak ada persentase royalti baku yang dipublikasikan.",
      "Tidak ada kampanye global, anggaran media, hasil sponsorship atau keberhasilan komersial yang dijanjikan tanpa cakupan yang disepakati.",
    ],
    cta: "Kirim pengajuan kolaborasi merek",
    cta2: "Pengajuan kemitraan pelatih",
  },
  families: {
    title: "Keluarga dan orang tua",
    lead: "Keputusan perlengkapan yang terinformasi, kesinambungan pengembangan, pengetahuan dan hak yang terjaga, keterlihatan partisipasi, serta manfaat yang ditetapkan program yang dapat mendukung kegiatan di masa depan.",
    nowTitle: "Tersedia saat ini",
    now: ["Pertanyaan keluarga dan pengembangan secara tertulis.", "Pemilihan perlengkapan dengan keterlibatan pelatih, permintaan fitting dan demonstrasi.", "Catatan privat: profil anak tidak pernah dipublikasikan dan tidak pernah dikomersialkan secara default.", "Jalur edukasi untuk orang tua: konfigurasi, pembebanan, tahapan, catatan dan hak."],
    plannedTitle: "Direncanakan",
    planned: ["Manfaat partisipasi yang ditetapkan program dan dapat digunakan untuk barang serta jasa di dalam ekosistem, bukan bunga tunai.", "Catatan pemilik dan keluarga di dalam usulan arsip pemilik dengan izin wali dan peralihan kendali pada usia 18 tahun."],
    categoriesTitle: "Dipisahkan secara tegas",
    categories: ["Royalti kontraktual yang timbul dari hak berlisensi atau penjualan yang memenuhi syarat", "Manfaat partisipasi yang ditetapkan oleh sebuah program", "Kredit pembelian atau layanan", "Pembayaran di muka", "Keanggotaan institusional"],
    categoriesP: "Kategori-kategori ini tidak pernah diperlakukan sebagai hal yang dapat saling ditukar.",
    statusTitle: "Status sebenarnya dari program keluarga",
    journeyTitle: "Jalur keluarga",
    journey: [
      ["Sasaran", "Apa yang ingin dicapai pemain selanjutnya."],
      ["Level saat ini", "Di mana posisi pemain hari ini."],
      ["Pelatih", "Apakah pelatih ikut serta dalam keputusan perlengkapan."],
      ["Perlengkapan", "Perlengkapan yang sesuai untuk tahap tersebut, termasuk sistem latihan bila relevan."],
      ["Latihan yang disepakati", "Penggunaan yang dipandu pelatih dan disepakati lebih dahulu."],
      ["Peninjauan", "Penilaian ulang pada titik evaluasi yang sebanding."],
    ],
    brief: {
      who: "Orang tua dan wali dari pemain pada tahap apa pun.",
      value: "Jawaban tertulis mengenai perlengkapan yang sesuai, keterlibatan pelatih dan langkah pengembangan berikutnya.",
      now: "Pertanyaan keluarga secara tertulis; pemilihan dengan keterlibatan pelatih; catatan privat — profil anak tidak pernah dipublikasikan.",
      next: "Kirim pengajuan keluarga di bawah ini. Anda langsung menerima ID permintaan.",
    },
    formTitle: "Pengajuan keluarga",
    formNote: "Harus diisi oleh orang tua atau wali. Jangan mencantumkan nama anak, tanggal lahir, sekolah atau informasi medis.",
    noPromise: "Pembelian tidak menjanjikan royalti, imbal hasil investasi, sponsorship atau pembiayaan pengembangan seorang anak.",
    statusP: "Rilis ini menjelaskan modelnya dan menerima pertanyaan tentang program. Akumulasi, pembayaran dan penukaran belum tersedia sampai peristiwa yang memenuhi syarat, penerima manfaat, sumber dana, dasar perhitungan, penggunaan yang diizinkan, perlakuan akuntansi, pengembalian dana, pembalikan transaksi, masa berlaku, keteralihan, penutupan program dan penanganan sengketa ditetapkan secara tertulis. Tidak ada saldo yang dijanjikan tidak akan pernah berkurang, tidak ada partisipasi yang membiayai seluruh latihan, dan tidak ada perlindungan modal yang tersirat.",
    cta: "Kirim pengajuan keluarga atau pengembangan",
  },
  owners: {
    title: "Pemilik dan arsip pemilik",
    lead: "Arsip pemilik adalah usulan catatan berizin atas perlengkapan, pengembangan, pengetahuan, konten dan hak yang terdokumentasi. Arsip ini disajikan sebagai bagian dari arsitektur pemilik yang direncanakan: tidak ada akun, saldo, sertifikat atau prestasi yang ditampilkan secara aktif.",
    nowTitle: "Untuk pemilik saat ini",
    now: ["Pertanyaan pemilik: referensi produk atau nomor seri, penyetelan, layanan dan permintaan catatan secara tertulis.", "Sertifikat Presisi dan dokumentasi set serasi sejauh kelas presisinya menyediakannya, diserahkan bersama produk."],
    archTitle: "Arsitektur arsip yang direncanakan",
    arch: ["Identitas produk dan referensi nomor seri", "Konfigurasi dan sertifikat kendali mutu yang berlaku", "Riwayat layanan dan penyetelan", "Catatan pengembangan pemain atau pelatih", "Kualifikasi dan prestasi yang terverifikasi", "Materi media dan karya yang haknya sudah bersih", "Lisensi, izin dan referensi kontrak", "Catatan program merek pribadi", "Laporan royalti atau manfaat partisipasi yang berlaku"],
    separationTitle: "Apa arti kepemilikan",
    separation: [
      "Kepemilikan atas raket fisik terpisah dari kepemilikan atas hak cipta, lisensi, hak kontraktual atau catatan yang menguraikan hal-hal tersebut.",
      "Dokumen yang tersimpan atau entri blockchain tidak otomatis menjadi bukti bahwa suatu hak hukum ada atau telah beralih.",
      "Bukti mempertahankan klasifikasinya: dinyatakan peserta, dikonfirmasi wali, divalidasi pelatih, diukur sistem.",
      "Untuk anak di bawah umur: catatan privat, izin wali, tidak ada profil anak yang dipublikasikan dan tidak ada komersialisasi identitas secara default.",
      "Ekspor data, koreksi, kendali akses dan peralihan kendali yang semestinya merupakan bagian dari rancangan.",
    ],
    techTitle: "Blockchain 5.0 dan MxSN",
    techP: "Blockchain 5.0 adalah arah teknologi yang dinyatakan; MxSN menetapkan konsep jaringan berizin untuk persetujuan, penyerahan, bukti, hak dan pelaporan. Implementasi operasionalnya tidak direpresentasikan. Model data aplikasi dibangun agar dapat diintegrasikan kemudian melalui antarmuka yang terdokumentasi, tanpa berpura-pura bahwa koneksi itu sudah ada hari ini.",
    cta: "Pertanyaan pemilik",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Penghubung antara pemain, pelatih, klub, akademi, penyedia layanan, operator program dan mitra regional.",
    functionsTitle: "Fungsi yang mungkin",
    functions: ["Penemuan mitra", "Perkenalan", "Program pengembangan", "Dukungan perlengkapan", "Acara", "Akses layanan", "Peluang kemitraan"],
    statusTitle: "Status sebenarnya",
    statusP: "Belum ada direktori publik yang diterbitkan: hanya peserta yang identitas, hubungan dan izin tampilnya sudah dipastikan yang akan dicantumkan. Proposal yang dikirim ke sebuah klub bukanlah kemitraan, dan calon distributor bukanlah distributor yang telah ditunjuk. Penerbitan direktori, pemesanan, perpesanan dan transaksi komersial dikendalikan secara terpisah dan belum aktif.",
    cta: "Ajukan diri ke jaringan",
  },
  partnerships: {
    title: "Jalur kemitraan",
    lead: "Kualifikasi tertulis lebih dahulu. Setiap jalur bermuara pada pengajuan sesuai peran; syarat komersial menyusul secara tertulis.",
    commercialTitle: "Kegiatan komersial yang mungkin dilakukan platform ini",
    commercial: ["Perlengkapan", "Rekayasa khusus", "Personalisasi", "Program tim dan akademi", "Sistem latihan", "Lisensi kontraktual", "Distribusi", "Layanan yang disetujui", "Kategori produk di masa depan"],
    boundary: "Hak atas negara, eksklusivitas, biaya wilayah dan margin distributor adalah syarat yang dinegosiasikan. Tidak ada pendapatan, proyeksi, valuasi, pangsa pasar, imbal hasil, komitmen pendanaan atau kemitraan tanpa nama yang dipublikasikan.",
    routes: {
      coaches: {
        title: "Pelatih",
        lead: "Sistem latihan, fitting, identitas profesional, program yang diizinkan, peluang merek pribadi dan pasokan perlengkapan.",
        points: ["Sweet Spot Trainer dan Spot Trainer dalam latihan yang dipandu pelatih.", "Fitting dengan matriks konfigurasi dan delapan ukuran grip pabrik.", "Coach-to-Brand: profil profesional terverifikasi dan sub-merek yang diatur oleh hak.", "Penggunaan program yang diizinkan mengikuti perjanjian tertulis."],
        cta: "Kirim pengajuan kemitraan pelatih",
        brief: {
          who: "Pelatih mandiri dan tim kepelatihan.",
          value: "Sistem latihan untuk praktik yang dipandu pelatih, fitting dengan matriks seri dan delapan grip pabrik, serta jalur menuju identitas profesional.",
          now: "Pertanyaan pelatih secara tertulis. Tidak ada komisi, penghasilan atau tarif rujukan yang dipublikasikan maupun tersirat.",
          next: "Kirim pengajuan pelatih di bawah ini. Syaratnya menyusul secara tertulis.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klub dan akademi",
        lead: "Perlengkapan tim, sistem latihan, personalisasi, program pengembangan, layanan dan partisipasi jaringan.",
        points: ["Set tim dan set serasi diajukan melalui konfigurator.", "Sistem latihan dan metodologi untuk pengembangan yang terstruktur.", "Personalisasi untuk program tim pada zona yang disetujui.", "Hari demo, sesi fitting dan partisipasi jaringan."],
        cta: "Kirim ringkasan kebutuhan klub atau akademi",
        brief: {
          who: "Klub, akademi dan program tim.",
          value: "Set tim dan set serasi, sistem latihan, personalisasi untuk program tim serta hari demonstrasi.",
          now: "Ringkasan kebutuhan klub dan akademi secara tertulis; set tim diajukan melalui konfigurator.",
          next: "Kirim ringkasan kebutuhan klub atau akademi di bawah ini.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribusi dan pengembangan negara",
        lead: "Pilihan asortmen, koordinasi produksi, kemampuan teknis, pengembangan wilayah dan kualifikasi komersial yang bersifat rahasia.",
        points: ["Kualifikasi tertulis atas mitra, wilayah dan kanal penjualan.", "Asortmen ditetapkan dari matriks konfigurasi dan kelas presisi.", "Wilayah, eksklusivitas, volume, harga dan perlindungan komersial adalah syarat yang dinegosiasikan dan disepakati secara tertulis.", "Badan hukum pihak kontrak, syarat pembayaran dan dasar pengiriman ditetapkan per transaksi."],
        cta: "Kirim pengajuan distribusi atau pengembangan negara",
        brief: {
          who: "Peritel, distributor dan mitra negara.",
          value: "Asortmen yang ditetapkan dari matriks terkonfirmasi, kelas presisi dan rangkaian grip, dengan kualifikasi tertulis atas wilayah dan kanal penjualan.",
          now: "Pertanyaan distribusi secara tertulis. Wilayah, eksklusivitas, volume dan harga dinegosiasikan — tidak satu pun diberikan melalui formulir.",
          next: "Kirim pengajuan distribusi di bawah ini.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategis dan investasi",
        lead: "Kemampuan rekayasa, kedalaman konfigurasi, model produksi, jalur ke pasar, kekayaan intelektual, layanan dan peluang ekspansi.",
        points: ["Diskusi strategis yang terkualifikasi atau akses informasi terkendali mengikuti kualifikasi tertulis.", "Informasi publik terbatas pada spesifikasi produk yang disetujui, arsitektur konfigurasi, kemampuan yang terverifikasi dan penjelasan program.", "Perhitungan ekonomi khusus pembeli, struktur biaya, metodologi yang dilindungi dan perjanjian yang tidak dipublikasikan hanya diungkapkan di bawah NDA atau kontrak."],
        cta: "Ajukan diskusi strategis yang terkualifikasi",
        brief: {
          who: "Investor dan mitra strategis.",
          value: "Diskusi terkualifikasi mengenai kemampuan rekayasa, kedalaman konfigurasi, model produksi, jalur ke pasar dan kekayaan intelektual.",
          now: "Tidak ada angka keuangan, proyeksi, valuasi atau imbal hasil yang dipublikasikan. Informasi terkendali mengikuti kualifikasi tertulis dan NDA.",
          next: "Ajukan diskusi strategis yang terkualifikasi di bawah ini.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Program institusional",
        lead: "Edukasi, akses, inovasi, bukti pengembangan, dampak sosial dan program yang disusun secara tepat.",
        points: ["Program institusional disusun melalui MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) sejauh program tersebut menetapkan peran itu.", "Dana program yang dibatasi penggunaannya dan transaksi komersial tetap terpisah.", "Sebuah pengajuan bukan permohonan keanggotaan yang diterima, dan pembeli perlengkapan bukan anggota institusional.", "Hibah, status nirlaba, perlakuan pajak dan izin regulator bersifat spesifik per negara dan tidak pernah diasumsikan."],
        cta: "Kirim pengajuan program institusional",
        brief: {
          who: "Institusi, program edukasi dan pengembangan.",
          value: "Program untuk edukasi, akses, inovasi dan bukti pengembangan, disusun bersama operator yang tepat.",
          now: "Pengajuan institusional secara tertulis. Sebuah pengajuan bukan permohonan keanggotaan; pembelian perlengkapan bukan keanggotaan institusional.",
          next: "Kirim pengajuan institusional di bawah ini.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Pengungkapan publik dan terkendali",
    disclosure: {
      public: { h: "Publik", p: "Spesifikasi produk yang disetujui, konstruksi, arsitektur konfigurasi, tujuan latihan, kemampuan yang terverifikasi, penjelasan program dan jalur kemitraan." },
      qualified: { h: "Pengajuan terkualifikasi", p: "Kebutuhan teknis, volume, minat atas wilayah, cakupan pengembangan dan diskusi komersial yang relevan." },
      controlled: { h: "Terkendali oleh NDA atau kontrak", p: "Formula internal, protokol kendali mutu yang rinci, susunan lapisan karbon, perkakas, metode produksi, identitas pemasok, struktur biaya, perhitungan ekonomi khusus pembeli, metodologi yang dilindungi, perjanjian yang tidak dipublikasikan dan catatan hak yang sensitif." },
    },
  },
  contact: {
    title: "Kontak dan permintaan",
    lead: "Pilih tujuan permintaan Anda. Setiap formulir hanya mengumpulkan data yang diperlukan untuk mengarahkan dan menilainya. Permintaan dijawab secara tertulis.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Identitas hukum",
  },
  form: {
    purposeLabel: "Tujuan permintaan",
    purposes: {
      selection: "Bantuan memilih raket",
      product: "Pertanyaan produk",
      fitting: "Fitting atau demonstrasi",
      technical: "Ringkasan teknis",
      config: "Permintaan konfigurasi",
      gps: "Profil perlengkapan GPS",
      coach: "Kemitraan pelatih",
      club: "Ringkasan kebutuhan klub atau akademi",
      distribution: "Distribusi atau pengembangan negara",
      brand: "Kolaborasi merek atau duta merek",
      family: "Pertanyaan keluarga atau pengembangan",
      institutional: "Program institusional",
      strategic: "Diskusi strategis atau investasi",
      owner: "Pertanyaan pemilik",
      network: "Pengajuan ke Sports Network",
      general: "Pertanyaan umum",
    },
    fields: {
      name: "Nama",
      email: "Email",
      role: "Peran Anda",
      country: "Negara atau wilayah",
      organisation: "Organisasi",
      message: "Pesan Anda",
      level: "Level saat ini",
      objectives: "Apa yang paling penting (maksimal tiga)",
      currentRacquet: "Raket saat ini",
      grip: "Ukuran grip, jika diketahui",
      seriesInterest: "Seri yang diminati",
      quantity: "Jumlah",
      city: "Kota atau lokasi sesi",
      coachInvolved: "Apakah pelatih terlibat?",
      timing: "Waktu yang diinginkan",
      targets: "Target yang diinginkan",
      limits: "Batas yang wajib",
      use: "Tujuan penggunaan",
      tradeoffs: "Kompromi yang dapat diterima",
      basis: "Dasar pengukuran",
      players: "Jumlah pemain",
      interests: "Bidang yang diminati",
      territory: "Wilayah yang diminati",
      channels: "Kanal dan pengalaman yang sudah ada",
      audience: "Audiens atau disiplin",
      proposal: "Kolaborasi yang diusulkan",
      goal: "Sasaran pengembangan",
      ageBand: "Kelompok usia pemain",
      scope: "Cakupan program",
      interestArea: "Bidang yang diminati",
      productRef: "Referensi produk atau nomor seri",
      requestType: "Jenis permintaan",
      seeking: "Apa yang Anda cari",
      consent: "Saya setuju MAXIMUS menyimpan dan menggunakan data ini untuk menjawab permintaan ini. Ini bukan pendaftaran untuk menerima materi pemasaran.",
    },
    roles: { player: "Pemain", parent: "Orang tua atau wali", coach: "Pelatih", club: "Klub atau akademi", retailer: "Peritel", distributor: "Distributor", brand: "Merek atau duta merek", investor: "Investor atau mitra strategis", institution: "Institusi", other: "Lainnya" },
    interestOptions: { training: "Sistem latihan", fitting: "Fitting raket", identity: "Identitas profesional", programmes: "Program yang diizinkan", brand: "Merek pribadi", supply: "Pasokan perlengkapan", team: "Perlengkapan tim", personalisation: "Personalisasi", development: "Program pengembangan", service: "Layanan", network: "Partisipasi jaringan" },
    ownerTypes: { setup: "Penyetelan dan konfigurasi", service: "Layanan", records: "Catatan dan sertifikat", other: "Lainnya" },
    strategicAreas: { engineering: "Kemampuan rekayasa", configuration: "Kedalaman konfigurasi", manufacturing: "Model produksi", routes: "Jalur ke pasar", ip: "Kekayaan intelektual dan layanan", expansion: "Peluang ekspansi" },
    errors: {
      required: "Kolom ini wajib diisi.",
      too_long: "Isian ini terlalu panjang.",
      too_short: "Isian ini terlalu pendek.",
      invalid_email: "Masukkan alamat e-mail yang sah, misalnya name@example.com.",
      invalid_choice: "Pilih salah satu opsi.",
      not_number: "Masukkan bilangan bulat, hanya dengan angka.",
      out_of_range: "Nilai ini di luar rentang yang diterima.",
      not_in_matrix: "Berat ini tidak ada di dalam matriks terdaftar untuk seri yang dipilih.",
      decimal_not_supported: "Masukkan bilangan bulat tanpa desimal.",
      too_many: "Pilih tidak lebih dari tiga opsi.",
      consent_required: "Persetujuan diperlukan agar MAXIMUS dapat menjawab permintaan ini.",
      invalid: "Isian ini tidak sah.",
    },
  },
  legal: {
    title: "Identitas hukum dan kendali",
    lead: "Merek publiknya adalah MAXIMUS / MAXIMUS GPS. Identitas hukum yang menjalankan kegiatan dapat dibedakan dan disebutkan di sini.",
    entities: {
      institutional: { role: "Lapisan program institusional", p: "Menyediakan lapisan program institusional sejauh sebuah program menetapkan peran tersebut. Bukan penjual raket secara komersial. Sebuah organisasi nirlaba yang terdaftar di Dubai International Financial Centre." },
      equipment: { role: "Badan komersial untuk perlengkapan", p: "Badan komersial perlengkapan untuk pasokan, distribusi dan penyerahan komersial berdasarkan kontrak sejauh dokumen operasional yang berlaku menetapkan peran tersebut. Pihak kontrak untuk setiap transaksi disebutkan dalam dokumen transaksi tersebut." },
      ip: { role: "Kekayaan intelektual, merek dan koordinasi komersial", p: "Muncul untuk peran yang sudah mapan dalam kekayaan intelektual, merek atau koordinasi komersial. Tidak ada tanggung jawab kontraktual yang belum dikonfirmasi yang dibebankan." },
      stewardship: { role: "Referensi penaungan", p: "House of Maximus adalah referensi penaungan bagi ekosistem ini sejauh didukung oleh sumber yang relevan." },
      control: { role: "Kendali internal atas kekayaan intelektual, asal-usul dan dokumen", p: "MIPA adalah lapisan internal untuk kekayaan intelektual, asal-usul dan kendali dokumen. Entri MIPA internal berbeda dari pendaftaran merek dagang, paten atau hak cipta eksternal maupun pengakuan pengadilan, dan bukan merupakan persetujuan visual." },
    },
    labels: { licence: "Lisensi", registration: "Pendaftaran", vat: "VAT TRN", address: "Alamat", email: "Email", jurisdiction: "Yurisdiksi" },
    boundaryTitle: "Batasan",
    boundary: [
      "Pembelian tidak secara otomatis memberikan keanggotaan institusional, hak tata kelola, royalti atau hak investasi.",
      "Peran institusional terpisah dari transaksi perlengkapan yang bersifat komersial.",
      "Privasi, syarat program dan pengaturan akses terkendali sesuai dengan fitur yang benar-benar dirilis.",
      "Tidak ada pernyataan menyeluruh tentang hukum yang berlaku bagi setiap pengunjung, setiap penjualan atau setiap program di luar negeri; dasar kontraktualnya ditetapkan per perjanjian.",
    ],
  },
  privacy: {
    title: "Privasi",
    updated: "Versi 2026-09-21 · situs 4.2",
    contactTitle: "Kontak untuk pertanyaan privasi",
    sections: {
      collect: ["Apa yang dikumpulkan", "Saat Anda mengirim formulir: data yang Anda masukkan (nama, e-mail, peran, negara atau wilayah, organisasi bila disebutkan, pesan Anda dan jawaban pada formulir), parameter halaman dan kampanye dari kunjungan Anda (halaman masuk, bahasa, parameter utm; pengenal klik iklan hanya bila Anda mengizinkan analitik) serta waktu pengiriman. Alamat IP Anda hanya digunakan dalam bentuk hash yang berumur pendek untuk membatasi penyalahgunaan dan tidak disimpan bersama permintaan Anda."],
      purpose: ["Mengapa", "Untuk menjawab permintaan Anda, menyiapkan proposal atau spesifikasi yang Anda minta, dan menyimpan catatan permintaan tersebut. Tidak ada pesan pemasaran yang dikirim atas dasar sebuah formulir."],
      storageOn: ["Di mana permintaan disimpan", "Permintaan disimpan dalam basis data milik Upstash, Inc. (Redis), yang disediakan melalui platform hosting Vercel Inc."],
      notifyEmail: ["Pemberitahuan permintaan baru", "Ketika sebuah permintaan diterima, pemberitahuan yang memuat data yang Anda kirim dikirimkan melalui e-mail ke kotak surat MAXIMUS yang bertanggung jawab."],
      notifyTelegram: ["Pemberitahuan permintaan baru", "Ketika sebuah permintaan diterima, pemberitahuan yang memuat data yang Anda kirim dikirimkan kepada penanggung jawab di MAXIMUS melalui Telegram (Telegram FZ-LLC, Dubai), yang karena itu memproses pemberitahuan tersebut saat transit."],
      notifyWebhook: ["Pemberitahuan permintaan baru", "Ketika sebuah permintaan diterima, pemberitahuan yang memuat data yang Anda kirim dikirimkan ke endpoint internal MAXIMUS melalui koneksi terenkripsi yang bertanda tangan digital."],
      notifyNone: ["Pemberitahuan permintaan baru", "Pemberitahuan untuk permintaan baru masih disiapkan. Permintaan Anda disimpan dan dibaca oleh MAXIMUS dari daftar internal; tidak ada yang dikirim ke pihak ketiga untuk tujuan ini."],
      storageOff: ["Di mana permintaan disimpan", "Penyimpanan permintaan masih disiapkan. Sampai penyimpanan itu aktif, formulir menyatakan bahwa permintaan tidak dapat diterima; tidak ada yang disimpan. Situs ini di-hosting oleh Vercel Inc."],
      browser: ["Penyimpanan di peramban", "Penyimpanan sesi menyimpan jawaban pilihan ganda pada GPS dan konfigurator serta parameter kampanye dari kunjungan Anda selama sesi peramban ini. Data kontak, teks bebas, teks gravir dan informasi tentang anak tidak disimpan di peramban."],
      analyticsOn: ["Analitik", "Dengan persetujuan Anda, Google Analytics 4 mengukur kunjungan dan peristiwa pada formulir tanpa data kontak maupun isi permintaan. Pilihan Anda disimpan di penyimpanan lokal dan dapat diubah kapan saja melalui “Pengaturan analitik” di bagian bawah halaman. Formulir tetap berfungsi tanpa analitik."],
      analyticsOff: ["Analitik", "Tidak ada alat analitik yang aktif di situs ini."],
      retention: ["Masa penyimpanan", "Belum ada periode penghapusan otomatis yang diterapkan. Anda dapat meminta permintaan Anda dihapus kapan saja."],
      children: ["Anak-anak", "Formulir harus diisi oleh orang dewasa. Permintaan yang menyangkut pemain di bawah 18 tahun diajukan oleh orang tua atau wali. Jangan mengirimkan nama anak, tanggal lahir, sekolah atau informasi medis. Profil anak tidak pernah dipublikasikan."],
      rights: ["Hak Anda", "Untuk mengakses, memperbaiki atau menghapus permintaan Anda, tulis ke gps@maximus.tennis dan sebutkan ID permintaan Anda."],
      controlled: ["Informasi terkendali", "Dokumen rahasia tidak disimpan di dalam maupun disajikan oleh situs ini. Pengungkapan terkendali dilakukan di bawah NDA atau kontrak melalui kanal terpisah."],
    },
  },
  terms: {
    title: "Ketentuan penggunaan",
    copyright: "Hak cipta atas situs ini — teks, foto, desain dan kodenya — sepenuhnya milik Maximus Kiriyakulov. Hak itu tidak dialihkan kepada perusahaan mana pun maupun kepada orang lain.",
    updated: "Versi 2026-09-21",
    sections: [
      ["Informasi, bukan penawaran", "Informasi produk di situs ini menguraikan spesifikasi yang disetujui, arsitektur konfigurasi dan penjelasan program. Informasi itu bukan penawaran untuk menjual, bukan daftar harga, bukan pernyataan stok dan bukan komitmen pengiriman. Syarat komersial disepakati secara terpisah dan tertulis dengan badan hukum pihak kontrak yang disebutkan dalam setiap transaksi."],
      ["Permintaan", "Permintaan yang dikirim melalui situs ini — termasuk profil GPS, permintaan konfigurasi dan ringkasan teknis — disimpan dengan ID permintaan dan ditinjau. Permintaan itu bukan pesanan yang diterima, bukan komitmen produksi, bukan jadwal pertemuan yang dipastikan, bukan permohonan keanggotaan dan bukan permohonan yang diterima untuk program apa pun."],
      ["Spesifikasi dan bukti", "Nilai hasil perhitungan, target produksi dan spesifikasi terkonfirmasi dibedakan pada halaman yang bersangkutan. Nilai kekakuan merupakan target produksi sampai dipublikasikan sebaliknya. Tidak ada hasil bagi pemain tertentu yang dijamin."],
      ["Ekosistem, keanggotaan dan hak", "Pembelian sebuah raket tidak menciptakan keanggotaan institusional, hak investasi, kepemilikan atas kekayaan intelektual, hak atas royalti atau manfaat partisipasi. Hak-hak mengikuti syarat program yang dipublikasikan atau perjanjian tertulis."],
      ["Kekayaan intelektual", "MAXIMUS®, lambang singa, merek GPS dan isi situs ini dilindungi. Formula rekayasa internal, protokol kendali mutu, susunan lapisan karbon, perkakas, identitas pemasok, struktur biaya dan metodologi yang dilindungi tidak diungkapkan di sini."],
    ],
  },
  lead: {
    submit: "Kirim permintaan",
    submitting: "Mengirim…",
    retry: "Coba lagi",
    acceptedEyebrow: "Permintaan diterima",
    acceptedTitle: "Permintaan Anda telah kami terima.",
    requestId: "ID permintaan",
    acceptedNext: "MAXIMUS meninjau setiap permintaan dan menjawab secara tertulis ke alamat e-mail yang Anda berikan. Simpan ID permintaan untuk tindak lanjut apa pun.",
    duplicate: "Permintaan ini sudah pernah diterima; tidak ada duplikat yang dibuat.",
    another: "Mulai permintaan baru",
    errorsTitle: "Mohon periksa kolom berikut:",
    failTitle: "Permintaan Anda belum terkirim.",
    fail: {
      offline: "Perangkat Anda sedang offline.",
      network: "Koneksi ke server gagal.",
      timeout: "Server tidak menjawab tepat waktu.",
      rate_limited: "Terlalu banyak permintaan datang dari jaringan ini. Silakan coba lagi dalam beberapa menit.",
      too_fast: "Formulir dikirim sangat cepat. Mohon periksa lalu kirim kembali.",
      spam_suspected: "Permintaan dihentikan oleh filter spam.",
      unavailable: "Permintaan tidak dapat diterima saat ini.",
      default: "Terjadi kesalahan yang tidak terduga.",
    },
    keepNote: "Isian Anda tetap tersimpan di halaman ini, sehingga Anda dapat mencoba lagi.",
    sendByEmail: "Kirim permintaan ini melalui e-mail",
    sendByEmailNote: "Aplikasi e-mail Anda terbuka berisi teks permintaan ini. MAXIMUS menerimanya ketika Anda mengirim e-mail tersebut.",
    mailConfig: "Konfigurasi",
    mailPage: "Halaman",
    fallback: "Jika masalahnya berlanjut, tulis ke {email}. Sebuah permintaan hanya terhitung terkirim bila ID permintaan sudah ditampilkan.",
    privacyLink: "Pemberitahuan privasi",
    hpLabel: "Biarkan kolom ini kosong",
    consentShort: "Persetujuan",
    after: "Setelah pengiriman, ID permintaan ditampilkan di halaman ini. Permintaan ditinjau dan dijawab secara tertulis; sebuah permintaan bukan pesanan.",
    basis: { unstrung: "Tanpa senar", strung: "Dengan senar", unknown: "Tidak yakin — akan disepakati dalam spesifikasi" },
    hints: {
      email: "MAXIMUS menjawab secara tertulis ke alamat ini.",
      goal: "Misalnya: raket kompetisi pertama, atau beralih dari raket junior. Jangan mencantumkan nama, tanggal lahir atau informasi medis tentang seorang anak.",
      currentRacquet: "Merek dan model, jika diketahui.",
      message: "Jangan mencantumkan kata sandi, data pembayaran atau informasi medis.",
    },
  },
  choose: {
    eyebrow: "Bantuan memilih",
    title: "Bantu saya memilih raket",
    lead: "Beri tahu MAXIMUS level Anda dan apa yang paling penting bagi Anda. Jawaban Anda ditinjau dan Anda menerima proposal tertulis: seri, kelas presisi, berat dan grip.",
    stepsTitle: "Apa yang terjadi selanjutnya",
    steps: [
      ["Jawaban Anda", "Level, prioritas dan ukuran grip bila Anda mengetahuinya."],
      ["Peninjauan ahli", "MAXIMUS membandingkan jawaban Anda dengan matriks setiap seri."],
      ["Proposal tertulis", "Konfigurasi yang diusulkan dan langkah berikutnya, secara tertulis."],
    ],
    formTitle: "Jawaban Anda",
    submit: "Minta bantuan memilih",
    altTitle: "Lebih suka memutuskan sendiri?",
    altGps: "Profil GPS yang terperinci",
    altBuild: "Konfigurasikan langsung",
    note: "Tidak ada fitting otomatis dan tidak ada klaim akurasi: setiap permintaan ditinjau oleh manusia.",
  },
  consent: {
    title: "Analitik",
    text: "Bolehkah MAXIMUS mengukur kunjungan dengan Google Analytics? Formulir tetap berfungsi dalam kedua pilihan; tidak ada data kontak maupun isi permintaan yang dikirim ke analitik.",
    allow: "Izinkan analitik",
    decline: "Tolak",
  },
  familyPlan: {
    title: "Rencana Keluarga",
    metaDescription: "Hitung anggaran tenis keluarga Anda: sesi, jam, kontak bola, serta biaya satu sesi, satu jam, dan satu pukulan — dari angka Anda sendiri, dalam tiga skenario.",
    eyebrow: "Rencana Keluarga · Berkontribusi bersama kami",
    heroTitle: "Berapa biaya tenis keluarga Anda — dan apa yang Anda dapatkan?",
    heroLead: "Hitung anggaran keluarga Anda, sesi dan jam yang dibiayainya, perkiraan jumlah kontak bola, serta biaya satu sesi, satu jam, dan satu pukulan — sesuai ketentuan Anda sendiri.",
    heroCta: "Hitung rencana keluarga Anda",
    strategy: {
      eyebrow: "Tujuan kami",
      title: "Lebih banyak tenis. Lebih banyak peluang. Bersama.",
      p1: "Tujuan kami adalah menumbuhkan pasar tenis dunia sepuluh kali lipat dengan memperluas partisipasi serta membuat jalan menuju tenis lebih jelas dan lebih mudah dijangkau. MAXIMUS bertujuan memimpin melalui manajemen, metodologi, kualitas, hasil, dan upaya mempopulerkan permainan ini.",
      p2: "Kami memandang produsen perlengkapan tenis lainnya beserta merek mereka sebagai mitra potensial. Kami mengusulkan untuk menyatukan kekuatan perusahaan, pelatih, klub, dan keluarga dalam satu program bersama guna mengembangkan, mempromosikan, dan memperluas tenis atas dasar saling menguntungkan.",
      p3: "MAXIMUS adalah unsur kelima dalam pendekatan ini: peran pemersatu yang membantu kekuatan-kekuatan yang terpisah bekerja bersama. Tantangan bersama kita adalah penyakit, kurangnya aktivitas fisik anak-anak, dan berbagai hambatan yang menghalangi orang untuk mulai bermain dan terus bermain.",
      p4: "Bagi keluarga, semuanya dimulai dari kejelasan. Rencana Keluarga menampilkan anggaran, jumlah sesi dan jam, perkiraan volume kontak bola, serta biaya latihan. Ubah kondisinya dan pilih skenario yang paling sesuai bagi Anda.",
      note: "Pertumbuhan sepuluh kali lipat adalah tujuan strategis MAXIMUS, bukan hasil yang sudah tercapai. Kalkulator ini menampilkan perhitungan skenario dan tidak menjanjikan penghematan, efek medis, maupun hasil olahraga apa pun.",
      ctaCalc: "Hitung rencana keluarga Anda",
      ctaPartner: "Diskusikan pengembangan tenis bersama",
    },
    beyond: {
      eyebrow: "Di luar lapangan",
      title: "Apa yang dibangun rencana ini selain latihan",
      admission: {
        h: "Masuk ke sekolah dan universitas unggulan",
        p: "MAXIMUS mendukung keluarga dalam perjalanan menuju sekolah dan universitas unggulan di seluruh dunia: membangun rekam jejak olahraga pemain, menyiapkan dokumen dan berkas pendaftaran, serta memilih program yang memadukan olahraga dan studi. Jika beasiswa olahraga diberikan, beasiswa itu mengurangi biaya pendidikan yang dibayar keluarga.",
      },
      assets: {
        h: "Aset digital: nama, citra, dan rekam jejak pemain",
        p: "Nama, citra, prestasi, konten, dan merek pribadi seorang pemain adalah aset, dan seiring waktu aset-aset ini dapat membangun nilai finansial dan status yang signifikan. MAXIMUS membantu menciptakan, mendaftarkan, dan melindunginya agar nilai tersebut tetap menjadi milik pemain dan keluarga.",
      },
      note: "Keduanya bukan bagian dari kalkulator. Nilai sebuah kursi di sekolah, beasiswa, atau aset digital bergantung pada kasusnya masing-masing dan tidak diperkirakan di sini.",
      cta: "Tanyakan dukungan pendaftaran dan aset digital",
    },
    steps: ["Data keluarga", "Biaya satuan", "Rencana jangka panjang", "Perhitungan akhir"],
    stepsLabel: "Langkah kalkulator",
    scenarios: { now: "Sekarang", planned: "Rencana", wish: "Keinginan" },
    scenarioHints: { now: "Apa yang dilakukan keluarga Anda saat ini.", planned: "Apa yang Anda rencanakan berikutnya.", wish: "Apa yang ingin Anda lakukan." },
    currency: {
      label: "Mata uang",
      note: "Setiap jumlah yang Anda masukkan dinyatakan dalam mata uang ini. Tidak ada yang dikonversi.",
    },
    fields: {
      players: { label: "Anggota keluarga yang bermain", hint: "Bilangan bulat." },
      cost: { label: "Harga satu sesi untuk satu pemain", hint: "Jumlah bulat, sudah termasuk pajak dan biaya lain." },
      sessions: { label: "Sesi per pemain per bulan", hint: "Bilangan bulat." },
      minutes: { label: "Durasi satu sesi, dalam menit", hint: "Waktu penuh termasuk jeda. Pecahan diperbolehkan." },
      contacts: { label: "Kontak bola per pemain per sesi", hint: "Satu kontak adalah raket milik pemain itu sendiri menyentuh bola. Satu reli bukan satu kontak. Hitung dengan cara yang sama di setiap skenario." },
    },
    presetsLabel: "Pilihan cepat, menit",
    ages: {
      title: "Durasi rencana",
      start: "Usia awal",
      end: "Usia akhir",
      hint: "Asumsi anonim tentang berapa lama rencana berjalan, hanya dipakai untuk tabel jangka panjang. Bukan tanggal lahir dan bukan usia mulai yang direkomendasikan.",
    },
    extras: {
      title: "Biaya tambahan keluarga",
      note: "Jumlah-jumlah ini berlaku untuk seluruh keluarga dan untuk ketiga skenario. Jumlah ini tidak dikalikan dengan jumlah pemain dan tidak masuk ke dalam biaya per jam maupun per kontak.",
      equipment: "Perlengkapan pertama — satu jumlah untuk periode ini",
      clothing: "Pakaian dan sepatu — satu jumlah untuk periode ini",
      renewal: "Penggantian perlengkapan — satu jumlah untuk periode ini, tidak berulang otomatis",
      court: "Lapangan atau klub — per bulan, seluruh keluarga",
      travel: "Perjalanan dan acara — per bulan, seluruh keluarga",
      quoteSource: "Sumber harga (opsional)",
      quoteDate: "Tanggal harga (opsional)",
      quoteNote: "Ditampilkan persis seperti yang Anda masukkan. MAXIMUS tidak memverifikasi harga-harga ini.",
    },
    storage: {
      save: "Simpan rencana di perangkat ini",
      clear: "Hapus rencana dari perangkat ini",
      saved: "Rencana tersimpan di perangkat ini. Tidak ada yang dikirim ke mana pun.",
      cleared: "Rencana dihapus. Kalkulator kembali ke nilai awalnya.",
      restored: "Rencana Anda yang tersimpan di perangkat ini telah dipulihkan.",
      invalid: "Rencana yang tersimpan di perangkat ini tidak dapat dibaca sehingga tidak diterapkan. Anda dapat memulai perhitungan baru.",
      unavailable: "Peramban ini tidak mengizinkan penyimpanan di perangkat.",
    },
    annual: {
      title: "Satu tahun, berdampingan",
      sessions: "Sesi-pemain per tahun",
      cost: "Pengeluaran keluarga untuk sesi per tahun",
      hours: "Jam-pemain per tahun",
      length: "Durasi satu sesi",
      contacts: "Kontak bola per tahun",
      note: "Sesi-pemain dan jam-pemain menjumlahkan sesi semua pemain. Keduanya bukan jam sewa lapangan atau jumlah pertemuan kelompok: dua pemain yang berlatih bersama selama 90 menit dihitung sebagai 2 sesi-pemain dan 3 jam-pemain.",
    },
    economics: {
      title: "Biaya satu sesi, satu jam, dan satu kontak",
      session: "Satu sesi untuk satu pemain",
      hour: "Satu jam latihan satu pemain",
      contact: "Satu kontak bola",
      undefinedContacts: "Tidak dapat dihitung: 0 kontak",
      undefinedMinutes: "Tidak dapat dihitung: 0 menit",
      below: "kurang dari {value}",
      note: "Hanya harga sesi yang masuk ke dalam angka ini. Biaya tambahan keluarga tidak dibagi dengan jumlah kontak.",
      caption: "Jumlah kontak dihitung dari volume sesi yang dipilih dan asumsi model. Latihan yang sebenarnya bergantung pada format, jeda, dan kondisi latihan. Biaya per kontak adalah ukuran anggaran, bukan ukuran kualitas kepelatihan.",
    },
    longTerm: {
      title: "Rencana pengeluaran jangka panjang",
      horizon: "Jangka waktu",
      activeYears: "Tahun aktif",
      years: "{n} tahun",
      note: "Tahun aktif dibatasi oleh selisih kedua usia. Harga, frekuensi, inflasi, musim, sesi yang terlewat, dan nilai tukar dianggap tetap. Biaya tambahan tidak termasuk dalam tabel ini.",
    },
    final: {
      title: "Perhitungan akhir",
      scenario: "Skenario",
      months: "Periode, dalam bulan",
      heading: "{scenario} · {months} bulan",
      total: "Total untuk periode ini",
      training: "Sesi",
      extras: "Biaya tambahan",
      oneOff: "Pos sekali bayar",
      monthly: "Pos bulanan × bulan",
      sessions: "Sesi-pemain dalam periode",
      hours: "Jam-pemain dalam periode",
      contacts: "Kontak bola dalam periode",
      formulaTitle: "Cara menghitungnya",
      formula: "Total = pemain × sesi per bulan × bulan × harga sesi + biaya sekali bayar + bulan × biaya tambahan bulanan.",
      formulaNote: "Biaya tambahan dimasukkan untuk seluruh keluarga. Pos sekali bayar dihitung satu kali, bahkan untuk periode 0 bulan.",
      inputs: "Data yang Anda masukkan",
    },
    units: { min: "mnt", h: "jam", approx: "≈" },
    errors: {
      title: "Perbaiki isian berikut untuk melihat hasilnya",
      required: "Wajib — masukkan angka; 0 diperbolehkan.",
      negative: "Tidak boleh negatif.",
      integer: "Hanya bilangan bulat.",
      number: "Masukkan angka.",
      tooLarge: "Angka ini terlalu besar untuk dihitung.",
      endBeforeStart: "Usia akhir tidak boleh lebih rendah daripada usia awal.",
      tooLong: "Maksimal 200 karakter.",
      date: "Masukkan tanggal yang valid.",
      currency: "Pilih mata uang.",
      scenario: "Pilih skenario.",
      result: "Hasilnya terlalu besar untuk ditampilkan secara andal. Kurangi nilai yang dimasukkan.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: komposisi lengkap — alat tampak dari depan dan dari samping, lambang singa dalam lingkaran yang digravir pada kepala kontak bundar, gravir MAXIMUS dan SPOT TRAINER di sepanjang batang, serta tutup gagang bersegi delapan dengan lambang singa",
    greatHero: "Seri MAXIMUS GREAT, 369 g: komposisi lengkap dengan detail kepala berwarna merah dan kuning, tulisan MAXIMUS mengilap, tanda tangan Maximus pada batang dan tutup gagang berlambang singa",
    spotDetail: "Dua MAXIMUS Spot Trainer dilihat lebih dekat: singa yang digravir pada kepala kontak hitam matte, bungkus grip beralur dan tutup gagang bersegi delapan dengan lambang singa",
    spotPair: "Dua MAXIMUS Spot Trainer diletakkan menyudut di atas permukaan gelap, MAXIMUS digravir di sepanjang batang yang satu dan SPOT TRAINER di sepanjang batang yang lain, dengan lambang singa dalam lingkaran pada setiap kepala kontak",
    spinVisual: "MAXIMUS SPIN: kepala bersenar, tulisan MAXIMUS mengilap, grip dan tutup gagang berlambang singa",
    powerVisual: "MAXIMUS POWER: kepala bersenar, tulisan MAXIMUS mengilap, gravir personalisasi, grip dan tutup gagang berlambang singa",
    greatVisual: "MAXIMUS GREAT: kepala bersenar, tulisan MAXIMUS mengilap, gravir personalisasi, grip, tutup gagang berlambang singa dan tanda seri G pada leher raket",
    spinHead: "Kepala dan bidang senar MAXIMUS SPIN",
    handleLion: "Leher, grip dan tutup gagang MAXIMUS dengan lambang singa",
    engraving: "Gravir personalisasi warna perak pada batang",
    lettering: "Tulisan MAXIMUS hitam mengilap pada rangka hitam matte",
    variantAlt: "Seri MAXIMUS {series} — {w} g, keseimbangan {b} mm: visualisasi lengkap dengan strip spesifikasi, zona gravir personalisasi dan penandaan MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistem empat raket",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Batang Sweet Spot Trainer dengan tulisan MAXIMUS",
    sstGrips: "Grip dan tutup gagang Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, empat tutup gagang dengan lambang singa",
    note: "Visual produk",
  },
  notFound: { title: "Halaman tidak ditemukan", p: "Halaman yang Anda minta tidak tersedia dalam bahasa ini.", cta: "Ke halaman beranda" },
};

export default id;
