/* Italian dictionary — MAXIMUS website v4.0. Translated from content/en.js; numerical product data lives in data/products.js. */
const it = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — racchette da tennis interamente in carbonio, progettate su specifica",
    defaultDescription:
      "Racchette da tennis interamente in carbonio, dal telaio al manico: GREAT 97 in², POWER 98 in² e SPIN 100 in², otto misure di manico di fabbrica L0–L7, classi di precisione per peso, bilanciamento, swingweight e rigidità, e progettazione personalizzata su richiesta.",
  },
  common: {
    statuses: {
      current: "Attuale",
      agreement: "Disponibile su accordo",
      development: "In sviluppo",
      concept: "Concetto",
      target: "Obiettivo di produzione",
      modelled: "Calcolato",
      confirmed: "Confermato",
      requested: "Architettura richiesta",
      notprovided: "Non fornito",
    },
    brief: { who: "A chi è rivolto", value: "Che cosa ottiene", now: "Confermato ora", next: "Passo successivo" },
    labels: {
      next: "Avanti",
      back: "Indietro",
      edit: "Modifica risposte",
      review: "Riepilogo",
      start: "Inizia",
      restart: "Ricomincia",
      copy: "Copia il testo della richiesta",
      copied: "Copiato",
      openEmail: "Apri l'email per inviare questa richiesta",
      reference: "Riferimento della richiesta",
      weight: "Peso",
      balance: "Bilanciamento",
      swingweight: "Swingweight",
      stiffness: "Rigidità",
      grip: "Misura del manico",
      headSize: "Superficie del piatto",
      series: "Serie",
      precisionClass: "Classe di precisione",
      quantity: "Quantità",
      notProvided: "Non ancora pubblicato",
      requestTarget: "Obiettivo richiesto",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Continua a leggere",
      allSeries: "Tutte le serie",
      points: "pesi elencati",
      optional: "facoltativo",
      required: "obbligatorio",
      select: "Seleziona",
      yes: "Sì",
      no: "No",
      unknown: "Non so",
      custom: "Obiettivo personalizzato",
      listed: "Peso elencato",
      individual: "Racchetta singola",
      pair: "Coppia abbinata",
      triple: "Terzetto abbinato",
      team: "Set per squadra",
      summaryTitle: "Riepilogo della sua richiesta",
      nextAction: "Azione successiva",
      status: "Stato",
      learn: "Per saperne di più",
      schematic: "Schema — non è una misurazione",
      photo: "Fotografia",
    },
    ecosystemStrip: "L'ecosistema MAXIMUS",
    truth: {
      noPrices: "Prezzi, quantità minime, tempi di consegna, garanzie e impegni di consegna sono confermati per iscritto per ciascun mercato e per ciascun programma.",
      requestNotOrder: "Una richiesta è una richiesta di esame. Non è un ordine accettato, un impegno di produzione o un appuntamento confermato.",
      noGuarantee: "Nessun risultato per un giocatore specifico è garantito da alcuna attrezzatura, metodo o programma qui descritti.",
      governing: "Questa pagina è pubblicata in più lingue. Fa fede la versione inglese; la traduzione è fornita per comodità di lettura.",
    },
  },
  nav: {
    language: "Lingua",
    groups: { racquets: "Racchette", training: "Allenamento", ecosystem: "Ecosistema", partnerships: "Collaborazioni" },
    racquets: "Serie di racchette e confronto",
    great: "GREAT — 97 in² · Controllo",
    power: "POWER — 98 in² · Potenza",
    spin: "SPIN — 100 in² · Rotazione",
    precision: "Precisione e rigidità",
    grip: "Architettura dei manici di fabbrica L0–L7",
    custom: "Progettazione su misura",
    training: "Sistemi di allenamento",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologia",
    gps: "MAXIMUS GPS",
    build: "Configuratore",
    choose: "Aiuto nella scelta",
    ecosystem: "Mappa dell'ecosistema",
    engineering: "Ingegneria e produzione",
    experience: "Esperienza e fitting",
    brands: "Brand personali e ambasciatori",
    families: "Famiglie e genitori",
    owners: "Proprietari e archivio del proprietario",
    network: "Sports Network",
    partnerships: "Tutti i percorsi di collaborazione",
    coaches: "Maestri",
    clubs: "Circoli e accademie",
    distribution: "Distribuzione e sviluppo per Paese",
    strategic: "Strategia e investimenti",
    institutional: "Programmi istituzionali",
    contact: "Contatti",
    legal: "Identità legale",
    privacy: "Informativa sulla privacy",
    terms: "Condizioni d'uso",
    menu: "Menu di navigazione",
    close: "Chiudi",
    home: "Pagina iniziale",
    skip: "Salta al contenuto",
  },
  footer: {
    line: "La racchetta MAXIMUS è la sua chiave per il mondo MAXIMUS.",
    product: "Prodotto",
    ecosystem: "Ecosistema",
    company: "Organizzazione",
    instagram: "Instagram",
    email: "Email",
    analytics: "Impostazioni di analisi",
    subscribe: {
      title: "Resti con MAXIMUS",
      line: "Nuove serie, date di fitting, materiali di allenamento e il programma dei proprietari. Qualche lettera all'anno, nient'altro.",
      label: "Indirizzo email",
      placeholder: "your@email.com",
      button: "Iscriviti",
      sending: "Invio",
      done: "Il suo indirizzo è in elenco. Scriviamo solo quando c'è qualcosa che vale la pena leggere.",
      invalid: "Verifichi l'indirizzo.",
      failed: "L'indirizzo non è stato registrato. Riprovi tra un istante.",
      terms: "Iscrivendosi, acconsente che MAXIMUS le invii questi aggiornamenti e conservi il suo indirizzo a tale scopo. Ogni lettera contiene un collegamento per annullare l'iscrizione.",
    },
    rights: "MAXIMUS® e l'emblema del leone sono marchi dell'ecosistema MAXIMUS. MIPA: proprietà intellettuale interna, provenienza e controllo documentale.",
    boundary:
      "I termini commerciali e contrattuali sono concordati separatamente per iscritto. L'acquisto di una racchetta non crea appartenenza istituzionale, diritti di investimento, titolarità di proprietà intellettuale o diritto a royalty.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "La precisione comincia all'impatto.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer e la metodologia MAXIMUS collegano l'allenamento mirato alle racchette da prestazione interamente in carbonio.",
    heroCta1: "Scopri il sistema di allenamento",
    heroCta2: "Scopri GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Controllo",
    heroMeta: [
      ["Interamente in carbonio", "dal telaio al manico"],
      ["4 parametri", "peso · bilanciamento · swingweight · rigidità"],
      ["8 misure di manico", "geometria di fabbrica L0–L7"],
      ["3 serie", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Inizi da qui",
      title: "Scelga il suo percorso",
      items: {
        player: { h: "Giocatore", p: "Trovi una racchetta per livello e priorità, oppure la configuri direttamente.", a: "Trova la tua racchetta" },
        parent: { h: "Genitore", p: "Un percorso scritto per obiettivi di sviluppo, coinvolgimento del maestro e attrezzatura adeguata.", a: "Percorso famiglia" },
        coach: { h: "Maestro, circolo o accademia", p: "Sistemi di allenamento, fitting, set per squadre e personalizzazione.", a: "Percorsi per maestri e circoli" },
        partner: { h: "Distributore o partner", p: "Percorsi di distribuzione, sviluppo per Paese, strategici e istituzionali.", a: "Percorsi di collaborazione" },
      },
    },
    series: {
      eyebrow: "Serie da prestazione",
      title: "Tre architetture di prestazione. Una piattaforma ingegneristica.",
      lead: "Scelga la serie in base alla direzione di gioco, poi completi la configurazione: classe di precisione, peso, misura del manico, personalizzazione.",
      cta: "Confronta le serie",
      configure: "Configura",
      open: "Apri la serie",
      photoPending: "Fotografia non ancora pubblicata",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Sistema di precisione MAXIMUS",
      title: "Peso. Bilanciamento. Swingweight. Rigidità.",
      sub: "Controllati come un unico sistema ingegneristico.",
      lead: "Tre classi di precisione definiscono con quale tolleranza ogni racchetta finita è tenuta alla specifica dichiarata. P0.5 è una tolleranza ristretta secondo un protocollo di misurazione definito — non errore zero.",
      cta: "Precisione e rigidità in dettaglio",
    },
    stiffness: {
      eyebrow: "Rigidità",
      title: "Risposta del telaio ripetibile rispetto a un obiettivo dichiarato.",
      p: "La rigidità del telaio influenza la risposta, la sensazione e la costanza tra le racchette. MAXIMUS la tratta come il quarto parametro controllato: l'obiettivo, il risultato misurato, la tolleranza ammessa e la capacità dello strumento sono conservati come registrazioni separate. Il vantaggio è la ripetibilità — non un risultato garantito per ogni giocatore.",
      cols: [["Risposta", "Come il telaio restituisce energia all'impatto."], ["Sensazione", "Ciò che il giocatore percepisce all'impatto."], ["Costanza", "Racchette costruite secondo la stessa specifica rispondono allo stesso modo entro la loro classe."]],
      schematicCaption: "Schema: deviazione ammessa attorno a un obiettivo di rigidità dichiarato per ciascuna classe. Non è una misurazione; non è implicato alcun valore RA.",
      bands: { p25: "tolleranza obiettivo ±1 RA", p15: "tolleranza obiettivo ±0,5 RA", p05: "conforme al valore RA obiettivo dichiarato secondo il protocollo di misurazione di fabbrica stabilito — non errore zero", target: "obiettivo dichiarato (nessun valore implicato)" },
    },
    carbon: {
      eyebrow: "Standard di costruzione",
      title: "Interamente in carbonio. Dal telaio al manico.",
      p: "Tutte le racchette MAXIMUS attuali di questa piattaforma sono interamente in carbonio nella loro struttura, manico compreso. La schiuma non è utilizzata per formare il manico.",
      gripTitle: "Otto misure di manico di fabbrica. L0–L7.",
      gripP: "Ogni misura è geometria del manico in carbonio realizzata in fabbrica — non un ingrossamento con overgrip.",
      scaleCaption: "Schema: designazioni nominali dei manici L0–L7 (da 4″ a 4⅞″). Non sono dimensioni misurate del manico.",
      cta: "Architettura dei manici di fabbrica",
    },
    custom: {
      eyebrow: "Progettazione su misura",
      title: "Progettata su specifica.",
      sub: "La gamma standard è il punto di partenza.",
      p: "MAXIMUS accetta requisiti tecnici oltre le matrici pubblicate per valutazione, progettazione, validazione e produzione secondo una specifica concordata. La fattibilità è confermata per iscritto.",
      chain: ["Definire", "Progettare", "Validare", "Specificare", "Produrre", "Misurare / registrare"],
      cta: "Invia un brief tecnico",
      cta2: "Richiedi un confronto sulla progettazione su misura",
    },
    training: {
      eyebrow: "Sistemi di allenamento",
      title: "Un sistema di allenamento costruito attorno all'impatto.",
      p: "Sweet Spot Trainer, la metodologia MAXIMUS e Spot Trainer collegano l'attrezzatura alla pratica guidata dal maestro: impatto centrato, controllo, carico progressivo e ritorno alla racchetta da prestazione.",
      cta: "Sistemi di allenamento",
      cta2: "Richiedi una dimostrazione",
      photoPending: "Fotografia del trainer non ancora pubblicata",
      sstP: "Una testa da allenamento di 50 in² per l'esercizio dell'impatto centrato, con quattro configurazioni di peso per il carico scelto dal maestro.",
      sstCta: "Scopri Sweet Spot Trainer",
      sstCaption: "Configurazione da 300 g, una delle quattro",
      methodP: "Definire gli obiettivi, scegliere l'attrezzatura, allenarsi con il coinvolgimento del maestro, registrare le osservazioni, rivalutare, correggere e trasferire il lavoro al gioco da prestazione.",
      methodCta: "Scopri la metodologia",
      spotP: "Un piccolo bersaglio rotondo per esercitare un punto d'impatto preciso e ripetibile.",
      spotCta: "Scopri Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Produzione e controllo qualità",
      title: "Costruita su specifica. Misurata e registrata.",
      p: "La produzione segue la specifica scritta di ogni ordine. Le registrazioni seguono la classe di precisione: registrazioni di produzione conservate per P2.5, registrazioni individuali e tracciabilità per P1.5, controllo individuale e documentazione per P0.5 dove il programma dell'ordine li prevede.",
      confirmedTitle: "Confermato",
      confirmed: ["Costruzione interamente in carbonio dal telaio al manico.", "Classi di precisione P2.5, P1.5 e P0.5 con quattro parametri controllati.", "Otto misure di manico di fabbrica L0–L7."],
      pendingTitle: "Non ancora pubblicato",
      pending: "Le fotografie degli strumenti di misura, esempi di registrazioni di controllo qualità e le riprese in fabbrica non sono ancora pubblicati. Nulla in questa pagina è un certificato di misurazione.",
      captions: { lettering: "Scritta MAXIMUS lucida sul telaio opaco", buttcap: "Grip e tappo del manico con il marchio del leone", handle: "Incisione argentata di personalizzazione", finish: "Testa e piatto corde" },
      cta: "Ingegneria e produzione",
    },
    world: {
      eyebrow: "Il mondo MAXIMUS",
      title: "Una chiave. Un ecosistema. Opportunità illimitate.",
      note: "«Opportunità illimitate» è un'espressione di marca, non una promessa di fattibilità tecnica, reddito o accesso illimitati. Un acquisto non crea royalty, rendimenti da investimento, sponsorizzazioni o finanziamento dello sviluppo di un giocatore.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — e la sua navigazione nel mondo del tennis: un profilo attrezzatura guidato, con risposta per iscritto." },
        personal: { h: "Personalizzazione", p: "Nomi, iniziali, numeri e identificazione della squadra nel trattamento approvato a incisione argentata." },
        development: { h: "Sviluppo", p: "Sistemi di allenamento guidati dal maestro, registrazioni e rivalutazione." },
        ecosystem: { h: "Ecosistema esteso", p: "Brand personali, registrazioni dei proprietari, network, licenze e programmi istituzionali — ciascuno mostrato con il suo stato effettivo." },
      },
      cta: "Scopri l'ecosistema",
    },
    partners: {
      eyebrow: "Percorsi di collaborazione",
      title: "Maestri, circoli, distributori e partner.",
      p: "Prima la qualificazione scritta. Diritti di Paese, esclusività e condizioni commerciali sono negoziati per iscritto — mai concessi tramite un modulo.",
      cta: "Tutti i percorsi di collaborazione",
      formTitle: "Richiesta breve",
      formLead: "Scelga la finalità e scriva a MAXIMUS. Riceve un ID richiesta su questa pagina.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "LA SUA NAVIGAZIONE NEL MONDO DEL TENNIS" } },
    personal: { eyebrow: "Personalizzazione", title: "Il suo nome. Il suo numero. La sua MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tre serie. Parametri reali." },
    map: { cta: "Scopri l'ecosistema" },
  },
  racquets: {
    title: "Racchette",
    lead: "Tre serie da prestazione che condividono lo standard di costruzione, il sistema di precisione e l'architettura dei manici di fabbrica. Ogni serie è un'architettura di prestazione definita all'interno di una piattaforma ingegneristica più ampia.",
    direction: { control: "Controllo", power: "Potenza", spin: "Rotazione" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Direzione di gioco principale",
    compareTitle: "Confronto delle serie",
    compareLead: "Solo dati di architettura confermati. Schemi corde, lunghezze, profili del telaio, intervalli di tensione e valori nominali di swingweight e rigidità di queste serie non sono pubblicati; sono raccolti come obiettivi richiesti per la revisione tecnica.",
    columns: { series: "Serie", head: "Superficie del piatto", direction: "Direzione", weights: "Pesi elencati", range: "Intervallo di peso", balance: "Dati di bilanciamento" },
    balanceModelled: "Valori calcolati",
    balanceNotProvided: "Non ancora pubblicato",
    construction: "Costruzione: interamente in carbonio, dal telaio al manico · Precisione: P2.5 / P1.5 / P0.5 · Manici: L0–L7",
    otherTitle: "Altri sport con racchetta",
    otherLead: "Direzioni di sviluppo approvate. In queste categorie non esiste alcun prodotto vendibile e nessuna specifica del tennis viene trasferita ad esse.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Beach Tennis" },
    ctaConfigure: "Configura una richiesta",
    ctaSeries: "Apri la serie",
  },
  seriesPage: {
    eyebrow: "Serie da prestazione",
    intro: {
      great: "L'architettura GREAT da 97 in² è costruita attorno al controllo: testa compatta, impatto preciso e sicurezza nelle direzioni.",
      power: "L'architettura POWER da 98 in² è costruita attorno al trasferimento di energia: profondità e velocità di palla da un telaio stabile.",
      spin: "L'architettura SPIN da 100 in² è costruita attorno al comportamento della palla: rotazione, margine e costruzione della traiettoria.",
    },
    photoPending: "Fotografia della serie non ancora pubblicata",
    detailPending: "Le fotografie di dettaglio della costruzione e del manico di questa serie non sono ancora pubblicate.",
    specsTitle: "Specifica e stato",
    catalogue: {
      eyebrow: "Catalogo della serie {series}",
      title: "{n} varianti di peso",
      lead: "Ogni variante della serie {series}, ordinata per peso. Peso in grammi, bilanciamento in millimetri dal fondo del manico. Ogni visualizzazione è mostrata integra: nulla è tagliato, mascherato o deformato.",
      selectLabel: "Scelga una variante di peso",
      select: "Mostra questa variante",
      selected: "Mostrata sopra",
      balanceLabel: "Bilanciamento",
      headLabel: "Superficie del piatto",
      constructionLabel: "Costruzione",
      gripsLabel: "Misure di manico di fabbrica",
      precisionLabel: "Classi di precisione",
      balanceConfirmed: "Il bilanciamento è il valore confermato per questo peso e corrisponde alla cifra stampata sulla visualizzazione. Prezzi, disponibilità e tempi di consegna non sono pubblicati qui.",
      balanceModelled: "Il bilanciamento è un valore calcolato per questo peso elencato, non una misurazione individuale di fabbrica; corrisponde alla cifra stampata sulla visualizzazione. Prezzi, disponibilità e tempi di consegna non sono pubblicati qui.",
      zoom: "Apri l'immagine",
      close: "Chiudi",
      allTitle: "Tutte le {n} varianti",
    },
    specs: { head: "Superficie del piatto", direction: "Direzione principale", weights: "Pesi elencati", range: "Intervallo di peso", balance: "Bilanciamento", construction: "Costruzione", grips: "Manici di fabbrica", precision: "Classi di precisione" },
    construction: "Interamente in carbonio, dal telaio al manico",
    statusTitle: "Stato dei valori",
    matrixTitle: "Matrice completa dei pesi",
    matrixLead: "I pesi elencati sono la selezione standard. Altri pesi possono essere richiesti come obiettivi personalizzati; i valori intermedi mancanti non vengono inseriti.",
    balanceNote: {
      confirmed: "I valori di bilanciamento sono confermati per ogni peso elencato (mm dal fondo del manico) e corrispondono alla cifra stampata sulla visualizzazione di quel peso. Non sono calcolati qui e non sono livellati tra pesi vicini; la base di misurazione è confermata nella specifica scritta.",
      modelled: "I valori di bilanciamento sono calcolati per ogni peso elencato (mm dal fondo del manico). Non sono misurazioni individuali di fabbrica; la base di misurazione è confermata nella specifica scritta.",
      notprovided: "I valori di bilanciamento di questa serie non sono forniti. Non li deduca da un'altra serie.",
    },
    optionsTitle: "Precisione, manico e peso",
    notPublished: "Non pubblicati per questa serie: schema corde, lunghezza, profilo del telaio, intervallo di tensione e valori di swingweight e rigidità. Può indicarli come obiettivi richiesti per la revisione tecnica.",
    offerTitle: "Che cosa accade dopo la sua richiesta",
    offerSteps: [
      ["Richiesta", "Invii una configurazione o una domanda. Un ID richiesta è mostrato immediatamente."],
      ["Revisione", "MAXIMUS esamina serie, classe, peso, manico e gli eventuali obiettivi richiesti."],
      ["Risposta scritta", "Specifica, disponibilità e condizioni commerciali sono confermate per iscritto."],
    ],
    faqTitle: "Domande",
    faq: [
      ["I valori di bilanciamento sono misurati?", "Sono calcolati per i pesi elencati, non sono misurazioni individuali. La base di misurazione è confermata nella specifica scritta."],
      ["Posso richiedere un peso non elencato?", "Sì, come obiettivo personalizzato in grammi interi. Viene esaminato tecnicamente e la fattibilità è confermata per iscritto."],
      ["Che cosa cambia la classe di precisione?", "Con quale tolleranza peso, bilanciamento, swingweight e rigidità sono tenuti alla specifica dichiarata, e quali registrazioni vengono conservate."],
      ["Il manico è ingrossato con overgrip?", "No. L0–L7 sono geometrie del manico in carbonio realizzate in fabbrica."],
      ["Dove sono prezzi e tempi di consegna?", "Sono confermati per iscritto per ogni richiesta e non sono pubblicati qui."],
    ],
    faqSpinBalance: ["Da dove provengono i valori di bilanciamento SPIN?", "Dalla tabella confermata della serie Spin: 33 varianti di peso con bilanciamento in millimetri dal fondo del manico. Ogni coppia corrisponde alla cifra stampata sulla visualizzazione approvata di quel peso. I valori non sono calcolati e non sono livellati tra pesi vicini."],
    ctaBuild: "Configura questa serie",
    ctaAsk: "Fai una domanda su questa serie",
    ctaCompare: "Confronta tutte le serie",
    weightsLabel: "pesi elencati",
    headLabel: "testa",
  },
  precision: {
    title: "Precisione e rigidità",
    switch: { label: "Scelga una classe di precisione", panelLabel: "Quattro parametri controllati —", qcLabel: "Architettura del controllo qualità", protocolNote: "secondo il protocollo di misurazione definito per il controllo qualità in fabbrica", fullTable: "Tabella di confronto completa" },
    lead: "Quattro parametri controllati come un unico sistema ingegneristico. Ogni classe definisce con quale tolleranza una racchetta finita è tenuta alla specifica dichiarata e quali registrazioni di qualità vengono prodotte.",
    statement: "Peso. Bilanciamento. Swingweight. Rigidità. Controllati come un unico sistema ingegneristico.",
    classes: {
      "P2.5": { name: "Nucleo prestazionale scalabile", qc: "Misurazione individuale e registrazioni di produzione conservate." },
      "P1.5": { name: "Precisione avanzata", qc: "Misurazione individuale, registrazioni individuali e tracciabilità." },
      "P0.5": { name: "Professionale · controllata individualmente", qc: "Controllo individuale con valori nominali ed effettivi e registrazioni di misurazione individuali; identità seriale, tracciabilità di lotto, un certificato di precisione e set abbinati dove il programma dell'ordine li prevede." },
    },
    columns: { cls: "Classe", weight: "Peso", balance: "Bilanciamento", sw: "Swingweight", stiff: "Rigidità", qc: "Architettura del controllo qualità" },
    stiffTarget: "tolleranza obiettivo",
    stiffExact: "conforme al valore RA obiettivo dichiarato secondo il protocollo di misurazione di fabbrica stabilito",
    programmeNote: "Identità seriale, certificati e documentazione dei set abbinati sono emessi solo dove il programma di un ordine specifico li prevede.",
    targetsNote: "Le specifiche di rigidità sono obiettivi di produzione fino a quando il protocollo pertinente e le prove di produzione non sostengano un'affermazione più forte. La proposta di architettura non implica che ogni configurazione elencata abbia già superato un processo completo di rilascio a quattro parametri.",
    stiffnessTitle: "Perché la rigidità conta",
    stiffnessP1: "La rigidità del telaio influenza il modo in cui il telaio risponde all'impatto, come viene percepito e quanto due racchette sono coerenti tra loro. Il vantaggio centrale del suo controllo è una risposta ripetibile rispetto a una specifica dichiarata.",
    stiffnessP2: "Prima che sia pubblicata una conformità verificata, la registrazione interna di controllo qualità identifica lo strumento, il suo stato di calibrazione, il metodo, le condizioni della racchetta, la risoluzione, l'incertezza di misura, le misurazioni ripetute, la regola di arrotondamento e la regola di accettazione. Un numero intero visualizzato identico non è prova di variazione fisica nulla o di errore di misura nullo.",
    fields: ["Obiettivo", "Risultato misurato", "Tolleranza ammessa", "Capacità dello strumento"],
    fieldsNote: "Conservati come campi separati in ogni registrazione.",
    matchedTitle: "Set abbinati",
    matchedP: "I criteri dei set abbinati sono definiti separatamente dalla tolleranza individuale. La conformità di ogni racchetta alla sua tolleranza nominale non dimostra da sola una determinata differenza massima tra due racchette. Coppie, terzetti e set per squadre abbinati sono richiesti attraverso il configuratore e confermati per iscritto.",
    extendedTitle: "Modello tecnico esteso",
    extendedP: "Il modello dati supporta parametri aggiuntivi. Per essi non esistono ancora valori né classi di tolleranza; possono essere indicati come obiettivi richiesti in un brief tecnico.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Comportamento torsionale", length: "Lunghezza", beamProfile: "Profilo del telaio", headGeometry: "Geometria della testa", stringPattern: "Schema corde", durability: "Durabilità", vibration: "Caratteristiche di vibrazione" },
    noZero: "MAXIMUS non descrive la sua gamma elencata come priva di tolleranza. Nella gamma la precisione è indicata come classe, con una tolleranza dichiarata e un'architettura di controllo qualità definita. ZERO non fa parte della gamma.",
    zero: {
      eyebrow: "Opzione esclusiva",
      title: "ZERO",
      sub: "Tolleranza zero al grammo.",
      p: "Le tre classi tengono una racchetta finita all'interno di una banda dichiarata. ZERO elimina la banda. La racchetta è costruita e misurata fino a quando la lettura è uguale al valore dichiarato alla risoluzione dello strumento di misura di fabbrica, e quella lettura è consegnata con essa. Non fa parte della gamma elencata e non è una quarta classe: è concordata individualmente, per una racchetta o un set abbinato, come un'esclusiva su misura. Previo accordo, lo stesso approccio è applicato al bilanciamento e allo swingweight.",
      points: [
        ["Nessuna banda", "Il valore dichiarato è il risultato, non il centro di una tolleranza."],
        ["Una alla volta", "Costruita, misurata e registrata come unità singola."],
        ["Consegnata con la racchetta", "La lettura misurata è consegnata e conservata nella registrazione di produzione."],
        ["Conferma per iscritto", "Parametri, ambito e tempi di consegna sono concordati prima della produzione."],
      ],
      note: "La corrispondenza è stabilita alla risoluzione dello strumento di misura di fabbrica. Un valore visualizzato identico non è un'affermazione di variazione fisica nulla. Disponibilità e condizioni sono concordate individualmente per ogni ordine.",
      cta: "Richiedi ZERO",
    },
    cta: "Configura con una classe di precisione",
  },
  grip: {
    title: "Architettura dei manici di fabbrica",
    statement: "Otto misure di manico di fabbrica. L0–L7.",
    lead: "La geometria del grip fa parte dell'architettura del manico in carbonio. Ogni misura è prodotta come geometria del manico, non ingrossata con overgrip.",
    emph: "Misure estese",
    p1: "La gamma di fabbrica a otto misure offre a maestri e giocatori un intervallo di configurazione più ampio, con cui l'attrezzatura può essere specificata attorno al giocatore, comprese le geometrie più grandi L6 e L7.",
    p2: "La designazione nominale del manico è distinta dalle dimensioni strutturali grezze del manico e dal protocollo di misurazione finale. Le misure si applicano alle serie da prestazione e alle famiglie da allenamento di questa piattaforma.",
    p3: "Per questa gamma non è rivendicata alcuna esclusività mondiale.",
    columns: { size: "Misura", nominal: "Nominale", family: "Si applica a" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Configura con la tua misura di manico",
  },
  custom: {
    title: "Progettazione su misura",
    statement: "Progettata su specifica.",
    sub: "La gamma standard è il punto di partenza.",
    lead: "MAXIMUS accetta requisiti tecnici oltre le matrici di configurazione pubblicate per valutazione, progettazione, validazione e produzione secondo una specifica concordata. La fattibilità è confermata mediante revisione — non ogni richiesta concepibile è fisicamente o commercialmente realizzabile.",
    scopeTitle: "Che cosa può riguardare un brief tecnico",
    scope: ["Geometria della testa e del telaio", "Lunghezza", "Peso", "Bilanciamento", "Swingweight", "Rigidità", "Twistweight", "Geometria del manico", "Costruzione", "Set abbinati", "Telai da allenamento", "Grafica e incisione", "Identità e programmi per squadre", "Sviluppo dipendente dall'attrezzaggio"],
    processTitle: "Processo",
    process: [
      ["Definire", "Obiettivi preferiti, limiti obbligatori, uso previsto e compromessi accettabili."],
      ["Progettare", "Valutazione ingegneristica rispetto alla piattaforma e all'attrezzaggio."],
      ["Validare", "Validazione rispetto alla specifica concordata."],
      ["Specificare", "Una specifica scritta con base di misurazione e tolleranze."],
      ["Produrre", "Produzione secondo la specifica."],
      ["Misurare / registrare", "Misurazione e registrazioni conservate secondo la classe di precisione applicabile."],
    ],
    formTitle: "Invia un brief tecnico",
    formLead: "Distingua gli obiettivi preferiti dai limiti obbligatori. Il risultato è una richiesta di revisione tecnica, non un ordine di produzione accettato automaticamente.",
    protected: "Ricette di laminazione, attrezzaggio, identità dei fornitori, costi interni e know-how protetto non sono divulgati attraverso questo percorso.",
    cta: "Invia un brief tecnico",
  },
  training: {
    title: "Sistemi di allenamento",
    lead: "Due famiglie da allenamento con i propri standard di produzione, collegate da una sola metodologia: pratica guidata dal maestro, registrazioni, rivalutazione e ritorno al gioco da prestazione.",
    sst: { h: "Sweet Spot Trainer", p: "Una racchetta da allenamento a testa ridotta di 50 in² in un sistema a quattro pesi, per l'esercizio dell'impatto centrato, la consapevolezza dello sweet spot, il controllo della racchetta e il carico progressivo." },
    spot: { h: "Spot Trainer", p: "Allenamento del punto d'impatto con un piccolo bersaglio rotondo di contatto, sulla base approvata a quattro pesi." },
    method: { h: "Metodologia", p: "Stabilire gli obiettivi, scegliere l'attrezzatura con il coinvolgimento del maestro, usare il sistema pertinente, registrare, rivalutare, correggere e trasferire." },
    experience: "La impugni. Faccia uno swing. La senta.",
    experienceP: "Richieda una prova, un fitting o una dimostrazione con il supporto del maestro. Una richiesta inviata non è un appuntamento confermato.",
    cta: "Richiedi un fitting o una dimostrazione",
    distinct: "Sweet Spot Trainer, Spot Trainer e qualsiasi dispositivo dimostrativo separato sono prodotti distinti e non vengono mai uniti.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Una categoria di allenamento separata, con un proprio standard di produzione. La testa da 50 in² concentra l'attenzione sul punto d'impatto; i quattro pesi forniscono la progressione di carico.",
    baseline: "Base confermata",
    columns: { head: "Testa", length: "Lunghezza", pattern: "Schema corde", grips: "Manici di fabbrica" },
    systemTitle: "Sistema a quattro racchette",
    detailsTitle: "Dettagli di costruzione",
    systemLead: "Peso e bilanciamento come forniti. La base di misurazione è registrata separatamente e non è ancora pubblicata.",
    purposeTitle: "Finalità",
    purpose: ["Esercizio dell'impatto centrato", "Consapevolezza dello sweet spot", "Controllo della racchetta", "Carico progressivo", "Sviluppo guidato dal maestro", "Ritorno alla racchetta da prestazione del giocatore"],
    heavy: "Il modello da 400 g è una configurazione di allenamento controllata. Non è raccomandato automaticamente a bambini, principianti o a ogni giocatore; il maestro definisce carico, durata e progressione.",
    precisionNote: "Le classi di precisione da prestazione P2.5, P1.5 e P0.5 non si applicano automaticamente a questa famiglia da allenamento. Le tolleranze di produzione da allenamento seguono la specifica approvata propria della famiglia.",
    health: "Non è promessa alcuna prevenzione o cura del gomito del tennista, eliminazione degli infortuni o miglioramento garantito.",
    cta: "Richiedi una dimostrazione di Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Allenamento del punto d'impatto con un piccolo bersaglio rotondo di contatto. Un prodotto distinto con una propria identità visiva, costruito sulla base approvata a quattro pesi.",
    purposeTitle: "Finalità confermata",
    purposeP: "Allenare il giocatore a trovare e ripetere un punto d'impatto preciso.",
    weightsTitle: "Progressione dei pesi",
    weightsP: "La progressione dei pesi segue la base di pesi approvata di Sweet Spot Trainer. I valori di bilanciamento e le altre specifiche di Sweet Spot Trainer non sono trasferiti a Spot Trainer.",
    dims: "Le dimensioni esatte del bersaglio non sono ancora pubblicate.",
    grips: "Architettura dei manici di fabbrica L0–L7.",
    notes: ["Le classi di precisione da prestazione non si applicano automaticamente.", "Non è una racchetta convenzionale in miniatura e non è pubblicato alcuno schema corde.", "Spot Trainer, Sweet Spot Trainer e qualsiasi dispositivo dimostrativo separato restano distinguibili."],
    cta: "Fai una domanda su Spot Trainer",
  },
  methodology: {
    title: "Metodologia ed esperienza di prodotto",
    lead: "L'attrezzatura è una parte di un percorso di sviluppo strutturato. Il metodo parte dagli obiettivi del giocatore, non da un'etichetta di prodotto.",
    stepsTitle: "Il percorso di sviluppo",
    steps: [
      ["Stabilire gli obiettivi", "Gli obiettivi del giocatore e il suo punto di partenza."],
      ["Scegliere l'attrezzatura", "Attrezzatura adeguata, scelta con il coinvolgimento del maestro."],
      ["Usare il sistema", "Il sistema di allenamento pertinente, guidato dal maestro."],
      ["Registrare", "Osservazioni della partecipazione effettiva, senza punteggi inventati."],
      ["Rivalutare", "Punti di verifica comparabili."],
      ["Correggere", "Aggiustamenti di configurazione o di programma."],
      ["Trasferire", "Apprendimento trasferito al gioco da prestazione."],
    ],
    educationTitle: "Percorsi formativi",
    education: { player: "Giocatori — comprendere configurazione, carico e progressione.", parent: "Genitori — continuità dello sviluppo, attrezzatura adeguata, registrazioni e diritti.", coach: "Maestri — sistemi di allenamento, fitting, valutazione e uso autorizzato dei programmi." },
    evidenceTitle: "Disciplina delle prove",
    evidenceP: "Le registrazioni della partecipazione effettiva e le osservazioni sono conservate con la loro classificazione — dichiarata dal partecipante, confermata dal tutore, validata dal maestro o misurata dal sistema. Progressi, punteggi e validazioni non vengono mai inventati.",
    experienceTitle: "La impugni. Faccia uno swing. La senta.",
    experienceP: "È possibile richiedere una prova, un fitting o una dimostrazione con il supporto del maestro. Una richiesta inviata non è un appuntamento confermato.",
    cta: "Richiedi fitting o dimostrazione",
    cta2: "Richiesta di collaborazione per maestri",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — profilo attrezzatura guidato",
    title: "MAXIMUS GPS",
    lead: "Un profilo attrezzatura guidato. Risponda solo a ciò che è pertinente; verifichi e corregga le sue risposte; riceve un riepilogo, le direzioni di configurazione applicabili e un'azione successiva concreta.",
    honesty: "In questa versione non è approvata alcuna regola di fitting automatico. GPS produce quindi un riepilogo chiaro dei requisiti e indica direzioni di configurazione; i dettagli dell'attrezzatura sono inoltrati alla revisione di un esperto.",
    rulesVersion: "Versione delle regole",
    dataVersion: "Versione dei dati di prodotto",
    steps: { role: "Ruolo", sport: "Disciplina", experience: "Esperienza", objectives: "Obiettivi", style: "Stile di gioco", equipment: "Attrezzatura attuale", preference: "Preferenze", coach: "Coinvolgimento del maestro", ageBand: "Fascia d'età", review: "Riepilogo" },
    notStored: "Non conservato in questo browser.",
    ageNote: "Utilizzata solo per indirizzare la richiesta. Non sono richiesti nome, data di nascita o informazioni sanitarie.",
    q: {
      role: "Quale descrizione le corrisponde?",
      sport: "Quale sport?",
      experience: "Livello di esperienza",
      objectives: "Che cosa conta di più? (selezioni fino a tre)",
      style: "Stile di gioco, se noto",
      equipment: "Attrezzatura attuale, se presente",
      equipmentHint: "Marca e modello, peso o misura del manico se li conosce. Facoltativo.",
      preference: "Configurazione preferita o misura del manico nota",
      grip: "Misura del manico nota",
      coach: "Un maestro è coinvolto nelle sue decisioni sull'attrezzatura?",
      ageBand: "Fascia d'età del giocatore (usata solo per indirizzare correttamente la richiesta)",
    },
    roles: { player: "Giocatore", parent: "Genitore o tutore", coach: "Maestro", club: "Circolo o accademia", other: "Altro" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Altro sport con racchetta" },
    sportNote: "I prodotti esistono per il tennis. Gli altri sport sono direzioni di sviluppo; il suo interesse è registrato per il programma pertinente.",
    experience: { beginner: "Principiante", developing: "In crescita", intermediate: "Intermedio", advanced: "Avanzato", competitive: "Agonista", professional: "Professionista" },
    objectives: { control: "Controllo", power: "Potenza", spin: "Rotazione", comfort: "Comfort", manoeuvrability: "Manovrabilità", development: "Sviluppo a lungo termine", competition: "Competizione", training: "Sistema di allenamento", team: "Squadra o set abbinato", personal: "Personalizzazione" },
    styles: { baseline: "Da fondo campo", allcourt: "Gioco a tutto campo", attacking: "Offensivo", defensive: "Difensivo", coach: "Scelto dal maestro", unknown: "Non so" },
    ageBands: { u10: "Meno di 10 anni", u14: "10–13", u18: "14–17", adult: "18 anni e oltre" },
    output: {
      title: "Il suo profilo attrezzatura",
      status: "Necessaria la revisione di un esperto",
      statusP: "In questa versione non viene prodotto alcun abbinamento automatico. Il suo profilo è stato riassunto per la revisione di un esperto.",
      directionsTitle: "Direzioni di configurazione applicabili",
      directionsP: "In base agli obiettivi che ha indicato e alla direzione di gioco dichiarata di ogni serie. È una direzione, non una raccomandazione di fitting.",
      trainingHint: "I suoi obiettivi comprendono un sistema di allenamento: veda Sweet Spot Trainer e Spot Trainer.",
      teamHint: "I set abbinati sono richiesti attraverso il configuratore e confermati per iscritto.",
      next1: "Invia il profilo per la revisione di un esperto",
      show: "Mostra il mio profilo",
      configure: "Configura",
      sendP: "Invii il suo profilo a MAXIMUS per la revisione di un esperto. Un ID richiesta è mostrato immediatamente; la risposta arriva per iscritto.",
      otherSport: "Le racchette MAXIMUS esistono per il tennis. Per gli altri sport con racchetta non viene suggerita alcuna serie da tennis; il suo interesse è registrato come direzione di sviluppo.",
      noDirection: "I suoi obiettivi non indicano una sola direzione di gioco. La revisione di un esperto propone una configurazione.",
      incomplete: "Mancano alcune risposte obbligatorie — usi «Modifica risposte» per completarle.",
    },
    privacy: "GPS non chiede informazioni sanitarie né identificativi di minori. In questa sessione del browser sono conservate solo le risposte a scelta multipla; il testo libero non è conservato.",
  },
  build: {
    title: "Configura la tua racchetta",
    lead: "Configuri una richiesta: serie, classe di precisione, peso elencato o obiettivo personalizzato, misura del manico, obiettivi richiesti, personalizzazione, set abbinati e quantità. Il risultato è una richiesta di configurazione con un ID richiesta — non un codice articolo, un prezzo, una data di consegna o un certificato.",
    steps: { series: "Serie", cls: "Classe di precisione", weight: "Peso", grip: "Manico", targets: "Obiettivi", personal: "Personalizzazione", set: "Set e quantità", use: "Uso", review: "Riepilogo" },
    q: {
      series: "Scelga una serie",
      cls: "Scelga una classe di precisione",
      weightMode: "Peso",
      listed: "Peso elencato",
      customWeight: "Peso richiesto (g)",
      balanceShown: "Bilanciamento calcolato per questo peso",
      balanceRequest: "Bilanciamento richiesto (mm)",
      grip: "Misura del manico di fabbrica",
      targetsTitle: "Obiettivi richiesti",
      swingweight: "Swingweight richiesto (kg·cm²)",
      stiffness: "Rigidità richiesta (RA)",
      basis: "Base di misurazione dei valori richiesti",
      engraving: "Testo dell'incisione",
      engravingHint: "Nome, iniziali o numero. Lettere latine, cifre, spazio, trattino, apostrofo e punto; fino a 24 caratteri. Altri sistemi di scrittura sono accettati per la conferma della grafica.",
      engravingType: "Personalizzazione",
      types: { none: "Nessuna", name: "Nome del giocatore", initials: "Iniziali", number: "Numero del set", academy: "Identificazione del maestro o dell'accademia", team: "Programma per squadre" },
      set: "Racchetta singola o set abbinato",
      use: "Uso previsto",
      uses: { play: "Gioco personale", competition: "Competizione", coaching: "Insegnamento", team: "Squadra o accademia", retail: "Valutazione per vendita al dettaglio o distribuzione", other: "Altro" },
      notes: "Requisiti tecnici aggiuntivi",
    },
    classes: { "P2.5": "P2.5 — nucleo prestazionale scalabile", "P1.5": "P1.5 — precisione avanzata", "P0.5": "P0.5 — professionale, controllata individualmente" },
    stiffExactShort: "la rigidità è conforme al valore RA obiettivo dichiarato secondo il protocollo di fabbrica stabilito",
    clsNote: "Ogni classe controlla quattro parametri. P0.5 è una tolleranza ristretta secondo un protocollo di misurazione definito — non errore zero. Identità seriale, certificati e documentazione dei set abbinati si applicano solo dove il programma del suo ordine li prevede.",
    listedNote: "Dalla matrice confermata della serie.",
    customNote: "Un peso fuori dalla matrice, esaminato tecnicamente.",
    balanceCaption: "Ogni peso elencato mostra il proprio bilanciamento calcolato in mm dal fondo del manico. I valori calcolati non sono misurazioni individuali.",
    spinNote: "I pesi SPIN formano l'architettura di peso richiesta. Bilanciamento, swingweight e rigidità per SPIN non sono forniti; sono definiti nella revisione tecnica.",
    customHint: "Grammi interi, solo cifre. Un peso personalizzato è una richiesta di revisione tecnica; la fattibilità è confermata per iscritto e nessun valore viene arrotondato.",
    gripNote: "geometria del manico in carbonio realizzata in fabbrica, non un ingrossamento con overgrip",
    targetsLead: "Facoltativo. Inserisca solo i valori che le servono. Ciascuno è registrato come obiettivo richiesto per la revisione tecnica, non come specifica pubblicata.",
    basisHint: "Obbligatorio quando richiede un peso personalizzato o un qualsiasi obiettivo: i valori si riferiscono a una racchetta senza corde o incordata?",
    inputRange: "Valori accettati: {min}–{max}.",
    inputRangeNote: "Gli intervalli di inserimento escludono soltanto i valori impossibili. Non descrivono la capacità produttiva.",
    listedBasis: "valori elencati — base di misurazione confermata nella specifica scritta",
    notStored: "Non conservato in questo browser; lo inserisca di nuovo se ricarica la pagina.",
    artworkReview: "è richiesta la conferma della grafica",
    previewNote: "Non viene mostrata alcuna anteprima visiva: un modello di incisione approvato per questo modello non è ancora pubblicato. Il suo testo è raccolto per la conferma della grafica.",
    teamSub: "4–99 racchette per set",
    setsLabel: { individual: "Numero di racchette", pair: "Numero di coppie abbinate", triple: "Numero di terzetti abbinati", team: "Numero di set per squadra" },
    teamSizeLabel: "Racchette per set di squadra",
    totalLabel: "Racchette in totale",
    racquetsUnit: "racchette",
    setRule: "La quantità conta i set: una coppia abbinata è 2 racchette per set, un terzetto abbinato 3.",
    restart: "Avvia una nuova configurazione",
    notices: { weightCleared: "{w} g non è nella matrice {series}, quindi il peso è stato azzerato. Scelga un peso elencato oppure richieda un obiettivo personalizzato." },
    reviewTitle: "Richiesta di configurazione",
    reviewP: "Verifichi la configurazione, poi aggiunga i suoi dati di contatto. La richiesta è registrata con un ID richiesta e riceve risposta per iscritto; disponibilità e condizioni commerciali sono confermate per iscritto.",
    reviewErrors: "Alcune risposte della configurazione richiedono attenzione:",
    edit: "Modifica",
    fieldNames: { series: "Serie", cls: "Classe di precisione", mode: "Scelta del peso", weight: "Peso elencato", customWeight: "Peso richiesto", basis: "Base di misurazione", balanceReq: "Bilanciamento richiesto", sw: "Swingweight richiesto", ra: "Rigidità richiesta", grip: "Misura del manico", ptype: "Personalizzazione", engraving: "Testo dell'incisione", setType: "Tipo di set", sets: "Quantità", teamSize: "Racchette per set di squadra", use: "Uso previsto", notes: "Requisiti aggiuntivi" },
    status: { listed: "peso elencato", requestedArchitecture: "architettura di peso richiesta", technicalReview: "richiesta di revisione tecnica", notPublished: "non fornito", requestedCondition: "condizione richiesta" },
    chooseLink: "Non sai quale serie fa per te? Chiedi aiuto nella scelta",
    cta: "Invia la richiesta di configurazione",
  },
  experience: {
    title: "Esperienza e fitting",
    statement: "La impugni. Faccia uno swing. La senta.",
    lead: "Richieda una prova, un fitting o una dimostrazione con il supporto del maestro. Le richieste sono esaminate e ricevono risposta per iscritto; una richiesta inviata non è un appuntamento confermato.",
    optionsTitle: "Che cosa si può richiedere",
    options: ["Prova racchetta", "Sessione di fitting", "Dimostrazione con il supporto del maestro", "Dimostrazione di Sweet Spot Trainer o Spot Trainer", "Giornata dimostrativa per squadre o accademie"],
    formTitle: "Richiesta di fitting o dimostrazione",
  },
  engineering: {
    title: "Ingegneria e produzione",
    statement: "Aerei. Yacht. Racchette.",
    lead: "Una sola filosofia ingegneristica in tre ambienti: i principi che danno forma a un aereo, la precisione che guida uno yacht in mare aperto, la prestazione che definisce ogni racchetta MAXIMUS. È una narrazione ingegneristica — non un'affermazione di certificazione aeronautica, di proprietà di yacht, di proprietà di uno stabilimento o di trasferimento diretto di materiali.",
    manifesto: ["Crediamo che la grande ingegneria non abbia confini.", "Una sola filosofia. Progettata senza compromessi."],
    capabilityTitle: "Capacità produttiva",
    capabilityLead: "La capacità è mostrata come una sequenza, non come uno slogan.",
    sequence: [
      ["Specifica", "Serie, classe di precisione, peso, bilanciamento, swingweight, obiettivo di rigidità, geometria del manico, personalizzazione."],
      ["Produzione", "Costruzione interamente in carbonio dal telaio al manico, realizzata secondo la specifica."],
      ["Controllo qualità", "Misurazione e registrazioni secondo la classe di precisione: registrazioni di produzione, registrazioni individuali e tracciabilità, certificazione individuale."],
      ["Produzione ripetuta", "Risposta ripetibile rispetto a una specifica dichiarata, tra i lotti."],
      ["Tracciabilità", "Identità seriale, tracciabilità di lotto e un Certificato di Precisione dove la classe lo prevede."],
    ],
    capacityNote: "Capacità produttiva, tempi di consegna, quantità minime e programmi di consegna sono confermati per iscritto per ciascun programma, rispetto a ordini confermati e a un calendario di rilascio concordato.",
    truth: "La capacità non è produzione realizzata, giacenza, una data di consegna garantita o la proprietà di uno stabilimento produttivo.",
    cta: "Distribuzione e sviluppo per Paese",
    cta2: "Invia un brief tecnico",
  },
  ecosystem: {
    title: "L'ecosistema MAXIMUS",
    lead: "Una chiave. Questo è ciò che apre. Ogni nodo ha una spiegazione, uno stato accurato e un'azione successiva pertinente.",
    words: ["Ingegneria", "Prestazione", "Innovazione", "Comunità", "Opportunità", "Scopo"],
    nodes: {
      engineering: { h: "Ingegneria e produzione delle racchette", p: "Racchette interamente in carbonio progettate su specifica, prodotte con registrazioni di qualità e tracciabilità.", a: "Ingegneria e produzione" },
      precision: { h: "Precisione e configurazione individuale", p: "Quattro parametri, tre classi di precisione, otto misure di manico e progettazione su misura.", a: "Precisione e rigidità" },
      training: { h: "Allenamento e metodologia", p: "Sweet Spot Trainer, Spot Trainer e un percorso di sviluppo strutturato.", a: "Sistemi di allenamento" },
      development: { h: "Sviluppo del giocatore e del maestro", p: "Scelta guidata dal maestro, registrazioni, rivalutazione e percorsi formativi.", a: "Metodologia" },
      identity: { h: "Identità personale e brand personali", p: "Dall'incisione a un brand personale o professionale regolato da diritti.", a: "Brand personali" },
      owners: { h: "Registrazioni, conoscenza e diritti del proprietario", p: "Un archivio del proprietario ad accesso autorizzato, proposto per registrazioni di attrezzatura, sviluppo e diritti.", a: "Proprietari e archivio" },
      mipa: { h: "Provenienza e controllo interno MIPA", p: "Il livello interno di proprietà intellettuale, provenienza e controllo documentale.", a: "Identità legale e controllo" },
      digital: { h: "Infrastruttura digitale e direzione Blockchain 5.0", p: "Provenienza, registrazioni tracciabili, prove ad accesso autorizzato e identità di prodotto come direzione tecnologica dichiarata.", a: "Direzione tecnologica" },
      licensing: { h: "Licenze contrattuali e programmi di royalty", p: "Brand, prodotti e pacchetti di diritti in licenza, con condizioni definite per ciascun accordo.", a: "Percorsi di licenza" },
      families: { h: "Partecipazione delle famiglie e vantaggi dei programmi", p: "Decisioni informate, continuità, registrazioni conservate e vantaggi definiti dal programma.", a: "Famiglie e genitori" },
      network: { h: "MAXIMUS Sports Network", p: "Giocatori, maestri, circoli, accademie, fornitori di servizi, operatori e partner regionali.", a: "Sports Network" },
      market: { h: "Circoli, accademie, distribuzione e sviluppo per Paese", p: "Programmi per squadre, vendita al dettaglio, distribuzione e sviluppo del territorio attraverso qualificazione scritta.", a: "Percorsi di collaborazione" },
      institutional: { h: "Programmi istituzionali, formazione, innovazione e impatto sociale", p: "Il livello istituzionale fornito da MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) dove un programma stabilisce tale ruolo.", a: "Programmi istituzionali" },
      extensions: { h: "Future estensioni agli sport con racchetta e all'abbigliamento MAXIMUS", p: "Padel, pickleball, squash, badminton, racquetball, beach tennis e abbigliamento come direzioni di sviluppo.", a: "Sport con racchetta" },
    },
    boundaryTitle: "Limiti",
    boundary: [
      "L'acquisto di una racchetta non crea appartenenza istituzionale, diritti di governance, royalty o diritti di investimento.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) è l'operatore istituzionale solo dove un programma stabilisce tale ruolo; le vendite di attrezzatura indicano la loro effettiva entità contrattuale.",
      "Contributi, status di ente non profit, trattamento fiscale e autorizzazioni regolamentari non si applicano automaticamente in tutti i Paesi.",
    ],
    techTitle: "Direzione tecnologica",
    techP: "Blockchain 5.0 è la direzione tecnologica dichiarata di MAXIMUS. Le sue finalità funzionali sono provenienza, registrazioni tracciabili, prove ad accesso autorizzato, identità di prodotto e riconciliazione degli eventi commerciali qualificanti. Non viene rappresentato alcun meccanismo di consenso, capacità transazionale, rete di nodi, indirizzo di smart contract, token o certificazione indipendente, e non si dichiara alcuna implementazione in esercizio. Informazioni personali, registrazioni di minori e accordi riservati non sono mai inseriti per impostazione predefinita in un sistema pubblico immutabile.",
  },
  brands: {
    title: "Brand personali e ambasciatori",
    statement: "Dal giocatore al brand. Dal maestro al brand.",
    lead: "Un percorso dedicato al brand personale. Il coinvolgimento di MAXIMUS comprende lo sviluppo del brand e la promozione concordata — non soltanto un nome su una racchetta.",
    progressionTitle: "Progressione prevista",
    progression: [
      ["Identità verificata", "Un'identità verificata e una storia di sviluppo."],
      ["Brand distintivo", "Un brand personale o professionale distintivo."],
      ["Contenuti con diritti liberati", "Contenuti con diritti liberati e identità di prodotto approvata."],
      ["Ingegneria e collezioni", "Ingegneria e sviluppo di collezioni dove concordato."],
      ["Promozione", "Promozione attraverso canali e collaborazioni MAXIMUS concordati."],
      ["Partecipazione", "Partecipazione contrattuale a vendite o licenze qualificanti."],
      ["Rendicontazione", "Rendicontazione trasparente secondo l'accordo."],
    ],
    royaltiesTitle: "Royalty e licenze",
    royalties: [
      "Le royalty sono collegate al brand, prodotto, operazione o pacchetto di diritti in licenza definito.",
      "«Vendite mondiali» indica le vendite qualificanti nell'ambito del contratto — mai ogni racchetta MAXIMUS non correlata.",
      "Aliquote, base di calcolo, territori, durata, rimborsi, detrazioni, rendicontazione, liquidazione e verifica sono definiti nell'accordo pertinente. Non è pubblicata alcuna percentuale di royalty predefinita.",
      "Nessuna campagna globale, budget media, risultato di sponsorizzazione o successo commerciale è promesso senza un ambito concordato.",
    ],
    cta: "Invia una richiesta di collaborazione di brand",
    cta2: "Richiesta di collaborazione per maestri",
  },
  families: {
    title: "Famiglie e genitori",
    lead: "Decisioni informate sull'attrezzatura, continuità dello sviluppo, conoscenza e diritti conservati, visibilità della partecipazione e vantaggi definiti dal programma che possono sostenere l'attività futura.",
    nowTitle: "Disponibile ora",
    now: ["Richieste su famiglia e sviluppo, per iscritto.", "Scelta dell'attrezzatura con il coinvolgimento del maestro, richieste di fitting e di dimostrazione.", "Registrazioni private: i profili dei minori non sono mai pubblicati e non sono mai commercializzati per impostazione predefinita.", "Percorso formativo per i genitori: configurazione, carico, progressione, registrazioni e diritti."],
    plannedTitle: "Previsto",
    planned: ["Vantaggi di partecipazione definiti dal programma, utilizzabili per beni e servizi all'interno dell'ecosistema, anziché come interesse in denaro.", "Registrazioni del proprietario e della famiglia nell'archivio del proprietario proposto, con permessi del tutore e passaggio del controllo a 18 anni."],
    categoriesTitle: "Tenuti separati",
    categories: ["Royalty contrattuali derivanti da diritti in licenza o da vendite qualificanti", "Vantaggi di partecipazione definiti da un programma", "Crediti per acquisti o servizi", "Pagamenti anticipati", "Appartenenza istituzionale"],
    categoriesP: "Queste categorie non sono mai trattate come interscambiabili.",
    statusTitle: "Stato effettivo del programma per le famiglie",
    journeyTitle: "Il percorso famiglia",
    journey: [
      ["Obiettivo", "Che cosa il giocatore vuole raggiungere come passo successivo."],
      ["Livello attuale", "Dove si trova oggi il giocatore."],
      ["Maestro", "Se un maestro partecipa alle decisioni sull'attrezzatura."],
      ["Attrezzatura", "Attrezzatura adeguata alla fase, compresi i sistemi di allenamento dove pertinenti."],
      ["Pratica concordata", "Uso guidato dal maestro, concordato in anticipo."],
      ["Verifica", "Rivalutazione in punti di verifica comparabili."],
    ],
    brief: {
      who: "Genitori e tutori di giocatori a qualsiasi livello.",
      value: "Una risposta scritta su attrezzatura adeguata, coinvolgimento del maestro e passo successivo di sviluppo.",
      now: "Richieste familiari per iscritto; scelta con il coinvolgimento del maestro; registrazioni private — i profili dei minori non sono mai pubblicati.",
      next: "Invii qui sotto la richiesta familiare. Riceve immediatamente un ID richiesta.",
    },
    formTitle: "Richiesta familiare",
    formNote: "Da compilare da un genitore o tutore. Non inserisca il nome, la data di nascita, la scuola o informazioni sanitarie del minore.",
    noPromise: "Un acquisto non promette royalty, rendimenti da investimento, sponsorizzazioni o finanziamento dello sviluppo di un minore.",
    statusP: "Questa versione spiega il modello e accetta richieste sul programma. Maturazione, pagamenti e utilizzo non sono disponibili fino a quando eventi qualificanti, beneficiari, fonte di finanziamento, base di calcolo, usi consentiti, trattamento contabile, rimborsi, storni, scadenza, trasferibilità, chiusura del programma e gestione delle controversie non siano definiti per iscritto. Non è promesso alcun saldo che non diminuisca mai, nessuna partecipazione paga tutto l'allenamento e non è implicata alcuna protezione del capitale.",
    cta: "Invia una richiesta familiare o di sviluppo",
  },
  owners: {
    title: "Proprietari e archivio del proprietario",
    lead: "L'archivio del proprietario è una registrazione proposta, ad accesso autorizzato, di attrezzatura, sviluppo, conoscenza, contenuti e diritti documentati. È presentato come parte dell'architettura del proprietario prevista: non sono mostrati account attivi, saldi, certificati o risultati.",
    nowTitle: "Per gli attuali proprietari, ora",
    now: ["Richieste dei proprietari: riferimento di prodotto o seriale, messa a punto, assistenza e richieste di registrazioni, per iscritto.", "Certificato di Precisione e documentazione dei set abbinati dove la classe di precisione li prevede, consegnati con il prodotto."],
    archTitle: "Architettura prevista dell'archivio",
    arch: ["Identità di prodotto e riferimenti seriali", "Configurazione e certificati di controllo qualità applicabili", "Storico di assistenza e di messa a punto", "Registrazioni di sviluppo del giocatore o del maestro", "Qualifiche e risultati verificati", "Contenuti multimediali con diritti liberati e materiali propri", "Licenze, permessi e riferimenti contrattuali", "Registrazioni del programma di brand personale", "Rendiconti di royalty applicabili o vantaggi di partecipazione"],
    separationTitle: "Che cosa significa la proprietà",
    separation: [
      "La proprietà di una racchetta fisica è distinta dalla titolarità del diritto d'autore, di una licenza, di un diritto contrattuale o di una registrazione che descrive tali elementi.",
      "Un documento conservato o una voce su blockchain non è automaticamente prova che un diritto esista o sia stato trasferito.",
      "Le prove mantengono la loro classificazione: dichiarate dal partecipante, confermate dal tutore, validate dal maestro, misurate dal sistema.",
      "Per i minori: registrazioni private, permessi del tutore, nessun profilo di minore pubblicato e nessuna commercializzazione dell'identità per impostazione predefinita.",
      "Esportazione, correzione, controllo degli accessi e un adeguato passaggio del controllo fanno parte del progetto.",
    ],
    techTitle: "Blockchain 5.0 e MxSN",
    techP: "Blockchain 5.0 è la direzione tecnologica dichiarata; MxSN definisce i concetti di una rete ad accesso autorizzato per consenso, consegna, prove, diritti e rendicontazione. L'implementazione operativa non è rappresentata. Il modello dati dell'applicazione è costruito per integrarsi successivamente attraverso un'interfaccia documentata, senza far credere che oggi esista una connessione.",
    cta: "Richiesta del proprietario",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Il collegamento tra giocatori, maestri, circoli, accademie, fornitori di servizi, operatori di programmi e partner regionali.",
    functionsTitle: "Funzioni potenziali",
    functions: ["Individuazione", "Presentazioni", "Programmi di sviluppo", "Supporto sull'attrezzatura", "Eventi", "Accesso ai servizi", "Opportunità per i partner"],
    statusTitle: "Stato effettivo",
    statusP: "Non è ancora pubblicato alcun elenco pubblico: saranno elencati solo i partecipanti la cui identità, relazione e autorizzazione a comparire siano accertate. Una proposta inviata a un circolo non è una collaborazione, e un potenziale distributore non è un distributore nominato. Pubblicazione dell'elenco, prenotazioni, messaggistica e operazioni commerciali sono controllate separatamente e non sono attive.",
    cta: "Candidati al network",
  },
  partnerships: {
    title: "Percorsi di collaborazione",
    lead: "Prima la qualificazione scritta. Ogni percorso porta a una richiesta specifica per il ruolo; le condizioni commerciali seguono per iscritto.",
    commercialTitle: "Attività commerciali potenziali della piattaforma",
    commercial: ["Attrezzatura", "Progettazione su misura", "Personalizzazione", "Programmi per squadre e accademie", "Sistemi di allenamento", "Licenze contrattuali", "Distribuzione", "Servizi approvati", "Future categorie di prodotto"],
    boundary: "Diritti di Paese, esclusività, corrispettivi di territorio e margini dei distributori sono condizioni negoziate. Non sono pubblicati fatturati, previsioni, valutazioni, quote di mercato, rendimenti, impegni di finanziamento o collaborazioni senza nome.",
    routes: {
      coaches: {
        title: "Maestri",
        lead: "Sistemi di allenamento, fitting, identità professionale, programmi autorizzati, opportunità di brand personale e fornitura di attrezzatura.",
        points: ["Sweet Spot Trainer e Spot Trainer nella pratica guidata dal maestro.", "Fitting con le matrici di configurazione e le otto misure di manico di fabbrica.", "Coach-to-Brand: un profilo professionale verificato e un sub-brand regolato da diritti.", "L'uso autorizzato dei programmi segue un accordo scritto."],
        cta: "Invia una richiesta di collaborazione per maestri",
        brief: {
          who: "Maestri indipendenti e staff tecnici.",
          value: "Sistemi di allenamento per la pratica guidata dal maestro, fitting con le matrici delle serie e gli otto manici di fabbrica, e un percorso verso un'identità professionale.",
          now: "Richieste dei maestri per iscritto. Non è pubblicata né implicata alcuna provvigione, guadagno o percentuale di segnalazione.",
          next: "Invii qui sotto la richiesta per maestri. Le condizioni seguono per iscritto.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Circoli e accademie",
        lead: "Attrezzatura per squadre, sistemi di allenamento, personalizzazione, programmi di sviluppo, assistenza e partecipazione al network.",
        points: ["Set per squadre e set abbinati richiesti attraverso il configuratore.", "Sistemi di allenamento e metodologia per uno sviluppo strutturato.", "Personalizzazione per programmi di squadra nelle zone approvate.", "Giornate dimostrative, sessioni di fitting e partecipazione al network."],
        cta: "Invia una richiesta per circolo o accademia",
        brief: {
          who: "Circoli, accademie e programmi di squadra.",
          value: "Set per squadre e set abbinati, sistemi di allenamento, personalizzazione per programmi di squadra e giornate dimostrative.",
          now: "Richieste di circoli e accademie per iscritto; i set per squadre sono richiesti attraverso il configuratore.",
          next: "Invii qui sotto la richiesta per circolo o accademia.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribuzione e sviluppo per Paese",
        lead: "Assortimento, coordinamento produttivo, capacità tecnica, sviluppo del territorio e qualificazione commerciale riservata.",
        points: ["Qualificazione scritta della controparte, del territorio e del canale.", "Assortimento definito a partire dalle matrici di configurazione e dalle classi di precisione.", "Territorio, esclusività, volumi, prezzi e protezione commerciale sono condizioni negoziate e concordate per iscritto.", "Entità contrattuale, condizioni di pagamento e base di consegna sono indicate per ciascuna operazione."],
        cta: "Invia una richiesta di distribuzione o di sviluppo per Paese",
        brief: {
          who: "Rivenditori, distributori e partner di Paese.",
          value: "Un assortimento definito a partire dalle matrici confermate, dalle classi di precisione e dalla gamma di manici, con qualificazione scritta di territorio e canale.",
          now: "Richieste di distribuzione per iscritto. Territorio, esclusività, volumi e prezzi sono negoziati — nessuno è concesso tramite un modulo.",
          next: "Invii qui sotto la richiesta di distribuzione.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategia e investimenti",
        lead: "Capacità ingegneristica, profondità di configurazione, modello produttivo, vie di accesso al mercato, proprietà intellettuale, servizi e opportunità di espansione.",
        points: ["Un confronto strategico qualificato o l'accesso controllato alle informazioni segue una qualificazione scritta.", "Le informazioni pubbliche si limitano a specifiche di prodotto approvate, architettura di configurazione, capacità verificate e spiegazioni dei programmi.", "Economia specifica dell'acquirente, costi, metodologia protetta e accordi non pubblicati sono divulgati solo con NDA o contratto."],
        cta: "Richiedi un confronto strategico qualificato",
        brief: {
          who: "Investitori e partner strategici.",
          value: "Un confronto qualificato su capacità ingegneristica, profondità di configurazione, modello produttivo, vie di accesso al mercato e proprietà intellettuale.",
          now: "Non sono pubblicati dati finanziari, previsioni, valutazioni o rendimenti. Le informazioni controllate seguono qualificazione scritta e NDA.",
          next: "Richieda qui sotto un confronto strategico qualificato.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Programmi istituzionali",
        lead: "Formazione, accesso, innovazione, prove di sviluppo, impatto sociale e programmi strutturati in modo adeguato.",
        points: ["I programmi istituzionali sono strutturati attraverso MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) dove il programma stabilisce tale ruolo.", "I fondi di programma vincolati e le operazioni commerciali restano distinti.", "Una richiesta non è una domanda di adesione accettata, e un acquirente di attrezzatura non è un membro istituzionale.", "Contributi, status di ente non profit, trattamento fiscale e autorizzazioni regolamentari sono specifici per Paese e non sono mai presunti."],
        cta: "Invia una richiesta di programma istituzionale",
        brief: {
          who: "Istituzioni, programmi formativi e di sviluppo.",
          value: "Programmi per formazione, accesso, innovazione e prove di sviluppo, strutturati con l'operatore adeguato.",
          now: "Richieste istituzionali per iscritto. Una richiesta non è una domanda di adesione; l'acquisto di attrezzatura non è un'appartenenza istituzionale.",
          next: "Invii qui sotto la richiesta istituzionale.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Divulgazione pubblica e controllata",
    disclosure: {
      public: { h: "Pubblico", p: "Specifiche di prodotto approvate, costruzione, architettura di configurazione, finalità di allenamento, capacità verificate, spiegazioni dei programmi e percorsi di collaborazione." },
      qualified: { h: "Richiesta qualificata", p: "Requisiti tecnici, quantità, interesse territoriale, ambito di sviluppo e discussioni commerciali pertinenti." },
      controlled: { h: "Controllato da NDA o contratto", p: "Formule interne, protocolli di controllo qualità dettagliati, laminazioni, attrezzaggio, metodi di produzione, identità dei fornitori, costi, economia specifica dell'acquirente, metodologia protetta, accordi non pubblicati e registrazioni sensibili sui diritti." },
    },
  },
  contact: {
    title: "Contatti e richieste",
    lead: "Scelga la finalità della sua richiesta. Ogni modulo raccoglie solo ciò che serve a indirizzarla e a valutarla. Le richieste ricevono risposta per iscritto.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Identità legale",
  },
  form: {
    purposeLabel: "Finalità della richiesta",
    purposes: {
      selection: "Aiuto nella scelta di una racchetta",
      product: "Informazioni sul prodotto",
      fitting: "Fitting o dimostrazione",
      technical: "Brief tecnico",
      config: "Richiesta di configurazione",
      gps: "Profilo attrezzatura GPS",
      coach: "Collaborazione per maestri",
      club: "Richiesta di circolo o accademia",
      distribution: "Distribuzione o sviluppo per Paese",
      brand: "Collaborazione di brand o ambasciatore",
      family: "Richiesta familiare o di sviluppo",
      institutional: "Programma istituzionale",
      strategic: "Confronto strategico o di investimento",
      owner: "Richiesta del proprietario",
      network: "Domanda per Sports Network",
      general: "Richiesta generale",
    },
    fields: {
      name: "Nome",
      email: "Email",
      role: "Il suo ruolo",
      country: "Paese o regione",
      organisation: "Organizzazione",
      message: "Il suo messaggio",
      level: "Livello attuale",
      objectives: "Che cosa conta di più (fino a tre)",
      currentRacquet: "Racchetta attuale",
      grip: "Misura del manico, se nota",
      seriesInterest: "Serie di interesse",
      quantity: "Quantità",
      city: "Città o luogo della sessione",
      coachInvolved: "È coinvolto un maestro?",
      timing: "Tempistica preferita",
      targets: "Obiettivi preferiti",
      limits: "Limiti obbligatori",
      use: "Uso previsto",
      tradeoffs: "Compromessi accettabili",
      basis: "Base di misurazione",
      players: "Numero di giocatori",
      interests: "Aree di interesse",
      territory: "Territorio di interesse",
      channels: "Canali esistenti ed esperienza",
      audience: "Pubblico o disciplina",
      proposal: "Collaborazione proposta",
      goal: "Obiettivo di sviluppo",
      ageBand: "Fascia d'età del giocatore",
      scope: "Ambito del programma",
      interestArea: "Area di interesse",
      productRef: "Riferimento di prodotto o seriale",
      requestType: "Tipo di richiesta",
      seeking: "Che cosa sta cercando",
      consent: "Acconsento che MAXIMUS conservi e utilizzi questi dati per rispondere a questa richiesta. Non è un'iscrizione a comunicazioni di marketing.",
    },
    roles: { player: "Giocatore", parent: "Genitore o tutore", coach: "Maestro", club: "Circolo o accademia", retailer: "Rivenditore", distributor: "Distributore", brand: "Brand o ambasciatore", investor: "Investitore o partner strategico", institution: "Istituzione", other: "Altro" },
    interestOptions: { training: "Sistemi di allenamento", fitting: "Fitting racchetta", identity: "Identità professionale", programmes: "Programmi autorizzati", brand: "Brand personale", supply: "Fornitura di attrezzatura", team: "Attrezzatura per squadre", personalisation: "Personalizzazione", development: "Programmi di sviluppo", service: "Assistenza", network: "Partecipazione al network" },
    ownerTypes: { setup: "Messa a punto e configurazione", service: "Assistenza", records: "Registrazioni e certificati", other: "Altro" },
    strategicAreas: { engineering: "Capacità ingegneristica", configuration: "Profondità di configurazione", manufacturing: "Modello produttivo", routes: "Vie di accesso al mercato", ip: "Proprietà intellettuale e servizi", expansion: "Opportunità di espansione" },
    errors: {
      required: "Questo campo è obbligatorio.",
      too_long: "Questo inserimento è troppo lungo.",
      too_short: "Questo inserimento è troppo breve.",
      invalid_email: "Inserisca un indirizzo email valido, per esempio nome@example.com.",
      invalid_choice: "Scelga una delle opzioni.",
      not_number: "Inserisca un numero intero usando solo cifre.",
      out_of_range: "Questo valore è fuori dall'intervallo accettato.",
      not_in_matrix: "Questo peso non è nella matrice elencata della serie selezionata.",
      decimal_not_supported: "Inserisca un numero intero, senza decimali.",
      too_many: "Selezioni non più di tre opzioni.",
      consent_required: "Il consenso è necessario perché MAXIMUS possa rispondere a questa richiesta.",
      invalid: "Questo inserimento non è valido.",
    },
  },
  legal: {
    title: "Identità legale e controllo",
    lead: "Il marchio pubblico è MAXIMUS / MAXIMUS GPS. Le identità legali operative sono distinguibili e sono indicate qui.",
    entities: {
      institutional: { role: "Livello dei programmi istituzionali", p: "Fornisce il livello dei programmi istituzionali dove un programma stabilisce tale ruolo. Non è un venditore commerciale di racchette. Organizzazione non profit costituita nel Dubai International Financial Centre." },
      equipment: { role: "Entità commerciale per l'attrezzatura", p: "L'entità commerciale per l'attrezzatura, per fornitura, distribuzione e consegna commerciale su contratto dove i documenti operativi vigenti stabiliscono tale ruolo. La parte contrattuale di ogni operazione è indicata nei documenti di quella operazione." },
      ip: { role: "Proprietà intellettuale, brand e coordinamento commerciale", p: "Compare per un ruolo accertato di proprietà intellettuale, brand o coordinamento commerciale. Non le è assegnata alcuna responsabilità contrattuale non confermata." },
      stewardship: { role: "Riferimento di stewardship", p: "House of Maximus è il riferimento di stewardship dell'ecosistema dove sostenuto dalla fonte pertinente." },
      control: { role: "Proprietà intellettuale interna, provenienza e controllo documentale", p: "MIPA è il livello interno di proprietà intellettuale, provenienza e controllo documentale. Una voce interna MIPA è distinta da un marchio registrato, un brevetto, una registrazione di diritto d'autore o un riconoscimento giudiziale esterni, e non costituisce approvazione visiva." },
    },
    labels: { licence: "Licenza", registration: "Registrazione", vat: "VAT TRN", address: "Indirizzo", email: "Email", jurisdiction: "Giurisdizione" },
    boundaryTitle: "Limiti",
    boundary: [
      "Un acquisto non concede automaticamente appartenenza istituzionale, diritti di governance, royalty o diritti di investimento.",
      "Il ruolo istituzionale è distinto dalle operazioni commerciali sull'attrezzatura.",
      "Privacy, condizioni dei programmi e disposizioni di accesso controllato corrispondono alle funzioni effettivamente rilasciate.",
      "Nessuna dichiarazione generale sulla legge applicabile vale per ogni visitatore, vendita o programma estero; la base contrattuale è stabilita per ciascun accordo.",
    ],
  },
  privacy: {
    title: "Informativa sulla privacy",
    updated: "Versione 2026-09-21 · sito 4.2",
    contactTitle: "Contatto per domande sulla privacy",
    sections: {
      collect: ["Che cosa viene raccolto", "Quando invia un modulo: i dati che inserisce (nome, email, ruolo, Paese o regione, organizzazione se indicata, il suo messaggio e le risposte del modulo), i parametri di pagina e di campagna della sua visita (pagina di arrivo, lingua, parametri utm; identificativi di clic pubblicitari solo se ha consentito le analisi) e l'ora dell'invio. Il suo indirizzo IP è utilizzato solo in forma hashata e di breve durata per limitare gli abusi e non è conservato con la sua richiesta."],
      purpose: ["Perché", "Per rispondere alla sua richiesta, preparare la proposta o la specifica che ha chiesto e conservare una registrazione della richiesta. Sulla base di un modulo non viene inviato alcun messaggio di marketing."],
      storageOn: ["Dove sono conservate le richieste", "Le richieste sono conservate in una banca dati di Upstash, Inc. (Redis), fornita attraverso la piattaforma di hosting Vercel Inc."],
      notifyEmail: ["Notifica di una nuova richiesta", "Quando una richiesta è accettata, una notifica contenente i dati che ha inviato è trasmessa via email alla casella MAXIMUS responsabile."],
      notifyTelegram: ["Notifica di una nuova richiesta", "Quando una richiesta è accettata, una notifica contenente i dati che ha inviato è trasmessa alla persona responsabile in MAXIMUS tramite Telegram (Telegram FZ-LLC, Dubai), che pertanto tratta tale notifica in transito."],
      notifyWebhook: ["Notifica di una nuova richiesta", "Quando una richiesta è accettata, una notifica contenente i dati che ha inviato è trasmessa a un endpoint interno MAXIMUS attraverso una connessione firmata e cifrata."],
      notifyNone: ["Notifica di una nuova richiesta", "La notifica delle nuove richieste è in fase di attivazione. La sua richiesta è conservata e letta da MAXIMUS nel registro interno; a questo scopo non viene inviato nulla a terzi."],
      storageOff: ["Dove sono conservate le richieste", "La conservazione delle richieste è in fase di attivazione. Finché non è attiva, i moduli indicano che una richiesta non può essere accettata; nulla viene conservato. Il sito è ospitato da Vercel Inc."],
      browser: ["Archiviazione nel browser", "La session storage conserva le risposte a scelta multipla di GPS e del configuratore e i parametri di campagna della sua visita per questa sessione del browser. Dati di contatto, testo libero, testo dell'incisione e informazioni sui minori non sono conservati nel browser."],
      analyticsOn: ["Analisi", "Con il suo consenso, Google Analytics 4 misura le visite e gli eventi dei moduli senza dati di contatto né testo delle richieste. La sua scelta è conservata nella local storage e può essere modificata in qualsiasi momento in «Impostazioni di analisi» nel piè di pagina. I moduli funzionano anche senza analisi."],
      analyticsOff: ["Analisi", "Su questo sito non è attivo alcuno strumento di analisi."],
      retention: ["Conservazione", "Non è ancora configurato alcun periodo di cancellazione automatica. Può chiedere in qualsiasi momento la cancellazione della sua richiesta."],
      children: ["Minori", "I moduli devono essere compilati da un adulto. Le richieste che riguardano giocatori di età inferiore a 18 anni sono presentate da un genitore o tutore. Non invii il nome, la data di nascita, la scuola o informazioni sanitarie di un minore. I profili dei minori non sono mai pubblicati."],
      rights: ["I suoi diritti", "Per accedere alla sua richiesta, correggerla o cancellarla, scriva a gps@maximus.tennis indicando il suo ID richiesta."],
      controlled: ["Informazioni controllate", "I documenti riservati non sono conservati in questo sito né distribuiti da esso. La divulgazione controllata avviene con NDA o contratto, attraverso canali separati."],
    },
  },
  terms: {
    title: "Condizioni d'uso",
    copyright: "Il diritto d'autore su questo sito — i suoi testi, le fotografie, il design e il codice — appartiene esclusivamente a Maximus Kiriyakulov. Non è stato ceduto a nessuna società né ad alcuna altra persona.",
    updated: "Versione 2026-09-21",
    sections: [
      ["Informazione, non offerta", "Le informazioni di prodotto di questo sito descrivono specifiche approvate, architettura di configurazione e spiegazioni dei programmi. Non sono un'offerta di vendita, un listino prezzi, una dichiarazione di giacenza o un impegno di consegna. Le condizioni commerciali sono concordate separatamente per iscritto con l'entità contrattuale indicata in ciascuna operazione."],
      ["Richieste", "Una richiesta inviata attraverso questo sito — compresi i profili GPS, le richieste di configurazione e i brief tecnici — è registrata con un ID richiesta ed esaminata. Non è un ordine accettato, un impegno di produzione, un appuntamento confermato, una domanda di adesione o una domanda accettata per un qualsiasi programma."],
      ["Specifiche e prove", "Valori calcolati, obiettivi di produzione e specifiche confermate sono distinti nelle pagine pertinenti. I valori di rigidità sono obiettivi di produzione fino a diversa pubblicazione. Nessun risultato per un giocatore specifico è garantito."],
      ["Ecosistema, appartenenza e diritti", "L'acquisto di una racchetta non crea appartenenza istituzionale, diritti di investimento, titolarità di proprietà intellettuale, diritto a royalty o vantaggi di partecipazione. I diritti derivano dalle condizioni di programma pubblicate o da un accordo scritto."],
      ["Proprietà intellettuale", "MAXIMUS®, l'emblema del leone, il marchio GPS e i contenuti di questo sito sono protetti. Formule ingegneristiche interne, protocolli di controllo qualità, laminazioni, attrezzaggio, identità dei fornitori, costi e metodologia protetta non sono divulgati qui."],
    ],
  },
  lead: {
    submit: "Invia la richiesta",
    submitting: "Invio in corso…",
    retry: "Riprova",
    acceptedEyebrow: "Richiesta accettata",
    acceptedTitle: "La sua richiesta è stata ricevuta.",
    requestId: "ID richiesta",
    acceptedNext: "MAXIMUS esamina ogni richiesta e risponde per iscritto all'indirizzo email che ha indicato. Conservi l'ID richiesta per ogni comunicazione successiva.",
    duplicate: "Questa richiesta era già stata ricevuta; non è stato creato alcun duplicato.",
    another: "Avvia una nuova richiesta",
    errorsTitle: "Verifichi questi campi:",
    failTitle: "La sua richiesta non è stata inviata.",
    fail: {
      offline: "Il suo dispositivo è offline.",
      network: "La connessione al server non è riuscita.",
      timeout: "Il server non ha risposto in tempo.",
      rate_limited: "Sono arrivate troppe richieste da questa rete. Riprovi tra qualche minuto.",
      too_fast: "Il modulo è stato inviato molto rapidamente. Lo verifichi e lo invii di nuovo.",
      spam_suspected: "La richiesta è stata bloccata dal filtro antispam.",
      unavailable: "In questo momento non è possibile accettare richieste.",
      default: "Si è verificato un errore inatteso.",
    },
    keepNote: "I suoi dati restano su questa pagina, così può riprovare.",
    sendByEmail: "Invia questa richiesta per email",
    sendByEmailNote: "Il suo programma di posta si apre con il testo di questa richiesta. MAXIMUS la riceve quando invia l'email.",
    mailConfig: "Configurazione",
    mailPage: "Pagina",
    fallback: "Se il problema persiste, scriva a {email}. Una richiesta si considera inviata solo quando è mostrato un ID richiesta.",
    privacyLink: "Informativa sulla privacy",
    hpLabel: "Lasci vuoto questo campo",
    consentShort: "Consenso",
    after: "Dopo l'invio, su questa pagina è mostrato un ID richiesta. Le richieste sono esaminate e ricevono risposta per iscritto; una richiesta non è un ordine.",
    basis: { unstrung: "Senza corde", strung: "Incordata", unknown: "Non so — da concordare nella specifica" },
    hints: {
      email: "MAXIMUS risponde per iscritto a questo indirizzo.",
      goal: "Per esempio: prima racchetta da competizione, oppure passaggio da una racchetta junior. Non inserisca nomi, date di nascita o informazioni sanitarie di un minore.",
      currentRacquet: "Marca e modello, se noti.",
      message: "Non inserisca password, dati di pagamento o informazioni sanitarie.",
    },
  },
  choose: {
    eyebrow: "Supporto alla scelta",
    title: "Aiuto nella scelta di una racchetta",
    lead: "Indichi a MAXIMUS il suo livello e ciò che conta di più. Le sue risposte sono esaminate e riceve una proposta scritta: serie, classe di precisione, peso e manico.",
    stepsTitle: "Che cosa accade dopo",
    steps: [
      ["Le sue risposte", "Livello, priorità e misura del manico, se la conosce."],
      ["Revisione di un esperto", "MAXIMUS confronta le sue risposte con le matrici delle serie."],
      ["Proposta scritta", "Una configurazione proposta e il passo successivo, per iscritto."],
    ],
    formTitle: "Le sue risposte",
    submit: "Richiedi aiuto nella scelta",
    altTitle: "Preferisce decidere da sé?",
    altGps: "Profilo GPS dettagliato",
    altBuild: "Configura direttamente",
    note: "Nessun fitting automatico e nessuna dichiarazione di accuratezza: una persona esamina ogni richiesta.",
  },
  consent: {
    title: "Analisi",
    text: "MAXIMUS può misurare le visite con Google Analytics? I moduli funzionano in ogni caso; agli strumenti di analisi non sono inviati dati di contatto né il testo delle richieste.",
    allow: "Consenti l'analisi",
    decline: "Rifiuta",
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: la composizione completa — lo Spot Trainer visto di fronte e di profilo, l'emblema rotondo del leone inciso sulla testa rotonda di contatto, l'incisione MAXIMUS e SPOT TRAINER lungo il fusto e il tappo ottagonale del manico con il marchio del leone",
    greatHero: "Serie MAXIMUS GREAT, 363 g: la composizione completa con i dettagli rossi e gialli sulla testa, la scritta MAXIMUS lucida, l'autografo Maximus sul fusto e il tappo del manico con il leone",
    spotDetail: "Due MAXIMUS Spot Trainer visti più da vicino: il leone inciso sulla testa di contatto nera opaca, la fasciatura a coste del grip e i tappi ottagonali del manico con il marchio del leone",
    spotPair: "Due MAXIMUS Spot Trainer appoggiati in diagonale su una superficie scura, con MAXIMUS inciso lungo il fusto di uno e SPOT TRAINER su quello dell'altro, e l'emblema rotondo del leone su ciascuna testa di contatto",
    spinVisual: "MAXIMUS SPIN: testa con corde, scritta MAXIMUS lucida, grip e tappo del manico con il leone",
    powerVisual: "MAXIMUS POWER: testa con corde, scritta MAXIMUS lucida, incisione di personalizzazione, grip e tappo del manico con il leone",
    greatVisual: "MAXIMUS GREAT: testa con corde, scritta MAXIMUS lucida, incisione di personalizzazione, grip, tappo del manico con il leone e il marchio della serie G sul cuore",
    spinHead: "Testa e piatto corde MAXIMUS SPIN",
    handleLion: "Cuore, grip e tappo del manico MAXIMUS con il marchio del leone",
    engraving: "Incisione argentata di personalizzazione sul fusto",
    lettering: "Scritta MAXIMUS nera lucida su telaio nero opaco",
    variantAlt: "Serie MAXIMUS {series} — {w} g, bilanciamento {b} mm: visualizzazione completa con la fascia delle specifiche, la zona di incisione per la personalizzazione e la marcatura MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistema a quattro racchette",
    sst270: "Sweet Spot Trainer da 270 g / 330 mm",
    sst285: "Sweet Spot Trainer da 285 g / 325 mm",
    sst300: "Sweet Spot Trainer da 300 g / 325 mm",
    sst400: "Sweet Spot Trainer da 400 g / 320 mm",
    sstShafts: "Fusti Sweet Spot Trainer con la scritta MAXIMUS",
    sstGrips: "Grip e tappi del manico Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, quattro tappi del manico con il marchio del leone",
    note: "Immagine del prodotto",
  },
  notFound: { title: "Pagina non trovata", p: "La pagina richiesta non esiste in questa lingua.", cta: "Torna alla pagina iniziale" },
};

export default it;
