/* Lithuanian dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const lt = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — vien iš anglies pluošto pagamintos teniso raketės pagal specifikaciją",
    defaultDescription:
      "Vien iš anglies pluošto pagamintos teniso raketės nuo rėmo iki rankenos: GREAT 97 in², POWER 98 in² ir SPIN 100 in², aštuoni gamykliniai rankenos dydžiai L0–L7, tikslumo klasės svoriui, balansui, mosto svoriui ir standumui bei individualūs inžineriniai sprendimai pagal užklausą.",
  },
  common: {
    statuses: {
      current: "Galiojantis",
      agreement: "Galima pagal susitarimą",
      development: "Kuriama",
      concept: "Koncepcija",
      target: "Gamybos tikslinė vertė",
      modelled: "Apskaičiuota",
      confirmed: "Patvirtinta",
      requested: "Pageidaujama architektūra",
      notprovided: "Nepateikta",
    },
    brief: { who: "Kam tai skirta", value: "Ką gaunate", now: "Šiuo metu patvirtinta", next: "Tolesnis žingsnis" },
    labels: {
      next: "Toliau",
      back: "Atgal",
      edit: "Keisti atsakymus",
      review: "Apžvalga",
      start: "Pradėti",
      restart: "Pradėti iš naujo",
      copy: "Kopijuoti užklausos tekstą",
      copied: "Nukopijuota",
      openEmail: "Atverti el. paštą šiai užklausai išsiųsti",
      reference: "Užklausos nuoroda",
      weight: "Svoris",
      balance: "Balansas",
      swingweight: "Mosto svoris",
      stiffness: "Standumas",
      grip: "Rankenos dydis",
      headSize: "Galvos dydis",
      series: "Serija",
      precisionClass: "Tikslumo klasė",
      quantity: "Kiekis",
      notProvided: "Dar nepaskelbta",
      requestTarget: "Pageidaujama tikslinė vertė",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Skaityti daugiau",
      allSeries: "Visos serijos",
      points: "katalogo svoriai",
      optional: "neprivaloma",
      required: "privaloma",
      select: "Pasirinkite",
      yes: "Taip",
      no: "Ne",
      unknown: "Tiksliai nežinau",
      custom: "Individuali tikslinė vertė",
      listed: "Katalogo svoris",
      individual: "Atskira raketė",
      pair: "Suderinta pora",
      triple: "Suderintas trejetas",
      team: "Komandos komplektas",
      summaryTitle: "Jūsų užklausos suvestinė",
      nextAction: "Tolesnis veiksmas",
      status: "Būsena",
      learn: "Sužinoti daugiau",
      schematic: "Schema — ne matavimo rezultatas",
      photo: "Fotografija",
    },
    ecosystemStrip: "MAXIMUS ekosistema",
    truth: {
      noPrices: "Kainos, minimalūs kiekiai, įvykdymo terminai, garantijos ir pristatymo įsipareigojimai patvirtinami raštu kiekvienai rinkai ir kiekvienai programai atskirai.",
      requestNotOrder: "Užklausa yra prašymas įvertinti. Tai nėra priimtas užsakymas, gamybos įsipareigojimas ar patvirtintas susitikimas.",
      noGuarantee: "Jokia čia aprašyta įranga, metodas ar programa negarantuoja konkrečiam žaidėjui rezultato.",
      governing: "Šis puslapis skelbiamas keliomis kalbomis. Vyraujanti yra anglų kalbos versija; vertimas teikiamas patogumo sumetimais.",
    },
  },
  nav: {
    language: "Kalba",
    groups: { racquets: "Raketės", training: "Treniruotės", ecosystem: "Ekosistema", partnerships: "Partnerystė" },
    familyPlan: "Šeimos planas",
    racquets: "Raketių serijos ir palyginimas",
    great: "GREAT — 97 in² · Kontrolė",
    power: "POWER — 98 in² · Galia",
    spin: "SPIN — 100 in² · Sukimas",
    precision: "Tikslumas ir standumas",
    grip: "Gamyklinė rankenos architektūra L0–L7",
    custom: "Individualūs inžineriniai sprendimai",
    training: "Treniruočių sistemos",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodika",
    gps: "MAXIMUS GPS",
    build: "Sukurkite savo raketę",
    choose: "Padėkite išsirinkti",
    ecosystem: "Ekosistemos žemėlapis",
    engineering: "Inžinerija ir gamyba",
    experience: "Išbandymas ir pritaikymas",
    brands: "Asmeniniai prekių ženklai ir ambasadoriai",
    families: "Šeimos ir tėvai",
    owners: "Savininkai ir savininko saugykla",
    network: "Sports Network",
    partnerships: "Visi partnerystės keliai",
    coaches: "Treneriai",
    clubs: "Klubai ir akademijos",
    distribution: "Platinimas ir šalies plėtra",
    strategic: "Strategija ir investicijos",
    institutional: "Institucinės programos",
    contact: "Kontaktai",
    legal: "Juridinė tapatybė",
    privacy: "Privatumas",
    terms: "Sąlygos",
    menu: "Meniu",
    close: "Užverti",
    home: "Pradžia",
    skip: "Pereiti prie turinio",
  },
  footer: {
    line: "MAXIMUS raketė yra jūsų raktas į MAXIMUS pasaulį.",
    product: "Produktas",
    ecosystem: "Ekosistema",
    company: "Organizacija",
    instagram: "Instagram",
    email: "El. paštas",
    analytics: "Analitikos nuostatos",
    subscribe: {
      title: "Likite su MAXIMUS",
      line: "Naujos serijos, pritaikymo datos, treniruočių medžiaga ir savininkų programa. Kelti laiškai per metus, nieko daugiau.",
      label: "El. pašto adresas",
      placeholder: "your@email.com",
      button: "Prenumeruoti",
      sending: "Siunčiama",
      done: "Esate sąraše. Rašome tik tada, kai yra kas skaityti.",
      invalid: "Patikrinkite adresą.",
      failed: "Adresas nebuvo užregistruotas. Pabandykite po akimirkos dar kartą.",
      terms: "Prenumeruodami sutinkate, kad MAXIMUS gali siųsti jums šiuos naujinius ir šiuo tikslu saugoti jūsų adresą. Kiekviename laiške yra atsisakymo nuoroda.",
    },
    rights: "MAXIMUS® ir liūto emblema yra MAXIMUS ekosistemos ženklai. MIPA vidinis intelektinės nuosavybės, kilmės ir dokumentų kontrolės lygmuo.",
    boundary:
      "Komercinės ir sutartinės sąlygos derinamos atskirai raštu. Raketės įsigijimas nesukuria institucinės narystės, investavimo teisių, intelektinės nuosavybės priklausomybės ar teisės į autorinį atlyginimą.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Tikslumas prasideda nuo kontakto.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer ir MAXIMUS metodika sujungia sutelktą treniruotę su vien iš anglies pluošto pagamintų varžybinių raketių charakteristikomis.",
    heroCta1: "Susipažinkite su treniruočių sistema",
    heroCta2: "Susipažinkite su GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrolė",
    heroMeta: [
      ["Vien anglies pluoštas", "nuo rėmo iki rankenos"],
      ["4 parametrai", "svoris · balansas · mosto svoris · standumas"],
      ["8 rankenos dydžiai", "gamyklinė geometrija L0–L7"],
      ["3 serijos", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Šeimos planas · Prisidėkite kartu su mumis",
      title: "Jūsų šeimos biudžetas. Ką už jį gaunate. Ką jis kuria.",
      p: "Trys scenarijai greta — dabar, planuojama ir norima. Treniruotės, valandos ir kontaktai su kamuoliu, kuriuos gaunate už savo biudžetą, ir vienos treniruotės, vienos valandos bei vieno smūgio kaina, apskaičiuota pagal jūsų pačių skaičius.",
      points: [
        ["Jūsų skaičiai", "Kiekvieną sumą nurodote jūs. Jokių prielaidų, jokio konvertavimo."],
        ["Trys scenarijai", "Palyginkite, ką darote dabar, su tuo, ką planuojate ir ko norėtumėte."],
        ["Dešimt metų į priekį", "Išlaidų planas nuo vienerių iki dešimties metų, ribojamas jūsų nurodytu amžiumi."],
        ["Už korto ribų", "Pagalba stojant į pirmaujančias mokyklas ir skaitmeninis turtas, kuris lieka žaidėjui."],
      ],
      cta: "Apskaičiuokite savo šeimos planą",
    },
    paths: {
      eyebrow: "Pradėkite nuo čia",
      title: "Pasirinkite savo kelią",
      items: {
        player: { h: "Žaidėjas", p: "Raskite raketę pagal lygį ir prioritetus arba iškart sukonfigūruokite ją patys.", a: "Raskite savo raketę" },
        parent: { h: "Tėvas ar mama", p: "Raštu aprašytas kelias plėtros tikslams, trenerio įsitraukimui ir tinkamai įrangai.", a: "Šeimos kelias" },
        coach: { h: "Treneris, klubas ar akademija", p: "Treniruočių sistemos, pritaikymas, komandos komplektai ir personalizavimas.", a: "Trenerio ir klubo keliai" },
        partner: { h: "Platintojas ar partneris", p: "Platinimo, šalies plėtros, strateginiai ir instituciniai keliai.", a: "Partnerystės keliai" },
      },
    },
    series: {
      eyebrow: "Varžybinės serijos",
      title: "Trys charakteristikų architektūros. Viena inžinerinė platforma.",
      lead: "Pasirinkite seriją pagal žaidimo kryptį, o paskui užbaikite konfigūraciją: tikslumo klasė, svoris, rankenos dydis, personalizavimas.",
      cta: "Palyginkite serijas",
      configure: "Konfigūruoti",
      open: "Atverti seriją",
      photoPending: "Fotografija dar nepaskelbta",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS tikslumo sistema",
      title: "Svoris. Balansas. Mosto svoris. Standumas.",
      sub: "Valdomi kaip viena inžinerinė sistema.",
      lead: "Trys tikslumo klasės nustato, kaip griežtai gatava raketė išlaikoma prie savo deklaruotos specifikacijos. P0.5 yra ankšta tolerancija pagal nustatytą matavimo protokolą — ne nulinė paklaida.",
      cta: "Tikslumas ir standumas išsamiai",
    },
    stiffness: {
      eyebrow: "Standumas",
      title: "Pakartojamas rėmo atsakas deklaruotos tikslinės vertės atžvilgiu.",
      p: "Rėmo standumas formuoja atsaką, pojūtį ir raketių tarpusavio vienodumą. MAXIMUS laiko jį ketvirtuoju valdomu parametru: tikslinė vertė, išmatuotas rezultatas, leidžiama tolerancija ir matavimo prietaiso geba saugomi kaip atskiri įrašai. Nauda yra pakartojamumas — o ne kiekvienam žaidėjui garantuotas rezultatas.",
      cols: [["Atsakas", "Kaip rėmas kontakto momentu grąžina energiją."], ["Pojūtis", "Ką žaidėjas pajunta kontakto momentu."], ["Vienodumas", "Pagal tą pačią specifikaciją pagamintos raketės savo klasės ribose reaguoja vienodai."]],
      schematicCaption: "Schema: leidžiamas nuokrypis apie kiekvienos klasės deklaruotą standumo tikslinę vertę. Tai ne matavimo rezultatas ir jokia RA vertė čia neteigiama.",
      bands: { p25: "tikslinės vertės tolerancija ±1 RA", p15: "tikslinės vertės tolerancija ±0,5 RA", p05: "atitinka deklaruotą RA tikslinę vertę pagal gamykloje nustatytą matavimo protokolą — ne nulinė paklaida", target: "deklaruota tikslinė vertė (vertė neteigiama)" },
    },
    carbon: {
      eyebrow: "Konstrukcijos standartas",
      title: "Vien anglies pluoštas. Nuo rėmo iki rankenos.",
      p: "Visos dabartinės šios platformos MAXIMUS raketės savo konstrukcijoje yra vien iš anglies pluošto, įskaitant rankeną. Rankenai formuoti putplastis nenaudojamas.",
      gripTitle: "Aštuoni gamykliniai rankenos dydžiai. L0–L7.",
      gripP: "Kiekvienas dydis yra gamykloje suformuota anglies pluošto rankenos geometrija — ne viršutinėmis apvijomis sustiprinta rankena.",
      scaleCaption: "Schema: rankenos dydžių nominalieji žymėjimai L0–L7 (nuo 4″ iki 4⅞″). Tai ne išmatuoti rankenos matmenys.",
      cta: "Gamyklinė rankenos architektūra",
    },
    custom: {
      eyebrow: "Individualūs inžineriniai sprendimai",
      title: "Pagaminta pagal specifikaciją.",
      sub: "Standartinis asortimentas yra atspirties taškas.",
      p: "MAXIMUS priima techninius reikalavimus, kurie viršija paskelbtas matricas, kad juos įvertintų, suprojektuotų, validuotų ir pagamintų pagal suderintą specifikaciją. Įgyvendinamumas patvirtinamas raštu.",
      chain: ["Apibrėžti", "Projektuoti", "Validuoti", "Specifikuoti", "Gaminti", "Matuoti / registruoti"],
      cta: "Pateikti techninę užduotį",
      cta2: "Aptarti individualų sprendimą",
    },
    training: {
      eyebrow: "Treniruočių sistemos",
      title: "Treniruočių sistema, sukurta apie kontaktą.",
      p: "Sweet Spot Trainer, MAXIMUS metodika ir Spot Trainer sujungia įrangą su trenerio vadovaujamu darbu: centruotas kontaktas, kontrolė, laipsniškas krūvis ir grįžimas prie varžybinės raketės.",
      cta: "Treniruočių sistemos",
      cta2: "Paprašyti demonstracijos",
      photoPending: "Treniruočių raketės fotografija dar nepaskelbta",
      sstP: "50 in² treniruočių galva centruotam kontaktui pratinti, su keturiomis svorio konfigūracijomis trenerio pasirinktam krūviui.",
      sstCta: "Susipažinkite su Sweet Spot Trainer",
      sstCaption: "300 g konfigūracija, viena iš keturių",
      methodP: "Nusistatykite tikslus, pasirinkite įrangą, treniruokitės su trenerio įsitraukimu, užrašykite pastebėjimus, įvertinkite iš naujo, pakoreguokite ir perkelkite darbą į varžybinį žaidimą.",
      methodCta: "Susipažinkite su metodika",
      spotP: "Nedidelis apvalus taikinys tiksliam ir pakartojamam kontakto taškui pratinti.",
      spotCta: "Susipažinkite su Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Gamyba ir kokybės kontrolė",
      title: "Pagaminta pagal specifikaciją. Išmatuota ir užregistruota.",
      p: "Gamyba vyksta pagal kiekvieno užsakymo rašytinę specifikaciją. Įrašai atitinka tikslumo klasę: saugomi gamybos įrašai P2.5 klasėje, individualūs įrašai ir atsekamumas P1.5 klasėje, individuali kontrolė ir dokumentacija P0.5 klasėje tais atvejais, kai užsakymo programa juos numato.",
      confirmedTitle: "Patvirtinta",
      confirmed: ["Vien iš anglies pluošto konstrukcija nuo rėmo iki rankenos.", "Tikslumo klasės P2.5, P1.5 ir P0.5 su keturiais valdomais parametrais.", "Aštuoni gamykliniai rankenos dydžiai L0–L7."],
      pendingTitle: "Dar nepaskelbta",
      pending: "Matavimo įrangos fotografijos, kokybės kontrolės įrašų pavyzdžiai ir gamyklos vaizdo medžiaga dar nepaskelbti. Niekas šiame puslapyje nėra matavimo sertifikatas.",
      captions: { lettering: "Blizgus MAXIMUS užrašas ant matinio rėmo", buttcap: "Rankena ir rankenos galo dangtelis su liūto ženklu", handle: "Sidabrinė personalizavimo graviūra", finish: "Galva ir stygų laukas" },
      cta: "Inžinerija ir gamyba",
    },
    world: {
      eyebrow: "MAXIMUS pasaulis",
      title: "Vienas raktas. Viena ekosistema. Neribotos galimybės.",
      note: "„Neribotos galimybės“ yra prekių ženklo išraiška, o ne pažadas dėl neriboto techninio įgyvendinamumo, pajamų ar prieigos. Įsigijimas nesukuria autorinio atlyginimo, investicijų grąžos, rėmimo ar žaidėjo plėtros finansavimo.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — ir jūsų navigacija teniso pasaulyje: vedamas įrangos profilis, į kurį atsakoma raštu." },
        personal: { h: "Personalizavimas", p: "Vardai, inicialai, numeriai ir komandos žymėjimai patvirtintoje sidabrinėje graviūroje." },
        development: { h: "Plėtra", p: "Trenerio vadovaujamos treniruočių sistemos, įrašai ir pakartotinis įvertinimas." },
        ecosystem: { h: "Išplėstinė ekosistema", p: "Asmeniniai prekių ženklai, savininkų įrašai, tinklas, licencijavimas ir institucinės programos — kiekviena su savo tikrąja būsena." },
      },
      cta: "Susipažinkite su ekosistema",
    },
    partners: {
      eyebrow: "Partnerystės keliai",
      title: "Treneriai, klubai, platintojai ir partneriai.",
      p: "Pirmiausia rašytinis kvalifikavimas. Šalies teisės, išimtinumas ir komercinės sąlygos derinamos raštu — niekada nesuteikiamos per formą.",
      cta: "Visi partnerystės keliai",
      formTitle: "Trumpa užklausa",
      formLead: "Pasirinkite tikslą ir rašykite MAXIMUS. Užklausos numerį gausite šiame pačiame puslapyje.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "JŪSŲ NAVIGACIJA TENISO PASAULYJE" } },
    personal: { eyebrow: "Personalizavimas", title: "Jūsų vardas. Jūsų numeris. Jūsų MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Trys serijos. Tikri parametrai." },
    map: { cta: "Susipažinkite su ekosistema" },
  },
  racquets: {
    title: "Raketės",
    lead: "Trys varžybinės serijos su bendru konstrukcijos standartu, bendra tikslumo sistema ir bendra gamykline rankenos architektūra. Kiekviena serija yra susiformavusi charakteristikų architektūra platesnėje inžinerinėje platformoje.",
    direction: { control: "Kontrolė", power: "Galia", spin: "Sukimas" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Pagrindinė žaidimo kryptis",
    compareTitle: "Serijų palyginimas",
    compareLead: "Tik patvirtinti architektūros duomenys. Stygų raštai, ilgiai, rėmo profiliai, įtempimo intervalai ir mosto svorio bei standumo nominaliosios vertės šioms serijoms nėra paskelbti; jie renkami kaip pageidaujamos tikslinės vertės techniniam įvertinimui.",
    columns: { series: "Serija", head: "Galvos dydis", direction: "Kryptis", weights: "Katalogo svoriai", range: "Svorio intervalas", balance: "Balanso duomenys" },
    balanceModelled: "Apskaičiuotos vertės",
    balanceNotProvided: "Dar nepaskelbta",
    construction: "Konstrukcija: vien anglies pluoštas, nuo rėmo iki rankenos · Tikslumas: P2.5 / P1.5 / P0.5 · Rankenos dydžiai: L0–L7",
    otherTitle: "Kitos raketių sporto rūšys",
    otherLead: "Patvirtintos plėtros kryptys. Šiose kategorijose parduoti paruoštų produktų nėra ir jokia teniso specifikacija jiems neperkeliama.",
    other: { padel: "Padelis", pickleball: "Pickleball", squash: "Skvošas", badminton: "Badmintonas", racquetball: "Raketbolas", beachTennis: "Paplūdimio tenisas" },
    ctaConfigure: "Konfigūruoti užklausą",
    ctaSeries: "Atverti seriją",
  },
  seriesPage: {
    eyebrow: "Varžybinės serijos",
    intro: {
      great: "97 in² GREAT architektūra sukurta apie kontrolę: kompaktiška galva, tikslus kontaktas ir pasitikėjimas kryptimi.",
      power: "98 in² POWER architektūra sukurta apie energijos perdavimą: gylis ir tempas iš stabilaus rėmo.",
      spin: "100 in² SPIN architektūra sukurta apie kamuolio elgseną: rotacija, atsarga ir skriejimo linijos formavimas.",
    },
    photoPending: "Serijos fotografija dar nepaskelbta",
    detailPending: "Šios serijos konstrukcijos ir rankenos detalių fotografijos dar nepaskelbtos.",
    specsTitle: "Specifikacija ir būsena",
    catalogue: {
      eyebrow: "{series} serijos katalogas",
      title: "{n} svorio variantai",
      lead: "Visi {series} serijos variantai, surikiuoti pagal svorį. Svoris gramais, balansas milimetrais nuo rankenos galo. Kiekviena vizualizacija parodyta visa: niekas neapkirpta, neužmaskuota ir neištempta.",
      selectLabel: "Pasirinkite svorio variantą",
      select: "Parodyti šį variantą",
      selected: "Parodyta aukščiau",
      balanceLabel: "Balansas",
      headLabel: "Galvos dydis",
      constructionLabel: "Konstrukcija",
      gripsLabel: "Gamykliniai rankenos dydžiai",
      precisionLabel: "Tikslumo klasės",
      balanceConfirmed: "Balansas yra šiam svoriui patvirtinta vertė ir atitinka skaičių, atspausdintą ant vizualizacijos. Kainos, atsargos ir pristatymo terminai čia neskelbiami.",
      balanceModelled: "Balansas yra šiam katalogo svoriui apskaičiuota vertė, o ne individualus gamyklos matavimas; ji atitinka skaičių, atspausdintą ant vizualizacijos. Kainos, atsargos ir pristatymo terminai čia neskelbiami.",
      zoom: "Atverti vaizdą",
      close: "Užverti",
      allTitle: "Visi {n} variantai",
    },
    specs: { head: "Galvos dydis", direction: "Pagrindinė kryptis", weights: "Katalogo svoriai", range: "Svorio intervalas", balance: "Balansas", construction: "Konstrukcija", grips: "Gamykliniai rankenos dydžiai", precision: "Tikslumo klasės" },
    construction: "Vien anglies pluoštas, nuo rėmo iki rankenos",
    statusTitle: "Verčių būsena",
    matrixTitle: "Visa svorių matrica",
    matrixLead: "Katalogo svoriai yra standartinis pasirinkimas. Kitų svorių galima prašyti kaip individualių tikslinių verčių; trūkstamos tarpinės vertės neįterpiamos.",
    balanceNote: {
      confirmed: "Balanso vertės yra patvirtintos kiekvienam katalogo svoriui (mm nuo rankenos galo) ir atitinka skaičių, atspausdintą ant to svorio vizualizacijos. Jos čia neskaičiuojamos ir neišlyginamos tarp gretimų svorių; matavimo pagrindas patvirtinamas rašytinėje specifikacijoje.",
      modelled: "Balanso vertės kiekvienam katalogo svoriui yra apskaičiuotos (mm nuo rankenos galo). Tai nėra individualūs gamyklos matavimai; matavimo pagrindas patvirtinamas rašytinėje specifikacijoje.",
      notprovided: "Šios serijos balanso vertės nepateikiamos. Neatkurkite jų iš kitos serijos.",
    },
    optionsTitle: "Tikslumas, rankenos dydis ir svoris",
    notPublished: "Šiai serijai nepaskelbta: stygų raštas, ilgis, rėmo profilis, įtempimo intervalas ir mosto svorio bei standumo vertės. Jas galite nurodyti kaip pageidaujamas tikslines vertes techniniam įvertinimui.",
    offerTitle: "Kas vyksta po jūsų užklausos",
    offerSteps: [
      ["Užklausa", "Pateikite konfigūraciją arba klausimą. Užklausos numeris parodomas iškart."],
      ["Įvertinimas", "MAXIMUS įvertina seriją, klasę, svorį, rankenos dydį ir visas pageidaujamas tikslines vertes."],
      ["Rašytinis atsakymas", "Specifikacija, prieinamumas ir komercinės sąlygos patvirtinami raštu."],
    ],
    faqTitle: "Klausimai",
    faq: [
      ["Ar balanso vertės yra išmatuotos?", "Jos apskaičiuotos katalogo svoriams, o ne individualūs matavimai. Matavimo pagrindas patvirtinamas rašytinėje specifikacijoje."],
      ["Ar galiu paprašyti svorio, kurio nėra kataloge?", "Taip, kaip individualios tikslinės vertės sveikais gramais. Ji įvertinama techniškai, o įgyvendinamumas patvirtinamas raštu."],
      ["Ką pakeičia tikslumo klasė?", "Tai, kaip griežtai svoris, balansas, mosto svoris ir standumas išlaikomi prie deklaruotos specifikacijos, ir tai, kokie įrašai saugomi."],
      ["Ar rankena sustiprinama viršutinėmis apvijomis?", "Ne. L0–L7 yra gamykloje suformuotos anglies pluošto rankenų geometrijos."],
      ["Kur yra kainos ir pristatymo terminai?", "Jie patvirtinami raštu kiekvienai užklausai ir čia neskelbiami."],
    ],
    faqSpinBalance: ["Iš kur atsiranda SPIN balanso vertės?", "Iš patvirtintos Spin serijos lentelės: 33 svorio variantai su balansu milimetrais nuo rankenos galo. Kiekviena pora atitinka skaičių, atspausdintą ant to svorio patvirtintos vizualizacijos. Vertės neskaičiuojamos ir neišlyginamos tarp gretimų svorių."],
    ctaBuild: "Konfigūruoti šią seriją",
    ctaAsk: "Paklausti apie šią seriją",
    ctaCompare: "Palyginti visas serijas",
    weightsLabel: "katalogo svoriai",
    headLabel: "galva",
  },
  precision: {
    title: "Tikslumas ir standumas",
    switch: { label: "Pasirinkite tikslumo klasę", panelLabel: "Keturi valdomi parametrai —", qcLabel: "Kokybės kontrolės architektūra", protocolNote: "pagal gamykloje nustatytą kokybės kontrolės matavimo protokolą", fullTable: "Visa palyginimo lentelė" },
    lead: "Keturi parametrai, valdomi kaip viena inžinerinė sistema. Kiekviena klasė nustato, kaip griežtai gatava raketė išlaikoma prie savo deklaruotos specifikacijos ir kokie kokybės įrašai sudaromi.",
    statement: "Svoris. Balansas. Mosto svoris. Standumas. Valdomi kaip viena inžinerinė sistema.",
    classes: {
      "P2.5": { name: "Keičiamo masto charakteristikų pagrindas", qc: "Individualus matavimas ir saugomi gamybos įrašai." },
      "P1.5": { name: "Pažangus tikslumas", qc: "Individualus matavimas, individualūs įrašai ir atsekamumas." },
      "P0.5": { name: "Profesionali · individualiai kontroliuojama", qc: "Individuali kontrolė su nominaliosiomis ir faktinėmis vertėmis bei individualūs matavimo įrašai; serijos numerio tapatybė, partijos atsekamumas, tikslumo sertifikatas ir suderinti komplektai tais atvejais, kai užsakymo programa juos numato." },
    },
    columns: { cls: "Klasė", weight: "Svoris", balance: "Balansas", sw: "Mosto svoris", stiff: "Standumas", qc: "Kokybės kontrolės architektūra" },
    stiffTarget: "tikslinės vertės tolerancija",
    stiffExact: "atitinka deklaruotą RA tikslinę vertę pagal gamykloje nustatytą matavimo protokolą",
    programmeNote: "Serijos numerio tapatybė, sertifikatai ir suderinto komplekto dokumentacija išduodami tik tais atvejais, kai konkretaus užsakymo programa juos numato.",
    targetsNote: "Standumo specifikacijos yra gamybos tikslinės vertės, kol atitinkamas protokolas ir gamybos įrodymai neleidžia teigti daugiau. Architektūros pasiūlymas nereiškia, kad kiekviena išvardyta konfigūracija jau būtų perėjusi visą keturių parametrų išleidimo procesą.",
    stiffnessTitle: "Kodėl standumas svarbus",
    stiffnessP1: "Rėmo standumas veikia tai, kaip rėmas reaguoja kontakto momentu, kokį pojūtį sukuria ir kaip vienodos tarpusavyje yra dvi raketės. Pagrindinė jo valdymo nauda yra pakartojamas atsakas deklaruotos specifikacijos atžvilgiu.",
    stiffnessP2: "Prieš paskelbiant patikrintą atitiktį, vidinis kokybės kontrolės įrašas nurodo matavimo prietaisą, jo kalibravimo būseną, metodą, raketės stovį, skiriamąją gebą, matavimo neapibrėžtį, pakartotinius matavimus, apvalinimo taisyklę ir priėmimo taisyklę. Identiškas parodytas sveikasis skaičius nėra nulinio fizinio kitimo ar nulinės matavimo paklaidos įrodymas.",
    fields: ["Tikslinė vertė", "Išmatuotas rezultatas", "Leidžiama tolerancija", "Matavimo prietaiso geba"],
    fieldsNote: "Saugomi kaip atskiri laukai kiekviename įraše.",
    matchedTitle: "Suderinti komplektai",
    matchedP: "Suderinto komplekto kriterijai apibrėžiami atskirai nuo individualios tolerancijos. Kiekvienos raketės atitiktis savo nominaliajai tolerancijai savaime neįrodo konkretaus didžiausio skirtumo tarp dviejų raketių. Suderintų porų, trejetų ir komandos komplektų prašoma per konfigūratorių, o patvirtinami jie raštu.",
    extendedTitle: "Išplėstinis techninis modelis",
    extendedP: "Duomenų modelis palaiko papildomus parametrus. Jiems dar nėra nei verčių, nei tolerancijos klasių; juos galima nurodyti kaip pageidaujamas tikslines vertes techninėje užduotyje.",
    extended: { twistweight: "Sąsūkos svoris", torsionalBehaviour: "Sąsūkos elgsena", length: "Ilgis", beamProfile: "Rėmo profilis", headGeometry: "Galvos geometrija", stringPattern: "Stygų raštas", durability: "Patvarumas", vibration: "Vibracijos rodikliai" },
    noZero: "MAXIMUS neapibūdina savo katalogo asortimento kaip turinčio nulinę toleranciją. Tikslumas šiame asortimente nurodomas kaip klasė su deklaruota tolerancija ir nustatyta kokybės kontrolės architektūra. ZERO nėra šio asortimento dalis.",
    zero: {
      eyebrow: "Išskirtinė galimybė",
      title: "ZERO",
      sub: "Nulinė tolerancija iki gramo.",
      p: "Trys klasės išlaiko gatavą raketę deklaruoto intervalo ribose. ZERO tą intervalą panaikina. Raketė gaminama ir matuojama tol, kol rodmuo tampa lygus deklaruotam skaičiui gamyklinio matavimo prietaiso skiriamojoje geboje, ir tas rodmuo išduodamas kartu su ja. Tai nėra katalogo asortimento dalis ir ne ketvirta klasė: tai derinama individualiai, vienai raketei arba vienam suderintam komplektui, kaip išskirtinis individualus gaminys. Susitarus toks pat požiūris taikomas balansui ir mosto svoriui.",
      points: [
        ["Intervalo nėra", "Deklaruotas skaičius yra rezultatas, o ne tolerancijos vidurys."],
        ["Po vieną", "Pagaminta, išmatuota ir užregistruota kaip vienas vienetas."],
        ["Išduodama kartu su rakete", "Išmatuotas rodmuo perduodamas ir saugomas gamybos įraše."],
        ["Patvirtinta raštu", "Parametrai, apimtis ir įvykdymo terminas suderinami prieš gamybą."],
      ],
      note: "Suderinta gamyklinio matavimo prietaiso skiriamojoje geboje. Identiškas parodytas skaičius nėra teiginys apie nulinį fizinį kitimą. Prieinamumas ir sąlygos derinami individualiai kiekvienam užsakymui.",
      cta: "Pateikti ZERO užklausą",
    },
    cta: "Konfigūruoti su tikslumo klase",
  },
  grip: {
    title: "Gamyklinė rankenos architektūra",
    statement: "Aštuoni gamykliniai rankenos dydžiai. L0–L7.",
    lead: "Rankenos geometrija yra anglies pluošto rankenos architektūros dalis. Kiekvienas dydis pagamintas kaip rankenos geometrija, o ne sustiprintas viršutinėmis apvijomis.",
    emph: "Išplėstiniai dydžiai",
    p1: "Aštuonių dydžių gamyklinis asortimentas treneriams ir žaidėjams suteikia platesnį konfigūracijos intervalą, kuriame įrangą galima specifikuoti pagal žaidėją, įskaitant didesnes L6 ir L7 geometrijas.",
    p2: "Nominalusis rankenos žymėjimas atskiriamas nuo rankenos struktūros neapdorotų matmenų ir nuo galutinio matavimo protokolo. Dydžiai taikomi šios platformos varžybinėms serijoms ir treniruočių grupėms.",
    p3: "Dėl šio asortimento neteigiama jokia pasaulinio masto išimtinė teisė.",
    columns: { size: "Dydis", nominal: "Nominalusis", family: "Taikoma" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigūruoti su savo rankenos dydžiu",
  },
  custom: {
    title: "Individualūs inžineriniai sprendimai",
    statement: "Pagaminta pagal specifikaciją.",
    sub: "Standartinis asortimentas yra atspirties taškas.",
    lead: "MAXIMUS priima techninius reikalavimus, kurie viršija paskelbtas konfigūracijos matricas, kad juos įvertintų, suprojektuotų, validuotų ir pagamintų pagal suderintą specifikaciją. Įgyvendinamumas patvirtinamas įvertinimo metu — ne kiekviena įsivaizduojama užklausa yra fiziškai ar komerciškai įgyvendinama.",
    scopeTitle: "Ką gali apimti techninė užduotis",
    scope: ["Galvos ir rėmo geometrija", "Ilgis", "Svoris", "Balansas", "Mosto svoris", "Standumas", "Sąsūkos svoris", "Rankenos geometrija", "Konstrukcija", "Suderinti komplektai", "Treniruočių rėmai", "Dizainas ir graviūra", "Tapatybės ir komandos programos", "Nuo įrankių priklausoma kūrimo veikla"],
    processTitle: "Procesas",
    process: [
      ["Apibrėžti", "Pageidaujamos tikslinės vertės, privalomi apribojimai, numatytas naudojimas ir priimtini kompromisai."],
      ["Projektuoti", "Inžinerinis vertinimas platformos ir įrankių atžvilgiu."],
      ["Validuoti", "Validavimas suderintos specifikacijos atžvilgiu."],
      ["Specifikuoti", "Rašytinė specifikacija su matavimo pagrindu ir tolerancijomis."],
      ["Gaminti", "Gamyba pagal specifikaciją."],
      ["Matuoti / registruoti", "Matavimas ir saugomi įrašai pagal taikomą tikslumo klasę."],
    ],
    formTitle: "Pateikti techninę užduotį",
    formLead: "Atskirkite pageidaujamas tikslines vertes nuo privalomų apribojimų. Rezultatas yra techninio įvertinimo užklausa, o ne automatiškai priimtas gamybos užsakymas.",
    protected: "Sluoksniavimo receptai, įrankiai, tiekėjų duomenys, vidinė savikaina ir saugoma praktinė patirtis šiuo keliu neatskleidžiami.",
    cta: "Pateikti techninę užduotį",
  },
  training: {
    title: "Treniruočių sistemos",
    lead: "Dvi treniruočių grupės su savais gamybos standartais, kurias sieja viena metodika: trenerio vadovaujamas darbas, įrašai, pakartotinis įvertinimas ir grįžimas į varžybinį žaidimą.",
    sst: { h: "Sweet Spot Trainer", p: "50 in² sumažintos galvos treniruočių raketė keturių svorių sistemoje centruotam kontaktui pratinti, tiksliausios zonos pajautai, raketės kontrolei ir laipsniškam krūviui." },
    spot: { h: "Spot Trainer", p: "Kontakto taško treniruotė su nedideliu apvaliu kontakto taikiniu, ant patvirtinto keturių svorių pagrindo." },
    method: { h: "Metodika", p: "Nusistatykite tikslus, pasirinkite įrangą su trenerio įsitraukimu, naudokite atitinkamą sistemą, registruokite, įvertinkite iš naujo, pakoreguokite ir perkelkite." },
    experience: "Paimkite. Mostelėkite. Pajuskite.",
    experienceP: "Paprašykite išbandymo, pritaikymo arba trenerio palaikomos demonstracijos. Pateikta užklausa nėra patvirtintas susitikimas.",
    cta: "Paprašyti pritaikymo arba demonstracijos",
    distinct: "Sweet Spot Trainer, Spot Trainer ir bet kuris atskiras demonstracinis įtaisas yra skirtingi produktai ir niekada nesujungiami.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Atskira treniruočių kategorija su savu gamybos standartu. 50 in² galva nukreipia dėmesį į kontakto vietą; keturi svoriai sudaro krūvio laipsniškumą.",
    baseline: "Patvirtintas pagrindas",
    columns: { head: "Galva", length: "Ilgis", pattern: "Stygų raštas", grips: "Gamykliniai rankenos dydžiai" },
    systemTitle: "Keturių raketių sistema",
    detailsTitle: "Konstrukcijos detalės",
    systemLead: "Svoris ir balansas tokie, kokie pateikiami. Matavimo pagrindas registruojamas atskirai ir dar nėra paskelbtas.",
    purposeTitle: "Paskirtis",
    purpose: ["Centruoto kontakto pratimai", "Tiksliausios zonos pajauta", "Raketės kontrolė", "Laipsniškas krūvis", "Trenerio vadovaujama plėtra", "Grįžimas prie žaidėjo varžybinės raketės"],
    heavy: "400 g modelis yra valdoma treniruočių konfigūracija. Jis nerekomenduojamas automatiškai vaikams, pradedantiesiems ar kiekvienam žaidėjui; krūvį, trukmę ir laipsniškumą nustato treneris.",
    precisionNote: "Varžybinių raketių tikslumo klasės P2.5, P1.5 ir P0.5 šiai treniruočių grupei automatiškai netaikomos. Treniruočių gamybos tolerancijos atitinka šios grupės pačios patvirtintą specifikaciją.",
    health: "Teniso alkūnės prevencija ar gydymas, traumų išvengimas ar garantuotas pagerėjimas nėra žadami.",
    cta: "Paprašyti Sweet Spot Trainer demonstracijos",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Kontakto taško treniruotė su nedideliu apvaliu kontakto taikiniu. Atskiras produktas su savo vizualine tapatybe, sukurtas ant patvirtinto keturių svorių pagrindo.",
    purposeTitle: "Patvirtinta paskirtis",
    purposeP: "Išmokyti žaidėją rasti ir pakartoti tikslų kontakto tašką.",
    weightsTitle: "Svorių laipsniškumas",
    weightsP: "Svorių laipsniškumas atitinka patvirtintą Sweet Spot Trainer svorių pagrindą. Balanso vertės ir kitos Sweet Spot Trainer specifikacijos į Spot Trainer neperkeliamos.",
    dims: "Tikslūs taikinio matmenys dar nepaskelbti.",
    grips: "Gamyklinė rankenos architektūra L0–L7.",
    notes: ["Varžybinių raketių tikslumo klasės netaikomos automatiškai.", "Tai nėra įprastos raketės miniatiūra ir stygų raštas neskelbiamas.", "Spot Trainer, Sweet Spot Trainer ir bet kuris atskiras demonstracinis įtaisas lieka atskiriami."],
    cta: "Paklausti apie Spot Trainer",
  },
  methodology: {
    title: "Metodika ir produkto patirtis",
    lead: "Įranga yra viena struktūruoto plėtros kelio dalis. Metodas pradedamas nuo žaidėjo tikslų, o ne nuo produkto pavadinimo.",
    stepsTitle: "Plėtros kelias",
    steps: [
      ["Nusistatykite tikslus", "Žaidėjo tikslai ir atspirties taškas."],
      ["Pasirinkite įrangą", "Tinkama įranga, parinkta su trenerio įsitraukimu."],
      ["Naudokite sistemą", "Atitinkama treniruočių sistema, vadovaujant treneriui."],
      ["Registruokite", "Pastebėjimai apie faktinį dalyvavimą, be išgalvotų rezultatų."],
      ["Įvertinkite iš naujo", "Palyginami kontroliniai taškai."],
      ["Pakoreguokite", "Konfigūracijos arba programos korekcijos."],
      ["Perkelkite", "Išmokta perkeliama atgal į varžybinį žaidimą."],
    ],
    educationTitle: "Mokymosi keliai",
    education: { player: "Žaidėjai — konfigūracijos, krūvio ir laipsniškumo supratimas.", parent: "Tėvai — plėtros tęstinumas, tinkama įranga, įrašai ir teisės.", coach: "Treneriai — treniruočių sistemos, pritaikymas, vertinimas ir įgaliotų programų naudojimas." },
    evidenceTitle: "Įrodymų disciplina",
    evidenceP: "Faktinio dalyvavimo įrašai ir pastebėjimai saugomi su savo klasifikacija — dalyvio nurodyta, globėjo patvirtinta, trenerio validuota ar sistemos išmatuota. Pažanga, rezultatai ir validavimas niekada neišgalvojami.",
    experienceTitle: "Paimkite. Mostelėkite. Pajuskite.",
    experienceP: "Išbandymo, pritaikymo arba trenerio palaikomos demonstracijos galima paprašyti. Pateikta užklausa nėra patvirtintas susitikimas.",
    cta: "Paprašyti pritaikymo arba demonstracijos",
    cta2: "Trenerio partnerystės užklausa",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — vedamas įrangos profilis",
    title: "MAXIMUS GPS",
    lead: "Vedamas įrangos profilis. Atsakykite tik į tai, kas aktualu; peržiūrėkite ir pataisykite savo atsakymus; gaukite suvestinę, taikomas konfigūracijos kryptis ir tikrą tolesnį veiksmą.",
    honesty: "Šioje versijoje automatinės pritaikymo taisyklės nėra patvirtintos. Todėl GPS sudaro aiškią reikalavimų suvestinę ir nurodo konfigūracijos kryptis; įrangos detalės nukreipiamos eksperto įvertinimui.",
    rulesVersion: "Taisyklių versija",
    dataVersion: "Produkto duomenų versija",
    steps: { role: "Vaidmuo", sport: "Sporto rūšis", experience: "Patirtis", objectives: "Tikslai", style: "Žaidimo stilius", equipment: "Dabartinė įranga", preference: "Pageidavimai", coach: "Trenerio įsitraukimas", ageBand: "Amžiaus grupė", review: "Apžvalga" },
    notStored: "Šioje naršyklėje nesaugoma.",
    ageNote: "Naudojama tik užklausai nukreipti. Vardo, gimimo datos ar medicininės informacijos neprašoma.",
    q: {
      role: "Kas jus apibūdina?",
      sport: "Kuri sporto rūšis?",
      experience: "Patirties lygis",
      objectives: "Kas svarbiausia? (pasirinkite iki trijų)",
      style: "Žaidimo stilius, jei žinomas",
      equipment: "Dabartinė įranga, jei turite",
      equipmentHint: "Prekės ženklas ir modelis, svoris ar rankenos dydis, jei juos žinote. Neprivaloma.",
      preference: "Pageidaujama konfigūracija arba žinomas rankenos dydis",
      grip: "Žinomas rankenos dydis",
      coach: "Ar treneris įtrauktas į jūsų sprendimus dėl įrangos?",
      ageBand: "Žaidėjo amžiaus grupė (naudojama tik užklausai tinkamai nukreipti)",
    },
    roles: { player: "Žaidėjas", parent: "Tėvas, mama ar globėjas", coach: "Treneris", club: "Klubas ar akademija", other: "Kita" },
    sports: { tennis: "Tenisas", padel: "Padelis", pickleball: "Pickleball", squash: "Skvošas", badminton: "Badmintonas", other: "Kita raketių sporto rūšis" },
    sportNote: "Produktai yra tenisui. Kitos sporto rūšys yra plėtros kryptys; jūsų susidomėjimas užrašomas atitinkamai programai.",
    experience: { beginner: "Pradedantysis", developing: "Augantis", intermediate: "Vidutinis", advanced: "Patyręs", competitive: "Varžybinis", professional: "Profesionalas" },
    objectives: { control: "Kontrolė", power: "Galia", spin: "Sukimas", comfort: "Komfortas", manoeuvrability: "Valdomumas", development: "Ilgalaikė plėtra", competition: "Varžybos", training: "Treniruočių sistema", team: "Komanda ar suderintas komplektas", personal: "Personalizavimas" },
    styles: { baseline: "Nuo galinės linijos", allcourt: "Universalus", attacking: "Atakuojantis", defensive: "Gynybinis", coach: "Trenerio parinktas", unknown: "Tiksliai nežinau" },
    ageBands: { u10: "Iki 10 metų", u14: "10–13", u18: "14–17", adult: "18 ir vyresni" },
    output: {
      title: "Jūsų įrangos profilis",
      status: "Reikalingas eksperto įvertinimas",
      statusP: "Šioje versijoje automatinis atitikimas nesudaromas. Jūsų profilis apibendrintas eksperto įvertinimui.",
      directionsTitle: "Taikomos konfigūracijos kryptys",
      directionsP: "Pagrįstos jūsų nurodytais tikslais ir kiekvienos serijos deklaruota žaidimo kryptimi. Tai kryptis, o ne pritaikymo rekomendacija.",
      trainingHint: "Tarp jūsų tikslų yra treniruočių sistema: žiūrėkite Sweet Spot Trainer ir Spot Trainer.",
      teamHint: "Suderintų komplektų prašoma per konfigūratorių, o patvirtinami jie raštu.",
      next1: "Siųsti profilį eksperto įvertinimui",
      show: "Parodyti mano profilį",
      configure: "Konfigūruoti",
      sendP: "Išsiųskite savo profilį MAXIMUS eksperto įvertinimui. Užklausos numeris parodomas iškart; atsakymas pateikiamas raštu.",
      otherSport: "MAXIMUS raketės yra tenisui. Kitoms raketių sporto rūšims jokia teniso serija nesiūloma; jūsų susidomėjimas užrašomas kaip plėtros kryptis.",
      noDirection: "Jūsų tikslai nerodo vienos žaidimo krypties. Eksperto įvertinimas pasiūlys konfigūraciją.",
      incomplete: "Kai kurių privalomų atsakymų nėra — pasinaudokite „Keisti atsakymus“, kad juos užpildytumėte.",
    },
    privacy: "GPS neprašo sveikatos informacijos ir vaiko identifikuojančių duomenų. Šioje naršyklės sesijoje paliekami tik pasirinkimo atsakymai; laisvas tekstas nesaugomas.",
  },
  build: {
    title: "Sukurkite savo raketę",
    lead: "Sukonfigūruokite užklausą: serija, tikslumo klasė, katalogo svoris arba individuali tikslinė vertė, rankenos dydis, pageidaujamos tikslinės vertės, personalizavimas, suderinti komplektai ir kiekis. Rezultatas yra konfigūracijos užklausa su užklausos numeriu — o ne prekės kodas, kaina, pristatymo data ar sertifikatas.",
    steps: { series: "Serija", cls: "Tikslumo klasė", weight: "Svoris", grip: "Rankena", targets: "Tikslinės vertės", personal: "Personalizavimas", set: "Komplektas ir kiekis", use: "Naudojimas", review: "Apžvalga" },
    q: {
      series: "Pasirinkite seriją",
      cls: "Pasirinkite tikslumo klasę",
      weightMode: "Svoris",
      listed: "Katalogo svoris",
      customWeight: "Pageidaujamas svoris (g)",
      balanceShown: "Apskaičiuotas šio svorio balansas",
      balanceRequest: "Pageidaujamas balansas (mm)",
      grip: "Gamyklinis rankenos dydis",
      targetsTitle: "Pageidaujamos tikslinės vertės",
      swingweight: "Pageidaujamas mosto svoris (kg·cm²)",
      stiffness: "Pageidaujamas standumas (RA)",
      basis: "Pageidaujamų verčių matavimo pagrindas",
      engraving: "Graviūros tekstas",
      engravingHint: "Vardas, inicialai ar numeris. Lotyniškos raidės, skaitmenys, tarpas, brūkšnelis, apostrofas ir taškas; iki 24 simbolių. Kiti raštai priimami dizaino patvirtinimui.",
      engravingType: "Personalizavimas",
      types: { none: "Nėra", name: "Žaidėjo vardas", initials: "Inicialai", number: "Komplekto numeris", academy: "Trenerio ar akademijos žymėjimas", team: "Komandos programa" },
      set: "Atskira raketė ar suderintas komplektas",
      use: "Numatytas naudojimas",
      uses: { play: "Asmeninis žaidimas", competition: "Varžybos", coaching: "Trenerio darbas", team: "Komanda ar akademija", retail: "Mažmeninės prekybos ar platinimo įvertinimas", other: "Kita" },
      notes: "Papildomi techniniai reikalavimai",
    },
    classes: { "P2.5": "P2.5 — keičiamo masto charakteristikų pagrindas", "P1.5": "P1.5 — pažangus tikslumas", "P0.5": "P0.5 — profesionali, individualiai kontroliuojama" },
    stiffExactShort: "standumas atitinka deklaruotą RA tikslinę vertę pagal gamykloje nustatytą protokolą",
    clsNote: "Kiekviena klasė valdo keturis parametrus. P0.5 yra ankšta tolerancija pagal nustatytą matavimo protokolą — ne nulinė paklaida. Serijos numerio tapatybė, sertifikatai ir suderinto komplekto dokumentacija taikomi tik tais atvejais, kai jūsų užsakymo programa juos numato.",
    listedNote: "Iš patvirtintos serijos matricos.",
    customNote: "Svoris už matricos ribų, įvertinamas techniškai.",
    balanceCaption: "Prie kiekvieno katalogo svorio nurodytas jo apskaičiuotas balansas milimetrais nuo rankenos galo. Apskaičiuotos vertės nėra individualūs matavimai.",
    spinNote: "SPIN svoriai sudaro pageidaujamą svorių architektūrą. SPIN balansas, mosto svoris ir standumas nepateikiami; jie apibrėžiami techninio įvertinimo metu.",
    customHint: "Sveiki gramai, tik skaitmenys. Individualus svoris yra techninio įvertinimo užklausa; įgyvendinamumas patvirtinamas raštu ir jokia vertė neapvalinama.",
    gripNote: "gamykloje suformuota anglies pluošto rankenos geometrija, o ne viršutinėmis apvijomis sustiprinta rankena",
    targetsLead: "Neprivaloma. Įveskite tik tas vertes, kurių jums reikia. Kiekviena užrašoma kaip pageidaujama tikslinė vertė techniniam įvertinimui, o ne kaip paskelbta specifikacija.",
    basisHint: "Privaloma, kai prašote individualaus svorio ar bet kurios tikslinės vertės: ar vertės taikomos raketei be stygų, ar su stygomis?",
    inputRange: "Priimama įvestis: {min}–{max}.",
    inputRangeNote: "Įvesties intervalai tik atmeta neįmanomus įrašus. Jie neapibūdina gamybos gebos.",
    listedBasis: "katalogo vertės — matavimo pagrindas patvirtinamas rašytinėje specifikacijoje",
    notStored: "Šioje naršyklėje nesaugoma; įveskite iš naujo, jei perkrausite puslapį.",
    artworkReview: "reikalingas dizaino patvirtinimas",
    previewNote: "Vizualinė peržiūra nerodoma: patvirtintas šio modelio graviūros šablonas dar nepaskelbtas. Jūsų tekstas renkamas dizaino patvirtinimui.",
    teamSub: "4–99 raketės komplekte",
    setsLabel: { individual: "Raketių skaičius", pair: "Suderintų porų skaičius", triple: "Suderintų trejetų skaičius", team: "Komandos komplektų skaičius" },
    teamSizeLabel: "Raketės viename komandos komplekte",
    totalLabel: "Iš viso raketių",
    racquetsUnit: "raketės",
    setRule: "Kiekis skaičiuoja komplektus: suderintoje poroje yra 2 raketės komplekte, suderintame trejete — 3.",
    restart: "Pradėti naują konfigūraciją",
    notices: { weightCleared: "Svorio {w} g nėra {series} matricoje, todėl svoris buvo išvalytas. Pasirinkite katalogo svorį arba paprašykite individualios tikslinės vertės." },
    reviewTitle: "Konfigūracijos užklausa",
    reviewP: "Patikrinkite konfigūraciją, paskui įrašykite savo kontaktinius duomenis. Užklausa išsaugoma su užklausos numeriu ir į ją atsakoma raštu; prieinamumas ir komercinės sąlygos patvirtinami raštu.",
    reviewErrors: "Kai kuriems konfigūracijos atsakymams reikia dėmesio:",
    edit: "Keisti",
    fieldNames: { series: "Serija", cls: "Tikslumo klasė", mode: "Svorio pasirinkimas", weight: "Katalogo svoris", customWeight: "Pageidaujamas svoris", basis: "Matavimo pagrindas", balanceReq: "Pageidaujamas balansas", sw: "Pageidaujamas mosto svoris", ra: "Pageidaujamas standumas", grip: "Rankenos dydis", ptype: "Personalizavimas", engraving: "Graviūros tekstas", setType: "Komplekto tipas", sets: "Kiekis", teamSize: "Raketės viename komandos komplekte", use: "Numatytas naudojimas", notes: "Papildomi reikalavimai" },
    status: { listed: "katalogo svoris", requestedArchitecture: "pageidaujama svorių architektūra", technicalReview: "techninio įvertinimo užklausa", notPublished: "nepateikta", requestedCondition: "pageidaujama būklė" },
    chooseLink: "Nežinote, kuri serija tinka? Gaukite pagalbos renkantis",
    cta: "Pateikti konfigūracijos užklausą",
  },
  experience: {
    title: "Išbandymas ir pritaikymas",
    statement: "Paimkite. Mostelėkite. Pajuskite.",
    lead: "Paprašykite išbandymo, pritaikymo arba trenerio palaikomos demonstracijos. Užklausos įvertinamos ir į jas atsakoma raštu; pateikta užklausa nėra patvirtintas susitikimas.",
    optionsTitle: "Ko galima paprašyti",
    options: ["Raketės išbandymas", "Pritaikymo seansas", "Trenerio palaikoma demonstracija", "Sweet Spot Trainer arba Spot Trainer demonstracija", "Komandos ar akademijos bandymų diena"],
    formTitle: "Pritaikymo arba demonstracijos užklausa",
  },
  engineering: {
    title: "Inžinerija ir gamyba",
    statement: "Orlaiviai. Jachtos. Raketės.",
    lead: "Viena inžinerijos filosofija trijose aplinkose: principai, kurie formuoja orlaivį, tikslumas, kuris veda jachtą atviroje jūroje, ir charakteristikos, kurios apibrėžia kiekvieną MAXIMUS raketę. Tai inžinerinis pasakojimas — o ne teiginys apie orlaivių sertifikavimą, jachtos ar gamyklos priklausomybę arba tiesioginį medžiagų perkėlimą.",
    manifesto: ["Tikime, kad didelė inžinerija neturi ribų.", "Viena filosofija. Suprojektuota be kompromisų."],
    capabilityTitle: "Gamybos geba",
    capabilityLead: "Geba parodoma kaip seka, o ne kaip šūkis.",
    sequence: [
      ["Specifikacija", "Serija, tikslumo klasė, svoris, balansas, mosto svoris, standumo tikslinė vertė, rankenos geometrija, personalizavimas."],
      ["Gamyba", "Vien iš anglies pluošto konstrukcija nuo rėmo iki rankenos, pagaminta pagal specifikaciją."],
      ["Kokybės kontrolė", "Matavimas ir įrašai pagal tikslumo klasę: gamybos įrašai, individualūs įrašai ir atsekamumas, individualus sertifikavimas."],
      ["Pakartotinė gamyba", "Pakartojamas atsakas deklaruotos specifikacijos atžvilgiu skirtingose partijose."],
      ["Atsekamumas", "Serijos numerio tapatybė, partijos atsekamumas ir tikslumo sertifikatas tais atvejais, kai klasė jį numato."],
    ],
    capacityNote: "Gamybos pajėgumas, įvykdymo terminai, minimalūs kiekiai ir pristatymo grafikai patvirtinami kiekvienai programai raštu pagal patvirtintus užsakymus ir suderintą išleidimo grafiką.",
    truth: "Pajėgumas nėra produkcija, atsargos, garantuota pristatymo data ar gamybos įmonės priklausomybė.",
    cta: "Platinimas ir šalies plėtra",
    cta2: "Pateikti techninę užduotį",
  },
  ecosystem: {
    title: "MAXIMUS ekosistema",
    lead: "Vienas raktas. Štai ką jis atveria. Kiekvienas mazgas turi paaiškinimą, tikslią būseną ir aktualų tolesnį veiksmą.",
    words: ["Inžinerija", "Charakteristikos", "Inovacija", "Bendruomenė", "Galimybė", "Paskirtis"],
    nodes: {
      engineering: { h: "Raketių inžinerija ir gamyba", p: "Vien iš anglies pluošto raketės, suprojektuotos pagal specifikaciją ir pagamintos su kokybės įrašais bei atsekamumu.", a: "Inžinerija ir gamyba" },
      precision: { h: "Tikslumas ir individuali konfigūracija", p: "Keturi parametrai, trys tikslumo klasės, aštuoni rankenos dydžiai ir individualūs inžineriniai sprendimai.", a: "Tikslumas ir standumas" },
      training: { h: "Treniruotės ir metodika", p: "Sweet Spot Trainer, Spot Trainer ir struktūruotas plėtros kelias.", a: "Treniruočių sistemos" },
      development: { h: "Žaidėjo ir trenerio plėtra", p: "Trenerio vadovaujamas parinkimas, įrašai, pakartotinis įvertinimas ir mokymosi keliai.", a: "Metodika" },
      identity: { h: "Asmeninė tapatybė ir asmeniniai prekių ženklai", p: "Nuo graviūros iki teisėmis sutvarkyto asmeninio ar profesinio prekių ženklo.", a: "Asmeniniai prekių ženklai" },
      owners: { h: "Savininkų įrašai, žinios ir teisės", p: "Siūloma leidimais valdoma savininko saugykla įrangos, plėtros ir teisių įrašams.", a: "Savininkai ir saugykla" },
      mipa: { h: "MIPA kilmė ir vidinė kontrolė", p: "Vidinis intelektinės nuosavybės, kilmės ir dokumentų kontrolės lygmuo.", a: "Juridinė tapatybė ir kontrolė" },
      digital: { h: "Skaitmeninė infrastruktūra ir Blockchain 5.0 kryptis", p: "Kilmė, atsekami įrašai, leidimais valdomi įrodymai ir produkto tapatybė kaip deklaruota technologijų kryptis.", a: "Technologijų kryptis" },
      licensing: { h: "Sutartinis licencijavimas ir autorinio atlyginimo programos", p: "Licencijuoti prekių ženklai, produktai ir teisių paketai su sąlygomis, apibrėžtomis kiekvienoje sutartyje.", a: "Licencijavimo keliai" },
      families: { h: "Šeimos dalyvavimas ir programos nauda", p: "Pagrįsti sprendimai, tęstinumas, saugomi įrašai ir programoje apibrėžta nauda.", a: "Šeimos ir tėvai" },
      network: { h: "MAXIMUS Sports Network", p: "Žaidėjai, treneriai, klubai, akademijos, paslaugų teikėjai, operatoriai ir regioniniai partneriai.", a: "Sports Network" },
      market: { h: "Klubai, akademijos, platinimas ir šalies plėtra", p: "Komandos programos, mažmeninė prekyba, platinimas ir teritorijos plėtra per rašytinį kvalifikavimą.", a: "Partnerystės keliai" },
      institutional: { h: "Institucinės programos, švietimas, inovacijos ir socialinis poveikis", p: "Institucinis lygmuo, kurį teikia MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tais atvejais, kai programa nustato šį vaidmenį.", a: "Institucinės programos" },
      extensions: { h: "Būsimi raketių sporto ir MAXIMUS aprangos išplėtimai", p: "Padelis, pickleball, skvošas, badmintonas, raketbolas, paplūdimio tenisas ir apranga kaip plėtros kryptys.", a: "Raketių sporto rūšys" },
    },
    boundaryTitle: "Ribos",
    boundary: [
      "Raketės įsigijimas nesukuria institucinės narystės, valdymo teisių, autorinio atlyginimo ar investavimo teisių.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) yra institucinis operatorius tik tais atvejais, kai programa nustato šį vaidmenį; parduodant įrangą nurodoma tikroji sutarties šalis.",
      "Dotacijos, labdaros statusas, mokestinis režimas ir reguliavimo leidimai skirtingose šalyse netaikomi automatiškai.",
    ],
    techTitle: "Technologijų kryptis",
    techP: "Blockchain 5.0 yra deklaruota MAXIMUS technologijų kryptis. Jos funkcinės paskirtys yra kilmė, atsekami įrašai, leidimais valdomas įrodymų saugojimas, produkto tapatybė ir kvalifikuojamų komercinių įvykių sutikrinimas. Jokio konsensuso mechanizmo, operacijų pajėgumo, mazgų tinklo, išmaniosios sutarties adreso, žetono ar nepriklausomo sertifikavimo nepateikiama, ir joks veikiantis įgyvendinimas neteigiamas. Asmeninė informacija, vaikų įrašai ir konfidencialios sutartys pagal nutylėjimą niekada nekeliami į viešą nekintamą sistemą.",
  },
  brands: {
    title: "Asmeniniai prekių ženklai ir ambasadoriai",
    statement: "Iš žaidėjo į prekių ženklą. Iš trenerio į prekių ženklą.",
    lead: "Atskiras asmeninio prekių ženklo kelias. MAXIMUS įsitraukimas apima prekių ženklo kūrimą ir suderintą reklamą — ne tik vardą ant raketės.",
    progressionTitle: "Numatyta eiga",
    progression: [
      ["Patikrinta tapatybė", "Patikrinta tapatybė ir plėtros istorija."],
      ["Išskirtinis prekių ženklas", "Išskirtinis asmeninis ar profesinis prekių ženklas."],
      ["Teisėmis sutvarkytas turinys", "Teisėmis sutvarkytas turinys ir patvirtinta produkto tapatybė."],
      ["Inžinerija ir kolekcijos", "Inžinerija ir kolekcijų kūrimas, kai dėl to susitarta."],
      ["Reklama", "Reklama per suderintus MAXIMUS kanalus ir partnerystes."],
      ["Dalyvavimas", "Sutartinis dalyvavimas kvalifikuojamuose pardavimuose ar licencijavime."],
      ["Atsiskaitymas", "Skaidrus atsiskaitymas pagal sutartį."],
    ],
    royaltiesTitle: "Autorinis atlyginimas ir licencijavimas",
    royalties: [
      "Autorinis atlyginimas siejamas su apibrėžtu licencijuotu prekių ženklu, produktu, sandoriu ar teisių paketu.",
      "„Pardavimai visame pasaulyje“ reiškia kvalifikuojamus pardavimus sutarties apimtyje — niekada kiekvieną nesusijusią MAXIMUS raketę.",
      "Tarifai, apskaičiavimo bazė, teritorijos, terminas, grąžinimai, atskaitymai, atsiskaitymas, mokėjimai ir patikra apibrėžiami atitinkamoje sutartyje. Jokia numatytoji autorinio atlyginimo procentinė dalis neskelbiama.",
      "Be suderintos apimties nežadama jokia pasaulinė kampanija, medijos biudžetas, rėmimo rezultatas ar komercinė sėkmė.",
    ],
    cta: "Pateikti prekių ženklo bendradarbiavimo užklausą",
    cta2: "Trenerio partnerystės užklausa",
  },
  families: {
    title: "Šeimos ir tėvai",
    lead: "Pagrįsti sprendimai dėl įrangos, plėtros tęstinumas, saugomos žinios ir teisės, dalyvavimo matomumas ir programoje apibrėžta nauda, kuri gali paremti būsimą veiklą.",
    nowTitle: "Prieinama dabar",
    now: ["Šeimos ir plėtros užklausos raštu.", "Įrangos parinkimas su trenerio įsitraukimu, pritaikymo ir demonstracijos užklausos.", "Privatūs įrašai: vaikų profiliai pagal nutylėjimą niekada neskelbiami ir komerciškai nenaudojami.", "Mokymosi kelias tėvams: konfigūracija, krūvis, laipsniškumas, įrašai ir teisės."],
    plannedTitle: "Planuojama",
    planned: ["Programoje apibrėžta dalyvavimo nauda, naudojama prekėms ir paslaugoms ekosistemos viduje, o ne kaip piniginės palūkanos.", "Savininko ir šeimos įrašai siūlomoje savininko saugykloje su globėjo leidimais ir kontrolės perdavimu sulaukus 18 metų."],
    categoriesTitle: "Laikoma atskirai",
    categories: ["Sutartinis autorinis atlyginimas, kylantis iš licencijuotų teisių ar kvalifikuojamų pardavimų", "Programoje apibrėžta dalyvavimo nauda", "Pirkimo ar paslaugų kreditas", "Išankstiniai mokėjimai", "Institucinė narystė"],
    categoriesP: "Šios kategorijos niekada nelaikomos tarpusavyje pakeičiamomis.",
    statusTitle: "Tikroji šeimos programos būsena",
    journeyTitle: "Šeimos kelias",
    journey: [
      ["Tikslas", "Ką žaidėjas nori pasiekti toliau."],
      ["Dabartinis lygis", "Kur žaidėjas yra šiandien."],
      ["Treneris", "Ar treneris dalyvauja sprendimuose dėl įrangos."],
      ["Įranga", "Etapui tinkama įranga, įskaitant treniruočių sistemas, kai jos aktualios."],
      ["Suderintas darbas", "Trenerio vadovaujamas naudojimas, suderintas iš anksto."],
      ["Apžvalga", "Pakartotinis įvertinimas palyginamuose kontroliniuose taškuose."],
    ],
    brief: {
      who: "Bet kurio etapo žaidėjų tėvai ir globėjai.",
      value: "Rašytinis atsakymas apie tinkamą įrangą, trenerio įsitraukimą ir tolesnį plėtros žingsnį.",
      now: "Šeimos užklausos raštu; parinkimas su trenerio įsitraukimu; privatūs įrašai — vaikų profiliai niekada neskelbiami.",
      next: "Pateikite šeimos užklausą žemiau. Užklausos numerį gausite iškart.",
    },
    formTitle: "Šeimos užklausa",
    formNote: "Užpildo tėvas, mama ar globėjas. Nenurodykite vaiko vardo, gimimo datos, mokyklos ar medicininės informacijos.",
    noPromise: "Įsigijimas nežada autorinio atlyginimo, investicijų grąžos, rėmimo ar vaiko plėtros finansavimo.",
    statusP: "Ši versija paaiškina modelį ir priima programos užklausas. Kaupimas, mokėjimai ir panaudojimas nebus prieinami, kol kvalifikuojami įvykiai, naudos gavėjai, finansavimo šaltinis, apskaičiavimo bazė, leidžiami naudojimo būdai, apskaitos režimas, grąžinimai, atšaukimai, galiojimo pabaiga, perleidimas, programos uždarymas ir nesutarimų sprendimas nebus apibrėžti raštu. Nė vienam likučiui nežadama niekada nemažėti, nė vienas dalyvavimas neapmoka visų treniruočių, ir kapitalo apsauga nėra numanoma.",
    cta: "Pateikti šeimos ar plėtros užklausą",
  },
  owners: {
    title: "Savininkai ir savininko saugykla",
    lead: "Savininko saugykla yra siūlomas leidimais valdomas įrangos, plėtros, žinių, turinio ir dokumentuotų teisių įrašas. Ji pateikiama kaip planuojamos savininko architektūros dalis: jokios veikiančios paskyros, likučiai, sertifikatai ar pasiekimai nerodomi.",
    nowTitle: "Dabartiniams savininkams dabar",
    now: ["Savininkų užklausos: produkto ar serijos numerio nuoroda, nustatymas, priežiūra ir įrašų užklausos raštu.", "Tikslumo sertifikatas ir suderinto komplekto dokumentacija tais atvejais, kai tikslumo klasė juos numato, perduodami kartu su produktu."],
    archTitle: "Planuojama saugyklos architektūra",
    arch: ["Produkto tapatybė ir serijos numerių nuorodos", "Konfigūracija ir taikomi kokybės kontrolės sertifikatai", "Priežiūros ir nustatymo istorija", "Žaidėjo ar trenerio plėtros įrašai", "Kvalifikacijos ir patikrinti pasiekimai", "Teisėmis sutvarkyta medija ir autoriniai darbai", "Licencijos, leidimai ir sutarčių nuorodos", "Asmeninio prekių ženklo programos įrašai", "Taikomos autorinio atlyginimo ataskaitos ar dalyvavimo nauda"],
    separationTitle: "Ką reiškia nuosavybė",
    separation: [
      "Fizinės raketės nuosavybė yra atskira nuo autorių teisių, licencijos, sutartinės teisės ar tai aprašančio įrašo priklausomybės.",
      "Išsaugotas dokumentas ar blokų grandinės įrašas nėra automatinis įrodymas, kad juridinė teisė egzistuoja ar yra perėjusi.",
      "Įrodymas išlaiko savo klasifikaciją: dalyvio nurodyta, globėjo patvirtinta, trenerio validuota, sistemos išmatuota.",
      "Nepilnamečiams: privatūs įrašai, globėjo leidimai, neskelbiami vaikų profiliai ir tapatybės komercinio naudojimo atsisakymas pagal nutylėjimą.",
      "Eksportas, taisymas, prieigos kontrolė ir tinkamas kontrolės perdavimas yra sprendimo dalis.",
    ],
    techTitle: "Blockchain 5.0 ir MxSN",
    techP: "Blockchain 5.0 yra deklaruota technologijų kryptis; MxSN apibrėžia leidimais valdomo tinklo koncepcijas sutikimui, pateikimui, įrodymams, teisėms ir atsiskaitymui. Veikiantis įgyvendinimas nepateikiamas. Programos duomenų modelis sukurtas vėlesnei integracijai per dokumentuotą sąsają, neapsimetant, kad ryšys jau egzistuoja.",
    cta: "Savininko užklausa",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Ryšys tarp žaidėjų, trenerių, klubų, akademijų, paslaugų teikėjų, programų operatorių ir regioninių partnerių.",
    functionsTitle: "Galimos funkcijos",
    functions: ["Paieška", "Supažindinimas", "Plėtros programos", "Įrangos parama", "Renginiai", "Prieiga prie paslaugų", "Partnerių galimybės"],
    statusTitle: "Tikroji būsena",
    statusP: "Viešas katalogas dar nepaskelbtas: bus įtraukiami tik tie dalyviai, kurių tapatybė, ryšys ir leidimas būti parodytiems yra nustatyti. Klubui išsiųstas pasiūlymas nėra partnerystė, o potencialus platintojas nėra paskirtas platintojas. Katalogo skelbimas, rezervavimas, susirašinėjimas ir komerciniai sandoriai kontroliuojami atskirai ir dar neveikia.",
    cta: "Pateikti paraišką tinklui",
  },
  partnerships: {
    title: "Partnerystės keliai",
    lead: "Pirmiausia rašytinis kvalifikavimas. Kiekvienas kelias veda į vaidmeniui pritaikytą užklausą; komercinės sąlygos pateikiamos raštu.",
    commercialTitle: "Galimos platformos komercinės veiklos",
    commercial: ["Įranga", "Individualūs inžineriniai sprendimai", "Personalizavimas", "Komandos ir akademijos programos", "Treniruočių sistemos", "Sutartinis licencijavimas", "Platinimas", "Patvirtintos paslaugos", "Būsimos produktų kategorijos"],
    boundary: "Šalies teisės, išimtinumas, teritorijos mokesčiai ir platintojų antkainiai yra išsiderėtos sąlygos. Neskelbiamos jokios pajamos, prognozės, vertinimai, rinkos dalys, grąža, finansavimo įsipareigojimai ar neįvardytos partnerystės.",
    routes: {
      coaches: {
        title: "Treneriai",
        lead: "Treniruočių sistemos, pritaikymas, profesinė tapatybė, įgaliotos programos, asmeninio prekių ženklo galimybės ir įrangos tiekimas.",
        points: ["Sweet Spot Trainer ir Spot Trainer trenerio vadovaujamame darbe.", "Pritaikymas su konfigūracijos matricomis ir aštuoniais gamykliniais rankenos dydžiais.", "Coach-to-Brand: patikrintas profesinis profilis ir teisėmis sutvarkytas antrinis prekių ženklas.", "Įgaliotų programų naudojimas vyksta pagal rašytinę sutartį."],
        cta: "Pateikti trenerio partnerystės užklausą",
        brief: {
          who: "Nepriklausomi treneriai ir trenerių komandos.",
          value: "Treniruočių sistemos trenerio vadovaujamam darbui, pritaikymas su serijų matricomis ir aštuoniais gamykliniais rankenos dydžiais bei kelias į profesinę tapatybę.",
          now: "Trenerių užklausos raštu. Jokie komisiniai, atlygis ar rekomendacijų tarifas neskelbiami ir nenumanomi.",
          next: "Pateikite trenerio užklausą žemiau. Sąlygos pateikiamos raštu.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubai ir akademijos",
        lead: "Komandos įranga, treniruočių sistemos, personalizavimas, plėtros programos, priežiūra ir dalyvavimas tinkle.",
        points: ["Komandos ir suderintų komplektų prašoma per konfigūratorių.", "Treniruočių sistemos ir metodika struktūruotai plėtrai.", "Personalizavimas komandos programoms patvirtintose zonose.", "Bandymų dienos, pritaikymo seansai ir dalyvavimas tinkle."],
        cta: "Pateikti klubo ar akademijos užduotį",
        brief: {
          who: "Klubai, akademijos ir komandos programos.",
          value: "Komandos ir suderinti komplektai, treniruočių sistemos, personalizavimas komandos programoms ir demonstracijų dienos.",
          now: "Klubų ir akademijų užduotys raštu; komandos komplektų prašoma per konfigūratorių.",
          next: "Pateikite klubo ar akademijos užduotį žemiau.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Platinimas ir šalies plėtra",
        lead: "Asortimentas, gamybos koordinavimas, techninė geba, teritorijos plėtra ir konfidencialus komercinis kvalifikavimas.",
        points: ["Rašytinis kontrahento, teritorijos ir kanalo kvalifikavimas.", "Asortimentas nustatomas iš konfigūracijos matricų ir tikslumo klasių.", "Teritorija, išimtinumas, apimtys, kainodara ir komercinė apsauga yra išsiderėtos sąlygos, suderinamos raštu.", "Sutarties šalis, apmokėjimo sąlygos ir pristatymo pagrindas nustatomi kiekvienam sandoriui."],
        cta: "Pateikti platinimo ar šalies plėtros užklausą",
        brief: {
          who: "Mažmenininkai, platintojai ir šalies partneriai.",
          value: "Asortimentas, nustatytas iš patvirtintų matricų, tikslumo klasių ir rankenos dydžių asortimento, su rašytiniu teritorijos ir kanalo kvalifikavimu.",
          now: "Platinimo užklausos raštu. Teritorija, išimtinumas, apimtys ir kainodara yra derybų dalykas — nė vienas iš jų nesuteikiamas per formą.",
          next: "Pateikite platinimo užklausą žemiau.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategija ir investicijos",
        lead: "Inžinerinė geba, konfigūracijos gylis, gamybos modelis, keliai į rinką, intelektinė nuosavybė, paslaugos ir plėtros galimybės.",
        points: ["Kvalifikuota strateginė diskusija ar kontroliuojama prieiga prie informacijos vyksta po rašytinio kvalifikavimo.", "Vieša informacija apsiriboja patvirtintomis produkto specifikacijomis, konfigūracijos architektūra, patikrintomis gebomis ir programų paaiškinimais.", "Pirkėjui būdinga ekonomika, savikaina, saugoma metodika ir nepaskelbtos sutartys atskleidžiamos tik pagal konfidencialumo sutartį ar sutartį."],
        cta: "Paprašyti kvalifikuotos strateginės diskusijos",
        brief: {
          who: "Investuotojai ir strateginiai partneriai.",
          value: "Kvalifikuota diskusija apie inžinerinę gebą, konfigūracijos gylį, gamybos modelį, kelius į rinką ir intelektinę nuosavybę.",
          now: "Neskelbiami jokie finansiniai rodikliai, prognozės, vertinimai ar grąža. Kontroliuojama informacija teikiama po rašytinio kvalifikavimo ir konfidencialumo sutarties.",
          next: "Paprašykite kvalifikuotos strateginės diskusijos žemiau.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institucinės programos",
        lead: "Švietimas, prieiga, inovacijos, plėtros įrodymai, socialinis poveikis ir tinkamai struktūruotos programos.",
        points: ["Institucinės programos struktūruojamos per MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tais atvejais, kai programa nustato šį vaidmenį.", "Riboto naudojimo programos lėšos ir komerciniai sandoriai lieka atskirti.", "Užklausa nėra priimtas narystės prašymas, o įrangos pirkėjas nėra institucinis narys.", "Dotacijos, labdaros statusas, mokestinis režimas ir reguliavimo leidimai priklauso nuo šalies ir niekada nelaikomi savaime suprantamais."],
        cta: "Pateikti institucinės programos užklausą",
        brief: {
          who: "Institucijos, švietimo ir plėtros programos.",
          value: "Švietimo, prieigos, inovacijų ir plėtros įrodymų programos, struktūruotos su atitinkamu operatoriumi.",
          now: "Institucinės užklausos raštu. Užklausa nėra narystės prašymas; įrangos įsigijimas nėra institucinė narystė.",
          next: "Pateikite institucinę užklausą žemiau.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Viešas ir kontroliuojamas informacijos atskleidimas",
    disclosure: {
      public: { h: "Vieša", p: "Patvirtintos produkto specifikacijos, konstrukcija, konfigūracijos architektūra, treniruočių paskirtys, patikrintos gebos, programų paaiškinimai ir partnerystės keliai." },
      qualified: { h: "Kvalifikuota užklausa", p: "Techniniai reikalavimai, kiekiai, susidomėjimas teritorija, kūrimo apimtis ir atitinkamos komercinės diskusijos." },
      controlled: { h: "Kontroliuojama konfidencialumo sutartimi ar sutartimi", p: "Vidinės formulės, išsamūs kokybės kontrolės protokolai, sluoksniavimas, įrankiai, gamybos metodai, tiekėjų duomenys, savikaina, pirkėjui būdinga ekonomika, saugoma metodika, nepaskelbtos sutartys ir jautrūs teisių įrašai." },
    },
  },
  contact: {
    title: "Kontaktai ir užklausos",
    lead: "Pasirinkite savo užklausos tikslą. Kiekviena forma renka tik tai, ko reikia jai nukreipti ir įvertinti. Į užklausas atsakoma raštu.",
    email: "El. paštas",
    instagram: "Instagram",
    legalLink: "Juridinė tapatybė",
  },
  form: {
    purposeLabel: "Užklausos tikslas",
    purposes: {
      selection: "Pagalba renkantis raketę",
      product: "Produkto užklausa",
      fitting: "Pritaikymas ar demonstracija",
      technical: "Techninė užduotis",
      config: "Konfigūracijos užklausa",
      gps: "GPS įrangos profilis",
      coach: "Trenerio partnerystė",
      club: "Klubo ar akademijos užduotis",
      distribution: "Platinimas ar šalies plėtra",
      brand: "Prekių ženklo bendradarbiavimas ar ambasadorius",
      family: "Šeimos ar plėtros užklausa",
      institutional: "Institucinė programa",
      strategic: "Strateginė ar investicijų diskusija",
      owner: "Savininko užklausa",
      network: "Paraiška į Sports Network",
      general: "Bendra užklausa",
    },
    fields: {
      name: "Vardas",
      email: "El. paštas",
      role: "Jūsų vaidmuo",
      country: "Šalis ar regionas",
      organisation: "Organizacija",
      message: "Jūsų žinutė",
      level: "Dabartinis lygis",
      objectives: "Kas svarbiausia (iki trijų)",
      currentRacquet: "Dabartinė raketė",
      grip: "Rankenos dydis, jei žinomas",
      seriesInterest: "Dominanti serija",
      quantity: "Kiekis",
      city: "Miestas ar vieta, kur vyktų seansas",
      coachInvolved: "Ar treneris įtrauktas?",
      timing: "Pageidaujamas laikas",
      targets: "Pageidaujamos tikslinės vertės",
      limits: "Privalomi apribojimai",
      use: "Numatytas naudojimas",
      tradeoffs: "Priimtini kompromisai",
      basis: "Matavimo pagrindas",
      players: "Žaidėjų skaičius",
      interests: "Interesų sritys",
      territory: "Dominanti teritorija",
      channels: "Esami kanalai ir patirtis",
      audience: "Auditorija ar disciplina",
      proposal: "Siūlomas bendradarbiavimas",
      goal: "Plėtros tikslas",
      ageBand: "Žaidėjo amžiaus grupė",
      scope: "Programos apimtis",
      interestArea: "Interesų sritis",
      productRef: "Produkto ar serijos numerio nuoroda",
      requestType: "Užklausos tipas",
      seeking: "Ko ieškote",
      consent: "Sutinku, kad MAXIMUS gali saugoti ir naudoti šiuos duomenis atsakydamas į šią užklausą. Tai nėra rinkodaros prenumerata.",
    },
    roles: { player: "Žaidėjas", parent: "Tėvas, mama ar globėjas", coach: "Treneris", club: "Klubas ar akademija", retailer: "Mažmenininkas", distributor: "Platintojas", brand: "Prekių ženklas ar ambasadorius", investor: "Investuotojas ar strateginis partneris", institution: "Institucija", other: "Kita" },
    interestOptions: { training: "Treniruočių sistemos", fitting: "Pritaikymas", identity: "Profesinė tapatybė", programmes: "Įgaliotos programos", brand: "Asmeninis prekių ženklas", supply: "Įrangos tiekimas", team: "Komandos įranga", personalisation: "Personalizavimas", development: "Plėtros programos", service: "Priežiūra", network: "Dalyvavimas tinkle" },
    ownerTypes: { setup: "Nustatymas ir konfigūracija", service: "Priežiūra", records: "Įrašai ir sertifikatai", other: "Kita" },
    strategicAreas: { engineering: "Inžinerinė geba", configuration: "Konfigūracijos gylis", manufacturing: "Gamybos modelis", routes: "Keliai į rinką", ip: "Intelektinė nuosavybė ir paslaugos", expansion: "Plėtros galimybės" },
    errors: {
      required: "Šis laukas yra privalomas.",
      too_long: "Šis įrašas per ilgas.",
      too_short: "Šis įrašas per trumpas.",
      invalid_email: "Įveskite galiojantį el. pašto adresą, pavyzdžiui vardas@example.com.",
      invalid_choice: "Pasirinkite vieną iš pateiktų variantų.",
      not_number: "Įveskite sveikąjį skaičių naudodami tik skaitmenis.",
      out_of_range: "Ši vertė yra už priimamo intervalo ribų.",
      not_in_matrix: "Šio svorio nėra pasirinktos serijos katalogo matricoje.",
      decimal_not_supported: "Įveskite sveikąjį skaičių be dešimtųjų.",
      too_many: "Pasirinkite ne daugiau kaip tris variantus.",
      consent_required: "Sutikimas reikalingas, kad MAXIMUS galėtų atsakyti į šią užklausą.",
      invalid: "Šis įrašas negalioja.",
    },
  },
  legal: {
    title: "Juridinė tapatybė ir kontrolė",
    lead: "Viešas prekių ženklas yra MAXIMUS / MAXIMUS GPS. Juridinės veiklos tapatybės yra atskiriamos ir nurodytos čia.",
    entities: {
      institutional: { role: "Institucinių programų lygmuo", p: "Teikia institucinių programų lygmenį tais atvejais, kai programa nustato šį vaidmenį. Nėra komercinis raketių pardavėjas. Nepelno siekianti registruota organizacija Dubajaus tarptautiniame finansų centre." },
      equipment: { role: "Įrangos komercinis subjektas", p: "Įrangos komercinis subjektas tiekimui, platinimui ir sutartiniam komerciniam vykdymui tais atvejais, kai galiojantys veiklos dokumentai nustato šį vaidmenį. Kiekvieno sandorio sutarties šalis nurodoma to sandorio dokumentuose." },
      ip: { role: "Intelektinės nuosavybės, prekių ženklo ir komercinio koordinavimo vaidmuo", p: "Pasirodo nustatytame intelektinės nuosavybės, prekių ženklo ar komercinio koordinavimo vaidmenyje. Jokia nepatvirtinta sutartinė atsakomybė nepriskiriama." },
      stewardship: { role: "Globos nuoroda", p: "House of Maximus yra ekosistemos globos nuoroda tais atvejais, kai tai patvirtina atitinkamas šaltinis." },
      control: { role: "Vidinė intelektinės nuosavybės, kilmės ir dokumentų kontrolė", p: "MIPA yra vidinis intelektinės nuosavybės, kilmės ir dokumentų kontrolės lygmuo. Vidinis MIPA įrašas atskiriamas nuo išorinio prekių ženklo, patento, autorių teisių registracijos ar teismo pripažinimo ir nėra vizualinis patvirtinimas." },
    },
    labels: { licence: "Licencija", registration: "Registracija", vat: "VAT TRN", address: "Adresas", email: "El. paštas", jurisdiction: "Jurisdikcija" },
    boundaryTitle: "Ribos",
    boundary: [
      "Įsigijimas automatiškai nesuteikia institucinės narystės, valdymo teisių, autorinio atlyginimo ar investavimo teisių.",
      "Institucinis vaidmuo yra atskirtas nuo komercinių įrangos sandorių.",
      "Privatumas, programos sąlygos ir kontroliuojamos prieigos tvarka atitinka faktiškai išleistas funkcijas.",
      "Jokia bendra taikomos teisės nuostata netaikoma kiekvienam apsilankymui, pardavimui ar užsienio programai; sutartinis pagrindas nustatomas kiekviename susitarime.",
    ],
  },
  privacy: {
    title: "Privatumas",
    updated: "Versija 2026-09-21 · svetainė 4.2",
    contactTitle: "Kontaktai privatumo klausimais",
    sections: {
      collect: ["Kas renkama", "Pateikiant formą: duomenys, kuriuos įvedate (vardas, el. paštas, vaidmuo, šalis ar regionas, organizacija, jei nurodyta, jūsų žinutė ir formos atsakymai), jūsų apsilankymo puslapio ir kampanijos parametrai (įėjimo puslapis, kalba, utm parametrai; reklamos paspaudimų identifikatoriai tik tuo atveju, jei leidote analitiką) ir pateikimo laikas. Jūsų IP adresas naudojamas tik maišos forma ir trumpai, kad būtų apribotas piktnaudžiavimas, ir nesaugomas su jūsų užklausa."],
      purpose: ["Kodėl", "Kad būtų atsakyta į jūsų užklausą, kad būtų parengtas jūsų prašomas pasiūlymas ar specifikacija ir kad būtų išsaugotas užklausos įrašas. Formos pagrindu rinkodaros žinutės nesiunčiamos."],
      storageOn: ["Kur saugomos užklausos", "Užklausos saugomos įmonės Upstash, Inc. duomenų bazėje (Redis), teikiamoje per prieglobos platformą Vercel Inc."],
      notifyEmail: ["Pranešimas apie naują užklausą", "Kai užklausa priimama, pranešimas su jūsų pateiktais duomenimis išsiunčiamas el. paštu į atsakingą MAXIMUS paštą."],
      notifyTelegram: ["Pranešimas apie naują užklausą", "Kai užklausa priimama, pranešimas su jūsų pateiktais duomenimis išsiunčiamas atsakingam MAXIMUS asmeniui per Telegram (Telegram FZ-LLC, Dubajus), kuris todėl apdoroja šį pranešimą jo persiuntimo metu."],
      notifyWebhook: ["Pranešimas apie naują užklausą", "Kai užklausa priimama, pranešimas su jūsų pateiktais duomenimis išsiunčiamas į vidinį MAXIMUS galinį tašką per pasirašytą, šifruotą ryšį."],
      notifyNone: ["Pranešimas apie naują užklausą", "Pranešimas apie naujas užklausas dar nustatomas. Jūsų užklausa išsaugoma, o MAXIMUS ją perskaito iš vidinio registro; šiuo tikslu niekas nesiunčiama trečiajai šaliai."],
      storageOff: ["Kur saugomos užklausos", "Užklausų saugojimas dar nustatomas. Kol jis neaktyvus, formos nurodo, kad užklausos priimti negalima; niekas nesaugoma. Svetainę talpina Vercel Inc."],
      browser: ["Naršyklės saugykla", "Sesijos saugykla šios naršyklės sesijos metu palaiko GPS ir konfigūratoriaus pasirinkimo atsakymus bei jūsų apsilankymo kampanijos parametrus. Kontaktiniai duomenys, laisvas tekstas, graviūros tekstas ir informacija apie vaikus naršyklėje nesaugomi."],
      analyticsOn: ["Analitika", "Jums sutikus Google Analytics 4 matuoja apsilankymus ir formų įvykius be kontaktinių duomenų ir užklausos teksto. Jūsų pasirinkimas laikomas vietinėje saugykloje ir bet kada gali būti pakeistas puslapio apačioje esančiame skyriuje „Analitikos nuostatos“. Formos veikia ir be analitikos."],
      analyticsOff: ["Analitika", "Šioje svetainėje jokia analitikos priemonė neaktyvi."],
      retention: ["Saugojimas", "Automatinis ištrynimo terminas dar nenustatytas. Galite bet kada paprašyti ištrinti savo užklausą."],
      children: ["Vaikai", "Formas turi užpildyti pilnametis. Užklausas dėl jaunesnių nei 18 metų žaidėjų pateikia tėvas, mama ar globėjas. Nepateikite vaiko vardo, gimimo datos, mokyklos ar medicininės informacijos. Vaikų profiliai niekada neskelbiami."],
      rights: ["Jūsų teisės", "Kad pasiektumėte, pataisytumėte ar ištrintumėte savo užklausą, rašykite adresu gps@maximus.tennis ir nurodykite savo užklausos numerį."],
      controlled: ["Kontroliuojama informacija", "Konfidencialūs dokumentai šioje svetainėje nesaugomi ir per ją neteikiami. Kontroliuojamas atskleidimas vyksta pagal konfidencialumo sutartį ar sutartį per atskirus kanalus."],
    },
  },
  terms: {
    title: "Naudojimo sąlygos",
    copyright: "Autorių teisės į šią svetainę — jos tekstus, fotografijas, dizainą ir kodą — priklauso vien Maximus Kiriyakulov. Jos nebuvo perleistos jokiai bendrovei ir jokiam kitam asmeniui.",
    updated: "Versija 2026-09-21",
    sections: [
      ["Informacija, o ne pasiūlymas", "Produkto informacija šioje svetainėje aprašo patvirtintas specifikacijas, konfigūracijos architektūrą ir programų paaiškinimus. Tai nėra pasiūlymas parduoti, kainų sąrašas, atsargų pareiškimas ar pristatymo įsipareigojimas. Komercinės sąlygos derinamos atskirai raštu su sutarties šalimi, nurodyta kiekviename sandoryje."],
      ["Užklausos", "Per šią svetainę pateikta užklausa — įskaitant GPS profilius, konfigūracijos užklausas ir technines užduotis — išsaugoma su užklausos numeriu ir įvertinama. Tai nėra priimtas užsakymas, gamybos įsipareigojimas, patvirtintas susitikimas, narystės prašymas ar priimta paraiška į kurią nors programą."],
      ["Specifikacijos ir įrodymai", "Apskaičiuotos vertės, gamybos tikslinės vertės ir patvirtintos specifikacijos atskiriamos atitinkamuose puslapiuose. Standumo vertės yra gamybos tikslinės vertės, kol nepaskelbta kitaip. Konkrečiam žaidėjui rezultatas negarantuojamas."],
      ["Ekosistema, narystė ir teisės", "Raketės įsigijimas nesukuria institucinės narystės, investavimo teisių, intelektinės nuosavybės priklausomybės, teisės į autorinį atlyginimą ar dalyvavimo naudos. Teisės kyla iš paskelbtų programos sąlygų ar rašytinės sutarties."],
      ["Intelektinė nuosavybė", "MAXIMUS®, liūto emblema, GPS ženklas ir šios svetainės turinys yra saugomi. Vidinės inžinerijos formulės, kokybės kontrolės protokolai, sluoksniavimas, įrankiai, tiekėjų duomenys, savikaina ir saugoma metodika čia neatskleidžiami."],
    ],
  },
  lead: {
    submit: "Pateikti užklausą",
    submitting: "Pateikiama…",
    retry: "Bandyti dar kartą",
    acceptedEyebrow: "Užklausa priimta",
    acceptedTitle: "Jūsų užklausa gauta.",
    requestId: "Užklausos numeris",
    acceptedNext: "MAXIMUS įvertina kiekvieną užklausą ir atsako raštu jūsų nurodytu el. pašto adresu. Išsaugokite užklausos numerį tolesniam susirašinėjimui.",
    duplicate: "Ši užklausa jau buvo gauta; dublikatas nebuvo sukurtas.",
    another: "Pradėti naują užklausą",
    errorsTitle: "Patikrinkite šiuos laukus:",
    failTitle: "Jūsų užklausa nebuvo pateikta.",
    fail: {
      offline: "Jūsų įrenginys neprijungtas prie tinklo.",
      network: "Ryšys su serveriu nepavyko.",
      timeout: "Serveris neatsakė laiku.",
      rate_limited: "Iš šio tinklo gauta per daug užklausų. Pabandykite dar kartą po kelių minučių.",
      too_fast: "Forma buvo pateikta labai greitai. Patikrinkite ją ir pateikite dar kartą.",
      spam_suspected: "Užklausą sustabdė šiukšlių filtras.",
      unavailable: "Šiuo metu užklausų priimti negalima.",
      default: "Įvyko netikėta klaida.",
    },
    keepNote: "Jūsų įrašyti duomenys paliekami šiame puslapyje, kad galėtumėte bandyti dar kartą.",
    sendByEmail: "Išsiųsti šią užklausą el. paštu",
    sendByEmailNote: "Jūsų el. pašto programa atsidaro su šios užklausos tekstu. MAXIMUS ją gauna, kai išsiunčiate laišką.",
    mailConfig: "Konfigūracija",
    mailPage: "Puslapis",
    fallback: "Jei problema nesibaigia, rašykite adresu {email}. Užklausa laikoma pateikta tik tada, kai parodomas užklausos numeris.",
    privacyLink: "Privatumo pranešimas",
    hpLabel: "Šį lauką palikite tuščią",
    consentShort: "Sutikimas",
    after: "Po pateikimo šiame puslapyje parodomas užklausos numeris. Užklausos įvertinamos ir į jas atsakoma raštu; užklausa nėra užsakymas.",
    basis: { unstrung: "Be stygų", strung: "Su stygomis", unknown: "Tiksliai nežinau — bus suderinta specifikacijoje" },
    hints: {
      email: "MAXIMUS atsako raštu šiuo adresu.",
      goal: "Pavyzdžiui: pirma varžybinė raketė arba perėjimas nuo jaunimo raketės. Nenurodykite vaiko vardo, gimimo datos ar medicininės informacijos.",
      currentRacquet: "Prekės ženklas ir modelis, jei žinomi.",
      message: "Nenurodykite slaptažodžių, mokėjimo duomenų ar medicininės informacijos.",
    },
  },
  choose: {
    eyebrow: "Pagalba renkantis",
    title: "Padėkite išsirinkti raketę",
    lead: "Nurodykite MAXIMUS savo lygį ir tai, kas jums svarbiausia. Jūsų atsakymai įvertinami ir jūs gaunate rašytinį pasiūlymą: serija, tikslumo klasė, svoris ir rankenos dydis.",
    stepsTitle: "Kas vyksta toliau",
    steps: [
      ["Jūsų atsakymai", "Lygis, prioritetai ir rankenos dydis, jei jį žinote."],
      ["Eksperto įvertinimas", "MAXIMUS palygina jūsų atsakymus su serijų matricomis."],
      ["Rašytinis pasiūlymas", "Pasiūlyta konfigūracija ir tolesnis žingsnis raštu."],
    ],
    formTitle: "Jūsų atsakymai",
    submit: "Paprašyti pagalbos renkantis",
    altTitle: "Norite nuspręsti patys?",
    altGps: "Išsamus GPS profilis",
    altBuild: "Konfigūruoti iškart",
    note: "Jokio automatinio pritaikymo ir jokio teiginio apie tikslumą: kiekvieną užklausą įvertina žmogus.",
  },
  consent: {
    title: "Analitika",
    text: "Ar MAXIMUS gali matuoti apsilankymus su Google Analytics? Formos veikia abiem atvejais; į analitiką nesiunčiami kontaktiniai duomenys ar užklausos tekstas.",
    allow: "Leisti analitiką",
    decline: "Atsisakyti",
  },
  familyPlan: {
    title: "Šeimos planas",
    metaDescription: "Apskaičiuokite savo šeimos teniso biudžetą: treniruotes, valandas, kontaktus su kamuoliu ir vienos treniruotės, vienos valandos bei vieno smūgio kainą — pagal savo skaičius, trimis scenarijais.",
    eyebrow: "Šeimos planas · Prisidėkite kartu su mumis",
    heroTitle: "Kiek kainuoja jūsų šeimos tenisas — ir ką už tai gaunate?",
    heroLead: "Apskaičiuokite savo šeimos biudžetą, treniruotes ir valandas, už kurias jis sumoka, numatomus kontaktus su kamuoliu ir vienos treniruotės, vienos valandos bei vieno smūgio kainą — savo sąlygomis.",
    heroCta: "Apskaičiuokite savo šeimos planą",
    strategy: {
      eyebrow: "Mūsų tikslas",
      title: "Daugiau teniso. Daugiau galimybių. Kartu.",
      p1: "Mūsų tikslas — dešimt kartų padidinti pasaulio teniso rinką, plečiant dalyvavimą ir darant kelią į tenisą aiškesnį bei prieinamesnį. MAXIMUS siekia pirmauti valdymu, metodika, kokybe, rezultatais ir žaidimo populiarinimu.",
      p2: "Kitus teniso įrangos gamintojus ir jų prekių ženklus matome kaip galimus partnerius. Siūlome sujungti įmonių, trenerių, klubų ir šeimų stipriąsias puses bendroje programoje, kuri abipusės naudos pagrindu plėtotų tenisą, jį populiarintų ir didintų jo mastą.",
      p3: "MAXIMUS yra penktasis šio požiūrio elementas: vienijantis vaidmuo, padedantis atskiroms stiprybėms veikti kartu. Mūsų bendri iššūkiai — ligos, vaikų fizinis pasyvumas ir kliūtys, trukdančios žmonėms pradėti žaisti ir žaisti toliau.",
      p4: "Šeimai viskas prasideda nuo aiškumo. Šeimos planas parodo biudžetą, treniruočių ir valandų skaičių, numatomą kontaktų su kamuoliu kiekį ir treniruočių kainą. Pakeiskite sąlygas ir pasirinkite jums tinkamą scenarijų.",
      note: "Dešimteriopas augimas yra strateginis tikslas, kurį išsikėlė MAXIMUS, o ne jau pasiektas rezultatas. Skaičiuoklė rodo scenarijų skaičiavimus ir nežada nei sutaupymų, nei medicininio poveikio, nei sportinio rezultato.",
      ctaCalc: "Apskaičiuokite savo šeimos planą",
      ctaPartner: "Aptarkime bendrą teniso plėtrą",
    },
    beyond: {
      eyebrow: "Už korto ribų",
      title: "Ką planas kuria be treniruočių",
      admission: {
        h: "Priėmimas į pirmaujančias mokyklas ir universitetus",
        p: "MAXIMUS padeda šeimai kelyje į pirmaujančias mokyklas ir universitetus visame pasaulyje: kuriant žaidėjo sportinių pasiekimų aprašą, rengiant dokumentus ir paraiškas bei renkantis programas, kuriose sportas ir mokslai eina koja kojon. Jei skiriama sportinė stipendija, ji sumažina sumą, kurią šeima moka už mokslą.",
      },
      assets: {
        h: "Skaitmeninis turtas: žaidėjo vardas, įvaizdis ir pasiekimai",
        p: "Žaidėjo vardas, įvaizdis, rezultatai, turinys ir asmeninis prekių ženklas yra turtas, ir laikui bėgant jie gali sukaupti reikšmingą finansinę ir statuso vertę. MAXIMUS padeda juos sukurti, užregistruoti ir apsaugoti, kad ši vertė liktų žaidėjui ir šeimai.",
      },
      note: "Nė viena iš šių paslaugų nėra skaičiuoklės dalis. Vietos mokykloje, stipendijos ar skaitmeninio turto vertė priklauso nuo atvejo ir čia nevertinama.",
      cta: "Klauskite apie pagalbą stojant ir skaitmeninį turtą",
    },
    steps: ["Šeimos duomenys", "Treniruotės ekonomika", "Ilgalaikis planas", "Galutinis skaičiavimas"],
    stepsLabel: "Skaičiuoklės žingsniai",
    scenarios: { now: "Dabar", planned: "Planuojama", wish: "Norima" },
    scenarioHints: { now: "Ką jūsų šeima daro šiandien.", planned: "Ką ketinate daryti toliau.", wish: "Ką norėtumėte daryti." },
    currency: {
      label: "Valiuta",
      note: "Visos jūsų įvestos sumos yra šia valiuta. Niekas nekonvertuojama.",
    },
    fields: {
      players: { label: "Žaidžiantys šeimos nariai", hint: "Sveikasis skaičius." },
      cost: { label: "Vienos treniruotės kaina vienam žaidėjui", hint: "Suma sveikuoju skaičiumi, įskaitant mokesčius ir rinkliavas." },
      sessions: { label: "Treniruotės vienam žaidėjui per mėnesį", hint: "Sveikasis skaičius." },
      minutes: { label: "Vienos treniruotės trukmė minutėmis", hint: "Visas laikas su pertraukomis. Leidžiamos dešimtainės trupmenos." },
      contacts: { label: "Kontaktai su kamuoliu vienam žaidėjui per treniruotę", hint: "Kontaktas — tai paties žaidėjo raketės prisilietimas prie kamuolio. Vienas apsikeitimas smūgiais nėra vienas kontaktas. Skaičiuokite vienodai visuose scenarijuose." },
    },
    presetsLabel: "Greitas pasirinkimas, minutės",
    ages: {
      title: "Plano trukmė",
      start: "Pradinis amžius",
      end: "Galutinis amžius",
      hint: "Anoniminė prielaida apie plano trukmę, naudojama tik ilgalaikei lentelei. Tai nėra gimimo data ir ne rekomenduojamas pradžios amžius.",
    },
    extras: {
      title: "Papildomos šeimos išlaidos",
      note: "Šios sumos skirtos visai šeimai ir taikomos visiems trims scenarijams. Jos nedauginamos iš žaidėjų skaičiaus ir neįtraukiamos į valandos ar kontakto kainą.",
      equipment: "Pirmoji įranga — viena suma visam laikotarpiui",
      clothing: "Apranga ir avalynė — viena suma visam laikotarpiui",
      renewal: "Įrangos atnaujinimas — viena suma visam laikotarpiui, automatiškai nekartojama",
      court: "Kortas ar klubas — per mėnesį, visa šeima",
      travel: "Kelionės ir renginiai — per mėnesį, visa šeima",
      quoteSource: "Iš kur paimtos kainos (neprivaloma)",
      quoteDate: "Kainų data (neprivaloma)",
      quoteNote: "Rodoma tiksliai taip, kaip įvedėte. MAXIMUS šių kainų netikrina.",
    },
    storage: {
      save: "Išsaugoti planą šiame įrenginyje",
      clear: "Išvalyti planą šiame įrenginyje",
      saved: "Planas išsaugotas šiame įrenginyje. Niekur nieko neišsiųsta.",
      cleared: "Planas išvalytas. Skaičiuoklėje atkurtos pradinės reikšmės.",
      restored: "Jūsų šiame įrenginyje išsaugotas planas atkurtas.",
      invalid: "Šiame įrenginyje išsaugoto plano nepavyko nuskaityti, todėl jis nepritaikytas. Galite pradėti naują skaičiavimą.",
      unavailable: "Ši naršyklė neleidžia išsaugoti įrenginyje.",
    },
    annual: {
      title: "Vieneri metai: scenarijai greta",
      sessions: "Žaidėjo treniruotės per metus",
      cost: "Šeimos išlaidos treniruotėms per metus",
      hours: "Žaidėjo valandos per metus",
      length: "Vienos treniruotės trukmė",
      contacts: "Kontaktai su kamuoliu per metus",
      note: "Žaidėjo treniruotės ir žaidėjo valandos sudeda visų žaidėjų treniruotes. Tai nėra korto nuomos valandos ar grupės užsiėmimai: du žaidėjai, kartu besitreniruojantys 90 minučių, sudaro 2 žaidėjo treniruotes ir 3 žaidėjo valandas.",
    },
    economics: {
      title: "Treniruotės, valandos ir kontakto kaina",
      session: "Viena vieno žaidėjo treniruotė",
      hour: "Viena vieno žaidėjo treniruotės valanda",
      contact: "Vienas kontaktas su kamuoliu",
      undefinedContacts: "Neapibrėžta: 0 kontaktų",
      undefinedMinutes: "Neapibrėžta: 0 minučių",
      below: "mažiau nei {value}",
      note: "Į šiuos skaičius įeina tik treniruotės kaina. Papildomos šeimos išlaidos nedalijamos iš kontaktų skaičiaus.",
      caption: "Kontaktų skaičius apskaičiuojamas pagal pasirinktą treniruočių apimtį ir modelio prielaidas. Faktinės treniruotės priklauso nuo formato, pertraukų ir treniravimosi sąlygų. Kontakto kaina yra biudžeto rodiklis, o ne trenerio darbo kokybės rodiklis.",
    },
    longTerm: {
      title: "Ilgalaikis išlaidų planas",
      horizon: "Horizontas",
      activeYears: "Aktyvūs metai",
      years: "{n} m.",
      note: "Aktyvius metus riboja abiejų amžių skirtumas. Kainos, dažnumas, infliacija, sezonai, praleistos treniruotės ir valiutų kursai laikomi nekintamais. Papildomos išlaidos į šią lentelę neįtrauktos.",
    },
    final: {
      title: "Galutinis skaičiavimas",
      scenario: "Scenarijus",
      months: "Laikotarpis mėnesiais",
      heading: "{scenario} · {months} mėn.",
      total: "Iš viso už laikotarpį",
      training: "Treniruotės",
      extras: "Papildomos išlaidos",
      oneOff: "Vienkartinės išlaidos",
      monthly: "Mėnesinės išlaidos × mėnesiai",
      sessions: "Žaidėjo treniruotės per laikotarpį",
      hours: "Žaidėjo valandos per laikotarpį",
      contacts: "Kontaktai su kamuoliu per laikotarpį",
      formulaTitle: "Kaip apskaičiuojama",
      formula: "Iš viso = žaidėjai × treniruotės per mėnesį × mėnesiai × treniruotės kaina + vienkartinės išlaidos + mėnesiai × mėnesinės papildomos išlaidos.",
      formulaNote: "Papildomos išlaidos įvedamos visai šeimai. Vienkartinės išlaidos įskaičiuojamos vieną kartą, net jei laikotarpis yra 0 mėnesių.",
      inputs: "Jūsų įvesti duomenys",
    },
    units: { min: "min.", h: "val.", approx: "≈" },
    errors: {
      title: "Ištaisykite šiuos laukus, kad pamatytumėte rezultatą",
      required: "Privaloma — įveskite skaičių; 0 leidžiamas.",
      negative: "Negali būti neigiamas.",
      integer: "Tik sveikasis skaičius.",
      number: "Įveskite skaičių.",
      tooLarge: "Šis skaičius per didelis skaičiavimui.",
      endBeforeStart: "Galutinis amžius negali būti mažesnis už pradinį.",
      tooLong: "Ne daugiau kaip 200 simbolių.",
      date: "Įveskite tinkamą datą.",
      currency: "Pasirinkite valiutą.",
      scenario: "Pasirinkite scenarijų.",
      result: "Rezultatas per didelis, kad būtų patikimai parodytas. Sumažinkite įvestas reikšmes.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: visa kompozicija — treniruočių raketė iš priekio ir iš šono, graviruotas liūto skydelis ant apvalios kontakto galvos, MAXIMUS ir SPOT TRAINER graviūra kakliuko ilgyje bei aštuonkampis rankenos galo dangtelis su liūto ženklu",
    greatHero: "MAXIMUS GREAT serija, 363 g: visa kompozicija su raudonu ir geltonu galvos apdailos akcentu, blizgiu MAXIMUS užrašu, Maximus autografu ant kakliuko ir liūto rankenos galo dangteliu",
    spotDetail: "Dvi MAXIMUS Spot Trainer raketės iš arčiau: graviruotas liūtas ant matiniai juodos kontakto galvos, briaunuota rankenos apvija ir aštuonkampiai rankenos galo dangteliai su liūto ženklu",
    spotPair: "Dvi MAXIMUS Spot Trainer raketės, padėtos įstrižai ant tamsaus paviršiaus, ant vieno kakliuko graviruota MAXIMUS, ant kito SPOT TRAINER, su liūto skydeliu ant kiekvienos kontakto galvos",
    spinVisual: "MAXIMUS SPIN: galva su stygomis, blizgus MAXIMUS užrašas, rankena ir liūto rankenos galo dangtelis",
    powerVisual: "MAXIMUS POWER: galva su stygomis, blizgus MAXIMUS užrašas, personalizavimo graviūra, rankena ir liūto rankenos galo dangtelis",
    greatVisual: "MAXIMUS GREAT: galva su stygomis, blizgus MAXIMUS užrašas, personalizavimo graviūra, rankena, liūto rankenos galo dangtelis ir G serijos ženklas ant kaklelio",
    spinHead: "MAXIMUS SPIN galva ir stygų laukas",
    handleLion: "MAXIMUS kaklelis, rankena ir rankenos galo dangtelis su liūto ženklu",
    engraving: "Sidabrinė personalizavimo graviūra ant kakliuko",
    lettering: "Blizgiai juodas MAXIMUS užrašas ant matiniai juodo rėmo",
    variantAlt: "MAXIMUS {series} serija — {w} g, balansas {b} mm: visa vizualizacija su specifikacijos juosta, personalizavimo graviūros zona ir MIPA žymėjimu",
    sstSystem: "MAXIMUS Sweet Spot Trainer, keturių raketių sistema",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Sweet Spot Trainer kakliukai su MAXIMUS užrašu",
    sstGrips: "Sweet Spot Trainer rankenos ir rankenos galo dangteliai",
    sstButtcaps: "Sweet Spot Trainer, keturi rankenos galo dangteliai su liūto ženklu",
    note: "Produkto vaizdas",
  },
  notFound: { title: "Puslapis nerastas", p: "Jūsų prašomo puslapio šia kalba nėra.", cta: "Eiti į pradinį puslapį" },
};

export default lt;
