/* Norwegian (Bokmål) dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const no = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — tennisracketer i helkarbon, utviklet etter spesifikasjon",
    defaultDescription:
      "Tennisracketer i helkarbon fra ramme til håndtak: GREAT 97 in², POWER 98 in² og SPIN 100 in², åtte grepsstørrelser fra fabrikk L0–L7, presisjonsklasser for vekt, balanse, swingweight og rammestivhet, og spesialutvikling på forespørsel.",
  },
  common: {
    statuses: {
      current: "Aktuell",
      agreement: "Tilgjengelig etter avtale",
      development: "Under utvikling",
      concept: "Konsept",
      target: "Produksjonsmål",
      modelled: "Beregnet",
      confirmed: "Bekreftet",
      requested: "Forespurt arkitektur",
      notprovided: "Ikke oppgitt",
    },
    brief: { who: "Hvem det er for", value: "Hva du får", now: "Bekreftet nå", next: "Neste steg" },
    labels: {
      next: "Videre",
      back: "Tilbake",
      edit: "Endre svar",
      review: "Gjennomgang",
      start: "Begynn",
      restart: "Begynn på nytt",
      copy: "Kopier forespørselsteksten",
      copied: "Kopiert",
      openEmail: "Åpne e-post for å sende denne forespørselen",
      reference: "Referanse for forespørselen",
      weight: "Vekt",
      balance: "Balanse",
      swingweight: "Swingweight",
      stiffness: "Rammestivhet",
      grip: "Grepsstørrelse",
      headSize: "Hodestørrelse",
      series: "Serie",
      precisionClass: "Presisjonsklasse",
      quantity: "Antall",
      notProvided: "Ikke publisert ennå",
      requestTarget: "Forespurt målverdi",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Les mer",
      allSeries: "Alle serier",
      points: "oppførte vekter",
      optional: "valgfritt",
      required: "påkrevd",
      select: "Velg",
      yes: "Ja",
      no: "Nei",
      unknown: "Ikke sikker",
      custom: "Egendefinert målverdi",
      listed: "Oppført vekt",
      individual: "Enkeltracket",
      pair: "Matchet par",
      triple: "Matchet trio",
      team: "Lagsett",
      summaryTitle: "Sammendrag av forespørselen din",
      nextAction: "Neste handling",
      status: "Status",
      learn: "Lær mer",
      schematic: "Skjematisk fremstilling — ikke en måling",
      photo: "Fotografi",
    },
    ecosystemStrip: "MAXIMUS-økosystemet",
    truth: {
      noPrices: "Priser, minimumsmengder, leveringstider, garantier og leveringsforpliktelser bekreftes skriftlig for hvert marked og hvert program.",
      requestNotOrder: "En forespørsel er en anmodning om vurdering. Den er ikke en akseptert ordre, en produksjonsforpliktelse eller en bekreftet avtale.",
      noGuarantee: "Ingen utstyr, metode eller program som er beskrevet her, garanterer et resultat for en bestemt spiller.",
      governing: "Denne siden er publisert på flere språk. Den engelske versjonen er den gjeldende versjonen; oversettelsen er en lesehjelp.",
    },
  },
  nav: {
    language: "Språk",
    groups: { racquets: "Racketer", training: "Trening", ecosystem: "Økosystem", partnerships: "Partnerskap" },
    familyPlan: "Familieplan",
    racquets: "Racketserier og sammenligning",
    great: "GREAT — 97 in² · Kontroll",
    power: "POWER — 98 in² · Kraft",
    spin: "SPIN — 100 in² · Spinn",
    precision: "Presisjon og rammestivhet",
    grip: "Grepsarkitektur fra fabrikk L0–L7",
    custom: "Spesialutvikling",
    training: "Treningssystemer",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodikk",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Hjelp til å velge",
    ecosystem: "Økosystemkart",
    engineering: "Utvikling og produksjon",
    experience: "Opplevelse og tilpasning",
    brands: "Personlige merkevarer og ambassadører",
    families: "Familier og foreldre",
    owners: "Eiere og eierarkivet",
    network: "Sports Network",
    partnerships: "Alle partnerskapsveier",
    coaches: "Trenere",
    clubs: "Klubber og akademier",
    distribution: "Distribusjon og landutvikling",
    strategic: "Strategi og investering",
    institutional: "Institusjonelle programmer",
    contact: "Kontakt",
    legal: "Juridisk identitet",
    privacy: "Personvern",
    terms: "Vilkår",
    menu: "Meny",
    close: "Lukk",
    home: "Forsiden",
    skip: "Gå til innholdet",
  },
  footer: {
    line: "MAXIMUS-racketen er din nøkkel til MAXIMUS-verdenen.",
    product: "Produkt",
    ecosystem: "Økosystem",
    company: "Organisasjon",
    instagram: "Instagram",
    email: "E-post",
    analytics: "Analyseinnstillinger",
    subscribe: {
      title: "Hold kontakten med MAXIMUS",
      line: "Nye serier, datoer for tilpasning, treningsmateriell og eierprogrammet. Noen få brev i året, ikke noe mer.",
      label: "E-postadresse",
      placeholder: "your@email.com",
      button: "Abonner",
      sending: "Sender",
      done: "Du står på listen. Vi skriver bare når det er noe verdt å lese.",
      invalid: "Kontroller adressen.",
      failed: "Adressen ble ikke registrert. Prøv igjen om et øyeblikk.",
      terms: "Ved å abonnere samtykker du i at MAXIMUS kan sende deg disse oppdateringene og lagre adressen din til dette formålet. Hvert brev inneholder en lenke for å melde seg av.",
    },
    rights: "MAXIMUS® og løveemblemet er merker som tilhører MAXIMUS-økosystemet. MIPA: intern kontroll av IP, proveniens og dokumenter.",
    boundary:
      "Kommersielle og kontraktsmessige vilkår avtales særskilt og skriftlig. Kjøp av en racket gir ikke institusjonelt medlemskap, investeringsrettigheter, eierskap til immaterielle rettigheter eller krav på royalty.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Presisjon starter i treffpunktet.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer og MAXIMUS-metodikken knytter konsentrert trening til performance-racketer i helkarbon.",
    heroCta1: "Utforsk treningssystemet",
    heroCta2: "Utforsk GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontroll",
    heroMeta: [
      ["Helkarbon", "fra ramme til håndtak"],
      ["4 parametere", "vekt · balanse · swingweight · rammestivhet"],
      ["8 grepsstørrelser", "geometri fra fabrikk L0–L7"],
      ["3 serier", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Familieplan · Bidra sammen med oss",
      title: "Familiebudsjettet ditt. Hva det gir. Hva det bygger opp.",
      p: "Tre scenarioer side om side — nå, planlagt og ønsket. Treningsøktene, timene og ballkontaktene som budsjettet ditt gir, og prisen på én økt, én time og ett slag — beregnet ut fra dine egne tall.",
      points: [
        ["Dine tall", "Alle beløp kommer fra deg. Ingenting antas, ingenting regnes om."],
        ["Tre scenarioer", "Sammenlign det du gjør nå, med det du planlegger og det du ønsker deg."],
        ["Ti år frem", "Utgiftsplanen over ett til ti år, avgrenset av aldersspennet du angir."],
        ["Utenfor banen", "Støtte ved opptak til ledende skoler, og digitale eiendeler som blir værende hos spilleren."],
      ],
      cta: "Beregn familieplanen din",
    },
    paths: {
      eyebrow: "Start her",
      title: "Velg din vei",
      items: {
        player: { h: "Spiller", p: "Finn en racket ut fra nivå og prioriteringer, eller konfigurer den direkte.", a: "Finn racketen din" },
        parent: { h: "Forelder", p: "En skriftlig vei for utviklingsmål, trenerens medvirkning og passende utstyr.", a: "Familieveien" },
        coach: { h: "Trener, klubb eller akademi", p: "Treningssystemer, tilpasning, lagsett og personalisering.", a: "Veier for trener og klubb" },
        partner: { h: "Distributør eller partner", p: "Distribusjon, landutvikling, strategiske og institusjonelle veier.", a: "Partnerskapsveier" },
      },
    },
    series: {
      eyebrow: "Performance-serier",
      title: "Tre performance-arkitekturer. Én utviklingsplattform.",
      lead: "Velg serie ut fra spillretning, og fullfør deretter konfigurasjonen: presisjonsklasse, vekt, grep, personalisering.",
      cta: "Sammenlign seriene",
      configure: "Konfigurer",
      open: "Åpne serien",
      photoPending: "Fotografi er ikke publisert ennå",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS presisjonssystem",
      title: "Vekt. Balanse. Swingweight. Rammestivhet.",
      sub: "Kontrollert som ett teknisk system.",
      lead: "Tre presisjonsklasser bestemmer hvor stramt hver ferdige racket holdes til sin deklarerte spesifikasjon. P0.5 er en stram toleranse under en definert måleprotokoll — ikke null feil.",
      cta: "Presisjon og rammestivhet i detalj",
    },
    stiffness: {
      eyebrow: "Rammestivhet",
      title: "Gjentakbar rammerespons mot en deklarert målverdi.",
      p: "Rammestivheten preger respons, følelse og likhet mellom racketer. MAXIMUS behandler den som den fjerde kontrollerte parameteren: målverdien, det målte resultatet, den tillatte toleransen og måleinstrumentets kapabilitet føres som atskilte opplysninger. Nytten er gjentakbarhet — ikke et garantert resultat for hver spiller.",
      cols: [["Respons", "Hvordan rammen gir energi tilbake i treffpunktet."], ["Følelse", "Hva spilleren kjenner i treffpunktet."], ["Likhet", "Racketer som er bygd etter samme spesifikasjon, responderer likt innenfor sin klasse."]],
      schematicCaption: "Skjematisk: tillatt avvik rundt en deklarert målverdi for rammestivhet i hver klasse. Ikke en måling; ingen RA-verdi er antydet.",
      bands: { p25: "måltoleranse ±1 RA", p15: "måltoleranse ±0.5 RA", p05: "samsvarer med deklarert mål-RA under fabrikkens etablerte måleprotokoll — ikke null feil", target: "deklarert målverdi (ingen verdi er antydet)" },
    },
    carbon: {
      eyebrow: "Konstruksjonsstandard",
      title: "Helkarbon. Fra ramme til håndtak.",
      p: "Alle aktuelle MAXIMUS-racketer på denne plattformen er i sin struktur helt i karbon, håndtaket inkludert. Håndtaket formes ikke med skum.",
      gripTitle: "Åtte grepsstørrelser fra fabrikk. L0–L7.",
      gripP: "Hver størrelse er karbongeometri i håndtaket fra fabrikk — ikke oppbygd med overgrip.",
      scaleCaption: "Skjematisk: nominelle grepsbetegnelser L0–L7 (4″ til 4⅞″). Ikke målte håndtaksmål.",
      cta: "Grepsarkitektur fra fabrikk",
    },
    custom: {
      eyebrow: "Spesialutvikling",
      title: "Utviklet etter spesifikasjon.",
      sub: "Standardutvalget er utgangspunktet.",
      p: "MAXIMUS tar imot tekniske krav utover de publiserte matrisene for vurdering, utvikling, validering og produksjon etter avtalt spesifikasjon. Gjennomførbarheten bekreftes skriftlig.",
      chain: ["Definere", "Utvikle", "Validere", "Spesifisere", "Produsere", "Måle / dokumentere"],
      cta: "Send inn et teknisk underlag",
      cta2: "Drøft spesialutvikling",
    },
    training: {
      eyebrow: "Treningssystemer",
      title: "Et treningssystem bygd rundt treffpunktet.",
      p: "Sweet Spot Trainer, MAXIMUS-metodikken og Spot Trainer knytter utstyret til trenerstyrt trening: sentrert treffpunkt, kontroll, progressiv belastning og overgangen tilbake til performance-racketen.",
      cta: "Treningssystemer",
      cta2: "Be om en demonstrasjon",
      photoPending: "Fotografi av treningsredskapet er ikke publisert ennå",
      sstP: "Et treningshode på 50 in² for trening på sentrert treffpunkt, med fire vektkonfigurasjoner for belastningen treneren velger.",
      sstCta: "Utforsk Sweet Spot Trainer",
      sstCaption: "Konfigurasjonen på 300 g, én av fire",
      methodP: "Sett mål, velg utstyr, tren med treneren involvert, dokumenter observasjoner, vurder på nytt, juster og overfør arbeidet til spill med performance-racketen.",
      methodCta: "Utforsk metodikken",
      spotP: "Et lite rundt mål for å trene et presist og gjentakbart treffpunkt.",
      spotCta: "Utforsk Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Produksjon og kvalitetskontroll",
      title: "Bygd etter en spesifikasjon. Målt og dokumentert.",
      p: "Produksjonen følger den skriftlige spesifikasjonen for hver ordre. Dokumentasjonen følger presisjonsklassen: arkivert produksjonsdokumentasjon for P2.5, individuell dokumentasjon og sporbarhet for P1.5, individuell kontroll og dokumentasjon for P0.5 der programmet for ordren omfatter det.",
      confirmedTitle: "Bekreftet",
      confirmed: ["Helkarbonkonstruksjon fra ramme til håndtak.", "Presisjonsklassene P2.5, P1.5 og P0.5 med fire kontrollerte parametere.", "Åtte grepsstørrelser fra fabrikk L0–L7."],
      pendingTitle: "Ikke publisert ennå",
      pending: "Fotografier av måleutstyr, eksempler på kvalitetsdokumentasjon og opptak fra fabrikken er ikke publisert ennå. Ingenting på denne siden er et målesertifikat.",
      captions: { lettering: "Blank MAXIMUS-skrift på den matte rammen", buttcap: "Grep og endehette med løvemerket", handle: "Sølvfarget personaliseringsgravering", finish: "Hode og strengebed" },
      cta: "Utvikling og produksjon",
    },
    world: {
      eyebrow: "MAXIMUS-verdenen",
      title: "Én nøkkel. Ett økosystem. Ubegrensede muligheter.",
      note: "«Ubegrensede muligheter» er et markedsuttrykk, ikke et løfte om ubegrenset teknisk gjennomførbarhet, inntekt eller tilgang. Et kjøp gir ikke royalty, investeringsavkastning, sponsing eller finansiering av en spillers utvikling.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — og din navigasjon i tennisverdenen: en veiledet utstyrsprofil som besvares skriftlig." },
        personal: { h: "Personalisering", p: "Navn, initialer, numre og lagmerking i den godkjente sølvfargede graveringen." },
        development: { h: "Utvikling", p: "Trenerstyrte treningssystemer, dokumentasjon og ny vurdering." },
        ecosystem: { h: "Utvidet økosystem", p: "Personlige merkevarer, eierdokumentasjon, nettverk, lisensiering og institusjonelle programmer — hvert med sin faktiske status." },
      },
      cta: "Utforsk økosystemet",
    },
    partners: {
      eyebrow: "Partnerskapsveier",
      title: "Trenere, klubber, distributører og partnere.",
      p: "Skriftlig kvalifisering først. Landrettigheter, eksklusivitet og kommersielle vilkår forhandles skriftlig — de tildeles aldri gjennom et skjema.",
      cta: "Alle partnerskapsveier",
      formTitle: "Kort henvendelse",
      formLead: "Velg formålet og skriv til MAXIMUS. Du får en forespørsels-ID på denne siden.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "DIN NAVIGASJON I TENNISVERDENEN" } },
    personal: { eyebrow: "Personalisering", title: "Ditt navn. Ditt nummer. Din MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tre serier. Reelle parametere." },
    map: { cta: "Utforsk økosystemet" },
  },
  racquets: {
    title: "Racketer",
    lead: "Tre performance-serier med felles konstruksjonsstandard, felles presisjonssystem og felles grepsarkitektur fra fabrikk. Hver serie er en etablert performance-arkitektur innenfor en bredere utviklingsplattform.",
    direction: { control: "Kontroll", power: "Kraft", spin: "Spinn" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Primær spillretning",
    compareTitle: "Sammenligning av seriene",
    compareLead: "Kun bekreftede arkitekturdata. Strengemønster, lengde, rammeprofil, strammingsområde og nominelle verdier for swingweight og rammestivhet er ikke publisert for disse seriene; de registreres som forespurte målverdier for teknisk vurdering.",
    columns: { series: "Serie", head: "Hodestørrelse", direction: "Retning", weights: "Oppførte vekter", range: "Vektområde", balance: "Balansedata" },
    balanceModelled: "Beregnede verdier",
    balanceNotProvided: "Ikke publisert ennå",
    construction: "Konstruksjon: helkarbon, ramme til håndtak · Presisjon: P2.5 / P1.5 / P0.5 · Grep: L0–L7",
    otherTitle: "Andre racketsporter",
    otherLead: "Godkjente utviklingsretninger. Det finnes ingen salgbare produkter i disse kategoriene, og ingen tennisspesifikasjon overføres til dem.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Beachtennis" },
    ctaConfigure: "Konfigurer en forespørsel",
    ctaSeries: "Åpne serien",
  },
  seriesPage: {
    eyebrow: "Performance-serier",
    intro: {
      great: "GREAT-arkitekturen på 97 in² er bygd rundt kontroll: et kompakt hode, presist treffpunkt og trygghet i retningen.",
      power: "POWER-arkitekturen på 98 in² er bygd rundt energioverføring: lengde og tempo fra en stabil ramme.",
      spin: "SPIN-arkitekturen på 100 in² er bygd rundt ballens oppførsel: rotasjon, sikkerhetsmargin og forming av ballbanen.",
    },
    photoPending: "Seriefotografi er ikke publisert ennå",
    detailPending: "Fotografier av konstruksjons- og håndtaksdetaljer for denne serien er ikke publisert ennå.",
    specsTitle: "Spesifikasjon og status",
    catalogue: {
      eyebrow: "Katalog for {series}-serien",
      title: "{n} vektvarianter",
      lead: "Hver variant i {series}-serien, sortert etter vekt. Vekt i gram, balanse i millimeter fra endehetten. Hver visualisering vises i sin helhet: ingenting er beskåret, maskert eller strukket.",
      selectLabel: "Velg en vektvariant",
      select: "Vis denne varianten",
      selected: "Vist over",
      balanceLabel: "Balanse",
      headLabel: "Hodestørrelse",
      constructionLabel: "Konstruksjon",
      gripsLabel: "Grepsstørrelser fra fabrikk",
      precisionLabel: "Presisjonsklasser",
      balanceConfirmed: "Balansen er den bekreftede verdien for denne vekten og stemmer med tallet som er trykt på visualiseringen.",
      balanceModelled: "Balansen er en beregnet verdi for denne oppførte vekten, ikke en individuell fabrikkmåling; den stemmer med tallet som er trykt på visualiseringen.",
      zoom: "Åpne bildet",
      close: "Lukk",
      allTitle: "Alle {n} varianter",
    },
    specs: { head: "Hodestørrelse", direction: "Primær retning", weights: "Oppførte vekter", range: "Vektområde", balance: "Balanse", construction: "Konstruksjon", grips: "Grep fra fabrikk", precision: "Presisjonsklasser" },
    construction: "Helkarbon, ramme til håndtak",
    statusTitle: "Status for verdiene",
    matrixTitle: "Fullstendig vektmatrise",
    matrixLead: "De oppførte vektene er standardutvalget. Andre vekter kan forespørres som egendefinerte målverdier; manglende mellomverdier settes ikke inn.",
    balanceNote: {
      confirmed: "Balanseverdiene er bekreftet for hver oppførte vekt (mm fra endehetten) og stemmer med tallet som er trykt på visualiseringen av den vekten. De beregnes ikke her og jevnes ikke ut mellom nærliggende vekter; målegrunnlaget bekreftes i den skriftlige spesifikasjonen.",
      modelled: "Balanseverdiene er beregnet for hver oppførte vekt (mm fra endehetten). De er ikke individuelle fabrikkmålinger; målegrunnlaget bekreftes i den skriftlige spesifikasjonen.",
      notprovided: "Balanseverdier er ikke oppgitt for denne serien. Ikke slutt deg til dem ut fra en annen serie.",
    },
    optionsTitle: "Presisjon, grep og vekt",
    notPublished: "Ikke publisert for denne serien: strengemønster, lengde, rammeprofil, strammingsområde og verdier for swingweight og rammestivhet. Du kan oppgi dem som forespurte målverdier for teknisk vurdering.",
    offerTitle: "Hva skjer etter forespørselen din",
    offerSteps: [
      ["Forespørsel", "Send inn en konfigurasjon eller et spørsmål. En forespørsels-ID vises umiddelbart."],
      ["Vurdering", "MAXIMUS vurderer serie, klasse, vekt, grep og eventuelle forespurte målverdier."],
      ["Skriftlig svar", "Spesifikasjon, tilgjengelighet og kommersielle vilkår bekreftes skriftlig."],
    ],
    faqTitle: "Spørsmål",
    faq: [
      ["Er balanseverdiene målt?", "De er beregnet for de oppførte vektene, ikke individuelle målinger. Målegrunnlaget bekreftes i den skriftlige spesifikasjonen."],
      ["Kan jeg be om en vekt som ikke er oppført?", "Ja, som egendefinert målverdi i hele gram. Den vurderes teknisk, og gjennomførbarheten bekreftes skriftlig."],
      ["Hva endrer presisjonsklassen?", "Hvor stramt vekt, balanse, swingweight og rammestivhet holdes til den deklarerte spesifikasjonen, og hvilken dokumentasjon som føres."],
      ["Bygges grepet opp med overgrip?", "Nei. L0–L7 er karbongeometrier i håndtaket fra fabrikk."],
      ["Hvor finner jeg priser og leveringstider?", "De bekreftes skriftlig for hver forespørsel og publiseres ikke her."],
    ],
    faqSpinBalance: ["Hvor kommer balanseverdiene for SPIN fra?", "Fra den bekreftede tabellen for Spin-serien: 33 vektvarianter med balanse i millimeter fra endehetten. Hvert par stemmer med tallet som er trykt på den godkjente visualiseringen av den vekten. Verdiene er ikke beregnet og ikke jevnet ut mellom nærliggende vekter."],
    ctaBuild: "Konfigurer denne serien",
    ctaAsk: "Still spørsmål om denne serien",
    ctaCompare: "Sammenlign alle serier",
    weightsLabel: "oppførte vekter",
    headLabel: "hode",
  },
  precision: {
    title: "Presisjon og rammestivhet",
    switch: { label: "Velg presisjonsklasse", panelLabel: "Fire kontrollerte parametere —", qcLabel: "Arkitektur for kvalitetskontroll", protocolNote: "under fabrikkens definerte måleprotokoll for kvalitetskontroll", fullTable: "Fullstendig sammenligningstabell" },
    lead: "Fire parametere kontrollert som ett teknisk system. Hver klasse bestemmer hvor stramt en ferdig racket holdes til sin deklarerte spesifikasjon, og hvilken kvalitetsdokumentasjon som produseres.",
    statement: "Vekt. Balanse. Swingweight. Rammestivhet. Kontrollert som ett teknisk system.",
    classes: {
      "P2.5": { name: "Skalerbar performance-kjerne", qc: "Individuell måling og arkivert produksjonsdokumentasjon." },
      "P1.5": { name: "Utvidet presisjon", qc: "Individuell måling, individuell dokumentasjon og sporbarhet." },
      "P0.5": { name: "Profesjonell · individuelt kontrollert", qc: "Individuell kontroll med nominelle og faktiske verdier og individuelle måleoppføringer; serieidentitet, sporbarhet per parti, et presisjonssertifikat og matchede sett der programmet for ordren omfatter det." },
    },
    columns: { cls: "Klasse", weight: "Vekt", balance: "Balanse", sw: "Swingweight", stiff: "Rammestivhet", qc: "Kvalitetskontroll" },
    stiffTarget: "måltoleranse",
    stiffExact: "samsvarer med deklarert mål-RA under fabrikkens etablerte måleprotokoll",
    programmeNote: "Serieidentitet, sertifikater og dokumentasjon av matchede sett utstedes bare der programmet for en konkret ordre omfatter det.",
    targetsNote: "Spesifikasjoner for rammestivhet er produksjonsmål inntil den aktuelle protokollen og produksjonsbevisene bærer en sterkere påstand. Arkitekturen innebærer ikke at hver oppførte konfigurasjon allerede har gjennomgått en fullstendig frigivelsesprosess for alle fire parametere.",
    stiffnessTitle: "Hvorfor rammestivheten betyr noe",
    stiffnessP1: "Rammestivheten påvirker hvordan rammen responderer i treffpunktet, hvordan den føles, og hvor like to racketer er. Hovednytten av å kontrollere den er gjentakbar respons mot en deklarert spesifikasjon.",
    stiffnessP2: "Før verifisert samsvar publiseres, angir den interne kvalitetsdokumentasjonen måleinstrumentet, kalibreringsstatusen, metoden, racketens tilstand, oppløsningen, måleusikkerheten, gjentatte målinger, avrundingsregelen og godkjenningsregelen. Et identisk vist heltall er ikke bevis for null fysisk variasjon eller null målefeil.",
    fields: ["Målverdi", "Målt resultat", "Tillatt toleranse", "Måleinstrumentets kapabilitet"],
    fieldsNote: "Føres som atskilte felt i hver oppføring.",
    matchedTitle: "Matchede sett",
    matchedP: "Kriteriene for matchede sett er definert atskilt fra den individuelle toleransen. At hver racket samsvarer med sin nominelle toleranse, beviser ikke i seg selv en bestemt største forskjell mellom to racketer. Matchede par, trioer og lagsett forespørres gjennom konfiguratoren og bekreftes skriftlig.",
    extendedTitle: "Utvidet teknisk modell",
    extendedP: "Datamodellen støtter flere parametere. Det finnes ennå ingen verdier eller toleranseklasser for dem; de kan oppgis som forespurte målverdier i et teknisk underlag.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torsjonsegenskaper", length: "Lengde", beamProfile: "Rammeprofil", headGeometry: "Hodegeometri", stringPattern: "Strengemønster", durability: "Holdbarhet", vibration: "Vibrasjonsegenskaper" },
    noZero: "MAXIMUS beskriver ikke sitt oppførte utvalg som toleransefritt. Presisjonen i utvalget oppgis som en klasse med deklarert toleranse og en definert arkitektur for kvalitetskontroll. ZERO er ikke en del av utvalget.",
    zero: {
      eyebrow: "Eksklusivt alternativ",
      title: "ZERO",
      sub: "Null gram toleranse.",
      p: "De tre klassene holder en ferdig racket innenfor et deklarert toleransebånd. ZERO fjerner båndet. Racketen bygges og måles til måleverdien er lik den deklarerte verdien ved oppløsningen til fabrikkens måleinstrument, og denne måleverdien følger med racketen. ZERO er ikke en del av det oppførte utvalget og ikke en fjerde klasse: det avtales individuelt, for én racket eller ett matchet sett, som en eksklusiv spesialproduksjon. Etter avtale brukes samme tilnærming på balanse og swingweight.",
      points: [
        ["Uten toleransebånd", "Den deklarerte verdien er resultatet, ikke midten av en toleranse."],
        ["Én om gangen", "Bygget, målt og dokumentert som én enhet."],
        ["Følger med racketen", "Den målte verdien overleveres og bevares i produksjonsdokumentasjonen."],
        ["Bekreftet skriftlig", "Parametere, omfang og leveringstid avtales før produksjon."],
      ],
      note: "Matchet ved oppløsningen til fabrikkens måleinstrument. En identisk vist verdi er ingen påstand om null fysisk variasjon. Tilgjengelighet og vilkår avtales individuelt for hver ordre.",
      cta: "Be om ZERO",
    },
    cta: "Konfigurer med en presisjonsklasse",
  },
  grip: {
    title: "Grepsarkitektur fra fabrikk",
    statement: "Åtte grepsstørrelser fra fabrikk. L0–L7.",
    lead: "Grepsgeometrien er en del av karbonhåndtakets arkitektur. Hver størrelse produseres som håndtaksgeometri, ikke bygd opp med overgrip.",
    emph: "Utvidede størrelser",
    p1: "Utvalget med åtte størrelser fra fabrikk gir trenere og spillere et bredere konfigurasjonsrom der utstyret kan tilpasses spilleren — også de større geometriene L6 og L7.",
    p2: "Den nominelle grepsbetegnelsen må skilles fra håndtakets rene strukturmål og fra den endelige måleprotokollen. Størrelsene gjelder for performance-seriene og for treningsfamiliene på denne plattformen.",
    p3: "Det hevdes ingen verdensomfattende eksklusivitet for dette utvalget.",
    columns: { size: "Størrelse", nominal: "Nominelt mål", family: "Gjelder for" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurer med din grepsstørrelse",
  },
  custom: {
    title: "Spesialutvikling",
    statement: "Utviklet etter spesifikasjon.",
    sub: "Standardutvalget er utgangspunktet.",
    lead: "MAXIMUS tar imot tekniske krav utover de publiserte konfigurasjonsmatrisene for vurdering, utvikling, validering og produksjon etter avtalt spesifikasjon. Gjennomførbarheten bekreftes gjennom vurdering — ikke alle tenkelige forespørsler er fysisk eller kommersielt gjennomførbare.",
    scopeTitle: "Hva et teknisk underlag kan omfatte",
    scope: ["Hode- og rammegeometri", "Lengde", "Vekt", "Balanse", "Swingweight", "Rammestivhet", "Twistweight", "Grepsgeometri", "Konstruksjon", "Matchede sett", "Treningsrammer", "Design og gravering", "Identitet og lagprogrammer", "Utvikling som krever nye former"],
    processTitle: "Prosess",
    process: [
      ["Definere", "Ønskede målverdier, bindende grenser, tenkt bruk og akseptable avveininger."],
      ["Utvikle", "Teknisk vurdering mot plattformen og formene."],
      ["Validere", "Validering mot den avtalte spesifikasjonen."],
      ["Spesifisere", "En skriftlig spesifikasjon med målegrunnlag og toleranser."],
      ["Produsere", "Produksjon etter spesifikasjonen."],
      ["Måle / dokumentere", "Måling og arkivert dokumentasjon etter gjeldende presisjonsklasse."],
    ],
    formTitle: "Send inn et teknisk underlag",
    formLead: "Skill ønskede målverdier fra bindende grenser. Resultatet er en forespørsel om teknisk vurdering, ikke en automatisk akseptert produksjonsordre.",
    protected: "Laminatoppbygging, former, leverandøridentiteter, interne kostnadsberegninger og beskyttet kunnskap utleveres ikke på denne veien.",
    cta: "Send inn et teknisk underlag",
  },
  training: {
    title: "Treningssystemer",
    lead: "To treningsfamilier med egne produksjonsstandarder, knyttet sammen av én metodikk: trenerstyrt trening, dokumentasjon, ny vurdering og overføring tilbake til spill med performance-racketen.",
    sst: { h: "Sweet Spot Trainer", p: "En treningsracket med redusert hode på 50 in² i et system med fire vekter, for trening på sentrert treffpunkt, bevissthet om sweet spot, racketkontroll og progressiv belastning." },
    spot: { h: "Spot Trainer", p: "Trening på treffpunktet med et lite rundt treffmål, på det godkjente grunnlaget med fire vekter." },
    method: { h: "Metodikk", p: "Sett mål, velg utstyr med treneren involvert, bruk det aktuelle systemet, dokumenter, vurder på nytt, juster og overfør." },
    experience: "Hold den. Sving den. Kjenn den.",
    experienceP: "Be om en test, en tilpasning eller en demonstrasjon med trener til stede. En innsendt forespørsel er ikke en bekreftet avtale.",
    cta: "Be om tilpasning eller demonstrasjon",
    distinct: "Sweet Spot Trainer, Spot Trainer og enhver separat demonstrasjonsenhet er egne produkter og blandes aldri sammen.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "En egen treningskategori med sin egen produksjonsstandard. Hodet på 50 in² retter oppmerksomheten mot hvor ballen treffer; de fire vektene gir belastningsprogresjonen.",
    baseline: "Bekreftet grunnlag",
    columns: { head: "Hode", length: "Lengde", pattern: "Strengemønster", grips: "Grep fra fabrikk" },
    systemTitle: "System med fire racketer",
    detailsTitle: "Konstruksjonsdetaljer",
    systemLead: "Vekt og balanse som levert. Målegrunnlaget dokumenteres særskilt og er ikke publisert ennå.",
    purposeTitle: "Formål",
    purpose: ["Trening på sentrert treffpunkt", "Bevissthet om sweet spot", "Racketkontroll", "Progressiv belastning", "Trenerstyrt utvikling", "Overgang tilbake til spillerens performance-racket"],
    heavy: "Modellen på 400 g er en kontrollert treningskonfigurasjon. Den anbefales ikke automatisk til barn, nybegynnere eller enhver spiller; treneren fastsetter belastning, varighet og progresjon.",
    precisionNote: "Presisjonsklassene P2.5, P1.5 og P0.5 for performance-racketene gjelder ikke automatisk for denne treningsfamilien. Toleransene i treningsproduksjonen følger familiens egen godkjente spesifikasjon.",
    health: "Det loves ingen forebygging eller behandling av tennisalbue, ingen utelukkelse av skader og ingen garantert forbedring.",
    cta: "Be om en demonstrasjon av Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Trening på treffpunktet med et lite rundt treffmål. Et eget produkt med sin egen visuelle identitet, bygd på det godkjente grunnlaget med fire vekter.",
    purposeTitle: "Bekreftet formål",
    purposeP: "Å trene spilleren i å finne og gjenta et presist treffpunkt.",
    weightsTitle: "Vektprogresjon",
    weightsP: "Vektprogresjonen følger det godkjente vektgrunnlaget til Sweet Spot Trainer. Balanseverdier og andre spesifikasjoner for Sweet Spot Trainer kopieres ikke over på Spot Trainer.",
    dims: "De nøyaktige målene på treffmålet er ikke publisert ennå.",
    grips: "Grepsarkitektur fra fabrikk L0–L7.",
    notes: ["Presisjonsklassene for performance-racketene brukes ikke automatisk.", "Det er ikke en miniatyrversjon av en vanlig racket, og det publiseres ingen strengemønster.", "Spot Trainer, Sweet Spot Trainer og enhver separat demonstrasjonsenhet holdes fra hverandre."],
    cta: "Still spørsmål om Spot Trainer",
  },
  methodology: {
    title: "Metodikk og produktopplevelse",
    lead: "Utstyr er én del av et strukturert utviklingsløp. Metoden starter med spillerens mål, ikke med en produktbetegnelse.",
    stepsTitle: "Utviklingsløpet",
    steps: [
      ["Sett mål", "Spillerens mål og utgangspunkt."],
      ["Velg utstyr", "Passende utstyr valgt med treneren involvert."],
      ["Bruk systemet", "Det aktuelle treningssystemet, trenerstyrt."],
      ["Dokumenter", "Observasjoner av faktisk deltakelse, uten oppdiktede resultater."],
      ["Vurder på nytt", "Sammenlignbare kontrollpunkter."],
      ["Juster", "Justeringer av konfigurasjonen eller programmet."],
      ["Overfør", "Det lærte overføres tilbake til spill med performance-racketen."],
    ],
    educationTitle: "Opplæringsveier",
    education: { player: "Spillere — å forstå konfigurasjon, belastning og progresjon.", parent: "Foreldre — kontinuitet i utviklingen, passende utstyr, dokumentasjon og rettigheter.", coach: "Trenere — treningssystemer, tilpasning, vurdering og autorisert bruk av programmer." },
    evidenceTitle: "Disiplin i dokumentasjonen",
    evidenceP: "Dokumentasjon av faktisk deltakelse og observasjoner bevares med sin klassifisering — oppgitt av deltakeren, bekreftet av foresatt, validert av trener eller målt av systemet. Fremgang, resultater og validering blir aldri oppdiktet.",
    experienceTitle: "Hold den. Sving den. Kjenn den.",
    experienceP: "Du kan be om en test, en tilpasning eller en demonstrasjon med trener til stede. En innsendt forespørsel er ikke en bekreftet avtale.",
    cta: "Be om tilpasning eller demonstrasjon",
    cta2: "Henvendelse om trenerpartnerskap",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — veiledet utstyrsprofil",
    title: "MAXIMUS GPS",
    lead: "En veiledet utstyrsprofil. Svar bare på det som er relevant; gå gjennom og rett svarene dine; få et sammendrag, de konfigurasjonsretningene som gjelder, og en reell neste handling.",
    honesty: "I denne versjonen er ingen automatiske tilpasningsregler godkjent. GPS lager derfor et tydelig sammendrag av kravene og peker på konfigurasjonsretninger; detaljene om utstyr sendes videre til faglig vurdering.",
    rulesVersion: "Regelversjon",
    dataVersion: "Versjon av produktdata",
    steps: { role: "Rolle", sport: "Idrett", experience: "Erfaring", objectives: "Mål", style: "Spillestil", equipment: "Dagens utstyr", preference: "Preferanser", coach: "Trenerens medvirkning", ageBand: "Aldersgruppe", review: "Gjennomgang" },
    notStored: "Lagres ikke i denne nettleseren.",
    ageNote: "Brukes bare til å rute forespørselen. Det spørres ikke om navn, fødselsdato eller helseopplysninger.",
    q: {
      role: "Hva passer på deg?",
      sport: "Hvilken idrett?",
      experience: "Erfaringsnivå",
      objectives: "Hva betyr mest? (velg opptil tre)",
      style: "Spillestil, hvis du kjenner den",
      equipment: "Dagens utstyr, hvis du har noe",
      equipmentHint: "Merke og modell, vekt eller grep hvis du vet det. Valgfritt.",
      preference: "Ønsket konfigurasjon eller kjent grepsstørrelse",
      grip: "Kjent grepsstørrelse",
      coach: "Er en trener involvert i utstyrsvalgene dine?",
      ageBand: "Spillerens aldersgruppe (brukes bare til å rute forespørselen riktig)",
    },
    roles: { player: "Spiller", parent: "Forelder eller foresatt", coach: "Trener", club: "Klubb eller akademi", other: "Annet" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Annen racketsport" },
    sportNote: "Det finnes produkter for tennis. Andre idretter er utviklingsretninger; interessen din registreres for det aktuelle programmet.",
    experience: { beginner: "Nybegynner", developing: "I utvikling", intermediate: "Middels", advanced: "Viderekommen", competitive: "Konkurransenivå", professional: "Profesjonell" },
    objectives: { control: "Kontroll", power: "Kraft", spin: "Spinn", comfort: "Komfort", manoeuvrability: "Manøvrerbarhet", development: "Langsiktig utvikling", competition: "Konkurranse", training: "Treningssystem", team: "Lag eller matchet sett", personal: "Personalisering" },
    styles: { baseline: "Grunnlinjespill", allcourt: "Allcourt", attacking: "Offensiv", defensive: "Defensiv", coach: "Valgt av treneren", unknown: "Ikke sikker" },
    ageBands: { u10: "Under 10 år", u14: "10–13", u18: "14–17", adult: "18 år og over" },
    output: {
      title: "Din utstyrsprofil",
      status: "Faglig vurdering kreves",
      statusP: "Det lages ingen automatisk match i denne versjonen. Profilen din er oppsummert for faglig vurdering.",
      directionsTitle: "Konfigurasjonsretninger som gjelder",
      directionsP: "Basert på målene du har oppgitt og den deklarerte spillretningen til hver serie. Dette er en retning, ikke en tilpasningsanbefaling.",
      trainingHint: "Målene dine omfatter et treningssystem: se Sweet Spot Trainer og Spot Trainer.",
      teamHint: "Matchede sett forespørres gjennom konfiguratoren og bekreftes skriftlig.",
      next1: "Send profilen til faglig vurdering",
      show: "Vis profilen min",
      configure: "Konfigurer",
      sendP: "Send profilen din til MAXIMUS for faglig vurdering. En forespørsels-ID vises umiddelbart; svaret kommer skriftlig.",
      otherSport: "MAXIMUS-racketer finnes for tennis. For andre racketsporter foreslås ingen tennisserie; interessen din registreres som en utviklingsretning.",
      noDirection: "Målene dine peker ikke mot én spillretning. Den faglige vurderingen foreslår en konfigurasjon.",
      incomplete: "Noen påkrevde svar mangler — bruk «Endre svar» for å fylle dem ut.",
    },
    privacy: "GPS spør ikke om helseopplysninger og ikke om opplysninger som identifiserer barn. Bare svar fra valglister beholdes i denne nettleserøkten; fritekst lagres ikke.",
  },
  build: {
    title: "Konfigurer din racket",
    lead: "Konfigurer en forespørsel: serie, presisjonsklasse, oppført vekt eller egendefinert målverdi, grepsstørrelse, forespurte målverdier, personalisering, matchede sett og antall. Resultatet er en konfigurasjonsforespørsel med en forespørsels-ID — ikke et varenummer, en pris, en leveringsdato eller et sertifikat.",
    steps: { series: "Serie", cls: "Presisjonsklasse", weight: "Vekt", grip: "Grep", targets: "Målverdier", personal: "Personalisering", set: "Sett og antall", use: "Bruk", review: "Gjennomgang" },
    q: {
      series: "Velg en serie",
      cls: "Velg en presisjonsklasse",
      weightMode: "Vekt",
      listed: "Oppført vekt",
      customWeight: "Ønsket vekt (g)",
      balanceShown: "Beregnet balanse for denne vekten",
      balanceRequest: "Ønsket balanse (mm)",
      grip: "Grepsstørrelse fra fabrikk",
      targetsTitle: "Forespurte målverdier",
      swingweight: "Ønsket swingweight (kg·cm²)",
      stiffness: "Ønsket rammestivhet (RA)",
      basis: "Målegrunnlag for ønskede verdier",
      engraving: "Graveringstekst",
      engravingHint: "Navn, initialer eller nummer. Latinske bokstaver, sifre, mellomrom, bindestrek, apostrof og punktum; opptil 24 tegn. Andre skriftsystemer tas imot for godkjenning av graveringsutkastet.",
      engravingType: "Personalisering",
      types: { none: "Ingen", name: "Spillerens navn", initials: "Initialer", number: "Settnummer", academy: "Merking for trener eller akademi", team: "Lagprogram" },
      set: "Enkeltracket eller matchet sett",
      use: "Tenkt bruk",
      uses: { play: "Eget spill", competition: "Konkurranse", coaching: "Trenervirksomhet", team: "Lag eller akademi", retail: "Vurdering for butikk eller distribusjon", other: "Annet" },
      notes: "Ytterligere tekniske krav",
    },
    classes: { "P2.5": "P2.5 — skalerbar performance-kjerne", "P1.5": "P1.5 — utvidet presisjon", "P0.5": "P0.5 — profesjonell, individuelt kontrollert" },
    stiffExactShort: "rammestivheten samsvarer med deklarert mål-RA under fabrikkens etablerte protokoll",
    clsNote: "Hver klasse kontrollerer fire parametere. P0.5 er en stram toleranse under en definert måleprotokoll — ikke null feil. Serieidentitet, sertifikater og dokumentasjon av matchede sett gjelder bare der programmet for din ordre omfatter det.",
    listedNote: "Fra den bekreftede matrisen for serien.",
    customNote: "En vekt utenfor matrisen, vurdert teknisk.",
    balanceCaption: "Hver oppførte vekt viser sin beregnede balanse i mm fra endehetten. Beregnede verdier er ikke individuelle målinger.",
    spinNote: "SPIN-vektene utgjør den forespurte vektarkitekturen. Balanse, swingweight og rammestivhet er ikke oppgitt for SPIN; de fastsettes i den tekniske vurderingen.",
    customHint: "Hele gram, bare sifre. En egendefinert vekt er en forespørsel om teknisk vurdering; gjennomførbarheten bekreftes skriftlig, og ingen verdi avrundes.",
    gripNote: "karbongeometri i håndtaket fra fabrikk, ikke oppbygd med overgrip",
    targetsLead: "Valgfritt. Fyll bare inn de verdiene du trenger. Hver av dem registreres som en forespurt målverdi for teknisk vurdering, ikke som en publisert spesifikasjon.",
    basisHint: "Påkrevd når du ber om en egendefinert vekt eller en målverdi: gjelder verdiene en racket uten strenger eller med strenger?",
    inputRange: "Godtatt inndata: {min}–{max}.",
    inputRangeNote: "Inndataområdene filtrerer bare bort umulige verdier. De beskriver ikke produksjonskapasiteten.",
    listedBasis: "oppførte verdier — målegrunnlaget bekreftes i den skriftlige spesifikasjonen",
    notStored: "Lagres ikke i denne nettleseren; fyll det inn på nytt hvis du laster siden om.",
    artworkReview: "godkjenning av graveringsutkastet er påkrevd",
    previewNote: "Det vises ingen visuell forhåndsvisning: en godkjent graveringsmal for denne modellen er ikke publisert ennå. Teksten din registreres for godkjenning av graveringsutkastet.",
    teamSub: "4–99 racketer per sett",
    setsLabel: { individual: "Antall racketer", pair: "Antall matchede par", triple: "Antall matchede trioer", team: "Antall lagsett" },
    teamSizeLabel: "Racketer per lagsett",
    totalLabel: "Racketer totalt",
    racquetsUnit: "racketer",
    setRule: "Antallet gjelder sett: et matchet par er 2 racketer per sett, en matchet trio 3.",
    restart: "Start en ny konfigurasjon",
    notices: { weightCleared: "{w} g finnes ikke i matrisen for {series}, så vekten ble nullstilt. Velg en oppført vekt eller be om en egendefinert målverdi." },
    reviewTitle: "Konfigurasjonsforespørsel",
    reviewP: "Kontroller konfigurasjonen, og legg deretter inn kontaktopplysningene dine. Forespørselen lagres med en forespørsels-ID og besvares skriftlig; tilgjengelighet og kommersielle vilkår bekreftes skriftlig.",
    reviewErrors: "Noen av svarene i konfigurasjonen må ses over:",
    edit: "Endre",
    fieldNames: { series: "Serie", cls: "Presisjonsklasse", mode: "Valg av vekt", weight: "Oppført vekt", customWeight: "Ønsket vekt", basis: "Målegrunnlag", balanceReq: "Ønsket balanse", sw: "Ønsket swingweight", ra: "Ønsket rammestivhet", grip: "Grepsstørrelse", ptype: "Personalisering", engraving: "Graveringstekst", setType: "Type sett", sets: "Antall", teamSize: "Racketer per lagsett", use: "Tenkt bruk", notes: "Ytterligere krav" },
    status: { listed: "oppført vekt", requestedArchitecture: "forespurt vektarkitektur", technicalReview: "forespørsel om teknisk vurdering", notPublished: "ikke oppgitt", requestedCondition: "ønsket tilstand" },
    chooseLink: "Usikker på hvilken serie som passer? Få hjelp til å velge",
    cta: "Send konfigurasjonsforespørsel",
  },
  experience: {
    title: "Opplevelse og tilpasning",
    statement: "Hold den. Sving den. Kjenn den.",
    lead: "Be om en test, en tilpasning eller en demonstrasjon med trener til stede. Forespørsler vurderes og besvares skriftlig; en innsendt forespørsel er ikke en bekreftet avtale.",
    optionsTitle: "Hva du kan be om",
    options: ["Test av racket", "Tilpasningstime", "Demonstrasjon med trener til stede", "Demonstrasjon av Sweet Spot Trainer eller Spot Trainer", "Prøvedag for lag eller akademi"],
    formTitle: "Forespørsel om tilpasning eller demonstrasjon",
  },
  engineering: {
    title: "Utvikling og produksjon",
    statement: "Fly. Yachter. Racketer.",
    lead: "Én ingeniørfilosofi i tre miljøer: prinsippene som former et fly, presisjonen som fører en yacht over åpent hav, ytelsen som definerer hver MAXIMUS-racket. En fortelling om ingeniørarbeid — ikke en påstand om flysertifisering, eierskap til yachter, eierskap til fabrikk eller direkte overføring av materialer.",
    manifesto: ["Vi mener at fremragende ingeniørarbeid ikke har grenser.", "Én filosofi. Utviklet uten kompromisser."],
    capabilityTitle: "Produksjonskapasitet",
    capabilityLead: "Kapasiteten vises som et forløp, ikke som et slagord.",
    sequence: [
      ["Spesifikasjon", "Serie, presisjonsklasse, vekt, balanse, swingweight, målverdi for rammestivhet, grepsgeometri, personalisering."],
      ["Produksjon", "Helkarbonkonstruksjon fra ramme til håndtak, produsert etter spesifikasjonen."],
      ["Kvalitetskontroll", "Måling og dokumentasjon etter presisjonsklasse: produksjonsdokumentasjon, individuell dokumentasjon og sporbarhet, individuell sertifisering."],
      ["Gjentatt produksjon", "Gjentakbar respons mot en deklarert spesifikasjon på tvers av partier."],
      ["Sporbarhet", "Serieidentitet, sporbarhet per parti og et presisjonssertifikat der klassen gir det."],
    ],
    capacityNote: "Produksjonskapasitet, leveringstider, minimumsmengder og leveringsplaner bekreftes skriftlig for hvert program, mot bekreftede ordrer og en avtalt frigivelsesplan.",
    truth: "Kapasitet er ikke produsert volum, lagerbeholdning, en garantert leveringsdato eller eierskap til et produksjonsanlegg.",
    cta: "Distribusjon og landutvikling",
    cta2: "Send inn et teknisk underlag",
  },
  ecosystem: {
    title: "MAXIMUS-økosystemet",
    lead: "Én nøkkel. Dette er hva den åpner. Hver node har en forklaring, en korrekt status og en relevant neste handling.",
    words: ["Ingeniørkunst", "Ytelse", "Innovasjon", "Fellesskap", "Mulighet", "Mening"],
    nodes: {
      engineering: { h: "Utvikling og produksjon av racketer", p: "Racketer i helkarbon utviklet etter spesifikasjon, produsert med kvalitetsdokumentasjon og sporbarhet.", a: "Utvikling og produksjon" },
      precision: { h: "Presisjon og individuell konfigurasjon", p: "Fire parametere, tre presisjonsklasser, åtte grepsstørrelser og spesialutvikling.", a: "Presisjon og rammestivhet" },
      training: { h: "Trening og metodikk", p: "Sweet Spot Trainer, Spot Trainer og et strukturert utviklingsløp.", a: "Treningssystemer" },
      development: { h: "Utvikling av spillere og trenere", p: "Trenerstyrt utvalg, dokumentasjon, ny vurdering og opplæringsveier.", a: "Metodikk" },
      identity: { h: "Personlig identitet og personlige merkevarer", p: "Fra gravering til en rettighetsstyrt personlig eller profesjonell merkevare.", a: "Personlige merkevarer" },
      owners: { h: "Eierdokumentasjon, kunnskap og rettigheter", p: "Et foreslått tilgangsstyrt eierarkiv for dokumentasjon av utstyr, utvikling og rettigheter.", a: "Eiere og arkivet" },
      mipa: { h: "MIPA-proveniens og intern kontroll", p: "Det interne laget for IP, proveniens og dokumentkontroll.", a: "Juridisk identitet og kontroll" },
      digital: { h: "Digital infrastruktur og retningen Blockchain 5.0", p: "Proveniens, sporbar dokumentasjon, tilgangsstyrte bevis og produktidentitet som den uttalte teknologiretningen.", a: "Teknologiretning" },
      licensing: { h: "Kontraktsfestet lisensiering og royaltyprogrammer", p: "Lisensierte merkevarer, produkter og rettighetspakker med vilkår fastsatt i hver avtale.", a: "Lisensveier" },
      families: { h: "Familiens deltakelse og programfordeler", p: "Informerte valg, kontinuitet, bevart dokumentasjon og fordeler fastsatt av programmet.", a: "Familier og foreldre" },
      network: { h: "MAXIMUS Sports Network", p: "Spillere, trenere, klubber, akademier, tjenesteytere, operatører og regionale partnere.", a: "Sports Network" },
      market: { h: "Klubber, akademier, distribusjon og landutvikling", p: "Lagprogrammer, butikksalg, distribusjon og områdeutvikling gjennom skriftlig kvalifisering.", a: "Partnerskapsveier" },
      institutional: { h: "Institusjonelle programmer, utdanning, innovasjon og samfunnsnytte", p: "Det institusjonelle laget som leveres av MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) der et program begrunner denne rollen.", a: "Institusjonelle programmer" },
      extensions: { h: "Fremtidige utvidelser til racketsporter og MAXIMUS-klær", p: "Padel, pickleball, squash, badminton, racquetball, beachtennis og klær som utviklingsretninger.", a: "Racketsporter" },
    },
    boundaryTitle: "Grenser",
    boundary: [
      "Kjøp av en racket gir ikke institusjonelt medlemskap, styringsrettigheter, royalty eller investeringsrettigheter.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) er institusjonell operatør bare der et program begrunner denne rollen; ved salg av utstyr oppgis den faktiske avtaleparten.",
      "Tilskudd, status som allmennyttig, skattemessig behandling og tillatelser fra myndigheter gjelder ikke automatisk på tvers av land.",
    ],
    techTitle: "Teknologiretning",
    techP: "Blockchain 5.0 er den uttalte teknologiretningen til MAXIMUS. De funksjonelle formålene er proveniens, sporbar dokumentasjon, tilgangsstyrte bevis, produktidentitet og avstemming av kvalifiserende kommersielle hendelser. Det fremstilles ingen konsensusmekanisme, transaksjonskapasitet, nodenettverk, smartkontraktsadresse, token eller uavhengig sertifisering, og det hevdes ingen implementering i drift. Personopplysninger, dokumentasjon om barn og fortrolige avtaler legges som standard aldri inn i et offentlig, uforanderlig system.",
  },
  brands: {
    title: "Personlige merkevarer og ambassadører",
    statement: "Fra spiller til merkevare. Fra trener til merkevare.",
    lead: "En egen vei for personlige merkevarer. MAXIMUS' medvirkning omfatter merkevarebygging og avtalt markedsføring — ikke bare et navn på en racket.",
    progressionTitle: "Tenkt forløp",
    progression: [
      ["Verifisert identitet", "En verifisert identitet og utviklingshistorikk."],
      ["Særpreget merkevare", "En særpreget personlig eller profesjonell merkevare."],
      ["Rettighetsklarert innhold", "Rettighetsklarert innhold og godkjent produktidentitet."],
      ["Utvikling og kolleksjoner", "Utvikling og oppbygging av kolleksjoner der det er avtalt."],
      ["Markedsføring", "Markedsføring gjennom avtalte MAXIMUS-kanaler og partnerskap."],
      ["Deltakelse", "Kontraktsfestet deltakelse i kvalifiserende salg eller lisensiering."],
      ["Rapportering", "Åpen rapportering i henhold til avtalen."],
    ],
    royaltiesTitle: "Royalty og lisensiering",
    royalties: [
      "Royalty knyttes til den definerte lisensierte merkevaren, produktet, transaksjonen eller rettighetspakken.",
      "«Verdensomfattende salg» betyr kvalifiserende salg innenfor avtalens omfang — aldri hver enkelt MAXIMUS-racket uten tilknytning.",
      "Satser, beregningsgrunnlag, områder, varighet, refusjoner, fradrag, rapportering, oppgjør og kontroll fastsettes i den aktuelle avtalen. Det publiseres ingen standard royaltysats.",
      "Uten avtalt omfang loves ingen global kampanje, ingen mediebudsjett, ingen sponsorresultater og ingen kommersiell suksess.",
    ],
    cta: "Send en henvendelse om merkevaresamarbeid",
    cta2: "Henvendelse om trenerpartnerskap",
  },
  families: {
    title: "Familier og foreldre",
    lead: "Informerte valg av utstyr, kontinuitet i utviklingen, bevart kunnskap og bevarte rettigheter, synlig deltakelse og fordeler fastsatt av programmet som kan støtte fremtidig aktivitet.",
    nowTitle: "Tilgjengelig nå",
    now: ["Familie- og utviklingshenvendelser skriftlig.", "Valg av utstyr med treneren involvert, forespørsler om tilpasning og demonstrasjon.", "Privat dokumentasjon: barns profiler publiseres som standard aldri og kommersialiseres aldri.", "Opplæringsvei for foreldre: konfigurasjon, belastning, progresjon, dokumentasjon og rettigheter."],
    plannedTitle: "Planlagt",
    planned: ["Deltakelsesfordeler fastsatt av programmet, som kan brukes på varer og tjenester i økosystemet, i stedet for renter i kontanter.", "Eier- og familiedokumentasjon i det foreslåtte eierarkivet, med tilganger for foresatte og overføring av kontroll ved 18 år."],
    categoriesTitle: "Holdes atskilt",
    categories: ["Kontraktsfestet royalty fra lisensierte rettigheter eller kvalifiserende salg", "Deltakelsesfordeler fastsatt av et program", "Tilgodehavende for kjøp eller tjenester", "Forskuddsbetalinger", "Institusjonelt medlemskap"],
    categoriesP: "Disse kategoriene behandles aldri som utbyttbare.",
    statusTitle: "Faktisk status for familieprogrammet",
    journeyTitle: "Familieveien",
    journey: [
      ["Mål", "Hva spilleren vil oppnå neste gang."],
      ["Dagens nivå", "Hvor spilleren står i dag."],
      ["Trener", "Om en trener deltar i valg av utstyr."],
      ["Utstyr", "Passende utstyr for fasen, inkludert treningssystemer der det er relevant."],
      ["Avtalt trening", "Trenerstyrt bruk avtalt på forhånd."],
      ["Gjennomgang", "Ny vurdering på sammenlignbare kontrollpunkter."],
    ],
    brief: {
      who: "Foreldre og foresatte til spillere på alle nivåer.",
      value: "Et skriftlig svar om passende utstyr, trenerens medvirkning og neste utviklingssteg.",
      now: "Familiehenvendelser skriftlig; valg med treneren involvert; privat dokumentasjon — barns profiler publiseres aldri.",
      next: "Send familiehenvendelsen nedenfor. Du får en forespørsels-ID umiddelbart.",
    },
    formTitle: "Familiehenvendelse",
    formNote: "Skal fylles ut av en forelder eller foresatt. Ikke oppgi barnets navn, fødselsdato, skole eller helseopplysninger.",
    noPromise: "Et kjøp lover ikke royalty, investeringsavkastning, sponsing eller finansiering av et barns utvikling.",
    statusP: "Denne versjonen forklarer modellen og tar imot henvendelser om programmet. Opptjening, utbetalinger og innløsning er ikke tilgjengelig før de kvalifiserende hendelsene, de berettigede, finansieringskilden, beregningsgrunnlaget, tillatt bruk, regnskapsmessig behandling, refusjoner, tilbakeføringer, foreldelse, overførbarhet, avslutning av programmet og håndtering av uenighet er fastsatt skriftlig. Det loves ingen saldo som aldri synker, ingen deltakelse betaler all trening, og det antydes ingen kapitalbeskyttelse.",
    cta: "Send en familie- eller utviklingshenvendelse",
  },
  owners: {
    title: "Eiere og eierarkivet",
    lead: "Eierarkivet er en foreslått tilgangsstyrt dokumentasjon av utstyr, utvikling, kunnskap, innhold og dokumenterte rettigheter. Det presenteres som en del av den planlagte eierarkitekturen: det vises ingen aktive kontoer, saldoer, sertifikater eller resultater.",
    nowTitle: "For dagens eiere nå",
    now: ["Eierhenvendelser: produkt- eller serienummerreferanse, oppsett, service og forespørsler om dokumentasjon, skriftlig.", "Presisjonssertifikat og dokumentasjon av matchede sett der presisjonsklassen gir det, levert sammen med produktet."],
    archTitle: "Planlagt arkitektur for arkivet",
    arch: ["Produktidentitet og serienummerreferanser", "Konfigurasjon og gjeldende kvalitetssertifikater", "Historikk for service og oppsett", "Utviklingsdokumentasjon for spiller eller trener", "Kvalifikasjoner og verifiserte resultater", "Rettighetsklarert innhold og egne materialer", "Lisenser, tillatelser og kontraktsreferanser", "Dokumentasjon fra programmet for personlige merkevarer", "Gjeldende royaltyoppgjør eller deltakelsesfordeler"],
    separationTitle: "Hva eierskap betyr",
    separation: [
      "Eierskap til en fysisk racket er atskilt fra eierskap til en opphavsrett, en lisens, et kontraktsfestet krav eller en oppføring som beskriver disse tingene.",
      "Et lagret dokument eller en blokkjedeoppføring er ikke automatisk bevis for at en rettighet finnes eller er overført.",
      "Bevis beholder sin klassifisering: oppgitt av deltakeren, bekreftet av foresatt, validert av trener, målt av systemet.",
      "For mindreårige: privat dokumentasjon, tilganger for foresatte, ingen publiserte barneprofiler og som standard ingen kommersialisering av identitet.",
      "Eksport, retting, tilgangskontroll og en forsvarlig overføring av kontroll er en del av utformingen.",
    ],
    techTitle: "Blockchain 5.0 og MxSN",
    techP: "Blockchain 5.0 er den uttalte teknologiretningen; MxSN definerer begrepene for et tilgangsstyrt nettverk for samtykke, levering, bevis, rettigheter og rapportering. Det fremstilles ingen implementering i drift. Datamodellen i løsningen er bygd for senere å kunne integreres gjennom et dokumentert grensesnitt, uten å gi inntrykk av at en forbindelse finnes i dag.",
    cta: "Eierhenvendelse",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Forbindelsen mellom spillere, trenere, klubber, akademier, tjenesteytere, programoperatører og regionale partnere.",
    functionsTitle: "Mulige funksjoner",
    functions: ["Søk", "Introduksjoner", "Utviklingsprogrammer", "Støtte med utstyr", "Arrangementer", "Tilgang til tjenester", "Partnermuligheter"],
    statusTitle: "Faktisk status",
    statusP: "Ingen offentlig oversikt er publisert ennå: bare deltakere der identitet, relasjon og tillatelse til å stå oppført er avklart, blir listet. Et forslag sendt til en klubb er ikke et partnerskap, og en mulig distributør er ikke en utpekt distributør. Publisering av oversikten, booking, meldinger og kommersielle transaksjoner styres særskilt og er ikke i drift.",
    cta: "Søk om å bli med i nettverket",
  },
  partnerships: {
    title: "Partnerskapsveier",
    lead: "Skriftlig kvalifisering først. Hver vei fører til en rollespesifikk henvendelse; kommersielle vilkår følger skriftlig.",
    commercialTitle: "Mulige kommersielle aktiviteter på plattformen",
    commercial: ["Utstyr", "Spesialutvikling", "Personalisering", "Lag- og akademiprogrammer", "Treningssystemer", "Kontraktsfestet lisensiering", "Distribusjon", "Godkjente tjenester", "Fremtidige produktkategorier"],
    boundary: "Landrettigheter, eksklusivitet, områdeavgifter og distributørmarginer er forhandlede vilkår. Det publiseres ingen omsetning, prognose, verdsettelse, markedsandel, avkastning, finansieringsforpliktelse eller unavngitt partnerskap.",
    routes: {
      coaches: {
        title: "Trenere",
        lead: "Treningssystemer, tilpasning, profesjonell identitet, autoriserte programmer, muligheter for personlige merkevarer og leveranse av utstyr.",
        points: ["Sweet Spot Trainer og Spot Trainer i trenerstyrt trening.", "Tilpasning med konfigurasjonsmatrisene og åtte grepsstørrelser fra fabrikk.", "Coach-to-Brand: en verifisert profesjonell profil og en rettighetsstyrt undermerkevare.", "Autorisert bruk av programmer følger en skriftlig avtale."],
        cta: "Send en henvendelse om trenerpartnerskap",
        brief: {
          who: "Uavhengige trenere og trenerteam.",
          value: "Treningssystemer for trenerstyrt trening, tilpasning med seriematrisene og åtte grep fra fabrikk, og en vei til en profesjonell identitet.",
          now: "Trenerhenvendelser skriftlig. Ingen provisjon, inntjening eller formidlingssats publiseres eller antydes.",
          next: "Send trenerhenvendelsen nedenfor. Vilkårene følger skriftlig.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubber og akademier",
        lead: "Lagutstyr, treningssystemer, personalisering, utviklingsprogrammer, service og deltakelse i nettverket.",
        points: ["Lagsett og matchede sett forespørres gjennom konfiguratoren.", "Treningssystemer og metodikk for strukturert utvikling.", "Personalisering for lagprogrammer på godkjente soner.", "Prøvedager, tilpasningstimer og deltakelse i nettverket."],
        cta: "Send inn underlag for klubb eller akademi",
        brief: {
          who: "Klubber, akademier og lagprogrammer.",
          value: "Lagsett og matchede sett, treningssystemer, personalisering for lagprogrammer og prøvedager.",
          now: "Underlag fra klubber og akademier skriftlig; lagsett forespørres gjennom konfiguratoren.",
          next: "Send inn underlaget for klubb eller akademi nedenfor.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribusjon og landutvikling",
        lead: "Vareutvalg, koordinering av produksjon, teknisk kapasitet, områdeutvikling og fortrolig kommersiell kvalifisering.",
        points: ["Skriftlig kvalifisering av motparten, området og kanalen.", "Vareutvalget fastsettes ut fra konfigurasjonsmatrisene og presisjonsklassene.", "Område, eksklusivitet, volumer, prissetting og kommersiell beskyttelse er forhandlede vilkår som avtales skriftlig.", "Avtalepart, betalingsvilkår og leveringsbetingelser oppgis for hver transaksjon."],
        cta: "Send en henvendelse om distribusjon eller landutvikling",
        brief: {
          who: "Butikker, distributører og landpartnere.",
          value: "Et vareutvalg fastsatt ut fra de bekreftede matrisene, presisjonsklassene og grepsutvalget, med skriftlig kvalifisering av område og kanal.",
          now: "Distribusjonshenvendelser skriftlig. Område, eksklusivitet, volumer og prissetting forhandles — ingenting tildeles gjennom et skjema.",
          next: "Send distribusjonshenvendelsen nedenfor.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategi og investering",
        lead: "Ingeniørkompetanse, konfigurasjonsdybde, produksjonsmodell, veier til markedet, IP, tjenester og ekspansjonsmuligheter.",
        points: ["En kvalifisert strategisk samtale eller kontrollert tilgang til informasjon følger skriftlig kvalifisering.", "Offentlig informasjon er begrenset til godkjente produktspesifikasjoner, konfigurasjonsarkitektur, verifisert kapasitet og forklaringer av programmene.", "Kjøperspesifikk økonomi, kostnadsberegninger, beskyttet metodikk og upubliserte avtaler utleveres bare under taushetserklæring eller kontrakt."],
        cta: "Be om en kvalifisert strategisk samtale",
        brief: {
          who: "Investorer og strategiske partnere.",
          value: "En kvalifisert samtale om ingeniørkompetanse, konfigurasjonsdybde, produksjonsmodell, veier til markedet og IP.",
          now: "Det publiseres ingen finansielle tall, prognoser, verdsettelser eller avkastning. Kontrollert informasjon følger skriftlig kvalifisering og taushetserklæring.",
          next: "Be om en kvalifisert strategisk samtale nedenfor.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institusjonelle programmer",
        lead: "Utdanning, tilgang, innovasjon, dokumentasjon av utvikling, samfunnsnytte og programmer med riktig struktur.",
        points: ["Institusjonelle programmer struktureres gjennom MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) der programmet begrunner denne rollen.", "Øremerkede programmidler og kommersielle transaksjoner holdes atskilt.", "En henvendelse er ikke en akseptert medlemssøknad, og en kjøper av utstyr er ikke et institusjonelt medlem.", "Tilskudd, status som allmennyttig, skattemessig behandling og tillatelser fra myndigheter er landspesifikke og forutsettes aldri."],
        cta: "Send en henvendelse om institusjonelt program",
        brief: {
          who: "Institusjoner, utdannings- og utviklingsprogrammer.",
          value: "Programmer for utdanning, tilgang, innovasjon og dokumentasjon av utvikling, strukturert med den riktige operatøren.",
          now: "Institusjonelle henvendelser skriftlig. En henvendelse er ikke en medlemssøknad; kjøp av utstyr er ikke et institusjonelt medlemskap.",
          next: "Send den institusjonelle henvendelsen nedenfor.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Offentlig og kontrollert utlevering",
    disclosure: {
      public: { h: "Offentlig", p: "Godkjente produktspesifikasjoner, konstruksjon, konfigurasjonsarkitektur, treningsformål, verifisert kapasitet, forklaringer av programmene og partnerskapsveier." },
      qualified: { h: "Kvalifisert henvendelse", p: "Tekniske krav, mengder, interesse for område, omfang av utvikling og relevante kommersielle samtaler." },
      controlled: { h: "Styrt av taushetserklæring eller kontrakt", p: "Interne formler, detaljerte protokoller for kvalitetskontroll, laminatoppbygging, former, produksjonsmetoder, leverandøridentiteter, kostnadsberegninger, kjøperspesifikk økonomi, beskyttet metodikk, upubliserte avtaler og sensitiv dokumentasjon om rettigheter." },
    },
  },
  contact: {
    title: "Kontakt og forespørsler",
    lead: "Velg formålet med forespørselen din. Hvert skjema samler bare det som er nødvendig for å rute og vurdere den. Forespørsler besvares skriftlig.",
    email: "E-post",
    instagram: "Instagram",
    legalLink: "Juridisk identitet",
  },
  form: {
    purposeLabel: "Formålet med forespørselen",
    purposes: {
      selection: "Hjelp til å velge racket",
      product: "Produktforespørsel",
      fitting: "Tilpasning eller demonstrasjon",
      technical: "Teknisk underlag",
      config: "Konfigurasjonsforespørsel",
      gps: "GPS-utstyrsprofil",
      coach: "Trenerpartnerskap",
      club: "Underlag for klubb eller akademi",
      distribution: "Distribusjon eller landutvikling",
      brand: "Merkevaresamarbeid eller ambassadør",
      family: "Familie- eller utviklingshenvendelse",
      institutional: "Institusjonelt program",
      strategic: "Strategi- eller investeringssamtale",
      owner: "Eierhenvendelse",
      network: "Søknad til Sports Network",
      general: "Generell henvendelse",
    },
    fields: {
      name: "Navn",
      email: "E-post",
      role: "Din rolle",
      country: "Land eller region",
      organisation: "Organisasjon",
      message: "Din melding",
      level: "Dagens nivå",
      objectives: "Hva som betyr mest (opptil tre)",
      currentRacquet: "Dagens racket",
      grip: "Grepsstørrelse, hvis kjent",
      seriesInterest: "Serie av interesse",
      quantity: "Antall",
      city: "By eller sted for timen",
      coachInvolved: "Er en trener involvert?",
      timing: "Ønsket tidspunkt",
      targets: "Ønskede målverdier",
      limits: "Bindende grenser",
      use: "Tenkt bruk",
      tradeoffs: "Akseptable avveininger",
      basis: "Målegrunnlag",
      players: "Antall spillere",
      interests: "Interesseområder",
      territory: "Område av interesse",
      channels: "Eksisterende kanaler og erfaring",
      audience: "Målgruppe eller disiplin",
      proposal: "Foreslått samarbeid",
      goal: "Utviklingsmål",
      ageBand: "Spillerens aldersgruppe",
      scope: "Programmets omfang",
      interestArea: "Interesseområde",
      productRef: "Produkt- eller serienummerreferanse",
      requestType: "Type forespørsel",
      seeking: "Hva du ser etter",
      consent: "Jeg samtykker i at MAXIMUS kan lagre og bruke disse opplysningene for å svare på denne forespørselen. Dette er ikke et abonnement på markedsføring.",
    },
    roles: { player: "Spiller", parent: "Forelder eller foresatt", coach: "Trener", club: "Klubb eller akademi", retailer: "Forhandler", distributor: "Distributør", brand: "Merkevare eller ambassadør", investor: "Investor eller strategisk partner", institution: "Institusjon", other: "Annet" },
    interestOptions: { training: "Treningssystemer", fitting: "Tilpasning", identity: "Profesjonell identitet", programmes: "Autoriserte programmer", brand: "Personlig merkevare", supply: "Leveranse av utstyr", team: "Lagutstyr", personalisation: "Personalisering", development: "Utviklingsprogrammer", service: "Tjenester", network: "Deltakelse i nettverket" },
    ownerTypes: { setup: "Oppsett og konfigurasjon", service: "Tjenester", records: "Dokumentasjon og sertifikater", other: "Annet" },
    strategicAreas: { engineering: "Ingeniørkompetanse", configuration: "Konfigurasjonsdybde", manufacturing: "Produksjonsmodell", routes: "Veier til markedet", ip: "IP og tjenester", expansion: "Ekspansjonsmuligheter" },
    errors: {
      required: "Dette feltet er påkrevd.",
      too_long: "Denne oppføringen er for lang.",
      too_short: "Denne oppføringen er for kort.",
      invalid_email: "Skriv inn en gyldig e-postadresse, for eksempel name@example.com.",
      invalid_choice: "Velg ett av alternativene.",
      not_number: "Skriv inn et helt tall med bare sifre.",
      out_of_range: "Denne verdien er utenfor det godtatte området.",
      not_in_matrix: "Denne vekten finnes ikke i den oppførte matrisen for den valgte serien.",
      decimal_not_supported: "Skriv inn et helt tall uten desimaler.",
      too_many: "Velg høyst tre alternativer.",
      consent_required: "Samtykke er påkrevd for at MAXIMUS skal kunne svare på denne forespørselen.",
      invalid: "Denne oppføringen er ikke gyldig.",
    },
  },
  legal: {
    title: "Juridisk identitet og kontroll",
    lead: "Den offentlige merkevaren er MAXIMUS / MAXIMUS GPS. De juridiske driftsidentitetene kan skilles fra hverandre og oppgis her.",
    entities: {
      institutional: { role: "Institusjonelt programlag", p: "Leverer det institusjonelle programlaget der et program begrunner denne rollen. Ikke en kommersiell selger av racketer. En ideell, registrert organisasjon i Dubai International Financial Centre." },
      equipment: { role: "Kommersiell enhet for utstyr", p: "Den kommersielle utstyrsenheten for leveranse, distribusjon og kontraktsfestet kommersiell levering der gjeldende driftsdokumenter begrunner denne rollen. Avtaleparten i en transaksjon oppgis i dokumentene for den transaksjonen." },
      ip: { role: "IP, merkevare og kommersiell koordinering", p: "Opptrer i en etablert rolle innen IP, merkevare eller kommersiell koordinering. Det tildeles ingen ubekreftet kontraktsmessig ansvar." },
      stewardship: { role: "Referanse for forvalterskap", p: "House of Maximus er referansen for forvalterskapet av økosystemet der dette støttes av den aktuelle kilden." },
      control: { role: "Intern kontroll av IP, proveniens og dokumenter", p: "MIPA er det interne laget for IP, proveniens og dokumentkontroll. En intern MIPA-oppføring må skilles fra en ekstern registrering av varemerke, patent eller opphavsrett og fra rettslig anerkjennelse, og den utgjør ingen visuell godkjenning." },
    },
    labels: { licence: "Lisens", registration: "Registrering", vat: "VAT TRN", address: "Adresse", email: "E-post", jurisdiction: "Jurisdiksjon" },
    boundaryTitle: "Grenser",
    boundary: [
      "Et kjøp gir ikke automatisk institusjonelt medlemskap, styringsrettigheter, royalty eller investeringsrettigheter.",
      "Den institusjonelle rollen er atskilt fra kommersielle transaksjoner med utstyr.",
      "Personvern, programvilkår og ordninger for kontrollert tilgang svarer til de funksjonene som faktisk er lansert.",
      "Ingen generell angivelse av lovvalg gjelder for hver besøkende, hvert salg eller hvert utenlandsk program; avtalegrunnlaget fastsettes i hver avtale.",
    ],
  },
  privacy: {
    title: "Personvern",
    updated: "Versjon 2026-09-21 · nettsted 4.2",
    contactTitle: "Kontakt for spørsmål om personvern",
    sections: {
      collect: ["Hva som samles inn", "Når du sender et skjema: opplysningene du fyller inn (navn, e-post, rolle, land eller region, organisasjon hvis oppgitt, meldingen din og svarene i skjemaet), side- og kampanjeparameterne for besøket ditt (landingsside, språk, utm-parametere; annonseklikk-ID-er bare hvis du har tillatt analyse) og tidspunktet for innsendingen. IP-adressen din brukes bare i hashet, kortvarig form for å begrense misbruk, og lagres ikke sammen med forespørselen din."],
      purpose: ["Hvorfor", "For å svare på forespørselen din, for å utarbeide det tilbudet eller den spesifikasjonen du ba om, og for å dokumentere forespørselen. Det sendes ingen markedsføring på grunnlag av et skjema."],
      storageOn: ["Hvor forespørsler lagres", "Forespørsler lagres i en database hos Upstash, Inc. (Redis), levert gjennom hostingplattformen Vercel Inc."],
      notifyEmail: ["Varsel om en ny forespørsel", "Når en forespørsel tas imot, sendes et varsel med opplysningene du har sendt inn, på e-post til den ansvarlige MAXIMUS-postboksen."],
      notifyTelegram: ["Varsel om en ny forespørsel", "Når en forespørsel tas imot, sendes et varsel med opplysningene du har sendt inn, til den ansvarlige hos MAXIMUS gjennom Telegram (Telegram FZ-LLC, Dubai), som derfor behandler varselet under overføringen."],
      notifyWebhook: ["Varsel om en ny forespørsel", "Når en forespørsel tas imot, sendes et varsel med opplysningene du har sendt inn, til et internt MAXIMUS-endepunkt over en signert, kryptert forbindelse."],
      notifyNone: ["Varsel om en ny forespørsel", "Varsling om nye forespørsler er under oppsett. Forespørselen din lagres og leses av MAXIMUS i det interne registeret; ingenting sendes til en tredjepart for dette formålet."],
      storageOff: ["Hvor forespørsler lagres", "Lagring av forespørsler er under oppsett. Så lenge den ikke er aktiv, opplyser skjemaene om at en forespørsel ikke kan tas imot; ingenting lagres. Nettstedet driftes av Vercel Inc."],
      browser: ["Lagring i nettleseren", "Øktlagringen beholder svarene fra valglistene i GPS og konfiguratoren samt kampanjeparameterne for besøket ditt i denne nettleserøkten. Kontaktopplysninger, fritekst, graveringstekst og opplysninger om barn lagres ikke i nettleseren."],
      analyticsOn: ["Analyse", "Med ditt samtykke måler Google Analytics 4 besøk og skjemahendelser uten kontaktopplysninger eller forespørselstekst. Valget ditt beholdes i lokal lagring og kan endres når som helst under «Analyseinnstillinger» i bunnteksten. Skjemaene virker uten analyse."],
      analyticsOff: ["Analyse", "Det er ikke aktivert noe analyseverktøy på dette nettstedet."],
      retention: ["Lagringstid", "Det er ennå ikke satt opp noen automatisk slettefrist. Du kan be om at forespørselen din slettes, når som helst."],
      children: ["Barn", "Skjemaene skal fylles ut av en voksen. Forespørsler som gjelder spillere under 18 år, sendes av en forelder eller foresatt. Ikke send inn et barns navn, fødselsdato, skole eller helseopplysninger. Barns profiler publiseres aldri."],
      rights: ["Dine rettigheter", "For å få innsyn i, rette eller slette forespørselen din, skriv til gps@maximus.tennis og oppgi forespørsels-ID-en din."],
      controlled: ["Kontrollert informasjon", "Fortrolige dokumenter lagres ikke på og leveres ikke fra dette nettstedet. Kontrollert utlevering skjer under taushetserklæring eller kontrakt gjennom egne kanaler."],
    },
  },
  terms: {
    title: "Bruksvilkår",
    copyright: "Opphavsretten til dette nettstedet — til tekstene, fotografiene, designet og koden — tilhører Maximus Kiriyakulov alene. Den er ikke overdratt til noe selskap eller til noen annen person.",
    updated: "Versjon 2026-09-21",
    sections: [
      ["Informasjon, ikke tilbud", "Produktinformasjonen på dette nettstedet beskriver godkjente spesifikasjoner, konfigurasjonsarkitektur og forklaringer av programmene. Den er ikke et salgstilbud, en prisliste, en lagerangivelse eller en leveringsforpliktelse. Kommersielle vilkår avtales særskilt og skriftlig med den avtaleparten som oppgis i hver transaksjon."],
      ["Forespørsler", "En forespørsel som sendes gjennom dette nettstedet — også GPS-profiler, konfigurasjonsforespørsler og tekniske underlag — lagres med en forespørsels-ID og vurderes. Den er ikke en akseptert ordre, en produksjonsforpliktelse, en bekreftet avtale, en medlemssøknad eller en akseptert søknad til noe program."],
      ["Spesifikasjoner og dokumentasjon", "Beregnede verdier, produksjonsmål og bekreftede spesifikasjoner skilles fra hverandre på de aktuelle sidene. Verdier for rammestivhet er produksjonsmål inntil noe annet publiseres. Det garanteres ikke noe resultat for en bestemt spiller."],
      ["Økosystem, medlemskap og rettigheter", "Kjøp av en racket gir ikke institusjonelt medlemskap, investeringsrettigheter, eierskap til immaterielle rettigheter, krav på royalty eller deltakelsesfordeler. Rettigheter følger publiserte programvilkår eller en skriftlig avtale."],
      ["Immaterielle rettigheter", "MAXIMUS®, løveemblemet, GPS-merket og innholdet på dette nettstedet er beskyttet. Interne tekniske formler, protokoller for kvalitetskontroll, laminatoppbygging, former, leverandøridentiteter, kostnadsberegninger og beskyttet metodikk utleveres ikke her."],
    ],
  },
  lead: {
    submit: "Send forespørsel",
    submitting: "Sender…",
    retry: "Prøv igjen",
    acceptedEyebrow: "Forespørsel akseptert",
    acceptedTitle: "Forespørselen din er mottatt.",
    requestId: "Forespørsels-ID",
    acceptedNext: "MAXIMUS vurderer hver forespørsel og svarer skriftlig til e-postadressen du oppgav. Ta vare på forespørsels-ID-en til eventuell oppfølging.",
    duplicate: "Denne forespørselen var allerede mottatt; det ble ikke opprettet noe duplikat.",
    another: "Start en ny forespørsel",
    errorsTitle: "Kontroller disse feltene:",
    failTitle: "Forespørselen din er ikke sendt.",
    fail: {
      offline: "Enheten din er frakoblet.",
      network: "Tilkoblingen til serveren mislyktes.",
      timeout: "Serveren svarte ikke i tid.",
      rate_limited: "Det kom for mange forespørsler fra dette nettverket. Prøv igjen om noen minutter.",
      too_fast: "Skjemaet ble sendt svært raskt. Kontroller det og send det på nytt.",
      spam_suspected: "Forespørselen ble stoppet av spamfilteret.",
      unavailable: "Forespørsler kan ikke tas imot for øyeblikket.",
      default: "Det oppstod en uventet feil.",
    },
    keepNote: "Det du har fylt inn, beholdes på denne siden, slik at du kan prøve igjen.",
    sendByEmail: "Send denne forespørselen på e-post",
    sendByEmailNote: "E-postprogrammet ditt åpnes med teksten til denne forespørselen. MAXIMUS mottar den når du sender e-posten.",
    mailConfig: "Konfigurasjon",
    mailPage: "Side",
    fallback: "Hvis problemet vedvarer, skriv til {email}. En forespørsel regnes som sendt først når en forespørsels-ID vises.",
    privacyLink: "Personvernerklæring",
    hpLabel: "La dette feltet stå tomt",
    consentShort: "Samtykke",
    after: "Etter innsending vises en forespørsels-ID på denne siden. Forespørsler vurderes og besvares skriftlig; en forespørsel er ikke en ordre.",
    basis: { unstrung: "Uten strenger", strung: "Med strenger", unknown: "Ikke sikker — avtales i spesifikasjonen" },
    hints: {
      email: "MAXIMUS svarer skriftlig til denne adressen.",
      goal: "For eksempel: første konkurranseracket, eller overgang fra en juniorracket. Ikke oppgi navn, fødselsdato eller helseopplysninger om et barn.",
      currentRacquet: "Merke og modell, hvis du vet det.",
      message: "Ikke oppgi passord, betalingsopplysninger eller helseopplysninger.",
    },
  },
  choose: {
    eyebrow: "Hjelp til å velge",
    title: "Hjelp meg å velge en racket",
    lead: "Fortell MAXIMUS hvilket nivå du spiller på og hva som betyr mest. Svarene dine vurderes, og du får et skriftlig forslag: serie, presisjonsklasse, vekt og grep.",
    stepsTitle: "Hva skjer videre",
    steps: [
      ["Dine svar", "Nivå, prioriteringer og grepsstørrelse hvis du kjenner den."],
      ["Faglig vurdering", "MAXIMUS sammenligner svarene dine med seriematrisene."],
      ["Skriftlig forslag", "En foreslått konfigurasjon og neste steg, skriftlig."],
    ],
    formTitle: "Dine svar",
    submit: "Be om hjelp til å velge",
    altTitle: "Vil du bestemme selv?",
    altGps: "Detaljert GPS-profil",
    altBuild: "Konfigurer direkte",
    note: "Ingen automatisk tilpasning og ingen påstand om treffsikkerhet: et menneske vurderer hver forespørsel.",
  },
  consent: {
    title: "Analyse",
    text: "Kan MAXIMUS måle besøk med Google Analytics? Skjemaene virker uansett; ingen kontaktopplysninger og ingen forespørselstekst sendes til analysen.",
    allow: "Tillat analyse",
    decline: "Avslå",
  },
  familyPlan: {
    title: "Familieplan",
    metaDescription: "Beregn familiens tennisbudsjett: treningsøkter, timer, ballkontakter og prisen på én økt, én time og ett slag — ut fra dine egne tall, i tre scenarioer.",
    eyebrow: "Familieplan · Bidra sammen med oss",
    heroTitle: "Hva koster familiens tennis — og hva får du for pengene?",
    heroLead: "Beregn familiebudsjettet, treningsøktene og timene det betaler for, de anslåtte ballkontaktene og prisen på én økt, én time og ett slag — på dine egne premisser.",
    heroCta: "Beregn familieplanen din",
    strategy: {
      eyebrow: "Vårt mål",
      title: "Mer tennis. Flere muligheter. Sammen.",
      p1: "Målet vårt er å gjøre verdens tennismarked ti ganger større ved å øke deltakelsen og gjøre veien inn i tennis tydeligere og mer tilgjengelig. MAXIMUS sikter mot å gå foran gjennom ledelse, metodikk, kvalitet, resultater og popularisering av spillet.",
      p2: "Vi ser de andre tennisprodusentene og merkevarene deres som mulige partnere. Vi foreslår å samle styrkene til selskaper, trenere, klubber og familier i et felles program for å utvikle, fremme og skalere tennis til gjensidig nytte.",
      p3: "MAXIMUS er det femte elementet i denne tilnærmingen: den samlende rollen som hjelper atskilte styrker å virke sammen. Våre felles utfordringer er sykdom, fysisk inaktivitet blant barn og hindringene som stopper folk fra å begynne å spille og fra å fortsette.",
      p4: "For en familie begynner alt med oversikt. Familieplanen viser budsjettet, antallet treningsøkter og timer, det anslåtte omfanget av ballkontakter og hva treningen koster. Endre forutsetningene og velg scenarioet som passer for deg.",
      note: "En tidobling er det strategiske målet for MAXIMUS, ikke et resultat som allerede er oppnådd. Kalkulatoren viser scenarioberegninger og lover ingen besparelse, ingen medisinsk effekt og intet sportslig resultat.",
      ctaCalc: "Beregn familieplanen din",
      ctaPartner: "Drøft hvordan vi kan utvikle tennis sammen",
    },
    beyond: {
      eyebrow: "Utenfor banen",
      title: "Hva planen bygger opp i tillegg til treningen",
      admission: {
        h: "Opptak ved ledende skoler og universiteter",
        p: "MAXIMUS støtter familien på veien inn til ledende skoler og universiteter over hele verden: med å bygge opp spillerens sportslige CV, forberede dokumenter og søknader og velge studieprogrammer der idrett og studier går hånd i hånd. Hvis et idrettsstipend blir tildelt, reduserer det familiens utgifter til utdanning.",
      },
      assets: {
        h: "Digitale eiendeler: spillerens navn, bilde og meritter",
        p: "En spillers navn, bilde, resultater, innhold og personlige merkevare er eiendeler, og over tid kan de bygge opp betydelig økonomisk verdi og statusverdi. MAXIMUS hjelper med å skape dem, registrere dem og beskytte dem, slik at verdien blir værende hos spilleren og familien.",
      },
      note: "Ingen av delene inngår i kalkulatoren. Verdien av en skoleplass, et stipend eller en digital eiendel avhenger av den enkelte saken og anslås ikke her.",
      cta: "Spør om støtte ved opptak og digitale eiendeler",
    },
    steps: ["Familiens opplysninger", "Økonomi per økt", "Langsiktig plan", "Sluttberegning"],
    stepsLabel: "Trinn i kalkulatoren",
    scenarios: { now: "Nå", planned: "Planlagt", wish: "Ønsket" },
    scenarioHints: { now: "Det familien din gjør i dag.", planned: "Det du har tenkt å gjøre videre.", wish: "Det du gjerne vil gjøre." },
    currency: {
      label: "Valuta",
      note: "Alle beløp du legger inn, er i denne valutaen. Ingenting regnes om.",
    },
    fields: {
      players: { label: "Spillende familiemedlemmer", hint: "Helt tall." },
      cost: { label: "Pris for én treningsøkt for én spiller", hint: "Beløp i hele enheter, inkludert avgifter og gebyrer." },
      sessions: { label: "Treningsøkter per spiller per måned", hint: "Helt tall." },
      minutes: { label: "Varighet på én treningsøkt, i minutter", hint: "Hele tiden, pauser inkludert. Desimaler er tillatt." },
      contacts: { label: "Ballkontakter per spiller per treningsøkt", hint: "En kontakt er når spillerens egen racket treffer ballen. En ballveksling teller ikke som én kontakt. Tell på samme måte i alle scenarioer." },
    },
    presetsLabel: "Hurtigvalg, minutter",
    ages: {
      title: "Planens varighet",
      start: "Startalder",
      end: "Sluttalder",
      hint: "En anonym antakelse om hvor lenge planen varer, som bare brukes i den langsiktige tabellen. Ikke en fødselsdato og ikke en anbefalt startalder.",
    },
    extras: {
      title: "Familiens tilleggskostnader",
      note: "Beløpene gjelder hele familien og alle tre scenarioene. De ganges ikke med antallet spillere, og de inngår ikke i prisen på en time eller en kontakt.",
      equipment: "Første utstyr — ett beløp for perioden",
      clothing: "Klær og sko — ett beløp for perioden",
      renewal: "Fornyelse av utstyr — ett beløp for perioden, gjentas ikke automatisk",
      court: "Bane eller klubb — per måned, hele familien",
      travel: "Reiser og arrangementer — per måned, hele familien",
      quoteSource: "Hvor prisene kommer fra (valgfritt)",
      quoteDate: "Dato for prisene (valgfritt)",
      quoteNote: "Vises nøyaktig slik du skrev det inn. MAXIMUS kontrollerer ikke disse prisene.",
    },
    storage: {
      save: "Lagre planen på denne enheten",
      clear: "Slett planen fra denne enheten",
      saved: "Planen er lagret på denne enheten. Ingenting er sendt noe sted.",
      cleared: "Planen er slettet. Kalkulatoren er tilbake på startverdiene.",
      restored: "Planen din som var lagret på denne enheten, er gjenopprettet.",
      invalid: "En plan som er lagret på denne enheten, kunne ikke leses og er ikke tatt i bruk. Du kan starte en ny beregning.",
      unavailable: "Denne nettleseren tillater ikke lagring på enheten.",
    },
    annual: {
      title: "Ett år, side om side",
      sessions: "Spillerøkter per år",
      cost: "Familiens utgifter til treningsøkter per år",
      hours: "Spillertimer per år",
      length: "Varighet på én treningsøkt",
      contacts: "Ballkontakter per år",
      note: "Spillerøkter og spillertimer legger sammen treningsøktene til alle spillerne. De er verken leide banetimer eller gruppesamlinger: to spillere som trener sammen i 90 minutter, gir 2 spillerøkter og 3 spillertimer.",
    },
    economics: {
      title: "Prisen på en økt, en time og en kontakt",
      session: "Én treningsøkt for én spiller",
      hour: "Én times trening for én spiller",
      contact: "Én ballkontakt",
      undefinedContacts: "Ikke definert: 0 kontakter",
      undefinedMinutes: "Ikke definert: 0 minutter",
      below: "mindre enn {value}",
      note: "Bare prisen på treningsøkten inngår i disse tallene. Familiens tilleggskostnader fordeles ikke på kontaktene.",
      caption: "Antallet kontakter beregnes ut fra valgt omfang av treningsøkter og modellens antakelser. Den faktiske treningen avhenger av formatet, pausene og treningsforholdene. Prisen på en kontakt er et budsjettmål, ikke et mål på kvaliteten i trenerarbeidet.",
    },
    longTerm: {
      title: "Langsiktig utgiftsplan",
      horizon: "Tidshorisont",
      activeYears: "Aktive år",
      years: "{n} år",
      note: "Antallet aktive år begrenses av forskjellen mellom de to aldrene. Priser, hyppighet, inflasjon, sesonger, fravær og valutakurser holdes konstante. Tilleggskostnader er ikke med i denne tabellen.",
    },
    final: {
      title: "Sluttberegning",
      scenario: "Valgt scenario",
      months: "Periode, i måneder",
      heading: "{scenario} · {months} måneder",
      total: "Totalt for perioden",
      training: "Treningsøkter",
      extras: "Tilleggskostnader",
      oneOff: "Engangsposter",
      monthly: "Månedlige poster × måneder",
      sessions: "Spillerøkter i perioden",
      hours: "Spillertimer i perioden",
      contacts: "Ballkontakter i perioden",
      formulaTitle: "Slik beregnes det",
      formula: "Totalt = spillere × treningsøkter per måned × måneder × pris per økt + engangskostnader + måneder × månedlige tilleggskostnader.",
      formulaNote: "Tilleggskostnader legges inn for hele familien. Engangsposter telles én gang, også for en periode på 0 måneder.",
      inputs: "Dine opplysninger",
    },
    units: { min: "min", h: "t", approx: "≈" },
    errors: {
      title: "Rett disse feltene for å se resultatet",
      required: "Påkrevd — skriv inn et tall; 0 er tillatt.",
      negative: "Kan ikke være negativt.",
      integer: "Bare hele tall.",
      number: "Skriv inn et tall.",
      tooLarge: "Tallet er for stort til å regne med.",
      endBeforeStart: "Sluttalderen kan ikke være lavere enn startalderen.",
      tooLong: "Høyst 200 tegn.",
      date: "Skriv inn en gyldig dato.",
      currency: "Velg en valuta.",
      scenario: "Velg et scenario.",
      result: "Resultatet er for stort til å vises pålitelig. Reduser verdiene.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: hele komposisjonen — treningsredskapet forfra og fra siden, det graverte runde løveemblemet på det runde treffhodet, graveringen MAXIMUS og SPOT TRAINER langs skaftet og den åttekantede endehetten med løvemerket",
    greatHero: "MAXIMUS GREAT-serien, 369 g: hele komposisjonen med røde og gule detaljer på hodet, blank MAXIMUS-skrift, Maximus-autografen på skaftet og endehetten med løven",
    spotDetail: "To MAXIMUS Spot Trainer sett nærmere: den graverte løven på det matt svarte treffhodet, det riflede grepbåndet og de åttekantede endehettene med løvemerket",
    spotPair: "To MAXIMUS Spot Trainer lagt i vinkel på en mørk flate, med MAXIMUS gravert langs det ene skaftet og SPOT TRAINER langs det andre, og løveemblemet på hvert treffhode",
    spinVisual: "MAXIMUS SPIN: hode med strenger, blank MAXIMUS-skrift, grep og endehette med løven",
    powerVisual: "MAXIMUS POWER: hode med strenger, blank MAXIMUS-skrift, personaliseringsgravering, grep og endehette med løven",
    greatVisual: "MAXIMUS GREAT: hode med strenger, blank MAXIMUS-skrift, personaliseringsgravering, grep, endehette med løven og G-seriemerket på halsen",
    spinHead: "MAXIMUS SPIN: hode og strengebed",
    handleLion: "MAXIMUS: hals, grep og endehette med løvemerket",
    engraving: "Sølvfarget personaliseringsgravering på skaftet",
    lettering: "Blank svart MAXIMUS-skrift på en matt svart ramme",
    variantAlt: "MAXIMUS {series}-serien — {w} g, balanse {b} mm: komplett visualisering med spesifikasjonsfeltet, sonen for personaliseringsgravering og MIPA-merkingen",
    sstSystem: "MAXIMUS Sweet Spot Trainer, system med fire racketer",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Skaftene på Sweet Spot Trainer med MAXIMUS-skriften",
    sstGrips: "Grep og endehetter på Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, fire endehetter med løvemerket",
    note: "Produktvisualisering",
  },
  notFound: { title: "Siden ble ikke funnet", p: "Siden du ba om, finnes ikke på dette språket.", cta: "Gå til forsiden" },
};

export default no;
