/* Polish dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const pl = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — w pełni karbonowe rakiety tenisowe wykonywane zgodnie ze specyfikacją",
    defaultDescription:
      "W pełni karbonowe rakiety tenisowe od ramy do rączki: GREAT 97 in², POWER 98 in² i SPIN 100 in², osiem fabrycznych rozmiarów rączki L0–L7, klasy precyzji dla wagi, balansu, swingweightu i sztywności ramy oraz konstrukcje na indywidualne zamówienie.",
  },
  common: {
    statuses: {
      current: "Aktualne",
      agreement: "Dostępne po uzgodnieniu",
      development: "W opracowaniu",
      concept: "Koncepcja",
      target: "Cel produkcyjny",
      modelled: "Obliczone",
      confirmed: "Potwierdzone",
      requested: "Zgłoszona architektura",
      notprovided: "Nie podano",
    },
    brief: { who: "Dla kogo", value: "Co Państwo otrzymują", now: "Potwierdzone obecnie", next: "Następny krok" },
    labels: {
      next: "Dalej",
      back: "Wstecz",
      edit: "Edytuj odpowiedzi",
      review: "Podsumowanie",
      start: "Rozpocznij",
      restart: "Rozpocznij ponownie",
      copy: "Kopiuj treść zgłoszenia",
      copied: "Skopiowano",
      openEmail: "Otwórz program pocztowy, aby wysłać to zgłoszenie",
      reference: "Referencja zgłoszenia",
      weight: "Waga",
      balance: "Balans",
      swingweight: "Swingweight",
      stiffness: "Sztywność ramy",
      grip: "Rozmiar rączki",
      headSize: "Rozmiar główki",
      series: "Seria",
      precisionClass: "Klasa precyzji",
      quantity: "Ilość",
      notProvided: "Jeszcze nieopublikowane",
      requestTarget: "Zgłoszona wartość docelowa",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Czytaj więcej",
      allSeries: "Wszystkie serie",
      points: "wagi z listy",
      optional: "opcjonalnie",
      required: "wymagane",
      select: "Wybierz",
      yes: "Tak",
      no: "Nie",
      unknown: "Nie wiem",
      custom: "Własna wartość docelowa",
      listed: "Waga z listy",
      individual: "Rakieta pojedyncza",
      pair: "Dobrana para",
      triple: "Dobrana trójka",
      team: "Zestaw drużynowy",
      summaryTitle: "Podsumowanie zgłoszenia",
      nextAction: "Następne działanie",
      status: "Status",
      learn: "Dowiedz się więcej",
      schematic: "Schemat — nie jest pomiarem",
      photo: "Zdjęcie",
    },
    ecosystemStrip: "Ekosystem MAXIMUS",
    truth: {
      noPrices: "Ceny, minimalne ilości, terminy realizacji, gwarancje i zobowiązania dostawy są potwierdzane na piśmie dla każdego rynku i każdego programu.",
      requestNotOrder: "Zgłoszenie jest wnioskiem o przegląd. Nie jest przyjętym zamówieniem, zobowiązaniem produkcyjnym ani potwierdzonym terminem spotkania.",
      noGuarantee: "Żaden opisany tu sprzęt, żadna metoda i żaden program nie gwarantują wyniku konkretnemu zawodnikowi.",
      governing: "Ta strona jest publikowana w kilku językach. Wersja angielska jest wersją wiążącą; tłumaczenie służy wygodzie czytelnika.",
    },
  },
  nav: {
    language: "Język",
    groups: { racquets: "Rakiety", training: "Trening", ecosystem: "Ekosystem", partnerships: "Współpraca" },
    familyPlan: "Plan rodzinny",
    racquets: "Serie rakiet i porównanie",
    great: "GREAT — 97 in² · Kontrola",
    power: "POWER — 98 in² · Moc",
    spin: "SPIN — 100 in² · Rotacja",
    precision: "Precyzja i sztywność ramy",
    grip: "Fabryczna architektura rączki L0–L7",
    custom: "Konstrukcje na zamówienie",
    training: "Systemy treningowe",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodyka",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Pomoc w wyborze",
    ecosystem: "Mapa ekosystemu",
    engineering: "Konstrukcja i produkcja",
    experience: "Testy i dobór rakiety",
    brands: "Marki osobiste i ambasadorzy",
    families: "Rodziny i rodzice",
    owners: "Właściciele i archiwum właściciela",
    network: "Sports Network",
    partnerships: "Wszystkie formy współpracy",
    coaches: "Trenerzy",
    clubs: "Kluby i akademie",
    distribution: "Dystrybucja i rozwój rynków krajowych",
    strategic: "Strategia i inwestycje",
    institutional: "Programy instytucjonalne",
    contact: "Kontakt",
    legal: "Tożsamość prawna",
    privacy: "Prywatność",
    terms: "Regulamin",
    menu: "Menu",
    close: "Zamknij",
    home: "Strona główna",
    skip: "Przejdź do treści",
  },
  footer: {
    line: "Rakieta MAXIMUS to Państwa klucz do świata MAXIMUS.",
    product: "Produkt",
    ecosystem: "Ekosystem",
    company: "Organizacja",
    instagram: "Instagram",
    email: "E-mail",
    analytics: "Ustawienia analityki",
    subscribe: {
      title: "W kontakcie z MAXIMUS",
      line: "Nowe serie, terminy doboru rakiety, materiały treningowe i program dla właścicieli. Kilka listów w roku, nic więcej.",
      label: "Adres e-mail",
      placeholder: "your@email.com",
      button: "Zapisz się",
      sending: "Wysyłanie",
      done: "Adres jest na liście. Piszemy tylko wtedy, gdy mamy coś wartego przeczytania.",
      invalid: "Prosimy sprawdzić adres.",
      failed: "Adres nie został zapisany. Prosimy spróbować ponownie za chwilę.",
      terms: "Zapisując się, zgadzają się Państwo na przesyłanie tych informacji przez MAXIMUS i na przechowywanie Państwa adresu w tym celu. W każdym liście znajduje się link do rezygnacji.",
    },
    rights: "MAXIMUS® i emblemat lwa są znakami ekosystemu MAXIMUS. MIPA — wewnętrzna kontrola własności intelektualnej, pochodzenia i dokumentów.",
    boundary:
      "Warunki handlowe i umowne są ustalane odrębnie na piśmie. Zakup rakiety nie tworzy członkostwa instytucjonalnego, praw inwestycyjnych, własności praw intelektualnych ani uprawnienia do tantiem.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Precyzja zaczyna się w punkcie kontaktu.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer i metodyka MAXIMUS łączą skoncentrowany trening z w pełni karbonowymi rakietami wyczynowymi.",
    heroCta1: "Poznaj system treningowy",
    heroCta2: "Poznaj GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrola",
    heroMeta: [
      ["Pełny karbon", "od ramy do rączki"],
      ["4 parametry", "waga · balans · swingweight · sztywność"],
      ["8 rozmiarów rączki", "fabryczna geometria L0–L7"],
      ["3 serie", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Plan rodzinny · Wnieś wkład razem z nami",
      title: "Budżet Państwa rodziny. Na co wystarcza. Co buduje.",
      p: "Trzy scenariusze obok siebie — obecny, planowany i wymarzony. Treningi, godziny i kontakty z piłką, na które wystarcza Państwa budżet, oraz koszt jednego treningu, jednej godziny i jednego uderzenia — obliczone na podstawie Państwa własnych danych.",
      points: [
        ["Państwa dane", "Każdą kwotę podają Państwo. Niczego nie zakładamy, niczego nie przeliczamy."],
        ["Trzy scenariusze", "Porównanie tego, co rodzina robi dziś, z tym, co planuje, i z tym, czego by chciała."],
        ["Dziesięć lat naprzód", "Plan wydatków na okres od roku do dziesięciu lat, ograniczony podanym przez Państwa przedziałem wieku."],
        ["Poza kortem", "Wsparcie w rekrutacji do czołowych szkół oraz aktywa cyfrowe, które pozostają przy zawodniku."],
      ],
      cta: "Oblicz swój plan rodzinny",
    },
    paths: {
      eyebrow: "Zacznij tutaj",
      title: "Wybierz swoją ścieżkę",
      items: {
        player: { h: "Zawodnik", p: "Znajdź rakietę według poziomu i priorytetów albo skonfiguruj ją bezpośrednio.", a: "Znajdź swoją rakietę" },
        parent: { h: "Rodzic", p: "Pisemna ścieżka dla celów rozwojowych, udziału trenera i odpowiedniego sprzętu.", a: "Ścieżka dla rodziny" },
        coach: { h: "Trener, klub lub akademia", p: "Systemy treningowe, dobór rakiet, zestawy drużynowe i personalizacja.", a: "Ścieżki dla trenerów i klubów" },
        partner: { h: "Dystrybutor lub partner", p: "Dystrybucja, rozwój rynków krajowych, ścieżka strategiczna i instytucjonalna.", a: "Formy współpracy" },
      },
    },
    series: {
      eyebrow: "Serie wyczynowe",
      title: "Trzy architektury wyczynowe. Jedna platforma konstrukcyjna.",
      lead: "Serię wybiera się według kierunku gry, a następnie uzupełnia konfigurację: klasa precyzji, waga, rączka, personalizacja.",
      cta: "Porównaj serie",
      configure: "Skonfiguruj",
      open: "Otwórz serię",
      photoPending: "Zdjęcie jeszcze nieopublikowane",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "System Precyzji MAXIMUS",
      title: "Waga. Balans. Swingweight. Sztywność.",
      sub: "Kontrolowane jako jeden system konstrukcyjny.",
      lead: "Trzy klasy precyzji określają, jak ściśle każda gotowa rakieta jest utrzymana w zadeklarowanej specyfikacji. P0.5 to wąska tolerancja w ramach zdefiniowanego protokołu pomiarowego — nie zerowy błąd.",
      cta: "Precyzja i sztywność w szczegółach",
    },
    stiffness: {
      eyebrow: "Sztywność ramy",
      title: "Powtarzalna reakcja ramy wobec zadeklarowanego celu.",
      p: "Sztywność ramy kształtuje reakcję, czucie i spójność między rakietami. MAXIMUS traktuje ją jako czwarty kontrolowany parametr: cel, wynik pomiaru, dopuszczalna tolerancja i możliwości przyrządu pomiarowego są prowadzone jako odrębne zapisy. Korzyścią jest powtarzalność — nie gwarantowany wynik dla każdego zawodnika.",
      cols: [["Reakcja", "Jak rama oddaje energię w punkcie kontaktu."], ["Czucie", "Co zawodnik odczuwa w punkcie kontaktu."], ["Spójność", "Rakiety zbudowane według tej samej specyfikacji reagują podobnie w granicach swojej klasy."]],
      schematicCaption: "Schemat: dopuszczalne odchylenie wokół zadeklarowanego celu sztywności dla każdej klasy. Nie jest pomiarem; nie sugeruje żadnej wartości RA.",
      bands: { p25: "tolerancja celu ±1 RA", p15: "tolerancja celu ±0.5 RA", p05: "zgodność z zadeklarowanym celem RA w ramach ustalonego fabrycznego protokołu pomiarowego — nie zerowy błąd", target: "zadeklarowany cel (bez sugerowania wartości)" },
    },
    carbon: {
      eyebrow: "Standard konstrukcji",
      title: "Pełny karbon. Od ramy do rączki.",
      p: "Wszystkie obecne rakiety MAXIMUS na tej platformie mają w pełni karbonową strukturę, łącznie z rączką. Do formowania rączki nie stosuje się pianki.",
      gripTitle: "Osiem fabrycznych rozmiarów rączki. L0–L7.",
      gripP: "Każdy rozmiar to fabryczna geometria karbonowej rączki — nie nadbudowa z owijek.",
      scaleCaption: "Schemat: nominalne oznaczenia rozmiarów rączki L0–L7 (od 4″ do 4⅞″). Nie są to zmierzone wymiary rączki.",
      cta: "Fabryczna architektura rączki",
    },
    custom: {
      eyebrow: "Konstrukcje na zamówienie",
      title: "Skonstruowane zgodnie ze specyfikacją.",
      sub: "Standardowa oferta jest punktem wyjścia.",
      p: "MAXIMUS przyjmuje wymagania techniczne wykraczające poza opublikowane matryce do oceny, opracowania konstrukcyjnego, walidacji i produkcji według uzgodnionej specyfikacji. Wykonalność jest potwierdzana na piśmie.",
      chain: ["Definicja", "Konstrukcja", "Walidacja", "Specyfikacja", "Produkcja", "Pomiar / zapis"],
      cta: "Przekaż brief techniczny",
      cta2: "Omów konstrukcję na zamówienie",
    },
    training: {
      eyebrow: "Systemy treningowe",
      title: "System treningowy zbudowany wokół punktu kontaktu.",
      p: "Sweet Spot Trainer, metodyka MAXIMUS i Spot Trainer łączą sprzęt z treningiem prowadzonym przez trenera: wyśrodkowany kontakt, kontrola, progresywne obciążenie i powrót do rakiety wyczynowej.",
      cta: "Systemy treningowe",
      cta2: "Poproś o prezentację",
      photoPending: "Zdjęcie trenażera jeszcze nieopublikowane",
      sstP: "Główka treningowa 50 in² do ćwiczenia wyśrodkowanego kontaktu, w czterech konfiguracjach wagowych do obciążenia wybranego przez trenera.",
      sstCta: "Poznaj Sweet Spot Trainer",
      sstCaption: "Konfiguracja 300 g, jedna z czterech",
      methodP: "Ustal cele, wybierz sprzęt, ćwicz z udziałem trenera, zapisuj obserwacje, oceniaj ponownie, koryguj i przenoś pracę do gry wyczynowej.",
      methodCta: "Poznaj metodykę",
      spotP: "Mały okrągły cel do ćwiczenia precyzyjnego, powtarzalnego punktu kontaktu.",
      spotCta: "Poznaj Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Produkcja i kontrola jakości",
      title: "Zbudowane według specyfikacji. Zmierzone i udokumentowane.",
      p: "Produkcja przebiega według pisemnej specyfikacji każdego zamówienia. Zapisy odpowiadają klasie precyzji: zachowane zapisy produkcyjne dla P2.5, zapisy indywidualne i identyfikowalność dla P1.5, kontrola indywidualna i dokumentacja dla P0.5 tam, gdzie program danego zamówienia je wdraża.",
      confirmedTitle: "Potwierdzone",
      confirmed: ["W pełni karbonowa konstrukcja od ramy do rączki.", "Klasy precyzji P2.5, P1.5 i P0.5 z czterema kontrolowanymi parametrami.", "Osiem fabrycznych rozmiarów rączki L0–L7."],
      pendingTitle: "Jeszcze nieopublikowane",
      pending: "Zdjęcia sprzętu pomiarowego, przykładowe zapisy kontroli jakości i materiały z fabryki nie są jeszcze publikowane. Nic na tej stronie nie jest certyfikatem pomiarowym.",
      captions: { lettering: "Błyszczący napis MAXIMUS na matowej ramie", buttcap: "Rączka i kapturek ze znakiem lwa", handle: "Srebrny grawer personalizacyjny", finish: "Główka i płaszczyzna naciągu" },
      cta: "Konstrukcja i produkcja",
    },
    world: {
      eyebrow: "Świat MAXIMUS",
      title: "Jeden klucz. Jeden ekosystem. Nieograniczone możliwości.",
      note: "„Nieograniczone możliwości” to wyrażenie marketingowe, a nie obietnica nieograniczonej wykonalności technicznej, dochodu czy dostępu. Zakup nie tworzy tantiem, zwrotów z inwestycji, sponsoringu ani finansowania rozwoju zawodnika.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — i Państwa nawigacja w świecie tenisa: prowadzony profil sprzętowy z odpowiedzią na piśmie." },
        personal: { h: "Personalizacja", p: "Imiona, inicjały, numery i identyfikacja drużynowa w zatwierdzonym srebrnym grawerze." },
        development: { h: "Rozwój", p: "Systemy treningowe prowadzone przez trenera, zapisy i ponowna ocena." },
        ecosystem: { h: "Rozszerzony ekosystem", p: "Marki osobiste, zapisy właścicieli, sieć, licencjonowanie i programy instytucjonalne — każdy element z faktycznym statusem." },
      },
      cta: "Poznaj ekosystem",
    },
    partners: {
      eyebrow: "Formy współpracy",
      title: "Trenerzy, kluby, dystrybutorzy i partnerzy.",
      p: "Najpierw pisemna kwalifikacja. Prawa krajowe, wyłączność i warunki handlowe są negocjowane na piśmie — nigdy nie przyznaje ich formularz.",
      cta: "Wszystkie formy współpracy",
      formTitle: "Krótkie zapytanie",
      formLead: "Prosimy wybrać cel i napisać do MAXIMUS. Numer zgłoszenia pojawi się na tej stronie.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "PAŃSTWA NAWIGACJA W ŚWIECIE TENISA" } },
    personal: { eyebrow: "Personalizacja", title: "Państwa imię. Państwa numer. Państwa MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Trzy serie. Realne parametry." },
    map: { cta: "Poznaj ekosystem" },
  },
  racquets: {
    title: "Rakiety",
    lead: "Trzy serie wyczynowe ze wspólnym standardem konstrukcji, wspólnym systemem precyzji i wspólną fabryczną architekturą rączki. Każda seria jest ustaloną architekturą wyczynową w ramach szerszej platformy konstrukcyjnej.",
    direction: { control: "Kontrola", power: "Moc", spin: "Rotacja" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Główny kierunek gry",
    compareTitle: "Porównanie serii",
    compareLead: "Wyłącznie potwierdzone dane architektury. Układy naciągu, długości, profile ramy, zakresy naciągu oraz nominalne wartości swingweightu i sztywności dla tych serii nie są publikowane; są zbierane jako zgłoszone wartości docelowe do przeglądu technicznego.",
    columns: { series: "Seria", head: "Rozmiar główki", direction: "Kierunek", weights: "Wagi z listy", range: "Zakres wagi", balance: "Dane balansu" },
    balanceModelled: "Wartości obliczone",
    balanceNotProvided: "Jeszcze nieopublikowane",
    construction: "Konstrukcja: w pełni karbonowa, od ramy do rączki · Precyzja: P2.5 / P1.5 / P0.5 · Rączki: L0–L7",
    otherTitle: "Inne sporty rakietowe",
    otherLead: "Zatwierdzone kierunki rozwoju. W tych kategoriach nie istnieją produkty na sprzedaż i nie przenosi się na nie żadnej specyfikacji tenisowej.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Tenis plażowy" },
    ctaConfigure: "Skonfiguruj zgłoszenie",
    ctaSeries: "Otwórz serię",
  },
  seriesPage: {
    eyebrow: "Serie wyczynowe",
    intro: {
      great: "Architektura GREAT 97 in² jest zbudowana wokół kontroli: zwarta główka, precyzyjny kontakt i pewność kierunku.",
      power: "Architektura POWER 98 in² jest zbudowana wokół przekazywania energii: głębokość i tempo ze stabilnej ramy.",
      spin: "Architektura SPIN 100 in² jest zbudowana wokół zachowania piłki: rotacja, margines i kształtowanie toru lotu.",
    },
    photoPending: "Zdjęcie serii jeszcze nieopublikowane",
    detailPending: "Zdjęcia detali konstrukcji i rączki dla tej serii nie są jeszcze publikowane.",
    specsTitle: "Specyfikacja i status",
    catalogue: {
      eyebrow: "Katalog serii {series}",
      title: "Warianty wagowe: {n}",
      lead: "Każdy wariant serii {series}, uporządkowany według wagi. Waga w gramach, balans w milimetrach od końca rączki. Każda wizualizacja jest pokazana w całości: nic nie jest obcięte, zasłonięte ani rozciągnięte.",
      selectLabel: "Wybierz wariant wagowy",
      select: "Pokaż ten wariant",
      selected: "Pokazany powyżej",
      balanceLabel: "Balans",
      headLabel: "Rozmiar główki",
      constructionLabel: "Konstrukcja",
      gripsLabel: "Fabryczne rozmiary rączki",
      precisionLabel: "Klasy precyzji",
      balanceConfirmed: "Balans to wartość potwierdzona dla tej wagi i zgadza się z liczbą nadrukowaną na wizualizacji.",
      balanceModelled: "Balans to wartość obliczona dla tej wagi z listy, a nie indywidualny pomiar fabryczny; zgadza się z liczbą nadrukowaną na wizualizacji.",
      zoom: "Otwórz obraz",
      close: "Zamknij",
      allTitle: "Wszystkie warianty ({n})",
    },
    specs: { head: "Rozmiar główki", direction: "Główny kierunek", weights: "Wagi z listy", range: "Zakres wagi", balance: "Balans", construction: "Konstrukcja", grips: "Rączki fabryczne", precision: "Klasy precyzji" },
    construction: "W pełni karbonowa, od ramy do rączki",
    statusTitle: "Status wartości",
    matrixTitle: "Pełna matryca wag",
    matrixLead: "Wagi z listy to standardowy wybór. Inne wagi można zgłosić jako własne wartości docelowe; brakujące wartości pośrednie nie są dopisywane.",
    balanceNote: {
      confirmed: "Wartości balansu są potwierdzone dla każdej wagi z listy (mm od końca rączki) i zgadzają się z liczbą nadrukowaną na wizualizacji danej wagi. Nie są tu obliczane ani wygładzane między sąsiednimi wagami; podstawa pomiaru jest potwierdzana w pisemnej specyfikacji.",
      modelled: "Wartości balansu są obliczane dla każdej wagi z listy (mm od końca rączki). Nie są indywidualnymi pomiarami fabrycznymi; podstawa pomiaru jest potwierdzana w pisemnej specyfikacji.",
      notprovided: "Wartości balansu dla tej serii nie są podane. Nie należy ich wnioskować z innej serii.",
    },
    optionsTitle: "Precyzja, rączka i waga",
    notPublished: "Nieopublikowane dla tej serii: układ naciągu, długość, profil ramy, zakres naciągu oraz wartości swingweightu i sztywności. Można je podać jako zgłoszone wartości docelowe do przeglądu technicznego.",
    offerTitle: "Co dzieje się po zgłoszeniu",
    offerSteps: [
      ["Zgłoszenie", "Prosimy przekazać konfigurację lub pytanie. Numer zgłoszenia pojawia się natychmiast."],
      ["Przegląd", "MAXIMUS analizuje serię, klasę, wagę, rączkę i wszystkie zgłoszone wartości docelowe."],
      ["Odpowiedź na piśmie", "Specyfikacja, dostępność i warunki handlowe są potwierdzane na piśmie."],
    ],
    faqTitle: "Pytania",
    faq: [
      ["Czy wartości balansu są zmierzone?", "Są obliczone dla wag z listy i nie są pomiarami indywidualnymi. Podstawa pomiaru jest potwierdzana w pisemnej specyfikacji."],
      ["Czy można zgłosić wagę, której nie ma na liście?", "Tak, jako własną wartość docelową w pełnych gramach. Podlega przeglądowi technicznemu, a wykonalność jest potwierdzana na piśmie."],
      ["Co zmienia klasa precyzji?", "To, jak ściśle waga, balans, swingweight i sztywność są utrzymane w zadeklarowanej specyfikacji oraz jakie zapisy są prowadzone."],
      ["Czy rączka jest pogrubiana owijkami?", "Nie. L0–L7 to fabryczne geometrie karbonowej rączki."],
      ["Gdzie są ceny i terminy dostaw?", "Są potwierdzane na piśmie dla każdego zgłoszenia i nie są tu publikowane."],
    ],
    faqSpinBalance: ["Skąd pochodzą wartości balansu SPIN?", "Z potwierdzonej tabeli serii Spin: 33 warianty wagowe z balansem w milimetrach od końca rączki. Każda para zgadza się z liczbą nadrukowaną na zatwierdzonej wizualizacji danej wagi. Wartości nie są obliczane ani wygładzane między sąsiednimi wagami."],
    ctaBuild: "Skonfiguruj tę serię",
    ctaAsk: "Zapytaj o tę serię",
    ctaCompare: "Porównaj wszystkie serie",
    weightsLabel: "wagi z listy",
    headLabel: "główka",
  },
  precision: {
    title: "Precyzja i sztywność ramy",
    switch: { label: "Wybierz klasę precyzji", panelLabel: "Cztery kontrolowane parametry —", qcLabel: "Architektura kontroli jakości", protocolNote: "w ramach zdefiniowanego fabrycznego protokołu pomiarowego kontroli jakości", fullTable: "Pełna tabela porównawcza" },
    lead: "Cztery parametry kontrolowane jako jeden system konstrukcyjny. Każda klasa określa, jak ściśle gotowa rakieta jest utrzymana w zadeklarowanej specyfikacji i jakie zapisy jakości powstają.",
    statement: "Waga. Balans. Swingweight. Sztywność. Kontrolowane jako jeden system konstrukcyjny.",
    classes: {
      "P2.5": { name: "Skalowalny rdzeń wyczynowy", qc: "Pomiar indywidualny i zachowane zapisy produkcyjne." },
      "P1.5": { name: "Precyzja rozszerzona", qc: "Pomiar indywidualny, zapisy indywidualne i identyfikowalność." },
      "P0.5": { name: "Profesjonalna · kontrolowana indywidualnie", qc: "Kontrola indywidualna z wartościami nominalnymi i rzeczywistymi oraz indywidualnymi zapisami pomiarowymi; identyfikacja seryjna, identyfikowalność partii, certyfikat precyzji i zestawy dobrane tam, gdzie program danego zamówienia je wdraża." },
    },
    columns: { cls: "Klasa", weight: "Waga", balance: "Balans", sw: "Swingweight", stiff: "Sztywność", qc: "Architektura kontroli jakości" },
    stiffTarget: "tolerancja celu",
    stiffExact: "zgodność z zadeklarowanym celem RA w ramach ustalonego fabrycznego protokołu pomiarowego",
    programmeNote: "Identyfikacja seryjna, certyfikaty i dokumentacja zestawów dobranych są wydawane tylko tam, gdzie program konkretnego zamówienia je wdraża.",
    targetsNote: "Specyfikacje sztywności są celami produkcyjnymi do czasu, gdy odpowiedni protokół i dowody produkcyjne pozwolą na mocniejsze twierdzenie. Propozycja architektury nie oznacza, że każda wymieniona konfiguracja przeszła już pełny proces zwolnienia według czterech parametrów.",
    stiffnessTitle: "Dlaczego sztywność ma znaczenie",
    stiffnessP1: "Sztywność ramy wpływa na to, jak rama reaguje w punkcie kontaktu, jak jest odczuwana i jak spójne są ze sobą dwie rakiety. Główną korzyścią z jej kontroli jest powtarzalna reakcja wobec zadeklarowanej specyfikacji.",
    stiffnessP2: "Przed opublikowaniem zweryfikowanej zgodności wewnętrzny zapis kontroli jakości wskazuje przyrząd, jego status wzorcowania, metodę, stan rakiety, rozdzielczość, niepewność pomiaru, pomiary powtórzone, zasadę zaokrąglania i kryterium przyjęcia. Identyczna wyświetlana liczba całkowita nie jest dowodem zerowej zmienności fizycznej ani zerowego błędu pomiaru.",
    fields: ["Cel", "Wynik pomiaru", "Dopuszczalna tolerancja", "Możliwości przyrządu"],
    fieldsNote: "Prowadzone jako odrębne pola w każdym zapisie.",
    matchedTitle: "Zestawy dobrane",
    matchedP: "Kryteria zestawu dobranego są definiowane odrębnie od tolerancji indywidualnej. Zgodność każdej rakiety z jej tolerancją nominalną sama w sobie nie dowodzi określonej maksymalnej różnicy między dwiema rakietami. Dobrane pary, trójki i zestawy drużynowe zgłasza się przez konfigurator i potwierdza na piśmie.",
    extendedTitle: "Rozszerzony model techniczny",
    extendedP: "Model danych obsługuje dodatkowe parametry. Nie istnieją dla nich jeszcze wartości ani klasy tolerancji; można je podać jako zgłoszone wartości docelowe w briefie technicznym.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Zachowanie skrętne", length: "Długość", beamProfile: "Profil ramy", headGeometry: "Geometria główki", stringPattern: "Układ naciągu", durability: "Trwałość", vibration: "Charakterystyka wibracji" },
    noZero: "MAXIMUS nie opisuje swojej oferty katalogowej jako mającej zerową tolerancję. Precyzja w tej ofercie jest podawana jako klasa z zadeklarowaną tolerancją i zdefiniowaną architekturą kontroli jakości. ZERO nie jest częścią tej oferty.",
    zero: {
      eyebrow: "Opcja ekskluzywna",
      title: "ZERO",
      sub: "Zerowa tolerancja co do grama.",
      p: "Trzy klasy utrzymują gotową rakietę w zadeklarowanym przedziale tolerancji. ZERO znosi ten przedział. Rakieta jest budowana i mierzona do chwili, gdy wskazanie jest równe zadeklarowanej wartości w rozdzielczości fabrycznego przyrządu pomiarowego, a to wskazanie jest wydawane razem z nią. Nie należy do oferty katalogowej i nie jest czwartą klasą: jest uzgadniane indywidualnie, dla jednej rakiety lub jednego zestawu dobranego, jako ekskluzywna konstrukcja na zamówienie. Po uzgodnieniu to samo podejście stosuje się do balansu i swingweight.",
      points: [
        ["Brak przedziału", "Zadeklarowana wartość jest wynikiem, a nie środkiem tolerancji."],
        ["Pojedynczo", "Budowana, mierzona i zapisywana jako jedna sztuka."],
        ["Wydawane razem z rakietą", "Zmierzone wskazanie jest przekazywane i zachowywane w zapisie produkcyjnym."],
        ["Potwierdzane na piśmie", "Parametry, zakres i termin realizacji są uzgadniane przed produkcją."],
      ],
      note: "Zgodność jest osiągana w rozdzielczości fabrycznego przyrządu pomiarowego. Identyczna wyświetlana wartość nie jest twierdzeniem o zerowej zmienności fizycznej. Dostępność i warunki są uzgadniane indywidualnie dla każdego zamówienia.",
      cta: "Poproś o ZERO",
    },
    cta: "Skonfiguruj z klasą precyzji",
  },
  grip: {
    title: "Fabryczna architektura rączki",
    statement: "Osiem fabrycznych rozmiarów rączki. L0–L7.",
    lead: "Geometria rączki jest częścią architektury karbonowej rączki. Każdy rozmiar jest wytwarzany jako geometria rączki, a nie nadbudowywany owijkami.",
    emph: "Rozmiary rozszerzone",
    p1: "Fabryczny zakres ośmiu rozmiarów daje trenerom i zawodnikom szerszy zakres konfiguracji, w którym sprzęt można dobrać do zawodnika, łącznie z większymi geometriami L6 i L7.",
    p2: "Nominalne oznaczenie rozmiaru rączki różni się od surowych wymiarów rączki konstrukcyjnej i od końcowego protokołu pomiarowego. Rozmiary dotyczą serii wyczynowych i rodzin treningowych na tej platformie.",
    p3: "Nie zgłasza się żadnych roszczeń do wyłączności światowej dla tego zakresu.",
    columns: { size: "Rozmiar", nominal: "Nominalnie", family: "Dotyczy" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Skonfiguruj ze swoim rozmiarem rączki",
  },
  custom: {
    title: "Konstrukcje na zamówienie",
    statement: "Skonstruowane zgodnie ze specyfikacją.",
    sub: "Standardowa oferta jest punktem wyjścia.",
    lead: "MAXIMUS przyjmuje wymagania techniczne wykraczające poza opublikowane matryce konfiguracji do oceny, opracowania konstrukcyjnego, walidacji i produkcji według uzgodnionej specyfikacji. Wykonalność jest potwierdzana w przeglądzie — nie każde wyobrażalne zgłoszenie jest wykonalne fizycznie lub handlowo.",
    scopeTitle: "Czego może dotyczyć brief techniczny",
    scope: ["Geometria główki i ramy", "Długość", "Waga", "Balans", "Swingweight", "Sztywność", "Twistweight", "Geometria rączki", "Konstrukcja", "Zestawy dobrane", "Ramy treningowe", "Kosmetyka i grawer", "Identyfikacja i programy drużynowe", "Rozwój zależny od oprzyrządowania"],
    processTitle: "Proces",
    process: [
      ["Definicja", "Preferowane wartości docelowe, obowiązkowe ograniczenia, przeznaczenie i akceptowalne kompromisy."],
      ["Konstrukcja", "Ocena konstrukcyjna wobec platformy i oprzyrządowania."],
      ["Walidacja", "Walidacja wobec uzgodnionej specyfikacji."],
      ["Specyfikacja", "Pisemna specyfikacja z podstawą pomiaru i tolerancjami."],
      ["Produkcja", "Produkcja według specyfikacji."],
      ["Pomiar / zapis", "Pomiar i zachowane zapisy zgodnie z obowiązującą klasą precyzji."],
    ],
    formTitle: "Przekaż brief techniczny",
    formLead: "Należy odróżnić preferowane wartości docelowe od obowiązkowych ograniczeń. Efektem jest zgłoszenie do przeglądu technicznego, a nie automatycznie przyjęte zamówienie produkcyjne.",
    protected: "Receptury laminatów, oprzyrządowanie, dane dostawców, wewnętrzna kalkulacja kosztów i chroniona wiedza techniczna nie są ujawniane tą drogą.",
    cta: "Przekaż brief techniczny",
  },
  training: {
    title: "Systemy treningowe",
    lead: "Dwie rodziny treningowe z własnymi standardami produkcji, połączone jedną metodyką: trening prowadzony przez trenera, zapisy, ponowna ocena i powrót do gry wyczynowej.",
    sst: { h: "Sweet Spot Trainer", p: "Rakieta treningowa o zmniejszonej główce 50 in² w systemie czterech wag do ćwiczenia wyśrodkowanego kontaktu, świadomości sweet spotu, kontroli rakiety i progresywnego obciążenia." },
    spot: { h: "Spot Trainer", p: "Trening punktu kontaktu z małym okrągłym celem, na zatwierdzonej podstawie czterech wag." },
    method: { h: "Metodyka", p: "Ustalenie celów, wybór sprzętu z udziałem trenera, korzystanie z właściwego systemu, zapis, ponowna ocena, korekta i przeniesienie efektów." },
    experience: "Chwyć ją. Zamachnij nią. Poczuj ją.",
    experienceP: "Można poprosić o testy, dobór rakiety lub prezentację z udziałem trenera. Przekazane zgłoszenie nie jest potwierdzonym terminem spotkania.",
    cta: "Poproś o dobór rakiety lub prezentację",
    distinct: "Sweet Spot Trainer, Spot Trainer i każde odrębne urządzenie demonstracyjne są osobnymi produktami i nigdy nie są łączone.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Odrębna kategoria treningowa z własnym standardem produkcji. Główka 50 in² skupia uwagę na miejscu kontaktu; cztery wagi zapewniają progresję obciążenia.",
    baseline: "Potwierdzona podstawa",
    columns: { head: "Główka", length: "Długość", pattern: "Układ naciągu", grips: "Rączki fabryczne" },
    systemTitle: "System czterech rakiet",
    detailsTitle: "Szczegóły konstrukcji",
    systemLead: "Waga i balans w stanie dostawy. Podstawa pomiaru jest zapisywana odrębnie i nie jest jeszcze publikowana.",
    purposeTitle: "Przeznaczenie",
    purpose: ["Ćwiczenie wyśrodkowanego kontaktu", "Świadomość sweet spotu", "Kontrola rakiety", "Progresywne obciążenie", "Rozwój prowadzony przez trenera", "Powrót do rakiety wyczynowej zawodnika"],
    heavy: "Model 400 g jest kontrolowaną konfiguracją treningową. Nie jest automatycznie zalecany dzieciom, początkującym ani każdemu zawodnikowi; obciążenie, czas i progresję określa trener.",
    precisionNote: "Wyczynowe klasy precyzji P2.5, P1.5 i P0.5 nie są automatycznie stosowane do tej rodziny treningowej. Tolerancje produkcji treningowej wynikają z własnej zatwierdzonej specyfikacji tej rodziny.",
    health: "Nie obiecuje się zapobiegania ani leczenia łokcia tenisisty, eliminacji urazów ani gwarantowanej poprawy.",
    cta: "Poproś o prezentację modelu Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Trening punktu kontaktu z małym okrągłym celem. Osobny produkt z własną identyfikacją wizualną, zbudowany na zatwierdzonej podstawie czterech wag.",
    purposeTitle: "Potwierdzone przeznaczenie",
    purposeP: "Nauczenie zawodnika znajdowania i powtarzania precyzyjnego punktu kontaktu.",
    weightsTitle: "Progresja wag",
    weightsP: "Progresja wag wynika z zatwierdzonej podstawy wagowej Sweet Spot Trainer. Wartości balansu i inne specyfikacje Sweet Spot Trainer nie są przenoszone na Spot Trainer.",
    dims: "Dokładne wymiary celu nie są jeszcze publikowane.",
    grips: "Fabryczna architektura rączki L0–L7.",
    notes: ["Wyczynowe klasy precyzji nie są stosowane automatycznie.", "Nie jest miniaturą zwykłej rakiety i nie publikuje się układu naciągu.", "Spot Trainer, Sweet Spot Trainer i każde odrębne urządzenie demonstracyjne pozostają rozróżnialne."],
    cta: "Zapytaj o Spot Trainer",
  },
  methodology: {
    title: "Metodyka i doświadczenie produktu",
    lead: "Sprzęt jest jedną częścią uporządkowanej drogi rozwoju. Metoda zaczyna się od celów zawodnika, a nie od nazwy produktu.",
    stepsTitle: "Droga rozwoju",
    steps: [
      ["Ustalenie celów", "Cele zawodnika i punkt wyjścia."],
      ["Wybór sprzętu", "Odpowiedni sprzęt wybrany z udziałem trenera."],
      ["Korzystanie z systemu", "Właściwy system treningowy, prowadzony przez trenera."],
      ["Zapis", "Obserwacje faktycznego udziału, bez wymyślonych wyników."],
      ["Ponowna ocena", "Porównywalne punkty kontrolne."],
      ["Korekta", "Korekty konfiguracji lub programu."],
      ["Przeniesienie", "Przeniesienie nauki do gry wyczynowej."],
    ],
    educationTitle: "Ścieżki edukacyjne",
    education: { player: "Zawodnicy — zrozumienie konfiguracji, obciążenia i progresji.", parent: "Rodzice — ciągłość rozwoju, odpowiedni sprzęt, zapisy i prawa.", coach: "Trenerzy — systemy treningowe, dobór rakiet, ocena i autoryzowane korzystanie z programów." },
    evidenceTitle: "Dyscyplina dowodowa",
    evidenceP: "Zapisy faktycznego udziału i obserwacje są przechowywane z klasyfikacją — zadeklarowane przez uczestnika, potwierdzone przez opiekuna, zwalidowane przez trenera lub zmierzone przez system. Postępów, wyników i walidacji nigdy się nie wymyśla.",
    experienceTitle: "Chwyć ją. Zamachnij nią. Poczuj ją.",
    experienceP: "Można poprosić o testy, dobór rakiety lub prezentację z udziałem trenera. Przekazane zgłoszenie nie jest potwierdzonym terminem spotkania.",
    cta: "Poproś o dobór rakiety lub prezentację",
    cta2: "Zapytanie o współpracę trenerską",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — prowadzony profil sprzętowy",
    title: "MAXIMUS GPS",
    lead: "Prowadzony profil sprzętowy. Odpowiadają Państwo tylko na to, co istotne, mogą przejrzeć i poprawić odpowiedzi, a następnie otrzymują podsumowanie, obowiązujące kierunki konfiguracji i realne następne działanie.",
    honesty: "W tej wersji nie zatwierdzono automatycznych reguł doboru. GPS tworzy więc jasne podsumowanie wymagań i wskazuje kierunki konfiguracji; szczegóły sprzętowe są kierowane do przeglądu eksperckiego.",
    rulesVersion: "Wersja reguł",
    dataVersion: "Wersja danych produktowych",
    steps: { role: "Rola", sport: "Dyscyplina", experience: "Doświadczenie", objectives: "Cele", style: "Styl gry", equipment: "Obecny sprzęt", preference: "Preferencje", coach: "Udział trenera", ageBand: "Grupa wiekowa", review: "Podsumowanie" },
    notStored: "Nie jest przechowywane w tej przeglądarce.",
    ageNote: "Służy wyłącznie do skierowania zgłoszenia. Nie pytamy o imię, datę urodzenia ani informacje medyczne.",
    q: {
      role: "Kim Państwo są?",
      sport: "Jaki sport?",
      experience: "Poziom doświadczenia",
      objectives: "Co jest najważniejsze? (do trzech odpowiedzi)",
      style: "Styl gry, jeśli jest znany",
      equipment: "Obecny sprzęt, jeśli jest",
      equipmentHint: "Marka i model, waga lub rozmiar rączki, jeśli są znane. Opcjonalnie.",
      preference: "Preferowana konfiguracja lub znany rozmiar rączki",
      grip: "Znany rozmiar rączki",
      coach: "Czy trener uczestniczy w decyzjach o sprzęcie?",
      ageBand: "Grupa wiekowa zawodnika (służy wyłącznie właściwemu skierowaniu zgłoszenia)",
    },
    roles: { player: "Zawodnik", parent: "Rodzic lub opiekun", coach: "Trener", club: "Klub lub akademia", other: "Inne" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Inny sport rakietowy" },
    sportNote: "Produkty istnieją dla tenisa. Pozostałe sporty są kierunkami rozwoju; Państwa zainteresowanie jest zapisywane dla odpowiedniego programu.",
    experience: { beginner: "Początkujący", developing: "Rozwijający się", intermediate: "Średnio zaawansowany", advanced: "Zaawansowany", competitive: "Startujący w zawodach", professional: "Zawodowy" },
    objectives: { control: "Kontrola", power: "Moc", spin: "Rotacja", comfort: "Komfort", manoeuvrability: "Zwrotność", development: "Rozwój długoterminowy", competition: "Zawody", training: "System treningowy", team: "Drużyna lub zestaw dobrany", personal: "Personalizacja" },
    styles: { baseline: "Gra z końca kortu", allcourt: "Gra na całym korcie", attacking: "Ofensywny", defensive: "Defensywny", coach: "Wybór trenera", unknown: "Nie wiem" },
    ageBands: { u10: "Poniżej 10 lat", u14: "10–13 lat", u18: "14–17 lat", adult: "18 lat i więcej" },
    output: {
      title: "Państwa profil sprzętowy",
      status: "Wymagany przegląd ekspercki",
      statusP: "W tej wersji nie powstaje automatyczne dopasowanie. Państwa profil został podsumowany do przeglądu eksperckiego.",
      directionsTitle: "Obowiązujące kierunki konfiguracji",
      directionsP: "Na podstawie podanych celów i zadeklarowanego kierunku gry każdej serii. To kierunek, a nie rekomendacja doboru.",
      trainingHint: "Państwa cele obejmują system treningowy: prosimy zobaczyć Sweet Spot Trainer i Spot Trainer.",
      teamHint: "Zestawy dobrane zgłasza się przez konfigurator i potwierdza na piśmie.",
      next1: "Wyślij profil do przeglądu eksperckiego",
      show: "Pokaż profil",
      configure: "Skonfiguruj",
      sendP: "Prosimy wysłać profil do MAXIMUS na przegląd ekspercki. Numer zgłoszenia pojawi się natychmiast; odpowiedź przychodzi na piśmie.",
      otherSport: "Rakiety MAXIMUS istnieją dla tenisa. Dla innych sportów rakietowych nie sugeruje się żadnej serii tenisowej; Państwa zainteresowanie jest zapisywane jako kierunek rozwoju.",
      noDirection: "Podane cele nie wskazują jednego kierunku gry. Konfigurację zaproponuje przegląd ekspercki.",
      incomplete: "Brakuje niektórych wymaganych odpowiedzi — prosimy użyć „Edytuj odpowiedzi”, aby je uzupełnić.",
    },
    privacy: "GPS nie pyta o informacje medyczne ani identyfikatory dzieci. W tej sesji przeglądarki zachowywane są tylko odpowiedzi wybrane z listy; tekst swobodny nie jest przechowywany.",
  },
  build: {
    title: "Zbuduj swoją rakietę",
    lead: "Prosimy skonfigurować zgłoszenie: seria, klasa precyzji, waga z listy lub własna wartość docelowa, rozmiar rączki, zgłoszone wartości docelowe, personalizacja, zestawy dobrane i ilość. Efektem jest zgłoszenie konfiguracji z numerem — nie SKU, cena, data dostawy ani certyfikat.",
    steps: { series: "Seria", cls: "Klasa precyzji", weight: "Waga", grip: "Rączka", targets: "Wartości docelowe", personal: "Personalizacja", set: "Zestaw i ilość", use: "Zastosowanie", review: "Podsumowanie" },
    q: {
      series: "Wybierz serię",
      cls: "Wybierz klasę precyzji",
      weightMode: "Waga",
      listed: "Waga z listy",
      customWeight: "Zgłaszana waga (g)",
      balanceShown: "Obliczony balans dla tej wagi",
      balanceRequest: "Zgłaszany balans (mm)",
      grip: "Fabryczny rozmiar rączki",
      targetsTitle: "Zgłaszane wartości docelowe",
      swingweight: "Zgłaszany swingweight (kg·cm²)",
      stiffness: "Zgłaszana sztywność (RA)",
      basis: "Podstawa pomiaru zgłaszanych wartości",
      engraving: "Treść grawera",
      engravingHint: "Imię, inicjały lub numer. Litery łacińskie, cyfry, spacja, łącznik, apostrof i kropka; do 24 znaków. Inne alfabety są przyjmowane do potwierdzenia projektu graficznego.",
      engravingType: "Personalizacja",
      types: { none: "Brak", name: "Imię zawodnika", initials: "Inicjały", number: "Numer zestawu", academy: "Identyfikacja trenera lub akademii", team: "Program drużynowy" },
      set: "Rakieta pojedyncza lub zestaw dobrany",
      use: "Przeznaczenie",
      uses: { play: "Gra własna", competition: "Zawody", coaching: "Praca trenerska", team: "Drużyna lub akademia", retail: "Ocena pod handel lub dystrybucję", other: "Inne" },
      notes: "Dodatkowe wymagania techniczne",
    },
    classes: { "P2.5": "P2.5 — skalowalny rdzeń wyczynowy", "P1.5": "P1.5 — precyzja rozszerzona", "P0.5": "P0.5 — profesjonalna, kontrolowana indywidualnie" },
    stiffExactShort: "sztywność zgodna z zadeklarowanym celem RA w ramach ustalonego protokołu fabrycznego",
    clsNote: "Każda klasa kontroluje cztery parametry. P0.5 to wąska tolerancja w ramach zdefiniowanego protokołu pomiarowego — nie zerowy błąd. Identyfikacja seryjna, certyfikaty i dokumentacja zestawów dobranych obowiązują tylko tam, gdzie program Państwa zamówienia je wdraża.",
    listedNote: "Z potwierdzonej matrycy serii.",
    customNote: "Waga poza matrycą, poddawana przeglądowi technicznemu.",
    balanceCaption: "Każda waga z listy pokazuje swój obliczony balans w mm od końca rączki. Wartości obliczone nie są pomiarami indywidualnymi.",
    spinNote: "Wagi SPIN tworzą zgłoszoną architekturę wagową. Balans, swingweight i sztywność dla SPIN nie są podane; są definiowane w przeglądzie technicznym.",
    customHint: "Pełne gramy, wyłącznie cyfry. Własna waga jest zgłoszeniem do przeglądu technicznego; wykonalność jest potwierdzana na piśmie i żadna wartość nie jest zaokrąglana.",
    gripNote: "fabryczna geometria karbonowej rączki, nie nadbudowa z owijek",
    targetsLead: "Opcjonalnie. Prosimy wpisać tylko potrzebne wartości. Każda jest zapisywana jako zgłoszona wartość docelowa do przeglądu technicznego, a nie jako opublikowana specyfikacja.",
    basisHint: "Wymagane przy zgłoszeniu własnej wagi lub dowolnej wartości docelowej: czy wartości dotyczą rakiety bez naciągu, czy z naciągiem?",
    inputRange: "Przyjmowany zakres: {min}–{max}.",
    inputRangeNote: "Zakresy wprowadzania odfiltrowują tylko niemożliwe wpisy. Nie opisują możliwości produkcyjnych.",
    listedBasis: "wartości z listy — podstawa pomiaru potwierdzana w pisemnej specyfikacji",
    notStored: "Nie jest przechowywane w tej przeglądarce; po odświeżeniu strony należy wpisać ponownie.",
    artworkReview: "wymagane potwierdzenie projektu graficznego",
    previewNote: "Podgląd wizualny nie jest pokazywany: zatwierdzony szablon grawera dla tego modelu nie jest jeszcze opublikowany. Państwa tekst jest zbierany do potwierdzenia projektu graficznego.",
    teamSub: "4–99 rakiet w zestawie",
    setsLabel: { individual: "Liczba rakiet", pair: "Liczba dobranych par", triple: "Liczba dobranych trójek", team: "Liczba zestawów drużynowych" },
    teamSizeLabel: "Rakiet w zestawie drużynowym",
    totalLabel: "Rakiet łącznie",
    racquetsUnit: "rakiet",
    setRule: "Ilość liczy zestawy: dobrana para to 2 rakiety w zestawie, dobrana trójka — 3.",
    restart: "Rozpocznij nową konfigurację",
    notices: { weightCleared: "{w} g nie występuje w matrycy serii {series}, dlatego waga została wyczyszczona. Prosimy wybrać wagę z listy lub zgłosić własną wartość docelową." },
    reviewTitle: "Zgłoszenie konfiguracji",
    reviewP: "Prosimy sprawdzić konfigurację, a następnie dodać dane kontaktowe. Zgłoszenie jest zapisywane z numerem i otrzymuje odpowiedź na piśmie; dostępność i warunki handlowe są potwierdzane na piśmie.",
    reviewErrors: "Niektóre odpowiedzi konfiguracji wymagają uwagi:",
    edit: "Edytuj",
    fieldNames: { series: "Seria", cls: "Klasa precyzji", mode: "Wybór wagi", weight: "Waga z listy", customWeight: "Zgłaszana waga", basis: "Podstawa pomiaru", balanceReq: "Zgłaszany balans", sw: "Zgłaszany swingweight", ra: "Zgłaszana sztywność", grip: "Rozmiar rączki", ptype: "Personalizacja", engraving: "Treść grawera", setType: "Rodzaj zestawu", sets: "Ilość", teamSize: "Rakiet w zestawie drużynowym", use: "Przeznaczenie", notes: "Dodatkowe wymagania" },
    status: { listed: "waga z listy", requestedArchitecture: "zgłoszona architektura wagowa", technicalReview: "zgłoszenie do przeglądu technicznego", notPublished: "nie podano", requestedCondition: "zgłoszony stan" },
    chooseLink: "Która seria będzie odpowiednia? Skorzystaj z pomocy w wyborze",
    cta: "Wyślij zgłoszenie konfiguracji",
  },
  experience: {
    title: "Testy i dobór rakiety",
    statement: "Chwyć ją. Zamachnij nią. Poczuj ją.",
    lead: "Można poprosić o testy, dobór rakiety lub prezentację z udziałem trenera. Zgłoszenia są rozpatrywane i otrzymują odpowiedź na piśmie; przekazane zgłoszenie nie jest potwierdzonym terminem spotkania.",
    optionsTitle: "O co można poprosić",
    options: ["Testy rakiet", "Sesja doboru rakiety", "Prezentacja z udziałem trenera", "Prezentacja Sweet Spot Trainer lub Spot Trainer", "Dzień testowy dla drużyny lub akademii"],
    formTitle: "Zgłoszenie doboru lub prezentacji",
  },
  engineering: {
    title: "Konstrukcja i produkcja",
    statement: "Samoloty. Jachty. Rakiety.",
    lead: "Jedna filozofia inżynierska w trzech środowiskach: zasady, które kształtują samolot, precyzja, która prowadzi jacht po otwartej wodzie, osiągi, które definiują każdą rakietę MAXIMUS. Narracja inżynierska — a nie twierdzenie o certyfikacji lotniczej, własności jachtów, własności fabryki czy bezpośrednim przeniesieniu materiałów.",
    manifesto: ["Wierzymy, że wielka inżynieria nie ma granic.", "Jedna filozofia. Konstrukcja bez kompromisów."],
    capabilityTitle: "Możliwości produkcyjne",
    capabilityLead: "Możliwości są pokazane jako sekwencja, a nie jako hasło.",
    sequence: [
      ["Specyfikacja", "Seria, klasa precyzji, waga, balans, swingweight, cel sztywności, geometria rączki, personalizacja."],
      ["Produkcja", "W pełni karbonowa konstrukcja od ramy do rączki, wykonana według specyfikacji."],
      ["Kontrola jakości", "Pomiar i zapisy zgodnie z klasą precyzji: zapisy produkcyjne, zapisy indywidualne i identyfikowalność, certyfikacja indywidualna."],
      ["Produkcja powtarzalna", "Powtarzalna reakcja wobec zadeklarowanej specyfikacji w kolejnych partiach."],
      ["Identyfikowalność", "Identyfikacja seryjna, identyfikowalność partii i Certyfikat Precyzji tam, gdzie klasa go przewiduje."],
    ],
    capacityNote: "Zdolności produkcyjne, terminy realizacji, minimalne ilości i harmonogramy dostaw są potwierdzane dla każdego programu na piśmie, wobec potwierdzonych zamówień i uzgodnionego harmonogramu zwolnień.",
    truth: "Zdolność produkcyjna nie jest wielkością produkcji, zapasem, gwarantowaną datą dostawy ani własnością zakładu produkcyjnego.",
    cta: "Dystrybucja i rozwój rynków krajowych",
    cta2: "Przekaż brief techniczny",
  },
  ecosystem: {
    title: "Ekosystem MAXIMUS",
    lead: "Jeden klucz. Oto co otwiera. Każdy węzeł ma wyjaśnienie, rzetelny status i właściwe następne działanie.",
    words: ["Inżynieria", "Osiągi", "Innowacja", "Społeczność", "Możliwości", "Cel"],
    nodes: {
      engineering: { h: "Konstrukcja i produkcja rakiet", p: "W pełni karbonowe rakiety konstruowane zgodnie ze specyfikacją, produkowane z zapisami jakości i identyfikowalnością.", a: "Konstrukcja i produkcja" },
      precision: { h: "Precyzja i konfiguracja indywidualna", p: "Cztery parametry, trzy klasy precyzji, osiem rozmiarów rączki i konstrukcje na zamówienie.", a: "Precyzja i sztywność ramy" },
      training: { h: "Trening i metodyka", p: "Sweet Spot Trainer, Spot Trainer i uporządkowana droga rozwoju.", a: "Systemy treningowe" },
      development: { h: "Rozwój zawodnika i trenera", p: "Wybór sprzętu z udziałem trenera, zapisy, ponowna ocena i ścieżki edukacyjne.", a: "Metodyka" },
      identity: { h: "Tożsamość osobista i marki osobiste", p: "Od grawera do marki osobistej lub zawodowej objętej prawami.", a: "Marki osobiste" },
      owners: { h: "Zapisy właścicieli, wiedza i prawa", p: "Proponowane archiwum właściciela z kontrolą dostępu do zapisów o sprzęcie, rozwoju i prawach.", a: "Właściciele i archiwum" },
      mipa: { h: "MIPA — pochodzenie i kontrola wewnętrzna", p: "Wewnętrzna warstwa kontroli własności intelektualnej, pochodzenia i dokumentów.", a: "Tożsamość prawna i kontrola" },
      digital: { h: "Infrastruktura cyfrowa i kierunek Blockchain 5.0", p: "Pochodzenie, zapisy z identyfikowalnością, dowody z kontrolą dostępu i tożsamość produktu jako zadeklarowany kierunek technologiczny.", a: "Kierunek technologiczny" },
      licensing: { h: "Umowne programy licencyjne i tantiemowe", p: "Licencjonowane marki, produkty i pakiety praw z warunkami określanymi w każdej umowie.", a: "Ścieżki licencyjne" },
      families: { h: "Udział rodziny i korzyści programowe", p: "Świadome decyzje, ciągłość, zachowane zapisy i korzyści określone przez program.", a: "Rodziny i rodzice" },
      network: { h: "MAXIMUS Sports Network", p: "Zawodnicy, trenerzy, kluby, akademie, usługodawcy, operatorzy i partnerzy regionalni.", a: "Sports Network" },
      market: { h: "Kluby, akademie, dystrybucja i rozwój rynków krajowych", p: "Programy drużynowe, handel detaliczny, dystrybucja i rozwój terytorium na podstawie pisemnej kwalifikacji.", a: "Formy współpracy" },
      institutional: { h: "Programy instytucjonalne, edukacja, innowacje i wpływ społeczny", p: "Warstwa instytucjonalna zapewniana przez MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, gdzie program ustanawia tę rolę.", a: "Programy instytucjonalne" },
      extensions: { h: "Przyszłe rozszerzenia na sporty rakietowe i odzież MAXIMUS", p: "Padel, pickleball, squash, badminton, racquetball, tenis plażowy i odzież jako kierunki rozwoju.", a: "Sporty rakietowe" },
    },
    boundaryTitle: "Granice",
    boundary: [
      "Zakup rakiety nie tworzy członkostwa instytucjonalnego, praw do zarządzania, tantiem ani praw inwestycyjnych.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) jest operatorem instytucjonalnym tylko tam, gdzie program ustanawia tę rolę; sprzedaż sprzętu wskazuje faktyczny podmiot będący stroną umowy.",
      "Dotacje, status organizacji dobroczynnej, traktowanie podatkowe i zezwolenia regulacyjne nie obowiązują automatycznie we wszystkich krajach.",
    ],
    techTitle: "Kierunek technologiczny",
    techP: "Blockchain 5.0 jest zadeklarowanym kierunkiem technologicznym MAXIMUS. Jego funkcje to pochodzenie, zapisy z identyfikowalnością, dowody z kontrolą dostępu, tożsamość produktu i rozliczanie kwalifikujących się zdarzeń handlowych. Nie przedstawia się żadnego mechanizmu konsensusu, przepustowości transakcji, sieci węzłów, adresu smart kontraktu, tokena ani niezależnej certyfikacji i nie twierdzi się, że działa jakiekolwiek wdrożenie. Dane osobowe, zapisy dotyczące dzieci i poufne umowy nigdy nie są domyślnie umieszczane w publicznym, niezmiennym systemie.",
  },
  brands: {
    title: "Marki osobiste i ambasadorzy",
    statement: "Od zawodnika do marki. Od trenera do marki.",
    lead: "Osobna ścieżka marki osobistej. Udział MAXIMUS obejmuje rozwój marki i uzgodnioną promocję — a nie tylko nazwisko na rakiecie.",
    progressionTitle: "Zakładana progresja",
    progression: [
      ["Zweryfikowana tożsamość", "Zweryfikowana tożsamość i historia rozwoju."],
      ["Wyrazista marka", "Wyrazista marka osobista lub zawodowa."],
      ["Treści z uregulowanymi prawami", "Treści z uregulowanymi prawami i zatwierdzona tożsamość produktu."],
      ["Konstrukcja i kolekcje", "Prace konstrukcyjne i rozwój kolekcji, jeśli zostaną uzgodnione."],
      ["Promocja", "Promocja przez uzgodnione kanały i partnerstwa MAXIMUS."],
      ["Udział", "Umowny udział w kwalifikujących się sprzedażach lub licencjach."],
      ["Raportowanie", "Przejrzyste raportowanie na warunkach umowy."],
    ],
    royaltiesTitle: "Tantiemy i licencjonowanie",
    royalties: [
      "Tantiemy dotyczą zdefiniowanej licencjonowanej marki, produktu, transakcji lub pakietu praw.",
      "„Sprzedaż na całym świecie” oznacza kwalifikujące się sprzedaże w zakresie umowy — nigdy każdą niepowiązaną rakietę MAXIMUS.",
      "Stawki, podstawa wyliczenia, terytoria, okres, zwroty, potrącenia, raportowanie, rozliczenie i weryfikacja są określane w odpowiedniej umowie. Nie publikuje się domyślnej stawki tantiem.",
      "Bez uzgodnionego zakresu nie obiecuje się globalnej kampanii, budżetu medialnego, efektu sponsoringu ani sukcesu handlowego.",
    ],
    cta: "Wyślij zapytanie o współpracę markową",
    cta2: "Zapytanie o współpracę trenerską",
  },
  families: {
    title: "Rodziny i rodzice",
    lead: "Świadome decyzje o sprzęcie, ciągłość rozwoju, zachowana wiedza i prawa, widoczność udziału oraz korzyści określone przez program, które mogą wspierać przyszłą aktywność.",
    nowTitle: "Dostępne teraz",
    now: ["Zapytania rodzinne i rozwojowe na piśmie.", "Wybór sprzętu z udziałem trenera, zgłoszenia doboru rakiety i prezentacji.", "Zapisy prywatne: profile dzieci nigdy nie są publikowane ani domyślnie komercjalizowane.", "Ścieżka edukacyjna dla rodziców: konfiguracja, obciążenie, progresja, zapisy i prawa."],
    plannedTitle: "Planowane",
    planned: ["Korzyści z udziału określone przez program, wykorzystywane na towary i usługi w ekosystemie, a nie oprocentowanie gotówkowe.", "Zapisy właściciela i rodziny w proponowanym archiwum właściciela, z uprawnieniami opiekuna i przejęciem kontroli w wieku 18 lat."],
    categoriesTitle: "Rozdzielane kategorie",
    categories: ["Tantiemy umowne wynikające z licencjonowanych praw lub kwalifikujących się sprzedaży", "Korzyści z udziału określone przez program", "Kredyty na zakupy lub usługi", "Przedpłaty", "Członkostwo instytucjonalne"],
    categoriesP: "Te kategorie nigdy nie są traktowane jako wymienne.",
    statusTitle: "Faktyczny status programu rodzinnego",
    journeyTitle: "Ścieżka rodzinna",
    journey: [
      ["Cel", "Co zawodnik chce osiągnąć w następnym kroku."],
      ["Obecny poziom", "Gdzie zawodnik jest dzisiaj."],
      ["Trener", "Czy trener uczestniczy w decyzjach o sprzęcie."],
      ["Sprzęt", "Sprzęt odpowiedni do etapu, w tym systemy treningowe, jeśli są potrzebne."],
      ["Uzgodniona praca", "Korzystanie pod okiem trenera, uzgodnione z wyprzedzeniem."],
      ["Przegląd", "Ponowna ocena w porównywalnych punktach kontrolnych."],
    ],
    brief: {
      who: "Rodzice i opiekunowie zawodników na każdym etapie.",
      value: "Pisemna odpowiedź o odpowiednim sprzęcie, udziale trenera i następnym kroku rozwoju.",
      now: "Zapytania rodzinne na piśmie; wybór z udziałem trenera; zapisy prywatne — profile dzieci nigdy nie są publikowane.",
      next: "Prosimy wysłać poniższe zapytanie rodzinne. Numer zgłoszenia pojawi się natychmiast.",
    },
    formTitle: "Zapytanie rodzinne",
    formNote: "Do wypełnienia przez rodzica lub opiekuna. Prosimy nie podawać imienia dziecka, daty urodzenia, szkoły ani informacji medycznych.",
    noPromise: "Zakup nie obiecuje tantiem, zwrotów z inwestycji, sponsoringu ani finansowania rozwoju dziecka.",
    statusP: "Ta wersja wyjaśnia model i przyjmuje zapytania programowe. Naliczanie, wypłaty i realizacja nie są dostępne, dopóki kwalifikujące się zdarzenia, beneficjenci, źródło finansowania, podstawa wyliczenia, dopuszczalne zastosowania, ujęcie księgowe, zwroty, korekty, wygaśnięcie, przenoszalność, zamknięcie programu i rozstrzyganie sporów nie zostaną określone na piśmie. Nie obiecuje się salda, które nigdy nie spada, żaden udział nie opłaca całego treningu i nie sugeruje się ochrony kapitału.",
    cta: "Wyślij zapytanie rodzinne lub rozwojowe",
  },
  owners: {
    title: "Właściciele i archiwum właściciela",
    lead: "Archiwum właściciela to proponowany zapis z kontrolą dostępu, obejmujący sprzęt, rozwój, wiedzę, treści i udokumentowane prawa. Jest przedstawiane jako część planowanej architektury właściciela: nie pokazuje się działających kont, sald, certyfikatów ani osiągnięć.",
    nowTitle: "Dla obecnych właścicieli już teraz",
    now: ["Zapytania właścicieli: odniesienie do produktu lub numeru seryjnego, ustawienia, serwis i zgłoszenia dotyczące zapisów — na piśmie.", "Certyfikat Precyzji i dokumentacja zestawu dobranego tam, gdzie klasa precyzji je przewiduje, dostarczane wraz z produktem."],
    archTitle: "Planowana architektura archiwum",
    arch: ["Tożsamość produktu i numery seryjne", "Konfiguracja i obowiązujące certyfikaty kontroli jakości", "Historia serwisu i ustawień", "Zapisy rozwoju zawodnika lub trenera", "Kwalifikacje i zweryfikowane osiągnięcia", "Materiały medialne z uregulowanymi prawami i materiały autorskie", "Licencje, zezwolenia i odniesienia do umów", "Zapisy programu marki osobistej", "Obowiązujące zestawienia tantiem lub korzyści z udziału"],
    separationTitle: "Co oznacza własność",
    separation: [
      "Własność fizycznej rakiety jest odrębna od własności praw autorskich, licencji, uprawnienia umownego lub zapisu opisującego te rzeczy.",
      "Przechowywany dokument lub wpis w blockchainie nie jest automatycznie dowodem, że prawo istnieje lub zostało przeniesione.",
      "Dowody zachowują swoją klasyfikację: zadeklarowane przez uczestnika, potwierdzone przez opiekuna, zwalidowane przez trenera, zmierzone przez system.",
      "W przypadku osób niepełnoletnich: zapisy prywatne, uprawnienia opiekuna, brak publikowanych profili dzieci i brak domyślnej komercjalizacji tożsamości.",
      "Eksport, korekta, kontrola dostępu i właściwe przejęcie kontroli są częścią projektu.",
    ],
    techTitle: "Blockchain 5.0 i MxSN",
    techP: "Blockchain 5.0 jest zadeklarowanym kierunkiem technologicznym; MxSN definiuje koncepcje sieci z kontrolą dostępu dla zgody, dostarczania, dowodów, praw i raportowania. Nie przedstawia się wdrożenia operacyjnego. Model danych aplikacji jest zbudowany tak, aby zintegrować się później przez udokumentowany interfejs, bez udawania, że połączenie istnieje już dziś.",
    cta: "Zapytanie właściciela",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Połączenie między zawodnikami, trenerami, klubami, akademiami, usługodawcami, operatorami programów i partnerami regionalnymi.",
    functionsTitle: "Możliwe funkcje",
    functions: ["Wyszukiwanie", "Kojarzenie kontaktów", "Programy rozwojowe", "Wsparcie sprzętowe", "Wydarzenia", "Dostęp do usług", "Możliwości partnerskie"],
    statusTitle: "Faktyczny status",
    statusP: "Publiczny katalog nie jest jeszcze publikowany: wymienieni będą tylko uczestnicy, których tożsamość, relacja i zgoda na publikację są ustalone. Propozycja przesłana do klubu nie jest partnerstwem, a potencjalny dystrybutor nie jest dystrybutorem wyznaczonym. Publikacja katalogu, rezerwacje, komunikator i transakcje handlowe są kontrolowane odrębnie i nie działają.",
    cta: "Zgłoś się do sieci",
  },
  partnerships: {
    title: "Formy współpracy",
    lead: "Najpierw pisemna kwalifikacja. Każda ścieżka prowadzi do zapytania właściwego dla roli; warunki handlowe następują na piśmie.",
    commercialTitle: "Możliwe działania handlowe platformy",
    commercial: ["Sprzęt", "Konstrukcje na zamówienie", "Personalizacja", "Programy drużynowe i akademickie", "Systemy treningowe", "Licencjonowanie umowne", "Dystrybucja", "Zatwierdzone usługi", "Przyszłe kategorie produktów"],
    boundary: "Prawa krajowe, wyłączność, opłaty terytorialne i marże dystrybutora są warunkami negocjowanymi. Nie publikuje się przychodów, prognoz, wycen, udziałów w rynku, zwrotów, zobowiązań finansowania ani niewymienionych partnerstw.",
    routes: {
      coaches: {
        title: "Trenerzy",
        lead: "Systemy treningowe, dobór rakiet, tożsamość zawodowa, autoryzowane programy, możliwości marki osobistej i dostawy sprzętu.",
        points: ["Sweet Spot Trainer i Spot Trainer w treningu prowadzonym przez trenera.", "Dobór rakiety z użyciem matryc konfiguracji i ośmiu fabrycznych rozmiarów rączki.", "Coach-to-Brand: zweryfikowany profil zawodowy i submarka objęta prawami.", "Autoryzowane korzystanie z programów wynika z pisemnej umowy."],
        cta: "Wyślij zapytanie o współpracę trenerską",
        brief: {
          who: "Niezależni trenerzy i zespoły trenerskie.",
          value: "Systemy treningowe do pracy prowadzonej przez trenera, dobór rakiet z matrycami serii i ośmioma fabrycznymi rozmiarami rączki oraz droga do tożsamości zawodowej.",
          now: "Zapytania trenerskie na piśmie. Nie publikuje się ani nie sugeruje żadnej prowizji, zarobków czy stawki za polecenie.",
          next: "Prosimy wysłać poniższe zapytanie trenerskie. Warunki następują na piśmie.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Kluby i akademie",
        lead: "Sprzęt drużynowy, systemy treningowe, personalizacja, programy rozwojowe, serwis i udział w sieci.",
        points: ["Zestawy drużynowe i dobrane zgłaszane przez konfigurator.", "Systemy treningowe i metodyka do uporządkowanego rozwoju.", "Personalizacja programów drużynowych w zatwierdzonych strefach.", "Dni testowe, sesje doboru rakiet i udział w sieci."],
        cta: "Wyślij brief klubu lub akademii",
        brief: {
          who: "Kluby, akademie i programy drużynowe.",
          value: "Zestawy drużynowe i dobrane, systemy treningowe, personalizacja programów drużynowych i dni prezentacji.",
          now: "Briefy klubów i akademii na piśmie; zestawy drużynowe zgłasza się przez konfigurator.",
          next: "Prosimy wysłać poniższy brief klubu lub akademii.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Dystrybucja i rozwój rynków krajowych",
        lead: "Asortyment, koordynacja produkcji, możliwości techniczne, rozwój terytorium i poufna kwalifikacja handlowa.",
        points: ["Pisemna kwalifikacja kontrahenta, terytorium i kanału.", "Asortyment definiowany na podstawie matryc konfiguracji i klas precyzji.", "Terytorium, wyłączność, wolumeny, ceny i ochrona handlowa są warunkami negocjowanymi i uzgadnianymi na piśmie.", "Podmiot będący stroną umowy, warunki płatności i baza dostawy są wskazywane dla każdej transakcji."],
        cta: "Wyślij zapytanie o dystrybucję lub rozwój rynku",
        brief: {
          who: "Sklepy, dystrybutorzy i partnerzy krajowi.",
          value: "Asortyment zdefiniowany na podstawie potwierdzonych matryc, klas precyzji i zakresu rozmiarów rączki, z pisemną kwalifikacją terytorium i kanału.",
          now: "Zapytania dystrybucyjne na piśmie. Terytorium, wyłączność, wolumeny i ceny są negocjowane — formularz nie przyznaje żadnego z nich.",
          next: "Prosimy wysłać poniższe zapytanie dystrybucyjne.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategia i inwestycje",
        lead: "Możliwości konstrukcyjne, głębokość konfiguracji, model produkcji, ścieżki wejścia na rynek, własność intelektualna, usługi i możliwości rozwoju.",
        points: ["Kwalifikowana rozmowa strategiczna lub kontrolowany dostęp do informacji następuje po pisemnej kwalifikacji.", "Informacje publiczne ograniczają się do zatwierdzonych specyfikacji produktów, architektury konfiguracji, zweryfikowanych możliwości i wyjaśnień programów.", "Ekonomika właściwa dla kupującego, kalkulacja kosztów, chroniona metodyka i nieopublikowane umowy są ujawniane wyłącznie na podstawie NDA lub umowy."],
        cta: "Poproś o kwalifikowaną rozmowę strategiczną",
        brief: {
          who: "Inwestorzy i partnerzy strategiczni.",
          value: "Kwalifikowana rozmowa o możliwościach konstrukcyjnych, głębokości konfiguracji, modelu produkcji, ścieżkach wejścia na rynek i własności intelektualnej.",
          now: "Nie publikuje się danych finansowych, prognoz, wycen ani zwrotów. Informacje kontrolowane następują po pisemnej kwalifikacji i podpisaniu NDA.",
          next: "Prosimy przesłać poniżej wniosek o kwalifikowaną rozmowę strategiczną.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Programy instytucjonalne",
        lead: "Edukacja, dostęp, innowacje, dowody rozwoju, wpływ społeczny i odpowiednio ustrukturyzowane programy.",
        points: ["Programy instytucjonalne są strukturyzowane przez MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, gdzie program ustanawia tę rolę.", "Środki programowe o ograniczonym przeznaczeniu i transakcje handlowe pozostają rozdzielone.", "Zapytanie nie jest przyjętym wnioskiem o członkostwo, a nabywca sprzętu nie jest członkiem instytucjonalnym.", "Dotacje, status organizacji dobroczynnej, traktowanie podatkowe i zezwolenia regulacyjne zależą od kraju i nigdy nie są zakładane."],
        cta: "Wyślij zapytanie o program instytucjonalny",
        brief: {
          who: "Instytucje oraz programy edukacyjne i rozwojowe.",
          value: "Programy edukacji, dostępu, innowacji i dowodów rozwoju, ustrukturyzowane z właściwym operatorem.",
          now: "Zapytania instytucjonalne na piśmie. Zapytanie nie jest wnioskiem o członkostwo; zakup sprzętu nie jest członkostwem instytucjonalnym.",
          next: "Prosimy wysłać poniższe zapytanie instytucjonalne.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Ujawnianie publiczne i kontrolowane",
    disclosure: {
      public: { h: "Publiczne", p: "Zatwierdzone specyfikacje produktów, konstrukcja, architektura konfiguracji, cele treningowe, zweryfikowane możliwości, wyjaśnienia programów i formy współpracy." },
      qualified: { h: "Zapytanie kwalifikowane", p: "Wymagania techniczne, ilości, zainteresowanie terytorium, zakres rozwoju i odpowiednie rozmowy handlowe." },
      controlled: { h: "Kontrolowane przez NDA lub umowę", p: "Wewnętrzne receptury, szczegółowe protokoły kontroli jakości, układy laminatu, oprzyrządowanie, metody produkcji, dane dostawców, kalkulacja kosztów, ekonomika właściwa dla kupującego, chroniona metodyka, nieopublikowane umowy i wrażliwe zapisy praw." },
    },
  },
  contact: {
    title: "Kontakt i zgłoszenia",
    lead: "Prosimy wybrać cel zgłoszenia. Każdy formularz zbiera tylko to, co jest potrzebne do skierowania i oceny. Zgłoszenia otrzymują odpowiedź na piśmie.",
    email: "E-mail",
    instagram: "Instagram",
    legalLink: "Tożsamość prawna",
  },
  form: {
    purposeLabel: "Cel zgłoszenia",
    purposes: {
      selection: "Pomoc w wyborze rakiety",
      product: "Zapytanie o produkt",
      fitting: "Dobór rakiety lub prezentacja",
      technical: "Brief techniczny",
      config: "Zgłoszenie konfiguracji",
      gps: "Profil sprzętowy GPS",
      coach: "Współpraca trenerska",
      club: "Brief klubu lub akademii",
      distribution: "Dystrybucja lub rozwój rynku",
      brand: "Współpraca markowa lub ambasador",
      family: "Zapytanie rodzinne lub rozwojowe",
      institutional: "Program instytucjonalny",
      strategic: "Rozmowa strategiczna lub inwestycyjna",
      owner: "Zapytanie właściciela",
      network: "Zgłoszenie do Sports Network",
      general: "Zapytanie ogólne",
    },
    fields: {
      name: "Imię i nazwisko",
      email: "E-mail",
      role: "Państwa rola",
      country: "Kraj lub region",
      organisation: "Organizacja",
      message: "Państwa wiadomość",
      level: "Obecny poziom",
      objectives: "Co jest najważniejsze (do trzech)",
      currentRacquet: "Obecna rakieta",
      grip: "Rozmiar rączki, jeśli znany",
      seriesInterest: "Interesująca seria",
      quantity: "Ilość",
      city: "Miasto lub miejsce sesji",
      coachInvolved: "Czy uczestniczy trener?",
      timing: "Preferowany termin",
      targets: "Preferowane wartości docelowe",
      limits: "Obowiązkowe ograniczenia",
      use: "Przeznaczenie",
      tradeoffs: "Akceptowalne kompromisy",
      basis: "Podstawa pomiaru",
      players: "Liczba zawodników",
      interests: "Obszary zainteresowania",
      territory: "Terytorium zainteresowania",
      channels: "Istniejące kanały i doświadczenie",
      audience: "Odbiorcy lub dyscyplina",
      proposal: "Proponowana współpraca",
      goal: "Cel rozwojowy",
      ageBand: "Grupa wiekowa zawodnika",
      scope: "Zakres programu",
      interestArea: "Obszar zainteresowania",
      productRef: "Produkt lub numer seryjny",
      requestType: "Rodzaj zgłoszenia",
      seeking: "Czego Państwo szukają",
      consent: "Zgadzam się na przechowywanie i wykorzystanie tych danych przez MAXIMUS w celu odpowiedzi na to zgłoszenie. Nie jest to zapis na newsletter.",
    },
    roles: { player: "Zawodnik", parent: "Rodzic lub opiekun", coach: "Trener", club: "Klub lub akademia", retailer: "Sklep", distributor: "Dystrybutor", brand: "Marka lub ambasador", investor: "Inwestor lub partner strategiczny", institution: "Instytucja", other: "Inne" },
    interestOptions: { training: "Systemy treningowe", fitting: "Dobór rakiety", identity: "Tożsamość zawodowa", programmes: "Autoryzowane programy", brand: "Marka osobista", supply: "Dostawy sprzętu", team: "Sprzęt drużynowy", personalisation: "Personalizacja", development: "Programy rozwojowe", service: "Serwis", network: "Udział w sieci" },
    ownerTypes: { setup: "Ustawienia i konfiguracja", service: "Serwis", records: "Zapisy i certyfikaty", other: "Inne" },
    strategicAreas: { engineering: "Możliwości konstrukcyjne", configuration: "Głębokość konfiguracji", manufacturing: "Model produkcji", routes: "Ścieżki wejścia na rynek", ip: "Własność intelektualna i usługi", expansion: "Możliwości rozwoju" },
    errors: {
      required: "To pole jest wymagane.",
      too_long: "Ten wpis jest zbyt długi.",
      too_short: "Ten wpis jest zbyt krótki.",
      invalid_email: "Prosimy podać prawidłowy adres e-mail, na przykład name@example.com.",
      invalid_choice: "Prosimy wybrać jedną z opcji.",
      not_number: "Prosimy podać liczbę całkowitą, wyłącznie cyframi.",
      out_of_range: "Ta wartość jest poza przyjmowanym zakresem.",
      not_in_matrix: "Ta waga nie występuje w matrycy wybranej serii.",
      decimal_not_supported: "Prosimy podać liczbę całkowitą, bez miejsc po przecinku.",
      too_many: "Prosimy wybrać nie więcej niż trzy opcje.",
      consent_required: "Zgoda jest potrzebna, aby MAXIMUS mógł odpowiedzieć na to zgłoszenie.",
      invalid: "Ten wpis jest nieprawidłowy.",
    },
  },
  legal: {
    title: "Tożsamość prawna i kontrola",
    lead: "Marką publiczną jest MAXIMUS / MAXIMUS GPS. Prawne tożsamości operacyjne są rozróżnialne i wskazane poniżej.",
    entities: {
      institutional: { role: "Warstwa programów instytucjonalnych", p: "Zapewnia warstwę programów instytucjonalnych tam, gdzie program ustanawia tę rolę. Nie jest handlowym sprzedawcą rakiet. Organizacja niedochodowa zarejestrowana w Dubai International Financial Centre." },
      equipment: { role: "Podmiot handlowy dla sprzętu", p: "Podmiot handlowy dla sprzętu — dostaw, dystrybucji i realizacji handlowej na podstawie umowy — tam, gdzie obecne dokumenty operacyjne ustanawiają tę rolę. Strona umowy dla danej transakcji jest wskazana w dokumentach tej transakcji." },
      ip: { role: "Własność intelektualna, marka i koordynacja handlowa", p: "Występuje w ustalonej roli dotyczącej własności intelektualnej, marki lub koordynacji handlowej. Nie przypisuje się żadnej niepotwierdzonej odpowiedzialności umownej." },
      stewardship: { role: "Odniesienie nadzorcze", p: "House of Maximus jest odniesieniem nadzorczym dla ekosystemu tam, gdzie potwierdza to odpowiednie źródło." },
      control: { role: "Wewnętrzna kontrola własności intelektualnej, pochodzenia i dokumentów", p: "MIPA jest wewnętrzną warstwą kontroli własności intelektualnej, pochodzenia i dokumentów. Wewnętrzny wpis MIPA różni się od zewnętrznej rejestracji znaku towarowego, patentu lub prawa autorskiego oraz od uznania sądowego i nie stanowi zatwierdzenia wizualnego." },
    },
    labels: { licence: "Licencja", registration: "Rejestracja", vat: "VAT TRN", address: "Adres", email: "E-mail", jurisdiction: "Jurysdykcja" },
    boundaryTitle: "Granice",
    boundary: [
      "Zakup nie przyznaje automatycznie członkostwa instytucjonalnego, praw do zarządzania, tantiem ani praw inwestycyjnych.",
      "Rola instytucjonalna jest odrębna od handlowych transakcji sprzętowych.",
      "Prywatność, warunki programów i ustalenia dotyczące dostępu kontrolowanego odpowiadają funkcjom faktycznie udostępnionym.",
      "Żadne ogólne stwierdzenie o prawie właściwym nie dotyczy każdego odwiedzającego, każdej sprzedaży ani każdego programu zagranicznego; podstawa umowna jest ustalana w każdej umowie.",
    ],
  },
  privacy: {
    title: "Prywatność",
    updated: "Wersja 2026-09-21 · strona 4.2",
    contactTitle: "Kontakt w sprawach prywatności",
    sections: {
      collect: ["Co jest zbierane", "Przy wysłaniu formularza: wpisane dane (imię i nazwisko, e-mail, rola, kraj lub region, organizacja, jeśli podana, wiadomość i odpowiedzi w formularzu), parametry strony i kampanii dla tej wizyty (strona wejścia, język, parametry utm; identyfikatory kliknięć reklamowych tylko przy zgodzie na analitykę) oraz czas wysłania. Adres IP jest używany wyłącznie w formie zahaszowanej i krótkotrwałej, aby ograniczyć nadużycia, i nie jest przechowywany razem ze zgłoszeniem."],
      purpose: ["Dlaczego", "Aby odpowiedzieć na zgłoszenie, przygotować zamówioną ofertę lub specyfikację i zachować zapis zgłoszenia. Na podstawie formularza nie są wysyłane wiadomości marketingowe."],
      storageOn: ["Gdzie przechowywane są zgłoszenia", "Zgłoszenia są przechowywane w bazie danych Upstash, Inc. (Redis), udostępnianej przez platformę hostingową Vercel Inc."],
      notifyEmail: ["Powiadomienie o nowym zgłoszeniu", "Po przyjęciu zgłoszenia powiadomienie zawierające przesłane dane jest wysyłane e-mailem na odpowiedzialną skrzynkę MAXIMUS."],
      notifyTelegram: ["Powiadomienie o nowym zgłoszeniu", "Po przyjęciu zgłoszenia powiadomienie zawierające przesłane dane jest wysyłane do osoby odpowiedzialnej w MAXIMUS przez Telegram (Telegram FZ-LLC, Dubaj), który w związku z tym przetwarza to powiadomienie w tranzycie."],
      notifyWebhook: ["Powiadomienie o nowym zgłoszeniu", "Po przyjęciu zgłoszenia powiadomienie zawierające przesłane dane jest wysyłane do wewnętrznego punktu końcowego MAXIMUS przez podpisane, szyfrowane połączenie."],
      notifyNone: ["Powiadomienie o nowym zgłoszeniu", "Powiadamianie o nowych zgłoszeniach jest w trakcie konfiguracji. Zgłoszenie jest przechowywane i odczytywane przez MAXIMUS z wewnętrznego rejestru; w tym celu nic nie jest przesyłane do podmiotu trzeciego."],
      storageOff: ["Gdzie przechowywane są zgłoszenia", "Przechowywanie zgłoszeń jest w trakcie konfiguracji. Do jego uruchomienia formularze informują, że zgłoszenie nie może zostać przyjęte; nic nie jest przechowywane. Stronę hostuje Vercel Inc."],
      browser: ["Pamięć przeglądarki", "Pamięć sesji zachowuje odpowiedzi wybrane z listy w GPS i w konfiguratorze oraz parametry kampanii dla tej wizyty na czas tej sesji przeglądarki. Dane kontaktowe, tekst swobodny, treść grawera i informacje o dzieciach nie są przechowywane w przeglądarce."],
      analyticsOn: ["Analityka", "Za Państwa zgodą Google Analytics 4 mierzy wizyty i zdarzenia formularzy bez danych kontaktowych i bez treści zgłoszeń. Państwa wybór jest zapisywany w pamięci lokalnej i można go zmienić w każdej chwili w „Ustawieniach analityki” w stopce. Formularze działają bez analityki."],
      analyticsOff: ["Analityka", "Na tej stronie nie działa żadne narzędzie analityczne."],
      retention: ["Przechowywanie", "Nie skonfigurowano jeszcze automatycznego okresu usuwania. W każdej chwili można poprosić o usunięcie zgłoszenia."],
      children: ["Dzieci", "Formularze wypełnia osoba dorosła. Zgłoszenia dotyczące zawodników poniżej 18 lat składa rodzic lub opiekun. Prosimy nie podawać imienia dziecka, daty urodzenia, szkoły ani informacji medycznych. Profile dzieci nigdy nie są publikowane."],
      rights: ["Państwa prawa", "Aby uzyskać dostęp do zgłoszenia, poprawić je lub usunąć, prosimy napisać na gps@maximus.tennis, podając numer zgłoszenia."],
      controlled: ["Informacje kontrolowane", "Dokumenty poufne nie są przechowywane na tej stronie ani przez nią udostępniane. Ujawnianie kontrolowane odbywa się na podstawie NDA lub umowy, przez odrębne kanały."],
    },
  },
  terms: {
    title: "Warunki korzystania",
    copyright: "Właścicielem praw autorskich do tej strony — jej tekstów, fotografii, projektu graficznego i kodu — jest wyłącznie Maximus Kiriyakulov. Prawa te nie zostały przeniesione ani na żadną spółkę, ani na żadną inną osobę.",
    updated: "Wersja 2026-09-21",
    sections: [
      ["Informacja, nie oferta", "Informacje o produktach na tej stronie opisują zatwierdzone specyfikacje, architekturę konfiguracji i wyjaśnienia programów. Nie są ofertą sprzedaży, cennikiem, informacją o stanach magazynowych ani zobowiązaniem dostawy. Warunki handlowe są uzgadniane odrębnie na piśmie z podmiotem wskazanym jako strona umowy w danej transakcji."],
      ["Zgłoszenia", "Zgłoszenie przesłane przez tę stronę — w tym profile GPS, zgłoszenia konfiguracji i briefy techniczne — jest zapisywane z numerem i poddawane przeglądowi. Nie jest przyjętym zamówieniem, zobowiązaniem produkcyjnym, potwierdzonym terminem spotkania, wnioskiem o członkostwo ani przyjętym wnioskiem do jakiegokolwiek programu."],
      ["Specyfikacje i dowody", "Wartości obliczone, cele produkcyjne i potwierdzone specyfikacje są rozróżniane na odpowiednich stronach. Wartości sztywności są celami produkcyjnymi, dopóki nie zostanie opublikowane inaczej. Nie gwarantuje się wyniku konkretnemu zawodnikowi."],
      ["Ekosystem, członkostwo i prawa", "Zakup rakiety nie tworzy członkostwa instytucjonalnego, praw inwestycyjnych, własności praw intelektualnych, uprawnienia do tantiem ani korzyści z udziału. Uprawnienia wynikają z opublikowanych warunków programu lub z pisemnej umowy."],
      ["Własność intelektualna", "MAXIMUS®, emblemat lwa, znak GPS i treść tej strony są chronione. Wewnętrzne receptury konstrukcyjne, protokoły kontroli jakości, układy laminatu, oprzyrządowanie, dane dostawców, kalkulacja kosztów i chroniona metodyka nie są tu ujawniane."],
    ],
  },
  lead: {
    submit: "Wyślij zgłoszenie",
    submitting: "Wysyłanie…",
    retry: "Spróbuj ponownie",
    acceptedEyebrow: "Zgłoszenie przyjęte",
    acceptedTitle: "Zgłoszenie zostało odebrane.",
    requestId: "Numer zgłoszenia",
    acceptedNext: "MAXIMUS rozpatruje każde zgłoszenie i odpowiada na piśmie na podany adres e-mail. Prosimy zachować numer zgłoszenia na potrzeby dalszej korespondencji.",
    duplicate: "To zgłoszenie zostało już wcześniej odebrane; duplikat nie został utworzony.",
    another: "Rozpocznij nowe zgłoszenie",
    errorsTitle: "Prosimy sprawdzić te pola:",
    failTitle: "Zgłoszenie nie zostało wysłane.",
    fail: {
      offline: "Urządzenie jest offline.",
      network: "Połączenie z serwerem nie powiodło się.",
      timeout: "Serwer nie odpowiedział w wymaganym czasie.",
      rate_limited: "Z tej sieci nadeszło zbyt wiele zgłoszeń. Prosimy spróbować ponownie za kilka minut.",
      too_fast: "Formularz został wysłany bardzo szybko. Prosimy go sprawdzić i wysłać ponownie.",
      spam_suspected: "Zgłoszenie zostało zatrzymane przez filtr antyspamowy.",
      unavailable: "W tej chwili nie można przyjmować zgłoszeń.",
      default: "Wystąpił nieoczekiwany błąd.",
    },
    keepNote: "Wpisane dane pozostają na tej stronie, więc można spróbować ponownie.",
    sendByEmail: "Wyślij to zgłoszenie e-mailem",
    sendByEmailNote: "Program pocztowy otworzy się z treścią tego zgłoszenia. MAXIMUS otrzyma je po wysłaniu wiadomości.",
    mailConfig: "Konfiguracja",
    mailPage: "Strona",
    fallback: "Jeśli problem się powtarza, prosimy napisać na {email}. Zgłoszenie uznaje się za wysłane tylko wtedy, gdy pojawi się numer zgłoszenia.",
    privacyLink: "Informacja o prywatności",
    hpLabel: "To pole prosimy pozostawić puste",
    consentShort: "Zgoda",
    after: "Po wysłaniu na tej stronie pojawia się numer zgłoszenia. Zgłoszenia są rozpatrywane i otrzymują odpowiedź na piśmie; zgłoszenie nie jest zamówieniem.",
    basis: { unstrung: "Bez naciągu", strung: "Z naciągiem", unknown: "Nie wiem — do ustalenia w specyfikacji" },
    hints: {
      email: "MAXIMUS odpowiada na piśmie na ten adres.",
      goal: "Na przykład: pierwsza rakieta turniejowa albo przejście z rakiety juniorskiej. Prosimy nie podawać imion, dat urodzenia ani informacji medycznych dotyczących dziecka.",
      currentRacquet: "Marka i model, jeśli są znane.",
      message: "Prosimy nie podawać haseł, danych płatniczych ani informacji medycznych.",
    },
  },
  choose: {
    eyebrow: "Pomoc w wyborze",
    title: "Pomoc w wyborze rakiety",
    lead: "Prosimy podać poziom i to, co jest najważniejsze. Odpowiedzi są analizowane, a Państwo otrzymują pisemną propozycję: seria, klasa precyzji, waga i rozmiar rączki.",
    stepsTitle: "Co dzieje się dalej",
    steps: [
      ["Państwa odpowiedzi", "Poziom, priorytety i rozmiar rączki, jeśli jest znany."],
      ["Przegląd ekspercki", "MAXIMUS porównuje odpowiedzi z matrycami serii."],
      ["Pisemna propozycja", "Proponowana konfiguracja i następny krok, na piśmie."],
    ],
    formTitle: "Państwa odpowiedzi",
    submit: "Poproś o pomoc w wyborze",
    altTitle: "Wolą Państwo zdecydować samodzielnie?",
    altGps: "Szczegółowy profil GPS",
    altBuild: "Skonfiguruj bezpośrednio",
    note: "Brak automatycznego doboru i brak twierdzeń o dokładności: każde zgłoszenie analizuje człowiek.",
  },
  consent: {
    title: "Analityka",
    text: "Czy MAXIMUS może mierzyć wizyty za pomocą Google Analytics? Formularze działają tak samo; do analityki nie są przesyłane dane kontaktowe ani treść zgłoszeń.",
    allow: "Zezwól na analitykę",
    decline: "Odrzuć",
  },
  familyPlan: {
    title: "Plan rodzinny",
    metaDescription: "Oblicz tenisowy budżet swojej rodziny: treningi, godziny, kontakty z piłką oraz koszt jednego treningu, jednej godziny i jednego uderzenia — na podstawie własnych danych, w trzech scenariuszach.",
    eyebrow: "Plan rodzinny · Wnieś wkład razem z nami",
    heroTitle: "Ile tenis kosztuje Państwa rodzinę — i co za to Państwo otrzymują?",
    heroLead: "Tutaj obliczą Państwo budżet rodziny, opłacane z niego treningi i godziny, szacowaną liczbę kontaktów z piłką oraz koszt jednego treningu, jednej godziny i jednego uderzenia — na własnych warunkach.",
    heroCta: "Oblicz swój plan rodzinny",
    strategy: {
      eyebrow: "Nasz cel",
      title: "Więcej tenisa. Więcej możliwości. Razem.",
      p1: "Naszym celem jest dziesięciokrotny wzrost światowego rynku tenisa — przez poszerzanie grona grających oraz wytyczanie jaśniejszej i bardziej dostępnej drogi do tenisa. MAXIMUS dąży do przywództwa poprzez zarządzanie, metodykę, jakość, wyniki i popularyzację gry.",
      p2: "Innych producentów sprzętu tenisowego i ich marki postrzegamy jako potencjalnych partnerów. Proponujemy połączenie mocnych stron firm, trenerów, klubów i rodzin we wspólnym programie rozwoju, promocji i upowszechniania tenisa na dużą skalę — na zasadach obopólnej korzyści.",
      p3: "MAXIMUS jest piątym elementem tego podejścia: pełni rolę spoiwa, które pomaga odrębnym siłom działać razem. Nasze wspólne wyzwania to choroby, brak ruchu wśród dzieci oraz bariery, przez które ludzie nie zaczynają grać albo rezygnują z gry.",
      p4: "Dla rodziny wszystko zaczyna się od jasnego obrazu sytuacji. Plan rodzinny pokazuje budżet, liczbę treningów i godzin, szacowaną liczbę kontaktów z piłką oraz koszt treningów. Wystarczy zmienić warunki i wybrać scenariusz, który Państwu odpowiada.",
      note: "Dziesięciokrotny wzrost to cel strategiczny, który wyznacza sobie MAXIMUS, a nie wynik już osiągnięty. Kalkulator pokazuje obliczenia scenariuszy i nie obiecuje żadnej oszczędności, żadnego efektu medycznego ani żadnego wyniku sportowego.",
      ctaCalc: "Oblicz swój plan rodzinny",
      ctaPartner: "Omów z nami wspólny rozwój tenisa",
    },
    beyond: {
      eyebrow: "Poza kortem",
      title: "Co plan buduje poza treningiem",
      admission: {
        h: "Przyjęcie do czołowych szkół i uczelni",
        p: "MAXIMUS wspiera rodzinę w drodze do czołowych szkół i uczelni na całym świecie: w budowaniu sportowego dorobku zawodnika, przygotowaniu dokumentów i wniosków rekrutacyjnych oraz wyborze programów, w których sport idzie w parze z nauką. Jeśli zostanie przyznane stypendium sportowe, zmniejsza ono kwotę, jaką rodzina płaci za edukację.",
      },
      assets: {
        h: "Aktywa cyfrowe: nazwisko, wizerunek i dorobek zawodnika",
        p: "Nazwisko, wizerunek, wyniki, treści i marka osobista zawodnika to aktywa, które z czasem mogą zyskać znaczną wartość finansową i prestiżową. MAXIMUS pomaga je tworzyć, rejestrować i chronić, aby ta wartość pozostała przy zawodniku i jego rodzinie.",
      },
      note: "Żadna z tych usług nie jest częścią kalkulatora. Wartość miejsca w szkole, stypendium czy aktywów cyfrowych zależy od konkretnego przypadku i nie jest tu szacowana.",
      cta: "Zapytaj o wsparcie w rekrutacji i aktywa cyfrowe",
    },
    steps: ["Dane rodziny", "Ekonomika treningów", "Plan długoterminowy", "Obliczenie końcowe"],
    stepsLabel: "Kroki kalkulatora",
    scenarios: { now: "Obecny", planned: "Planowany", wish: "Wymarzony" },
    scenarioHints: { now: "To, co Państwa rodzina robi dziś.", planned: "To, co zamierzają Państwo robić dalej.", wish: "To, co chcieliby Państwo robić." },
    currency: {
      label: "Waluta",
      note: "Wszystkie wpisywane kwoty są w tej walucie. Nic nie jest przeliczane.",
    },
    fields: {
      players: { label: "Grający członkowie rodziny", hint: "Liczba całkowita." },
      cost: { label: "Cena jednego treningu dla jednego zawodnika", hint: "Kwota w pełnych jednostkach waluty, z podatkami i opłatami." },
      sessions: { label: "Treningi na zawodnika w miesiącu", hint: "Liczba całkowita." },
      minutes: { label: "Długość jednego treningu w minutach", hint: "Cały czas łącznie z przerwami. Dozwolone są ułamki dziesiętne." },
      contacts: { label: "Kontakty z piłką na zawodnika podczas jednego treningu", hint: "Kontakt to zetknięcie własnej rakiety zawodnika z piłką. Jedna wymiana to nie jeden kontakt. Prosimy liczyć tak samo w każdym scenariuszu." },
    },
    presetsLabel: "Szybki wybór, minuty",
    ages: {
      title: "Czas trwania planu",
      start: "Wiek początkowy",
      end: "Wiek końcowy",
      hint: "Anonimowe założenie co do czasu trwania planu, używane wyłącznie w tabeli długoterminowej. Nie jest to data urodzenia ani zalecany wiek rozpoczęcia gry.",
    },
    extras: {
      title: "Dodatkowe koszty rodziny",
      note: "Te kwoty dotyczą całej rodziny i obowiązują we wszystkich trzech scenariuszach. Nie są mnożone przez liczbę zawodników i nie wchodzą do kosztu godziny ani kontaktu.",
      equipment: "Pierwszy sprzęt — jedna kwota na cały okres",
      clothing: "Odzież i obuwie — jedna kwota na cały okres",
      renewal: "Wymiana sprzętu — jedna kwota na cały okres, bez automatycznego powtarzania",
      court: "Kort lub klub — miesięcznie, cała rodzina",
      travel: "Wyjazdy i wydarzenia — miesięcznie, cała rodzina",
      quoteSource: "Skąd pochodzą ceny (opcjonalnie)",
      quoteDate: "Ceny na dzień (opcjonalnie)",
      quoteNote: "Wyświetlane dokładnie tak, jak zostało wpisane. MAXIMUS nie weryfikuje tych cen.",
    },
    storage: {
      save: "Zapisz plan na tym urządzeniu",
      clear: "Usuń plan z tego urządzenia",
      saved: "Plan zapisano na tym urządzeniu. Nic nie zostało nigdzie wysłane.",
      cleared: "Plan usunięto. Kalkulator wrócił do wartości początkowych.",
      restored: "Przywrócono Państwa plan zapisany na tym urządzeniu.",
      invalid: "Nie udało się odczytać planu zapisanego na tym urządzeniu, dlatego nie został zastosowany. Można rozpocząć nowe obliczenie.",
      unavailable: "Ta przeglądarka nie pozwala na zapis na urządzeniu.",
    },
    annual: {
      title: "Jeden rok — scenariusze obok siebie",
      sessions: "Osobotreningi w roku",
      cost: "Wydatki rodziny na treningi w roku",
      hours: "Osobogodziny w roku",
      length: "Długość jednego treningu",
      contacts: "Kontakty z piłką w roku",
      note: "Osobotreningi i osobogodziny sumują treningi wszystkich zawodników. Nie są to godziny wynajmu kortu ani liczba spotkań grupy: dwóch zawodników trenujących razem przez 90 minut to 2 osobotreningi i 3 osobogodziny.",
    },
    economics: {
      title: "Koszt treningu, godziny i kontaktu",
      session: "Jeden trening jednego zawodnika",
      hour: "Jedna godzina treningu jednego zawodnika",
      contact: "Jeden kontakt z piłką",
      undefinedContacts: "Nieokreślone: 0 kontaktów",
      undefinedMinutes: "Nieokreślone: 0 minut",
      below: "mniej niż {value}",
      note: "Do tych wartości wchodzi wyłącznie cena treningu. Dodatkowe koszty rodziny nie są dzielone przez liczbę kontaktów.",
      caption: "Liczba kontaktów jest obliczana na podstawie wybranej liczby treningów i założeń modelu. Rzeczywisty przebieg treningu zależy od jego formy, przerw i warunków. Koszt kontaktu jest miarą budżetową, a nie miarą jakości pracy trenera.",
    },
    longTerm: {
      title: "Długoterminowy plan wydatków",
      horizon: "Horyzont",
      activeYears: "Aktywne lata",
      years: "{n}-letni",
      note: "Liczbę aktywnych lat ogranicza różnica między wiekiem początkowym a końcowym. Ceny, częstotliwość, inflację, sezony, opuszczone treningi i kursy walut przyjmuje się jako stałe. Dodatkowe koszty nie wchodzą do tej tabeli.",
    },
    final: {
      title: "Obliczenie końcowe",
      scenario: "Scenariusz",
      months: "Okres w miesiącach",
      heading: "{scenario} · {months} mies.",
      total: "Razem za okres",
      training: "Treningi",
      extras: "Koszty dodatkowe",
      oneOff: "Pozycje jednorazowe",
      monthly: "Pozycje miesięczne × miesiące",
      sessions: "Osobotreningi w okresie",
      hours: "Osobogodziny w okresie",
      contacts: "Kontakty z piłką w okresie",
      formulaTitle: "Sposób obliczenia",
      formula: "Razem = zawodnicy × treningi w miesiącu × miesiące × cena treningu + koszty jednorazowe + miesiące × miesięczne koszty dodatkowe.",
      formulaNote: "Koszty dodatkowe podaje się dla całej rodziny. Pozycje jednorazowe są liczone raz, nawet dla okresu 0 miesięcy.",
      inputs: "Państwa dane",
    },
    units: { min: "min", h: "godz.", approx: "≈" },
    errors: {
      title: "Prosimy poprawić te pola, aby zobaczyć wynik",
      required: "Pole wymagane — prosimy wpisać liczbę; 0 jest dozwolone.",
      negative: "Wartość nie może być ujemna.",
      integer: "Tylko liczba całkowita.",
      number: "Prosimy wpisać liczbę.",
      tooLarge: "Ta liczba jest zbyt duża, aby wykonać obliczenie.",
      endBeforeStart: "Wiek końcowy nie może być niższy niż wiek początkowy.",
      tooLong: "Maksymalnie 200 znaków.",
      date: "Prosimy podać prawidłową datę.",
      currency: "Prosimy wybrać walutę.",
      scenario: "Prosimy wybrać scenariusz.",
      result: "Wynik jest zbyt duży, aby można go było wiarygodnie pokazać. Prosimy zmniejszyć wprowadzone wartości.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: pełna kompozycja — trenażer widziany z przodu i z boku, grawerowany okrągły emblemat lwa na okrągłej główce kontaktowej, grawer MAXIMUS i SPOT TRAINER wzdłuż trzonu oraz ośmiokątny kapturek ze znakiem lwa",
    greatHero: "Seria MAXIMUS GREAT, 369 g: pełna kompozycja z czerwonymi i żółtymi detalami główki, błyszczącym napisem MAXIMUS, autografem Maximus na trzonie i kapturkiem z lwem",
    spotDetail: "Dwa trenażery MAXIMUS Spot Trainer z bliska: grawerowany lew na matowej czarnej główce kontaktowej, żebrowana owijka rączki i ośmiokątne kapturki ze znakiem lwa",
    spotPair: "Dwa trenażery MAXIMUS Spot Trainer ułożone pod skosem na ciemnej powierzchni, z grawerem MAXIMUS wzdłuż jednego trzonu i SPOT TRAINER wzdłuż drugiego oraz z okrągłym emblematem lwa na każdej główce kontaktowej",
    spinVisual: "MAXIMUS SPIN: główka z naciągiem, błyszczący napis MAXIMUS, rączka i kapturek z lwem",
    powerVisual: "MAXIMUS POWER: główka z naciągiem, błyszczący napis MAXIMUS, grawer personalizacyjny, rączka i kapturek z lwem",
    greatVisual: "MAXIMUS GREAT: główka z naciągiem, błyszczący napis MAXIMUS, grawer personalizacyjny, rączka, kapturek z lwem i znak serii G na sercu rakiety",
    spinHead: "Główka i płaszczyzna naciągu MAXIMUS SPIN",
    handleLion: "Serce, rączka i kapturek MAXIMUS ze znakiem lwa",
    engraving: "Srebrny grawer personalizacyjny na trzonie",
    lettering: "Błyszczący czarny napis MAXIMUS na matowej czarnej ramie",
    variantAlt: "Seria MAXIMUS {series} — {w} g, balans {b} mm: pełna wizualizacja z paskiem specyfikacji, strefą grawera personalizacyjnego i oznaczeniem MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, system czterech rakiet",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Trzony Sweet Spot Trainer z napisem MAXIMUS",
    sstGrips: "Rączki i kapturki Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, cztery kapturki ze znakiem lwa",
    note: "Wizualizacja produktu",
  },
  notFound: { title: "Strona nie znaleziona", p: "Żądana strona nie istnieje w tym języku.", cta: "Przejdź na stronę główną" },
};

export default pl;
