/* Romanian dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const ro = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — rachete de tenis integral din carbon, proiectate conform specificației",
    defaultDescription:
      "Rachete de tenis integral din carbon, de la cadru la mâner: GREAT 97 in², POWER 98 in² și SPIN 100 in², opt mărimi de mâner din fabrică L0–L7, clase de precizie pentru greutate, balans, swingweight și rigiditate, precum și proiectare la comandă la cerere.",
  },
  common: {
    statuses: {
      current: "Actual",
      agreement: "Disponibil prin acord",
      development: "În dezvoltare",
      concept: "Stadiu de concept",
      target: "Țintă de producție",
      modelled: "Calculat",
      confirmed: "Confirmat",
      requested: "Arhitectură solicitată",
      notprovided: "Neprecizat",
    },
    brief: { who: "Pentru cine este", value: "Ce primiți", now: "Confirmat acum", next: "Pasul următor" },
    labels: {
      next: "Înainte",
      back: "Înapoi",
      edit: "Modificați răspunsurile",
      review: "Verificare",
      start: "Începeți",
      restart: "Începeți din nou",
      copy: "Copiați textul cererii",
      copied: "Copiat",
      openEmail: "Deschideți clientul de e-mail pentru a trimite cererea",
      reference: "Referința cererii",
      weight: "Greutate",
      balance: "Balans",
      swingweight: "Swingweight",
      stiffness: "Rigiditate",
      grip: "Mărimea mânerului",
      headSize: "Suprafața capului",
      series: "Serie",
      precisionClass: "Clasă de precizie",
      quantity: "Cantitate",
      notProvided: "Nepublicat încă",
      requestTarget: "Țintă solicitată",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Citiți mai mult",
      allSeries: "Toate seriile",
      points: "greutăți listate",
      optional: "opțional",
      required: "obligatoriu",
      select: "Selectați",
      yes: "Da",
      no: "Nu",
      unknown: "Nu știu",
      custom: "Țintă la cerere",
      listed: "Greutate listată",
      individual: "Rachetă individuală",
      pair: "Pereche asortată",
      triple: "Triplet asortat",
      team: "Set de echipă",
      summaryTitle: "Sinteza cererii dumneavoastră",
      nextAction: "Acțiunea următoare",
      status: "Stare",
      learn: "Aflați mai mult",
      schematic: "Schemă — nu o măsurătoare",
      photo: "Fotografie",
    },
    ecosystemStrip: "Ecosistemul MAXIMUS",
    truth: {
      noPrices: "Prețurile, cantitățile minime, termenele de livrare, garanțiile și angajamentele de livrare se confirmă în scris, pentru fiecare piață și fiecare program.",
      requestNotOrder: "O cerere este o solicitare de analiză. Nu este o comandă acceptată, un angajament de producție sau o programare confirmată.",
      noGuarantee: "Niciun echipament, nicio metodă și niciun program descris aici nu garantează un rezultat pentru un jucător anume.",
      governing: "Această pagină este publicată în mai multe limbi. Versiunea în limba engleză este versiunea de referință; traducerea este oferită pentru comoditate.",
    },
  },
  nav: {
    language: "Limbă",
    groups: { racquets: "Rachete", training: "Antrenament", ecosystem: "Ecosistem", partnerships: "Parteneriate" },
    racquets: "Seriile de rachete și comparația",
    great: "GREAT — 97 in² · Control",
    power: "POWER — 98 in² · Putere",
    spin: "SPIN — 100 in² · Efect",
    precision: "Precizie și rigiditate",
    grip: "Arhitectura mânerelor din fabrică L0–L7",
    custom: "Proiectare la comandă",
    training: "Sisteme de antrenament",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologie",
    gps: "MAXIMUS GPS",
    build: "Configurator",
    choose: "Ajutor în alegere",
    ecosystem: "Harta ecosistemului",
    engineering: "Inginerie și producție",
    experience: "Testare și fitting",
    brands: "Branduri personale și ambasadori",
    families: "Familii și părinți",
    owners: "Proprietari și arhiva proprietarului",
    network: "Sports Network",
    partnerships: "Toate formele de parteneriat",
    coaches: "Antrenori",
    clubs: "Cluburi și academii",
    distribution: "Distribuție și dezvoltare pe țări",
    strategic: "Strategie și investiții",
    institutional: "Programe instituționale",
    contact: "Contact",
    legal: "Identitate juridică",
    privacy: "Confidențialitate",
    terms: "Termeni de utilizare",
    menu: "Meniu",
    close: "Închideți",
    home: "Pagina principală",
    skip: "Săriți la conținut",
  },
  footer: {
    line: "Racheta MAXIMUS este cheia dumneavoastră către lumea MAXIMUS.",
    product: "Produs",
    ecosystem: "Ecosistem",
    company: "Organizație",
    instagram: "Instagram",
    email: "E-mail",
    analytics: "Setări de analiză",
    subscribe: {
      title: "Rămâneți cu MAXIMUS",
      line: "Serii noi, date de fitting, materiale de antrenament și programul pentru proprietari. Câteva scrisori pe an, nimic altceva.",
      label: "Adresă de e-mail",
      placeholder: "your@email.com",
      button: "Abonați-vă",
      sending: "Se trimite",
      done: "Adresa dumneavoastră este pe listă. Scriem numai atunci când avem ceva ce merită citit.",
      invalid: "Verificați adresa.",
      failed: "Adresa nu a fost înregistrată. Încercați din nou într-o clipă.",
      terms: "Prin abonare, acceptați ca MAXIMUS să vă trimită aceste noutăți și să păstreze adresa dumneavoastră în acest scop. Fiecare scrisoare include opțiunea de dezabonare.",
    },
    rights: "MAXIMUS® și emblema cu leu sunt mărci ale ecosistemului MAXIMUS. MIPA: proprietate intelectuală internă, proveniență și control documentar.",
    boundary:
      "Condițiile comerciale și contractuale se convin separat, în scris. Cumpărarea unei rachete nu creează calitatea de membru instituțional, drepturi de investiție, titlu de proprietate intelectuală sau dreptul la redevențe.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Precizia începe la impact.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer și metodologia MAXIMUS leagă antrenamentul concentrat de rachetele de performanță integral din carbon.",
    heroCta1: "Descoperiți sistemul de antrenament",
    heroCta2: "Descoperiți GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Control",
    heroMeta: [
      ["Integral din carbon", "de la cadru la mâner"],
      ["4 parametri", "greutate · balans · swingweight · rigiditate"],
      ["8 mărimi de mâner", "geometrie din fabrică L0–L7"],
      ["3 serii", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Începeți aici",
      title: "Alegeți-vă parcursul",
      items: {
        player: { h: "Jucător", p: "Găsiți o rachetă după nivel și priorități sau configurați-o direct.", a: "Găsiți-vă racheta" },
        parent: { h: "Părinte", p: "Un parcurs scris pentru obiectivele de dezvoltare, implicarea antrenorului și echipamentul potrivit.", a: "Parcursul pentru familii" },
        coach: { h: "Antrenor, club sau academie", p: "Sisteme de antrenament, fitting, seturi de echipă și personalizare.", a: "Parcursuri pentru antrenori și cluburi" },
        partner: { h: "Distribuitor sau partener", p: "Distribuție, dezvoltare pe țări, parcursuri strategice și instituționale.", a: "Forme de parteneriat" },
      },
    },
    series: {
      eyebrow: "Serii de performanță",
      title: "Trei arhitecturi de performanță. O singură platformă de inginerie.",
      lead: "Alegeți seria după direcția de joc, apoi completați configurația: clasa de precizie, greutatea, mânerul, personalizarea.",
      cta: "Comparați seriile",
      configure: "Configurați",
      open: "Vedeți seria",
      photoPending: "Fotografia nu este încă publicată",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Sistemul de precizie MAXIMUS",
      title: "Greutate. Balans. Swingweight. Rigiditate.",
      sub: "Controlate ca un singur sistem de inginerie.",
      lead: "Trei clase de precizie definesc cât de strâns este menținută fiecare rachetă finită la specificația declarată. P0.5 este o toleranță strânsă, obținută conform unui protocol de măsurare definit — nu eroare zero.",
      cta: "Precizia și rigiditatea în detaliu",
    },
    stiffness: {
      eyebrow: "Rigiditate",
      title: "Răspuns repetabil al cadrului față de o țintă declarată.",
      p: "Rigiditatea cadrului influențează răspunsul, senzația la impact și consecvența dintre rachete. MAXIMUS o tratează ca pe al patrulea parametru controlat: ținta, rezultatul măsurat, toleranța admisă și capabilitatea instrumentului se păstrează ca înregistrări separate. Beneficiul este repetabilitatea — nu un rezultat garantat pentru fiecare jucător.",
      cols: [["Răspuns", "Modul în care cadrul restituie energia la impact."], ["Senzație", "Ceea ce simte jucătorul la impact."], ["Consecvență", "Rachetele construite după aceeași specificație răspund la fel, în limitele clasei lor."]],
      schematicCaption: "Schemă: abaterea admisă în jurul unei ținte declarate de rigiditate, pentru fiecare clasă. Nu este o măsurătoare și nu sugerează nicio valoare RA.",
      bands: { p25: "toleranța țintei ±1 RA", p15: "toleranța țintei ±0.5 RA", p05: "corespunde valorii RA țintă declarate, conform protocolului de măsurare stabilit în fabrică — nu eroare zero", target: "țintă declarată (fără valoare sugerată)" },
    },
    carbon: {
      eyebrow: "Standard de construcție",
      title: "Integral din carbon. De la cadru la mâner.",
      p: "Toate rachetele MAXIMUS actuale de pe această platformă sunt integral din carbon în structura lor, inclusiv mânerul. Mânerul nu este format cu spumă.",
      gripTitle: "Opt mărimi de mâner din fabrică. L0–L7.",
      gripP: "Fiecare mărime este o geometrie de mâner din carbon realizată în fabrică — nu o îngroșare obținută cu overgrip.",
      scaleCaption: "Schemă: denumirile nominale ale mânerelor L0–L7 (de la 4″ la 4⅞″). Nu sunt dimensiuni măsurate ale mânerului.",
      cta: "Arhitectura mânerelor din fabrică",
    },
    custom: {
      eyebrow: "Proiectare la comandă",
      title: "Proiectat conform specificației.",
      sub: "Gama standard este punctul de plecare.",
      p: "MAXIMUS acceptă cerințe tehnice dincolo de matricele publicate pentru evaluare, proiectare, validare și fabricație conform unei specificații convenite. Fezabilitatea se confirmă în scris.",
      chain: ["Definire", "Proiectare", "Validare", "Specificare", "Producție", "Măsurare / înregistrare"],
      cta: "Transmiteți o temă tehnică",
      cta2: "Discutați proiectarea la comandă",
    },
    training: {
      eyebrow: "Sisteme de antrenament",
      title: "Un sistem de antrenament construit în jurul impactului.",
      p: "Sweet Spot Trainer, metodologia MAXIMUS și Spot Trainer leagă echipamentul de antrenamentul condus de antrenor: impact centrat, control, încărcare progresivă și revenirea la racheta de performanță.",
      cta: "Sisteme de antrenament",
      cta2: "Solicitați o demonstrație",
      photoPending: "Fotografia rachetei de antrenament nu este încă publicată",
      sstP: "Un cap de antrenament de 50 in² pentru exersarea impactului centrat, cu patru configurații de greutate pentru încărcarea aleasă de antrenor.",
      sstCta: "Descoperiți Sweet Spot Trainer",
      sstCaption: "configurația de 300 g, una dintre cele patru",
      methodP: "Stabiliți obiectivele, alegeți echipamentul, exersați cu implicarea antrenorului, consemnați observațiile, reevaluați, ajustați și transferați munca în jocul de performanță.",
      methodCta: "Descoperiți metodologia",
      spotP: "O țintă rotundă mică pentru exersarea unui punct de impact precis și repetabil.",
      spotCta: "Descoperiți Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Producție și control al calității",
      title: "Construită după o specificație. Măsurată și consemnată.",
      p: "Producția respectă specificația scrisă a fiecărei comenzi. Înregistrările urmează clasa de precizie: înregistrări de producție păstrate pentru P2.5, înregistrări individuale și trasabilitate pentru P1.5, control individual și documentație pentru P0.5, acolo unde programul comenzii le prevede.",
      confirmedTitle: "Confirmat",
      confirmed: ["Construcție integral din carbon, de la cadru la mâner.", "Clasele de precizie P2.5, P1.5 și P0.5, cu patru parametri controlați.", "Opt mărimi de mâner din fabrică, L0–L7."],
      pendingTitle: "Nepublicat încă",
      pending: "Fotografiile echipamentelor de măsurare, exemplele de înregistrări de control al calității și filmările din fabrică nu sunt încă publicate. Nimic de pe această pagină nu constituie un certificat de măsurare.",
      captions: { lettering: "Inscripția MAXIMUS lucioasă pe cadrul mat", buttcap: "Mânerul și capacul inferior cu emblema leului", handle: "Gravură argintie de personalizare", finish: "Capul și planul cordajului" },
      cta: "Inginerie și producție",
    },
    world: {
      eyebrow: "Lumea MAXIMUS",
      title: "O cheie. Un ecosistem. Oportunități nelimitate.",
      note: "„Oportunități nelimitate” este o expresie de brand, nu o promisiune de fezabilitate tehnică, de venit sau de acces nelimitate. O achiziție nu creează redevențe, randamente din investiții, sponsorizare sau finanțarea dezvoltării unui jucător.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — și navigația dumneavoastră în lumea tenisului: un profil de echipament ghidat, la care se răspunde în scris." },
        personal: { h: "Personalizare", p: "Nume, inițiale, numere și identificarea echipei, realizate în tratamentul aprobat de gravură argintie." },
        development: { h: "Dezvoltare", p: "Sisteme de antrenament conduse de antrenor, înregistrări și reevaluare." },
        ecosystem: { h: "Ecosistem extins", p: "Branduri personale, înregistrări ale proprietarilor, rețea, licențiere și programe instituționale — fiecare prezentat cu stadiul său real." },
      },
      cta: "Descoperiți ecosistemul",
    },
    partners: {
      eyebrow: "Forme de parteneriat",
      title: "Antrenori, cluburi, distribuitori și parteneri.",
      p: "Întâi calificarea scrisă. Drepturile de țară, exclusivitatea și condițiile comerciale se negociază în scris — niciodată acordate printr-un formular.",
      cta: "Toate formele de parteneriat",
      formTitle: "Solicitare scurtă",
      formLead: "Alegeți scopul și scrieți-i MAXIMUS. Primiți un ID de cerere pe această pagină.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "NAVIGAȚIA DUMNEAVOASTRĂ ÎN LUMEA TENISULUI" } },
    personal: { eyebrow: "Personalizare", title: "Numele dumneavoastră. Numărul dumneavoastră. MAXIMUS al dumneavoastră." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Trei serii. Parametri reali." },
    map: { cta: "Descoperiți ecosistemul" },
  },
  racquets: {
    title: "Rachete",
    lead: "Trei serii de performanță cu un standard de construcție comun, un sistem de precizie comun și o arhitectură comună a mânerelor din fabrică. Fiecare serie este o arhitectură de performanță consacrată, în cadrul unei platforme de inginerie mai largi.",
    direction: { control: "Control", power: "Putere", spin: "Efect" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Direcția principală de joc",
    compareTitle: "Comparația seriilor",
    compareLead: "Doar date de arhitectură confirmate. Schemele de cordaj, lungimile, profilurile cadrului, intervalele de tensionare și valorile nominale de swingweight și de rigiditate pentru aceste serii nu sunt publicate; ele se colectează drept ținte solicitate, pentru analiză tehnică.",
    columns: { series: "Serie", head: "Suprafața capului", direction: "Direcție", weights: "Greutăți listate", range: "Interval de greutate", balance: "Date de balans" },
    balanceModelled: "Valori calculate",
    balanceNotProvided: "Nepublicat încă",
    construction: "Construcție: integral din carbon, de la cadru la mâner · Precizie: P2.5 / P1.5 / P0.5 · Mânere: L0–L7",
    otherTitle: "Alte sporturi cu rachetă",
    otherLead: "Direcții de dezvoltare aprobate. În aceste categorii nu există produse comercializabile și nicio specificație de tenis nu se transferă către ele.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Beach tennis" },
    ctaConfigure: "Configurați o cerere",
    ctaSeries: "Vedeți seria",
  },
  seriesPage: {
    eyebrow: "Serii de performanță",
    intro: {
      great: "Arhitectura GREAT de 97 in² este construită în jurul controlului: un cap compact, impact precis și siguranță în direcționare.",
      power: "Arhitectura POWER de 98 in² este construită în jurul transferului de energie: lungime și viteză a loviturii, pornind de la un cadru stabil.",
      spin: "Arhitectura SPIN de 100 in² este construită în jurul comportamentului mingii: rotație, marjă și modelarea traiectoriei.",
    },
    photoPending: "Fotografia seriei nu este încă publicată",
    detailPending: "Fotografiile de detaliu ale construcției și ale mânerului pentru această serie nu sunt încă publicate.",
    specsTitle: "Specificație și stare",
    catalogue: {
      eyebrow: "Catalogul seriei {series}",
      title: "{n} variante de greutate",
      lead: "Toate variantele seriei {series}, ordonate după greutate. Greutatea în grame, balansul în milimetri de la capătul mânerului. Fiecare vizualizare este afișată integral: nimic decupat, mascat sau întins.",
      selectLabel: "Alegeți o variantă de greutate",
      select: "Afișați această variantă",
      selected: "Afișată mai sus",
      balanceLabel: "Balans",
      headLabel: "Suprafața capului",
      constructionLabel: "Construcție",
      gripsLabel: "Mărimi de mâner din fabrică",
      precisionLabel: "Clase de precizie",
      balanceConfirmed: "Balansul este valoarea confirmată pentru această greutate și corespunde cifrei imprimate pe vizualizare. Prețurile, stocul și termenele de livrare nu sunt publicate aici.",
      balanceModelled: "Balansul este o valoare calculată pentru această greutate listată, nu o măsurătoare individuală din fabrică; el corespunde cifrei imprimate pe vizualizare. Prețurile, stocul și termenele de livrare nu sunt publicate aici.",
      zoom: "Deschideți imaginea",
      close: "Închideți",
      allTitle: "Toate cele {n} variante",
    },
    specs: { head: "Suprafața capului", direction: "Direcția principală", weights: "Greutăți listate", range: "Interval de greutate", balance: "Balans", construction: "Construcție", grips: "Mânere din fabrică", precision: "Clase de precizie" },
    construction: "Integral din carbon, de la cadru la mâner",
    statusTitle: "Stadiul valorilor",
    matrixTitle: "Matricea completă a greutăților",
    matrixLead: "Greutățile listate reprezintă selecția standard. Alte greutăți pot fi solicitate ca ținte la cerere; valorile intermediare care lipsesc nu se inserează.",
    balanceNote: {
      confirmed: "Valorile de balans sunt confirmate pentru fiecare greutate listată (mm de la capătul mânerului) și corespund cifrei imprimate pe vizualizarea acelei greutăți. Ele nu sunt calculate aici și nu sunt netezite între greutățile vecine; baza de măsurare se confirmă în specificația scrisă.",
      modelled: "Valorile de balans sunt calculate pentru fiecare greutate listată (mm de la capătul mânerului). Ele nu sunt măsurători individuale din fabrică; baza de măsurare se confirmă în specificația scrisă.",
      notprovided: "Valorile de balans pentru această serie nu sunt furnizate. Nu le deduceți din altă serie.",
    },
    optionsTitle: "Precizie, mâner și greutate",
    notPublished: "Nepublicate pentru această serie: schema de cordaj, lungimea, profilul cadrului, intervalul de tensionare și valorile de swingweight și de rigiditate. Le puteți indica drept ținte solicitate, pentru analiză tehnică.",
    offerTitle: "Ce se întâmplă după cererea dumneavoastră",
    offerSteps: [
      ["Cerere", "Trimiteți o configurație sau o întrebare. Un ID de cerere se afișează imediat."],
      ["Analiză", "MAXIMUS analizează seria, clasa, greutatea, mânerul și eventualele ținte solicitate."],
      ["Răspuns scris", "Specificația, disponibilitatea și condițiile comerciale se confirmă în scris."],
    ],
    faqTitle: "Întrebări",
    faq: [
      ["Valorile de balans sunt măsurate?", "Ele sunt calculate pentru greutățile listate, nu sunt măsurători individuale. Baza de măsurare se confirmă în specificația scrisă."],
      ["Pot solicita o greutate care nu este listată?", "Da, ca țintă la cerere, în grame întregi. Este analizată tehnic, iar fezabilitatea se confirmă în scris."],
      ["Ce schimbă clasa de precizie?", "Cât de strâns sunt menținute greutatea, balansul, swingweight și rigiditatea la specificația declarată și care înregistrări se păstrează."],
      ["Mânerul este îngroșat cu overgrip?", "Nu. L0–L7 sunt geometrii de mâner din carbon realizate în fabrică."],
      ["Unde sunt prețurile și termenele de livrare?", "Ele se confirmă în scris pentru fiecare cerere și nu sunt publicate aici."],
    ],
    faqSpinBalance: ["De unde provin valorile de balans ale seriei SPIN?", "Din tabelul confirmat al seriei Spin: 33 de variante de greutate, cu balansul în milimetri de la capătul mânerului. Fiecare pereche corespunde cifrei imprimate pe vizualizarea aprobată a acelei greutăți. Valorile nu sunt calculate și nu sunt netezite între greutățile vecine."],
    ctaBuild: "Configurați această serie",
    ctaAsk: "Întrebați despre această serie",
    ctaCompare: "Comparați toate seriile",
    weightsLabel: "greutăți listate",
    headLabel: "cap",
  },
  precision: {
    title: "Precizie și rigiditate",
    switch: { label: "Alegeți o clasă de precizie", panelLabel: "Patru parametri controlați —", qcLabel: "Arhitectura controlului calității", protocolNote: "conform protocolului de măsurare definit în controlul calității din fabrică", fullTable: "Tabel comparativ complet" },
    lead: "Patru parametri controlați ca un singur sistem de inginerie. Fiecare clasă definește cât de strâns este menținută o rachetă finită la specificația declarată și care înregistrări de calitate se produc.",
    statement: "Greutate. Balans. Swingweight. Rigiditate. Controlate ca un singur sistem de inginerie.",
    classes: {
      "P2.5": { name: "Nucleu de performanță scalabil", qc: "Măsurare individuală și înregistrări de producție păstrate." },
      "P1.5": { name: "Precizie avansată", qc: "Măsurare individuală, înregistrări individuale și trasabilitate." },
      "P0.5": { name: "Profesional · control individual", qc: "Control individual cu valori nominale și efective și înregistrări individuale de măsurare; identitate de serie, trasabilitate pe lot, certificat de precizie și seturi asortate, acolo unde programul comenzii le prevede." },
    },
    columns: { cls: "Clasă", weight: "Greutate", balance: "Balans", sw: "Swingweight", stiff: "Rigiditate", qc: "Arhitectura controlului calității" },
    stiffTarget: "toleranța țintei",
    stiffExact: "corespunde valorii RA țintă declarate, conform protocolului de măsurare stabilit în fabrică",
    programmeNote: "Identitatea de serie, certificatele și documentația pentru seturile asortate se emit numai acolo unde programul unei comenzi anume le prevede.",
    targetsNote: "Specificațiile de rigiditate sunt ținte de producție până când protocolul relevant și dovezile din producție susțin o afirmație mai puternică. Propunerea de arhitectură nu presupune că fiecare configurație listată a trecut deja printr-un proces complet de eliberare pe patru parametri.",
    stiffnessTitle: "De ce contează rigiditatea",
    stiffnessP1: "Rigiditatea cadrului influențează modul în care cadrul răspunde la impact, senzația pe care o transmite și cât de consecvente sunt două rachete între ele. Beneficiul central al controlului ei este răspunsul repetabil față de o specificație declarată.",
    stiffnessP2: "Înainte de publicarea unei conformități verificate, înregistrarea internă de control al calității identifică instrumentul, starea lui de calibrare, metoda, starea rachetei, rezoluția, incertitudinea de măsurare, măsurătorile repetate, regula de rotunjire și regula de acceptare. Un număr întreg afișat identic nu este o dovadă a variației fizice zero sau a erorii de măsurare zero.",
    fields: ["Țintă", "Rezultat măsurat", "Toleranță admisă", "Capabilitatea instrumentului"],
    fieldsNote: "Păstrate ca câmpuri separate în fiecare înregistrare.",
    matchedTitle: "Seturi asortate",
    matchedP: "Criteriile pentru seturile asortate se definesc separat de toleranța individuală. Conformitatea fiecărei rachete cu toleranța sa nominală nu dovedește, prin ea însăși, o anumită diferență maximă între două rachete. Perechile, tripletele și seturile de echipă asortate se solicită prin configurator și se confirmă în scris.",
    extendedTitle: "Model tehnic extins",
    extendedP: "Modelul de date acceptă parametri suplimentari. Pentru aceștia nu există încă valori sau clase de toleranță; ei pot fi indicați drept ținte solicitate într-o temă tehnică.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Comportament torsional", length: "Lungime", beamProfile: "Profilul cadrului", headGeometry: "Geometria capului", stringPattern: "Schema de cordaj", durability: "Durabilitate", vibration: "Caracteristici de vibrație" },
    noZero: "MAXIMUS nu descrie gama sa listată drept una cu toleranță zero. În cadrul gamei, precizia este exprimată ca o clasă, cu o toleranță declarată și o arhitectură definită de control al calității. ZERO nu face parte din gamă.",
    zero: {
      eyebrow: "Opțiune exclusivă",
      title: "ZERO",
      sub: "Zero grame de toleranță.",
      p: "Cele trei clase mențin o rachetă finită în interiorul unei benzi declarate. ZERO elimină banda. Racheta este construită și măsurată până când citirea este egală cu valoarea declarată la rezoluția instrumentului de măsurare din fabrică, iar acea citire este predată împreună cu ea. Nu face parte din gama listată și nu este o a patra clasă: se convine individual, pentru o rachetă sau un set asortat, ca exclusivitate la comandă. Prin acord, aceeași abordare se aplică balansului și swingweight-ului.",
      points: [
        ["Fără bandă", "Valoarea declarată este rezultatul, nu centrul unei toleranțe."],
        ["Una câte una", "Construită, măsurată și înregistrată ca unitate unică."],
        ["Predată împreună cu racheta", "Citirea măsurată este predată și păstrată în înregistrarea de producție."],
        ["Confirmare în scris", "Parametrii, obiectul și termenul de livrare se convin înainte de producție."],
      ],
      note: "Concordanța se stabilește la rezoluția instrumentului de măsurare din fabrică. O valoare afișată identică nu reprezintă o afirmație privind variația fizică zero. Disponibilitatea și condițiile se convin individual pentru fiecare comandă.",
      cta: "Solicitați ZERO",
    },
    cta: "Configurați cu o clasă de precizie",
  },
  grip: {
    title: "Arhitectura mânerelor din fabrică",
    statement: "Opt mărimi de mâner din fabrică. L0–L7.",
    lead: "Geometria mânerului face parte din arhitectura mânerului de carbon. Fiecare mărime este fabricată ca geometrie de mâner, nu obținută prin înfășurare cu overgrip.",
    emph: "Mărimi extinse",
    p1: "Gama de opt mărimi din fabrică oferă antrenorilor și jucătorilor un interval de configurare mai larg, prin care echipamentul poate fi specificat în jurul jucătorului, inclusiv geometriile mai mari L6 și L7.",
    p2: "Denumirea nominală a mânerului este distinctă de dimensiunile brute ale mânerului structural și de protocolul final de măsurare. Mărimile se aplică seriilor de performanță și familiilor de antrenament de pe această platformă.",
    p3: "Pentru această gamă nu se formulează nicio pretenție de exclusivitate mondială.",
    columns: { size: "Mărime", nominal: "Valoare nominală", family: "Se aplică la" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Configurați cu mărimea dumneavoastră de mâner",
  },
  custom: {
    title: "Proiectare la comandă",
    statement: "Proiectat conform specificației.",
    sub: "Gama standard este punctul de plecare.",
    lead: "MAXIMUS acceptă cerințe tehnice dincolo de matricele de configurare publicate pentru evaluare, proiectare, validare și fabricație conform unei specificații convenite. Fezabilitatea se confirmă prin analiză — nu orice cerere imaginabilă este realizabilă fizic sau comercial.",
    scopeTitle: "Ce poate acoperi o temă tehnică",
    scope: ["Geometria capului și a cadrului", "Lungime", "Greutate", "Balans", "Swingweight", "Rigiditate", "Twistweight", "Geometria mânerului", "Construcție", "Seturi asortate", "Rachete de antrenament", "Grafică și gravură", "Identitate și programe de echipă", "Dezvoltare dependentă de matrițe"],
    processTitle: "Proces",
    process: [
      ["Definire", "Ținte preferate, limite obligatorii, utilizare prevăzută și compromisuri acceptabile."],
      ["Proiectare", "Evaluare inginerească în raport cu platforma și cu matrițele."],
      ["Validare", "Validare în raport cu specificația convenită."],
      ["Specificare", "O specificație scrisă, cu baza de măsurare și toleranțele."],
      ["Producție", "Producție conform specificației."],
      ["Măsurare / înregistrare", "Măsurare și înregistrări păstrate conform clasei de precizie aplicabile."],
    ],
    formTitle: "Transmiteți o temă tehnică",
    formLead: "Faceți distincția între țintele preferate și limitele obligatorii. Rezultatul este o cerere de analiză tehnică, nu o comandă de producție acceptată automat.",
    protected: "Rețetele de laminare, matrițele, identitatea furnizorilor, calculația internă a costurilor și know-how-ul protejat nu se divulgă pe acest canal.",
    cta: "Transmiteți o temă tehnică",
  },
  training: {
    title: "Sisteme de antrenament",
    lead: "Două familii de antrenament, cu standarde de producție proprii, unite de o singură metodologie: lucru condus de antrenor, înregistrări, reevaluare și transfer înapoi în jocul de performanță.",
    sst: { h: "Sweet Spot Trainer", p: "O rachetă de antrenament cu cap redus, de 50 in², într-un sistem cu patru greutăți, pentru exersarea impactului centrat, conștientizarea sweet spot-ului, controlul rachetei și încărcarea progresivă." },
    spot: { h: "Spot Trainer", p: "Antrenarea punctului de impact cu o țintă de contact rotundă și mică, pe baza aprobată cu patru greutăți." },
    method: { h: "Metodologie", p: "Stabiliți obiectivele, alegeți echipamentul cu implicarea antrenorului, folosiți sistemul potrivit, consemnați, reevaluați, ajustați și transferați." },
    experience: "Prindeți-o în mână. Loviți cu ea. Simțiți-o.",
    experienceP: "Solicitați testare, fitting sau o demonstrație asistată de antrenor. O cerere trimisă nu este o programare confirmată.",
    cta: "Solicitați o sesiune de fitting sau o demonstrație",
    distinct: "Sweet Spot Trainer, Spot Trainer și orice dispozitiv separat de demonstrație sunt produse distincte și nu se confundă niciodată.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "O categorie de antrenament separată, cu propriul standard de producție. Capul de 50 in² concentrează atenția pe locul impactului, iar cele patru greutăți asigură progresia încărcării.",
    baseline: "Bază confirmată",
    columns: { head: "Cap", length: "Lungime", pattern: "Schema de cordaj", grips: "Mânere din fabrică" },
    systemTitle: "Sistem de patru rachete",
    detailsTitle: "Detalii de construcție",
    systemLead: "Greutatea și balansul la livrare. Baza de măsurare se consemnează separat și nu este încă publicată.",
    purposeTitle: "Scop",
    purpose: ["Exersarea impactului centrat", "Conștientizarea sweet spot-ului", "Controlul rachetei", "Încărcare progresivă", "Dezvoltare condusă de antrenor", "Revenirea la racheta de performanță a jucătorului"],
    heavy: "Modelul de 400 g este o configurație de antrenament controlată. Nu este recomandat automat copiilor, începătorilor sau oricărui jucător; antrenorul stabilește încărcarea, durata și progresia.",
    precisionNote: "Clasele de precizie pentru performanță P2.5, P1.5 și P0.5 nu se aplică automat acestei familii de antrenament. Toleranțele de producție pentru antrenament urmează specificația aprobată proprie familiei.",
    health: "Nu se promite prevenirea sau tratarea cotului tenismanului, eliminarea accidentărilor ori o ameliorare garantată.",
    cta: "Solicitați o demonstrație Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Antrenarea punctului de impact cu o țintă de contact rotundă și mică. Un produs distinct, cu identitate vizuală proprie, construit pe baza aprobată cu patru greutăți.",
    purposeTitle: "Scop confirmat",
    purposeP: "Antrenarea jucătorului pentru a găsi și a repeta un punct de impact precis.",
    weightsTitle: "Progresia greutăților",
    weightsP: "Progresia greutăților urmează baza de greutăți aprobată a Sweet Spot Trainer. Valorile de balans și celelalte specificații ale Sweet Spot Trainer nu se transferă pe Spot Trainer.",
    dims: "Dimensiunile exacte ale țintei nu sunt încă publicate.",
    grips: "Arhitectura mânerelor din fabrică L0–L7.",
    notes: ["Clasele de precizie pentru performanță nu se aplică automat.", "Nu este o rachetă clasică în miniatură și nu se publică nicio schemă de cordaj.", "Spot Trainer, Sweet Spot Trainer și orice dispozitiv separat de demonstrație rămân distincte."],
    cta: "Întrebați despre Spot Trainer",
  },
  methodology: {
    title: "Metodologie și experiența produsului",
    lead: "Echipamentul este o singură parte a unui parcurs structurat de dezvoltare. Metoda pornește de la obiectivele jucătorului, nu de la eticheta unui produs.",
    stepsTitle: "Parcursul de dezvoltare",
    steps: [
      ["Stabilirea obiectivelor", "Obiectivele jucătorului și punctul de plecare."],
      ["Alegerea echipamentului", "Echipament adecvat, ales cu implicarea antrenorului."],
      ["Folosirea sistemului", "Sistemul de antrenament potrivit, condus de antrenor."],
      ["Consemnare", "Observații privind participarea reală, fără scoruri inventate."],
      ["Reevaluare", "Puncte de control comparabile."],
      ["Ajustare", "Ajustări de configurație sau de program."],
      ["Transfer", "Transferul celor învățate în jocul de performanță."],
    ],
    educationTitle: "Parcursuri de instruire",
    education: { player: "Jucători — înțelegerea configurației, a încărcării și a progresiei.", parent: "Părinți — continuitatea dezvoltării, echipament potrivit, înregistrări și drepturi.", coach: "Antrenori — sisteme de antrenament, fitting, evaluare și utilizarea autorizată a programelor." },
    evidenceTitle: "Disciplina probelor",
    evidenceP: "Înregistrările privind participarea reală și observațiile se păstrează împreună cu clasificarea lor — declarate de participant, confirmate de tutore, validate de antrenor sau măsurate de sistem. Progresul, scorurile și validarea nu se inventează niciodată.",
    experienceTitle: "Prindeți-o în mână. Loviți cu ea. Simțiți-o.",
    experienceP: "Se pot solicita testarea, o sesiune de fitting sau o demonstrație asistată de antrenor. O cerere trimisă nu este o programare confirmată.",
    cta: "Solicitați fitting sau demonstrație",
    cta2: "Solicitare de parteneriat pentru antrenori",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — profil de echipament ghidat",
    title: "MAXIMUS GPS",
    lead: "Un profil de echipament ghidat. Răspundeți numai la ce este relevant; verificați și corectați răspunsurile; primiți o sinteză, direcțiile de configurare aplicabile și o acțiune următoare concretă.",
    honesty: "În această versiune nu sunt aprobate reguli automate de fitting. De aceea, GPS produce o sinteză clară a cerințelor și indică direcții de configurare; detaliile de echipament sunt direcționate către analiza unui specialist.",
    rulesVersion: "Versiunea regulilor",
    dataVersion: "Versiunea datelor de produs",
    steps: { role: "Rol", sport: "Disciplină", experience: "Experiență", objectives: "Obiective", style: "Stil de joc", equipment: "Echipament actual", preference: "Preferințe", coach: "Implicarea antrenorului", ageBand: "Categorie de vârstă", review: "Verificare" },
    notStored: "Nu se păstrează în acest browser.",
    ageNote: "Folosită numai pentru direcționarea cererii. Nu se solicită nume, dată de naștere sau informații medicale.",
    q: {
      role: "Care dintre acestea vă descrie?",
      sport: "Care sport?",
      experience: "Nivel de experiență",
      objectives: "Ce contează cel mai mult? (alegeți până la trei)",
      style: "Stilul de joc, dacă îl cunoașteți",
      equipment: "Echipamentul actual, dacă există",
      equipmentHint: "Marca și modelul, greutatea sau mărimea mânerului, dacă le cunoașteți. Opțional.",
      preference: "Configurația preferată sau mărimea de mâner cunoscută",
      grip: "Mărimea de mâner cunoscută",
      coach: "Un antrenor este implicat în deciziile privind echipamentul?",
      ageBand: "Categoria de vârstă a jucătorului (folosită numai pentru direcționarea corectă a cererii)",
    },
    roles: { player: "Jucător", parent: "Părinte sau tutore", coach: "Antrenor", club: "Club sau academie", other: "Altul" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Alt sport cu rachetă" },
    sportNote: "Produsele există pentru tenis. Celelalte sporturi sunt direcții de dezvoltare; interesul dumneavoastră este consemnat pentru programul corespunzător.",
    experience: { beginner: "Începător", developing: "În dezvoltare", intermediate: "Intermediar", advanced: "Avansat", competitive: "Competițional", professional: "Profesionist" },
    objectives: { control: "Control", power: "Putere", spin: "Efect", comfort: "Confort", manoeuvrability: "Manevrabilitate", development: "Dezvoltare pe termen lung", competition: "Competiție", training: "Sistem de antrenament", team: "Echipă sau set asortat", personal: "Personalizare" },
    styles: { baseline: "De fund de teren", allcourt: "Joc complet", attacking: "Ofensiv", defensive: "Defensiv", coach: "Ales de antrenor", unknown: "Nu știu" },
    ageBands: { u10: "Sub 10 ani", u14: "10–13 ani", u18: "14–17 ani", adult: "18 ani și peste" },
    output: {
      title: "Profilul dumneavoastră de echipament",
      status: "Necesită analiza unui specialist",
      statusP: "În această versiune nu se produce o potrivire automată. Profilul dumneavoastră a fost sintetizat pentru analiza unui specialist.",
      directionsTitle: "Direcțiile de configurare aplicabile",
      directionsP: "Pe baza obiectivelor pe care le-ați declarat și a direcției de joc declarate pentru fiecare serie. Este o direcție, nu o recomandare de fitting.",
      trainingHint: "Obiectivele dumneavoastră includ un sistem de antrenament: vedeți Sweet Spot Trainer și Spot Trainer.",
      teamHint: "Seturile asortate se solicită prin configurator și se confirmă în scris.",
      next1: "Trimiteți profilul pentru analiza unui specialist",
      show: "Afișați profilul meu",
      configure: "Configurați",
      sendP: "Trimiteți profilul către MAXIMUS pentru analiza unui specialist. Un ID de cerere se afișează imediat; răspunsul vine în scris.",
      otherSport: "Rachetele MAXIMUS există pentru tenis. Pentru celelalte sporturi cu rachetă nu se sugerează nicio serie de tenis; interesul dumneavoastră este consemnat ca direcție de dezvoltare.",
      noDirection: "Obiectivele dumneavoastră nu indică o singură direcție de joc. Analiza unui specialist propune o configurație.",
      incomplete: "Lipsesc câteva răspunsuri obligatorii — folosiți „Modificați răspunsurile” pentru a le completa.",
    },
    privacy: "GPS nu solicită informații medicale și nici date de identificare ale copiilor. În această sesiune de browser se păstrează numai răspunsurile cu variante predefinite; textul liber nu se stochează.",
  },
  build: {
    title: "Configurați-vă racheta",
    lead: "Configurați o cerere: seria, clasa de precizie, greutatea listată sau o țintă la cerere, mărimea mânerului, țintele solicitate, personalizarea, seturile asortate și cantitatea. Rezultatul este o cerere de configurație cu un ID de cerere — nu un cod de produs, un preț, un termen de livrare sau un certificat.",
    steps: { series: "Serie", cls: "Clasă de precizie", weight: "Greutate", grip: "Mâner", targets: "Ținte", personal: "Personalizare", set: "Set și cantitate", use: "Utilizare", review: "Verificare" },
    q: {
      series: "Alegeți o serie",
      cls: "Alegeți o clasă de precizie",
      weightMode: "Greutate",
      listed: "Greutate listată",
      customWeight: "Greutatea solicitată (g)",
      balanceShown: "Balansul calculat pentru această greutate",
      balanceRequest: "Balansul solicitat (mm)",
      grip: "Mărimea de mâner din fabrică",
      targetsTitle: "Ținte solicitate",
      swingweight: "Swingweight solicitat (kg·cm²)",
      stiffness: "Rigiditatea solicitată (RA)",
      basis: "Baza de măsurare pentru valorile solicitate",
      engraving: "Textul gravurii",
      engravingHint: "Nume, inițiale sau număr. Litere latine, cifre, spațiu, cratimă, apostrof și punct; până la 24 de caractere. Alte alfabete se acceptă pentru confirmarea grafică.",
      engravingType: "Personalizare",
      types: { none: "Fără", name: "Numele jucătorului", initials: "Inițiale", number: "Numărul setului", academy: "Identificarea antrenorului sau a academiei", team: "Program de echipă" },
      set: "Rachetă individuală sau set asortat",
      use: "Utilizare prevăzută",
      uses: { play: "Joc personal", competition: "Competiție", coaching: "Antrenorat", team: "Echipă sau academie", retail: "Evaluare pentru retail sau distribuție", other: "Altceva" },
      notes: "Cerințe tehnice suplimentare",
    },
    classes: { "P2.5": "P2.5 — nucleu de performanță scalabil", "P1.5": "P1.5 — precizie avansată", "P0.5": "P0.5 — profesional, control individual" },
    stiffExactShort: "rigiditatea corespunde valorii RA țintă declarate, conform protocolului stabilit în fabrică",
    clsNote: "Fiecare clasă controlează patru parametri. P0.5 este o toleranță strânsă, obținută conform unui protocol de măsurare definit — nu eroare zero. Identitatea de serie, certificatele și documentația pentru seturile asortate se aplică numai acolo unde programul comenzii dumneavoastră le prevede.",
    listedNote: "Din matricea confirmată a seriei.",
    customNote: "O greutate din afara matricei, analizată tehnic.",
    balanceCaption: "Fiecare greutate listată își afișează balansul calculat, în mm de la capătul mânerului. Valorile calculate nu sunt măsurători individuale.",
    spinNote: "Greutățile SPIN formează arhitectura de greutăți solicitată. Balansul, swingweight și rigiditatea pentru SPIN nu sunt furnizate; ele se definesc în analiza tehnică.",
    customHint: "Grame întregi, numai cifre. O greutate la cerere este o solicitare de analiză tehnică; fezabilitatea se confirmă în scris și nicio valoare nu se rotunjește.",
    gripNote: "geometrie de mâner din carbon realizată în fabrică, nu o îngroșare obținută cu overgrip",
    targetsLead: "Opțional. Introduceți numai valorile de care aveți nevoie. Fiecare se consemnează ca țintă solicitată pentru analiză tehnică, nu ca specificație publicată.",
    basisHint: "Obligatoriu atunci când solicitați o greutate la cerere sau orice țintă: valorile se referă la o rachetă fără cordaj sau cu cordaj?",
    inputRange: "Valori acceptate: {min}–{max}.",
    inputRangeNote: "Intervalele de introducere doar elimină valorile imposibile. Ele nu descriu capacitatea de producție.",
    listedBasis: "valori listate — baza de măsurare se confirmă în specificația scrisă",
    notStored: "Nu se păstrează în acest browser; reintroduceți-l dacă reîncărcați pagina.",
    artworkReview: "este necesară confirmarea grafică",
    previewNote: "Nu se afișează o previzualizare: un șablon de gravură aprobat pentru acest model nu este încă publicat. Textul dumneavoastră se colectează pentru confirmarea grafică.",
    teamSub: "4–99 de rachete pe set",
    setsLabel: { individual: "Numărul de rachete", pair: "Numărul de perechi asortate", triple: "Numărul de triplete asortate", team: "Numărul de seturi de echipă" },
    teamSizeLabel: "Rachete pe set de echipă",
    totalLabel: "Total rachete",
    racquetsUnit: "rachete",
    setRule: "Cantitatea numără seturi: o pereche asortată are 2 rachete pe set, un triplet asortat are 3.",
    restart: "Începeți o configurație nouă",
    notices: { weightCleared: "{w} g nu există în matricea {series}, de aceea greutatea a fost ștearsă. Alegeți o greutate listată sau solicitați o țintă la cerere." },
    reviewTitle: "Cerere de configurație",
    reviewP: "Verificați configurația, apoi adăugați datele dumneavoastră de contact. Cererea se înregistrează cu un ID de cerere și primește răspuns în scris; disponibilitatea și condițiile comerciale se confirmă în scris.",
    reviewErrors: "Câteva răspunsuri din configurație necesită atenție:",
    edit: "Modificați",
    fieldNames: { series: "Serie", cls: "Clasă de precizie", mode: "Selecția greutății", weight: "Greutate listată", customWeight: "Greutate solicitată", basis: "Baza de măsurare", balanceReq: "Balans solicitat", sw: "Swingweight solicitat", ra: "Rigiditate solicitată", grip: "Mărimea mânerului", ptype: "Personalizare", engraving: "Textul gravurii", setType: "Tip de set", sets: "Cantitate", teamSize: "Rachete pe set de echipă", use: "Utilizare prevăzută", notes: "Cerințe suplimentare" },
    status: { listed: "greutate listată", requestedArchitecture: "arhitectură de greutăți solicitată", technicalReview: "cerere de analiză tehnică", notPublished: "nu este furnizat", requestedCondition: "stare solicitată" },
    chooseLink: "Nu sunteți sigur care serie vi se potrivește? Primiți ajutor în alegere",
    cta: "Trimiteți cererea de configurație",
  },
  experience: {
    title: "Testare și fitting",
    statement: "Prindeți-o în mână. Loviți cu ea. Simțiți-o.",
    lead: "Solicitați testare, o sesiune de fitting sau o demonstrație asistată de antrenor. Cererile se analizează și primesc răspuns în scris; o cerere trimisă nu este o programare confirmată.",
    optionsTitle: "Ce se poate solicita",
    options: ["Testarea rachetelor", "Sesiune de fitting", "Demonstrație asistată de antrenor", "Demonstrație Sweet Spot Trainer sau Spot Trainer", "Zi de demonstrații pentru echipă sau academie"],
    formTitle: "Cerere de fitting sau de demonstrație",
  },
  engineering: {
    title: "Inginerie și producție",
    statement: "Aeronave. Iahturi. Rachete.",
    lead: "O singură filozofie de inginerie în trei medii: principiile care modelează o aeronavă, precizia care ghidează un iaht în larg, performanța care definește fiecare rachetă MAXIMUS. O narațiune de inginerie — nu o afirmație privind certificarea aeronautică, deținerea de iahturi, deținerea unei fabrici sau transferul direct de materiale.",
    manifesto: ["Credem că ingineria de excepție nu are granițe.", "O singură filozofie. Proiectată fără compromisuri."],
    capabilityTitle: "Capabilitate de producție",
    capabilityLead: "Capabilitatea este prezentată ca o succesiune, nu ca un slogan.",
    sequence: [
      ["Specificație", "Seria, clasa de precizie, greutatea, balansul, swingweight, ținta de rigiditate, geometria mânerului, personalizarea."],
      ["Producție", "Construcție integral din carbon, de la cadru la mâner, realizată conform specificației."],
      ["Control al calității", "Măsurare și înregistrări conform clasei de precizie: înregistrări de producție, înregistrări individuale și trasabilitate, certificare individuală."],
      ["Producție repetată", "Răspuns repetabil față de o specificație declarată, de la un lot la altul."],
      ["Trasabilitate", "Identitate de serie, trasabilitate pe lot și certificat de precizie, acolo unde clasa îl prevede."],
    ],
    capacityNote: "Capacitatea de producție, termenele de livrare, cantitățile minime și graficele de livrare se confirmă în scris, pentru fiecare program, în raport cu comenzile confirmate și cu un grafic de lansare convenit.",
    truth: "Capacitatea nu este producție realizată, stoc, un termen de livrare garantat sau deținerea unei unități de producție.",
    cta: "Distribuție și dezvoltare pe țări",
    cta2: "Transmiteți o temă tehnică",
  },
  ecosystem: {
    title: "Ecosistemul MAXIMUS",
    lead: "O singură cheie. Iată ce deschide. Fiecare nod are o explicație, un stadiu exact și o acțiune următoare relevantă.",
    words: ["Inginerie", "Performanță", "Inovație", "Comunitate", "Oportunitate", "Scop"],
    nodes: {
      engineering: { h: "Ingineria și producția rachetelor", p: "Rachete integral din carbon, proiectate conform specificației, produse cu înregistrări de calitate și trasabilitate.", a: "Inginerie și producție" },
      precision: { h: "Precizie și configurare individuală", p: "Patru parametri, trei clase de precizie, opt mărimi de mâner și proiectare la comandă.", a: "Precizie și rigiditate" },
      training: { h: "Antrenament și metodologie", p: "Sweet Spot Trainer, Spot Trainer și un parcurs structurat de dezvoltare.", a: "Sisteme de antrenament" },
      development: { h: "Dezvoltarea jucătorului și a antrenorului", p: "Selecție condusă de antrenor, înregistrări, reevaluare și parcursuri de instruire.", a: "Metodologie" },
      identity: { h: "Identitate personală și branduri personale", p: "De la gravură până la un brand personal sau profesional guvernat prin drepturi.", a: "Branduri personale" },
      owners: { h: "Înregistrări, cunoștințe și drepturi ale proprietarilor", p: "O arhivă a proprietarului, propusă și cu acces controlat, pentru înregistrări de echipament, de dezvoltare și de drepturi.", a: "Proprietari și arhiva" },
      mipa: { h: "Proveniență MIPA și control intern", p: "Stratul intern de proprietate intelectuală, proveniență și control documentar.", a: "Identitate juridică și control" },
      digital: { h: "Infrastructură digitală și direcția Blockchain 5.0", p: "Proveniență, înregistrări trasabile, probe cu acces controlat și identitatea produsului, ca direcție tehnologică declarată.", a: "Direcție tehnologică" },
      licensing: { h: "Licențiere contractuală și programe de redevențe", p: "Branduri, produse și pachete de drepturi licențiate, cu condiții definite în fiecare acord.", a: "Forme de licențiere" },
      families: { h: "Participarea familiei și beneficiile programului", p: "Decizii informate, continuitate, înregistrări păstrate și beneficii definite de program.", a: "Familii și părinți" },
      network: { h: "MAXIMUS Sports Network", p: "Jucători, antrenori, cluburi, academii, prestatori de servicii, operatori și parteneri regionali.", a: "Sports Network" },
      market: { h: "Cluburi, academii, distribuție și dezvoltare pe țări", p: "Programe de echipă, retail, distribuție și dezvoltarea teritoriului, prin calificare scrisă.", a: "Forme de parteneriat" },
      institutional: { h: "Programe instituționale, educație, inovație și impact social", p: "Stratul instituțional asigurat de MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC), acolo unde un program stabilește acest rol.", a: "Programe instituționale" },
      extensions: { h: "Viitoare extinderi în sporturi cu rachetă și îmbrăcăminte MAXIMUS", p: "Padel, pickleball, squash, badminton, racquetball, beach tennis și îmbrăcămintea, ca direcții de dezvoltare.", a: "Sporturi cu rachetă" },
    },
    boundaryTitle: "Limite",
    boundary: [
      "Cumpărarea unei rachete nu creează calitatea de membru instituțional, drepturi de guvernanță, redevențe sau drepturi de investiție.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) este operatorul instituțional numai acolo unde un program stabilește acest rol; vânzările de echipament indică entitatea contractantă efectivă.",
      "Granturile, statutul de organizație nonprofit, tratamentul fiscal și autorizațiile de reglementare nu se aplică automat în toate țările.",
    ],
    techTitle: "Direcție tehnologică",
    techP: "Blockchain 5.0 este direcția tehnologică declarată a MAXIMUS. Scopurile ei funcționale sunt proveniența, înregistrările trasabile, probele cu acces controlat, identitatea produsului și reconcilierea evenimentelor comerciale eligibile. Nu se prezintă niciun mecanism de consens, nicio capacitate de tranzacționare, nicio rețea de noduri, nicio adresă de contract inteligent, niciun token și nicio certificare independentă și nu se afirmă existența unei implementări în funcțiune. Informațiile personale, înregistrările privind copiii și acordurile confidențiale nu se introduc niciodată, în mod implicit, într-un sistem public imuabil.",
  },
  brands: {
    title: "Branduri personale și ambasadori",
    statement: "De la jucător la brand. De la antrenor la brand.",
    lead: "Un parcurs dedicat brandului personal. Implicarea MAXIMUS include dezvoltarea brandului și promovarea convenită — nu doar un nume pe o rachetă.",
    progressionTitle: "Progresia prevăzută",
    progression: [
      ["Identitate verificată", "O identitate verificată și un istoric de dezvoltare."],
      ["Brand distinctiv", "Un brand personal sau profesional distinctiv."],
      ["Conținut cu drepturi clarificate", "Conținut cu drepturi clarificate și identitate de produs aprobată."],
      ["Inginerie și colecții", "Proiectare și dezvoltare de colecții, acolo unde se convine."],
      ["Promovare", "Promovare prin canalele și parteneriatele MAXIMUS convenite."],
      ["Participare", "Participare contractuală la vânzările sau licențierile eligibile."],
      ["Raportare", "Raportare transparentă, conform acordului."],
    ],
    royaltiesTitle: "Redevențe și licențiere",
    royalties: [
      "Redevențele se atașează brandului, produsului, tranzacției sau pachetului de drepturi licențiate care au fost definite.",
      "„Vânzări la nivel mondial” înseamnă vânzările eligibile din aria contractului — niciodată fiecare rachetă MAXIMUS fără legătură cu el.",
      "Cotele, baza de calcul, teritoriile, durata, restituirile, deducerile, raportarea, decontarea și verificarea se definesc prin acordul relevant. Nu se publică niciun procent de redevență implicit.",
      "Nu se promite nicio campanie globală, niciun buget de media, niciun rezultat de sponsorizare și niciun succes comercial în absența unei arii convenite.",
    ],
    cta: "Trimiteți o solicitare de colaborare de brand",
    cta2: "Solicitare de parteneriat pentru antrenori",
  },
  families: {
    title: "Familii și părinți",
    lead: "Decizii informate privind echipamentul, continuitatea dezvoltării, cunoștințe și drepturi păstrate, vizibilitatea participării și beneficii definite de program, care pot susține activitatea viitoare.",
    nowTitle: "Disponibil acum",
    now: ["Solicitări privind familia și dezvoltarea, în scris.", "Alegerea echipamentului cu implicarea antrenorului, cereri de fitting și de demonstrație.", "Înregistrări private: profilurile copiilor nu se publică niciodată și nu se comercializează în mod implicit.", "Parcurs de instruire pentru părinți: configurație, încărcare, progresie, înregistrări și drepturi."],
    plannedTitle: "În plan",
    planned: ["Beneficii de participare definite de program, utilizabile pentru bunuri și servicii din ecosistem, nu ca dobândă în numerar.", "Înregistrări ale proprietarului și ale familiei în arhiva propusă a proprietarului, cu permisiuni pentru tutore și transferul controlului la împlinirea vârstei de 18 ani."],
    categoriesTitle: "Păstrate separat",
    categories: ["Redevențe contractuale rezultate din drepturi licențiate sau din vânzări eligibile", "Beneficii de participare definite de un program", "Credite pentru achiziții sau servicii", "Plăți în avans", "Calitatea de membru instituțional"],
    categoriesP: "Aceste categorii nu se tratează niciodată ca interschimbabile.",
    statusTitle: "Stadiul real al programului pentru familii",
    journeyTitle: "Parcursul pentru familii",
    journey: [
      ["Obiectiv", "Ce vrea jucătorul să realizeze în continuare."],
      ["Nivelul actual", "Unde se află jucătorul astăzi."],
      ["Antrenor", "Dacă un antrenor participă la deciziile privind echipamentul."],
      ["Echipament", "Echipament potrivit pentru etapă, inclusiv sisteme de antrenament, acolo unde este relevant."],
      ["Practică convenită", "Utilizare condusă de antrenor, convenită în prealabil."],
      ["Reevaluare", "Reevaluare la puncte de control comparabile."],
    ],
    brief: {
      who: "Părinți și tutori ai jucătorilor, în orice etapă.",
      value: "Un răspuns scris privind echipamentul potrivit, implicarea antrenorului și următorul pas de dezvoltare.",
      now: "Solicitări privind familia, în scris; alegere cu implicarea antrenorului; înregistrări private — profilurile copiilor nu se publică niciodată.",
      next: "Trimiteți solicitarea pentru familie de mai jos. Primiți imediat un ID de cerere.",
    },
    formTitle: "Solicitare pentru familii",
    formNote: "Se completează de către un părinte sau tutore. Nu includeți numele copilului, data nașterii, școala sau informații medicale.",
    noPromise: "O achiziție nu promite redevențe, randamente din investiții, sponsorizare sau finanțarea dezvoltării unui copil.",
    statusP: "Această versiune explică modelul și acceptă solicitări privind programul. Acumularea, plățile și utilizarea beneficiilor nu sunt disponibile până când evenimentele eligibile, beneficiarii, sursa de finanțare, baza de calcul, utilizările permise, tratamentul contabil, restituirile, anulările, expirarea, transferabilitatea, închiderea programului și soluționarea litigiilor nu sunt definite în scris. Nu se promite niciun sold care să nu scadă niciodată, nicio participare nu acoperă costul întregului antrenament și nu se sugerează nicio protecție a capitalului.",
    cta: "Trimiteți o solicitare privind familia sau dezvoltarea",
  },
  owners: {
    title: "Proprietari și arhiva proprietarului",
    lead: "Arhiva proprietarului este o înregistrare propusă, cu acces controlat, a echipamentului, a dezvoltării, a cunoștințelor, a conținutului și a drepturilor documentate. Este prezentată ca parte a arhitecturii planificate pentru proprietari: nu se afișează conturi active, solduri, certificate sau realizări.",
    nowTitle: "Pentru proprietarii actuali, acum",
    now: ["Solicitări ale proprietarilor: referința produsului sau numărul de serie, configurarea, service-ul și cererile de înregistrări, în scris.", "Certificat de precizie și documentație pentru seturile asortate, acolo unde clasa de precizie le prevede, livrate împreună cu produsul."],
    archTitle: "Arhitectura planificată a arhivei",
    arch: ["Identitatea produsului și referințele de serie", "Configurația și certificatele de calitate aplicabile", "Istoricul de service și de configurare", "Înregistrări de dezvoltare ale jucătorului sau ale antrenorului", "Calificări și realizări verificate", "Materiale media cu drepturi clarificate și lucrări proprii", "Licențe, permisiuni și referințe contractuale", "Înregistrări ale programului de brand personal", "Situații de redevențe aplicabile sau beneficii de participare"],
    separationTitle: "Ce înseamnă proprietatea",
    separation: [
      "Proprietatea asupra unei rachete fizice este separată de titularitatea dreptului de autor, de o licență, de un drept contractual sau de o înregistrare care descrie aceste lucruri.",
      "Un document stocat sau o înscriere în blockchain nu este automat dovada că un drept legal există sau că a fost transferat.",
      "Probele își păstrează clasificarea: declarate de participant, confirmate de tutore, validate de antrenor, măsurate de sistem.",
      "Pentru minori: înregistrări private, permisiuni pentru tutore, fără profiluri publicate ale copiilor și fără comercializarea identității în mod implicit.",
      "Exportul, corectarea, controlul accesului și un transfer adecvat al controlului fac parte din concepție.",
    ],
    techTitle: "Blockchain 5.0 și MxSN",
    techP: "Blockchain 5.0 este direcția tehnologică declarată; MxSN definește conceptele unei rețele cu acces controlat pentru consimțământ, livrare, probe, drepturi și raportare. Implementarea operațională nu este prezentată. Modelul de date al aplicației este construit pentru a se integra ulterior printr-o interfață documentată, fără a pretinde că astăzi există o conexiune.",
    cta: "Solicitare a proprietarului",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Legătura dintre jucători, antrenori, cluburi, academii, prestatori de servicii, operatori de programe și parteneri regionali.",
    functionsTitle: "Funcții posibile",
    functions: ["Descoperire", "Puneri în legătură", "Programe de dezvoltare", "Sprijin pentru echipament", "Evenimente", "Acces la servicii", "Oportunități pentru parteneri"],
    statusTitle: "Stadiul real",
    statusP: "Nu este publicat încă niciun registru public: vor fi listați numai participanții a căror identitate, relație și permisiune de a apărea sunt stabilite. O propunere trimisă unui club nu este un parteneriat, iar un potențial distribuitor nu este un distribuitor numit. Publicarea registrului, rezervările, mesageria și tranzacțiile comerciale sunt controlate separat și nu sunt active.",
    cta: "Candidați pentru rețea",
  },
  partnerships: {
    title: "Forme de parteneriat",
    lead: "Întâi calificarea scrisă. Fiecare formă conduce la o solicitare specifică rolului; condițiile comerciale urmează în scris.",
    commercialTitle: "Activități comerciale posibile ale platformei",
    commercial: ["Echipament", "Proiectare la comandă", "Personalizare", "Programe pentru echipe și academii", "Sisteme de antrenament", "Licențiere contractuală", "Distribuție", "Servicii aprobate", "Viitoare categorii de produse"],
    boundary: "Drepturile de țară, exclusivitatea, taxele de teritoriu și marjele distribuitorilor sunt condiții negociate. Nu se publică niciun venit, nicio prognoză, nicio evaluare, nicio cotă de piață, niciun randament, niciun angajament de finanțare și niciun parteneriat nenumit.",
    routes: {
      coaches: {
        title: "Antrenori",
        lead: "Sisteme de antrenament, fitting, identitate profesională, programe autorizate, oportunități de brand personal și furnizarea de echipament.",
        points: ["Sweet Spot Trainer și Spot Trainer în lucrul condus de antrenor.", "Fitting cu matricele de configurare și cele opt mărimi de mâner din fabrică.", "Coach-to-Brand: un profil profesional verificat și un sub-brand guvernat prin drepturi.", "Utilizarea autorizată a programelor urmează un acord scris."],
        cta: "Trimiteți o solicitare de parteneriat pentru antrenori",
        brief: {
          who: "Antrenori independenți și echipe de antrenori.",
          value: "Sisteme de antrenament pentru lucrul condus de antrenor, fitting cu matricele seriilor și cele opt mânere din fabrică, precum și un parcurs către o identitate profesională.",
          now: "Solicitări ale antrenorilor, în scris. Nu se publică și nu se sugerează niciun comision, câștig sau cotă de recomandare.",
          next: "Trimiteți solicitarea pentru antrenori de mai jos. Condițiile urmează în scris.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Cluburi și academii",
        lead: "Echipament pentru echipe, sisteme de antrenament, personalizare, programe de dezvoltare, service și participare în rețea.",
        points: ["Seturi de echipă și seturi asortate, solicitate prin configurator.", "Sisteme de antrenament și metodologie pentru dezvoltare structurată.", "Personalizare pentru programele de echipă, pe zonele aprobate.", "Zile de demonstrații, sesiuni de fitting și participare în rețea."],
        cta: "Trimiteți o temă pentru club sau academie",
        brief: {
          who: "Cluburi, academii și programe de echipă.",
          value: "Seturi de echipă și seturi asortate, sisteme de antrenament, personalizare pentru programele de echipă și zile de demonstrații.",
          now: "Teme pentru cluburi și academii, în scris; seturile de echipă se solicită prin configurator.",
          next: "Trimiteți tema pentru club sau academie de mai jos.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribuție și dezvoltare pe țări",
        lead: "Sortiment, coordonarea producției, capabilitate tehnică, dezvoltarea teritoriului și calificare comercială confidențială.",
        points: ["Calificarea scrisă a contrapărții, a teritoriului și a canalului.", "Sortiment definit pornind de la matricele de configurare și clasele de precizie.", "Teritoriul, exclusivitatea, volumele, prețurile și protecția comercială sunt condiții negociate, convenite în scris.", "Entitatea contractantă, condițiile de plată și baza de livrare se stabilesc pentru fiecare tranzacție."],
        cta: "Trimiteți o solicitare de distribuție sau de dezvoltare pe țară",
        brief: {
          who: "Comercianți, distribuitori și parteneri de țară.",
          value: "Un sortiment definit pornind de la matricele confirmate, clasele de precizie și gama de mânere, cu calificarea scrisă a teritoriului și a canalului.",
          now: "Solicitări de distribuție, în scris. Teritoriul, exclusivitatea, volumele și prețurile se negociază — niciunul nu se acordă printr-un formular.",
          next: "Trimiteți solicitarea de distribuție de mai jos.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategie și investiții",
        lead: "Capabilitate de inginerie, profunzimea configurării, modelul de producție, căile către piață, proprietatea intelectuală, serviciile și oportunitățile de extindere.",
        points: ["O discuție strategică calificată sau accesul controlat la informații urmează după calificarea scrisă.", "Informațiile publice se limitează la specificațiile de produs aprobate, arhitectura de configurare, capabilitățile verificate și explicațiile programelor.", "Economia specifică unui cumpărător, calculația costurilor, metodologia protejată și acordurile nepublicate se divulgă numai sub acord de confidențialitate sau contract."],
        cta: "Solicitați o discuție strategică calificată",
        brief: {
          who: "Investitori și parteneri strategici.",
          value: "O discuție calificată despre capabilitatea de inginerie, profunzimea configurării, modelul de producție, căile către piață și proprietatea intelectuală.",
          now: "Nu se publică cifre financiare, prognoze, evaluări sau randamente. Informațiile controlate urmează după calificarea scrisă și acordul de confidențialitate.",
          next: "Solicitați mai jos o discuție strategică calificată.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Programe instituționale",
        lead: "Educație, acces, inovație, dovezi de dezvoltare, impact social și programe structurate adecvat.",
        points: ["Programele instituționale se structurează prin MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC), acolo unde programul stabilește acest rol.", "Fondurile restricționate de program și tranzacțiile comerciale rămân distincte.", "O solicitare nu este o cerere de aderare acceptată, iar un cumpărător de echipament nu este membru instituțional.", "Granturile, statutul de organizație nonprofit, tratamentul fiscal și autorizațiile de reglementare sunt specifice fiecărei țări și nu se presupun niciodată."],
        cta: "Trimiteți o solicitare privind un program instituțional",
        brief: {
          who: "Instituții, programe de educație și de dezvoltare.",
          value: "Programe pentru educație, acces, inovație și dovezi de dezvoltare, structurate împreună cu operatorul adecvat.",
          now: "Solicitări instituționale, în scris. O solicitare nu este o cerere de aderare; achiziția de echipament nu este calitate de membru instituțional.",
          next: "Trimiteți solicitarea instituțională de mai jos.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Divulgare publică și controlată",
    disclosure: {
      public: { h: "Informații publice", p: "Specificațiile de produs aprobate, construcția, arhitectura de configurare, scopurile de antrenament, capabilitățile verificate, explicațiile programelor și formele de parteneriat." },
      qualified: { h: "Solicitare calificată", p: "Cerințe tehnice, cantități, interes teritorial, aria de dezvoltare și discuțiile comerciale relevante." },
      controlled: { h: "Controlat prin acord de confidențialitate sau contract", p: "Formule interne, protocoale detaliate de control al calității, scheme de laminare, matrițe, metode de producție, identitatea furnizorilor, calculația costurilor, economia specifică unui cumpărător, metodologia protejată, acordurile nepublicate și înregistrările sensibile privind drepturile." },
    },
  },
  contact: {
    title: "Contact și cereri",
    lead: "Alegeți scopul cererii. Fiecare formular colectează numai ce este necesar pentru direcționarea și evaluarea ei. Cererile primesc răspuns în scris.",
    email: "E-mail",
    instagram: "Instagram",
    legalLink: "Identitate juridică",
  },
  form: {
    purposeLabel: "Scopul cererii",
    purposes: {
      selection: "Ajutor în alegerea rachetei",
      product: "Solicitare despre produs",
      fitting: "Fitting sau demonstrație",
      technical: "Temă tehnică",
      config: "Cerere de configurație",
      gps: "Profil de echipament GPS",
      coach: "Parteneriat pentru antrenori",
      club: "Temă pentru club sau academie",
      distribution: "Distribuție sau dezvoltare pe țară",
      brand: "Colaborare de brand sau ambasador",
      family: "Solicitare privind familia sau dezvoltarea",
      institutional: "Program instituțional",
      strategic: "Discuție strategică sau de investiții",
      owner: "Solicitare a proprietarului",
      network: "Candidatură pentru Sports Network",
      general: "Solicitare generală",
    },
    fields: {
      name: "Nume",
      email: "E-mail",
      role: "Rolul dumneavoastră",
      country: "Țara sau regiunea",
      organisation: "Organizație",
      message: "Mesajul dumneavoastră",
      level: "Nivelul actual",
      objectives: "Ce contează cel mai mult (până la trei)",
      currentRacquet: "Racheta actuală",
      grip: "Mărimea mânerului, dacă o cunoașteți",
      seriesInterest: "Seria de interes",
      quantity: "Cantitate",
      city: "Orașul sau locul sesiunii",
      coachInvolved: "Este implicat un antrenor?",
      timing: "Perioada preferată",
      targets: "Ținte preferate",
      limits: "Limite obligatorii",
      use: "Utilizare prevăzută",
      tradeoffs: "Compromisuri acceptabile",
      basis: "Baza de măsurare",
      players: "Numărul de jucători",
      interests: "Domenii de interes",
      territory: "Teritoriul de interes",
      channels: "Canale existente și experiență",
      audience: "Public sau disciplină",
      proposal: "Colaborarea propusă",
      goal: "Obiectivul de dezvoltare",
      ageBand: "Categoria de vârstă a jucătorului",
      scope: "Aria programului",
      interestArea: "Domeniul de interes",
      productRef: "Referința produsului sau numărul de serie",
      requestType: "Tipul cererii",
      seeking: "Ce căutați",
      consent: "Sunt de acord ca MAXIMUS să păstreze și să folosească aceste date pentru a răspunde la această cerere. Acesta nu este un abonament de marketing.",
    },
    roles: { player: "Jucător", parent: "Părinte sau tutore", coach: "Antrenor", club: "Club sau academie", retailer: "Comerciant", distributor: "Distribuitor", brand: "Brand sau ambasador", investor: "Investitor sau partener strategic", institution: "Instituție", other: "Altul" },
    interestOptions: { training: "Sisteme de antrenament", fitting: "Fitting rachetă", identity: "Identitate profesională", programmes: "Programe autorizate", brand: "Brand personal", supply: "Furnizare de echipament", team: "Echipament pentru echipă", personalisation: "Personalizare", development: "Programe de dezvoltare", service: "Service și întreținere", network: "Participare în rețea" },
    ownerTypes: { setup: "Reglaj și configurare", service: "Service și întreținere", records: "Înregistrări și certificate", other: "Altceva" },
    strategicAreas: { engineering: "Capabilitate de inginerie", configuration: "Profunzimea configurării", manufacturing: "Modelul de producție", routes: "Căi către piață", ip: "Proprietate intelectuală și servicii", expansion: "Oportunități de extindere" },
    errors: {
      required: "Acest câmp este obligatoriu.",
      too_long: "Această valoare este prea lungă.",
      too_short: "Această valoare este prea scurtă.",
      invalid_email: "Introduceți o adresă de e-mail valabilă, de exemplu nume@example.com.",
      invalid_choice: "Alegeți una dintre opțiuni.",
      not_number: "Introduceți un număr întreg, folosind numai cifre.",
      out_of_range: "Această valoare se află în afara intervalului acceptat.",
      not_in_matrix: "Această greutate nu se află în matricea listată a seriei selectate.",
      decimal_not_supported: "Introduceți un număr întreg, fără zecimale.",
      too_many: "Selectați cel mult trei opțiuni.",
      consent_required: "Consimțământul este necesar pentru ca MAXIMUS să poată răspunde la această cerere.",
      invalid: "Această valoare nu este valabilă.",
    },
  },
  legal: {
    title: "Identitate juridică și control",
    lead: "Brandul public este MAXIMUS / MAXIMUS GPS. Identitățile juridice de operare sunt distincte și sunt prezentate aici.",
    entities: {
      institutional: { role: "Stratul programelor instituționale", p: "Asigură stratul programelor instituționale acolo unde un program stabilește acest rol. Nu este vânzător comercial de rachete. O organizație nonprofit constituită în Dubai International Financial Centre." },
      equipment: { role: "Entitatea comercială pentru echipament", p: "Entitatea comercială pentru echipament, pentru furnizare, distribuție și livrare comercială contractată, acolo unde documentele de operare actuale stabilesc acest rol. Partea contractantă a oricărei tranzacții este indicată în documentele acelei tranzacții." },
      ip: { role: "Proprietate intelectuală, brand și coordonare comercială", p: "Apare pentru un rol stabilit de proprietate intelectuală, de brand sau de coordonare comercială. Nu se atribuie nicio responsabilitate contractuală neconfirmată." },
      stewardship: { role: "Referință de administrare", p: "House of Maximus este referința de administrare a ecosistemului, acolo unde este susținută de sursa relevantă." },
      control: { role: "Proprietate intelectuală internă, proveniență și control documentar", p: "MIPA este stratul intern de proprietate intelectuală, proveniență și control documentar. O înregistrare internă MIPA este distinctă de o marcă externă, de un brevet, de o înregistrare a dreptului de autor sau de o recunoaștere judiciară și nu constituie o aprobare vizuală." },
    },
    labels: { licence: "Licență", registration: "Înregistrare", vat: "VAT TRN", address: "Adresă", email: "E-mail", jurisdiction: "Jurisdicție" },
    boundaryTitle: "Limite",
    boundary: [
      "O achiziție nu acordă automat calitatea de membru instituțional, drepturi de guvernanță, redevențe sau drepturi de investiție.",
      "Rolul instituțional este separat de tranzacțiile comerciale cu echipament.",
      "Confidențialitatea, condițiile programelor și aranjamentele de acces controlat corespund funcțiilor efectiv lansate.",
      "Nicio declarație generală privind legea aplicabilă nu se aplică fiecărui vizitator, fiecărei vânzări sau fiecărui program din străinătate; baza contractuală se stabilește în fiecare acord.",
    ],
  },
  privacy: {
    title: "Confidențialitate",
    updated: "Versiunea 2026-09-21 · site 4.2",
    contactTitle: "Contact pentru întrebări privind confidențialitatea",
    sections: {
      collect: ["Ce se colectează", "Când trimiteți un formular: datele pe care le introduceți (nume, e-mail, rol, țară sau regiune, organizație dacă o indicați, mesajul dumneavoastră și răspunsurile din formular), pagina și parametrii de campanie ai vizitei (pagina de intrare, limba, parametrii utm; identificatorii de clic publicitar numai dacă ați permis analiza) și momentul trimiterii. Adresa dumneavoastră IP este folosită doar în formă criptată (hash) și pe termen scurt, pentru limitarea abuzurilor, și nu se păstrează împreună cu cererea."],
      purpose: ["De ce", "Pentru a răspunde cererii dumneavoastră, pentru a pregăti propunerea sau specificația pe care ați solicitat-o și pentru a păstra o evidență a cererii. Pe baza unui formular nu se trimit mesaje de marketing."],
      storageOn: ["Unde se păstrează cererile", "Cererile se păstrează într-o bază de date a Upstash, Inc. (Redis), furnizată prin platforma de găzduire Vercel Inc."],
      notifyEmail: ["Notificarea unei cereri noi", "Când o cerere este acceptată, o notificare care conține datele trimise este expediată prin e-mail către cutia poștală MAXIMUS responsabilă."],
      notifyTelegram: ["Notificarea unei cereri noi", "Când o cerere este acceptată, o notificare care conține datele trimise este transmisă persoanei responsabile din MAXIMUS prin Telegram (Telegram FZ-LLC, Dubai), care prelucrează astfel notificarea în tranzit."],
      notifyWebhook: ["Notificarea unei cereri noi", "Când o cerere este acceptată, o notificare care conține datele trimise este transmisă către un punct intern MAXIMUS, pe o conexiune semnată și criptată."],
      notifyNone: ["Notificarea unei cereri noi", "Notificarea cererilor noi este în curs de configurare. Cererea dumneavoastră se păstrează și este citită de MAXIMUS din registrul intern; în acest scop nu se transmite nimic către un terț."],
      storageOff: ["Unde se păstrează cererile", "Stocarea cererilor este în curs de configurare. Până la activarea ei, formularele indică faptul că o cerere nu poate fi acceptată; nu se păstrează nimic. Site-ul este găzduit de Vercel Inc."],
      browser: ["Stocarea în browser", "Stocarea de sesiune păstrează răspunsurile cu variante predefinite din GPS și din configurator, precum și parametrii de campanie ai vizitei, pe durata acestei sesiuni de browser. Datele de contact, textul liber, textul gravurii și informațiile despre copii nu se păstrează în browser."],
      analyticsOn: ["Analiză", "Cu consimțământul dumneavoastră, Google Analytics 4 măsoară vizitele și evenimentele din formulare, fără date de contact și fără textul cererii. Alegerea dumneavoastră se păstrează în stocarea locală și poate fi schimbată oricând, la „Setări de analiză” din subsolul paginii. Formularele funcționează și fără analiză."],
      analyticsOff: ["Analiză", "Pe acest site nu este activ niciun instrument de analiză."],
      retention: ["Păstrare", "Nu este configurată încă nicio perioadă de ștergere automată. Puteți solicita oricând ștergerea cererii dumneavoastră."],
      children: ["Copii", "Formularele trebuie completate de un adult. Cererile privind jucătorii sub 18 ani se fac de către un părinte sau tutore. Nu transmiteți numele copilului, data nașterii, școala sau informații medicale. Profilurile copiilor nu se publică niciodată."],
      rights: ["Drepturile dumneavoastră", "Pentru a accesa, a corecta sau a șterge cererea dumneavoastră, scrieți la gps@maximus.tennis și indicați ID-ul cererii."],
      controlled: ["Informații controlate", "Documentele confidențiale nu se păstrează pe acest site și nu sunt livrate prin el. Divulgarea controlată are loc sub acord de confidențialitate sau contract, pe canale separate."],
    },
  },
  terms: {
    title: "Termeni de utilizare",
    copyright: "Dreptul de autor asupra acestui site — asupra textelor, fotografiilor, designului și codului său — aparține exclusiv lui Maximus Kiriyakulov. Nu a fost cedat niciunei societăți și niciunei alte persoane.",
    updated: "Versiunea 2026-09-21",
    sections: [
      ["Informare, nu ofertă", "Informațiile despre produse de pe acest site descriu specificații aprobate, arhitectura de configurare și explicații ale programelor. Nu reprezintă o ofertă de vânzare, o listă de prețuri, o declarație de stoc sau un angajament de livrare. Condițiile comerciale se convin separat, în scris, cu entitatea contractantă indicată în fiecare tranzacție."],
      ["Cereri", "O cerere trimisă prin acest site — inclusiv profilurile GPS, cererile de configurație și temele tehnice — se păstrează cu un ID de cerere și este analizată. Nu este o comandă acceptată, un angajament de producție, o programare confirmată, o cerere de aderare sau o candidatură acceptată la vreun program."],
      ["Specificații și dovezi", "Valorile calculate, țintele de producție și specificațiile confirmate sunt distinse pe paginile relevante. Valorile de rigiditate sunt ținte de producție până la publicarea unei alte mențiuni. Nu se garantează niciun rezultat pentru un jucător anume."],
      ["Ecosistem, calitate de membru și drepturi", "Cumpărarea unei rachete nu creează calitatea de membru instituțional, drepturi de investiție, titlu de proprietate intelectuală, dreptul la redevențe sau beneficii de participare. Drepturile decurg din condițiile publicate ale programelor sau dintr-un acord scris."],
      ["Proprietate intelectuală", "MAXIMUS®, emblema cu leu, marca GPS și conținutul acestui site sunt protejate. Formulele interne de inginerie, protocoalele de control al calității, schemele de laminare, matrițele, identitatea furnizorilor, calculația costurilor și metodologia protejată nu se divulgă aici."],
    ],
  },
  lead: {
    submit: "Trimiteți cererea",
    submitting: "Se trimite…",
    retry: "Încercați din nou",
    acceptedEyebrow: "Cerere acceptată",
    acceptedTitle: "Cererea dumneavoastră a fost primită.",
    requestId: "ID-ul cererii",
    acceptedNext: "MAXIMUS analizează fiecare cerere și răspunde în scris la adresa de e-mail pe care ați indicat-o. Păstrați ID-ul cererii pentru orice comunicare ulterioară.",
    duplicate: "Această cerere fusese deja primită; nu s-a creat niciun duplicat.",
    another: "Începeți o cerere nouă",
    errorsTitle: "Verificați aceste câmpuri:",
    failTitle: "Cererea dumneavoastră nu a fost trimisă.",
    fail: {
      offline: "Dispozitivul dumneavoastră nu este conectat la internet.",
      network: "Conexiunea cu serverul a eșuat.",
      timeout: "Serverul nu a răspuns în timp util.",
      rate_limited: "Din această rețea au venit prea multe cereri. Încercați din nou în câteva minute.",
      too_fast: "Formularul a fost trimis foarte repede. Verificați-l și trimiteți-l din nou.",
      spam_suspected: "Cererea a fost oprită de filtrul antispam.",
      unavailable: "În acest moment cererile nu pot fi acceptate.",
      default: "A apărut o eroare neașteptată.",
    },
    keepNote: "Datele introduse rămân pe această pagină, astfel încât puteți încerca din nou.",
    sendByEmail: "Trimiteți această cerere prin e-mail",
    sendByEmailNote: "Aplicația dumneavoastră de e-mail se deschide cu textul acestei cereri. MAXIMUS o primește atunci când trimiteți mesajul.",
    mailConfig: "Configurație",
    mailPage: "Pagină",
    fallback: "Dacă problema persistă, scrieți la {email}. O cerere este considerată trimisă numai atunci când se afișează un ID de cerere.",
    privacyLink: "Notă de confidențialitate",
    hpLabel: "Lăsați acest câmp necompletat",
    consentShort: "Consimțământ",
    after: "După trimitere, pe această pagină se afișează un ID de cerere. Cererile se analizează și primesc răspuns în scris; o cerere nu este o comandă.",
    basis: { unstrung: "Fără cordaj", strung: "Cu cordaj", unknown: "Nu știu — se va stabili în specificație" },
    hints: {
      email: "MAXIMUS răspunde în scris la această adresă.",
      goal: "De exemplu: prima rachetă de competiție sau trecerea de la o rachetă de juniori. Nu includeți nume, date de naștere sau informații medicale despre un copil.",
      currentRacquet: "Marca și modelul, dacă le cunoașteți.",
      message: "Nu includeți parole, date de plată sau informații medicale.",
    },
  },
  choose: {
    eyebrow: "Ajutor în alegere",
    title: "Ajutați-mă să aleg o rachetă",
    lead: "Spuneți-i MAXIMUS nivelul dumneavoastră și ce contează cel mai mult. Răspunsurile sunt analizate și primiți o propunere scrisă: seria, clasa de precizie, greutatea și mânerul.",
    stepsTitle: "Ce urmează",
    steps: [
      ["Răspunsurile dumneavoastră", "Nivelul, prioritățile și mărimea mânerului, dacă o cunoașteți."],
      ["Analiza unui specialist", "MAXIMUS compară răspunsurile dumneavoastră cu matricele seriilor."],
      ["Propunere scrisă", "O configurație propusă și pasul următor, în scris."],
    ],
    formTitle: "Răspunsurile dumneavoastră",
    submit: "Solicitați ajutor în alegere",
    altTitle: "Preferați să decideți singur?",
    altGps: "Profil GPS detaliat",
    altBuild: "Configurați direct",
    note: "Fără potrivire automată și fără pretenții de exactitate: fiecare cerere este analizată de o persoană.",
  },
  consent: {
    title: "Analiză",
    text: "Permiteți MAXIMUS să măsoare vizitele cu Google Analytics? Formularele funcționează în ambele cazuri; către analiză nu se trimit date de contact și nici textul cererilor.",
    allow: "Permiteți analiza",
    decline: "Refuzați",
  },
  media: {
    spotHeadsUp: "Cinci Spot Trainer MAXIMUS unul lângă altul, cu capetele rotunde de contact în sus și mânerele în jos, cu mingi așezate pe capete",
    greatHero: "Seria MAXIMUS GREAT, 363 g: compoziția completă, cu detalii roșii și galbene pe cap, inscripția MAXIMUS lucioasă, autograful Maximus pe tijă și capacul inferior cu leu",
    spotRow: "Cinci Spot Trainer MAXIMUS așezate în rând, cu mingi pe capetele rotunde de contact",
    spotPair: "Două Spot Trainer MAXIMUS în poziție verticală, în fața emblemei cu leu MAXIMUS, cu mingi pe capetele rotunde de contact",
    spinVisual: "MAXIMUS SPIN: capul cu cordaj, inscripția MAXIMUS lucioasă, mânerul și capacul inferior cu leu",
    powerVisual: "MAXIMUS POWER: capul cu cordaj, inscripția MAXIMUS lucioasă, gravura de personalizare, mânerul și capacul inferior cu leu",
    greatVisual: "MAXIMUS GREAT: capul cu cordaj, inscripția MAXIMUS lucioasă, gravura de personalizare, mânerul, capacul inferior cu leu și marcajul seriei G pe gâtul rachetei",
    spinHead: "Capul și planul cordajului MAXIMUS SPIN",
    handleLion: "Gâtul, mânerul și capacul inferior MAXIMUS, cu emblema leului",
    engraving: "Gravură argintie de personalizare pe tijă",
    lettering: "Inscripția MAXIMUS neagră lucioasă pe un cadru negru mat",
    variantAlt: "Seria MAXIMUS {series} — {w} g, balans {b} mm: vizualizare completă, cu banda de specificații, zona de gravură pentru personalizare și marcajul MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistem de patru rachete",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Tijele Sweet Spot Trainer, cu inscripția MAXIMUS",
    sstGrips: "Mânerele și capacele inferioare Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, patru capace inferioare cu emblema leului",
    note: "Vizual de produs",
  },
  notFound: { title: "Pagină inexistentă", p: "Pagina pe care ați solicitat-o nu există în această limbă.", cta: "Mergeți la pagina principală" },
};

export default ro;
