/* Slovak dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const sk = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — celokarbónové tenisové rakety vyvinuté podľa špecifikácie",
    defaultDescription:
      "Celokarbónové tenisové rakety od rámu po rukoväť: GREAT 97 in², POWER 98 in² a SPIN 100 in², osem veľkostí gripu z výroby L0–L7, triedy presnosti pre hmotnosť, vyváženie, swingweight a tuhosť rámu a individuálny vývoj na požiadanie.",
  },
  common: {
    statuses: {
      current: "Aktuálne",
      agreement: "Dostupné po dohode",
      development: "Vo vývoji",
      concept: "Koncept",
      target: "Výrobný cieľ",
      modelled: "Vypočítané",
      confirmed: "Potvrdené",
      requested: "Požadovaná architektúra",
      notprovided: "Neuvedené",
    },
    brief: { who: "Pre koho je to určené", value: "Čo získate", now: "Potvrdené teraz", next: "Ďalší krok" },
    labels: {
      next: "Ďalej",
      back: "Späť",
      edit: "Upraviť odpovede",
      review: "Kontrola",
      start: "Začať",
      restart: "Začať odznova",
      copy: "Kopírovať text žiadosti",
      copied: "Skopírované",
      openEmail: "Otvoriť e-mail na odoslanie tejto žiadosti",
      reference: "Referencia žiadosti",
      weight: "Hmotnosť",
      balance: "Vyváženie",
      swingweight: "Swingweight",
      stiffness: "Tuhosť rámu",
      grip: "Veľkosť gripu",
      headSize: "Veľkosť hlavy",
      series: "Séria",
      precisionClass: "Trieda presnosti",
      quantity: "Množstvo",
      notProvided: "Ešte nezverejnené",
      requestTarget: "Požadovaná cieľová hodnota",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Čítať ďalej",
      allSeries: "Všetky série",
      points: "uvedené hmotnosti",
      optional: "nepovinné",
      required: "povinné",
      select: "Vybrať",
      yes: "Áno",
      no: "Nie",
      unknown: "Neviem",
      custom: "Individuálna cieľová hodnota",
      listed: "Uvedená hmotnosť",
      individual: "Jednotlivá raketa",
      pair: "Zladený pár",
      triple: "Zladená trojica",
      team: "Tímová súprava",
      summaryTitle: "Prehľad vašej žiadosti",
      nextAction: "Ďalšia akcia",
      status: "Stav",
      learn: "Zistiť viac",
      schematic: "Schéma — nie je to meranie",
      photo: "Fotografia",
    },
    ecosystemStrip: "Ekosystém MAXIMUS",
    truth: {
      noPrices: "Ceny, minimálne množstvá, dodacie lehoty, záruky a záväzky k dodaniu sa potvrdzujú písomne pre každý trh a každý program.",
      requestNotOrder: "Žiadosť je žiadosťou o posúdenie. Nie je prijatou objednávkou, výrobným záväzkom ani potvrdeným termínom.",
      noGuarantee: "Žiadna tu opísaná výstroj, metóda ani program negarantuje konkrétnemu hráčovi výsledok.",
      governing: "Táto stránka vychádza vo viacerých jazykoch. Rozhodujúca je anglická verzia; preklad slúži pre lepšiu čitateľnosť.",
    },
  },
  nav: {
    language: "Jazyk",
    groups: { racquets: "Rakety", training: "Tréning", ecosystem: "Ekosystém", partnerships: "Partnerstvá" },
    racquets: "Série rakiet a porovnanie",
    great: "GREAT — 97 in² · Kontrola",
    power: "POWER — 98 in² · Sila",
    spin: "SPIN — 100 in² · Rotácia",
    precision: "Presnosť a tuhosť rámu",
    grip: "Architektúra gripov z výroby L0–L7",
    custom: "Individuálny vývoj",
    training: "Tréningové systémy",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodika",
    gps: "MAXIMUS GPS",
    build: "Konfigurátor",
    choose: "Pomoc s výberom",
    ecosystem: "Mapa ekosystému",
    engineering: "Vývoj a výroba",
    experience: "Vyskúšanie a prispôsobenie",
    brands: "Osobné značky a ambasádori",
    families: "Rodiny a rodičia",
    owners: "Majitelia a trezor majiteľa",
    network: "Sports Network",
    partnerships: "Všetky formy partnerstva",
    coaches: "Tréneri",
    clubs: "Kluby a akadémie",
    distribution: "Distribúcia a rozvoj krajín",
    strategic: "Stratégia a investície",
    institutional: "Inštitucionálne programy",
    contact: "Kontakt",
    legal: "Právna identita",
    privacy: "Ochrana osobných údajov",
    terms: "Podmienky používania",
    menu: "Ponuka",
    close: "Zavrieť",
    home: "Domov",
    skip: "Preskočiť na obsah",
  },
  footer: {
    line: "Raketa MAXIMUS je váš kľúč do sveta MAXIMUS.",
    product: "Produkt",
    ecosystem: "Ekosystém",
    company: "Organizácia",
    instagram: "Instagram",
    email: "E-mail",
    analytics: "Nastavenia analytiky",
    subscribe: {
      title: "Zostaňte s MAXIMUS",
      line: "Nové série, termíny prispôsobenia, tréningové materiály a program pre majiteľov. Niekoľko listov ročne, nič viac.",
      label: "E-mailová adresa",
      placeholder: "your@email.com",
      button: "Prihlásiť sa",
      sending: "Odosielanie",
      done: "Adresa je v zozname. Píšeme len vtedy, keď máme niečo, čo stojí za prečítanie.",
      invalid: "Skontrolujte, prosím, adresu.",
      failed: "Adresa nebola zaregistrovaná. Skúste to, prosím, o chvíľu znova.",
      terms: "Prihlásením sa súhlasíte s tým, aby vám MAXIMUS posielal tieto aktuality a na tento účel uchovával vašu adresu. Každý list obsahuje odkaz na odhlásenie.",
    },
    rights: "MAXIMUS® a emblém leva sú známkami ekosystému MAXIMUS. MIPA — interná kontrola duševného vlastníctva, pôvodu a dokumentov.",
    boundary:
      "Komerčné a zmluvné podmienky sa dohadujú osobitne a písomne. Kúpa rakety nezakladá inštitucionálne členstvo, investičné práva, vlastníctvo duševného majetku ani nárok na licenčné odmeny.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Presnosť začína v momente kontaktu.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer a metodika MAXIMUS spájajú sústredený tréning s celokarbónovými výkonnostnými raketami.",
    heroCta1: "Objavte tréningový systém",
    heroCta2: "Objavte GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrola",
    heroMeta: [
      ["Celokarbónová konštrukcia", "od rámu po rukoväť"],
      ["4 parametre", "hmotnosť · vyváženie · swingweight · tuhosť rámu"],
      ["8 veľkostí gripu", "geometria z výroby L0–L7"],
      ["3 série", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Začnite tu",
      title: "Vyberte si svoju cestu",
      items: {
        player: { h: "Hráč", p: "Nájdite raketu podľa úrovne a priorít alebo si ju priamo nakonfigurujte.", a: "Nájdite svoju raketu" },
        parent: { h: "Rodič", p: "Písomná cesta pre rozvojové ciele, zapojenie trénera a vhodnú výstroj.", a: "Cesta pre rodinu" },
        coach: { h: "Tréner, klub alebo akadémia", p: "Tréningové systémy, prispôsobenie, tímové súpravy a personalizácia.", a: "Cesty pre trénerov a kluby" },
        partner: { h: "Distribútor alebo partner", p: "Distribúcia, rozvoj krajín, strategické a inštitucionálne cesty.", a: "Formy partnerstva" },
      },
    },
    series: {
      eyebrow: "Výkonnostné série",
      title: "Tri výkonnostné architektúry. Jedna vývojová platforma.",
      lead: "Vyberte sériu podľa hráčskeho zamerania a potom dokončite konfiguráciu: trieda presnosti, hmotnosť, grip, personalizácia.",
      cta: "Porovnať série",
      configure: "Konfigurovať",
      open: "Otvoriť sériu",
      photoPending: "Fotografia ešte nie je zverejnená",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Systém presnosti MAXIMUS",
      title: "Hmotnosť. Vyváženie. Swingweight. Tuhosť rámu.",
      sub: "Riadené ako jeden inžiniersky systém.",
      lead: "Tri triedy presnosti určujú, ako presne je každá hotová raketa držaná pri svojej deklarovanej špecifikácii. P0.5 je úzka tolerancia podľa definovaného protokolu merania — nie nulová odchýlka.",
      cta: "Presnosť a tuhosť rámu podrobne",
    },
    stiffness: {
      eyebrow: "Tuhosť rámu",
      title: "Opakovateľná odozva rámu voči deklarovanému cieľu.",
      p: "Tuhosť rámu formuje odozvu, pocit a konzistentnosť medzi raketami. MAXIMUS ju považuje za štvrtý riadený parameter: cieľová hodnota, výsledok merania, povolená tolerancia a schopnosť meracieho prístroja sa vedú ako samostatné záznamy. Prínosom je opakovateľnosť — nie garantovaný výsledok pre každého hráča.",
      cols: [["Odozva", "Ako rám pri kontakte vracia energiu."], ["Pocit", "Čo hráč pri kontakte cíti."], ["Konzistentnosť", "Rakety postavené podľa tej istej špecifikácie reagujú v rámci svojej triedy rovnako."]],
      schematicCaption: "Schéma: povolená odchýlka okolo deklarovanej cieľovej tuhosti pre každú triedu. Nie je to meranie a nevyplýva z nej žiadna hodnota RA.",
      bands: { p25: "tolerancia cieľa ±1 RA", p15: "tolerancia cieľa ±0.5 RA", p05: "zodpovedá deklarovanej cieľovej hodnote RA podľa zavedeného výrobného protokolu merania — nie nulová odchýlka", target: "deklarovaný cieľ (bez uvedenia hodnoty)" },
    },
    carbon: {
      eyebrow: "Konštrukčný štandard",
      title: "Celokarbónová konštrukcia. Od rámu po rukoväť.",
      p: "Všetky súčasné rakety MAXIMUS na tejto platforme sú vo svojej štruktúre celokarbónové, vrátane rukoväte. Na tvarovanie rukoväte sa nepoužíva pena.",
      gripTitle: "Osem veľkostí gripu z výroby. L0–L7.",
      gripP: "Každá veľkosť je geometria karbónovej rukoväte z výroby — nie navrstvená omotávka.",
      scaleCaption: "Schéma: nominálne označenia gripov L0–L7 (4″ až 4⅞″). Nie sú to merané rozmery rukoväte.",
      cta: "Architektúra gripov z výroby",
    },
    custom: {
      eyebrow: "Individuálny vývoj",
      title: "Vyvinuté podľa špecifikácie.",
      sub: "Štandardná ponuka je len východiskový bod.",
      p: "MAXIMUS prijíma technické požiadavky nad rámec zverejnených matíc na posúdenie, vývoj, validáciu a výrobu podľa dohodnutej špecifikácie. Realizovateľnosť sa potvrdzuje písomne.",
      chain: ["Definovať", "Vyvinúť", "Validovať", "Špecifikovať", "Vyrobiť", "Odmerať / zaznamenať"],
      cta: "Odoslať technické zadanie",
      cta2: "Prediskutovať individuálny vývoj",
    },
    training: {
      eyebrow: "Tréningové systémy",
      title: "Tréningový systém postavený na momente kontaktu.",
      p: "Sweet Spot Trainer, metodika MAXIMUS a Spot Trainer spájajú výstroj s tréningom vedeným trénerom: kontakt v strede, kontrola, postupné zaťaženie a prechod späť na výkonnostnú raketu.",
      cta: "Tréningové systémy",
      cta2: "Vyžiadať ukážku",
      photoPending: "Fotografia trenažéra ešte nie je zverejnená",
      sstP: "Tréningová hlava 50 in² na precvičovanie kontaktu v strede, so štyrmi hmotnostnými konfiguráciami pre zaťaženie určené trénerom.",
      sstCta: "Objavte Sweet Spot Trainer",
      sstCaption: "Konfigurácia 300 g, jedna zo štyroch",
      methodP: "Stanovte ciele, vyberte výstroj, trénujte so zapojením trénera, zaznamenávajte pozorovania, prehodnoťte, upravte a preneste prácu do výkonnostnej hry.",
      methodCta: "Objavte metodiku",
      spotP: "Malý okrúhly terč na precvičovanie presného a opakovateľného bodu kontaktu.",
      spotCta: "Objavte Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Výroba a kontrola kvality",
      title: "Postavené podľa špecifikácie. Odmerané a zaznamenané.",
      p: "Výroba sa riadi písomnou špecifikáciou každej objednávky. Záznamy zodpovedajú triede presnosti: uchovávané výrobné záznamy pri P2.5, individuálne záznamy a vysledovateľnosť pri P1.5, individuálna kontrola a dokumentácia pri P0.5 tam, kde ich program danej objednávky uplatňuje.",
      confirmedTitle: "Potvrdené",
      confirmed: ["Celokarbónová konštrukcia od rámu po rukoväť.", "Triedy presnosti P2.5, P1.5 a P0.5 so štyrmi riadenými parametrami.", "Osem veľkostí gripu z výroby L0–L7."],
      pendingTitle: "Ešte nezverejnené",
      pending: "Fotografie meracieho vybavenia, vzorové záznamy kontroly kvality a záznamy z výroby ešte nie sú zverejnené. Nič na tejto stránke nie je meraným certifikátom.",
      captions: { lettering: "Lesklé písmo MAXIMUS na matnom ráme", buttcap: "Grip a koncová krytka s emblémom leva", handle: "Strieborná personalizačná gravúra", finish: "Hlava a výplet" },
      cta: "Vývoj a výroba",
    },
    world: {
      eyebrow: "Svet MAXIMUS",
      title: "Jeden kľúč. Jeden ekosystém. Neobmedzené možnosti.",
      note: "„Neobmedzené možnosti“ je značkové vyjadrenie, nie prísľub neobmedzenej technickej realizovateľnosti, príjmu či prístupu. Kúpa nezakladá licenčné odmeny, investičné výnosy, sponzoring ani financovanie rozvoja hráča.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — a vaša navigácia vo svete tenisu: riadený profil výstroje s písomnou odpoveďou." },
        personal: { h: "Personalizácia", p: "Mená, iniciály, čísla a tímová identifikácia v schválenom striebornom gravírovaní." },
        development: { h: "Rozvoj", p: "Tréningové systémy vedené trénerom, záznamy a prehodnotenie." },
        ecosystem: { h: "Rozšírený ekosystém", p: "Osobné značky, záznamy majiteľov, sieť, licencovanie a inštitucionálne programy — každý so svojím skutočným stavom." },
      },
      cta: "Objavte ekosystém",
    },
    partners: {
      eyebrow: "Formy partnerstva",
      title: "Tréneri, kluby, distribútori a partneri.",
      p: "Najprv písomná kvalifikácia. Práva na krajinu, exkluzivita a komerčné podmienky sa dojednávajú písomne — nikdy sa neudeľujú cez formulár.",
      cta: "Všetky formy partnerstva",
      formTitle: "Krátky dopyt",
      formLead: "Vyberte účel a napíšte MAXIMUS. ID žiadosti dostanete na tejto stránke.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "VAŠA NAVIGÁCIA VO SVETE TENISU" } },
    personal: { eyebrow: "Personalizácia", title: "Vaše meno. Vaše číslo. Váš MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tri série. Skutočné parametre." },
    map: { cta: "Objavte ekosystém" },
  },
  racquets: {
    title: "Rakety",
    lead: "Tri výkonnostné série so spoločným konštrukčným štandardom, spoločným systémom presnosti a spoločnou architektúrou gripov z výroby. Každá séria je ustálená výkonnostná architektúra v rámci širšej vývojovej platformy.",
    direction: { control: "Kontrola", power: "Sila", spin: "Rotácia" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Primárne hráčske zameranie",
    compareTitle: "Porovnanie sérií",
    compareLead: "Iba potvrdené údaje o architektúre. Vzory výpletu, dĺžky, profily rámu, rozsahy napnutia výpletu a nominálne hodnoty swingweight a tuhosti rámu pre tieto série nie sú zverejnené; zaznamenávajú sa ako požadované cieľové hodnoty na technické posúdenie.",
    columns: { series: "Séria", head: "Veľkosť hlavy", direction: "Zameranie", weights: "Uvedené hmotnosti", range: "Rozsah hmotnosti", balance: "Údaje o vyvážení" },
    balanceModelled: "Vypočítané hodnoty",
    balanceNotProvided: "Ešte nezverejnené",
    construction: "Konštrukcia: celokarbónová, od rámu po rukoväť · Presnosť: P2.5 / P1.5 / P0.5 · Gripy: L0–L7",
    otherTitle: "Ďalšie raketové športy",
    otherLead: "Schválené smery vývoja. V týchto kategóriách neexistujú predajné produkty a neprenáša sa na ne žiadna tenisová špecifikácia.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Bedminton", racquetball: "Racquetball", beachTennis: "Plážový tenis" },
    ctaConfigure: "Konfigurovať žiadosť",
    ctaSeries: "Otvoriť sériu",
  },
  seriesPage: {
    eyebrow: "Výkonnostné série",
    intro: {
      great: "Architektúra GREAT s hlavou 97 in² je postavená na kontrole: kompaktná hlava, presný kontakt a istota v smerovaní.",
      power: "Architektúra POWER s hlavou 98 in² je postavená na prenose energie: dĺžka a tempo zo stabilného rámu.",
      spin: "Architektúra SPIN s hlavou 100 in² je postavená na správaní loptičky: rotácia, bezpečná rezerva a tvarovanie letovej dráhy.",
    },
    photoPending: "Fotografia série ešte nie je zverejnená",
    detailPending: "Detailné fotografie konštrukcie a rukoväte pre túto sériu ešte nie sú zverejnené.",
    specsTitle: "Špecifikácia a stav",
    catalogue: {
      eyebrow: "Katalóg série {series}",
      title: "{n} hmotnostných variantov",
      lead: "Každý variant série {series}, zoradený podľa hmotnosti. Hmotnosť v gramoch, vyváženie v milimetroch od konca rukoväte. Každá vizualizácia je zobrazená celá: nič nie je vystrihnuté, zakryté ani roztiahnuté.",
      selectLabel: "Vyberte hmotnostný variant",
      select: "Zobraziť tento variant",
      selected: "Zobrazené vyššie",
      balanceLabel: "Vyváženie",
      headLabel: "Veľkosť hlavy",
      constructionLabel: "Konštrukcia",
      gripsLabel: "Veľkosti gripu z výroby",
      precisionLabel: "Triedy presnosti",
      balanceConfirmed: "Vyváženie je potvrdená hodnota pre túto hmotnosť a zhoduje sa s údajom vytlačeným na vizualizácii. Ceny, dostupnosť a dodacie lehoty sa tu nezverejňujú.",
      balanceModelled: "Vyváženie je vypočítaná hodnota pre túto uvedenú hmotnosť, nie individuálne výrobné meranie; zhoduje sa s údajom vytlačeným na vizualizácii. Ceny, dostupnosť a dodacie lehoty sa tu nezverejňujú.",
      zoom: "Otvoriť obrázok",
      close: "Zavrieť",
      allTitle: "Všetkých {n} variantov",
    },
    specs: { head: "Veľkosť hlavy", direction: "Primárne zameranie", weights: "Uvedené hmotnosti", range: "Rozsah hmotnosti", balance: "Vyváženie", construction: "Konštrukcia", grips: "Gripy z výroby", precision: "Triedy presnosti" },
    construction: "Celokarbónová, od rámu po rukoväť",
    statusTitle: "Stav hodnôt",
    matrixTitle: "Úplná matica hmotností",
    matrixLead: "Uvedené hmotnosti sú štandardný výber. Iné hmotnosti sa dajú vyžiadať ako individuálne cieľové hodnoty; chýbajúce medzihodnoty sa nedopĺňajú.",
    balanceNote: {
      confirmed: "Hodnoty vyváženia sú potvrdené pre každú uvedenú hmotnosť (mm od konca rukoväte) a zhodujú sa s údajom vytlačeným na vizualizácii danej hmotnosti. Nie sú tu vypočítané ani vyhladené medzi susednými hmotnosťami; základ merania sa potvrdzuje v písomnej špecifikácii.",
      modelled: "Hodnoty vyváženia sú pre každú uvedenú hmotnosť vypočítané (mm od konca rukoväte). Nie sú individuálnymi výrobnými meraniami; základ merania sa potvrdzuje v písomnej špecifikácii.",
      notprovided: "Hodnoty vyváženia pre túto sériu nie sú uvedené. Nevyvodzujte ich z inej série.",
    },
    optionsTitle: "Presnosť, grip a hmotnosť",
    notPublished: "Pre túto sériu nie sú zverejnené: vzor výpletu, dĺžka, profil rámu, rozsah napnutia výpletu a hodnoty swingweight a tuhosti rámu. Môžete ich uviesť ako požadované cieľové hodnoty na technické posúdenie.",
    offerTitle: "Čo nasleduje po vašej žiadosti",
    offerSteps: [
      ["Žiadosť", "Odošlite konfiguráciu alebo otázku. ID žiadosti sa zobrazí okamžite."],
      ["Posúdenie", "MAXIMUS posúdi sériu, triedu, hmotnosť, grip a prípadné požadované cieľové hodnoty."],
      ["Písomná odpoveď", "Špecifikácia, dostupnosť a komerčné podmienky sa potvrdzujú písomne."],
    ],
    faqTitle: "Otázky",
    faq: [
      ["Sú hodnoty vyváženia merané?", "Sú vypočítané pre uvedené hmotnosti, nie sú individuálnymi meraniami. Základ merania sa potvrdzuje v písomnej špecifikácii."],
      ["Môžem si vyžiadať hmotnosť, ktorá nie je uvedená?", "Áno, ako individuálnu cieľovú hodnotu v celých gramoch. Prejde technickým posúdením a realizovateľnosť sa potvrdí písomne."],
      ["Čo mení trieda presnosti?", "Ako presne sú hmotnosť, vyváženie, swingweight a tuhosť rámu držané pri deklarovanej špecifikácii a aké záznamy sa vedú."],
      ["Je grip navrstvený omotávkami?", "Nie. L0–L7 sú geometrie karbónovej rukoväte z výroby."],
      ["Kde sú ceny a dodacie lehoty?", "Potvrdzujú sa písomne pre každú žiadosť a tu sa nezverejňujú."],
    ],
    faqSpinBalance: ["Odkiaľ pochádzajú hodnoty vyváženia pre SPIN?", "Z potvrdenej tabuľky série Spin: 33 hmotnostných variantov s vyvážením v milimetroch od konca rukoväte. Každá dvojica sa zhoduje s údajom vytlačeným na schválenej vizualizácii danej hmotnosti. Hodnoty nie sú vypočítané ani vyhladené medzi susednými hmotnosťami."],
    ctaBuild: "Konfigurovať túto sériu",
    ctaAsk: "Opýtať sa na túto sériu",
    ctaCompare: "Porovnať všetky série",
    weightsLabel: "uvedené hmotnosti",
    headLabel: "hlava",
  },
  precision: {
    title: "Presnosť a tuhosť rámu",
    switch: { label: "Vyberte triedu presnosti", panelLabel: "Štyri riadené parametre —", qcLabel: "Architektúra kontroly kvality", protocolNote: "podľa definovaného výrobného protokolu merania kvality", fullTable: "Úplná porovnávacia tabuľka" },
    lead: "Štyri parametre riadené ako jeden inžiniersky systém. Každá trieda určuje, ako presne je hotová raketa držaná pri svojej deklarovanej špecifikácii a aké záznamy o kvalite sa vytvárajú.",
    statement: "Hmotnosť. Vyváženie. Swingweight. Tuhosť rámu. Riadené ako jeden inžiniersky systém.",
    classes: {
      "P2.5": { name: "Škálovateľné výkonnostné jadro", qc: "Individuálne meranie a uchovávané výrobné záznamy." },
      "P1.5": { name: "Rozšírená presnosť", qc: "Individuálne meranie, individuálne záznamy a vysledovateľnosť." },
      "P0.5": { name: "Profesionálna · individuálne kontrolovaná", qc: "Individuálna kontrola s nominálnymi a skutočnými hodnotami a s individuálnymi záznamami o meraní; sériová identita, vysledovateľnosť šarže, certifikát presnosti a zladené súpravy tam, kde ich program danej objednávky uplatňuje." },
    },
    columns: { cls: "Trieda", weight: "Hmotnosť", balance: "Vyváženie", sw: "Swingweight", stiff: "Tuhosť rámu", qc: "Architektúra kontroly kvality" },
    stiffTarget: "tolerancia cieľa",
    stiffExact: "zodpovedá deklarovanej cieľovej hodnote RA podľa zavedeného výrobného protokolu merania",
    programmeNote: "Sériová identita, certifikáty a dokumentácia zladených súprav sa vydávajú iba tam, kde ich program konkrétnej objednávky uplatňuje.",
    targetsNote: "Špecifikácie tuhosti rámu sú výrobnými cieľmi, kým príslušný protokol a výrobné dôkazy nepodporia silnejšie tvrdenie. Ponuka architektúry neznamená, že každá uvedená konfigurácia už prešla úplným uvoľňovacím procesom pre všetky štyri parametre.",
    stiffnessTitle: "Prečo je tuhosť rámu dôležitá",
    stiffnessP1: "Tuhosť rámu ovplyvňuje, ako rám reaguje pri kontakte, aký má pocit pri hre a aké konzistentné sú dve rakety medzi sebou. Hlavným prínosom jej riadenia je opakovateľná odozva voči deklarovanej špecifikácii.",
    stiffnessP2: "Kým sa nezverejní overená zhoda, interný záznam kontroly kvality uvádza merací prístroj, stav jeho kalibrácie, metódu, stav rakety, rozlíšenie, neistotu merania, opakované merania, pravidlo zaokrúhľovania a pravidlo prijatia. Rovnaké zobrazené celé číslo nie je dôkazom nulovej fyzickej odchýlky ani nulovej chyby merania.",
    fields: ["Cieľová hodnota", "Výsledok merania", "Povolená tolerancia", "Schopnosť meracieho prístroja"],
    fieldsNote: "V každom zázname sa vedú ako samostatné polia.",
    matchedTitle: "Zladené súpravy",
    matchedP: "Kritériá zladenej súpravy sú definované osobitne od individuálnej tolerancie. Zhoda každej rakety s jej nominálnou toleranciou sama o sebe nedokazuje konkrétny maximálny rozdiel medzi dvoma raketami. Zladené páry, trojice a tímové súpravy sa vyžiadajú v konfigurátore a potvrdzujú sa písomne.",
    extendedTitle: "Rozšírený technický model",
    extendedP: "Model údajov podporuje ďalšie parametre. Zatiaľ pre ne neexistujú hodnoty ani tolerančné triedy; možno ich uviesť ako požadované cieľové hodnoty v technickom zadaní.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torzné správanie", length: "Dĺžka", beamProfile: "Profil rámu", headGeometry: "Geometria hlavy", stringPattern: "Vzor výpletu", durability: "Trvanlivosť", vibration: "Vibračné charakteristiky" },
    noZero: "MAXIMUS neopisuje svoju ponuku ako ponuku s nulovou toleranciou. Presnosť sa uvádza ako trieda s deklarovanou toleranciou a definovanou architektúrou kontroly kvality.",
    cta: "Konfigurovať s triedou presnosti",
  },
  grip: {
    title: "Architektúra gripov z výroby",
    statement: "Osem veľkostí gripu z výroby. L0–L7.",
    lead: "Geometria gripu je súčasťou architektúry karbónovej rukoväte. Každá veľkosť sa vyrába ako geometria rukoväte, nie navrstvením omotávok.",
    emph: "Rozšírené veľkosti",
    p1: "Osemveľkostná ponuka z výroby dáva trénerom a hráčom širší konfiguračný rozsah, v ktorom možno výstroj špecifikovať okolo hráča, vrátane väčších geometrií L6 a L7.",
    p2: "Nominálne označenie gripu je odlišné od hrubých rozmerov konštrukčnej rukoväte a od záverečného protokolu merania. Veľkosti sa vzťahujú na výkonnostné série a na tréningové rodiny na tejto platforme.",
    p3: "Pre túto ponuku sa neuplatňuje nárok na svetovú exkluzivitu.",
    columns: { size: "Veľkosť", nominal: "Nominálne", family: "Vzťahuje sa na" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurovať s vašou veľkosťou gripu",
  },
  custom: {
    title: "Individuálny vývoj",
    statement: "Vyvinuté podľa špecifikácie.",
    sub: "Štandardná ponuka je len východiskový bod.",
    lead: "MAXIMUS prijíma technické požiadavky nad rámec zverejnených konfiguračných matíc na posúdenie, vývoj, validáciu a výrobu podľa dohodnutej špecifikácie. Realizovateľnosť sa potvrdzuje posúdením — nie každá predstaviteľná požiadavka je fyzicky alebo komerčne realizovateľná.",
    scopeTitle: "Čo môže technické zadanie obsahovať",
    scope: ["Geometria hlavy a rámu", "Dĺžka", "Hmotnosť", "Vyváženie", "Swingweight", "Tuhosť rámu", "Twistweight", "Geometria gripu", "Konštrukcia", "Zladené súpravy", "Tréningové rámy", "Grafika a gravírovanie", "Identita a tímové programy", "Vývoj závislý od výrobných foriem"],
    processTitle: "Postup",
    process: [
      ["Definovať", "Preferované cieľové hodnoty, povinné limity, zamýšľané použitie a akceptovateľné kompromisy."],
      ["Vyvinúť", "Inžinierske posúdenie voči platforme a výrobným formám."],
      ["Validovať", "Validácia voči dohodnutej špecifikácii."],
      ["Špecifikovať", "Písomná špecifikácia so základom merania a s toleranciami."],
      ["Vyrobiť", "Výroba podľa špecifikácie."],
      ["Odmerať / zaznamenať", "Meranie a uchovávané záznamy podľa príslušnej triedy presnosti."],
    ],
    formTitle: "Odoslať technické zadanie",
    formLead: "Odlíšte preferované cieľové hodnoty od povinných limitov. Výsledkom je žiadosť o technické posúdenie, nie automaticky prijatá výrobná objednávka.",
    protected: "Receptúry laminácie, výrobné formy, identita dodávateľov, interná kalkulácia nákladov a chránené know-how sa touto cestou nesprístupňujú.",
    cta: "Odoslať technické zadanie",
  },
  training: {
    title: "Tréningové systémy",
    lead: "Dve tréningové rodiny s vlastnými výrobnými štandardmi, spojené jednou metodikou: tréning vedený trénerom, záznamy, prehodnotenie a prenos späť do výkonnostnej hry.",
    sst: { h: "Sweet Spot Trainer", p: "Tréningová raketa so zmenšenou hlavou 50 in² v systéme štyroch hmotností na precvičovanie kontaktu v strede, vnímania sweet spotu, kontroly rakety a postupného zaťaženia." },
    spot: { h: "Spot Trainer", p: "Tréning bodu kontaktu s malým okrúhlym kontaktným terčom, na schválenom základe štyroch hmotností." },
    method: { h: "Metodika", p: "Stanovte ciele, vyberte výstroj so zapojením trénera, použite príslušný systém, zaznamenávajte, prehodnoťte, upravte a preneste." },
    experience: "Uchopte ju. Švihnite ňou. Pocíťte ju.",
    experienceP: "Vyžiadajte si testovanie, prispôsobenie alebo ukážku s podporou trénera. Odoslaná žiadosť nie je potvrdeným termínom.",
    cta: "Vyžiadať prispôsobenie alebo ukážku",
    distinct: "Sweet Spot Trainer, Spot Trainer a akékoľvek samostatné ukážkové zariadenie sú odlišné produkty a nikdy sa nespájajú.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Samostatná tréningová kategória s vlastným výrobným štandardom. Hlava 50 in² sústreďuje pozornosť na miesto kontaktu; štyri hmotnosti zabezpečujú postupné zaťaženie.",
    baseline: "Potvrdený základ",
    columns: { head: "Hlava", length: "Dĺžka", pattern: "Vzor výpletu", grips: "Gripy z výroby" },
    systemTitle: "Systém štyroch rakiet",
    detailsTitle: "Detaily konštrukcie",
    systemLead: "Hmotnosť a vyváženie v stave dodania. Základ merania sa vedie osobitne a ešte nie je zverejnený.",
    purposeTitle: "Účel",
    purpose: ["Precvičovanie kontaktu v strede", "Vnímanie sweet spotu", "Kontrola rakety", "Postupné zaťaženie", "Rozvoj vedený trénerom", "Prechod späť na výkonnostnú raketu hráča"],
    heavy: "Model 400 g je riadená tréningová konfigurácia. Neodporúča sa automaticky deťom, začiatočníkom ani každému hráčovi; zaťaženie, trvanie a postup určuje tréner.",
    precisionNote: "Výkonnostné triedy presnosti P2.5, P1.5 a P0.5 sa na túto tréningovú rodinu neuplatňujú automaticky. Tolerancie tréningovej výroby sa riadia vlastnou schválenou špecifikáciou tejto rodiny.",
    health: "Neprisľubuje sa prevencia ani liečba tenisového lokťa, odstránenie zranení ani garantované zlepšenie.",
    cta: "Vyžiadať ukážku Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Tréning bodu kontaktu s malým okrúhlym kontaktným terčom. Samostatný produkt s vlastnou vizuálnou identitou, postavený na schválenom základe štyroch hmotností.",
    purposeTitle: "Potvrdený účel",
    purposeP: "Naučiť hráča nájsť a opakovať presný bod kontaktu.",
    weightsTitle: "Postupnosť hmotností",
    weightsP: "Postupnosť hmotností vychádza zo schváleného hmotnostného základu Sweet Spot Trainer. Hodnoty vyváženia a ďalšie špecifikácie Sweet Spot Trainer sa na Spot Trainer neprenášajú.",
    dims: "Presné rozmery terča ešte nie sú zverejnené.",
    grips: "Architektúra gripov z výroby L0–L7.",
    notes: ["Výkonnostné triedy presnosti sa neuplatňujú automaticky.", "Nie je to miniatúrna klasická raketa a nezverejňuje sa žiadny vzor výpletu.", "Spot Trainer, Sweet Spot Trainer a akékoľvek samostatné ukážkové zariadenie zostávajú rozlíšiteľné."],
    cta: "Opýtať sa na Spot Trainer",
  },
  methodology: {
    title: "Metodika a skúsenosť s produktom",
    lead: "Výstroj je len jednou časťou štruktúrovanej rozvojovej cesty. Metóda začína cieľmi hráča, nie označením produktu.",
    stepsTitle: "Rozvojová cesta",
    steps: [
      ["Stanoviť ciele", "Ciele a východiskový bod hráča."],
      ["Vybrať výstroj", "Vhodná výstroj vybraná so zapojením trénera."],
      ["Použiť systém", "Príslušný tréningový systém, vedený trénerom."],
      ["Zaznamenať", "Pozorovania skutočnej účasti, bez vymyslených výsledkov."],
      ["Prehodnotiť", "Porovnateľné kontrolné body."],
      ["Upraviť", "Úpravy konfigurácie alebo programu."],
      ["Preniesť", "Prenos naučeného späť do výkonnostnej hry."],
    ],
    educationTitle: "Vzdelávacie cesty",
    education: { player: "Hráči — porozumenie konfigurácii, zaťaženiu a postupu.", parent: "Rodičia — kontinuita rozvoja, vhodná výstroj, záznamy a práva.", coach: "Tréneri — tréningové systémy, prispôsobenie, hodnotenie a autorizované používanie programov." },
    evidenceTitle: "Disciplína dôkazov",
    evidenceP: "Záznamy o skutočnej účasti a pozorovania sa uchovávajú so svojou klasifikáciou — uvedené účastníkom, potvrdené zákonným zástupcom, overené trénerom alebo merané systémom. Pokrok, výsledky a overenie sa nikdy nevymýšľajú.",
    experienceTitle: "Uchopte ju. Švihnite ňou. Pocíťte ju.",
    experienceP: "Testovanie, prispôsobenie alebo ukážku s podporou trénera si možno vyžiadať. Odoslaná žiadosť nie je potvrdeným termínom.",
    cta: "Vyžiadať prispôsobenie alebo ukážku",
    cta2: "Dopyt na partnerstvo pre trénerov",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — riadený profil výstroje",
    title: "MAXIMUS GPS",
    lead: "Riadený profil výstroje. Odpovedzte len na to, čo je relevantné; skontrolujte a opravte svoje odpovede; dostanete prehľad, konfiguračné smery, ktoré sa uplatňujú, a skutočný ďalší krok.",
    honesty: "V tomto vydaní nie sú schválené žiadne automatické pravidlá prispôsobenia. GPS preto vytvára jasný prehľad požiadaviek a poukazuje na konfiguračné smery; špecifiká výstroje sa posielajú na odborné posúdenie.",
    rulesVersion: "Verzia pravidiel",
    dataVersion: "Verzia produktových údajov",
    steps: { role: "Rola", sport: "Šport", experience: "Skúsenosti", objectives: "Ciele", style: "Hráčsky štýl", equipment: "Súčasná výstroj", preference: "Preferencie", coach: "Zapojenie trénera", ageBand: "Veková kategória", review: "Kontrola" },
    notStored: "Neukladá sa v tomto prehliadači.",
    ageNote: "Používa sa len na nasmerovanie žiadosti. Nevyžaduje sa meno, dátum narodenia ani zdravotné informácie.",
    q: {
      role: "Čo vás najlepšie opisuje?",
      sport: "Ktorý šport?",
      experience: "Úroveň skúseností",
      objectives: "Čo je najdôležitejšie? (vyberte najviac tri)",
      style: "Hráčsky štýl, ak ho poznáte",
      equipment: "Súčasná výstroj, ak nejakú máte",
      equipmentHint: "Značka a model, hmotnosť alebo grip, ak ich poznáte. Nepovinné.",
      preference: "Preferovaná konfigurácia alebo známa veľkosť gripu",
      grip: "Známa veľkosť gripu",
      coach: "Je do vašich rozhodnutí o výstroji zapojený tréner?",
      ageBand: "Veková kategória hráča (používa sa len na správne nasmerovanie žiadosti)",
    },
    roles: { player: "Hráč", parent: "Rodič alebo zákonný zástupca", coach: "Tréner", club: "Klub alebo akadémia", other: "Iné" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Bedminton", other: "Iný raketový šport" },
    sportNote: "Produkty existujú pre tenis. Ostatné športy sú smery vývoja; váš záujem sa zaznamená pre príslušný program.",
    experience: { beginner: "Začiatočník", developing: "Rozvíjajúci sa", intermediate: "Stredne pokročilý", advanced: "Pokročilý", competitive: "Súťažný", professional: "Profesionál" },
    objectives: { control: "Kontrola", power: "Sila", spin: "Rotácia", comfort: "Komfort", manoeuvrability: "Ovládateľnosť", development: "Dlhodobý rozvoj", competition: "Súťaž", training: "Tréningový systém", team: "Tím alebo zladená súprava", personal: "Personalizácia" },
    styles: { baseline: "Zo základnej čiary", allcourt: "Univerzálny", attacking: "Útočný", defensive: "Defenzívny", coach: "Určí tréner", unknown: "Neviem" },
    ageBands: { u10: "Do 10 rokov", u14: "10–13", u18: "14–17", adult: "18 a viac" },
    output: {
      title: "Váš profil výstroje",
      status: "Potrebné odborné posúdenie",
      statusP: "V tomto vydaní sa nevytvára automatické priradenie. Váš profil bol zosumarizovaný na odborné posúdenie.",
      directionsTitle: "Konfiguračné smery, ktoré sa uplatňujú",
      directionsP: "Na základe vašich uvedených cieľov a deklarovaného hráčskeho zamerania každej série. Ide o smer, nie o odporúčanie prispôsobenia.",
      trainingHint: "Vaše ciele zahŕňajú tréningový systém: pozrite si Sweet Spot Trainer a Spot Trainer.",
      teamHint: "Zladené súpravy sa vyžiadajú v konfigurátore a potvrdzujú sa písomne.",
      next1: "Odoslať profil na odborné posúdenie",
      show: "Zobraziť môj profil",
      configure: "Konfigurovať",
      sendP: "Odošlite svoj profil MAXIMUS na odborné posúdenie. ID žiadosti sa zobrazí okamžite; odpoveď prichádza písomne.",
      otherSport: "Rakety MAXIMUS existujú pre tenis. Pre ostatné raketové športy sa nenavrhuje žiadna tenisová séria; váš záujem sa zaznamená ako smer vývoja.",
      noDirection: "Vaše ciele nesmerujú k jednému hráčskemu zameraniu. Konfiguráciu navrhne odborné posúdenie.",
      incomplete: "Chýbajú niektoré povinné odpovede — doplňte ich cez „Upraviť odpovede“.",
    },
    privacy: "GPS nežiada žiadne zdravotné informácie ani identifikátory dieťaťa. V tejto relácii prehliadača sa uchovávajú len odpovede s možnosťou výberu; voľný text sa neukladá.",
  },
  build: {
    title: "Postavte si vlastnú raketu",
    lead: "Nakonfigurujte žiadosť: séria, trieda presnosti, uvedená hmotnosť alebo individuálna cieľová hodnota, veľkosť gripu, požadované cieľové hodnoty, personalizácia, zladené súpravy a množstvo. Výsledkom je konfiguračná žiadosť s ID žiadosti — nie SKU, cena, dátum dodania ani certifikát.",
    steps: { series: "Séria", cls: "Trieda presnosti", weight: "Hmotnosť", grip: "Veľkosť gripu", targets: "Cieľové hodnoty", personal: "Personalizácia", set: "Súprava a množstvo", use: "Použitie", review: "Kontrola" },
    q: {
      series: "Vyberte sériu",
      cls: "Vyberte triedu presnosti",
      weightMode: "Hmotnosť",
      listed: "Uvedená hmotnosť",
      customWeight: "Požadovaná hmotnosť (g)",
      balanceShown: "Vypočítané vyváženie pre túto hmotnosť",
      balanceRequest: "Požadované vyváženie (mm)",
      grip: "Veľkosť gripu z výroby",
      targetsTitle: "Požadované cieľové hodnoty",
      swingweight: "Požadovaný swingweight (kg·cm²)",
      stiffness: "Požadovaná tuhosť rámu (RA)",
      basis: "Základ merania pre požadované hodnoty",
      engraving: "Text gravírovania",
      engravingHint: "Meno, iniciály alebo číslo. Latinské písmená, číslice, medzera, spojovník, apostrof a bodka; najviac 24 znakov. Iné písmá sa prijímajú na potvrdenie grafiky.",
      engravingType: "Personalizácia",
      types: { none: "Žiadna", name: "Meno hráča", initials: "Iniciály", number: "Číslo súpravy", academy: "Identifikácia trénera alebo akadémie", team: "Tímový program" },
      set: "Jednotlivá raketa alebo zladená súprava",
      use: "Zamýšľané použitie",
      uses: { play: "Osobná hra", competition: "Súťaž", coaching: "Trénovanie", team: "Tím alebo akadémia", retail: "Posúdenie pre predaj alebo distribúciu", other: "Iné" },
      notes: "Ďalšie technické požiadavky",
    },
    classes: { "P2.5": "P2.5 — škálovateľné výkonnostné jadro", "P1.5": "P1.5 — rozšírená presnosť", "P0.5": "P0.5 — profesionálna, individuálne kontrolovaná" },
    stiffExactShort: "tuhosť rámu zodpovedá deklarovanej cieľovej hodnote RA podľa zavedeného výrobného protokolu",
    clsNote: "Každá trieda riadi štyri parametre. P0.5 je úzka tolerancia podľa definovaného protokolu merania — nie nulová odchýlka. Sériová identita, certifikáty a dokumentácia zladených súprav sa uplatňujú iba tam, kde ich program vašej objednávky zavádza.",
    listedNote: "Z potvrdenej matice série.",
    customNote: "Hmotnosť mimo matice, posúdená technicky.",
    balanceCaption: "Každá uvedená hmotnosť zobrazuje svoje vypočítané vyváženie v mm od konca rukoväte. Vypočítané hodnoty nie sú individuálnymi meraniami.",
    spinNote: "Hmotnosti SPIN tvoria požadovanú hmotnostnú architektúru. Vyváženie, swingweight a tuhosť rámu pre SPIN nie sú uvedené; určujú sa pri technickom posúdení.",
    customHint: "Celé gramy, iba číslice. Individuálna hmotnosť je žiadosťou o technické posúdenie; realizovateľnosť sa potvrdzuje písomne a žiadna hodnota sa nezaokrúhľuje.",
    gripNote: "geometria karbónovej rukoväte z výroby, nie navrstvená omotávka",
    targetsLead: "Nepovinné. Zadajte len hodnoty, ktoré potrebujete. Každá sa zaznamená ako požadovaná cieľová hodnota na technické posúdenie, nie ako zverejnená špecifikácia.",
    basisHint: "Povinné, keď žiadate individuálnu hmotnosť alebo akúkoľvek cieľovú hodnotu: vzťahujú sa hodnoty na raketu bez výpletu alebo s výpletom?",
    inputRange: "Prijímaný vstup: {min}–{max}.",
    inputRangeNote: "Vstupné rozsahy len odfiltrujú nemožné zadania. Neopisujú výrobné možnosti.",
    listedBasis: "uvedené hodnoty — základ merania potvrdený v písomnej špecifikácii",
    notStored: "Neukladá sa v tomto prehliadači; po znovunačítaní stránky ho zadajte znova.",
    artworkReview: "vyžaduje sa potvrdenie grafiky",
    previewNote: "Nezobrazuje sa vizuálna ukážka: schválená šablóna gravírovania pre tento model ešte nie je zverejnená. Váš text sa zbiera na potvrdenie grafiky.",
    teamSub: "4–99 rakiet na súpravu",
    setsLabel: { individual: "Počet rakiet", pair: "Počet zladených párov", triple: "Počet zladených trojíc", team: "Počet tímových súprav" },
    teamSizeLabel: "Rakiet v tímovej súprave",
    totalLabel: "Celkovo rakiet",
    racquetsUnit: "rakiet",
    setRule: "Množstvo sa počíta v súpravách: zladený pár sú 2 rakety na súpravu, zladená trojica 3.",
    restart: "Začať novú konfiguráciu",
    notices: { weightCleared: "{w} g nie je v matici {series}, preto sa hmotnosť vymazala. Vyberte uvedenú hmotnosť alebo si vyžiadajte individuálnu cieľovú hodnotu." },
    reviewTitle: "Konfiguračná žiadosť",
    reviewP: "Skontrolujte konfiguráciu a potom doplňte svoje kontaktné údaje. Žiadosť sa uloží s ID žiadosti a odpovie sa na ňu písomne; dostupnosť a komerčné podmienky sa potvrdzujú písomne.",
    reviewErrors: "Niektoré odpovede v konfigurácii potrebujú pozornosť:",
    edit: "Upraviť",
    fieldNames: { series: "Séria", cls: "Trieda presnosti", mode: "Výber hmotnosti", weight: "Uvedená hmotnosť", customWeight: "Požadovaná hmotnosť", basis: "Základ merania", balanceReq: "Požadované vyváženie", sw: "Požadovaný swingweight", ra: "Požadovaná tuhosť rámu", grip: "Veľkosť gripu", ptype: "Personalizácia", engraving: "Text gravírovania", setType: "Typ súpravy", sets: "Množstvo", teamSize: "Rakiet v tímovej súprave", use: "Zamýšľané použitie", notes: "Ďalšie požiadavky" },
    status: { listed: "uvedená hmotnosť", requestedArchitecture: "požadovaná hmotnostná architektúra", technicalReview: "žiadosť o technické posúdenie", notPublished: "neuvedené", requestedCondition: "požadovaný stav" },
    chooseLink: "Neviete, ktorá séria vám sedí? Pomôžeme vám s výberom",
    cta: "Odoslať konfiguračnú žiadosť",
  },
  experience: {
    title: "Vyskúšanie a prispôsobenie",
    statement: "Uchopte ju. Švihnite ňou. Pocíťte ju.",
    lead: "Vyžiadajte si testovanie, prispôsobenie alebo ukážku s podporou trénera. Žiadosti sa posudzujú a odpovedá sa na ne písomne; odoslaná žiadosť nie je potvrdeným termínom.",
    optionsTitle: "Čo si možno vyžiadať",
    options: ["Testovanie rakety", "Individuálne prispôsobenie rakety", "Ukážka s podporou trénera", "Ukážka Sweet Spot Trainer alebo Spot Trainer", "Ukážkový deň pre tím alebo akadémiu"],
    formTitle: "Žiadosť o prispôsobenie alebo ukážku",
  },
  engineering: {
    title: "Vývoj a výroba",
    statement: "Lietadlá. Jachty. Rakety.",
    lead: "Jedna inžinierska filozofia v troch prostrediach: princípy, ktoré formujú lietadlo, presnosť, ktorá vedie jachtu otvoreným morom, výkon, ktorý definuje každú raketu MAXIMUS. Inžinierske vyjadrenie — nie tvrdenie o letovej certifikácii, vlastníctve jachty, vlastníctve výrobného závodu ani o priamom prenose materiálov.",
    manifesto: ["Veríme, že skvelé inžinierstvo nemá hranice.", "Jedna filozofia. Vyvinuté bez kompromisov."],
    capabilityTitle: "Výrobné možnosti",
    capabilityLead: "Možnosti sú ukázané ako postupnosť, nie ako slogan.",
    sequence: [
      ["Špecifikácia", "Séria, trieda presnosti, hmotnosť, vyváženie, swingweight, cieľová tuhosť rámu, geometria gripu, personalizácia."],
      ["Výroba", "Celokarbónová konštrukcia od rámu po rukoväť, vyrobená podľa špecifikácie."],
      ["Kontrola kvality", "Meranie a záznamy podľa triedy presnosti: výrobné záznamy, individuálne záznamy a vysledovateľnosť, individuálna certifikácia."],
      ["Opakovaná výroba", "Opakovateľná odozva voči deklarovanej špecifikácii vo všetkých výrobných šaržiach."],
      ["Vysledovateľnosť", "Sériová identita, vysledovateľnosť šarže a certifikát presnosti tam, kde ho trieda poskytuje."],
    ],
    capacityNote: "Výrobná kapacita, dodacie lehoty, minimálne množstvá a harmonogramy dodania sa potvrdzujú písomne pre každý program voči potvrdeným objednávkam a dohodnutému harmonogramu uvoľňovania.",
    truth: "Kapacita nie je výstup, zásoby, garantovaný dátum dodania ani vlastníctvo výrobného zariadenia.",
    cta: "Distribúcia a rozvoj krajín",
    cta2: "Odoslať technické zadanie",
  },
  ecosystem: {
    title: "Ekosystém MAXIMUS",
    lead: "Jeden kľúč. Toto odomyká. Každý uzol má vysvetlenie, presný stav a relevantný ďalší krok.",
    words: ["Inžinierstvo", "Výkon", "Inovácia", "Komunita", "Príležitosť", "Zmysel"],
    nodes: {
      engineering: { h: "Vývoj a výroba rakiet", p: "Celokarbónové rakety vyvinuté podľa špecifikácie, vyrobené so záznamami o kvalite a s vysledovateľnosťou.", a: "Vývoj a výroba" },
      precision: { h: "Presnosť a individuálna konfigurácia", p: "Štyri parametre, tri triedy presnosti, osem veľkostí gripu a individuálny vývoj.", a: "Presnosť a tuhosť rámu" },
      training: { h: "Tréning a metodika", p: "Sweet Spot Trainer, Spot Trainer a štruktúrovaná rozvojová cesta.", a: "Tréningové systémy" },
      development: { h: "Rozvoj hráčov a trénerov", p: "Výber vedený trénerom, záznamy, prehodnotenie a vzdelávacie cesty.", a: "Metodika" },
      identity: { h: "Osobná identita a osobné značky", p: "Od gravírovania po osobnú alebo profesionálnu značku riadenú právami.", a: "Osobné značky" },
      owners: { h: "Záznamy majiteľov, znalosti a práva", p: "Navrhovaný trezor majiteľa s riadeným prístupom pre záznamy o výstroji, rozvoji a právach.", a: "Majitelia a trezor" },
      mipa: { h: "MIPA — pôvod a interná kontrola", p: "Interná vrstva kontroly duševného vlastníctva, pôvodu a dokumentov.", a: "Právna identita a kontrola" },
      digital: { h: "Digitálna infraštruktúra a smer Blockchain 5.0", p: "Pôvod, vysledovateľné záznamy, dôkazy s riadeným prístupom a identita produktu ako deklarovaný technologický smer.", a: "Technologický smer" },
      licensing: { h: "Zmluvné licencovanie a programy licenčných odmien", p: "Licencované značky, produkty a balíky práv s podmienkami určenými v každej zmluve.", a: "Licenčné cesty" },
      families: { h: "Účasť rodiny a výhody programu", p: "Informované rozhodnutia, kontinuita, uchované záznamy a výhody určené programom.", a: "Rodiny a rodičia" },
      network: { h: "MAXIMUS Sports Network", p: "Hráči, tréneri, kluby, akadémie, poskytovatelia služieb, operátori a regionálni partneri.", a: "Sports Network" },
      market: { h: "Kluby, akadémie, distribúcia a rozvoj krajín", p: "Tímové programy, predaj, distribúcia a rozvoj území prostredníctvom písomnej kvalifikácie.", a: "Formy partnerstva" },
      institutional: { h: "Inštitucionálne programy, vzdelávanie, inovácie a sociálny dopad", p: "Inštitucionálna vrstva zabezpečovaná organizáciou MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, kde program túto rolu zakladá.", a: "Inštitucionálne programy" },
      extensions: { h: "Budúce rozšírenia na raketové športy a odevy MAXIMUS", p: "Padel, pickleball, squash, bedminton, racquetball, plážový tenis a odevy ako smery vývoja.", a: "Raketové športy" },
    },
    boundaryTitle: "Hranice",
    boundary: [
      "Kúpa rakety nezakladá inštitucionálne členstvo, práva v riadení, licenčné odmeny ani investičné práva.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) je inštitucionálnym operátorom iba tam, kde túto rolu zakladá program; predaj výstroje uvádza svoj skutočný zmluvný subjekt.",
      "Granty, status neziskovej organizácie, daňový režim a regulačné povolenia sa neuplatňujú automaticky vo všetkých krajinách.",
    ],
    techTitle: "Technologický smer",
    techP: "Blockchain 5.0 je deklarovaný technologický smer MAXIMUS. Jeho funkčnými účelmi sú pôvod, vysledovateľné záznamy, dôkazy s riadeným prístupom, identita produktu a odsúhlasenie kvalifikujúcich komerčných udalostí. Neuvádza sa žiadny konsenzuálny mechanizmus, transakčná kapacita, sieť uzlov, adresa inteligentnej zmluvy, token ani nezávislá certifikácia a netvrdí sa žiadne nasadené riešenie. Osobné údaje, záznamy o deťoch a dôverné zmluvy sa nikdy štandardne neukladajú do verejného nemenného systému.",
  },
  brands: {
    title: "Osobné značky a ambasádori",
    statement: "Od hráča k značke. Od trénera k značke.",
    lead: "Samostatná cesta osobnej značky. Zapojenie MAXIMUS zahŕňa rozvoj značky a dohodnutú propagáciu — nie len meno na rakete.",
    progressionTitle: "Zamýšľaný postup",
    progression: [
      ["Overená identita", "Overená identita a história rozvoja."],
      ["Osobitná značka", "Osobitná osobná alebo profesionálna značka."],
      ["Obsah s vyriešenými právami", "Obsah s vyriešenými právami a schválená identita produktu."],
      ["Vývoj a kolekcie", "Vývoj a tvorba kolekcií tam, kde je to dohodnuté."],
      ["Propagácia", "Propagácia prostredníctvom dohodnutých kanálov a partnerstiev MAXIMUS."],
      ["Účasť", "Zmluvná účasť na kvalifikujúcich predajoch alebo na licencovaní."],
      ["Reportovanie", "Transparentné reportovanie podľa zmluvy."],
    ],
    royaltiesTitle: "Licenčné odmeny a licencovanie",
    royalties: [
      "Licenčné odmeny sa vzťahujú na definovanú licencovanú značku, produkt, transakciu alebo balík práv.",
      "„Celosvetové predaje“ znamenajú kvalifikujúce predaje v rozsahu zmluvy — nikdy každú nesúvisiacu raketu MAXIMUS.",
      "Sadzby, základ výpočtu, územia, trvanie, vratky, odpočty, reportovanie, vyrovnanie a overovanie sa určujú v príslušnej zmluve. Žiadne štandardné percento licenčnej odmeny sa nezverejňuje.",
      "Bez dohodnutého rozsahu sa neprisľubuje žiadna globálna kampaň, mediálny rozpočet, výsledok sponzoringu ani komerčný úspech.",
    ],
    cta: "Odoslať dopyt na spoluprácu na značke",
    cta2: "Dopyt na partnerstvo pre trénerov",
  },
  families: {
    title: "Rodiny a rodičia",
    lead: "Informované rozhodnutia o výstroji, kontinuita rozvoja, uchované znalosti a práva, prehľad o účasti a výhody určené programom, ktoré môžu podporiť budúcu činnosť.",
    nowTitle: "Dostupné teraz",
    now: ["Rodinné a rozvojové dopyty písomne.", "Výber výstroje so zapojením trénera, žiadosti o prispôsobenie a ukážku.", "Súkromné záznamy: profily detí sa nikdy nezverejňujú a štandardne sa nikdy komerčne nevyužívajú.", "Vzdelávacia cesta pre rodičov: konfigurácia, zaťaženie, postup, záznamy a práva."],
    plannedTitle: "Plánované",
    planned: ["Výhody z účasti určené programom, použiteľné na tovar a služby v rámci ekosystému, a nie ako peňažný úrok.", "Záznamy majiteľa a rodiny v navrhovanom trezore majiteľa s povoleniami zákonného zástupcu a s prechodom kontroly vo veku 18 rokov."],
    categoriesTitle: "Vedené oddelene",
    categories: ["Zmluvné licenčné odmeny vyplývajúce z licencovaných práv alebo z kvalifikujúcich predajov", "Výhody z účasti určené programom", "Kredity na nákup alebo na služby", "Predplatby", "Inštitucionálne členstvo"],
    categoriesP: "Tieto kategórie sa nikdy nepovažujú za vzájomne zameniteľné.",
    statusTitle: "Skutočný stav rodinného programu",
    journeyTitle: "Cesta pre rodinu",
    journey: [
      ["Cieľ", "Čo chce hráč dosiahnuť ako ďalšie."],
      ["Súčasná úroveň", "Kde sa hráč nachádza dnes."],
      ["Tréner", "Či sa tréner zúčastňuje na rozhodnutiach o výstroji."],
      ["Výstroj", "Vhodná výstroj pre danú fázu, vrátane tréningových systémov tam, kde je to relevantné."],
      ["Dohodnutý tréning", "Používanie vedené trénerom dohodnuté vopred."],
      ["Kontrola", "Prehodnotenie v porovnateľných kontrolných bodoch."],
    ],
    brief: {
      who: "Rodičia a zákonní zástupcovia hráčov v každej fáze.",
      value: "Písomná odpoveď o vhodnej výstroji, zapojení trénera a o ďalšom kroku v rozvoji.",
      now: "Rodinné dopyty písomne; výber so zapojením trénera; súkromné záznamy — profily detí sa nikdy nezverejňujú.",
      next: "Odošlite rodinný dopyt nižšie. ID žiadosti dostanete okamžite.",
    },
    formTitle: "Rodinný dopyt",
    formNote: "Vypĺňa rodič alebo zákonný zástupca. Neuvádzajte meno dieťaťa, dátum narodenia, školu ani zdravotné informácie.",
    noPromise: "Kúpa neprisľubuje licenčné odmeny, investičné výnosy, sponzoring ani financovanie rozvoja dieťaťa.",
    statusP: "Toto vydanie vysvetľuje model a prijíma dopyty na program. Pripisovanie, platby a uplatnenie nie sú dostupné, kým sa písomne nedefinujú kvalifikujúce udalosti, prijímatelia, zdroj financovania, základ výpočtu, povolené použitia, účtovný režim, vratky, storná, expirácia, prenosnosť, ukončenie programu a riešenie sporov. Neprisľubuje sa, že zostatok nikdy neklesne, žiadna účasť neuhradí celý tréning a nevyplýva z nej žiadna ochrana kapitálu.",
    cta: "Odoslať rodinný alebo rozvojový dopyt",
  },
  owners: {
    title: "Majitelia a trezor majiteľa",
    lead: "Trezor majiteľa je navrhovaný záznam s riadeným prístupom o výstroji, rozvoji, znalostiach, obsahu a o zdokumentovaných právach. Prezentuje sa ako súčasť plánovanej architektúry pre majiteľov: nezobrazujú sa žiadne živé účty, zostatky, certifikáty ani úspechy.",
    nowTitle: "Pre súčasných majiteľov teraz",
    now: ["Dopyty majiteľov: produktová alebo sériová referencia, nastavenie, servis a žiadosti o záznamy písomne.", "Certifikát presnosti a dokumentácia zladenej súpravy tam, kde ich trieda presnosti poskytuje, doručené s produktom."],
    archTitle: "Plánovaná architektúra trezora",
    arch: ["Identita produktu a sériové referencie", "Konfigurácia a príslušné certifikáty kontroly kvality", "História servisu a nastavenia", "Záznamy o rozvoji hráča alebo trénera", "Kvalifikácie a overené úspechy", "Médiá s vyriešenými právami a autorské materiály", "Licencie, povolenia a zmluvné referencie", "Záznamy programu osobnej značky", "Príslušné výkazy licenčných odmien alebo výhody z účasti"],
    separationTitle: "Čo znamená vlastníctvo",
    separation: [
      "Vlastníctvo fyzickej rakety je oddelené od vlastníctva autorského práva, licencie, zmluvného nároku alebo záznamu, ktorý ich opisuje.",
      "Uložený dokument alebo záznam v blockchaine nie je automaticky dôkazom, že právo existuje alebo že bolo prevedené.",
      "Dôkaz si uchováva svoju klasifikáciu: uvedené účastníkom, potvrdené zákonným zástupcom, overené trénerom, merané systémom.",
      "Pre neplnoletých: súkromné záznamy, povolenia zákonného zástupcu, žiadne zverejnené profily detí a štandardne žiadne komerčné využitie identity.",
      "Export, oprava, riadenie prístupu a primeraný prechod kontroly sú súčasťou návrhu.",
    ],
    techTitle: "Blockchain 5.0 a MxSN",
    techP: "Blockchain 5.0 je deklarovaný technologický smer; MxSN definuje koncepty siete s riadeným prístupom pre súhlas, doručenie, dôkazy, práva a reportovanie. Prevádzková implementácia sa neuvádza. Model údajov aplikácie je postavený tak, aby sa neskôr integroval prostredníctvom zdokumentovaného rozhrania, bez predstierania, že spojenie dnes existuje.",
    cta: "Dopyt majiteľa",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Spojenie medzi hráčmi, trénermi, klubmi, akadémiami, poskytovateľmi služieb, operátormi programov a regionálnymi partnermi.",
    functionsTitle: "Možné funkcie",
    functions: ["Vyhľadávanie", "Sprostredkovanie kontaktov", "Rozvojové programy", "Podpora s výstrojou", "Podujatia", "Prístup k službám", "Partnerské príležitosti"],
    statusTitle: "Skutočný stav",
    statusP: "Verejný zoznam sa ešte nezverejňuje: uvedení budú iba účastníci, u ktorých je zistená identita, vzťah a povolenie na uvedenie. Návrh poslaný klubu nie je partnerstvom a potenciálny distribútor nie je vymenovaným distribútorom. Zverejnenie zoznamu, rezervácie, správy a komerčné transakcie sú riadené osobitne a nie sú v prevádzke.",
    cta: "Prihlásiť sa do siete",
  },
  partnerships: {
    title: "Formy partnerstva",
    lead: "Najprv písomná kvalifikácia. Každá cesta vedie k dopytu podľa roly; komerčné podmienky nasledujú písomne.",
    commercialTitle: "Možné komerčné činnosti platformy",
    commercial: ["Výstroj", "Individuálny vývoj", "Personalizácia", "Tímové a akademické programy", "Tréningové systémy", "Zmluvné licencovanie", "Distribúcia", "Schválené služby", "Budúce produktové kategórie"],
    boundary: "Práva na krajinu, exkluzivita, poplatky za územie a marže distribútorov sú dojednávané podmienky. Nezverejňujú sa žiadne výnosy, prognózy, ocenenia, podiely na trhu, návratnosť, záväzky k financovaniu ani nemenované partnerstvá.",
    routes: {
      coaches: {
        title: "Tréneri",
        lead: "Tréningové systémy, prispôsobenie, profesionálna identita, autorizované programy, príležitosti pre osobnú značku a dodávky výstroje.",
        points: ["Sweet Spot Trainer a Spot Trainer v tréningu vedenom trénerom.", "Prispôsobenie s konfiguračnými maticami a ôsmimi veľkosťami gripu z výroby.", "Coach-to-Brand: overený profesionálny profil a podznačka riadená právami.", "Autorizované používanie programu vychádza z písomnej zmluvy."],
        cta: "Odoslať dopyt na partnerstvo pre trénerov",
        brief: {
          who: "Nezávislí tréneri a trénerské tímy.",
          value: "Tréningové systémy pre tréning vedený trénerom, prispôsobenie s maticami sérií a s ôsmimi gripmi z výroby a cesta k profesionálnej identite.",
          now: "Dopyty trénerov písomne. Nezverejňuje sa ani nevyplýva žiadna provízia, zárobok ani sadzba za odporúčanie.",
          next: "Odošlite dopyt pre trénerov nižšie. Podmienky nasledujú písomne.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Kluby a akadémie",
        lead: "Tímová výstroj, tréningové systémy, personalizácia, rozvojové programy, servis a účasť v sieti.",
        points: ["Tímové a zladené súpravy vyžiadané v konfigurátore.", "Tréningové systémy a metodika pre štruktúrovaný rozvoj.", "Personalizácia pre tímové programy v schválených zónach.", "Ukážkové dni, stretnutia na prispôsobenie rakiet a účasť v sieti."],
        cta: "Odoslať zadanie klubu alebo akadémie",
        brief: {
          who: "Kluby, akadémie a tímové programy.",
          value: "Tímové a zladené súpravy, tréningové systémy, personalizácia pre tímové programy a ukážkové dni.",
          now: "Zadania klubov a akadémií písomne; tímové súpravy sa vyžiadajú v konfigurátore.",
          next: "Odošlite zadanie klubu alebo akadémie nižšie.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribúcia a rozvoj krajín",
        lead: "Sortiment, koordinácia výroby, technické možnosti, rozvoj území a dôverná komerčná kvalifikácia.",
        points: ["Písomná kvalifikácia protistrany, územia a kanála.", "Sortiment definovaný z konfiguračných matíc a tried presnosti.", "Územie, exkluzivita, objemy, ceny a komerčná ochrana sú dojednávané podmienky dohodnuté písomne.", "Zmluvný subjekt, platobné podmienky a dodacia podmienka sa určujú pre každú transakciu."],
        cta: "Odoslať dopyt na distribúciu alebo rozvoj krajiny",
        brief: {
          who: "Predajcovia, distribútori a partneri pre krajiny.",
          value: "Sortiment definovaný z potvrdených matíc, tried presnosti a rozsahu gripov, s písomnou kvalifikáciou územia a kanála.",
          now: "Dopyty na distribúciu písomne. Územie, exkluzivita, objemy a ceny sa dojednávajú — nič sa neudeľuje cez formulár.",
          next: "Odošlite dopyt na distribúciu nižšie.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Stratégia a investície",
        lead: "Inžinierske možnosti, hĺbka konfigurácie, výrobný model, cesty na trh, duševné vlastníctvo, služby a príležitosti na expanziu.",
        points: ["Kvalifikovaná strategická diskusia alebo riadený prístup k informáciám nasleduje po písomnej kvalifikácii.", "Verejné informácie sú obmedzené na schválené špecifikácie produktov, konfiguračnú architektúru, overené možnosti a vysvetlenia programov.", "Ekonomika špecifická pre kupujúceho, kalkulácia nákladov, chránená metodika a nezverejnené zmluvy sa sprístupňujú iba na základe NDA alebo zmluvy."],
        cta: "Vyžiadať kvalifikovanú strategickú diskusiu",
        brief: {
          who: "Investori a strategickí partneri.",
          value: "Kvalifikovaná diskusia o inžinierskych možnostiach, hĺbke konfigurácie, výrobnom modeli, cestách na trh a o duševnom vlastníctve.",
          now: "Nezverejňujú sa žiadne finančné údaje, prognózy, ocenenia ani návratnosť. Riadené informácie nasledujú po písomnej kvalifikácii a po NDA.",
          next: "Vyžiadajte si kvalifikovanú strategickú diskusiu nižšie.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Inštitucionálne programy",
        lead: "Vzdelávanie, prístup, inovácie, dôkazy o rozvoji, sociálny dopad a primerane štruktúrované programy.",
        points: ["Inštitucionálne programy sú štruktúrované prostredníctvom MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, kde program túto rolu zakladá.", "Vyhradené programové prostriedky a komerčné transakcie zostávajú oddelené.", "Dopyt nie je prijatou žiadosťou o členstvo a kupujúci výstroje nie je inštitucionálnym členom.", "Granty, status neziskovej organizácie, daňový režim a regulačné povolenia sú špecifické pre každú krajinu a nikdy sa nepredpokladajú."],
        cta: "Odoslať dopyt na inštitucionálny program",
        brief: {
          who: "Inštitúcie, vzdelávacie a rozvojové programy.",
          value: "Programy pre vzdelávanie, prístup, inovácie a dôkazy o rozvoji, štruktúrované s primeraným operátorom.",
          now: "Inštitucionálne dopyty písomne. Dopyt nie je žiadosťou o členstvo; kúpa výstroje nie je inštitucionálnym členstvom.",
          next: "Odošlite inštitucionálny dopyt nižšie.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Verejné a riadené sprístupňovanie",
    disclosure: {
      public: { h: "Verejné", p: "Schválené špecifikácie produktov, konštrukcia, konfiguračná architektúra, tréningové účely, overené možnosti, vysvetlenia programov a formy partnerstva." },
      qualified: { h: "Kvalifikovaný dopyt", p: "Technické požiadavky, množstvá, záujem o územie, rozsah rozvoja a relevantné komerčné diskusie." },
      controlled: { h: "Riadené NDA alebo zmluvou", p: "Interné receptúry, podrobné protokoly kontroly kvality, laminácie, výrobné formy, výrobné metódy, identita dodávateľov, kalkulácia nákladov, ekonomika špecifická pre kupujúceho, chránená metodika, nezverejnené zmluvy a citlivé záznamy o právach." },
    },
  },
  contact: {
    title: "Kontakt a žiadosti",
    lead: "Vyberte účel svojej žiadosti. Každý formulár zbiera len to, čo je potrebné na jej nasmerovanie a vyhodnotenie. Na žiadosti sa odpovedá písomne.",
    email: "E-mail",
    instagram: "Instagram",
    legalLink: "Právna identita",
  },
  form: {
    purposeLabel: "Účel žiadosti",
    purposes: {
      selection: "Pomoc s výberom rakety",
      product: "Dopyt na produkt",
      fitting: "Prispôsobenie alebo ukážka",
      technical: "Technické zadanie",
      config: "Konfiguračná žiadosť",
      gps: "Profil výstroje GPS",
      coach: "Partnerstvo pre trénerov",
      club: "Zadanie klubu alebo akadémie",
      distribution: "Distribúcia alebo rozvoj krajiny",
      brand: "Spolupráca na značke alebo ambasádorstvo",
      family: "Rodinný alebo rozvojový dopyt",
      institutional: "Inštitucionálny program",
      strategic: "Strategická alebo investičná diskusia",
      owner: "Dopyt majiteľa",
      network: "Prihláška do Sports Network",
      general: "Všeobecný dopyt",
    },
    fields: {
      name: "Meno",
      email: "E-mail",
      role: "Vaša rola",
      country: "Krajina alebo región",
      organisation: "Organizácia",
      message: "Vaša správa",
      level: "Súčasná úroveň",
      objectives: "Čo je najdôležitejšie (najviac tri)",
      currentRacquet: "Súčasná raketa",
      grip: "Veľkosť gripu, ak ju poznáte",
      seriesInterest: "Séria, ktorá vás zaujíma",
      quantity: "Množstvo",
      city: "Mesto alebo miesto stretnutia",
      coachInvolved: "Je zapojený tréner?",
      timing: "Preferovaný termín",
      targets: "Preferované cieľové hodnoty",
      limits: "Povinné limity",
      use: "Zamýšľané použitie",
      tradeoffs: "Akceptovateľné kompromisy",
      basis: "Základ merania",
      players: "Počet hráčov",
      interests: "Oblasti záujmu",
      territory: "Územie, ktoré vás zaujíma",
      channels: "Existujúce kanály a skúsenosti",
      audience: "Publikum alebo disciplína",
      proposal: "Navrhovaná spolupráca",
      goal: "Rozvojový cieľ",
      ageBand: "Veková kategória hráča",
      scope: "Rozsah programu",
      interestArea: "Oblasť záujmu",
      productRef: "Produktová alebo sériová referencia",
      requestType: "Typ žiadosti",
      seeking: "Čo hľadáte",
      consent: "Súhlasím, aby MAXIMUS uchoval a použil tieto údaje na odpoveď na túto žiadosť. Nie je to prihlásenie na marketingové správy.",
    },
    roles: { player: "Hráč", parent: "Rodič alebo zákonný zástupca", coach: "Tréner", club: "Klub alebo akadémia", retailer: "Predajca", distributor: "Distribútor", brand: "Značka alebo ambasádor", investor: "Investor alebo strategický partner", institution: "Inštitúcia", other: "Iné" },
    interestOptions: { training: "Tréningové systémy", fitting: "Prispôsobenie", identity: "Profesionálna identita", programmes: "Autorizované programy", brand: "Osobná značka", supply: "Dodávky výstroje", team: "Tímová výstroj", personalisation: "Personalizácia", development: "Rozvojové programy", service: "Servis", network: "Účasť v sieti" },
    ownerTypes: { setup: "Nastavenie a konfigurácia", service: "Servis", records: "Záznamy a certifikáty", other: "Iné" },
    strategicAreas: { engineering: "Inžinierske možnosti", configuration: "Hĺbka konfigurácie", manufacturing: "Výrobný model", routes: "Cesty na trh", ip: "Duševné vlastníctvo a služby", expansion: "Príležitosti na expanziu" },
    errors: {
      required: "Toto pole je povinné.",
      too_long: "Tento záznam je príliš dlhý.",
      too_short: "Tento záznam je príliš krátky.",
      invalid_email: "Zadajte platnú e-mailovú adresu, napríklad name@example.com.",
      invalid_choice: "Vyberte jednu z možností.",
      not_number: "Zadajte celé číslo len pomocou číslic.",
      out_of_range: "Táto hodnota je mimo prijímaného rozsahu.",
      not_in_matrix: "Táto hmotnosť nie je v uvedenej matici vybranej série.",
      decimal_not_supported: "Zadajte celé číslo bez desatinných miest.",
      too_many: "Vyberte najviac tri možnosti.",
      consent_required: "Súhlas je potrebný, aby MAXIMUS mohol na túto žiadosť odpovedať.",
      invalid: "Tento záznam nie je platný.",
    },
  },
  legal: {
    title: "Právna identita a kontrola",
    lead: "Verejnou značkou je MAXIMUS / MAXIMUS GPS. Právne prevádzkové identity sú rozlíšiteľné a uvádzajú sa tu.",
    entities: {
      institutional: { role: "Vrstva inštitucionálnych programov", p: "Zabezpečuje vrstvu inštitucionálnych programov tam, kde program túto rolu zakladá. Nie je komerčným predajcom rakiet. Nezisková registrovaná organizácia v Dubai International Financial Centre." },
      equipment: { role: "Komerčný subjekt pre výstroj", p: "Komerčný subjekt pre výstroj na dodávky, distribúciu a zmluvné komerčné plnenie tam, kde túto rolu zakladajú súčasné prevádzkové dokumenty. Zmluvná strana každej transakcie je uvedená v dokumentoch danej transakcie." },
      ip: { role: "Duševné vlastníctvo, značka a komerčná koordinácia", p: "Vystupuje v zistenej role pre duševné vlastníctvo, značku alebo komerčnú koordináciu. Nepriraďuje sa žiadna nepotvrdená zmluvná zodpovednosť." },
      stewardship: { role: "Referencia správcovstva", p: "House of Maximus je referenciou správcovstva pre ekosystém tam, kde to podporuje príslušný zdroj." },
      control: { role: "Interná kontrola duševného vlastníctva, pôvodu a dokumentov", p: "MIPA je internou vrstvou kontroly duševného vlastníctva, pôvodu a dokumentov. Interný záznam MIPA je odlišný od externej registrácie obchodnej známky, patentu alebo autorského práva a od súdneho uznania a nepredstavuje vizuálne schválenie." },
    },
    labels: { licence: "Licencia", registration: "Registrácia", vat: "VAT TRN", address: "Adresa", email: "E-mail", jurisdiction: "Jurisdikcia" },
    boundaryTitle: "Hranice",
    boundary: [
      "Kúpa automaticky neudeľuje inštitucionálne členstvo, práva v riadení, licenčné odmeny ani investičné práva.",
      "Inštitucionálna rola je oddelená od komerčných transakcií s výstrojou.",
      "Ochrana osobných údajov, podmienky programov a opatrenia riadeného prístupu zodpovedajú skutočne uvoľneným funkciám.",
      "Žiadne všeobecné určenie rozhodného práva sa nevzťahuje na každého návštevníka, každý predaj ani na každý zahraničný program; zmluvný základ sa určuje v každej zmluve.",
    ],
  },
  privacy: {
    title: "Ochrana osobných údajov",
    updated: "Verzia 2026-09-21 · webová stránka 4.2",
    contactTitle: "Kontakt pre otázky k ochrane osobných údajov",
    sections: {
      collect: ["Čo sa zbiera", "Keď odošlete formulár: údaje, ktoré zadáte (meno, e-mail, rola, krajina alebo región, organizácia, ak ju uvediete, vaša správa a odpovede vo formulári), stránka a kampaňové parametre vašej návštevy (vstupná stránka, jazyk, parametre utm; identifikátory reklamných kliknutí len vtedy, ak ste povolili analytiku) a čas odoslania. Vaša IP adresa sa používa len v hašovanej a krátkodobej podobe na obmedzenie zneužitia a neukladá sa s vašou žiadosťou."],
      purpose: ["Prečo", "Aby sme odpovedali na vašu žiadosť, pripravili návrh alebo špecifikáciu, o ktorú ste požiadali, a zachovali záznam o žiadosti. Na základe formulára sa neposielajú žiadne marketingové správy."],
      storageOn: ["Kde sa žiadosti ukladajú", "Žiadosti sa ukladajú v databáze spoločnosti Upstash, Inc. (Redis), poskytovanej prostredníctvom hostingovej platformy Vercel Inc."],
      notifyEmail: ["Upozornenie na novú žiadosť", "Keď je žiadosť prijatá, upozornenie s údajmi, ktoré ste odoslali, sa zasiela e-mailom do zodpovednej poštovej schránky MAXIMUS."],
      notifyTelegram: ["Upozornenie na novú žiadosť", "Keď je žiadosť prijatá, upozornenie s údajmi, ktoré ste odoslali, sa zasiela zodpovednej osobe v MAXIMUS prostredníctvom Telegramu (Telegram FZ-LLC, Dubaj), ktorý toto upozornenie pri prenose spracúva."],
      notifyWebhook: ["Upozornenie na novú žiadosť", "Keď je žiadosť prijatá, upozornenie s údajmi, ktoré ste odoslali, sa zasiela na interný koncový bod MAXIMUS cez podpísané a šifrované spojenie."],
      notifyNone: ["Upozornenie na novú žiadosť", "Upozorňovanie na nové žiadosti sa práve nastavuje. Vaša žiadosť sa uloží a MAXIMUS ju číta z interného registra; na tento účel sa nič neposiela tretej strane."],
      storageOff: ["Kde sa žiadosti ukladajú", "Ukladanie žiadostí sa práve nastavuje. Kým nie je aktívne, formuláre uvádzajú, že žiadosť nemožno prijať; nič sa neukladá. Webovú stránku hostuje Vercel Inc."],
      browser: ["Úložisko prehliadača", "Úložisko relácie uchováva odpovede s možnosťou výberu z GPS a z konfigurátora a kampaňové parametre vašej návštevy počas tejto relácie prehliadača. Kontaktné údaje, voľný text, text gravírovania a informácie o deťoch sa v prehliadači neukladajú."],
      analyticsOn: ["Analytika", "S vaším súhlasom Google Analytics 4 meria návštevy a udalosti formulárov bez kontaktných údajov a bez textu žiadosti. Vaša voľba sa uchováva v lokálnom úložisku a možno ju kedykoľvek zmeniť v „Nastaveniach analytiky“ v päte stránky. Formuláre fungujú aj bez analytiky."],
      analyticsOff: ["Analytika", "Na tejto webovej stránke nie je aktívny žiadny analytický nástroj."],
      retention: ["Uchovávanie", "Zatiaľ nie je nastavená žiadna automatická lehota na vymazanie. O vymazanie svojej žiadosti môžete požiadať kedykoľvek."],
      children: ["Deti", "Formuláre musí vyplniť dospelá osoba. Žiadosti týkajúce sa hráčov do 18 rokov podáva rodič alebo zákonný zástupca. Neodosielajte meno dieťaťa, dátum narodenia, školu ani zdravotné informácie. Profily detí sa nikdy nezverejňujú."],
      rights: ["Vaše práva", "Ak chcete získať prístup k svojej žiadosti, opraviť ju alebo vymazať, napíšte na gps@maximus.tennis a uveďte svoje ID žiadosti."],
      controlled: ["Riadené informácie", "Dôverné dokumenty sa na tejto webovej stránke neukladajú ani z nej neposkytujú. Riadené sprístupňovanie prebieha na základe NDA alebo zmluvy prostredníctvom osobitných kanálov."],
    },
  },
  terms: {
    title: "Podmienky používania",
    copyright: "Výlučným nositeľom autorských práv k tejto webovej stránke — k jej textom, fotografiám, dizajnu a kódu — je Maximus Kiriyakulov. Tieto práva neboli prevedené na žiadnu spoločnosť ani na žiadnu inú osobu.",
    updated: "Verzia 2026-09-21",
    sections: [
      ["Informácia, nie ponuka", "Informácie o produktoch na tejto webovej stránke opisujú schválené špecifikácie, konfiguračnú architektúru a vysvetlenia programov. Nie sú ponukou na predaj, cenníkom, vyjadrením o zásobách ani záväzkom k dodaniu. Komerčné podmienky sa dohadujú osobitne a písomne so zmluvným subjektom uvedeným v každej transakcii."],
      ["Žiadosti", "Žiadosť odoslaná prostredníctvom tejto webovej stránky — vrátane profilov GPS, konfiguračných žiadostí a technických zadaní — sa uloží s ID žiadosti a posúdi sa. Nie je prijatou objednávkou, výrobným záväzkom, potvrdeným termínom, žiadosťou o členstvo ani prijatou prihláškou do akéhokoľvek programu."],
      ["Špecifikácie a dôkazy", "Vypočítané hodnoty, výrobné ciele a potvrdené špecifikácie sú na príslušných stránkach odlíšené. Hodnoty tuhosti rámu sú výrobnými cieľmi, kým sa nezverejní inak. Negarantuje sa žiadny výsledok pre konkrétneho hráča."],
      ["Ekosystém, členstvo a práva", "Kúpa rakety nezakladá inštitucionálne členstvo, investičné práva, vlastníctvo duševného majetku, nárok na licenčné odmeny ani výhody z účasti. Nároky vyplývajú zo zverejnených podmienok programu alebo z písomnej zmluvy."],
      ["Duševné vlastníctvo", "MAXIMUS®, emblém leva, známka GPS a obsah tejto webovej stránky sú chránené. Interné inžinierske receptúry, protokoly kontroly kvality, laminácie, výrobné formy, identita dodávateľov, kalkulácia nákladov a chránená metodika sa tu nesprístupňujú."],
    ],
  },
  lead: {
    submit: "Odoslať žiadosť",
    submitting: "Odosiela sa…",
    retry: "Skúsiť znova",
    acceptedEyebrow: "Žiadosť prijatá",
    acceptedTitle: "Vaša žiadosť bola prijatá.",
    requestId: "ID žiadosti",
    acceptedNext: "MAXIMUS posúdi každú žiadosť a odpovie písomne na e-mailovú adresu, ktorú ste uviedli. ID žiadosti si uchovajte pre ďalšiu komunikáciu.",
    duplicate: "Táto žiadosť už bola prijatá; duplikát sa nevytvoril.",
    another: "Začať novú žiadosť",
    errorsTitle: "Skontrolujte prosím tieto polia:",
    failTitle: "Vaša žiadosť nebola odoslaná.",
    fail: {
      offline: "Vaše zariadenie je bez pripojenia k internetu.",
      network: "Spojenie so serverom sa nepodarilo.",
      timeout: "Server neodpovedal včas.",
      rate_limited: "Z tejto siete prišlo príliš veľa žiadostí. Skúste to prosím znova o niekoľko minút.",
      too_fast: "Formulár bol odoslaný veľmi rýchlo. Skontrolujte ho prosím a odošlite znova.",
      spam_suspected: "Žiadosť zastavil filter nevyžiadanej pošty.",
      unavailable: "Žiadosti momentálne nemožno prijímať.",
      default: "Nastala neočakávaná chyba.",
    },
    keepNote: "Vaše údaje zostávajú na tejto stránke, takže to môžete skúsiť znova.",
    sendByEmail: "Odoslať túto žiadosť e-mailom",
    sendByEmailNote: "Otvorí sa vaša e-mailová aplikácia s textom tejto žiadosti. MAXIMUS ju dostane, keď e-mail odošlete.",
    mailConfig: "Konfigurácia",
    mailPage: "Stránka",
    fallback: "Ak problém pretrváva, napíšte na {email}. Žiadosť sa považuje za odoslanú len vtedy, keď sa zobrazí ID žiadosti.",
    privacyLink: "Informácie o ochrane osobných údajov",
    hpLabel: "Toto pole nechajte prázdne",
    consentShort: "Súhlas",
    after: "Po odoslaní sa na tejto stránke zobrazí ID žiadosti. Žiadosti sa posudzujú a odpovedá sa na ne písomne; žiadosť nie je objednávkou.",
    basis: { unstrung: "Bez výpletu", strung: "S výpletom", unknown: "Neviem — dohodne sa v špecifikácii" },
    hints: {
      email: "MAXIMUS odpovedá písomne na túto adresu.",
      goal: "Napríklad: prvá súťažná raketa alebo prechod z juniorskej rakety. Neuvádzajte mená, dátumy narodenia ani zdravotné informácie o dieťati.",
      currentRacquet: "Značka a model, ak ich poznáte.",
      message: "Neuvádzajte heslá, platobné údaje ani zdravotné informácie.",
    },
  },
  choose: {
    eyebrow: "Pomoc s výberom",
    title: "Pomôžte mi vybrať raketu",
    lead: "Povedzte MAXIMUS svoju úroveň a to, čo je pre vás najdôležitejšie. Vaše odpovede sa posúdia a dostanete písomný návrh: séria, trieda presnosti, hmotnosť a grip.",
    stepsTitle: "Čo bude nasledovať",
    steps: [
      ["Vaše odpovede", "Úroveň, priority a veľkosť gripu, ak ju poznáte."],
      ["Odborné posúdenie", "MAXIMUS porovná vaše odpovede s maticami sérií."],
      ["Písomný návrh", "Navrhovaná konfigurácia a ďalší krok, písomne."],
    ],
    formTitle: "Vaše odpovede",
    submit: "Požiadať o pomoc s výberom",
    altTitle: "Chcete sa rozhodnúť sami?",
    altGps: "Podrobný profil GPS",
    altBuild: "Konfigurovať priamo",
    note: "Žiadne automatické prispôsobenie a žiadne tvrdenie o presnosti: každú žiadosť posudzuje človek.",
  },
  consent: {
    title: "Analytika",
    text: "Môže MAXIMUS merať návštevy pomocou Google Analytics? Formuláre fungujú v oboch prípadoch; do analytiky sa neposielajú žiadne kontaktné údaje ani text žiadosti.",
    allow: "Povoliť analytiku",
    decline: "Odmietnuť",
  },
  media: {
    spotHeadsUp: "Päť trenažérov MAXIMUS Spot Trainer vedľa seba, okrúhlymi kontaktnými hlavami nahor a rukoväťami dole, s loptičkami položenými na hlavách",
    greatHero: "Séria MAXIMUS GREAT, 363 g: celá kompozícia s červeným a žltým detailom na hlave, lesklým písmom MAXIMUS, podpisom Maximus na drieku a koncovou krytkou s levom",
    spotRow: "Päť trenažérov MAXIMUS Spot Trainer vyložených v rade, loptičky položené na ich okrúhlych kontaktných hlavách",
    spotPair: "Dva trenažéry MAXIMUS Spot Trainer stojace vzpriamene pred emblémom leva MAXIMUS, loptičky na ich okrúhlych kontaktných hlavách",
    spinVisual: "MAXIMUS SPIN: hlava s výpletom, lesklé písmo MAXIMUS, grip a koncová krytka s levom",
    powerVisual: "MAXIMUS POWER: hlava s výpletom, lesklé písmo MAXIMUS, personalizačná gravúra, grip a koncová krytka s levom",
    greatVisual: "MAXIMUS GREAT: hlava s výpletom, lesklé písmo MAXIMUS, personalizačná gravúra, grip, koncová krytka s levom a znak série G na srdci rakety",
    spinHead: "Hlava a výplet MAXIMUS SPIN",
    handleLion: "Srdce, grip a koncová krytka MAXIMUS s emblémom leva",
    engraving: "Strieborná personalizačná gravúra na drieku",
    lettering: "Lesklé čierne písmo MAXIMUS na matnom čiernom ráme",
    variantAlt: "Séria MAXIMUS {series} — {w} g, vyváženie {b} mm: úplná vizualizácia so špecifikačným pásom, so zónou personalizačnej gravúry a s označením MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, systém štyroch rakiet",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Drieky Sweet Spot Trainer s písmom MAXIMUS",
    sstGrips: "Gripy a koncové krytky Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, štyri koncové krytky s emblémom leva",
    note: "Produktová vizualizácia",
  },
  notFound: { title: "Stránka sa nenašla", p: "Stránka, ktorú ste požadovali, v tomto jazyku neexistuje.", cta: "Prejsť na domovskú stránku" },
};

export default sk;
