/* Slovenian dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const sl = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — v celoti karbonski teniški loparji, razviti po specifikaciji",
    defaultDescription:
      "V celoti karbonski teniški loparji od okvirja do ročaja: GREAT 97 in², POWER 98 in² in SPIN 100 in², osem tovarniških velikosti gripov L0–L7, razredi natančnosti za težo, ravnotežje, swingweight in togost ter individualno inženirstvo na zahtevo.",
  },
  common: {
    statuses: {
      current: "Aktualno",
      agreement: "Na voljo po dogovoru",
      development: "V razvoju",
      concept: "Zasnova",
      target: "Proizvodni cilj",
      modelled: "Izračunano",
      confirmed: "Potrjeno",
      requested: "Zahtevana arhitektura",
      notprovided: "Ni navedeno",
    },
    brief: { who: "Komu je namenjeno", value: "Kaj dobite", now: "Potrjeno zdaj", next: "Naslednji korak" },
    labels: {
      next: "Naprej",
      back: "Nazaj",
      edit: "Uredi odgovore",
      review: "Pregled",
      start: "Začni",
      restart: "Začni znova",
      copy: "Kopiraj besedilo povpraševanja",
      copied: "Kopirano",
      openEmail: "Odpri e-pošto in pošlji to povpraševanje",
      reference: "Številka povpraševanja",
      weight: "Teža",
      balance: "Ravnotežje",
      swingweight: "Swingweight",
      stiffness: "Togost",
      grip: "Velikost gripa",
      headSize: "Velikost glave",
      series: "Serija",
      precisionClass: "Razred natančnosti",
      quantity: "Količina",
      notProvided: "Še ni objavljeno",
      requestTarget: "Zahtevana ciljna vrednost",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Več o tem",
      allSeries: "Vse serije",
      points: "navedene teže",
      optional: "neobvezno",
      required: "obvezno",
      select: "Izberite",
      yes: "Da",
      no: "Ne",
      unknown: "Ne vem",
      custom: "Lastna ciljna vrednost",
      listed: "Navedena teža",
      individual: "Posamezen lopar",
      pair: "Usklajen par",
      triple: "Usklajena trojica",
      team: "Ekipni set",
      summaryTitle: "Povzetek vašega povpraševanja",
      nextAction: "Naslednje dejanje",
      status: "Stanje",
      learn: "Izvedite več",
      schematic: "Shema — ne meritev",
      photo: "Fotografija",
    },
    ecosystemStrip: "Ekosistem MAXIMUS",
    truth: {
      noPrices: "Cene, najmanjše količine, dobavni roki, garancije in dobavne zaveze se pisno potrdijo za vsak trg in vsak program posebej.",
      requestNotOrder: "Povpraševanje je zahteva za presojo. Ni sprejeto naročilo, proizvodna zaveza ali potrjen termin.",
      noGuarantee: "Nobena oprema, metoda ali program, opisan tukaj, posameznemu igralcu ne zagotavlja določenega izida.",
      governing: "Ta stran je objavljena v več jezikih. Odločilna je angleška različica; prevod je namenjen lažjemu razumevanju.",
    },
  },
  nav: {
    language: "Jezik",
    groups: { racquets: "Loparji", training: "Vadba", ecosystem: "Ekosistem", partnerships: "Partnerstva" },
    racquets: "Serije loparjev in primerjava",
    great: "GREAT — 97 in² · Nadzor",
    power: "POWER — 98 in² · Moč",
    spin: "SPIN — 100 in² · Rotacija",
    precision: "Natančnost in togost",
    grip: "Tovarniška arhitektura gripov L0–L7",
    custom: "Inženirstvo po meri",
    training: "Sistemi vadbe",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologija",
    gps: "MAXIMUS GPS",
    build: "Sestavite svojega",
    choose: "Pomagajte mi izbrati",
    ecosystem: "Zemljevid ekosistema",
    engineering: "Inženirstvo in proizvodnja",
    experience: "Preizkus in prilagoditev",
    brands: "Osebne znamke in ambasadorji",
    families: "Družine in starši",
    owners: "Lastniki in trezor lastnika",
    network: "Sports Network",
    partnerships: "Vse partnerske poti",
    coaches: "Trenerji",
    clubs: "Klubi in akademije",
    distribution: "Distribucija in razvoj držav",
    strategic: "Strateško sodelovanje in naložbe",
    institutional: "Institucionalni programi",
    contact: "Stik",
    legal: "Pravna identiteta",
    privacy: "Zasebnost",
    terms: "Pogoji",
    menu: "Meni",
    close: "Zapri",
    home: "Domov",
    skip: "Preskoči na vsebino",
  },
  footer: {
    line: "Lopar MAXIMUS je vaš ključ v svet MAXIMUS.",
    product: "Izdelek",
    ecosystem: "Ekosistem",
    company: "Organizacija",
    instagram: "Instagram",
    email: "E-pošta",
    analytics: "Nastavitve analitike",
    subscribe: {
      title: "Ostanite z MAXIMUS",
      line: "Nove serije, termini prilagajanja loparjev, gradiva za vadbo in program za lastnike. Nekaj pisem na leto, nič drugega.",
      label: "E-poštni naslov",
      placeholder: "your@email.com",
      button: "Prijavite se",
      sending: "Pošiljanje",
      done: "Na seznamu ste. Pišemo samo takrat, ko imamo kaj vrednega branja.",
      invalid: "Prosimo, preverite naslov.",
      failed: "Naslova ni bilo mogoče zabeležiti. Prosimo, poskusite znova v nekaj trenutkih.",
      terms: "S prijavo soglašate, da vam MAXIMUS lahko pošilja te novice in za ta namen hrani vaš naslov. Vsako pismo vsebuje povezavo za odjavo.",
    },
    rights: "MAXIMUS® in lev v emblemu sta znamki ekosistema MAXIMUS. MIPA — interno upravljanje intelektualne lastnine, izvora in dokumentacije.",
    boundary:
      "Poslovni in pogodbeni pogoji se dogovorijo posebej in pisno. Nakup loparja ne ustvarja institucionalnega članstva, naložbenih pravic, lastništva intelektualne lastnine ali upravičenja do licenčnin.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Natančnost se začne pri stiku.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer in metodologija MAXIMUS povezujejo osredotočeno vadbo z zmogljivostjo v celoti karbonskih loparjev.",
    heroCta1: "Raziščite sistem vadbe",
    heroCta2: "Raziščite GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Nadzor",
    heroMeta: [
      ["V celoti karbonski", "od okvirja do ročaja"],
      ["4 parametri", "teža · ravnotežje · swingweight · togost"],
      ["8 velikosti gripov", "tovarniška geometrija L0–L7"],
      ["3 serije", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Začnite tukaj",
      title: "Izberite svojo pot",
      items: {
        player: { h: "Igralec", p: "Poiščite lopar glede na raven in prioritete ali ga nastavite neposredno.", a: "Poiščite svoj lopar" },
        parent: { h: "Starš", p: "Pisna pot za razvojne cilje, vključenost trenerja in primerno opremo.", a: "Pot za družine" },
        coach: { h: "Trener, klub ali akademija", p: "Sistemi vadbe, prilagajanje loparja, ekipni seti in personalizacija.", a: "Poti za trenerje in klube" },
        partner: { h: "Distributer ali partner", p: "Distribucija, razvoj držav, strateške in institucionalne poti.", a: "Partnerske poti" },
      },
    },
    series: {
      eyebrow: "Zmogljivostne serije",
      title: "Tri zmogljivostne arhitekture. Ena inženirska platforma.",
      lead: "Serijo izberite glede na igralno usmeritev, nato dokončajte nastavitev: razred natančnosti, teža, grip, personalizacija.",
      cta: "Primerjajte serije",
      configure: "Nastavite",
      open: "Odprite serijo",
      photoPending: "Fotografija še ni objavljena",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Sistem natančnosti MAXIMUS",
      title: "Teža. Ravnotežje. Swingweight. Togost.",
      sub: "Vodeno kot en inženirski sistem.",
      lead: "Trije razredi natančnosti določajo, kako tesno je vsak dokončan lopar zadržan pri svoji navedeni specifikaciji. P0.5 je ozka toleranca po določenem merilnem protokolu — ne ničelna napaka.",
      cta: "Natančnost in togost podrobno",
    },
    stiffness: {
      eyebrow: "Togost",
      title: "Ponovljiv odziv okvirja glede na navedeni cilj.",
      p: "Togost okvirja oblikuje odziv, občutek in skladnost med loparji. MAXIMUS jo obravnava kot četrti nadzorovani parameter: ciljna vrednost, izmerjeni rezultat, dovoljena toleranca in zmožnost merilnega instrumenta se vodijo kot ločeni zapisi. Korist je ponovljivost — ne zagotovljen izid za vsakega igralca.",
      cols: [["Odziv", "Kako okvir ob stiku vrne energijo."], ["Občutek", "Kaj igralec ob stiku zazna."], ["Skladnost", "Loparji, izdelani po isti specifikaciji, se znotraj svojega razreda odzivajo enako."]],
      schematicCaption: "Shema: dovoljeno odstopanje okoli navedene ciljne togosti za vsak razred. Ni meritev in iz nje ne izhaja nobena vrednost RA.",
      bands: { p25: "ciljna toleranca ±1 RA", p15: "ciljna toleranca ±0,5 RA", p05: "ustreza navedeni ciljni vrednosti RA po uveljavljenem tovarniškem merilnem protokolu — ne ničelna napaka", target: "navedeni cilj (brez navedbe vrednosti)" },
    },
    carbon: {
      eyebrow: "Standard izdelave",
      title: "V celoti karbonski. Od okvirja do ročaja.",
      p: "Vsi sedanji loparji MAXIMUS na tej platformi so po svoji strukturi v celoti karbonski, vključno z ročajem. Za oblikovanje ročaja se pena ne uporablja.",
      gripTitle: "Osem tovarniških velikosti gripov. L0–L7.",
      gripP: "Vsaka velikost je tovarniška geometrija karbonskega ročaja — ne nadgradnja z ovojnimi trakovi.",
      scaleCaption: "Shema: nazivne oznake gripov L0–L7 (4″ do 4⅞″). Ne gre za izmerjene dimenzije ročaja.",
      cta: "Tovarniška arhitektura gripov",
    },
    custom: {
      eyebrow: "Inženirstvo po meri",
      title: "Razvito po specifikaciji.",
      sub: "Standardna linija je izhodišče.",
      p: "MAXIMUS sprejema tehnične zahteve, ki presegajo objavljene matrike, v presojo, inženirsko obdelavo, validacijo in izdelavo po dogovorjeni specifikaciji. Izvedljivost se potrdi pisno.",
      chain: ["Opredelitev", "Inženirska obdelava", "Validacija", "Specifikacija", "Izdelava", "Meritev / zapis"],
      cta: "Pošljite tehnično zahtevo",
      cta2: "Pogovorite se o inženirstvu po meri",
    },
    training: {
      eyebrow: "Sistemi vadbe",
      title: "Sistem vadbe, zgrajen okoli stika.",
      p: "Sweet Spot Trainer, metodologija MAXIMUS in Spot Trainer povezujejo opremo z vadbo pod vodstvom trenerja: stik v sredini, nadzor, postopna obremenitev in prehod nazaj na zmogljivostni lopar.",
      cta: "Sistemi vadbe",
      cta2: "Zahtevajte predstavitev",
      photoPending: "Fotografija pripomočka še ni objavljena",
      sstP: "Vadbena glava 50 in² za vadbo stika v sredini, s štirimi težnimi izvedbami za obremenitev, ki jo izbere trener.",
      sstCta: "Raziščite Sweet Spot Trainer",
      sstCaption: "Izvedba 300 g, ena od štirih",
      methodP: "Postavite cilje, izberite opremo, vadite ob vključenosti trenerja, zapisujte opažanja, znova ocenite, prilagodite in delo prenesite v tekmovalno igro.",
      methodCta: "Raziščite metodologijo",
      spotP: "Majhna okrogla tarča za vadbo natančne in ponovljive točke stika.",
      spotCta: "Raziščite Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Proizvodnja in kontrola kakovosti",
      title: "Izdelano po specifikaciji. Izmerjeno in zapisano.",
      p: "Proizvodnja sledi pisni specifikaciji vsakega naročila. Zapisi sledijo razredu natančnosti: hranjeni proizvodni zapisi pri P2.5, posamični zapisi in sledljivost pri P1.5, posamični nadzor in dokumentacija pri P0.5 tam, kjer jih program za naročilo uvaja.",
      confirmedTitle: "Potrjeno",
      confirmed: ["V celoti karbonska izdelava od okvirja do ročaja.", "Razredi natančnosti P2.5, P1.5 in P0.5 s štirimi nadzorovanimi parametri.", "Osem tovarniških velikosti gripov L0–L7."],
      pendingTitle: "Še ni objavljeno",
      pending: "Fotografije merilne opreme, vzorčni zapisi kontrole kakovosti in posnetki iz proizvodnje še niso objavljeni. Nič na tej strani ni izmerjeno potrdilo.",
      captions: { lettering: "Sijajni napis MAXIMUS na mat okvirju", buttcap: "Grip in zaključni pokrovček z levom", handle: "Srebrna gravura personalizacije", finish: "Glava in pletivo strun" },
      cta: "Inženirstvo in proizvodnja",
    },
    world: {
      eyebrow: "Svet MAXIMUS",
      title: "En ključ. En ekosistem. Neomejene priložnosti.",
      note: "„Neomejene priložnosti“ je izraz znamke, ne obljuba neomejene tehnične izvedljivosti, dohodka ali dostopa. Nakup ne ustvarja licenčnin, naložbenih donosov, sponzorstva ali financiranja razvoja igralca.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — in vaša navigacija v svetu tenisa: voden profil opreme z pisnim odgovorom." },
        personal: { h: "Personalizacija", p: "Imena, začetnice, številke in ekipne oznake v odobreni izvedbi srebrne gravure." },
        development: { h: "Razvoj", p: "Sistemi vadbe pod vodstvom trenerja, zapisi in ponovna ocena." },
        ecosystem: { h: "Razširjeni ekosistem", p: "Osebne znamke, zapisi lastnikov, mreža, licenciranje in institucionalni programi — vsak s svojim dejanskim stanjem." },
      },
      cta: "Raziščite ekosistem",
    },
    partners: {
      eyebrow: "Partnerske poti",
      title: "Trenerji, klubi, distributerji in partnerji.",
      p: "Najprej pisna kvalifikacija. Pravice za državo, izključnost in poslovni pogoji se dogovorijo pisno — nikoli niso dodeljeni prek obrazca.",
      cta: "Vse partnerske poti",
      formTitle: "Kratko povpraševanje",
      formLead: "Izberite namen in pišite MAXIMUS. Na tej strani prejmete številko povpraševanja.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "VAŠA NAVIGACIJA V SVETU TENISA" } },
    personal: { eyebrow: "Personalizacija", title: "Vaše ime. Vaša številka. Vaš MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tri serije. Resnični parametri." },
    map: { cta: "Raziščite ekosistem" },
  },
  racquets: {
    title: "Loparji",
    lead: "Tri zmogljivostne serije s skupnim standardom izdelave, skupnim sistemom natančnosti in skupno tovarniško arhitekturo gripov. Vsaka serija je uveljavljena zmogljivostna arhitektura v okviru širše inženirske platforme.",
    direction: { control: "Nadzor", power: "Moč", spin: "Rotacija" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Glavna igralna usmeritev",
    compareTitle: "Primerjava serij",
    compareLead: "Samo potrjeni podatki o arhitekturi. Vzorci strun, dolžine, profili okvirja, razponi napetosti ter nazivne vrednosti swingweighta in togosti za te serije niso objavljeni; zbiramo jih kot zahtevane ciljne vrednosti za tehnično presojo.",
    columns: { series: "Serija", head: "Velikost glave", direction: "Usmeritev", weights: "Navedene teže", range: "Razpon teže", balance: "Podatki o ravnotežju" },
    balanceModelled: "Izračunane vrednosti",
    balanceNotProvided: "Še ni objavljeno",
    construction: "Izdelava: v celoti karbonska, od okvirja do ročaja · Natančnost: P2.5 / P1.5 / P0.5 · Gripi: L0–L7",
    otherTitle: "Drugi športi z loparji",
    otherLead: "Odobrene smeri razvoja. V teh kategorijah ni prodajnih izdelkov in nobena teniška specifikacija se nanje ne prenaša.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Plažni tenis" },
    ctaConfigure: "Sestavite povpraševanje",
    ctaSeries: "Odprite serijo",
  },
  seriesPage: {
    eyebrow: "Zmogljivostne serije",
    intro: {
      great: "Arhitektura GREAT z glavo 97 in² je zgrajena okoli nadzora: zbrana glava, natančen stik in zaupanje v smer.",
      power: "Arhitektura POWER z glavo 98 in² je zgrajena okoli prenosa energije: globina in tempo iz stabilnega okvirja.",
      spin: "Arhitektura SPIN z glavo 100 in² je zgrajena okoli vedenja žogice: rotacija, varnostna rezerva in oblikovanje leta.",
    },
    photoPending: "Fotografija serije še ni objavljena",
    detailPending: "Podrobne fotografije izdelave in ročaja za to serijo še niso objavljene.",
    specsTitle: "Specifikacija in stanje",
    catalogue: {
      eyebrow: "Katalog serije {series}",
      title: "{n} težnih različic",
      lead: "Vsaka različica serije {series}, razvrščena po teži. Teža v gramih, ravnotežje v milimetrih od konca ročaja. Vsaka vizualizacija je prikazana v celoti: nič ni obrezano, prekrito ali raztegnjeno.",
      selectLabel: "Izberite težno različico",
      select: "Prikaži to različico",
      selected: "Prikazano zgoraj",
      balanceLabel: "Ravnotežje",
      headLabel: "Velikost glave",
      constructionLabel: "Izdelava",
      gripsLabel: "Tovarniške velikosti gripov",
      precisionLabel: "Razredi natančnosti",
      balanceConfirmed: "Ravnotežje je potrjena vrednost za to težo in ustreza številki, natisnjeni na vizualizaciji. Cene, zaloga in dobavni roki tu niso objavljeni.",
      balanceModelled: "Ravnotežje je izračunana vrednost za to navedeno težo, ne posamična tovarniška meritev; ustreza številki, natisnjeni na vizualizaciji. Cene, zaloga in dobavni roki tu niso objavljeni.",
      zoom: "Odprite sliko",
      close: "Zapri",
      allTitle: "Vseh {n} različic",
    },
    specs: { head: "Velikost glave", direction: "Glavna usmeritev", weights: "Navedene teže", range: "Razpon teže", balance: "Ravnotežje", construction: "Izdelava", grips: "Tovarniški gripi", precision: "Razredi natančnosti" },
    construction: "V celoti karbonska, od okvirja do ročaja",
    statusTitle: "Stanje vrednosti",
    matrixTitle: "Celotna matrika teže",
    matrixLead: "Navedene teže so standardni izbor. Druge teže je mogoče zahtevati kot lastne ciljne vrednosti; manjkajoče vmesne vrednosti se ne vstavljajo.",
    balanceNote: {
      confirmed: "Vrednosti ravnotežja so potrjene za vsako navedeno težo (mm od konca ročaja) in ustrezajo številki, natisnjeni na vizualizaciji te teže. Tu niso izračunane in niso zglajene med sosednjimi težami; merilna podlaga se potrdi v pisni specifikaciji.",
      modelled: "Vrednosti ravnotežja so izračunane za vsako navedeno težo (mm od konca ročaja). Niso posamične tovarniške meritve; merilna podlaga se potrdi v pisni specifikaciji.",
      notprovided: "Vrednosti ravnotežja za to serijo niso navedene. Ne sklepajte jih iz druge serije.",
    },
    optionsTitle: "Natančnost, grip in teža",
    notPublished: "Za to serijo ni objavljeno: vzorec strun, dolžina, profil okvirja, razpon napetosti ter vrednosti swingweighta in togosti. Navedete jih lahko kot zahtevane ciljne vrednosti za tehnično presojo.",
    offerTitle: "Kaj sledi vašemu povpraševanju",
    offerSteps: [
      ["Povpraševanje", "Pošljite nastavitev ali vprašanje. Številka povpraševanja se prikaže takoj."],
      ["Presoja", "MAXIMUS presodi serijo, razred, težo, grip in morebitne zahtevane ciljne vrednosti."],
      ["Pisni odgovor", "Specifikacija, razpoložljivost in poslovni pogoji se potrdijo pisno."],
    ],
    faqTitle: "Vprašanja",
    faq: [
      ["Ali so vrednosti ravnotežja izmerjene?", "Za navedene teže so izračunane, niso posamične meritve. Merilna podlaga se potrdi v pisni specifikaciji."],
      ["Ali lahko zahtevam težo, ki ni navedena?", "Da, kot lastno ciljno vrednost v celih gramih. Gre v tehnično presojo, izvedljivost pa se potrdi pisno."],
      ["Kaj spremeni razred natančnosti?", "Kako tesno so teža, ravnotežje, swingweight in togost zadržani pri navedeni specifikaciji in kateri zapisi se vodijo."],
      ["Ali se grip nadgradi z ovojnimi trakovi?", "Ne. L0–L7 so tovarniške geometrije karbonskega ročaja."],
      ["Kje so cene in dobavni roki?", "Pisno se potrdijo za vsako povpraševanje in tu niso objavljeni."],
    ],
    faqSpinBalance: ["Od kod izhajajo vrednosti ravnotežja serije SPIN?", "Iz potrjene preglednice serije Spin: 33 težnih različic z ravnotežjem v milimetrih od konca ročaja. Vsak par ustreza številki, natisnjeni na odobreni vizualizaciji te teže. Vrednosti niso izračunane in niso zglajene med sosednjimi težami."],
    ctaBuild: "Nastavite to serijo",
    ctaAsk: "Vprašajte o tej seriji",
    ctaCompare: "Primerjajte vse serije",
    weightsLabel: "navedene teže",
    headLabel: "glava",
  },
  precision: {
    title: "Natančnost in togost",
    switch: { label: "Izberite razred natančnosti", panelLabel: "Štirje nadzorovani parametri —", qcLabel: "Arhitektura kontrole kakovosti", protocolNote: "po določenem tovarniškem merilnem protokolu kontrole kakovosti", fullTable: "Celotna primerjalna preglednica" },
    lead: "Štirje parametri, vodeni kot en inženirski sistem. Vsak razred določa, kako tesno je dokončan lopar zadržan pri svoji navedeni specifikaciji in kateri zapisi kakovosti nastanejo.",
    statement: "Teža. Ravnotežje. Swingweight. Togost. Vodeno kot en inženirski sistem.",
    classes: {
      "P2.5": { name: "Nadgradljivo zmogljivostno jedro", qc: "Posamična meritev in hranjeni proizvodni zapisi." },
      "P1.5": { name: "Napredna natančnost", qc: "Posamična meritev, posamični zapisi in sledljivost." },
      "P0.5": { name: "Profesionalno · posamično nadzorovano", qc: "Posamični nadzor z nazivnimi in dejanskimi vrednostmi ter posamičnimi zapisi meritev; serijska identiteta, sledljivost šarže, potrdilo o natančnosti in usklajeni seti tam, kjer jih program za naročilo uvaja." },
    },
    columns: { cls: "Razred", weight: "Teža", balance: "Ravnotežje", sw: "Swingweight", stiff: "Togost", qc: "Arhitektura kontrole kakovosti" },
    stiffTarget: "ciljna toleranca",
    stiffExact: "ustreza navedeni ciljni vrednosti RA po uveljavljenem tovarniškem merilnem protokolu",
    programmeNote: "Serijska identiteta, potrdila in dokumentacija usklajenih setov se izdajo samo tam, kjer jih program za posamezno naročilo uvaja.",
    targetsNote: "Specifikacije togosti so proizvodni cilji, dokler ustrezen protokol in proizvodna dokazila ne omogočijo močnejše trditve. Trditev o arhitekturi ne pomeni, da je vsaka navedena izvedba že prestala celoten postopek sprostitve po vseh štirih parametrih.",
    stiffnessTitle: "Zakaj je togost pomembna",
    stiffnessP1: "Togost okvirja vpliva na to, kako se okvir odzove ob stiku, kakšen je občutek in kako skladna sta dva loparja med sabo. Osrednja korist njenega nadzora je ponovljiv odziv glede na navedeno specifikacijo.",
    stiffnessP2: "Preden je objavljena preverjena skladnost, interni zapis kontrole kakovosti navaja instrument, stanje njegove kalibracije, metodo, stanje loparja, ločljivost, merilno negotovost, ponovljene meritve, pravilo zaokroževanja in merilo sprejemljivosti. Enako prikazano celo število ni dokaz ničelnega fizičnega odstopanja ali ničelne merilne napake.",
    fields: ["Ciljna vrednost", "Izmerjeni rezultat", "Dovoljena toleranca", "Zmožnost instrumenta"],
    fieldsNote: "V vsakem zapisu vodeno kot ločena polja.",
    matchedTitle: "Usklajeni seti",
    matchedP: "Merila za usklajeni set so opredeljena ločeno od posamične tolerance. Skladnost vsakega loparja z njegovo nazivno toleranco sama po sebi ne dokazuje določene največje razlike med dvema loparjema. Usklajene pare, trojice in ekipne sete se zahteva prek konfiguratorja in potrdi pisno.",
    extendedTitle: "Razširjeni tehnični model",
    extendedP: "Podatkovni model podpira dodatne parametre. Zanje še ne obstajajo vrednosti ali razredi tolerance; navesti jih je mogoče kot zahtevane ciljne vrednosti v tehnični zahtevi.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torzijsko vedenje", length: "Dolžina", beamProfile: "Profil okvirja", headGeometry: "Geometrija glave", stringPattern: "Vzorec strun", durability: "Trajnost", vibration: "Lastnosti vibracij" },
    noZero: "MAXIMUS svoje navedene linije ne opisuje kot linije z ničelno toleranco. Natančnost v liniji je navedena kot razred z navedeno toleranco in določeno arhitekturo kontrole kakovosti. ZERO ni del linije.",
    zero: {
      eyebrow: "Izključna možnost",
      title: "ZERO",
      sub: "Ničelna toleranca v gramih.",
      p: "Trije razredi zadržijo dokončan lopar znotraj navedenega pasu. ZERO ta pas odpravi. Lopar se izdeluje in meri, dokler odčitek ni enak navedeni številki pri ločljivosti tovarniškega instrumenta, in ta odčitek se izda z njim. Ni del navedene linije in ni četrti razred: dogovori se posamično, za en lopar ali en usklajen set, kot izključna izdelava po naročilu. Po dogovoru se enak pristop uporabi za ravnotežje in swingweight.",
      points: [
        ["Brez pasu", "Navedena številka je rezultat, ne središče tolerance."],
        ["Po enem", "Izdelano, izmerjeno in zapisano kot ena sama enota."],
        ["Izdano z loparjem", "Izmerjeni odčitek se izroči in ostane v proizvodnem zapisu."],
        ["Potrjeno pisno", "Parametri, obseg in dobavni rok se dogovorijo pred izdelavo."],
      ],
      note: "Usklajeno pri ločljivosti tovarniškega merilnega instrumenta. Enako prikazana številka ni trditev o ničelnem fizičnem odstopanju. Razpoložljivost in pogoji se dogovorijo posamično za vsako naročilo.",
      cta: "Zahtevajte ZERO",
    },
    cta: "Nastavite z razredom natančnosti",
  },
  grip: {
    title: "Tovarniška arhitektura gripov",
    statement: "Osem tovarniških velikosti gripov. L0–L7.",
    lead: "Geometrija gripa je del arhitekture karbonskega ročaja. Vsaka velikost je izdelana kot geometrija ročaja, ne nadgrajena z ovojnimi trakovi.",
    emph: "Razširjene velikosti",
    p1: "Tovarniška linija osmih velikosti daje trenerjem in igralcem širši razpon nastavitev, v katerem je mogoče opremo opredeliti glede na igralca, vključno z večjima geometrijama L6 in L7.",
    p2: "Nazivna oznaka gripa se razlikuje od surovih dimenzij konstrukcijskega ročaja in od končnega merilnega protokola. Velikosti veljajo za zmogljivostne serije in za vadbene družine na tej platformi.",
    p3: "Za to linijo ni nobene trditve o svetovni izključnosti.",
    columns: { size: "Velikost", nominal: "Nazivno", family: "Velja za" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Nastavite s svojo velikostjo gripa",
  },
  custom: {
    title: "Inženirstvo po meri",
    statement: "Razvito po specifikaciji.",
    sub: "Standardna linija je izhodišče.",
    lead: "MAXIMUS sprejema tehnične zahteve, ki presegajo objavljene matrike nastavitev, v presojo, inženirsko obdelavo, validacijo in izdelavo po dogovorjeni specifikaciji. Izvedljivost se potrdi s presojo — ni vsaka zamisljiva zahteva fizično ali poslovno izvedljiva.",
    scopeTitle: "Česa se tehnična zahteva lahko dotika",
    scope: ["Geometrija glave in okvirja", "Dolžina", "Teža", "Ravnotežje", "Swingweight", "Togost", "Twistweight", "Geometrija gripa", "Izdelava", "Usklajeni seti", "Vadbeni okvirji", "Oblika in gravura", "Identiteta in ekipni programi", "Razvoj, odvisen od orodij"],
    processTitle: "Postopek",
    process: [
      ["Opredelitev", "Želene ciljne vrednosti, obvezne omejitve, predvidena uporaba in sprejemljivi kompromisi."],
      ["Inženirska obdelava", "Inženirska presoja glede na platformo in orodja."],
      ["Validacija", "Validacija glede na dogovorjeno specifikacijo."],
      ["Specifikacija", "Pisna specifikacija z merilno podlago in tolerancami."],
      ["Izdelava", "Izdelava po specifikaciji."],
      ["Meritev / zapis", "Meritev in hranjeni zapisi po ustreznem razredu natančnosti."],
    ],
    formTitle: "Pošljite tehnično zahtevo",
    formLead: "Ločite želene ciljne vrednosti od obveznih omejitev. Rezultat je zahteva za tehnično presojo, ne samodejno sprejeto proizvodno naročilo.",
    protected: "Recepture laminata, orodja, identiteta dobaviteljev, interni izračuni stroškov in zaščiteno znanje po tej poti niso razkriti.",
    cta: "Pošljite tehnično zahtevo",
  },
  training: {
    title: "Sistemi vadbe",
    lead: "Dve vadbeni družini z lastnima proizvodnima standardoma, povezani z eno metodologijo: vadba pod vodstvom trenerja, zapisi, ponovna ocena in prenos nazaj v tekmovalno igro.",
    sst: { h: "Sweet Spot Trainer", p: "Vadbeni lopar z zmanjšano glavo 50 in² v sistemu štirih tež za vadbo stika v sredini, zavedanje sweet spota, nadzor loparja in postopno obremenjevanje." },
    spot: { h: "Spot Trainer", p: "Vadba točke stika z majhno okroglo tarčo, na odobreni podlagi štirih tež." },
    method: { h: "Metodologija", p: "Postavite cilje, izberite opremo ob vključenosti trenerja, uporabljajte ustrezen sistem, zapisujte, znova ocenite, prilagodite in prenesite." },
    experience: "Primite ga. Zamahnite z njim. Občutite ga.",
    experienceP: "Zahtevajte preizkus, prilagoditev loparja ali predstavitev s podporo trenerja. Poslano povpraševanje ni potrjen termin.",
    cta: "Zahtevajte prilagoditev ali predstavitev",
    distinct: "Sweet Spot Trainer, Spot Trainer in katera koli ločena predstavitvena naprava so različni izdelki in se nikoli ne združujejo.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Samostojna vadbena kategorija z lastnim proizvodnim standardom. Glava 50 in² usmeri pozornost na mesto stika; štiri teže zagotavljajo napredovanje obremenitve.",
    baseline: "Potrjena izhodiščna osnova",
    columns: { head: "Glava", length: "Dolžina", pattern: "Vzorec strun", grips: "Tovarniški gripi" },
    systemTitle: "Sistem štirih loparjev",
    detailsTitle: "Podrobnosti izdelave",
    systemLead: "Teža in ravnotežje v stanju dobave. Merilna podlaga se vodi ločeno in še ni objavljena.",
    purposeTitle: "Namen",
    purpose: ["Vadba stika v sredini", "Zavedanje sweet spota", "Nadzor loparja", "Postopno obremenjevanje", "Razvoj pod vodstvom trenerja", "Prehod nazaj na igralčev zmogljivostni lopar"],
    heavy: "Model 400 g je nadzorovana vadbena izvedba. Ni samodejno priporočen otrokom, začetnikom ali vsakemu igralcu; obremenitev, trajanje in napredovanje določi trener.",
    precisionNote: "Zmogljivostni razredi natančnosti P2.5, P1.5 in P0.5 za to vadbeno družino ne veljajo samodejno. Tolerance vadbene proizvodnje sledijo lastni odobreni specifikaciji te družine.",
    health: "Ne obljubljamo preprečevanja ali zdravljenja teniškega komolca, odprave poškodb ali zagotovljenega napredka.",
    cta: "Zahtevajte predstavitev Sweet Spot Trainerja",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Vadba točke stika z majhno okroglo tarčo. Samostojen izdelek z lastno vizualno identiteto, zgrajen na odobreni podlagi štirih tež.",
    purposeTitle: "Potrjen namen",
    purposeP: "Naučiti igralca najti in ponoviti natančno točko stika.",
    weightsTitle: "Napredovanje tež",
    weightsP: "Napredovanje tež sledi odobreni težni podlagi Sweet Spot Trainerja. Vrednosti ravnotežja in druge specifikacije Sweet Spot Trainerja se na Spot Trainer ne prenašajo.",
    dims: "Natančne dimenzije tarče še niso objavljene.",
    grips: "Tovarniška arhitektura gripov L0–L7.",
    notes: ["Zmogljivostni razredi natančnosti ne veljajo samodejno.", "Ni pomanjšan običajen lopar in noben vzorec strun ni objavljen.", "Spot Trainer, Sweet Spot Trainer in katera koli ločena predstavitvena naprava ostanejo razločljivi."],
    cta: "Vprašajte o Spot Trainerju",
  },
  methodology: {
    title: "Metodologija in izkušnja z izdelkom",
    lead: "Oprema je en del strukturirane razvojne poti. Metoda se začne pri igralčevih ciljih, ne pri oznaki izdelka.",
    stepsTitle: "Razvojna pot",
    steps: [
      ["Postavitev ciljev", "Igralčevi cilji in izhodiščna točka."],
      ["Izbira opreme", "Primerna oprema, izbrana ob vključenosti trenerja."],
      ["Uporaba sistema", "Ustrezen sistem vadbe pod vodstvom trenerja."],
      ["Zapis", "Opažanja dejanskega sodelovanja, brez izmišljenih ocen."],
      ["Ponovna ocena", "Primerljive kontrolne točke."],
      ["Prilagoditev", "Prilagoditve nastavitve ali programa."],
      ["Prenos", "Naučeno prenesemo nazaj v tekmovalno igro."],
    ],
    educationTitle: "Izobraževalne poti",
    education: { player: "Igralci — razumevanje nastavitve, obremenitve in napredovanja.", parent: "Starši — kontinuiteta razvoja, primerna oprema, zapisi in pravice.", coach: "Trenerji — sistemi vadbe, prilagajanje loparja, ocenjevanje in pooblaščena uporaba programov." },
    evidenceTitle: "Disciplina dokazil",
    evidenceP: "Zapisi o dejanskem sodelovanju in opažanja se hranijo s svojo klasifikacijo — navedel udeleženec, potrdil skrbnik, potrdil trener ali izmeril sistem. Napredka, rezultatov in potrditev nikoli ne izmišljujemo.",
    experienceTitle: "Primite ga. Zamahnite z njim. Občutite ga.",
    experienceP: "Zahtevati je mogoče preizkus, prilagoditev loparja ali predstavitev s podporo trenerja. Poslano povpraševanje ni potrjen termin.",
    cta: "Zahtevajte prilagoditev ali predstavitev",
    cta2: "Povpraševanje za partnerstvo s trenerji",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — voden profil opreme",
    title: "MAXIMUS GPS",
    lead: "Voden profil opreme. Odgovorite samo na to, kar je za vas pomembno; odgovore preglejte in popravite; prejmete povzetek, smeri nastavitve, ki za vas veljajo, in resničen naslednji korak.",
    honesty: "V tej izdaji ni odobrenih samodejnih pravil za prilagajanje loparja. GPS zato pripravi jasen povzetek zahtev in pokaže smeri nastavitve; podrobnosti opreme se usmerijo v strokovno presojo.",
    rulesVersion: "Različica pravil",
    dataVersion: "Različica podatkov o izdelkih",
    steps: { role: "Vloga", sport: "Šport", experience: "Izkušnje", objectives: "Cilji", style: "Igralni slog", equipment: "Sedanja oprema", preference: "Želje", coach: "Vključenost trenerja", ageBand: "Starostna skupina", review: "Pregled" },
    notStored: "V tem brskalniku se ne shranjuje.",
    ageNote: "Uporablja se izključno za usmerjanje povpraševanja. Ime, datum rojstva in zdravstveni podatki se ne zahtevajo.",
    q: {
      role: "Kaj vas najbolje opisuje?",
      sport: "Kateri šport?",
      experience: "Raven izkušenj",
      objectives: "Kaj je najpomembnejše? (izberite do tri)",
      style: "Igralni slog, če ga poznate",
      equipment: "Sedanja oprema, če jo imate",
      equipmentHint: "Znamka in model, teža ali grip, če jih poznate. Neobvezno.",
      preference: "Želena nastavitev ali znana velikost gripa",
      grip: "Znana velikost gripa",
      coach: "Ali trener sodeluje pri odločitvah o vaši opremi?",
      ageBand: "Starostna skupina igralca (uporabi se samo za ustrezno usmerjanje povpraševanja)",
    },
    roles: { player: "Igralec", parent: "Starš ali skrbnik", coach: "Trener", club: "Klub ali akademija", other: "Drugo" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Drug šport z loparjem" },
    sportNote: "Izdelki obstajajo za tenis. Drugi športi so smeri razvoja; vaše zanimanje zabeležimo za ustrezen program.",
    experience: { beginner: "Začetnik", developing: "V razvoju", intermediate: "Srednje napreden", advanced: "Napreden", competitive: "Tekmovalen", professional: "Profesionalen" },
    objectives: { control: "Nadzor", power: "Moč", spin: "Rotacija", comfort: "Udobje", manoeuvrability: "Okretnost", development: "Dolgoročen razvoj", competition: "Tekmovanje", training: "Sistem vadbe", team: "Ekipa ali usklajen set", personal: "Personalizacija" },
    styles: { baseline: "Z osnovne črte", allcourt: "Univerzalen", attacking: "Napadalen", defensive: "Obramben", coach: "Izbere trener", unknown: "Ne vem" },
    ageBands: { u10: "Do 10 let", u14: "10–13", u18: "14–17", adult: "18 let in več" },
    output: {
      title: "Vaš profil opreme",
      status: "Potrebna je strokovna presoja",
      statusP: "V tej izdaji se samodejno ujemanje ne pripravi. Vaš profil je povzet za strokovno presojo.",
      directionsTitle: "Smeri nastavitve, ki veljajo",
      directionsP: "Na podlagi vaših navedenih ciljev in navedene igralne usmeritve vsake serije. To je smer, ne priporočilo za prilagoditev loparja.",
      trainingHint: "Med vašimi cilji je sistem vadbe: oglejte si Sweet Spot Trainer in Spot Trainer.",
      teamHint: "Usklajene sete se zahteva prek konfiguratorja in potrdi pisno.",
      next1: "Pošljite profil v strokovno presojo",
      show: "Prikaži moj profil",
      configure: "Nastavite",
      sendP: "Pošljite svoj profil MAXIMUS v strokovno presojo. Številka povpraševanja se prikaže takoj; odgovor pride pisno.",
      otherSport: "Loparji MAXIMUS obstajajo za tenis. Za druge športe z loparji nobena teniška serija ni predlagana; vaše zanimanje zabeležimo kot smer razvoja.",
      noDirection: "Vaši cilji ne kažejo na eno igralno usmeritev. Nastavitev predlaga strokovna presoja.",
      incomplete: "Nekateri obvezni odgovori manjkajo — dopolnite jih z „Uredi odgovore“.",
    },
    privacy: "GPS ne sprašuje po zdravstvenih podatkih in po nobenih podatkih za prepoznavo otrok. V tej seji brskalnika se hranijo samo odgovori z izbiro med možnostmi; prosto besedilo se ne shranjuje.",
  },
  build: {
    title: "Sestavite svojega",
    lead: "Sestavite povpraševanje: serija, razred natančnosti, navedena teža ali lastna ciljna vrednost, velikost gripa, zahtevane ciljne vrednosti, personalizacija, usklajeni seti in količina. Rezultat je povpraševanje za nastavitev s številko — ne šifra izdelka, cena, datum dobave ali potrdilo.",
    steps: { series: "Serija", cls: "Razred natančnosti", weight: "Teža", grip: "Velikost gripa", targets: "Ciljne vrednosti", personal: "Personalizacija", set: "Set in količina", use: "Uporaba", review: "Pregled" },
    q: {
      series: "Izberite serijo",
      cls: "Izberite razred natančnosti",
      weightMode: "Teža",
      listed: "Navedena teža",
      customWeight: "Zahtevana teža (g)",
      balanceShown: "Izračunano ravnotežje za to težo",
      balanceRequest: "Zahtevano ravnotežje (mm)",
      grip: "Tovarniška velikost gripa",
      targetsTitle: "Zahtevane ciljne vrednosti",
      swingweight: "Zahtevani swingweight (kg·cm²)",
      stiffness: "Zahtevana togost (RA)",
      basis: "Merilna podlaga za zahtevane vrednosti",
      engraving: "Besedilo gravure",
      engravingHint: "Ime, začetnice ali številka. Latinske črke, številke, presledek, vezaj, opuščaj in pika; do 24 znakov. Druge pisave sprejmemo s potrditvijo grafične predloge.",
      engravingType: "Personalizacija",
      types: { none: "Brez", name: "Ime igralca", initials: "Začetnice", number: "Številka seta", academy: "Oznaka trenerja ali akademije", team: "Ekipni program" },
      set: "Posamezen lopar ali usklajen set",
      use: "Predvidena uporaba",
      uses: { play: "Osebna igra", competition: "Tekmovanje", coaching: "Treniranje", team: "Ekipa ali akademija", retail: "Presoja za prodajo ali distribucijo", other: "Drugo" },
      notes: "Dodatne tehnične zahteve",
    },
    classes: { "P2.5": "P2.5 — nadgradljivo zmogljivostno jedro", "P1.5": "P1.5 — napredna natančnost", "P0.5": "P0.5 — profesionalno, posamično nadzorovano" },
    stiffExactShort: "togost ustreza navedeni ciljni vrednosti RA po uveljavljenem tovarniškem protokolu",
    clsNote: "Vsak razred nadzoruje štiri parametre. P0.5 je ozka toleranca po določenem merilnem protokolu — ne ničelna napaka. Serijska identiteta, potrdila in dokumentacija usklajenih setov veljajo samo tam, kjer jih program za vaše naročilo uvaja.",
    listedNote: "Iz potrjene matrike serije.",
    customNote: "Teža zunaj matrike, presojana tehnično.",
    balanceCaption: "Pri vsaki navedeni teži je prikazano izračunano ravnotežje v mm od konca ročaja. Izračunane vrednosti niso posamične meritve.",
    spinNote: "Teže serije SPIN tvorijo zahtevano težno arhitekturo. Ravnotežje, swingweight in togost za SPIN niso navedeni; opredelijo se v tehnični presoji.",
    customHint: "Celi grami, samo številke. Lastna teža je zahteva za tehnično presojo; izvedljivost se potrdi pisno in nobena vrednost se ne zaokroži.",
    gripNote: "tovarniška geometrija karbonskega ročaja, ne nadgradnja z ovojnimi trakovi",
    targetsLead: "Neobvezno. Vnesite samo vrednosti, ki jih potrebujete. Vsaka se zabeleži kot zahtevana ciljna vrednost za tehnično presojo, ne kot objavljena specifikacija.",
    basisHint: "Obvezno, kadar zahtevate lastno težo ali katero koli ciljno vrednost: se vrednosti nanašajo na lopar brez strun ali s strunami?",
    inputRange: "Sprejeti vnos: {min}–{max}.",
    inputRangeNote: "Razponi vnosa samo odfiltrirajo nemogoče vnose. Ne opisujejo proizvodne zmožnosti.",
    listedBasis: "navedene vrednosti — merilna podlaga se potrdi v pisni specifikaciji",
    notStored: "V tem brskalniku se ne shranjuje; po ponovnem nalaganju strani ga vnesite znova.",
    artworkReview: "potrebna je potrditev grafične predloge",
    previewNote: "Vizualni predogled ni prikazan: odobrena predloga gravure za ta model še ni objavljena. Vaše besedilo zbiramo za potrditev grafične predloge.",
    teamSub: "4–99 loparjev na set",
    setsLabel: { individual: "Število loparjev", pair: "Število usklajenih parov", triple: "Število usklajenih trojic", team: "Število ekipnih setov" },
    teamSizeLabel: "Loparjev na ekipni set",
    totalLabel: "Loparjev skupaj",
    racquetsUnit: "loparjev",
    setRule: "Količina šteje sete: usklajen par sta 2 loparja na set, usklajena trojica 3.",
    restart: "Začnite novo nastavitev",
    notices: { weightCleared: "{w} g ni v matriki serije {series}, zato je bila teža izbrisana. Izberite navedeno težo ali zahtevajte lastno ciljno vrednost." },
    reviewTitle: "Povpraševanje za nastavitev",
    reviewP: "Preverite nastavitev, nato dodajte svoje kontaktne podatke. Povpraševanje se shrani s številko in odgovor pride pisno; razpoložljivost in poslovni pogoji se potrdijo pisno.",
    reviewErrors: "Nekateri odgovori v nastavitvi potrebujejo pozornost:",
    edit: "Uredi",
    fieldNames: { series: "Serija", cls: "Razred natančnosti", mode: "Izbira teže", weight: "Navedena teža", customWeight: "Zahtevana teža", basis: "Merilna podlaga", balanceReq: "Zahtevano ravnotežje", sw: "Zahtevani swingweight", ra: "Zahtevana togost", grip: "Velikost gripa", ptype: "Personalizacija", engraving: "Besedilo gravure", setType: "Vrsta seta", sets: "Količina", teamSize: "Loparjev na ekipni set", use: "Predvidena uporaba", notes: "Dodatne zahteve" },
    status: { listed: "navedena teža", requestedArchitecture: "zahtevana težna arhitektura", technicalReview: "zahteva za tehnično presojo", notPublished: "ni navedeno", requestedCondition: "zahtevano stanje" },
    chooseLink: "Niste prepričani, katera serija vam ustreza? Pomagamo vam izbrati",
    cta: "Pošljite povpraševanje za nastavitev",
  },
  experience: {
    title: "Preizkus in prilagoditev",
    statement: "Primite ga. Zamahnite z njim. Občutite ga.",
    lead: "Zahtevajte preizkus, prilagoditev loparja ali predstavitev s podporo trenerja. Povpraševanja presojamo in odgovarjamo pisno; poslano povpraševanje ni potrjen termin.",
    optionsTitle: "Kaj je mogoče zahtevati",
    options: ["Preizkus loparja", "Srečanje za prilagoditev loparja", "Predstavitev s podporo trenerja", "Predstavitev Sweet Spot Trainerja ali Spot Trainerja", "Predstavitveni dan za ekipo ali akademijo"],
    formTitle: "Povpraševanje za prilagoditev ali predstavitev",
  },
  engineering: {
    title: "Inženirstvo in proizvodnja",
    statement: "Letala. Jahte. Loparji.",
    lead: "Ena inženirska filozofija v treh okoljih: načela, ki oblikujejo letalo, natančnost, ki vodi jahto po odprtem morju, in zmogljivost, ki opredeljuje vsak lopar MAXIMUS. To je inženirska pripoved — ne trditev o letalski certifikaciji, lastništvu jaht, lastništvu tovarne ali neposrednem prenosu materialov.",
    manifesto: ["Verjamemo, da odlično inženirstvo ne pozna meja.", "Ena filozofija. Razvito brez kompromisov."],
    capabilityTitle: "Proizvodna zmožnost",
    capabilityLead: "Zmožnost prikazujemo kot zaporedje, ne kot slogan.",
    sequence: [
      ["Specifikacija", "Serija, razred natančnosti, teža, ravnotežje, swingweight, ciljna togost, geometrija gripa, personalizacija."],
      ["Proizvodnja", "V celoti karbonska izdelava od okvirja do ročaja, izdelana po specifikaciji."],
      ["Kontrola kakovosti", "Meritve in zapisi po razredu natančnosti: proizvodni zapisi, posamični zapisi in sledljivost, posamično potrjevanje."],
      ["Ponovljiva proizvodnja", "Ponovljiv odziv glede na navedeno specifikacijo med šaržami."],
      ["Sledljivost", "Serijska identiteta, sledljivost šarže in potrdilo o natančnosti tam, kjer ga razred predvideva."],
    ],
    capacityNote: "Proizvodna zmogljivost, dobavni roki, najmanjše količine in načrti dobav se za vsak program pisno potrdijo glede na potrjena naročila in dogovorjen načrt sproščanja.",
    truth: "Zmogljivost ni proizvodnja, zaloga, zagotovljen datum dobave ali lastništvo proizvodnega obrata.",
    cta: "Distribucija in razvoj držav",
    cta2: "Pošljite tehnično zahtevo",
  },
  ecosystem: {
    title: "Ekosistem MAXIMUS",
    lead: "En ključ. To je tisto, kar odpira. Vsako vozlišče ima razlago, točno stanje in ustrezen naslednji korak.",
    words: ["Inženirstvo", "Zmogljivost", "Inovacije", "Skupnost", "Priložnost", "Namen"],
    nodes: {
      engineering: { h: "Inženirstvo in proizvodnja loparjev", p: "V celoti karbonski loparji, razviti po specifikaciji, izdelani z zapisi kakovosti in sledljivostjo.", a: "Inženirstvo in proizvodnja" },
      precision: { h: "Natančnost in posamična nastavitev", p: "Štirje parametri, trije razredi natančnosti, osem velikosti gripov in inženirstvo po meri.", a: "Natančnost in togost" },
      training: { h: "Vadba in metodologija", p: "Sweet Spot Trainer, Spot Trainer in strukturirana razvojna pot.", a: "Sistemi vadbe" },
      development: { h: "Razvoj igralcev in trenerjev", p: "Izbira pod vodstvom trenerja, zapisi, ponovna ocena in izobraževalne poti.", a: "Metodologija" },
      identity: { h: "Osebna identiteta in osebne znamke", p: "Od gravure do osebne ali poklicne znamke z urejenimi pravicami.", a: "Osebne znamke" },
      owners: { h: "Zapisi lastnikov, znanje in pravice", p: "Predlagan trezor lastnika z nadzorovanim dostopom za zapise o opremi, razvoju in pravicah.", a: "Lastniki in trezor" },
      mipa: { h: "MIPA — izvor in interni nadzor", p: "Interna plast za intelektualno lastnino, izvor in nadzor dokumentov.", a: "Pravna identiteta in nadzor" },
      digital: { h: "Digitalna infrastruktura in smer Blockchain 5.0", p: "Izvor, sledljivi zapisi, dokazila z nadzorovanim dostopom in identiteta izdelka kot navedena tehnološka smer.", a: "Tehnološka smer" },
      licensing: { h: "Pogodbeno licenciranje in programi licenčnin", p: "Licencirane znamke, izdelki in paketi pravic s pogoji, opredeljenimi v vsaki pogodbi.", a: "Licenčne poti" },
      families: { h: "Sodelovanje družine in koristi programa", p: "Premišljene odločitve, kontinuiteta, ohranjeni zapisi in koristi, opredeljene s programom.", a: "Družine in starši" },
      network: { h: "MAXIMUS Sports Network", p: "Igralci, trenerji, klubi, akademije, ponudniki storitev, izvajalci programov in regionalni partnerji.", a: "Sports Network" },
      market: { h: "Klubi, akademije, distribucija in razvoj držav", p: "Ekipni programi, prodaja, distribucija in razvoj ozemelj na podlagi pisne kvalifikacije.", a: "Partnerske poti" },
      institutional: { h: "Institucionalni programi, izobraževanje, inovacije in družbeni učinek", p: "Institucionalno plast zagotavlja MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, kjer program to vlogo vzpostavi.", a: "Institucionalni programi" },
      extensions: { h: "Prihodnje širitve na športe z loparji in oblačila MAXIMUS", p: "Padel, pickleball, squash, badminton, racquetball, plažni tenis in oblačila kot smeri razvoja.", a: "Športi z loparji" },
    },
    boundaryTitle: "Meje",
    boundary: [
      "Nakup loparja ne ustvarja institucionalnega članstva, upravljavskih pravic, licenčnin ali naložbenih pravic.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) je institucionalni izvajalec samo tam, kjer program to vlogo vzpostavi; prodaja opreme navede svoj dejanski pogodbeni subjekt.",
      "Nepovratna sredstva, status nepridobitne organizacije, davčna obravnava in regulatorna dovoljenja med državami ne veljajo samodejno.",
    ],
    techTitle: "Tehnološka smer",
    techP: "Blockchain 5.0 je navedena tehnološka smer MAXIMUS. Njegovi funkcionalni nameni so izvor, sledljivi zapisi, dokazila z nadzorovanim dostopom, identiteta izdelka in uskladitev kvalificiranih poslovnih dogodkov. Noben mehanizem soglasja, transakcijska zmogljivost, omrežje vozlišč, naslov pametne pogodbe, žeton ali neodvisno potrjevanje niso predstavljeni in nobena uvedena rešitev ni zatrjevana. Osebni podatki, zapisi o otrocih in zaupne pogodbe se privzeto nikoli ne vnesejo v javni nespremenljivi sistem.",
  },
  brands: {
    title: "Osebne znamke in ambasadorji",
    statement: "Od igralca do znamke. Od trenerja do znamke.",
    lead: "Namenska pot za osebno znamko. Vključenost MAXIMUS zajema razvoj znamke in dogovorjeno promocijo — ne le imena na loparju.",
    progressionTitle: "Predvideno napredovanje",
    progression: [
      ["Preverjena identiteta", "Preverjena identiteta in razvojna zgodovina."],
      ["Razpoznavna znamka", "Razpoznavna osebna ali poklicna znamka."],
      ["Vsebina z urejenimi pravicami", "Vsebina z urejenimi pravicami in odobrena identiteta izdelka."],
      ["Inženirstvo in kolekcije", "Inženirstvo in razvoj kolekcij tam, kjer je dogovorjeno."],
      ["Promocija", "Promocija prek dogovorjenih kanalov in partnerstev MAXIMUS."],
      ["Udeležba", "Pogodbena udeležba pri kvalificirani prodaji ali licenciranju."],
      ["Poročanje", "Pregledno poročanje po pogodbi."],
    ],
    royaltiesTitle: "Licenčnine in licenciranje",
    royalties: [
      "Licenčnine se vežejo na opredeljeno licencirano znamko, izdelek, transakcijo ali paket pravic.",
      "„Svetovna prodaja“ pomeni kvalificirano prodajo v obsegu pogodbe — nikoli vsakega nepovezanega loparja MAXIMUS.",
      "Stopnje, osnova za izračun, ozemlja, trajanje, vračila, odbitki, poročanje, poravnava in preverjanje so opredeljeni v ustrezni pogodbi. Nobena privzeta odstotna stopnja ni objavljena.",
      "Brez dogovorjenega obsega niso obljubljeni nobena svetovna kampanja, medijski proračun, sponzorski izid ali poslovni uspeh.",
    ],
    cta: "Pošljite povpraševanje za sodelovanje pri znamki",
    cta2: "Povpraševanje za partnerstvo s trenerji",
  },
  families: {
    title: "Družine in starši",
    lead: "Premišljene odločitve o opremi, kontinuiteta razvoja, ohranjeno znanje in pravice, pregled nad sodelovanjem ter koristi, opredeljene s programom, ki lahko podprejo prihodnje dejavnosti.",
    nowTitle: "Na voljo zdaj",
    now: ["Družinska in razvojna povpraševanja pisno.", "Izbira opreme ob vključenosti trenerja, povpraševanja za prilagoditev loparja in predstavitve.", "Zasebni zapisi: profili otrok niso nikoli objavljeni in se privzeto nikoli ne tržijo.", "Izobraževalna pot za starše: nastavitev, obremenitev, napredovanje, zapisi in pravice."],
    plannedTitle: "Načrtovano",
    planned: ["Koristi sodelovanja, opredeljene s programom, uporabne za blago in storitve v ekosistemu, in ne denarne obresti.", "Zapisi lastnika in družine v predlaganem trezorju lastnika s skrbniškimi dovoljenji in prenosom nadzora pri 18 letih."],
    categoriesTitle: "Vodeno ločeno",
    categories: ["Pogodbene licenčnine iz licenciranih pravic ali kvalificirane prodaje", "Koristi sodelovanja, opredeljene s programom", "Dobropisi za nakup ali storitve", "Predplačila", "Institucionalno članstvo"],
    categoriesP: "Te kategorije nikoli ne veljajo za medsebojno zamenljive.",
    statusTitle: "Dejansko stanje družinskega programa",
    journeyTitle: "Pot za družine",
    journey: [
      ["Cilj", "Kaj želi igralec doseči v naslednjem koraku."],
      ["Sedanja raven", "Kje je igralec danes."],
      ["Trener", "Ali trener sodeluje pri odločitvah o opremi."],
      ["Oprema", "Primerna oprema za to stopnjo, vključno s sistemi vadbe, kadar so pomembni."],
      ["Dogovorjena vadba", "Uporaba pod vodstvom trenerja, dogovorjena vnaprej."],
      ["Pregled", "Ponovna ocena v primerljivih kontrolnih točkah."],
    ],
    brief: {
      who: "Starši in skrbniki igralcev na vseh stopnjah.",
      value: "Pisni odgovor o primerni opremi, vključenosti trenerja in naslednjem razvojnem koraku.",
      now: "Družinska povpraševanja pisno; izbira ob vključenosti trenerja; zasebni zapisi — profili otrok niso nikoli objavljeni.",
      next: "Pošljite družinsko povpraševanje spodaj. Številko povpraševanja prejmete takoj.",
    },
    formTitle: "Družinsko povpraševanje",
    formNote: "Izpolni ga starš ali skrbnik. Ne navajajte otrokovega imena, datuma rojstva, šole ali zdravstvenih podatkov.",
    noPromise: "Nakup ne obljublja licenčnin, naložbenih donosov, sponzorstva ali financiranja otrokovega razvoja.",
    statusP: "Ta izdaja razloži model in sprejema povpraševanja o programu. Pripisovanje, izplačila in unovčenje niso na voljo, dokler niso pisno opredeljeni kvalificirani dogodki, upravičenci, vir sredstev, osnova za izračun, dovoljene uporabe, računovodska obravnava, vračila, razveljavitve, iztek, prenosljivost, zaprtje programa in reševanje sporov. Noben saldo ni obljubljen, da nikoli ne bo padel, nobena udeležba ne plača celotne vadbe in nobena zaščita kapitala ni nakazana.",
    cta: "Pošljite družinsko ali razvojno povpraševanje",
  },
  owners: {
    title: "Lastniki in trezor lastnika",
    lead: "Trezor lastnika je predlagan zapis z nadzorovanim dostopom za opremo, razvoj, znanje, vsebino in dokumentirane pravice. Predstavljen je kot del načrtovane arhitekture za lastnike: nobeni delujoči računi, saldi, potrdila ali dosežki niso prikazani.",
    nowTitle: "Za sedanje lastnike zdaj",
    now: ["Povpraševanja lastnikov: sklic na izdelek ali serijsko številko, nastavitev, servis in zahteve za zapise pisno.", "Potrdilo o natančnosti in dokumentacija usklajenega seta tam, kjer ju razred natančnosti predvideva, dobavljena z izdelkom."],
    archTitle: "Načrtovana arhitektura trezorja",
    arch: ["Identiteta izdelka in serijski sklici", "Nastavitev in ustrezna potrdila kontrole kakovosti", "Zgodovina servisa in nastavitev", "Razvojni zapisi igralca ali trenerja", "Kvalifikacije in preverjeni dosežki", "Mediji z urejenimi pravicami in avtorska gradiva", "Licence, dovoljenja in sklici na pogodbe", "Zapisi programa osebne znamke", "Ustrezni obračuni licenčnin ali koristi sodelovanja"],
    separationTitle: "Kaj pomeni lastništvo",
    separation: [
      "Lastništvo fizičnega loparja je ločeno od lastništva avtorske pravice, licence, pogodbenega upravičenja ali zapisa, ki te stvari opisuje.",
      "Shranjen dokument ali vnos v verigo blokov ni samodejno dokaz, da pravica obstaja ali da je bila prenesena.",
      "Dokazila ohranijo svojo klasifikacijo: navedel udeleženec, potrdil skrbnik, potrdil trener, izmeril sistem.",
      "Za mladoletne: zasebni zapisi, skrbniška dovoljenja, nobenih objavljenih profilov otrok in privzeto nobenega trženja identitete.",
      "Izvoz, popravek, nadzor dostopa in ustrezen prenos nadzora so del zasnove.",
    ],
    techTitle: "Blockchain 5.0 in MxSN",
    techP: "Blockchain 5.0 je navedena tehnološka smer; MxSN opredeljuje zasnovo omrežja z nadzorovanim dostopom za soglasje, dostavo, dokazila, pravice in poročanje. Operativna uvedba ni predstavljena. Podatkovni model aplikacije je zgrajen tako, da se pozneje poveže prek dokumentiranega vmesnika, brez pretvarjanja, da povezava danes obstaja.",
    cta: "Povpraševanje lastnika",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Povezava med igralci, trenerji, klubi, akademijami, ponudniki storitev, izvajalci programov in regionalnimi partnerji.",
    functionsTitle: "Možne funkcije",
    functions: ["Iskanje", "Predstavitve", "Razvojni programi", "Podpora pri opremi", "Dogodki", "Dostop do storitev", "Partnerske priložnosti"],
    statusTitle: "Dejansko stanje",
    statusP: "Javni imenik še ni objavljen: navedeni bodo samo udeleženci, pri katerih so ugotovljeni identiteta, razmerje in dovoljenje za objavo. Predlog, poslan klubu, ni partnerstvo, možni distributer pa ni imenovani distributer. Objava imenika, rezervacije, sporočanje in poslovne transakcije se nadzirajo ločeno in niso v delovanju.",
    cta: "Prijavite se v mrežo",
  },
  partnerships: {
    title: "Partnerske poti",
    lead: "Najprej pisna kvalifikacija. Vsaka pot vodi do povpraševanja glede na vlogo; poslovni pogoji sledijo pisno.",
    commercialTitle: "Možne poslovne dejavnosti platforme",
    commercial: ["Oprema", "Inženirstvo po meri", "Personalizacija", "Ekipni in akademijski programi", "Sistemi vadbe", "Pogodbeno licenciranje", "Distribucija", "Odobrene storitve", "Prihodnje kategorije izdelkov"],
    boundary: "Pravice za državo, izključnost, pristojbine za ozemlje in marže distributerjev so predmet pogajanj. Nobeni prihodki, napovedi, vrednotenja, tržni deleži, donosi, zaveze o financiranju ali neimenovana partnerstva niso objavljeni.",
    routes: {
      coaches: {
        title: "Trenerji",
        lead: "Sistemi vadbe, prilagajanje loparjev, poklicna identiteta, pooblaščeni programi, priložnosti osebne znamke in dobava opreme.",
        points: ["Sweet Spot Trainer in Spot Trainer v vadbi pod vodstvom trenerja.", "Prilagajanje loparja z matrikami nastavitev in osmimi tovarniškimi velikostmi gripov.", "Coach-to-Brand: preverjen poklicni profil in podznamka z urejenimi pravicami.", "Pooblaščena uporaba programov sledi pisni pogodbi."],
        cta: "Pošljite povpraševanje za partnerstvo s trenerji",
        brief: {
          who: "Samostojni trenerji in trenerske ekipe.",
          value: "Sistemi vadbe za delo pod vodstvom trenerja, prilagajanje loparja z matrikami serij in osmimi tovarniškimi gripi ter pot do poklicne identitete.",
          now: "Povpraševanja trenerjev pisno. Nobena provizija, zaslužek ali stopnja za priporočilo ni objavljena ali nakazana.",
          next: "Pošljite povpraševanje trenerja spodaj. Pogoji sledijo pisno.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubi in akademije",
        lead: "Ekipna oprema, sistemi vadbe, personalizacija, razvojni programi, servis in sodelovanje v mreži.",
        points: ["Ekipni in usklajeni seti, zahtevani prek konfiguratorja.", "Sistemi vadbe in metodologija za strukturiran razvoj.", "Personalizacija za ekipne programe na odobrenih območjih.", "Predstavitveni dnevi, srečanja za prilagoditev loparjev in sodelovanje v mreži."],
        cta: "Pošljite zahtevo kluba ali akademije",
        brief: {
          who: "Klubi, akademije in ekipni programi.",
          value: "Ekipni in usklajeni seti, sistemi vadbe, personalizacija za ekipne programe in predstavitveni dnevi.",
          now: "Zahteve klubov in akademij pisno; ekipne sete se zahteva prek konfiguratorja.",
          next: "Pošljite zahtevo kluba ali akademije spodaj.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribucija in razvoj držav",
        lead: "Asortiment, usklajevanje proizvodnje, tehnična zmožnost, razvoj ozemelj in zaupna poslovna kvalifikacija.",
        points: ["Pisna kvalifikacija nasprotne stranke, ozemlja in kanala.", "Asortiment, opredeljen iz matrik nastavitev in razredov natančnosti.", "Ozemlje, izključnost, količine, cene in poslovna zaščita so predmet pogajanj in se dogovorijo pisno.", "Pogodbeni subjekt, plačilni pogoji in dobavna podlaga se določijo pri vsaki transakciji."],
        cta: "Pošljite povpraševanje za distribucijo ali razvoj države",
        brief: {
          who: "Trgovci, distributerji in partnerji za posamezne države.",
          value: "Asortiment, opredeljen iz potrjenih matrik, razredov natančnosti in linije gripov, s pisno kvalifikacijo ozemlja in kanala.",
          now: "Povpraševanja za distribucijo pisno. Ozemlje, izključnost, količine in cene so predmet pogajanj — nič od tega ni dodeljeno prek obrazca.",
          next: "Pošljite povpraševanje za distribucijo spodaj.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strateško sodelovanje in naložbe",
        lead: "Inženirska zmožnost, globina nastavitev, proizvodni model, poti na trg, intelektualna lastnina, storitve in priložnosti za širitev.",
        points: ["Kvalificiran strateški pogovor ali nadzorovan dostop do informacij sledi pisni kvalifikaciji.", "Javne informacije so omejene na odobrene specifikacije izdelkov, arhitekturo nastavitev, preverjene zmožnosti in razlage programov.", "Ekonomika posameznega kupca, izračuni stroškov, zaščitena metodologija in neobjavljene pogodbe se razkrijejo samo na podlagi NDA ali pogodbe."],
        cta: "Zahtevajte kvalificiran strateški pogovor",
        brief: {
          who: "Vlagatelji in strateški partnerji.",
          value: "Kvalificiran pogovor o inženirski zmožnosti, globini nastavitev, proizvodnem modelu, poteh na trg in intelektualni lastnini.",
          now: "Nobeni finančni podatki, napovedi, vrednotenja ali donosi niso objavljeni. Nadzorovane informacije sledijo pisni kvalifikaciji in NDA.",
          next: "Zahtevajte kvalificiran strateški pogovor spodaj.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institucionalni programi",
        lead: "Izobraževanje, dostop, inovacije, dokazila o razvoju, družbeni učinek in ustrezno strukturirani programi.",
        points: ["Institucionalni programi so strukturirani prek MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tam, kjer program to vlogo vzpostavi.", "Namenska programska sredstva in poslovne transakcije ostanejo ločeni.", "Povpraševanje ni sprejeta prijava za članstvo, kupec opreme pa ni institucionalni član.", "Nepovratna sredstva, status nepridobitne organizacije, davčna obravnava in regulatorna dovoljenja so odvisni od države in nikoli niso predpostavljeni."],
        cta: "Pošljite povpraševanje za institucionalni program",
        brief: {
          who: "Institucije, izobraževalni in razvojni programi.",
          value: "Programi za izobraževanje, dostop, inovacije in dokazila o razvoju, strukturirani z ustreznim izvajalcem.",
          now: "Institucionalna povpraševanja pisno. Povpraševanje ni prijava za članstvo; nakup opreme ni institucionalno članstvo.",
          next: "Pošljite institucionalno povpraševanje spodaj.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Javno in nadzorovano razkritje",
    disclosure: {
      public: { h: "Javno", p: "Odobrene specifikacije izdelkov, izdelava, arhitektura nastavitev, nameni vadbe, preverjene zmožnosti, razlage programov in partnerske poti." },
      qualified: { h: "Kvalificirano povpraševanje", p: "Tehnične zahteve, količine, zanimanje za ozemlje, obseg razvoja in ustrezni poslovni pogovori." },
      controlled: { h: "Nadzorovano z NDA ali pogodbo", p: "Interne formule, podrobni protokoli kontrole kakovosti, laminati, orodja, proizvodne metode, identiteta dobaviteljev, izračuni stroškov, ekonomika posameznega kupca, zaščitena metodologija, neobjavljene pogodbe in občutljivi zapisi o pravicah." },
    },
  },
  contact: {
    title: "Stik in povpraševanja",
    lead: "Izberite namen svojega povpraševanja. Vsak obrazec zbere samo tisto, kar je potrebno za usmeritev in presojo. Na povpraševanja odgovarjamo pisno.",
    email: "E-pošta",
    instagram: "Instagram",
    legalLink: "Pravna identiteta",
  },
  form: {
    purposeLabel: "Namen povpraševanja",
    purposes: {
      selection: "Pomoč pri izbiri loparja",
      product: "Vprašanje o izdelku",
      fitting: "Prilagoditev ali predstavitev",
      technical: "Tehnična zahteva",
      config: "Povpraševanje za nastavitev",
      gps: "Profil opreme GPS",
      coach: "Partnerstvo s trenerji",
      club: "Zahteva kluba ali akademije",
      distribution: "Distribucija ali razvoj države",
      brand: "Sodelovanje pri znamki ali ambasadorstvo",
      family: "Družinsko ali razvojno povpraševanje",
      institutional: "Institucionalni program",
      strategic: "Strateški ali naložbeni pogovor",
      owner: "Povpraševanje lastnika",
      network: "Prijava v Sports Network",
      general: "Splošno vprašanje",
    },
    fields: {
      name: "Ime",
      email: "E-pošta",
      role: "Vaša vloga",
      country: "Država ali regija",
      organisation: "Organizacija",
      message: "Vaše sporočilo",
      level: "Sedanja raven",
      objectives: "Kaj je najpomembnejše (do tri)",
      currentRacquet: "Sedanji lopar",
      grip: "Velikost gripa, če jo poznate",
      seriesInterest: "Serija, ki vas zanima",
      quantity: "Količina",
      city: "Mesto ali kraj srečanja",
      coachInvolved: "Ali je trener vključen?",
      timing: "Želeni termin",
      targets: "Želene ciljne vrednosti",
      limits: "Obvezne omejitve",
      use: "Predvidena uporaba",
      tradeoffs: "Sprejemljivi kompromisi",
      basis: "Merilna podlaga",
      players: "Število igralcev",
      interests: "Področja zanimanja",
      territory: "Ozemlje, ki vas zanima",
      channels: "Obstoječi kanali in izkušnje",
      audience: "Občinstvo ali disciplina",
      proposal: "Predlagano sodelovanje",
      goal: "Razvojni cilj",
      ageBand: "Starostna skupina igralca",
      scope: "Obseg programa",
      interestArea: "Področje zanimanja",
      productRef: "Sklic na izdelek ali serijsko številko",
      requestType: "Vrsta povpraševanja",
      seeking: "Kaj iščete",
      consent: "Soglašam, da MAXIMUS te podatke hrani in uporabi za odgovor na to povpraševanje. To ni naročnina na marketinška sporočila.",
    },
    roles: { player: "Igralec", parent: "Starš ali skrbnik", coach: "Trener", club: "Klub ali akademija", retailer: "Trgovec", distributor: "Distributer", brand: "Znamka ali ambasador", investor: "Vlagatelj ali strateški partner", institution: "Institucija", other: "Drugo" },
    interestOptions: { training: "Sistemi vadbe", fitting: "Prilagajanje loparja", identity: "Poklicna identiteta", programmes: "Pooblaščeni programi", brand: "Osebna znamka", supply: "Dobava opreme", team: "Ekipna oprema", personalisation: "Personalizacija", development: "Razvojni programi", service: "Servis", network: "Sodelovanje v mreži" },
    ownerTypes: { setup: "Nastavitev in konfiguracija", service: "Servis", records: "Zapisi in potrdila", other: "Drugo" },
    strategicAreas: { engineering: "Inženirska zmožnost", configuration: "Globina nastavitev", manufacturing: "Proizvodni model", routes: "Poti na trg", ip: "Intelektualna lastnina in storitve", expansion: "Priložnosti za širitev" },
    errors: {
      required: "To polje je obvezno.",
      too_long: "Ta vnos je predolg.",
      too_short: "Ta vnos je prekratek.",
      invalid_email: "Vnesite veljaven e-poštni naslov, na primer ime@example.com.",
      invalid_choice: "Izberite eno od možnosti.",
      not_number: "Vnesite celo število samo s številkami.",
      out_of_range: "Ta vrednost je zunaj sprejetega razpona.",
      not_in_matrix: "Te teže ni v navedeni matriki izbrane serije.",
      decimal_not_supported: "Vnesite celo število brez decimalnih mest.",
      too_many: "Izberite največ tri možnosti.",
      consent_required: "Soglasje je potrebno, da lahko MAXIMUS odgovori na to povpraševanje.",
      invalid: "Ta vnos ni veljaven.",
    },
  },
  legal: {
    title: "Pravna identiteta in nadzor",
    lead: "Javna znamka je MAXIMUS / MAXIMUS GPS. Pravne poslovne identitete so razločljive in so navedene tukaj.",
    entities: {
      institutional: { role: "Plast institucionalnih programov", p: "Zagotavlja plast institucionalnih programov tam, kjer program to vlogo vzpostavi. Ni poslovni prodajalec loparjev. Nepridobitna registrirana organizacija v Dubai International Financial Centre." },
      equipment: { role: "Poslovni subjekt za opremo", p: "Poslovni subjekt za opremo za dobavo, distribucijo in pogodbeno poslovno izvedbo tam, kjer to vlogo vzpostavljajo veljavni poslovni dokumenti. Pogodbena stranka vsake transakcije je navedena v dokumentih te transakcije." },
      ip: { role: "Intelektualna lastnina, znamka in poslovno usklajevanje", p: "Nastopa v vzpostavljeni vlogi za intelektualno lastnino, znamko ali poslovno usklajevanje. Nobena nepotrjena pogodbena odgovornost ni dodeljena." },
      stewardship: { role: "Sklic na skrbništvo", p: "House of Maximus je skrbniški sklic ekosistema tam, kjer to podpira ustrezen vir." },
      control: { role: "Interna intelektualna lastnina, izvor in nadzor dokumentov", p: "MIPA je interna plast za intelektualno lastnino, izvor in nadzor dokumentov. Interni vnos MIPA se razlikuje od zunanje registracije blagovne znamke, patenta ali avtorske pravice in od sodnega priznanja ter ne pomeni odobritve vizualne podobe." },
    },
    labels: { licence: "Licenca", registration: "Registracija", vat: "VAT TRN", address: "Naslov", email: "E-pošta", jurisdiction: "Jurisdikcija" },
    boundaryTitle: "Meje",
    boundary: [
      "Nakup samodejno ne podeli institucionalnega članstva, upravljavskih pravic, licenčnin ali naložbenih pravic.",
      "Institucionalna vloga je ločena od poslovnih transakcij z opremo.",
      "Zasebnost, pogoji programov in ureditve nadzorovanega dostopa ustrezajo dejansko izdanim funkcijam.",
      "Nobena splošna navedba prava, ki se uporablja, ne velja za vsakega obiskovalca, prodajo ali tuji program; pogodbena podlaga se določi v vsaki pogodbi.",
    ],
  },
  privacy: {
    title: "Zasebnost",
    updated: "Različica 2026-09-21 · spletno mesto 4.2",
    contactTitle: "Stik za vprašanja o zasebnosti",
    sections: {
      collect: ["Kaj se zbira", "Ko pošljete obrazec: podatki, ki jih vnesete (ime, e-pošta, vloga, država ali regija, organizacija, če jo navedete, vaše sporočilo in odgovori v obrazcu), stran in parametri kampanje vašega obiska (vstopna stran, jezik, parametri utm; identifikatorji oglasnih klikov samo, če ste dovolili analitiko) ter čas pošiljanja. Vaš naslov IP se uporablja samo v zgoščeni in kratkotrajni obliki za omejevanje zlorab in se ne shranjuje skupaj z vašim povpraševanjem."],
      purpose: ["Zakaj", "Da odgovorimo na vaše povpraševanje, pripravimo ponudbo ali specifikacijo, za katero ste zaprosili, in vodimo zapis o povpraševanju. Na podlagi obrazca ne pošiljamo marketinških sporočil."],
      storageOn: ["Kje se povpraševanja shranjujejo", "Povpraševanja se shranjujejo v zbirki podatkov družbe Upstash, Inc. (Redis), ki je zagotovljena prek platforme za gostovanje Vercel Inc."],
      notifyEmail: ["Obvestilo o novem povpraševanju", "Ko je povpraševanje sprejeto, se obvestilo s podatki, ki ste jih poslali, pošlje po e-pošti v odgovorni poštni predal MAXIMUS."],
      notifyTelegram: ["Obvestilo o novem povpraševanju", "Ko je povpraševanje sprejeto, se obvestilo s podatki, ki ste jih poslali, pošlje odgovorni osebi v MAXIMUS prek Telegrama (Telegram FZ-LLC, Dubaj), ki to obvestilo med prenosom obdeluje."],
      notifyWebhook: ["Obvestilo o novem povpraševanju", "Ko je povpraševanje sprejeto, se obvestilo s podatki, ki ste jih poslali, pošlje na interno končno točko MAXIMUS prek podpisane in šifrirane povezave."],
      notifyNone: ["Obvestilo o novem povpraševanju", "Obveščanje o novih povpraševanjih se vzpostavlja. Vaše povpraševanje se shrani, MAXIMUS pa ga prebere iz internega registra; za ta namen se tretji osebi ne pošlje nič."],
      storageOff: ["Kje se povpraševanja shranjujejo", "Shranjevanje povpraševanj se vzpostavlja. Dokler ni aktivno, obrazci navajajo, da povpraševanja ni mogoče sprejeti; nič se ne shrani. Spletno mesto gostuje Vercel Inc."],
      browser: ["Shramba brskalnika", "Shramba seje hrani odgovore z izbiro med možnostmi iz GPS in konfiguratorja ter parametre kampanje vašega obiska za to sejo brskalnika. Kontaktni podatki, prosto besedilo, besedilo gravure in podatki o otrocih se v brskalniku ne shranjujejo."],
      analyticsOn: ["Analitika", "Z vašim soglasjem Google Analytics 4 meri obiske in dogodke obrazcev brez kontaktnih podatkov in brez besedila povpraševanja. Vaša izbira se hrani v lokalni shrambi in jo lahko kadar koli spremenite pod „Nastavitve analitike“ v nogi strani. Obrazci delujejo tudi brez analitike."],
      analyticsOff: ["Analitika", "Na tem spletnem mestu ni dejavnega nobenega analitičnega orodja."],
      retention: ["Hramba", "Samodejno obdobje brisanja še ni nastavljeno. Izbris svojega povpraševanja lahko zahtevate kadar koli."],
      children: ["Otroci", "Obrazce mora izpolniti odrasla oseba. Povpraševanja za igralce, mlajše od 18 let, oddata starš ali skrbnik. Ne pošiljajte otrokovega imena, datuma rojstva, šole ali zdravstvenih podatkov. Profili otrok niso nikoli objavljeni."],
      rights: ["Vaše pravice", "Za dostop do svojega povpraševanja, njegov popravek ali izbris pišite na gps@maximus.tennis in navedite številko povpraševanja."],
      controlled: ["Nadzorovane informacije", "Zaupni dokumenti se na tem spletnem mestu ne shranjujejo in z njega niso dostavljeni. Nadzorovano razkritje poteka na podlagi NDA ali pogodbe po ločenih kanalih."],
    },
  },
  terms: {
    title: "Pogoji uporabe",
    copyright: "Avtorska pravica na tem spletnem mestu — na njegovih besedilih, fotografijah, oblikovanju in kodi — pripada izključno Maximusu Kiriyakulovu. Ni bila prenesena na nobeno družbo in na nobeno drugo osebo.",
    updated: "Različica 2026-09-21",
    sections: [
      ["Informacija, ne ponudba", "Informacije o izdelkih na tem spletnem mestu opisujejo odobrene specifikacije, arhitekturo nastavitev in razlage programov. Niso ponudba za prodajo, cenik, izjava o zalogi ali zaveza o dobavi. Poslovni pogoji se dogovorijo posebej in pisno s pogodbenim subjektom, navedenim pri vsaki transakciji."],
      ["Povpraševanja", "Povpraševanje, poslano prek tega spletnega mesta — vključno s profili GPS, povpraševanji za nastavitev in tehničnimi zahtevami — se shrani s številko povpraševanja in gre v presojo. Ni sprejeto naročilo, proizvodna zaveza, potrjen termin, prijava za članstvo ali sprejeta prijava v kateri koli program."],
      ["Specifikacije in dokazila", "Izračunane vrednosti, proizvodni cilji in potrjene specifikacije so na ustreznih straneh razločeni. Vrednosti togosti so proizvodni cilji, dokler ni objavljeno drugače. Noben izid za posameznega igralca ni zagotovljen."],
      ["Ekosistem, članstvo in pravice", "Nakup loparja ne ustvarja institucionalnega članstva, naložbenih pravic, lastništva intelektualne lastnine, upravičenja do licenčnin ali koristi sodelovanja. Upravičenja sledijo objavljenim pogojem programa ali pisni pogodbi."],
      ["Intelektualna lastnina", "MAXIMUS®, lev v emblemu, znamka GPS in vsebina tega spletnega mesta so zaščiteni. Interne inženirske formule, protokoli kontrole kakovosti, laminati, orodja, identiteta dobaviteljev, izračuni stroškov in zaščitena metodologija tu niso razkriti."],
    ],
  },
  lead: {
    submit: "Pošljite povpraševanje",
    submitting: "Pošiljanje…",
    retry: "Poskusite znova",
    acceptedEyebrow: "Povpraševanje sprejeto",
    acceptedTitle: "Vaše povpraševanje smo prejeli.",
    requestId: "Številka povpraševanja",
    acceptedNext: "MAXIMUS presodi vsako povpraševanje in odgovori pisno na e-poštni naslov, ki ste ga navedli. Številko povpraševanja shranite za nadaljnjo komunikacijo.",
    duplicate: "To povpraševanje je bilo že prejeto; dvojnik ni bil ustvarjen.",
    another: "Začnite novo povpraševanje",
    errorsTitle: "Prosimo, preverite ta polja:",
    failTitle: "Vaše povpraševanje ni bilo poslano.",
    fail: {
      offline: "Vaša naprava je brez povezave.",
      network: "Povezava s strežnikom ni uspela.",
      timeout: "Strežnik ni odgovoril pravočasno.",
      rate_limited: "Iz tega omrežja je prišlo preveč zahtev. Prosimo, poskusite znova v nekaj minutah.",
      too_fast: "Obrazec je bil poslan zelo hitro. Prosimo, preverite ga in pošljite znova.",
      spam_suspected: "Povpraševanje je ustavil filter za nezaželeno pošto.",
      unavailable: "Povpraševanj trenutno ni mogoče sprejeti.",
      default: "Prišlo je do nepričakovane napake.",
    },
    keepNote: "Vaš vnos ostane na tej strani, da lahko poskusite znova.",
    sendByEmail: "Pošljite to povpraševanje po e-pošti",
    sendByEmailNote: "Odpre se vaša e-poštna aplikacija z besedilom tega povpraševanja. MAXIMUS ga prejme, ko e-pošto pošljete.",
    mailConfig: "Nastavitev",
    mailPage: "Stran",
    fallback: "Če težava ne mine, pišite na {email}. Povpraševanje velja za poslano samo takrat, ko je prikazana njegova številka.",
    privacyLink: "Obvestilo o zasebnosti",
    hpLabel: "To polje pustite prazno",
    consentShort: "Soglasje",
    after: "Po pošiljanju se na tej strani prikaže številka povpraševanja. Povpraševanja presojamo in odgovarjamo pisno; povpraševanje ni naročilo.",
    basis: { unstrung: "Brez strun", strung: "S strunami", unknown: "Ne vem — dogovorimo v specifikaciji" },
    hints: {
      email: "MAXIMUS odgovarja pisno na ta naslov.",
      goal: "Na primer: prvi tekmovalni lopar ali prehod z mladinskega loparja. Ne navajajte imen, datumov rojstva ali zdravstvenih podatkov o otroku.",
      currentRacquet: "Znamka in model, če ju poznate.",
      message: "Ne navajajte gesel, plačilnih podatkov ali zdravstvenih podatkov.",
    },
  },
  choose: {
    eyebrow: "Pomoč pri izbiri",
    title: "Pomagajte mi izbrati lopar",
    lead: "Napišite MAXIMUS svojo raven in to, kar vam je najpomembnejše. Vaše odgovore presodimo in prejmete pisni predlog: serija, razred natančnosti, teža in grip.",
    stepsTitle: "Kaj sledi",
    steps: [
      ["Vaši odgovori", "Raven, prioritete in velikost gripa, če jo poznate."],
      ["Strokovna presoja", "MAXIMUS primerja vaše odgovore z matrikami serij."],
      ["Pisni predlog", "Predlagana nastavitev in naslednji korak, pisno."],
    ],
    formTitle: "Vaši odgovori",
    submit: "Zahtevajte pomoč pri izbiri",
    altTitle: "Želite se odločiti sami?",
    altGps: "Podroben profil GPS",
    altBuild: "Nastavite neposredno",
    note: "Brez samodejnega prilagajanja loparja in brez trditve o natančnosti: vsako povpraševanje presodi človek.",
  },
  consent: {
    title: "Analitika",
    text: "Ali lahko MAXIMUS meri obiske z Google Analytics? Obrazci delujejo v obeh primerih; v analitiko se ne pošljejo nobeni kontaktni podatki ali besedilo povpraševanja.",
    allow: "Dovoli analitiko",
    decline: "Zavrni",
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: celotna kompozicija — pripomoček od spredaj in s strani, gravirani lev v okroglem polju na okrogli kontaktni glavi, gravura MAXIMUS in SPOT TRAINER po vratu ter osmerokotni zaključni pokrovček z levom",
    greatHero: "Serija MAXIMUS GREAT, 363 g: celotna kompozicija z rdečimi in rumenimi detajli glave, sijajnim napisom MAXIMUS, podpisom Maximus na vratu in zaključnim pokrovčkom z levom",
    spotDetail: "Dva pripomočka MAXIMUS Spot Trainer od blizu: gravirani lev na mat črni kontaktni glavi, rebrasti ovoj gripa in osmerokotna zaključna pokrovčka z levom",
    spotPair: "Dva pripomočka MAXIMUS Spot Trainer, položena poševno na temno površino, na enem vratu gravura MAXIMUS in na drugem SPOT TRAINER, z okroglim poljem z levom na vsaki kontaktni glavi",
    spinVisual: "MAXIMUS SPIN: glava s strunami, sijajni napis MAXIMUS, grip in zaključni pokrovček z levom",
    powerVisual: "MAXIMUS POWER: glava s strunami, sijajni napis MAXIMUS, gravura personalizacije, grip in zaključni pokrovček z levom",
    greatVisual: "MAXIMUS GREAT: glava s strunami, sijajni napis MAXIMUS, gravura personalizacije, grip, zaključni pokrovček z levom in oznaka serije G na grlu",
    spinHead: "Glava in pletivo strun MAXIMUS SPIN",
    handleLion: "Grlo, grip in zaključni pokrovček MAXIMUS z levom",
    engraving: "Srebrna gravura personalizacije na vratu",
    lettering: "Sijajni črni napis MAXIMUS na mat črnem okvirju",
    variantAlt: "Serija MAXIMUS {series} — {w} g, ravnotežje {b} mm: celotna vizualizacija s specifikacijskim trakom, območjem gravure personalizacije in oznako MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistem štirih loparjev",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Vratovi Sweet Spot Trainerjev z napisom MAXIMUS",
    sstGrips: "Gripi in zaključni pokrovčki Sweet Spot Trainerjev",
    sstButtcaps: "Sweet Spot Trainer, štirje zaključni pokrovčki z levom",
    note: "Vizualizacija izdelka",
  },
  notFound: { title: "Strani ni mogoče najti", p: "Stran, ki ste jo zahtevali, v tem jeziku ne obstaja.", cta: "Pojdite na domačo stran" },
};

export default sl;
