/* Albanian dictionary — MAXIMUS website v4.0. Translated from content/en.js; numerical product data lives in data/products.js. */
const sq = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — raketa tenisi tërësisht prej karboni, projektuar sipas specifikimit",
    defaultDescription:
      "Raketa tenisi tërësisht prej karboni, nga korniza deri në dorezë: GREAT 97 in², POWER 98 in² dhe SPIN 100 in², tetë masa doreze fabrike L0–L7, klasa precizioni për peshën, balancën, swingweight dhe ngurtësinë, si edhe inxhinieri me porosi sipas kërkesës.",
  },
  common: {
    statuses: {
      current: "Aktuale",
      agreement: "E disponueshme me marrëveshje",
      development: "Në zhvillim",
      concept: "Koncept",
      target: "Objektiv prodhimi",
      modelled: "E llogaritur",
      confirmed: "E konfirmuar",
      requested: "Arkitekturë e kërkuar",
      notprovided: "Nuk është dhënë",
    },
    brief: { who: "Për kë është", value: "Çfarë merrni", now: "Konfirmuar tani", next: "Hapi tjetër" },
    labels: {
      next: "Vazhdo",
      back: "Kthehu",
      edit: "Ndrysho përgjigjet",
      review: "Rishikim",
      start: "Nis",
      restart: "Nis nga e para",
      copy: "Kopjo tekstin e kërkesës",
      copied: "U kopjua",
      openEmail: "Hap emailin për t'i dërguar kërkesën",
      reference: "Referenca e kërkesës",
      weight: "Pesha",
      balance: "Balanca",
      swingweight: "Swingweight",
      stiffness: "Ngurtësia",
      grip: "Masa e dorezës",
      headSize: "Madhësia e kokës",
      series: "Seria",
      precisionClass: "Klasa e precizionit",
      quantity: "Sasia",
      notProvided: "Nuk është publikuar ende",
      requestTarget: "Objektiv i kërkuar",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Lexo më shumë",
      allSeries: "Të gjitha seritë",
      points: "pesha të listuara",
      optional: "opsionale",
      required: "e detyrueshme",
      select: "Zgjidh",
      yes: "Po",
      no: "Jo",
      unknown: "Nuk e di",
      custom: "Objektiv me porosi",
      listed: "Peshë e listuar",
      individual: "Raketë individuale",
      pair: "Çift i përputhur",
      triple: "Tresh i përputhur",
      team: "Set ekipi",
      summaryTitle: "Përmbledhja e kërkesës tuaj",
      nextAction: "Veprimi tjetër",
      status: "Statusi",
      learn: "Mëso më shumë",
      schematic: "Skemë — nuk është matje",
      photo: "Fotografi",
    },
    ecosystemStrip: "Ekosistemi MAXIMUS",
    truth: {
      noPrices: "Çmimet, sasitë minimale, afatet e prodhimit, garancitë dhe angazhimet e dorëzimit konfirmohen me shkrim për çdo treg dhe për çdo program.",
      requestNotOrder: "Një kërkesë është kërkesë për rishikim. Nuk është porosi e pranuar, angazhim prodhimi ose takim i konfirmuar.",
      noGuarantee: "Asnjë rezultat për një lojtar të caktuar nuk garantohet nga pajisjet, metoda ose programi i përshkruar këtu.",
      governing: "Kjo faqe publikohet në disa gjuhë. Versioni në anglisht është versioni që mbizotëron; përkthimi ofrohet për lehtësi.",
    },
  },
  nav: {
    language: "Gjuha",
    groups: { racquets: "Raketa", training: "Trajnim", ecosystem: "Ekosistemi", partnerships: "Partneritete" },
    familyPlan: "Plani familjar",
    racquets: "Seritë e raketave dhe krahasimi",
    great: "GREAT — 97 in² · Kontroll",
    power: "POWER — 98 in² · Fuqi",
    spin: "SPIN — 100 in² · Rrotullim",
    precision: "Precizioni dhe ngurtësia",
    grip: "Arkitektura e dorezës fabrike L0–L7",
    custom: "Inxhinieri me porosi",
    training: "Sistemet e trajnimit",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologjia",
    gps: "MAXIMUS GPS",
    build: "Ndërto tënden",
    choose: "Ndihmomë të zgjedh",
    ecosystem: "Harta e ekosistemit",
    engineering: "Inxhinieria dhe prodhimi",
    experience: "Përvoja dhe përshtatja",
    brands: "Markat personale dhe ambasadorët",
    families: "Familjet dhe prindërit",
    owners: "Pronarët dhe arkivi i pronarit",
    network: "Sports Network",
    partnerships: "Të gjitha rrugët e partneritetit",
    coaches: "Trajnerët",
    clubs: "Klubet dhe akademitë",
    distribution: "Distribucioni dhe zhvillimi i vendeve",
    strategic: "Strategjike dhe investime",
    institutional: "Programet institucionale",
    contact: "Kontakt",
    legal: "Identiteti juridik",
    privacy: "Privatësia",
    terms: "Kushtet",
    menu: "Menu",
    close: "Mbyll",
    home: "Kreu",
    skip: "Kalo te përmbajtja",
  },
  footer: {
    line: "Raketa MAXIMUS është çelësi juaj për botën MAXIMUS.",
    product: "Produkti",
    ecosystem: "Ekosistemi",
    company: "Organizata",
    instagram: "Instagram",
    email: "Email",
    analytics: "Cilësimet e analitikës",
    subscribe: {
      title: "Qëndroni me MAXIMUS",
      line: "Seri të reja, data përshtatjeje, material trajnimi dhe programi i pronarit. Disa letra në vit, asgjë më shumë.",
      label: "Adresa e emailit",
      placeholder: "your@email.com",
      button: "Abonohu",
      sending: "Po dërgohet",
      done: "Jeni në listë. Shkruajmë vetëm kur ka diçka që ia vlen të lexohet.",
      invalid: "Kontrolloni adresën.",
      failed: "Adresa nuk u regjistrua. Provoni përsëri pas një momenti.",
      terms: "Duke u abonuar, pranoni që MAXIMUS mund t'ju dërgojë këto përditësime dhe të mbajë adresën tuaj për këtë qëllim. Çdo letër përmban një lidhje për çabonim.",
    },
    rights: "MAXIMUS® dhe emblema e luanit janë shenja të ekosistemit MAXIMUS. Pronësi intelektuale e brendshme, prejardhje dhe kontroll dokumentesh me MIPA.",
    boundary:
      "Kushtet tregtare dhe kontraktuale dakordohen veçmas me shkrim. Blerja e një rakete nuk krijon anëtarësi institucionale, të drejta investimi, pronësi të pronësisë intelektuale ose të drejtë për honorare.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Precizioni nis në kontakt.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer dhe metodologjia MAXIMUS lidhin praktikën e fokusuar me raketa performance tërësisht prej karboni.",
    heroCta1: "Zbuloni sistemin e trajnimit",
    heroCta2: "Zbuloni GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontroll",
    heroMeta: [
      ["Tërësisht karbon", "nga korniza deri në dorezë"],
      ["4 parametra", "pesha · balanca · swingweight · ngurtësia"],
      ["8 masa doreze", "geometri fabrike L0–L7"],
      ["3 seri", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Plani familjar · Kontribuoni me ne",
      title: "Buxheti i familjes suaj. Çfarë blen. Çfarë ndërton.",
      p: "Tre skenarë krah për krah — tani, në plan dhe dëshira. Sesionet, orët dhe kontaktet me topin që blen buxheti juaj, si edhe kostoja e një sesioni, e një ore dhe e një goditjeje — të gjitha të llogaritura nga numrat tuaj.",
      points: [
        ["Numrat tuaj", "Çdo shumë vjen nga ju. Asgjë nuk supozohet, asgjë nuk konvertohet."],
        ["Tre skenarë", "Krahasoni atë që bëni tani me atë që planifikoni dhe me atë që do të dëshironit."],
        ["Horizont dhjetëvjeçar", "Plani i shpenzimeve nga një deri në dhjetë vjet, i kufizuar nga moshat që caktoni."],
        ["Përtej fushës", "Mbështetje për pranimin në shkolla prestigjioze dhe asete dixhitale që mbeten te lojtari."],
      ],
      cta: "Llogaritni planin e familjes suaj",
    },
    paths: {
      eyebrow: "Nisni nga këtu",
      title: "Zgjidhni rrugën tuaj",
      items: {
        player: { h: "Lojtar", p: "Gjeni një raketë sipas nivelit dhe prioriteteve, ose konfiguroni drejtpërdrejt një.", a: "Gjeni raketën tuaj" },
        parent: { h: "Prind", p: "Një rrugë me shkrim për objektivat e zhvillimit, përfshirjen e trajnerit dhe pajisjet e përshtatshme.", a: "Rruga familjare" },
        coach: { h: "Trajner, klub ose akademi", p: "Sisteme trajnimi, përshtatje, sete ekipi dhe personalizim.", a: "Rrugët për trajnerë dhe klube" },
        partner: { h: "Distributor ose partner", p: "Rrugët e distribucionit, të zhvillimit të vendeve, strategjike dhe institucionale.", a: "Rrugët e partneritetit" },
      },
    },
    series: {
      eyebrow: "Seritë e performancës",
      title: "Tri arkitektura performance. Një platformë inxhinierike.",
      lead: "Zgjidhni serinë sipas drejtimit të lojës, më pas plotësoni konfigurimin: klasa e precizionit, pesha, doreza, personalizimi.",
      cta: "Krahasoni seritë",
      configure: "Konfiguro",
      open: "Hap serinë",
      photoPending: "Fotografia nuk është publikuar ende",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "Sistemi i Precizionit MAXIMUS",
      title: "Pesha. Balanca. Swingweight. Ngurtësia.",
      sub: "Kontrolluar si një sistem i vetëm inxhinierik.",
      lead: "Tri klasa precizioni përcaktojnë sa fort mbahet çdo raketë e përfunduar brenda specifikimit të deklaruar. P0.5 është tolerancë e ngushtë nën një protokoll matjeje të përcaktuar — jo gabim zero.",
      cta: "Precizioni dhe ngurtësia në detaje",
    },
    stiffness: {
      eyebrow: "Ngurtësia",
      title: "Reagim i përsëritshëm i kornizës përkundrejt një objektivi të deklaruar.",
      p: "Ngurtësia e kornizës formëson reagimin, ndjesinë dhe qëndrueshmërinë midis raketave. MAXIMUS e trajton si parametrin e katërt të kontrolluar: objektivi, rezultati i matur, toleranca e lejuar dhe aftësia e instrumentit mbahen si regjistrime të ndara. Përfitimi është përsëritshmëria — jo rezultat i garantuar për çdo lojtar.",
      cols: [["Reagimi", "Si e kthen korniza energjinë në kontakt."], ["Ndjesia", "Çfarë ndjen lojtari në kontakt."], ["Qëndrueshmëria", "Raketat e ndërtuara sipas të njëjtit specifikim reagojnë njësoj brenda klasës së tyre."]],
      schematicCaption: "Skemë: devijimi i lejuar rreth një objektivi të deklaruar të ngurtësisë për çdo klasë. Nuk është matje; nuk nënkuptohet asnjë vlerë RA.",
      bands: { p25: "tolerancë objektivi ±1 RA", p15: "tolerancë objektivi ±0.5 RA", p05: "përputhet me objektivin e deklaruar RA sipas protokollit të vendosur të matjes në fabrikë — jo gabim zero", target: "objektivi i deklaruar (pa nënkuptuar vlerë)" },
    },
    carbon: {
      eyebrow: "Standardi i ndërtimit",
      title: "Tërësisht karbon. Nga korniza deri në dorezë.",
      p: "Të gjitha raketat aktuale MAXIMUS në këtë platformë janë tërësisht prej karboni në strukturën e tyre, përfshirë dorezën. Shkuma nuk përdoret për të formuar dorezën.",
      gripTitle: "Tetë masa doreze fabrike. L0–L7.",
      gripP: "Çdo masë është geometri fabrike e dorezës prej karboni — nuk është shtresim me overgrip.",
      scaleCaption: "Skemë: emërtimet nominale të dorezës L0–L7 (4″ deri 4⅞″). Nuk janë dimensione të matura të dorezës.",
      cta: "Arkitektura e dorezës fabrike",
    },
    custom: {
      eyebrow: "Inxhinieri me porosi",
      title: "Projektuar sipas specifikimit.",
      sub: "Gama standarde është pikënisja.",
      p: "MAXIMUS pranon kërkesa teknike përtej matricave të publikuara për vlerësim, inxhinieri, validim dhe prodhim sipas një specifikimi të rënë dakord. Realizueshmëria konfirmohet me shkrim.",
      chain: ["Përcakto", "Projekto", "Valido", "Specifiko", "Prodho", "Mat / regjistro"],
      cta: "Dorëzoni një përshkrim teknik",
      cta2: "Diskutoni inxhinierinë me porosi",
    },
    training: {
      eyebrow: "Sistemet e trajnimit",
      title: "Një sistem trajnimi i ndërtuar rreth kontaktit.",
      p: "Sweet Spot Trainer, metodologjia MAXIMUS dhe Spot Trainer lidhin pajisjet me praktikën e drejtuar nga trajneri: kontakt i qendërzuar, kontroll, ngarkesë progresive dhe kalimi sërish te raketa e performancës.",
      cta: "Sistemet e trajnimit",
      cta2: "Kërkoni një demonstrim",
      photoPending: "Fotografia e trajnuesit nuk është publikuar ende",
      sstP: "Një kokë trajnimi 50 in² për praktikën e kontaktit të qendërzuar, me katër konfigurime peshe për ngarkesë të zgjedhur nga trajneri.",
      sstCta: "Zbuloni Sweet Spot Trainer",
      sstCaption: "Konfigurimi 300 g, një nga katër",
      methodP: "Vendosni objektivat, zgjidhni pajisjet, praktikoni me përfshirjen e trajnerit, regjistroni vëzhgimet, rivlerësoni, rregulloni dhe transferoni punën në lojën e performancës.",
      methodCta: "Zbuloni metodologjinë",
      spotP: "Një objektiv i vogël e i rrumbullakët për të praktikuar një pikë kontakti të saktë dhe të përsëritshme.",
      spotCta: "Zbuloni Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Prodhimi dhe kontrolli i cilësisë",
      title: "Ndërtuar sipas një specifikimi. Matur dhe regjistruar.",
      p: "Prodhimi ndjek specifikimin me shkrim të çdo porosie. Regjistrimet ndjekin klasën e precizionit: regjistrime prodhimi të ruajtura për P2.5, regjistrime individuale dhe gjurmueshmëri për P1.5, kontroll individual dhe dokumentim për P0.5 kur programi i porosisë i zbaton.",
      confirmedTitle: "Konfirmuar",
      confirmed: ["Ndërtim tërësisht prej karboni nga korniza deri në dorezë.", "Klasat e precizionit P2.5, P1.5 dhe P0.5 me katër parametra të kontrolluar.", "Tetë masa doreze fabrike L0–L7."],
      pendingTitle: "Nuk është publikuar ende",
      pending: "Fotografitë e pajisjeve matëse, mostrat e regjistrimeve të kontrollit të cilësisë dhe materialet filmike nga fabrika nuk janë publikuar ende. Asgjë në këtë faqe nuk është certifikatë matjeje.",
      captions: { lettering: "Shkrimi MAXIMUS me shkëlqim mbi kornizën mat", buttcap: "Doreza dhe kapaku fundor me shenjën e luanit", handle: "Gdhendje personalizimi në argjend", finish: "Koka dhe shtroja e telave" },
      cta: "Inxhinieria dhe prodhimi",
    },
    world: {
      eyebrow: "Bota MAXIMUS",
      title: "Një çelës. Një ekosistem. Mundësi të pakufizuara.",
      note: "“Mundësi të pakufizuara” është shprehje e markës, nuk është premtim për realizueshmëri teknike, të ardhura ose akses të pakufizuar. Blerja nuk krijon honorare, kthime investimi, sponsorizim ose financim të zhvillimit të një lojtari.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — dhe navigimi juaj në botën e tenisit: një profil i udhëhequr i pajisjeve, me përgjigje me shkrim." },
        personal: { h: "Personalizimi", p: "Emra, inicialet, numra dhe identifikim ekipi në trajtimin e miratuar me gdhendje argjendi." },
        development: { h: "Zhvillimi", p: "Sisteme trajnimi të drejtuara nga trajneri, regjistrime dhe rivlerësim." },
        ecosystem: { h: "Ekosistemi i zgjeruar", p: "Marka personale, regjistrime të pronarëve, rrjet, licencim dhe programe institucionale — secili i paraqitur me statusin e tij real." },
      },
      cta: "Zbuloni ekosistemin",
    },
    partners: {
      eyebrow: "Rrugët e partneritetit",
      title: "Trajnerë, klube, distributorë dhe partnerë.",
      p: "Së pari kualifikim me shkrim. Të drejtat e vendit, ekskluziviteti dhe kushtet tregtare negociohen me shkrim — nuk jepen kurrë përmes një formulari.",
      cta: "Të gjitha rrugët e partneritetit",
      formTitle: "Kërkesë e shkurtër",
      formLead: "Zgjidhni qëllimin dhe shkruajini MAXIMUS. Në këtë faqe merrni një ID kërkese.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "NAVIGIMI JUAJ NË BOTËN E TENISIT" } },
    personal: { eyebrow: "Personalizimi", title: "Emri juaj. Numri juaj. MAXIMUS juaj." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tri seri. Parametra realë." },
    map: { cta: "Zbuloni ekosistemin" },
  },
  racquets: {
    title: "Raketa",
    lead: "Tri seri performance me standard të përbashkët ndërtimi, sistem të përbashkët precizioni dhe arkitekturë të përbashkët të dorezës fabrike. Çdo seri është arkitekturë e themeluar performance brenda një platforme inxhinierike më të gjerë.",
    direction: { control: "Kontroll", power: "Fuqi", spin: "Rrotullim" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Drejtimi kryesor i lojës",
    compareTitle: "Krahasimi i serive",
    compareLead: "Vetëm të dhëna arkitekture të konfirmuara. Modelet e telave, gjatësitë, profilet e trarit, intervalet e tensionit, swingweight dhe vlerat nominale të ngurtësisë për këto seri nuk publikohen; ato mblidhen si objektiva të kërkuar për rishikim teknik.",
    columns: { series: "Seria", head: "Madhësia e kokës", direction: "Drejtimi", weights: "Pesha të listuara", range: "Intervali i peshës", balance: "Të dhënat e balancës" },
    balanceModelled: "Vlera të llogaritura",
    balanceNotProvided: "Nuk është publikuar ende",
    construction: "Ndërtimi: tërësisht karbon, nga korniza deri në dorezë · Precizioni: P2.5 / P1.5 / P0.5 · Doreza: L0–L7",
    otherTitle: "Sporte të tjera me raketë",
    otherLead: "Drejtime zhvillimi të miratuara. Në këto kategori nuk ekziston asnjë produkt i shitshëm dhe asnjë specifikim i tenisit nuk transferohet tek ato.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Tenis plazhi" },
    ctaConfigure: "Konfiguroni një kërkesë",
    ctaSeries: "Hap serinë",
  },
  seriesPage: {
    eyebrow: "Seritë e performancës",
    intro: {
      great: "Arkitektura GREAT 97 in² është ndërtuar rreth kontrollit: kokë kompakte, kontakt i saktë dhe siguri në drejtim.",
      power: "Arkitektura POWER 98 in² është ndërtuar rreth transferimit të energjisë: thellësi dhe ritëm nga një kornizë e stabilizuar.",
      spin: "Arkitektura SPIN 100 in² është ndërtuar rreth sjelljes së topit: rrotullim, margjinë dhe formësim i trajektores.",
    },
    photoPending: "Fotografia e serisë nuk është publikuar ende",
    detailPending: "Fotografitë e detajeve të ndërtimit dhe të dorezës për këtë seri nuk janë publikuar ende.",
    specsTitle: "Specifikimi dhe statusi",
    catalogue: {
      eyebrow: "Katalogu i serisë {series}",
      title: "{n} variante peshe",
      lead: "Çdo variant i serisë {series}, i renditur sipas peshës. Pesha në gramë, balanca në milimetra nga fundi i dorezës. Çdo vizualizim paraqitet i plotë: asgjë e prerë, e maskuar ose e shtrirë.",
      selectLabel: "Zgjidhni një variant peshe",
      select: "Shfaq këtë variant",
      selected: "Shfaqur më lart",
      balanceLabel: "Balanca",
      headLabel: "Madhësia e kokës",
      constructionLabel: "Ndërtimi",
      gripsLabel: "Masat e dorezës fabrike",
      precisionLabel: "Klasat e precizionit",
      balanceConfirmed: "Balanca është vlera e konfirmuar për këtë peshë dhe përputhet me figurën e shtypur në vizualizim.",
      balanceModelled: "Balanca është vlerë e llogaritur për këtë peshë të listuar, nuk është matje individuale në fabrikë; përputhet me figurën e shtypur në vizualizim.",
      zoom: "Hap imazhin",
      close: "Mbyll",
      allTitle: "Të gjitha {n} variantet",
    },
    specs: { head: "Madhësia e kokës", direction: "Drejtimi kryesor", weights: "Pesha të listuara", range: "Intervali i peshës", balance: "Balanca", construction: "Ndërtimi", grips: "Doreza fabrike", precision: "Klasat e precizionit" },
    construction: "Tërësisht karbon, nga korniza deri në dorezë",
    statusTitle: "Statusi i vlerave",
    matrixTitle: "Matrica e plotë e peshave",
    matrixLead: "Peshat e listuara janë përzgjedhja standarde. Pesha të tjera mund të kërkohen si objektiva me porosi; vlerat e ndërmjetme që mungojnë nuk shtohen.",
    balanceNote: {
      confirmed: "Vlerat e balancës janë konfirmuar për çdo peshë të listuar (mm nga fundi i dorezës) dhe përputhen me figurën e shtypur në vizualizimin e kësaj peshe. Ato nuk llogariten këtu dhe nuk rrafshohen midis peshave fqinje; baza e matjes konfirmohet në specifikimin me shkrim.",
      modelled: "Vlerat e balancës janë llogaritur për çdo peshë të listuar (mm nga fundi i dorezës). Ato nuk janë matje individuale në fabrikë; baza e matjes konfirmohet në specifikimin me shkrim.",
      notprovided: "Vlerat e balancës për këtë seri nuk janë dhënë. Mos i nxirrni nga një seri tjetër.",
    },
    optionsTitle: "Precizioni, doreza dhe pesha",
    notPublished: "Nuk publikohen për këtë seri: modeli i telave, gjatësia, trari, intervali i tensionit, swingweight dhe vlerat e ngurtësisë. Mund t'i deklaroni si objektiva të kërkuar për rishikim teknik.",
    offerTitle: "Çfarë ndodh pas kërkesës tuaj",
    offerSteps: [
      ["Kërkesa", "Dorëzoni një konfigurim ose një pyetje. ID-ja e kërkesës shfaqet menjëherë."],
      ["Rishikimi", "MAXIMUS rishikon serinë, klasën, peshën, dorezën dhe çdo objektiv të kërkuar."],
      ["Përgjigje me shkrim", "Specifikimi, disponueshmëria dhe kushtet tregtare konfirmohen me shkrim."],
    ],
    faqTitle: "Pyetje",
    faq: [
      ["A janë matur vlerat e balancës?", "Ato janë llogaritur për peshat e listuara dhe nuk janë matje individuale. Baza e matjes konfirmohet në specifikimin me shkrim."],
      ["A mund të kërkoj një peshë që nuk është në listë?", "Po, si objektiv me porosi në gramë të plotë. Ajo rishikohet teknikisht dhe realizueshmëria konfirmohet me shkrim."],
      ["Çfarë ndryshon klasa e precizionit?", "Sa fort mbahen pesha, balanca, swingweight dhe ngurtësia brenda specifikimit të deklaruar dhe çfarë regjistrimesh ruhen."],
      ["A ndërtohet doreza me overgrip?", "Jo. L0–L7 janë geometri fabrike të dorezës prej karboni."],
      ["Ku janë çmimet dhe afatet e dorëzimit?", "Ato konfirmohen me shkrim për çdo kërkesë dhe nuk publikohen këtu."],
    ],
    faqSpinBalance: ["Nga vijnë vlerat e balancës të SPIN?", "Nga tabela e konfirmuar e serisë Spin: 33 variante peshe me balancë në milimetra nga fundi i dorezës. Çdo çift përputhet me figurën e shtypur në vizualizimin e miratuar të kësaj peshe. Vlerat nuk janë llogaritur dhe nuk rrafshohen midis peshave fqinje."],
    ctaBuild: "Konfiguroni këtë seri",
    ctaAsk: "Pyesni për këtë seri",
    ctaCompare: "Krahasoni të gjitha seritë",
    weightsLabel: "pesha të listuara",
    headLabel: "koka",
  },
  precision: {
    title: "Precizioni dhe ngurtësia",
    switch: { label: "Zgjidhni një klasë precizioni", panelLabel: "Katër parametra të kontrolluar —", qcLabel: "Arkitektura e kontrollit të cilësisë", protocolNote: "sipas protokollit të përcaktuar të matjes së kontrollit të cilësisë në fabrikë", fullTable: "Tabela e plotë e krahasimit" },
    lead: "Katër parametra të kontrolluar si një sistem i vetëm inxhinierik. Çdo klasë përcakton sa fort mbahet një raketë e përfunduar brenda specifikimit të deklaruar dhe çfarë regjistrimesh cilësie prodhohen.",
    statement: "Pesha. Balanca. Swingweight. Ngurtësia. Kontrolluar si një sistem i vetëm inxhinierik.",
    classes: {
      "P2.5": { name: "Bërthamë performance e skalueshme", qc: "Matje individuale dhe regjistrime prodhimi të ruajtura." },
      "P1.5": { name: "Precizion i avancuar", qc: "Matje individuale, regjistrime individuale dhe gjurmueshmëri." },
      "P0.5": { name: "Profesionale · e kontrolluar individualisht", qc: "Kontroll individual me vlera nominale dhe aktuale dhe regjistrime individuale të matjes; identitet serial, gjurmueshmëri e partisë, certifikatë precizioni dhe sete të përputhura kur programi i porosisë i zbaton." },
    },
    columns: { cls: "Klasa", weight: "Pesha", balance: "Balanca", sw: "Swingweight", stiff: "Ngurtësia", qc: "Arkitektura e kontrollit të cilësisë" },
    stiffTarget: "tolerancë objektivi",
    stiffExact: "përputhet me objektivin e deklaruar RA sipas protokollit të vendosur të matjes në fabrikë",
    programmeNote: "Identiteti serial, certifikatat dhe dokumentacioni i seteve të përputhura lëshohen vetëm kur programi i një porosie të caktuar i zbaton.",
    targetsNote: "Specifikimet e ngurtësisë janë objektiva prodhimi derisa protokolli përkatës dhe dëshmia e prodhimit të mbështetin një pohim më të fortë. Propozimi arkitekturor nuk nënkupton që çdo konfigurim i listuar ka kaluar tashmë një proces të plotë lëshimi me katër parametra.",
    stiffnessTitle: "Pse ka vlerë ngurtësia",
    stiffnessP1: "Ngurtësia e kornizës ndikon se si reagon korniza në kontakt, si ndihet dhe sa të njëjta janë dy raketa midis tyre. Përfitimi kryesor i kontrollit të saj është reagimi i përsëritshëm përkundrejt një specifikimi të deklaruar.",
    stiffnessP2: "Përpara se të publikohet përputhshmëria e verifikuar, regjistrimi i brendshëm i kontrollit të cilësisë identifikon instrumentin, statusin e kalibrimit, metodën, gjendjen e raketës, rezolucionin, pasigurinë e matjes, matjet e përsëritura, rregullin e rrumbullakimit dhe rregullin e pranimit. Një numër i plotë identik i shfaqur nuk është provë e variacionit fizik zero ose e gabimit zero të matjes.",
    fields: ["Objektivi", "Rezultati i matur", "Toleranca e lejuar", "Aftësia e instrumentit"],
    fieldsNote: "Mbahen si fusha të ndara në çdo regjistrim.",
    matchedTitle: "Setet e përputhura",
    matchedP: "Kriteret e seteve të përputhura përcaktohen veçmas nga toleranca individuale. Përputhshmëria e çdo rakete me tolerancën e vet nominale nuk provon në vetvete një diferencë maksimale të caktuar midis dy raketave. Çiftet, treshet dhe setet e ekipit të përputhura kërkohen përmes konfiguratorit dhe konfirmohen me shkrim.",
    extendedTitle: "Modeli teknik i zgjeruar",
    extendedP: "Modeli i të dhënave mbështet parametra shtesë. Për ato nuk ekzistojnë ende vlera ose klasa tolerance; mund të deklarohen si objektiva të kërkuar në një përshkrim teknik.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Sjellja torsionale", length: "Gjatësia", beamProfile: "Profili i trarit", headGeometry: "Geometria e kokës", stringPattern: "Modeli i telave", durability: "Qëndrueshmëria", vibration: "Karakteristikat e dridhjeve" },
    noZero: "MAXIMUS nuk e përshkruan gamën e vet të listuar si gamë me tolerancë zero. Precizioni në gamë deklarohet si klasë me tolerancë të deklaruar dhe me arkitekturë të përcaktuar të kontrollit të cilësisë. ZERO nuk është pjesë e gamës.",
    zero: {
      eyebrow: "Opsion ekskluziv",
      title: "ZERO",
      sub: "Tolerancë zero gramë.",
      p: "Tri klasat mbajnë një raketë të përfunduar brenda një brezi të deklaruar. ZERO e heq brezin. Raketa ndërtohet dhe matet derisa leximi të jetë i njëjtë me figurën e deklaruar, në rezolucionin e instrumentit të fabrikës, dhe ai lexim lëshohet bashkë me të. Nuk është pjesë e gamës së listuar dhe nuk është klasë e katërt: dakordohet individualisht, për një raketë ose një set të përputhur, si ekskluzivitet i punuar me porosi. Me marrëveshje, e njëjta qasje zbatohet edhe për balancën dhe swingweight.",
      points: [
        ["Pa brez", "Figura e deklaruar është rezultati, jo qendra e një tolerance."],
        ["Një nga një", "E ndërtuar, e matur dhe e regjistruar si njësi e vetme."],
        ["Lëshuar bashkë me raketën", "Leximi i matur dorëzohet dhe ruhet në regjistrimin e prodhimit."],
        ["Konfirmuar me shkrim", "Parametrat, shtrirja dhe afati i prodhimit dakordohen përpara prodhimit."],
      ],
      note: "E përputhur në rezolucionin e instrumentit matës të fabrikës. Një figurë identike e shfaqur nuk është pohim për variacion fizik zero. Disponueshmëria dhe kushtet dakordohen individualisht për çdo porosi.",
      cta: "Kërkoni ZERO",
    },
    cta: "Konfiguroni me një klasë precizioni",
  },
  grip: {
    title: "Arkitektura e dorezës fabrike",
    statement: "Tetë masa doreze fabrike. L0–L7.",
    lead: "Geometria e dorezës është pjesë e arkitekturës së dorezës prej karboni. Çdo masë prodhohet si geometri doreze, nuk shtresohet me overgrip.",
    emph: "Masa të zgjeruara",
    p1: "Gama e fabrikës me tetë masa i jep trajnerëve dhe lojtarëve një interval më të gjerë konfigurimi, përmes të cilit pajisjet mund të specifikohen rreth lojtarit, përfshirë geometritë më të mëdha L6 dhe L7.",
    p2: "Emërtimi nominal i dorezës është i ndryshëm nga dimensionet e papërpunuara strukturore të dorezës dhe nga protokolli përfundimtar i matjes. Masat zbatohen për seritë e performancës dhe për familjet e trajnimit në këtë platformë.",
    p3: "Për këtë gamë nuk pohohet ekskluzivitet në të gjithë botën.",
    columns: { size: "Masa", nominal: "Nominale", family: "Zbatohet për" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfiguroni me masën e dorezës tuaj",
  },
  custom: {
    title: "Inxhinieri me porosi",
    statement: "Projektuar sipas specifikimit.",
    sub: "Gama standarde është pikënisja.",
    lead: "MAXIMUS pranon kërkesa teknike përtej matricave të publikuara të konfigurimit për vlerësim, inxhinieri, validim dhe prodhim sipas një specifikimi të rënë dakord. Realizueshmëria konfirmohet përmes rishikimit — nuk është fizikisht ose tregtarisht e realizueshme çdo kërkesë e mendueshme.",
    scopeTitle: "Çfarë mund të trajtojë një përshkrim teknik",
    scope: ["Geometria e kokës dhe e kornizës", "Gjatësia", "Pesha", "Balanca", "Swingweight", "Ngurtësia", "Twistweight", "Geometria e dorezës", "Ndërtimi", "Setet e përputhura", "Kornizat e trajnimit", "Kozmetika dhe gdhendja", "Identiteti dhe programet e ekipit", "Zhvillim i varur nga veglat e prodhimit"],
    processTitle: "Procesi",
    process: [
      ["Përcakto", "Objektivat e preferuar, kufijtë e detyrueshëm, përdorimi i synuar dhe kompromiset e pranueshme."],
      ["Projekto", "Vlerësim inxhinierik përkundrejt platformës dhe veglave të prodhimit."],
      ["Valido", "Validim përkundrejt specifikimit të rënë dakord."],
      ["Specifiko", "Një specifikim me shkrim me bazën e matjes dhe tolerancat."],
      ["Prodho", "Prodhim sipas specifikimit."],
      ["Mat / regjistro", "Matje dhe regjistrime të ruajtura sipas klasës përkatëse të precizionit."],
    ],
    formTitle: "Dorëzoni një përshkrim teknik",
    formLead: "Dalloni objektivat e preferuar nga kufijtë e detyrueshëm. Rezultati është kërkesë për rishikim teknik, nuk është porosi prodhimi e pranuar automatikisht.",
    protected: "Recetat e shtresimit, veglat e prodhimit, identitetet e furnitorëve, kostot e brendshme dhe njohuritë e mbrojtura nuk zbulohen përmes kësaj rruge.",
    cta: "Dorëzoni një përshkrim teknik",
  },
  training: {
    title: "Sistemet e trajnimit",
    lead: "Dy familje trajnimi me standardet e tyre të prodhimit, të lidhura nga një metodologji: praktikë e drejtuar nga trajneri, regjistrime, rivlerësim dhe kthim në lojën e performancës.",
    sst: { h: "Sweet Spot Trainer", p: "Një raketë trajnimi me kokë të reduktuar 50 in² në një sistem me katër pesha, për praktikën e kontaktit të qendërzuar, ndërgjegjësimin për zonën optimale të goditjes, kontrollin e raketës dhe ngarkesën progresive." },
    spot: { h: "Spot Trainer", p: "Trajnim i pikës së kontaktit me një objektiv të vogël e të rrumbullakët, mbi bazën e miratuar me katër pesha." },
    method: { h: "Metodologjia", p: "Vendosni objektivat, zgjidhni pajisjet me përfshirjen e trajnerit, përdorni sistemin përkatës, regjistroni, rivlerësoni, rregulloni dhe transferoni." },
    experience: "Mbajeni. Goditni. Ndjeni.",
    experienceP: "Kërkoni testim, përshtatje ose demonstrim me mbështetjen e trajnerit. Një kërkesë e dorëzuar nuk është takim i konfirmuar.",
    cta: "Kërkoni përshtatje ose demonstrim",
    distinct: "Sweet Spot Trainer, Spot Trainer dhe çdo pajisje e veçantë demonstrimi janë produkte të dallueshme dhe nuk bashkohen kurrë.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Një kategori trajnimi e veçantë me standardin e vet të prodhimit. Koka 50 in² përqendron vëmendjen në vendin e kontaktit; katër peshat ofrojnë progresionin e ngarkesës.",
    baseline: "Bazë e konfirmuar",
    columns: { head: "Koka", length: "Gjatësia", pattern: "Modeli i telave", grips: "Doreza fabrike" },
    systemTitle: "Sistem me katër raketa",
    detailsTitle: "Detajet e ndërtimit",
    systemLead: "Pesha dhe balanca si dorëzohen. Baza e matjes regjistrohet veçmas dhe nuk është publikuar ende.",
    purposeTitle: "Qëllimi",
    purpose: ["Praktikë e kontaktit të qendërzuar", "Ndërgjegjësim për zonën optimale të goditjes", "Kontroll i raketës", "Ngarkesë progresive", "Zhvillim i drejtuar nga trajneri", "Kthim te raketa e performancës e lojtarit"],
    heavy: "Modeli 400 g është konfigurim trajnimi i kontrolluar. Nuk rekomandohet automatikisht për fëmijët, fillestarët ose çdo lojtar; trajneri përcakton ngarkesën, kohëzgjatjen dhe progresionin.",
    precisionNote: "Klasat e precizionit të performancës P2.5, P1.5 dhe P0.5 nuk zbatohen automatikisht për këtë familje trajnimi. Tolerancat e prodhimit të trajnimit ndjekin specifikimin e miratuar të vetë familjes.",
    health: "Nuk premtohet parandalim ose trajtim i bërrylit të tenistit, eliminim i lëndimeve ose përmirësim i garantuar.",
    cta: "Kërkoni një demonstrim të Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Trajnim i pikës së kontaktit me një objektiv të vogël e të rrumbullakët. Produkt i dallueshëm me identitetin e vet vizual, i ndërtuar mbi bazën e miratuar me katër pesha.",
    purposeTitle: "Qëllim i konfirmuar",
    purposeP: "Të trajnojë lojtarin për të gjetur dhe përsëritur një pikë kontakti të saktë.",
    weightsTitle: "Progresioni i peshës",
    weightsP: "Progresioni i peshës ndjek bazën e miratuar të peshave të Sweet Spot Trainer. Vlerat e balancës dhe specifikimet e tjera të Sweet Spot Trainer nuk kopjohen tek Spot Trainer.",
    dims: "Dimensionet e sakta të objektivit nuk janë publikuar ende.",
    grips: "Arkitektura e dorezës fabrike L0–L7.",
    notes: ["Klasat e precizionit të performancës nuk zbatohen automatikisht.", "Nuk është raketë konvencionale në miniaturë dhe nuk publikohet asnjë model telash.", "Spot Trainer, Sweet Spot Trainer dhe çdo pajisje e veçantë demonstrimi mbeten të dallueshme."],
    cta: "Pyesni për Spot Trainer",
  },
  methodology: {
    title: "Metodologjia dhe përvoja e produktit",
    lead: "Pajisjet janë një pjesë e një rrugëtimi të strukturuar zhvillimi. Metoda nis me objektivat e lojtarit, jo me etiketën e një produkti.",
    stepsTitle: "Rrugëtimi i zhvillimit",
    steps: [
      ["Vendosni objektivat", "Objektivat e lojtarit dhe pika e nisjes."],
      ["Zgjidhni pajisjet", "Pajisje të përshtatshme, zgjedhur me përfshirjen e trajnerit."],
      ["Përdorni sistemin", "Sistemi përkatës i trajnimit, i drejtuar nga trajneri."],
      ["Regjistroni", "Vëzhgime të pjesëmarrjes reale, pa rezultate të trilluara."],
      ["Rivlerësoni", "Pika kontrolli të krahasueshme."],
      ["Rregulloni", "Rregullime të konfigurimit ose të programit."],
      ["Transferoni", "Të mësuarit transferohet sërish në lojën e performancës."],
    ],
    educationTitle: "Rrugët e edukimit",
    education: { player: "Lojtarët — kuptimi i konfigurimit, i ngarkesës dhe i progresionit.", parent: "Prindërit — vijimësia e zhvillimit, pajisjet e përshtatshme, regjistrimet dhe të drejtat.", coach: "Trajnerët — sistemet e trajnimit, përshtatja, vlerësimi dhe përdorimi i autorizuar i programeve." },
    evidenceTitle: "Disiplina e dëshmisë",
    evidenceP: "Regjistrimet e pjesëmarrjes reale dhe vëzhgimet ruhen me klasifikimin e tyre — deklaruar nga pjesëmarrësi, konfirmuar nga kujdestari, validuar nga trajneri ose matur nga sistemi. Progresi, rezultatet dhe validimi nuk trillohen kurrë.",
    experienceTitle: "Mbajeni. Goditni. Ndjeni.",
    experienceP: "Mund të kërkohet testim, përshtatje ose demonstrim me mbështetjen e trajnerit. Një kërkesë e dorëzuar nuk është takim i konfirmuar.",
    cta: "Kërkoni përshtatje ose demonstrim",
    cta2: "Kërkesë për partneritet me trajner",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — profil i udhëhequr i pajisjeve",
    title: "MAXIMUS GPS",
    lead: "Një profil i udhëhequr i pajisjeve. Përgjigjuni vetëm atyre pyetjeve që kanë vlerë; rishikoni dhe korrigjoni përgjigjet; marrni një përmbledhje, drejtimet e konfigurimit që zbatohen dhe një veprim real të radhës.",
    honesty: "Në këtë publikim nuk është miratuar asnjë rregull automatik përshtatjeje. Për këtë arsye GPS prodhon një përmbledhje të qartë të kërkesave dhe tregon drejtimet e konfigurimit; specifikat e pajisjeve kalojnë për rishikim nga ekspertët.",
    rulesVersion: "Versioni i rregullave",
    dataVersion: "Versioni i të dhënave të produktit",
    steps: { role: "Roli", sport: "Sporti", experience: "Përvoja", objectives: "Objektivat", style: "Stili i lojës", equipment: "Pajisjet aktuale", preference: "Preferencat", coach: "Përfshirja e trajnerit", ageBand: "Grupi i moshës", review: "Rishikimi" },
    notStored: "Nuk ruhet në këtë shfletues.",
    ageNote: "Përdoret vetëm për drejtimin e kërkesës. Nuk kërkohet emër, datëlindje ose informacion mjekësor.",
    q: {
      role: "Cila alternativë ju përshkruan?",
      sport: "Cili sport?",
      experience: "Niveli i përvojës",
      objectives: "Çfarë ka më shumë vlerë? (zgjidhni deri në tri)",
      style: "Stili i lojës, nëse dihet",
      equipment: "Pajisjet aktuale, nëse ka",
      equipmentHint: "Marka dhe modeli, pesha ose doreza, nëse i dini. Opsionale.",
      preference: "Konfigurimi i preferuar ose masa e njohur e dorezës",
      grip: "Masa e njohur e dorezës",
      coach: "A përfshihet një trajner në vendimet për pajisjet?",
      ageBand: "Grupi i moshës së lojtarit (përdoret vetëm për t'i dhënë kërkesës drejtimin e duhur)",
    },
    roles: { player: "Lojtar", parent: "Prind ose kujdestar", coach: "Trajner", club: "Klub ose akademi", other: "Tjetër" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Sport tjetër me raketë" },
    sportNote: "Produktet ekzistojnë për tenisin. Sportet e tjera janë drejtime zhvillimi; interesi juaj regjistrohet për programin përkatës.",
    experience: { beginner: "Fillestar", developing: "Në zhvillim", intermediate: "I mesëm", advanced: "I avancuar", competitive: "Garues", professional: "Profesionist" },
    objectives: { control: "Kontroll", power: "Fuqi", spin: "Rrotullim", comfort: "Komoditet", manoeuvrability: "Manovrueshmëri", development: "Zhvillim afatgjatë", competition: "Garë", training: "Sistem trajnimi", team: "Ekip ose set i përputhur", personal: "Personalizim" },
    styles: { baseline: "Nga vija e fundit", allcourt: "Në të gjithë fushën", attacking: "Ofensiv", defensive: "Mbrojtës", coach: "Zgjedhur nga trajneri", unknown: "Nuk e di" },
    ageBands: { u10: "Nën 10 vjeç", u14: "10–13", u18: "14–17", adult: "18 vjeç e lart" },
    output: {
      title: "Profili i pajisjeve tuaja",
      status: "Kërkohet rishikim nga ekspertët",
      statusP: "Në këtë publikim nuk prodhohet asnjë përputhje automatike. Profili juaj është përmbledhur për rishikim nga ekspertët.",
      directionsTitle: "Drejtimet e konfigurimit që zbatohen",
      directionsP: "Bazuar në objektivat që deklaruat dhe në drejtimin e deklaruar të lojës së çdo serie. Ky është drejtim, nuk është rekomandim përshtatjeje.",
      trainingHint: "Objektivat tuaja përfshijnë një sistem trajnimi: shihni Sweet Spot Trainer dhe Spot Trainer.",
      teamHint: "Setet e përputhura kërkohen përmes konfiguratorit dhe konfirmohen me shkrim.",
      next1: "Dërgoni profilin për rishikim nga ekspertët",
      show: "Shfaq profilin tim",
      configure: "Konfiguro",
      sendP: "Dërgojini profilin tuaj MAXIMUS për rishikim nga ekspertët. ID-ja e kërkesës shfaqet menjëherë; përgjigjja vjen me shkrim.",
      otherSport: "Raketat MAXIMUS ekzistojnë për tenisin. Për sportet e tjera me raketë nuk sugjerohet asnjë seri tenisi; interesi juaj regjistrohet si drejtim zhvillimi.",
      noDirection: "Objektivat tuaja nuk tregojnë një drejtim të vetëm loje. Rishikimi nga ekspertët propozon një konfigurim.",
      incomplete: "Disa përgjigje të detyrueshme mungojnë — përdorni “Ndrysho përgjigjet” për t'i plotësuar.",
    },
    privacy: "GPS nuk kërkon informacion shëndetësor dhe nuk kërkon identifikues të fëmijëve. Në këtë sesion të shfletuesit mbahen vetëm përgjigjet me zgjedhje të shumëfishtë; teksti i lirë nuk ruhet.",
  },
  build: {
    title: "Ndërto tënden",
    lead: "Konfiguroni një kërkesë: seria, klasa e precizionit, pesha e listuar ose objektiv me porosi, masa e dorezës, objektivat e kërkuar, personalizimi, setet e përputhura dhe sasia. Rezultati është kërkesë konfigurimi me një ID kërkese — nuk është kod produkti, çmim, datë dorëzimi ose certifikatë.",
    steps: { series: "Seria", cls: "Klasa e precizionit", weight: "Pesha", grip: "Doreza", targets: "Objektivat", personal: "Personalizimi", set: "Seti dhe sasia", use: "Përdorimi", review: "Rishikimi" },
    q: {
      series: "Zgjidhni një seri",
      cls: "Zgjidhni një klasë precizioni",
      weightMode: "Pesha",
      listed: "Peshë e listuar",
      customWeight: "Pesha e kërkuar (g)",
      balanceShown: "Balanca e llogaritur për këtë peshë",
      balanceRequest: "Balanca e kërkuar (mm)",
      grip: "Masa e dorezës fabrike",
      targetsTitle: "Objektivat e kërkuar",
      swingweight: "Swingweight i kërkuar (kg·cm²)",
      stiffness: "Ngurtësia e kërkuar (RA)",
      basis: "Baza e matjes për vlerat e kërkuara",
      engraving: "Teksti i gdhendjes",
      engravingHint: "Emër, inicialet ose numër. Shkronja latine, shifra, hapësirë, vizë, apostrof dhe pikë; deri në 24 karaktere. Shkrime të tjera pranohen për konfirmim të grafikës.",
      engravingType: "Personalizimi",
      types: { none: "Asnjë", name: "Emri i lojtarit", initials: "Inicialet", number: "Numri i setit", academy: "Identifikim i trajnerit ose i akademisë", team: "Program ekipi" },
      set: "Raketë individuale ose set i përputhur",
      use: "Përdorimi i synuar",
      uses: { play: "Lojë personale", competition: "Garë", coaching: "Trajnim", team: "Ekip ose akademi", retail: "Vlerësim për shitje me pakicë ose distribucion", other: "Tjetër" },
      notes: "Kërkesa teknike shtesë",
    },
    classes: { "P2.5": "P2.5 — bërthamë performance e skalueshme", "P1.5": "P1.5 — precizion i avancuar", "P0.5": "P0.5 — profesionale, e kontrolluar individualisht" },
    stiffExactShort: "ngurtësia përputhet me objektivin e deklaruar RA sipas protokollit të vendosur të fabrikës",
    clsNote: "Çdo klasë kontrollon katër parametra. P0.5 është tolerancë e ngushtë nën një protokoll matjeje të përcaktuar — jo gabim zero. Identiteti serial, certifikatat dhe dokumentacioni i seteve të përputhura zbatohen vetëm kur programi i porosisë tuaj i zbaton.",
    listedNote: "Nga matrica e konfirmuar e serisë.",
    customNote: "Një peshë jashtë matricës, e rishikuar teknikisht.",
    balanceCaption: "Çdo peshë e listuar shfaq balancën e llogaritur në mm nga fundi i dorezës. Vlerat e llogaritura nuk janë matje individuale.",
    spinNote: "Peshat e SPIN formojnë arkitekturën e kërkuar të peshës. Balanca, swingweight dhe ngurtësia për SPIN nuk janë dhënë; ato përcaktohen në rishikimin teknik.",
    customHint: "Gramë të plotë, vetëm shifra. Një peshë me porosi është kërkesë për rishikim teknik; realizueshmëria konfirmohet me shkrim dhe asnjë vlerë nuk rrumbullakohet.",
    gripNote: "geometri fabrike e dorezës prej karboni, nuk është shtresim me overgrip",
    targetsLead: "Opsionale. Shkruani vetëm vlerat që ju duhen. Secila regjistrohet si objektiv i kërkuar për rishikim teknik, nuk regjistrohet si specifikim i publikuar.",
    basisHint: "E detyrueshme kur kërkoni një peshë me porosi ose çdo objektiv: vlerat u referohen një rakete pa tela apo me tela?",
    inputRange: "Vlera e pranuar: {min}–{max}.",
    inputRangeNote: "Intervalet e vlerave vetëm filtrojnë të dhënat e pamundura. Ato nuk përshkruajnë kapacitetin e prodhimit.",
    listedBasis: "vlera të listuara — baza e matjes konfirmohet në specifikimin me shkrim",
    notStored: "Nuk ruhet në këtë shfletues; shkruajeni sërish nëse e rifreskoni faqen.",
    artworkReview: "kërkohet konfirmim i grafikës",
    previewNote: "Nuk shfaqet asnjë pamje paraprake: për këtë model nuk është publikuar ende një shabllon i miratuar i gdhendjes. Teksti juaj mblidhet për konfirmim të grafikës.",
    teamSub: "4–99 raketa për set",
    setsLabel: { individual: "Numri i raketave", pair: "Numri i çifteve të përputhura", triple: "Numri i tresheve të përputhura", team: "Numri i seteve të ekipit" },
    teamSizeLabel: "Raketa për set ekipi",
    totalLabel: "Raketa në total",
    racquetsUnit: "raketa",
    setRule: "Sasia numëron setet: një çift i përputhur është 2 raketa për set, një tresh i përputhur 3.",
    restart: "Nisni një konfigurim të ri",
    notices: { weightCleared: "{w} g nuk është në matricën e serisë {series}, ndaj pesha u fshi. Zgjidhni një peshë të listuar ose kërkoni një objektiv me porosi." },
    reviewTitle: "Kërkesë konfigurimi",
    reviewP: "Kontrolloni konfigurimin, më pas shtoni të dhënat e kontaktit. Kërkesa ruhet me një ID kërkese dhe merr përgjigje me shkrim; disponueshmëria dhe kushtet tregtare konfirmohen me shkrim.",
    reviewErrors: "Disa përgjigje të konfigurimit kërkojnë vëmendje:",
    edit: "Ndrysho",
    fieldNames: { series: "Seria", cls: "Klasa e precizionit", mode: "Zgjedhja e peshës", weight: "Pesha e listuar", customWeight: "Pesha e kërkuar", basis: "Baza e matjes", balanceReq: "Balanca e kërkuar", sw: "Swingweight i kërkuar", ra: "Ngurtësia e kërkuar", grip: "Masa e dorezës", ptype: "Personalizimi", engraving: "Teksti i gdhendjes", setType: "Tipi i setit", sets: "Sasia", teamSize: "Raketa për set ekipi", use: "Përdorimi i synuar", notes: "Kërkesa shtesë" },
    status: { listed: "peshë e listuar", requestedArchitecture: "arkitekturë e kërkuar e peshës", technicalReview: "kërkesë për rishikim teknik", notPublished: "nuk është dhënë", requestedCondition: "gjendje e kërkuar" },
    chooseLink: "Nuk e dini cila seri ju përshtatet? Marrni ndihmë për zgjedhjen",
    cta: "Dorëzoni kërkesën e konfigurimit",
  },
  experience: {
    title: "Përvoja dhe përshtatja",
    statement: "Mbajeni. Goditni. Ndjeni.",
    lead: "Kërkoni testim, përshtatje ose demonstrim me mbështetjen e trajnerit. Kërkesat rishikohen dhe marrin përgjigje me shkrim; një kërkesë e dorëzuar nuk është takim i konfirmuar.",
    optionsTitle: "Çfarë mund të kërkohet",
    options: ["Testim i raketës", "Sesion përshtatjeje", "Demonstrim me mbështetjen e trajnerit", "Demonstrim i Sweet Spot Trainer ose Spot Trainer", "Ditë demo për ekip ose akademi"],
    formTitle: "Kërkesë për përshtatje ose demonstrim",
  },
  engineering: {
    title: "Inxhinieria dhe prodhimi",
    statement: "Avionë. Jahte. Raketa.",
    lead: "Një filozofi inxhinierike në tri mjedise: principet që formësojnë një avion, precizioni që drejton një jaht në det të hapur, performanca që përcakton çdo raketë MAXIMUS. Një rrëfim inxhinierik — nuk është pohim për certifikim avionësh, pronësi jahtesh, pronësi fabrike ose transferim të drejtpërdrejtë të materialeve.",
    manifesto: ["Besojmë se inxhinieria e madhe nuk ka kufij.", "Një filozofi. Projektuar pa kompromis."],
    capabilityTitle: "Kapaciteti i prodhimit",
    capabilityLead: "Kapaciteti paraqitet si sekuencë, nuk është slogan.",
    sequence: [
      ["Specifikimi", "Seria, klasa e precizionit, pesha, balanca, swingweight, objektivi i ngurtësisë, geometria e dorezës, personalizimi."],
      ["Prodhimi", "Ndërtim tërësisht prej karboni nga korniza deri në dorezë, prodhuar sipas specifikimit."],
      ["Kontrolli i cilësisë", "Matje dhe regjistrime sipas klasës së precizionit: regjistrime prodhimi, regjistrime individuale dhe gjurmueshmëri, certifikim individual."],
      ["Prodhimi i përsëritur", "Reagim i përsëritshëm përkundrejt një specifikimi të deklaruar në çdo parti prodhimi."],
      ["Gjurmueshmëria", "Identitet serial, gjurmueshmëri e partisë dhe Certifikatë Precizioni kur klasa e parashikon."],
    ],
    capacityNote: "Kapaciteti i prodhimit, afatet, sasitë minimale dhe planet e dorëzimit konfirmohen për çdo program me shkrim, përkundrejt porosive të konfirmuara dhe një plani lëshimi të rënë dakord.",
    truth: "Kapaciteti nuk është prodhim i realizuar, stok, datë dorëzimi e garantuar ose pronësi e një njësie prodhimi.",
    cta: "Distribucioni dhe zhvillimi i vendeve",
    cta2: "Dorëzoni një përshkrim teknik",
  },
  ecosystem: {
    title: "Ekosistemi MAXIMUS",
    lead: "Një çelës. Kjo është ajo që hap. Çdo nyje ka një shpjegim, status të saktë dhe veprim përkatës të radhës.",
    words: ["Inxhinieri", "Performancë", "Inovacion", "Komunitet", "Mundësi", "Qëllim"],
    nodes: {
      engineering: { h: "Inxhinieria dhe prodhimi i raketave", p: "Raketa tërësisht prej karboni, projektuar sipas specifikimit, prodhuar me regjistrime cilësie dhe gjurmueshmëri.", a: "Inxhinieria dhe prodhimi" },
      precision: { h: "Precizioni dhe konfigurimi individual", p: "Katër parametra, tri klasa precizioni, tetë masa doreze dhe inxhinieri me porosi.", a: "Precizioni dhe ngurtësia" },
      training: { h: "Trajnimi dhe metodologjia", p: "Sweet Spot Trainer, Spot Trainer dhe një rrugëtim i strukturuar zhvillimi.", a: "Sistemet e trajnimit" },
      development: { h: "Zhvillimi i lojtarit dhe i trajnerit", p: "Përzgjedhje e drejtuar nga trajneri, regjistrime, rivlerësim dhe rrugë edukimi.", a: "Metodologjia" },
      identity: { h: "Identiteti personal dhe markat personale", p: "Nga gdhendja deri te një markë personale ose profesionale e rregulluar me të drejta.", a: "Markat personale" },
      owners: { h: "Regjistrimet, njohuritë dhe të drejtat e pronarit", p: "Një arkiv i propozuar i pronarit, me akses të kontrolluar, për regjistrimet e pajisjeve, të zhvillimit dhe të të drejtave.", a: "Pronarët dhe arkivi" },
      mipa: { h: "Prejardhja MIPA dhe kontrolli i brendshëm", p: "Shtresa e brendshme e pronësisë intelektuale, e prejardhjes dhe e kontrollit të dokumenteve.", a: "Identiteti juridik dhe kontrolli" },
      digital: { h: "Infrastruktura dixhitale dhe drejtimi Blockchain 5.0", p: "Prejardhja, regjistrimet e gjurmueshme, dëshmia me akses të kontrolluar dhe identiteti i produktit si drejtimi i deklaruar teknologjik.", a: "Drejtimi teknologjik" },
      licensing: { h: "Licencimi kontraktual dhe programet e honorareve", p: "Marka, produkte dhe pako të drejtash të licencuara, me kushte të përcaktuara për çdo marrëveshje.", a: "Rrugët e licencimit" },
      families: { h: "Pjesëmarrja familjare dhe përfitimet e programit", p: "Vendime të informuara, vijimësi, regjistrime të ruajtura dhe përfitime të përcaktuara nga programi.", a: "Familjet dhe prindërit" },
      network: { h: "MAXIMUS Sports Network", p: "Lojtarë, trajnerë, klube, akademi, ofrues shërbimesh, operatorë dhe partnerë regjionalë.", a: "Sports Network" },
      market: { h: "Klubet, akademitë, distribucioni dhe zhvillimi i vendeve", p: "Programe ekipi, shitje me pakicë, distribucion dhe zhvillim territori përmes kualifikimit me shkrim.", a: "Rrugët e partneritetit" },
      institutional: { h: "Programet institucionale, edukimi, inovacioni dhe ndikimi social", p: "Shtresa institucionale e ofruar nga MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) kur një program e përcakton këtë rol.", a: "Programet institucionale" },
      extensions: { h: "Zgjerimet e ardhshme në sportet me raketë dhe veshjet MAXIMUS", p: "Padel, pickleball, squash, badminton, racquetball, tenis plazhi dhe veshjet si drejtime zhvillimi.", a: "Sportet me raketë" },
    },
    boundaryTitle: "Kufijtë",
    boundary: [
      "Blerja e një rakete nuk krijon anëtarësi institucionale, të drejta qeverisjeje, honorare ose të drejta investimi.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) është operatori institucional vetëm kur një program e përcakton këtë rol; shitjet e pajisjeve identifikojnë subjektin e tyre real kontraktues.",
      "Grantet, statusi bamirës, trajtimi tatimor dhe lejet rregullatore nuk zbatohen automatikisht nga një vend në tjetrin.",
    ],
    techTitle: "Drejtimi teknologjik",
    techP: "Blockchain 5.0 është drejtimi teknologjik i deklaruar i ekosistemit MAXIMUS. Qëllimet e tij funksionale janë prejardhja, regjistrimet e gjurmueshme, dëshmia me akses të kontrolluar, identiteti i produktit dhe rakordimi i eventeve tregtare kualifikuese. Nuk përfaqësohet asnjë mekanizëm konsensusi, kapacitet transaksionesh, rrjet nyjesh, adresë kontrate inteligjente, token ose certifikim i pavarur, dhe nuk pohohet asnjë implementim i vendosur në punë. Informacioni personal, regjistrimet e fëmijëve dhe marrëveshjet konfidenciale nuk vendosen kurrë si parazgjedhje në një sistem publik të pandryshueshëm.",
  },
  brands: {
    title: "Markat personale dhe ambasadorët",
    statement: "Nga lojtar në markë. Nga trajner në markë.",
    lead: "Një rrugë e dedikuar për markën personale. Përfshirja e MAXIMUS përmban zhvillimin e markës dhe promovimin e rënë dakord — nuk është vetëm një emër mbi një raketë.",
    progressionTitle: "Progresioni i synuar",
    progression: [
      ["Identitet i verifikuar", "Një identitet i verifikuar dhe histori zhvillimi."],
      ["Markë e dallueshme", "Një markë personale ose profesionale e dallueshme."],
      ["Përmbajtje me të drejta të rregulluara", "Përmbajtje me të drejta të rregulluara dhe identitet produkti i miratuar."],
      ["Inxhinieri dhe koleksione", "Inxhinieri dhe zhvillim koleksioni kur bihet dakord."],
      ["Promovim", "Promovim përmes kanaleve dhe partneriteteve MAXIMUS të rënë dakord."],
      ["Pjesëmarrje", "Pjesëmarrje kontraktuale në shitjet ose licencimet kualifikuese."],
      ["Raportim", "Raportim transparent sipas marrëveshjes."],
    ],
    royaltiesTitle: "Honorarët dhe licencimi",
    royalties: [
      "Honorarët i lidhen markës, produktit, transaksionit ose pakos së drejtash të licencuar e të përcaktuar.",
      "“Shitje në të gjithë botën” nënkupton shitjet kualifikuese brenda shtrirjes së kontratës — nuk nënkupton kurrë çdo raketë MAXIMUS të palidhur me të.",
      "Normat, baza e llogaritjes, territoret, kohëzgjatja, rimbursimet, zbritjet, raportimi, shlyerja dhe verifikimi përcaktohen përmes marrëveshjes përkatëse. Nuk publikohet asnjë përqindje e parazgjedhur honorari.",
      "Nuk premtohet asnjë kampanjë globale, buxhet mediatik, rezultat sponsorizimi ose sukses tregtar pa një shtrirje të rënë dakord.",
    ],
    cta: "Dorëzoni një kërkesë për bashkëpunim marke",
    cta2: "Kërkesë për partneritet me trajner",
  },
  families: {
    title: "Familjet dhe prindërit",
    lead: "Vendime të informuara për pajisjet, vijimësi e zhvillimit, njohuri dhe të drejta të ruajtura, dukshmëri e pjesëmarrjes dhe përfitime të përcaktuara nga programi, që mund të mbështetin aktivitet të ardhshëm.",
    nowTitle: "E disponueshme tani",
    now: ["Kërkesa familjare dhe zhvillimore me shkrim.", "Përzgjedhje e pajisjeve me përfshirjen e trajnerit, kërkesa për përshtatje dhe demonstrim.", "Regjistrime private: profilet e fëmijëve nuk publikohen kurrë dhe nuk komercializohen si parazgjedhje.", "Rrugë edukimi për prindërit: konfigurimi, ngarkesa, progresioni, regjistrimet dhe të drejtat."],
    plannedTitle: "Të planifikuara",
    planned: ["Përfitime pjesëmarrjeje të përcaktuara nga programi, të përdorshme për mallra dhe shërbime brenda ekosistemit, në vend të interesit në të holla.", "Regjistrime të pronarit dhe të familjes në arkivin e propozuar të pronarit, me të drejta të kujdestarit dhe kalim të kontrollit në moshën 18 vjeç."],
    categoriesTitle: "Mbahen të ndara",
    categories: ["Honorare kontraktuale që rrjedhin nga të drejta të licencuara ose shitje kualifikuese", "Përfitime pjesëmarrjeje të përcaktuara nga një program", "Kredi blerjeje ose shërbimi", "Parapagesa", "Anëtarësi institucionale"],
    categoriesP: "Këto kategori nuk trajtohen kurrë si të zëvendësueshme me njëra-tjetrën.",
    statusTitle: "Statusi real i programit familjar",
    journeyTitle: "Rruga familjare",
    journey: [
      ["Objektivi", "Çfarë do të arrijë lojtari më pas."],
      ["Niveli aktual", "Ku ndodhet lojtari sot."],
      ["Trajneri", "A merr pjesë një trajner në vendimet për pajisjet."],
      ["Pajisjet", "Pajisje të përshtatshme për fazën, përfshirë sistemet e trajnimit kur ka vend."],
      ["Praktika e rënë dakord", "Përdorim i drejtuar nga trajneri, i rënë dakord paraprakisht."],
      ["Rishikimi", "Rivlerësim në pika kontrolli të krahasueshme."],
    ],
    brief: {
      who: "Prindër dhe kujdestarë të lojtarëve në çdo fazë.",
      value: "Një përgjigje me shkrim për pajisjet e përshtatshme, përfshirjen e trajnerit dhe hapin e radhës të zhvillimit.",
      now: "Kërkesa familjare me shkrim; përzgjedhje me përfshirjen e trajnerit; regjistrime private — profilet e fëmijëve nuk publikohen kurrë.",
      next: "Dorëzoni kërkesën familjare më poshtë. Merrni menjëherë një ID kërkese.",
    },
    formTitle: "Kërkesë familjare",
    formNote: "Plotësohet nga një prind ose kujdestar. Mos përfshini emrin, datëlindjen, shkollën ose informacionin mjekësor të fëmijës.",
    noPromise: "Blerja nuk premton honorare, kthime investimi, sponsorizim ose financim të zhvillimit të një fëmije.",
    statusP: "Ky publikim shpjegon modelin dhe pranon kërkesa për programin. Akumulimi, pagesat dhe shfrytëzimi nuk ofrohen derisa eventet kualifikuese, përfituesit, burimi i financimit, baza e llogaritjes, përdorimet e lejuara, trajtimi kontabël, rimbursimet, anulimet, skadimi, transferueshmëria, mbyllja e programit dhe trajtimi i mosmarrëveshjeve të përcaktohen me shkrim. Nuk premtohet asnjë bilanc që nuk bie kurrë, asnjë pjesëmarrje nuk paguan të gjithë trajnimin dhe nuk nënkuptohet asnjë mbrojtje e kapitalit.",
    cta: "Dorëzoni një kërkesë familjare ose zhvillimore",
  },
  owners: {
    title: "Pronarët dhe arkivi i pronarit",
    lead: "Arkivi i pronarit është një regjistër i propozuar, me akses të kontrolluar, për pajisjet, zhvillimin, njohuritë, përmbajtjen dhe të drejtat e dokumentuara. Paraqitet si pjesë e arkitekturës së planifikuar të pronarit: nuk shfaqen llogari, bilanca, certifikata ose arritje reale.",
    nowTitle: "Për pronarët aktualë tani",
    now: ["Kërkesa pronarësh: referencë produkti ose numër serial, rregullim, servis dhe kërkesa për regjistrime, me shkrim.", "Certifikatë Precizioni dhe dokumentacion i seteve të përputhura kur klasa e precizionit i parashikon, dorëzuar bashkë me produktin."],
    archTitle: "Arkitektura e planifikuar e arkivit",
    arch: ["Identiteti i produktit dhe numrat serialë", "Konfigurimi dhe certifikatat përkatëse të kontrollit të cilësisë", "Historiku i servisit dhe i rregullimit", "Regjistrime të zhvillimit të lojtarit ose të trajnerit", "Kualifikime dhe arritje të verifikuara", "Media me të drejta të rregulluara dhe materiale të autorësuara", "Licenca, leje dhe referenca kontratash", "Regjistrime të programit të markës personale", "Pasqyra përkatëse të honorareve ose përfitime pjesëmarrjeje"],
    separationTitle: "Çfarë kuptohet me pronësi",
    separation: [
      "Pronësia e një rakete fizike është e ndarë nga pronësia e të drejtës së autorit, e një licence, e një të drejte kontraktuale ose e një regjistrimi që i përshkruan ato.",
      "Një dokument i ruajtur ose një zë në blockchain nuk është automatikisht provë që një e drejtë ligjore ekziston ose është transferuar.",
      "Dëshmia mban klasifikimin e vet: deklaruar nga pjesëmarrësi, konfirmuar nga kujdestari, validuar nga trajneri, matur nga sistemi.",
      "Për të miturit: regjistrime private, të drejta të kujdestarit, pa profile të publikuara fëmijësh dhe pa komercializim të identitetit si parazgjedhje.",
      "Eksportimi, korrigjimi, kontrolli i aksesit dhe një kalim i përshtatshëm i kontrollit janë pjesë e dizajnit.",
    ],
    techTitle: "Blockchain 5.0 dhe MxSN",
    techP: "Blockchain 5.0 është drejtimi teknologjik i deklaruar; MxSN përcakton konceptet e një rrjeti me akses të kontrolluar për pëlqimin, dorëzimin, dëshminë, të drejtat dhe raportimin. Implementimi operacional nuk përfaqësohet. Modeli i të dhënave të aplikacionit është ndërtuar për t'u integruar më vonë përmes një ndërfaqeje të dokumentuar, pa pretenduar se lidhja ekziston tani.",
    cta: "Kërkesë pronari",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Lidhja midis lojtarëve, trajnerëve, klubeve, akademive, ofruesve të shërbimeve, operatorëve të programeve dhe partnerëve regjionalë.",
    functionsTitle: "Funksione të mundshme",
    functions: ["Zbulim", "Njohje", "Programe zhvillimi", "Mbështetje me pajisje", "Evente", "Akses në shërbime", "Mundësi partneriteti"],
    statusTitle: "Statusi real",
    statusP: "Nuk është publikuar ende asnjë direktori publike: do të listohen vetëm pjesëmarrësit të cilëve u është vërtetuar identiteti, marrëdhënia dhe leja për të figuruar. Një propozim i dërguar një klubi nuk është partneritet, dhe një distributor i mundshëm nuk është distributor i caktuar. Publikimi i direktorisë, rezervimet, mesazhet dhe transaksionet tregtare kontrollohen veçmas dhe nuk janë aktive.",
    cta: "Aplikoni në rrjet",
  },
  partnerships: {
    title: "Rrugët e partneritetit",
    lead: "Së pari kualifikim me shkrim. Çdo rrugë çon në një kërkesë specifike për rolin; kushtet tregtare vijnë me shkrim.",
    commercialTitle: "Aktivitete tregtare të mundshme të platformës",
    commercial: ["Pajisje", "Inxhinieri me porosi", "Personalizim", "Programe ekipi dhe akademie", "Sisteme trajnimi", "Licencim kontraktual", "Distribucion", "Shërbime të miratuara", "Kategori produktesh të ardhshme"],
    boundary: "Të drejtat e vendit, ekskluziviteti, tarifat e territorit dhe marzhet e distributorit janë kushte të negociuara. Nuk publikohet asnjë e ardhur, parashikim, vlerësim, pjesë tregu, kthim, angazhim financimi ose partneritet pa emër.",
    routes: {
      coaches: {
        title: "Trajnerët",
        lead: "Sisteme trajnimi, përshtatje, identitet profesional, programe të autorizuara, mundësi për markë personale dhe furnizim me pajisje.",
        points: ["Sweet Spot Trainer dhe Spot Trainer në praktikën e drejtuar nga trajneri.", "Përshtatje me matricat e konfigurimit dhe tetë masat e dorezës fabrike.", "Coach-to-Brand: profil profesional i verifikuar dhe nënmarkë e rregulluar me të drejta.", "Përdorimi i autorizuar i programeve ndjek një marrëveshje me shkrim."],
        cta: "Dorëzoni një kërkesë për partneritet me trajner",
        brief: {
          who: "Trajnerë të pavarur dhe ekipe trajnerësh.",
          value: "Sisteme trajnimi për praktikën e drejtuar nga trajneri, përshtatje me matricat e serive dhe tetë masat e dorezës fabrike, dhe një rrugë drejt identitetit profesional.",
          now: "Kërkesa trajnerësh me shkrim. Nuk publikohet dhe nuk nënkuptohet asnjë komision, fitim ose normë referimi.",
          next: "Dorëzoni kërkesën për trajnerë më poshtë. Kushtet vijnë me shkrim.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubet dhe akademitë",
        lead: "Pajisje për ekipin, sisteme trajnimi, personalizim, programe zhvillimi, servis dhe pjesëmarrje në rrjet.",
        points: ["Setet e ekipit dhe setet e përputhura kërkohen përmes konfiguratorit.", "Sisteme trajnimi dhe metodologji për zhvillim të strukturuar.", "Personalizim për programe ekipi në zonat e miratuara.", "Ditë demo, sesione përshtatjeje dhe pjesëmarrje në rrjet."],
        cta: "Dorëzoni një kërkesë klubi ose akademie",
        brief: {
          who: "Klube, akademi dhe programe ekipi.",
          value: "Sete ekipi dhe sete të përputhura, sisteme trajnimi, personalizim për programe ekipi dhe ditë demonstrimi.",
          now: "Kërkesa klubesh dhe akademive me shkrim; setet e ekipit kërkohen përmes konfiguratorit.",
          next: "Dorëzoni kërkesën e klubit ose të akademisë më poshtë.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribucioni dhe zhvillimi i vendeve",
        lead: "Asortimenti, koordinimi i prodhimit, kapaciteti teknik, zhvillimi i territorit dhe kualifikimi tregtar konfidencial.",
        points: ["Kualifikim me shkrim i palës, i territorit dhe i kanalit.", "Asortiment i përcaktuar nga matricat e konfigurimit dhe klasat e precizionit.", "Territori, ekskluziviteti, volumet, çmimet dhe mbrojtja tregtare janë kushte të negociuara, të rëna dakord me shkrim.", "Subjekti kontraktues, kushtet e pagesës dhe baza e dorëzimit identifikohen për çdo transaksion."],
        cta: "Dorëzoni një kërkesë për distribucion ose zhvillim vendi",
        brief: {
          who: "Shitës me pakicë, distributorë dhe partnerë vendi.",
          value: "Një asortiment i përcaktuar nga matricat e konfirmuara, klasat e precizionit dhe gama e dorezave, me kualifikim me shkrim të territorit dhe të kanalit.",
          now: "Kërkesa distribucioni me shkrim. Territori, ekskluziviteti, volumet dhe çmimet negociohen — asnjëra nuk jepet përmes një formulari.",
          next: "Dorëzoni kërkesën për distribucion më poshtë.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategjike dhe investime",
        lead: "Kapaciteti inxhinierik, thellësia e konfigurimit, modeli i prodhimit, rrugët drejt tregut, pronësia intelektuale, shërbimet dhe mundësitë e zgjerimit.",
        points: ["Diskutimi strategjik i kualifikuar ose aksesi i kontrolluar në informacion ndjek kualifikimin me shkrim.", "Informacioni publik kufizohet në specifikimet e miratuara të produktit, arkitekturën e konfigurimit, kapacitetet e verifikuara dhe shpjegimet e programeve.", "Ekonomia specifike e blerësit, kostot, metodologjia e mbrojtur dhe marrëveshjet e papublikuara zbulohen vetëm nën marrëveshje konfidencialiteti ose kontratë."],
        cta: "Kërkoni një diskutim strategjik të kualifikuar",
        brief: {
          who: "Investitorë dhe partnerë strategjikë.",
          value: "Një diskutim i kualifikuar për kapacitetin inxhinierik, thellësinë e konfigurimit, modelin e prodhimit, rrugët drejt tregut dhe pronësinë intelektuale.",
          now: "Nuk publikohen të dhëna financiare, parashikime, vlerësime ose kthime. Informacioni i kontrolluar ndjek kualifikimin me shkrim dhe marrëveshjen e konfidencialitetit.",
          next: "Kërkoni më poshtë një diskutim strategjik të kualifikuar.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Programet institucionale",
        lead: "Edukimi, aksesi, inovacioni, dëshmia e zhvillimit, ndikimi social dhe programe të strukturuara në mënyrën e duhur.",
        points: ["Programet institucionale strukturohen përmes MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) kur programi e përcakton këtë rol.", "Fondet e kufizuara të programit dhe transaksionet tregtare mbeten të ndara.", "Një kërkesë nuk është aplikim anëtarësie i pranuar, dhe një blerës pajisjesh nuk është anëtar institucional.", "Grantet, statusi bamirës, trajtimi tatimor dhe lejet rregullatore varen nga vendi dhe nuk nënkuptohen kurrë."],
        cta: "Dorëzoni një kërkesë për program institucional",
        brief: {
          who: "Institucione, programe edukimi dhe zhvillimi.",
          value: "Programe për edukim, akses, inovacion dhe dëshmi të zhvillimit, strukturuar me operatorin e duhur.",
          now: "Kërkesa institucionale me shkrim. Një kërkesë nuk është aplikim anëtarësie; blerja e pajisjeve nuk është anëtarësi institucionale.",
          next: "Dorëzoni kërkesën institucionale më poshtë.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Zbulimi publik dhe i kontrolluar",
    disclosure: {
      public: { h: "Publik", p: "Specifikime të miratuara të produktit, ndërtimi, arkitektura e konfigurimit, qëllimet e trajnimit, kapacitetet e verifikuara, shpjegimet e programeve dhe rrugët e partneritetit." },
      qualified: { h: "Kërkesë e kualifikuar", p: "Kërkesa teknike, sasitë, interesi për territor, shtrirja e zhvillimit dhe diskutimet tregtare përkatëse." },
      controlled: { h: "Kontrolluar me marrëveshje konfidencialiteti ose kontratë", p: "Formulat e brendshme, protokollet e detajuara të kontrollit të cilësisë, shtresimet, veglat e prodhimit, metodat e prodhimit, identitetet e furnitorëve, kostot, ekonomia specifike e blerësit, metodologjia e mbrojtur, marrëveshjet e papublikuara dhe regjistrimet e ndjeshme të të drejtave." },
    },
  },
  contact: {
    title: "Kontakti dhe kërkesat",
    lead: "Zgjidhni qëllimin e kërkesës tuaj. Çdo formular mbledh vetëm atë që nevojitet për ta drejtuar dhe për ta vlerësuar. Kërkesat marrin përgjigje me shkrim.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Identiteti juridik",
  },
  form: {
    purposeLabel: "Qëllimi i kërkesës",
    purposes: {
      selection: "Ndihmë për zgjedhjen e një rakete",
      product: "Kërkesë për produkt",
      fitting: "Përshtatje ose demonstrim",
      technical: "Përshkrim teknik",
      config: "Kërkesë konfigurimi",
      gps: "Profil pajisjesh GPS",
      coach: "Partneritet me trajner",
      club: "Kërkesë klubi ose akademie",
      distribution: "Distribucion ose zhvillim vendi",
      brand: "Bashkëpunim marke ose ambasador",
      family: "Kërkesë familjare ose zhvillimore",
      institutional: "Program institucional",
      strategic: "Diskutim strategjik ose investimi",
      owner: "Kërkesë pronari",
      network: "Aplikim për Sports Network",
      general: "Kërkesë e përgjithshme",
    },
    fields: {
      name: "Emri",
      email: "Email",
      role: "Roli juaj",
      country: "Vendi ose regjioni",
      organisation: "Organizata",
      message: "Mesazhi juaj",
      level: "Niveli aktual",
      objectives: "Çfarë ka më shumë vlerë (deri në tri)",
      currentRacquet: "Raketa aktuale",
      grip: "Masa e dorezës, nëse dihet",
      seriesInterest: "Seria e interesit",
      quantity: "Sasia",
      city: "Qyteti ose vendi i sesionit",
      coachInvolved: "A përfshihet një trajner?",
      timing: "Afati i preferuar",
      targets: "Objektivat e preferuar",
      limits: "Kufijtë e detyrueshëm",
      use: "Përdorimi i synuar",
      tradeoffs: "Kompromise të pranueshme",
      basis: "Baza e matjes",
      players: "Numri i lojtarëve",
      interests: "Fushat e interesit",
      territory: "Territori i interesit",
      channels: "Kanalet dhe përvoja aktuale",
      audience: "Publiku ose disiplina",
      proposal: "Bashkëpunimi i propozuar",
      goal: "Objektivi i zhvillimit",
      ageBand: "Grupi i moshës së lojtarit",
      scope: "Shtrirja e programit",
      interestArea: "Fusha e interesit",
      productRef: "Referenca e produktit ose numri serial",
      requestType: "Tipi i kërkesës",
      seeking: "Çfarë kërkoni",
      consent: "Pranoj që MAXIMUS mund t'i ruajë dhe t'i përdorë këto të dhëna për t'i përgjigjur kësaj kërkese. Ky nuk është abonim marketingu.",
    },
    roles: { player: "Lojtar", parent: "Prind ose kujdestar", coach: "Trajner", club: "Klub ose akademi", retailer: "Shitës me pakicë", distributor: "Distributor", brand: "Markë ose ambasador", investor: "Investitor ose partner strategjik", institution: "Institucion", other: "Tjetër" },
    interestOptions: { training: "Sisteme trajnimi", fitting: "Përshtatje", identity: "Identitet profesional", programmes: "Programe të autorizuara", brand: "Markë personale", supply: "Furnizim me pajisje", team: "Pajisje për ekipin", personalisation: "Personalizim", development: "Programe zhvillimi", service: "Servis", network: "Pjesëmarrje në rrjet" },
    ownerTypes: { setup: "Rregullim dhe konfigurim", service: "Servis", records: "Regjistrime dhe certifikata", other: "Tjetër" },
    strategicAreas: { engineering: "Kapaciteti inxhinierik", configuration: "Thellësia e konfigurimit", manufacturing: "Modeli i prodhimit", routes: "Rrugët drejt tregut", ip: "Pronësia intelektuale dhe shërbimet", expansion: "Mundësitë e zgjerimit" },
    errors: {
      required: "Kjo fushë është e detyrueshme.",
      too_long: "Kjo e dhënë është shumë e gjatë.",
      too_short: "Kjo e dhënë është shumë e shkurtër.",
      invalid_email: "Shkruani një adresë emaili të vlefshme, për shembull emri@shembull.com.",
      invalid_choice: "Zgjidhni një nga opsionet.",
      not_number: "Shkruani një numër të plotë vetëm me shifra.",
      out_of_range: "Kjo vlerë është jashtë intervalit të pranuar.",
      not_in_matrix: "Kjo peshë nuk është në matricën e listuar të serisë së zgjedhur.",
      decimal_not_supported: "Shkruani një numër të plotë pa dhjetore.",
      too_many: "Zgjidhni jo më shumë se tri opsione.",
      consent_required: "Pëlqimi është i detyrueshëm që MAXIMUS të mund t'i përgjigjet kësaj kërkese.",
      invalid: "Kjo e dhënë nuk është e vlefshme.",
    },
  },
  legal: {
    title: "Identiteti juridik dhe kontrolli",
    lead: "Marka publike është MAXIMUS / MAXIMUS GPS. Identitetet juridike operative janë të dallueshme dhe deklarohen këtu.",
    entities: {
      institutional: { role: "Shtresa e programeve institucionale", p: "Ofron shtresën e programeve institucionale kur një program e përcakton këtë rol. Nuk është shitëse tregtare e raketave. Organizatë jofitimprurëse e inkorporuar në Dubai International Financial Centre." },
      equipment: { role: "Subjekti tregtar i pajisjeve", p: "Subjekti tregtar i pajisjeve për furnizim, distribucion dhe dorëzim tregtar me kontratë, kur dokumentet aktuale operative e përcaktojnë këtë rol. Pala kontraktuese për çdo transaksion identifikohet në dokumentet e atij transaksioni." },
      ip: { role: "Pronësia intelektuale, marka dhe koordinimi tregtar", p: "Shfaqet për një rol të themeluar në pronësi intelektuale, markë ose koordinim tregtar. Nuk i caktohet asnjë përgjegjësi kontraktuale e pakonfirmuar." },
      stewardship: { role: "Referenca e kujdestarisë", p: "House of Maximus është referenca e kujdestarisë për ekosistemin kur mbështetet nga burimi përkatës." },
      control: { role: "Pronësia intelektuale e brendshme, prejardhja dhe kontrolli i dokumenteve", p: "MIPA është shtresa e brendshme e pronësisë intelektuale, e prejardhjes dhe e kontrollit të dokumenteve. Një zë i brendshëm MIPA është i ndryshëm nga një markë tregtare e jashtme, patentë, regjistrim i të drejtës së autorit ose njohje gjyqësore dhe nuk përbën miratim vizual." },
    },
    labels: { licence: "Licenca", registration: "Regjistrimi", vat: "VAT TRN", address: "Adresa", email: "Email", jurisdiction: "Jurisdiksioni" },
    boundaryTitle: "Kufijtë",
    boundary: [
      "Blerja nuk jep automatikisht anëtarësi institucionale, të drejta qeverisjeje, honorare ose të drejta investimi.",
      "Roli institucional është i ndarë nga transaksionet tregtare të pajisjeve.",
      "Privatësia, kushtet e programeve dhe rregullimet e aksesit të kontrolluar përputhen me funksionet e lëshuara faktikisht.",
      "Asnjë deklaratë e përgjithshme për ligjin e zbatueshëm nuk vlen për çdo vizitor, shitje ose program të huaj; baza kontraktuale caktohet për çdo marrëveshje.",
    ],
  },
  privacy: {
    title: "Privatësia",
    updated: "Versioni 2026-09-21 · faqja 4.2",
    contactTitle: "Kontakt për pyetje mbi privatësinë",
    sections: {
      collect: ["Çfarë mblidhet", "Kur dorëzoni një formular: të dhënat që shkruani (emri, emaili, roli, vendi ose regjioni, organizata nëse jepet, mesazhi juaj dhe përgjigjet e formularit), parametrat e faqes dhe të kampanjës të vizitës tuaj (faqja e mbërritjes, gjuha, parametrat utm; identifikuesit e klikimeve reklamuese vetëm nëse lejoni analitikën) dhe ora e dorëzimit. Adresa juaj IP përdoret vetëm në formë të hashuar dhe jetëshkurtër, për të kufizuar abuzimin, dhe nuk ruhet bashkë me kërkesën tuaj."],
      purpose: ["Pse", "Për t'i përgjigjur kërkesës tuaj, për të përgatitur propozimin ose specifikimin që kërkuat dhe për të mbajtur një regjistrim të kërkesës. Në bazë të një formulari nuk dërgohet asnjë mesazh marketingu."],
      storageOn: ["Ku ruhen kërkesat", "Kërkesat ruhen në një bazë të dhënash të Upstash, Inc. (Redis), të ofruar përmes platformës së hostimit Vercel Inc."],
      notifyEmail: ["Njoftim për një kërkesë të re", "Kur një kërkesë pranohet, një njoftim me të dhënat që dorëzuat dërgohet me email në kutinë postare përgjegjëse të MAXIMUS."],
      notifyTelegram: ["Njoftim për një kërkesë të re", "Kur një kërkesë pranohet, një njoftim me të dhënat që dorëzuat dërgohet personit përgjegjës në MAXIMUS përmes Telegram (Telegram FZ-LLC, Dubai), i cili për këtë arsye e përpunon atë njoftim gjatë tranzitit."],
      notifyWebhook: ["Njoftim për një kërkesë të re", "Kur një kërkesë pranohet, një njoftim me të dhënat që dorëzuat dërgohet në një pikë fundore të brendshme të MAXIMUS përmes një lidhjeje të nënshkruar dhe të enkriptuar."],
      notifyNone: ["Njoftim për një kërkesë të re", "Njoftimi për kërkesa të reja është në proces konfigurimi. Kërkesa juaj ruhet dhe lexohet nga MAXIMUS në regjistrin e brendshëm; për këtë qëllim nuk dërgohet asgjë palëve të treta."],
      storageOff: ["Ku ruhen kërkesat", "Ruajtja e kërkesave është në proces konfigurimi. Derisa të aktivizohet, formularët deklarojnë se një kërkesë nuk mund të pranohet; nuk ruhet asgjë. Faqja hostohet nga Vercel Inc."],
      browser: ["Ruajtja në shfletues", "Ruajtja e sesionit mban përgjigjet me zgjedhje të shumëfishtë të GPS dhe të konfiguratorit, si edhe parametrat e kampanjës të vizitës tuaj, për këtë sesion të shfletuesit. Të dhënat e kontaktit, teksti i lirë, teksti i gdhendjes dhe informacioni për fëmijët nuk ruhen në shfletues."],
      analyticsOn: ["Analitika", "Me pëlqimin tuaj, Google Analytics 4 mat vizitat dhe eventet e formularëve pa të dhëna kontakti dhe pa tekstin e kërkesës. Zgjedhja juaj mbahet në ruajtjen lokale dhe mund të ndryshohet në çdo kohë nën “Cilësimet e analitikës” në fund të faqes. Formularët funksionojnë pa analitikë."],
      analyticsOff: ["Analitika", "Në këtë faqe nuk është aktiv asnjë instrument analitike."],
      retention: ["Ruajtja në kohë", "Nuk është konfiguruar ende asnjë periudhë fshirjeje automatike. Mund të kërkoni në çdo kohë fshirjen e kërkesës tuaj."],
      children: ["Fëmijët", "Formularët duhet të plotësohen nga një i rritur. Kërkesat që kanë të bëjnë me lojtarë nën 18 vjeç bëhen nga një prind ose kujdestar. Mos dorëzoni emrin, datëlindjen, shkollën ose informacionin mjekësor të një fëmije. Profilet e fëmijëve nuk publikohen kurrë."],
      rights: ["Të drejtat tuaja", "Për të aksesuar, korrigjuar ose fshirë kërkesën tuaj, shkruani në gps@maximus.tennis dhe citoni ID-në e kërkesës."],
      controlled: ["Informacioni i kontrolluar", "Dokumentet konfidenciale nuk ruhen dhe nuk shërbehen nga kjo faqe. Zbulimi i kontrolluar bëhet nën marrëveshje konfidencialiteti ose kontratë, përmes kanaleve të veçanta."],
    },
  },
  terms: {
    title: "Kushtet e përdorimit",
    copyright: "Të drejtat e autorit për këtë faqe — tekstet, fotografitë, dizajnin dhe kodin — i përkasin vetëm Maximus Kiriyakulov. Ato nuk janë kaluar asnjë kompanie dhe asnjë personi tjetër.",
    updated: "Versioni 2026-09-21",
    sections: [
      ["Informacion, nuk është ofertë", "Informacioni i produktit në këtë faqe përshkruan specifikime të miratuara, arkitekturë konfigurimi dhe shpjegime programesh. Nuk është ofertë për shitje, listë çmimesh, deklaratë stoku ose angazhim dorëzimi. Kushtet tregtare dakordohen veçmas me shkrim, me subjektin kontraktues të identifikuar në çdo transaksion."],
      ["Kërkesat", "Një kërkesë e dorëzuar përmes kësaj faqeje — përfshirë profilet GPS, kërkesat e konfigurimit dhe përshkrimet teknike — ruhet me një ID kërkese dhe rishikohet. Nuk është porosi e pranuar, angazhim prodhimi, takim i konfirmuar, aplikim anëtarësie ose aplikim i pranuar në ndonjë program."],
      ["Specifikimet dhe dëshmia", "Vlerat e llogaritura, objektivat e prodhimit dhe specifikimet e konfirmuara dallohen në faqet përkatëse. Vlerat e ngurtësisë janë objektiva prodhimi derisa të publikohet ndryshe. Nuk garantohet asnjë rezultat për një lojtar të caktuar."],
      ["Ekosistemi, anëtarësia dhe të drejtat", "Blerja e një rakete nuk krijon anëtarësi institucionale, të drejta investimi, pronësi të pronësisë intelektuale, të drejtë për honorare ose përfitime pjesëmarrjeje. Të drejtat ndjekin kushtet e publikuara të programit ose një marrëveshje me shkrim."],
      ["Pronësia intelektuale", "MAXIMUS®, emblema e luanit, shenja GPS dhe përmbajtja e kësaj faqeje janë të mbrojtura. Formulat e brendshme inxhinierike, protokollet e kontrollit të cilësisë, shtresimet, veglat e prodhimit, identitetet e furnitorëve, kostot dhe metodologjia e mbrojtur nuk zbulohen këtu."],
    ],
  },
  lead: {
    submit: "Dërgo kërkesën",
    submitting: "Po dërgohet…",
    retry: "Provo përsëri",
    acceptedEyebrow: "Kërkesa u pranua",
    acceptedTitle: "Kërkesa juaj është marrë.",
    requestId: "ID e kërkesës",
    acceptedNext: "MAXIMUS rishikon çdo kërkesë dhe përgjigjet me shkrim në adresën e emailit që dhatë. Mbajeni ID-në e kërkesës për çdo ndjekje.",
    duplicate: "Kjo kërkesë ishte marrë më parë; nuk u krijua dublikatë.",
    another: "Nisni një kërkesë të re",
    errorsTitle: "Kontrolloni këto fusha:",
    failTitle: "Kërkesa juaj nuk u dërgua.",
    fail: {
      offline: "Pajisja juaj është jashtë linje.",
      network: "Lidhja me serverin dështoi.",
      timeout: "Serveri nuk u përgjigj në kohë.",
      rate_limited: "Nga ky rrjet erdhën shumë kërkesa. Provoni përsëri pas disa minutash.",
      too_fast: "Formulari u dorëzua shumë shpejt. Kontrollojeni dhe dorëzojeni përsëri.",
      spam_suspected: "Kërkesa u ndal nga filtri i mesazheve të padëshiruara.",
      unavailable: "Kërkesat nuk mund të pranohen për momentin.",
      default: "Ndodhi një gabim i papritur.",
    },
    keepNote: "Të dhënat tuaja mbahen në këtë faqe, kështu që mund të provoni përsëri.",
    sendByEmail: "Dërgojeni këtë kërkesë me e-mail",
    sendByEmailNote: "Aplikacioni i e-mailit hapet me tekstin e kësaj kërkese. MAXIMUS e merr kur ta dërgoni e-mailin.",
    mailConfig: "Konfigurimi",
    mailPage: "Faqja",
    fallback: "Nëse problemi vazhdon, shkruani në {email}. Një kërkesë numërohet si e dorëzuar vetëm kur shfaqet një ID kërkese.",
    privacyLink: "Shënim për privatësinë",
    hpLabel: "Lëreni këtë fushë bosh",
    consentShort: "Pëlqimi",
    after: "Pas dorëzimit, në këtë faqe shfaqet një ID kërkese. Kërkesat rishikohen dhe marrin përgjigje me shkrim; një kërkesë nuk është porosi.",
    basis: { unstrung: "Pa tela", strung: "Me tela", unknown: "Nuk e di — do të dakordohet në specifikim" },
    hints: {
      email: "MAXIMUS përgjigjet me shkrim në këtë adresë.",
      goal: "Për shembull: raketa e parë e garave ose kalimi nga një raketë juniori. Mos përfshini emra, datëlindje ose informacion mjekësor për një fëmijë.",
      currentRacquet: "Marka dhe modeli, nëse dihen.",
      message: "Mos përfshini fjalëkalime, të dhëna pagesash ose informacion mjekësor.",
    },
  },
  choose: {
    eyebrow: "Ndihmë për zgjedhjen",
    title: "Ndihmomë të zgjedh një raketë",
    lead: "Thojini MAXIMUS nivelin tuaj dhe çfarë ka më shumë vlerë për ju. Përgjigjet tuaja rishikohen dhe marrni një propozim me shkrim: seria, klasa e precizionit, pesha dhe doreza.",
    stepsTitle: "Çfarë ndodh më pas",
    steps: [
      ["Përgjigjet tuaja", "Niveli, prioritetet dhe masa e dorezës, nëse e dini."],
      ["Rishikim nga ekspertët", "MAXIMUS krahason përgjigjet tuaja me matricat e serive."],
      ["Propozim me shkrim", "Një konfigurim i propozuar dhe hapi i radhës, me shkrim."],
    ],
    formTitle: "Përgjigjet tuaja",
    submit: "Kërkoni ndihmë për zgjedhjen",
    altTitle: "Preferoni të vendosni vetë?",
    altGps: "Profil i detajuar GPS",
    altBuild: "Konfiguroni drejtpërdrejt",
    note: "Pa përshtatje automatike dhe pa pohim saktësie: çdo kërkesë e rishikon një person.",
  },
  consent: {
    title: "Analitika",
    text: "A mund të matë MAXIMUS vizitat me Google Analytics? Formularët funksionojnë në çdo rast; në analitikë nuk dërgohen të dhëna kontakti dhe nuk dërgohet teksti i kërkesës.",
    allow: "Lejo analitikën",
    decline: "Refuzo",
  },
  familyPlan: {
    title: "Plani familjar",
    metaDescription: "Llogaritni buxhetin e tenisit për familjen tuaj: sesionet, orët, kontaktet me topin dhe koston e një sesioni, të një ore dhe të një goditjeje — nga numrat tuaj, në tre skenarë.",
    eyebrow: "Plani familjar · Kontribuoni me ne",
    heroTitle: "Sa i kushton tenisi familjes suaj — dhe çfarë merrni në këmbim?",
    heroLead: "Llogaritni buxhetin familjar, sesionet dhe orët që ai mbulon, kontaktet e vlerësuara me topin dhe koston e një sesioni, të një ore dhe të një goditjeje — sipas kushteve tuaja.",
    heroCta: "Llogaritni planin e familjes suaj",
    strategy: {
      eyebrow: "Qëllimi ynë",
      title: "Më shumë tenis. Më shumë mundësi. Së bashku.",
      p1: "Qëllimi ynë është ta rrisim dhjetëfish tregun botëror të tenisit, duke zgjeruar pjesëmarrjen dhe duke e bërë rrugën drejt tenisit më të qartë dhe më të arritshme. MAXIMUS synon të udhëheqë përmes menaxhimit, metodologjisë, cilësisë, rezultateve dhe popullarizimit të lojës.",
      p2: "Prodhuesit e tjerë në tenis dhe markat e tyre i shohim si partnerë të mundshëm. Propozojmë të bashkojmë forcat e kompanive, trajnerëve, klubeve dhe familjeve në një program të përbashkët për të zhvilluar, promovuar dhe zgjeruar tenisin, mbi baza përfitimi të ndërsjellë.",
      p3: "MAXIMUS është elementi i pestë i kësaj qasjeje: roli bashkues që i ndihmon forcat e veçanta të punojnë së bashku. Sfidat tona të përbashkëta janë sëmundjet, mungesa e aktivitetit fizik te fëmijët dhe pengesat që i ndalojnë njerëzit të fillojnë dhe të vazhdojnë të luajnë.",
      p4: "Për një familje, gjithçka nis me qartësinë. Plani familjar tregon buxhetin, numrin e sesioneve dhe të orëve, vëllimin e vlerësuar të kontakteve me topin dhe koston e praktikës. Ndryshoni kushtet dhe zgjidhni skenarin që ju përshtatet.",
      note: "Rritja dhjetëfish është objektivi strategjik i MAXIMUS, jo një rezultat i arritur tashmë. Kalkulatori tregon llogaritje sipas skenarëve dhe nuk premton asnjë kursim, asnjë efekt mjekësor dhe asnjë rezultat sportiv.",
      ctaCalc: "Llogaritni planin e familjes suaj",
      ctaPartner: "Diskutoni zhvillimin e përbashkët të tenisit",
    },
    beyond: {
      eyebrow: "Përtej fushës",
      title: "Çfarë ndërton plani përveç praktikës",
      admission: {
        h: "Pranimi në shkolla dhe universitete prestigjioze",
        p: "MAXIMUS e mbështet familjen në rrugën drejt shkollave dhe universiteteve prestigjioze në mbarë botën: ndërtimi i dosjes sportive të lojtarit, përgatitja e dokumenteve dhe e aplikimeve dhe zgjedhja e programeve ku sporti dhe studimi ecin bashkë. Në rastet kur jepet një bursë sportive, ajo ul shumën që familja paguan për arsimin.",
      },
      assets: {
        h: "Asete dixhitale: emri, imazhi dhe palmaresi i lojtarit",
        p: "Emri, imazhi, rezultatet, përmbajtja dhe marka personale e një lojtari janë asete dhe, me kalimin e kohës, mund të krijojnë vlerë të konsiderueshme financiare dhe statusi. MAXIMUS ndihmon që ato të krijohen, të regjistrohen dhe të mbrohen, në mënyrë që kjo vlerë t'u mbetet lojtarit dhe familjes.",
      },
      note: "Asnjëra prej tyre nuk është pjesë e kalkulatorit. Vlera e një vendi në shkollë, e një burse ose e një aseti dixhital varet nga rasti dhe nuk vlerësohet këtu.",
      cta: "Pyesni për mbështetjen në pranime dhe për asetet dixhitale",
    },
    steps: ["Të dhënat e familjes", "Ekonomia e sesionit", "Plani afatgjatë", "Llogaritja përfundimtare"],
    stepsLabel: "Hapat e kalkulatorit",
    scenarios: { now: "Tani", planned: "Në plan", wish: "Dëshira" },
    scenarioHints: { now: "Çfarë bën familja juaj sot.", planned: "Çfarë keni ndër mend të bëni më pas.", wish: "Çfarë do të dëshironit të bënit." },
    currency: {
      label: "Monedha",
      note: "Çdo shumë që vendosni është në këtë monedhë. Asgjë nuk konvertohet.",
    },
    fields: {
      players: { label: "Anëtarë të familjes që luajnë", hint: "Numër i plotë." },
      cost: { label: "Çmimi i një sesioni për një lojtar", hint: "Shumë e plotë, me taksat dhe tarifat të përfshira." },
      sessions: { label: "Sesione në muaj për lojtar", hint: "Numër i plotë." },
      minutes: { label: "Kohëzgjatja e një sesioni, në minuta", hint: "Koha e plotë, përfshirë pushimet. Lejohen numra dhjetorë." },
      contacts: { label: "Kontakte me topin për lojtar në një sesion", hint: "Kontakt është prekja e topit me raketën e vetë lojtarit. Një shkëmbim goditjesh nuk është një kontakt i vetëm. Numëroni në të njëjtën mënyrë në çdo skenar." },
    },
    presetsLabel: "Zgjedhje e shpejtë, minuta",
    ages: {
      title: "Kohëzgjatja e planit",
      start: "Mosha fillestare",
      end: "Mosha përfundimtare",
      hint: "Një supozim anonim për sa zgjat plani, i përdorur vetëm për tabelën afatgjatë. Nuk është datëlindje dhe as moshë fillestare e rekomanduar.",
    },
    extras: {
      title: "Kosto shtesë të familjes",
      note: "Këto shuma janë për gjithë familjen dhe vlejnë për të tre skenarët. Nuk shumëzohen me numrin e lojtarëve dhe nuk hyjnë në koston e një ore ose të një kontakti.",
      equipment: "Pajisjet e para — një shumë për periudhën",
      clothing: "Veshje dhe këpucë — një shumë për periudhën",
      renewal: "Rinovimi i pajisjeve — një shumë për periudhën, pa u përsëritur automatikisht",
      court: "Fusha ose klubi — në muaj, për gjithë familjen",
      travel: "Udhëtime dhe aktivitete — në muaj, për gjithë familjen",
      quoteSource: "Nga vijnë çmimet (opsionale)",
      quoteDate: "Data e çmimeve (opsionale)",
      quoteNote: "Shfaqet saktësisht siç e keni vendosur. MAXIMUS nuk i verifikon këto çmime.",
    },
    storage: {
      save: "Ruaj planin në këtë pajisje",
      clear: "Fshi planin nga kjo pajisje",
      saved: "Plani u ruajt në këtë pajisje. Asgjë nuk u dërgua askund.",
      cleared: "Plani u fshi. Kalkulatori u kthye në vlerat fillestare.",
      restored: "Plani juaj i ruajtur në këtë pajisje u rikthye.",
      invalid: "Një plan i ruajtur në këtë pajisje nuk mund të lexohej dhe nuk u zbatua. Mund të nisni një llogaritje të re.",
      unavailable: "Ky shfletues nuk lejon ruajtjen në pajisje.",
    },
    annual: {
      title: "Një vit, krah për krah",
      sessions: "Sesione-lojtar në vit",
      cost: "Shpenzimet e familjes për sesionet në vit",
      hours: "Orë-lojtar në vit",
      length: "Kohëzgjatja e një sesioni",
      contacts: "Kontakte me topin në vit",
      note: "Sesionet-lojtar dhe orët-lojtar mbledhin sesionet e çdo lojtari. Nuk janë orë qiraje të fushës as takime grupi: dy lojtarë që stërviten bashkë për 90 minuta përbëjnë 2 sesione-lojtar dhe 3 orë-lojtar.",
    },
    economics: {
      title: "Kostoja e një sesioni, e një ore dhe e një kontakti",
      session: "Një sesion i një lojtari",
      hour: "Një orë praktike e një lojtari",
      contact: "Një kontakt me topin",
      undefinedContacts: "E papërcaktuar: 0 kontakte",
      undefinedMinutes: "E papërcaktuar: 0 minuta",
      below: "më pak se {value}",
      note: "Në këto shifra hyn vetëm çmimi i sesionit. Kostot shtesë të familjes nuk ndahen me kontaktet.",
      caption: "Numri i kontakteve llogaritet nga vëllimi i zgjedhur i sesioneve dhe nga supozimet e modelit. Praktika reale varet nga formati, pushimet dhe kushtet e stërvitjes. Kostoja e një kontakti është tregues buxheti, jo tregues i cilësisë së punës së trajnerit.",
    },
    longTerm: {
      title: "Plani afatgjatë i shpenzimeve",
      horizon: "Horizonti",
      activeYears: "Vite aktive",
      years: "Vite: {n}",
      note: "Vitet aktive kufizohen nga diferenca midis dy moshave. Çmimet, frekuenca, inflacioni, sezonet, sesionet e humbura dhe kurset e këmbimit mbahen konstante. Kostot shtesë nuk janë pjesë e kësaj tabele.",
    },
    final: {
      title: "Llogaritja përfundimtare",
      scenario: "Skenari",
      months: "Periudha, në muaj",
      heading: "{scenario} · {months} muaj",
      total: "Totali për periudhën",
      training: "Sesionet",
      extras: "Kostot shtesë",
      oneOff: "Zëra të njëhershëm",
      monthly: "Zëra mujorë × muaj",
      sessions: "Sesione-lojtar në periudhë",
      hours: "Orë-lojtar në periudhë",
      contacts: "Kontakte me topin në periudhë",
      formulaTitle: "Si llogaritet",
      formula: "Totali = lojtarë × sesione në muaj × muaj × çmimi i sesionit + kosto të njëhershme + muaj × kosto shtesë mujore.",
      formulaNote: "Kostot shtesë vendosen për gjithë familjen. Zërat e njëhershëm llogariten një herë, edhe për një periudhë prej 0 muajsh.",
      inputs: "Të dhënat tuaja",
    },
    units: { min: "min", h: "orë", approx: "≈" },
    errors: {
      title: "Korrigjoni këto fusha për të parë rezultatin",
      required: "E detyrueshme — vendosni një numër; lejohet 0.",
      negative: "Nuk mund të jetë negativ.",
      integer: "Vetëm numër i plotë.",
      number: "Vendosni një numër.",
      tooLarge: "Ky numër është shumë i madh për t'u llogaritur.",
      endBeforeStart: "Mosha përfundimtare nuk mund të jetë më e ulët se mosha fillestare.",
      tooLong: "Jo më shumë se 200 karaktere.",
      date: "Vendosni një datë të vlefshme.",
      currency: "Zgjidhni një monedhë.",
      scenario: "Zgjidhni një skenar.",
      result: "Rezultati është shumë i madh për t'u shfaqur në mënyrë të besueshme. Zvogëloni vlerat e vendosura.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: kompozimi i plotë — trajnuesi i parë nga përpara dhe nga ana, rrethi i gdhendur me luan në kokën e rrumbullakët të kontaktit, gdhendja MAXIMUS dhe SPOT TRAINER përgjatë bishtit, dhe kapaku tetëkëndor fundor me shenjën e luanit",
    greatHero: "Seria MAXIMUS GREAT, 363 g: kompozimi i plotë me detaje të kuqe dhe të verdha në kokë, shkrimi MAXIMUS me shkëlqim, autografi Maximus në bisht dhe luani në dorezë",
    spotDetail: "Dy MAXIMUS Spot Trainer nga më afër: luani i gdhendur në kokën mat të zezë të kontaktit, mbështjellja me rrudha e dorezës dhe kapakët tetëkëndorë fundorë me shenjën e luanit",
    spotPair: "Dy MAXIMUS Spot Trainer të vendosur me kënd mbi një sipërfaqe të errët, MAXIMUS i gdhendur përgjatë një bishti dhe SPOT TRAINER përgjatë tjetrit, me rrethin e luanit në çdo kokë kontakti",
    spinVisual: "MAXIMUS SPIN: koka me tela, shkrimi MAXIMUS me shkëlqim, doreza dhe kapaku fundor me luan",
    powerVisual: "MAXIMUS POWER: koka me tela, shkrimi MAXIMUS me shkëlqim, gdhendja e personalizimit, doreza dhe kapaku fundor me luan",
    greatVisual: "MAXIMUS GREAT: koka me tela, shkrimi MAXIMUS me shkëlqim, gdhendja e personalizimit, doreza, kapaku fundor me luan dhe shenja e serisë G në qafë",
    spinHead: "Koka dhe shtroja e telave MAXIMUS SPIN",
    handleLion: "Qafa, doreza dhe kapaku fundor MAXIMUS me shenjën e luanit",
    engraving: "Gdhendje personalizimi në argjend përgjatë bishtit",
    lettering: "Shkrim MAXIMUS i zi me shkëlqim mbi kornizë të zezë mat",
    variantAlt: "Seria MAXIMUS {series} — {w} g, balanca {b} mm: vizualizim i plotë me shiritin e specifikimit, zonën e gdhendjes së personalizimit dhe markimin MIPA",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistem me katër raketa",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Bishtat e Sweet Spot Trainer me shkrimin MAXIMUS",
    sstGrips: "Dorezat dhe kapakët fundorë të Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, katër kapakë fundorë me shenjën e luanit",
    note: "Vizual i produktit",
  },
  notFound: { title: "Faqja nuk u gjet", p: "Faqja që kërkuat nuk ekziston në këtë gjuhë.", cta: "Shkoni në faqen kryesore" },
};

export default sq;
