/* Serbian dictionary (Latin script) — MAXIMUS website. Numerical product data lives in data/products.js. */
const sr = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — teniski reketi u celosti od karbona, projektovani prema specifikaciji",
    defaultDescription:
      "Teniski reketi u celosti od karbona, od rama do ručke: GREAT 97 in², POWER 98 in² i SPIN 100 in², osam fabričkih veličina ručke L0–L7, klase preciznosti za težinu, balans, swingweight i krutost, kao i inženjering po meri na zahtev.",
  },
  common: {
    statuses: {
      current: "Aktuelno",
      agreement: "Dostupno po dogovoru",
      development: "U razvoju",
      concept: "Koncept",
      target: "Proizvodni cilj",
      modelled: "Izračunato",
      confirmed: "Potvrđeno",
      requested: "Zahtevana arhitektura",
      notprovided: "Nije dostavljeno",
    },
    brief: { who: "Za koga je", value: "Šta dobijate", now: "Potvrđeno sada", next: "Sledeći korak" },
    labels: {
      next: "Dalje",
      back: "Nazad",
      edit: "Uredite odgovore",
      review: "Provera",
      start: "Počnite",
      restart: "Počnite iznova",
      copy: "Kopirajte tekst zahteva",
      copied: "Kopirano",
      openEmail: "Otvorite e-poštu da pošaljete ovaj zahtev",
      reference: "Referenca zahteva",
      weight: "Težina",
      balance: "Balans",
      swingweight: "Swingweight",
      stiffness: "Krutost",
      grip: "Veličina ručke",
      headSize: "Veličina glave",
      series: "Serija",
      precisionClass: "Klasa preciznosti",
      quantity: "Količina",
      notProvided: "Još nije objavljeno",
      requestTarget: "Zahtevani cilj",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Pročitajte više",
      allSeries: "Sve serije",
      points: "navedene težine",
      optional: "opciono",
      required: "obavezno",
      select: "Izaberite",
      yes: "Da",
      no: "Ne",
      unknown: "Nisam siguran",
      custom: "Cilj po meri",
      listed: "Navedena težina",
      individual: "Pojedinačni reket",
      pair: "Usklađeni par",
      triple: "Usklađena trojka",
      team: "Timski set",
      summaryTitle: "Sažetak vašeg zahteva",
      nextAction: "Sledeća radnja",
      status: "Status",
      learn: "Saznajte više",
      schematic: "Šema — nije merenje",
      photo: "Fotografija",
    },
    ecosystemStrip: "MAXIMUS ekosistem",
    truth: {
      noPrices: "Cene, minimalne količine, rokovi izrade, garancije i obaveze isporuke potvrđuju se u pisanoj formi, za svako tržište i svaki program.",
      requestNotOrder: "Zahtev je zahtev za razmatranje. Nije prihvaćena narudžbina, proizvodna obaveza niti potvrđen termin.",
      noGuarantee: "Nijedna oprema, metod ili program opisan ovde ne garantuje rezultat konkretnom igraču.",
      governing: "Ova stranica se objavljuje na više jezika. Engleska verzija je obavezujuća; prevod je dat radi lakšeg razumevanja.",
    },
  },
  nav: {
    language: "Jezik",
    groups: { racquets: "Reketi", training: "Trening", ecosystem: "Ekosistem", partnerships: "Partnerstva" },
    familyPlan: "Porodični plan",
    racquets: "Serije reketa i uporedni pregled",
    great: "GREAT — 97 in² · Kontrola",
    power: "POWER — 98 in² · Snaga",
    spin: "SPIN — 100 in² · Rotacija",
    precision: "Preciznost i krutost",
    grip: "Fabrička arhitektura ručke L0–L7",
    custom: "Inženjering po meri",
    training: "Sistemi za trening",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologija",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Pomoć pri izboru",
    ecosystem: "Mapa ekosistema",
    engineering: "Inženjering i proizvodnja",
    experience: "Testiranje i prilagođavanje",
    brands: "Lični brendovi i ambasadori",
    families: "Porodice i roditelji",
    owners: "Vlasnici i trezor vlasnika",
    network: "Sports Network",
    partnerships: "Svi putevi partnerstva",
    coaches: "Treneri",
    clubs: "Klubovi i akademije",
    distribution: "Distribucija i razvoj tržišta",
    strategic: "Strategija i investicije",
    institutional: "Institucionalni programi",
    contact: "Kontakt",
    legal: "Pravni identitet",
    privacy: "Privatnost",
    terms: "Uslovi korišćenja",
    menu: "Meni",
    close: "Zatvorite",
    home: "Početna",
    skip: "Pređite na sadržaj",
  },
  footer: {
    line: "Reket MAXIMUS je vaš ključ za svet MAXIMUS.",
    product: "Proizvod",
    ecosystem: "Ekosistem",
    company: "Organizacija",
    instagram: "Instagram",
    email: "E-pošta",
    analytics: "Podešavanja analitike",
    subscribe: {
      title: "Ostanite uz MAXIMUS",
      line: "Nove serije, termini prilagođavanja, materijali za trening i program za vlasnike. Nekoliko pisama godišnje, ništa više.",
      label: "Adresa e-pošte",
      placeholder: "your@email.com",
      button: "Pretplatite se",
      sending: "Šalje se",
      done: "Adresa je na listi. Pišemo samo kada imamo nešto vredno čitanja.",
      invalid: "Proverite adresu.",
      failed: "Adresa nije zabeležena. Pokušajte ponovo za trenutak.",
      terms: "Pretplatom prihvatate da vam MAXIMUS može da šalje ta obaveštenja i da u tu svrhu čuva vašu adresu. Svako pismo sadrži link za odjavu.",
    },
    rights: "MAXIMUS® i amblem lava su oznake MAXIMUS ekosistema. MIPA: interna kontrola intelektualne svojine, porekla i dokumentacije.",
    boundary:
      "Komercijalni i ugovorni uslovi dogovaraju se posebno, u pisanoj formi. Kupovina reketa ne stvara institucionalno članstvo, investicijska prava, vlasništvo nad intelektualnom svojinom niti pravo na tantijeme.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Preciznost počinje u trenutku udara.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer i MAXIMUS metodologija povezuju fokusiran trening sa reketima visokih performansi u celosti od karbona.",
    heroCta1: "Istražite sistem za trening",
    heroCta2: "Istražite GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrola",
    heroMeta: [
      ["U celosti od karbona", "od rama do ručke"],
      ["4 parametra", "težina · balans · swingweight · krutost"],
      ["8 veličina ručke", "fabrička geometrija L0–L7"],
      ["3 serije", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Porodični plan · Doprinesite sa nama",
      title: "Vaš porodični budžet. Šta za njega dobijate. Šta njime gradite.",
      p: "Tri scenarija jedan pored drugog — trenutno, planirano i željeno. Koliko treninga, sati i kontakata sa lopticom pokriva vaš budžet i koliko košta jedan trening, jedan sat i jedan udarac — sve izračunato na osnovu vaših sopstvenih brojeva.",
      points: [
        ["Vaši brojevi", "Svaki iznos dolazi od vas. Bez pretpostavki i bez preračunavanja valuta."],
        ["Tri scenarija", "Uporedite ono što radite sada sa onim što planirate i sa onim što biste želeli."],
        ["Deset godina unapred", "Plan troškova za period od jedne do deset godina, ograničen rasponom uzrasta koji sami odredite."],
        ["Van terena", "Podrška pri upisu u vodeće škole i digitalna imovina koja ostaje igraču."],
      ],
      cta: "Izračunajte svoj porodični plan",
    },
    paths: {
      eyebrow: "Počnite odavde",
      title: "Izaberite svoj put",
      items: {
        player: { h: "Igrač", p: "Pronađite reket po nivou i prioritetima ili ga odmah konfigurišite.", a: "Pronađite svoj reket" },
        parent: { h: "Roditelj", p: "Pisani put za razvojne ciljeve, uključenost trenera i odgovarajuću opremu.", a: "Put za porodice" },
        coach: { h: "Trener, klub ili akademija", p: "Sistemi za trening, prilagođavanje, timski setovi i personalizacija.", a: "Putevi za trenere i klubove" },
        partner: { h: "Distributer ili partner", p: "Distribucija, razvoj tržišta, strateški i institucionalni putevi.", a: "Putevi partnerstva" },
      },
    },
    series: {
      eyebrow: "Serije visokih performansi",
      title: "Tri arhitekture performansi. Jedna inženjerska platforma.",
      lead: "Izaberite seriju prema pravcu igre, a zatim dovršite konfiguraciju: klasa preciznosti, težina, ručka, personalizacija.",
      cta: "Uporedite serije",
      configure: "Konfigurišite",
      open: "Otvorite seriju",
      photoPending: "Fotografija još nije objavljena",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS sistem preciznosti",
      title: "Težina. Balans. Swingweight. Krutost.",
      sub: "Kontrolisani kao jedan inženjerski sistem.",
      lead: "Tri klase preciznosti određuju koliko se strogo svaki gotov reket drži svoje deklarisane specifikacije. P0.5 je uska tolerancija pod definisanim protokolom merenja — a ne nulta greška.",
      cta: "Preciznost i krutost detaljno",
    },
    stiffness: {
      eyebrow: "Krutost",
      title: "Ponovljiv odziv rama prema deklarisanom cilju.",
      p: "Krutost rama oblikuje odziv, osećaj i doslednost između reketa. MAXIMUS je tretira kao četvrti kontrolisani parametar: cilj, izmereni rezultat, dozvoljena tolerancija i mogućnosti mernog instrumenta vode se kao odvojeni zapisi. Korist je ponovljivost — a ne garantovan rezultat za svakog igrača.",
      cols: [["Odziv", "Kako ram vraća energiju u trenutku udara."], ["Osećaj", "Šta igrač oseća u trenutku udara."], ["Doslednost", "Reketi izrađeni po istoj specifikaciji reaguju jednako, u okviru svoje klase."]],
      schematicCaption: "Šema: dozvoljeno odstupanje oko deklarisanog cilja krutosti za svaku klasu. Nije merenje; nijedna RA vrednost se ne podrazumeva.",
      bands: { p25: "tolerancija cilja ±1 RA", p15: "tolerancija cilja ±0.5 RA", p05: "odgovara deklarisanoj ciljnoj RA vrednosti po utvrđenom fabričkom protokolu merenja — a ne nulta greška", target: "deklarisani cilj (bez podrazumevane vrednosti)" },
    },
    carbon: {
      eyebrow: "Standard konstrukcije",
      title: "U celosti od karbona. Od rama do ručke.",
      p: "Svi aktuelni MAXIMUS reketi na ovoj platformi su po svojoj strukturi u celosti od karbona, uključujući i ručku. Pena se ne koristi za formiranje ručke.",
      gripTitle: "Osam fabričkih veličina ručke. L0–L7.",
      gripP: "Svaka veličina je fabrička geometrija karbonske ručke — a ne nadogradnja overgripom.",
      scaleCaption: "Šema: nominalne oznake veličina ručke L0–L7 (4″ do 4⅞″). Nisu izmerene dimenzije ručke.",
      cta: "Fabrička arhitektura ručke",
    },
    custom: {
      eyebrow: "Inženjering po meri",
      title: "Projektovano prema specifikaciji.",
      sub: "Standardni asortiman je polazna tačka.",
      p: "MAXIMUS prihvata tehničke zahteve izvan objavljenih matrica radi procene, inženjerskog razvoja, validacije i proizvodnje prema dogovorenoj specifikaciji. Izvodljivost se potvrđuje u pisanoj formi.",
      chain: ["Definisanje", "Inženjering", "Validacija", "Specifikacija", "Proizvodnja", "Merenje / evidentiranje"],
      cta: "Pošaljite tehnički zahtev",
      cta2: "Razgovor o inženjeringu po meri",
    },
    training: {
      eyebrow: "Sistemi za trening",
      title: "Sistem treninga izgrađen oko trenutka udara.",
      p: "Sweet Spot Trainer, MAXIMUS metodologija i Spot Trainer povezuju opremu sa treningom pod vođstvom trenera: centriran udar, kontrola, progresivno opterećenje i prelazak natrag na reket za igru.",
      cta: "Sistemi za trening",
      cta2: "Zatražite demonstraciju",
      photoPending: "Fotografija trenažnog reketa još nije objavljena",
      sstP: "Trenažna glava od 50 in² za vežbanje centriranog udara, sa četiri konfiguracije težine za opterećenje koje određuje trener.",
      sstCta: "Istražite Sweet Spot Trainer",
      sstCaption: "Konfiguracija od 300 g, jedna od četiri",
      methodP: "Postavite ciljeve, izaberite opremu, trenirajte uz uključenost trenera, zabeležite zapažanja, ponovo procenite, prilagodite i prenesite rad u takmičarsku igru.",
      methodCta: "Istražite metodologiju",
      spotP: "Mala okrugla meta za vežbanje precizne i ponovljive tačke udara.",
      spotCta: "Istražite Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Proizvodnja i kontrola kvaliteta",
      title: "Izrađeno prema specifikaciji. Izmereno i evidentirano.",
      p: "Proizvodnja prati pisanu specifikaciju svake narudžbine. Zapisi zavise od klase preciznosti: sačuvana proizvodna evidencija za P2.5, pojedinačni zapisi i sledivost za P1.5, pojedinačna kontrola i dokumentacija za P0.5 tamo gde ih program za tu narudžbinu sprovodi.",
      confirmedTitle: "Potvrđeno",
      confirmed: ["Konstrukcija u celosti od karbona, od rama do ručke.", "Klase preciznosti P2.5, P1.5 i P0.5 sa četiri kontrolisana parametra.", "Osam fabričkih veličina ručke L0–L7."],
      pendingTitle: "Još nije objavljeno",
      pending: "Fotografije merne opreme, primeri zapisa kontrole kvaliteta i snimci iz fabrike još nisu objavljeni. Ništa na ovoj stranici nije sertifikat o merenju.",
      captions: { lettering: "Sjajni MAXIMUS natpis na mat ramu", buttcap: "Ručka i poklopac ručke sa oznakom lava", handle: "Srebrna gravura personalizacije", finish: "Glava i površina žica" },
      cta: "Inženjering i proizvodnja",
    },
    world: {
      eyebrow: "Svet MAXIMUS",
      title: "Jedan ključ. Jedan ekosistem. Neograničene mogućnosti.",
      note: "„Neograničene mogućnosti“ je izraz brenda, a ne obećanje neograničene tehničke izvodljivosti, prihoda ili pristupa. Kupovina ne stvara tantijeme, investicijske prinose, sponzorstvo niti finansiranje razvoja igrača.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — i vaša navigacija u svetu tenisa: vođeni profil opreme na koji se odgovara u pisanoj formi." },
        personal: { h: "Personalizacija", p: "Imena, inicijali, brojevi i timska identifikacija u odobrenoj tehnici srebrne gravure." },
        development: { h: "Razvoj", p: "Sistemi za trening pod vođstvom trenera, zapisi i ponovna procena." },
        ecosystem: { h: "Prošireni ekosistem", p: "Lični brendovi, zapisi vlasnika, mreža, licenciranje i institucionalni programi — svaki prikazan sa svojim stvarnim statusom." },
      },
      cta: "Istražite ekosistem",
    },
    partners: {
      eyebrow: "Putevi partnerstva",
      title: "Treneri, klubovi, distributeri i partneri.",
      p: "Prvo pisana kvalifikacija. Prava za zemlju, ekskluzivnost i komercijalni uslovi dogovaraju se u pisanoj formi — nikada se ne dodeljuju putem obrasca.",
      cta: "Svi putevi partnerstva",
      formTitle: "Kratak upit",
      formLead: "Izaberite svrhu i pišite MAXIMUS-u. ID zahteva dobijate na ovoj stranici.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "VAŠA NAVIGACIJA U SVETU TENISA" } },
    personal: { eyebrow: "Personalizacija", title: "Vaše ime. Vaš broj. Vaš MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tri serije. Stvarni parametri." },
    map: { cta: "Istražite ekosistem" },
  },
  racquets: {
    title: "Reketi",
    lead: "Tri serije visokih performansi sa zajedničkim standardom konstrukcije, zajedničkim sistemom preciznosti i zajedničkom fabričkom arhitekturom ručke. Svaka serija je ustanovljena arhitektura performansi unutar šire inženjerske platforme.",
    direction: { control: "Kontrola", power: "Snaga", spin: "Rotacija" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Primarni pravac igre",
    compareTitle: "Uporedni pregled serija",
    compareLead: "Samo potvrđeni podaci o arhitekturi. Šeme žica, dužine, profili rama, opsezi napetosti žica i nominalne vrednosti za swingweight i krutost za ove serije nisu objavljeni; prikupljaju se kao zahtevani ciljevi za tehničko razmatranje.",
    columns: { series: "Serija", head: "Veličina glave", direction: "Pravac", weights: "Navedene težine", range: "Opseg težine", balance: "Podaci o balansu" },
    balanceModelled: "Izračunate vrednosti",
    balanceNotProvided: "Još nije objavljeno",
    construction: "Konstrukcija: u celosti od karbona, od rama do ručke · Preciznost: P2.5 / P1.5 / P0.5 · Ručke: L0–L7",
    otherTitle: "Drugi reketski sportovi",
    otherLead: "Odobreni pravci razvoja. U ovim kategorijama ne postoje proizvodi za prodaju i nijedna teniska specifikacija se na njih ne prenosi.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Skvoš", badminton: "Badminton", racquetball: "Reketbol", beachTennis: "Beach tenis" },
    ctaConfigure: "Konfigurišite zahtev",
    ctaSeries: "Otvorite seriju",
  },
  seriesPage: {
    eyebrow: "Serije visokih performansi",
    intro: {
      great: "Arhitektura GREAT od 97 in² izgrađena je oko kontrole: kompaktna glava, precizan udar i sigurnost u pravcu udarca.",
      power: "Arhitektura POWER od 98 in² izgrađena je oko prenosa energije: dubina i brzina iz stabilnog rama.",
      spin: "Arhitektura SPIN od 100 in² izgrađena je oko ponašanja loptice: rotacija, margina i oblikovanje putanje.",
    },
    photoPending: "Fotografija serije još nije objavljena",
    detailPending: "Fotografije detalja konstrukcije i ručke za ovu seriju još nisu objavljene.",
    specsTitle: "Specifikacija i status",
    catalogue: {
      eyebrow: "Katalog serije {series}",
      title: "Varijante težine: {n}",
      lead: "Svaka varijanta serije {series}, sortirana po težini. Težina u gramima, balans u milimetrima od kraja ručke. Svaka vizualizacija prikazana je u celini: ništa nije isečeno, maskirano ni rastegnuto.",
      selectLabel: "Izaberite varijantu težine",
      select: "Prikažite ovu varijantu",
      selected: "Prikazano iznad",
      balanceLabel: "Balans",
      headLabel: "Veličina glave",
      constructionLabel: "Konstrukcija",
      gripsLabel: "Fabričke veličine ručke",
      precisionLabel: "Klase preciznosti",
      balanceConfirmed: "Balans je potvrđena vrednost za ovu težinu i odgovara broju ispisanom na vizualizaciji. Cene, zalihe i rokovi isporuke se ovde ne objavljuju.",
      balanceModelled: "Balans je izračunata vrednost za ovu navedenu težinu, a ne pojedinačno fabričko merenje; odgovara broju ispisanom na vizualizaciji. Cene, zalihe i rokovi isporuke se ovde ne objavljuju.",
      zoom: "Otvorite sliku",
      close: "Zatvorite",
      allTitle: "Sve varijante ({n})",
    },
    specs: { head: "Veličina glave", direction: "Primarni pravac", weights: "Navedene težine", range: "Opseg težine", balance: "Balans", construction: "Konstrukcija", grips: "Fabričke ručke", precision: "Klase preciznosti" },
    construction: "U celosti od karbona, od rama do ručke",
    statusTitle: "Status vrednosti",
    matrixTitle: "Puna matrica težina",
    matrixLead: "Navedene težine su standardni izbor. Druge težine mogu se zahtevati kao ciljevi po meri; međuvrednosti koje ne postoje ne dodaju se.",
    balanceNote: {
      confirmed: "Vrednosti balansa potvrđene su za svaku navedenu težinu (mm od kraja ručke) i odgovaraju broju ispisanom na vizualizaciji te težine. Ne izračunavaju se ovde i ne izglađuju se između susednih težina; osnova merenja potvrđuje se u pisanoj specifikaciji.",
      modelled: "Vrednosti balansa izračunate su za svaku navedenu težinu (mm od kraja ručke). Nisu pojedinačna fabrička merenja; osnova merenja potvrđuje se u pisanoj specifikaciji.",
      notprovided: "Vrednosti balansa za ovu seriju nisu dostavljene. Ne izvodite ih iz druge serije.",
    },
    optionsTitle: "Preciznost, ručka i težina",
    notPublished: "Nije objavljeno za ovu seriju: šema žica, dužina, profil rama, opseg napetosti žica, swingweight i vrednosti krutosti. Možete ih navesti kao zahtevane ciljeve za tehničko razmatranje.",
    offerTitle: "Šta se dešava posle vašeg zahteva",
    offerSteps: [
      ["Zahtev", "Pošaljite konfiguraciju ili pitanje. ID zahteva se prikazuje odmah."],
      ["Razmatranje", "MAXIMUS razmatra seriju, klasu, težinu, ručku i sve zahtevane ciljeve."],
      ["Pisani odgovor", "Specifikacija, dostupnost i komercijalni uslovi potvrđuju se u pisanoj formi."],
    ],
    faqTitle: "Pitanja",
    faq: [
      ["Da li su vrednosti balansa izmerene?", "Izračunate su za navedene težine, nisu pojedinačna merenja. Osnova merenja potvrđuje se u pisanoj specifikaciji."],
      ["Mogu li da zahtevam težinu koja nije navedena?", "Da, kao cilj po meri u celim gramima. Razmatra se tehnički, a izvodljivost se potvrđuje u pisanoj formi."],
      ["Šta menja klasa preciznosti?", "Koliko se strogo težina, balans, swingweight i krutost drže deklarisane specifikacije i koji se zapisi vode."],
      ["Da li se ručka nadograđuje overgripovima?", "Ne. L0–L7 su fabričke geometrije karbonske ručke."],
      ["Gde su cene i rokovi isporuke?", "Potvrđuju se u pisanoj formi za svaki zahtev i ne objavljuju se ovde."],
    ],
    faqSpinBalance: ["Odakle dolaze vrednosti balansa za SPIN?", "Iz potvrđene tabele serije Spin: 33 varijante težine sa balansom u milimetrima od kraja ručke. Svaki par odgovara broju ispisanom na odobrenoj vizualizaciji te težine. Vrednosti se ne izračunavaju i ne izglađuju između susednih težina."],
    ctaBuild: "Konfigurišite ovu seriju",
    ctaAsk: "Pitajte o ovoj seriji",
    ctaCompare: "Uporedite sve serije",
    weightsLabel: "navedene težine",
    headLabel: "glava",
  },
  precision: {
    title: "Preciznost i krutost",
    switch: { label: "Izaberite klasu preciznosti", panelLabel: "Četiri kontrolisana parametra —", qcLabel: "Arhitektura kontrole kvaliteta", protocolNote: "po definisanom fabričkom protokolu merenja za kontrolu kvaliteta", fullTable: "Puna uporedna tabela" },
    lead: "Četiri parametra kontrolisana kao jedan inženjerski sistem. Svaka klasa definiše koliko se strogo gotov reket drži svoje deklarisane specifikacije i koji se zapisi kvaliteta izrađuju.",
    statement: "Težina. Balans. Swingweight. Krutost. Kontrolisani kao jedan inženjerski sistem.",
    classes: {
      "P2.5": { name: "Skalabilna osnova performansi", qc: "Pojedinačno merenje i sačuvana proizvodna evidencija." },
      "P1.5": { name: "Napredna preciznost", qc: "Pojedinačno merenje, pojedinačni zapisi i sledivost." },
      "P0.5": { name: "Profesionalno · pojedinačno kontrolisano", qc: "Pojedinačna kontrola sa nominalnim i stvarnim vrednostima i pojedinačnim zapisima merenja; serijski identitet, sledivost proizvodne serije, sertifikat preciznosti i usklađeni setovi tamo gde ih program za tu narudžbinu sprovodi." },
    },
    columns: { cls: "Klasa", weight: "Težina", balance: "Balans", sw: "Swingweight", stiff: "Krutost", qc: "Arhitektura kontrole kvaliteta" },
    stiffTarget: "tolerancija cilja",
    stiffExact: "odgovara deklarisanoj ciljnoj RA vrednosti po utvrđenom fabričkom protokolu merenja",
    programmeNote: "Serijski identitet, sertifikati i dokumentacija o usklađenim setovima izdaju se samo tamo gde ih program za konkretnu narudžbinu sprovodi.",
    targetsNote: "Specifikacije krutosti su proizvodni ciljevi dok odgovarajući protokol i proizvodni dokazi ne potkrepe jaču tvrdnju. Postavka arhitekture ne znači da je svaka navedena konfiguracija već prošla kompletan postupak odobravanja po sva četiri parametra.",
    stiffnessTitle: "Zašto je krutost važna",
    stiffnessP1: "Krutost rama utiče na to kako ram reaguje u trenutku udara, kakav je osećaj i koliko su dva reketa međusobno dosledna. Glavna korist od njene kontrole je ponovljiv odziv prema deklarisanoj specifikaciji.",
    stiffnessP2: "Pre objavljivanja verifikovane usklađenosti, interni zapis kontrole kvaliteta identifikuje instrument, status njegove kalibracije, metod, stanje reketa, rezoluciju, mernu nesigurnost, ponovljena merenja, pravilo zaokruživanja i pravilo prihvatanja. Isti prikazani ceo broj nije dokaz nulte fizičke varijacije ni nulte greške merenja.",
    fields: ["Cilj", "Izmereni rezultat", "Dozvoljena tolerancija", "Mogućnosti mernog instrumenta"],
    fieldsNote: "Vode se kao odvojena polja u svakom zapisu.",
    matchedTitle: "Usklađeni setovi",
    matchedP: "Kriterijumi za usklađeni set definišu se odvojeno od pojedinačne tolerancije. Usklađenost svakog reketa sa njegovom nominalnom tolerancijom sama po sebi ne dokazuje određenu najveću razliku između dva reketa. Usklađeni parovi, trojke i timski setovi zahtevaju se preko konfiguratora i potvrđuju u pisanoj formi.",
    extendedTitle: "Prošireni tehnički model",
    extendedP: "Model podataka podržava dodatne parametre. Za njih još ne postoje vrednosti ni klase tolerancije; mogu se navesti kao zahtevani ciljevi u tehničkom zahtevu.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Torziono ponašanje", length: "Dužina", beamProfile: "Profil rama", headGeometry: "Geometrija glave", stringPattern: "Šema žica", durability: "Trajnost", vibration: "Karakteristike vibracija" },
    noZero: "MAXIMUS ne opisuje svoj navedeni asortiman kao asortiman sa nultom tolerancijom. Preciznost u asortimanu se navodi kao klasa sa deklarisanom tolerancijom i definisanom arhitekturom kontrole kvaliteta. ZERO nije deo asortimana.",
    zero: {
      eyebrow: "Ekskluzivna opcija",
      title: "ZERO",
      sub: "Nulta tolerancija na gram.",
      p: "Tri klase drže gotov reket unutar deklarisanog raspona. ZERO ukida taj raspon. Reket se izrađuje i meri dok izmerena vrednost ne bude jednaka deklarisanoj vrednosti u rezoluciji fabričkog mernog instrumenta, a ta vrednost se izdaje sa njim. Nije deo navedenog asortimana ni četvrta klasa: dogovara se pojedinačno, za jedan reket ili jedan usklađeni set, kao ekskluzivna izrada po meri. Po dogovoru se isti pristup primenjuje na balans i swingweight.",
      points: [
        ["Bez raspona", "Deklarisana vrednost je rezultat, a ne središte tolerancije."],
        ["Jedan po jedan", "Izrađuje se, meri i evidentira kao pojedinačna jedinica."],
        ["Izdaje se sa reketom", "Izmerena vrednost se predaje i čuva u proizvodnoj evidenciji."],
        ["Potvrđeno u pisanoj formi", "Parametri, obuhvat i rok izrade dogovaraju se pre proizvodnje."],
      ],
      note: "Usklađenost se postiže u rezoluciji fabričkog mernog instrumenta. Ista prikazana vrednost nije tvrdnja o nultoj fizičkoj varijaciji. Dostupnost i uslovi dogovaraju se pojedinačno za svaku narudžbinu.",
      cta: "Zatražite ZERO",
    },
    cta: "Konfigurišite sa klasom preciznosti",
  },
  grip: {
    title: "Fabrička arhitektura ručke",
    statement: "Osam fabričkih veličina ručke. L0–L7.",
    lead: "Geometrija ručke deo je arhitekture karbonske ručke. Svaka veličina se proizvodi kao geometrija ručke, a ne nadograđuje overgripovima.",
    emph: "Proširene veličine",
    p1: "Fabrički asortiman od osam veličina daje trenerima i igračima širi opseg konfiguracije, u kojem se oprema može specificirati oko igrača, uključujući i veće geometrije L6 i L7.",
    p2: "Nominalna oznaka veličine ručke razlikuje se od sirovih dimenzija strukturne ručke i od konačnog protokola merenja. Veličine se primenjuju na serije visokih performansi i na trenažne linije na ovoj platformi.",
    p3: "Za ovaj asortiman se ne tvrdi svetska ekskluzivnost.",
    columns: { size: "Veličina", nominal: "Nominalno", family: "Primenjuje se na" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurišite sa svojom veličinom ručke",
  },
  custom: {
    title: "Inženjering po meri",
    statement: "Projektovano prema specifikaciji.",
    sub: "Standardni asortiman je polazna tačka.",
    lead: "MAXIMUS prihvata tehničke zahteve izvan objavljenih matrica konfiguracije radi procene, inženjerskog razvoja, validacije i proizvodnje prema dogovorenoj specifikaciji. Izvodljivost se potvrđuje kroz razmatranje — nije svaki zamislivi zahtev fizički ili komercijalno izvodljiv.",
    scopeTitle: "Šta tehnički zahtev može da obuhvati",
    scope: ["Geometrija glave i rama", "Dužina", "Težina", "Balans", "Swingweight", "Krutost", "Twistweight", "Geometrija ručke", "Konstrukcija", "Usklađeni setovi", "Trenažni ramovi", "Estetika i gravura", "Identitet i timski programi", "Razvoj zavisan od alata"],
    processTitle: "Proces",
    process: [
      ["Definisanje", "Željeni ciljevi, obavezna ograničenja, namena i prihvatljivi kompromisi."],
      ["Inženjering", "Inženjerska procena u odnosu na platformu i alate."],
      ["Validacija", "Validacija u odnosu na dogovorenu specifikaciju."],
      ["Specifikacija", "Pisana specifikacija sa osnovom merenja i tolerancijama."],
      ["Proizvodnja", "Proizvodnja prema specifikaciji."],
      ["Merenje / evidentiranje", "Merenje i sačuvani zapisi prema primenjivoj klasi preciznosti."],
    ],
    formTitle: "Pošaljite tehnički zahtev",
    formLead: "Razlikujte željene ciljeve od obaveznih ograničenja. Rezultat je zahtev za tehničko razmatranje, a ne automatski prihvaćena proizvodna narudžbina.",
    protected: "Recepture slaganja karbonskih slojeva, alati, identitet dobavljača, interni obračun troškova i zaštićeno znanje ne otkrivaju se ovim putem.",
    cta: "Pošaljite tehnički zahtev",
  },
  training: {
    title: "Sistemi za trening",
    lead: "Dve trenažne linije sa sopstvenim proizvodnim standardima, povezane jednom metodologijom: trening pod vođstvom trenera, zapisi, ponovna procena i prenos natrag u takmičarsku igru.",
    sst: { h: "Sweet Spot Trainer", p: "Trenažni reket smanjene glave od 50 in² u sistemu od četiri težine, za vežbanje centriranog udara, osećaj za sweet spot, kontrolu reketa i progresivno opterećenje." },
    spot: { h: "Spot Trainer", p: "Trening tačke udara pomoću male okrugle mete za kontakt, na odobrenoj osnovi od četiri težine." },
    method: { h: "Metodologija", p: "Postavite ciljeve, izaberite opremu uz uključenost trenera, koristite odgovarajući sistem, beležite, ponovo procenite, prilagodite i prenesite u igru." },
    experience: "Držite ga. Zamahnite njime. Osetite ga.",
    experienceP: "Zatražite testiranje, prilagođavanje ili demonstraciju uz podršku trenera. Poslat zahtev nije potvrđen termin.",
    cta: "Zatražite prilagođavanje ili demonstraciju",
    distinct: "Sweet Spot Trainer, Spot Trainer i svaki poseban demonstracijski uređaj su različiti proizvodi i nikada se ne spajaju.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Posebna trenažna kategorija sa sopstvenim proizvodnim standardom. Glava od 50 in² usmerava pažnju na mesto udara; četiri težine daju progresiju opterećenja.",
    baseline: "Potvrđena osnova",
    columns: { head: "Glava", length: "Dužina", pattern: "Šema žica", grips: "Fabričke ručke" },
    systemTitle: "Sistem od četiri reketa",
    detailsTitle: "Detalji konstrukcije",
    systemLead: "Težina i balans kako se dostavljaju. Osnova merenja evidentira se posebno i još nije objavljena.",
    purposeTitle: "Namena",
    purpose: ["Vežbanje centriranog udara", "Osećaj za sweet spot", "Kontrola reketa", "Progresivno opterećenje", "Razvoj pod vođstvom trenera", "Prelazak natrag na igračev reket za igru"],
    heavy: "Model od 400 g je kontrolisana trenažna konfiguracija. Ne preporučuje se automatski deci, početnicima ni svakom igraču; trener određuje opterećenje, trajanje i progresiju.",
    precisionNote: "Klase preciznosti P2.5, P1.5 i P0.5 iz serija visokih performansi ne primenjuju se automatski na ovu trenažnu liniju. Tolerancije trenažne proizvodnje prate sopstvenu odobrenu specifikaciju te linije.",
    health: "Ne obećava se sprečavanje ili lečenje teniskog lakta, otklanjanje povreda niti garantovano napredovanje.",
    cta: "Zatražite demonstraciju Sweet Spot Trainer sistema",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Trening tačke udara pomoću male okrugle mete za kontakt. Poseban proizvod sa sopstvenim vizuelnim identitetom, izgrađen na odobrenoj osnovi od četiri težine.",
    purposeTitle: "Potvrđena namena",
    purposeP: "Učenje igrača da nađe i ponovi preciznu tačku udara.",
    weightsTitle: "Progresija težine",
    weightsP: "Progresija težine prati odobrenu osnovu težina sistema Sweet Spot Trainer. Vrednosti balansa i druge specifikacije sistema Sweet Spot Trainer ne prenose se na Spot Trainer.",
    dims: "Tačne dimenzije mete još nisu objavljene.",
    grips: "Fabrička arhitektura ručke L0–L7.",
    notes: ["Klase preciznosti iz serija visokih performansi ne primenjuju se automatski.", "Nije minijaturni konvencionalni reket i nijedna šema žica se ne objavljuje.", "Spot Trainer, Sweet Spot Trainer i svaki poseban demonstracijski uređaj ostaju jasno razdvojeni."],
    cta: "Pitajte o proizvodu Spot Trainer",
  },
  methodology: {
    title: "Metodologija i iskustvo proizvoda",
    lead: "Oprema je samo jedan deo strukturiranog razvojnog puta. Metod počinje od ciljeva igrača, a ne od naziva proizvoda.",
    stepsTitle: "Razvojni put",
    steps: [
      ["Postavite ciljeve", "Ciljevi igrača i polazna tačka."],
      ["Izaberite opremu", "Odgovarajuća oprema izabrana uz uključenost trenera."],
      ["Koristite sistem", "Odgovarajući sistem za trening, pod vođstvom trenera."],
      ["Beležite", "Zapažanja o stvarnom učešću, bez izmišljenih rezultata."],
      ["Ponovo procenite", "Uporedive kontrolne tačke."],
      ["Prilagodite", "Prilagođavanja konfiguracije ili programa."],
      ["Prenesite", "Naučeno se prenosi u takmičarsku igru."],
    ],
    educationTitle: "Putevi edukacije",
    education: { player: "Igrači — razumevanje konfiguracije, opterećenja i progresije.", parent: "Roditelji — kontinuitet razvoja, odgovarajuća oprema, zapisi i prava.", coach: "Treneri — sistemi za trening, prilagođavanje, procena i ovlašćena upotreba programa." },
    evidenceTitle: "Disciplina dokaza",
    evidenceP: "Zapisi o stvarnom učešću i zapažanja čuvaju se sa svojom klasifikacijom — prijavio učesnik, potvrdio staratelj, validirao trener ili izmerio sistem. Napredak, rezultati i validacija se nikada ne izmišljaju.",
    experienceTitle: "Držite ga. Zamahnite njime. Osetite ga.",
    experienceP: "Testiranje, prilagođavanje ili demonstracija uz podršku trenera mogu se zatražiti. Poslat zahtev nije potvrđen termin.",
    cta: "Zatražite prilagođavanje ili demonstraciju",
    cta2: "Upit za partnerstvo sa trenerom",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — vođeni profil opreme",
    title: "MAXIMUS GPS",
    lead: "Vođeni profil opreme. Odgovorite samo na ono što je relevantno; pregledajte i ispravite svoje odgovore; dobijate sažetak, pravce konfiguracije koji se primenjuju i stvarnu sledeću radnju.",
    honesty: "U ovom izdanju nisu odobrena automatska pravila prilagođavanja. GPS zato daje jasan sažetak zahteva i ukazuje na pravce konfiguracije; detalji opreme se upućuju na stručno razmatranje.",
    rulesVersion: "Verzija pravila",
    dataVersion: "Verzija podataka o proizvodima",
    steps: { role: "Uloga", sport: "Sport", experience: "Iskustvo", objectives: "Ciljevi", style: "Stil igre", equipment: "Trenutna oprema", preference: "Preferencije", coach: "Uključenost trenera", ageBand: "Uzrasna grupa", review: "Provera" },
    notStored: "Ne čuva se u ovom pregledaču.",
    ageNote: "Koristi se samo za usmeravanje zahteva. Ime, datum rođenja i medicinski podaci se ne traže.",
    q: {
      role: "Šta vas najbolje opisuje?",
      sport: "Koji sport?",
      experience: "Nivo iskustva",
      objectives: "Šta je najvažnije? (izaberite do tri)",
      style: "Stil igre, ako je poznat",
      equipment: "Trenutna oprema, ako je imate",
      equipmentHint: "Marka i model, težina ili veličina ručke ako ih znate. Opciono.",
      preference: "Željena konfiguracija ili poznata veličina ručke",
      grip: "Poznata veličina ručke",
      coach: "Da li je trener uključen u vaše odluke o opremi?",
      ageBand: "Uzrasna grupa igrača (koristi se samo za pravilno usmeravanje zahteva)",
    },
    roles: { player: "Igrač", parent: "Roditelj ili staratelj", coach: "Trener", club: "Klub ili akademija", other: "Drugo" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Skvoš", badminton: "Badminton", other: "Drugi reketski sport" },
    sportNote: "Proizvodi postoje za tenis. Drugi sportovi su pravci razvoja; vaše interesovanje se evidentira za odgovarajući program.",
    experience: { beginner: "Početnik", developing: "U razvoju", intermediate: "Srednji nivo", advanced: "Napredni nivo", competitive: "Takmičarski nivo", professional: "Profesionalni nivo" },
    objectives: { control: "Kontrola", power: "Snaga", spin: "Rotacija", comfort: "Komfor", manoeuvrability: "Upravljivost", development: "Dugoročni razvoj", competition: "Takmičenje", training: "Sistem za trening", team: "Tim ili usklađeni set", personal: "Personalizacija" },
    styles: { baseline: "Igra sa osnovne linije", allcourt: "Univerzalna igra", attacking: "Napadački", defensive: "Odbrambeni", coach: "Trener odlučuje", unknown: "Nisam siguran" },
    ageBands: { u10: "Do 10 godina", u14: "10–13", u18: "14–17", adult: "18 i više" },
    output: {
      title: "Vaš profil opreme",
      status: "Potrebno je stručno razmatranje",
      statusP: "U ovom izdanju se ne pravi automatsko uparivanje. Vaš profil je sažet za stručno razmatranje.",
      directionsTitle: "Pravci konfiguracije koji se primenjuju",
      directionsP: "Na osnovu ciljeva koje ste naveli i deklarisanog pravca igre svake serije. Ovo je pravac, a ne preporuka prilagođavanja.",
      trainingHint: "Vaši ciljevi uključuju sistem za trening: pogledajte Sweet Spot Trainer i Spot Trainer.",
      teamHint: "Usklađeni setovi zahtevaju se preko konfiguratora i potvrđuju u pisanoj formi.",
      next1: "Pošaljite profil na stručno razmatranje",
      show: "Prikažite moj profil",
      configure: "Konfigurišite",
      sendP: "Pošaljite svoj profil MAXIMUS-u na stručno razmatranje. ID zahteva se prikazuje odmah; odgovor dolazi u pisanoj formi.",
      otherSport: "MAXIMUS reketi postoje za tenis. Za druge reketske sportove ne predlaže se nijedna teniska serija; vaše interesovanje se evidentira kao pravac razvoja.",
      noDirection: "Vaši ciljevi ne ukazuju na jedan pravac igre. Stručno razmatranje predlaže konfiguraciju.",
      incomplete: "Neki obavezni odgovori nedostaju — upotrebite „Uredite odgovore“ da ih dopunite.",
    },
    privacy: "GPS ne traži medicinske podatke ni identifikatore dece. U ovoj sesiji pregledača čuvaju se samo odgovori sa višestrukim izborom; slobodan tekst se ne čuva.",
  },
  build: {
    title: "Konfigurišite svoj reket",
    lead: "Konfigurišite zahtev: serija, klasa preciznosti, navedena težina ili cilj po meri, veličina ručke, zahtevani ciljevi, personalizacija, usklađeni setovi i količina. Rezultat je zahtev za konfiguraciju sa ID-om zahteva — a ne šifra artikla, cena, datum isporuke ili sertifikat.",
    steps: { series: "Serija", cls: "Klasa preciznosti", weight: "Težina", grip: "Ručka", targets: "Ciljevi", personal: "Personalizacija", set: "Set i količina", use: "Namena", review: "Provera" },
    q: {
      series: "Izaberite seriju",
      cls: "Izaberite klasu preciznosti",
      weightMode: "Težina",
      listed: "Navedena težina",
      customWeight: "Zahtevana težina (g)",
      balanceShown: "Izračunati balans za ovu težinu",
      balanceRequest: "Zahtevani balans (mm)",
      grip: "Fabrička veličina ručke",
      targetsTitle: "Zahtevani ciljevi",
      swingweight: "Zahtevani swingweight (kg·cm²)",
      stiffness: "Zahtevana krutost (RA)",
      basis: "Osnova merenja za zahtevane vrednosti",
      engraving: "Tekst gravure",
      engravingHint: "Ime, inicijali ili broj. Latinična slova, cifre, razmak, crtica, apostrof i tačka; do 24 znaka. Druga pisma se prihvataju uz potvrdu grafičkog rešenja.",
      engravingType: "Personalizacija",
      types: { none: "Bez personalizacije", name: "Ime igrača", initials: "Inicijali", number: "Broj seta", academy: "Identifikacija trenera ili akademije", team: "Timski program" },
      set: "Pojedinačni reket ili usklađeni set",
      use: "Namena",
      uses: { play: "Lična igra", competition: "Takmičenje", coaching: "Trenerski rad", team: "Tim ili akademija", retail: "Procena za maloprodaju ili distribuciju", other: "Drugo" },
      notes: "Dodatni tehnički zahtevi",
    },
    classes: { "P2.5": "P2.5 — skalabilna osnova performansi", "P1.5": "P1.5 — napredna preciznost", "P0.5": "P0.5 — profesionalno, pojedinačno kontrolisano" },
    stiffExactShort: "krutost odgovara deklarisanoj ciljnoj RA vrednosti po utvrđenom fabričkom protokolu",
    clsNote: "Svaka klasa kontroliše četiri parametra. P0.5 je uska tolerancija pod definisanim protokolom merenja — a ne nulta greška. Serijski identitet, sertifikati i dokumentacija o usklađenim setovima primenjuju se samo tamo gde ih program za vašu narudžbinu sprovodi.",
    listedNote: "Iz potvrđene matrice serije.",
    customNote: "Težina izvan matrice, uz tehničko razmatranje.",
    balanceCaption: "Za svaku navedenu težinu prikazan je izračunati balans u mm od kraja ručke. Izračunate vrednosti nisu pojedinačna merenja.",
    spinNote: "Težine serije SPIN čine zahtevanu arhitekturu težina. Balans, swingweight i krutost za SPIN nisu dostavljeni; definišu se u tehničkom razmatranju.",
    customHint: "Celi grami, samo cifre. Težina po meri je zahtev za tehničko razmatranje; izvodljivost se potvrđuje u pisanoj formi i nijedna vrednost se ne zaokružuje.",
    gripNote: "fabrička geometrija karbonske ručke, a ne nadogradnja overgripom",
    targetsLead: "Opciono. Unesite samo vrednosti koje su vam potrebne. Svaka se evidentira kao zahtevani cilj za tehničko razmatranje, a ne kao objavljena specifikacija.",
    basisHint: "Obavezno kada zahtevate težinu po meri ili bilo koji cilj: da li se vrednosti odnose na reket bez žica ili sa žicama?",
    inputRange: "Prihvaćen unos: {min}–{max}.",
    inputRangeNote: "Opsezi unosa samo isključuju nemoguće vrednosti. Ne opisuju proizvodnu sposobnost.",
    listedBasis: "navedene vrednosti — osnova merenja potvrđuje se u pisanoj specifikaciji",
    notStored: "Ne čuva se u ovom pregledaču; unesite ponovo ako osvežite stranicu.",
    artworkReview: "potrebna je potvrda grafičkog rešenja",
    previewNote: "Vizuelni pregled se ne prikazuje: odobreni šablon gravure za ovaj model još nije objavljen. Vaš tekst se prikuplja radi potvrde grafičkog rešenja.",
    teamSub: "4–99 reketa po setu",
    setsLabel: { individual: "Broj reketa", pair: "Broj usklađenih parova", triple: "Broj usklađenih trojki", team: "Broj timskih setova" },
    teamSizeLabel: "Reketa po timskom setu",
    totalLabel: "Ukupno reketa",
    racquetsUnit: "reketa",
    setRule: "Količina se računa po setovima: usklađeni par ima 2 reketa po setu, usklađena trojka 3.",
    restart: "Započnite novu konfiguraciju",
    notices: { weightCleared: "{w} g nije u matrici serije {series}, pa je težina obrisana. Izaberite navedenu težinu ili zahtevajte cilj po meri." },
    reviewTitle: "Zahtev za konfiguraciju",
    reviewP: "Proverite konfiguraciju, a zatim dodajte svoje kontakt podatke. Zahtev se čuva sa ID-om zahteva i na njega se odgovara u pisanoj formi; dostupnost i komercijalni uslovi potvrđuju se u pisanoj formi.",
    reviewErrors: "Neki odgovori u konfiguraciji zahtevaju pažnju:",
    edit: "Uredite",
    fieldNames: { series: "Serija", cls: "Klasa preciznosti", mode: "Izbor težine", weight: "Navedena težina", customWeight: "Zahtevana težina", basis: "Osnova merenja", balanceReq: "Zahtevani balans", sw: "Zahtevani swingweight", ra: "Zahtevana krutost", grip: "Veličina ručke", ptype: "Personalizacija", engraving: "Tekst gravure", setType: "Vrsta seta", sets: "Količina", teamSize: "Reketa po timskom setu", use: "Namena", notes: "Dodatni zahtevi" },
    status: { listed: "navedena težina", requestedArchitecture: "zahtevana arhitektura težina", technicalReview: "zahtev za tehničko razmatranje", notPublished: "nije dostavljeno", requestedCondition: "zahtevano stanje" },
    chooseLink: "Niste sigurni koja serija vam odgovara? Potražite pomoć pri izboru",
    cta: "Pošaljite zahtev za konfiguraciju",
  },
  experience: {
    title: "Testiranje i prilagođavanje",
    statement: "Držite ga. Zamahnite njime. Osetite ga.",
    lead: "Zatražite testiranje, prilagođavanje ili demonstraciju uz podršku trenera. Zahtevi se razmatraju i na njih se odgovara u pisanoj formi; poslat zahtev nije potvrđen termin.",
    optionsTitle: "Šta se može zatražiti",
    options: ["Testiranje reketa", "Sesija prilagođavanja", "Demonstracija uz podršku trenera", "Demonstracija Sweet Spot Trainer ili Spot Trainer sistema", "Demo dan za tim ili akademiju"],
    formTitle: "Zahtev za prilagođavanje ili demonstraciju",
  },
  engineering: {
    title: "Inženjering i proizvodnja",
    statement: "Avioni. Jahte. Reketi.",
    lead: "Jedna inženjerska filozofija u tri okruženja: principi koji oblikuju avion, preciznost koja vodi jahtu kroz otvoreno more i performanse koje definišu svaki MAXIMUS reket. Inženjerska priča — a ne tvrdnja o vazduhoplovnoj sertifikaciji, vlasništvu nad jahtama, vlasništvu nad fabrikom ili direktnom prenosu materijala.",
    manifesto: ["Verujemo da veliki inženjering nema granica.", "Jedna filozofija. Projektovano bez kompromisa."],
    capabilityTitle: "Proizvodna sposobnost",
    capabilityLead: "Sposobnost se prikazuje kao niz koraka, a ne kao slogan.",
    sequence: [
      ["Specifikacija", "Serija, klasa preciznosti, težina, balans, swingweight, ciljna krutost, geometrija ručke, personalizacija."],
      ["Proizvodnja", "Konstrukcija u celosti od karbona, od rama do ručke, izrađena prema specifikaciji."],
      ["Kontrola kvaliteta", "Merenje i zapisi po klasi preciznosti: proizvodna evidencija, pojedinačni zapisi i sledivost, pojedinačna sertifikacija."],
      ["Ponovljena proizvodnja", "Ponovljiv odziv prema deklarisanoj specifikaciji kroz različite proizvodne serije."],
      ["Sledivost", "Serijski identitet, sledivost proizvodne serije i Sertifikat preciznosti tamo gde ih klasa predviđa."],
    ],
    capacityNote: "Proizvodni kapacitet, rokovi izrade, minimalne količine i planovi isporuke potvrđuju se za svaki program u pisanoj formi, na osnovu potvrđenih narudžbina i dogovorenog plana otpreme.",
    truth: "Kapacitet nije proizvedena količina, zaliha, garantovan datum isporuke niti vlasništvo nad proizvodnim objektom.",
    cta: "Distribucija i razvoj tržišta",
    cta2: "Pošaljite tehnički zahtev",
  },
  ecosystem: {
    title: "MAXIMUS ekosistem",
    lead: "Jedan ključ. Ovo je ono što otvara. Svaki čvor ima objašnjenje, tačan status i relevantnu sledeću radnju.",
    words: ["Inženjering", "Performanse", "Inovacija", "Zajednica", "Mogućnost", "Svrha"],
    nodes: {
      engineering: { h: "Inženjering i proizvodnja reketa", p: "Reketi u celosti od karbona, projektovani prema specifikaciji, proizvedeni sa zapisima kvaliteta i sledivošću.", a: "Inženjering i proizvodnja" },
      precision: { h: "Preciznost i pojedinačna konfiguracija", p: "Četiri parametra, tri klase preciznosti, osam veličina ručke i inženjering po meri.", a: "Preciznost i krutost" },
      training: { h: "Trening i metodologija", p: "Sweet Spot Trainer, Spot Trainer i strukturiran razvojni put.", a: "Sistemi za trening" },
      development: { h: "Razvoj igrača i trenera", p: "Izbor opreme uz trenera, zapisi, ponovna procena i putevi edukacije.", a: "Metodologija" },
      identity: { h: "Lični identitet i lični brendovi", p: "Od gravure do ličnog ili profesionalnog brenda uređenog pravima.", a: "Lični brendovi" },
      owners: { h: "Zapisi vlasnika, znanje i prava", p: "Predloženi trezor vlasnika sa kontrolisanim pristupom, za zapise o opremi, razvoju i pravima.", a: "Vlasnici i trezor" },
      mipa: { h: "MIPA poreklo i interna kontrola", p: "Interni sloj kontrole intelektualne svojine, porekla i dokumentacije.", a: "Pravni identitet i kontrola" },
      digital: { h: "Digitalna infrastruktura i pravac Blockchain 5.0", p: "Poreklo, sledivi zapisi, dokazi sa kontrolisanim pristupom i identitet proizvoda kao navedeni tehnološki pravac.", a: "Tehnološki pravac" },
      licensing: { h: "Ugovorno licenciranje i programi tantijema", p: "Licencirani brendovi, proizvodi i paketi prava, sa uslovima definisanim po ugovoru.", a: "Putevi licenciranja" },
      families: { h: "Učešće porodice i pogodnosti programa", p: "Informisane odluke, kontinuitet, sačuvani zapisi i pogodnosti definisane programom.", a: "Porodice i roditelji" },
      network: { h: "MAXIMUS Sports Network", p: "Igrači, treneri, klubovi, akademije, pružaoci usluga, operatori i regionalni partneri.", a: "Sports Network" },
      market: { h: "Klubovi, akademije, distribucija i razvoj tržišta", p: "Timski programi, maloprodaja, distribucija i razvoj teritorije uz pisanu kvalifikaciju.", a: "Putevi partnerstva" },
      institutional: { h: "Institucionalni programi, edukacija, inovacija i društveni uticaj", p: "Institucionalni sloj koji obezbeđuje MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tamo gde program utvrđuje tu ulogu.", a: "Institucionalni programi" },
      extensions: { h: "Buduća proširenja na reketske sportove i MAXIMUS odeću", p: "Padel, pickleball, skvoš, badminton, reketbol, beach tenis i odeća kao pravci razvoja.", a: "Reketski sportovi" },
    },
    boundaryTitle: "Granice",
    boundary: [
      "Kupovina reketa ne stvara institucionalno članstvo, upravljačka prava, tantijeme ni investicijska prava.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) je institucionalni operator samo tamo gde program utvrđuje tu ulogu; prodaja opreme navodi svoj stvarni ugovorni subjekt.",
      "Grantovi, status neprofitne organizacije, poreski tretman i regulatorne dozvole ne primenjuju se automatski u svim zemljama.",
    ],
    techTitle: "Tehnološki pravac",
    techP: "Blockchain 5.0 je navedeni tehnološki pravac MAXIMUS-a. Njegove funkcionalne namene su poreklo, sledivi zapisi, dokazi sa kontrolisanim pristupom, identitet proizvoda i usklađivanje kvalifikovanih komercijalnih događaja. Ne prikazuje se nikakav mehanizam konsenzusa, transakcijski kapacitet, mreža nodova, adresa pametnog ugovora, token ni nezavisna sertifikacija, i ne tvrdi se da je implementacija postavljena. Lični podaci, zapisi o deci i poverljivi ugovori nikada se po pravilu ne unose u javni nepromenljivi sistem.",
  },
  brands: {
    title: "Lični brendovi i ambasadori",
    statement: "Od igrača do brenda. Od trenera do brenda.",
    lead: "Poseban put za lični brend. Uključenost MAXIMUS-a obuhvata razvoj brenda i dogovorenu promociju — a ne samo ime na reketu.",
    progressionTitle: "Predviđeni razvoj",
    progression: [
      ["Verifikovan identitet", "Verifikovan identitet i istorija razvoja."],
      ["Prepoznatljiv brend", "Prepoznatljiv lični ili profesionalni brend."],
      ["Sadržaj sa rešenim pravima", "Sadržaj sa rešenim pravima i odobren identitet proizvoda."],
      ["Inženjering i kolekcije", "Inženjering i razvoj kolekcije tamo gde je dogovoreno."],
      ["Promocija", "Promocija kroz dogovorene MAXIMUS kanale i partnerstva."],
      ["Učešće", "Ugovorno učešće u kvalifikovanoj prodaji ili licenciranju."],
      ["Izveštavanje", "Transparentno izveštavanje po ugovoru."],
    ],
    royaltiesTitle: "Tantijeme i licenciranje",
    royalties: [
      "Tantijeme se vezuju za definisani licencirani brend, proizvod, transakciju ili paket prava.",
      "„Prodaja na svetskom nivou“ znači kvalifikovanu prodaju u okviru obuhvata ugovora — nikada svaki nepovezani MAXIMUS reket.",
      "Stope, osnovica obračuna, teritorije, trajanje, povraćaji, odbici, izveštavanje, obračun i verifikacija definišu se odgovarajućim ugovorom. Nijedan podrazumevani procenat tantijema se ne objavljuje.",
      "Nijedna globalna kampanja, medijski budžet, rezultat sponzorstva ni komercijalni uspeh se ne obećavaju bez dogovorenog obuhvata.",
    ],
    cta: "Pošaljite upit za saradnju na brendu",
    cta2: "Upit za partnerstvo sa trenerom",
  },
  families: {
    title: "Porodice i roditelji",
    lead: "Informisane odluke o opremi, kontinuitet razvoja, sačuvano znanje i prava, vidljivost učešća i pogodnosti definisane programom koje mogu podržati buduće aktivnosti.",
    nowTitle: "Dostupno sada",
    now: ["Upiti o porodici i razvoju u pisanoj formi.", "Izbor opreme uz uključenost trenera, zahtevi za prilagođavanje i demonstraciju.", "Privatni zapisi: profili dece se nikada ne objavljuju i po pravilu se ne komercijalizuju.", "Put edukacije za roditelje: konfiguracija, opterećenje, progresija, zapisi i prava."],
    plannedTitle: "Planirano",
    planned: ["Pogodnosti učešća definisane programom, upotrebljive za robu i usluge unutar ekosistema, a ne kao kamata u novcu.", "Zapisi vlasnika i porodice u predloženom trezoru vlasnika, sa dozvolama staratelja i prenosom kontrole sa 18 godina."],
    categoriesTitle: "Strogo odvojeno",
    categories: ["Ugovorne tantijeme iz licenciranih prava ili kvalifikovane prodaje", "Pogodnosti učešća definisane programom", "Krediti za kupovinu ili usluge", "Avansne uplate", "Institucionalno članstvo"],
    categoriesP: "Ove kategorije se nikada ne tretiraju kao zamenljive.",
    statusTitle: "Stvarni status porodičnog programa",
    journeyTitle: "Put za porodice",
    journey: [
      ["Cilj", "Šta igrač želi da postigne u sledećem koraku."],
      ["Trenutni nivo", "Gde je igrač danas."],
      ["Trener", "Da li trener učestvuje u odlukama o opremi."],
      ["Oprema", "Oprema odgovarajuća za tu fazu, uključujući sisteme za trening kada je to relevantno."],
      ["Dogovoren trening", "Upotreba pod vođstvom trenera, dogovorena unapred."],
      ["Provera", "Ponovna procena u uporedivim kontrolnim tačkama."],
    ],
    brief: {
      who: "Roditelji i staratelji igrača u svakoj fazi.",
      value: "Pisani odgovor o odgovarajućoj opremi, uključenosti trenera i sledećem razvojnom koraku.",
      now: "Porodični upiti u pisanoj formi; izbor uz uključenost trenera; privatni zapisi — profili dece se nikada ne objavljuju.",
      next: "Pošaljite porodični upit ispod. ID zahteva dobijate odmah.",
    },
    formTitle: "Porodični upit",
    formNote: "Obrazac popunjava roditelj ili staratelj. Ne navodite ime deteta, datum rođenja, školu ni medicinske podatke.",
    noPromise: "Kupovina ne obećava tantijeme, investicijske prinose, sponzorstvo niti finansiranje razvoja deteta.",
    statusP: "Ovo izdanje objašnjava model i prihvata upite o programu. Obračun, isplate i korišćenje nisu dostupni dok se kvalifikovani događaji, korisnici, izvor sredstava, osnovica obračuna, dozvoljene namene, računovodstveni tretman, povraćaji, storniranja, rokovi važenja, prenosivost, zatvaranje programa i rešavanje sporova ne definišu u pisanoj formi. Ne obećava se da nijedno stanje nikada neće opasti, nijedno učešće ne pokriva ceo trening i ne podrazumeva se zaštita kapitala.",
    cta: "Pošaljite porodični ili razvojni upit",
  },
  owners: {
    title: "Vlasnici i trezor vlasnika",
    lead: "Trezor vlasnika je predložena evidencija sa kontrolisanim pristupom, o opremi, razvoju, znanju, sadržaju i dokumentovanim pravima. Predstavljen je kao deo planirane arhitekture za vlasnike: ne prikazuju se aktivni računi, stanja, sertifikati ni postignuća.",
    nowTitle: "Za sadašnje vlasnike sada",
    now: ["Upiti vlasnika: referenca proizvoda ili serijski broj, postavka, servis i zahtevi za zapise u pisanoj formi.", "Sertifikat preciznosti i dokumentacija o usklađenom setu tamo gde ih klasa preciznosti predviđa, dostavljeni sa proizvodom."],
    archTitle: "Planirana arhitektura trezora",
    arch: ["Identitet proizvoda i serijske reference", "Konfiguracija i primenjivi sertifikati kontrole kvaliteta", "Istorija servisa i postavke", "Zapisi o razvoju igrača ili trenera", "Kvalifikacije i verifikovana postignuća", "Mediji sa rešenim pravima i autorski materijali", "Licence, dozvole i reference ugovora", "Zapisi o programu ličnog brenda", "Primenjivi obračuni tantijema ili pogodnosti učešća"],
    separationTitle: "Šta znači vlasništvo",
    separation: [
      "Vlasništvo nad fizičkim reketom odvojeno je od vlasništva nad autorskim pravom, licencom, ugovornim pravom ili zapisom koji te stvari opisuje.",
      "Sačuvan dokument ili unos u blokčejnu nije automatski dokaz da pravo postoji ili da je preneto.",
      "Dokaz zadržava svoju klasifikaciju: prijavio učesnik, potvrdio staratelj, validirao trener, izmerio sistem.",
      "Za maloletnike: privatni zapisi, dozvole staratelja, bez objavljenih profila dece i bez komercijalizacije identiteta po pravilu.",
      "Izvoz, ispravka, kontrola pristupa i odgovarajući prenos kontrole deo su projektovanog rešenja.",
    ],
    techTitle: "Blockchain 5.0 i MxSN",
    techP: "Blockchain 5.0 je navedeni tehnološki pravac; MxSN definiše koncepte mreže sa kontrolisanim pristupom za saglasnost, dostavu, dokaze, prava i izveštavanje. Operativna implementacija se ne prikazuje. Model podataka aplikacije izgrađen je tako da se kasnije integriše preko dokumentovanog interfejsa, bez pretvaranja da veza danas postoji.",
    cta: "Upit vlasnika",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Veza između igrača, trenera, klubova, akademija, pružalaca usluga, operatora programa i regionalnih partnera.",
    functionsTitle: "Moguće funkcije",
    functions: ["Pronalaženje", "Upoznavanje", "Razvojni programi", "Podrška u opremi", "Događaji", "Pristup uslugama", "Partnerske prilike"],
    statusTitle: "Stvarni status",
    statusP: "Javni direktorijum još nije objavljen: biće navedeni samo učesnici čiji su identitet, odnos i dozvola za prikazivanje utvrđeni. Predlog poslat klubu nije partnerstvo, a potencijalni distributer nije imenovani distributer. Objavljivanje direktorijuma, rezervacije, razmena poruka i komercijalne transakcije kontrolišu se odvojeno i nisu aktivni.",
    cta: "Prijavite se u mrežu",
  },
  partnerships: {
    title: "Putevi partnerstva",
    lead: "Prvo pisana kvalifikacija. Svaki put vodi do upita specifičnog za ulogu; komercijalni uslovi slede u pisanoj formi.",
    commercialTitle: "Moguće komercijalne aktivnosti platforme",
    commercial: ["Oprema", "Inženjering po meri", "Personalizacija", "Programi za timove i akademije", "Sistemi za trening", "Ugovorno licenciranje", "Distribucija", "Odobrene usluge", "Buduće kategorije proizvoda"],
    boundary: "Prava za zemlju, ekskluzivnost, naknade za teritoriju i marže distributera su predmet pregovora. Ne objavljuju se prihodi, projekcije, procene vrednosti, tržišni udeli, prinosi, obaveze finansiranja niti neimenovana partnerstva.",
    routes: {
      coaches: {
        title: "Treneri",
        lead: "Sistemi za trening, prilagođavanje, profesionalni identitet, ovlašćeni programi, prilike za lični brend i snabdevanje opremom.",
        points: ["Sweet Spot Trainer i Spot Trainer u treningu pod vođstvom trenera.", "Prilagođavanje pomoću matrica konfiguracije i osam fabričkih veličina ručke.", "Coach-to-Brand: verifikovan profesionalni profil i pod-brend uređen pravima.", "Ovlašćena upotreba programa sledi iz pisanog ugovora."],
        cta: "Pošaljite upit za partnerstvo sa trenerom",
        brief: {
          who: "Samostalni treneri i trenerski timovi.",
          value: "Sistemi za trening pod vođstvom trenera, prilagođavanje pomoću matrica serija i osam fabričkih veličina ručke, i put do profesionalnog identiteta.",
          now: "Upiti trenera u pisanoj formi. Nijedna provizija, zarada ni stopa za preporuku se ne objavljuje niti podrazumeva.",
          next: "Pošaljite upit za trenere ispod. Uslovi slede u pisanoj formi.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubovi i akademije",
        lead: "Timska oprema, sistemi za trening, personalizacija, razvojni programi, servis i učešće u mreži.",
        points: ["Timski i usklađeni setovi zahtevaju se preko konfiguratora.", "Sistemi za trening i metodologija za strukturiran razvoj.", "Personalizacija za timske programe na odobrenim zonama.", "Demo dani, sesije prilagođavanja i učešće u mreži."],
        cta: "Pošaljite zahtev kluba ili akademije",
        brief: {
          who: "Klubovi, akademije i timski programi.",
          value: "Timski i usklađeni setovi, sistemi za trening, personalizacija za timske programe i demonstracijski dani.",
          now: "Zahtevi klubova i akademija u pisanoj formi; timski setovi se zahtevaju preko konfiguratora.",
          next: "Pošaljite zahtev kluba ili akademije ispod.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribucija i razvoj tržišta",
        lead: "Asortiman, koordinacija proizvodnje, tehnička sposobnost, razvoj teritorije i poverljiva komercijalna kvalifikacija.",
        points: ["Pisana kvalifikacija partnera, teritorije i kanala.", "Asortiman definisan iz matrica konfiguracije i klasa preciznosti.", "Teritorija, ekskluzivnost, količine, cene i komercijalna zaštita su predmet pregovora i dogovaraju se u pisanoj formi.", "Ugovorni subjekt, uslovi plaćanja i osnova isporuke određuju se za svaku transakciju."],
        cta: "Pošaljite upit za distribuciju ili razvoj tržišta",
        brief: {
          who: "Trgovci, distributeri i partneri po zemljama.",
          value: "Asortiman definisan iz potvrđenih matrica, klasa preciznosti i opsega veličina ručke, uz pisanu kvalifikaciju teritorije i kanala.",
          now: "Upiti za distribuciju u pisanoj formi. Teritorija, ekskluzivnost, količine i cene su predmet pregovora — nijedno se ne dodeljuje putem obrasca.",
          next: "Pošaljite upit za distribuciju ispod.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategija i investicije",
        lead: "Inženjerska sposobnost, dubina konfiguracije, model proizvodnje, putevi na tržište, intelektualna svojina, usluge i prilike za širenje.",
        points: ["Kvalifikovan strateški razgovor ili kontrolisan pristup informacijama sledi posle pisane kvalifikacije.", "Javne informacije ograničene su na odobrene specifikacije proizvoda, arhitekturu konfiguracije, verifikovane sposobnosti i objašnjenja programa.", "Ekonomika specifična za kupca, obračun troškova, zaštićena metodologija i neobjavljeni ugovori otkrivaju se samo pod NDA ili ugovorom."],
        cta: "Zatražite kvalifikovan strateški razgovor",
        brief: {
          who: "Investitori i strateški partneri.",
          value: "Kvalifikovan razgovor o inženjerskoj sposobnosti, dubini konfiguracije, modelu proizvodnje, putevima na tržište i intelektualnoj svojini.",
          now: "Ne objavljuju se finansijski podaci, projekcije, procene vrednosti ni prinosi. Kontrolisane informacije slede posle pisane kvalifikacije i NDA.",
          next: "Zatražite kvalifikovan strateški razgovor ispod.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institucionalni programi",
        lead: "Edukacija, pristup, inovacija, dokazi o razvoju, društveni uticaj i programi odgovarajuće strukture.",
        points: ["Institucionalni programi se strukturiraju preko MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tamo gde program utvrđuje tu ulogu.", "Namenska sredstva programa i komercijalne transakcije ostaju odvojeni.", "Upit nije prihvaćena prijava za članstvo, a kupac opreme nije institucionalni član.", "Grantovi, status neprofitne organizacije, poreski tretman i regulatorne dozvole zavise od zemlje i nikada se ne podrazumevaju."],
        cta: "Pošaljite upit za institucionalni program",
        brief: {
          who: "Institucije, obrazovni i razvojni programi.",
          value: "Programi za edukaciju, pristup, inovaciju i dokaze o razvoju, strukturirani sa odgovarajućim operatorom.",
          now: "Institucionalni upiti u pisanoj formi. Upit nije prijava za članstvo; kupovina opreme nije institucionalno članstvo.",
          next: "Pošaljite institucionalni upit ispod.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Javno i kontrolisano otkrivanje",
    disclosure: {
      public: { h: "Javno", p: "Odobrene specifikacije proizvoda, konstrukcija, arhitektura konfiguracije, namene treninga, verifikovane sposobnosti, objašnjenja programa i putevi partnerstva." },
      qualified: { h: "Kvalifikovan upit", p: "Tehnički zahtevi, količine, interes za teritoriju, obuhvat razvoja i relevantni komercijalni razgovori." },
      controlled: { h: "Kontrolisano NDA ili ugovorom", p: "Interne formule, detaljni protokoli kontrole kvaliteta, slojevi karbona, alati, metode proizvodnje, identitet dobavljača, obračun troškova, ekonomika specifična za kupca, zaštićena metodologija, neobjavljeni ugovori i osetljivi zapisi o pravima." },
    },
  },
  contact: {
    title: "Kontakt i zahtevi",
    lead: "Izaberite svrhu svog zahteva. Svaki obrazac prikuplja samo ono što je potrebno za usmeravanje i procenu. Na zahteve se odgovara u pisanoj formi.",
    email: "E-pošta",
    instagram: "Instagram",
    legalLink: "Pravni identitet",
  },
  form: {
    purposeLabel: "Svrha zahteva",
    purposes: {
      selection: "Pomoć pri izboru reketa",
      product: "Upit o proizvodu",
      fitting: "Prilagođavanje ili demonstracija",
      technical: "Tehnički zahtev",
      config: "Zahtev za konfiguraciju",
      gps: "GPS profil opreme",
      coach: "Partnerstvo sa trenerom",
      club: "Zahtev kluba ili akademije",
      distribution: "Distribucija ili razvoj tržišta",
      brand: "Saradnja na brendu ili ambasador",
      family: "Porodični ili razvojni upit",
      institutional: "Institucionalni program",
      strategic: "Strateški ili investicijski razgovor",
      owner: "Upit vlasnika",
      network: "Prijava za Sports Network",
      general: "Opšti upit",
    },
    fields: {
      name: "Ime",
      email: "E-pošta",
      role: "Vaša uloga",
      country: "Zemlja ili region",
      organisation: "Organizacija",
      message: "Vaša poruka",
      level: "Trenutni nivo",
      objectives: "Šta je najvažnije (do tri)",
      currentRacquet: "Trenutni reket",
      grip: "Veličina ručke, ako je poznata",
      seriesInterest: "Serija koja vas zanima",
      quantity: "Količina",
      city: "Grad ili mesto za sesiju",
      coachInvolved: "Da li je trener uključen?",
      timing: "Željeni termin",
      targets: "Željeni ciljevi",
      limits: "Obavezna ograničenja",
      use: "Namena",
      tradeoffs: "Prihvatljivi kompromisi",
      basis: "Osnova merenja",
      players: "Broj igrača",
      interests: "Oblasti interesovanja",
      territory: "Teritorija interesovanja",
      channels: "Postojeći kanali i iskustvo",
      audience: "Publika ili disciplina",
      proposal: "Predložena saradnja",
      goal: "Razvojni cilj",
      ageBand: "Uzrasna grupa igrača",
      scope: "Obuhvat programa",
      interestArea: "Oblast interesovanja",
      productRef: "Referenca proizvoda ili serijski broj",
      requestType: "Vrsta zahteva",
      seeking: "Šta tražite",
      consent: "Prihvatam da MAXIMUS može da čuva i koristi ove podatke radi odgovora na ovaj zahtev. Ovo nije prijava na marketinške poruke.",
    },
    roles: { player: "Igrač", parent: "Roditelj ili staratelj", coach: "Trener", club: "Klub ili akademija", retailer: "Trgovac", distributor: "Distributer", brand: "Brend ili ambasador", investor: "Investitor ili strateški partner", institution: "Institucija", other: "Drugo" },
    interestOptions: { training: "Sistemi za trening", fitting: "Prilagođavanje", identity: "Profesionalni identitet", programmes: "Ovlašćeni programi", brand: "Lični brend", supply: "Snabdevanje opremom", team: "Timska oprema", personalisation: "Personalizacija", development: "Razvojni programi", service: "Servis", network: "Učešće u mreži" },
    ownerTypes: { setup: "Postavka i konfiguracija", service: "Servis", records: "Zapisi i sertifikati", other: "Drugo" },
    strategicAreas: { engineering: "Inženjerska sposobnost", configuration: "Dubina konfiguracije", manufacturing: "Model proizvodnje", routes: "Putevi na tržište", ip: "Intelektualna svojina i usluge", expansion: "Prilike za širenje" },
    errors: {
      required: "Ovo polje je obavezno.",
      too_long: "Ovaj unos je predugačak.",
      too_short: "Ovaj unos je prekratak.",
      invalid_email: "Unesite ispravnu adresu e-pošte, na primer name@example.com.",
      invalid_choice: "Izaberite jednu od opcija.",
      not_number: "Unesite ceo broj, samo cifre.",
      out_of_range: "Ova vrednost je izvan prihvaćenog opsega.",
      not_in_matrix: "Ova težina nije u navedenoj matrici izabrane serije.",
      decimal_not_supported: "Unesite ceo broj, bez decimala.",
      too_many: "Izaberite najviše tri opcije.",
      consent_required: "Saglasnost je obavezna da bi MAXIMUS mogao da odgovori na ovaj zahtev.",
      invalid: "Ovaj unos nije ispravan.",
    },
  },
  legal: {
    title: "Pravni identitet i kontrola",
    lead: "Javni brend je MAXIMUS / MAXIMUS GPS. Pravni operativni subjekti se razlikuju i navedeni su ovde.",
    entities: {
      institutional: { role: "Institucionalni programski sloj", p: "Obezbeđuje institucionalni programski sloj tamo gde program utvrđuje tu ulogu. Nije komercijalni prodavac reketa. Neprofitna inkorporirana organizacija u Dubai International Financial Centre." },
      equipment: { role: "Komercijalni subjekt za opremu", p: "Komercijalni subjekt za opremu, za snabdevanje, distribuciju i ugovorenu komercijalnu isporuku tamo gde aktuelni operativni dokumenti utvrđuju tu ulogu. Ugovorna strana za svaku transakciju navedena je u dokumentima te transakcije." },
      ip: { role: "Intelektualna svojina, brend i komercijalna koordinacija", p: "Pojavljuje se za utvrđenu ulogu u oblasti intelektualne svojine, brenda ili komercijalne koordinacije. Ne dodeljuje se nijedna nepotvrđena ugovorna odgovornost." },
      stewardship: { role: "Referenca upravljanja", p: "House of Maximus je referenca upravljanja za ekosistem tamo gde je to podržano odgovarajućim izvorom." },
      control: { role: "Interna kontrola intelektualne svojine, porekla i dokumentacije", p: "MIPA je interni sloj kontrole intelektualne svojine, porekla i dokumentacije. Interni MIPA unos razlikuje se od eksterne registracije robne marke, patenta ili autorskog prava i od sudskog priznanja, i ne predstavlja odobrenje vizuelnog rešenja." },
    },
    labels: { licence: "Licenca", registration: "Registracija", vat: "VAT TRN", address: "Adresa", email: "E-pošta", jurisdiction: "Jurisdikcija" },
    boundaryTitle: "Granice",
    boundary: [
      "Kupovina ne daje automatski institucionalno članstvo, upravljačka prava, tantijeme ni investicijska prava.",
      "Institucionalna uloga je odvojena od komercijalnih transakcija sa opremom.",
      "Privatnost, uslovi programa i rešenja za kontrolisan pristup odgovaraju funkcijama koje su stvarno objavljene.",
      "Nijedna opšta izjava o merodavnom pravu ne primenjuje se na svakog posetioca, svaku prodaju ili svaki program u inostranstvu; ugovorna osnova se određuje po ugovoru.",
    ],
  },
  privacy: {
    title: "Privatnost",
    updated: "Verzija 2026-09-21 · sajt 4.2",
    contactTitle: "Kontakt za pitanja o privatnosti",
    sections: {
      collect: ["Šta se prikuplja", "Kada pošaljete obrazac: podaci koje unesete (ime, e-pošta, uloga, zemlja ili region, organizacija ako je navedena, vaša poruka i odgovori iz obrasca), parametri stranice i kampanje vaše posete (ulazna stranica, jezik, utm parametri; identifikatori klikova na reklame samo ako ste dozvolili analitiku) i vreme slanja. Vaša IP adresa se koristi samo u heširanom obliku kratkog trajanja, radi ograničavanja zloupotrebe, i ne čuva se sa vašim zahtevom."],
      purpose: ["Zašto", "Da se odgovori na vaš zahtev, da se pripremi ponuda ili specifikacija koju ste tražili i da se vodi evidencija o zahtevu. Na osnovu obrasca se ne šalju marketinške poruke."],
      storageOn: ["Gde se zahtevi čuvaju", "Zahtevi se čuvaju u bazi podataka kompanije Upstash, Inc. (Redis), koja se obezbeđuje preko hosting platforme Vercel Inc."],
      notifyEmail: ["Obaveštenje o novom zahtevu", "Kada se zahtev prihvati, obaveštenje sa podacima koje ste poslali šalje se e-poštom na odgovorno MAXIMUS poštansko sanduče."],
      notifyTelegram: ["Obaveštenje o novom zahtevu", "Kada se zahtev prihvati, obaveštenje sa podacima koje ste poslali šalje se odgovornoj osobi u MAXIMUS-u preko Telegrama (Telegram FZ-LLC, Dubai), koji zato obrađuje to obaveštenje u prenosu."],
      notifyWebhook: ["Obaveštenje o novom zahtevu", "Kada se zahtev prihvati, obaveštenje sa podacima koje ste poslali šalje se na internu MAXIMUS adresu, preko potpisane i šifrovane veze."],
      notifyNone: ["Obaveštenje o novom zahtevu", "Obaveštavanje o novim zahtevima je u postavljanju. Vaš zahtev se čuva i MAXIMUS ga čita iz internog registra; ništa se za ovu namenu ne šalje trećoj strani."],
      storageOff: ["Gde se zahtevi čuvaju", "Čuvanje zahteva je u postavljanju. Dok ne postane aktivno, obrasci navode da zahtev ne može biti prihvaćen; ništa se ne čuva. Sajt hostuje Vercel Inc."],
      browser: ["Skladište u pregledaču", "Sesijsko skladište čuva odgovore sa višestrukim izborom iz GPS-a i konfiguratora, kao i parametre kampanje vaše posete, za ovu sesiju pregledača. Kontakt podaci, slobodan tekst, tekst gravure i podaci o deci ne čuvaju se u pregledaču."],
      analyticsOn: ["Analitika", "Uz vašu saglasnost, Google Analytics 4 meri posete i događaje u obrascima, bez kontakt podataka i bez teksta zahteva. Vaš izbor se čuva u lokalnom skladištu i može se promeniti u svakom trenutku preko „Podešavanja analitike“ u podnožju. Obrasci rade i bez analitike."],
      analyticsOff: ["Analitika", "Na ovom sajtu nije aktivan nijedan alat za analitiku."],
      retention: ["Rok čuvanja", "Automatski rok brisanja još nije podešen. U svakom trenutku možete zahtevati brisanje svog zahteva."],
      children: ["Deca", "Obrasce popunjava punoletna osoba. Zahteve za igrače mlađe od 18 godina podnosi roditelj ili staratelj. Ne unosite ime deteta, datum rođenja, školu ni medicinske podatke. Profili dece se nikada ne objavljuju."],
      rights: ["Vaša prava", "Za pristup, ispravku ili brisanje svog zahteva pišite na gps@maximus.tennis i navedite ID zahteva."],
      controlled: ["Kontrolisane informacije", "Poverljivi dokumenti se ne čuvaju na ovom sajtu i ne dostavljaju se preko njega. Kontrolisano otkrivanje se obavlja pod NDA ili ugovorom, preko odvojenih kanala."],
    },
  },
  terms: {
    title: "Uslovi korišćenja",
    copyright: "Nosilac autorskog prava na ovom sajtu — na njegovim tekstovima, fotografijama, dizajnu i kodu — je isključivo Maximus Kiriyakulov. To pravo nije preneto nijednom privrednom društvu niti bilo kom drugom licu.",
    updated: "Verzija 2026-09-21",
    sections: [
      ["Informacija, ne ponuda", "Informacije o proizvodima na ovom sajtu opisuju odobrene specifikacije, arhitekturu konfiguracije i objašnjenja programa. Nisu ponuda za prodaju, cenovnik, izjava o zalihama niti obaveza isporuke. Komercijalni uslovi dogovaraju se posebno, u pisanoj formi, sa ugovornim subjektom navedenim u svakoj transakciji."],
      ["Zahtevi", "Zahtev poslat preko ovog sajta — uključujući GPS profile, zahteve za konfiguraciju i tehničke zahteve — čuva se sa ID-om zahteva i razmatra se. Nije prihvaćena narudžbina, proizvodna obaveza, potvrđen termin, prijava za članstvo niti prihvaćena prijava za bilo koji program."],
      ["Specifikacije i dokazi", "Izračunate vrednosti, proizvodni ciljevi i potvrđene specifikacije razlikuju se na odgovarajućim stranicama. Vrednosti krutosti su proizvodni ciljevi dok se ne objavi drugačije. Nijedan rezultat za konkretnog igrača nije garantovan."],
      ["Ekosistem, članstvo i prava", "Kupovina reketa ne stvara institucionalno članstvo, investicijska prava, vlasništvo nad intelektualnom svojinom, pravo na tantijeme niti pogodnosti učešća. Prava proizlaze iz objavljenih uslova programa ili iz pisanog ugovora."],
      ["Intelektualna svojina", "MAXIMUS®, amblem lava, oznaka GPS i sadržaj ovog sajta su zaštićeni. Interne inženjerske formule, protokoli kontrole kvaliteta, slojevi karbona, alati, identitet dobavljača, obračun troškova i zaštićena metodologija ne otkrivaju se ovde."],
    ],
  },
  lead: {
    submit: "Pošaljite zahtev",
    submitting: "Šalje se…",
    retry: "Pokušajte ponovo",
    acceptedEyebrow: "Zahtev je prihvaćen",
    acceptedTitle: "Vaš zahtev je primljen.",
    requestId: "ID zahteva",
    acceptedNext: "MAXIMUS razmatra svaki zahtev i odgovara u pisanoj formi na adresu e-pošte koju ste naveli. Sačuvajte ID zahteva za svaku dalju komunikaciju.",
    duplicate: "Ovaj zahtev je već bio primljen; duplikat nije napravljen.",
    another: "Započnite novi zahtev",
    errorsTitle: "Proverite ova polja:",
    failTitle: "Vaš zahtev nije poslat.",
    fail: {
      offline: "Vaš uređaj je oflajn.",
      network: "Veza sa serverom nije uspela.",
      timeout: "Server nije odgovorio na vreme.",
      rate_limited: "Sa ove mreže je došlo previše zahteva. Pokušajte ponovo za nekoliko minuta.",
      too_fast: "Obrazac je poslat veoma brzo. Proverite ga i pošaljite ponovo.",
      spam_suspected: "Zahtev je zaustavio filter za neželjenu poštu.",
      unavailable: "Zahtevi trenutno ne mogu biti prihvaćeni.",
      default: "Došlo je do neočekivane greške.",
    },
    keepNote: "Vaš unos ostaje na ovoj stranici, tako da možete pokušati ponovo.",
    sendByEmail: "Pošaljite ovaj zahtev e-poštom",
    sendByEmailNote: "Vaša aplikacija za e-poštu otvara se sa tekstom ovog zahteva. MAXIMUS ga prima kada pošaljete e-poruku.",
    mailConfig: "Konfiguracija",
    mailPage: "Stranica",
    fallback: "Ako se problem nastavi, pišite na {email}. Zahtev se smatra poslatim samo kada se prikaže ID zahteva.",
    privacyLink: "Obaveštenje o privatnosti",
    hpLabel: "Ostavite ovo polje prazno",
    consentShort: "Saglasnost",
    after: "Posle slanja, ID zahteva se prikazuje na ovoj stranici. Zahtevi se razmatraju i na njih se odgovara u pisanoj formi; zahtev nije narudžbina.",
    basis: { unstrung: "Bez žica", strung: "Sa žicama", unknown: "Nisam siguran — dogovoriti u specifikaciji" },
    hints: {
      email: "MAXIMUS odgovara u pisanoj formi na ovu adresu.",
      goal: "Na primer: prvi takmičarski reket ili prelazak sa juniorskog reketa. Ne navodite imena, datume rođenja ni medicinske podatke o detetu.",
      currentRacquet: "Marka i model, ako su poznati.",
      message: "Ne navodite lozinke, podatke o plaćanju ni medicinske podatke.",
    },
  },
  choose: {
    eyebrow: "Pomoć pri izboru",
    title: "Pomozite mi da izaberem reket",
    lead: "Recite MAXIMUS-u svoj nivo i šta vam je najvažnije. Vaši odgovori se razmatraju i dobijate pisani predlog: serija, klasa preciznosti, težina i veličina ručke.",
    stepsTitle: "Šta sledi",
    steps: [
      ["Vaši odgovori", "Nivo, prioriteti i veličina ručke ako je znate."],
      ["Stručno razmatranje", "MAXIMUS upoređuje vaše odgovore sa matricama serija."],
      ["Pisani predlog", "Predložena konfiguracija i sledeći korak, u pisanoj formi."],
    ],
    formTitle: "Vaši odgovori",
    submit: "Zatražite pomoć pri izboru",
    altTitle: "Želite sami da odlučite?",
    altGps: "Detaljan GPS profil",
    altBuild: "Konfigurišite direktno",
    note: "Bez automatskog prilagođavanja i bez tvrdnje o tačnosti: svaki zahtev pregleda čovek.",
  },
  consent: {
    title: "Analitika",
    text: "Može li MAXIMUS da meri posete pomoću Google Analytics? Obrasci rade u svakom slučaju; analitici se ne šalju kontakt podaci ni tekst zahteva.",
    allow: "Dozvolite analitiku",
    decline: "Odbijte",
  },
  familyPlan: {
    title: "Porodični plan",
    metaDescription: "Izračunajte teniski budžet svoje porodice: treninge, sate, kontakte sa lopticom i cenu jednog treninga, jednog sata i jednog udarca — na osnovu sopstvenih brojeva, u tri scenarija.",
    eyebrow: "Porodični plan · Doprinesite sa nama",
    heroTitle: "Koliko vašu porodicu košta tenis — i šta za to dobijate?",
    heroLead: "Izračunajte porodični budžet, treninge i sate koje on pokriva, procenjeni broj kontakata sa lopticom i cenu jednog treninga, jednog sata i jednog udarca — po sopstvenim uslovima.",
    heroCta: "Izračunajte svoj porodični plan",
    strategy: {
      eyebrow: "Naš cilj",
      title: "Više tenisa. Više prilika. Zajedno.",
      p1: "Naš cilj je da desetostruko povećamo svetsko tržište tenisa tako što ćemo proširiti učešće i put u tenis učiniti jasnijim i dostupnijim. MAXIMUS teži da preuzme vodeću ulogu kroz upravljanje, metodologiju, kvalitet, rezultate i popularizaciju igre.",
      p2: "Druge proizvođače teniske opreme i njihove brendove vidimo kao potencijalne partnere. Predlažemo da snage kompanija, trenera, klubova i porodica udružimo u zajednički program za razvoj, promociju i širenje tenisa, na obostranu korist.",
      p3: "MAXIMUS je peti element ovog pristupa: uloga koja ujedinjuje i pomaže da odvojene snage deluju zajedno. Naši zajednički izazovi su bolesti, neaktivnost dece i prepreke koje ljude sprečavaju da počnu i nastave da igraju.",
      p4: "Za porodicu sve počinje jasnoćom. Porodični plan prikazuje budžet, broj treninga i sati, procenjeni broj kontakata sa lopticom i cenu treniranja. Promenite uslove i izaberite scenario koji vam odgovara.",
      note: "Za MAXIMUS je desetostruki rast strateški cilj, a ne već ostvaren rezultat. Kalkulator prikazuje proračune po scenarijima i ne obećava ni uštedu, ni medicinski efekat, ni sportski rezultat.",
      ctaCalc: "Izračunajte svoj porodični plan",
      ctaPartner: "Razgovarajmo o zajedničkom razvoju tenisa",
    },
    beyond: {
      eyebrow: "Van terena",
      title: "Šta plan gradi osim treninga",
      admission: {
        h: "Upis u vodeće škole i univerzitete",
        p: "MAXIMUS podržava porodicu na putu do vodećih škola i univerziteta u svetu: kroz izgradnju sportske biografije igrača, pripremu dokumenata i prijava, kao i izbor programa u kojima sport i školovanje idu ruku pod ruku. Ako se dodeli sportska stipendija, ona smanjuje iznos koji porodica plaća za obrazovanje.",
      },
      assets: {
        h: "Digitalna imovina: ime, lik i postignuća igrača",
        p: "Ime, lik, rezultati, sadržaj i lični brend igrača su imovina koja vremenom može da izgradi značajnu finansijsku i statusnu vrednost. MAXIMUS pomaže da se ta imovina stvori, registruje i zaštiti, kako bi ta vrednost ostala igraču i porodici.",
      },
      note: "Ni jedno ni drugo nije deo kalkulatora. Vrednost mesta u školi, stipendije ili digitalne imovine zavisi od konkretnog slučaja i ovde se ne procenjuje.",
      cta: "Pitajte o podršci pri upisu i o digitalnoj imovini",
    },
    steps: ["Podaci porodice", "Ekonomika treninga", "Dugoročni plan", "Konačni obračun"],
    stepsLabel: "Koraci kalkulatora",
    scenarios: { now: "Trenutno", planned: "Planirano", wish: "Željeno" },
    scenarioHints: { now: "Ono što vaša porodica radi danas.", planned: "Ono što nameravate da radite dalje.", wish: "Ono što biste želeli da radite." },
    currency: {
      label: "Valuta",
      note: "Svaki iznos koji unesete izražen je u ovoj valuti. Ništa se ne preračunava u drugu valutu.",
    },
    fields: {
      players: { label: "Članovi porodice koji igraju", hint: "Ceo broj." },
      cost: { label: "Cena jednog treninga za jednog igrača", hint: "Iznos bez decimala, sa uključenim porezima i taksama." },
      sessions: { label: "Broj treninga po igraču mesečno", hint: "Ceo broj." },
      minutes: { label: "Trajanje jednog treninga, u minutima", hint: "Puno vreme, uključujući pauze. Dozvoljeni su decimalni brojevi." },
      contacts: { label: "Kontakti sa lopticom po igraču po treningu", hint: "Kontakt je dodir igračevog sopstvenog reketa sa lopticom. Jedna razmena udaraca nije jedan kontakt. U svakom scenariju brojite na isti način." },
    },
    presetsLabel: "Brzi izbor, minuti",
    ages: {
      title: "Trajanje plana",
      start: "Početni uzrast",
      end: "Završni uzrast",
      hint: "Anonimna pretpostavka o tome koliko plan traje, koristi se samo za dugoročnu tabelu. Nije datum rođenja niti preporučeni uzrast za početak.",
    },
    extras: {
      title: "Dodatni troškovi porodice",
      note: "Ovi iznosi se odnose na celu porodicu i važe za sva tri scenarija. Ne množe se brojem igrača i ne ulaze u cenu sata niti kontakta.",
      equipment: "Prva oprema — jedan iznos za period",
      clothing: "Odeća i obuća — jedan iznos za period",
      renewal: "Obnova opreme — jedan iznos za period, ne ponavlja se automatski",
      court: "Teren ili klub — mesečno, za celu porodicu",
      travel: "Putovanja i događaji — mesečno, za celu porodicu",
      quoteSource: "Izvor cena (opciono)",
      quoteDate: "Datum cena (opciono)",
      quoteNote: "Prikazuje se tačno onako kako ste uneli. MAXIMUS ne proverava ove cene.",
    },
    storage: {
      save: "Sačuvajte plan na ovom uređaju",
      clear: "Obrišite plan sa ovog uređaja",
      saved: "Plan je sačuvan na ovom uređaju. Ništa nije nigde poslato.",
      cleared: "Plan je obrisan. Kalkulator je vraćen na početne vrednosti.",
      restored: "Vraćen je plan koji ste sačuvali na ovom uređaju.",
      invalid: "Plan sačuvan na ovom uređaju nije mogao da se pročita i nije primenjen. Možete da započnete novi proračun.",
      unavailable: "Ovaj pregledač ne dozvoljava čuvanje na uređaju.",
    },
    annual: {
      title: "Jedna godina, uporedo",
      sessions: "Igrač-treninzi godišnje",
      cost: "Izdaci porodice za treninge godišnje",
      hours: "Igrač-sati godišnje",
      length: "Trajanje jednog treninga",
      contacts: "Kontakti sa lopticom godišnje",
      note: "Igrač-treninzi i igrač-sati sabiraju treninge svih igrača. To nisu sati iznajmljivanja terena niti grupni termini: dva igrača koji zajedno treniraju 90 minuta čine 2 igrač-treninga i 3 igrač-sata.",
    },
    economics: {
      title: "Cena treninga, sata i kontakta",
      session: "Jedan trening jednog igrača",
      hour: "Jedan sat treninga jednog igrača",
      contact: "Jedan kontakt sa lopticom",
      undefinedContacts: "Nije definisano: 0 kontakata",
      undefinedMinutes: "Nije definisano: 0 minuta",
      below: "manje od {value}",
      note: "U ove brojke ulazi samo cena treninga. Dodatni troškovi porodice ne raspoređuju se na kontakte.",
      caption: "Broj kontakata izračunava se na osnovu izabranog obima treninga i pretpostavki modela. Stvarni trening zavisi od formata, pauza i uslova rada. Cena kontakta je budžetski pokazatelj, a ne merilo kvaliteta trenerskog rada.",
    },
    longTerm: {
      title: "Dugoročni plan troškova",
      horizon: "Horizont",
      activeYears: "Aktivne godine",
      years: "{n} god.",
      note: "Aktivne godine ograničene su razlikom između početnog i završnog uzrasta. Cene, učestalost, inflacija, sezone, propušteni treninzi i devizni kursevi uzimaju se kao nepromenljivi. Dodatni troškovi nisu deo ove tabele.",
    },
    final: {
      title: "Konačni obračun",
      scenario: "Scenario za obračun",
      months: "Period, u mesecima",
      heading: "{scenario} · {months} mes.",
      total: "Ukupno za period",
      training: "Treninzi",
      extras: "Dodatni troškovi",
      oneOff: "Jednokratne stavke",
      monthly: "Mesečne stavke × broj meseci",
      sessions: "Igrač-treninzi u periodu",
      hours: "Igrač-sati u periodu",
      contacts: "Kontakti sa lopticom u periodu",
      formulaTitle: "Kako se računa",
      formula: "Ukupno = broj igrača × broj treninga mesečno × broj meseci × cena treninga + jednokratni troškovi + broj meseci × mesečni dodatni troškovi.",
      formulaNote: "Dodatni troškovi unose se za celu porodicu. Jednokratne stavke računaju se jednom, čak i za period od 0 meseci.",
      inputs: "Vaši unosi",
    },
    units: { min: "min", h: "h", approx: "≈" },
    errors: {
      title: "Ispravite ova polja da biste videli rezultat",
      required: "Obavezno polje — unesite broj; 0 je dozvoljena vrednost.",
      negative: "Vrednost ne može biti negativna.",
      integer: "Samo ceo broj.",
      number: "Unesite broj.",
      tooLarge: "Ovaj broj je prevelik za proračun.",
      endBeforeStart: "Završni uzrast ne može biti manji od početnog.",
      tooLong: "Najviše 200 znakova.",
      date: "Unesite ispravan datum.",
      currency: "Izaberite valutu.",
      scenario: "Izaberite scenario.",
      result: "Rezultat je prevelik da bi se pouzdano prikazao. Smanjite unete vrednosti.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: kompletna kompozicija — meta prikazana spreda i sa strane, gravirani medaljon sa lavom na okrugloj glavi za kontakt, gravura MAXIMUS i SPOT TRAINER duž vrata i osmougaoni poklopac ručke sa oznakom lava",
    greatHero: "MAXIMUS GREAT serija, 363 g: kompletna kompozicija sa crvenim i žutim detaljima na glavi, sjajnim MAXIMUS natpisom, Maximus autogramom na vratu reketa i poklopcem ručke sa lavom",
    spotDetail: "Dve MAXIMUS Spot Trainer mete izbliza: gravirani lav na mat crnoj glavi za kontakt, rebrasti omot ručke i osmougaoni poklopci ručki sa oznakom lava",
    spotPair: "Dve MAXIMUS Spot Trainer mete položene pod uglom na tamnoj površini, sa gravurom MAXIMUS duž jednog vrata i SPOT TRAINER duž drugog, sa medaljonom lava na svakoj glavi za kontakt",
    spinVisual: "MAXIMUS SPIN: glava sa žicama, sjajni MAXIMUS natpis, ručka i poklopac ručke sa lavom",
    powerVisual: "MAXIMUS POWER: glava sa žicama, sjajni MAXIMUS natpis, gravura personalizacije, ručka i poklopac ručke sa lavom",
    greatVisual: "MAXIMUS GREAT: glava sa žicama, sjajni MAXIMUS natpis, gravura personalizacije, ručka, poklopac ručke sa lavom i oznaka serije G na grlu reketa",
    spinHead: "MAXIMUS SPIN glava i površina žica",
    handleLion: "MAXIMUS grlo reketa, ručka i poklopac ručke sa oznakom lava",
    engraving: "Srebrna gravura personalizacije na vratu reketa",
    lettering: "Sjajni crni MAXIMUS natpis na mat crnom ramu",
    variantAlt: "MAXIMUS serija {series} — {w} g, balans {b} mm: kompletna vizualizacija sa trakom specifikacije, zonom gravure personalizacije i MIPA oznakom",
    sstSystem: "MAXIMUS Sweet Spot Trainer, sistem od četiri reketa",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Vratovi reketa Sweet Spot Trainer sa MAXIMUS natpisom",
    sstGrips: "Ručke i poklopci ručki Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, četiri poklopca ručke sa oznakom lava",
    note: "Vizual proizvoda",
  },
  notFound: { title: "Stranica nije nađena", p: "Stranica koju ste zatražili ne postoji na ovom jeziku.", cta: "Idite na početnu stranicu" },
};

export default sr;
