/* Swedish dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const sv = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — tennisracketar i helkolfiber, konstruerade enligt specifikation",
    defaultDescription:
      "Tennisracketar i helkolfiber från ram till handtag: GREAT 97 in², POWER 98 in² och SPIN 100 in², åtta greppstorlekar från fabrik L0–L7, precisionsklasser för vikt, balans, swingweight och styvhet samt specialkonstruktion på begäran.",
  },
  common: {
    statuses: {
      current: "Aktuell",
      agreement: "Tillgänglig enligt överenskommelse",
      development: "Under utveckling",
      concept: "Koncept",
      target: "Tillverkningsmål",
      modelled: "Beräknad",
      confirmed: "Bekräftad",
      requested: "Önskad arkitektur",
      notprovided: "Ej angivet",
    },
    brief: { who: "Vem det är för", value: "Vad du får", now: "Bekräftat i dag", next: "Nästa steg" },
    labels: {
      next: "Nästa",
      back: "Tillbaka",
      edit: "Ändra svar",
      review: "Granska",
      start: "Börja",
      restart: "Börja om",
      copy: "Kopiera förfrågans text",
      copied: "Kopierat",
      openEmail: "Öppna e-post för att skicka förfrågan",
      reference: "Ärendereferens",
      weight: "Vikt",
      balance: "Balans",
      swingweight: "Swingweight",
      stiffness: "Styvhet",
      grip: "Greppstorlek",
      headSize: "Huvudstorlek",
      series: "Serie",
      precisionClass: "Precisionsklass",
      quantity: "Antal",
      notProvided: "Ännu inte publicerat",
      requestTarget: "Önskat målvärde",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Läs mer",
      allSeries: "Alla serier",
      points: "listade vikter",
      optional: "valfritt",
      required: "obligatoriskt",
      select: "Välj",
      yes: "Ja",
      no: "Nej",
      unknown: "Osäker",
      custom: "Eget målvärde",
      listed: "Listad vikt",
      individual: "Enskild racket",
      pair: "Matchat par",
      triple: "Matchad trio",
      team: "Lagsats",
      summaryTitle: "Sammanfattning av din förfrågan",
      nextAction: "Nästa åtgärd",
      status: "Status",
      learn: "Mer information",
      schematic: "Schematisk bild — ingen mätning",
      photo: "Fotografi",
    },
    ecosystemStrip: "MAXIMUS-ekosystemet",
    truth: {
      noPrices: "Priser, minimikvantiteter, ledtider, garantier och leveransåtaganden bekräftas skriftligt per marknad och per program.",
      requestNotOrder: "En förfrågan är en begäran om granskning. Den är inte en accepterad order, ett tillverkningsåtagande eller en bekräftad bokning.",
      noGuarantee: "Ingen utrustning, metod eller något program som beskrivs här garanterar ett resultat för en enskild spelare.",
      governing: "Den här sidan publiceras på flera språk. Den engelska versionen är den gällande versionen; översättningen tillhandahålls som en hjälp.",
    },
  },
  nav: {
    language: "Språk",
    groups: { racquets: "Racketar", training: "Träning", ecosystem: "Ekosystem", partnerships: "Partnerskap" },
    racquets: "Racketserier och jämförelse",
    great: "GREAT — 97 in² · Kontroll",
    power: "POWER — 98 in² · Kraft",
    spin: "SPIN — 100 in² · Skruv",
    precision: "Precision och styvhet",
    grip: "Greppstorlekar från fabrik L0–L7",
    custom: "Specialkonstruktion",
    training: "Träningssystem",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodik",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Hjälp att välja",
    ecosystem: "Ekosystemkarta",
    engineering: "Konstruktion och tillverkning",
    experience: "Prova och anpassa",
    brands: "Personliga varumärken och ambassadörer",
    families: "Familjer och föräldrar",
    owners: "Ägare och ägararkivet",
    network: "Sports Network",
    partnerships: "Alla partnerskapsvägar",
    coaches: "Tränare",
    clubs: "Klubbar och akademier",
    distribution: "Distribution och marknadsutveckling",
    strategic: "Strategi och investering",
    institutional: "Institutionella program",
    contact: "Kontakt",
    legal: "Juridisk identitet",
    privacy: "Integritet",
    terms: "Användarvillkor",
    menu: "Meny",
    close: "Stäng",
    home: "Startsida",
    skip: "Hoppa till innehållet",
  },
  footer: {
    line: "MAXIMUS-racketen är din nyckel till MAXIMUS-världen.",
    product: "Produkt",
    ecosystem: "Ekosystem",
    company: "Organisation",
    instagram: "Instagram",
    email: "E-post",
    analytics: "Inställningar för webbanalys",
    subscribe: {
      title: "Håll kontakten med MAXIMUS",
      line: "Nya serier, datum för anpassning, träningsmaterial och ägarprogrammet. Några brev om året, inget mer.",
      label: "E-postadress",
      placeholder: "your@email.com",
      button: "Prenumerera",
      sending: "Skickar",
      done: "Du står på listan. Vi skriver bara när det finns något värt att läsa.",
      invalid: "Kontrollera adressen.",
      failed: "Adressen registrerades inte. Försök igen om en stund.",
      terms: "Genom att prenumerera godkänner du att MAXIMUS får skicka dig dessa uppdateringar och lagra din adress för det ändamålet. Varje brev innehåller en länk för att avsluta prenumerationen.",
    },
    rights: "MAXIMUS® och lejonemblemet är varumärken i MAXIMUS-ekosystemet. MIPA: intern kontroll av immateriella rättigheter, proveniens och dokument.",
    boundary:
      "Kommersiella och avtalsmässiga villkor avtalas separat och skriftligt. Köpet av en racket ger inte institutionellt medlemskap, investeringsrättigheter, äganderätt till immateriella rättigheter eller rätt till royalty.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Precisionen börjar i träffpunkten.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer och MAXIMUS-metodiken kopplar fokuserad träning till prestationsracketar i helkolfiber.",
    heroCta1: "Utforska träningssystemet",
    heroCta2: "Utforska GREAT",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontroll",
    heroMeta: [
      ["Helkolfiber", "från ram till handtag"],
      ["4 parametrar", "vikt · balans · swingweight · styvhet"],
      ["8 greppstorlekar", "fabriksgeometri L0–L7"],
      ["3 serier", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "Börja här",
      title: "Välj din väg",
      items: {
        player: { h: "Spelare", p: "Hitta en racket utifrån nivå och prioriteringar, eller konfigurera en direkt.", a: "Hitta din racket" },
        parent: { h: "Förälder", p: "En skriftlig väg för utvecklingsmål, tränarens medverkan och lämplig utrustning.", a: "Familjevägen" },
        coach: { h: "Tränare, klubb eller akademi", p: "Träningssystem, anpassning, lagsatser och personalisering.", a: "Vägar för tränare och klubb" },
        partner: { h: "Distributör eller partner", p: "Vägar för distribution, marknadsutveckling, strategi och institutionella program.", a: "Partnerskapsvägar" },
      },
    },
    series: {
      eyebrow: "Prestationsserier",
      title: "Tre prestationsarkitekturer. En teknisk plattform.",
      lead: "Välj serie utifrån spelriktning och slutför sedan konfigurationen: precisionsklass, vikt, grepp, personalisering.",
      cta: "Jämför serierna",
      configure: "Konfigurera",
      open: "Öppna serien",
      photoPending: "Fotografi ännu inte publicerat",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS precisionssystem",
      title: "Vikt. Balans. Swingweight. Styvhet.",
      sub: "Styrda som ett enda tekniskt system.",
      lead: "Tre precisionsklasser anger hur snävt varje färdig racket hålls till sin deklarerade specifikation. P0.5 är en snäv tolerans under ett definierat mätprotokoll — inte noll avvikelse.",
      cta: "Precision och styvhet i detalj",
    },
    stiffness: {
      eyebrow: "Styvhet",
      title: "Repeterbart ramsvar mot ett deklarerat målvärde.",
      p: "Ramens styvhet formar svaret, känslan och likheten mellan racketar. MAXIMUS behandlar den som den fjärde styrda parametern: målvärdet, det uppmätta resultatet, den tillåtna toleransen och mätinstrumentets kapacitet förs som skilda uppgifter. Nyttan är repeterbarhet — inte ett garanterat resultat för varje spelare.",
      cols: [["Svar", "Hur ramen återför energi i träffpunkten."], ["Känsla", "Vad spelaren förnimmer i träffpunkten."], ["Likhet", "Racketar byggda enligt samma specifikation svarar likadant inom sin klass."]],
      schematicCaption: "Schematisk bild: tillåten avvikelse omkring ett deklarerat styvhetsmål för varje klass. Ingen mätning; inget RA-värde antyds.",
      bands: { p25: "måltolerans ±1 RA", p15: "måltolerans ±0.5 RA", p05: "uppfyller det deklarerade mål-RA-värdet enligt fabrikens fastställda mätprotokoll — inte noll avvikelse", target: "deklarerat målvärde (inget värde antyds)" },
    },
    carbon: {
      eyebrow: "Konstruktionsstandard",
      title: "Helkolfiber. Från ram till handtag.",
      p: "Alla aktuella MAXIMUS-racketar på den här plattformen är helt i kolfiber i sin struktur, handtaget inkluderat. Skumfyllning används inte för att forma handtaget.",
      gripTitle: "Åtta greppstorlekar från fabrik. L0–L7.",
      gripP: "Varje storlek är greppgeometri i kolfiber från fabrik — ingen uppbyggnad med overgrip.",
      scaleCaption: "Schematisk bild: nominella greppbeteckningar L0–L7 (4″ till 4⅞″). Inga uppmätta handtagsmått.",
      cta: "Greppstorlekar från fabrik",
    },
    custom: {
      eyebrow: "Specialkonstruktion",
      title: "Konstruerad enligt specifikation.",
      sub: "Standardsortimentet är utgångspunkten.",
      p: "MAXIMUS tar emot tekniska krav utanför de publicerade matriserna för bedömning, konstruktion, validering och tillverkning enligt avtalad specifikation. Genomförbarheten bekräftas skriftligt.",
      chain: ["Definiera", "Konstruera", "Validera", "Specificera", "Tillverka", "Mät / dokumentera"],
      cta: "Skicka ett tekniskt underlag",
      cta2: "Diskutera specialkonstruktion",
    },
    training: {
      eyebrow: "Träningssystem",
      title: "Ett träningssystem byggt kring träffpunkten.",
      p: "Sweet Spot Trainer, MAXIMUS-metodiken och Spot Trainer förenar utrustning med tränarledd träning: centrerad träff, kontroll, stegvis belastning och övergången tillbaka till prestationsracketen.",
      cta: "Träningssystem",
      cta2: "Begär en visning",
      photoPending: "Fotografi av träningsracketen ännu inte publicerat",
      sstP: "Ett träningshuvud på 50 in² för övning av centrerad träff, med fyra viktkonfigurationer för tränarens val av belastning.",
      sstCta: "Utforska Sweet Spot Trainer",
      sstCaption: "Konfigurationen 300 g, en av fyra",
      methodP: "Sätt mål, välj utrustning, träna med tränarens medverkan, dokumentera iakttagelser, utvärdera på nytt, justera och överför arbetet till tävlingsspel.",
      methodCta: "Utforska metodiken",
      spotP: "En liten rund träffyta för att öva in en exakt och repeterbar träffpunkt.",
      spotCta: "Utforska Spot Trainer",
    },
    manufacturing: {
      eyebrow: "Tillverkning och kvalitetskontroll",
      title: "Byggd enligt en specifikation. Uppmätt och dokumenterad.",
      p: "Tillverkningen följer den skriftliga specifikationen för varje order. Dokumentationen följer precisionsklassen: bevarad tillverkningsdokumentation för P2.5, individuell dokumentation och spårbarhet för P1.5, individuell kontroll och dokumentation för P0.5 där programmet för ordern omfattar dem.",
      confirmedTitle: "Bekräftat",
      confirmed: ["Konstruktion i helkolfiber från ram till handtag.", "Precisionsklasserna P2.5, P1.5 och P0.5 med fyra styrda parametrar.", "Åtta greppstorlekar från fabrik L0–L7."],
      pendingTitle: "Ännu inte publicerat",
      pending: "Fotografier av mätutrustning, exempel på kvalitetsprotokoll och filmer från fabriken är ännu inte publicerade. Inget på den här sidan är ett uppmätt certifikat.",
      captions: { lettering: "Glansig MAXIMUS-text på den matta ramen", buttcap: "Grepp och greppkapsel med lejonmärket", handle: "Silverfärgad personaliseringsgravyr", finish: "Huvud och strängplan" },
      cta: "Konstruktion och tillverkning",
    },
    world: {
      eyebrow: "MAXIMUS-världen",
      title: "En nyckel. Ett ekosystem. Obegränsade möjligheter.",
      note: "”Obegränsade möjligheter” är ett varumärkesuttryck, inte ett löfte om obegränsad teknisk genomförbarhet, inkomst eller tillgång. Ett köp ger ingen royalty, avkastning på investering, sponsring eller finansiering av en spelares utveckling.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — och din navigation i tennisens värld: en vägledd utrustningsprofil som besvaras skriftligt." },
        personal: { h: "Personalisering", p: "Namn, initialer, nummer och lagmärkning i den godkända silverfärgade gravyren." },
        development: { h: "Utveckling", p: "Tränarledda träningssystem, dokumentation och ny utvärdering." },
        ecosystem: { h: "Utvidgat ekosystem", p: "Personliga varumärken, ägardokumentation, nätverk, licensiering och institutionella program — var och en med sin faktiska status." },
      },
      cta: "Utforska ekosystemet",
    },
    partners: {
      eyebrow: "Partnerskapsvägar",
      title: "Tränare, klubbar, distributörer och partner.",
      p: "Skriftlig kvalificering först. Landsrättigheter, exklusivitet och kommersiella villkor förhandlas skriftligt — de ges aldrig via ett formulär.",
      cta: "Alla partnerskapsvägar",
      formTitle: "Kort förfrågan",
      formLead: "Välj syfte och skriv till MAXIMUS. Du får ett ärendenummer på den här sidan.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "DIN NAVIGATION I TENNISENS VÄRLD" } },
    personal: { eyebrow: "Personalisering", title: "Ditt namn. Ditt nummer. Din MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Tre serier. Verkliga parametrar." },
    map: { cta: "Utforska ekosystemet" },
  },
  racquets: {
    title: "Racketar",
    lead: "Tre prestationsserier med gemensam konstruktionsstandard, gemensamt precisionssystem och gemensamma greppstorlekar från fabrik. Varje serie är en etablerad prestationsarkitektur inom en bredare teknisk plattform.",
    direction: { control: "Kontroll", power: "Kraft", spin: "Skruv" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Primär spelriktning",
    compareTitle: "Jämförelse av serierna",
    compareLead: "Endast bekräftade arkitekturdata. Strängmönster, längder, ramprofiler, intervall för strängspänning samt nominella värden för swingweight och styvhet är inte publicerade för de här serierna; de samlas in som önskade målvärden för teknisk granskning.",
    columns: { series: "Serie", head: "Huvudstorlek", direction: "Riktning", weights: "Listade vikter", range: "Viktspann", balance: "Balansdata" },
    balanceModelled: "Beräknade värden",
    balanceNotProvided: "Ännu inte publicerat",
    construction: "Konstruktion: helkolfiber, ram till handtag · Precision: P2.5 / P1.5 / P0.5 · Grepp: L0–L7",
    otherTitle: "Andra racketsporter",
    otherLead: "Godkända utvecklingsriktningar. Det finns inga säljbara produkter i de här kategorierna och ingen tennisspecifikation överförs till dem.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Beachtennis" },
    ctaConfigure: "Konfigurera en förfrågan",
    ctaSeries: "Öppna serien",
  },
  seriesPage: {
    eyebrow: "Prestationsserie",
    intro: {
      great: "Arkitekturen GREAT på 97 in² är byggd kring kontroll: ett kompakt huvud, exakt träff och trygghet i riktningen.",
      power: "Arkitekturen POWER på 98 in² är byggd kring energiöverföring: djup och fart från en stabil ram.",
      spin: "Arkitekturen SPIN på 100 in² är byggd kring bollens beteende: rotation, marginal och bana.",
    },
    photoPending: "Fotografi av serien ännu inte publicerat",
    detailPending: "Detaljfotografier av konstruktion och handtag för den här serien är ännu inte publicerade.",
    specsTitle: "Specifikation och status",
    catalogue: {
      eyebrow: "Katalog för serien {series}",
      title: "{n} viktvarianter",
      lead: "Varje variant av serien {series}, sorterad efter vikt. Vikt i gram, balans i millimeter från greppändan. Varje visualisering visas hel: inget är beskuret, maskerat eller utsträckt.",
      selectLabel: "Välj en viktvariant",
      select: "Visa den här varianten",
      selected: "Visas ovan",
      balanceLabel: "Balans",
      headLabel: "Huvudstorlek",
      constructionLabel: "Konstruktion",
      gripsLabel: "Greppstorlekar från fabrik",
      precisionLabel: "Precisionsklasser",
      balanceConfirmed: "Balansen är det bekräftade värdet för den här vikten och stämmer med den siffra som är tryckt på visualiseringen. Priser, lager och leveranstider publiceras inte här.",
      balanceModelled: "Balansen är ett beräknat värde för den här listade vikten, inte en individuell fabriksmätning; den stämmer med den siffra som är tryckt på visualiseringen. Priser, lager och leveranstider publiceras inte här.",
      zoom: "Öppna bilden",
      close: "Stäng",
      allTitle: "Alla {n} varianter",
    },
    specs: { head: "Huvudstorlek", direction: "Primär riktning", weights: "Listade vikter", range: "Viktspann", balance: "Balans", construction: "Konstruktion", grips: "Grepp från fabrik", precision: "Precisionsklasser" },
    construction: "Helkolfiber, ram till handtag",
    statusTitle: "Värdenas status",
    matrixTitle: "Fullständig viktmatris",
    matrixLead: "De listade vikterna är standardurvalet. Andra vikter kan begäras som egna målvärden; mellanliggande värden som saknas läggs inte till.",
    balanceNote: {
      confirmed: "Balansvärdena är bekräftade för varje listad vikt (mm från greppändan) och stämmer med den siffra som är tryckt på visualiseringen av den vikten. De beräknas inte här och jämnas inte ut mellan närliggande vikter; mätunderlaget bekräftas i den skriftliga specifikationen.",
      modelled: "Balansvärdena är beräknade för varje listad vikt (mm från greppändan). De är inte individuella fabriksmätningar; mätunderlaget bekräftas i den skriftliga specifikationen.",
      notprovided: "Balansvärden för den här serien anges inte. Härled dem inte från en annan serie.",
    },
    optionsTitle: "Precision, grepp och vikt",
    notPublished: "Inte publicerat för den här serien: strängmönster, längd, ramprofil, intervall för strängspänning samt värden för swingweight och styvhet. Du kan ange dem som önskade målvärden för teknisk granskning.",
    offerTitle: "Så går det till efter din förfrågan",
    offerSteps: [
      ["Förfrågan", "Skicka in en konfiguration eller en fråga. Ett ärendenummer visas direkt."],
      ["Granskning", "MAXIMUS granskar serie, klass, vikt, grepp och eventuella önskade målvärden."],
      ["Skriftligt svar", "Specifikation, tillgänglighet och kommersiella villkor bekräftas skriftligt."],
    ],
    faqTitle: "Frågor",
    faq: [
      ["Är balansvärdena uppmätta?", "De är beräknade för de listade vikterna, inte individuella mätningar. Mätunderlaget bekräftas i den skriftliga specifikationen."],
      ["Kan jag begära en vikt som inte är listad?", "Ja, som ett eget målvärde i hela gram. Den granskas tekniskt och genomförbarheten bekräftas skriftligt."],
      ["Vad förändrar precisionsklassen?", "Hur snävt vikt, balans, swingweight och styvhet hålls till den deklarerade specifikationen och vilken dokumentation som förs."],
      ["Byggs greppet upp med overgrip?", "Nej. L0–L7 är greppgeometrier i kolfiber från fabrik."],
      ["Var finns priser och leveranstider?", "De bekräftas skriftligt för varje förfrågan och publiceras inte här."],
    ],
    faqSpinBalance: ["Varifrån kommer balansvärdena för SPIN?", "Från den bekräftade tabellen för Spin-serien: 33 viktvarianter med balans i millimeter från greppändan. Varje par stämmer med den siffra som är tryckt på den godkända visualiseringen av den vikten. Värdena är inte beräknade och jämnas inte ut mellan närliggande vikter."],
    ctaBuild: "Konfigurera den här serien",
    ctaAsk: "Fråga om den här serien",
    ctaCompare: "Jämför alla serier",
    weightsLabel: "listade vikter",
    headLabel: "huvud",
  },
  precision: {
    title: "Precision och styvhet",
    switch: { label: "Välj en precisionsklass", panelLabel: "Fyra styrda parametrar —", qcLabel: "Kvalitetsarkitektur", protocolNote: "enligt fabrikens definierade mätprotokoll för kvalitetskontroll", fullTable: "Fullständig jämförelsetabell" },
    lead: "Fyra parametrar som styrs som ett enda tekniskt system. Varje klass anger hur snävt en färdig racket hålls till sin deklarerade specifikation och vilken kvalitetsdokumentation som tas fram.",
    statement: "Vikt. Balans. Swingweight. Styvhet. Styrda som ett enda tekniskt system.",
    classes: {
      "P2.5": { name: "Skalbar prestationskärna", qc: "Individuell mätning och bevarad tillverkningsdokumentation." },
      "P1.5": { name: "Avancerad precision", qc: "Individuell mätning, individuell dokumentation och spårbarhet." },
      "P0.5": { name: "Professionell · individuellt kontrollerad", qc: "Individuell kontroll med nominella och verkliga värden samt individuella mätprotokoll; serieidentitet, batchspårbarhet, ett precisionscertifikat och matchade uppsättningar där programmet för ordern omfattar dem." },
    },
    columns: { cls: "Klass", weight: "Vikt", balance: "Balans", sw: "Swingweight", stiff: "Styvhet", qc: "Kvalitetsarkitektur" },
    stiffTarget: "måltolerans",
    stiffExact: "uppfyller det deklarerade mål-RA-värdet enligt fabrikens fastställda mätprotokoll",
    programmeNote: "Serieidentitet, certifikat och dokumentation för matchade uppsättningar utfärdas bara där programmet för en bestämd order omfattar dem.",
    targetsNote: "Specifikationer för styvhet är tillverkningsmål till dess att tillämpligt protokoll och produktionsunderlag bär ett starkare påstående. Arkitekturen innebär inte att varje listad konfiguration redan har genomgått en fullständig frisläppningsprocess för alla fyra parametrar.",
    stiffnessTitle: "Därför betyder styvheten något",
    stiffnessP1: "Ramens styvhet påverkar hur ramen svarar i träffpunkten, hur den känns och hur lika två racketar är varandra. Den främsta nyttan av att styra den är ett repeterbart svar mot en deklarerad specifikation.",
    stiffnessP2: "Innan verifierad överensstämmelse publiceras anger den interna kvalitetsdokumentationen instrumentet, dess kalibreringsstatus, metoden, racketens skick, upplösningen, mätosäkerheten, upprepade mätningar, avrundningsregeln och godkännandekriteriet. Ett identiskt visat heltal är inget bevis på noll fysisk variation eller noll mätfel.",
    fields: ["Målvärde", "Uppmätt resultat", "Tillåten tolerans", "Instrumentets kapacitet"],
    fieldsNote: "Förs som skilda fält i varje protokoll.",
    matchedTitle: "Matchade uppsättningar",
    matchedP: "Kriterierna för matchade uppsättningar definieras separat från den individuella toleransen. Att varje racket håller sin nominella tolerans bevisar inte i sig en bestämd maximal skillnad mellan två racketar. Matchade par, trior och lagsatser begärs via konfiguratorn och bekräftas skriftligt.",
    extendedTitle: "Utvidgad teknisk modell",
    extendedP: "Datamodellen rymmer fler parametrar. Det finns ännu inga värden eller toleransklasser för dem; de kan anges som önskade målvärden i ett tekniskt underlag.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Vridningsbeteende", length: "Längd", beamProfile: "Ramprofil", headGeometry: "Huvudgeometri", stringPattern: "Strängmönster", durability: "Hållbarhet", vibration: "Vibrationsegenskaper" },
    noZero: "MAXIMUS beskriver inte sitt sortiment som att det har noll tolerans. Precision anges som en klass med en deklarerad tolerans och en definierad kvalitetsarkitektur.",
    cta: "Konfigurera med en precisionsklass",
  },
  grip: {
    title: "Greppstorlekar från fabrik",
    statement: "Åtta greppstorlekar från fabrik. L0–L7.",
    lead: "Greppets geometri är en del av handtagets kolfiberarkitektur. Varje storlek tillverkas som handtagsgeometri och byggs inte upp med overgrip.",
    emph: "Utökade storlekar",
    p1: "Fabrikssortimentet med åtta storlekar ger tränare och spelare ett bredare konfigurationsspann, så att utrustningen kan specificeras kring spelaren, inklusive de större geometrierna L6 och L7.",
    p2: "Den nominella greppbeteckningen skiljer sig från handtagets råa strukturmått och från det slutliga mätprotokollet. Storlekarna gäller för prestationsserierna och för träningsfamiljerna på den här plattformen.",
    p3: "Inget krav på världsomfattande exklusivitet görs för det här sortimentet.",
    columns: { size: "Storlek", nominal: "Nominellt", family: "Gäller för" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Konfigurera med din greppstorlek",
  },
  custom: {
    title: "Specialkonstruktion",
    statement: "Konstruerad enligt specifikation.",
    sub: "Standardsortimentet är utgångspunkten.",
    lead: "MAXIMUS tar emot tekniska krav utanför de publicerade konfigurationsmatriserna för bedömning, konstruktion, validering och tillverkning enligt avtalad specifikation. Genomförbarheten bekräftas genom granskning — varje tänkbar förfrågan är inte fysiskt eller kommersiellt genomförbar.",
    scopeTitle: "Detta kan ett tekniskt underlag omfatta",
    scope: ["Geometri för huvud och ram", "Längd", "Vikt", "Balans", "Swingweight", "Styvhet", "Twistweight", "Greppgeometri", "Konstruktion", "Matchade uppsättningar", "Träningsramar", "Dekor och gravyr", "Identitets- och lagprogram", "Verktygsberoende utveckling"],
    processTitle: "Process",
    process: [
      ["Definiera", "Önskade målvärden, obligatoriska gränser, avsedd användning och godtagbara avvägningar."],
      ["Konstruera", "Teknisk bedömning mot plattformen och verktygen."],
      ["Validera", "Validering mot den avtalade specifikationen."],
      ["Specificera", "En skriftlig specifikation med mätunderlag och toleranser."],
      ["Tillverka", "Tillverkning enligt specifikationen."],
      ["Mät / dokumentera", "Mätning och bevarad dokumentation enligt tillämplig precisionsklass."],
    ],
    formTitle: "Skicka ett tekniskt underlag",
    formLead: "Skilj önskade målvärden från obligatoriska gränser. Resultatet är en begäran om teknisk granskning, inte en automatiskt accepterad tillverkningsorder.",
    protected: "Laminatuppbyggnader, verktyg, leverantörers identitet, intern kalkylering och skyddat kunnande lämnas inte ut via den här vägen.",
    cta: "Skicka ett tekniskt underlag",
  },
  training: {
    title: "Träningssystem",
    lead: "Två träningsfamiljer med egna produktionsstandarder, förenade av en metodik: tränarledd träning, dokumentation, ny utvärdering och överföring tillbaka till tävlingsspel.",
    sst: { h: "Sweet Spot Trainer", p: "En träningsracket med förminskat huvud på 50 in² i ett system med fyra vikter för övning av centrerad träff, känsla för sweet spot, racketkontroll och stegvis belastning." },
    spot: { h: "Spot Trainer", p: "Träning av träffpunkten med en liten rund träffyta, på den godkända grunden med fyra vikter." },
    method: { h: "Metodik", p: "Sätt mål, välj utrustning med tränarens medverkan, använd relevant system, dokumentera, utvärdera på nytt, justera och överför." },
    experience: "Håll den. Svinga den. Känn den.",
    experienceP: "Begär provspel, anpassning eller en visning med tränarstöd. En inskickad förfrågan är inte en bekräftad bokning.",
    cta: "Begär anpassning eller visning",
    distinct: "Sweet Spot Trainer, Spot Trainer och varje separat demonstrationsenhet är skilda produkter och sammanblandas aldrig.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "En egen träningskategori med sin egen produktionsstandard. Huvudet på 50 in² riktar uppmärksamheten mot var träffen sker; de fyra vikterna ger belastningstrappan.",
    baseline: "Bekräftad grund",
    columns: { head: "Huvud", length: "Längd", pattern: "Strängmönster", grips: "Grepp från fabrik" },
    systemTitle: "System med fyra racketar",
    detailsTitle: "Konstruktionsdetaljer",
    systemLead: "Vikt och balans som levererade. Mätunderlaget dokumenteras separat och är ännu inte publicerat.",
    purposeTitle: "Syfte",
    purpose: ["Övning av centrerad träff", "Känsla för sweet spot", "Racketkontroll", "Stegvis belastning", "Tränarledd utveckling", "Övergång tillbaka till spelarens prestationsracket"],
    heavy: "Modellen på 400 g är en styrd träningskonfiguration. Den rekommenderas inte automatiskt till barn, nybörjare eller varje spelare; tränaren bestämmer belastning, längd och progression.",
    precisionNote: "Prestationsklasserna P2.5, P1.5 och P0.5 tillämpas inte automatiskt på den här träningsfamiljen. Toleranserna i träningsproduktionen följer familjens egen godkända specifikation.",
    health: "Inget förebyggande eller behandling av tennisarmbåge, ingen eliminering av skador och ingen garanterad förbättring utlovas.",
    cta: "Begär en visning av Sweet Spot Trainer",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Träning av träffpunkten med en liten rund träffyta. En egen produkt med sin egen visuella identitet, byggd på den godkända grunden med fyra vikter.",
    purposeTitle: "Bekräftat syfte",
    purposeP: "Att träna spelaren att hitta och upprepa en exakt träffpunkt.",
    weightsTitle: "Vikttrappa",
    weightsP: "Vikttrappan följer den godkända viktgrunden för Sweet Spot Trainer. Balansvärden och övriga specifikationer för Sweet Spot Trainer kopieras inte över till Spot Trainer.",
    dims: "Exakta mått på träffytan är ännu inte publicerade.",
    grips: "Greppstorlekar från fabrik L0–L7.",
    notes: ["Prestationsklasserna för precision tillämpas inte automatiskt.", "Den är inte en miniatyr av en vanlig racket och inget strängmönster publiceras.", "Spot Trainer, Sweet Spot Trainer och varje separat demonstrationsenhet går att skilja åt."],
    cta: "Fråga om Spot Trainer",
  },
  methodology: {
    title: "Metodik och produktupplevelse",
    lead: "Utrustningen är en del av en strukturerad utvecklingsresa. Metoden börjar med spelarens mål, inte med en produktbeteckning.",
    stepsTitle: "Utvecklingsresan",
    steps: [
      ["Sätt mål", "Spelarens mål och utgångsläge."],
      ["Välj utrustning", "Lämplig utrustning som väljs med tränarens medverkan."],
      ["Använd systemet", "Det relevanta träningssystemet, tränarlett."],
      ["Dokumentera", "Iakttagelser av faktiskt deltagande, utan påhittade resultat."],
      ["Utvärdera på nytt", "Jämförbara avstämningspunkter."],
      ["Justera", "Justeringar av konfiguration eller program."],
      ["Överför", "Lärandet överförs tillbaka till tävlingsspel."],
    ],
    educationTitle: "Utbildningsvägar",
    education: { player: "Spelare — förstå konfiguration, belastning och progression.", parent: "Föräldrar — kontinuitet i utvecklingen, lämplig utrustning, dokumentation och rättigheter.", coach: "Tränare — träningssystem, anpassning, bedömning och behörig användning av program." },
    evidenceTitle: "Disciplin i underlaget",
    evidenceP: "Dokumentation av faktiskt deltagande och iakttagelser bevaras med sin klassificering — uppgiven av deltagaren, bekräftad av vårdnadshavare, validerad av tränare eller uppmätt av systemet. Utveckling, resultat och validering hittas aldrig på.",
    experienceTitle: "Håll den. Svinga den. Känn den.",
    experienceP: "Provspel, anpassning eller en visning med tränarstöd kan begäras. En inskickad förfrågan är inte en bekräftad bokning.",
    cta: "Begär anpassning eller visning",
    cta2: "Förfrågan om tränarpartnerskap",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — vägledd utrustningsprofil",
    title: "MAXIMUS GPS",
    lead: "En vägledd utrustningsprofil. Svara bara på det som är relevant; granska och rätta dina svar; få en sammanfattning, de konfigurationsriktningar som gäller och en verklig nästa åtgärd.",
    honesty: "I den här versionen finns inga godkända automatiska anpassningsregler. GPS tar därför fram en tydlig sammanfattning av kraven och pekar ut konfigurationsriktningar; detaljerna om utrustningen går vidare till expertgranskning.",
    rulesVersion: "Regelversion",
    dataVersion: "Version av produktdata",
    steps: { role: "Roll", sport: "Sport", experience: "Erfarenhet", objectives: "Mål", style: "Spelstil", equipment: "Nuvarande utrustning", preference: "Önskemål", coach: "Tränarens medverkan", ageBand: "Åldersgrupp", review: "Granska" },
    notStored: "Lagras inte i den här webbläsaren.",
    ageNote: "Används bara för att styra förfrågan rätt. Inget namn, födelsedatum eller någon medicinsk uppgift efterfrågas.",
    q: {
      role: "Vad passar in på dig?",
      sport: "Vilken sport?",
      experience: "Erfarenhetsnivå",
      objectives: "Vad är viktigast? (välj upp till tre)",
      style: "Spelstil, om du känner till den",
      equipment: "Nuvarande utrustning, om du har någon",
      equipmentHint: "Märke och modell, vikt eller grepp om du vet dem. Valfritt.",
      preference: "Önskad konfiguration eller känd greppstorlek",
      grip: "Känd greppstorlek",
      coach: "Är en tränare med i dina beslut om utrustning?",
      ageBand: "Spelarens åldersgrupp (används bara för att styra förfrågan rätt)",
    },
    roles: { player: "Spelare", parent: "Förälder eller vårdnadshavare", coach: "Tränare", club: "Klubb eller akademi", other: "Annat" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Annan racketsport" },
    sportNote: "Det finns produkter för tennis. Övriga sporter är utvecklingsriktningar; ditt intresse dokumenteras för rätt program.",
    experience: { beginner: "Nybörjare", developing: "Utvecklingsnivå", intermediate: "Medelnivå", advanced: "Avancerad", competitive: "Tävlingsnivå", professional: "Professionell" },
    objectives: { control: "Kontroll", power: "Kraft", spin: "Skruv", comfort: "Komfort", manoeuvrability: "Manövrerbarhet", development: "Långsiktig utveckling", competition: "Tävling", training: "Träningssystem", team: "Lag eller matchad uppsättning", personal: "Personalisering" },
    styles: { baseline: "Grundlinjespel", allcourt: "Allcourtspel", attacking: "Offensivt spel", defensive: "Defensivt spel", coach: "Tränarens val", unknown: "Osäker" },
    ageBands: { u10: "Under 10", u14: "10–13", u18: "14–17", adult: "18 och äldre" },
    output: {
      title: "Din utrustningsprofil",
      status: "Expertgranskning krävs",
      statusP: "Ingen automatisk matchning tas fram i den här versionen. Din profil har sammanfattats för expertgranskning.",
      directionsTitle: "Konfigurationsriktningar som gäller",
      directionsP: "Utifrån de mål du angett och varje series deklarerade spelriktning. Detta är en riktning, inte en anpassningsrekommendation.",
      trainingHint: "Dina mål omfattar ett träningssystem: se Sweet Spot Trainer och Spot Trainer.",
      teamHint: "Matchade uppsättningar begärs via konfiguratorn och bekräftas skriftligt.",
      next1: "Skicka profilen till expertgranskning",
      show: "Visa min profil",
      configure: "Konfigurera",
      sendP: "Skicka din profil till MAXIMUS för expertgranskning. Ett ärendenummer visas direkt; svaret kommer skriftligt.",
      otherSport: "MAXIMUS-racketar finns för tennis. För andra racketsporter föreslås ingen tennisserie; ditt intresse dokumenteras som en utvecklingsriktning.",
      noDirection: "Dina mål pekar inte mot en enda spelriktning. Expertgranskningen föreslår en konfiguration.",
      incomplete: "Några obligatoriska svar saknas — använd ”Ändra svar” för att fylla i dem.",
    },
    privacy: "GPS frågar inte efter några hälsouppgifter och inga uppgifter som identifierar barn. Bara svaren på flervalsfrågorna sparas i den här webbläsarsessionen; fritext lagras inte.",
  },
  build: {
    title: "Bygg din racket",
    lead: "Konfigurera en förfrågan: serie, precisionsklass, listad vikt eller eget målvärde, greppstorlek, önskade målvärden, personalisering, matchade uppsättningar och antal. Resultatet är en konfigurationsförfrågan med ett ärendenummer — inte ett artikelnummer, pris, leveransdatum eller certifikat.",
    steps: { series: "Serie", cls: "Precisionsklass", weight: "Vikt", grip: "Grepp", targets: "Målvärden", personal: "Personalisering", set: "Uppsättning och antal", use: "Användning", review: "Granska" },
    q: {
      series: "Välj en serie",
      cls: "Välj en precisionsklass",
      weightMode: "Vikt",
      listed: "Listad vikt",
      customWeight: "Önskad vikt (g)",
      balanceShown: "Beräknad balans för den här vikten",
      balanceRequest: "Önskad balans (mm)",
      grip: "Greppstorlek från fabrik",
      targetsTitle: "Önskade målvärden",
      swingweight: "Önskad swingweight (kg·cm²)",
      stiffness: "Önskad styvhet (RA)",
      basis: "Mätunderlag för önskade värden",
      engraving: "Gravyrtext",
      engravingHint: "Namn, initialer eller nummer. Latinska bokstäver, siffror, mellanslag, bindestreck, apostrof och punkt; upp till 24 tecken. Andra skriftsystem tas emot för bekräftelse av grafiskt original.",
      engravingType: "Personalisering",
      types: { none: "Ingen", name: "Spelarens namn", initials: "Initialer", number: "Nummer i uppsättningen", academy: "Märkning för tränare eller akademi", team: "Lagprogram" },
      set: "Enskild racket eller matchad uppsättning",
      use: "Avsedd användning",
      uses: { play: "Eget spel", competition: "Tävling", coaching: "Träningsverksamhet", team: "Lag eller akademi", retail: "Utvärdering för handel eller distribution", other: "Annat" },
      notes: "Ytterligare tekniska krav",
    },
    classes: { "P2.5": "P2.5 — skalbar prestationskärna", "P1.5": "P1.5 — avancerad precision", "P0.5": "P0.5 — professionell, individuellt kontrollerad" },
    stiffExactShort: "styvheten uppfyller det deklarerade mål-RA-värdet enligt fabrikens fastställda protokoll",
    clsNote: "Varje klass styr fyra parametrar. P0.5 är en snäv tolerans under ett definierat mätprotokoll — inte noll avvikelse. Serieidentitet, certifikat och dokumentation för matchade uppsättningar gäller bara där programmet för din order omfattar dem.",
    listedNote: "Ur seriens bekräftade matris.",
    customNote: "En vikt utanför matrisen, som granskas tekniskt.",
    balanceCaption: "Varje listad vikt visar sin beräknade balans i mm från greppändan. Beräknade värden är inte individuella mätningar.",
    spinNote: "SPIN-vikterna utgör den önskade viktarkitekturen. Balans, swingweight och styvhet för SPIN anges inte; de fastställs vid teknisk granskning.",
    customHint: "Hela gram, bara siffror. En egen vikt är en begäran om teknisk granskning; genomförbarheten bekräftas skriftligt och inget värde avrundas.",
    gripNote: "greppgeometri i kolfiber från fabrik, ingen uppbyggnad med overgrip",
    targetsLead: "Valfritt. Ange bara de värden du behöver. Varje värde registreras som ett önskat målvärde för teknisk granskning, inte som en publicerad specifikation.",
    basisHint: "Obligatoriskt när du begär en egen vikt eller något målvärde: gäller värdena en osträngad eller en strängad racket?",
    inputRange: "Tillåten inmatning: {min}–{max}.",
    inputRangeNote: "Inmatningsintervallen filtrerar bara bort omöjliga värden. De beskriver inte tillverkningskapaciteten.",
    listedBasis: "listade värden — mätunderlaget bekräftas i den skriftliga specifikationen",
    notStored: "Lagras inte i den här webbläsaren; ange den igen om du laddar om sidan.",
    artworkReview: "kräver bekräftelse av grafiskt original",
    previewNote: "Ingen visuell förhandsvisning visas: en godkänd gravyrmall för den här modellen är ännu inte publicerad. Din text samlas in för bekräftelse av grafiskt original.",
    teamSub: "4–99 racketar per sats",
    setsLabel: { individual: "Antal racketar", pair: "Antal matchade par", triple: "Antal matchade trior", team: "Antal lagsatser" },
    teamSizeLabel: "Racketar per lagsats",
    totalLabel: "Racketar totalt",
    racquetsUnit: "racketar",
    setRule: "Antalet räknas i satser: ett matchat par är 2 racketar per sats, en matchad trio 3.",
    restart: "Börja en ny konfiguration",
    notices: { weightCleared: "{w} g finns inte i matrisen för {series}, därför nollställdes vikten. Välj en listad vikt eller begär ett eget målvärde." },
    reviewTitle: "Konfigurationsförfrågan",
    reviewP: "Kontrollera konfigurationen och lägg sedan till dina kontaktuppgifter. Förfrågan sparas med ett ärendenummer och besvaras skriftligt; tillgänglighet och kommersiella villkor bekräftas skriftligt.",
    reviewErrors: "Några svar i konfigurationen behöver ses över:",
    edit: "Ändra",
    fieldNames: { series: "Serie", cls: "Precisionsklass", mode: "Viktval", weight: "Listad vikt", customWeight: "Önskad vikt", basis: "Mätunderlag", balanceReq: "Önskad balans", sw: "Önskad swingweight", ra: "Önskad styvhet", grip: "Greppstorlek", ptype: "Personalisering", engraving: "Gravyrtext", setType: "Typ av uppsättning", sets: "Antal", teamSize: "Racketar per lagsats", use: "Avsedd användning", notes: "Ytterligare krav" },
    status: { listed: "listad vikt", requestedArchitecture: "önskad viktarkitektur", technicalReview: "begäran om teknisk granskning", notPublished: "ej angivet", requestedCondition: "önskat tillstånd" },
    chooseLink: "Osäker på vilken serie som passar? Få hjälp att välja",
    cta: "Skicka konfigurationsförfrågan",
  },
  experience: {
    title: "Prova och anpassa",
    statement: "Håll den. Svinga den. Känn den.",
    lead: "Begär provspel, anpassning eller en visning med tränarstöd. Förfrågningar granskas och besvaras skriftligt; en inskickad förfrågan är inte en bekräftad bokning.",
    optionsTitle: "Detta kan begäras",
    options: ["Provspel med racket", "Anpassningstillfälle", "Visning med tränarstöd", "Visning av Sweet Spot Trainer eller Spot Trainer", "Prova-på-dag för lag eller akademi"],
    formTitle: "Förfrågan om anpassning eller visning",
  },
  engineering: {
    title: "Konstruktion och tillverkning",
    statement: "Flygplan. Yachter. Racketar.",
    lead: "En teknisk filosofi i tre miljöer: principerna som formar ett flygplan, precisionen som styr en yacht över öppet vatten, prestationen som definierar varje MAXIMUS-racket. En teknisk berättelse — inte ett påstående om flygcertifiering, yachtägande, fabriksägande eller direkt materialöverföring.",
    manifesto: ["Vi tror att stor ingenjörskonst inte har några gränser.", "En filosofi. Konstruerad utan kompromisser."],
    capabilityTitle: "Tillverkningsförmåga",
    capabilityLead: "Förmågan visas som ett förlopp, inte som en slogan.",
    sequence: [
      ["Specifikation", "Serie, precisionsklass, vikt, balans, swingweight, styvhetsmål, greppgeometri, personalisering."],
      ["Tillverkning", "Konstruktion i helkolfiber från ram till handtag, tillverkad enligt specifikationen."],
      ["Kvalitetskontroll", "Mätning och dokumentation enligt precisionsklass: tillverkningsdokumentation, individuell dokumentation och spårbarhet, individuell certifiering."],
      ["Upprepad tillverkning", "Repeterbart svar mot en deklarerad specifikation över flera batcher."],
      ["Spårbarhet", "Serieidentitet, batchspårbarhet och ett precisionscertifikat där klassen omfattar det."],
    ],
    capacityNote: "Produktionskapacitet, ledtider, minimikvantiteter och leveransplaner bekräftas skriftligt per program mot bekräftade order och en avtalad frisläppningsplan.",
    truth: "Kapacitet är inte produktion, lager, ett garanterat leveransdatum eller ägande av en tillverkningsanläggning.",
    cta: "Distribution och marknadsutveckling",
    cta2: "Skicka ett tekniskt underlag",
  },
  ecosystem: {
    title: "MAXIMUS-ekosystemet",
    lead: "En nyckel. Detta är vad den öppnar. Varje nod har en förklaring, en korrekt status och en relevant nästa åtgärd.",
    words: ["Konstruktion", "Prestation", "Innovation", "Gemenskap", "Möjlighet", "Syfte"],
    nodes: {
      engineering: { h: "Konstruktion och tillverkning av racketar", p: "Racketar i helkolfiber konstruerade enligt specifikation, tillverkade med kvalitetsdokumentation och spårbarhet.", a: "Konstruktion och tillverkning" },
      precision: { h: "Precision och individuell konfiguration", p: "Fyra parametrar, tre precisionsklasser, åtta greppstorlekar och specialkonstruktion.", a: "Precision och styvhet" },
      training: { h: "Träning och metodik", p: "Sweet Spot Trainer, Spot Trainer och en strukturerad utvecklingsresa.", a: "Träningssystem" },
      development: { h: "Utveckling av spelare och tränare", p: "Tränarlett urval, dokumentation, ny utvärdering och utbildningsvägar.", a: "Metodik" },
      identity: { h: "Personlig identitet och personliga varumärken", p: "Från gravyr till ett personligt eller professionellt varumärke som styrs av rättigheter.", a: "Personliga varumärken" },
      owners: { h: "Ägardokumentation, kunnande och rättigheter", p: "Ett föreslaget behörighetsstyrt ägararkiv för dokumentation av utrustning, utveckling och rättigheter.", a: "Ägare och arkivet" },
      mipa: { h: "MIPA-proveniens och intern kontroll", p: "Det interna skiktet för immateriella rättigheter, proveniens och dokumentkontroll.", a: "Juridisk identitet och kontroll" },
      digital: { h: "Digital infrastruktur och riktningen Blockchain 5.0", p: "Proveniens, spårbar dokumentation, behörighetsstyrt underlag och produktidentitet som den angivna tekniska riktningen.", a: "Teknisk riktning" },
      licensing: { h: "Avtalsbaserad licensiering och royaltyprogram", p: "Licensierade varumärken, produkter och rättighetspaket med villkor som definieras per avtal.", a: "Licensvägar" },
      families: { h: "Familjens medverkan och programförmåner", p: "Välgrundade beslut, kontinuitet, bevarad dokumentation och förmåner som definieras av programmet.", a: "Familjer och föräldrar" },
      network: { h: "MAXIMUS Sports Network", p: "Spelare, tränare, klubbar, akademier, tjänsteleverantörer, operatörer och regionala partner.", a: "Sports Network" },
      market: { h: "Klubbar, akademier, distribution och marknadsutveckling", p: "Lagprogram, handel, distribution och territoriell utveckling genom skriftlig kvalificering.", a: "Partnerskapsvägar" },
      institutional: { h: "Institutionella program, utbildning, innovation och samhällsnytta", p: "Det institutionella skiktet som tillhandahålls av MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) där ett program fastställer den rollen.", a: "Institutionella program" },
      extensions: { h: "Framtida racketsporter och MAXIMUS-kläder", p: "Padel, pickleball, squash, badminton, racquetball, beachtennis och kläder som utvecklingsriktningar.", a: "Racketsporter" },
    },
    boundaryTitle: "Gränser",
    boundary: [
      "Köpet av en racket ger inte institutionellt medlemskap, rättigheter i styrningen, royalty eller investeringsrättigheter.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) är institutionell operatör bara där ett program fastställer den rollen; vid försäljning av utrustning anges den faktiska avtalsparten.",
      "Bidrag, status som allmännyttig, skattemässig behandling och myndighetstillstånd gäller inte automatiskt i alla länder.",
    ],
    techTitle: "Teknisk riktning",
    techP: "Blockchain 5.0 är MAXIMUS angivna tekniska riktning. Dess funktionella syften är proveniens, spårbar dokumentation, behörighetsstyrt underlag, produktidentitet och avstämning av kvalificerande kommersiella händelser. Ingen konsensusmekanism, transaktionskapacitet, nodnätverk, adress för smarta kontrakt, token eller oberoende certifiering utlovas, och ingen driftsatt implementation påstås finnas. Personuppgifter, dokumentation om barn och konfidentiella avtal placeras aldrig som standard i ett offentligt oföränderligt system.",
  },
  brands: {
    title: "Personliga varumärken och ambassadörer",
    statement: "Från spelare till varumärke. Från tränare till varumärke.",
    lead: "En egen väg för personliga varumärken. MAXIMUS medverkan omfattar varumärkesutveckling och avtalad marknadsföring — inte bara ett namn på en racket.",
    progressionTitle: "Avsedd utveckling",
    progression: [
      ["Verifierad identitet", "En verifierad identitet och utvecklingshistorik."],
      ["Eget varumärke", "Ett särskiljande personligt eller professionellt varumärke."],
      ["Rättighetsklarerat innehåll", "Rättighetsklarerat innehåll och godkänd produktidentitet."],
      ["Konstruktion och kollektioner", "Konstruktion och kollektionsutveckling där det avtalas."],
      ["Marknadsföring", "Marknadsföring via avtalade MAXIMUS-kanaler och partnerskap."],
      ["Deltagande", "Avtalsbaserat deltagande i kvalificerande försäljning eller licensiering."],
      ["Rapportering", "Transparent rapportering enligt avtalet."],
    ],
    royaltiesTitle: "Royalty och licensiering",
    royalties: [
      "Royalty knyts till det definierade licensierade varumärket, produkten, transaktionen eller rättighetspaketet.",
      "”Försäljning i hela världen” betyder kvalificerande försäljning inom avtalets omfattning — aldrig varje MAXIMUS-racket utan koppling till avtalet.",
      "Satser, beräkningsunderlag, territorier, löptid, återbetalningar, avdrag, rapportering, reglering och verifiering definieras genom respektive avtal. Ingen standardsats för royalty publiceras.",
      "Ingen global kampanj, mediebudget, sponsringseffekt eller kommersiell framgång utlovas utan avtalad omfattning.",
    ],
    cta: "Skicka en förfrågan om varumärkessamarbete",
    cta2: "Förfrågan om tränarpartnerskap",
  },
  families: {
    title: "Familjer och föräldrar",
    lead: "Välgrundade beslut om utrustning, kontinuitet i utvecklingen, bevarat kunnande och bevarade rättigheter, insyn i deltagandet och förmåner som definieras av programmet och kan stödja framtida verksamhet.",
    nowTitle: "Tillgängligt nu",
    now: ["Förfrågningar om familj och utveckling, skriftligt.", "Val av utrustning med tränarens medverkan, anpassning och förfrågningar om visning.", "Privat dokumentation: barns profiler publiceras aldrig och används som standard aldrig kommersiellt.", "Utbildningsväg för föräldrar: konfiguration, belastning, progression, dokumentation och rättigheter."],
    plannedTitle: "Planerat",
    planned: ["Programdefinierade förmåner för deltagande som kan användas till varor och tjänster inom ekosystemet, i stället för kontant ränta.", "Dokumentation om ägare och familj i det föreslagna ägararkivet med behörigheter för vårdnadshavare och överföring av kontrollen vid 18 års ålder."],
    categoriesTitle: "Hålls åtskilt",
    categories: ["Avtalsbaserad royalty från licensierade rättigheter eller kvalificerande försäljning", "Förmåner för deltagande som definieras av ett program", "Tillgodohavanden för köp eller tjänster", "Förskottsbetalningar", "Institutionellt medlemskap"],
    categoriesP: "De här kategorierna behandlas aldrig som utbytbara.",
    statusTitle: "Familjeprogrammets faktiska status",
    journeyTitle: "Familjevägen",
    journey: [
      ["Mål", "Vad spelaren vill uppnå härnäst."],
      ["Nuvarande nivå", "Var spelaren står i dag."],
      ["Tränare", "Om en tränare medverkar i besluten om utrustning."],
      ["Utrustning", "Lämplig utrustning för stadiet, inklusive träningssystem där det är relevant."],
      ["Avtalad träning", "Tränarledd användning som avtalas i förväg."],
      ["Uppföljning", "Ny utvärdering vid jämförbara avstämningspunkter."],
    ],
    brief: {
      who: "Föräldrar och vårdnadshavare till spelare på alla nivåer.",
      value: "Ett skriftligt svar om lämplig utrustning, tränarens medverkan och nästa steg i utvecklingen.",
      now: "Familjeförfrågningar skriftligt; val med tränarens medverkan; privat dokumentation — barns profiler publiceras aldrig.",
      next: "Skicka familjeförfrågan nedan. Du får ett ärendenummer direkt.",
    },
    formTitle: "Familjeförfrågan",
    formNote: "Ska fyllas i av en förälder eller vårdnadshavare. Ange inte barnets namn, födelsedatum, skola eller medicinska uppgifter.",
    noPromise: "Ett köp utlovar ingen royalty, avkastning på investering, sponsring eller finansiering av ett barns utveckling.",
    statusP: "Den här versionen förklarar modellen och tar emot förfrågningar om programmet. Uppbyggnad, utbetalningar och inlösen är inte tillgängliga förrän de kvalificerande händelserna, förmånstagarna, finansieringskällan, beräkningsunderlaget, tillåten användning, den redovisningsmässiga behandlingen, återbetalningar, återföringar, giltighetstid, överlåtbarhet, programmets avslutande och hanteringen av tvister är definierade skriftligt. Inget tillgodohavande utlovas att aldrig minska, inget deltagande betalar för all träning och inget kapitalskydd antyds.",
    cta: "Skicka en familje- eller utvecklingsförfrågan",
  },
  owners: {
    title: "Ägare och ägararkivet",
    lead: "Ägararkivet är en föreslagen behörighetsstyrd dokumentation av utrustning, utveckling, kunnande, innehåll och dokumenterade rättigheter. Det presenteras som en del av den planerade ägararkitekturen: inga aktiva konton, tillgodohavanden, certifikat eller prestationer visas.",
    nowTitle: "För nuvarande ägare i dag",
    now: ["Ägarförfrågningar: produkt- eller serienummer, inställning, service och begäran om dokumentation, skriftligt.", "Precisionscertifikat och dokumentation för matchade uppsättningar där precisionsklassen omfattar det, levererat med produkten."],
    archTitle: "Planerad arkitektur för arkivet",
    arch: ["Produktidentitet och serienummer", "Konfiguration och tillämpliga kvalitetscertifikat", "Historik för service och inställning", "Utvecklingsdokumentation för spelare eller tränare", "Kvalifikationer och verifierade prestationer", "Rättighetsklarerade medier och eget material", "Licenser, tillstånd och avtalsreferenser", "Dokumentation i programmet för personliga varumärken", "Tillämpliga royaltyredovisningar eller förmåner för deltagande"],
    separationTitle: "Vad ägandet innebär",
    separation: [
      "Ägandet av en fysisk racket är skilt från ägandet av upphovsrätt, en licens, en avtalsrätt eller av dokumentation som beskriver dessa saker.",
      "Ett lagrat dokument eller en blockkedjepost är inte automatiskt bevis för att en juridisk rättighet finns eller har överlåtits.",
      "Underlaget behåller sin klassificering: uppgivet av deltagaren, bekräftat av vårdnadshavare, validerat av tränare, uppmätt av systemet.",
      "För minderåriga: privat dokumentation, behörigheter för vårdnadshavare, inga publicerade barnprofiler och ingen kommersiell användning av identiteten som standard.",
      "Export, rättelse, åtkomstkontroll och en ändamålsenlig överföring av kontrollen ingår i designen.",
    ],
    techTitle: "Blockchain 5.0 och MxSN",
    techP: "Blockchain 5.0 är den angivna tekniska riktningen; MxSN definierar begreppen för ett behörighetsstyrt nätverk för samtycke, leverans, underlag, rättigheter och rapportering. Ingen operativ implementation utlovas. Applikationens datamodell är byggd för att integreras senare via ett dokumenterat gränssnitt, utan att låta påskina att en koppling finns i dag.",
    cta: "Ägarförfrågan",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Kopplingen mellan spelare, tränare, klubbar, akademier, tjänsteleverantörer, programoperatörer och regionala partner.",
    functionsTitle: "Möjliga funktioner",
    functions: ["Sökbarhet", "Introduktioner", "Utvecklingsprogram", "Stöd med utrustning", "Evenemang", "Tillgång till tjänster", "Partnermöjligheter"],
    statusTitle: "Faktisk status",
    statusP: "Ingen offentlig katalog är publicerad ännu: bara deltagare vars identitet, relation och tillstånd att visas är fastställda kommer att listas. Ett förslag som skickats till en klubb är inget partnerskap, och en tänkbar distributör är ingen utsedd distributör. Publicering av katalogen, bokning, meddelanden och kommersiella transaktioner styrs separat och är inte i drift.",
    cta: "Ansök till nätverket",
  },
  partnerships: {
    title: "Partnerskapsvägar",
    lead: "Skriftlig kvalificering först. Varje väg leder till en förfrågan för din roll; kommersiella villkor följer skriftligt.",
    commercialTitle: "Plattformens möjliga kommersiella verksamheter",
    commercial: ["Utrustning", "Specialkonstruktion", "Personalisering", "Program för lag och akademier", "Träningssystem", "Avtalsbaserad licensiering", "Distribution", "Godkända tjänster", "Framtida produktkategorier"],
    boundary: "Landsrättigheter, exklusivitet, territorieavgifter och distributörsmarginaler är förhandlade villkor. Ingen omsättning, prognos, värdering, marknadsandel, avkastning, finansieringsutfästelse eller onämnt partnerskap publiceras.",
    routes: {
      coaches: {
        title: "Tränare",
        lead: "Träningssystem, anpassning, professionell identitet, behöriga program, möjligheter för ett personligt varumärke och leverans av utrustning.",
        points: ["Sweet Spot Trainer och Spot Trainer i tränarledd träning.", "Anpassning med konfigurationsmatriserna och åtta greppstorlekar från fabrik.", "Coach-to-Brand: en verifierad professionell profil och ett rättighetsstyrt undervarumärke.", "Behörig användning av program följer ett skriftligt avtal."],
        cta: "Skicka en förfrågan om tränarpartnerskap",
        brief: {
          who: "Fristående tränare och tränarteam.",
          value: "Träningssystem för tränarledd träning, anpassning med seriernas matriser och åtta greppstorlekar från fabrik, samt en väg till en professionell identitet.",
          now: "Tränarförfrågningar skriftligt. Ingen provision, ersättning eller förmedlingssats publiceras eller antyds.",
          next: "Skicka tränarförfrågan nedan. Villkoren följer skriftligt.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klubbar och akademier",
        lead: "Lagutrustning, träningssystem, personalisering, utvecklingsprogram, service och deltagande i nätverket.",
        points: ["Lagsatser och matchade uppsättningar begärs via konfiguratorn.", "Träningssystem och metodik för strukturerad utveckling.", "Personalisering för lagprogram på godkända zoner.", "Prova-på-dagar, anpassningstillfällen och deltagande i nätverket."],
        cta: "Skicka ett underlag för klubb eller akademi",
        brief: {
          who: "Klubbar, akademier och lagprogram.",
          value: "Lagsatser och matchade uppsättningar, träningssystem, personalisering för lagprogram och prova-på-dagar.",
          now: "Underlag från klubbar och akademier skriftligt; lagsatser begärs via konfiguratorn.",
          next: "Skicka underlaget för klubb eller akademi nedan.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribution och marknadsutveckling",
        lead: "Sortiment, samordning av tillverkning, teknisk förmåga, territoriell utveckling och konfidentiell kommersiell kvalificering.",
        points: ["Skriftlig kvalificering av motparten, territoriet och kanalen.", "Sortiment som definieras utifrån konfigurationsmatriserna och precisionsklasserna.", "Territorium, exklusivitet, volymer, prissättning och kommersiellt skydd är förhandlade villkor som avtalas skriftligt.", "Avtalspart, betalningsvillkor och leveransvillkor fastställs per transaktion."],
        cta: "Skicka en förfrågan om distribution eller marknadsutveckling",
        brief: {
          who: "Återförsäljare, distributörer och landspartner.",
          value: "Ett sortiment som definieras utifrån de bekräftade matriserna, precisionsklasserna och greppsortimentet, med skriftlig kvalificering av territorium och kanal.",
          now: "Distributionsförfrågningar skriftligt. Territorium, exklusivitet, volymer och prissättning förhandlas — inget ges via ett formulär.",
          next: "Skicka distributionsförfrågan nedan.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategi och investering",
        lead: "Teknisk förmåga, konfigurationsdjup, tillverkningsmodell, vägar till marknaden, immateriella rättigheter, tjänster och expansionsmöjligheter.",
        points: ["Kvalificerade strategiska samtal eller styrd tillgång till information följer efter skriftlig kvalificering.", "Offentlig information är begränsad till godkända produktspecifikationer, konfigurationsarkitektur, verifierade förmågor och förklaringar av program.", "Köparspecifik ekonomi, kalkylering, skyddad metodik och opublicerade avtal lämnas ut endast under sekretessavtal eller avtal."],
        cta: "Begär ett kvalificerat strategiskt samtal",
        brief: {
          who: "Investerare och strategiska partner.",
          value: "Ett kvalificerat samtal om teknisk förmåga, konfigurationsdjup, tillverkningsmodell, vägar till marknaden och immateriella rättigheter.",
          now: "Inga finansiella siffror, prognoser, värderingar eller avkastningstal publiceras. Styrd information följer efter skriftlig kvalificering och sekretessavtal.",
          next: "Begär ett kvalificerat strategiskt samtal nedan.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institutionella program",
        lead: "Utbildning, tillgång, innovation, underlag om utveckling, samhällsnytta och ändamålsenligt strukturerade program.",
        points: ["Institutionella program struktureras genom MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) där programmet fastställer den rollen.", "Öronmärkta programmedel och kommersiella transaktioner hålls åtskilda.", "En förfrågan är ingen godkänd medlemsansökan, och en köpare av utrustning är ingen institutionell medlem.", "Bidrag, status som allmännyttig, skattemässig behandling och myndighetstillstånd är landsspecifika och förutsätts aldrig."],
        cta: "Skicka en förfrågan om institutionellt program",
        brief: {
          who: "Institutioner samt utbildnings- och utvecklingsprogram.",
          value: "Program för utbildning, tillgång, innovation och underlag om utveckling, strukturerade med rätt operatör.",
          now: "Institutionella förfrågningar skriftligt. En förfrågan är ingen medlemsansökan; ett köp av utrustning är inget institutionellt medlemskap.",
          next: "Skicka den institutionella förfrågan nedan.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Offentligt och styrt utlämnande",
    disclosure: {
      public: { h: "Offentligt", p: "Godkända produktspecifikationer, konstruktion, konfigurationsarkitektur, träningssyften, verifierade förmågor, förklaringar av program och partnerskapsvägar." },
      qualified: { h: "Kvalificerad förfrågan", p: "Tekniska krav, kvantiteter, intresse för territorium, utvecklingens omfattning och relevanta kommersiella samtal." },
      controlled: { h: "Styrt av sekretessavtal eller avtal", p: "Interna formler, detaljerade kvalitetsprotokoll, laminatuppbyggnader, verktyg, tillverkningsmetoder, leverantörers identitet, kalkylering, köparspecifik ekonomi, skyddad metodik, opublicerade avtal och känslig dokumentation om rättigheter." },
    },
  },
  contact: {
    title: "Kontakt och förfrågningar",
    lead: "Välj syftet med din förfrågan. Varje formulär samlar bara in det som behövs för att styra och bedöma den. Förfrågningar besvaras skriftligt.",
    email: "E-post",
    instagram: "Instagram",
    legalLink: "Juridisk identitet",
  },
  form: {
    purposeLabel: "Syftet med förfrågan",
    purposes: {
      selection: "Hjälp att välja racket",
      product: "Produktfråga",
      fitting: "Anpassning eller visning",
      technical: "Tekniskt underlag",
      config: "Konfigurationsförfrågan",
      gps: "GPS-utrustningsprofil",
      coach: "Tränarpartnerskap",
      club: "Underlag för klubb eller akademi",
      distribution: "Distribution eller marknadsutveckling",
      brand: "Varumärkessamarbete eller ambassadör",
      family: "Familje- eller utvecklingsförfrågan",
      institutional: "Institutionellt program",
      strategic: "Strategiskt samtal eller investering",
      owner: "Ägarförfrågan",
      network: "Ansökan till Sports Network",
      general: "Allmän förfrågan",
    },
    fields: {
      name: "Namn",
      email: "E-post",
      role: "Din roll",
      country: "Land eller region",
      organisation: "Organisation",
      message: "Ditt meddelande",
      level: "Nuvarande nivå",
      objectives: "Vad som är viktigast (upp till tre)",
      currentRacquet: "Nuvarande racket",
      grip: "Greppstorlek, om du vet den",
      seriesInterest: "Serie du är intresserad av",
      quantity: "Antal",
      city: "Stad eller plats för tillfället",
      coachInvolved: "Medverkar en tränare?",
      timing: "Önskad tidpunkt",
      targets: "Önskade målvärden",
      limits: "Obligatoriska gränser",
      use: "Avsedd användning",
      tradeoffs: "Godtagbara avvägningar",
      basis: "Mätunderlag",
      players: "Antal spelare",
      interests: "Intresseområden",
      territory: "Territorium du är intresserad av",
      channels: "Befintliga kanaler och erfarenhet",
      audience: "Målgrupp eller disciplin",
      proposal: "Föreslaget samarbete",
      goal: "Utvecklingsmål",
      ageBand: "Spelarens åldersgrupp",
      scope: "Programmets omfattning",
      interestArea: "Intresseområde",
      productRef: "Produkt- eller serienummer",
      requestType: "Typ av förfrågan",
      seeking: "Vad du söker",
      consent: "Jag godkänner att MAXIMUS får lagra och använda dessa uppgifter för att besvara förfrågan. Detta är ingen prenumeration på marknadsföring.",
    },
    roles: { player: "Spelare", parent: "Förälder eller vårdnadshavare", coach: "Tränare", club: "Klubb eller akademi", retailer: "Återförsäljare", distributor: "Distributör", brand: "Varumärke eller ambassadör", investor: "Investerare eller strategisk partner", institution: "Institution", other: "Annat" },
    interestOptions: { training: "Träningssystem", fitting: "Anpassning", identity: "Professionell identitet", programmes: "Behöriga program", brand: "Personligt varumärke", supply: "Leverans av utrustning", team: "Lagutrustning", personalisation: "Personalisering", development: "Utvecklingsprogram", service: "Service", network: "Deltagande i nätverket" },
    ownerTypes: { setup: "Inställning och konfiguration", service: "Service", records: "Dokumentation och certifikat", other: "Annat" },
    strategicAreas: { engineering: "Teknisk förmåga", configuration: "Konfigurationsdjup", manufacturing: "Tillverkningsmodell", routes: "Vägar till marknaden", ip: "Immateriella rättigheter och tjänster", expansion: "Expansionsmöjligheter" },
    errors: {
      required: "Det här fältet är obligatoriskt.",
      too_long: "Den här uppgiften är för lång.",
      too_short: "Den här uppgiften är för kort.",
      invalid_email: "Ange en giltig e-postadress, till exempel namn@exempel.se.",
      invalid_choice: "Välj ett av alternativen.",
      not_number: "Ange ett heltal med bara siffror.",
      out_of_range: "Värdet ligger utanför det tillåtna intervallet.",
      not_in_matrix: "Den här vikten finns inte i den listade matrisen för den valda serien.",
      decimal_not_supported: "Ange ett heltal utan decimaler.",
      too_many: "Välj högst tre alternativ.",
      consent_required: "Samtycke krävs för att MAXIMUS ska kunna besvara förfrågan.",
      invalid: "Den här uppgiften är inte giltig.",
    },
  },
  legal: {
    title: "Juridisk identitet och kontroll",
    lead: "Det publika varumärket är MAXIMUS / MAXIMUS GPS. De juridiska verksamhetsidentiteterna går att skilja åt och anges här.",
    entities: {
      institutional: { role: "Institutionellt programskikt", p: "Tillhandahåller det institutionella programskiktet där ett program fastställer den rollen. Ingen kommersiell säljare av racketar. En registrerad ideell organisation i Dubai International Financial Centre." },
      equipment: { role: "Kommersiell enhet för utrustning", p: "Den kommersiella enheten för utrustning vid leverans, distribution och avtalad kommersiell leverans där gällande verksamhetshandlingar fastställer den rollen. Avtalsparten för en transaktion anges i handlingarna för den transaktionen." },
      ip: { role: "Immateriella rättigheter, varumärke och kommersiell samordning", p: "Förekommer för en fastställd roll inom immateriella rättigheter, varumärke eller kommersiell samordning. Inget obekräftat avtalsansvar tilldelas." },
      stewardship: { role: "Förvaltningsreferens", p: "House of Maximus är förvaltningsreferensen för ekosystemet där den relevanta källan stöder det." },
      control: { role: "Intern kontroll av immateriella rättigheter, proveniens och dokument", p: "MIPA är det interna skiktet för immateriella rättigheter, proveniens och dokumentkontroll. En intern MIPA-post skiljer sig från en extern registrering av varumärke, patent eller upphovsrätt och från ett domstolsbeslut, och utgör inget visuellt godkännande." },
    },
    labels: { licence: "Licens", registration: "Registrering", vat: "VAT TRN", address: "Adress", email: "E-post", jurisdiction: "Jurisdiktion" },
    boundaryTitle: "Gränser",
    boundary: [
      "Ett köp ger inte automatiskt institutionellt medlemskap, rättigheter i styrningen, royalty eller investeringsrättigheter.",
      "Den institutionella rollen är skild från kommersiella transaktioner med utrustning.",
      "Integritet, programvillkor och arrangemang för styrd åtkomst motsvarar de funktioner som faktiskt är släppta.",
      "Ingen generell bestämmelse om tillämplig lag gäller varje besökare, försäljning eller utländskt program; den avtalsmässiga grunden fastställs per avtal.",
    ],
  },
  privacy: {
    title: "Integritetspolicy",
    updated: "Version 2026-09-21 · webbplats 4.2",
    contactTitle: "Kontakt för frågor om integritet",
    sections: {
      collect: ["Vad som samlas in", "När du skickar in ett formulär: de uppgifter du anger (namn, e-post, roll, land eller region, organisation om du anger den, ditt meddelande och svaren i formuläret), sid- och kampanjparametrarna för ditt besök (landningssida, språk, utm-parametrar; identifierare för annonsklick bara om du har tillåtit webbanalys) samt tidpunkten för insändningen. Din IP-adress används bara i hashad, kortlivad form för att begränsa missbruk och lagras inte med din förfrågan."],
      purpose: ["Varför", "För att besvara din förfrågan, ta fram det förslag eller den specifikation du har bett om och bevara en notering om förfrågan. Inga marknadsföringsmeddelanden skickas på grund av ett formulär."],
      storageOn: ["Var förfrågningar lagras", "Förfrågningar lagras i en databas hos Upstash, Inc. (Redis), som tillhandahålls via värdplattformen Vercel Inc."],
      notifyEmail: ["Avisering om en ny förfrågan", "När en förfrågan tas emot skickas en avisering med de uppgifter du har lämnat via e-post till den ansvariga MAXIMUS-brevlådan."],
      notifyTelegram: ["Avisering om en ny förfrågan", "När en förfrågan tas emot skickas en avisering med de uppgifter du har lämnat till den ansvariga personen på MAXIMUS via Telegram (Telegram FZ-LLC, Dubai), som därmed behandlar aviseringen under överföringen."],
      notifyWebhook: ["Avisering om en ny förfrågan", "När en förfrågan tas emot skickas en avisering med de uppgifter du har lämnat till en intern MAXIMUS-slutpunkt över en signerad och krypterad anslutning."],
      notifyNone: ["Avisering om en ny förfrågan", "Aviseringen om nya förfrågningar håller på att sättas upp. Din förfrågan lagras och läses av MAXIMUS i det interna registret; ingenting skickas till tredje part för detta ändamål."],
      storageOff: ["Var förfrågningar lagras", "Lagringen av förfrågningar håller på att sättas upp. Tills den är aktiv anger formulären att en förfrågan inte kan tas emot; ingenting lagras. Webbplatsen driftas av Vercel Inc."],
      browser: ["Lagring i webbläsaren", "Sessionslagringen behåller flervalssvaren från GPS och konfiguratorn samt kampanjparametrarna för ditt besök under den här webbläsarsessionen. Kontaktuppgifter, fritext, gravyrtext och uppgifter om barn lagras inte i webbläsaren."],
      analyticsOn: ["Webbanalys", "Med ditt samtycke mäter Google Analytics 4 besök och formulärhändelser utan kontaktuppgifter eller text från förfrågan. Ditt val sparas i den lokala lagringen och kan ändras när som helst under ”Inställningar för webbanalys” i sidfoten. Formulären fungerar utan webbanalys."],
      analyticsOff: ["Webbanalys", "Inget verktyg för webbanalys är aktivt på den här webbplatsen."],
      retention: ["Lagringstid", "Ingen automatisk gallringstid är konfigurerad ännu. Du kan när som helst begära att din förfrågan tas bort."],
      children: ["Barn", "Formulär ska fyllas i av en vuxen. Förfrågningar som rör spelare under 18 år görs av en förälder eller vårdnadshavare. Ange inte barnets namn, födelsedatum, skola eller medicinska uppgifter. Barns profiler publiceras aldrig."],
      rights: ["Dina rättigheter", "För att få tillgång till, rätta eller ta bort din förfrågan, skriv till gps@maximus.tennis och ange ditt ärendenummer."],
      controlled: ["Styrd information", "Konfidentiella dokument lagras inte på och levereras inte av den här webbplatsen. Styrt utlämnande sker under sekretessavtal eller avtal via separata kanaler."],
    },
  },
  terms: {
    title: "Användarvillkor",
    copyright: "Upphovsrätten till den här webbplatsen — till dess texter, fotografier, design och kod — tillhör Maximus Kiriyakulov ensam. Den har inte överlåtits till något företag eller till någon annan person.",
    updated: "Version 2026-09-21",
    sections: [
      ["Information, inte erbjudande", "Produktinformationen på den här webbplatsen beskriver godkända specifikationer, konfigurationsarkitektur och förklaringar av program. Den är inget erbjudande om försäljning, ingen prislista, ingen lagerbesked och inget leveransåtagande. Kommersiella villkor avtalas separat och skriftligt med den avtalsenhet som anges i varje transaktion."],
      ["Förfrågningar", "En förfrågan som skickas via den här webbplatsen — inklusive GPS-profiler, konfigurationsförfrågningar och tekniska underlag — lagras med ett ärendenummer och granskas. Den är inte en accepterad order, ett tillverkningsåtagande, en bekräftad bokning, en medlemsansökan eller en godkänd ansökan till något program."],
      ["Specifikationer och underlag", "Beräknade värden, tillverkningsmål och bekräftade specifikationer skiljs åt på respektive sida. Styvhetsvärden är tillverkningsmål till dess att annat publiceras. Inget resultat för en enskild spelare garanteras."],
      ["Ekosystem, medlemskap och rättigheter", "Köpet av en racket skapar inte institutionellt medlemskap, investeringsrättigheter, äganderätt till immateriella rättigheter, rätt till royalty eller förmåner för deltagande. Rättigheter följer publicerade programvillkor eller ett skriftligt avtal."],
      ["Immateriella rättigheter", "MAXIMUS®, lejonemblemet, GPS-märket och innehållet på den här webbplatsen är skyddade. Interna tekniska formler, kvalitetsprotokoll, laminatuppbyggnader, verktyg, leverantörers identitet, kalkylering och skyddad metodik lämnas inte ut här."],
    ],
  },
  lead: {
    submit: "Skicka förfrågan",
    submitting: "Skickar…",
    retry: "Försök igen",
    acceptedEyebrow: "Förfrågan mottagen",
    acceptedTitle: "Din förfrågan har tagits emot.",
    requestId: "Ärendenummer",
    acceptedNext: "MAXIMUS granskar varje förfrågan och svarar skriftligt till den e-postadress du har angett. Spara ärendenumret för eventuell uppföljning.",
    duplicate: "Den här förfrågan hade redan tagits emot; ingen dubblett skapades.",
    another: "Börja en ny förfrågan",
    errorsTitle: "Se över dessa fält:",
    failTitle: "Din förfrågan har inte skickats.",
    fail: {
      offline: "Din enhet är offline.",
      network: "Anslutningen till servern misslyckades.",
      timeout: "Servern svarade inte i tid.",
      rate_limited: "För många förfrågningar kom från det här nätverket. Försök igen om några minuter.",
      too_fast: "Formuläret skickades mycket snabbt. Kontrollera det och skicka igen.",
      spam_suspected: "Förfrågan stoppades av skräppostfiltret.",
      unavailable: "Förfrågningar kan inte tas emot just nu.",
      default: "Ett oväntat fel uppstod.",
    },
    keepNote: "Dina uppgifter behålls på den här sidan, så du kan försöka igen.",
    sendByEmail: "Skicka förfrågan med e-post",
    sendByEmailNote: "Ditt e-postprogram öppnas med texten till förfrågan. MAXIMUS får den när du skickar meddelandet.",
    mailConfig: "Konfiguration",
    mailPage: "Sida",
    fallback: "Om problemet kvarstår, skriv till {email}. En förfrågan räknas som skickad först när ett ärendenummer visas.",
    privacyLink: "Integritetspolicy",
    hpLabel: "Lämna det här fältet tomt",
    consentShort: "Samtycke",
    after: "Efter insändningen visas ett ärendenummer på den här sidan. Förfrågningar granskas och besvaras skriftligt; en förfrågan är ingen order.",
    basis: { unstrung: "Osträngad", strung: "Strängad", unknown: "Osäker — avtalas i specifikationen" },
    hints: {
      email: "MAXIMUS svarar skriftligt till den här adressen.",
      goal: "Till exempel: första tävlingsracketen, eller steget bort från en juniorracket. Ange inte namn, födelsedatum eller medicinska uppgifter om ett barn.",
      currentRacquet: "Märke och modell, om du vet dem.",
      message: "Ange inte lösenord, betaluppgifter eller medicinska uppgifter.",
    },
  },
  choose: {
    eyebrow: "Hjälp att välja",
    title: "Hjälp mig välja en racket",
    lead: "Berätta för MAXIMUS vilken nivå du har och vad som är viktigast. Dina svar granskas och du får ett skriftligt förslag: serie, precisionsklass, vikt och grepp.",
    stepsTitle: "Så går det till",
    steps: [
      ["Dina svar", "Nivå, prioriteringar och greppstorlek om du vet den."],
      ["Expertgranskning", "MAXIMUS jämför dina svar med seriernas matriser."],
      ["Skriftligt förslag", "En föreslagen konfiguration och nästa steg, skriftligt."],
    ],
    formTitle: "Dina svar",
    submit: "Begär hjälp att välja",
    altTitle: "Vill du hellre bestämma själv?",
    altGps: "Utförlig GPS-profil",
    altBuild: "Konfigurera direkt",
    note: "Ingen automatisk anpassning och inget påstående om träffsäkerhet: en människa granskar varje förfrågan.",
  },
  consent: {
    title: "Webbanalys",
    text: "Får MAXIMUS mäta besök med Google Analytics? Formulären fungerar oavsett; inga kontaktuppgifter och ingen text från förfrågan skickas till webbanalysen.",
    allow: "Tillåt webbanalys",
    decline: "Neka",
  },
  media: {
    spotHeadsUp: "Fem MAXIMUS Spot Trainer sida vid sida, med de runda träffytorna uppåt och handtagen nedåt, och bollar som vilar på träffytorna",
    greatHero: "MAXIMUS GREAT-serien, 363 g: den kompletta kompositionen med röda och gula detaljer på huvudet, glansig MAXIMUS-text, Maximus-autografen på skaftet och lejonet på greppkapseln",
    spotRow: "Fem MAXIMUS Spot Trainer lagda i en rad, med bollar som vilar på de runda träffytorna",
    spotPair: "Två MAXIMUS Spot Trainer stående upprätt framför MAXIMUS lejonemblem, med bollar på de runda träffytorna",
    spinVisual: "MAXIMUS SPIN: huvud med strängar, glansig MAXIMUS-text, grepp och greppkapsel med lejonet",
    powerVisual: "MAXIMUS POWER: huvud med strängar, glansig MAXIMUS-text, personaliseringsgravyr, grepp och greppkapsel med lejonet",
    greatVisual: "MAXIMUS GREAT: huvud med strängar, glansig MAXIMUS-text, personaliseringsgravyr, grepp, greppkapsel med lejonet och seriemärket G på halsen",
    spinHead: "MAXIMUS SPIN, huvud och strängplan",
    handleLion: "MAXIMUS hals, grepp och greppkapsel med lejonmärket",
    engraving: "Silverfärgad personaliseringsgravyr på skaftet",
    lettering: "Glansigt svart MAXIMUS-text på en matt svart ram",
    variantAlt: "MAXIMUS {series}-serien — {w} g, balans {b} mm: fullständig visualisering med specifikationslisten, zonen för personaliseringsgravyr och MIPA-märkningen",
    sstSystem: "MAXIMUS Sweet Spot Trainer, system med fyra racketar",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "Skaften på Sweet Spot Trainer med MAXIMUS-texten",
    sstGrips: "Grepp och greppkapslar på Sweet Spot Trainer",
    sstButtcaps: "Sweet Spot Trainer, fyra greppkapslar med lejonmärket",
    note: "Produktvisualisering",
  },
  notFound: { title: "Sidan hittades inte", p: "Sidan du efterfrågade finns inte på det här språket.", cta: "Till startsidan" },
};

export default sv;
