/* Turkish dictionary — MAXIMUS website v4.0. Translated from content/en.js; numerical product data lives in data/products.js. */
const tr = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — şartnameye göre mühendisliği yapılan tamamen karbon tenis raketleri",
    defaultDescription:
      "Kasadan sapa tamamen karbon tenis raketleri: GREAT 97 in², POWER 98 in² ve SPIN 100 in², sekiz fabrika sap ölçüsü L0–L7, ağırlık, denge, swingweight ve sertlik için hassasiyet sınıfları, talep üzerine özel mühendislik.",
  },
  common: {
    statuses: {
      current: "Güncel",
      agreement: "Anlaşmaya bağlı olarak mevcut",
      development: "Geliştirme aşamasında",
      concept: "Konsept",
      target: "Üretim hedefi",
      modelled: "Hesaplanmış",
      confirmed: "Teyit edilmiş",
      requested: "Talep edilen mimari",
      notprovided: "Verilmemiş",
    },
    brief: { who: "Kimler için", value: "Ne elde edersiniz", now: "Şu anda teyitli", next: "Sonraki adım" },
    labels: {
      next: "İleri",
      back: "Geri",
      edit: "Yanıtları düzenle",
      review: "Gözden geçirme",
      start: "Başla",
      restart: "Yeniden başla",
      copy: "Talep metnini kopyala",
      copied: "Kopyalandı",
      openEmail: "Bu talebi göndermek için e-posta uygulamasını açın",
      reference: "Talep referansı",
      weight: "Ağırlık",
      balance: "Denge",
      swingweight: "Swingweight",
      stiffness: "Sertlik",
      grip: "Sap ölçüsü",
      headSize: "Kafa ölçüsü",
      series: "Seri",
      precisionClass: "Hassasiyet sınıfı",
      quantity: "Adet",
      notProvided: "Henüz yayımlanmadı",
      requestTarget: "Talep edilen hedef",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Devamını okuyun",
      allSeries: "Tüm seriler",
      points: "listelenmiş ağırlık",
      optional: "isteğe bağlı",
      required: "zorunlu",
      select: "Seçin",
      yes: "Evet",
      no: "Hayır",
      unknown: "Emin değilim",
      custom: "Özel hedef",
      listed: "Listedeki ağırlık",
      individual: "Tek raket",
      pair: "Eşleştirilmiş ikili",
      triple: "Eşleştirilmiş üçlü",
      team: "Takım seti",
      summaryTitle: "Talebinizin özeti",
      nextAction: "Sonraki eylem",
      status: "Durum",
      learn: "Daha fazla bilgi",
      schematic: "Şematik — ölçüm değildir",
      photo: "Fotoğraf",
    },
    ecosystemStrip: "MAXIMUS ekosistemi",
    truth: {
      noPrices: "Fiyatlar, asgari miktarlar, teslim süreleri, garantiler ve teslim taahhütleri her pazar ve her program için yazılı olarak teyit edilir.",
      requestNotOrder: "Talep, bir inceleme talebidir. Kabul edilmiş bir sipariş, bir üretim taahhüdü veya teyit edilmiş bir randevu değildir.",
      noGuarantee: "Burada anlatılan hiçbir ekipman, yöntem veya program belirli bir oyuncu için bir sonuç garanti etmez.",
      governing: "Bu sayfa birkaç dilde yayımlanır. Geçerli sürüm İngilizce sürümdür; çeviri kolaylık sağlamak amacıyla sunulur.",
    },
  },
  nav: {
    language: "Dil",
    groups: { racquets: "Raketler", training: "Antrenman", ecosystem: "Ekosistem", partnerships: "İş birlikleri" },
    familyPlan: "Aile Planı",
    racquets: "Raket serileri ve karşılaştırma",
    great: "GREAT — 97 in² · Kontrol",
    power: "POWER — 98 in² · Güç",
    spin: "SPIN — 100 in² · Spin",
    precision: "Hassasiyet ve sertlik",
    grip: "Fabrika sap mimarisi L0–L7",
    custom: "Özel mühendislik",
    training: "Antrenman sistemleri",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodoloji",
    gps: "MAXIMUS GPS",
    build: "Yapılandırıcı",
    choose: "Seçmeme yardım edin",
    ecosystem: "Ekosistem haritası",
    engineering: "Mühendislik ve üretim",
    experience: "Deneme ve fitting",
    brands: "Kişisel markalar ve marka elçileri",
    families: "Aileler ve ebeveynler",
    owners: "Sahipler ve sahip kasası",
    network: "Sports Network",
    partnerships: "Tüm iş birliği yolları",
    coaches: "Antrenörler",
    clubs: "Kulüpler ve akademiler",
    distribution: "Distribütörlük ve ülke geliştirme",
    strategic: "Stratejik ve yatırım",
    institutional: "Kurumsal programlar",
    contact: "İletişim",
    legal: "Hukuki kimlik",
    privacy: "Gizlilik",
    terms: "Kullanım şartları",
    menu: "Menü",
    close: "Kapat",
    home: "Ana sayfa",
    skip: "İçeriğe geç",
  },
  footer: {
    line: "MAXIMUS raketi, MAXIMUS dünyasına açılan anahtarınızdır.",
    product: "Ürün",
    ecosystem: "Ekosistem",
    company: "Kuruluş",
    instagram: "Instagram",
    email: "Email",
    analytics: "Analitik ayarları",
    subscribe: {
      title: "MAXIMUS ile kalın",
      line: "Yeni seriler, fitting tarihleri, antrenman materyalleri ve sahip programı. Yılda birkaç e-posta — başka hiçbir şey.",
      label: "E-posta adresi",
      placeholder: "your@email.com",
      button: "Abone ol",
      sending: "Gönderiliyor",
      done: "Listedesiniz. Yalnızca okumaya değer bir şey olduğunda yazıyoruz.",
      invalid: "Lütfen adresi kontrol edin.",
      failed: "Adres kaydedilmedi. Lütfen birazdan tekrar deneyin.",
      terms: "Abone olarak MAXIMUS'un bu güncellemeleri size göndermesini ve adresinizi bu amaçla saklamasını kabul edersiniz. Her e-postada abonelikten çıkma bağlantısı yer alır.",
    },
    rights: "MAXIMUS® ve aslan amblemi, MAXIMUS ekosisteminin markalarıdır. MIPA dahili fikri mülkiyet, köken ve doküman kontrolü.",
    boundary:
      "Ticari ve sözleşmeye ilişkin şartlar ayrıca yazılı olarak kararlaştırılır. Bir raketin satın alınması; kurumsal üyelik, yatırım hakkı, fikri mülkiyet sahipliği veya telif payı hakkı doğurmaz.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Hassasiyet temas anında başlar.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer ve MAXIMUS metodolojisi, odaklı çalışmayı tamamen karbon performans raketleriyle birleştirir.",
    heroCta1: "Antrenman sistemini keşfedin",
    heroCta2: "GREAT'i keşfedin",
    heroCaption: "MAXIMUS GREAT · 97 in² · Kontrol",
    heroMeta: [
      ["Tamamen karbon", "kasadan sapa"],
      ["4 parametre", "ağırlık · denge · swingweight · sertlik"],
      ["8 sap ölçüsü", "fabrika geometrisi L0–L7"],
      ["3 seri", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Aile Planı · Bizimle katkıda bulunun",
      title: "Aile bütçeniz. Neyi karşılar? Neyi inşa eder?",
      p: "Üç senaryo yan yana — mevcut, planlanan ve istenen. Bütçenizin karşıladığı antrenmanlar, saatler ve top temasları ile bir antrenmanın, bir saatin ve bir vuruşun maliyeti — hepsi kendi rakamlarınızla hesaplanır.",
      points: [
        ["Kendi rakamlarınız", "Her tutar sizden gelir. Hiçbir şey varsayılmaz, hiçbir şey dönüştürülmez."],
        ["Üç senaryo", "Şu an yaptığınızı, planladığınızla ve yapmak istediğinizle karşılaştırın."],
        ["On yıl ileriye", "Belirlediğiniz yaşlarla sınırlı, bir ila on yıllık harcama planı."],
        ["Kortun ötesinde", "Önde gelen okullara kabul sürecinde destek ve oyuncuya ait kalan dijital varlıklar."],
      ],
      cta: "Aile planınızı hesaplayın",
    },
    paths: {
      eyebrow: "Buradan başlayın",
      title: "Yolunuzu seçin",
      items: {
        player: { h: "Oyuncu", p: "Seviyenize ve önceliklerinize göre bir raket bulun ya da doğrudan yapılandırın.", a: "Raketinizi bulun" },
        parent: { h: "Ebeveyn", p: "Gelişim hedefleri, antrenör katılımı ve uygun ekipman için yazılı bir yol.", a: "Aile yolu" },
        coach: { h: "Antrenör, kulüp veya akademi", p: "Antrenman sistemleri, fitting, takım setleri ve kişiselleştirme.", a: "Antrenör ve kulüp yolları" },
        partner: { h: "Distribütör veya iş ortağı", p: "Distribütörlük, ülke geliştirme, stratejik ve kurumsal yollar.", a: "İş birliği yolları" },
      },
    },
    series: {
      eyebrow: "Performans serileri",
      title: "Üç performans mimarisi. Tek mühendislik platformu.",
      lead: "Seriyi oyun yönüne göre seçin, ardından yapılandırmayı tamamlayın: hassasiyet sınıfı, ağırlık, sap ölçüsü, kişiselleştirme.",
      cta: "Serileri karşılaştırın",
      configure: "Yapılandır",
      open: "Seriyi aç",
      photoPending: "Fotoğraf henüz yayımlanmadı",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS Hassasiyet Sistemi",
      title: "Ağırlık. Denge. Swingweight. Sertlik.",
      sub: "Tek bir mühendislik sistemi olarak kontrol edilir.",
      lead: "Üç hassasiyet sınıfı, tamamlanmış her raketin beyan edilen şartnamesine ne kadar sıkı tutulduğunu tanımlar. P0.5, tanımlı bir ölçüm protokolü altında sıkı bir toleranstır — sıfır hata değildir.",
      cta: "Hassasiyet ve sertliğin ayrıntıları",
    },
    stiffness: {
      eyebrow: "Sertlik",
      title: "Beyan edilen bir hedefe karşı tekrarlanabilir kasa tepkisi.",
      p: "Kasa sertliği; tepkiyi, hissi ve raketler arasındaki tutarlılığı şekillendirir. MAXIMUS bunu kontrol edilen dördüncü parametre olarak ele alır: hedef, ölçüm sonucu, izin verilen tolerans ve ölçüm cihazının kabiliyeti ayrı kayıtlar olarak tutulur. Elde edilen fayda tekrarlanabilirliktir — her oyuncu için garanti edilmiş bir sonuç değildir.",
      cols: [["Tepki", "Kasanın temas anında enerjiyi nasıl geri verdiği."], ["His", "Oyuncunun temas anında ne algıladığı."], ["Tutarlılık", "Aynı şartnameye göre üretilen raketler, sınıflarının içinde benzer tepki verir."]],
      schematicCaption: "Şematik: her sınıf için beyan edilen sertlik hedefi çevresinde izin verilen sapma. Ölçüm değildir; hiçbir RA değeri ima edilmez.",
      bands: { p25: "hedef toleransı ±1 RA", p15: "hedef toleransı ±0.5 RA", p05: "yerleşik fabrika ölçüm protokolü altında beyan edilen hedef RA değerine uygundur — sıfır hata değildir", target: "beyan edilen hedef (hiçbir değer ima edilmez)" },
    },
    carbon: {
      eyebrow: "Yapı standardı",
      title: "Tamamen karbon. Kasadan sapa.",
      p: "Bu platformdaki mevcut tüm MAXIMUS raketleri, sap dahil olmak üzere yapı itibarıyla tamamen karbondur. Sapı oluşturmak için köpük kullanılmaz.",
      gripTitle: "Sekiz fabrika sap ölçüsü. L0–L7.",
      gripP: "Her ölçü, fabrikada üretilen karbon sap geometrisidir — overgrip ile kalınlaştırma değildir.",
      scaleCaption: "Şematik: nominal sap tanımları L0–L7 (4″ ile 4⅞″ arası). Ölçülmüş sap boyutları değildir.",
      cta: "Fabrika sap mimarisi",
    },
    custom: {
      eyebrow: "Özel mühendislik",
      title: "Şartnameye göre mühendislik.",
      sub: "Standart seri, başlangıç noktasıdır.",
      p: "MAXIMUS, yayımlanmış matrislerin ötesindeki teknik gereksinimleri değerlendirme, mühendislik, doğrulama ve üzerinde anlaşılan şartnameye göre üretim için kabul eder. Uygulanabilirlik yazılı olarak teyit edilir.",
      chain: ["Tanımlama", "Mühendislik", "Doğrulama", "Şartname", "Üretim", "Ölçüm / kayıt"],
      cta: "Teknik brief gönderin",
      cta2: "Özel mühendisliği görüşün",
    },
    training: {
      eyebrow: "Antrenman sistemleri",
      title: "Temas noktası etrafında kurulmuş bir antrenman sistemi.",
      p: "Sweet Spot Trainer, MAXIMUS metodolojisi ve Spot Trainer, ekipmanı antrenör liderliğindeki çalışmayla birleştirir: merkezden temas, kontrol, kademeli yükleme ve performans raketine geri dönüş.",
      cta: "Antrenman sistemleri",
      cta2: "Tanıtım talep edin",
      photoPending: "Antrenman raketinin fotoğrafı henüz yayımlanmadı",
      sstP: "Merkezden temas çalışması için 50 in² antrenman kafası; antrenörün belirleyeceği yükleme için dört ağırlık yapılandırması.",
      sstCta: "Sweet Spot Trainer'ı keşfedin",
      sstCaption: "300 g yapılandırması, dört yapılandırmadan biri",
      methodP: "Hedefleri belirleyin, ekipmanı seçin, antrenör katılımıyla çalışın, gözlemleri kaydedin, yeniden değerlendirin, ayarlayın ve çalışmayı performans oyununa aktarın.",
      methodCta: "Metodolojiyi keşfedin",
      spotP: "Hassas ve tekrarlanabilir bir temas noktasını çalışmak için küçük, yuvarlak bir hedef.",
      spotCta: "Spot Trainer'ı keşfedin",
    },
    manufacturing: {
      eyebrow: "Üretim ve kalite kontrol",
      title: "Şartnameye göre üretilir. Ölçülür ve kaydedilir.",
      p: "Üretim, her siparişin yazılı şartnamesine uyar. Kayıtlar hassasiyet sınıfını izler: P2.5 için saklanan üretim kayıtları, P1.5 için bireysel kayıtlar ve izlenebilirlik, P0.5 için — siparişin programı bunları uyguladığı ölçüde — bireysel kontrol ve dokümantasyon.",
      confirmedTitle: "Teyit edilmiş",
      confirmed: ["Kasadan sapa tamamen karbon yapı.", "Dört kontrollü parametreyle P2.5, P1.5 ve P0.5 hassasiyet sınıfları.", "Sekiz fabrika sap ölçüsü L0–L7."],
      pendingTitle: "Henüz yayımlanmadı",
      pending: "Ölçüm ekipmanının fotoğrafları, örnek kalite kontrol kayıtları ve fabrika görüntüleri henüz yayımlanmadı. Bu sayfadaki hiçbir bilgi ölçülmüş bir sertifika değildir.",
      captions: { lettering: "Mat kasa üzerinde parlak MAXIMUS yazısı", buttcap: "Aslan markalı grip ve sap kapağı", handle: "Gümüş kişiselleştirme gravürü", finish: "Kafa ve kordaj yüzeyi" },
      cta: "Mühendislik ve üretim",
    },
    world: {
      eyebrow: "MAXIMUS dünyası",
      title: "Tek anahtar. Tek ekosistem. Sınırsız fırsat.",
      note: "“Sınırsız fırsat” bir marka ifadesidir; sınırsız teknik uygulanabilirlik, gelir veya erişim vaadi değildir. Satın alma; telif payı, yatırım getirisi, sponsorluk ya da bir oyuncunun gelişiminin finanse edilmesi anlamına gelmez.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — ve tenis dünyasındaki navigasyonunuz: yazılı olarak yanıtlanan, yönlendirmeli bir ekipman profili." },
        personal: { h: "Kişiselleştirme", p: "Onaylı gümüş gravür uygulamasıyla isimler, baş harfler, numaralar ve takım tanımlaması." },
        development: { h: "Gelişim", p: "Antrenör liderliğinde antrenman sistemleri, kayıtlar ve yeniden değerlendirme." },
        ecosystem: { h: "Genişletilmiş ekosistem", p: "Kişisel markalar, sahip kayıtları, ağ, lisanslama ve kurumsal programlar — her biri gerçek durumuyla gösterilir." },
      },
      cta: "Ekosistemi keşfedin",
    },
    partners: {
      eyebrow: "İş birliği yolları",
      title: "Antrenörler, kulüpler, distribütörler ve iş ortakları.",
      p: "Önce yazılı yeterlilik değerlendirmesi. Ülke hakları, münhasırlık ve ticari şartlar yazılı olarak görüşülür — asla bir form üzerinden verilmez.",
      cta: "Tüm iş birliği yolları",
      formTitle: "Kısa talep",
      formLead: "Talebin amacını seçin ve MAXIMUS'a yazın. Bu sayfada bir talep numarası alırsınız.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "TENİS DÜNYASINDAKİ NAVİGASYONUNUZ" } },
    personal: { eyebrow: "Kişiselleştirme", title: "Adınız. Numaranız. MAXIMUS'unuz." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Üç seri. Gerçek parametreler." },
    map: { cta: "Ekosistemi keşfedin" },
  },
  racquets: {
    title: "Raketler",
    lead: "Ortak bir yapı standardını, ortak bir hassasiyet sistemini ve ortak bir fabrika sap mimarisini paylaşan üç performans serisi. Her seri, daha geniş bir mühendislik platformu içinde yerleşik bir performans mimarisidir.",
    direction: { control: "Kontrol", power: "Güç", spin: "Spin" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Birincil oyun yönü",
    compareTitle: "Seri karşılaştırması",
    compareLead: "Yalnızca teyit edilmiş mimari verileri. Bu seriler için kordaj deseni, uzunluk, kasa profili, kordaj gerginliği aralığı, swingweight ve sertlik nominal değerleri yayımlanmaz; bunlar teknik inceleme için talep edilen hedefler olarak toplanır.",
    columns: { series: "Seri", head: "Kafa ölçüsü", direction: "Yön", weights: "Listedeki ağırlıklar", range: "Ağırlık aralığı", balance: "Denge verileri" },
    balanceModelled: "Hesaplanmış değerler",
    balanceNotProvided: "Henüz yayımlanmadı",
    construction: "Yapı: kasadan sapa tamamen karbon · Hassasiyet: P2.5 / P1.5 / P0.5 · Sap ölçüleri: L0–L7",
    otherTitle: "Diğer raket sporları",
    otherLead: "Onaylı geliştirme yönleri. Bu kategorilerde satılabilir ürün bulunmuyor ve bu kategorilere hiçbir tenis şartnamesi aktarılmıyor.",
    other: { padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", racquetball: "Racquetball", beachTennis: "Plaj tenisi" },
    ctaConfigure: "Talep yapılandırın",
    ctaSeries: "Seriyi aç",
  },
  seriesPage: {
    eyebrow: "Performans serileri",
    intro: {
      great: "97 in² GREAT mimarisi kontrol üzerine kurulmuştur: kompakt bir kafa, hassas temas ve yön güveni.",
      power: "98 in² POWER mimarisi enerji aktarımı üzerine kurulmuştur: stabil bir kasadan derinlik ve hız.",
      spin: "100 in² SPIN mimarisi topun davranışı üzerine kurulmuştur: dönüş, güvenlik payı ve yörünge şekillendirme.",
    },
    photoPending: "Serinin fotoğrafı henüz yayımlanmadı",
    detailPending: "Bu serinin yapı ve sap detay fotoğrafları henüz yayımlanmadı.",
    specsTitle: "Şartname ve durum",
    catalogue: {
      eyebrow: "{series} serisi kataloğu",
      title: "{n} ağırlık varyantı",
      lead: "{series} serisinin ağırlığa göre sıralanmış tüm varyantları. Ağırlık gram, denge sap dibinden milimetre cinsindendir. Her görselleştirme bütün olarak gösterilir: hiçbir şey kırpılmaz, maskelenmez veya gerilmez.",
      selectLabel: "Bir ağırlık varyantı seçin",
      select: "Bu varyantı göster",
      selected: "Yukarıda gösteriliyor",
      balanceLabel: "Denge",
      headLabel: "Kafa ölçüsü",
      constructionLabel: "Yapı",
      gripsLabel: "Fabrika sap ölçüleri",
      precisionLabel: "Hassasiyet sınıfları",
      balanceConfirmed: "Denge, bu ağırlık için teyit edilmiş değerdir ve görselleştirmede basılı olan değerle örtüşür.",
      balanceModelled: "Denge, listedeki bu ağırlık için hesaplanmış bir değerdir, bireysel bir fabrika ölçümü değildir; görselleştirmede basılı olan değerle örtüşür.",
      zoom: "Görseli aç",
      close: "Kapat",
      allTitle: "{n} varyantın tümü",
    },
    specs: { head: "Kafa ölçüsü", direction: "Birincil yön", weights: "Listedeki ağırlıklar", range: "Ağırlık aralığı", balance: "Denge", construction: "Yapı", grips: "Fabrika sap ölçüleri", precision: "Hassasiyet sınıfları" },
    construction: "Kasadan sapa tamamen karbon",
    statusTitle: "Değerlerin durumu",
    matrixTitle: "Tam ağırlık matrisi",
    matrixLead: "Listedeki ağırlıklar standart seçimdir. Diğer ağırlıklar özel hedef olarak talep edilebilir; eksik ara değerler sonradan eklenmez.",
    balanceNote: {
      confirmed: "Denge değerleri listedeki her ağırlık için teyit edilmiştir (sap dibinden mm) ve o ağırlığın görselleştirmesinde basılı olan değerle örtüşür. Burada hesaplanmaz ve komşu ağırlıklar arasında düzleştirilmez; ölçüm esası yazılı şartnamede teyit edilir.",
      modelled: "Denge değerleri listedeki her ağırlık için hesaplanır (sap dibinden mm). Bunlar bireysel fabrika ölçümleri değildir; ölçüm esası yazılı şartnamede teyit edilir.",
      notprovided: "Bu seri için denge değerleri verilmemiştir. Bunları başka bir seriden çıkarmayın.",
    },
    optionsTitle: "Hassasiyet, sap ölçüsü ve ağırlık",
    notPublished: "Bu seri için yayımlanmayanlar: kordaj deseni, uzunluk, kasa profili, kordaj gerginliği aralığı, swingweight ve sertlik değerleri. Bunları teknik inceleme için talep edilen hedefler olarak belirtebilirsiniz.",
    offerTitle: "Talebinizden sonra ne olur",
    offerSteps: [
      ["Talep", "Bir yapılandırma veya soru gönderin. Talep numarası anında gösterilir."],
      ["İnceleme", "MAXIMUS seriyi, sınıfı, ağırlığı, sap ölçüsünü ve talep edilen hedefleri inceler."],
      ["Yazılı yanıt", "Şartname, temin durumu ve ticari şartlar yazılı olarak teyit edilir."],
    ],
    faqTitle: "Sorular",
    faq: [
      ["Denge değerleri ölçülmüş mü?", "Listedeki ağırlıklar için hesaplanmıştır, bireysel ölçüm değildir. Ölçüm esası yazılı şartnamede teyit edilir."],
      ["Listede olmayan bir ağırlık talep edebilir miyim?", "Evet, tam gram cinsinden özel hedef olarak. Teknik olarak incelenir ve uygulanabilirlik yazılı olarak teyit edilir."],
      ["Hassasiyet sınıfı neyi değiştirir?", "Ağırlığın, dengenin, swingweight'in ve sertliğin beyan edilen şartnameye ne kadar sıkı tutulduğunu ve hangi kayıtların tutulduğunu."],
      ["Sap, overgrip ile kalınlaştırılıyor mu?", "Hayır. L0–L7, fabrikada üretilen karbon sap geometrileridir."],
      ["Fiyatlar ve teslim süreleri nerede?", "Her talep için yazılı olarak teyit edilir; burada yayımlanmaz."],
    ],
    faqSpinBalance: ["SPIN denge değerleri nereden geliyor?", "Teyit edilmiş Spin serisi tablosundan: sap dibinden milimetre cinsinden dengeyle 33 ağırlık varyantı. Her çift, o ağırlığın onaylı görselleştirmesinde basılı olan değerle örtüşür. Değerler hesaplanmaz ve komşu ağırlıklar arasında düzleştirilmez."],
    ctaBuild: "Bu seriyi yapılandırın",
    ctaAsk: "Bu seri hakkında soru sorun",
    ctaCompare: "Tüm serileri karşılaştırın",
    weightsLabel: "listelenmiş ağırlık",
    headLabel: "kafa",
  },
  precision: {
    title: "Hassasiyet ve sertlik",
    switch: { label: "Bir hassasiyet sınıfı seçin", panelLabel: "Dört kontrollü parametre —", qcLabel: "Kalite kontrol mimarisi", protocolNote: "tanımlı fabrika kalite kontrol ölçüm protokolü altında", fullTable: "Tam karşılaştırma tablosu" },
    lead: "Tek bir mühendislik sistemi olarak kontrol edilen dört parametre. Her sınıf, tamamlanmış bir raketin beyan edilen şartnamesine ne kadar sıkı tutulduğunu ve hangi kalite kayıtlarının üretildiğini tanımlar.",
    statement: "Ağırlık. Denge. Swingweight. Sertlik. Tek bir mühendislik sistemi olarak kontrol edilir.",
    classes: {
      "P2.5": { name: "Ölçeklenebilir performans çekirdeği", qc: "Bireysel ölçüm ve saklanan üretim kayıtları." },
      "P1.5": { name: "İleri hassasiyet", qc: "Bireysel ölçüm, bireysel kayıtlar ve izlenebilirlik." },
      "P0.5": { name: "Profesyonel · bireysel olarak kontrol edilen", qc: "Nominal ve gerçek değerlerle bireysel kontrol ve bireysel ölçüm kayıtları; siparişin programı bunları uyguladığı ölçüde seri kimliği, parti izlenebilirliği, hassasiyet sertifikası ve eşleştirilmiş setler." },
    },
    columns: { cls: "Sınıf", weight: "Ağırlık", balance: "Denge", sw: "Swingweight", stiff: "Sertlik", qc: "Kalite kontrol mimarisi" },
    stiffTarget: "hedef toleransı",
    stiffExact: "yerleşik fabrika ölçüm protokolü altında beyan edilen hedef RA değerine uygundur",
    programmeNote: "Seri kimliği, sertifikalar ve eşleştirilmiş set dokümantasyonu yalnızca belirli bir siparişin programı bunları uyguladığı durumlarda düzenlenir.",
    targetsNote: "Sertlik şartnameleri, ilgili protokol ve üretim kanıtları daha güçlü bir iddiayı destekleyene kadar üretim hedefidir. Mimari önerisi, listelenen her yapılandırmanın dört parametreli tam bir serbest bırakma sürecini geçtiği anlamına gelmez.",
    stiffnessTitle: "Sertlik neden önemli",
    stiffnessP1: "Kasa sertliği; kasanın temas anında nasıl tepki verdiğini, nasıl hissettirdiğini ve iki raketin birbirine ne kadar tutarlı olduğunu etkiler. Bunu kontrol etmenin temel faydası, beyan edilen bir şartnameye karşı tekrarlanabilir tepkidir.",
    stiffnessP2: "Doğrulanmış uygunluk yayımlanmadan önce dahili kalite kontrol kaydı; cihazı, kalibrasyon durumunu, yöntemi, raketin durumunu, çözünürlüğü, ölçüm belirsizliğini, tekrarlı ölçümleri, yuvarlama kuralını ve kabul kuralını tanımlar. Ekranda görünen tam sayının aynı olması, sıfır fiziksel değişkenliğin veya sıfır ölçüm hatasının kanıtı değildir.",
    fields: ["Hedef", "Ölçüm sonucu", "İzin verilen tolerans", "Cihaz kabiliyeti"],
    fieldsNote: "Her kayıtta ayrı alanlar olarak tutulur.",
    matchedTitle: "Eşleştirilmiş setler",
    matchedP: "Eşleştirilmiş set kriterleri, bireysel toleranstan ayrı tanımlanır. Her raketin kendi nominal toleransına uygun olması, iki raket arasındaki belirli bir azami farkı tek başına kanıtlamaz. Eşleştirilmiş ikililer, üçlüler ve takım setleri yapılandırıcı üzerinden talep edilir ve yazılı olarak teyit edilir.",
    extendedTitle: "Genişletilmiş teknik model",
    extendedP: "Veri modeli ek parametreleri destekler. Bunlar için henüz değer veya tolerans sınıfı bulunmuyor; bir teknik brief içinde talep edilen hedefler olarak belirtilebilirler.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Burulma davranışı", length: "Uzunluk", beamProfile: "Kasa profili", headGeometry: "Kafa geometrisi", stringPattern: "Kordaj deseni", durability: "Dayanıklılık", vibration: "Titreşim özellikleri" },
    noZero: "MAXIMUS, listelenmiş ürün serisini sıfır toleranslı olarak tanımlamaz. Serideki hassasiyet; beyan edilmiş bir toleransı ve tanımlı bir kalite kontrol mimarisi olan bir sınıf olarak belirtilir. ZERO, bu serinin bir parçası değildir.",
    zero: {
      eyebrow: "Ayrıcalıklı seçenek",
      title: "ZERO",
      sub: "Sıfır gram tolerans.",
      p: "Üç sınıf, tamamlanmış bir raketi beyan edilmiş bir tolerans bandının içinde tutar. ZERO bu bandı kaldırır. Raket, ölçüm değeri fabrika cihazının çözünürlüğünde beyan edilen değere eşit olana kadar üretilir ve ölçülür; o ölçüm değeri raketle birlikte verilir. Listelenmiş serinin bir parçası değildir ve dördüncü bir sınıf değildir: tek bir raket veya tek bir eşleştirilmiş set için, özel üretim bir ayrıcalık olarak bireysel olarak kararlaştırılır. Anlaşmaya bağlı olarak aynı yaklaşım dengeye ve swingweight'e de uygulanır.",
      points: [
        ["Bant yok", "Beyan edilen değer sonucun kendisidir, bir toleransın merkezi değil."],
        ["Her seferinde bir raket", "Tek bir birim olarak üretilir, ölçülür ve kaydedilir."],
        ["Raketle birlikte verilir", "Ölçülen değer teslim edilir ve üretim kaydında saklanır."],
        ["Yazılı olarak teyit edilir", "Parametreler, kapsam ve teslim süresi üretimden önce kararlaştırılır."],
      ],
      note: "Eşitlik, fabrika ölçüm cihazının çözünürlüğü düzeyinde geçerlidir. Ekranda görünen değerin aynı olması, sıfır fiziksel değişkenlik iddiası değildir. Temin durumu ve koşullar her sipariş için bireysel olarak kararlaştırılır.",
      cta: "ZERO talep edin",
    },
    cta: "Hassasiyet sınıfıyla yapılandırın",
  },
  grip: {
    title: "Fabrika sap mimarisi",
    statement: "Sekiz fabrika sap ölçüsü. L0–L7.",
    lead: "Sap geometrisi, karbon sap mimarisinin bir parçasıdır. Her ölçü sap geometrisi olarak üretilir, overgrip ile kalınlaştırılmaz.",
    emph: "Genişletilmiş ölçüler",
    p1: "Sekiz ölçülük fabrika serisi, antrenörlere ve oyunculara ekipmanın oyuncunun çevresinde tanımlanabileceği daha geniş bir yapılandırma aralığı sunar; buna daha büyük L6 ve L7 geometrileri de dahildir.",
    p2: "Nominal sap tanımı, işlenmemiş yapısal sap boyutlarından ve nihai ölçüm protokolünden farklıdır. Ölçüler, bu platformdaki performans serileri ve antrenman aileleri için geçerlidir.",
    p3: "Bu ürün serisi için dünya çapında münhasırlık iddiasında bulunulmaz.",
    columns: { size: "Ölçü", nominal: "Nominal", family: "Geçerli olduğu ürünler" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Sap ölçünüzle yapılandırın",
  },
  custom: {
    title: "Özel mühendislik",
    statement: "Şartnameye göre mühendislik.",
    sub: "Standart seri, başlangıç noktasıdır.",
    lead: "MAXIMUS, yayımlanmış yapılandırma matrislerinin ötesindeki teknik gereksinimleri değerlendirme, mühendislik, doğrulama ve üzerinde anlaşılan şartnameye göre üretim için kabul eder. Uygulanabilirlik inceleme yoluyla teyit edilir — akla gelebilecek her talep fiziksel veya ticari olarak uygulanabilir değildir.",
    scopeTitle: "Bir teknik brief neleri kapsayabilir",
    scope: ["Kafa ve kasa geometrisi", "Uzunluk", "Ağırlık", "Denge", "Swingweight", "Sertlik", "Twistweight", "Sap geometrisi", "Yapı", "Eşleştirilmiş setler", "Antrenman kasaları", "Kozmetik ve gravür", "Kimlik ve takım programları", "Kalıba bağlı geliştirme"],
    processTitle: "Süreç",
    process: [
      ["Tanımlama", "Tercih edilen hedefler, zorunlu sınırlar, kullanım amacı ve kabul edilebilir ödünler."],
      ["Mühendislik", "Platform ve kalıplar karşısında mühendislik değerlendirmesi."],
      ["Doğrulama", "Üzerinde anlaşılan şartnameye karşı doğrulama."],
      ["Şartname", "Ölçüm esasını ve toleransları içeren yazılı bir şartname."],
      ["Üretim", "Şartnameye göre üretim."],
      ["Ölçüm / kayıt", "Geçerli hassasiyet sınıfına göre ölçüm ve saklanan kayıtlar."],
    ],
    formTitle: "Teknik brief gönderin",
    formLead: "Tercih edilen hedefleri zorunlu sınırlardan ayırın. Sonuç, otomatik olarak kabul edilmiş bir üretim siparişi değil, bir teknik inceleme talebidir.",
    protected: "Katman dizilimi reçeteleri, kalıplar, tedarikçi kimlikleri, dahili maliyetlendirme ve korunan bilgi birikimi bu yol üzerinden paylaşılmaz.",
    cta: "Teknik brief gönderin",
  },
  training: {
    title: "Antrenman sistemleri",
    lead: "Kendi üretim standartlarına sahip iki antrenman ailesi, tek bir metodolojiyle birbirine bağlanır: antrenör liderliğinde çalışma, kayıtlar, yeniden değerlendirme ve performans oyununa geri aktarım.",
    sst: { h: "Sweet Spot Trainer", p: "Merkezden temas çalışması, sweet spot farkındalığı, raket kontrolü ve kademeli yükleme için dört ağırlıklı bir sistemde 50 in² küçültülmüş kafalı antrenman raketi." },
    spot: { h: "Spot Trainer", p: "Onaylı dört ağırlık temeli üzerinde, küçük ve yuvarlak bir temas hedefiyle temas noktası çalışması." },
    method: { h: "Metodoloji", p: "Hedefleri belirleyin, antrenör katılımıyla ekipmanı seçin, ilgili sistemi kullanın, kaydedin, yeniden değerlendirin, ayarlayın ve aktarın." },
    experience: "Elinize alın. Sallayın. Hissedin.",
    experienceP: "Deneme, fitting veya antrenör destekli tanıtım talep edin. Gönderilen bir talep, teyit edilmiş bir randevu değildir.",
    cta: "Fitting veya tanıtım talep edin",
    distinct: "Sweet Spot Trainer, Spot Trainer ve ayrı her tanıtım cihazı farklı ürünlerdir ve asla birleştirilmez.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Kendi üretim standardına sahip ayrı bir antrenman kategorisi. 50 in² kafa, dikkati temas noktasına odaklar; dört ağırlık yükleme kademesini sağlar.",
    baseline: "Teyit edilmiş temel",
    columns: { head: "Kafa", length: "Uzunluk", pattern: "Kordaj deseni", grips: "Fabrika sap ölçüleri" },
    systemTitle: "Dört raketli sistem",
    detailsTitle: "Yapı detayları",
    systemLead: "Teslim edildiği haliyle ağırlık ve denge. Ölçüm esası ayrıca kaydedilir ve henüz yayımlanmadı.",
    purposeTitle: "Amaç",
    purpose: ["Merkezden temas çalışması", "Sweet spot farkındalığı", "Raket kontrolü", "Kademeli yükleme", "Antrenör liderliğinde gelişim", "Oyuncunun performans raketine geri dönüş"],
    heavy: "400 g model, kontrollü bir antrenman yapılandırmasıdır. Çocuklara, yeni başlayanlara veya her oyuncuya otomatik olarak önerilmez; yükü, süreyi ve kademelenmeyi antrenör belirler.",
    precisionNote: "P2.5, P1.5 ve P0.5 performans hassasiyet sınıfları bu antrenman ailesine otomatik olarak uygulanmaz. Antrenman üretim toleransları, ailenin kendi onaylı şartnamesine uyar.",
    health: "Tenisçi dirseğinin önlenmesi ya da tedavisi, sakatlıkların ortadan kaldırılması veya garantili gelişim vaat edilmez.",
    cta: "Sweet Spot Trainer tanıtımı talep edin",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Küçük ve yuvarlak bir temas hedefiyle temas noktası çalışması. Onaylı dört ağırlık temeli üzerine kurulmuş, kendi görsel kimliğine sahip ayrı bir ürün.",
    purposeTitle: "Teyit edilmiş amaç",
    purposeP: "Oyuncuya hassas bir temas noktasını bulmayı ve tekrarlamayı çalıştırmak.",
    weightsTitle: "Ağırlık kademelenmesi",
    weightsP: "Ağırlık kademelenmesi, onaylı Sweet Spot Trainer ağırlık temelini izler. Denge değerleri ve diğer Sweet Spot Trainer şartnameleri Spot Trainer'a kopyalanmaz.",
    dims: "Hedefin tam ölçüleri henüz yayımlanmadı.",
    grips: "Fabrika sap mimarisi L0–L7.",
    notes: ["Performans hassasiyet sınıfları otomatik olarak uygulanmaz.", "Küçültülmüş bir klasik raket değildir ve hiçbir kordaj deseni yayımlanmaz.", "Spot Trainer, Sweet Spot Trainer ve ayrı her tanıtım cihazı birbirinden ayırt edilebilir kalır."],
    cta: "Spot Trainer hakkında soru sorun",
  },
  methodology: {
    title: "Metodoloji ve ürün deneyimi",
    lead: "Ekipman, yapılandırılmış bir gelişim yolculuğunun bir parçasıdır. Yöntem, bir ürün etiketiyle değil, oyuncunun hedefleriyle başlar.",
    stepsTitle: "Gelişim yolculuğu",
    steps: [
      ["Hedefleri belirleme", "Oyuncunun hedefleri ve başlangıç noktası."],
      ["Ekipman seçimi", "Antrenör katılımıyla uygun ekipmanın seçilmesi."],
      ["Sistemi kullanma", "Antrenör liderliğinde ilgili antrenman sistemi."],
      ["Kayıt", "Uydurma puanlar olmadan, gerçek katılımın gözlemleri."],
      ["Yeniden değerlendirme", "Karşılaştırılabilir kontrol noktaları."],
      ["Ayarlama", "Yapılandırma veya program ayarlamaları."],
      ["Aktarım", "Öğrenilenlerin performans oyununa geri aktarılması."],
    ],
    educationTitle: "Eğitim yolları",
    education: { player: "Oyuncular — yapılandırmayı, yüklemeyi ve kademelenmeyi anlamak.", parent: "Ebeveynler — gelişimin sürekliliği, uygun ekipman, kayıtlar ve haklar.", coach: "Antrenörler — antrenman sistemleri, fitting, değerlendirme ve yetkili program kullanımı." },
    evidenceTitle: "Kanıt disiplini",
    evidenceP: "Gerçek katılımın kayıtları ve gözlemler, sınıflandırmalarıyla birlikte saklanır — katılımcı beyanı, veli teyidi, antrenör doğrulaması veya sistem ölçümü. Gelişim, puanlar ve doğrulama asla uydurulmaz.",
    experienceTitle: "Elinize alın. Sallayın. Hissedin.",
    experienceP: "Deneme, fitting veya antrenör destekli tanıtım talep edilebilir. Gönderilen bir talep, teyit edilmiş bir randevu değildir.",
    cta: "Fitting veya tanıtım talep edin",
    cta2: "Antrenör iş birliği talebi",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — yönlendirmeli ekipman profili",
    title: "MAXIMUS GPS",
    lead: "Yönlendirmeli bir ekipman profili. Yalnızca sizin için geçerli olanları yanıtlayın; yanıtlarınızı gözden geçirip düzeltin; bir özet, geçerli yapılandırma yönleri ve gerçek bir sonraki adım alın.",
    honesty: "Bu sürümde otomatik fitting kuralları onaylı değildir. Bu nedenle GPS, net bir gereksinim özeti üretir ve yapılandırma yönlerine işaret eder; ekipman ayrıntıları uzman incelemesine yönlendirilir.",
    rulesVersion: "Kural sürümü",
    dataVersion: "Ürün verisi sürümü",
    steps: { role: "Rol", sport: "Spor", experience: "Deneyim", objectives: "Hedefler", style: "Oyun tarzı", equipment: "Mevcut ekipman", preference: "Tercihler", coach: "Antrenör katılımı", ageBand: "Yaş aralığı", review: "Gözden geçirme" },
    notStored: "Bu tarayıcıda saklanmaz.",
    ageNote: "Yalnızca talebi yönlendirmek için kullanılır. İsim, doğum tarihi veya tıbbi bilgi istenmez.",
    q: {
      role: "Sizi hangisi tanımlıyor?",
      sport: "Hangi spor?",
      experience: "Deneyim seviyesi",
      objectives: "Sizin için en önemlisi ne? (en fazla üç seçim)",
      style: "Biliyorsanız oyun tarzı",
      equipment: "Varsa mevcut ekipman",
      equipmentHint: "Biliyorsanız marka ve model, ağırlık veya sap ölçüsü. İsteğe bağlı.",
      preference: "Tercih edilen yapılandırma veya bilinen sap ölçüsü",
      grip: "Bilinen sap ölçüsü",
      coach: "Ekipman kararlarınıza bir antrenör dahil mi?",
      ageBand: "Oyuncunun yaş aralığı (yalnızca talebin doğru yönlendirilmesi için kullanılır)",
    },
    roles: { player: "Oyuncu", parent: "Ebeveyn veya veli", coach: "Antrenör", club: "Kulüp veya akademi", other: "Diğer" },
    sports: { tennis: "Tenis", padel: "Padel", pickleball: "Pickleball", squash: "Squash", badminton: "Badminton", other: "Diğer raket sporu" },
    sportNote: "Ürünler tenis için mevcuttur. Diğer sporlar geliştirme yönleridir; ilginiz ilgili program için kaydedilir.",
    experience: { beginner: "Yeni başlayan", developing: "Gelişmekte olan", intermediate: "Orta seviye", advanced: "İleri seviye", competitive: "Turnuva oynayan", professional: "Profesyonel" },
    objectives: { control: "Kontrol", power: "Güç", spin: "Spin", comfort: "Konfor", manoeuvrability: "Manevra kabiliyeti", development: "Uzun vadeli gelişim", competition: "Müsabaka", training: "Antrenman sistemi", team: "Takım veya eşleştirilmiş set", personal: "Kişiselleştirme" },
    styles: { baseline: "Kort arkası", allcourt: "Tüm kort", attacking: "Atak", defensive: "Defans", coach: "Antrenör seçimi", unknown: "Emin değilim" },
    ageBands: { u10: "10 yaş altı", u14: "10–13", u18: "14–17", adult: "18 ve üzeri" },
    output: {
      title: "Ekipman profiliniz",
      status: "Uzman incelemesi gerekiyor",
      statusP: "Bu sürümde otomatik eşleştirme üretilmez. Profiliniz uzman incelemesi için özetlenmiştir.",
      directionsTitle: "Geçerli yapılandırma yönleri",
      directionsP: "Belirttiğiniz hedeflere ve her serinin beyan edilen oyun yönüne dayanır. Bu bir yöndür, fitting önerisi değildir.",
      trainingHint: "Hedefleriniz bir antrenman sistemini içeriyor: Sweet Spot Trainer ve Spot Trainer'a bakın.",
      teamHint: "Eşleştirilmiş setler yapılandırıcı üzerinden talep edilir ve yazılı olarak teyit edilir.",
      next1: "Profili uzman incelemesine gönderin",
      show: "Profilimi göster",
      configure: "Yapılandır",
      sendP: "Profilinizi uzman incelemesi için MAXIMUS'a gönderin. Talep numarası anında gösterilir; yanıt yazılı olarak gelir.",
      otherSport: "MAXIMUS raketleri tenis için mevcuttur. Diğer raket sporları için hiçbir tenis serisi önerilmez; ilginiz bir geliştirme yönü olarak kaydedilir.",
      noDirection: "Hedefleriniz tek bir oyun yönüne işaret etmiyor. Uzman incelemesi bir yapılandırma önerir.",
      incomplete: "Bazı zorunlu yanıtlar eksik — bunları tamamlamak için “Yanıtları düzenle” seçeneğini kullanın.",
    },
    privacy: "GPS hiçbir sağlık bilgisi ve hiçbir çocuk kimlik bilgisi istemez. Bu tarayıcı oturumunda yalnızca çoktan seçmeli yanıtlar tutulur; serbest metin saklanmaz.",
  },
  build: {
    title: "Kendi raketinizi yapılandırın",
    lead: "Bir talep yapılandırın: seri, hassasiyet sınıfı, listedeki ağırlık veya özel hedef, sap ölçüsü, talep edilen hedefler, kişiselleştirme, eşleştirilmiş setler ve adet. Sonuç, talep numarası olan bir yapılandırma talebidir — stok kodu, fiyat, teslim tarihi veya sertifika değildir.",
    steps: { series: "Seri", cls: "Hassasiyet sınıfı", weight: "Ağırlık", grip: "Sap ölçüsü", targets: "Hedefler", personal: "Kişiselleştirme", set: "Set ve adet", use: "Kullanım", review: "Gözden geçirme" },
    q: {
      series: "Bir seri seçin",
      cls: "Bir hassasiyet sınıfı seçin",
      weightMode: "Ağırlık",
      listed: "Listedeki ağırlık",
      customWeight: "Talep edilen ağırlık (g)",
      balanceShown: "Bu ağırlık için hesaplanmış denge",
      balanceRequest: "Talep edilen denge (mm)",
      grip: "Fabrika sap ölçüsü",
      targetsTitle: "Talep edilen hedefler",
      swingweight: "Talep edilen swingweight (kg·cm²)",
      stiffness: "Talep edilen sertlik (RA)",
      basis: "Talep edilen değerlerin ölçüm esası",
      engraving: "Gravür metni",
      engravingHint: "İsim, baş harfler veya numara. Latin harfleri, rakamlar, boşluk, kısa çizgi, kesme işareti ve nokta; en fazla 24 karakter. Diğer alfabeler, görsel onayı için kabul edilir.",
      engravingType: "Kişiselleştirme",
      types: { none: "Yok", name: "Oyuncu adı", initials: "Baş harfler", number: "Set numarası", academy: "Antrenör veya akademi tanımı", team: "Takım programı" },
      set: "Tek raket veya eşleştirilmiş set",
      use: "Kullanım amacı",
      uses: { play: "Kişisel oyun", competition: "Müsabaka", coaching: "Antrenörlük", team: "Takım veya akademi", retail: "Perakende veya distribütörlük değerlendirmesi", other: "Diğer" },
      notes: "Ek teknik gereksinimler",
    },
    classes: { "P2.5": "P2.5 — ölçeklenebilir performans çekirdeği", "P1.5": "P1.5 — ileri hassasiyet", "P0.5": "P0.5 — profesyonel, bireysel olarak kontrol edilen" },
    stiffExactShort: "sertlik, yerleşik fabrika protokolü altında beyan edilen hedef RA değerine uygundur",
    clsNote: "Her sınıf dört parametreyi kontrol eder. P0.5, tanımlı bir ölçüm protokolü altında sıkı bir toleranstır — sıfır hata değildir. Seri kimliği, sertifikalar ve eşleştirilmiş set dokümantasyonu yalnızca siparişinizin programı bunları uyguladığı durumlarda geçerlidir.",
    listedNote: "Serinin teyit edilmiş matrisinden.",
    customNote: "Matrisin dışında, teknik olarak incelenen bir ağırlık.",
    balanceCaption: "Listedeki her ağırlık, sap dibinden mm cinsinden hesaplanmış dengesini gösterir. Hesaplanmış değerler bireysel ölçüm değildir.",
    spinNote: "SPIN ağırlıkları, talep edilen ağırlık mimarisini oluşturur. SPIN için denge, swingweight ve sertlik verilmemiştir; bunlar teknik incelemede tanımlanır.",
    customHint: "Tam gram, yalnızca rakam. Özel ağırlık, teknik inceleme talebidir; uygulanabilirlik yazılı olarak teyit edilir ve hiçbir değer yuvarlanmaz.",
    gripNote: "fabrikada üretilen karbon sap geometrisi, overgrip ile kalınlaştırma değil",
    targetsLead: "İsteğe bağlı. Yalnızca ihtiyaç duyduğunuz değerleri girin. Her biri, yayımlanmış bir şartname olarak değil, teknik inceleme için talep edilen hedef olarak kaydedilir.",
    basisHint: "Özel bir ağırlık veya herhangi bir hedef talep ettiğinizde zorunludur: değerler kordajsız mı, kordajlı bir raketi mi ifade ediyor?",
    inputRange: "Kabul edilen giriş: {min}–{max}.",
    inputRangeNote: "Giriş aralıkları yalnızca imkânsız girişleri ayıklar. Üretim kabiliyetini tanımlamaz.",
    listedBasis: "listedeki değerler — ölçüm esası yazılı şartnamede teyit edilir",
    notStored: "Bu tarayıcıda saklanmaz; sayfayı yeniden yüklerseniz tekrar girin.",
    artworkReview: "görsel onayı gerekiyor",
    previewNote: "Görsel önizleme gösterilmez: bu model için onaylı bir gravür şablonu henüz yayımlanmadı. Metniniz görsel onayı için toplanır.",
    teamSub: "set başına 4–99 raket",
    setsLabel: { individual: "Raket sayısı", pair: "Eşleştirilmiş ikili sayısı", triple: "Eşleştirilmiş üçlü sayısı", team: "Takım seti sayısı" },
    teamSizeLabel: "Takım seti başına raket",
    totalLabel: "Toplam raket",
    racquetsUnit: "raket",
    setRule: "Adet, set sayısını ifade eder: eşleştirilmiş ikili set başına 2 raket, eşleştirilmiş üçlü 3 rakettir.",
    restart: "Yeni bir yapılandırma başlatın",
    notices: { weightCleared: "{w} g, {series} matrisinde yok; bu nedenle ağırlık temizlendi. Listedeki bir ağırlığı seçin veya özel hedef talep edin." },
    reviewTitle: "Yapılandırma talebi",
    reviewP: "Yapılandırmayı kontrol edin, ardından iletişim bilgilerinizi ekleyin. Talep, bir talep numarasıyla kaydedilir ve yazılı olarak yanıtlanır; temin durumu ve ticari şartlar yazılı olarak teyit edilir.",
    reviewErrors: "Bazı yapılandırma yanıtları dikkat gerektiriyor:",
    edit: "Düzenle",
    fieldNames: { series: "Seri", cls: "Hassasiyet sınıfı", mode: "Ağırlık seçimi", weight: "Listedeki ağırlık", customWeight: "Talep edilen ağırlık", basis: "Ölçüm esası", balanceReq: "Talep edilen denge", sw: "Talep edilen swingweight", ra: "Talep edilen sertlik", grip: "Sap ölçüsü", ptype: "Kişiselleştirme", engraving: "Gravür metni", setType: "Set türü", sets: "Adet", teamSize: "Takım seti başına raket", use: "Kullanım amacı", notes: "Ek gereksinimler" },
    status: { listed: "listedeki ağırlık", requestedArchitecture: "talep edilen ağırlık mimarisi", technicalReview: "teknik inceleme talebi", notPublished: "verilmemiş", requestedCondition: "talep edilen durum" },
    chooseLink: "Hangi serinin size uygun olduğundan emin değil misiniz? Seçim için yardım alın",
    cta: "Yapılandırma talebini gönderin",
  },
  experience: {
    title: "Deneme ve fitting",
    statement: "Elinize alın. Sallayın. Hissedin.",
    lead: "Deneme, fitting veya antrenör destekli tanıtım talep edin. Talepler incelenir ve yazılı olarak yanıtlanır; gönderilen bir talep, teyit edilmiş bir randevu değildir.",
    optionsTitle: "Neler talep edilebilir",
    options: ["Raket denemesi", "Fitting seansı", "Antrenör destekli tanıtım", "Sweet Spot Trainer veya Spot Trainer tanıtımı", "Takım veya akademi tanıtım günü"],
    formTitle: "Fitting veya tanıtım talebi",
  },
  engineering: {
    title: "Mühendislik ve üretim",
    statement: "Uçaklar. Yatlar. Raketler.",
    lead: "Üç ortamda tek bir mühendislik felsefesi: bir uçağı şekillendiren ilkeler, bir yatı açık suda yönlendiren hassasiyet, her MAXIMUS raketini tanımlayan performans. Bu bir mühendislik anlatısıdır — uçak sertifikasyonu, yat sahipliği, fabrika sahipliği veya doğrudan malzeme aktarımı iddiası değildir.",
    manifesto: ["İyi mühendisliğin sınırı olmadığına inanıyoruz.", "Tek felsefe. Ödünsüz mühendislik."],
    capabilityTitle: "Üretim kabiliyeti",
    capabilityLead: "Kabiliyet bir slogan olarak değil, bir sıra olarak gösterilir.",
    sequence: [
      ["Şartname", "Seri, hassasiyet sınıfı, ağırlık, denge, swingweight, sertlik hedefi, sap geometrisi, kişiselleştirme."],
      ["Üretim", "Şartnameye göre üretilen, kasadan sapa tamamen karbon yapı."],
      ["Kalite kontrol", "Hassasiyet sınıfına göre ölçüm ve kayıtlar: üretim kayıtları, bireysel kayıtlar ve izlenebilirlik, bireysel sertifikasyon."],
      ["Tekrarlı üretim", "Partiler arasında, beyan edilen bir şartnameye karşı tekrarlanabilir tepki."],
      ["İzlenebilirlik", "Sınıfın öngördüğü durumlarda seri kimliği, parti izlenebilirliği ve Hassasiyet Sertifikası."],
    ],
    capacityNote: "Üretim kapasitesi, teslim süreleri, asgari miktarlar ve teslim programları; teyit edilmiş siparişlere ve üzerinde anlaşılan bir sevkiyat takvimine karşı her program için yazılı olarak teyit edilir.",
    truth: "Kapasite; çıktı, stok, garantili bir teslim tarihi veya bir üretim tesisinin sahipliği değildir.",
    cta: "Distribütörlük ve ülke geliştirme",
    cta2: "Teknik brief gönderin",
  },
  ecosystem: {
    title: "MAXIMUS ekosistemi",
    lead: "Tek anahtar. Açtığı kapılar bunlar. Her düğümün bir açıklaması, doğru bir durumu ve uygun bir sonraki adımı var.",
    words: ["Mühendislik", "Performans", "İnovasyon", "Topluluk", "Fırsat", "Amaç"],
    nodes: {
      engineering: { h: "Raket mühendisliği ve üretimi", p: "Şartnameye göre mühendisliği yapılan, kalite kayıtları ve izlenebilirlikle üretilen tamamen karbon raketler.", a: "Mühendislik ve üretim" },
      precision: { h: "Hassasiyet ve bireysel yapılandırma", p: "Dört parametre, üç hassasiyet sınıfı, sekiz sap ölçüsü ve özel mühendislik.", a: "Hassasiyet ve sertlik" },
      training: { h: "Antrenman ve metodoloji", p: "Sweet Spot Trainer, Spot Trainer ve yapılandırılmış bir gelişim yolculuğu.", a: "Antrenman sistemleri" },
      development: { h: "Oyuncu ve antrenör gelişimi", p: "Antrenör liderliğinde seçim, kayıtlar, yeniden değerlendirme ve eğitim yolları.", a: "Metodoloji" },
      identity: { h: "Kişisel kimlik ve kişisel markalar", p: "Gravürden, haklarla yönetilen kişisel veya profesyonel bir markaya.", a: "Kişisel markalar" },
      owners: { h: "Sahip kayıtları, bilgi ve haklar", p: "Ekipman, gelişim ve hak kayıtları için önerilen, izne dayalı bir sahip kasası.", a: "Sahipler ve sahip kasası" },
      mipa: { h: "MIPA köken kaydı ve dahili kontrol", p: "Dahili fikri mülkiyet, köken ve doküman kontrolü katmanı.", a: "Hukuki kimlik ve kontrol" },
      digital: { h: "Dijital altyapı ve Blockchain 5.0 yönü", p: "Beyan edilen teknoloji yönü olarak köken, izlenebilir kayıtlar, izne dayalı kanıt ve ürün kimliği.", a: "Teknoloji yönü" },
      licensing: { h: "Sözleşmeye dayalı lisanslama ve telif programları", p: "Şartları her sözleşmede tanımlanan lisanslı markalar, ürünler ve hak paketleri.", a: "Lisanslama yolları" },
      families: { h: "Aile katılımı ve program avantajları", p: "Bilgiye dayalı kararlar, süreklilik, saklanan kayıtlar ve programla tanımlanmış avantajlar.", a: "Aileler ve ebeveynler" },
      network: { h: "MAXIMUS Sports Network", p: "Oyuncular, antrenörler, kulüpler, akademiler, hizmet sağlayıcılar, işletmeciler ve bölgesel iş ortakları.", a: "Sports Network" },
      market: { h: "Kulüpler, akademiler, distribütörlük ve ülke geliştirme", p: "Yazılı yeterlilik değerlendirmesiyle takım programları, perakende, distribütörlük ve bölge geliştirme.", a: "İş birliği yolları" },
      institutional: { h: "Kurumsal programlar, eğitim, inovasyon ve sosyal etki", p: "Bir programın bu rolü belirlediği durumlarda MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) tarafından sağlanan kurumsal katman.", a: "Kurumsal programlar" },
      extensions: { h: "Gelecekteki raket sporları ve MAXIMUS giyim uzantıları", p: "Geliştirme yönleri olarak padel, pickleball, squash, badminton, racquetball, plaj tenisi ve giyim.", a: "Raket sporları" },
    },
    boundaryTitle: "Sınırlar",
    boundary: [
      "Bir raketin satın alınması; kurumsal üyelik, yönetim hakkı, telif payı veya yatırım hakkı doğurmaz.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC), yalnızca bir programın bu rolü belirlediği durumlarda kurumsal işletmecidir; ekipman satışları kendi gerçek sözleşme tarafını belirtir.",
      "Hibeler, hayır kurumu statüsü, vergi uygulaması ve düzenleyici izinler ülkeler arasında otomatik olarak geçerli olmaz.",
    ],
    techTitle: "Teknoloji yönü",
    techP: "Blockchain 5.0, MAXIMUS'un beyan ettiği teknoloji yönüdür. İşlevsel amaçları; köken, izlenebilir kayıtlar, izne dayalı kanıt, ürün kimliği ve nitelikli ticari olayların mutabakatıdır. Hiçbir uzlaşma mekanizması, işlem kapasitesi, düğüm ağı, akıllı sözleşme adresi, token veya bağımsız sertifikasyon beyan edilmez ve hayata geçirilmiş bir uygulama iddia edilmez. Kişisel bilgiler, çocuklara ait kayıtlar ve gizli sözleşmeler varsayılan olarak asla herkese açık, değiştirilemez bir sisteme konulmaz.",
  },
  brands: {
    title: "Kişisel markalar ve marka elçileri",
    statement: "Oyuncudan markaya. Antrenörden markaya.",
    lead: "Kişisel markaya ayrılmış bir yol. MAXIMUS'un katılımı, yalnızca rakette bir isim değil; marka geliştirme ve üzerinde anlaşılan tanıtımı da içerir.",
    progressionTitle: "Öngörülen ilerleyiş",
    progression: [
      ["Doğrulanmış kimlik", "Doğrulanmış bir kimlik ve gelişim geçmişi."],
      ["Ayırt edici marka", "Ayırt edici bir kişisel veya profesyonel marka."],
      ["Hakları temizlenmiş içerik", "Hakları temizlenmiş içerik ve onaylı ürün kimliği."],
      ["Mühendislik ve koleksiyonlar", "Anlaşılan durumlarda mühendislik ve koleksiyon geliştirme."],
      ["Tanıtım", "Üzerinde anlaşılan MAXIMUS kanalları ve iş birlikleri üzerinden tanıtım."],
      ["Katılım", "Nitelikli satışlara veya lisanslamaya sözleşmeye dayalı katılım."],
      ["Raporlama", "Sözleşme kapsamında şeffaf raporlama."],
    ],
    royaltiesTitle: "Telif payları ve lisanslama",
    royalties: [
      "Telif payları; tanımlanmış lisanslı markaya, ürüne, işleme veya hak paketine bağlanır.",
      "“Dünya çapındaki satışlar”, sözleşmenin kapsamı içindeki nitelikli satışlar anlamına gelir — ilgisiz her MAXIMUS raketi değil.",
      "Oranlar, hesaplama esası, bölgeler, süre, iadeler, kesintiler, raporlama, ödeme ve doğrulama ilgili sözleşmeyle tanımlanır. Varsayılan bir telif payı yüzdesi yayımlanmaz.",
      "Üzerinde anlaşılmış bir kapsam olmadan hiçbir küresel kampanya, medya bütçesi, sponsorluk sonucu veya ticari başarı vaat edilmez.",
    ],
    cta: "Marka iş birliği talebi gönderin",
    cta2: "Antrenör iş birliği talebi",
  },
  families: {
    title: "Aileler ve ebeveynler",
    lead: "Bilgiye dayalı ekipman kararları, gelişimin sürekliliği, saklanan bilgi ve haklar, katılımın görünürlüğü ve gelecekteki faaliyetleri destekleyebilecek, programla tanımlanmış avantajlar.",
    nowTitle: "Şimdi mevcut",
    now: ["Yazılı olarak aile ve gelişim talepleri.", "Antrenör katılımlı ekipman seçimi, fitting ve tanıtım talepleri.", "Özel kayıtlar: çocuk profilleri varsayılan olarak asla yayımlanmaz ve ticarileştirilmez.", "Ebeveynler için eğitim yolu: yapılandırma, yükleme, kademelenme, kayıtlar ve haklar."],
    plannedTitle: "Planlanan",
    planned: ["Nakit faiz yerine, ekosistem içindeki mal ve hizmetler için kullanılabilen, programla tanımlanmış katılım avantajları.", "Veli izinleri ve 18 yaşında kontrolün devri ile, önerilen sahip kasasında sahip ve aile kayıtları."],
    categoriesTitle: "Ayrı tutulanlar",
    categories: ["Lisanslı haklardan veya nitelikli satışlardan doğan sözleşmeye dayalı telif payları", "Bir programla tanımlanmış katılım avantajları", "Satın alma veya hizmet kredileri", "Ön ödemeler", "Kurumsal üyelik"],
    categoriesP: "Bu kategoriler asla birbirinin yerine geçebilir sayılmaz.",
    statusTitle: "Aile programının gerçek durumu",
    journeyTitle: "Aile yolu",
    journey: [
      ["Hedef", "Oyuncunun bir sonraki adımda ulaşmak istediği şey."],
      ["Mevcut seviye", "Oyuncunun bugün bulunduğu nokta."],
      ["Antrenör", "Ekipman kararlarına bir antrenörün katılıp katılmadığı."],
      ["Ekipman", "Gerektiğinde antrenman sistemleri dahil, bu aşamaya uygun ekipman."],
      ["Üzerinde anlaşılan çalışma", "Önceden anlaşılmış, antrenör liderliğinde kullanım."],
      ["Gözden geçirme", "Karşılaştırılabilir kontrol noktalarında yeniden değerlendirme."],
    ],
    brief: {
      who: "Her aşamadaki oyuncuların ebeveynleri ve velileri.",
      value: "Uygun ekipman, antrenör katılımı ve bir sonraki gelişim adımı hakkında yazılı bir yanıt.",
      now: "Yazılı olarak aile talepleri; antrenör katılımlı seçim; özel kayıtlar — çocuk profilleri asla yayımlanmaz.",
      next: "Aşağıdaki aile talebini gönderin. Talep numarasını anında alırsınız.",
    },
    formTitle: "Aile talebi",
    formNote: "Bir ebeveyn veya veli tarafından doldurulmalıdır. Çocuğun adını, doğum tarihini, okulunu veya tıbbi bilgilerini eklemeyin.",
    noPromise: "Satın alma; telif payı, yatırım getirisi, sponsorluk veya bir çocuğun gelişiminin finanse edilmesini vaat etmez.",
    statusP: "Bu sürüm modeli açıklıyor ve program taleplerini kabul ediyor. Nitelikli olaylar, hak sahipleri, finansman kaynağı, hesaplama esası, izin verilen kullanımlar, muhasebe uygulaması, iadeler, geri alımlar, geçerlilik süresi, devredilebilirlik, programın kapatılması ve uyuşmazlıkların ele alınması yazılı olarak tanımlanana kadar tahakkuk, ödeme ve kullanım mümkün değildir. Hiçbir bakiyenin asla azalmayacağı vaat edilmez, hiçbir katılım tüm antrenmanları karşılamaz ve hiçbir anapara koruması ima edilmez.",
    cta: "Aile veya gelişim talebi gönderin",
  },
  owners: {
    title: "Sahipler ve sahip kasası",
    lead: "Sahip kasası; ekipman, gelişim, bilgi, içerik ve belgelenmiş hakların izne dayalı, önerilen bir kaydıdır. Planlanan sahip mimarisinin bir parçası olarak sunulur: canlı hesap, bakiye, sertifika veya başarı gösterilmez.",
    nowTitle: "Mevcut sahipler için şimdi",
    now: ["Sahip talepleri: ürün veya seri referansı, kurulum, servis ve kayıt talepleri yazılı olarak.", "Hassasiyet sınıfının öngördüğü durumlarda ürünle birlikte teslim edilen Hassasiyet Sertifikası ve eşleştirilmiş set dokümantasyonu."],
    archTitle: "Planlanan kasa mimarisi",
    arch: ["Ürün kimliği ve seri referansları", "Yapılandırma ve geçerli kalite kontrol sertifikaları", "Servis ve kurulum geçmişi", "Oyuncu veya antrenör gelişim kayıtları", "Nitelikler ve doğrulanmış başarılar", "Hakları temizlenmiş medya ve telifi size ait materyaller", "Lisanslar, izinler ve sözleşme referansları", "Kişisel marka programı kayıtları", "Geçerli telif beyanları veya katılım avantajları"],
    separationTitle: "Sahiplik ne anlama gelir",
    separation: [
      "Fiziksel bir raketin sahipliği; telif hakkının, bir lisansın, sözleşmeye dayalı bir hakkın veya bunları tanımlayan bir kaydın sahipliğinden ayrıdır.",
      "Saklanan bir doküman veya blockchain kaydı, bir hukuki hakkın var olduğunun ya da devredildiğinin otomatik kanıtı değildir.",
      "Kanıt, sınıflandırmasını korur: katılımcı beyanı, veli teyidi, antrenör doğrulaması, sistem ölçümü.",
      "Reşit olmayanlar için: özel kayıtlar, veli izinleri, yayımlanmayan çocuk profilleri ve varsayılan olarak kimliğin ticarileştirilmemesi.",
      "Dışa aktarma, düzeltme, erişim kontrolü ve kontrolün uygun şekilde devri, tasarımın parçasıdır.",
    ],
    techTitle: "Blockchain 5.0 ve MxSN",
    techP: "Blockchain 5.0, beyan edilen teknoloji yönüdür; MxSN ise onay, teslim, kanıt, haklar ve raporlama için izne dayalı bir ağın kavramlarını tanımlar. Operasyonel bir uygulama beyan edilmez. Uygulamanın veri modeli, bugün bir bağlantının var olduğu izlenimi verilmeden, daha sonra belgelenmiş bir arayüz üzerinden entegre olacak şekilde kurulmuştur.",
    cta: "Sahip talebi",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Oyuncular, antrenörler, kulüpler, akademiler, hizmet sağlayıcılar, program işletmecileri ve bölgesel iş ortakları arasındaki bağlantı.",
    functionsTitle: "Olası işlevler",
    functions: ["Keşif", "Tanıştırma", "Gelişim programları", "Ekipman desteği", "Etkinlikler", "Hizmet erişimi", "İş ortağı fırsatları"],
    statusTitle: "Gerçek durum",
    statusP: "Henüz herkese açık bir rehber yayımlanmadı: yalnızca kimliği, ilişkisi ve görünme izni belirlenmiş katılımcılar listelenecek. Bir kulübe gönderilen teklif bir iş birliği değildir ve aday bir distribütör, atanmış distribütör değildir. Rehberin yayımlanması, randevu alma, mesajlaşma ve ticari işlemler ayrıca kontrol edilir ve etkin değildir.",
    cta: "Ağa başvurun",
  },
  partnerships: {
    title: "İş birliği yolları",
    lead: "Önce yazılı yeterlilik değerlendirmesi. Her yol, role özgü bir talebe çıkar; ticari şartlar yazılı olarak izler.",
    commercialTitle: "Platformun olası ticari faaliyetleri",
    commercial: ["Ekipman", "Özel mühendislik", "Kişiselleştirme", "Takım ve akademi programları", "Antrenman sistemleri", "Sözleşmeye dayalı lisanslama", "Distribütörlük", "Onaylı hizmetler", "Gelecekteki ürün kategorileri"],
    boundary: "Ülke hakları, münhasırlık, bölge ücretleri ve distribütör marjları görüşmeye tabi şartlardır. Hiçbir gelir, tahmin, değerleme, pazar payı, getiri, finansman taahhüdü veya adı açıklanmayan iş birliği yayımlanmaz.",
    routes: {
      coaches: {
        title: "Antrenörler",
        lead: "Antrenman sistemleri, fitting, profesyonel kimlik, yetkili programlar, kişisel marka fırsatları ve ekipman tedariki.",
        points: ["Antrenör liderliğindeki çalışmada Sweet Spot Trainer ve Spot Trainer.", "Yapılandırma matrisleri ve sekiz fabrika sap ölçüsüyle fitting.", "Coach-to-Brand: doğrulanmış bir profesyonel profil ve haklarla yönetilen bir alt marka.", "Yetkili program kullanımı yazılı bir sözleşmeye tabidir."],
        cta: "Antrenör iş birliği talebi gönderin",
        brief: {
          who: "Bağımsız antrenörler ve antrenör ekipleri.",
          value: "Antrenör liderliğindeki çalışma için antrenman sistemleri, seri matrisleri ve sekiz fabrika sap ölçüsüyle fitting, profesyonel bir kimliğe giden yol.",
          now: "Yazılı olarak antrenör talepleri. Hiçbir komisyon, kazanç veya yönlendirme oranı yayımlanmaz ya da ima edilmez.",
          next: "Aşağıdaki antrenör talebini gönderin. Şartlar yazılı olarak izler.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Kulüpler ve akademiler",
        lead: "Takım ekipmanı, antrenman sistemleri, kişiselleştirme, gelişim programları, servis ve ağ katılımı.",
        points: ["Yapılandırıcı üzerinden talep edilen takım ve eşleştirilmiş setler.", "Yapılandırılmış gelişim için antrenman sistemleri ve metodoloji.", "Onaylı bölgelerde takım programları için kişiselleştirme.", "Tanıtım günleri, fitting seansları ve ağ katılımı."],
        cta: "Kulüp veya akademi brief'i gönderin",
        brief: {
          who: "Kulüpler, akademiler ve takım programları.",
          value: "Takım ve eşleştirilmiş setler, antrenman sistemleri, takım programları için kişiselleştirme ve tanıtım günleri.",
          now: "Yazılı olarak kulüp ve akademi brief'leri; takım setleri yapılandırıcı üzerinden talep edilir.",
          next: "Aşağıdaki kulüp veya akademi brief'ini gönderin.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribütörlük ve ülke geliştirme",
        lead: "Ürün gamı, üretim koordinasyonu, teknik kabiliyet, bölge geliştirme ve gizli ticari yeterlilik değerlendirmesi.",
        points: ["Karşı tarafın, bölgenin ve kanalın yazılı yeterlilik değerlendirmesi.", "Yapılandırma matrislerinden ve hassasiyet sınıflarından tanımlanan ürün gamı.", "Bölge, münhasırlık, hacimler, fiyatlandırma ve ticari koruma, yazılı olarak kararlaştırılan ve görüşmeye tabi şartlardır.", "Sözleşme tarafı, ödeme şartları ve teslim esası her işlem için ayrıca belirlenir."],
        cta: "Distribütörlük veya ülke geliştirme talebi gönderin",
        brief: {
          who: "Perakendeciler, distribütörler ve ülke iş ortakları.",
          value: "Teyit edilmiş matrislerden, hassasiyet sınıflarından ve sap ölçüsü aralığından tanımlanan bir ürün gamı; bölgenin ve kanalın yazılı yeterlilik değerlendirmesiyle.",
          now: "Yazılı olarak distribütörlük talepleri. Bölge, münhasırlık, hacimler ve fiyatlandırma görüşmeye tabidir — hiçbiri bir form üzerinden verilmez.",
          next: "Aşağıdaki distribütörlük talebini gönderin.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Stratejik ve yatırım",
        lead: "Mühendislik kabiliyeti, yapılandırma derinliği, üretim modeli, pazara giriş yolları, fikri mülkiyet, hizmetler ve büyüme fırsatları.",
        points: ["Nitelikli stratejik görüşme veya kontrollü bilgi erişimi, yazılı yeterlilik değerlendirmesine tabidir.", "Herkese açık bilgi; onaylı ürün şartnameleri, yapılandırma mimarisi, doğrulanmış kabiliyetler ve program açıklamalarıyla sınırlıdır.", "Alıcıya özgü ekonomik veriler, maliyetlendirme, korunan metodoloji ve yayımlanmamış sözleşmeler yalnızca gizlilik sözleşmesi ya da sözleşme kapsamında paylaşılır."],
        cta: "Nitelikli stratejik görüşme talep edin",
        brief: {
          who: "Yatırımcılar ve stratejik iş ortakları.",
          value: "Mühendislik kabiliyeti, yapılandırma derinliği, üretim modeli, pazara giriş yolları ve fikri mülkiyet üzerine nitelikli bir görüşme.",
          now: "Hiçbir finansal veri, tahmin, değerleme veya getiri yayımlanmaz. Kontrollü bilgi, yazılı yeterlilik değerlendirmesine ve gizlilik sözleşmesine tabidir.",
          next: "Aşağıdan nitelikli bir stratejik görüşme talep edin.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Kurumsal programlar",
        lead: "Eğitim, erişim, inovasyon, gelişim kanıtı, sosyal etki ve uygun şekilde yapılandırılmış programlar.",
        points: ["Kurumsal programlar, programın bu rolü belirlediği durumlarda MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) üzerinden yapılandırılır.", "Kısıtlı program fonları ile ticari işlemler ayrı kalır.", "Bir talep, kabul edilmiş bir üyelik başvurusu değildir ve bir ekipman alıcısı kurumsal üye değildir.", "Hibeler, hayır kurumu statüsü, vergi uygulaması ve düzenleyici izinler ülkeye özgüdür ve asla varsayılmaz."],
        cta: "Kurumsal program talebi gönderin",
        brief: {
          who: "Kurumlar, eğitim ve gelişim programları.",
          value: "Eğitim, erişim, inovasyon ve gelişim kanıtı için uygun işletmeciyle yapılandırılmış programlar.",
          now: "Yazılı olarak kurumsal talepler. Bir talep, üyelik başvurusu değildir; bir ekipman satın alımı kurumsal üyelik değildir.",
          next: "Aşağıdaki kurumsal talebi gönderin.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Herkese açık ve kontrollü paylaşım",
    disclosure: {
      public: { h: "Herkese açık", p: "Onaylı ürün şartnameleri, yapı, yapılandırma mimarisi, antrenman amaçları, doğrulanmış kabiliyetler, program açıklamaları ve iş birliği yolları." },
      qualified: { h: "Nitelikli talep", p: "Teknik gereksinimler, miktarlar, bölge ilgisi, geliştirme kapsamı ve ilgili ticari görüşmeler." },
      controlled: { h: "Gizlilik sözleşmesi veya sözleşme kontrolünde", p: "Dahili formüller, ayrıntılı kalite kontrol protokolleri, katman dizilimleri, kalıplar, üretim yöntemleri, tedarikçi kimlikleri, maliyetlendirme, alıcıya özgü ekonomik veriler, korunan metodoloji, yayımlanmamış sözleşmeler ve hassas hak kayıtları." },
    },
  },
  contact: {
    title: "İletişim ve talepler",
    lead: "Talebinizin amacını seçin. Her form, talebi yönlendirmek ve değerlendirmek için yalnızca gerekli bilgileri toplar. Talepler yazılı olarak yanıtlanır.",
    email: "Email",
    instagram: "Instagram",
    legalLink: "Hukuki kimlik",
  },
  form: {
    purposeLabel: "Talebin amacı",
    purposes: {
      selection: "Raket seçiminde yardım",
      product: "Ürün talebi",
      fitting: "Fitting veya tanıtım",
      technical: "Teknik brief",
      config: "Yapılandırma talebi",
      gps: "GPS ekipman profili",
      coach: "Antrenör iş birliği",
      club: "Kulüp veya akademi brief'i",
      distribution: "Distribütörlük veya ülke geliştirme",
      brand: "Marka iş birliği veya marka elçiliği",
      family: "Aile veya gelişim talebi",
      institutional: "Kurumsal program",
      strategic: "Stratejik veya yatırım görüşmesi",
      owner: "Sahip talebi",
      network: "Sports Network başvurusu",
      general: "Genel talep",
    },
    fields: {
      name: "Ad",
      email: "Email",
      role: "Rolünüz",
      country: "Ülke veya bölge",
      organisation: "Kuruluş",
      message: "Mesajınız",
      level: "Mevcut seviye",
      objectives: "Sizin için en önemlisi (en fazla üç)",
      currentRacquet: "Mevcut raket",
      grip: "Biliyorsanız sap ölçüsü",
      seriesInterest: "İlgilendiğiniz seri",
      quantity: "Adet",
      city: "Seans için şehir veya konum",
      coachInvolved: "Bir antrenör dahil mi?",
      timing: "Tercih edilen zaman",
      targets: "Tercih edilen hedefler",
      limits: "Zorunlu sınırlar",
      use: "Kullanım amacı",
      tradeoffs: "Kabul edilebilir ödünler",
      basis: "Ölçüm esası",
      players: "Oyuncu sayısı",
      interests: "İlgi alanları",
      territory: "İlgilendiğiniz bölge",
      channels: "Mevcut kanallar ve deneyim",
      audience: "Kitle veya disiplin",
      proposal: "Önerilen iş birliği",
      goal: "Gelişim hedefi",
      ageBand: "Oyuncunun yaş aralığı",
      scope: "Program kapsamı",
      interestArea: "İlgi alanı",
      productRef: "Ürün veya seri referansı",
      requestType: "Talep türü",
      seeking: "Aradığınız şey",
      consent: "MAXIMUS'un bu talebi yanıtlamak için bu bilgileri saklamasını ve kullanmasını kabul ediyorum. Bu bir pazarlama aboneliği değildir.",
    },
    roles: { player: "Oyuncu", parent: "Ebeveyn veya veli", coach: "Antrenör", club: "Kulüp veya akademi", retailer: "Perakendeci", distributor: "Distribütör", brand: "Marka veya marka elçisi", investor: "Yatırımcı veya stratejik iş ortağı", institution: "Kurum", other: "Diğer" },
    interestOptions: { training: "Antrenman sistemleri", fitting: "Fitting", identity: "Profesyonel kimlik", programmes: "Yetkili programlar", brand: "Kişisel marka", supply: "Ekipman tedariki", team: "Takım ekipmanı", personalisation: "Kişiselleştirme", development: "Gelişim programları", service: "Servis", network: "Ağ katılımı" },
    ownerTypes: { setup: "Kurulum ve yapılandırma", service: "Servis", records: "Kayıtlar ve sertifikalar", other: "Diğer" },
    strategicAreas: { engineering: "Mühendislik kabiliyeti", configuration: "Yapılandırma derinliği", manufacturing: "Üretim modeli", routes: "Pazara giriş yolları", ip: "Fikri mülkiyet ve hizmetler", expansion: "Büyüme fırsatları" },
    errors: {
      required: "Bu alan zorunludur.",
      too_long: "Bu giriş çok uzun.",
      too_short: "Bu giriş çok kısa.",
      invalid_email: "Geçerli bir e-posta adresi girin, örneğin ad@example.com.",
      invalid_choice: "Seçeneklerden birini seçin.",
      not_number: "Yalnızca rakam kullanarak tam sayı girin.",
      out_of_range: "Bu değer kabul edilen aralığın dışında.",
      not_in_matrix: "Bu ağırlık, seçilen serinin listelenmiş matrisinde yok.",
      decimal_not_supported: "Ondalık kullanmadan tam sayı girin.",
      too_many: "En fazla üç seçenek seçin.",
      consent_required: "MAXIMUS'un bu talebi yanıtlayabilmesi için onay gereklidir.",
      invalid: "Bu giriş geçerli değil.",
    },
  },
  legal: {
    title: "Hukuki kimlik ve kontrol",
    lead: "Herkese açık marka MAXIMUS / MAXIMUS GPS'tir. Hukuki işletme kimlikleri birbirinden ayırt edilebilir ve burada belirtilmiştir.",
    entities: {
      institutional: { role: "Kurumsal program katmanı", p: "Bir programın bu rolü belirlediği durumlarda kurumsal program katmanını sağlar. Raketlerin ticari satıcısı değildir. Dubai International Financial Centre bünyesinde kâr amacı gütmeyen bir tüzel kuruluştur." },
      equipment: { role: "Ekipman ticari kuruluşu", p: "Mevcut işletme dokümanlarının bu rolü belirlediği durumlarda tedarik, distribütörlük ve sözleşmeye dayalı ticari teslim için ekipman ticari kuruluşudur. Herhangi bir işlemin sözleşme tarafı, o işlemin dokümanlarında belirtilir." },
      ip: { role: "Fikri mülkiyet, marka ve ticari koordinasyon", p: "Yerleşik bir fikri mülkiyet, marka veya ticari koordinasyon rolü için görünür. Teyit edilmemiş hiçbir sözleşmesel sorumluluk atfedilmez." },
      stewardship: { role: "Gözetim referansı", p: "House of Maximus, ilgili kaynağın desteklediği durumlarda ekosistemin gözetim referansıdır." },
      control: { role: "Dahili fikri mülkiyet, köken ve doküman kontrolü", p: "MIPA, dahili fikri mülkiyet, köken ve doküman kontrolü katmanıdır. Dahili bir MIPA kaydı; harici bir marka, patent, telif hakkı tescili veya yargı kararından farklıdır ve görsel onay teşkil etmez." },
    },
    labels: { licence: "Lisans", registration: "Tescil", vat: "VAT TRN", address: "Adres", email: "Email", jurisdiction: "Yetki alanı" },
    boundaryTitle: "Sınırlar",
    boundary: [
      "Bir satın alma; kurumsal üyelik, yönetim hakkı, telif payı veya yatırım hakkı otomatik olarak vermez.",
      "Kurumsal rol, ticari ekipman işlemlerinden ayrıdır.",
      "Gizlilik, program şartları ve kontrollü erişim düzenlemeleri, fiilen yayına alınan işlevlere karşılık gelir.",
      "Her ziyaretçi, satış veya yurt dışı programı için geçerli hukuka ilişkin genel bir beyan bulunmaz; sözleşmesel esas her sözleşmede ayrıca belirlenir.",
    ],
  },
  privacy: {
    title: "Gizlilik",
    updated: "Sürüm 2026-09-21 · web sitesi 4.2",
    contactTitle: "Gizlilik soruları için iletişim",
    sections: {
      collect: ["Neler toplanır", "Bir form gönderdiğinizde: girdiğiniz bilgiler (ad, e-posta, rol, ülke veya bölge, verildiyse kuruluş, mesajınız ve formun yanıtları), ziyaretinizin sayfa ve kampanya parametreleri (giriş sayfası, dil, utm parametreleri; reklam tıklama tanımlayıcıları yalnızca analitiğe izin verdiyseniz) ve gönderim zamanı. IP adresiniz yalnızca kötüye kullanımı sınırlamak için özetlenmiş (hash) ve kısa ömürlü biçimde kullanılır; talebinizle birlikte saklanmaz."],
      purpose: ["Neden", "Talebinizi yanıtlamak, istediğiniz teklifi veya şartnameyi hazırlamak ve talebin kaydını tutmak için. Bir form nedeniyle pazarlama mesajı gönderilmez."],
      storageOn: ["Talepler nerede saklanır", "Talepler, Vercel Inc. barındırma platformu üzerinden sağlanan Upstash, Inc. (Redis) veritabanında saklanır."],
      notifyEmail: ["Yeni talebin bildirimi", "Bir talep kabul edildiğinde, gönderdiğiniz bilgileri içeren bir bildirim e-posta ile sorumlu MAXIMUS posta kutusuna gönderilir."],
      notifyTelegram: ["Yeni talebin bildirimi", "Bir talep kabul edildiğinde, gönderdiğiniz bilgileri içeren bir bildirim, MAXIMUS'taki sorumlu kişiye Telegram (Telegram FZ-LLC, Dubai) üzerinden gönderilir; Telegram bu nedenle söz konusu bildirimi iletim sırasında işler."],
      notifyWebhook: ["Yeni talebin bildirimi", "Bir talep kabul edildiğinde, gönderdiğiniz bilgileri içeren bir bildirim, imzalı ve şifreli bir bağlantı üzerinden dahili bir MAXIMUS uç noktasına gönderilir."],
      notifyNone: ["Yeni talebin bildirimi", "Yeni taleplerin bildirimi kurulum aşamasındadır. Talebiniz saklanır ve MAXIMUS tarafından dahili kayıttan okunur; bu amaçla üçüncü bir tarafa hiçbir şey gönderilmez."],
      storageOff: ["Talepler nerede saklanır", "Talep saklama kurulum aşamasındadır. Etkin olana kadar formlar, talebin kabul edilemeyeceğini belirtir; hiçbir şey saklanmaz. Web sitesi Vercel Inc. tarafından barındırılır."],
      browser: ["Tarayıcı depolaması", "Oturum depolaması; GPS'in ve yapılandırıcının çoktan seçmeli yanıtlarını ve ziyaretinizin kampanya parametrelerini bu tarayıcı oturumu boyunca tutar. İletişim bilgileri, serbest metin, gravür metni ve çocuklara ilişkin bilgiler tarayıcıda saklanmaz."],
      analyticsOn: ["Analitik", "Onayınızla Google Analytics 4, iletişim bilgileri veya talep metni olmadan ziyaretleri ve form olaylarını ölçer. Seçiminiz yerel depolamada tutulur ve alt bilgideki “Analitik ayarları” bölümünden her zaman değiştirilebilir. Formlar analitik olmadan da çalışır."],
      analyticsOff: ["Analitik", "Bu web sitesinde etkin bir analitik aracı yoktur."],
      retention: ["Saklama süresi", "Henüz otomatik bir silme süresi yapılandırılmamıştır. Talebinizin silinmesini her zaman isteyebilirsiniz."],
      children: ["Çocuklar", "Formlar bir yetişkin tarafından doldurulmalıdır. 18 yaşın altındaki oyunculara ilişkin talepler bir ebeveyn veya veli tarafından yapılır. Çocuğun adını, doğum tarihini, okulunu veya tıbbi bilgilerini göndermeyin. Çocuk profilleri asla yayımlanmaz."],
      rights: ["Haklarınız", "Talebinize erişmek, talebinizi düzeltmek veya silmek için gps@maximus.tennis adresine yazın ve talep numaranızı belirtin."],
      controlled: ["Kontrollü bilgi", "Gizli dokümanlar bu web sitesinde saklanmaz ve bu site üzerinden sunulmaz. Kontrollü paylaşım, gizlilik sözleşmesi veya sözleşme kapsamında ayrı kanallar üzerinden yapılır."],
    },
  },
  terms: {
    title: "Kullanım şartları",
    copyright: "Bu web sitesinin — metinlerinin, fotoğraflarının, tasarımının ve kodunun — telif hakkı yalnızca Maximus Kiriyakulov'a aittir. Bu hak hiçbir şirkete veya başka bir kişiye devredilmemiştir.",
    updated: "Sürüm 2026-09-21",
    sections: [
      ["Bilgi, teklif değil", "Bu web sitesindeki ürün bilgileri; onaylı şartnameleri, yapılandırma mimarisini ve program açıklamalarını anlatır. Satış teklifi, fiyat listesi, stok beyanı veya teslim taahhüdü değildir. Ticari şartlar, her işlemde belirtilen sözleşme tarafıyla ayrıca yazılı olarak kararlaştırılır."],
      ["Talepler", "Bu web sitesi üzerinden gönderilen bir talep — GPS profilleri, yapılandırma talepleri ve teknik brief'ler dahil — bir talep numarasıyla saklanır ve incelenir. Kabul edilmiş bir sipariş, bir üretim taahhüdü, teyit edilmiş bir randevu, bir üyelik başvurusu veya herhangi bir programa kabul edilmiş bir başvuru değildir."],
      ["Şartnameler ve kanıt", "Hesaplanmış değerler, üretim hedefleri ve teyit edilmiş şartnameler ilgili sayfalarda birbirinden ayrılır. Sertlik değerleri, aksi yayımlanana kadar üretim hedefidir. Belirli bir oyuncu için hiçbir sonuç garanti edilmez."],
      ["Ekosistem, üyelik ve haklar", "Bir raketin satın alınması; kurumsal üyelik, yatırım hakkı, fikri mülkiyet sahipliği, telif payı hakkı veya katılım avantajı doğurmaz. Haklar, yayımlanmış program şartlarına ya da yazılı bir sözleşmeye tabidir."],
      ["Fikri mülkiyet", "MAXIMUS®, aslan amblemi, GPS markası ve bu web sitesinin içeriği korunmaktadır. Dahili mühendislik formülleri, kalite kontrol protokolleri, katman dizilimleri, kalıplar, tedarikçi kimlikleri, maliyetlendirme ve korunan metodoloji burada paylaşılmaz."],
    ],
  },
  lead: {
    submit: "Talebi gönderin",
    submitting: "Gönderiliyor…",
    retry: "Yeniden deneyin",
    acceptedEyebrow: "Talep kabul edildi",
    acceptedTitle: "Talebiniz alındı.",
    requestId: "Talep numarası",
    acceptedNext: "MAXIMUS her talebi inceler ve verdiğiniz e-posta adresine yazılı olarak yanıt verir. Sonraki yazışmalar için talep numarasını saklayın.",
    duplicate: "Bu talep daha önce alınmıştı; kopya oluşturulmadı.",
    another: "Yeni bir talep başlatın",
    errorsTitle: "Lütfen şu alanları kontrol edin:",
    failTitle: "Talebiniz gönderilmedi.",
    fail: {
      offline: "Cihazınız çevrimdışı.",
      network: "Sunucu bağlantısı kurulamadı.",
      timeout: "Sunucu zamanında yanıt vermedi.",
      rate_limited: "Bu ağdan çok fazla talep geldi. Lütfen birkaç dakika sonra tekrar deneyin.",
      too_fast: "Form çok hızlı gönderildi. Lütfen kontrol edip yeniden gönderin.",
      spam_suspected: "Talep, spam filtresi tarafından durduruldu.",
      unavailable: "Şu anda talepler kabul edilemiyor.",
      default: "Beklenmeyen bir hata oluştu.",
    },
    keepNote: "Girdiğiniz bilgiler bu sayfada korunur, böylece yeniden deneyebilirsiniz.",
    sendByEmail: "Bu talebi e-posta ile gönderin",
    sendByEmailNote: "E-posta uygulamanız bu talebin metniyle açılır. E-postayı gönderdiğinizde MAXIMUS talebi alır.",
    mailConfig: "Yapılandırma",
    mailPage: "Sayfa",
    fallback: "Sorun devam ederse {email} adresine yazın. Bir talep, ancak talep numarası gösterildiğinde gönderilmiş sayılır.",
    privacyLink: "Gizlilik bildirimi",
    hpLabel: "Bu alanı boş bırakın",
    consentShort: "Onay",
    after: "Gönderimden sonra bu sayfada bir talep numarası gösterilir. Talepler incelenir ve yazılı olarak yanıtlanır; bir talep sipariş değildir.",
    basis: { unstrung: "Kordajsız", strung: "Kordajlı", unknown: "Emin değilim — şartnamede kararlaştırılacak" },
    hints: {
      email: "MAXIMUS bu adrese yazılı olarak yanıt verir.",
      goal: "Örneğin: ilk müsabaka raketi ya da junior raketten geçiş. Bir çocuğa ilişkin isim, doğum tarihi veya tıbbi bilgi eklemeyin.",
      currentRacquet: "Biliyorsanız marka ve model.",
      message: "Şifre, ödeme bilgisi veya tıbbi bilgi eklemeyin.",
    },
  },
  choose: {
    eyebrow: "Seçim yardımı",
    title: "Raket seçmeme yardım edin",
    lead: "MAXIMUS'a seviyenizi ve sizin için en önemli olanı bildirin. Yanıtlarınız incelenir ve yazılı bir öneri alırsınız: seri, hassasiyet sınıfı, ağırlık ve sap ölçüsü.",
    stepsTitle: "Bundan sonra ne olur",
    steps: [
      ["Yanıtlarınız", "Seviye, öncelikler ve biliyorsanız sap ölçüsü."],
      ["Uzman incelemesi", "MAXIMUS yanıtlarınızı seri matrisleriyle karşılaştırır."],
      ["Yazılı öneri", "Önerilen bir yapılandırma ve sonraki adım, yazılı olarak."],
    ],
    formTitle: "Yanıtlarınız",
    submit: "Seçim yardımı talep edin",
    altTitle: "Kendiniz karar vermeyi mi tercih edersiniz?",
    altGps: "Ayrıntılı GPS profili",
    altBuild: "Doğrudan yapılandırın",
    note: "Otomatik fitting yok, doğruluk iddiası yok: her talebi bir kişi inceler.",
  },
  consent: {
    title: "Analitik",
    text: "MAXIMUS ziyaretleri Google Analytics ile ölçebilir mi? Formlar her durumda çalışır; analitiğe hiçbir iletişim bilgisi veya talep metni gönderilmez.",
    allow: "Analitiğe izin ver",
    decline: "Reddet",
  },
  familyPlan: {
    title: "Aile Planı",
    metaDescription: "Ailenizin tenis bütçesini hesaplayın: antrenmanlar, saatler, top temasları ve bir antrenmanın, bir saatin ve bir vuruşun maliyeti — kendi rakamlarınızla, üç senaryoda.",
    eyebrow: "Aile Planı · Bizimle katkıda bulunun",
    heroTitle: "Ailenizin tenisi ne kadara mal oluyor — ve karşılığında ne alıyorsunuz?",
    heroLead: "Aile bütçenizi, karşıladığı antrenmanları ve saatleri, tahmini top temaslarını ve bir antrenmanın, bir saatin ve bir vuruşun maliyetini hesaplayın — kendi koşullarınızla.",
    heroCta: "Aile planınızı hesaplayın",
    strategy: {
      eyebrow: "Hedefimiz",
      title: "Daha çok tenis. Daha çok fırsat. Birlikte.",
      p1: "Hedefimiz, katılımı genişleterek ve tenise giden yolu daha anlaşılır ve erişilebilir kılarak dünya tenis pazarını on kat büyütmek. MAXIMUS; yönetim, metodoloji, kalite, sonuçlar ve oyunun yaygınlaştırılması yoluyla öncülük etmeyi amaçlar.",
      p2: "Diğer tenis üreticilerini ve markalarını potansiyel iş ortakları olarak görüyoruz. Şirketlerin, antrenörlerin, kulüplerin ve ailelerin güçlerini; tenisi karşılıklı yarar esasıyla geliştirmek, tanıtmak ve büyütmek için ortak bir programda birleştirmeyi öneriyoruz.",
      p3: "MAXIMUS bu yaklaşımın beşinci elementidir: ayrı güçlerin birlikte çalışmasına yardımcı olan birleştirici rol. Ortak zorluklarımız hastalıklar, çocukların hareketsizliği ve insanların oynamaya başlamasının ve oynamayı sürdürmesinin önündeki engellerdir.",
      p4: "Bir aile için her şey netlikle başlar. Aile Planı; bütçeyi, antrenman ve saat sayısını, tahmini top teması hacmini ve antrenmanın maliyetini gösterir. Koşulları değiştirin ve size uyan senaryoyu seçin.",
      note: "On kat büyüme, MAXIMUS olarak belirlediğimiz stratejik hedeftir; halihazırda ulaşılmış bir sonuç değildir. Hesaplayıcı senaryo hesaplamaları gösterir; hiçbir tasarruf, hiçbir tıbbi etki ve hiçbir sportif sonuç vaat etmez.",
      ctaCalc: "Aile planınızı hesaplayın",
      ctaPartner: "Tenisi birlikte geliştirmeyi görüşelim",
    },
    beyond: {
      eyebrow: "Kortun ötesinde",
      title: "Planın antrenman dışında inşa ettikleri",
      admission: {
        h: "Önde gelen okullara ve üniversitelere kabul",
        p: "MAXIMUS, dünyanın önde gelen okullarına ve üniversitelerine giden yolda aileye destek olur: oyuncunun sportif geçmişinin oluşturulması, belgelerin ve başvuruların hazırlanması, sporun ve eğitimin birlikte yürüdüğü programların seçilmesi. Spor bursu verildiği durumlarda burs, ailenin eğitim için ödediği tutarı azaltır.",
      },
      assets: {
        h: "Dijital varlıklar: oyuncunun adı, imajı ve başarı geçmişi",
        p: "Bir oyuncunun adı, imajı, sonuçları, içerikleri ve kişisel markası birer varlıktır ve zamanla önemli bir finansal ve statü değeri oluşturabilir. MAXIMUS bu varlıkların oluşturulmasına, tescil edilmesine ve korunmasına yardımcı olur; böylece bu değer oyuncuda ve ailede kalır.",
      },
      note: "İkisi de hesaplayıcının bir parçası değildir. Bir okuldaki yerin, bir bursun veya bir dijital varlığın değeri duruma göre değişir ve burada tahmin edilmez.",
      cta: "Kabul desteği ve dijital varlıklar hakkında bilgi alın",
    },
    steps: ["Aile verileri", "Antrenman ekonomisi", "Uzun vadeli plan", "Nihai hesaplama"],
    stepsLabel: "Hesaplayıcı adımları",
    scenarios: { now: "Mevcut", planned: "Planlanan", wish: "İstenen" },
    scenarioHints: { now: "Ailenizin bugün yaptığı.", planned: "Bundan sonra yapmayı düşündüğünüz.", wish: "Yapmak istediğiniz." },
    currency: {
      label: "Para birimi",
      note: "Girdiğiniz her tutar bu para birimindedir. Hiçbir dönüştürme yapılmaz.",
    },
    fields: {
      players: { label: "Oynayan aile üyeleri", hint: "Tam sayı." },
      cost: { label: "Bir oyuncu için bir antrenmanın ücreti", hint: "Vergiler ve harçlar dahil, tam tutar." },
      sessions: { label: "Oyuncu başına aylık antrenman sayısı", hint: "Tam sayı." },
      minutes: { label: "Bir antrenmanın süresi, dakika", hint: "Molalar dahil toplam süre. Ondalık değer girilebilir." },
      contacts: { label: "Bir antrenmanda oyuncu başına top teması", hint: "Temas, oyuncunun kendi raketinin topa değmesidir. Bir ralli tek bir temas değildir. Her senaryoda aynı şekilde sayın." },
    },
    presetsLabel: "Hızlı seçim, dakika",
    ages: {
      title: "Planın süresi",
      start: "Başlangıç yaşı",
      end: "Bitiş yaşı",
      hint: "Planın ne kadar süreceğine dair anonim bir varsayım; yalnızca uzun vadeli tabloda kullanılır. Doğum tarihi değildir, önerilen bir başlangıç yaşı da değildir.",
    },
    extras: {
      title: "Ailenin ek giderleri",
      note: "Bu tutarlar tüm aile içindir ve üç senaryonun hepsine uygulanır. Oyuncu sayısıyla çarpılmaz ve bir saatin ya da bir temasın maliyetine dahil edilmez.",
      equipment: "İlk ekipman — dönem için tek tutar",
      clothing: "Giyim ve ayakkabı — dönem için tek tutar",
      renewal: "Ekipman yenileme — dönem için tek tutar, otomatik olarak tekrarlanmaz",
      court: "Kort veya kulüp — aylık, tüm aile",
      travel: "Seyahat ve etkinlikler — aylık, tüm aile",
      quoteSource: "Fiyatların kaynağı (isteğe bağlı)",
      quoteDate: "Fiyatların tarihi (isteğe bağlı)",
      quoteNote: "Tam olarak girdiğiniz şekilde gösterilir. MAXIMUS bu fiyatları doğrulamaz.",
    },
    storage: {
      save: "Planı bu cihaza kaydet",
      clear: "Planı bu cihazdan sil",
      saved: "Plan bu cihaza kaydedildi. Hiçbir yere hiçbir şey gönderilmedi.",
      cleared: "Plan silindi. Hesaplayıcı başlangıç değerlerine döndü.",
      restored: "Bu cihaza kaydettiğiniz plan geri yüklendi.",
      invalid: "Bu cihaza kaydedilmiş bir plan okunamadı ve uygulanmadı. Yeni bir hesaplama başlatabilirsiniz.",
      unavailable: "Bu tarayıcı cihaza kaydetmeye izin vermiyor.",
    },
    annual: {
      title: "Bir yıl, yan yana",
      sessions: "Yıllık oyuncu-antrenman",
      cost: "Ailenin yıllık antrenman harcaması",
      hours: "Yıllık oyuncu-saat",
      length: "Bir antrenmanın süresi",
      contacts: "Yıllık top teması",
      note: "Oyuncu-antrenman ve oyuncu-saat değerleri, her oyuncunun antrenmanlarını toplar. Kort kiralama saatleri ya da grup buluşmaları değildir: birlikte 90 dakika antrenman yapan iki oyuncu 2 oyuncu-antrenman ve 3 oyuncu-saat eder.",
    },
    economics: {
      title: "Bir antrenmanın, bir saatin ve bir temasın maliyeti",
      session: "Bir oyuncunun bir antrenmanı",
      hour: "Bir oyuncunun bir saatlik çalışması",
      contact: "Bir top teması",
      undefinedContacts: "Tanımsız: 0 temas",
      undefinedMinutes: "Tanımsız: 0 dakika",
      below: "{value} altında",
      note: "Bu rakamlara yalnızca antrenman ücreti girer. Ailenin ek giderleri temaslara bölünmez.",
      caption: "Temas sayısı, seçilen antrenman hacminden ve modelin varsayımlarından hesaplanır. Gerçek çalışma; formata, molalara ve antrenman koşullarına bağlıdır. Bir temasın maliyeti bir bütçe ölçüsüdür, antrenörlük kalitesinin ölçüsü değildir.",
    },
    longTerm: {
      title: "Uzun vadeli harcama planı",
      horizon: "Süre",
      activeYears: "Aktif yıllar",
      years: "{n} yıl",
      note: "Aktif yıllar, iki yaş arasındaki farkla sınırlıdır. Fiyatlar, sıklık, enflasyon, sezonlar, kaçırılan antrenmanlar ve döviz kurları sabit kabul edilir. Ek giderler bu tabloya dahil değildir.",
    },
    final: {
      title: "Nihai hesaplama",
      scenario: "Senaryo",
      months: "Dönem, ay olarak",
      heading: "{scenario} · {months} ay",
      total: "Dönem toplamı",
      training: "Antrenmanlar",
      extras: "Ek giderler",
      oneOff: "Tek seferlik kalemler",
      monthly: "Aylık kalemler × ay",
      sessions: "Dönemdeki oyuncu-antrenman",
      hours: "Dönemdeki oyuncu-saat",
      contacts: "Dönemdeki top teması",
      formulaTitle: "Nasıl hesaplanır",
      formula: "Toplam = oyuncu × aylık antrenman × ay × antrenman ücreti + tek seferlik giderler + ay × aylık ek giderler.",
      formulaNote: "Ek giderler tüm aile için girilir. Tek seferlik kalemler, 0 aylık bir dönem için bile bir kez sayılır.",
      inputs: "Girdiğiniz veriler",
    },
    units: { min: "dk", h: "sa", approx: "≈" },
    errors: {
      title: "Sonucu görmek için bu alanları düzeltin",
      required: "Zorunlu — bir sayı girin; 0 kabul edilir.",
      negative: "Negatif olamaz.",
      integer: "Yalnızca tam sayı.",
      number: "Bir sayı girin.",
      tooLarge: "Bu sayı hesaplama için çok büyük.",
      endBeforeStart: "Bitiş yaşı başlangıç yaşından küçük olamaz.",
      tooLong: "En fazla 200 karakter.",
      date: "Geçerli bir tarih girin.",
      currency: "Bir para birimi seçin.",
      scenario: "Bir senaryo seçin.",
      result: "Sonuç, güvenilir biçimde gösterilemeyecek kadar büyük. Girdiğiniz değerleri küçültün.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: eksiksiz kompozisyon — önden ve yandan görünen antrenman raketi, yuvarlak temas kafasındaki gravürlü yuvarlak aslan amblemi, şaft boyunca MAXIMUS ve SPOT TRAINER gravürü ve aslan markalı sekizgen sap kapağı",
    greatHero: "MAXIMUS GREAT serisi, 363 g: kırmızı ve sarı kafa detayları, parlak MAXIMUS yazısı, şaft üzerindeki Maximus imzası ve sap üzerindeki aslan amblemiyle eksiksiz kompozisyon",
    spotDetail: "Daha yakından görünen iki MAXIMUS Spot Trainer: mat siyah temas kafasındaki gravürlü aslan, tırtıklı grip sargısı ve aslan markalı sekizgen sap kapakları",
    spotPair: "Koyu renkli bir zemin üzerinde açılı şekilde yatan iki MAXIMUS Spot Trainer; bir şaft boyunca MAXIMUS, diğer şaft boyunca SPOT TRAINER gravürü, her temas kafasında aslan amblemi",
    spinVisual: "MAXIMUS SPIN: kordajlı kafa, parlak MAXIMUS yazısı, grip ve aslanlı sap kapağı",
    powerVisual: "MAXIMUS POWER: kordajlı kafa, parlak MAXIMUS yazısı, kişiselleştirme gravürü, grip ve aslanlı sap kapağı",
    greatVisual: "MAXIMUS GREAT: kordajlı kafa, parlak MAXIMUS yazısı, kişiselleştirme gravürü, grip, aslanlı sap kapağı ve boğazdaki G seri işareti",
    spinHead: "MAXIMUS SPIN kafası ve kordaj yüzeyi",
    handleLion: "MAXIMUS boğazı, gripi ve aslan markalı sap kapağı",
    engraving: "Şaft üzerinde gümüş kişiselleştirme gravürü",
    lettering: "Mat siyah kasa üzerinde parlak siyah MAXIMUS yazısı",
    variantAlt: "MAXIMUS {series} serisi — {w} g, denge {b} mm: şartname şeridi, kişiselleştirme gravürü bölgesi ve MIPA işaretiyle eksiksiz görselleştirme",
    sstSystem: "MAXIMUS Sweet Spot Trainer, dört raketli sistem",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "MAXIMUS yazılı Sweet Spot Trainer şaftları",
    sstGrips: "Sweet Spot Trainer gripleri ve sap kapakları",
    sstButtcaps: "Sweet Spot Trainer, aslan markalı dört sap kapağı",
    note: "Ürün görseli",
  },
  notFound: { title: "Sayfa bulunamadı", p: "İstediğiniz sayfa bu dilde bulunmuyor.", cta: "Ana sayfaya gidin" },
};

export default tr;
