/* Uzbek dictionary — MAXIMUS website. Numerical product data lives in data/products.js. */
const uz = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS — spetsifikatsiya boʻyicha ishlab chiqilgan toʻliq karbon tennis raketkalari",
    defaultDescription:
      "Ramadan dastakkacha toʻliq karbon tennis raketkalari: GREAT 97 in², POWER 98 in² va SPIN 100 in², sakkizta zavod grip oʻlchami L0–L7, vazn, balans, swingweight va qattiqlik uchun aniqlik sinflari hamda soʻrov boʻyicha maxsus injiniring.",
  },
  common: {
    statuses: {
      current: "Amaldagi",
      agreement: "Kelishuv asosida mavjud",
      development: "Ishlab chiqilmoqda",
      concept: "Konsepsiya",
      target: "Ishlab chiqarish maqsadi",
      modelled: "Hisoblangan",
      confirmed: "Tasdiqlangan",
      requested: "Soʻralgan arxitektura",
      notprovided: "Taqdim etilmagan",
    },
    brief: { who: "Kimlar uchun", value: "Nima olasiz", now: "Hozir tasdiqlangan", next: "Keyingi qadam" },
    labels: {
      next: "Keyingisi",
      back: "Orqaga",
      edit: "Javoblarni tahrirlash",
      review: "Tekshirish",
      start: "Boshlash",
      restart: "Qaytadan boshlash",
      copy: "Soʻrov matnini nusxalash",
      copied: "Nusxalandi",
      openEmail: "Bu soʻrovni yuborish uchun pochtani ochish",
      reference: "Soʻrov kodi",
      weight: "Vazn",
      balance: "Balans",
      swingweight: "Swingweight",
      stiffness: "Qattiqlik",
      grip: "Grip oʻlchami",
      headSize: "Bosh oʻlchami",
      series: "Seriya",
      precisionClass: "Aniqlik sinfi",
      quantity: "Miqdor",
      notProvided: "Hali eʼlon qilinmagan",
      requestTarget: "Soʻralgan maqsad",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "Batafsil",
      allSeries: "Barcha seriyalar",
      points: "roʻyxatdagi vaznlar",
      optional: "majburiy emas",
      required: "majburiy",
      select: "Tanlash",
      yes: "Ha",
      no: "Yoʻq",
      unknown: "Bilmayman",
      custom: "Maxsus maqsad",
      listed: "Roʻyxatdagi vazn",
      individual: "Alohida raketka",
      pair: "Moslashtirilgan juftlik",
      triple: "Moslashtirilgan uchlik",
      team: "Jamoa toʻplami",
      summaryTitle: "Soʻrovingiz xulosasi",
      nextAction: "Keyingi harakat",
      status: "Holati",
      learn: "Batafsil bilish",
      schematic: "Sxema — oʻlchov natijasi emas",
      photo: "Surat",
    },
    ecosystemStrip: "MAXIMUS ekotizimi",
    truth: {
      noPrices: "Narxlar, minimal miqdorlar, yetkazib berish muddatlari, kafolatlar va yetkazib berish majburiyatlari har bir bozor va har bir dastur uchun yozma ravishda tasdiqlanadi.",
      requestNotOrder: "Soʻrov — koʻrib chiqish uchun murojaat. U qabul qilingan buyurtma, ishlab chiqarish majburiyati yoki tasdiqlangan uchrashuv emas.",
      noGuarantee: "Bu yerda tasvirlangan hech bir jihoz, uslub yoki dastur muayyan oʻyinchi uchun natijani kafolatlamaydi.",
      governing: "Bu sahifa bir necha tilda eʼlon qilinadi. Ingliz tilidagi versiya hukmron versiya hisoblanadi; tarjima qulaylik uchun beriladi.",
    },
  },
  nav: {
    language: "Til",
    groups: { racquets: "Raketkalar", training: "Mashgʻulot", ecosystem: "Ekotizim", partnerships: "Hamkorlik" },
    familyPlan: "Oilaviy tennis",
    racquets: "Raketka seriyalari va qiyoslash",
    great: "GREAT — 97 in² · Nazorat",
    power: "POWER — 98 in² · Quvvat",
    spin: "SPIN — 100 in² · Aylanish",
    precision: "Aniqlik va qattiqlik",
    grip: "Zavod grip arxitekturasi L0–L7",
    custom: "Maxsus injiniring",
    training: "Mashgʻulot tizimlari",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "Metodologiya",
    gps: "MAXIMUS GPS",
    build: "Konfigurator",
    choose: "Tanlashga yordam bering",
    ecosystem: "Ekotizim xaritasi",
    engineering: "Injiniring va ishlab chiqarish",
    experience: "Sinov va fitting",
    brands: "Shaxsiy brendlar va brend elchilari",
    families: "Oilalar va ota-onalar",
    owners: "Egalar va egalar sayfi",
    network: "Sports Network",
    partnerships: "Barcha hamkorlik yoʻllari",
    coaches: "Murabbiylar",
    clubs: "Klublar va akademiyalar",
    distribution: "Distribyutorlik va mamlakatni rivojlantirish",
    strategic: "Strategik va investitsiya",
    institutional: "Institutsional dasturlar",
    contact: "Aloqa",
    legal: "Huquqiy maqom",
    privacy: "Maxfiylik",
    terms: "Foydalanish shartlari",
    menu: "Menyu",
    close: "Yopish",
    home: "Bosh sahifa",
    skip: "Kontentga oʻtish",
  },
  footer: {
    line: "MAXIMUS raketkasi — MAXIMUS dunyosiga ochiladigan kalitingiz.",
    product: "Mahsulot",
    ecosystem: "Ekotizim",
    company: "Tashkilot",
    instagram: "Instagram",
    email: "E-pochta",
    analytics: "Analitika sozlamalari",
    subscribe: {
      title: "MAXIMUS bilan qoling",
      line: "Yangi seriyalar, fitting sanalari, mashgʻulot materiallari va egalar dasturi. Yilda bir necha xat — boshqa hech narsa.",
      label: "E-pochta manzili",
      placeholder: "your@email.com",
      button: "Obuna boʻlish",
      sending: "Yuborilmoqda",
      done: "Siz roʻyxatdasiz. Faqat oʻqishga arziydigan narsa boʻlganda yozamiz.",
      invalid: "Iltimos, manzilni tekshiring.",
      failed: "Manzil qayd etilmadi. Iltimos, bir oz vaqtdan soʻng qaytadan urinib koʻring.",
      terms: "Obuna boʻlish orqali siz MAXIMUS bu yangiliklarni sizga yuborishi va manzilingizni shu maqsadda saqlashiga rozilik bildirasiz. Har bir xatda obunani bekor qilish havolasi boʻladi.",
    },
    rights: "MAXIMUS® va sher emblemasi — MAXIMUS ekotizimining belgilari. MIPA — ichki intellektual mulk, kelib chiqish va hujjat nazorati.",
    boundary:
      "Tijorat va shartnoma shartlari alohida, yozma ravishda kelishiladi. Raketka xaridi institutsional aʼzolik, investitsiya huquqlari, intellektual mulk egaligi yoki royalti olish huquqini vujudga keltirmaydi.",
  },
  home: {
    heroEyebrow: "MAXIMUS TENNIS · GREAT POWER & SPIN",
    heroTitle: "Aniqlik kontakt nuqtasida boshlanadi.",
    heroProduct: "Sweet Spot Trainer, Spot Trainer va MAXIMUS metodologiyasi maqsadli mashgʻulotni toʻliq karbon performans raketkalari bilan bogʻlaydi.",
    heroCta1: "Mashgʻulot tizimi bilan tanishing",
    heroCta2: "GREAT bilan tanishing",
    heroCaption: "MAXIMUS GREAT · 97 in² · Nazorat",
    heroMeta: [
      ["Toʻliq karbon", "ramadan dastakkacha"],
      ["4 parametr", "vazn · balans · swingweight · qattiqlik"],
      ["8 grip oʻlchami", "zavod geometriyasi L0–L7"],
      ["3 seriya", "GREAT · POWER · SPIN"],
    ],
    familyPlan: {
      eyebrow: "Oilaviy tennis rejasi · Biz bilan birga hissa qoʻshing",
      title: "Oilaviy byudjetingiz. U nimaga yetadi. U nimani yaratadi.",
      p: "Uchta ssenariy yonma-yon: «Hozir», «Reja» va «Orzu». Byudjetingiz qancha mashgʻulot, soat va toʻp bilan kontaktga yetishi hamda bitta mashgʻulot, bir soat va bitta zarba qanchaga tushishi — hammasi oʻz raqamlaringiz asosida hisoblanadi.",
      points: [
        ["Oʻz raqamlaringiz", "Har bir summani oʻzingiz kiritasiz. Hech qanday taxmin ham, valyuta konvertatsiyasi ham yoʻq."],
        ["Uchta ssenariy", "Hozir qilayotganingizni rejalashtirganingiz va xohlaganingiz bilan solishtiring."],
        ["Oʻn yil oldinga", "Bir yildan oʻn yilgacha boʻlgan xarajatlar rejasi — siz belgilagan yosh oraligʻida."],
        ["Kortdan tashqarida", "Yetakchi maktablarga kirishda koʻmak hamda oʻyinchida qoladigan raqamli aktivlar."],
      ],
      cta: "Oilaviy tennis rejasini hisoblash",
    },
    paths: {
      eyebrow: "Shu yerdan boshlang",
      title: "Yoʻlingizni tanlang",
      items: {
        player: { h: "Oʻyinchi", p: "Darajangiz va ustuvorliklaringizga koʻra raketka toping yoki uni bevosita konfiguratsiya qiling.", a: "Raketkangizni toping" },
        parent: { h: "Ota-ona", p: "Rivojlanish maqsadlari, murabbiyning ishtiroki va mos jihoz uchun yozma yoʻl.", a: "Oila yoʻli" },
        coach: { h: "Murabbiy, klub yoki akademiya", p: "Mashgʻulot tizimlari, fitting, jamoa toʻplamlari va personalizatsiya.", a: "Murabbiy va klub yoʻllari" },
        partner: { h: "Distribyutor yoki hamkor", p: "Distribyutorlik, mamlakatni rivojlantirish, strategik va institutsional yoʻllar.", a: "Hamkorlik yoʻllari" },
      },
    },
    series: {
      eyebrow: "Performans seriyalari",
      title: "Uchta performans arxitekturasi. Bitta injiniring platformasi.",
      lead: "Seriyani oʻyin yoʻnalishiga koʻra tanlang, soʻngra konfiguratsiyani yakunlang: aniqlik sinfi, vazn, grip, personalizatsiya.",
      cta: "Seriyalarni qiyoslash",
      configure: "Konfiguratsiya qilish",
      open: "Seriyani ochish",
      photoPending: "Surat hali eʼlon qilinmagan",
      photoLabel: { great: "GREAT · 97 in²", power: "POWER · 98 in²", spin: "SPIN · 100 in²" },
    },
    precision: {
      eyebrow: "MAXIMUS Aniqlik tizimi",
      title: "Vazn. Balans. Swingweight. Qattiqlik.",
      sub: "Yagona injiniring tizimi sifatida nazorat qilinadi.",
      lead: "Uchta aniqlik sinfi har bir tayyor raketka oʻzining eʼlon qilingan spetsifikatsiyasiga qanchalik qatʼiy rioya qilishini belgilaydi. P0.5 — belgilangan oʻlchov protokoli boʻyicha qatʼiy chetlanish chegarasi, nol xatolik emas.",
      cta: "Aniqlik va qattiqlik haqida batafsil",
    },
    stiffness: {
      eyebrow: "Qattiqlik",
      title: "Eʼlon qilingan maqsadga nisbatan takrorlanadigan rama javobi.",
      p: "Rama qattiqligi javob berishni, hissiyotni va raketkalar oʻrtasidagi barqarorlikni shakllantiradi. MAXIMUS uni toʻrtinchi nazorat parametri sifatida koʻradi: maqsad, oʻlchangan natija, ruxsat etilgan chetlanish va asbobning imkoniyati alohida yozuvlar sifatida saqlanadi. Foydasi — takrorlanuvchanlikda, har bir oʻyinchi uchun kafolatlangan natijada emas.",
      cols: [["Javob", "Rama kontakt nuqtasida energiyani qanday qaytarishi."], ["Hissiyot", "Oʻyinchi kontakt nuqtasida nimani sezishi."], ["Barqarorlik", "Bitta spetsifikatsiya boʻyicha yasalgan raketkalar oʻz sinfi doirasida bir xil javob beradi."]],
      schematicCaption: "Sxema: har bir sinf uchun eʼlon qilingan qattiqlik maqsadi atrofida ruxsat etilgan chetlanish. Bu oʻlchov natijasi emas; hech qanday RA qiymati nazarda tutilmaydi.",
      bands: { p25: "maqsadli chetlanish ±1 RA", p15: "maqsadli chetlanish ±0.5 RA", p05: "zavodning belgilangan oʻlchov protokoli boʻyicha eʼlon qilingan maqsadli RA ga mos keladi — nol xatolik emas", target: "eʼlon qilingan maqsad (qiymat nazarda tutilmaydi)" },
    },
    carbon: {
      eyebrow: "Konstruksiya standarti",
      title: "Toʻliq karbon. Ramadan dastakkacha.",
      p: "Bu platformadagi barcha amaldagi MAXIMUS raketkalari tuzilishi boʻyicha, dastagi bilan birga, toʻliq karbondan iborat. Dastakni shakllantirish uchun koʻpik ishlatilmaydi.",
      gripTitle: "Sakkizta zavod grip oʻlchami. L0–L7.",
      gripP: "Har bir oʻlcham — zavodda ishlangan karbon dastak geometriyasi, overgrip bilan qalinlashtirish emas.",
      scaleCaption: "Sxema: L0–L7 nominal grip belgilari (4″ dan 4⅞″ gacha). Bu oʻlchangan dastak oʻlchamlari emas.",
      cta: "Zavod grip arxitekturasi",
    },
    custom: {
      eyebrow: "Maxsus injiniring",
      title: "Spetsifikatsiya boʻyicha ishlab chiqilgan.",
      sub: "Standart qator — faqat boshlangʻich nuqta.",
      p: "MAXIMUS eʼlon qilingan matritsalardan tashqaridagi texnik talablarni baholash, injiniring, validatsiya va kelishilgan spetsifikatsiya boʻyicha ishlab chiqarish uchun qabul qiladi. Amalga oshirish imkoniyati yozma ravishda tasdiqlanadi.",
      chain: ["Belgilash", "Injiniring", "Validatsiya", "Spetsifikatsiya", "Ishlab chiqarish", "Oʻlchash / qayd etish"],
      cta: "Texnik topshiriq yuborish",
      cta2: "Maxsus injiniringni muhokama qilish",
    },
    training: {
      eyebrow: "Mashgʻulot tizimlari",
      title: "Kontakt nuqtasi atrofida qurilgan mashgʻulot tizimi.",
      p: "Sweet Spot Trainer, MAXIMUS metodologiyasi va Spot Trainer jihozni murabbiy boshchiligidagi mashgʻulot bilan bogʻlaydi: markazlashgan kontakt, nazorat, bosqichma-bosqich yuklama va performans raketkasiga qaytish.",
      cta: "Mashgʻulot tizimlari",
      cta2: "Namoyish soʻrash",
      photoPending: "Trenajyor surati hali eʼlon qilinmagan",
      sstP: "Markazlashgan kontaktni mashq qilish uchun 50 in² mashgʻulot boshi; murabbiy tanlagan yuklama uchun toʻrtta vazn konfiguratsiyasi.",
      sstCta: "Sweet Spot Trainer bilan tanishing",
      sstCaption: "300 g konfiguratsiyasi, toʻrttadan biri",
      methodP: "Maqsadlarni belgilang, jihozni tanlang, murabbiy ishtirokida mashq qiling, kuzatuvlarni qayd eting, qayta baholang, sozlang va ishni performans oʻyiniga koʻchiring.",
      methodCta: "Metodologiya bilan tanishing",
      spotP: "Aniq va takrorlanadigan kontakt nuqtasini mashq qilish uchun kichik yumaloq nishon.",
      spotCta: "Spot Trainer bilan tanishing",
    },
    manufacturing: {
      eyebrow: "Ishlab chiqarish va sifat nazorati",
      title: "Spetsifikatsiya boʻyicha yasaladi. Oʻlchanadi va qayd etiladi.",
      p: "Ishlab chiqarish har bir buyurtmaning yozma spetsifikatsiyasiga amal qiladi. Yozuvlar aniqlik sinfiga qarab yuritiladi: P2.5 uchun saqlanadigan ishlab chiqarish yozuvlari, P1.5 uchun individual yozuvlar va kuzatuvchanlik, P0.5 uchun — buyurtma dasturi shuni koʻzda tutsa — individual nazorat va hujjatlashtirish.",
      confirmedTitle: "Tasdiqlangan",
      confirmed: ["Ramadan dastakkacha toʻliq karbon konstruksiya.", "Toʻrtta nazorat parametri bilan P2.5, P1.5 va P0.5 aniqlik sinflari.", "Sakkizta zavod grip oʻlchami L0–L7."],
      pendingTitle: "Hali eʼlon qilinmagan",
      pending: "Oʻlchov uskunalari suratlari, namunaviy sifat nazorati yozuvlari va zavod videolari hali eʼlon qilinmagan. Bu sahifadagi hech narsa oʻlchov sertifikati emas.",
      captions: { lettering: "Mat ramadagi yaltiroq MAXIMUS yozuvi", buttcap: "Grip va sher belgisi bilan dastak qopqogʻi", handle: "Kumushrang personalizatsiya gravirovkasi", finish: "Bosh va tor maydoni" },
      cta: "Injiniring va ishlab chiqarish",
    },
    world: {
      eyebrow: "MAXIMUS dunyosi",
      title: "Bitta kalit. Bitta ekotizim. Cheksiz imkoniyatlar.",
      note: "«Cheksiz imkoniyatlar» — brend iborasi, cheksiz texnik imkoniyat, daromad yoki kirish huquqi vaʼdasi emas. Xarid royalti, investitsiya daromadi, sponsorlik yoki oʻyinchi rivojlanishini moliyalashtirishni vujudga keltirmaydi.",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN — va tennis dunyosidagi navigatsiyangiz: yozma javob beriladigan boshqariladigan jihoz profili." },
        personal: { h: "Personalizatsiya", p: "Ismlar, bosh harflar, raqamlar va jamoa identifikatsiyasi tasdiqlangan kumushrang gravirovka uslubida." },
        development: { h: "Rivojlanish", p: "Murabbiy boshchiligidagi mashgʻulot tizimlari, yozuvlar va qayta baholash." },
        ecosystem: { h: "Kengaytirilgan ekotizim", p: "Shaxsiy brendlar, egalar yozuvlari, tarmoq, litsenziyalash va institutsional dasturlar — har biri haqiqiy holati bilan koʻrsatiladi." },
      },
      cta: "Ekotizim bilan tanishing",
    },
    partners: {
      eyebrow: "Hamkorlik yoʻllari",
      title: "Murabbiylar, klublar, distribyutorlar va hamkorlar.",
      p: "Avvalo yozma kvalifikatsiya. Mamlakat huquqlari, eksklyuzivlik va tijorat shartlari yozma ravishda muhokama qilinadi — hech qachon forma orqali berilmaydi.",
      cta: "Barcha hamkorlik yoʻllari",
      formTitle: "Qisqa murojaat",
      formLead: "Maqsadni tanlab, MAXIMUS ga yozing. Soʻrov raqamini shu sahifada olasiz.",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "TENNIS DUNYOSIDAGI NAVIGATSIYANGIZ" } },
    personal: { eyebrow: "Personalizatsiya", title: "Ismingiz. Raqamingiz. Sizning MAXIMUS." },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "Uchta seriya. Haqiqiy parametrlar." },
    map: { cta: "Ekotizim bilan tanishing" },
  },
  racquets: {
    title: "Raketkalar",
    lead: "Umumiy konstruksiya standarti, umumiy aniqlik tizimi va umumiy zavod grip arxitekturasiga ega uchta performans seriyasi. Har bir seriya kengroq injiniring platformasi ichidagi shakllangan performans arxitekturasidir.",
    direction: { control: "Nazorat", power: "Quvvat", spin: "Aylanish" },
    seriesName: { great: "Great", power: "Power", spin: "Spin" },
    directionLabel: "Asosiy oʻyin yoʻnalishi",
    compareTitle: "Seriyalarni qiyoslash",
    compareLead: "Faqat tasdiqlangan arxitektura maʼlumotlari. Bu seriyalar uchun tor sxemalari, uzunliklar, rama profillari, tarangligi diapazonlari, swingweight va qattiqlikning nominal qiymatlari eʼlon qilinmagan; ular texnik koʻrib chiqish uchun soʻralgan maqsadlar sifatida yigʻiladi.",
    columns: { series: "Seriya", head: "Bosh oʻlchami", direction: "Yoʻnalish", weights: "Roʻyxatdagi vaznlar", range: "Vazn diapazoni", balance: "Balans maʼlumotlari" },
    balanceModelled: "Hisoblangan qiymatlar",
    balanceNotProvided: "Hali eʼlon qilinmagan",
    construction: "Konstruksiya: toʻliq karbon, ramadan dastakkacha · Aniqlik: P2.5 / P1.5 / P0.5 · Griplar: L0–L7",
    otherTitle: "Boshqa raketka sport turlari",
    otherLead: "Tasdiqlangan rivojlanish yoʻnalishlari. Bu toifalarda sotishga yaroqli mahsulotlar mavjud emas va ularga hech qanday tennis spetsifikatsiyasi koʻchirilmaydi.",
    other: { padel: "Padel", pickleball: "Pikleboll", squash: "Skvosh", badminton: "Badminton", racquetball: "Raketbol", beachTennis: "Plyaj tennisi" },
    ctaConfigure: "Soʻrovni konfiguratsiya qilish",
    ctaSeries: "Seriyani ochish",
  },
  seriesPage: {
    eyebrow: "Performans seriyalari",
    intro: {
      great: "97 in² GREAT arxitekturasi nazorat atrofida qurilgan: ixcham bosh, aniq kontakt va yoʻnalish boʻyicha ishonch.",
      power: "98 in² POWER arxitekturasi energiya uzatish atrofida qurilgan: barqaror ramadan chuqurlik va tezlik.",
      spin: "100 in² SPIN arxitekturasi toʻpning harakati atrofida qurilgan: aylanish, zapas va traektoriyani shakllantirish.",
    },
    photoPending: "Seriya surati hali eʼlon qilinmagan",
    detailPending: "Bu seriya uchun konstruksiya va dastak detallarining suratlari hali eʼlon qilinmagan.",
    specsTitle: "Spetsifikatsiya va holat",
    catalogue: {
      eyebrow: "{series} seriyasi katalogi",
      title: "{n} vazn variantlari",
      lead: "{series} seriyasining har bir varianti, vazn boʻyicha tartiblangan. Vazn grammda, balans dastak uchidan millimetrda. Har bir vizualizatsiya butunligicha koʻrsatiladi: hech narsa kesilmagan, yopilmagan yoki choʻzilmagan.",
      selectLabel: "Vazn variantini tanlang",
      select: "Bu variantni koʻrsatish",
      selected: "Yuqorida koʻrsatilgan",
      balanceLabel: "Balans",
      headLabel: "Bosh oʻlchami",
      constructionLabel: "Konstruksiya",
      gripsLabel: "Zavod grip oʻlchamlari",
      precisionLabel: "Aniqlik sinflari",
      balanceConfirmed: "Balans — bu vazn uchun tasdiqlangan qiymat va vizualizatsiyada bosilgan raqamga mos keladi.",
      balanceModelled: "Balans — bu roʻyxatdagi vazn uchun hisoblangan qiymat, individual zavod oʻlchovi emas; u vizualizatsiyada bosilgan raqamga mos keladi.",
      zoom: "Tasvirni ochish",
      close: "Yopish",
      allTitle: "Barcha {n} variant",
    },
    specs: { head: "Bosh oʻlchami", direction: "Asosiy yoʻnalish", weights: "Roʻyxatdagi vaznlar", range: "Vazn diapazoni", balance: "Balans", construction: "Konstruksiya", grips: "Zavod griplari", precision: "Aniqlik sinflari" },
    construction: "Toʻliq karbon, ramadan dastakkacha",
    statusTitle: "Qiymatlarning holati",
    matrixTitle: "Toʻliq vazn matritsasi",
    matrixLead: "Roʻyxatdagi vaznlar — standart tanlov. Boshqa vaznlarni maxsus maqsad sifatida soʻrash mumkin; yetishmayotgan oraliq qiymatlar qoʻshib qoʻyilmaydi.",
    balanceNote: {
      confirmed: "Balans qiymatlari har bir roʻyxatdagi vazn uchun tasdiqlangan (dastak uchidan mm) va shu vaznning vizualizatsiyasida bosilgan raqamga mos keladi. Ular bu yerda hisoblanmaydi va qoʻshni vaznlar oʻrtasida tekislanmaydi; oʻlchov asosi yozma spetsifikatsiyada tasdiqlanadi.",
      modelled: "Balans qiymatlari har bir roʻyxatdagi vazn uchun hisoblanadi (dastak uchidan mm). Ular individual zavod oʻlchovlari emas; oʻlchov asosi yozma spetsifikatsiyada tasdiqlanadi.",
      notprovided: "Bu seriya uchun balans qiymatlari taqdim etilmagan. Ularni boshqa seriyadan kelib chiqib taxmin qilmang.",
    },
    optionsTitle: "Aniqlik, grip va vazn",
    notPublished: "Bu seriya uchun eʼlon qilinmagan: tor sxemasi, uzunlik, rama profili, taranglik diapazoni, swingweight va qattiqlik qiymatlari. Ularni texnik koʻrib chiqish uchun soʻralgan maqsadlar sifatida koʻrsatishingiz mumkin.",
    offerTitle: "Soʻrovingizdan keyin nima boʻladi",
    offerSteps: [
      ["Soʻrov", "Konfiguratsiya yoki savol yuboring. Soʻrov raqami darhol koʻrsatiladi."],
      ["Koʻrib chiqish", "MAXIMUS seriyani, sinfni, vaznni, gripni va soʻralgan maqsadlarni koʻrib chiqadi."],
      ["Yozma javob", "Spetsifikatsiya, mavjudlik va tijorat shartlari yozma ravishda tasdiqlanadi."],
    ],
    faqTitle: "Savollar",
    faq: [
      ["Balans qiymatlari oʻlchanganmi?", "Ular roʻyxatdagi vaznlar uchun hisoblangan, individual oʻlchovlar emas. Oʻlchov asosi yozma spetsifikatsiyada tasdiqlanadi."],
      ["Roʻyxatda yoʻq vaznni soʻrasam boʻladimi?", "Ha, butun grammlarda maxsus maqsad sifatida. U texnik jihatdan koʻrib chiqiladi va amalga oshirish imkoniyati yozma ravishda tasdiqlanadi."],
      ["Aniqlik sinfi nimani oʻzgartiradi?", "Vazn, balans, swingweight va qattiqlik eʼlon qilingan spetsifikatsiyaga qanchalik qatʼiy rioya qilishini hamda qanday yozuvlar yuritilishini."],
      ["Grip overgriplar bilan qalinlashtiriladimi?", "Yoʻq. L0–L7 — zavodda ishlangan karbon dastak geometriyalari."],
      ["Narxlar va yetkazib berish muddatlari qayerda?", "Ular har bir soʻrov uchun yozma ravishda tasdiqlanadi va bu yerda eʼlon qilinmaydi."],
    ],
    faqSpinBalance: ["SPIN balans qiymatlari qayerdan olingan?", "Tasdiqlangan Spin seriyasi jadvalidan: 33 vazn varianti va dastak uchidan millimetrdagi balans. Har bir juftlik shu vaznning tasdiqlangan vizualizatsiyasida bosilgan raqamga mos keladi. Qiymatlar hisoblanmagan va qoʻshni vaznlar oʻrtasida tekislanmagan."],
    ctaBuild: "Bu seriyani konfiguratsiya qilish",
    ctaAsk: "Bu seriya haqida soʻrash",
    ctaCompare: "Barcha seriyalarni qiyoslash",
    weightsLabel: "roʻyxatdagi vaznlar",
    headLabel: "bosh",
  },
  precision: {
    title: "Aniqlik va qattiqlik",
    switch: { label: "Aniqlik sinfini tanlang", panelLabel: "Toʻrtta nazorat parametri —", qcLabel: "Sifat nazorati arxitekturasi", protocolNote: "zavodning belgilangan sifat nazorati oʻlchov protokoli boʻyicha", fullTable: "Toʻliq qiyoslash jadvali" },
    lead: "Yagona injiniring tizimi sifatida nazorat qilinadigan toʻrtta parametr. Har bir sinf tayyor raketkaning eʼlon qilingan spetsifikatsiyasiga qanchalik qatʼiy rioya qilishini va qanday sifat yozuvlari yaratilishini belgilaydi.",
    statement: "Vazn. Balans. Swingweight. Qattiqlik. Yagona injiniring tizimi sifatida nazorat qilinadi.",
    classes: {
      "P2.5": { name: "Masshtablanadigan performans yadrosi", qc: "Individual oʻlchov va saqlanadigan ishlab chiqarish yozuvlari." },
      "P1.5": { name: "Kengaytirilgan aniqlik", qc: "Individual oʻlchov, individual yozuvlar va kuzatuvchanlik." },
      "P0.5": { name: "Professional · individual nazorat ostida", qc: "Nominal va haqiqiy qiymatlar hamda individual oʻlchov yozuvlari bilan individual nazorat; buyurtma dasturi shuni koʻzda tutsa — seriya raqami, partiya kuzatuvchanligi, aniqlik sertifikati va moslashtirilgan toʻplamlar." },
    },
    columns: { cls: "Sinf", weight: "Vazn", balance: "Balans", sw: "Swingweight", stiff: "Qattiqlik", qc: "Sifat nazorati arxitekturasi" },
    stiffTarget: "maqsadli chetlanish",
    stiffExact: "zavodning belgilangan oʻlchov protokoli boʻyicha eʼlon qilingan maqsadli RA ga mos keladi",
    programmeNote: "Seriya raqami, sertifikatlar va moslashtirilgan toʻplam hujjatlari faqat muayyan buyurtma dasturi shuni koʻzda tutgan hollarda beriladi.",
    targetsNote: "Qattiqlik spetsifikatsiyalari — tegishli protokol va ishlab chiqarish dalillari kuchliroq daʼvoni qoʻllab-quvvatlamaguncha ishlab chiqarish maqsadlari hisoblanadi. Arxitektura taklifi har bir roʻyxatdagi konfiguratsiya toʻrt parametrli chiqarish jarayonini toʻliq oʻtganini anglatmaydi.",
    stiffnessTitle: "Qattiqlik nega muhim",
    stiffnessP1: "Rama qattiqligi ramaning kontakt nuqtasida qanday javob berishiga, qanday sezilishiga va ikki raketkaning bir-biriga qanchalik mos kelishiga taʼsir qiladi. Uni nazorat qilishning asosiy foydasi — eʼlon qilingan spetsifikatsiyaga nisbatan takrorlanadigan javob.",
    stiffnessP2: "Tasdiqlangan muvofiqlik eʼlon qilinishidan oldin ichki sifat nazorati yozuvida asbob, uning kalibrlash holati, usul, raketkaning holati, aniqlik darajasi, oʻlchov noaniqligi, takroriy oʻlchovlar, yaxlitlash qoidasi va qabul qilish qoidasi koʻrsatiladi. Ekranda bir xil butun son koʻrinishi fizik oʻzgarishning yoki oʻlchov xatosining nolga tengligini isbotlamaydi.",
    fields: ["Maqsad", "Oʻlchangan natija", "Ruxsat etilgan chetlanish", "Asbobning imkoniyati"],
    fieldsNote: "Har bir yozuvda alohida maydonlar sifatida saqlanadi.",
    matchedTitle: "Moslashtirilgan toʻplamlar",
    matchedP: "Moslashtirilgan toʻplam mezonlari individual chetlanishdan alohida belgilanadi. Har bir raketkaning oʻz nominal chetlanishiga mos kelishi oʻz-oʻzidan ikki raketka oʻrtasidagi muayyan maksimal farqni isbotlamaydi. Moslashtirilgan juftliklar, uchliklar va jamoa toʻplamlari konfigurator orqali soʻraladi va yozma ravishda tasdiqlanadi.",
    extendedTitle: "Kengaytirilgan texnik model",
    extendedP: "Maʼlumotlar modeli qoʻshimcha parametrlarni qoʻllab-quvvatlaydi. Ular uchun hali qiymatlar yoki chetlanish sinflari mavjud emas; ularni texnik topshiriqda soʻralgan maqsadlar sifatida koʻrsatish mumkin.",
    extended: { twistweight: "Twistweight", torsionalBehaviour: "Burilishga xulq-atvor", length: "Uzunlik", beamProfile: "Rama profili", headGeometry: "Bosh geometriyasi", stringPattern: "Tor sxemasi", durability: "Chidamlilik", vibration: "Tebranish xususiyatlari" },
    noZero: "MAXIMUS roʻyxatdagi qatorini nol chetlanishli deb taʼriflamaydi. Qatordagi aniqlik eʼlon qilingan chetlanish va belgilangan sifat nazorati arxitekturasiga ega sinf sifatida koʻrsatiladi. ZERO qator tarkibiga kirmaydi.",
    zero: {
      eyebrow: "Eksklyuziv variant",
      title: "ZERO",
      sub: "Nol gramm chetlanish.",
      p: "Uch sinf tayyor raketkani eʼlon qilingan chetlanish oraligʻi ichida ushlab turadi. ZERO bu oraliqni olib tashlaydi. Raketka oʻlchov qiymati zavod asbobining aniqlik darajasida eʼlon qilingan qiymatga teng boʻlguncha tayyorlanadi va oʻlchanadi; shu oʻlchov qiymati raketka bilan birga beriladi. U roʻyxatdagi qator tarkibiga kirmaydi va toʻrtinchi sinf emas: bitta raketka yoki bitta moslashtirilgan toʻplam uchun maxsus tayyorlanadigan eksklyuziv sifatida individual kelishiladi. Kelishuvga koʻra xuddi shu yondashuv balans va swingweight uchun ham qoʻllanadi.",
      points: [
        ["Oraliq yoʻq", "Eʼlon qilingan qiymat — natijaning oʻzi, chetlanishning markazi emas."],
        ["Har galda bitta raketka", "Yagona birlik sifatida tayyorlanadi, oʻlchanadi va qayd etiladi."],
        ["Raketka bilan birga beriladi", "Oʻlchangan qiymat topshiriladi va ishlab chiqarish yozuvida saqlanadi."],
        ["Yozma ravishda tasdiqlanadi", "Parametrlar, qamrov va yetkazib berish muddati ishlab chiqarishdan oldin kelishiladi."],
      ],
      note: "Tenglik zavod oʻlchov asbobining aniqlik darajasida amal qiladi. Ekranda bir xil qiymat koʻrinishi fizik oʻzgarish nolga teng degan daʼvo emas. Mavjudlik va shartlar har bir buyurtma uchun individual kelishiladi.",
      cta: "ZERO soʻrash",
    },
    cta: "Aniqlik sinfi bilan konfiguratsiya qilish",
  },
  grip: {
    title: "Zavod grip arxitekturasi",
    statement: "Sakkizta zavod grip oʻlchami. L0–L7.",
    lead: "Grip geometriyasi — karbon dastak arxitekturasining bir qismi. Har bir oʻlcham dastak geometriyasi sifatida ishlab chiqariladi, overgriplar bilan qalinlashtirilmaydi.",
    emph: "Kengaytirilgan oʻlchamlar",
    p1: "Sakkiz oʻlchamli zavod qatori murabbiylar va oʻyinchilarga jihozni oʻyinchi atrofida belgilash imkonini beradigan kengroq konfiguratsiya diapazonini, shu qatorda kattaroq L6 va L7 geometriyalarini beradi.",
    p2: "Nominal grip belgisi dastakning xom konstruktiv oʻlchamlaridan va yakuniy oʻlchov protokolidan farq qiladi. Oʻlchamlar bu platformadagi performans seriyalariga va mashgʻulot oilalariga tegishli.",
    p3: "Bu qator uchun butun dunyo boʻyicha eksklyuzivlik daʼvo qilinmaydi.",
    columns: { size: "Oʻlcham", nominal: "Nominal belgi", family: "Qoʻllaniladi" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "Oʻz grip oʻlchamingiz bilan konfiguratsiya qilish",
  },
  custom: {
    title: "Maxsus injiniring",
    statement: "Spetsifikatsiya boʻyicha ishlab chiqilgan.",
    sub: "Standart qator — faqat boshlangʻich nuqta.",
    lead: "MAXIMUS eʼlon qilingan konfiguratsiya matritsalaridan tashqaridagi texnik talablarni baholash, injiniring, validatsiya va kelishilgan spetsifikatsiya boʻyicha ishlab chiqarish uchun qabul qiladi. Amalga oshirish imkoniyati koʻrib chiqish orqali tasdiqlanadi — har qanday tasavvur qilinadigan soʻrov fizik yoki tijorat jihatdan amalga oshirilmaydi.",
    scopeTitle: "Texnik topshiriq nimalarni qamrab olishi mumkin",
    scope: ["Bosh va rama geometriyasi", "Uzunlik", "Vazn", "Balans", "Swingweight", "Qattiqlik", "Twistweight", "Grip geometriyasi", "Konstruksiya", "Moslashtirilgan toʻplamlar", "Mashgʻulot ramalari", "Kosmetika va gravirovka", "Identifikatsiya va jamoa dasturlari", "Asbob-uskunaga bogʻliq ishlab chiqish"],
    processTitle: "Jarayon",
    process: [
      ["Belgilash", "Afzal maqsadlar, majburiy cheklovlar, foydalanish maqsadi va qabul qilinadigan murosalar."],
      ["Injiniring", "Platforma va asbob-uskunaga nisbatan injiniring bahosi."],
      ["Validatsiya", "Kelishilgan spetsifikatsiyaga nisbatan validatsiya."],
      ["Spetsifikatsiya", "Oʻlchov asosi va chetlanishlari bilan yozma spetsifikatsiya."],
      ["Ishlab chiqarish", "Spetsifikatsiya boʻyicha ishlab chiqarish."],
      ["Oʻlchash / qayd etish", "Tegishli aniqlik sinfi boʻyicha oʻlchash va saqlanadigan yozuvlar."],
    ],
    formTitle: "Texnik topshiriq yuborish",
    formLead: "Afzal maqsadlarni majburiy cheklovlardan ajratib koʻrsating. Natija — texnik koʻrib chiqish soʻrovi, avtomatik qabul qilingan ishlab chiqarish buyurtmasi emas.",
    protected: "Karbon qatlamlash retseptlari, asbob-uskuna, yetkazib beruvchilar maʼlumoti, ichki tannarx va himoyalangan nou-xau bu yoʻl orqali ochilmaydi.",
    cta: "Texnik topshiriq yuborish",
  },
  training: {
    title: "Mashgʻulot tizimlari",
    lead: "Oʻz ishlab chiqarish standartlariga ega ikkita mashgʻulot oilasi bitta metodologiya bilan bogʻlangan: murabbiy boshchiligidagi mashgʻulot, yozuvlar, qayta baholash va performans oʻyiniga qaytish.",
    sst: { h: "Sweet Spot Trainer", p: "Markazlashgan kontaktni mashq qilish, sweet spot hissini rivojlantirish, raketkani nazorat qilish va bosqichma-bosqich yuklama uchun toʻrt vaznli tizimdagi 50 in² kichraytirilgan boshli mashgʻulot raketkasi." },
    spot: { h: "Spot Trainer", p: "Tasdiqlangan toʻrt vaznli asosda, kichik yumaloq kontakt nishoni yordamida kontakt nuqtasini mashq qilish." },
    method: { h: "Metodologiya", p: "Maqsadlarni belgilash, murabbiy ishtirokida jihozni tanlash, tegishli tizimdan foydalanish, qayd etish, qayta baholash, sozlash va koʻchirish." },
    experience: "Qoʻlga oling. Zarba bering. His qiling.",
    experienceP: "Sinov, fitting yoki murabbiy koʻmagidagi namoyish soʻrang. Yuborilgan soʻrov tasdiqlangan uchrashuv emas.",
    cta: "Fitting yoki namoyish soʻrash",
    distinct: "Sweet Spot Trainer, Spot Trainer va har qanday alohida namoyish qurilmasi — turli mahsulotlar va hech qachon birlashtirilmaydi.",
  },
  sst: {
    title: "Sweet Spot Trainer",
    lead: "Oʻz ishlab chiqarish standartiga ega alohida mashgʻulot toifasi. 50 in² bosh eʼtiborni kontakt joyiga qaratadi; toʻrtta vazn yuklama bosqichlarini taʼminlaydi.",
    baseline: "Tasdiqlangan asos",
    columns: { head: "Bosh", length: "Uzunlik", pattern: "Tor sxemasi", grips: "Zavod griplari" },
    systemTitle: "Toʻrt raketkali tizim",
    detailsTitle: "Konstruksiya tafsilotlari",
    systemLead: "Vazn va balans — yetkazib berilgan holatda. Oʻlchov asosi alohida qayd etiladi va hali eʼlon qilinmagan.",
    purposeTitle: "Maqsad",
    purpose: ["Markazlashgan kontaktni mashq qilish", "Sweet spot hissi", "Raketkani nazorat qilish", "Bosqichma-bosqich yuklama", "Murabbiy boshchiligida rivojlanish", "Oʻyinchining performans raketkasiga qaytish"],
    heavy: "400 g modeli — nazorat ostidagi mashgʻulot konfiguratsiyasi. U bolalarga, boshlovchilarga yoki har bir oʻyinchiga avtomatik tavsiya etilmaydi; yuklamani, davomiylikni va bosqichlarni murabbiy belgilaydi.",
    precisionNote: "P2.5, P1.5 va P0.5 performans aniqlik sinflari bu mashgʻulot oilasiga avtomatik qoʻllanilmaydi. Mashgʻulot ishlab chiqarish chetlanishlari oilaning oʻz tasdiqlangan spetsifikatsiyasiga amal qiladi.",
    health: "Tennischi tirsagining oldini olish yoki davolash, jarohatlarni yoʻqotish yoki natijani kafolatlangan yaxshilash vaʼda qilinmaydi.",
    cta: "Sweet Spot Trainer namoyishini soʻrash",
  },
  spot: {
    title: "Spot Trainer",
    lead: "Kichik yumaloq kontakt nishoni yordamida kontakt nuqtasini mashq qilish. Oʻz vizual identifikatsiyasiga ega alohida mahsulot, tasdiqlangan toʻrt vaznli asosda qurilgan.",
    purposeTitle: "Tasdiqlangan maqsad",
    purposeP: "Oʻyinchini aniq kontakt nuqtasini topishga va uni takrorlashga oʻrgatish.",
    weightsTitle: "Vazn bosqichlari",
    weightsP: "Vazn bosqichlari tasdiqlangan Sweet Spot Trainer vazn asosiga amal qiladi. Balans qiymatlari va Sweet Spot Trainer ning boshqa spetsifikatsiyalari Spot Trainer ga koʻchirilmaydi.",
    dims: "Nishonning aniq oʻlchamlari hali eʼlon qilinmagan.",
    grips: "Zavod grip arxitekturasi L0–L7.",
    notes: ["Performans aniqlik sinflari avtomatik qoʻllanilmaydi.", "Bu oddiy raketkaning kichraytirilgan nusxasi emas va hech qanday tor sxemasi eʼlon qilinmaydi.", "Spot Trainer, Sweet Spot Trainer va har qanday alohida namoyish qurilmasi bir-biridan farqlanadigan boʻlib qoladi."],
    cta: "Spot Trainer haqida soʻrash",
  },
  methodology: {
    title: "Metodologiya va mahsulot tajribasi",
    lead: "Jihoz — tizimli rivojlanish yoʻlining bir qismi. Usul mahsulot yorligʻidan emas, oʻyinchining maqsadlaridan boshlanadi.",
    stepsTitle: "Rivojlanish yoʻli",
    steps: [
      ["Maqsadlarni belgilash", "Oʻyinchining maqsadlari va boshlangʻich nuqtasi."],
      ["Jihozni tanlash", "Murabbiy ishtirokida mos jihoz tanlanadi."],
      ["Tizimdan foydalanish", "Tegishli mashgʻulot tizimi, murabbiy boshchiligida."],
      ["Qayd etish", "Haqiqiy ishtirok kuzatuvlari, oʻylab topilgan ballarsiz."],
      ["Qayta baholash", "Qiyoslanadigan nazorat nuqtalari."],
      ["Sozlash", "Konfiguratsiya yoki dasturga tuzatishlar."],
      ["Koʻchirish", "Oʻzlashtirilgan narsalar performans oʻyiniga koʻchiriladi."],
    ],
    educationTitle: "Taʼlim yoʻllari",
    education: { player: "Oʻyinchilar — konfiguratsiya, yuklama va bosqichlarni tushunish.", parent: "Ota-onalar — rivojlanish uzluksizligi, mos jihoz, yozuvlar va huquqlar.", coach: "Murabbiylar — mashgʻulot tizimlari, fitting, baholash va ruxsat etilgan dasturlardan foydalanish." },
    evidenceTitle: "Dalil intizomi",
    evidenceP: "Haqiqiy ishtirok va kuzatuvlar yozuvlari oʻz tasnifi bilan saqlanadi — ishtirokchi tomonidan bildirilgan, vasiy tomonidan tasdiqlangan, murabbiy tomonidan tekshirilgan yoki tizim tomonidan oʻlchangan. Natijalar, ballar va tasdiqlar hech qachon oʻylab topilmaydi.",
    experienceTitle: "Qoʻlga oling. Zarba bering. His qiling.",
    experienceP: "Sinov, fitting yoki murabbiy koʻmagidagi namoyishni soʻrash mumkin. Yuborilgan soʻrov tasdiqlangan uchrashuv emas.",
    cta: "Fitting yoki namoyish soʻrash",
    cta2: "Murabbiylik hamkorligi boʻyicha murojaat",
  },
  gps: {
    metaTitle: "MAXIMUS GPS — boshqariladigan jihoz profili",
    title: "MAXIMUS GPS",
    lead: "Boshqariladigan jihoz profili. Faqat oʻzingizga tegishli savollarga javob bering; javoblarni koʻrib chiqing va tuzating; xulosa, qoʻllanadigan konfiguratsiya yoʻnalishlari va haqiqiy keyingi harakatni oling.",
    honesty: "Bu versiyada avtomatik fitting qoidalari tasdiqlanmagan. Shuning uchun GPS aniq talablar xulosasini tayyorlaydi va konfiguratsiya yoʻnalishlarini koʻrsatadi; jihozning tafsilotlari ekspert koʻrigiga yoʻnaltiriladi.",
    rulesVersion: "Qoidalar versiyasi",
    dataVersion: "Mahsulot maʼlumotlari versiyasi",
    steps: { role: "Rol", sport: "Sport turi", experience: "Tajriba", objectives: "Maqsadlar", style: "Oʻyin uslubi", equipment: "Hozirgi jihoz", preference: "Afzalliklar", coach: "Murabbiy ishtiroki", ageBand: "Yosh guruhi", review: "Tekshirish" },
    notStored: "Bu brauzerda saqlanmaydi.",
    ageNote: "Faqat soʻrovni yoʻnaltirish uchun ishlatiladi. Ism, tugʻilgan sana yoki tibbiy maʼlumot soʻralmaydi.",
    q: {
      role: "Oʻzingizni qanday taʼriflaysiz?",
      sport: "Qaysi sport turi?",
      experience: "Tajriba darajasi",
      objectives: "Sizga nima eng muhim? (uchtagacha tanlang)",
      style: "Oʻyin uslubi, agar bilsangiz",
      equipment: "Hozirgi jihoz, agar bor boʻlsa",
      equipmentHint: "Brend va model, bilsangiz vazn yoki grip. Majburiy emas.",
      preference: "Afzal konfiguratsiya yoki maʼlum grip oʻlchami",
      grip: "Maʼlum grip oʻlchami",
      coach: "Jihoz boʻyicha qarorlarda murabbiy ishtirok etadimi?",
      ageBand: "Oʻyinchining yosh guruhi (faqat soʻrovni toʻgʻri yoʻnaltirish uchun ishlatiladi)",
    },
    roles: { player: "Oʻyinchi", parent: "Ota-ona yoki vasiy", coach: "Murabbiy", club: "Klub yoki akademiya", other: "Boshqa" },
    sports: { tennis: "Tennis", padel: "Padel", pickleball: "Pikleboll", squash: "Skvosh", badminton: "Badminton", other: "Boshqa raketka sporti" },
    sportNote: "Mahsulotlar tennis uchun mavjud. Boshqa sport turlari — rivojlanish yoʻnalishlari; qiziqishingiz tegishli dastur uchun qayd etiladi.",
    experience: { beginner: "Boshlovchi", developing: "Rivojlanayotgan", intermediate: "Oʻrta daraja", advanced: "Yuqori daraja", competitive: "Musobaqa darajasi", professional: "Professional daraja" },
    objectives: { control: "Nazorat", power: "Quvvat", spin: "Aylanish", comfort: "Qulaylik", manoeuvrability: "Manevrchanlik", development: "Uzoq muddatli rivojlanish", competition: "Musobaqa", training: "Mashgʻulot tizimi", team: "Jamoa yoki moslashtirilgan toʻplam", personal: "Personalizatsiya" },
    styles: { baseline: "Orqa chiziqdan", allcourt: "Universal", attacking: "Hujumkor", defensive: "Himoyaviy", coach: "Murabbiy tanlaydi", unknown: "Bilmayman" },
    ageBands: { u10: "10 yoshgacha", u14: "10–13", u18: "14–17", adult: "18 va undan katta" },
    output: {
      title: "Sizning jihoz profilingiz",
      status: "Ekspert koʻrigi talab qilinadi",
      statusP: "Bu versiyada avtomatik moslik tayyorlanmaydi. Profilingiz ekspert koʻrigi uchun xulosa qilindi.",
      directionsTitle: "Qoʻllanadigan konfiguratsiya yoʻnalishlari",
      directionsP: "Siz bildirgan maqsadlar va har bir seriyaning eʼlon qilingan oʻyin yoʻnalishi asosida. Bu yoʻnalish, fitting tavsiyasi emas.",
      trainingHint: "Maqsadlaringiz orasida mashgʻulot tizimi bor: Sweet Spot Trainer va Spot Trainer bilan tanishing.",
      teamHint: "Moslashtirilgan toʻplamlar konfigurator orqali soʻraladi va yozma ravishda tasdiqlanadi.",
      next1: "Profilni ekspert koʻrigiga yuborish",
      show: "Profilimni koʻrsatish",
      configure: "Konfiguratsiya qilish",
      sendP: "Profilingizni ekspert koʻrigi uchun MAXIMUS ga yuboring. Soʻrov raqami darhol koʻrsatiladi; javob yozma ravishda keladi.",
      otherSport: "MAXIMUS raketkalari tennis uchun mavjud. Boshqa raketka sport turlari uchun hech qanday tennis seriyasi taklif qilinmaydi; qiziqishingiz rivojlanish yoʻnalishi sifatida qayd etiladi.",
      noDirection: "Maqsadlaringiz bitta oʻyin yoʻnalishini koʻrsatmaydi. Konfiguratsiyani ekspert koʻrigi taklif qiladi.",
      incomplete: "Baʼzi majburiy javoblar yoʻq — ularni toʻldirish uchun «Javoblarni tahrirlash» dan foydalaning.",
    },
    privacy: "GPS tibbiy maʼlumot ham, bolaning identifikatorlarini ham soʻramaydi. Bu brauzer sessiyasida faqat variantlardan tanlangan javoblar saqlanadi; erkin matn saqlanmaydi.",
  },
  build: {
    title: "Oʻz raketkangizni yarating",
    lead: "Soʻrovni konfiguratsiya qiling: seriya, aniqlik sinfi, roʻyxatdagi vazn yoki maxsus maqsad, grip oʻlchami, soʻralgan maqsadlar, personalizatsiya, moslashtirilgan toʻplamlar va miqdor. Natija — soʻrov raqamiga ega konfiguratsiya soʻrovi, SKU, narx, yetkazib berish sanasi yoki sertifikat emas.",
    steps: { series: "Seriya", cls: "Aniqlik sinfi", weight: "Vazn", grip: "Grip oʻlchami", targets: "Maqsadlar", personal: "Personalizatsiya", set: "Toʻplam va miqdor", use: "Foydalanish", review: "Tekshirish" },
    q: {
      series: "Seriyani tanlang",
      cls: "Aniqlik sinfini tanlang",
      weightMode: "Vazn",
      listed: "Roʻyxatdagi vazn",
      customWeight: "Soʻralgan vazn (g)",
      balanceShown: "Bu vazn uchun hisoblangan balans",
      balanceRequest: "Soʻralgan balans (mm)",
      grip: "Zavod grip oʻlchami",
      targetsTitle: "Soʻralgan maqsadlar",
      swingweight: "Soʻralgan swingweight (kg·cm²)",
      stiffness: "Soʻralgan qattiqlik (RA)",
      basis: "Soʻralgan qiymatlar uchun oʻlchov asosi",
      engraving: "Gravirovka matni",
      engravingHint: "Ism, bosh harflar yoki raqam. Lotin harflari, raqamlar, boʻshliq, chiziqcha, apostrof va nuqta; 24 belgigacha. Boshqa yozuvlar maketni tasdiqlash uchun qabul qilinadi.",
      engravingType: "Personalizatsiya",
      types: { none: "Yoʻq", name: "Oʻyinchining ismi", initials: "Bosh harflar", number: "Toʻplam raqami", academy: "Murabbiy yoki akademiya identifikatsiyasi", team: "Jamoa dasturi" },
      set: "Alohida raketka yoki moslashtirilgan toʻplam",
      use: "Foydalanish maqsadi",
      uses: { play: "Shaxsiy oʻyin", competition: "Musobaqa", coaching: "Murabbiylik", team: "Jamoa yoki akademiya", retail: "Chakana savdo yoki distribyutorlikni baholash", other: "Boshqa" },
      notes: "Qoʻshimcha texnik talablar",
    },
    classes: { "P2.5": "P2.5 — masshtablanadigan performans yadrosi", "P1.5": "P1.5 — kengaytirilgan aniqlik", "P0.5": "P0.5 — professional, individual nazorat ostida" },
    stiffExactShort: "qattiqlik zavodning belgilangan protokoli boʻyicha eʼlon qilingan maqsadli RA ga mos keladi",
    clsNote: "Har bir sinf toʻrtta parametrni nazorat qiladi. P0.5 — belgilangan oʻlchov protokoli boʻyicha qatʼiy chetlanish chegarasi, nol xatolik emas. Seriya raqami, sertifikatlar va moslashtirilgan toʻplam hujjatlari faqat buyurtmangiz dasturi shuni koʻzda tutgan hollarda qoʻllanadi.",
    listedNote: "Seriyaning tasdiqlangan matritsasidan.",
    customNote: "Matritsadan tashqaridagi vazn, texnik jihatdan koʻrib chiqiladi.",
    balanceCaption: "Har bir roʻyxatdagi vazn dastak uchidan mm da hisoblangan balansini koʻrsatadi. Hisoblangan qiymatlar individual oʻlchovlar emas.",
    spinNote: "SPIN vaznlari soʻralgan vazn arxitekturasini tashkil qiladi. SPIN uchun balans, swingweight va qattiqlik taqdim etilmagan; ular texnik koʻrib chiqishda belgilanadi.",
    customHint: "Butun grammlarda, faqat raqamlar. Maxsus vazn — texnik koʻrib chiqish uchun soʻrov; amalga oshirish imkoniyati yozma ravishda tasdiqlanadi va hech qanday qiymat yaxlitlanmaydi.",
    gripNote: "zavodda ishlangan karbon dastak geometriyasi, overgrip bilan qalinlashtirish emas",
    targetsLead: "Majburiy emas. Faqat kerakli qiymatlarni kiriting. Har biri eʼlon qilingan spetsifikatsiya emas, texnik koʻrib chiqish uchun soʻralgan maqsad sifatida qayd etiladi.",
    basisHint: "Maxsus vazn yoki biror maqsadni soʻraganingizda majburiy: qiymatlar torlanmagan yoki torlangan raketkaga tegishlimi?",
    inputRange: "Qabul qilinadigan kiritish: {min}–{max}.",
    inputRangeNote: "Kiritish diapazonlari faqat imkonsiz qiymatlarni saralaydi. Ular ishlab chiqarish imkoniyatini taʼriflamaydi.",
    listedBasis: "roʻyxatdagi qiymatlar — oʻlchov asosi yozma spetsifikatsiyada tasdiqlanadi",
    notStored: "Bu brauzerda saqlanmaydi; sahifani qayta yuklasangiz, uni qaytadan kiriting.",
    artworkReview: "maketni tasdiqlash talab qilinadi",
    previewNote: "Vizual koʻrinish koʻrsatilmaydi: bu model uchun tasdiqlangan gravirovka shabloni hali eʼlon qilinmagan. Matningiz maketni tasdiqlash uchun yigʻiladi.",
    teamSub: "toʻplamda 4–99 raketka",
    setsLabel: { individual: "Raketkalar soni", pair: "Moslashtirilgan juftliklar soni", triple: "Moslashtirilgan uchliklar soni", team: "Jamoa toʻplamlari soni" },
    teamSizeLabel: "Bitta jamoa toʻplamidagi raketkalar",
    totalLabel: "Jami raketkalar",
    racquetsUnit: "raketka",
    setRule: "Miqdor toʻplamlar bilan hisoblanadi: moslashtirilgan juftlikda toʻplamiga 2 raketka, uchlikda — 3.",
    restart: "Yangi konfiguratsiyani boshlash",
    notices: { weightCleared: "{w} g {series} matritsasida yoʻq, shuning uchun vazn tozalandi. Roʻyxatdagi vaznni tanlang yoki maxsus maqsadni soʻrang." },
    reviewTitle: "Konfiguratsiya soʻrovi",
    reviewP: "Konfiguratsiyani tekshiring, soʻngra aloqa maʼlumotlaringizni qoʻshing. Soʻrov soʻrov raqami bilan saqlanadi va yozma ravishda javob beriladi; mavjudlik va tijorat shartlari yozma ravishda tasdiqlanadi.",
    reviewErrors: "Baʼzi konfiguratsiya javoblariga eʼtibor qaratish kerak:",
    edit: "Tahrirlash",
    fieldNames: { series: "Seriya", cls: "Aniqlik sinfi", mode: "Vaznni tanlash", weight: "Roʻyxatdagi vazn", customWeight: "Soʻralgan vazn", basis: "Oʻlchov asosi", balanceReq: "Soʻralgan balans", sw: "Soʻralgan swingweight", ra: "Soʻralgan qattiqlik", grip: "Grip oʻlchami", ptype: "Personalizatsiya", engraving: "Gravirovka matni", setType: "Toʻplam turi", sets: "Miqdor", teamSize: "Bitta jamoa toʻplamidagi raketkalar", use: "Foydalanish maqsadi", notes: "Qoʻshimcha talablar" },
    status: { listed: "roʻyxatdagi vazn", requestedArchitecture: "soʻralgan vazn arxitekturasi", technicalReview: "texnik koʻrib chiqish uchun soʻrov", notPublished: "taqdim etilmagan", requestedCondition: "soʻralgan holat" },
    chooseLink: "Qaysi seriya mos kelishini bilmayapsizmi? Tanlashda yordam oling",
    cta: "Konfiguratsiya soʻrovini yuborish",
  },
  experience: {
    title: "Sinov va fitting",
    statement: "Qoʻlga oling. Zarba bering. His qiling.",
    lead: "Sinov, fitting yoki murabbiy koʻmagidagi namoyish soʻrang. Soʻrovlar koʻrib chiqiladi va yozma ravishda javob beriladi; yuborilgan soʻrov tasdiqlangan uchrashuv emas.",
    optionsTitle: "Nimani soʻrash mumkin",
    options: ["Raketkani sinab koʻrish", "Fitting seansi", "Murabbiy koʻmagidagi namoyish", "Sweet Spot Trainer yoki Spot Trainer namoyishi", "Jamoa yoki akademiya uchun demo kun"],
    formTitle: "Fitting yoki namoyish soʻrovi",
  },
  engineering: {
    title: "Injiniring va ishlab chiqarish",
    statement: "Samolyotlar. Yaxtalar. Raketkalar.",
    lead: "Uch muhitda bitta injiniring falsafasi: samolyotni shakllantiradigan tamoyillar, yaxtani ochiq suvda boshqaradigan aniqlik, har bir MAXIMUS raketkasini belgilaydigan performans. Bu — injiniring bayoni, aviatsiya sertifikati, yaxta egaligi, zavod egaligi yoki materiallarning bevosita koʻchirilishi haqidagi daʼvo emas.",
    manifesto: ["Biz buyuk injiniringning chegarasi yoʻq deb hisoblaymiz.", "Bitta falsafa. Murosasiz injiniring."],
    capabilityTitle: "Ishlab chiqarish imkoniyati",
    capabilityLead: "Imkoniyat shior sifatida emas, ketma-ketlik sifatida koʻrsatiladi.",
    sequence: [
      ["Spetsifikatsiya", "Seriya, aniqlik sinfi, vazn, balans, swingweight, qattiqlik maqsadi, grip geometriyasi, personalizatsiya."],
      ["Ishlab chiqarish", "Ramadan dastakkacha toʻliq karbon konstruksiya, spetsifikatsiya boʻyicha ishlab chiqariladi."],
      ["Sifat nazorati", "Aniqlik sinfi boʻyicha oʻlchash va yozuvlar: ishlab chiqarish yozuvlari, individual yozuvlar va kuzatuvchanlik, individual sertifikatlash."],
      ["Takroriy ishlab chiqarish", "Partiyalar boʻylab eʼlon qilingan spetsifikatsiyaga nisbatan takrorlanadigan javob."],
      ["Kuzatuvchanlik", "Sinf koʻzda tutgan hollarda seriya raqami, partiya kuzatuvchanligi va Aniqlik sertifikati."],
    ],
    capacityNote: "Ishlab chiqarish quvvati, yetkazib berish muddatlari, minimal miqdorlar va yetkazib berish jadvallari har bir dastur uchun tasdiqlangan buyurtmalar va kelishilgan chiqarish jadvaliga nisbatan yozma ravishda tasdiqlanadi.",
    truth: "Quvvat — bu hajm, ombordagi qoldiq, kafolatlangan yetkazib berish sanasi yoki ishlab chiqarish quvvatiga egalik emas.",
    cta: "Distribyutorlik va mamlakatni rivojlantirish",
    cta2: "Texnik topshiriq yuborish",
  },
  ecosystem: {
    title: "MAXIMUS ekotizimi",
    lead: "Bitta kalit. Mana u nimani ochadi. Har bir tugun tushuntirishga, aniq holatga va tegishli keyingi harakatga ega.",
    words: ["Injiniring", "Performans", "Innovatsiya", "Jamoa", "Imkoniyat", "Maqsad"],
    nodes: {
      engineering: { h: "Raketka injiniringi va ishlab chiqarishi", p: "Spetsifikatsiya boʻyicha ishlab chiqilgan toʻliq karbon raketkalar, sifat yozuvlari va kuzatuvchanlik bilan ishlab chiqariladi.", a: "Injiniring va ishlab chiqarish" },
      precision: { h: "Aniqlik va individual konfiguratsiya", p: "Toʻrtta parametr, uchta aniqlik sinfi, sakkizta grip oʻlchami va maxsus injiniring.", a: "Aniqlik va qattiqlik" },
      training: { h: "Mashgʻulot va metodologiya", p: "Sweet Spot Trainer, Spot Trainer va tizimli rivojlanish yoʻli.", a: "Mashgʻulot tizimlari" },
      development: { h: "Oʻyinchi va murabbiy rivojlanishi", p: "Murabbiy boshchiligida tanlash, yozuvlar, qayta baholash va taʼlim yoʻllari.", a: "Metodologiya" },
      identity: { h: "Shaxsiy identifikatsiya va shaxsiy brendlar", p: "Gravirovkadan huquqlar bilan boshqariladigan shaxsiy yoki professional brendgacha.", a: "Shaxsiy brendlar" },
      owners: { h: "Egalar yozuvlari, bilim va huquqlar", p: "Jihoz, rivojlanish va huquqlar yozuvlari uchun taklif qilinayotgan ruxsat asosidagi egalar sayfi.", a: "Egalar va sayf" },
      mipa: { h: "MIPA kelib chiqishi va ichki nazorati", p: "Ichki intellektual mulk, kelib chiqish va hujjat nazorati qatlami.", a: "Huquqiy maqom va nazorat" },
      digital: { h: "Raqamli infratuzilma va Blockchain 5.0 yoʻnalishi", p: "Kelib chiqish, kuzatiladigan yozuvlar, ruxsat asosidagi dalillar va mahsulot identifikatsiyasi — eʼlon qilingan texnologiya yoʻnalishi sifatida.", a: "Texnologiya yoʻnalishi" },
      licensing: { h: "Shartnoma asosidagi litsenziyalash va royalti dasturlari", p: "Shartlari har bir kelishuv boʻyicha belgilanadigan litsenziyalangan brendlar, mahsulotlar va huquqlar paketlari.", a: "Litsenziyalash yoʻllari" },
      families: { h: "Oilaning ishtiroki va dastur imtiyozlari", p: "Xabardor qarorlar, uzluksizlik, saqlanadigan yozuvlar va dastur belgilagan imtiyozlar.", a: "Oilalar va ota-onalar" },
      network: { h: "MAXIMUS Sports Network", p: "Oʻyinchilar, murabbiylar, klublar, akademiyalar, xizmat koʻrsatuvchilar, operatorlar va hududiy hamkorlar.", a: "Sports Network" },
      market: { h: "Klublar, akademiyalar, distribyutorlik va mamlakatni rivojlantirish", p: "Yozma kvalifikatsiya orqali jamoa dasturlari, chakana savdo, distribyutorlik va hududni rivojlantirish.", a: "Hamkorlik yoʻllari" },
      institutional: { h: "Institutsional dasturlar, taʼlim, innovatsiya va ijtimoiy taʼsir", p: "Dastur shu rolni belgilagan hollarda MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) taqdim etadigan institutsional qatlam.", a: "Institutsional dasturlar" },
      extensions: { h: "Kelgusi raketka sportlari va MAXIMUS kiyim yoʻnalishlari", p: "Padel, pikleboll, skvosh, badminton, raketbol, plyaj tennisi va kiyim — rivojlanish yoʻnalishlari sifatida.", a: "Raketka sportlari" },
    },
    boundaryTitle: "Chegaralar",
    boundary: [
      "Raketka xaridi institutsional aʼzolik, boshqaruv huquqlari, royalti yoki investitsiya huquqlarini vujudga keltirmaydi.",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) faqat dastur shu rolni belgilagan hollarda institutsional operator hisoblanadi; jihoz savdosida haqiqiy shartnoma tuzuvchi shaxs koʻrsatiladi.",
      "Grantlar, xayriya maqomi, soliq rejimi va tartibga soluvchi ruxsatlar mamlakatlar boʻylab avtomatik qoʻllanilmaydi.",
    ],
    techTitle: "Texnologiya yoʻnalishi",
    techP: "Blockchain 5.0 — eʼlon qilingan MAXIMUS texnologiya yoʻnalishi. Uning funksional maqsadlari: kelib chiqish, kuzatiladigan yozuvlar, ruxsat asosidagi dalillar, mahsulot identifikatsiyasi va shartlarga mos tijorat hodisalarini solishtirish. Hech qanday konsensus mexanizmi, tranzaksiya quvvati, tugunlar tarmogʻi, smart-kontrakt manzili, token yoki mustaqil sertifikat taqdim etilmaydi va joriy etilgan amalga oshirish daʼvo qilinmaydi. Shaxsiy maʼlumotlar, bolalarga tegishli yozuvlar va maxfiy kelishuvlar hech qachon sukut boʻyicha ommaviy oʻzgarmas tizimga joylashtirilmaydi.",
  },
  brands: {
    title: "Shaxsiy brendlar va brend elchilari",
    statement: "Oʻyinchidan brendga. Murabbiydan brendga.",
    lead: "Alohida shaxsiy brend yoʻli. MAXIMUS ishtiroki brendni rivojlantirish va kelishilgan targʻibotni oʻz ichiga oladi — faqat raketkadagi ism emas.",
    progressionTitle: "Koʻzda tutilgan bosqichlar",
    progression: [
      ["Tasdiqlangan shaxs", "Tasdiqlangan shaxs va rivojlanish tarixi."],
      ["Oʻziga xos brend", "Oʻziga xos shaxsiy yoki professional brend."],
      ["Huquqlari tozalangan kontent", "Huquqlari tozalangan kontent va tasdiqlangan mahsulot identifikatsiyasi."],
      ["Injiniring va kolleksiyalar", "Kelishilgan hollarda injiniring va kolleksiyani ishlab chiqish."],
      ["Targʻibot", "Kelishilgan MAXIMUS kanallari va hamkorliklari orqali targʻibot."],
      ["Ishtirok", "Shartlarga mos savdo yoki litsenziyalashda shartnomaviy ishtirok."],
      ["Hisobot", "Kelishuv boʻyicha shaffof hisobot."],
    ],
    royaltiesTitle: "Royalti va litsenziyalash",
    royalties: [
      "Royalti belgilangan litsenziyalangan brend, mahsulot, tranzaksiya yoki huquqlar paketiga bogʻlanadi.",
      "«Butun dunyo boʻyicha savdo» shartnoma qamrovidagi shartlarga mos savdoni anglatadi — hech qachon har qanday aloqasi yoʻq MAXIMUS raketkasini emas.",
      "Stavkalar, hisoblash asosi, hududlar, muddat, qaytarishlar, chegirmalar, hisobot, hisob-kitob va tekshiruv tegishli kelishuv orqali belgilanadi. Hech qanday sukut boʻyicha royalti foizi eʼlon qilinmaydi.",
      "Kelishilgan qamrovsiz hech qanday global kampaniya, media byudjeti, sponsorlik natijasi yoki tijorat muvaffaqiyati vaʼda qilinmaydi.",
    ],
    cta: "Brend hamkorligi boʻyicha murojaat yuborish",
    cta2: "Murabbiylik hamkorligi boʻyicha murojaat",
  },
  families: {
    title: "Oilalar va ota-onalar",
    lead: "Jihoz boʻyicha xabardor qarorlar, rivojlanish uzluksizligi, saqlanadigan bilim va huquqlar, ishtirokning koʻrinib turishi hamda kelgusi faoliyatni qoʻllab-quvvatlashi mumkin boʻlgan dastur imtiyozlari.",
    nowTitle: "Hozir mavjud",
    now: ["Oila va rivojlanish boʻyicha yozma murojaatlar.", "Murabbiy ishtirokida jihozni tanlash, fitting va namoyish soʻrovlari.", "Maxfiy yozuvlar: bolalarning profillari hech qachon eʼlon qilinmaydi va sukut boʻyicha tijoratlashtirilmaydi.", "Ota-onalar uchun taʼlim yoʻli: konfiguratsiya, yuklama, bosqichlar, yozuvlar va huquqlar."],
    plannedTitle: "Rejalashtirilgan",
    planned: ["Pul foizi emas, ekotizim ichidagi tovar va xizmatlar uchun ishlatiladigan, dastur belgilagan ishtirok imtiyozlari.", "Taklif qilinayotgan egalar sayfida egalar va oila yozuvlari — vasiy ruxsatlari va 18 yoshda nazoratning oʻtishi bilan."],
    categoriesTitle: "Alohida yuritiladi",
    categories: ["Litsenziyalangan huquqlar yoki shartlarga mos savdodan kelib chiqadigan shartnomaviy royalti", "Dastur belgilagan ishtirok imtiyozlari", "Xarid yoki xizmat krediti", "Oldindan toʻlovlar", "Institutsional aʼzolik"],
    categoriesP: "Bu toifalar hech qachon bir-birining oʻrnini bosadigan deb hisoblanmaydi.",
    statusTitle: "Oila dasturining haqiqiy holati",
    journeyTitle: "Oila yoʻli",
    journey: [
      ["Maqsad", "Oʻyinchi keyingi navbatda nimaga erishmoqchi."],
      ["Hozirgi daraja", "Oʻyinchi bugun qaysi darajada."],
      ["Murabbiy", "Jihoz boʻyicha qarorlarda murabbiy ishtirok etadimi."],
      ["Jihoz", "Bosqichga mos jihoz, kerak boʻlganda mashgʻulot tizimlari bilan."],
      ["Kelishilgan mashgʻulot", "Oldindan kelishilgan, murabbiy boshchiligidagi foydalanish."],
      ["Tekshirish", "Qiyoslanadigan nazorat nuqtalarida qayta baholash."],
    ],
    brief: {
      who: "Har qanday bosqichdagi oʻyinchilarning ota-onalari va vasiylari.",
      value: "Mos jihoz, murabbiyning ishtiroki va keyingi rivojlanish qadami boʻyicha yozma javob.",
      now: "Oila murojaatlari yozma ravishda; murabbiy ishtirokida tanlash; maxfiy yozuvlar — bolalarning profillari hech qachon eʼlon qilinmaydi.",
      next: "Quyida oila murojaatini yuboring. Soʻrov raqamini darhol olasiz.",
    },
    formTitle: "Oila murojaati",
    formNote: "Ota-ona yoki vasiy tomonidan toʻldirilishi kerak. Bolaning ismini, tugʻilgan sanasini, maktabini yoki tibbiy maʼlumotini kiritmang.",
    noPromise: "Xarid royalti, investitsiya daromadi, sponsorlik yoki bolaning rivojlanishini moliyalashtirishni vaʼda qilmaydi.",
    statusP: "Bu versiya modelni tushuntiradi va dastur boʻyicha murojaatlarni qabul qiladi. Hisoblash, toʻlovlar va imtiyozdan foydalanish — shartlarga mos hodisalar, benefitsiarlar, moliyalashtirish manbasi, hisoblash asosi, ruxsat etilgan foydalanish turlari, buxgalteriya hisobi, qaytarishlar, bekor qilishlar, amal qilish muddati, oʻtkazilishi, dasturning yopilishi va nizolarni hal qilish yozma ravishda belgilanmaguncha mavjud emas. Hech qanday balans kamaymasligi vaʼda qilinmaydi, hech qanday ishtirok barcha mashgʻulotlar uchun toʻlamaydi va kapitalning himoyasi nazarda tutilmaydi.",
    cta: "Oila yoki rivojlanish boʻyicha murojaat yuborish",
  },
  owners: {
    title: "Egalar va egalar sayfi",
    lead: "Egalar sayfi — jihoz, rivojlanish, bilim, kontent va hujjatlashtirilgan huquqlarning taklif qilinayotgan ruxsat asosidagi yozuvi. U rejalashtirilgan egalar arxitekturasining qismi sifatida taqdim etiladi: hech qanday faol hisob, balans, sertifikat yoki yutuq koʻrsatilmaydi.",
    nowTitle: "Hozirgi egalar uchun hozir",
    now: ["Egalar murojaatlari: mahsulot yoki seriya raqami, sozlash, xizmat va yozuvlar boʻyicha yozma soʻrovlar.", "Aniqlik sinfi koʻzda tutgan hollarda Aniqlik sertifikati va moslashtirilgan toʻplam hujjatlari mahsulot bilan birga beriladi."],
    archTitle: "Rejalashtirilgan sayf arxitekturasi",
    arch: ["Mahsulot identifikatsiyasi va seriya raqamlari", "Konfiguratsiya va tegishli sifat nazorati sertifikatlari", "Xizmat va sozlash tarixi", "Oʻyinchi yoki murabbiyning rivojlanish yozuvlari", "Malakalar va tasdiqlangan yutuqlar", "Huquqlari tozalangan media va muallif materiallari", "Litsenziyalar, ruxsatlar va shartnoma havolalari", "Shaxsiy brend dasturi yozuvlari", "Tegishli royalti hisobotlari yoki ishtirok imtiyozlari"],
    separationTitle: "Egalik nimani anglatadi",
    separation: [
      "Jismoniy raketkaga egalik mualliflik huquqiga, litsenziyaga, shartnomaviy huquqqa yoki bularni taʼriflaydigan yozuvga egalikdan alohida.",
      "Saqlangan hujjat yoki blokcheyn yozuvi huquqiy huquq mavjudligini yoki oʻtganini avtomatik isbotlamaydi.",
      "Dalil oʻz tasnifini saqlaydi: ishtirokchi tomonidan bildirilgan, vasiy tomonidan tasdiqlangan, murabbiy tomonidan tekshirilgan, tizim tomonidan oʻlchangan.",
      "Voyaga yetmaganlar uchun: maxfiy yozuvlar, vasiy ruxsatlari, bolalarning eʼlon qilingan profillari yoʻq va sukut boʻyicha shaxsni tijoratlashtirish yoʻq.",
      "Eksport, tuzatish, kirishni nazorat qilish va nazoratning tegishli tarzda oʻtishi loyihaning qismidir.",
    ],
    techTitle: "Blockchain 5.0 va MxSN",
    techP: "Blockchain 5.0 — eʼlon qilingan texnologiya yoʻnalishi; MxSN rozilik, yetkazib berish, dalil, huquqlar va hisobot uchun ruxsat asosidagi tarmoq tushunchalarini belgilaydi. Operatsion joriy etilish taqdim etilmaydi. Ilovaning maʼlumotlar modeli keyinchalik hujjatlashtirilgan interfeys orqali integratsiya qilish uchun qurilgan — bugun ulanish bor degan koʻrinish yaratmasdan.",
    cta: "Egalar murojaati",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "Oʻyinchilar, murabbiylar, klublar, akademiyalar, xizmat koʻrsatuvchilar, dastur operatorlari va hududiy hamkorlar oʻrtasidagi bogʻliqlik.",
    functionsTitle: "Mumkin boʻlgan funksiyalar",
    functions: ["Topish", "Tanishtirish", "Rivojlanish dasturlari", "Jihoz boʻyicha koʻmak", "Tadbirlar", "Xizmatlardan foydalanish", "Hamkorlik imkoniyatlari"],
    statusTitle: "Haqiqiy holat",
    statusP: "Hali hech qanday ommaviy katalog eʼlon qilinmagan: faqat shaxsi, munosabati va koʻrinish uchun ruxsati belgilangan ishtirokchilar roʻyxatga kiritiladi. Klubga yuborilgan taklif hamkorlik emas, boʻlgʻusi distribyutor esa tayinlangan distribyutor emas. Katalog nashri, bronlash, xabar almashish va tijorat operatsiyalari alohida nazorat qilinadi va hozir faol emas.",
    cta: "Tarmoqqa arizani yuborish",
  },
  partnerships: {
    title: "Hamkorlik yoʻllari",
    lead: "Avvalo yozma kvalifikatsiya. Har bir yoʻl rolga mos murojaatga olib boradi; tijorat shartlari keyin yozma ravishda keladi.",
    commercialTitle: "Platformaning mumkin boʻlgan tijorat faoliyati",
    commercial: ["Jihoz", "Maxsus injiniring", "Personalizatsiya", "Jamoa va akademiya dasturlari", "Mashgʻulot tizimlari", "Shartnoma asosidagi litsenziyalash", "Distribyutorlik", "Tasdiqlangan xizmatlar", "Kelgusi mahsulot toifalari"],
    boundary: "Mamlakat huquqlari, eksklyuzivlik, hudud toʻlovlari va distribyutor marjasi — muzokara shartlari. Hech qanday daromad, prognoz, baholash, bozor ulushi, daromadlilik, moliyalashtirish majburiyati yoki nomi koʻrsatilmagan hamkorlik eʼlon qilinmaydi.",
    routes: {
      coaches: {
        title: "Murabbiylar",
        lead: "Mashgʻulot tizimlari, fitting, professional identifikatsiya, ruxsat etilgan dasturlar, shaxsiy brend imkoniyatlari va jihoz taʼminoti.",
        points: ["Murabbiy boshchiligidagi mashgʻulotda Sweet Spot Trainer va Spot Trainer.", "Konfiguratsiya matritsalari va sakkizta zavod grip oʻlchami bilan fitting.", "Coach-to-Brand: tasdiqlangan professional profil va huquqlar bilan boshqariladigan sub-brend.", "Ruxsat etilgan dasturlardan foydalanish yozma kelishuvga amal qiladi."],
        cta: "Murabbiylik hamkorligi boʻyicha murojaat yuborish",
        brief: {
          who: "Mustaqil murabbiylar va murabbiylar guruhlari.",
          value: "Murabbiy boshchiligidagi mashgʻulot uchun mashgʻulot tizimlari, seriya matritsalari va sakkizta zavod gripi bilan fitting hamda professional identifikatsiyaga yoʻl.",
          now: "Murabbiylar murojaatlari yozma ravishda. Hech qanday komissiya, daromad yoki tavsiya stavkasi eʼlon qilinmaydi va nazarda tutilmaydi.",
          next: "Quyida murabbiylik murojaatini yuboring. Shartlar keyin yozma ravishda keladi.",
        },
        purpose: "coach",
      },
      clubs: {
        title: "Klublar va akademiyalar",
        lead: "Jamoa jihozi, mashgʻulot tizimlari, personalizatsiya, rivojlanish dasturlari, xizmat va tarmoqda ishtirok.",
        points: ["Konfigurator orqali soʻraladigan jamoa va moslashtirilgan toʻplamlar.", "Tizimli rivojlanish uchun mashgʻulot tizimlari va metodologiya.", "Tasdiqlangan zonalarda jamoa dasturlari uchun personalizatsiya.", "Demo kunlar, fitting seanslari va tarmoqda ishtirok."],
        cta: "Klub yoki akademiya topshirigʻini yuborish",
        brief: {
          who: "Klublar, akademiyalar va jamoa dasturlari.",
          value: "Jamoa va moslashtirilgan toʻplamlar, mashgʻulot tizimlari, jamoa dasturlari uchun personalizatsiya va namoyish kunlari.",
          now: "Klub va akademiya topshiriqlari yozma ravishda; jamoa toʻplamlari konfigurator orqali soʻraladi.",
          next: "Quyida klub yoki akademiya topshirigʻini yuboring.",
        },
        purpose: "club",
      },
      distribution: {
        title: "Distribyutorlik va mamlakatni rivojlantirish",
        lead: "Assortiment, ishlab chiqarishni muvofiqlashtirish, texnik imkoniyat, hududni rivojlantirish va maxfiy tijorat kvalifikatsiyasi.",
        points: ["Kontragent, hudud va kanalning yozma kvalifikatsiyasi.", "Assortiment konfiguratsiya matritsalari va aniqlik sinflari asosida belgilanadi.", "Hudud, eksklyuzivlik, hajmlar, narx va tijorat himoyasi — yozma ravishda kelishiladigan muzokara shartlari.", "Shartnoma tuzuvchi shaxs, toʻlov shartlari va yetkazib berish asosi har bir operatsiya boʻyicha koʻrsatiladi."],
        cta: "Distribyutorlik yoki mamlakatni rivojlantirish boʻyicha murojaat yuborish",
        brief: {
          who: "Chakana sotuvchilar, distribyutorlar va mamlakat hamkorlari.",
          value: "Tasdiqlangan matritsalar, aniqlik sinflari va grip qatori asosida belgilangan assortiment, hudud va kanalning yozma kvalifikatsiyasi bilan.",
          now: "Distribyutorlik murojaatlari yozma ravishda. Hudud, eksklyuzivlik, hajmlar va narx muzokara qilinadi — hech biri forma orqali berilmaydi.",
          next: "Quyida distribyutorlik murojaatini yuboring.",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "Strategik va investitsiya",
        lead: "Injiniring imkoniyati, konfiguratsiya chuqurligi, ishlab chiqarish modeli, bozorga chiqish yoʻllari, intellektual mulk, xizmatlar va kengayish imkoniyatlari.",
        points: ["Malakali strategik muhokama yoki nazorat ostidagi maʼlumotdan foydalanish yozma kvalifikatsiyadan keyin boʻladi.", "Ommaviy maʼlumot tasdiqlangan mahsulot spetsifikatsiyalari, konfiguratsiya arxitekturasi, tasdiqlangan imkoniyatlar va dastur tushuntirishlari bilan cheklanadi.", "Xaridorga xos iqtisodiy koʻrsatkichlar, tannarx, himoyalangan metodologiya va eʼlon qilinmagan kelishuvlar faqat NDA yoki shartnoma asosida ochiladi."],
        cta: "Malakali strategik muhokamani soʻrash",
        brief: {
          who: "Investorlar va strategik hamkorlar.",
          value: "Injiniring imkoniyati, konfiguratsiya chuqurligi, ishlab chiqarish modeli, bozorga chiqish yoʻllari va intellektual mulk boʻyicha malakali muhokama.",
          now: "Hech qanday moliyaviy koʻrsatkich, prognoz, baholash yoki daromadlilik eʼlon qilinmaydi. Nazorat ostidagi maʼlumot yozma kvalifikatsiya va NDA dan keyin beriladi.",
          next: "Quyida malakali strategik muhokamani soʻrang.",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "Institutsional dasturlar",
        lead: "Taʼlim, imkoniyatlardan foydalanish, innovatsiya, rivojlanish dalillari, ijtimoiy taʼsir va tegishli tarzda tuzilgan dasturlar.",
        points: ["Institutsional dasturlar, dastur shu rolni belgilagan hollarda, MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC) orqali tuziladi.", "Cheklangan dastur mablagʻlari va tijorat operatsiyalari alohida qoladi.", "Murojaat qabul qilingan aʼzolik arizasi emas, jihoz xaridori esa institutsional aʼzo emas.", "Grantlar, xayriya maqomi, soliq rejimi va tartibga soluvchi ruxsatlar mamlakatga xos boʻlib, hech qachon oldindan nazarda tutilmaydi."],
        cta: "Institutsional dastur boʻyicha murojaat yuborish",
        brief: {
          who: "Institutlar, taʼlim va rivojlanish dasturlari.",
          value: "Taʼlim, imkoniyatlardan foydalanish, innovatsiya va rivojlanish dalillari uchun dasturlar, tegishli operator bilan tuzilgan.",
          now: "Institutsional murojaatlar yozma ravishda. Murojaat aʼzolik arizasi emas; jihoz xaridi institutsional aʼzolik emas.",
          next: "Quyida institutsional murojaatni yuboring.",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "Ommaviy va nazorat ostidagi oshkoralik",
    disclosure: {
      public: { h: "Ommaviy", p: "Tasdiqlangan mahsulot spetsifikatsiyalari, konstruksiya, konfiguratsiya arxitekturasi, mashgʻulot maqsadlari, tasdiqlangan imkoniyatlar, dastur tushuntirishlari va hamkorlik yoʻllari." },
      qualified: { h: "Malakali murojaat", p: "Texnik talablar, miqdorlar, hududga qiziqish, rivojlantirish qamrovi va tegishli tijorat muhokamalari." },
      controlled: { h: "NDA yoki shartnoma nazorati ostida", p: "Ichki formulalar, batafsil sifat nazorati protokollari, karbon qatlamlashlar, asbob-uskuna, ishlab chiqarish usullari, yetkazib beruvchilar maʼlumoti, tannarx, xaridorga xos iqtisodiy koʻrsatkichlar, himoyalangan metodologiya, eʼlon qilinmagan kelishuvlar va maxfiy huquqlar yozuvlari." },
    },
  },
  contact: {
    title: "Aloqa va soʻrovlar",
    lead: "Soʻrovingizning maqsadini tanlang. Har bir forma faqat soʻrovni yoʻnaltirish va baholash uchun kerakli maʼlumotni yigʻadi. Soʻrovlarga yozma ravishda javob beriladi.",
    email: "E-pochta",
    instagram: "Instagram",
    legalLink: "Huquqiy maqom",
  },
  form: {
    purposeLabel: "Soʻrovning maqsadi",
    purposes: {
      selection: "Raketka tanlashda yordam",
      product: "Mahsulot boʻyicha murojaat",
      fitting: "Fitting yoki namoyish",
      technical: "Texnik topshiriq",
      config: "Konfiguratsiya soʻrovi",
      gps: "GPS jihoz profili",
      coach: "Murabbiylik hamkorligi",
      club: "Klub yoki akademiya topshirigʻi",
      distribution: "Distribyutorlik yoki mamlakatni rivojlantirish",
      brand: "Brend hamkorligi yoki brend elchisi",
      family: "Oila yoki rivojlanish boʻyicha murojaat",
      institutional: "Institutsional dastur",
      strategic: "Strategik yoki investitsiya muhokamasi",
      owner: "Egalar murojaati",
      network: "Sports Network ga ariza",
      general: "Umumiy murojaat",
    },
    fields: {
      name: "Ism",
      email: "E-pochta",
      role: "Rolingiz",
      country: "Mamlakat yoki hudud",
      organisation: "Tashkilot",
      message: "Xabaringiz",
      level: "Hozirgi daraja",
      objectives: "Nima eng muhim (uchtagacha)",
      currentRacquet: "Hozirgi raketka",
      grip: "Grip oʻlchami, agar bilsangiz",
      seriesInterest: "Qiziqtirgan seriya",
      quantity: "Miqdor",
      city: "Seans uchun shahar yoki joy",
      coachInvolved: "Murabbiy ishtirok etadimi?",
      timing: "Afzal vaqt",
      targets: "Afzal maqsadlar",
      limits: "Majburiy cheklovlar",
      use: "Foydalanish maqsadi",
      tradeoffs: "Qabul qilinadigan murosalar",
      basis: "Oʻlchov asosi",
      players: "Oʻyinchilar soni",
      interests: "Qiziqish sohalari",
      territory: "Qiziqtirgan hudud",
      channels: "Mavjud kanallar va tajriba",
      audience: "Auditoriya yoki yoʻnalish",
      proposal: "Taklif qilinayotgan hamkorlik",
      goal: "Rivojlanish maqsadi",
      ageBand: "Oʻyinchining yosh guruhi",
      scope: "Dastur qamrovi",
      interestArea: "Qiziqish sohasi",
      productRef: "Mahsulot yoki seriya raqami",
      requestType: "Soʻrov turi",
      seeking: "Nimani izlayotganingiz",
      consent: "MAXIMUS bu soʻrovga javob berish uchun bu maʼlumotlarni saqlashi va ishlatishiga roziman. Bu marketing obunasi emas.",
    },
    roles: { player: "Oʻyinchi", parent: "Ota-ona yoki vasiy", coach: "Murabbiy", club: "Klub yoki akademiya", retailer: "Chakana sotuvchi", distributor: "Distribyutor", brand: "Brend yoki brend elchisi", investor: "Investor yoki strategik hamkor", institution: "Institut", other: "Boshqa" },
    interestOptions: { training: "Mashgʻulot tizimlari", fitting: "Fitting", identity: "Professional identifikatsiya", programmes: "Ruxsat etilgan dasturlar", brand: "Shaxsiy brend", supply: "Jihoz taʼminoti", team: "Jamoa jihozi", personalisation: "Personalizatsiya", development: "Rivojlanish dasturlari", service: "Xizmat", network: "Tarmoqda ishtirok" },
    ownerTypes: { setup: "Sozlash va konfiguratsiya", service: "Xizmat", records: "Yozuvlar va sertifikatlar", other: "Boshqa" },
    strategicAreas: { engineering: "Injiniring imkoniyati", configuration: "Konfiguratsiya chuqurligi", manufacturing: "Ishlab chiqarish modeli", routes: "Bozorga chiqish yoʻllari", ip: "Intellektual mulk va xizmatlar", expansion: "Kengayish imkoniyatlari" },
    errors: {
      required: "Bu maydon toʻldirilishi shart.",
      too_long: "Bu yozuv juda uzun.",
      too_short: "Bu yozuv juda qisqa.",
      invalid_email: "Haqiqiy e-pochta manzilini kiriting, masalan name@example.com.",
      invalid_choice: "Variantlardan birini tanlang.",
      not_number: "Faqat raqamlar bilan butun son kiriting.",
      out_of_range: "Bu qiymat qabul qilinadigan diapazondan tashqarida.",
      not_in_matrix: "Bu vazn tanlangan seriyaning roʻyxatdagi matritsasida yoʻq.",
      decimal_not_supported: "Kasr qismisiz butun son kiriting.",
      too_many: "Uchtadan ortiq variantni tanlamang.",
      consent_required: "MAXIMUS bu soʻrovga javob berishi uchun rozilik talab qilinadi.",
      invalid: "Bu yozuv notoʻgʻri.",
    },
  },
  legal: {
    title: "Huquqiy maqom va nazorat",
    lead: "Ommaviy brend — MAXIMUS / MAXIMUS GPS. Huquqiy operatsion shaxslar bir-biridan farqlanadi va shu yerda koʻrsatilgan.",
    entities: {
      institutional: { role: "Institutsional dastur qatlami", p: "Dastur shu rolni belgilagan hollarda institutsional dastur qatlamini taqdim etadi. Raketkalarning tijorat sotuvchisi emas. Dubai International Financial Centre dagi notijorat tashkilot." },
      equipment: { role: "Jihoz boʻyicha tijorat shaxsi", p: "Amaldagi operatsion hujjatlar shu rolni belgilagan hollarda taʼminot, distribyutorlik va shartnoma asosidagi tijorat yetkazib berish uchun jihoz boʻyicha tijorat shaxsi. Har qanday operatsiya boʻyicha shartnoma tuzuvchi tomon shu operatsiyaning hujjatlarida koʻrsatiladi." },
      ip: { role: "Intellektual mulk, brend va tijoratni muvofiqlashtirish", p: "Belgilangan intellektual mulk, brend yoki tijoratni muvofiqlashtirish roli uchun koʻrinadi. Hech qanday tasdiqlanmagan shartnomaviy javobgarlik yuklanmaydi." },
      stewardship: { role: "Vasiylik havolasi", p: "House of Maximus — tegishli manba qoʻllab-quvvatlagan hollarda ekotizim uchun vasiylik havolasi." },
      control: { role: "Ichki intellektual mulk, kelib chiqish va hujjat nazorati", p: "MIPA — ichki intellektual mulk, kelib chiqish va hujjat nazorati qatlami. Ichki MIPA yozuvi tashqi savdo belgisi, patent, mualliflik huquqi roʻyxatga olinishi yoki sud tomonidan tan olinishidan farq qiladi va vizual tasdiq hisoblanmaydi." },
    },
    labels: { licence: "Litsenziya", registration: "Roʻyxatga olish", vat: "VAT TRN", address: "Manzil", email: "E-pochta", jurisdiction: "Yurisdiksiya" },
    boundaryTitle: "Chegaralar",
    boundary: [
      "Xarid avtomatik ravishda institutsional aʼzolik, boshqaruv huquqlari, royalti yoki investitsiya huquqlarini bermaydi.",
      "Institutsional rol tijorat jihoz operatsiyalaridan alohida.",
      "Maxfiylik, dastur shartlari va nazorat ostidagi kirish tartiblari haqiqatda chiqarilgan funksiyalarga mos keladi.",
      "Hech qanday umumiy qoʻllanadigan huquq bayoni har bir tashrif buyuruvchi, savdo yoki chet eldagi dasturga tegishli emas; shartnomaviy asos har bir kelishuv boʻyicha belgilanadi.",
    ],
  },
  privacy: {
    title: "Maxfiylik",
    updated: "Versiya 2026-09-21 · sayt 4.2",
    contactTitle: "Maxfiylik boʻyicha savollar uchun aloqa",
    sections: {
      collect: ["Nimalar yigʻiladi", "Formani yuborganingizda: siz kiritgan maʼlumotlar (ism, e-pochta, rol, mamlakat yoki hudud, agar koʻrsatilsa tashkilot, xabaringiz va formaning javoblari), tashrifingizning sahifa va kampaniya parametrlari (kirish sahifasi, til, utm parametrlari; reklama bosish identifikatorlari — faqat analitikaga ruxsat bergan boʻlsangiz) hamda yuborilgan vaqt. IP manzilingiz suiisteʼmolni cheklash uchun faqat xeshlangan, qisqa muddatli shaklda ishlatiladi va soʻrovingiz bilan birga saqlanmaydi."],
      purpose: ["Nima uchun", "Soʻrovingizga javob berish, siz soʻragan taklif yoki spetsifikatsiyani tayyorlash va soʻrov yozuvini saqlash uchun. Forma asosida hech qanday marketing xabari yuborilmaydi."],
      storageOn: ["Soʻrovlar qayerda saqlanadi", "Soʻrovlar Upstash, Inc. (Redis) maʼlumotlar bazasida, Vercel Inc. hosting platformasi orqali saqlanadi."],
      notifyEmail: ["Yangi soʻrov haqida xabar", "Soʻrov qabul qilinganda, siz yuborgan maʼlumotlarni oʻz ichiga olgan xabar e-pochta orqali MAXIMUS ning masʼul pochta qutisiga yuboriladi."],
      notifyTelegram: ["Yangi soʻrov haqida xabar", "Soʻrov qabul qilinganda, siz yuborgan maʼlumotlarni oʻz ichiga olgan xabar MAXIMUS dagi masʼul shaxsga Telegram (Telegram FZ-LLC, Dubai) orqali yuboriladi, shuning uchun u shu xabarni uzatish jarayonida qayta ishlaydi."],
      notifyWebhook: ["Yangi soʻrov haqida xabar", "Soʻrov qabul qilinganda, siz yuborgan maʼlumotlarni oʻz ichiga olgan xabar imzolangan, shifrlangan ulanish orqali MAXIMUS ning ichki nuqtasiga yuboriladi."],
      notifyNone: ["Yangi soʻrov haqida xabar", "Yangi soʻrovlar haqida xabar berish sozlanmoqda. Soʻrovingiz saqlanadi va MAXIMUS uni ichki reyestrdan oʻqiydi; bu maqsadda uchinchi tomonga hech narsa yuborilmaydi."],
      storageOff: ["Soʻrovlar qayerda saqlanadi", "Soʻrovlarni saqlash sozlanmoqda. U faollashmaguncha formalar soʻrovni qabul qilish mumkin emasligini koʻrsatadi; hech narsa saqlanmaydi. Sayt Vercel Inc. tomonidan joylashtirilgan."],
      browser: ["Brauzer xotirasi", "Sessiya xotirasi GPS va konfiguratorning variantlardan tanlangan javoblarini hamda tashrifingizning kampaniya parametrlarini shu brauzer sessiyasi uchun saqlaydi. Aloqa maʼlumotlari, erkin matn, gravirovka matni va bolalar haqidagi maʼlumot brauzerda saqlanmaydi."],
      analyticsOn: ["Analitika", "Roziligingiz bilan Google Analytics 4 tashriflar va forma hodisalarini aloqa maʼlumotlari va soʻrov matnisiz oʻlchaydi. Tanlovingiz lokal xotirada saqlanadi va uni istalgan vaqtda pastki qismdagi «Analitika sozlamalari» boʻlimida oʻzgartirish mumkin. Formalar analitikasiz ham ishlaydi."],
      analyticsOff: ["Analitika", "Bu saytda hech qanday analitika vositasi faol emas."],
      retention: ["Saqlash muddati", "Hali hech qanday avtomatik oʻchirish muddati sozlanmagan. Soʻrovingizni oʻchirishni istalgan vaqtda soʻrashingiz mumkin."],
      children: ["Bolalar", "Formalar voyaga yetgan shaxs tomonidan toʻldirilishi kerak. 18 yoshgacha boʻlgan oʻyinchilarga tegishli soʻrovlar ota-ona yoki vasiy tomonidan yuboriladi. Bolaning ismini, tugʻilgan sanasini, maktabini yoki tibbiy maʼlumotini yubormang. Bolalarning profillari hech qachon eʼlon qilinmaydi."],
      rights: ["Huquqlaringiz", "Soʻrovingizdan foydalanish, uni tuzatish yoki oʻchirish uchun gps@maximus.tennis manziliga yozing va soʻrov raqamingizni koʻrsating."],
      controlled: ["Nazorat ostidagi maʼlumot", "Maxfiy hujjatlar bu saytda saqlanmaydi va u orqali taqdim etilmaydi. Nazorat ostidagi oshkoralik NDA yoki shartnoma asosida alohida kanallar orqali amalga oshiriladi."],
    },
  },
  terms: {
    title: "Foydalanish shartlari",
    copyright: "Bu saytga — uning matnlari, suratlari, dizayni va kodiga — mualliflik huquqi faqat Maximus Kiriyakulovga tegishli. U hech qanday kompaniyaga va hech qanday boshqa shaxsga oʻtkazilmagan.",
    updated: "Versiya 2026-09-21",
    sections: [
      ["Maʼlumot, taklif emas", "Bu saytdagi mahsulot maʼlumoti tasdiqlangan spetsifikatsiyalarni, konfiguratsiya arxitekturasini va dastur tushuntirishlarini taʼriflaydi. Bu sotish taklifi, narxlar roʻyxati, ombordagi qoldiq bayoni yoki yetkazib berish majburiyati emas. Tijorat shartlari har bir operatsiyada koʻrsatilgan shartnoma tuzuvchi shaxs bilan alohida, yozma ravishda kelishiladi."],
      ["Soʻrovlar", "Bu sayt orqali yuborilgan soʻrov — shu qatorda GPS profillari, konfiguratsiya soʻrovlari va texnik topshiriqlar — soʻrov raqami bilan saqlanadi va koʻrib chiqiladi. U qabul qilingan buyurtma, ishlab chiqarish majburiyati, tasdiqlangan uchrashuv, aʼzolik arizasi yoki biror dasturga qabul qilingan ariza emas."],
      ["Spetsifikatsiyalar va dalillar", "Hisoblangan qiymatlar, ishlab chiqarish maqsadlari va tasdiqlangan spetsifikatsiyalar tegishli sahifalarda bir-biridan ajratiladi. Qattiqlik qiymatlari boshqacha eʼlon qilinmaguncha ishlab chiqarish maqsadlari hisoblanadi. Muayyan oʻyinchi uchun hech qanday natija kafolatlanmaydi."],
      ["Ekotizim, aʼzolik va huquqlar", "Raketka xaridi institutsional aʼzolik, investitsiya huquqlari, intellektual mulk egaligi, royalti olish huquqi yoki ishtirok imtiyozlarini vujudga keltirmaydi. Huquqlar eʼlon qilingan dastur shartlari yoki yozma kelishuvga amal qiladi."],
      ["Intellektual mulk", "MAXIMUS®, sher emblemasi, GPS belgisi va bu saytning mazmuni himoyalangan. Ichki injiniring formulalari, sifat nazorati protokollari, karbon qatlamlashlar, asbob-uskuna, yetkazib beruvchilar maʼlumoti, tannarx va himoyalangan metodologiya bu yerda ochilmaydi."],
    ],
  },
  lead: {
    submit: "Soʻrovni yuborish",
    submitting: "Yuborilmoqda…",
    retry: "Qaytadan urinib koʻrish",
    acceptedEyebrow: "Soʻrov qabul qilindi",
    acceptedTitle: "Soʻrovingiz qabul qilindi.",
    requestId: "Soʻrov raqami",
    acceptedNext: "MAXIMUS har bir soʻrovni koʻrib chiqadi va siz koʻrsatgan e-pochta manziliga yozma ravishda javob beradi. Keyingi murojaatlar uchun soʻrov raqamini saqlab qoʻying.",
    duplicate: "Bu soʻrov avvalroq qabul qilingan edi; nusxa yaratilmadi.",
    another: "Yangi soʻrovni boshlash",
    errorsTitle: "Iltimos, bu maydonlarni tekshiring:",
    failTitle: "Soʻrovingiz yuborilmadi.",
    fail: {
      offline: "Qurilmangiz internetga ulanmagan.",
      network: "Serverga ulanish amalga oshmadi.",
      timeout: "Server oʻz vaqtida javob bermadi.",
      rate_limited: "Bu tarmoqdan juda koʻp soʻrov keldi. Iltimos, bir necha daqiqadan soʻng qaytadan urinib koʻring.",
      too_fast: "Forma juda tez yuborildi. Iltimos, uni tekshirib, qaytadan yuboring.",
      spam_suspected: "Soʻrov spam filtri tomonidan toʻxtatildi.",
      unavailable: "Hozir soʻrovlar qabul qilinmaydi.",
      default: "Kutilmagan xatolik yuz berdi.",
    },
    keepNote: "Kiritganlaringiz bu sahifada saqlanadi, shuning uchun qaytadan urinib koʻrishingiz mumkin.",
    sendByEmail: "Bu soʻrovni e-pochta orqali yuborish",
    sendByEmailNote: "E-pochta ilovangiz bu soʻrovning matni bilan ochiladi. MAXIMUS uni siz xatni yuborganingizda oladi.",
    mailConfig: "Konfiguratsiya",
    mailPage: "Sahifa",
    fallback: "Muammo davom etsa, {email} manziliga yozing. Soʻrov faqat soʻrov raqami koʻrsatilganda yuborilgan hisoblanadi.",
    privacyLink: "Maxfiylik bildirishnomasi",
    hpLabel: "Bu maydonni boʻsh qoldiring",
    consentShort: "Rozilik",
    after: "Yuborilgandan soʻng bu sahifada soʻrov raqami koʻrsatiladi. Soʻrovlar koʻrib chiqiladi va yozma ravishda javob beriladi; soʻrov buyurtma emas.",
    basis: { unstrung: "Torlanmagan", strung: "Torlangan", unknown: "Bilmayman — spetsifikatsiyada kelishiladi" },
    hints: {
      email: "MAXIMUS bu manzilga yozma ravishda javob beradi.",
      goal: "Masalan: birinchi musobaqa raketkasi yoki yoshlar raketkasidan oʻtish. Bola haqidagi ismlarni, tugʻilgan sanalarni yoki tibbiy maʼlumotni kiritmang.",
      currentRacquet: "Brend va model, agar bilsangiz.",
      message: "Parollarni, toʻlov maʼlumotlarini yoki tibbiy maʼlumotni kiritmang.",
    },
  },
  choose: {
    eyebrow: "Tanlashda yordam",
    title: "Raketka tanlashga yordam bering",
    lead: "MAXIMUS ga darajangizni va sizga nima eng muhim ekanini aytib bering. Javoblaringiz koʻrib chiqiladi va siz yozma taklif olasiz: seriya, aniqlik sinfi, vazn va grip.",
    stepsTitle: "Keyin nima boʻladi",
    steps: [
      ["Javoblaringiz", "Daraja, ustuvorliklar va bilsangiz grip oʻlchami."],
      ["Ekspert koʻrigi", "MAXIMUS javoblaringizni seriya matritsalari bilan qiyoslaydi."],
      ["Yozma taklif", "Taklif qilingan konfiguratsiya va keyingi qadam, yozma ravishda."],
    ],
    formTitle: "Javoblaringiz",
    submit: "Tanlashda yordam soʻrash",
    altTitle: "Oʻzingiz qaror qilmoqchimisiz?",
    altGps: "Batafsil GPS profili",
    altBuild: "Bevosita konfiguratsiya qilish",
    note: "Avtomatik fitting ham, aniqlik daʼvosi ham yoʻq: har bir soʻrovni odam koʻrib chiqadi.",
  },
  consent: {
    title: "Analitika",
    text: "MAXIMUS tashriflarni Google Analytics bilan oʻlchashi mumkinmi? Formalar har qanday holatda ishlaydi; analitikaga hech qanday aloqa maʼlumoti yoki soʻrov matni yuborilmaydi.",
    allow: "Analitikaga ruxsat berish",
    decline: "Rad etish",
  },
  familyPlan: {
    title: "Oilaviy tennis rejasi",
    metaDescription: "Oilangizning tennis byudjetini hisoblang: mashgʻulotlar, soatlar, toʻp bilan kontaktlar hamda bitta mashgʻulot, bir soat va bitta zarba narxi — oʻz raqamlaringiz asosida, uchta ssenariyda.",
    eyebrow: "Oilaviy tennis rejasi · Biz bilan birga hissa qoʻshing",
    heroTitle: "Tennis oilangizga qanchaga tushadi — va buning evaziga nima olasiz?",
    heroLead: "Oilaviy byudjetingizni, u qoplaydigan mashgʻulotlar va soatlar sonini, toʻp bilan kontaktlarning taxminiy miqdorini hamda bitta mashgʻulot, bir soat va bitta zarba narxini oʻz shartlaringiz asosida hisoblang.",
    heroCta: "Oilaviy tennis rejasini hisoblash",
    strategy: {
      eyebrow: "Maqsadimiz",
      title: "Koʻproq tennis. Koʻproq imkoniyat. Birgalikda.",
      p1: "Maqsadimiz — tennis oʻynaydiganlar doirasini kengaytirib, tennisga yoʻlni yanada tushunarli va qulay qilib, jahon tennis bozorini oʻn barobar oʻstirish. MAXIMUS boshqaruv, metodologiya, sifat, natijalar va oʻyinni ommalashtirish orqali yetakchilikka intiladi.",
      p2: "Boshqa tennis jihozlari ishlab chiqaruvchilarini va ularning brendlarini biz salohiyatli hamkorlar deb bilamiz. Kompaniyalar, murabbiylar, klublar va oilalarning kuchlarini tennisni oʻzaro manfaatli asosda rivojlantirish, targʻib qilish va miqyosini kengaytirishga qaratilgan umumiy dasturda birlashtirishni taklif qilamiz.",
      p3: "MAXIMUS — bu yondashuvning beshinchi elementi: alohida kuchlarning birgalikda ishlashiga yordam beradigan birlashtiruvchi boʻgʻin. Umumiy muammolarimiz — kasalliklar, bolalarning kam harakatliligi hamda odamlarning tennis oʻynashni boshlashi va davom ettirishiga xalaqit beradigan toʻsiqlar.",
      p4: "Oila uchun hammasi aniqlikdan boshlanadi. «Oilaviy tennis rejasi» byudjetni, mashgʻulotlar va soatlar sonini, toʻp bilan kontaktlarning taxminiy hajmini va mashgʻulotlar narxini koʻrsatadi. Shartlarni oʻzgartiring va oʻzingizga mos ssenariyni tanlang.",
      note: "Oʻn barobar oʻsish — MAXIMUS strategik maqsadi, allaqachon erishilgan natija emas. Kalkulyator ssenariy hisob-kitoblarini koʻrsatadi va hech qanday tejash, tibbiy samara yoki sport natijasini vaʼda qilmaydi.",
      ctaCalc: "Oilaviy tennis rejasini hisoblash",
      ctaPartner: "Tennisni birgalikda rivojlantirishni muhokama qilish",
    },
    beyond: {
      eyebrow: "Kortdan tashqarida",
      title: "Reja mashgʻulotlardan tashqari nimani yaratadi",
      admission: {
        h: "Yetakchi maktab va universitetlarga qabul",
        p: "MAXIMUS oilani dunyoning yetakchi maktab va universitetlariga kirish yoʻlida qoʻllab-quvvatlaydi: oʻyinchining sport portfoliosini shakllantirish, hujjatlar va arizalarni tayyorlash, sport va oʻqish uygʻun boradigan dasturlarni tanlashda yordam beradi. Sport stipendiyasi berilgan hollarda u oilaning taʼlim uchun xarajatlarini kamaytiradi.",
      },
      assets: {
        h: "Raqamli aktivlar: oʻyinchining ismi, qiyofasi va sport tarixi",
        p: "Oʻyinchining ismi, qiyofasi, natijalari, kontenti va shaxsiy brendi — bu aktivlar boʻlib, vaqt oʻtishi bilan ular katta moliyaviy qiymat va nufuz kasb etishi mumkin. MAXIMUS bu qiymat oʻyinchi va uning oilasida qolishi uchun ularni yaratish, roʻyxatdan oʻtkazish va himoya qilishda yordam beradi.",
      },
      note: "Bularning hech biri kalkulyatorga kirmaydi. Maktabdagi oʻrin, stipendiya yoki raqamli aktivning qiymati muayyan holatga bogʻliq va bu yerda baholanmaydi.",
      cta: "Qabulda koʻmak va raqamli aktivlar haqida soʻrash",
    },
    steps: ["Oila maʼlumotlari", "Mashgʻulotlar iqtisodiyoti", "Uzoq muddatli reja", "Yakuniy hisob-kitob"],
    stepsLabel: "Kalkulyator bosqichlari",
    scenarios: { now: "Hozir", planned: "Reja", wish: "Orzu" },
    scenarioHints: { now: "Oilangiz hozir nima qilayotgani.", planned: "Keyin nima qilmoqchi ekaningiz.", wish: "Nima qilishni xohlashingiz." },
    currency: {
      label: "Valyuta",
      note: "Kiritiladigan barcha summalar shu valyutada. Hech narsa konvertatsiya qilinmaydi.",
    },
    fields: {
      players: { label: "Oʻynaydigan oila aʼzolari soni", hint: "Butun son." },
      cost: { label: "Bir oʻyinchi uchun bitta mashgʻulot narxi", hint: "Butun son, soliq va yigʻimlar bilan birga." },
      sessions: { label: "Bir oʻyinchining oyiga mashgʻulotlar soni", hint: "Butun son." },
      minutes: { label: "Bitta mashgʻulot davomiyligi, daqiqada", hint: "Tanaffuslar bilan birga toʻliq vaqt. Kasr qiymatlar ham mumkin." },
      contacts: { label: "Bir oʻyinchining bitta mashgʻulotdagi toʻp bilan kontaktlari soni", hint: "Kontakt — oʻyinchining oʻz raketkasi toʻpga tegishi. Bitta zarbalar almashinuvi bitta kontakt emas. Barcha ssenariylarda bir xil usulda sanang." },
    },
    presetsLabel: "Tezkor tanlov, daqiqa",
    ages: {
      title: "Reja davomiyligi",
      start: "Boshlangʻich yosh",
      end: "Yakuniy yosh",
      hint: "Reja qancha davom etishi haqidagi anonim taxmin; faqat uzoq muddatli jadvalda ishlatiladi. Bu tugʻilgan sana ham, tavsiya etilgan boshlash yoshi ham emas.",
    },
    extras: {
      title: "Oilaning qoʻshimcha xarajatlari",
      note: "Bu summalar butun oila uchun kiritiladi va uchala ssenariyga ham qoʻllanadi. Ular oʻyinchilar soniga koʻpaytirilmaydi hamda bir soat yoki bitta kontakt narxiga kirmaydi.",
      equipment: "Birinchi jihozlar — butun davr uchun bitta summa",
      clothing: "Kiyim va poyabzal — butun davr uchun bitta summa",
      renewal: "Jihozlarni yangilash — butun davr uchun bitta summa, avtomatik takrorlanmaydi",
      court: "Kort yoki klub — oyiga, butun oila uchun",
      travel: "Safarlar va tadbirlar — oyiga, butun oila uchun",
      quoteSource: "Narxlar manbasi (majburiy emas)",
      quoteDate: "Narxlar sanasi (majburiy emas)",
      quoteNote: "Aynan siz kiritgandek koʻrsatiladi. MAXIMUS bu narxlarni tekshirmaydi.",
    },
    storage: {
      save: "Rejani shu qurilmada saqlash",
      clear: "Rejani shu qurilmadan oʻchirish",
      saved: "Reja shu qurilmada saqlandi. Hech qayerga hech narsa yuborilmadi.",
      cleared: "Reja oʻchirildi. Kalkulyator boshlangʻich qiymatlarga qaytarildi.",
      restored: "Shu qurilmada saqlangan rejangiz tiklandi.",
      invalid: "Shu qurilmada saqlangan rejani oʻqib boʻlmadi, shuning uchun u qoʻllanmadi. Yangi hisob-kitobni boshlashingiz mumkin.",
      unavailable: "Bu brauzer qurilmada maʼlumot saqlashga ruxsat bermaydi.",
    },
    annual: {
      title: "Bir yil: ssenariylar yonma-yon",
      sessions: "Yiliga kishi-mashgʻulotlar",
      cost: "Oilaning yillik mashgʻulot xarajatlari",
      hours: "Yiliga kishi-soatlar",
      length: "Bitta mashgʻulot davomiyligi",
      contacts: "Yiliga toʻp bilan kontaktlar",
      note: "Kishi-mashgʻulotlar va kishi-soatlar barcha oʻyinchilarning mashgʻulotlarini jamlaydi. Bular kort ijarasi soatlari yoki guruh uchrashuvlari emas: birga 90 daqiqa shugʻullangan ikki oʻyinchi — bu 2 kishi-mashgʻulot va 3 kishi-soat.",
    },
    economics: {
      title: "Mashgʻulot, soat va kontakt narxi",
      session: "Bir oʻyinchining bitta mashgʻuloti",
      hour: "Bir oʻyinchi mashgʻulotining bir soati",
      contact: "Toʻp bilan bitta kontakt",
      undefinedContacts: "Aniqlanmagan: 0 kontakt",
      undefinedMinutes: "Aniqlanmagan: 0 daqiqa",
      below: "{value} miqdoridan kam",
      note: "Bu koʻrsatkichlarga faqat mashgʻulot narxi kiradi. Oilaning qoʻshimcha xarajatlari kontaktlar soniga boʻlinmaydi.",
      caption: "Kontaktlar soni tanlangan mashgʻulotlar hajmi va model taxminlari asosida hisoblanadi. Amalda hammasi mashgʻulot formati, tanaffuslar va sharoitlarga bogʻliq. Kontakt narxi — byudjet koʻrsatkichi, murabbiylik sifati koʻrsatkichi emas.",
    },
    longTerm: {
      title: "Uzoq muddatli xarajatlar rejasi",
      horizon: "Muddat",
      activeYears: "Faol yillar",
      years: "{n} yil",
      note: "Faol yillar soni ikki yosh orasidagi farq bilan cheklanadi. Narxlar, mashgʻulotlar chastotasi, inflyatsiya, mavsumiylik, qoldirilgan mashgʻulotlar va valyuta kurslari oʻzgarmas deb olinadi. Qoʻshimcha xarajatlar bu jadvalga kirmaydi.",
    },
    final: {
      title: "Yakuniy hisob-kitob",
      scenario: "Ssenariy",
      months: "Davr, oylarda",
      heading: "{scenario} · {months} oy",
      total: "Davr uchun jami",
      training: "Mashgʻulotlar",
      extras: "Qoʻshimcha xarajatlar",
      oneOff: "Bir martalik xarajatlar",
      monthly: "Oylik xarajatlar × oylar",
      sessions: "Davrdagi kishi-mashgʻulotlar",
      hours: "Davrdagi kishi-soatlar",
      contacts: "Davrdagi toʻp bilan kontaktlar",
      formulaTitle: "Qanday hisoblanadi",
      formula: "Jami = oʻyinchilar × oyiga mashgʻulotlar × oylar × mashgʻulot narxi + bir martalik xarajatlar + oylar × oylik qoʻshimcha xarajatlar.",
      formulaNote: "Qoʻshimcha xarajatlar butun oila uchun kiritiladi. Bir martalik xarajatlar davr 0 oy boʻlsa ham bir marta hisobga olinadi.",
      inputs: "Kiritgan maʼlumotlaringiz",
    },
    units: { min: "daq.", h: "soat", approx: "≈" },
    errors: {
      title: "Natijani koʻrish uchun bu maydonlarni tuzating",
      required: "Majburiy: son kiriting, nol ham mumkin.",
      negative: "Manfiy boʻlishi mumkin emas.",
      integer: "Faqat butun son.",
      number: "Son kiriting.",
      tooLarge: "Bu son hisoblash uchun juda katta.",
      endBeforeStart: "Yakuniy yosh boshlangʻich yoshdan kichik boʻlishi mumkin emas.",
      tooLong: "Koʻpi bilan 200 ta belgi.",
      date: "Toʻgʻri sana kiriting.",
      currency: "Valyutani tanlang.",
      scenario: "Ssenariyni tanlang.",
      result: "Natija ishonchli koʻrsatish uchun juda katta. Kiritilgan qiymatlarni kamaytiring.",
      in: "{scenario}: {field}",
    },
  },
  media: {
    spotComposition: "MAXIMUS Spot Trainer: toʻliq kompozitsiya — oldidan va yondan koʻrsatilgan trenajyor, yumaloq kontakt boshidagi gravirovka qilingan yumaloq sher emblemasi, shaft boʻylab MAXIMUS va SPOT TRAINER gravirovkasi va sher belgili sakkiz qirrali dastak qopqogʻi",
    greatHero: "MAXIMUS GREAT seriyasi, 363 g: qizil va sariq bosh detallari, yaltiroq MAXIMUS yozuvi, shaftdagi Maximus avtografi va dastakdagi sher belgisi bilan toʻliq kompozitsiya",
    spotDetail: "Ikkita MAXIMUS Spot Trainer yaqindan koʻrsatilgan: mat qora kontakt boshidagi gravirovka qilingan sher, qovurgʻali grip oʻrami va sher belgili sakkiz qirrali dastak qopqoqlari",
    spotPair: "Toʻq rangli sirt ustida qiya holatda yotgan ikkita MAXIMUS Spot Trainer, bir shaft boʻylab MAXIMUS, ikkinchi shaft boʻylab SPOT TRAINER gravirovkasi, har bir kontakt boshida sher emblemasi",
    spinVisual: "MAXIMUS SPIN: torlangan bosh, yaltiroq MAXIMUS yozuvi, grip va sherli dastak qopqogʻi",
    powerVisual: "MAXIMUS POWER: torlangan bosh, yaltiroq MAXIMUS yozuvi, personalizatsiya gravirovkasi, grip va sherli dastak qopqogʻi",
    greatVisual: "MAXIMUS GREAT: torlangan bosh, yaltiroq MAXIMUS yozuvi, personalizatsiya gravirovkasi, grip, sherli dastak qopqogʻi va boʻyindagi G seriyasi belgisi",
    spinHead: "MAXIMUS SPIN boshi va tor maydoni",
    handleLion: "MAXIMUS boʻyni, gripi va sher belgisi bilan dastak qopqogʻi",
    engraving: "Shaftdagi kumushrang personalizatsiya gravirovkasi",
    lettering: "Mat qora ramadagi yaltiroq qora MAXIMUS yozuvi",
    variantAlt: "MAXIMUS {series} seriyasi — {w} g, balans {b} mm: spetsifikatsiya chizigʻi, personalizatsiya gravirovkasi zonasi va MIPA belgisi bilan toʻliq vizualizatsiya",
    sstSystem: "MAXIMUS Sweet Spot Trainer, toʻrt raketkali tizim",
    sst270: "Sweet Spot Trainer, 270 g / 330 mm",
    sst285: "Sweet Spot Trainer, 285 g / 325 mm",
    sst300: "Sweet Spot Trainer, 300 g / 325 mm",
    sst400: "Sweet Spot Trainer, 400 g / 320 mm",
    sstShafts: "MAXIMUS yozuvi bilan Sweet Spot Trainer shaftlari",
    sstGrips: "Sweet Spot Trainer griplari va dastak qopqoqlari",
    sstButtcaps: "Sweet Spot Trainer, sher belgisi bilan toʻrtta dastak qopqogʻi",
    note: "Mahsulot tasviri",
  },
  notFound: { title: "Sahifa topilmadi", p: "Siz soʻragan sahifa bu tilda mavjud emas.", cta: "Bosh sahifaga oʻtish" },
};

export default uz;
