/* 简体中文词典 — MAXIMUS 网站 v4.0。产品数值数据位于 data/products.js。结构与 content/en.js 严格一致。 */
const zh = {
  meta: {
    siteName: "MAXIMUS",
    titleSuffix: " | MAXIMUS",
    defaultTitle: "MAXIMUS——按规格设计制造的全碳素网球拍",
    defaultDescription:
      "从拍框到拍柄的全碳素网球拍：GREAT 97 in²、POWER 98 in²与SPIN 100 in²，八种出厂握柄尺寸L0–L7，涵盖重量、平衡点、挥重与硬度的精度等级，以及应要求提供的定制工程。",
  },
  common: {
    statuses: {
      current: "现行",
      agreement: "按协议提供",
      development: "开发中",
      concept: "概念",
      target: "制造目标",
      modelled: "计算值",
      confirmed: "已确认",
      requested: "申请的架构",
      notprovided: "未提供",
    },
    brief: { who: "适用对象", value: "您将获得", now: "目前已确认", next: "下一步" },
    labels: {
      next: "下一步",
      back: "返回",
      edit: "修改答案",
      review: "检查",
      start: "开始",
      restart: "重新开始",
      copy: "复制申请文本",
      copied: "已复制",
      openEmail: "打开邮件发送此申请",
      reference: "申请编号",
      weight: "重量",
      balance: "平衡点",
      swingweight: "挥重",
      stiffness: "硬度",
      grip: "握柄尺寸",
      headSize: "拍面尺寸",
      series: "系列",
      precisionClass: "精度等级",
      quantity: "数量",
      notProvided: "尚未发布",
      requestTarget: "申请目标值",
      grams: "g",
      mm: "mm",
      sqin: "in²",
      inches: "in",
      ra: "RA",
      kgcm2: "kg·cm²",
      readMore: "阅读更多",
      allSeries: "全部系列",
      points: "列表重量数量",
      optional: "可选",
      required: "必填",
      select: "请选择",
      yes: "是",
      no: "否",
      unknown: "不确定",
      custom: "自定义目标值",
      listed: "列表重量",
      individual: "单支球拍",
      pair: "配对拍",
      triple: "三支配对套装",
      team: "团队套装",
      summaryTitle: "您的申请摘要",
      nextAction: "下一步行动",
      status: "状态",
      learn: "了解更多",
      schematic: "示意图——非测量结果",
      photo: "照片",
    },
    ecosystemStrip: "MAXIMUS生态系统",
    truth: {
      noPrices: "价格、最低数量、交付周期、保修与交付承诺按市场和按计划以书面形式确认。",
      requestNotOrder: "申请是一份待审核的申请。它不是已接受的订单、制造承诺或已确认的预约。",
      noGuarantee: "此处描述的任何装备、方法或计划均不保证特定球员获得任何结果。",
    },
  },
  nav: {
    groups: { racquets: "球拍", training: "训练", ecosystem: "生态系统", partnerships: "合作" },
    racquets: "球拍系列与对比",
    great: "GREAT — 97 in² · 控制",
    power: "POWER — 98 in² · 力量",
    spin: "SPIN — 100 in² · 旋转",
    precision: "精度与硬度",
    grip: "出厂握柄架构L0–L7",
    custom: "定制工程",
    training: "训练系统",
    sst: "Sweet Spot Trainer",
    spot: "Spot Trainer",
    methodology: "方法论",
    gps: "MAXIMUS GPS",
    build: "定制您的球拍",
    choose: "帮我挑选",
    ecosystem: "生态系统地图",
    engineering: "工程与制造",
    experience: "体验、试打与适配",
    brands: "个人品牌与品牌大使",
    families: "家庭与家长",
    owners: "所有者与所有者档案库",
    network: "Sports Network",
    partnerships: "全部合作路径",
    coaches: "教练",
    clubs: "俱乐部与学院",
    distribution: "分销与国家市场开发",
    strategic: "战略与投资",
    institutional: "机构计划",
    contact: "联系",
    legal: "法律主体",
    privacy: "隐私",
    terms: "条款",
    menu: "菜单",
    close: "关闭",
    home: "首页",
    skip: "跳至主要内容",
  },
  footer: {
    line: "MAXIMUS球拍，是您进入MAXIMUS世界的钥匙。",
    product: "产品",
    ecosystem: "生态系统",
    company: "组织",
    instagram: "Instagram",
    email: "电子邮箱",
    analytics: "数据分析设置",
    rights: "MAXIMUS®及狮子徽标为MAXIMUS生态系统的标识。MIPA内部知识产权、来源溯源与文件控制。",
    boundary:
      "商业与合同条款另行以书面形式约定。购买球拍不产生机构会员资格、投资权利、知识产权所有权或特许权使用费权益。",
  },
  home: {
    heroEyebrow: "MAXIMUS GPS · GREAT POWER & SPIN",
    heroTitle: "MAXIMUS球拍，是您进入MAXIMUS世界的钥匙。",
    heroProduct: "全碳素球拍，配备出厂握柄L0–L7，按您的要求配置。",
    heroCta1: "找到适合您的球拍",
    heroCta2: "查看各系列",
    heroCaption: "MAXIMUS POWER · 98 in² · 未穿线拍框",
    heroMeta: [
      ["全碳素", "从拍框到拍柄"],
      ["4项参数", "重量·平衡点·挥重·硬度"],
      ["8种握柄尺寸", "出厂几何结构L0–L7"],
      ["3个系列", "GREAT · POWER · SPIN"],
    ],
    paths: {
      eyebrow: "从这里开始",
      title: "选择您的路径",
      items: {
        player: { h: "球员", p: "按水平与侧重点寻找球拍，或直接进行配置。", a: "找到适合您的球拍" },
        parent: { h: "家长", p: "以书面形式进行的路径：发展目标、教练参与及合适的装备。", a: "家庭路径" },
        coach: { h: "教练、俱乐部或学院", p: "训练系统、试打与适配、团队套装与个性化。", a: "教练与俱乐部路径" },
        partner: { h: "经销商或合作伙伴", p: "分销、国家市场开发、战略与机构路径。", a: "合作路径" },
      },
    },
    series: {
      eyebrow: "性能系列",
      title: "三种性能架构。一个工程平台。",
      lead: "按打法方向选择系列，然后完成配置：精度等级、重量、握柄、个性化。",
      cta: "对比各系列",
      configure: "配置",
      open: "查看系列",
      photoPending: "照片尚未发布",
      photoLabel: { great: "GREAT · 拍头与V形拍喉几何结构", power: "POWER · 完整拍框，未穿线" },
    },
    precision: {
      eyebrow: "MAXIMUS精度系统",
      title: "重量。平衡点。挥重。硬度。",
      sub: "作为一个工程系统统一控制。",
      lead: "三个精度等级定义了每支成品球拍与其声明规格的一致程度。P0.5是在既定测量规程下的严格公差——并非零误差。",
      cta: "精度与硬度详情",
    },
    stiffness: {
      eyebrow: "硬度",
      title: "针对声明目标值的可重复拍框响应。",
      p: "拍框硬度影响响应、手感以及球拍之间的一致性。MAXIMUS将其作为第四项受控参数：目标值、测量结果、允许公差与仪器能力分别作为独立记录保存。其价值在于可重复性——而非对每位球员都保证结果。",
      cols: [["响应", "拍框在击球瞬间如何回馈能量。"], ["手感", "球员在击球瞬间的感受。"], ["一致性", "按同一规格制造的球拍，在其精度等级范围内响应一致。"]],
      schematicCaption: "示意图：各等级围绕声明硬度目标值的允许偏差。并非测量结果；不暗示任何RA数值。",
      bands: { p25: "目标公差±1 RA", p15: "目标公差±0.5 RA", p05: "在既定的工厂测量规程下符合声明的RA目标值——并非零误差", target: "声明的目标值（不暗示任何数值）" },
    },
    carbon: {
      eyebrow: "构造标准",
      title: "全碳素。从拍框到拍柄。",
      p: "本平台上所有现行MAXIMUS球拍在结构上均为全碳素，包括拍柄在内。拍柄不使用泡沫成型。",
      gripTitle: "八种出厂握柄尺寸。L0–L7。",
      gripP: "每种尺寸均为出厂碳素拍柄几何结构——而非通过缠绕吸汗带加粗。",
      scaleCaption: "示意图：标称握柄代号L0–L7（4″至4⅞″）。并非实测拍柄尺寸。",
      cta: "出厂握柄架构",
    },
    custom: {
      eyebrow: "定制工程",
      title: "按规格设计制造。",
      sub: "标准产品线只是起点。",
      p: "MAXIMUS接受超出已发布矩阵的技术要求，进行评估、工程设计、验证，并按约定规格制造。可行性以书面形式确认。",
      chain: ["定义", "工程设计", "验证", "规格确定", "生产", "测量/记录"],
      cta: "提交技术需求书",
      cta2: "咨询定制工程",
    },
    training: {
      eyebrow: "训练系统",
      title: "握持。挥动。感受。",
      p: "Sweet Spot Trainer与Spot Trainer将装备与教练主导的练习连接起来：中心击球、控制、渐进式负荷，以及过渡回实战球拍。",
      cta: "训练系统",
      cta2: "申请演示",
      photoPending: "训练拍照片尚未发布",
    },
    manufacturing: {
      eyebrow: "制造与质量控制",
      title: "按规格制造。经测量并记录。",
      p: "生产遵循每份订单的书面规格。记录取决于精度等级：P2.5为留存的生产记录，P1.5为逐支记录与可追溯性，P0.5为逐支控制与文件记录，前提是该订单的计划实施了这些内容。",
      confirmedTitle: "已确认",
      confirmed: ["从拍框到拍柄的全碳素构造。", "精度等级P2.5、P1.5与P0.5，控制四项参数。", "八种出厂握柄尺寸L0–L7。"],
      pendingTitle: "尚未发布",
      pending: "测量设备照片、质检记录样本与工厂影像尚未发布。本页上的任何内容均不是测量证书。",
      captions: { lettering: "哑光黑色拍框上的亮面黑色MAXIMUS字样", buttcap: "拍柄底盖上的狮子徽标", handle: "POWER拍喉至拍柄的过渡段", finish: "表面处理参考——拍框未按系列标识" },
      cta: "工程与制造",
    },
    world: {
      eyebrow: "MAXIMUS世界",
      title: "一把钥匙。一个生态系统。无限机遇。",
      note: "“无限机遇”是品牌表达，并非对无限技术可行性、收入或访问权限的承诺。购买不产生特许权使用费、投资回报、赞助或对球员发展的资助。",
      items: {
        gps: { h: "MAXIMUS GPS", p: "GREAT POWER & SPIN——也是您在网球世界中的导航：一份以书面形式答复的引导式装备档案。" },
        personal: { h: "个性化", p: "姓名、姓名首字母、编号与团队标识，采用经批准的银色刻字工艺。" },
        development: { h: "发展", p: "教练主导的训练系统、记录与重新评估。" },
        ecosystem: { h: "扩展生态系统", p: "个人品牌、所有者记录、网络、许可与机构计划——均按其实际状态呈现。" },
      },
      cta: "探索生态系统",
    },
    partners: {
      eyebrow: "合作路径",
      title: "教练、俱乐部、经销商与合作伙伴。",
      p: "先进行书面资格审核。国家市场权利、独家权与商业条款以书面形式协商——绝不通过表单授予。",
      cta: "全部合作路径",
      formTitle: "简短咨询",
      formLead: "请选择咨询目的并向MAXIMUS留言。您将在本页获得申请编号。",
    },
    gps: { eyebrow: "MAXIMUS GPS", a: { h: "GREAT POWER & SPIN" }, b: { h: "您在网球世界中的导航" } },
    personal: { eyebrow: "个性化", title: "您的名字。您的编号。您的MAXIMUS。" },
    brands: { eyebrow: "Player-to-Brand · Coach-to-Brand" },
    index: { title: "三个系列。真实参数。" },
    map: { cta: "探索生态系统" },
  },
  racquets: {
    title: "球拍",
    lead: "三个性能系列，共享同一构造标准、同一精度系统与同一出厂握柄架构。每个系列都是更广阔工程平台内一种既定的性能架构。",
    direction: { control: "控制", power: "力量", spin: "旋转" },
    directionLabel: "主要打法方向",
    compareTitle: "系列对比",
    compareLead: "仅列出已确认的架构数据。这些系列的穿线模式、长度、拍框截面、张力范围、挥重与硬度标称值尚未发布；它们作为申请目标值收集，供技术审核。",
    columns: { series: "系列", head: "拍面尺寸", direction: "方向", weights: "列表重量", range: "重量范围", balance: "平衡点数据" },
    balanceModelled: "计算值",
    balanceNotProvided: "尚未发布",
    construction: "构造：全碳素，从拍框到拍柄 · 精度：P2.5 / P1.5 / P0.5 · 握柄：L0–L7",
    otherTitle: "其他球拍运动",
    otherLead: "经批准的发展方向。这些类别目前没有可销售的产品，也不将任何网球规格转用于这些类别。",
    other: { padel: "板式网球", pickleball: "匹克球", squash: "壁球", badminton: "羽毛球", racquetball: "短柄壁球", beachTennis: "沙滩网球" },
    ctaConfigure: "发起配置申请",
    ctaSeries: "查看系列",
  },
  seriesPage: {
    eyebrow: "性能系列",
    intro: {
      great: "97 in²的GREAT架构围绕控制而构建：紧凑的拍面、精准的触球与方向上的信心。",
      power: "98 in²的POWER架构围绕能量传递而构建：来自稳定拍框的深度与速度。",
      spin: "100 in²的SPIN架构围绕球路表现而构建：旋转、容错空间与弹道塑造。",
    },
    photoPending: "系列照片尚未发布",
    detailPending: "该系列的构造与拍柄细节照片尚未发布。",
    specsTitle: "规格与状态",
    specs: { head: "拍面尺寸", direction: "主要方向", weights: "列表重量", range: "重量范围", balance: "平衡点", construction: "构造", grips: "出厂握柄", precision: "精度等级" },
    construction: "全碳素，从拍框到拍柄",
    statusTitle: "数值状态",
    spinExplanation: "SPIN保持“申请的重量架构”状态：下列29种重量为申请的架构。SPIN的平衡点、挥重与硬度未提供；它们在技术审核中确定。",
    matrixTitle: "完整重量矩阵",
    matrixLead: "列表重量为标准选项。其他重量可作为自定义目标值申请；不会插入缺失的中间值。",
    balanceNote: {
      modelled: "平衡点数值按每个列表重量计算（自拍柄末端起算，单位mm）。它们并非逐支出厂测量值；测量基准在书面规格中确认。",
      notprovided: "该系列的平衡点数值未提供。请勿从其他系列推断。",
    },
    optionsTitle: "精度、握柄与重量",
    notPublished: "该系列未发布：穿线模式、长度、拍框截面、张力范围、挥重与硬度数值。您可以将其作为申请目标值提出，供技术审核。",
    offerTitle: "提交申请后的流程",
    offerSteps: [
      ["申请", "提交配置或问题。申请编号会立即显示。"],
      ["审核", "MAXIMUS审核系列、等级、重量、握柄以及任何申请目标值。"],
      ["书面答复", "规格、供货情况与商业条款以书面形式确认。"],
    ],
    faqTitle: "常见问题",
    faq: [
      ["平衡点数值是测量值吗？", "它们是针对列表重量的计算值，而非逐支测量值。测量基准在书面规格中确认。"],
      ["我可以申请未列出的重量吗？", "可以，以整克数作为自定义目标值提出。该申请将经过技术审核，可行性以书面形式确认。"],
      ["精度等级会改变什么？", "它决定重量、平衡点、挥重和硬度与声明规格的一致程度，以及保存哪些记录。"],
      ["握柄是通过缠绕吸汗带加粗的吗？", "不是。L0–L7是出厂碳素拍柄几何结构。"],
      ["价格与交付时间在哪里查看？", "它们针对每份申请以书面形式确认，不在此处发布。"],
    ],
    faqSpinBalance: ["SPIN有平衡点数值吗？", "没有。SPIN的平衡点、挥重与硬度未提供；它们在技术审核中确定。"],
    ctaBuild: "配置此系列",
    ctaAsk: "咨询此系列",
    ctaCompare: "对比全部系列",
    weightsLabel: "列表重量数量",
    headLabel: "拍面",
  },
  precision: {
    title: "精度与硬度",
    switch: { label: "选择精度等级", panelLabel: "四项受控参数 —", qcLabel: "质检架构", protocolNote: "依据既定工厂质检测量规程", fullTable: "完整对比表" },
    lead: "四项参数作为一个工程系统统一控制。每个等级定义了成品球拍与其声明规格的一致程度，以及所生成的质量记录。",
    statement: "重量。平衡点。挥重。硬度。作为一个工程系统统一控制。",
    classes: {
      "P2.5": { name: "可规模化的性能核心", qc: "逐支测量并留存生产记录。" },
      "P1.5": { name: "高级精度", qc: "逐支测量、逐支记录与可追溯性。" },
      "P0.5": { name: "专业级·逐支控制", qc: "逐支控制，包括标称值与实际值以及逐支测量记录；在该订单的计划予以实施的情况下，提供序列号标识、批次可追溯、精度证书与配对套装。" },
    },
    columns: { cls: "等级", weight: "重量", balance: "平衡点", sw: "挥重", stiff: "硬度", qc: "质检架构" },
    stiffTarget: "目标公差",
    stiffExact: "在既定的工厂测量规程下符合声明的RA目标值",
    programmeNote: "序列号标识、证书与配对套装文件，仅在特定订单的计划予以实施时签发。",
    targetsNote: "在相关规程和生产证据支持更明确的主张之前，硬度规格均为制造目标值。架构主张并不意味着每一款列出的配置都已通过完整的四参数放行流程。",
    stiffnessTitle: "硬度为何重要",
    stiffnessP1: "拍框硬度影响拍框在触球时的响应、手感，以及两支球拍之间的一致性。控制硬度的核心价值在于针对声明规格的可重复响应。",
    stiffnessP2: "在发布经验证的符合性之前，内部质检记录会标明仪器、其校准状态、方法、球拍状态、分辨率、测量不确定度、重复测量、舍入规则与判定规则。显示的整数相同并不能证明物理差异为零或测量误差为零。",
    fields: ["目标值", "测量结果", "允许公差", "仪器能力"],
    fieldsNote: "在每条记录中作为独立字段保存。",
    matchedTitle: "配对套装",
    matchedP: "配对套装的标准与单支公差分别定义。每支球拍符合其标称公差，本身并不能证明两支球拍之间的差异不超过某一特定最大值。配对拍、三支配对套装与团队套装通过配置器申请，并以书面形式确认。",
    extendedTitle: "扩展技术模型",
    extendedP: "数据模型支持更多参数。这些参数目前尚无数值或公差等级；可在技术需求书中作为申请目标值提出。",
    extended: { twistweight: "扭重", torsionalBehaviour: "扭转特性", length: "长度", beamProfile: "拍框截面", headGeometry: "拍头几何结构", stringPattern: "穿线模式", durability: "耐用性", vibration: "振动特性" },
    noZero: "MAXIMUS不将其产品线描述为零公差。精度以等级形式表述，附有声明公差和既定的质检架构。",
    cta: "按精度等级配置",
  },
  grip: {
    title: "出厂握柄架构",
    statement: "八种出厂握柄尺寸。L0–L7。",
    lead: "握柄几何结构是碳素拍柄架构的一部分。每种尺寸都作为拍柄几何结构制造，而非通过缠绕吸汗带加粗。",
    emph: "扩展尺寸",
    p1: "八种尺寸的出厂范围为教练和球员提供了更宽的配置范围，使装备可以围绕球员来指定规格，包括较大的L6与L7几何结构。",
    p2: "标称握柄代号不同于拍柄结构的原始尺寸，也不同于最终测量规程。这些尺寸适用于本平台上的性能系列与训练系列。",
    p3: "不对该尺寸范围作任何全球独有性的声明。",
    columns: { size: "尺寸", nominal: "标称尺寸", family: "适用于" },
    families: "GREAT · POWER · SPIN · Sweet Spot Trainer · Spot Trainer",
    cta: "按您的握柄尺寸配置",
  },
  custom: {
    title: "定制工程",
    statement: "按规格设计制造。",
    sub: "标准产品线只是起点。",
    lead: "MAXIMUS接受超出已发布配置矩阵的技术要求，进行评估、工程设计、验证，并按约定规格制造。可行性通过审核确认——并非每一项设想的要求在物理上或商业上都可行。",
    scopeTitle: "技术需求书可涉及的内容",
    scope: ["拍头与拍框几何结构", "长度", "重量", "平衡点", "挥重", "硬度", "扭重", "握柄几何结构", "构造", "配对套装", "训练拍框", "外观与刻字", "身份与团队计划", "依赖模具的开发"],
    processTitle: "流程",
    process: [
      ["定义", "期望目标值、强制限制、预期用途与可接受的取舍。"],
      ["工程设计", "基于平台与模具进行工程评估。"],
      ["验证", "按约定规格进行验证。"],
      ["规格确定", "一份包含测量基准与公差的书面规格。"],
      ["生产", "按规格生产。"],
      ["测量/记录", "按适用精度等级进行测量并留存记录。"],
    ],
    formTitle: "提交技术需求书",
    formLead: "请区分期望目标值与强制限制。结果是一份技术审核申请，而非自动接受的制造订单。",
    protected: "铺层方案、模具、供应商身份、内部成本核算与受保护的专有技术不通过此路径披露。",
    cta: "提交技术需求书",
  },
  training: {
    title: "训练系统",
    lead: "两个训练系列各有自己的生产标准，由同一方法论连接：教练主导的练习、记录、重新评估，以及向实战击球的转化。",
    sst: { h: "Sweet Spot Trainer（甜区训练拍）", p: "一款50 in²缩小拍面的训练球拍，采用四重量系统，用于中心击球练习、甜区感知、球拍控制与渐进式负荷。" },
    spot: { h: "Spot Trainer（击球点训练拍）", p: "使用小型圆形击球目标区进行击球点训练，基于经批准的四重量基础。" },
    method: { h: "方法论", p: "确立目标，在教练参与下选择装备，使用相应系统，记录，重新评估，调整并转化。" },
    experience: "握持。挥动。感受。",
    experienceP: "申请测试、试打与适配或教练协助的演示。已提交的申请并非已确认的预约。",
    cta: "申请试打与适配或演示",
    distinct: "Sweet Spot Trainer、Spot Trainer以及任何单独的演示器材都是不同的产品，绝不合并。",
  },
  sst: {
    title: "Sweet Spot Trainer（甜区训练拍）",
    lead: "一个独立的训练类别，拥有自己的生产标准。50 in²的拍面将注意力集中在触球位置；四种重量提供负荷递进。",
    baseline: "已确认的基准",
    columns: { head: "拍面", length: "长度", pattern: "穿线模式", grips: "出厂握柄" },
    systemTitle: "四支球拍系统",
    systemLead: "重量与平衡点为供货状态下的数值。测量基准另行记录，尚未发布。",
    purposeTitle: "用途",
    purpose: ["中心击球练习", "甜区感知", "球拍控制", "渐进式负荷", "教练主导的发展", "过渡回球员的实战球拍"],
    heavy: "400 g型号是一种受控的训练配置。它不会自动推荐给儿童、初学者或每一位球员；负荷、时长与递进由教练确定。",
    precisionNote: "性能精度等级P2.5、P1.5与P0.5不会自动适用于该训练系列。训练产品的生产公差遵循该系列自身经批准的规格。",
    health: "不承诺预防或治疗网球肘、消除损伤或保证取得进步。",
    cta: "申请Sweet Spot Trainer演示",
  },
  spot: {
    title: "Spot Trainer（击球点训练拍）",
    lead: "使用小型圆形击球目标区进行击球点训练。一款拥有独立视觉识别的独立产品，基于经批准的四重量基础构建。",
    purposeTitle: "已确认的用途",
    purposeP: "训练球员找到并重复精准的击球点。",
    weightsTitle: "重量递进",
    weightsP: "重量递进遵循经批准的Sweet Spot Trainer重量基础。平衡点数值及其他Sweet Spot Trainer规格不会照搬到Spot Trainer上。",
    dims: "目标区的精确尺寸尚未发布。",
    grips: "出厂握柄架构L0–L7。",
    notes: ["性能精度等级不会自动适用。", "它不是缩小版的常规球拍，也未发布穿线模式。", "Spot Trainer、Sweet Spot Trainer以及任何单独的演示器材始终保持可区分。"],
    cta: "咨询Spot Trainer",
  },
  methodology: {
    title: "方法论与产品体验",
    lead: "装备只是结构化发展历程的一部分。该方法从球员的目标出发，而非从产品标签出发。",
    stepsTitle: "发展历程",
    steps: [
      ["确立目标", "球员的目标与起点。"],
      ["选择装备", "在教练参与下选择合适的装备。"],
      ["使用系统", "由教练主导使用相应的训练系统。"],
      ["记录", "对实际参与情况的观察，不编造分数。"],
      ["重新评估", "可比较的检查点。"],
      ["调整", "配置或计划的调整。"],
      ["转化", "将所学转化回实战击球。"],
    ],
    educationTitle: "教育路径",
    education: { player: "球员——理解配置、负荷与递进。", parent: "家长——发展的连续性、合适的装备、记录与权利。", coach: "教练——训练系统、试打与适配、评估与授权计划的使用。" },
    evidenceTitle: "证据规范",
    evidenceP: "实际参与与观察的记录连同其分类一并保存——参与者自述、监护人确认、教练验证或系统测量。进步、分数与验证绝不编造。",
    experienceTitle: "握持。挥动。感受。",
    experienceP: "可申请测试、试打与适配或教练协助的演示。已提交的申请并非已确认的预约。",
    cta: "申请试打与适配或演示",
    cta2: "教练合作咨询",
  },
  gps: {
    metaTitle: "MAXIMUS GPS——装备引导档案",
    title: "MAXIMUS GPS",
    lead: "一份引导式的装备档案。只需回答相关问题；检查并修正您的答案；获得一份摘要、适用的配置方向以及切实的下一步行动。",
    honesty: "本版本尚未批准任何自动化适配规则。因此GPS生成清晰的需求摘要并指出配置方向；具体装备事项将转交专家审核。",
    rulesVersion: "规则版本",
    dataVersion: "产品数据版本",
    steps: { role: "角色", sport: "运动项目", experience: "经验水平", objectives: "目标", style: "打法风格", equipment: "现有装备", preference: "偏好", coach: "教练参与", ageBand: "年龄段", review: "检查" },
    notStored: "不会保存在本浏览器中。",
    ageNote: "仅用于转交申请。不会要求提供姓名、出生日期或医疗信息。",
    q: {
      role: "以下哪项描述符合您？",
      sport: "哪项运动？",
      experience: "经验水平",
      objectives: "最重要的是什么？（最多选择三项）",
      style: "打法风格（如已知）",
      equipment: "现有装备（如有）",
      equipmentHint: "如已知，请填写品牌与型号、重量或握柄尺寸。可选。",
      preference: "偏好的配置或已知的握柄尺寸",
      grip: "已知的握柄尺寸",
      coach: "您的装备决策是否有教练参与？",
      ageBand: "球员年龄段（仅用于恰当地转交申请）",
    },
    roles: { player: "球员", parent: "家长或监护人", coach: "教练", club: "俱乐部或学院", other: "其他" },
    sports: { tennis: "网球", padel: "板式网球", pickleball: "匹克球", squash: "壁球", badminton: "羽毛球", other: "其他球拍运动" },
    sportNote: "现有产品面向网球。其他运动为发展方向；您的兴趣将记录至相关计划。",
    experience: { beginner: "初学者", developing: "进阶中", intermediate: "中级", advanced: "高级", competitive: "竞技级", professional: "职业级" },
    objectives: { control: "控制", power: "力量", spin: "旋转", comfort: "舒适性", manoeuvrability: "灵活性", development: "长期发展", competition: "比赛", training: "训练系统", team: "团队或配对套装", personal: "个性化" },
    styles: { baseline: "底线型", allcourt: "全场型", attacking: "进攻型", defensive: "防守型", coach: "由教练选定", unknown: "不确定" },
    ageBands: { u10: "10岁以下", u14: "10–13岁", u18: "14–17岁", adult: "18岁及以上" },
    output: {
      title: "您的装备档案",
      status: "需要专家审核",
      statusP: "本版本不生成自动匹配结果。您的档案已汇总，供专家审核。",
      directionsTitle: "适用的配置方向",
      directionsP: "基于您所述的目标以及各系列声明的打法方向。这是一个方向，而非试打与适配建议。",
      trainingHint: "您的目标包含训练系统：请参阅Sweet Spot Trainer与Spot Trainer。",
      teamHint: "配对套装通过配置器申请，并以书面形式确认。",
      next1: "将档案发送给专家审核",
      show: "查看我的档案",
      configure: "配置",
      sendP: "将您的档案发送给MAXIMUS进行专家审核。申请编号会立即显示；答复将以书面形式发出。",
      otherSport: "MAXIMUS球拍面向网球。对于其他球拍运动，不推荐任何网球系列；您的兴趣将作为发展方向记录。",
      noDirection: "您的目标未指向单一打法方向。专家审核将提出配置建议。",
      incomplete: "部分必填答案缺失——请使用“修改答案”补全。",
    },
    privacy: "GPS不询问任何健康信息，也不询问任何儿童身份标识。仅选择题答案保存在本浏览器会话中；自由填写的文本不会被保存。",
  },
  build: {
    title: "定制您的球拍",
    lead: "配置一份申请：系列、精度等级、列表重量或自定义目标值、握柄尺寸、申请目标值、个性化、配对套装与数量。结果是一份带有申请编号的配置申请——不是SKU、价格、交付日期或证书。",
    steps: { series: "系列", cls: "精度等级", weight: "重量", grip: "握柄", targets: "目标值", personal: "个性化", set: "套装与数量", use: "用途", review: "检查" },
    q: {
      series: "选择系列",
      cls: "选择精度等级",
      weightMode: "重量",
      listed: "列表重量",
      customWeight: "申请的重量（g）",
      balanceShown: "该重量对应的计算平衡点",
      balanceRequest: "申请的平衡点（mm）",
      grip: "出厂握柄尺寸",
      targetsTitle: "申请目标值",
      swingweight: "申请的挥重（kg·cm²）",
      stiffness: "申请的硬度（RA）",
      basis: "申请数值的测量基准",
      engraving: "刻字文本",
      engravingHint: "姓名、姓名首字母或编号。拉丁字母、数字、空格、连字符、撇号和句点；最多24个字符。其他文字也可接受，需经图样确认。",
      engravingType: "个性化",
      types: { none: "无", name: "球员姓名", initials: "姓名首字母", number: "套装编号", academy: "教练或学院标识", team: "团队计划" },
      set: "单支球拍或配对套装",
      use: "预期用途",
      uses: { play: "个人打球", competition: "比赛", coaching: "教学", team: "团队或学院", retail: "零售或分销评估", other: "其他" },
      notes: "其他技术要求",
    },
    classes: { "P2.5": "P2.5——可规模化的性能核心", "P1.5": "P1.5——高级精度", "P0.5": "P0.5——专业级，逐支控制" },
    stiffExactShort: "硬度在既定的工厂规程下符合声明的RA目标值",
    clsNote: "每个等级都控制四项参数。P0.5是在既定测量规程下的严格公差——并非零误差。序列号标识、证书与配对套装文件，仅在您订单的计划予以实施时适用。",
    listedNote: "选自该系列已确认的矩阵。",
    customNote: "矩阵以外的重量，需经技术审核。",
    balanceCaption: "每个列表重量均显示其计算平衡点（自拍柄末端起算，单位mm）。计算值并非逐支测量值。",
    spinNote: "SPIN的重量构成申请的重量架构。SPIN的平衡点、挥重与硬度未提供；它们在技术审核中确定。",
    customHint: "以整克计，仅限数字。自定义重量是一项技术审核申请；可行性以书面形式确认，任何数值均不作舍入。",
    gripNote: "出厂碳素拍柄几何结构，而非通过缠绕吸汗带加粗",
    targetsLead: "可选。仅填写您需要的数值。每项数值均作为申请目标值记录，供技术审核，而非作为已发布的规格。",
    basisHint: "申请自定义重量或任何目标值时必填：这些数值是指未穿线球拍还是已穿线球拍？",
    inputRange: "可接受的输入：{min}–{max}。",
    inputRangeNote: "输入范围仅用于排除不可能的输入，并不描述生产能力。",
    listedBasis: "列表数值——测量基准在书面规格中确认",
    notStored: "不会保存在本浏览器中；如重新加载页面，请重新输入。",
    artworkReview: "需进行图样确认",
    previewNote: "不显示视觉预览：该型号经批准的刻字模板尚未发布。您的文本将被收集，用于图样确认。",
    teamSub: "每套4–99支球拍",
    setsLabel: { individual: "球拍数量（支）", pair: "配对拍数量（对）", triple: "三支配对套装数量（套）", team: "团队套装数量（套）" },
    teamSizeLabel: "每套团队套装的球拍数",
    totalLabel: "球拍总数",
    racquetsUnit: "支球拍",
    setRule: "数量按套计算：配对拍每套2支球拍，三支配对套装每套3支。",
    restart: "开始新的配置",
    notices: { weightCleared: "{w} g不在{series}矩阵中，因此已清除该重量。请选择列表重量或申请自定义目标值。" },
    reviewTitle: "配置申请",
    reviewP: "请检查配置，然后填写您的联系方式。申请将连同申请编号一并保存，并以书面形式答复；供货情况与商业条款以书面形式确认。",
    reviewErrors: "部分配置答案需要处理：",
    edit: "修改",
    fieldNames: { series: "系列", cls: "精度等级", mode: "重量选择方式", weight: "列表重量", customWeight: "申请的重量", basis: "测量基准", balanceReq: "申请的平衡点", sw: "申请的挥重", ra: "申请的硬度", grip: "握柄尺寸", ptype: "个性化", engraving: "刻字文本", setType: "套装类型", sets: "数量", teamSize: "每套团队套装的球拍数", use: "预期用途", notes: "其他要求" },
    status: { listed: "列表重量", requestedArchitecture: "申请的重量架构", technicalReview: "技术审核申请", notPublished: "未提供", requestedCondition: "申请的球拍状态" },
    chooseLink: "不确定哪个系列适合您？获取选择帮助",
    cta: "提交配置申请",
  },
  experience: {
    title: "体验、试打与适配",
    statement: "握持。挥动。感受。",
    lead: "申请测试、试打与适配或教练协助的演示。申请经审核后以书面形式答复；已提交的申请并非已确认的预约。",
    optionsTitle: "可申请的内容",
    options: ["球拍测试", "试打与适配环节", "教练协助的演示", "Sweet Spot Trainer或Spot Trainer演示", "团队或学院演示日"],
    formTitle: "试打与适配或演示申请",
  },
  engineering: {
    title: "工程与制造",
    statement: "飞机。游艇。球拍。",
    lead: "同一工程理念贯穿三种环境：塑造飞机的原则、引导游艇穿越开阔水域的精度、定义每一支MAXIMUS球拍的性能。这是一种工程叙事——并非对航空器认证、游艇所有权、工厂所有权或材料直接转用的声明。",
    manifesto: ["我们相信，卓越的工程没有边界。", "一个理念。绝不妥协的工程。"],
    capabilityTitle: "制造能力",
    capabilityLead: "能力以流程呈现，而非口号。",
    sequence: [
      ["规格", "系列、精度等级、重量、平衡点、挥重、硬度目标值、握柄几何结构、个性化。"],
      ["生产", "从拍框到拍柄的全碳素构造，按规格生产。"],
      ["质量控制", "按精度等级进行测量并记录：生产记录、逐支记录与可追溯性、逐支认证。"],
      ["重复生产", "跨批次针对声明规格的可重复响应。"],
      ["可追溯性", "序列号标识、批次可追溯，以及（在等级提供的情况下）精度证书。"],
    ],
    capacityNote: "生产能力、交付周期、最低数量与交付计划按计划以书面形式确认，以已确认的订单和约定的放行计划为依据。",
    truth: "产能不等于产量、库存、保证的交付日期或对制造设施的所有权。",
    cta: "分销与国家市场开发",
    cta2: "提交技术需求书",
  },
  ecosystem: {
    title: "MAXIMUS生态系统",
    lead: "一把钥匙。它能开启这些。每个节点都有说明、准确的状态与相关的下一步行动。",
    words: ["工程", "性能", "创新", "社区", "机遇", "使命"],
    nodes: {
      engineering: { h: "球拍工程与制造", p: "按规格设计制造的全碳素球拍，生产过程附有质量记录与可追溯性。", a: "工程与制造" },
      precision: { h: "精度与个人配置", p: "四项参数、三个精度等级、八种握柄尺寸与定制工程。", a: "精度与硬度" },
      training: { h: "训练与方法论", p: "Sweet Spot Trainer、Spot Trainer与结构化的发展历程。", a: "训练系统" },
      development: { h: "球员与教练发展", p: "教练主导的选择、记录、重新评估与教育路径。", a: "方法论" },
      identity: { h: "个人身份与个人品牌", p: "从刻字到受权利规则约束的个人或职业品牌。", a: "个人品牌" },
      owners: { h: "所有者记录、知识与权利", p: "一个拟议中的许可制所有者档案库，用于装备、发展与权利记录。", a: "所有者与档案库" },
      mipa: { h: "MIPA来源溯源与内部控制", p: "内部知识产权、来源溯源与文件控制层。", a: "法律主体与控制" },
      digital: { h: "数字基础设施与Blockchain 5.0方向", p: "来源溯源、可追溯记录、许可制证据与产品标识，作为既定的技术方向。", a: "技术方向" },
      licensing: { h: "合同许可与特许权使用费计划", p: "被许可的品牌、产品与权利组合，条款按各协议定义。", a: "许可路径" },
      families: { h: "家庭参与与计划权益", p: "知情决策、连续性、记录保存与由计划定义的权益。", a: "家庭与家长" },
      network: { h: "MAXIMUS Sports Network", p: "球员、教练、俱乐部、学院、服务提供方、运营方与区域合作伙伴。", a: "Sports Network" },
      market: { h: "俱乐部、学院、分销与国家市场开发", p: "团队计划、零售、分销与区域市场开发，均经书面资格审核。", a: "合作路径" },
      institutional: { h: "机构计划、教育、创新与社会影响", p: "由MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC)提供的机构层，仅在某一计划确立该角色时适用。", a: "机构计划" },
      extensions: { h: "未来的球拍运动与MAXIMUS服饰延伸", p: "板式网球、匹克球、壁球、羽毛球、短柄壁球、沙滩网球与服饰，作为发展方向。", a: "球拍运动" },
    },
    boundaryTitle: "边界",
    boundary: [
      "购买球拍不产生机构会员资格、治理权利、特许权使用费或投资权利。",
      "MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC)仅在某一计划确立该角色时担任机构运营方；装备销售以其实际签约主体为准。",
      "资助、慈善地位、税务处理与监管许可不会自动适用于各个国家。",
    ],
    techTitle: "技术方向",
    techP: "Blockchain 5.0是MAXIMUS既定的技术方向。其功能目的为来源溯源、可追溯记录、许可制证据、产品标识以及符合条件的商业事件的对账。不表述任何共识机制、交易容量、节点网络、智能合约地址、代币或独立认证，也不声称存在已部署的实现。个人信息、儿童记录与保密协议默认绝不放入公开的不可篡改系统。",
  },
  brands: {
    title: "个人品牌与品牌大使",
    statement: "从球员到品牌。从教练到品牌。",
    lead: "一条专门的个人品牌路径。MAXIMUS的参与包括品牌发展与约定的推广——而不仅仅是球拍上的一个名字。",
    progressionTitle: "预期的进阶路径",
    progression: [
      ["经验证的身份", "经验证的身份与发展历史。"],
      ["具有辨识度的品牌", "一个具有辨识度的个人或职业品牌。"],
      ["完成权利清理的内容", "完成权利清理的内容与经批准的产品标识。"],
      ["工程与系列产品", "经约定的工程与系列产品开发。"],
      ["推广", "通过约定的MAXIMUS渠道与合作伙伴进行推广。"],
      ["参与", "按合同参与符合条件的销售或许可。"],
      ["报告", "按协议进行透明报告。"],
    ],
    royaltiesTitle: "特许权使用费与许可",
    royalties: [
      "特许权使用费附着于所定义的被许可品牌、产品、交易或权利组合。",
      "“全球销售”指合同范围内符合条件的销售——绝不包括所有无关的MAXIMUS球拍。",
      "费率、计算基础、区域、期限、退款、扣减、报告、结算与核验均通过相关协议定义。不发布任何默认的特许权使用费比例。",
      "在没有约定范围的情况下，不承诺任何全球推广活动、媒体预算、赞助成果或商业成功。",
    ],
    cta: "提交品牌合作咨询",
    cta2: "教练合作咨询",
  },
  families: {
    title: "家庭与家长",
    lead: "知情的装备决策、发展的连续性、知识与权利的保存、参与情况的可见性，以及由计划定义、可能为未来活动提供支持的权益。",
    nowTitle: "现已提供",
    now: ["以书面形式提出的家庭与发展咨询。", "教练参与的装备选择、试打与适配及演示申请。", "私密记录：儿童档案默认绝不公开，也绝不商业化。", "面向家长的教育路径：配置、负荷、递进、记录与权利。"],
    plannedTitle: "规划中",
    planned: ["由计划定义的参与权益，可用于生态系统内的商品与服务，而非现金利息。", "所有者与家庭记录存于拟议中的所有者档案库，设有监护人权限，并在年满18岁时转移控制权。"],
    categoriesTitle: "分别处理",
    categories: ["因被许可权利或符合条件的销售而产生的合同特许权使用费", "由计划定义的参与权益", "购买或服务抵扣额度", "预付款", "机构会员资格"],
    categoriesP: "这些类别绝不视为可以互换。",
    statusTitle: "家庭计划的实际状态",
    journeyTitle: "家庭路径",
    journey: [
      ["目标", "球员下一步希望达成的目标。"],
      ["当前水平", "球员目前所处的水平。"],
      ["教练", "是否有教练参与装备决策。"],
      ["装备", "适合当前阶段的装备，在相关情况下包括训练系统。"],
      ["约定的练习", "事先约定、由教练主导的使用。"],
      ["回顾", "在可比较的检查点重新评估。"],
    ],
    brief: {
      who: "各阶段球员的家长与监护人。",
      value: "关于合适装备、教练参与及下一步发展的书面答复。",
      now: "以书面形式提出的家庭咨询；教练参与的装备选择；私密记录——儿童档案绝不公开。",
      next: "请提交下方的家庭咨询。您将立即获得申请编号。",
    },
    formTitle: "家庭咨询",
    formNote: "请由家长或监护人填写。请勿填写儿童的姓名、出生日期、学校或医疗信息。",
    noPromise: "购买并不承诺特许权使用费、投资回报、赞助或对儿童发展的资助。",
    statusP: "本版本说明该模式并接受计划咨询。在符合条件的事件、受益人、资金来源、计算基础、允许用途、会计处理、退款、冲销、到期、可转让性、计划终止与争议处理以书面形式定义之前，累计、支付与兑换均不可用。不承诺任何余额永不减少，任何参与权益都不足以支付全部训练费用，也不暗示任何资本保护。",
    cta: "提交家庭或发展咨询",
  },
  owners: {
    title: "所有者与所有者档案库",
    lead: "所有者档案库是一个拟议中的许可制记录，涵盖装备、发展、知识、内容与有据可查的权利。它作为规划中的所有者架构的一部分呈现：不显示任何真实账户、余额、证书或成就。",
    nowTitle: "面向现有所有者，现已提供",
    now: ["所有者咨询：以书面形式提出的产品或序列号、设置、服务与记录申请。", "在精度等级提供的情况下，精度证书与配对套装文件随产品交付。"],
    archTitle: "规划中的档案库架构",
    arch: ["产品标识与序列号", "配置与适用的质检证书", "服务与设置历史", "球员或教练发展记录", "资质与经验证的成就", "完成权利清理的媒体素材与创作材料", "许可、授权与合同参照", "个人品牌计划记录", "适用的特许权使用费报表或参与权益"],
    separationTitle: "所有权的含义",
    separation: [
      "对实体球拍的所有权，不同于对版权、许可、合同权益或描述这些事项的记录的所有权。",
      "存储的文件或区块链条目并不自动证明某项法律权利存在或已转移。",
      "证据保留其分类：参与者自述、监护人确认、教练验证、系统测量。",
      "对于未成年人：私密记录、监护人权限、不公开儿童档案，且默认不对身份进行商业化。",
      "导出、更正、访问控制以及恰当的控制权转移均属于设计的一部分。",
    ],
    techTitle: "Blockchain 5.0与MxSN",
    techP: "Blockchain 5.0是既定的技术方向；MxSN定义了一个用于同意、交付、证据、权利与报告的许可制网络的概念。不表述任何运营层面的实现。应用数据模型的构建旨在日后通过有文档记录的接口进行集成，而不假装当前已存在连接。",
    cta: "所有者咨询",
  },
  network: {
    title: "MAXIMUS Sports Network",
    lead: "球员、教练、俱乐部、学院、服务提供方、计划运营方与区域合作伙伴之间的连接。",
    functionsTitle: "潜在功能",
    functions: ["发现", "引荐", "发展计划", "装备支持", "活动", "服务获取", "合作机会"],
    statusTitle: "实际状态",
    statusP: "目前尚未发布任何公开名录：只有身份、关系与出现许可均已确立的参与者才会被列出。发送给俱乐部的提案并不构成合作关系，潜在经销商也并非已获委任的经销商。名录发布、预约、消息与商业交易分别受控，且尚未上线。",
    cta: "申请加入网络",
  },
  partnerships: {
    title: "合作路径",
    lead: "先进行书面资格审核。每条路径都通向针对特定角色的咨询；商业条款随后以书面形式确定。",
    commercialTitle: "平台的潜在商业活动",
    commercial: ["装备", "定制工程", "个性化", "团队与学院计划", "训练系统", "合同许可", "分销", "经批准的服务", "未来的产品类别"],
    boundary: "国家市场权利、独家权、区域费用与经销商利润率均为协商条款。不发布任何收入、预测、估值、市场份额、回报、资金承诺或未具名的合作关系。",
    routes: {
      coaches: {
        title: "教练",
        lead: "训练系统、试打与适配、职业身份、授权计划、个人品牌机会与装备供应。",
        points: ["在教练主导的练习中使用Sweet Spot Trainer与Spot Trainer。", "借助配置矩阵与八种出厂握柄尺寸进行试打与适配。", "Coach-to-Brand：经验证的职业档案与受权利规则约束的子品牌。", "授权计划的使用以书面协议为准。"],
        cta: "提交教练合作咨询",
        brief: {
          who: "独立教练与教练团队。",
          value: "用于教练主导练习的训练系统，借助系列矩阵与八种出厂握柄进行的试打与适配，以及通往职业身份的路径。",
          now: "以书面形式提出的教练咨询。不发布也不暗示任何佣金、收入或推荐费率。",
          next: "请提交下方的教练咨询。条款随后以书面形式确定。",
        },
        purpose: "coach",
      },
      clubs: {
        title: "俱乐部与学院",
        lead: "团队装备、训练系统、个性化、发展计划、服务与网络参与。",
        points: ["通过配置器申请团队套装与配对套装。", "用于结构化发展的训练系统与方法论。", "在经批准的区域为团队计划进行个性化。", "演示日、试打与适配环节以及网络参与。"],
        cta: "提交俱乐部或学院需求书",
        brief: {
          who: "俱乐部、学院与团队计划。",
          value: "团队套装与配对套装、训练系统、团队计划的个性化以及演示日。",
          now: "以书面形式提交的俱乐部与学院需求书；团队套装通过配置器申请。",
          next: "请提交下方的俱乐部或学院需求书。",
        },
        purpose: "club",
      },
      distribution: {
        title: "分销与国家市场开发",
        lead: "产品组合、制造协调、技术能力、区域市场开发与保密的商业资格审核。",
        points: ["对交易对方、区域与渠道进行书面资格审核。", "产品组合根据配置矩阵与精度等级确定。", "区域、独家权、采购量、定价与商业保护均为以书面形式约定的协商条款。", "签约主体、付款条款与交付条件按每笔交易确定。"],
        cta: "提交分销或国家市场开发咨询",
        brief: {
          who: "零售商、经销商与国家合作伙伴。",
          value: "根据已确认的矩阵、精度等级与握柄尺寸范围确定的产品组合，并对区域与渠道进行书面资格审核。",
          now: "以书面形式提出的分销咨询。区域、独家权、采购量与定价均为协商事项——任何一项都不通过表单授予。",
          next: "请提交下方的分销咨询。",
        },
        purpose: "distribution",
      },
      strategic: {
        title: "战略与投资",
        lead: "工程能力、配置深度、制造模式、市场路径、知识产权、服务与扩展机会。",
        points: ["经资格审核的战略讨论或受控信息访问，以书面资格审核为前提。", "公开信息仅限于经批准的产品规格、配置架构、经验证的能力与计划说明。", "针对特定买方的经济条款、成本核算、受保护的方法与未发布的协议，仅在保密协议（NDA）或合同下披露。"],
        cta: "申请经资格审核的战略讨论",
        brief: {
          who: "投资者与战略合作伙伴。",
          value: "经资格审核的讨论，涉及工程能力、配置深度、制造模式、市场路径与知识产权。",
          now: "不发布任何财务数据、预测、估值或回报。受控信息以书面资格审核与保密协议（NDA）为前提。",
          next: "请在下方申请经资格审核的战略讨论。",
        },
        purpose: "strategic",
      },
      institutional: {
        title: "机构计划",
        lead: "教育、可及性、创新、发展证据、社会影响以及结构恰当的计划。",
        points: ["机构计划通过MAXIMUS INVESTMENT BUSINESS CLUB NPIO (DIFC)组织，仅在该计划确立该角色时适用。", "限定用途的计划资金与商业交易保持区分。", "咨询并不等于已接受的会员申请，装备购买者也并非机构会员。", "资助、慈善地位、税务处理与监管许可因国家而异，绝不作默认假设。"],
        cta: "提交机构计划咨询",
        brief: {
          who: "机构、教育与发展计划。",
          value: "面向教育、可及性、创新与发展证据的计划，通过相应的运营方组织。",
          now: "以书面形式提出的机构咨询。咨询并非会员申请；购买装备并不构成机构会员资格。",
          next: "请提交下方的机构咨询。",
        },
        purpose: "institutional",
      },
    },
    disclosureTitle: "公开披露与受控披露",
    disclosure: {
      public: { h: "公开", p: "经批准的产品规格、构造、配置架构、训练用途、经验证的能力、计划说明与合作路径。" },
      qualified: { h: "经资格审核的咨询", p: "技术要求、数量、区域意向、开发范围与相关商业讨论。" },
      controlled: { h: "受保密协议或合同控制", p: "内部公式、详细质检规程、铺层方案、模具、制造方法、供应商身份、成本核算、针对特定买方的经济条款、受保护的方法、未发布的协议与敏感的权利记录。" },
    },
  },
  contact: {
    title: "联系与申请",
    lead: "请选择您申请的目的。每份表单仅收集转交和评估所需的信息。申请以书面形式答复。",
    email: "电子邮箱",
    instagram: "Instagram",
    legalLink: "法律主体",
  },
  form: {
    purposeLabel: "申请目的",
    purposes: {
      selection: "球拍选择帮助",
      product: "产品咨询",
      fitting: "试打与适配或演示",
      technical: "技术需求书",
      config: "配置申请",
      gps: "GPS装备档案",
      coach: "教练合作",
      club: "俱乐部或学院需求书",
      distribution: "分销或国家市场开发",
      brand: "品牌合作或品牌大使",
      family: "家庭或发展咨询",
      institutional: "机构计划",
      strategic: "战略或投资讨论",
      owner: "所有者咨询",
      network: "申请加入Sports Network",
      general: "一般咨询",
    },
    fields: {
      name: "姓名",
      email: "电子邮箱",
      role: "您的角色",
      country: "国家或地区",
      organisation: "所属组织",
      message: "您的留言",
      level: "当前水平",
      objectives: "最看重的因素（最多三项）",
      currentRacquet: "目前使用的球拍",
      grip: "握柄尺寸（如已知）",
      seriesInterest: "感兴趣的系列",
      quantity: "数量",
      city: "试打或演示的城市或地点",
      coachInvolved: "是否有教练参与？",
      timing: "期望时间",
      targets: "期望目标值",
      limits: "强制限制",
      use: "预期用途",
      tradeoffs: "可接受的取舍",
      basis: "测量基准",
      players: "球员人数",
      interests: "感兴趣的领域",
      territory: "感兴趣的区域",
      channels: "现有渠道与经验",
      audience: "受众或专业领域",
      proposal: "拟议的合作",
      goal: "发展目标",
      ageBand: "球员年龄段",
      scope: "计划范围",
      interestArea: "感兴趣的领域",
      productRef: "产品或序列号",
      requestType: "申请类型",
      seeking: "您希望获得的内容",
      consent: "我同意MAXIMUS存储并使用这些信息以答复本申请。这并非营销订阅。",
    },
    roles: { player: "球员", parent: "家长或监护人", coach: "教练", club: "俱乐部或学院", retailer: "零售商", distributor: "经销商", brand: "品牌或品牌大使", investor: "投资者或战略合作伙伴", institution: "机构", other: "其他" },
    interestOptions: { training: "训练系统", fitting: "试打与适配", identity: "职业身份", programmes: "授权计划", brand: "个人品牌", supply: "装备供应", team: "团队装备", personalisation: "个性化", development: "发展计划", service: "服务", network: "网络参与" },
    ownerTypes: { setup: "设置与配置", service: "服务", records: "记录与证书", other: "其他" },
    strategicAreas: { engineering: "工程能力", configuration: "配置深度", manufacturing: "制造模式", routes: "市场路径", ip: "知识产权与服务", expansion: "扩展机会" },
    errors: {
      required: "此字段为必填项。",
      too_long: "输入内容过长。",
      too_short: "输入内容过短。",
      invalid_email: "请输入有效的电子邮箱地址，例如：name@example.com。",
      invalid_choice: "请从选项中选择一项。",
      not_number: "请输入整数，仅限使用数字。",
      out_of_range: "该数值超出可接受的范围。",
      not_in_matrix: "该重量不在所选系列的列表矩阵中。",
      decimal_not_supported: "请输入不带小数的整数。",
      too_many: "最多只能选择三项。",
      consent_required: "需要您的同意，MAXIMUS才能答复本申请。",
      invalid: "输入内容无效。",
    },
  },
  legal: {
    title: "法律主体与控制",
    lead: "公开品牌为MAXIMUS / MAXIMUS GPS。各法律运营主体相互区分，并在此列明。",
    entities: {
      institutional: { role: "机构计划层", p: "在某一计划确立该角色时提供机构计划层。并非球拍的商业销售方。一家在迪拜国际金融中心注册成立的非营利法人组织。" },
      equipment: { role: "装备商业主体", p: "在现行运营文件确立该角色的情况下，作为供应、分销与合同商业交付的装备商业主体。任何交易的签约方均在该交易的文件中列明。" },
      ip: { role: "知识产权、品牌与商业协调", p: "以既定的知识产权、品牌或商业协调角色出现。不指派任何未经确认的合同责任。" },
      stewardship: { role: "管护参照", p: "在相关来源支持的情况下，House of Maximus是该生态系统的管护参照。" },
      control: { role: "内部知识产权、来源溯源与文件控制", p: "MIPA是内部知识产权、来源溯源与文件控制层。MIPA内部记录不同于外部商标、专利、版权登记或司法认可，也不构成视觉批准。" },
    },
    labels: { licence: "执照", registration: "注册号", vat: "增值税税号（VAT TRN）", address: "地址", email: "电子邮箱", jurisdiction: "司法管辖区" },
    boundaryTitle: "边界",
    boundary: [
      "购买并不自动授予机构会员资格、治理权利、特许权使用费或投资权利。",
      "机构角色与商业装备交易相互独立。",
      "隐私、计划条款与受控访问安排与实际发布的功能相对应。",
      "不存在适用于每位访问者、每笔销售或每个境外计划的一概而论的管辖法律声明；合同依据按各协议确定。",
    ],
  },
  privacy: {
    title: "隐私",
    updated: "版本2026-09-21 · 网站4.2",
    contactTitle: "隐私问题联系方式",
    sections: {
      collect: ["收集的内容", "提交表单时，收集以下内容：您输入的信息，即姓名、电子邮箱、角色、国家或地区、所属组织（如已填写）、您的留言及表单中的答案；您访问时的页面与推广活动参数，即着陆页、语言与utm参数（广告点击标识符仅在您允许数据分析时收集）；以及提交时间。您的IP地址仅以经哈希处理、短期保留的形式用于限制滥用行为，不会与您的申请一同存储。"],
      purpose: ["收集目的", "用于答复您的申请、准备您所要求的方案或规格，以及保存该申请的记录。不会基于表单发送任何营销信息。"],
      storageOn: ["申请的存储位置", "申请存储于Upstash, Inc.的数据库（Redis）中，该数据库通过托管平台Vercel Inc.提供。新申请的通知通过电子邮件发送至MAXIMUS邮箱。"],
      storageOff: ["申请的存储位置", "申请存储功能正在设置中。在其启用之前，表单会提示无法接收申请；不会存储任何内容。本网站由Vercel Inc.托管。"],
      browser: ["浏览器存储", "在本次浏览器会话期间，浏览器的会话存储会保存GPS与配置器中的选择题答案以及您访问时的推广活动参数。联系方式、自由填写的文本、刻字文本以及有关儿童的信息不会存储在浏览器中。"],
      analyticsOn: ["数据分析", "经您同意后，Google Analytics 4会统计访问与表单事件，不包含联系方式或申请文本。您的选择保存在本地存储中，可随时通过页脚的“数据分析设置”更改。不启用数据分析时，表单同样可以正常使用。"],
      analyticsOff: ["数据分析", "本网站未启用任何数据分析工具。"],
      retention: ["保留期限", "目前尚未设置自动删除期限。您可以随时要求删除您的申请。"],
      children: ["儿童", "表单必须由成年人填写。涉及18岁以下球员的申请由家长或监护人提出。请勿提交儿童的姓名、出生日期、学校或医疗信息。儿童档案绝不公开。"],
      rights: ["您的权利", "如需查阅、更正或删除您的申请，请写信至gps@maximus.tennis，并注明您的申请编号。"],
      controlled: ["受控信息", "保密文件不存储于本网站，也不由本网站提供。受控披露在保密协议或合同下通过单独渠道进行。"],
    },
  },
  terms: {
    title: "使用条款",
    updated: "版本2026-09-21",
    sections: [
      ["信息，而非要约", "本网站的产品信息描述经批准的规格、配置架构与计划说明。它不是销售要约、价目表、库存声明或交付承诺。商业条款与每笔交易中列明的签约主体另行以书面形式约定。"],
      ["申请", "通过本网站提交的申请——包括GPS档案、配置申请与技术需求书——将连同申请编号一并保存并接受审核。它不是已接受的订单、制造承诺、已确认的预约、会员申请，也不是任何计划的已接受申请。"],
      ["规格与证据", "计算值、制造目标值与已确认规格在相关页面上加以区分。在另行发布之前，硬度值均为制造目标值。不保证任何特定球员获得任何结果。"],
      ["生态系统、会员资格与权利", "购买球拍不产生机构会员资格、投资权利、知识产权所有权、特许权使用费权益或参与权益。权益以已发布的计划条款或书面协议为准。"],
      ["知识产权", "MAXIMUS®、狮子徽标、GPS标识以及本网站的内容均受保护。内部工程公式、质检规程、铺层方案、模具、供应商身份、成本核算与受保护的方法不在此披露。"],
    ],
  },
  lead: {
    submit: "提交申请",
    submitting: "正在提交……",
    retry: "重试",
    acceptedEyebrow: "申请已接收",
    acceptedTitle: "您的申请已收到。",
    requestId: "申请编号",
    acceptedNext: "MAXIMUS会审核每份申请，并以书面形式答复至您提供的电子邮箱地址。请保留申请编号，以便后续跟进。",
    duplicate: "此申请此前已收到；未创建重复申请。",
    another: "发起新申请",
    errorsTitle: "请检查以下字段：",
    failTitle: "您的申请尚未提交。",
    fail: {
      offline: "您的设备处于离线状态。",
      network: "与服务器的连接失败。",
      timeout: "服务器未能及时响应。",
      rate_limited: "来自该网络的申请过多。请几分钟后再试。",
      too_fast: "表单提交速度过快。请检查后重新提交。",
      spam_suspected: "该申请已被垃圾信息过滤器拦截。",
      unavailable: "目前无法接收申请。",
      default: "发生了意外错误。",
    },
    keepNote: "您的输入仍保留在本页，您可以重试。",
    fallback: "如问题仍然存在，请发送邮件至{email}。只有在显示申请编号后，申请才算已提交。",
    privacyLink: "隐私声明",
    consentShort: "同意",
    hpLabel: "请将此字段留空",
    after: "提交后，本页将显示申请编号。申请经审核后以书面形式答复；申请并非订单。",
    basis: { unstrung: "未穿线", strung: "已穿线", unknown: "不确定——在规格中约定" },
    hints: {
      email: "MAXIMUS将以书面形式答复至此地址。",
      goal: "例如：首支比赛用拍，或从青少年球拍过渡。请勿填写儿童的姓名、出生日期或医疗信息。",
      currentRacquet: "品牌与型号（如已知）。",
      message: "请勿填写密码、支付信息或医疗信息。",
    },
  },
  choose: {
    eyebrow: "选择帮助",
    title: "帮我挑选球拍",
    lead: "请告诉MAXIMUS您的水平以及您最看重的因素。您的答案将经过审核，您将收到一份书面方案：系列、精度等级、重量与握柄。",
    stepsTitle: "接下来的流程",
    steps: [
      ["您的答案", "水平、侧重点，以及握柄尺寸（如已知）。"],
      ["专家审核", "MAXIMUS将您的答案与各系列矩阵进行比对。"],
      ["书面方案", "以书面形式提供的建议配置与下一步。"],
    ],
    formTitle: "您的答案",
    submit: "申请选择帮助",
    altTitle: "想自行决定？",
    altGps: "详细的GPS档案",
    altBuild: "直接配置",
    note: "不进行自动适配，也不作任何准确性声明：每份申请均由专人审核。",
  },
  consent: {
    title: "数据分析",
    text: "是否允许MAXIMUS使用Google Analytics统计访问情况？无论您如何选择，表单均可正常使用；联系方式与申请文本不会发送至数据分析工具。",
    allow: "允许数据分析",
    decline: "拒绝",
  },
  media: {
    powerFull: "MAXIMUS POWER球拍，未穿线拍框，哑光黑色",
    powerHandle: "MAXIMUS POWER拍喉至拍柄的过渡段",
    buttcap: "MAXIMUS拍柄底盖上的狮子徽标",
    lettering: "哑光黑色拍框上的亮面黑色MAXIMUS字样",
    greatHead: "MAXIMUS GREAT拍头与V形拍喉几何结构",
    finish: "MAXIMUS拍框，表面处理参考",
  },
  notFound: { title: "页面未找到", p: "您请求的页面在此语言版本中不存在。", cta: "返回首页" },
};

export default zh;
